### ISSUE TITLE
Install and execute tools within a Stack configured environment

### ISSUE THREAD

**Issue by cies** [commercialhaskell/stack#1001]
Currently there is an `ide` command in stack to execute `stack-ide` within the configured environment. Other tools also need this kind of integration, for instance `ghc-mod`.

Would it be possible to provide a generic way for tools to integrate within a stack configured environment? Otherwise every tool needs to be integrated into stack [the way stack-ide is](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Ide.hs). Or the tools --especially with they are GHC-specific-- can only reasonably installed for one stack environment.

The need for this was [expressed in a thread on reddit](https://www.reddit.com/r/haskell/comments/3l4zcp/ann_ghcmod5400_now_with_stack_support/cv3dg1g?context=3).

**Comment by snoyberg** [comment]
How is that different from `stack build ghc-mod && stack exec ghc-mod`? I already use an approach like that when testing out wai-devel.

**Comment by DanielG** [comment]
What happens when the user edits `stack.yaml` and changes the resolver from lts-3.1 to lts-2.1 or something like that? `ghc-mod` would have to be recompiled against the new version of ghc but I don't think `stack exec ghc-mod` would do that, right?

**Comment by snoyberg** [comment]
No, but `stack build ghc-mod && stack exec ghc-mod` would. Or even better: `stack build ghc-mod --exec ghc-mod`.

**Comment by DanielG** [comment]
That might be prohibitively slow for the one-shot version of ghc-mod though `stack build` takes quite a long time to start up last time I checked.

**Comment by snoyberg** [comment]
Then you can check if it exists first with `stack exec which ghc-mod`. I'm really uncertain right now what the goal of this issue is.

**Comment by DanielG** [comment]
Well if the behavior is how you say then that would probably satisfy our use case actually :)

**Comment by cies** [comment]
Sorry this led to confusion. I'll close this issue. I still wonder how I should setup ghc-mod on a stack-managed multi-GHC machine. But I'll have a look at this issues while keeping the above advises in mind.
