### ISSUE TITLE
Be more explicit about what `stack setup` does.

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1004]
Per this objection:

> If you look here Stack suggested to try run stack setup and I given the wording and how stack setup is named I didn't expect it to go downloading stuff (honestly, who expects a setup stage to imply downloading?).

```
Populated index cache.
GHC version mismatched, found 7.10.2 (x86_64), but expected version 7.8.4 (i386)
(based on resolver setting in ...\stack.yaml). Try running stack setup
```

Perhaps add, "Try running stack setup to download and install GHC 7.8.4 locally".

Not 100% on "locally", want to make it clear it won't be system-wide or break anything else.

**Comment by mgsloan** [comment]
Good point!

I've pushed a commit that makes it look like this:

> Compiler version mismatched, found ghc-7.10.2 (x86_64), but expected minor version match with ghc-7.8.4 (x86_64) (based on resolver setting in /home/mgsloan/fpco/stack-ide/stack-7.8.yaml).
> Try running "stack setup" to install the correct GHC into /home/mgsloan/.stack/programs/x86_64-linux/

**Comment by bitemyapp** [comment]
@mgsloan I'm satisfied, thank you very much :)
