### ISSUE TITLE
`stack install` does not install "data-files"

### ISSUE THREAD

**Issue by Peaker** [commercialhaskell/stack#1005]
The data dir (`build/autogen/Paths_<project>.hs`) is the project's `.stack-work/install`.

This means that after `stack install` the executable in the global/homedir's binary directory depends on files in `.stack-work`.

In practice, this means that cleaning up .stack-work or just doing "local" rebuilds breaks user-wide installs that were already done.

**Comment by sinelaw** [comment]
+1, sucks for projects with .so dependencies that are built by cabal/stack

**Comment by snoyberg** [comment]
This looks like it will be solved by #848.

**Comment by snoyberg** [comment]
Closing as duplicate
