### ISSUE TITLE
Error when running "stack install --test --coverage"?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1006]
Reported by Alfredo Di Napoli, in this [PR](https://github.com/commercialhaskell/stack/pull/1003).

```
Linking .stack-work/dist/x86_64-osx/Cabal-1.18.1.5/build/chronos-ctl/chronos-ctl ...
chronos-0.15.0.0: install
Installing executable(s) in
/Users/adinapoli/work/chronos/.stack-work/install/x86_64-osx/lts-2.16/7.8.4/bin
/Users/adinapoli/work/chronos/.stack-work/install/x86_64-osx/lts-2.16/7.8.4/hpc/: getDirectoryContents: does not exist (No such file or directory)
```

Can this be reproduced with a publicly accessible repo?

**Comment by adinapoli** [comment]
To give you folks a bit more insights:

* I did call `stack install --coverage` **without** the `--test` flag
* This was a project I ported by not using `stack setup` but I manually created the `stack.yaml`
* The project doesn't have a test suite or a `test` folder altogether.

Is it possible that the `hpc` folder is created as part of the initial `stack` bootstrapping and therefore that's the culprit?

**Comment by mgsloan** [comment]
Ah, this actually turned out to be a rather trivial thing to fix.  Not sure why the problem wasn't obvious before, perhaps because it has nothing to do with the main coverage stuff.  Pretty sure that the issue is that it's trying to create an index of all the hpc reports by listing the contents of a directory.  The directory doesn't get created if no reports get generated.

Can you still reproduce the issue?  Does the commit I've just pushed fix it?  Please close if so :D Thanks!

**Comment by adinapoli** [comment]
Hey @mgsloan , I will make sure to give this a spin as soon as I'll have a chance and report back (closing the issue in case). Thanks!

**Comment by adinapoli** [comment]
@mgsloan Close enough! Now I'm getting a slightly different error:

![screen shot 2015-10-07 at 11 29 11](https://cloud.githubusercontent.com/assets/442035/10335145/ba24ed30-6ce6-11e5-87a1-4aa0ee6c2f3e.png)

**Comment by mgsloan** [comment]
@adinapoli Hah, doh!  Fix pushed.

**Comment by adinapoli** [comment]
Perfect, working as expected now! Thanks!

**Comment by mgsloan** [comment]
Awesome, thanks for trying my fixes!
