### ISSUE TITLE
More helpful error message on TLS error

### ISSUE THREAD

**Issue by dominique-unruh** [commercialhaskell/stack#1010]
When stack raises
```
TlsException (HandshakeFailed (Error_Protocol ("certificate has unknown CA",True,UnknownCa)))
```
(see #234) the error message should include the URL that was accessed (or at least the host), and the suggestion to open it in Internet Explorer and/or a link to the stackoverflow answer (http://stackoverflow.com/questions/32654493/stack-haskell-throws-tlsexception-in-windows/32654494#32654494). The suggestion and link should only occur in Windows.

**Comment by snoyberg** [comment]
I've released a new version of http-client to Hackage, which includes the host and port number for these exceptions. Let's wait until that version makes it into the next LTS release (on Sunday), and then we can bump the resolver in stack.yaml.

In the interim, can you trying adding `http-client-0.4.24` to your `extra-deps` to confirm that this does what you were expecting?

**Comment by dominique-unruh** [comment]
Hi,

no, I can't test it because the error goes away permanently after loading
the pages in IE.
It can probably be reproduced by installing a fresh Windows and installing
stack from scratch without opening IE first.
(But I don't have the time to do that.)
Also: I am not sure one can test the new package via extra-deps, because
the error happens when stack installs, so probably *before* the extra-deps
are installed. But I don't understand the stack install & build process
well enough to be sure.

Best wishes,
Dominique
