### ISSUE TITLE
Cabal postCopy hook doesn't get run

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1016]
`stack install` nearly works for building `ghcjs`, but it doesn't use `runhaskell Setup.hs copy` to install the binaries, and so the ghcjs wrapper scripts don't get installed.  See [the ghcjs Setup.hs file](https://github.com/ghcjs/ghcjs/blob/master/Setup.hs#L34)

**Comment by snoyberg** [comment]
That's very strange, are you suing that `runhaskell Setup.hs install` is not calling the postCopy hook?

**Comment by mgsloan** [comment]
Ahah, that is indeed exactly what's happening: https://mail.haskell.org/pipermail/cabal-devel/2010-July/006535.html

Summary is that `runhaskell Setup.hs install` doesn't call the postCopy hook, just the postInstall hook.  So, given that this behavior isn't going to change, I'd say this is a bug with GHCJS's Setup.hs.  I'll open a patch for that.

**Comment by mgsloan** [comment]
PR for ghcjs: https://github.com/ghcjs/ghcjs/pull/402

**Comment by mgsloan** [comment]
Ok, that worked for `stack build`, but not for `stack install`, since for install, it copies the binaries [here](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Build/Execute.hs#L359).  GHCJS's postCopy / postInstall hook adds more files to the bin directory and uses absolute paths in the wrapper scripts, so in order for it to work correctly, it also needs to be invoked for the final part of

So, it seems like the right thing to do is to invoke `runhaskell Setup.hs copy`, but this doesn't seem to directly work out.  I've tried using Cabal `copy` with the flags that I'd think would make it work, but I get:

```
mgsloan@computer:~/user/Downloads/ghcjs-0.1.0$ runhaskell Setup.hs copy --destdir=~/.stack/programs/x86_64-linux/ghcjs-0.1.0_ghc-7.10.2/ --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/
Installing library in
~/.stack/programs/x86_64-linux/ghcjs-0.1.0_ghc-7.10.2/home/mgsloan/user/Downloads/ghcjs-0.1.0/.stack-work/install/x86_64-linux/lts-3.4/7.10.2/lib/x86_64-linux-ghc-7.10.2/ghcjs-0.1.0-DQPG8NNmyXW45lzfCqtgbc
Installing executable(s) in
~/.stack/programs/x86_64-linux/ghcjs-0.1.0_ghc-7.10.2/home/mgsloan/user/Downloads/ghcjs-0.1.0/.stack-work/install/x86_64-linux/lts-3.4/7.10.2/bin
Warning: The directory
~/.stack/programs/x86_64-linux/ghcjs-0.1.0_ghc-7.10.2/home/mgsloan/user/Downloads/ghcjs-0.1.0/.stack-work/install/x86_64-linux/lts-3.4/7.10.2/bin
is not in the system search path.
```

Note the path `~/.stack/programs/x86_64-linux/ghcjs-0.1.0_ghc-7.10.2/home/mgsloan/user/Downloads/ghcjs-0.1.0/.stack-work/install/x86_64-linux/lts-3.4/7.10.2/lib/x86_64-linux-ghc-7.10.2/ghcjs-0.1.0-DQPG8NNmyXW45lzfCqtgbc` - looks like what's happening is that the configured install dir is getting appended with the requested destination dir.  So, I think we'd need to do another configure in order to use `copy` for this.

@snoyberg thoughts?

**Comment by snoyberg** [comment]
I don't get it.

1. Why do you need to use `stack install` for ghcjs? Keeping it local to the resolver seems correct to me.
2. What's wrong with the original absolute paths being used? Does something actually break?

**Comment by mgsloan** [comment]
1. Keeping it local to the resolver doesn't work for a few reasons:

  - Which resolver would we look in for our copy of ghcjs?  We know to use GHCJS when you specify the `ghcjs-0.1.0_ghc-7.10.2` resolver.

  - I'm reusing the existing code for maintaining tools in `~/.stack/programs/`

It's fine to not have it be resolver-local, as long as we

  - [ ] Add a stack.yaml file to ghcjs (I found that simply `resolver: lts-3.4` was good enough)

This way, there will always be a canonical set of dependencies for a given ghcjs version.

2. Nothing breaks with the original absolute paths, except that initially they pointed into `/tmp/`!  Infact, my current workaround is to unpack the source tarball into a folder such as `.stack/programs/x86_64-linux/ghcjs-0.1.0_ghc-7.10.2/src`.  Then, `stack install`.

Besides these specific details related to setting up GHCJS, here's the problem:

`stack install` doesn't invoke `Setup.hs` when copying binaries to the `local-bin-path`.  It **does**, however, invoke it when copying them to `local-install-root`.

**Comment by mgsloan** [comment]
Looks like this will be resolved by https://github.com/commercialhaskell/stack/issues/848
