### ISSUE TITLE
Ubuntu 15.04 gpg error

### ISSUE THREAD

**Issue by mrLSD** [commercialhaskell/stack#1018]
**Ubuntu 15.04**
sudo apt-get update:
Error GPG: http://download.fpcomplete.com stable Release: NO_PUBKEY 575159689BEFB442

![apt-get-update](https://cloud.githubusercontent.com/assets/798086/9980276/af411c8a-5f9a-11e5-8761-bf355a0ef9dd.png)

**Comment by snoyberg** [comment]
Did you run step 1 in the Ubuntu installation steps?

    wget -q -O- https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -

**Comment by mrLSD** [comment]
That's it!
I lost "-" at end of the command...
Thank you!
