### ISSUE TITLE
`stack ghci` option to switch ghci command and thus use `ghci-ng`

### ISSUE THREAD

**Issue by rrnewton** [commercialhaskell/stack#1024]
The new stack integration in haskell-mode is great, but the "get type at point" command can't work currently, see:  haskell/haskell-mode#889

The problem is it depends on some of the [ghci-ng](https://github.com/chrisdone/ghci-ng) extensions, and there's currently no way to tell `stack` to use `ghci-ng`.  `stack ghci` takes an optional `--with-ghc` option, but that expects a full command-line replacement for ghc, which `ghci-ng` is not.

What is the right thing here?

**Comment by chrisdone** [comment]
`--with-ghc` is the right thing here. It's what you would use with `cabal repl --with-ghc` to use ghci-ng. It's what I use to use ghci-ng with stack. In my stack projects I have this in my `.dir-locals.el`:

``` lisp
((haskell-mode
  . ((haskell-process-type . ghci)
     (haskell-process-path-ghci . "stack")
     (haskell-process-args-ghci . ("ghci" "--with-ghc" "ghci-ng")))))
```

**Comment by chrisdone** [comment]
Think this can be moved back to the haskell-mode discussion.
