### ISSUE TITLE
Add the option of building GHC from source to `stack setup`

### ISSUE THREAD

**Issue by jdnavarro** [commercialhaskell/stack#1026]
This is triggered by the current situation for Arch Linux: https://aur.archlinux.org/packages/haskell-stack/. This issue will eventually be fixed but here I want to propose a more permanent solution.

My first thought was to ask the GHC folks for an official Arch Linux GHC bindist but @hvr explained that the bindists are not optimized for each distribution and they don't want to get into the business of supporting more, which I think it's understandable.

Having `stack` build GHC from source, with the possibility of fine tuning the build process, would be the first step to be able to support different distributions natively. In the case of Arch Linux, for example, the build configurations for different GHC versions could be extracted from the official Arch Linux GHC packages and have them shipped with `haskell-stack` AUR package. I'm willing to maintain such AUR package if necessary.

Compiling from GHC from source will take more time than the bindists, but this avoids security related issues with downloading custom GHC bindists from who knows where.

/cc @borsboom

**Comment by snoyberg** [comment]
I don't think this will really solve the problem you're trying to solve, since GHC needs GHC to build itself. This would also be a heavy code burden for the Stack team to maintain.

**Comment by jdnavarro** [comment]
The system GHC could be used for bootstrapping. But I acknowledge this may be too much work to maintain.

I'll build my own GHC bindist for Arch, then.
