### ISSUE TITLE
Share builds from extra-deps

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#1029]
Since `stack` is able to copy identical builds from different snapshots, can it also copy identical builds from different libraries in `extra-deps`? I'm imagining that `stack` would simply build *all* packages in some mega folder and copy them to other snapshots and working directories as necessary.

**Comment by snoyberg** [comment]
It's theoretically possible, but leads to done complications. Current Cabal doesn't allow us to register the same package/version combination in a single database, for example.

I'm also not sure this is behavior that most people will want: it can increase disk usage in possibly surprising ways.

**Comment by snoyberg** [comment]
Closing as wontfix.

**Comment by proger** [comment]
> but leads to done complications. Current Cabal doesn't allow us to register the same package/version combination in a single database, for example

Could you elaborate on this one?

Would it be at least possible to share *sets* of `extra-deps`? I assume that the easiest way to build a new curated set is to take lts or nightly and add some extra stuff on top which is usually listed in extra-deps.
The use case I have in mind is a set of multiple scripts I'd like to run with `stack runghc` that share the same set of dependencies which grows outside of the lts.

**Comment by bergmark** [comment]
I was just trying to figure out how to get more sharing. For each project I'll probably either choose to use lts/nightly or `stack init --solver` and then make a custom snapshot out of that (we'll see if i can manage this without accidentally mutating a snap shot). I'll probably end up with the latter for all my packages that are part of stackage.

**Comment by proger** [comment]
Though making a custom snapshot every time is still unpleasant business
