### ISSUE TITLE
Stack crashes on Windows

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#1034]
This will likely trickle up to something else, but I'm seeing `stack` crash when it tries to download a new snapshot while my Internet is disabled by 3rd-party software. While it's tempting to blame the 3rd-party, nothing else on my system acts abnormally.

```
C:\code\windows-client>stack build -v
Version 0.1.4.0, Git revision dac8cfe51802e08edb523b80c51cf35e21933513 (1722 commits) X86_64
2015-09-23 15:10:54.8895538: [debug] Checking for project config at: C:\code\windows-client\stack.yaml @(stack_GXibO6avQ
tx8ez3M6BHFie:Stack.Config src/Stack\Config.hs:466:9)
2015-09-23 15:10:54.8913959: [debug] Loading project config file stack.yaml @(stack_GXibO6avQtx8ez3M6BHFie:Stack.Config
src/Stack\Config.hs:489:13)
2015-09-23 15:10:54.8945537: [debug] Trying to decode C:\Users\developer\AppData\Roaming\stack\build-plan-cache\x86_64-w
indows\lts-3.6.cache @(stack_GXibO6avQtx8ez3M6BHFie:Data.Binary.VersionTagged src/Data\Binary\VersionTagged.hs:77:5)
2015-09-23 15:10:54.8952522: [debug] Failure decoding C:\Users\developer\AppData\Roaming\stack\build-plan-cache\x86_64-w
indows\lts-3.6.cache @(stack_GXibO6avQtx8ez3M6BHFie:Data.Binary.VersionTagged src/Data\Binary\VersionTagged.hs:81:13)
2015-09-23 15:10:54.8963227: [debug] Decoding build plan from: C:\Users\developer\AppData\Roaming\stack\build-plan\lts-3
.6.yaml @(stack_GXibO6avQtx8ez3M6BHFie:Stack.BuildPlan src/Stack\BuildPlan.hs:476:5)
2015-09-23 15:10:54.8963227: [debug] Decoding build plan from file failed: InvalidYaml (Just (YamlException "Yaml file n
ot found: C:\\Users\\developer\\AppData\\Roaming\\stack\\build-plan\\lts-3.6.yaml")) @(stack_GXibO6avQtx8ez3M6BHFie:Stac
k.BuildPlan src/Stack\BuildPlan.hs:481:13)
2015-09-23 15:10:54.9013797: [debug] Downloading build plan from: https://raw.githubusercontent.com/fpco/lts-haskell/mas
ter/lts-3.6.yaml @(stack_GXibO6avQtx8ez3M6BHFie:Stack.BuildPlan src/Stack\BuildPlan.hs:485:13)
Downloading lts-3.6 build plan ...
```
That's all she wrote.

**Comment by 3noch** [comment]
The 32-bit build of `stack` has a potentially more helpful error log:

```
C:\code\windows-client>stack build -v
Version 0.1.4.0, Git revision dac8cfe51802e08edb523b80c51cf35e21933513 (1722 commits) I386
2015-09-23 15:18:39.3125972: [debug] Checking for project config at: C:\code\windows-client\stack.yaml @(stack_GXibO6avQ
tx8ez3M6BHFie:Stack.Config src/Stack\Config.hs:466:9)
2015-09-23 15:18:39.3132905: [debug] Loading project config file stack.yaml @(stack_GXibO6avQtx8ez3M6BHFie:Stack.Config
src/Stack\Config.hs:489:13)
2015-09-23 15:18:39.3162303: [debug] Trying to decode C:\Users\developer\AppData\Roaming\stack\build-plan-cache\i386-win
dows\lts-3.6.cache @(stack_GXibO6avQtx8ez3M6BHFie:Data.Binary.VersionTagged src/Data\Binary\VersionTagged.hs:77:5)
2015-09-23 15:18:39.3168484: [debug] Failure decoding C:\Users\developer\AppData\Roaming\stack\build-plan-cache\i386-win
dows\lts-3.6.cache @(stack_GXibO6avQtx8ez3M6BHFie:Data.Binary.VersionTagged src/Data\Binary\VersionTagged.hs:81:13)
2015-09-23 15:18:39.3178931: [debug] Decoding build plan from: C:\Users\developer\AppData\Roaming\stack\build-plan\lts-3
.6.yaml @(stack_GXibO6avQtx8ez3M6BHFie:Stack.BuildPlan src/Stack\BuildPlan.hs:476:5)
2015-09-23 15:18:39.3178931: [debug] Decoding build plan from file failed: InvalidYaml (Just (YamlException "Yaml file n
ot found: C:\\Users\\developer\\AppData\\Roaming\\stack\\build-plan\\lts-3.6.yaml")) @(stack_GXibO6avQtx8ez3M6BHFie:Stac
k.BuildPlan src/Stack\BuildPlan.hs:481:13)
2015-09-23 15:18:39.3228465: [debug] Downloading build plan from: https://raw.githubusercontent.com/fpco/lts-haskell/mas
ter/lts-3.6.yaml @(stack_GXibO6avQtx8ez3M6BHFie:Stack.BuildPlan src/Stack\BuildPlan.hs:485:13)
Downloading lts-3.6 build plan ...FailedConnectionException2 "raw.githubusercontent.com" 443 True <socket: 552>: hPutBuf
: already exists (File exists)
```

**Comment by 3noch** [comment]
I just experienced this on a different computer while in the middle of building a plan. This time the Internet was actually working just fine.

**Comment by snoyberg** [comment]
When you say crashes, do you mean core dumps, or prints an error message and exits with a failure exit code?

**Comment by 3noch** [comment]
For the 32-bit version it prints an exception. For the 64-bit version I get a nasty Windows dialog saying that "stack has stopped working".

**Comment by snoyberg** [comment]
Are you using official binaries or building them yourself?

**Comment by 3noch** [comment]
Official 0.1.4.0 builds from GitHub

**Comment by 3noch** [comment]
Both cases are Windows 10

**Comment by 3noch** [comment]
Scratch that. I just realized one was on a Windows 8 64-bit VM.

**Comment by snoyberg** [comment]
Interesting. Did the crashing only happen on Windows 8? Was that with the
32 or 64 but binary?

**Comment by 3noch** [comment]
I've seen the "stack has stopped working" on both Windows 8 and 10, both times with the 64-bit build of stack from GitHub.

**Comment by snoyberg** [comment]
I'm worried that that might be a GHC bug, or possibly a network package bug. @ndmitchell have you sees anything like this?

**Comment by 3noch** [comment]
On Windows 8 I thought it was merely because my Internet was disabled. But on Windows 10 my Internet (via wifi) was working well enough. It could have had a blip of downtime, however. I couldn't tell. I reran `stack build` and it picked up where it left off.

**Comment by 3noch** [comment]
My thoughts exactly. A segfault is not something Haskell encounters regularly.

**Comment by 3noch** [comment]
Are there any tools to capture low-level logs for this? I'll bet I can reproduce it if I try hard enough.

**Comment by snoyberg** [comment]
At the very least, using --verbose will give a bit more information about
when this happened. Unfortunately, I don't really know details about
debugging a segfault on Windows.

**Comment by ndmitchell** [comment]
Network package seems plausible. For Haskell segfaults none of the nice Windows tricks work, so I fall back to printf debugging usually...

**Comment by 3noch** [comment]
I might chase this for a bit: Haskell/network#166

**Comment by ndmitchell** [comment]
@3noch, that looks like a leak to me, not a segfault.

**Comment by 3noch** [comment]
Oops, wrong issue. Edited.

**Comment by 3noch** [comment]
This crashing is happening almost every time I perform a network-heavy task! Are there logs I can look at/upload?

**Comment by 3noch** [comment]
Definitely *seems* to be an issue with the 64-bit build of `stack`. I'm finally feeling some of the 64-bit concerns that @ndmitchell has harped on over the years. :cry:

**Comment by ndmitchell** [comment]
If you predict doom enough eventually you are right...

**Comment by 3noch** [comment]
Haha..."oh death where is your victory?!"
 
I'd sooner blame `network` than GHC though. Gee wiz, I want to get 64-bit up to snuff.

**Comment by 3noch** [comment]
@borsboom @snoyberg What version of Windows is being used to build the `stack` bindists? I wonder if the executable is linking in different Windows dependencies and getting confused when run on different systems.

**Comment by borsboom** [comment]
@3noch: I'm build it on Windows 10.

**Comment by 3noch** [comment]
32 or 64-bit?

**Comment by borsboom** [comment]
64-bit.

**Comment by 3noch** [comment]
Oh, of course. Anyway, I'm not able to reproduce the crash right now. :( I'm trying to get Process Monitor logs for a crash. One of my colleagues also saw a crash on the 64-bit build (of 0.1.4.0) but the 32-bit version is working.

**Comment by snoyberg** [comment]
Closing for now, as (1) this is almost certainly upstream, and (2) there's no reliable repro.
