### ISSUE TITLE
git refs besides commit hash? (stack.yaml article clarification) 

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#1035]
I'd like to expound this paragraph from [stack.yaml](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md) docs:

```
Note: it is highly recommended that you only use SHA1 values for a Git commit. Other values may work, but they are not officially supported, and may result in unexpected behavior (namely, stack will not automatically pull to update to new versions).
```

- What other syntax is accepted besides `commit: (hash)`?
- When using some unofficial git ref, can you force stack to automatically pull with some flag?

**Comment by mitchellwrosen** [comment]
Sorry, I guess I missed my one change to label this ticket as a "question" - can't seem to do it after it's been created.

**Comment by cocreature** [comment]
You can't and you really shouldn't force stack to automatically pull, that would destroy reproducability.
Not quite sure what other values are supported, I assume it's being handed off to git at some point and if git doesn't complain then other values will work to, but the only sensible thing is really to put a hash in there. For more complex usecases you probably want to go for git submodules or subtrees.

**Comment by mitchellwrosen** [comment]
I agree with all that, but I think the point of the article is to give a comprehensive overview of the valid `stack.yaml` syntax.

**Comment by snoyberg** [comment]
The valid syntax is "anything accepted by Git." I'm OK with a wording change that indicates that, but the warning should stay in place, since it's not recommended practice.

I'm going to close out the issue, if you believe the wording should be in the document, please follow up with a PR.
