### ISSUE TITLE
Support .yml extension

### ISSUE THREAD

**Issue by LukeHoersten** [commercialhaskell/stack#1036]
Some other projects (Ansible for example) support the `.yml` Yaml extension and it would be nice to be consistent through the whole project. [Wikipedia lists both](https://en.wikipedia.org/wiki/YAML).

**Comment by snoyberg** [comment]
I'd be pretty nervous about this, it can lead to a lot of confusion, especially with external tools trying to interact with stack. Having one file path that's supported has lots of advantages.

**Comment by radix** [comment]
Agreed. I can't think of any other app that looks for multiple names for a config file in the same directory. Seems like it'd cause some problems. Which do you choose if both exist?

**Comment by rvion** [comment]
I agree, -1 for supporting several files.

(This being said, I understand the request because I wrote `stack.yml` more than once by mistake in the early days of stack, and spent at least 5 minutes figuring out why didn't my `~/.stack/stack.yml`  work)

**Comment by LukeHoersten** [comment]
@radix many apps support this type of functionality. The order of precedence would be something like "use stack.yaml unless it's missing then look for stack.yml".

@snoyberg I think with simple documentation any minor confusion could be avoided.

**Comment by LukeHoersten** [comment]
On the other hand I guess it's very uncommon to see an app supporting file.conf and file.cfg - It's really up to you guys. I was just making a suggestion.
