### ISSUE TITLE
Windows license restriction in FAQ: outdated?

### ISSUE THREAD

**Issue by mgeisler** [commercialhaskell/stack#1049]
I was skimming the FAQ and saw the section on a [license restriction on Windows][1]. That section says

> [...] Contrary to the majority of Haskell code licensed under permissive BSD3 license, GMP library is licensed under LGPL, which means resulting binaries have to be provided with source code or object files. That may or may not be acceptable for your situation. [...]

I think that is incorrect based on the discussion in #399, which seems to have fizzled out after it was pointed out that LGPL is less dangerous than initially thought.

The basic idea for making the LGPL was to give an alternative to library authors who wanted to allow non-free software to link against their libraries. Unlike the GPL, you can link against a LGPL library without it affecting your program's choice of license. So your program can be BSD, MIT, or even proprietary.

However, *if* you make changes to the LGPL library, *then* you need to provide these changes as well. So you cannot make new cool features in the library and then sit on them while you distribute your fancy program using the new features. Whether you see that feature as a good thing or not is up to you, but that's how LGPL works as far as I can tell.

[1]: https://github.com/commercialhaskell/stack/blob/master/doc/faq.md#what-is-licensing-restrictions-on-windows

**Comment by mwu-tow** [comment]
As far as I know it is not that easy.  
Let's say you develop a proprietory program and want to use library licensed on LGPL. In such case:
* you can link dynamically with the library; 
* you cannot statically link LGPL library into such program (unless you open-source it).

The point is that a user of your programs that depends on LGPL should be able to use the program with a modified version of the open-sourced library. If it is is dynamically-loaded, then it is a matter of replacing .so/.dll (given that ABI is compatible). When statically linked, your program is huge, binary blob and the library cannot be easily replaced.

See 4. d) in http://www.gnu.org/licenses/lgpl-3.0.html

Since GHC handling of `-dynamic` on Windows is not properly supported, all your dependencies get statically linked into your program.

**Comment by vyp** [comment]
IANAL but from my own understanding I have always understood it to be how @mwu-tow described. So what you (@mgeisler) say applies only when dynamically linking. http://programmers.stackexchange.com/questions/47323/can-i-use-an-lgpl-licenced-library-in-my-commercial-app is a link which may help. It also has links to other places (some of which link to even more articles) if someone wants to find out more. (Of course the ultimate reference though is the license text itself which @mwu-tow already linked.)

**Comment by mgeisler** [comment]
@mwu-tow and @vyp Thanks! What you say fits with what the [GPL FAQ][1] says about statically linking with LGPL libraries:

> For the purpose of complying with the LGPL (any extant version: v2, v2.1 or v3):
>
>  (1) If you statically link against an LGPL'd library, you must also provide your application in an object (not necessarily source) format, so that a user has the opportunity to modify the library and relink the application.

Basically, you must provide your program in object form so the user can re-link with an updated version of the library. This is not the same as saying that you must open source your program — but it does of course make some extra demands on you.

What made me open the issue is the "binaries have to be provided with source code or object files" part from the README. Would it be okay if I remove "source code" so it only talks about object files?

[1]: http://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic

**Comment by quyse** [comment]
@mgeisler I would say it would be better to stay as it is. If someone is author of open-source Haskell program (not necessary GPL, but MIT-licensed for example), it would be misleading to say "binaries have to be provided with object files", because in that case it's easier to just provide sources.

**Comment by mgeisler** [comment]
Hmm, well, it's your project :-) I know little about Windows and nothing about how you would go about actually relinking a Haskell program... I was just concerned about what looked like a misunderstanding of what the LGPL actually requires of you.

I'll close the issue — others can refer back to it in the future if they get confused by the README.
