### ISSUE TITLE
Provide an environment in which to compile GHC

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1051]
Currently getting an environment ready to compile GHC is tricky, at least on Windows. You need the right pieces of MSYS (which Stack gets), and a boot version of GHC (which Stack also gets), and a version of Git (which Stack also gets). Are the Stack developers interested in exploring what it would take to make the GHC developer guidelines (perhaps just on Windows, maybe on all platforms) start with "type `stack <something>`"?

**Comment by ndmitchell** [comment]
CC @simonmar @simonpj @snowleopard

**Comment by snoyberg** [comment]
It's somewhat outside the scope of Stack, but I'm not opposed in principle.
I'm sure I'd end up using it myself actually. My first question would be
what pieces of missing. It may even be that `stack exec
--no-ghc-package-path -- standard ghc build instructions` will just work.

**Comment by ndmitchell** [comment]
So the hope is that once GHC is using a Shake based build system then GHC will require "GHC installed and shake installed in the package db", maybe that can be achieved by adding a .yaml file to GHC itself.

**Comment by ndmitchell** [comment]
I've documented the steps currently required: http://neilmitchell.blogspot.co.uk/2016/03/compiling-ghc-on-windows.html

**Comment by ndmitchell** [comment]
Brainstorming ways Stack might be able to generically help:

* Stack doesn't seem to have git on the path when doing `stack exec` by default, unless I pacman install it. I know Stack fundamentally relies on git, so why isn't it requiring the pacman git? If it has its own version of git, why not put that on the path?
* The requirement to first `stack setup` before you have got git, and thus before you can get your hands on a valid stack-yaml file, is a bit sad - since we don't know which stack we are trying to setup for. But I realise the question of how much magic should be done vs how much should you explicitly state stack setup have been gone over before. Perhaps having stack exec before stack setup just install MinGW, but not Haskell compiler?
* If the GHC stack file had Alex/Happy as build dependencies then we could skip installing them explicitly. I assume that's already possible, but haven't looked into it yet.
* If the GHC stack file could specify additional pacman dependencies that would be useful, and eliminate one line.

CC @snowleopard.

**Comment by mgsloan** [comment]
Wow, cool stuff @ndmitchell !

We no longer use pacman to install git - see the note [here](https://github.com/commercialhaskell/stack/blob/ca685c7a1a93d2b07290689ab5df38db28ea4acf/src/Stack/Setup.hs#L1077).

> The requirement to first stack setup before you have got git, and thus before you can get your hands on a valid stack-yaml file, is a bit sad - since we don't know which stack we are trying to setup for. But I realise the question of how much magic should be done vs how much should you explicitly state stack setup have been gone over before. Perhaps having stack exec before stack setup just install MinGW, but not Haskell compiler?

Don't we need a haskell compiler to build ghc?  You can do `stack setup 7.10.3` to install a specific version.

> If the GHC stack file had Alex/Happy as build dependencies then we could skip installing them explicitly. I assume that's already possible, but haven't looked into it yet.

Adding them to `extra-deps` won't be sufficient, as they only get installed by need.  

> If the GHC stack file could specify additional pacman dependencies that would be useful, and eliminate one line.

Related issues:
* https://github.com/commercialhaskell/stack/issues/1586
* https://github.com/commercialhaskell/stack/issues/1384

**Comment by ndmitchell** [comment]
If the git installed by pacman is dodgy, that's an even bigger reason to want to use a different one. Does stack install any git? If so, can that git get added to the PATH?

We do need a GHC to build GHC, but we really want to pick whatever the stack.yaml file says, rather than hardcoding it in the instructions. Therefore we want to have the stack.yaml, and we can't do that until we've got git (so we can get the repo), and we can't do that before stack setup, which installs a GHC, but quite possibly not the right GHC. If we could avoid some of that it would be gently nice - but really no more than gently nice.

Sounds like build-tools will do exactly what we need and eliminate a line out of that list. Thanks!

**Comment by mgsloan** [comment]
Stack actually does not install or require git.  We prefer to have it to get the hackage index, but it will fallback on getting the index tarball via http.  To have stack setup install mingw but not ghc, we could add `stack setup --no-install-ghc`.

**Comment by mgsloan** [comment]
I just had reason to build ghc and was having trouble with it, so figured I'd give this a spin.  Not sure if it's working 100% (will find out in the morning), but it's chugging along.  Great stuff! :D

**Comment by snowleopard** [comment]
@mgsloan Cool, hope it will work! Please let us know the outcome.

**Comment by mgsloan** [comment]
It worked!  I can compile files.  Should I expect `./ghc-stage2 --interactive` to work?  I get

```
GHCi, version 8.1.20160302: http://www.haskell.org/ghc/  :? for help
ghc-stage2: /home/mgsloan/oss/haskell/ghc/.build/stage1/libraries/integer-gmp/HSinteger-gmp-1.0.0.1.o: unknown symbol `__gmpn_rshift'
ghc-stage2: unable to load package `integer-gmp-1.0.0.1'
```

**Comment by snowleopard** [comment]
@mgsloan Great! 

I'm afraid `ghci` won't work. We can only build GHC the vanilla way at the moment, but as I understand the interactive GHC requires the dynamic way, which is not yet implemented: https://github.com/snowleopard/shaking-up-ghc/issues/4.

**Comment by snoyberg** [comment]
@ndmitchell Is this issue still relevant? I think I saw a recent blog post by you where there are already scripts inside GHC which use Stack to set up the build environment.

**Comment by ndmitchell** [comment]
There are scripts and they work well, so I think everything has been solved. FWIW I find compiling GHC with stack to be massively more reproducible than with Cabal, and I think @snowleopard also had to convert SPJ to `stack` so he could compile GHC.

**Comment by snoyberg** [comment]
Awesome, that's great to hear.

**Comment by snowleopard** [comment]
> I think @snowleopard also had to convert SPJ to stack so he could compile GHC.

Just to avoid any misinterpretation, here is what happened: SPJ had an old Cabal installed, which couldn't build Hadrian and also failed on `cabal install cabal-install` with an error. We could install a new Cabal manually, which would likely work fine, but we decided to give Stack a try and it worked fine too, giving us a working GHC build using Hadrian.

**Comment by simonmar** [comment]
Random drive-by comment:

> the interactive GHC requires the dynamic way, which is not yet implemented

Actually GHCi should work fine without the dynamic way, so there must be something else wrong.
