### ISSUE TITLE
Bad Bash completion script on Ubuntu

### ISSUE THREAD

**Issue by xenog** [commercialhaskell/stack#1056]
On Ubuntu, the file `/etc/bash_completion.d/stack` provided by the stack package contains this line:

```bash
    COMPREPLY=( $(usr/bin/stack "${CMDLINE[@]}") )
```

The correct line should include a `/` before `usr/bin/stack`, as such:

```bash
    COMPREPLY=( $(/usr/bin/stack "${CMDLINE[@]}") )
```

As a consequence of this mistake, Bash completion does not work on Ubuntu. Whenever I type the `Tab` key, I get the following error:

```
bash: usr/bin/stack: No such file or directory
```

**Comment by borsboom** [comment]
Oops, a mistake in the release script.  I'll fix it for the next release.
