### ISSUE TITLE
Ubuntu 15.10 (beta): missing dependency on libyaml-0-2?

### ISSUE THREAD

**Issue by ojw** [commercialhaskell/stack#1059]
After `sudo apt-get install haskell-stack` on a fresh install of 15.10, and running `stack upgrade`, I received the complaint:

stack: error while loading shared libraries: libyaml-0.so.2: cannot open shared object file: No such file or directory
After `sudo apt-get install libyaml-0-2`, I was able to run `stack upgrade` successfully.

Possibly a missing dependency in the deb?

**Comment by borsboom** [comment]
Hmm, we don't actually control the `haskell-stack` package on wily.  Not sure who put that together.  Happy to see it officially in a distro, though, although it's already a pretty old version!  Perhaps file a bug report here: <https://bugs.launchpad.net/ubuntu/+source/haskell-stack/+filebug>?

Instructions for the Apt packages we control are available at https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md#ubuntu, but we aren't uploading wily packages yet.  In all likelyhood, the vivid packages will work, but I haven't tested it.

**Comment by ojw** [comment]
I see, thanks.
