### ISSUE TITLE
stack doesn't rebuild test using when using hspec-discover

### ISSUE THREAD

**Issue by maxigit** [commercialhaskell/stack#1061]
I'm using `hspec` with auto discovery. Doing `stack test` doesn't rebuild the tests when one of the spec file is modified.
It think it's due to `hspec-discover`, .i.e the main spec file doesn't change and so it's not detected by stack. Touching the file does't trigger a rebuild, but modifying it (adding a space) does.

I created [there](https://github.com/maxigit/stack-hspec-bug) a repo to reproduce the bug.
To do so, modify the "message to change" in `test/MainSpec.hs` file. `stack test should run the test and show the new message.

**Comment by maxigit** [comment]
I was using stack 1.4, problem seems solved with 1.5.

**Comment by adrianmay** [comment]
It's back in stack 2.3.1. I did `stack new foo hspec; stack test` then edited `test/Data/String/String.hs` and `stack test`. There was no rebuild and the edit had no effect.
