### ISSUE TITLE
Stack --version says I386, should be i386

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1063]
$ stack --version
    Version 0.1.5.0, Git revision 06a4b270de2d2dcbd3ee8abe98078151c4a8f075 I386

It's always written i386, so seeing I386 (I guess because it's a constructor?) looks very weird.

**Comment by NightRa** [comment]
The issue should be redirected to `Cabal`:
http://hackage.haskell.org/package/Cabal-1.22.4.0/docs/src/Distribution.System.html#Arch
The Show instance is derived, and we get the Arch via `buildArch`

**Comment by ndmitchell** [comment]
I think the Show instance should rarely be overridden (it's primary purpose tends to be debugging), the question is whether you should be using a Show or some kind of Pretty function before displaying it to the user. Similarly `OtherArch "My Cool CPU"` wouldn't be a nice way of displaying it, even though Shw would quite reasonably display it.

I do note there is a `Text` instance for `Arch` about 20 lines down from the definition which would produce `i386`, and might be a better thing to use.
