### ISSUE TITLE
Stack ghci before stack build fails

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1065]
C:\Neil\hlint>stack ghci
    Using main module: Package `hlint' component exe:hlint with main-is file: C:\Neil\hlint\src\Main.hs
    Configuring GHCi with the following packages: hlint
    GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help

    <command line>:
        Could not find module `Paths_hlint'
        Use -v to see a list of the files searched for.
    Failed, modules loaded: none.
    Prelude> :q
    Leaving GHCi.

That's after deleting my .ghci file and removing my .stack-work.

My guess is `stack ghci` should generate the paths file if it needs it. I thought it used to do a whole build before launching ghci? Using 06a4b270de2d2dcbd3ee8abe98078151c4a8f075.

**Comment by borsboom** [comment]
@chrisdone / @snoyberg: any thoughts?

**Comment by snoyberg** [comment]
That Paths module will have to be generated by Cabal, which unfortunately only happens from a call to `build`. I'm not deeply involved in the GHCi stuff, but it seems like a large number of issues are coming out of trying to avoid doing a full build before `stack ghci` starts, but that we just need to bite the bullet and do such a build anyway.

**Comment by chrisdone** [comment]
Yep, I agree. It's time to just bite the bullet and do the build and cache-and-ignore any exceptions to retain the optimistic case of running ghci. I was thinking we could also add a trivial `--no-build` flag for impatient people like myself.

**Comment by borsboom** [comment]
@chrisdone: currently `stack targets` and `stack ide` also both do an implicit `build --only-dependencies` beforehand (since they use `ghciSetup` as well).  Should their behaviour also be changed?
