### ISSUE TITLE
Use dependency precompiled with another GHC version

### ISSUE THREAD

**Issue by themoritz** [commercialhaskell/stack#1069]
Is there a way to make stack use the object and lib files of a dependency that were precompiled using a different version of GHC?

Naively copying over the corresponding files from `snapshots\x86_64-windows\lts-3.0\7.10.2.other` to `snapshots\x86_64-windows\lts-3.0\7.10.2`, as well as the files in the `precompiled` folder didn't help, I guess because of something like wrong checksums.

**Comment by snoyberg** [comment]
No, this is a limitation of GHC itself. Stack does everything it can to
prevent you from doing this, since it can result in serious bugs, including
segfaults.

**Comment by themoritz** [comment]
Okay, I understand, thanks!
