### ISSUE TITLE
Stack setup issues strange warning

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#1075]
I'm on Windows and my project is using LTS 3.6. Using official release of stack 0.1.5.0, 64-bit.

```
> stack setup
...
Warning: https://raw.githubusercontent.com/fpco/stackage-content/master/stack/stack-setup-2.yaml: Unrecognized field in SetupInfo: ghcjs```
...
```

**Comment by borsboom** [comment]
That'll be going away in the next release.  It's because a new field was added to stack-setup-2.yaml which trips this warning.  The next release won't warn about extra fields in that file.

**Comment by 3noch** [comment]
Cool
