### ISSUE TITLE
stack solver with --modify-stack-yaml removes all comments from stack.yaml

### ISSUE THREAD

**Issue by hithroc** [commercialhaskell/stack#1079]
When you modify stack.yaml with `stack solver` all of the comments in the file just disappear. This happens even if no needed changes found:
```
$ cat stack.yaml 
# My very important comment
flags: {}
packages:
- '.'
extra-deps: []
resolver: lts-3.6

$ stack solver --modify-stack-yaml
This command is not guaranteed to give you a perfect build plan
It's possible that even with the changes generated below, you will still need to do some manual tweaking
Asking cabal to calculate a build plan, please wait
No needed changes found
Updated /home/hithroc/Programming/Haskell/my-project/stack.yaml

$ cat stack.yaml 
flags: {}
packages:
- '.'
extra-deps: []
resolver: lts-3.6

```

**Comment by snoyberg** [comment]
This is an inherent limitation of the YAML parser available, which throws away comments. This is also common behavior for other command line tools, such as the `travis` CLI. It's highly unlikely that we'll make any changes around this, unless you have some suggestions for approaches here.

**Comment by borsboom** [comment]
Would be nice if there was something like [ruamel](https://pypi.python.org/pypi/ruamel.yaml/0.10.11) for Haskell (or ghc-exactprint for YAML).  Until such exists, not much we can do about this.
