### ISSUE TITLE
symbol lookup error, possibly ld issue?

### ISSUE THREAD

**Issue by vagifverdi** [commercialhaskell/stack#1085]
When trying to run a some functions in repl in emacs haskell-mode that connect to database and fetch data using hdbc-odbc (unixodbc to ms sql server) I'm getting this error: 
/usr/local/lib/ghc-7.10.2/bin/ghc: symbol lookup error: /tmp/ghc25980_0/libghc_1.so: undefined symbol: SQLSetConnectAttr 

Obviously trying the same thing with cabal repl instead of stack was always working fine, and stack build produces normal executable that works fine as well.

I'm guessing this is some sort of ld issue? The odbc drivers are located at /usr/local/lib (this is ubuntu)

Maybe stack is not configured to look there?

**Comment by vagifverdi** [comment]
The same error if running from stack ghci. So it is not emacs or haskell-mode related.

**Comment by borsboom** [comment]
@chrisdone / @snoyberg: any ideas?

**Comment by snoyberg** [comment]
I'm not familiar enough with ghci to have any ideas, sorry.

**Comment by borsboom** [comment]
@vagifverdi: Can you provide `stack --verbose` output?  Also some more information about your environment would be helpful.  Which Linux distribution are you using, and which relevant system package versions are installed?  Any instructions for us to set up a reproduction (if possible, down to how to install a free version of SQL Server to test against) would be really helpful.

**Comment by vagifverdi** [comment]
Linux Ubuntu 15.04
Looks like i'm wrong about ld issue. The error is specific to hdbc-odbc package. It says: /usr/local/lib/ghc-7.10.2/bin/ghc: symbol lookup error: /tmp/ghc25980_0/libghc_1.so: undefined symbol: SQLSetConnectAttr 

Function SQLSetConnectAttr calls a c file hdbc-odbc-helper.c that is bundled with hdbc-odbc package.

I forked hdbc-odbc to patch it for my needs and provide a path to its folder via stack yaml

I just tested with stock hdbc-odbc package installed from hackage and it works fine in stack ghci.

So something is wrong with building a package locally that has a c files included.

To reproduce you need to fetch the hdbc-odbc package source code, and then in a different test project refer to it locally rather than fetching from hackage.

**Comment by vagifverdi** [comment]
I think this is the same issue as #961

**Comment by borsboom** [comment]
@vagifverdi: #961 was merged before stack-0.1.6.0 was released.  Have you tried the latest release of stack?  Or the latest master, if that doesn't help?

**Comment by vagifverdi** [comment]
tried with stack 1.7, still fails

**Comment by mgsloan** [comment]
Looks you've opened another issue on the same subject?  Closing this one in favor of the newer https://github.com/commercialhaskell/stack/issues/1239 .  The most helpful thing to move this forward would be to have a set of steps for reproducing the problem.  Ideally, a repro I can download and directly try.
