### ISSUE TITLE
Stack defaults to 32bit arch on 64bit Windows

### ISSUE THREAD

**Issue by lukexi** [commercialhaskell/stack#1088]
Any time I try to build a local project with `stack build` on Windows with a default stack.yaml, stack complains with
```
GHC version mismatched, found 7.10.2 (x86_64), but expected version 7.10.2 (i386) (based on resolver setting in C:\msys64\home\lukex_000\Code\ide-backend\stack.yaml). Try running stack setup
```

I can work around this by adding
```
arch: x86_64
```
to the package's stack.yaml, but that doesn't seem like it should be necessary.

**Comment by snoyberg** [comment]
The default architecture is determined by the architecture of stack itself.
Try downloading the 64 bit executable instead

**Comment by lukexi** [comment]
Thanks Michael! That indeed does the trick. (possibly this could be called out in the error message?)
