### ISSUE TITLE
Can't start stack ghci with Mueval because of funky Cabal file

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1094]
```
$ stack ghci mueval:exe:mueval
Using main module: Package `mueval' component exe:mueval with main-is file: /home/callen/work/mueval/watchdog.hs
Configuring GHCi with the following packages: mueval
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
ghc: --interactive can't be used with -prof or -unreg.
Usage: For basic information, try the `--help' option.
```

Cabal file: https://github.com/bitemyapp/mueval/blob/master/mueval.cabal#L31-L51

I don't see prof/unreg anywhere?

**Comment by snoyberg** [comment]
It appears to be the -static usage. This sounds like a GHC bug (as far as the confusing messages go), would you be able to open up an issue upstream?

**Comment by bitemyapp** [comment]
@snoyberg sure, should it go to GHC Trac?

**Comment by snoyberg** [comment]
Yes, I think so. It should be reproducible with just the command line for ghci.

@chrisdone should we strip out problematic arguments to ghci like -static?

**Comment by chrisdone** [comment]
@snoyberg We already [do such stripping](https://github.com/fpco/stack/blob/master/src/Stack/Ghci.hs#L291..L293), so I'll go ahead and skip `-static`.

**Comment by chrisdone** [comment]
@bitemyapp Implemented in c42f625. Can you confirm and close?

**Comment by mgsloan** [comment]
No response, looks fixed to me.  Closing!

**Comment by bitemyapp** [comment]
@mgsloan @chrisdone this did indeed solve it, sorry for the delay!

**Comment by mgsloan** [comment]
No worries, just doing issue cleanup :D
