### ISSUE TITLE
"Try running stack setup"... no help.

### ISSUE THREAD

**Issue by njbartlett** [commercialhaskell/stack#1096]
I'm on stack 0.1.2.0 and trying to upgrade. Running `stack upgrade` reports:

    GHC version mismatched, found 7.8.4 (x86_64), but expected version 7.10.2 (x86_64) (based on resolver setting in /var/folders/90/xngk3qjd59d7bpwgq5zvnm_r0000gn/T/stack-upgrade70329/stack-0.1.5.0/stack.yaml). Try running stack setup

So I try the suggestion of running `stack setup` and it prints as follows:

    Using resolver: lts-2.16 from global config file: /Users/nbartlett/.stack/global/stack.yaml
    GHC on PATH would be used

Then I go back and do `stack upgrade` again and it prints exactly the same error:

    GHC version mismatched, found 7.8.4 (x86_64), but expected version 7.10.2 (x86_64) (based on resolver setting in /var/folders/90/xngk3qjd59d7bpwgq5zvnm_r0000gn/T/stack-upgrade70271/stack-0.1.5.0/stack.yaml). Try running stack setup

So I'm stuck in an infinite loop. What can I do? Do I just have to eradicate stack and start over?

**Comment by snoyberg** [comment]
This issue was resolved a while ago. You can upgrade by either:

* downloading a new binary
* running `stack --install-ghc upgrade`

From then on, just the upgrade command should work

**Comment by snoyberg** [comment]
Closing as resolved
