### ISSUE TITLE
C bindings that compile with cabal do not compile with stack

### ISSUE THREAD

**Issue by jgm** [commercialhaskell/stack#1097]
I'm running into this with cmark in particular.  No problems with a regular cabal build, but with `stack test` I get:
```
pandoc-1.15.0.6.log

    ghc: unable to load package `cmark-0.4.1'
    ghc: C:\Users\......\AppData\Roaming\stack\snapshots\i386-windows\lts-3.3\7.10.2\lib\i386-windows-ghc-7.10.2\cmark-0.4.1-JBAkJhqtQdDC7teYNJOjXQ\HScmark-0.4.1-JBAkJhqtQdDC7teYNJOjXQ.o: unknown symbol `___mingw_vsprintf'
```
Any ideas about why?

**Comment by snoyberg** [comment]
When building with cabal, did you also use 32 but GHC? Are you using a
stack installed GHC, or something else?

**Comment by jgm** [comment]
Sorry, I forgot to say explicitly that this is on Windows
(though it may have been obvious from the error message).
I don't have similar problems with stack elsewhere.

Both the stack and cabal builds were done on appveyor
continuous integration.

The successful cabal build used Haskell Platform 2014.2.0.0 64-bit.

The failed stack build used stack.exe from
https://github.com/commercialhaskell/stack/releases/download/v0.1.5.0/stack-0.1.5.0-x86_64-windows.zip

Here's the appveyor build log for the attempted stack build:
https://ci.appveyor.com/project/jgm/pandoc/build/1.0.5

**Comment by snoyberg** [comment]
There are enough differences that I'm very suspect of Stack being the culprit here. From what I can see, you're using:

* Stack (64-bit) with GHC 7.10.2 32-bit
* cabal-install with GHC 7.8.3 64-bit

I find it much more likely that the difference in behavior is coming from GHC than from Stack. Have you tried using Stack with GHC 7.8.4/64-bit, or cabal-install with GHC 7.10.2/32-bit?

**Comment by jgm** [comment]
Sorry, my old appveyor.yml was using `--arch i386` which explains why the 32-bit compiler was used.

I switched to a [version of appveyor.yml](https://github.com/jgm/pandoc/blob/96c8b9dc052205ff87ee01d559212173b24afbb6/appveyor.yml) that just:

- downloads the 64-bit Windows stack and installs it
- clones the pandoc repository
- `stack setup`
- `stack test`

Shouldn't this be expected to work?  This time it produces errors installing old-time and network.
```
Configuring old-time-1.1.0.3...
    ./configure: line 560: 0: Bad file descriptor
    ghc: warning: _tzset from msvcrt is linked instead of __imp__tzset
    ghc: warning: SetConsoleCursorPosition from kernel32 is linked instead of __imp_SetConsoleCursorPosition
    ghc: warning: FillConsoleOutputCharacterA from kernel32 is linked instead of __imp_FillConsoleOutputCharacterA
    ghc: warning: FillConsoleOutputAttribute from kernel32 is linked instead of __imp_FillConsoleOutputAttribute
 ```

Adding `--arch=x86_64` to `stack setup` didn't make any difference.

**Comment by snoyberg** [comment]
Looks like you also removed the `echo "" |` bit from your appveyor.yml, which is necessary to work around the broken stdin it provides to configure scripts. I ran into the same problem when setting up AppVeyor for the Stack repo.

**Comment by jgm** [comment]
Is this an AppVeyor issue or a Windows issue?  Could the `echo "" |` be added inside stack itself, so this hack wouldn't be necessary?

In any case, I added the `echo "" |` back, and now I get a failure at a different point:
```
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\pandoc\.stack-work\logs\pandoc-1.15.1.log
 
    ghc: unable to load package `hslua-0.4.0'
    ghc: warning: _tzset from msvcrt is linked instead of __imp__tzset
    ghc: warning: _strdup from msvcrt is linked instead of __imp__strdup
    ghc: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
    ghc: warning: WSAStartup from ws2_32 is linked instead of __imp_WSAStartup
    ghc: warning: WSACleanup from ws2_32 is linked instead of __imp_WSACleanup
    ghc: warning: accept from ws2_32 is linked instead of __imp_accept
    ghc: warning: inet_ntoa from ws2_32 is linked instead of __imp_inet_ntoa
    ghc: warning: getnameinfo from ws2_32 is linked instead of __imp_getnameinfo
    ghc: warning: getaddrinfo from ws2_32 is linked instead of __imp_getaddrinfo
    ghc: warning: freeaddrinfo from ws2_32 is linked instead of __imp_freeaddrinfo
    ghc: C:\sr\snapshots\x86_64-windows\lts-3.4\7.10.2\lib\x86_64-windows-ghc-7.10.2\hslua-0.4.0-EvWig6BPg4g2AI8IbteY0J\HShslua-0.4.0-EvWig6BPg4g2AI8IbteY0J.o: unknown symbol `mingw_getsp'
Command exited with code 1
```
Any ideas here?  It may not be a stack issue, but as reported, I had no trouble building with cabal (and  ghc 7.8 -- haven't tried 7.10).

**Comment by snoyberg** [comment]
The `echo "" |` is an appveyor issue, you can search the error string you got and find other (non-Haskell) examples. We can't work around it in Stack, since doing so would require breaking terminal detection and other nice features like `--file-watch`.

My idea is still the same: this looks much more like a GHC issue than a Stack issue. The error message you're providing here is one I've gotten every time I tried building Snowdrift with a 64-bit compiler. A quick Google finds:

https://github.com/osa1/hslua/issues/22

**Comment by jgm** [comment]
OK, I'll close this, then.  Looks like it's not a stack issue.
