### ISSUE TITLE
`stack haddock` doesn't detect changes in .cabal files

### ISSUE THREAD

**Issue by lortabac** [commercialhaskell/stack#1098]
If you only modify .cabal files, `stack haddock` doesn't do anything.
You have to modify some other files in order to force it to update the documentation.

**Comment by borsboom** [comment]
Which sorts of changes to the .cabal file do you think cause the haddocks to rebuild?

**Comment by lortabac** [comment]
Changes to the `description` field should trigger a rebuild, but they don't.

**Comment by snoyberg** [comment]
@lortabac This should be resolved on master with 4617847506ef78b39d04bac68a7527493a2f9ece, can you test (`stack upgrade --git`)?

**Comment by lortabac** [comment]
Yes, it works. Now it rebuilds the docs when I change the .cabal file.

**Comment by snoyberg** [comment]
Cool, thanks!
