### ISSUE TITLE
stack setup for GHC 7.10.1 fails (installing Idris)

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1099]
Trying to install Idris from https://github.com/idris-lang/Idris-dev on Windows, it fails at `stack setup`.

    C:\Neil\Idris-dev>stack install
    Compiler version mismatched, found ghc-7.10.2 (i386), but expected minor version match with ghc-7.10.1 (i386) (based on resolver setting in C:\Neil\Idris-dev\stack.yaml).
    Try running "stack setup" to install the correct GHC into C:\Users\ndmit_000\AppData\Local\Programs\stack\i386-windows\

    C:\Neil\Idris-dev>stack setup
    Preparing to install GHC to an isolated location.
    This will not interfere with any system-level installation.
    Already downloaded.
    Already downloaded.
    Already downloaded.

    7-Zip 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

    Processing archive: C:\Users\ndmit_000\AppData\Local\Programs\stack\i386-windows\ghc-7.10.tar.xz

    Extracting  ghc-7.10.tar
    ...
    Extracting  ghc-7.10.1\mingw\share\man\man3
    Extracting  ghc-7.10.1\mingw\share\man\man3\basename.3
    Extracting  ghc-7.10.1\mingw\share\man\man3\dirname.3
    Extracting  ghc-7.10.1\perl
    Extracting  ghc-7.10.1\perl\perl.exe
    Extracting  ghc-7.10.1\perl\perl56.dll

    Everything is Ok

    Folders: 344
    Files: 5895
    Size:       892874952
    Compressed: 897781760
    C:\Users\ndmit_000\AppData\Local\Programs\stack\i386-windows\ghc-7.10-tmp7116\ghc-7.10\: renameDirectory: does not exist (No such file or directory)

    C:\Neil\Idris-dev>stack --version
    Version 0.1.5.0, Git revision 1b0b453df18d0ec0a6d6bcc58e904857c5576887 i386

**Comment by borsboom** [comment]
I've reproduced.

**Comment by borsboom** [comment]
Turns out this was an error in the metadata stack downloads to find the GHC bindists.  I've fixed the metadata, and `stack setup` worked for me this time.  So you won't even need to build a new `stack` to get this fix.
