### ISSUE TITLE
Support of git tags

### ISSUE THREAD

**Issue by d12frosted** [commercialhaskell/stack#1100]
Hey,

What do you think about supporting git tags as well as git commits for packages in `stack.yaml`? I think about git commits as lower bound for package dependency. Since a lot of people are using git tags for versioning it allows more declarative way of describing packages from git. So for example, you could have following lines in `stack.yaml` file.

```
packages:
- '.'
- location:
    git: link/to/.git
    tag: v0.1.2.0
```

In my opinion it's a bit clearer. Yeah, it's just cosmetic feature, but I think it would be nice to have. What do you think?

P. S. Sorry if it's duplicate of existing feature request – I couldn't find anything similar.

**Comment by borsboom** [comment]
Did you try setting the `commit:` value to the tag?  I believe that it will accept any "commit-ish"

**Comment by borsboom** [comment]
Closing this issue, but feel free to reopen if putting a tag in `commit:` doesn't work for you.

**Comment by d12frosted** [comment]
Yeah, sorry. Haven't had a chance to test it properly until now. And yes, it perfectly works! Thanks for making it so convenient :smile:
