### ISSUE TITLE
stack ghci has duplicate package installs

### ISSUE THREAD

**Issue by andrewthad** [commercialhaskell/stack#1104]
So, I'll start by saying that I can't provide the exact steps to reproduce this, but I can show what happens. Basically, I use yesod-form in an application I'm writing, and I use another library, yesod-bootstrap, which also uses yesod-form. However the `AForm` type is somehow failing to unify. Here is the error:

    Model/Fields.hs:103:26:
        Couldn't match type ‘AForm
                               (Yesod.Core.Types.HandlerT site0 IO) Severity’
                       with ‘yesod-form-1.4.4.1@yesod_Hus1GucwCuoKpwDjNlci5f:Yesod.Form.Types.AForm
                               (Yesod.Core.Types.HandlerT site IO) Severity’
        NB: ‘AForm’
              is defined in ‘Yesod.Form.Types’
                  in package ‘yesod-form-1.4.4.1@yesod_LwocnXCrypx4tYVO8g9tJG’
            ‘yesod-form-1.4.4.1@yesod_Hus1GucwCuoKpwDjNlci5f:Yesod.Form.Types.AForm’
              is defined in ‘Yesod.Form.Types’
                  in package ‘yesod-form-1.4.4.1@yesod_Hus1GucwCuoKpwDjNlci5f’
        Expected type: yesod-form-1.4.4.1@yesod_Hus1GucwCuoKpwDjNlci5f:Yesod.Form.Types.AForm
                         m Severity
          Actual type: AForm (Yesod.Core.Types.HandlerT site0 IO) Severity
        In the expression:
          areq (selectField optionsEnum) (bfs $ Text.dropWhile isLower lbl) m
        In an equation for ‘gcrudFormNamed’:
            gcrudFormNamed lbl m
              = areq
                  (selectField optionsEnum) (bfs $ Text.dropWhile isLower lbl) m

This only happens with `stack ghci`, not with `stack build`. Somehow, it's got two builds of yesod-form in the package database. I've tried clearing out `.stack-work` and running `stack clean`. My version is:

    Version 0.1.5.0, Git revision a30f022c3dca7c489e08f31908ea77c3bf305375 (2159 commits) X86_64

**Comment by snoyberg** [comment]
I believe this should be addressed by PR #1082, can you test that out?

**Comment by snoyberg** [comment]
Closing, let's follow up on #1082 if necessary.

**Comment by andrewthad** [comment]
Although the issue is already closed out, I'll go ahead an confirm that the problem is fixed with the newest version of stack in the ubuntu repos:

    Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64

And things are all working correctly. Thanks.
