### ISSUE TITLE
Haddocks not copied for dependencies (was: Installing and using offline documentations?)

### ISSUE THREAD

**Issue by carldong** [commercialhaskell/stack#1105]
I use only stack for my local haskell installation. However, I don't see a way to locally install documents from packages, and `hoogle` does not find them either. It may be a nice feature to have because when I used the haskell platform in Ubuntu official repo, I can easily just search using `hoogle`, or look into local documentations.

**Comment by snoyberg** [comment]
`stack haddock` should generate the documents locally. See #55 about a `stack hoogle` command

**Comment by diegs** [comment]
Running `stack haddock` or `stack build --haddock` seems to populate local haddock in `.stack-work` and snapshot-wide haddock `~/.stack/snapshots/x86_64-osx/lts-3.8/7.10.2/doc/`. Very cool! Unfortunately the snapshot-wide haddocks appear to be missing the documentation for Base. Is there any way for that to be included?

I'd love to be able to go offline and easily browse all the version-correct docs for my current project.

**Comment by snoyberg** [comment]
Are you using a Stack installed GHC, or something else? The GHC which Stack
installs should include documents for bundled libraries.

**Comment by carldong** [comment]
I am using stack installed GHC. I found the offline docs after I installed packages using `stack install <pkg> --haddock`. However, `hoogle` does not find all documentations about the packages I installed. For example:

```
hoogle blit
Graphics.Rendering.OpenGL.GL.ReadCopyPixels blitFramebuffer :: Position -> Position -> Position -> Position -> [BlitBuffer] -> TextureFilter -> IO ()
Graphics.Rendering.OpenGL.GL.ReadCopyPixels data BlitBuffer
```

There should also be results from `SDL` and `sdl2`.

**Comment by snoyberg** [comment]
This sounds more like a question about how best to use hoogle, rather than a feature in stack, unless I'm mistaken.

**Comment by carldong** [comment]
No, it is about stack. If I use Ubuntu official version of GHC, then any package I installed will automatically be in database of Hoogle, but stack packagages do not.

**Comment by borsboom** [comment]
`stack hoogle` (#55) is going to be the way to do this.  Stack doesn't install packages and documentation to the default locations where globally installed `hoogle` looks.  `stack haddock` does output the `.txt` input files for `hoogle`, so it *is* possible to use `hoogle` commands to generate a database from those and search them, but installing into the global databases is not something Stack will ever do.

**Comment by carldong** [comment]
I see. Will `stack hoogle` be supported in some future release?

**Comment by borsboom** [comment]
Yes, it's also a feature that I want.

**Comment by diegs** [comment]
I am using stack installed GHC as well, which I assume lives in `.stack/snapshots/x86_64-osx/lts-3.8/` but there's no documentation in there. Is it somewhere else?

It would be nice if it were all in one place, but as long as it's somewhere local I could make do.

**Comment by borsboom** [comment]
There does seem to be something going wrong with `stack haddock` putting documentation for dependencies where it should be.  There's a regression here.

Expected behaviour is for `stack haddock` to put documentation for snapshot packages and their dependencies included with GHC in, e.g., `~/.stack/snapshots/x86_64-osx/lts-3.0/7.10.2/doc`.  It does seem to be putting the docs for the snapshot packages it builds, but it's not linking in the GHC-included docs (e.g. for `base`).

In addition, all of a project's dependencies' docs should get put in, e.g., `.stack-work/install/x86_64-osx/lts-3.0/7.10.2/doc/all/`, but that doesn't seem to be happening.  It is correctly putting the project's local packages' docs in `.stack-work/install/x86_64-osx/lts-3.0/7.10.2/doc`, though.
