### ISSUE TITLE
Released package is missing documentation

### ISSUE THREAD

**Issue by magthe** [commercialhaskell/stack#1108]
It would be nice to have the documentation included in the releases on hackage.

**Comment by borsboom** [comment]
Looks like Hackage hits a weird error for a missing dependency when building haddocks.  I've uploaded the docs for 0.1.5.0, and I'll add uploading documentation to the release process for future releases.  Also good impetus for getting #737 done.

**Comment by magthe** [comment]
My bad!  I meant the very handy usage documentation found under `doc/`.

**Comment by borsboom** [comment]
Ah, sorry I misunderstood.  Yes, we should add that to `stack.cabal`'s `extra-source-files`.

**Comment by borsboom** [comment]
New release includes the docs here: http://hackage.haskell.org/package/stack-0.1.6.0/src/doc/
