### ISSUE TITLE
Make compilation cycles in --file-watch mode visually separated

### ISSUE THREAD

**Issue by ethercrow** [commercialhaskell/stack#1109]
Currently it's pretty hard to see in a wall of output where the previous compilation ended and current compilation began.

I suppose stack could make ExitFailure and ExitSuccess lines colored red and green when stdout goes to an interactive terminal. Alternatively, some ascii-art page breaks would work too.

Attaching output of `stack install --file-watch` and `sos -p '\.hs' -c 'stack build'` for comparison.
![screen shot 2015-10-06 at 14 55 46](https://cloud.githubusercontent.com/assets/222467/10304207/2c5ca344-6c32-11e5-81a6-a4dc3d01a3f7.png)
![screen shot 2015-10-06 at 14 56 03](https://cloud.githubusercontent.com/assets/222467/10304211/34915a64-6c32-11e5-8adb-92e5017b76c4.png)

**Comment by snoyberg** [comment]
Sounds like a good change to me, and is in a very isolated part of the codebase. Interested in taking a stab at this?

**Comment by ethercrow** [comment]
Sure, I'll probably look into it during the weekend if noone jumps in before that.

**Comment by snoyberg** [comment]
Implemented by #1142, closing.
