### ISSUE TITLE
LTS 2.7 and network strange error on Windows 8.1 x64

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#1113]
Windows 8.1 x64
Stack Version 0.1.4.1 (UNKNOWN commits) X86_64

```...
Loading package network-2.6.0.2 ... linking ... ghc.exe: unable to load package `network-2.6.0.2'
ghc.exe: C:\Users\varosi\AppData\Roaming\stack\snapshots\x86_64-windows\lts-2.7\7.8.4\lib\x86_64-windows-ghc-7.8.4\network-2.6.0.2\HSnetwork-2.6.0.2.o: unknown symbol `shutdownWinSock'

**Comment by varosi** [comment]
same is with 0.1.5, too.

**Comment by snoyberg** [comment]
Please provide a complete set of steps for repro

**Comment by varosi** [comment]
Could I send it to you privately somehow?

**Comment by snoyberg** [comment]
To look into this I'm really going to need something minimal, I won't have
time right now to dig into a large code base.

**Comment by mgsloan** [comment]
Closing this, as it's an old support ticket.  If you think this is in error, please comment with more info.
