### ISSUE TITLE
`stack ghci stack:exe:stack` doesn't work

### ISSUE THREAD

**Issue by rrnewton** [commercialhaskell/stack#1114]
I love the new ability to select targets for `stack ghci`!

I tried to follow the instructions for specifying a target, as recommended by `stack ghci` itself.  What I got was a whole bunch of errors like this one:

```
$ stack ghci stack:exe:stack
Using main module: Package `stack' component exe:stack with main-is file: /home.local/rrnewton/working_copies/stack/src/main/Main.hs
Configuring GHCi with the following packages: stack
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
...
/home.local/rrnewton/working_copies/stack/src/main/Main.hs:52:18:
    Could not find module ‘Stack.Dot’
    Use -v to see a list of the files searched for.
...
/home.local/rrnewton/working_copies/stack/src/main/Main.hs:79:18:
    Could not find module ‘System.Process.Read’
    Perhaps you meant
      System.Process (from process-1.2.3.0@proce_FLTz0SLwyG6LJUpZ52HjkU)
      System.Process.Extra (needs flag -package-key extra-1.4.2@extra_5OxQCVeoy8KDx9eBZEd38j)
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
```

So it looks like none of the dependencies for that executable target are getting loaded... hmm.

This is when trying to build stack itself (current HEAD), using stack 0.1.5 on Mac or Linux (which both exhibit the same behavior).

**Comment by borsboom** [comment]
@chrisdone, any ideas?

**Comment by mgsloan** [comment]
This is fixed for me in the latest development version.  Feel free to reopen if the issue isn't resolved!
