### ISSUE TITLE
During linking of my program I get strange paths under Windows 8 and 10

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#1116]
Stack 0.1.5.0
Windows 10 x64 and Windows 8.1 x64

During linking of my program I get:

 > ghc.exe: could not execute: C:\Users\myuser\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.2\lib/../mingw/bin/gcc.exe

gcc.exe is really there, but there are some strange *nix based slashes inside the path.
Tested on two different machines.

**Comment by snoyberg** [comment]
See https://www.fpcomplete.com/blog/2015/08/stack-ghc-windows

**Comment by varosi** [comment]
set STACK_ROOT=c:\stack

Solved this problem! Thanks! We're waiting for new GHC!
