### ISSUE TITLE
Show full path to log file

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#1120]
Stack Version 0.1.5.0 X86_64

Currently stack is giving that message:
 > See `config.log' for more details

Where is that is a mistery. It'll be great if it gives full path to this log file.

**Comment by snoyberg** [comment]
I can't be sure due to lack of context, but I believe that error message is coming from a configure script (based on #1121), which Stack has no control over. Unpacking network and running `stack build` inside that directory may provide more information.
