### ISSUE TITLE
Remove PCRE dependency

### ISSUE THREAD

**Issue by TomMD** [commercialhaskell/stack#1123]
The community shift toward used stack frustrates deployment by additionally requiring the C PCRE library on any machine used to build stack.  That is to say, it used to be easy to `wget $GHC-bin ; wget $cabal ; unpack/install ghc ; boostrap.sh cabal`.  These days I now also need to bother an administrator or build pcre as a user-local library.

Two possible solutions come to mind:

1. Replace the use of PCRE with pure Haskell, perhaps TDFA if appropriate.
2. Add, to pcre-light, a flag that indicates the C library should be built locally.  Add a `boostrap.sh` to stack that detects PCRE and conditionally uses said flag.

Thoughts?

**Comment by borsboom** [comment]
`stack` itself doesn't require PCRE, but the [ignore](http://hackage.haskell.org/package/ignore) dependency does by default, unless you set its `without-pcre` flag.  Stack's `stack.yaml` does exactly that, so building Stack with `stack` will not require PCRE.

**Comment by TomMD** [comment]
So the current zero-to-stack method is then:

```
# Download GHC and cabal
# Unpack GHC
# bootstrap cabal
cabal install ignore -fwithout-pcre
cabal install stack
```
This still seems livable, but that is an unfortunate indirection in the middle.  I'll push this over to ignore.

**Comment by borsboom** [comment]
If you're using a GHC bindist anyway, you could also use a [bindist of Stack](https://github.com/commercialhaskell/stack/releases/latest).

**Comment by TomMD** [comment]
I didn't realize stack had diverse bindist, thanks!

**Comment by borsboom** [comment]
FYI: the `ignore` dependency was removed in #1155, so libpcre will no longer be needed for `cabal install stack`.

**Comment by TomMD** [comment]
Nice, thanks for pushing forward on this!
