### ISSUE TITLE
Incorrect bash_completion file on Ubuntu 12.04

### ISSUE THREAD

**Issue by jorgecunhamendes** [commercialhaskell/stack#1126]
After installing stack from deb (0.1.5.0-0~trusty), bash completion is not working correctly. Modifying
```
    COMPREPLY=( $(usr/bin/stack "${CMDLINE[@]}") )
```
to
```
    COMPREPLY=( $(/usr/bin/stack "${CMDLINE[@]}") )
```
in `/etc/bash_completion.d/stack` seems to solve the issue (notice the root slash in the path).

**Comment by borsboom** [comment]
Duplicate of #1056
