### ISSUE TITLE
Change default to not use system-ghc unless otherwise specified.

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1129]
Justification here: https://github.com/commercialhaskell/stack/issues/1125#issuecomment-146733987

**Comment by bitemyapp** [comment]
Inverting this: https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#system-ghc

**Comment by bitemyapp** [comment]
Rejected per @snoyberg (user feedback overwhelmingly wants system GHC)

**Comment by snoyberg** [comment]
As a general note that applies here too: if you think the general consensus wouldn't be this direction, feel free to raise the point on the mailing list to garner more feedback. I'm just basing this on whom I've heard from.

**Comment by bitemyapp** [comment]
@snoyberg sent!
