### ISSUE TITLE
Module excluded from other-modules lead to package getting unregistered

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#1134]
This is an old problem that I thought was addressed. Repro available at: http://download.fpcomplete.com/michael/unnecessary-recompilation-missing-other-modules.tar.gz. Actions:

1. Unpack tarball
2. Run `stack test` in directory, both `foo1` and `foo2` build and pass tests (expected)
3. Run `stack test` again

Expected: tests rerun immediately

Actual: both foo1 and foo2 are first unregistered and rebuilt due to the `Unused` module not appearing in the foo1.cabal file:

```
$ stack test
foo1-0.1.0.0: unregistering (local file changes: test/Unused.hs)
foo2-0.1.0.0: unregistering (missing dependencies: foo1)
foo1-0.1.0.0: build
Warning: module not listed in foo1.cabal for 'foo1-test' component (add to other-modules): Unused
foo1-0.1.0.0: install
foo2-0.1.0.0: configure
foo1-0.1.0.0: build (test)
foo1-0.1.0.0: test (suite: foo1-test)
foo2-0.1.0.0: build
foo2-0.1.0.0: install
foo2-0.1.0.0: configure (test)
foo2-0.1.0.0: build (test)
foo2-0.1.0.0: test (suite: foo2-test)
Completed all 4 actions.
```

**Comment by snoyberg** [comment]
Something possibly unrelated I ran into: when working on a large code base with many packages, I had to run `stack test` multiple times to get the relevant warnings about missing other-modules. Each time I fixed some, more warnings would appear until I got all of them. The ideal would be that on first run, every missing other-module is detected and warned about.

**Comment by snoyberg** [comment]
Also somewhat tangential, but: we may want to always ignore cabal_macros.h as a dependency. That file should only change meaningfully when our configure options have changed, and therefore recompiles triggered by that file should be meaningless.

**Comment by borsboom** [comment]
This is now fixed in a way that made minimal changes to the code.  However, this can be improved (especially to eliminate the duplicate warnings) once I discuss with @mgsloan how best to approach in conjunction with his changes to the tests/benchmarks.
