### ISSUE TITLE
entropy-0.3.7 error

### ISSUE THREAD

**Issue by mrLSD** [commercialhaskell/stack#1137]
Really strange issue:

Ubuntu 15.04
<pre>
$ stack --version
Version 0.1.5.0, Git revision a30f022c3dca7c489e08f31908ea77c3bf305375 (2159 commits) X86_64

$ stack new tst2 yesod-postgres
Downloading template "yesod-postgres" to create project "tst2" in tst2/ ...
Writing default config file to: /home/evgeny/hs/tst2/stack.yaml
Basing on cabal files:
- /home/evgeny/hs/tst2/tst2.cabal

Checking against build plan lts-3.6
Selected resolver: lts-3.6
Wrote project config to: /home/evgeny/hs/tst2/stack.yaml

$ cd tst2

$ stack build
asn1-types-0.3.0: configure
asn1-types-0.3.0: build
happy-1.19.5: configure
entropy-0.3.7: configure
http-date-0.0.6.1: configure
http-date-0.0.6.1: build
asn1-types-0.3.0: install
http-date-0.0.6.1: install
Progress: 4/134
--  While building package entropy-0.3.7 using:
      /home/evgeny/.stack/programs/x86_64-linux/ghc-7.10.2/bin/runhaskell -clear-package-db -global-package-db -package-db=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/pkgdb/ -package-db=/home/evgeny/hs/tst2/.stack-work/install/x86_64-linux/lts-3.6/7.10.2/pkgdb/ -hide-all-packages -package=Cabal-1.22.4.0 -package-id=array-0.5.1.0-d4206b835b96b5079d918fa1eab1a9a8 -package-id=base-4.8.1.0-4f7206fd964c629946bb89db72c80011 -package-id=bin-package-db-0.0.0.0-b04c253694f93767af4f641e39a406a0 -package-id=binary-0.7.5.0-07214b304bb0a2c4cbf50d9dc7914ee6 -package-id=bytestring-0.10.6.0-2362d1f36f1255e85478e7793e15b170 -package-id=containers-0.5.6.2-2de75421d746ab474b330e43191bb31b -package-id=deepseq-1.4.1.1-8fb9688ae42216e388cee132aef3d148 -package-id=directory-1.2.2.0-258f6e56fc0799f4b45f149644b75783 -package-id=filepath-1.4.0.0-8fee9c13b5e42926cc01f6aa7c403c4b -package-id=ghc-prim-0.4.0.0-af16264bc80979d06e37ac63e3ba9a21 -package-id=haskeline-0.7.2.1-0a475c6a6a7de67d5fce6186e9d8d81a -package-id=hoopl-3.10.0.2-c84778769b61752ff34e979bbbebdb63 -package-id=hpc-0.6.0.2-567a296524cbf417c57abd674ccf4f5e -package-id=integer-gmp-1.0.0.0-8e0f14d0262184533b417ca1f8b44482 -package-id=pretty-1.1.2.0-2932d0905cc17ca1d9638eb9cca0a227 -package-id=process-1.2.3.0-f0287ac288afc0705be775d1adda59ee -package-id=template-haskell-2.10.0.0-90e8393d65f4ae44cb2026177a257f28 -package-id=terminfo-0.4.0.1-c72a7d139b97f9299867b81ab34b8dde -package-id=time-1.5.0.1-c208e8fcb3277879fd30f1140654d53e -package-id=transformers-0.4.2.0-21dcbf13c43f5d8cf6a1f54dee6c5bff -package-id=unix-2.7.1.0-6436007ffcf967b9823833b48295b586 -package-id=xhtml-3000.2.1-5a3d6f023f8af89b9c3e60e732c4b723 /tmp/stack9082/entropy-0.3.7/Setup.hs --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/pkgdb/ --libdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/lib --bindir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/bin --datadir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/share --libexecdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/libexec --sysconfdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/etc --docdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/doc/entropy-0.3.7 --htmldir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/doc/entropy-0.3.7 --haddockdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/doc/entropy-0.3.7 --dependency=base=base-4.8.1.0-4f7206fd964c629946bb89db72c80011 --dependency=bytestring=bytestring-0.10.6.0-2362d1f36f1255e85478e7793e15b170 --dependency=unix=unix-2.7.1.0-6436007ffcf967b9823833b48295b586
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/evgeny/hs/tst2/.stack-work/logs/entropy-0.3.7.log

    <command line>: can't load .so/.DLL for: libtinfo.so (libtinfo.so: cannot open shared object file: No such file or directory)

--  While building package happy-1.19.5 using:
      /home/evgeny/.stack/programs/x86_64-linux/ghc-7.10.2/bin/runhaskell -clear-package-db -global-package-db -package-db=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/pkgdb/ -package-db=/home/evgeny/hs/tst2/.stack-work/install/x86_64-linux/lts-3.6/7.10.2/pkgdb/ -hide-all-packages -package=Cabal-1.22.4.0 -package-id=array-0.5.1.0-d4206b835b96b5079d918fa1eab1a9a8 -package-id=base-4.8.1.0-4f7206fd964c629946bb89db72c80011 -package-id=bin-package-db-0.0.0.0-b04c253694f93767af4f641e39a406a0 -package-id=binary-0.7.5.0-07214b304bb0a2c4cbf50d9dc7914ee6 -package-id=bytestring-0.10.6.0-2362d1f36f1255e85478e7793e15b170 -package-id=containers-0.5.6.2-2de75421d746ab474b330e43191bb31b -package-id=deepseq-1.4.1.1-8fb9688ae42216e388cee132aef3d148 -package-id=directory-1.2.2.0-258f6e56fc0799f4b45f149644b75783 -package-id=filepath-1.4.0.0-8fee9c13b5e42926cc01f6aa7c403c4b -package-id=ghc-prim-0.4.0.0-af16264bc80979d06e37ac63e3ba9a21 -package-id=haskeline-0.7.2.1-0a475c6a6a7de67d5fce6186e9d8d81a -package-id=hoopl-3.10.0.2-c84778769b61752ff34e979bbbebdb63 -package-id=hpc-0.6.0.2-567a296524cbf417c57abd674ccf4f5e -package-id=integer-gmp-1.0.0.0-8e0f14d0262184533b417ca1f8b44482 -package-id=mtl-2.2.1-5cf332b11edb88a6040af20fd6a58acb -package-id=pretty-1.1.2.0-2932d0905cc17ca1d9638eb9cca0a227 -package-id=process-1.2.3.0-f0287ac288afc0705be775d1adda59ee -package-id=template-haskell-2.10.0.0-90e8393d65f4ae44cb2026177a257f28 -package-id=terminfo-0.4.0.1-c72a7d139b97f9299867b81ab34b8dde -package-id=time-1.5.0.1-c208e8fcb3277879fd30f1140654d53e -package-id=transformers-0.4.2.0-21dcbf13c43f5d8cf6a1f54dee6c5bff -package-id=unix-2.7.1.0-6436007ffcf967b9823833b48295b586 -package-id=xhtml-3000.2.1-5a3d6f023f8af89b9c3e60e732c4b723 /tmp/stack9082/happy-1.19.5/Setup.lhs --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/ configure --user --package-db=clear --package-db=global --package-db=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/pkgdb/ --libdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/lib --bindir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/bin --datadir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/share --libexecdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/libexec --sysconfdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/etc --docdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/doc/happy-1.19.5 --htmldir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/doc/happy-1.19.5 --haddockdir=/home/evgeny/.stack/snapshots/x86_64-linux/lts-3.6/7.10.2/doc/happy-1.19.5 --dependency=array=array-0.5.1.0-d4206b835b96b5079d918fa1eab1a9a8 --dependency=base=base-4.8.1.0-4f7206fd964c629946bb89db72c80011 --dependency=containers=containers-0.5.6.2-2de75421d746ab474b330e43191bb31b --dependency=mtl=mtl-2.2.1-5cf332b11edb88a6040af20fd6a58acb
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/evgeny/hs/tst2/.stack-work/logs/happy-1.19.5.log

    <command line>: can't load .so/.DLL for: libtinfo.so (libtinfo.so: cannot open shared object file: No such file or directory)
</pre>

**Comment by snoyberg** [comment]
You likely need to run something like

sudo apt-get install libtinfo-dev

**Comment by mrLSD** [comment]
Thanks, that's it!
