### ISSUE TITLE
Installer for Stack that updates user's PATH automatically

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1140]
I realize this might sound trivial, but there are a lot of people on Mac OS X and Linux that really have no idea how the PATH works.

https://ghcformacosx.github.io/ does this.

**Comment by bitemyapp** [comment]
A command like `stack setup-path` would satisfy.

**Comment by Rufflewind** [comment]
It looks like `stack exec` does something very similar already.

  - On non-Windows systems, one can use `stack exec bash`.

  - On Windows, one can use `stack exec cmd.exe` (file extension is mandatory) or `stack exec bash`, depending on preference.

In both cases, the existing environment not modified; rather, a new shell process is spawn with the Stack environment.  When the shell is used interactively, most users are unlikely to care about this this subtle distinction.

---

If the user really wants to modify the current environment (which may be useful in certaom scripts), it is still possible (albeit not as straightforward).

`stack path` seems to prints out the `PATH` variable in the form:

    bin-path: …

which means if one can parse this output somehow, then it would be a simple matter of setting `PATH` to the printed value.  In Bash this is easy:

~~~sh
new_path=$(stack path | sed -n 's/^bin-path: *\(.*\)/\1/p') &&
[ "$new_path" ] &&
export PATH=$new_path
~~~

It would be quite hard to do this in Command Prompt without third-party tools, but it seems possible in PowerShell (someone more proficient in PowerShell should double-check this):

~~~ps
stack path | %{
  if ($_ -match "(.*): (.*)" -and $matches[1] -eq "bin-path") {
    $env:PATH = $matches[2];
  }
}
~~~

**Comment by NightRa** [comment]
@Rufflewind It should be documented.

**Comment by borsboom** [comment]
@Rufflewind What about `export PATH="$(stack path --bin-path):$PATH"`?

That said, I'd some clarity on what @bitemyapp is asking for, because I'm not sure that it's the same thing.  Do you mean a command that appends something `export PATH="~/.local/bin:$PATH"` to your .profile/.bashrc?  That (and making sure `stack` itself is in the PATH) is the only user PATH change we  recommend people make.    For project-specific paths, using `stack exec` is the preferred approach.

**Comment by Blaisorblade** [comment]
> That said, I'd some clarity on what @bitemyapp is asking for, because I'm not sure that it's the same thing. Do you mean a command that appends something like export PATH="~/.local/bin:$PATH" to your .profile/.bashrc? That (and making sure stack itself is in the PATH) is the only user PATH change we recommend people make.

Yes—that's what https://ghcformacosx.github.io/ does.

**Comment by harendra-kumar** [comment]
It is ugly to modify a user's shell rc/profile, I personally do not like that. But more than the personal choice it could be an implementation ugliness - to make it work for every case you will have to take care of all the shells not just bash.

**Comment by Blaisorblade** [comment]
In fairness: GHC for Mac OS X gives you a button to do that. I've seen tons of installers doing this and IIUC none supports non-Bourne shells—and I'm not sure any supports non-bash. (Systems using `~/.profile` are more general, but we have no choice over that).

The original proposal suggested  a `stack setup-path` command might be enough, and that would not force this on users.

Though how do you run that if stack is not yet on the PATH? I guess after downloading the binary but before moving it in place...

There might well be users of alternative shells that don't know what PATH is or miss the instructions; but I think that population is tiny.

**Comment by Rufflewind** [comment]
> It is ugly to modify a user's shell rc/profile

I agree. Since shell profiles contain arbitrary scripts, modifying it may not always work (imagine if there was an early `return` in the script), or it could break the profile (unlikely but possible).

At the very least, the installer should *ask* if they want the shell profile modified.

**Comment by 23Skidoo** [comment]
> At the very least, the installer should ask if they want the shell profile modified.

That's how `opam setup` does it.

**Comment by snoyberg** [comment]
Check out issue #3232 and PR #3234, it will hopefully achieve similar goals

**Comment by mgsloan** [comment]
Closing, seems likely this is resolved.
