### ISSUE TITLE
Add commands for automating stack.yaml management

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#115]
Originally discussed in #27. Exact requirements here are uncertain, some ideas:
- Upgrade to a new snapshot
- Prune the extra-deps
- Add an extra package to the list of packages (and remove one?)
- Use a dependency solver to automatically add necessary extra-deps

**Comment by chreekat** [comment]
+1 for easy way to upgrade snapshot (and probably extra-deps at the same time). Looks like the current way to do it is 
* move stack.yaml
* (re)run stack build/init (if/when init exists) — which should not fare very well
* see if any extra-deps have made it into the new snapshot
* manually check the extra-deps to see if any newer versions are available
* merge the old stack.yaml into the new one

Lots of hairballs there.

**Comment by rvion** [comment]
+1, I find myself doing naively the same as @chreekat for now

**Comment by snoyberg** [comment]
Following #390: running `stack config set resolver nightly` should set to the newest nightly. Other similar kinds of shortcuts should be allowed too (e.g., lts-2 for newest LTS 2.x).

**Comment by alanz** [comment]
Would `stack config set resolver nightly` update the per-project config or the global (on a given machine) config?

Because if the latter, it makes it simple to move a given dev environment as a whole onto a different snapshot/nightly.

**Comment by snoyberg** [comment]
I think it would do both: `stack config` should work the same way as `stack exec`/`stack ghci`, using a local project config if available, otherwise falling back to the default global (aka `ExecStrategy` in the code base). Thanks for pointing out this requirement.

**Comment by ekmett** [comment]
:+1: I just found myself in the situation of needing some form of `stack config set resolver nightly` that doesn't involve a hack that goes and retrieves the current version from the json document and found my way to this ticket.

**Comment by drwebb** [comment]
`stack config set resolver <snapshot>` is currently in master. There is another branch where I am adding `stack config add extra-dep <packagename>-packagever [--suggested]`. It would be great to have more generic add and sets, but it's easier to just add in special cases for the %80 of actual uses.

**Comment by harendra-kumar** [comment]
Something that may be relevant to this discussion - [augeas] (http://augeas.net/) is a nice tool to manipulate config files in a generic way. One can write a augeas lens for stack.yaml to be able to manipulate it via augtool. This can be handy to manipulate stack.yaml through scripts. I could find one example of a YAML lens on my debian jessie linux installation - `/usr/share/augeas/lenses/dist/cobblersettings.aug`. May be a good idea to adapt that to `stack.aug` if anyone is interested. 

If we ship the lens with augeas then it will provide anyone the ability to manipulate stack configs via standard configuration management tools which support augeas. Not sure if that use case is useful for stack though.

**Comment by harendra-kumar** [comment]
The discussion in #1365 is related to this. Some `stack config` commands are proposed there as well.

**Comment by sjakobi** [comment]
> augeas is a nice tool to manipulate config files in a generic way.

One advantage of augeas would be that according to its [FAQ](http://augeas.net/faq.html):

> Augeas works very hard to preserve comments and formatting details such as the number of spaces used to separate fields etc. 

Augeas even has [Haskell bindings](http://hackage.haskell.org/package/augeas) although these have not been updated since 2012.

It seems though that augeas is Unix-only, so any use of augeas, whether via the bindings on by providing lenses for use with augtool, would exclude Windows users.

**Comment by mgsloan** [comment]
It does seem that an augeas port to windows may be within reach.  This branch is a bit behind, but sounds promising: https://tickets.puppetlabs.com/browse/PUP-4971 https://github.com/MikaelSmith/augeas/tree/windows

I haven't worked with augeas, but I am certainly in favor of such re-use when it's possible and it works well.  On the other hand, refactoring yaml is an interesting problem to me, that I wouldn't mind having a swing at it (readers, feel free to leave a comment here and have a swing at it too!).

**Comment by snoyberg** [comment]
I think we've implemented as much of this as desired for now. New requests can go into new issues.
