### ISSUE TITLE
stack new template complete with tests *and* benchmarking

### ISSUE THREAD

**Issue by codygman** [commercialhaskell/stack#1153]
I believe it would be very useful for newcomers wanting to create a library to have all of this setup by default.

I'm not sure if this is feasible since you might have to choose a specific testing framework or benchmark framework and as far as I can tell stack tries to remain agnostic.

**Comment by snoyberg** [comment]
Want to send a PR to the template on stack-templates?

**Comment by codygman** [comment]
Yeah, I'll take a stab at that as soon as I can get to it.

**Comment by borsboom** [comment]
I'll close this as it doesn't look like this needs anything to be added to Stack itself (just the template data).

**Comment by tfausak** [comment]
[My Haskeleton template](https://github.com/commercialhaskell/stack-templates/blob/336d2fce25e904b61b21f8960f0955aef7aab55f/haskeleton.hsfiles) has both a test suite and benchmarks.
