### ISSUE TITLE
Win32-extras needed on windows for git-annex

### ISSUE THREAD

**Issue by joeyh** [commercialhaskell/stack#1158]
git-annex is included in stackage, but it turrns out this didn't get Win32-extras included. git-annex only depends on that on windows, naturally.

This means stack build fails for git-annex on windows. Also had no luck with stack-solver.

It suggested I put Win32-extras in extra-deps, but I don't see a way to do that for only a single OS, so I don't think I can fix this in git-annex.

**Comment by snoyberg** [comment]
You can put it in the extra-deps, and it simply won't be used on other OSes.

In order to improve this situation going forward, it would be best to include that package in the build-constraints.yaml for Stackage, as well as in the skipped-builds section thereof (https://github.com/fpco/stackage/blob/master/build-constraints.yaml#L1665).

**Comment by joeyh** [comment]
Michael Snoyman wrote:
> You can put it in the extra-deps, and it simply won't be used on other OSes.

Huh, that's surprising.

> In order to improve this situation going forward, it would be best to include
> that package in the build-constraints.yaml for Stackage, as well as in the
> skipped-builds section thereof (https://github.com/fpco/stackage/blob/master/
> build-constraints.yaml#L1665).

Ok, but another case of the general problem is that git-annex needs
process-1.3.0.0 on windows, while older versions will work otherwise.
Don't know how this approach generalizes to deal with that..

-- 
see shy jo

**Comment by snoyberg** [comment]
It won't deal with that case, we don't support switching dependencies per
OS. You can use alternate stack.yaml files if you want.

The reason extra-deps work is that they are only compiled as needed. On
Linux and Mac, that dependency will never be demanded.

**Comment by joeyh** [comment]
Michael Snoyman wrote:
> It won't deal with that case, we don't support switching dependencies per
> OS. You can use alternate stack.yaml files if you want.

It would get messy; even with stackage nightly, adding a newer
process-version to stack.yaml leads to cabal hell.

So, I don't see how I can use stack for git-annex on Windows, at least
until I can get rid of the windows-specific version requirement.

-- 
see shy jo

**Comment by borsboom** [comment]
I don't think there's much we can do about needing a newer process than is included with GHC, since Stackage snapshots are fixed to the versions of packages included with GHC. You could try creating a custom snapshot for use with Stack on Windows.

**Comment by borsboom** [comment]
You'd still need a separate stack.yaml for Windows, of course, so a custom snapshot might not be much better than explicitly listing all the extra-deps in that stack.yaml.  We don't have any imminent plans to support conditionals in stack.yaml, but the idea could be considered someday, and a separate issue to discuss it might be appropriate.
