### ISSUE TITLE
Failed to get started, Failure when adding dependencies..

### ISSUE THREAD

**Issue by deflexor** [commercialhaskell/stack#1160]
After installation of stack I tried to install some packages needed for emacs haskell-mode:

`stack install happy hasktags stylish-haskell present ghc-mod hlint hoogle structured-haskell-mode hindent`

And got following error messages:

```
$ stack install happy hasktags stylish-haskell present ghc-mod hlint hoogle structured-haskell-mode hindent
Run from outside a project, using implicit global config
Using resolver: lts-3.9 from global config file: /home/dfr/.stack/global/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package atto-lisp in known packages

--  While attempting to add dependency,
    Could not find package cabal-helper in known packages

--  Failure when adding dependencies:    
      cabal-helper: needed (==0.6.* && >=0.6.0.0), not present in build plan (latest is 0.6.1.0)
    needed for package: ghc-mod-5.4.0.0

--  Failure when adding dependencies:    
      atto-lisp: needed (-any), not present in build plan (latest is 0.2.2)
    needed for package: present-2.2
```

**Comment by snoyberg** [comment]
There are two different problems:

1. ghc-mod is not present in LTS Haskell, which is the default snapshot used by Stack. You can either:
    * Switch to nightly with `stack --resolver nightly install ...`
    * Explicitly state that you want to pull in the latest `cabal-helper` also:

            stack install happy hasktags stylish-haskell ghc-mod hlint hoogle structured-haskell-mode hindent cabal-helper
2. The `present` package depends on atto-lisp, which has a restrictive upper bound on deepseq, making it incompatible with GHC 7.10. That's something that's been an open issue since April: https://github.com/nominolo/atto-lisp/issues/18

**Comment by deflexor** [comment]
Thank you for comprehensive answer.
