### ISSUE TITLE
Ctrl-C kills stack ghci when Docker is used

### ISSUE THREAD

**Issue by nh2** [commercialhaskell/stack#1163]
On Linux, when I'm in `stack ghci` in stack's Docker environment, it doesn't clear the line or cancel the currently running function as expected, but instead shuts down the Docker container (thus killing the ghci session).

This gives tough times for doing e.g. web development in ghci (you can't cancel the server and quickly reload).

Most likely this is related to `docker run` signal propagation (we already had to deal with some of that fun in #547), and its `-i` (`--interactive`), `-t` (`--tty`), and `--sig-proxy` flags.

**Comment by nh2** [comment]
Some more investigation:

* `docker run -t -i stack-full ghci` - Ctrl-C breaks ghci
* `docker run -t -i stack-full python` - Ctrl-C breaks python
* `docker run -t -i stack-full bash` - Ctrl-C does *not* break bash, it works as expected

It seems likely to me these interrupt problems are related to the entrypoint:

When I build a custom image based on Ubuntu that contains ghc (`docker run ubuntu:14.04`, `apt-get install ghc` inside there, `docker commit ghc [thatcontainer]`) and then `docker run -t -i ghc ghci` (or `python`) in there, I can Ctrl-C without problem, both ghci and python work as expected in there.

The entry point calls `phusion/baseimage`'s `my_init` (as @borsboom mentions in https://github.com/commercialhaskell/stack/issues/547#issuecomment-125787293), which might be the reason why our entry point breaks `ghci` and `python`.

But I don't understand why it doesn't break `bash`!

**Comment by borsboom** [comment]
Pretty sure this is issue is encompassed by #547, so closing.  I'll add a note there to ensure this case is handled.

**Comment by nh2** [comment]
Workarond for now:

* first run `stack exec -- bash`
* then inside run `stack ghci`

and you can Ctrl-C safely.

**Comment by borsboom** [comment]
FYI: this looks to be fixed in stack-0.1.8.0
