### ISSUE TITLE
InvalidProxyEnvironmentVariable in 0.1.5.0 (Ubuntu 15.04 Cntlm)

### ISSUE THREAD

**Issue by schernichkin** [commercialhaskell/stack#1165]
InvalidProxyEnvironmentVariable error when using proxy under Ubuntu 15.04 with Cntlm.

Steps to reproduce:
1. Install Cntlm, configure Ubuntu to use proxy using System Setting -> Network application.
2. Run command `stack new my-project`

Expected:
Except Stack will create new project.

Actual:
InvalidProxyEnvironmentVariable error.

Here is the `stack --version` output:
```
$ stack --version
Version 0.1.5.0, Git revision a30f022c3dca7c489e08f31908ea77c3bf305375 (2159 commits) X86_64
```

Here is the command I ran with `--verbose`:
```
$ stack new my-project --verbose
Version 0.1.5.0, Git revision a30f022c3dca7c489e08f31908ea77c3bf305375 (2159 commits) X86_64
InvalidProxyEnvironmentVariable "https_proxy" "https://localhost:3128/"
```

**Comment by snoyberg** [comment]
How did you get your `stack` executable? Is it one of the official
releases, or did you compile it yourself? If you compiled it yourself, did
you compile with Stack, or with cabal-install?

**Comment by schernichkin** [comment]
I followed instructions from: https://github.com/commercialhaskell/stack/blob/release/doc/install_and_upgrade.md#ubuntu for Ubuntu 15.04 (amd64)

**Comment by snoyberg** [comment]
There's currently no support in the http-client library for communicating with a proxy server over HTTPS, only over HTTP. Can you try changing the environment variable to `http://localhost:3128` and see if that works?

**Comment by schernichkin** [comment]
Yes it works. I woundering why it expect `https_proxy` to be `http://..`? For unsecured connections we have `http_proxy` which is `http://..` for secured `https_proxy` which is normally `https://..`

**Comment by snoyberg** [comment]
Because it's still connecting to the proxy server over an insecure connection, and then upgrading to a secure connection afterwards via a `CONNECT` interaction.
