### ISSUE TITLE
Do all-in-one package builds when there are no cyclic dependencies

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#1166]
Discussed with @mgsloan already. The current reason for this is dealing with code coverage better, but this should in general make Stack behave better for common cases. (@meteficha, you in particular will probably like this.)

Currently, Stack does a separate `cabal build` for the library/executables, tests, and benchmarks. The reason is *cyclic dependencies*: package B may depend on package A, while package A's test suite depends on package B. We want to tweak this as follows:

1. When there are cyclic dependencies: act just as we do today
2. Otherwise: force all test and benchmark dependencies (as requested) to be built before building a package, and then build all necessary components at once.

**Comment by meteficha** [comment]
Nice!  Just to make sure I understood the implications, the advantages are that:

  * There will be fewer dependencies between packages, thus more opportunity for parallelism.

  * Fewer `cabal build`s per package will mean less overhead.

Is that correct?

**Comment by snoyberg** [comment]
I don't know that (1) will happen; actually, the _opposite_ is likely true, though I'm not certain. The second is the real advantage (and avoiding some unfortunately Cabal cases with unnecessarily-overwritten cabal_macros.h).

**Comment by mgsloan** [comment]
I've resolved #1181 with a different approach, so this isn't so urgent.  It would be a nice optimization, though.

Almost humorously, the only way to work around a different --coverage issue is to build tests one at a time -  https://ghc.haskell.org/trac/ghc/ticket/1853#comment:23 (tl;dr; there are problems getting coverage for modules built directly into an executable, when there are multiple executable stanzas).

**Comment by mgsloan** [comment]
While working on this, I had a thought: wouldn't it be consistent to also allow executable components depend on some package which depends on the library?  I think supporting cabal stanzas in a uniform way will help clarify the code.

So far, I'm having some trouble with refactoring the code to add this feature in a nice way.  I think a large-ish restructure is in order, both to clarify things and to enable this change.  The main thing I'd like to change is to improve how the build steps are represented, and clarify which components will be built.

First off, here are some notes about how things currently work:

* [The `Package` type](https://github.com/fpco/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Types/Package.hs#L79) sets `testEnabled` / `benchEnabled` based on whether these are part of the configuration - [here](https://github.com/fpco/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Package.hs#L714). The purpose of this seems to be to affect the results of [allBuildInfo'](https://github.com/fpco/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Package.hs#L447), and so affect the results of querying the package's dependencies (`packageDependencies`, `packageToolDependencies`, `packageDescTools`).  So, this also affects the population of the `packageDeps` field.

* [`loadLocalPackages`](https://github.com/fpco/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Build/Source.hs#L287) is where things get tricky.  Here's what happens:

  - We write down a `Just` value for the `lpExeComponents` if the package is a build target.  I think this applies even if there isn't an exe component, and it's just a library.  lpExeComponents is used in the following ways:

    - If it or `lpTestBench` is set, then [it's a wanted package](https://github.com/fpco/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Types/Package.hs#L233)

    - If it's set, then `constructPlan` [will plan to build it as a normal task](https://github.com/fpco/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Build/ConstructPlan.hs#L143)

    - The components get provided to `cabal build` during execution, [here](https://github.com/fpco/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Build/Execute.hs#L999).  The `Nothing` case is confusing to me, I'm not sure which circumstances it happens.

  - `lpTestDeps` is set to the dependencies of the tests, similarly for `lpBenchDeps`.  This is used to determine whether we should enable tests even when not building them, to avoid reconfigure (and probably avoid writing cabal_macros.h again)

  - `lpTestBench` is set to a package which is configured with all, but it is only a `Just` if there are any tests or benchmarks that are targets.  It is a `LocalPackageTB`, which stores a `Package` along with the set of tests and benchmarks that are targets.

In all, this feels like a lot of in flight, and a lot to understand while reading the code for package execution.  How about restructuring things like this:

- Don't have `singleBuild` / `singleTest` execute build actions.  Instead, each element of `planTasks` specifies that a particular set of package components to be built.  A package will either be built all in one `Task` or be split into two: one for the Lib, and one for the rest of the components.

- Have the `final` actions just store enough info to run the test or benchmark.

- This may also allow us to address [this TODO](https://github.com/fpco/stack/blob/193b285e0dc8fd705a7d2475e5a57bb15f4a9990/src/Stack/Build/Execute.hs#L993)

**Comment by mgsloan** [comment]
Done!
