### ISSUE TITLE
Fast way to get GHC version for a given project

### ISSUE THREAD

**Issue by DanielG** [commercialhaskell/stack#1169]
I would like to be able to check the GHC version a given stack project is using in ghc-mod, but `stack exec -- ghc --numeric-version` takes around 100ms on my machine which is quite a lot of latency for an action that we will have to run on every command (for the non daemon version of ghc-mod). I think stack should already know internally which GHC version it's going to use given a project's resolver so adding a command to print this should be really easy, right?
 
Also is there a way to print a list of known resolver versions and the corresponding GHC versions?

**Comment by snoyberg** [comment]
The reason this is taking 100ms is actually necessary most likely: Stack has to:

1. Check for GHC on the PATH
2. Ask that GHC to report its version
3. If no GHC is found, or the GHC doesn't match:
    a. Search its internal installed GHC list for a match
    b. Optionally perform the numeric-version sanity check on it

You may say "but we already know the exact version of GHC we're going to be using!" But that's not actually true: we know the version of GHC that was used to build the snapshot, but users have control over tweaking that to allow for newer GHC minor versions, patch releases, or even completely different versions. This full check is the only way to be certain what the user is going to be using.

**Comment by DanielG** [comment]
I had a feeling there might be more to it, thanks for the explanation.
