### ISSUE TITLE
Store "stack-path" files in directories that have been shortened with SHAs

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1173]
The resolution for #1145 / #1027 is to replace some long paths with 8 character SHAs on windows, due to the MAX_PATH limitation.  It would be good to store a file, maybe called `SHA/stack-path`, with the path that would have been used in place of the SHA.  This is useful for a variety circumstances:
- If a user is curious what's in the directory.
- If garbage collection gets implemented at some point. (https://github.com/commercialhaskell/stack/issues/133)
- It will allow SHAs to also be used for snapshot dependencies.  The contents of the snapshots folder is scanned and parsed as part of `stack init` - https://github.com/fpco/stack/blob/master/src/Stack/Init.hs#L229

It gets a little bit tricky to ensure that every possible execution involving these paths will also create the `path` file, though. These paths are used in quite a few places, and often they get created be external tools.

/me shakes fist menacingly at MAX_PATH

**Comment by drbo** [comment]
Another solution is to do [what CoreCLR is doing](https://github.com/dotnet/corefx/pull/3001) &ndash; have GHC implicitly use extended paths.

**Comment by mgsloan** [comment]
> It gets a little bit tricky to ensure that every possible execution involving these paths will also create the path file, though. These paths are used in quite a few places, and often they get created be external tools.

I'm thinking that the solution here is to have an in-memory cache of whether a particular `path.yaml` file has been written - something like `Set (Path Abs Dir)`.  Then we can just check this cache each time the paths are used.  While this is slightly less efficient than statically knowing when to initialize these `path.yaml` files, it also seems less error-prone.

Creating these `path.yaml` files also means creating the folders.  This means that functions like `installationRootLocal`, `installationRootDeps`, and `distRelativeDir` will have the side effect of creating the folders, when on windows.  This seems relatively benign to me, but I think it makes sense to also create the folders on linux, for the sake of consistency.

**Comment by snoyberg** [comment]
Moved to wishlist: https://github.com/commercialhaskell/stack/wiki/Wishlist
