### ISSUE TITLE
Appveyor builds failing misteriously/timing out?

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stack#1176]
The README shows a "build failing" badge for AppVeyor.

I looked into the logs, but I see no obvious recent genuine failure. [The](https://ci.appveyor.com/project/snoyberg/stack/build/1.0.156) [latest] (https://ci.appveyor.com/project/snoyberg/stack/build/1.0.155) [builds](https://ci.appveyor.com/project/snoyberg/stack/build/1.0.154) are confusing — two time out, only the third shows [a possible genuine failure](https://ci.appveyor.com/project/snoyberg/stack/build/1.0.154#L216), and ends with "Connection started reconnecting before invocation result was received".

(I'm no Windows user, but I was surprised to find no issue on these failures).

**Comment by j-a-k** [comment]
I've used appveyor for a little haskell project and have the following observation:

1) the console log does not show all errors, you have to look at the messages tab for some of them, but as far as I can see this only gets used if you are using the build script part which stack doesn't, it might be worth splitting the build and test steps to aid in diagnostics?

2) I tried to get caching of stack to work in a similar way to stacks appveyor.yml but have never succeeded as the stack folder always seems to be larger than the limit they allow you to cache (100 MB) this could be the cause, though this does appear in the log when on my project

3) the stack appveyor.yml seems to download 7z, but that shouldnt be necessary as 7z is part of the appveyor environment anyway (this is just uneccessary rather than a fault)

**Comment by borsboom** [comment]
The badge seems to show "failing" even though the project appears to build successfully on AppVeyor right now.  @snoyberg, I don't seem to have admin access to the project on AppVeyor, so I can't look into this further.  Can you give me access?

**Comment by snoyberg** [comment]
I can't figure out how to share permissions on Appveyor, but I've updated the badge URL, which seems to have fixed things.

**Comment by borsboom** [comment]
The [latest AppVeyor build](https://ci.appveyor.com/project/snoyberg/stack/build/1.0.278) appears to complete in the log, but then in the Messages tab says

> Build execution time has reached the maximum allowed time for your plan (60 minutes)

and appears to have hung on "Updating build cache".

Looking at the history, I'm also seeing some failures due to this message:

> Connection started reconnecting before invocation result was received.

Does anyone have any idea what that means?  I think both of these messages come from AppVeyor itself (I don't see the strings anywhere in Stack's codebase).

**Comment by borsboom** [comment]
@snoyberg Have you tried disabling the cache in `appveyor.yml`?  Ugh, I hate to see it have to install GHC and build all the dependencies for every run though.

**Comment by snoyberg** [comment]
I haven't tried it; do you want to try pushing a commit and see what
happens?

**Comment by borsboom** [comment]
Since disabling the AppVeyor cache, it's been "all green" on master.

**Comment by domenkozar** [comment]
Not sure if this is related, but we've been seeing stack build failures with cache like: https://ci.appveyor.com/project/jagajaga/pos-haskell-prototype/build/1.0.648

**Comment by Blaisorblade** [comment]
@domenkozar While that build looks complex, my first (educated) guess from the logs is that some Template Haskell custom build steps (which are clearly there) produce build outputs outside the cache, the cached build doesn't rebuild those build outputs (probably because *other* build outputs are indeed found in the cache), so the build fails. I can't investigate more, but maybe that helps you take a look? It's not clear what Stack might be doing wrong, and it seems more likely the custom build steps and the caching don't integrate well. I might well be wrong, and a minimization would help.

Evidence: Such an uncached build product is `C:\projects\pos-haskell-prototype\stdlib.pls`, mentioned by this log entry:

> [00:04:24] Warning: qAddDepedency path listed in C:\projects\pos-haskell-prototype\.stack-work\dist\b7fec021\build\src\Pos\Script.dump-hi does not exist: C:\projects\pos-haskell-prototype\stdlib.pls

`stdlib.pls` appears a build product because it isn't in the GitHub repo, and it isn't going to be cached. Fixing this involves caching such build products and/or fixing the build steps to create build products elsewhere.
The message says that cached files depend on it? In particular, the Template Haskell run while compiling `src\Pos\Script.hs` called `qAddDepedency` (ahem, `qAddDependency`) to inform GHC that if `stdlib.pls` should change, then `src\Pos\Script.hs` should be recompiled.
But I am not sure what code is creating that. https://github.com/input-output-hk/pos-haskell-prototype/blob/master/src/Pos/Script.hs#L128-L131 is probably involved. Wild guess: purescript-bridge might be involved too.

I've also been unable to understand where `Interface.Prelude` should come from (already searched Hayoo), which is bad since it's the source of the actual error:
> [00:04:23] C:\projects\pos-haskell-prototype\src\Pos\Script.hs:29:1: error:
[00:04:23]     Failed to load interface for `Interface.Prelude' 

---


Also of note (not sure for whom), this is looking for a file that probably exists, but isn't found because of the wrong path. This appears unrelated to the actual failure but problematic:
> Warning: Can't find file "C:\Users\appveyor\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\lib/include\ghcversion.h" in directories

I guess that file exists because of these entries:
> [00:02:07] Processing archive: C:\Users\appveyor\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1.tar
> [...]
> [00:02:14] Extracting  ghc-8.0.1\lib\include\ghcversion.h

**Comment by Blaisorblade** [comment]
> I've also been unable to understand where Interface.Prelude should come from (already searched Hayoo), which is bad since it's the source of the actual error:
> ```
> [00:04:23] C:\projects\pos-haskell-prototype\src\Pos\Script.hs:29:1: error:
> [00:04:23] Failed to load interface for `Interface.Prelude'
> ```

So I must partially retract: `Interface.Prelude` comes from `plutus-prototype` (https://github.com/input-output-hk/plutus-prototype) which is regularly declared as a dependency. So `Interface.Prelude`'s interface file should be part of the cache. I'm confused 😞

**Comment by domenkozar** [comment]
@Blaisorblade for the record, there were other issues like https://ci.appveyor.com/project/jagajaga/pos-haskell-prototype/build/1.0.622 and the build did manage to succeed sometimes.

After appveyor caching was removed, build works reliably now.

**Comment by domenkozar** [comment]
@Blaisorblade should we reopen this or create a new issue?

**Comment by Blaisorblade** [comment]
@domenkozar Right — I'd say a separate issue (linking to this), since the relation is unclear...

**Comment by domenkozar** [comment]
Will do. If someone is available to look into this issue (paid), contact me please at domen@enlambda.com

**Comment by Blaisorblade** [comment]
@domenkozar I lack the time for this, so for paid support you might want to contact https://www.fpcomplete.com/...

**Comment by domenkozar** [comment]
@Blaisorblade just for the record, I've tracked down warning and reported it upstream: https://ghc.haskell.org/trac/ghc/ticket/13166
