### ISSUE TITLE
stack build fails with `streamingProcess: runInteractiveProcess: pipe: resource exhausted (Too many open files)`

### ISSUE THREAD

**Issue by wereHamster** [commercialhaskell/stack#1177]
I updated the resolver in my stack.yaml from nightly-(~3 days ago) to nightly-(today) and then running `stack build` failed with:

```
/.../ghc-7.10.2/bin/ghc-pkg: streamingProcess: runInteractiveProcess:
  pipe: resource exhausted (Too many open files)
```

When that happened the progress was at 88/128, stack was mostly copying precompiled packages, just one had to be recompiled up until that point.

The exact same message repeated two more times and then I was dropped back to the shell. Running the same stack command again allowed the build to succeed.

**Comment by snoyberg** [comment]
What's your open file descriptor limit?

**Comment by wereHamster** [comment]
soft 256, hard unlimited -- the default on Mac OS X

**Comment by snoyberg** [comment]
There's likely nothing we can do about this. 256 is a relatively low open FD limit, I'd recommend raising it. Since this issue is solved by rerunning, any objection to closing?

**Comment by borsboom** [comment]
Haven't heard back, so closing.

**Comment by tfausak** [comment]
I know this is an old issue with an easy workaround, but is there any way to fix this? It seems silly to fail with the default settings on OS X when changing the resolver.

**Comment by mgsloan** [comment]
@tfausak Not as far as I know, sorry.  Seems silly for OS X to have such a low limit

**Comment by heroxbd** [comment]
No, it is not only OS X.  Under GNU/Linux, compiling with -j128, I run out of file descriptors.
