### ISSUE TITLE
Add `stack build` options to `stack ghci`?

### ISSUE THREAD

**Issue by danclien** [commercialhaskell/stack#1186]
It looks like a `stack ghci` will invoke a `stack build` without any addition options? 

I normally build with `stack build --executable-profiling`. When I run `stack ghci`, it has to unregister everything in my local database and rebuild everything without profiling. 

Would it be possible to add the options from `stack build` to `stack ghci`? I'm currently running v0.1.6.0 (e22271f5ce9afa2cb5be3bad9cafa392c623f85c, OS X x86_64).

**Comment by bergmark** [comment]
#971

**Comment by mgsloan** [comment]
This is a good idea!  It would also be good to have `stack ghci` follow `stack build`'s convention of defaulting to only building libraries and executables - see this comment https://github.com/commercialhaskell/stack/issues/817#issuecomment-132345231.

**Comment by borsboom** [comment]
Yeah, I agree.  Becomes even more relevant with #1228.

**Comment by mgsloan** [comment]
I'm going to go ahead with this, but not looking forward to what it will do to `stack ghci --help` (See #1333)

**Comment by mgsloan** [comment]
@danclien This is now implemented!

**Comment by danclien** [comment]
Awesome. Thank you so much!
