### ISSUE TITLE
Ignore cabal_macros.h as a dependency

### ISSUE THREAD

**Issue by lukexi** [commercialhaskell/stack#1195]
As Michael says in #1134:
> Also somewhat tangential, but: we may want to always ignore cabal_macros.h as a dependency. That file should only change meaningfully when our configure options have changed, and therefore recompiles triggered by that file should be meaningless.

I seem to get endless spurious rebuilds of my local packages due to cabal_macros.h — nearly every time I make a change. If I run stack build a few more times it eventually settles down.

It's of course particularly pernicious when the cabal_macros.h change is detected in package A, which is depended upon by B C D E F, yet I'm only actually making changes in package G that depends on all of the above.

**Comment by snoyberg** [comment]
PR was merged, closing. Thanks!
