### ISSUE TITLE
Executables with the same names from different projects are clobbered

### ISSUE THREAD

**Issue by jberryman** [commercialhaskell/stack#1198]
```
» stack --version
Version 0.1.5.0 X86_64
```

We have a `stack.yaml` starting like:

```
flags: {}
packages:
- foo/
- bar/
- baz/
```

It appears that if both `foo/foo.cabal` and `bar/bar.cabal` have an executable of the same name, with a section

```
executable some-exec
   ...
```

That the built executables in e.g. `.stack-work/install/x86_64-linux/lts-3.3/7.10.2/bin/` will be clobbered by whichever executable was just build. 

This should perhaps be a warning, or executables should be placed in sub-directories.

**Comment by borsboom** [comment]
I think a warning would be appropriate.  Putting them in separate sub-directories still wouldn't help the `stack exec some-exec` case, since all the subdirectories would have to be on the PATH for `stack exec`.    A pull request would be welcome.

**Comment by sjakobi** [comment]
I'm working on this on my [`1198-warnings` branch](https://github.com/sjakobi/stack/commits/1198-warnings).

I have added a warning to the `stack init` command and would add another one for `stack build`.
Does this sound about right?

Regarding the warning during `init`: Should we recommend renaming the executables or simply point out the problem?

**Comment by mgsloan** [comment]
Cool, looks good to me so far!  Yes, warning on `stack init` and `stack build` should be sufficient.

I'd say it's reasonable to mention that renaming one of the executables is the way to resolve the problem.
