### ISSUE TITLE
Can't use docker to build for centos6 (gmp4)

### ISSUE THREAD

**Issue by madjar** [commercialhaskell/stack#1209]
Hello

I'm trying to build for a centos6 from a machine with a more recent gmp, and I though I could use docker for that. However, I can't find a way to make a working image.

I tried this naïve approach:

```
FROM centos:6.6

RUN curl -sSL https://s3.amazonaws.com/download.fpcomplete.com/centos/6/fpco.repo | tee /etc/yum.repos.d/fpco.repo
RUN yum -y update && yum -y install stack
```
but it the `stack build` command fails with
```
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?
```

Also, I can't seem to find how the original docker images are created, so I have no idea how they should actually be built.

How could I build a working image based on centos6 ?

Thanks a lot

**Comment by borsboom** [comment]
That looks more like an issue with your `stack.yaml` that anything related to Docker.  Are you just running `stack` within a Docker container?  If so, it's no different than running it on any other machine or VM.

**Comment by madjar** [comment]
Sorry, that wasn't clear. I'm trying to use the stack docker support, but with a centos6-based image (in order to build binaries for centos6 systems).

When I run `stack build` with this `stack.yaml`, it works like a charm:
```
packages:
- '.'
extra-deps:
- reactive-banana-0.9.0.0
resolver: lts-3.10
docker:
  enable: true
```

However, if I try to use the docker image that I built with the Dockerfile show before, I get the error I mentioned.
```
packages:
- '.'
extra-deps:
- reactive-banana-0.9.0.0
resolver: lts-3.10
docker:
  enable: true
  #image: "stack-centos6"
  #stack-exe: image
```

I have no troubles building withing the container, but I hoped I could use stack's docker support to make it more straighforward.

**Comment by borsboom** [comment]
There are various reasons why that isn't going to work right now.  Currently `stack` has some specific requirements of images which mean that, practically, they need to be derived from the images we're providing, which are of course not CentOS 6.x-based (#531 will fix that, and work on that has begun).  In addition, the stack executable bind-mounted from the host won't work on CentOS 6.x (though you could use the `stack-exe` option to override that).  I'd suggest not trying to use Stack's Docker integration in this case, and just run `stack` in a container manually (e.g. `docker run <options> <image> stack build`).

**Comment by borsboom** [comment]
I see you already figured out the `stack-exe`, but the other point (which is harder to overcome) still stands.  Stack has very specific requirements for what the entrypoint in the image does, so it may be possible to pull the entrypoint from our images and then adapt it to CentOS, but it's probably not worth it.

**Comment by madjar** [comment]
Okay, thanks a lot for the explanation and the suggestion. Should I close the issue?
