### ISSUE TITLE
no underscore in names allowed 

### ISSUE THREAD

**Issue by rwobben** [commercialhaskell/stack#1219]
Hello, 

When I try something like stack new project-1 or stack new project_1 I see a message that the name is not allowed. 

Expected valid package name, but got: project-1

Is it possible that _ or - are allowed in packagenames.

**Comment by mgsloan** [comment]
Yes, package names are just letters, numbers, and `-`.  However, it looks like the first character after `-` must be a letter: https://github.com/fpco/stack/blob/4797dedd12aedc661697625549c52de8d335ffaf/src/Stack/Types/PackageName.hs#L90 .  If `project-1` was a valid package name, then in some places it would erroneously be parsed as the package name `project` with version `1`.
