### ISSUE TITLE
stack runghc - ambiguous module (or, how to run tests quickly)

### ISSUE THREAD

**Issue by dbp** [commercialhaskell/stack#1220]
I'm not sure exactly what the solution is to this (it may not be `runghc`), but here is the problem:

`stack test` takes a _long_ time to run tests, because it reconfigures, builds and installs the whole package (including the test Main) before running the test suite. On a tiny project, I made a whitespace change to the test file (no changes to the rest of the code) and it took 11.5 seconds to run (with no changes it takes 1.3 seconds, though some of that is still stack - the actual tests take a fraction of a second). 

This isn't particular to stack - it's also how `cabal test` works. So in the past, instead of actually using `cabal test` on a day-to-day basis, I would instead run `runghc -isrc path/to/test/main.hs` (or cabal exec, etc). This runs incredibly fast. Obviously this doesn't work when dependencies are missing, etc, but of the hundreds of times a day I run tests, very few (if any) actually require any change to packages! (and CI still runs `cabal test` or now, `stack test`).

I tried running `stack runghc -- -isrc path/to/test/main.hs`, but it look like the packge db it is using isn't right, or something - I end up getting:

```
src/Application.hs:18:8:
    Ambiguous module name ‘Data.Pool’:
      it was found in multiple packages:
      resource-pool-0.2.3.2@resou_07WWhNMBPs8Ihbjf6mIyPw resource-pool-catchio-0.2.1.0@resou_8G9WFKh0acxJ37iDpVihQy
```

I assume that mean that not enough of the package information that stack has is being passed in. Is there a way to do what I want currently, or is that something that `stack runghc` can gain as an ability (or maybe even better, to have some flag to `stack test` that skips all of the setup and just tries to evaluate the main file as quickly as possible).

**Comment by borsboom** [comment]
`stack runghc` doesn't take into account any dependencies specified in .cabal files, so I don't think it could solve this automatically.  I can think of a couple of ways around this:

1. Use GHC's `-hide-package` argument.  E.g.:

    ```
    stack runghc -- -isrc -hide-package=resource-pool-catchio path/to/test/main.hs
    ```

2. Use qualified imports.  E.g, in `main.hs`:

    ```
    {-# LANGUAGE PackageImports #-}
    import "resource-pool" Data.Pool
    ```
