### ISSUE TITLE
Failed to load interface for 'Prelude' when invoking GHCi with test target

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#1222]
I'm trying to switch to Stack completely and so I need to use it to run REPL. As I understand `stack ghci` is the correct command for this. I have a project with a library, two test suites and a benchmark. This command works OK:

```
$ stack ghci myproject:lib --no-load
```

Then I can use `:m` to load file of interest (otherwise all modules are loaded at once, given that some of them are intended to be imported qualified, it's not what I usually want). However, when I need to work with tests, I get this:

```
$ stack ghci myproject:test:mytestsuite --no-load
Using main module: Package `mypackage' component test:mytestsuite with main-is file: /some/path/here
Configuring GHCi with the following packages: myproject
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help

<interactive>:1:1:
    Failed to load interface for ‘Prelude’
    It is a member of the hidden package ‘base-4.8.1.0’.
    Use -v to see a list of the files searched for.
```

How is that? The test suite specifies `base >= 4.6 && < 5` in Cabal file, so it cannot be hidden. I would normally think that this is sort of problem with my configuration, but `stack test` and other commands work fine.

**Comment by mrkkrp** [comment]
Living without REPL sometimes can be quite painful. Is there something I can do to use REPL with non-default build target?

**Comment by mgsloan** [comment]
@mrkkrp I figured that your repro case is `stack ghci megaparsec:tests`.  That should indeed work.  I fixed 3 things and now it does :D

**Comment by mrkkrp** [comment]
@mgsloan, It works now! Thank you very much.

**Comment by mac10688** [comment]
I have the same issue. How did you upgrade your version of stack? I did "stack upgrade" but it said I'm at the latest. I have a workaround for now. I just ":l test/test.hs", but it would be nice to just load my test suite directly.

**Comment by mgsloan** [comment]
@mac10688 `stack upgrade --git` to get the latest development version.
