### ISSUE TITLE
Coverage report doesn't consider any code

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#1224]
Previously with the same Cabal file I could get coverage report using Cabal. With Stack I'm getting:

> Error: The coverage report for myproject's test-suite "tests" did not consider any code. One possible cause of this is if your test-suite builds the library code (see stack issue #1008). It may also indicate a bug in stack or the hpc program. Please report this issue if you think your coverage report should have meaningful results.

I think it should. GHC options are identical for all components of my package. There is no need for test suite to rebuild the library. After all, if Cabal can generate the report, Stack should be able to do it given the same Cabal config or am I mistaken?

**Comment by mrkkrp** [comment]
Related: commercialhaskell/stack#1181.

**Comment by mrkkrp** [comment]
```
$ stack --version
Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64
```

Here is real Cabal file I'm working with: https://github.com/mrkkrp/megaparsec/blob/master/megaparsec.cabal

I tried to make all flags the same to avoid possible recompilation, then rebuilt, re-tested it and result is the same. I've tried everything, it doesn't work.

**Comment by mgsloan** [comment]
Coverage has changed quite a bit / had a couple fixes applied since v0.1.6.0.  In particular:

* https://github.com/commercialhaskell/stack/commit/cfa0c850daae6a04a349be72c5132f852c3bac6d
* https://github.com/commercialhaskell/stack/commit/7888313565865138f36e6e5488e7e475355a51ad

So, this should work on stack HEAD (use `stack upgrade --git` to install it)

**Comment by mrkkrp** [comment]
@mgsloan, No success, I'm seeing the same error. I've updated `stack` (now it's `Version 0.1.7.0, Git revision 33462aba13f85a3d5c1690c6ee0bb3dd4af6b616 x86_64`) but result is the same. I also updated `hpc`. Anyway, thanks for your reply.

**Comment by mrkkrp** [comment]
@mgsloan, After some editing of source code of the test suite it now works! Might it be the case that my editing triggered some sort of re-caching or something? This seems to work now. I'll experiment more to confirm that the result is reproducible from now on. Thank you again.

**Comment by mrkkrp** [comment]
Yes, this is resolved. Closing.
