### ISSUE TITLE
ghcjs setup fails on Windows; ghcjs-boot patches not applied?

### ISSUE THREAD

**Issue by conklech** [commercialhaskell/stack#1233]
Cross-posting with ghcjs/ghcjs#435 because I don't know which side this problem comes from.

With the following in `stack.yaml`,

```
resolver: lts-3.10
compiler: ghcjs-0.1.0.20150924_ghc-7.10.2
compiler-check: match-exact
```

and the following stack version:

```
c:\Projects\reflex-todomvc>stack --version
Version 0.1.7.0, Git revision ac6c9e12816b9b6db488e40d02a6b55f94b3b7f1 (2407 commits) x86_64
```

and node.js installed, `stack setup` chugs along merrily all through building ghcjs and through part of ghcjs-boot. But it fails to build `ghc-prim`, as follows:

```
Configuring ghc-prim-0.4.0.0...
setup.exe: cmp: does not exist
Failed to install ghc-prim-0.4.0.0
cabal.exe: Error: some packages failed to install:
ghc-prim-0.4.0.0 failed during the building phase. The exception was:
ExitFailure 1
ghcjs-boot.exe: error running: C:\Users\chris\AppData\Roaming\stack\snapshots\723c816e\bin\cabal.exe --config-file C:\Users\chris\AppData\Roaming\ghcjs\x86_64-mingw32-0.1.0.20150924-7.10.2\ghcjs\cabalBootConfig install ./boot/ghc-prim --solver=topdown --configure-option=--with-gmp-includes=C:\Users\chris\AppData\Roaming\ghcjs\x86_64-mingw32-0.1.0.20150924-7.10.2\ghcjs\ghcjs-boot\boot\integer-gmp\gmp\intree\include --configure-option=--with-intree-gmp --global --ghcjs --one-shot --avoid-reinstalls --builddir dist --with-compiler C:\Users\chris\AppData\Local\Programs\stack\x86_64-windows\ghcjs-0.1.0.20150924_ghc-7.10.2\src\.stack-work\install\d8e26a87\bin\ghcjs.exe --with-hc-pkg C:\Users\chris\AppData\Local\Programs\stack\x86_64-windows\ghcjs-0.1.0.20150924_ghc-7.10.2\src\.stack-work\install\d8e26a87\bin\ghcjs-pkg.exe --prefix C:\Users\chris\AppData\Roaming\ghcjs\x86_64-mingw32-0.1.0.20150924-7.10.2\ghcjs --enable-documentation --haddock-html --haddock-hyperlink-source --enable-library-profiling --disable-executable-stripping --disable-library-stripping
exit status: 1
stderr: Warning: No remote package servers have been specified. Usually you would have
one specified in the config file.

boot\ghc-prim\dist\setup\setup.hs:19:1: Warning:
    Module `System.Cmd' is deprecated: Use "System.Process" instead
setup.exe: cmp: does not exist
cabal.exe: Error: some packages failed to install:
ghc-prim-0.4.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

The `Setup.hs` for `ghc-prim` is trying to call out to the program `cmp`, which doesn't exist on Windows. But from my cursory search, it looks like that system call [should be patched out via ghcjs-boot's ghc-prim.patch](https://github.com/ghcjs/ghcjs-boot/blob/01e813ff1ae58fe445fdb9fb3aa27daf100fdec0/patches/ghc-prim.patch#L73-L85). I guess that patch isn't being applied?

Let me know if you need more details. As I mentioned, this is cross-reported upstream; I'll make a note here if it's an upstream problem.

**Comment by conklech** [comment]
It looks like we're getting the patches from the `old-base-ghc-7.10` branch of `ghcjs-boot`, which doesn't have the patch to remove the `cmp` call. Details in the other issue.

**Comment by mgsloan** [comment]
I'm inclined to resolve this by waiting for a proper release of GHCJS.  This is just a pre-release.

**Comment by borsboom** [comment]
Let's close this for now assuming it will be resolved by a proper release of GHCJS.
