### ISSUE TITLE
Binary upgrade code path

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#1238]
- [ ] Add a new option for the `stack upgrade` command, `--binary`, that will download the latest binary version from the Github release (`--no-binary` will also be available)
- [ ] When compiling official releases, have some flag that indicates that this is an official release
- [ ] When using an official binary release, `--binary` is on by default. Otherwise, it's off by default.

**Comment by Blaisorblade** [comment]
- [ ] Show the "official release" flag in `stack --version`, as suggested by https://github.com/commercialhaskell/stack/issues/2222#issuecomment-234030699.

**Comment by borsboom** [comment]
Bumped priority of this in light of planning to stop maintaining Linux APT/YUM repos.
