### ISSUE TITLE
Add `stack runhaskell`

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1241]
As an alias for `stack runghc`. I keep mistyping it, and both are valid GHC supplied binaries.

**Comment by borsboom** [comment]
We're mostly sticking with using `ghc` in the subcommand names (e.g. `stack ghci` instead of `stack repl`, etc.).   That said, no real objection to adding the alias.  A PR would be welcome.

**Comment by ndmitchell** [comment]
Note that repl is a bad name since it isn't a GHC command, while runhaskell is a GHC command and has been for many years (however, for cabal compat, repl is probably useful)

**Comment by rvion** [comment]
I also think stack repl is a good idea, both for discoverability and cabal compatibility

**Comment by rubik** [comment]
The PR has been merged, this should be closed.

https://github.com/commercialhaskell/stack/commit/dd554f5fc337dd7c98b4036d335d84f0c8943f13
