### ISSUE TITLE
Have "stack ghci" ignore build errors

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1249]
While trying out the repro for #1067, it failed to find the autogenerated Paths_ghcid.  This was because of two things:

1) The resolution of #817 was to not do a build if there are no explicit targets.  I don't think this is the right solution to the problem, and it makes the behavior of `stack ghci` inconsistent.

2) The resolution of #810 was to only build the dependencies.  I don't think this is the right solution to the problem, because if the project has never been built then autogenerated modules won't exist.

I think the solution is to remove the changes from #817 and #810 and instead adopt the following resolution:

Ignore build errors which occur during the implicit build which comes before running ghci.  This will consist of catching `ExcecutionFailure` exceptions, [thrown from here](https://github.com/fpco/stack/blob/c9b040376c7e35724907d9476aac841f05e2289b/src/Stack/Build/Execute.hs#L504), and warn the user that the errors were ignored.

**Comment by borsboom** [comment]
#1228 includes what I think you're proposing.  Although that one catches any synchronous exception, not just `ExecutationFailure`.

**Comment by mgsloan** [comment]
Yep, that nearly covers it!  I've turned point (1) into a comment on the PR.
