### ISSUE TITLE
How install a package from tarball or just from its directory?

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#1256]
Suppose a I have either a tarball containing source code of package or I just want to install my own package that is not on Stackage yet. I want to be able to `import` modules of the installed package and use it in other projects, or if it's an executable, executable should be available (I've added the directory where Stack keeps its executables to `PATH`, by the way).

`cabal-install` can take name of tarball as its argument (if memory serves me well), and also I can install packages locally, so executables appear in `~/.cabal/bin/` by default. Can I achieve the same using Stack?

**Comment by snoyberg** [comment]
There's am example of using a tarball as a package at https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#packages

**Comment by mrkkrp** [comment]
Aha, it's done via inclusion of the package into `stack.yaml` file of dependent module. As I see `stack build --copy-bins` on the other hand copies binaries to `~/.local/bin`.

Thanks, I should have read that file before opening an issue, though.
