### ISSUE TITLE
Add a progress indicator to stack setup

### ISSUE THREAD

**Issue by meteficha** [commercialhaskell/stack#126]
```
$ stack setup
Downloading from: https://www.haskell.org/ghc/dist/7.8.4/ghc-7.8.4-x86_64-unknown-linux-deb7.tar.xz
^C
```

**Comment by DanBurton** [comment]
I wasn't sure whether we wanted the progress output anywhere else, so I just put it in Stack.Setup for now. (See download-enhancements branch).

**Comment by chrisdone** [comment]
@DanBurton We do! See other comments on commits and PR.

**Comment by snoyberg** [comment]
This is now implemented, closing.
