### ISSUE TITLE
Provide guidance when build plan fails when installing a package outside of the snapshot

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1260]
Thanks to zedbourbaki in #haskell IRC for bringing this up.  When installing hmatrix-special atop an lts-3.0 global config:

```
mgsloan@computer:~$ stack install hmatrix-special
Run from outside a project, using implicit global config
Using resolver: lts-3.10 from global config file: /home/mgsloan/.stack/global/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      hmatrix: needed (>=0.17), 0.16.1.5 found (latest is 0.17.0.1)
    needed for package: hmatrix-special-0.4.0.0
```

To get this to work, you need to install an older version of hmatrix-special.  Namely, `stack install hmatrix-special-0.3.0.1`.  Maybe when there's a planning error, we can tell the user something like "The hmatrix-special target does not have a version specified by the resolver.  It may be possible to resolve this by picking a version which is compatible with the resolver".

**Comment by snoyberg** [comment]
We provide some guidance at this point. Further clarification PRs are welcome if desired.
