### ISSUE TITLE
Allow targets to override snapshot versions?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1261]
Thanks to zedbourbaki in #haskell IRC for bringing this up.  If you try to override a package version that's in the resolver, via `stack install`, it refuses:

```
mgsloan@computer:~$ stack install hmatrix-0.17.0.1
Run from outside a project, using implicit global config
Using resolver: lts-3.10 from global config file: /home/mgsloan/.stack/global/stack.yaml
Error parsing targets: Specified target version 0.17.0.1 for package hmatrix does not match snapshot version 0.16.1.5
```

This is a pretty good message, but particularly when using the global project, to me it makes sense to implicitly make this into an extra-dep.  Some of the checkboxes on #272 seems to suggest that this was intended at some point:

> - To force a specific version of a package to be installed, can run `stack install foo-1.2.3`
> - For ease of use, can provide `stack install foo:latest` to ignore whatever's in the snapshot

**Comment by borsboom** [comment]
I agree, seems like that should work based on #272.
