### ISSUE TITLE
Relocatable data-files: support

### ISSUE THREAD

**Issue by lukexi** [commercialhaskell/stack#1262]
I have some packages that require some accompanying data to be placed alongside any executables that depend on them; in a few cases that's some closed-source DLLs, and in another it's some shader files. I could use [file-embed](https://hackage.haskell.org/package/file-embed) as a workaround for the shaders, but the DLLs aren't as straightforward.

`cabal-install` has the ability to specify where the `data-files:` of a package are placed via `--datadir` and `--datasubdir`, which I think would solve this nicely alongside the existing `--local-bin-dir` option?

(I haven't needed this until I switched to Stack, but I assume `cabal-install`'s `--datadir` flag works alongside the `Paths_foo` module system to enable use of `getDataFileName` regardless of installation destination, for the shader example case)

**Comment by borsboom** [comment]
@lukexi, will #848 do what you need?  If not, is there a way that proposal could be extended to support what you need?

**Comment by borsboom** [comment]
For lack of feedback, closing as duplicate of #848.

**Comment by lukexi** [comment]
Whoops, sorry I missed this!

I *think* #848 will do the trick — I'll explain exactly what I'm hoping for just in case and you can close again if #848 subsumes it : )

Say I have a dependency tree like this:
```
foo
|
bar baz
|    |
\   /
 bat
```

`bat` defines an executable, and all of the projects have `data-files` in their `.cabal`.


When I run `stack install --prefix releasedir`, I want to have all of `foo`, `bar`, `baz` and `bat`'s `data-files` along with `bat`'s executable installed into `releasedir`, and for `Paths_Foo`, `Paths_Bar`, and `Paths_baz` to be configured so that `bat`'s executable can load data from them at runtime.

Hope that makes sense : )

**Comment by borsboom** [comment]
Pretty sure #848 will cover this case.  I'll reference your case over there to make sure.
