### ISSUE TITLE
Invalid package ID: "mtl-2.2.1-3FiGA50C4U5zQmGPawLX7X stm-2.4.4-15WkjbTgSVCfkxgHmYw5nJ"

### ISSUE THREAD

**Issue by wereHamster** [commercialhaskell/stack#1263]
This is the error I get when I try to compile my little GHCJS project with `stack build` (using latest versions from git of stack, ghcjs and cabal). I found the string in this file: .stack-work/install/x86_64-osx/ghcjs-0.2.0_ghc-7.10.2/ghcjs-0.2.0_ghc-7.10.2/pkgdb/exceptions-0.8.0.2-cd78e29b7853e6833b57e88b86bbea3e.con, the `depends` section looks like this:

```
depends:
    base-4.8.0.0-45Z4nIi4lruME53Rd5vE5A
    mtl-2.2.1-3FiGA50C4U5zQmGPawLX7X stm-2.4.4-15WkjbTgSVCfkxgHmYw5nJ
    transformers-0.4.3.0-4XX75EDlArEc6GIS61SgA1
    transformers-compat-0.4.0.4-3ca5cbcec233c17da785d5f27705643c
```

**Comment by mgsloan** [comment]
Strange!  Can you please provide a repro that I can try?  Does `rm -r .stack-work` and doing a fresh `stack build` resolve the issue?

**Comment by tolysz** [comment]
@wereHamster Did you manage to pinpoint what was the issue? Could you try with some more recent snapshots and see if this problem persists. Otherwise maybe we could close it?

**Comment by mgsloan** [comment]
I think it is sensible to close it because this ticket has been open for a long time without activity.
