### ISSUE TITLE
`stack haddock` fails on Windows

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1266]
I can't get it to succeed. I tried `stack haddock` from Hoogle and that failed trying to install 78 packages worth of documentation. I then tried a single package from outside a package directory, and that failed to. I suspect your filepath library is causing issues (I hear filepath libraries are tricky :) )

    C:\Neil>stack haddock extra
    Run from outside a project, using implicit global project config
    Using resolver: lts-2.14 from implicit global project's config file: C:\Users\ndmit_000\AppData\Roaming\stack\global\stack.yaml
    Setting codepage to UTF-8 (65001) to ensure correct output from GHC
    extra-1.1: configure
    extra-1.1: build
    extra-1.1: haddock
    extra-1.1: copy/register
    InvalidAbsDir "C:\\Users\\ndmit_000\\AppData\\Local\\Programs\\stack\\i386-windows\\ghc-7.8.4\\lib/../doc/html/libraries/base-4.7.0.2"

**Comment by borsboom** [comment]
This should now be fixed on master.
