### ISSUE TITLE
Have "stack ghci" warn when certain package options are likely to cause it to fail to load multiple packages

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1270]
For example, it's usually the case that loading a package that specifies `NoImplicitPrelude` will fail to load along with a package that uses the prelude.

**Comment by mgsloan** [comment]
Implemented this for `-XNoImplicitPrelude`, `-XCPP`, `-XNoTraditionalRecordSyntax`, `-XSafe`, and `-XTemplateHaskell`.  I can't think of many other cases that can cause breakage.  Any other such circumstances can be covered in other issues.

One potential case is combining flags with their negations - if one package specifies `-XNoMonomorphismRestriction`, and another specifies `-XMonomorphismRestriction`.  Doesn't seem worth the effort to warn about this in general.

```
* * * * * * * *
There are issues with this project which may prevent GHCi from working properly.

-XNoImplicitPrelude will be used, but GHCi will likely fail to build things which depend on the implicit prelude.
It is specified for:
    stack-repro:lib
But not for: 
    extradep:lib

To resolve, remove the flag(s) from the cabal file(s) and instead put them at the top of the haskell files.

It isn't yet possible to load multiple packages into GHCi in all cases - see
https://ghc.haskell.org/trac/ghc/ticket/10827
* * * * * * * *
```

**Comment by parsonsmatt** [comment]
Very nice. Thanks! :D
