### ISSUE TITLE
Starting a project has many distasteful edges

### ISSUE THREAD

**Issue by TakSuyu** [commercialhaskell/stack#1271]
There are a few commands associated with getting started with stack. All of which have some sort of behaviour that I would expect could work with a folder already created for the repository.

`stack new` which does nothing from outside the folder, and will make a new folder if you're inside.
`stack init` which does nothing if you don't have a cabal file.
`stack setup` which doesn't do anything for a project that isn't initialized.
`stack exec cabal init` which won't work because cabal complains about package-db info.

So you're stuck with making a template somewhere else and copying files over instead.

Couldn't there be an exposed flag to make templates within the directory, or even making `stack init` work much like `cabal init` and make a project if there isn't one already?

**Comment by mrkkrp** [comment]
@TakSuyu, There is `--bare` flag that will create project according to specified template but inside current directory.

**Comment by TakSuyu** [comment]
Oh I see, I had to update for the option
