### ISSUE TITLE
stack build --pedantic shouldn't apply to packages marked extra-dep

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#1272]
Create a new project with `stack new blah simple`. Then unpack any odd package from Hackage with compiler warnings into `vendor/foo`, and make your project depend on it:

```
resolver: lts-3.11

packages:
- '.'
- location: vendor/foo
  extra-dep: true
```

Now compile everything with `stack build --pedantic`. The build will fail due to a compiler warning in `foo`. I would argue that since `foo` is a vendor package that the programmer has little control over, `--pedantic` shouldn't apply to any package marked with `extra-dep: true`.

**Comment by borsboom** [comment]
#1265 will have this effect, since extra-deps will be treated like snapshot packages and won't have command-line GHC flags applied.
