### ISSUE TITLE
A question about LICENSE and a proposition

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#1274]
Sorry, it must be unimportant question and not my business, but anyway, is `stack` some sort of legal entity if you put it as copyright holder in your `LICENSE` file:

```
Copyright (c) 2015, stack
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the
    documentation and/or other materials provided with the distribution.
    * Neither the name of stack nor the
    names of its contributors may be used to endorse or promote products
    derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
```

Shouldn't it be Commercial Haskell or FP Complete?

Also, it may be desirable to replace `<COPYRIGHT HOLDER>` in the disclaimer with actual copyright holder (upcased), be it `stack` or whatever. Another option is to put `THE COPYRIGHT HOLDER` there.

**Comment by borsboom** [comment]
I don't really know the legal implications of this.  Commercial Haskell Group is not a legal entity, and FP Complete doesn't consider itself the owner of the Stack project (just a contributor).  We don't ask contributors to sign their copyright over to any legal entity.  So really Stack's copyright belongs to all the hundreds of people who have contributed.  Would `Copyright (c) 2015, many authors` make any sense, and replace `<COPYRIGHT HOLDER>` `THE AUTHOR(S)`?   I don't think that could be any worse than what's there now, from a legal perspective, but probably not any better either.

**Comment by mrkkrp** [comment]
@borsboom, I've seen this approach: `Copyright (c) 2015 <Project name> contributors` in licenses of some well-known open source projects, so it could be `Copyright (c) 2015 Stack contributors`. You see, I'm not a lawyer, but if you state that copyright holder of stack is stack (which is not a person and not a clearly defined legal entity), it's not very good. When you use `Project contributors` formula, it's clear who is mentioned (because of version control you can reconstruct list of contributors if you don't keep `CONTRIBUTORS` file or something like that).

**Comment by borsboom** [comment]
Makes sense, and I've updated the LICENSE that way.
