### ISSUE TITLE
Add a way to install the test binary

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1277]
I want to install the test binary. I tried `stack install --test` and that ran the test. I tried `stack build --copy-bins --test` and that did the same thing. Is installing test programs impossible?

**Comment by mgsloan** [comment]
Correct, test-suites and benchmarks don't get installed.  As far as I can tell, Cabal itself does not support this, at least from what I can tell from `runhaskell Setup.hs copy --help`.

How about this bit of bash to do this (untested, may require tweaking): `cp PKG_PATH/$(stack path --dist-dir)/TEST_NAME/TEST_NAME $(stack path --local-bin-path)/TEST_NAME`, where `PKG_PATH` is the path to the package and `TEST_NAME` is the name of the test.

Closing as wontfix, feel free to reopen if there's a good reason to add explicit support for this.

**Comment by ndmitchell** [comment]
Agreed, won't fix seems reasonable. I guess it's just an artefact that cabal tests and benchmark, which should have been a command line over a program, not a separate section...
