### ISSUE TITLE
Regression, stack init --resolver doesn't write a stack.yaml

### ISSUE THREAD

**Issue by drwebb** [commercialhaskell/stack#1286]
I noticed that I don't get a yaml file written when I run `stack init --resolver`.

```
λ church /tmp → stack --version
Version 0.1.7.0, Git revision 2efbc9aafe5cea6b9e2bce176b4a1fc9778c025f (2474 commits) x86_64
λ church /tmp → stack unpack lens
lens-4.13: download
Unpacked lens-4.13 to /tmp/lens-4.13/
λ church /tmp → cd lens-4.13
λ church lens-4.13 → stack init --resolver nightly-2015-11-04                     no stack/sandbox
Writing default config file to: /tmp/lens-4.13/stack.yaml
.... stack init output ...
λ church lens-4.13 → ls                                                           no stack/sandbox
AUTHORS.markdown    examples/  lens.cabal        README.markdown  SUPPORT.markdown
benchmarks/         HLint.hs   lens-properties/  Setup.lhs        tests/
CHANGELOG.markdown  images/    LICENSE           src/             travis/
```

The output of `ls` is missing the `stack.yaml`

**Comment by drwebb** [comment]
The resolver seems to be swallowed without doing anything. Adding `--resolver nightly-2015-11-04` has no effect on a `stack init` that otherwise works.

**Comment by drwebb** [comment]
Breakage is introduced after b265f80012

**Comment by borsboom** [comment]
Looks like `stack init` has its own `--resolver` option and this is conflicting with the global `--resolver` option.  The code currently ends up preferring the global option when there's a conflict, but should be easy to fix (just put the globals after the locals instead of before in the optparse-applicative Parser).

**Comment by borsboom** [comment]
Should now be fixed with master (in addition to another problem I discovered while testing the fix, where global args to sub-subcommands weren't behaving quite properly).
