### ISSUE TITLE
Something similar to `npm run`?

### ISSUE THREAD

**Issue by eightyeight** [commercialhaskell/stack#1287]
I don't know where I might find previous discussion on this, but is there any plan to allow users to add custom scripts to e.g. `stack.yaml` in the same way that `package.json` can contain `run` scripts? I've found this ability very useful when working on javascript projects, as it allows you to add project-specific commands in a uniform way (e.g., linting, integration testing).

**Comment by borsboom** [comment]
This may be out of scope, as we don't intend Stack to be a "does everything" make-like tool.  If what you need is more sophisticated, I'd suggest looking into creating a build system with Niel Mitchell's excellent [shake](http://hackage.haskell.org/package/shake) package, and having it run `stack` to create artifacts.  For example, [the tool that does Stack's re-release checking and create its bindists](https://github.com/commercialhaskell/stack/blob/master/etc/scripts/release.hs) is written using Shake.

**Comment by eightyeight** [comment]
I guess I wasn't necessarily looking to have a 'do everything' tool, just a more standardised way to run similar commands between projects. Totally get that it might be out of scope.
