### ISSUE TITLE
stack exec messes PATH on Windows

### ISSUE THREAD

**Issue by jacereda** [commercialhaskell/stack#1288]
From a Visual Studio command prompt, the following:

    link

will invoke the VS linker. If I instead run:

    stack exec link

will invoke coreutils link. Shouldn't PATH modifications be append-only?

**Comment by mgsloan** [comment]
I think the PATH modification is append-only.  Check out the results of `stack path --bin-path`.  What's likely happening is that stack adds mingw stuff to the PATH, and so you get a different `link` executable.

**Comment by jacereda** [comment]
It isn't append-only, the mingw paths are being inserted in front of the current PATH.

**Comment by mgsloan** [comment]
Yes, we need to override the installed versions.  For example, if we appended to the end instead of the front, then we might get the system GHC instead of the version intended.
