### ISSUE TITLE
travis build --test --pedantic fails for warning in dependency

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#1292]
See https://travis-ci.org/haskell/haskell-ide-engine/builds/89528688

The build is initiated with

    ./travis_long stack +RTS -N2 -RTS build --test --haddock --pedantic

One of the dependencies of one of the sub-projects (HaRe) has a warning in it

```
    [ 6 of 25] Compiling Language.Haskell.Refact.Utils.Monad ( src/Language/Haskell/Refact/Utils/Monad.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Language/Haskell/Refact/Utils/Monad.o )
    src/Language/Haskell/Refact/Utils/Monad.hs:211:10: Warning:
        No explicit implementation for
          ‘GM.gmoAsk’
        In the instance declaration for ‘GM.GmOut (StateT RefactState IO)’
```

The build then terminates with 

    The command "./travis_long stack +RTS -N2 -RTS build --test --haddock --pedantic" exited with 1.

Is this expected behaviour?

stack installed via

    travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin

**Comment by mgsloan** [comment]
Good point, I agree that `--pedantic` should only apply to local packages.  This is related to #849 / #1265

**Comment by alanz** [comment]
I updated stack to 

    Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64

by using

    travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

The problem is no longer there. So perhaps it was misdiagnosed.

**Comment by alanz** [comment]
Nope, spoke to soon, the travis cache meant HaRe was not rebuilt.

See https://travis-ci.org/haskell/haskell-ide-engine/builds/89597777 where it was merged to master with a new cache and shows the same problem.

Not sure if it is `--haddock` or `--pedantic` that does it though.

**Comment by alanz** [comment]
I just ran a [build](https://travis-ci.org/haskell/haskell-ide-engine/builds/89608351) on travis which failed doing

    stack +RTS -N2 -RTS build --haddock

This is after successfully doing 

    ./travis_long stack +RTS -N2 -RTS build --only-snapshot --pedantic

Does `--haddock` re-install all the dependencies? Which seems to be the case in this build

**Comment by borsboom** [comment]
`--haddock` does rebuild dependencies that don't already have haddocks.

**Comment by borsboom** [comment]
@alanz: the --haddock issue sounds like #1317, and the --pedantic will be covered by #1265.  I'm thinking we can close this as duplicate, but let me know if those issues don't seem to cover it.

**Comment by alanz** [comment]
Sounds fine.
