### ISSUE TITLE
TemplateHaskell + C fails on Windows GHC 7.10.3 RC1

### ISSUE THREAD

**Issue by kejace** [commercialhaskell/stack#1293]
`ghc` fails to link external C libraries in conjunction with `TH`

```

$ stack install --extra-include-dirs=c:\\haskell\\bitcoin\\src\\leveldb\\include --extra-lib-dirs=c:\\haskell\\bitcoin\\src\\leveldb

.....

--  While building package data-0.0.1 using:
      C:\stack\setup-exe-cache\setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.20151030.exe --builddir=.stack-work\dist\d96ab9d9\ build lib:data --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\haskell\.stack-work\logs\data-0.0.1.log

    Preprocessing library data-0.0.1...
    [4 of 5] Compiling Data.PersistTypes ( src\Data\PersistTypes.hs, .stack-work\dist\d96ab9d9\build\Data\PersistTypes.o )
    ghc.exe: unable to load package `leveldb-haskell-0.6.3'
    ghc.exe: c:\haskell\bitcoin\src\leveldb\libleveldb.a: unknown symbol `_Znwy'

```

Superficially I'm having a similar situation to this: http://stackoverflow.com/questions/26449154/a-workaround-for-the-template-haskell-c-bug except that issue relates to `GHCi 7.6` 

Specifically

```
`leveldb-haskell` is a wrapper over `leveldb`
Library A depends on `leveldb-haskell`
`data` uses Template Haskell (through `persistent`) and depends on library A.
```

Note that installing `leveldb-haskell` alone works using `stack` (on windows `leveldb` is difficult to build so I am using the bitcoin bundled version):

```
$ stack install --extra-include-dirs=c:\\haskell\\bitcoin\\src\\leveldb\\include --extra-lib-dirs=c:\\haskell\\bitcoin\\src\\leveldb
```

Also note that I am using `ghc 7.10.3 RC1` successfully to avoid the command line limitation (see https://github.com/commercialhaskell/stack/issues/1170) using https://github.com/commercialhaskell/stack/issues/1275#issuecomment-153567878

I have tried a lot of solutions to older, similar looking issues but it seems to me that this specific issue has not been reported before for `ghc > 7.6`.

Needless to say, this builds on both Linux and OS X

**Comment by kejace** [comment]
I can confirm that this is indeed related to TH. I can solve the issue for an individual package by extracting all TH code from `data` to `data-th` which uses TH but does _not_ use `leveldb-haskell`. Then I have `data` depend on `data-th` if needed.

**Comment by borsboom** [comment]
@kejace Have you tried building this with cabal-install or pure GHC? This
sounds like it could be an upstream bug, rather than anything specific
Stack is doing. If it is only a problem in Stack, more details and an
example project would be very helpful to diagnose.

**Comment by mgsloan** [comment]
Closing as an old need-repro issue.
