### ISSUE TITLE
Path passed to --stack-yaml doesn't allow home directory tilda

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1294]
`stack --stack-yaml ~/.stack/global/stack.yaml build stack` results in `~/.stack/global/stack.yaml: canonicalizePath: does not exist (No such file or directory)`, despite it existing.  This likely affects many other places paths are accepted.

**Comment by borsboom** [comment]
Which shell are you using?  Tilde expansion should be performed by the shell prior to passing the path to `stack` (much like environment variable expansion).

**Comment by mgsloan** [comment]
Gotcha, that makes sense.  I'm using bash.

Ah, with the exact command given above, this only happens when doing `:set args --stack-yaml ...` in GHCI, in order to run stack from the repl.  I tend to use this for faster development iterations.

The case where this happens from the shell is when I do `stack --stack-yaml=~/.stack/global/stack.yaml build stack`.  I suppose we shouldn't be too concerned about this case, though - closing.
