### ISSUE TITLE
Stack failed to configure project when Distribution.Simple.I18N.GetText is used

### ISSUE THREAD

**Issue by gromakovsky** [commercialhaskell/stack#1299]
I am developing a project which needs internalization and I want to use gettext to achieve this. I have a simple Setup.hs which uses *Distribution.Simple.I18N.GetText* module from *hgettext* package:
`import Distribution.Simple.I18N.GetText`
`main = gettextDefaultMain`
When I run `stack build --reconfigure -v` I get the following output: https://gist.github.com/gromakovsky/d0ea603555218ceeed9d
I use `build-type: Custom` in my .cabal file. I've listed hgettext as *build-depends* for every target in .cabal file, but still get this error. Relevant parts of my stack.yaml:
`resolver: lts-3.11`
`extra-deps:`
`- hgettext-0.1.30`
After some searching I've found a similar issue: https://github.com/fpco/stackage/issues/746
A workaround there was just to inline GetText module.
I guess this will work in my case, but I don't think this is a good solution.
By the way, if I use cabal directly, then everything gets installed smoothly.

**Comment by gromakovsky** [comment]
Here is a small self-contained example of this: http://git.io/v8nMD
output.txt is output of `stack build --reconfigure -v`

**Comment by mgsloan** [comment]
Hi, thanks for the report and repro!  Once Cabal-1.24 is out, the proper way to resolve this will be https://github.com/haskell/cabal/issues/948 .  For now, you will need to use

```
explicit-setup-deps:
  opasa: true
```

In your stack.yaml.  See #1110 for more info on this, and why it isn't on by default.  [Here are the docs for explicit-setup-deps](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#explicit-setup-deps)

**Comment by gromakovsky** [comment]
That worked, thank you very much for a detailed answer.
Sorry for duplicate, I tried my best to find the solution, but it wasn't easy enough :)

**Comment by mgsloan** [comment]
No problem!  This stuff is quite strange - the current situation for dependencies of Setup.hs is really ugly.  All of the points in the design space we've considered are poor, so this is what we've got for now until Cabal-1.24 is released.
