### ISSUE TITLE
Let building unlinked binaries (ghc -c)

### ISSUE THREAD

**Issue by robinp** [commercialhaskell/stack#1301]
If myproject.cabal has an executable, with `ghc-options: -c`, `cabal build` successfully creates the `.o`, and `cabal install` fails (probably it is not Main). Anyway, the install phase is not needed.

It seems stack does `cabal install` without `build`, so the `.o` is not produced, and the install fails.
## Request

Support creating such unlinked executable using stack.
Not sure where this should fit between cabal and stack.
## Background

This is needed, for example for loadable plugins. If a loadable plugin is compiled with cabal as a cabal library, cabal adds `package-name` on the GHC command line, which in turn adds some mangled name prefix to the object symbols (can check using `objdump -t Some.o`). This prefix is not expected by the `plugins` package, so dynamic symbol loading fails.

Maybe it would be enough to suppress the package-name flag of cabal somehow, and build the plugin as a cabal library?

**Comment by snoyberg** [comment]
This does in fact now work from my testing, since we call `build` before `copy`.
