### ISSUE TITLE
missing newline at the end of "Progress: 1/2"

### ISSUE THREAD

**Issue by FranklinYu** [commercialhaskell/stack#1302]
When I run `stack test` the newline is missing, so this line and next (testing message in my case) are concatenated into one. I found the source at [Execute.hs](../blob/75e118fc0a9b616295d052609c41f5e3dd988c1a/src/Stack/Build/Execute.hs#L492) but I have no idea how to fix it since I am a Haskell newbie. Minor bug, but should be easy to fix (I assume).

**Comment by rubik** [comment]
I noticed this bug as well. It would suffice to add `<> "\n"` at the end, but I find it very strange that `logSticky` does not append newlines automatically. In fact, searching for occurrences of that functions in Stack's source shows that it's never used with newlines:
https://github.com/commercialhaskell/stack/search?utf8=%E2%9C%93&q=logsticky

So the problem must be somewhere else.

**Comment by franklinyu** [comment]
@rubik I read the description of `logSticky`; it says that we need `logStickyDone` if we need the trailing newline. Actually I should not have seen the "Progress: 1/2" in the final output; output after `logStickyDone` should have overwritten this line, and this happens (as expected) if nothing is printed during test, i.e.,
```haskell
main :: IO ()
main = return ()
```
So basically any output in test suite, even as simple as
```haskell
main :: IO ()
main = putStrLn "test"
```
will break the `logSticky` and leave the "Progress 1/2" in final output.

**Comment by franklinyu** [comment]
One of the template, `new-template`, serves as an example of this bug.

**Comment by rubik** [comment]
Well done @franklinyu, I can confirm what you said. My test suite uses Hspec and Stack's output is hijacked because of this. One possible solution could be to suspend the progress status during tests and resume it right after.

**Comment by borsboom** [comment]
I think Stack should be capturing the output of the tests (and benchmarks, which I suspect will have the same problem) and re-emitting it in a way that's friendly to the sticky progress, the same way as it does for GHC output.

**Comment by franklinyu** [comment]
@borsboom Yes I think that is a better solution!

**Comment by mgsloan** [comment]
There were two issues here:

* `runActions` wasn't waiting for the progress thread to finish its work before exiting, so we wouldn't always get the `$logStickyDone` message that actions completed.

* Test output is being directly sent to stack's stdout / stderr, without first clearing the sticky message.  It now clears the sticky message before running the test.

**Comment by borsboom** [comment]
I'm reopening this since the fix was reverted.

**Comment by mgsloan** [comment]
Good catch!  I thought https://github.com/commercialhaskell/stack/commit/68ef02763525d12d2f92cdf2a3716567224d594f was sufficient, but turns out that you still get the "Progress 1/2" message.  Weird!

**Comment by mgsloan** [comment]
Fixed!

**Comment by mgsloan** [comment]
Balls, the resolution to https://github.com/commercialhaskell/stack/issues/1685 brought this back

**Comment by mgsloan** [comment]
I don't have time to work on this right now, but I have a theory it may be due to `hPutStrLn h t = hPutStr h t >> hPutChar h '\n'` in `Data.Text`.  Concurrent execution can cause other output to be inserted between your text and the newline.

**Comment by snoyberg** [comment]
I believe this is actually resolved now, please ping or open a new issue if that's not the case.
