### ISSUE TITLE
Default to having `stack ghci` load no targets?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1307]
Having `stack ghci` mean "attempt to load up all of the local packages" means that the default invocation of `stack ghci` often fails.  The more packages you have, the more likely you are to run into incompatibilities between how they're built - see https://ghc.haskell.org/trac/ghc/ticket/10827 .  Defaulting to loading everything is just asking for trouble.

This would make `stack ghci` behave pretty much like `stack exec ghci`.  I think this is good, because folks probably don't know to use `stack exec ghci` when they just want to run ghci and be able to `:m +` their project's dependencies.

It seems people are caught by surprise when they need to mark some packages as extra-dep so that their projects work with `stack ghci` - #1154 #1243 .  I think these would have been non-issues if it just required you to specify the components to load.  We can also provide the current behavior by adding an `--all` flag.

If implemented, then this should happen in tandem with https://github.com/commercialhaskell/stack/issues/1186 .  This would be a deviation from `stack build`'s default behavior, though (all libs and exes).

**Comment by ndmitchell** [comment]
As the `ghcid` author, I want a way to load everything, since sometimes you want "bring everything in to scope and quickly check it compiles". I'm happy if that is a separate flag.

**Comment by mgsloan** [comment]
Now that I've added the build flags to ghci, I think the way to go is to follow the same convention as build for targets.
