### ISSUE TITLE
stack haddock rebuilds everything

### ISSUE THREAD

**Issue by andrewthad** [commercialhaskell/stack#1317]
For some reason, every time I run `stack haddock`, it unregisters everything and rebuilds the haddocks for every transitive dependency. This can be upwards of 100 packages sometimes. It seems like (1) this shouldn't happen and (2) stack should be able to haddocks for a snapshot if it has already generated them before.

**Comment by ndmitchell** [comment]
I am seeing this behaviour too on Windows. In the Hoogle repo `stack haddock` always spits out a bunch of lines such as:

    random-1.1: copying precompiled package

Then goes on to do:

    http-types-0.8.6: configure
    http-types-0.8.6: build
    http-types-0.8.6: haddock
    http-types-0.8.6: copy/register

Repeating `stack haddock` does this complete sequence again. Doing `stack exec ghc-pkg describe random` gives:

    haddock-html: C:\Users\ndmit_000\AppData\Roaming\stack\snapshots\i386-windows\lts-3.7\7.10.2\doc\random-1.1

But the documentation at this address is just the `LICENSE` file, there are no haddock docs, which seems to be another bug.

**Comment by borsboom** [comment]
I'd say the two problems are linked.  It looks like, for some reason, the haddocks are not being copied to where they belong (Cabal should do that in the "copy/register" step).  And that means next time you run `stack haddock` it sees the haddocks are missing and so builds the package again.

I haven't been able to reproduce this so far.  Some `stack --verbose` output might be helpful.

**Comment by ndmitchell** [comment]
[dump.txt](https://github.com/commercialhaskell/stack/files/33886/dump.txt) - output with `--verbose`.

**Comment by borsboom** [comment]
Thanks, I've now been able to reproduce this on Mac OS X.

**Comment by borsboom** [comment]
I've just pushed a commit that fixes this on my system.  Please try out the
latest master.

**Comment by ndmitchell** [comment]
Confirmed, works now.
