### ISSUE TITLE
stack new --bare included outdated gitignore

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1322]
The new one at `github/gitignore` ignores .stack-work which I don't want in my git repo.

<img width="619" alt="screen shot 2015-11-09 at 10 23 34 am" src="https://cloud.githubusercontent.com/assets/320177/11037482/f6661c3e-86cb-11e5-97d8-dffc431a026d.png">

**Comment by borsboom** [comment]
@bitemyapp I'm not exactly sure what you're asking.  The `stack new` templates don't include any `.gitignore`.  Perhaps your `.gitignore` came from somewhere else?  It looks like creating new new repo at Github and choosing the the __Add .gitignore: Haskell__ dropdown does initialize the repo with an out of date `.gitignore`, but perhaps that issue should be filed with Github?

**Comment by bitemyapp** [comment]
@borsboom sounds reasonable.
