### ISSUE TITLE
Stack build should warn about redundant other-modules

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1324]
Given a library component with exposed-modules and other-modules, if one of the other-modules is not a dependency of any exposed-module, then it should be deleted. I believe given Stack's existing information this should be relatively easy to determine.

**Comment by borsboom** [comment]
Agreed, that would be a nice enhancement.  A pull request would be welcome.

**Comment by snoyberg** [comment]
I think this can be addressed by using weeder, closing.
