### ISSUE TITLE
Ability to redirect output of 'stack test'

### ISSUE THREAD

**Issue by dredozubov** [commercialhaskell/stack#1328]
I'm encountering the following scenario with travis CI right now: 'stack test' takes a long time to finish and it redirects output to a log file. Travis kills process because it has no output for some time:
```
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```
Am i missing something or there is currently no way of redirecting output from stack to a stdout? Wouldn't it be nice to have this?

**Comment by luigy** [comment]
I wonder if `stack --verbose test` would be enough for travis

Also, I've noticed that the verbosity in the output may be different depending if it is a multi-package project (less verbose than single-package)
for multi-package project you can try doing it individually:
```
stack test package
stack test otherpackage
```

**Comment by dredozubov** [comment]
Good point, forgot to mention i was referring to the multi-package project!

**Comment by borsboom** [comment]
@dredozubov: This looks similar to #426.  Would that solve your Travis problem?

**Comment by borsboom** [comment]
Closing in favour of #426.
