### ISSUE TITLE
How to get Stack build directory?

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#1329]
Is it possible to get directory where results of building are put? With Cabal it's simple: `dist/build`, but Stack uses more complex approach that involves subdirectories named according to Cabal version and operating system. This makes it harder to teach some tools how to work with Stack (I'm improving one such tool now).

So, is there a way to get path to `build` directory (via Haskell code or command line interface)?

**Comment by sjakobi** [comment]
Take a look at `Stack.Constants.distDirFromDir` or `Stack.Constants.distRelativeDir`.

**Comment by mrkkrp** [comment]
@sjakobi, I need to get the path from outside of Stack, for concrete project.

**Comment by sjakobi** [comment]
Copying the implementation of `distRelativeDir` is the only thing I can come up with, then.

**Comment by sjakobi** [comment]
Or maybe you could parse at least a part of the path from `stack path`?

Maybe some functionality in that regard could be added to `stack query`…

**Comment by mgsloan** [comment]
Yeah, appending `/build` to `stack path --dist-dir` should do the trick.

**Comment by mrkkrp** [comment]
@mgsloan, That's fantastic! Thank you.
