### ISSUE TITLE
populating index cache process is killed spontaneously

### ISSUE THREAD

**Issue by tippenein** [commercialhaskell/stack#1335]
Many of the stack commands I try are killed mid process:
```
Caching build plan
Populating index cache ...[1]    32713 killed     stack build
```

`stack --version`
`Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64`

I'm using ` Debian GNU/Linux 8.2 (jessie)`

In case it's pertinent, I've included my global stack config
```
cat ~/.stack/global/stack.yaml                                              
flags: {}
packages: []
extra-deps: []
resolver: lts-3.2
```
As suggested on #haskell irc, it may be a memory issue. I'm running this on a 128mb RAM VPS

**Comment by rubik** [comment]
128MB IMHO is too little. When I run that command on my computer, memory usage is much higher.

**Comment by tippenein** [comment]
I agree. It didn't occur to me until after posting this issue, but it may serve as a nice searchable answer for anyone running into the same thing.

**Comment by luochen1990** [comment]
I have same problem on vps, is there any solution?
