### ISSUE TITLE
stack build ignores changes in command line options ghc-options / ghc-prof-options in cabal file

### ISSUE THREAD

**Issue by sinelaw** [commercialhaskell/stack#1339]
To reproduce: 
1. Run stack build in a project
2. Change ghc-options in the cabal file
3. Run stack build again

The second `stack build` should rebuild, but it doesn't.

(Please excuse the noisy issue submission, browser submitted the form prematurely)

**Comment by borsboom** [comment]
This is expected behaviour.  See the [rebuild-ghc-options](
https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#rebuild-ghc-options)
setting to change it.
