### ISSUE TITLE
Allow to disable executable stripping

### ISSUE THREAD

**Issue by proger** [commercialhaskell/stack#1342]
It seems there's no way to do an equivalent of `cabal configure --disable-executable-stripping` to get any binary symbols.

Not sure if it's a duplicate of #846 

Weirdly, I only have this problem on Linux (stack 0.1.6.0), not on Darwin:

```
stack build
nm path-to-bin/my-program # empty
```

**Comment by borsboom** [comment]
Discussion about adding `cabal configure` options: #1438

**Comment by blitzcode** [comment]
It seems we need this option to build on armv7, because otherwise this happens:

    /usr/bin/ld.gold: warning: cannot scan executable section 1 of /home/pi/.cabal/lib/arm-linux-ghc-7.10.3/filelock-0.1.0.1-0GuYZFry5kL0ASYgccAvYE/libHSfilelock-0.1.0.1-0GuYZFry5kL0ASYgccAvYE.a(Flock.o) for Cortex-A8 erratum because it has no mapping symbols.

Using Cabal, everything builds fine when specifying `--disable-library-stripping --disable-executable-stripping`, but there's no option to do so in stack.

**Comment by mgsloan** [comment]
@blitzcode Please feel free to open a PR with changes adding support for disabling stripping.

**Comment by mgsloan** [comment]
Also, we may as well enable this by default on ARM.

**Comment by blitzcode** [comment]
Oddly enough, this doesn't seem to be an issue when using stack itself, don't know why. I can't build stack with Cabal without disabling stripping, but stack itself is able to build everything I've tried (100+ packages, several programs) just fine without this option.

**Comment by mpilgrem** [comment]
Closing because `--no-executable-stripping` was added in Stack 1.4.0.
