### ISSUE TITLE
stack sdist fails with "too many open files"

### ISSUE THREAD

**Issue by jgm** [commercialhaskell/stack#1344]
```
git clone https://github.com/jgm/pandoc-citeproc.git
cd pandoc-citeproc
stack sdist
```

Result:
```
 % stack sdist
 % stack sdist
Getting file list for /Users/jgm/src/pandoc-citeproc/
Building sdist tarball for /Users/jgm/src/pandoc-citeproc/
/Users/jgm/src/pandoc-citeproc/tests/biblio2yaml/shore.biblatex: openBinaryFile: resource exhausted (Too many open files)
```

This package contains a large number of files for tests.  Is this perhaps a lazy IO issue?

**Comment by mgsloan** [comment]
Thanks for reporting this!  Looks like it is indeed a lazy IO issue.  Unfortunately, `tar-conduit` doesn't support generating tar files, so I needed to use the `tar` package, which uses lazy IO for everything.

I've pushed a commit which should resolve the issue.  Does it work for you now?

**Comment by jgm** [comment]
Great, it works on my project.  (At least, it creates a
tarball.  I haven't verified the contents of the tarball.)

+++ Michael Sloan [Nov 16 15 22:05 ]:

**Comment by borsboom** [comment]
This isn't the only place we use the `tar` package.  I've opened #1386 to
track fixing the rest as well.
