### ISSUE TITLE
stack ghci doesn't see preprocessed files for executables

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack#1347]
There is a very similar issue #498, but as the problem there seems to be fixed, I'll open a new one.

In a project ([example](https://github.com/Ptival/PeaCoq) with an executable and some files which are processed by alex/happy which are listed under `other-modules` `stack ghci` doesn't find those files.

As far as I can see the issue is that they end up in the `…-tmp` directory while for a library where they are listed in `exposed-modules` they end up in some other place. So the original issue only fixed it for libraries.

**Comment by chrisdone** [comment]
Had the same problem. Fixed in 9b2c441. Please confirm @cocreature?

**Comment by cocreature** [comment]
Confirmed, thanks.
