### ISSUE TITLE
<command line>: cannot satisfy -package-id

### ISSUE THREAD

**Issue by ximet** [commercialhaskell/stack#1355]
After install(or during installation) some package (example text, MissingH) command:  "stack install namePackage" and after building project - I throw this exception:
" Configuring hslogger-1.2.9...
    Building hslogger-1.2.9...
    Preprocessing library hslogger-1.2.9...
    <command line>: cannot satisfy -package-id mtl-2.2.1-7fee06b00eebbe3fa92f6d82f0fb6c19" (or other lib, for example text-2.1.1-82332eeebbb42afd...)"

Install version: 0.1.6.0 x86_64 on MacOS Capitan.

What doing?

**Comment by borsboom** [comment]
This looks very similar to #980.  Do you by any chance have the Haskell Platform installed?

**Comment by borsboom** [comment]
Closing on the assumption that this is a duplicate of #980.  Please re-open if you have further information.
