### ISSUE TITLE
stack ghci --no-load *unloads* modules

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#1360]
I have a module that I use for repl'ing that I want to use like this:

    --- BEGIN .ghci ----
    :load dev/Runner.hs
    --- END ---

    $ stack ghci --no-load

That doesn't work, because after ghci loads dev/Runner.hs, it is immediately unloaded.

This is easy to see with a new template:

        $ stack new foobar 2>/dev/null
        $ cd foobar
        $ cat > .ghci
        :load src/Lib.hs
        $ stack ghci --no-load
        foobar-0.1.0.0: configure
        Configuring foobar-0.1.0.0...
        foobar-0.1.0.0: build
        Preprocessing library foobar-0.1.0.0...
        [1 of 1] Compiling Lib              ( src/Lib.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Lib.o )
        In-place registering foobar-0.1.0.0...
        Preprocessing executable 'foobar-exe' for foobar-0.1.0.0...
        [1 of 1] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/foobar-exe/foobar-exe-tmp/Main.o )
        Linking .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/foobar-exe/foobar-exe ...
        foobar-0.1.0.0: copy/register
        Installing library in
        /home/b/tmp/foobar/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/lib/x86_64-linux-ghc-7.10.2/foobar-0.1.0.0-E05fmeQhYiF0vVxMlsqLP6
        Installing executable(s) in
        /home/b/tmp/foobar/.stack-work/install/x86_64-linux/lts-3.7/7.10.2/bin
        Registering foobar-0.1.0.0...
        The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
        Using main module: Package `foobar' component exe:foobar-exe with main-is file: /home/b/tmp/foobar/app/Main.hs
        Configuring GHCi with the following packages: foobar
        GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
        [1 of 1] Compiling Lib              ( src/Lib.hs, interpreted )
    --> Ok, modules loaded: Lib.
    --> Ok, modules loaded: none.
        |Prelude|
        λ :r
        Ok, modules loaded: none.
        |Prelude|
        λ

This works for ghci, however:

    $ ghci
    GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
    Loading package ghc-prim ... linking ... done.
    Loading package integer-gmp ... linking ... done.
    Loading package base ... linking ... done.
    [1 of 1] Compiling Lib              ( src/Lib.hs, interpreted )
    Ok, modules loaded: Lib.
    |*Lib|
    λ :r
    Ok, modules loaded: Lib.
    |*Lib|
    λ

**Comment by mgsloan** [comment]
Thanks for the report, good catch!  Now `stack ghci --no-load` does not pass in `-ghci-script`.
