### ISSUE TITLE
stack ghci <file>

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#1361]
Is it possible to load a single module into ghci, outside of a project?

```
> stack ghci foo.hs
Run from outside a project, using implicit global project config
Using resolver: lts-3.10 from implicit global project's config file: /Users/mrosen/.stack/global-project/stack.yaml
Error parsing targets: Directory not found: foo.hs
```

**Comment by mgsloan** [comment]
Not currently, but it's a good idea.  I'd also like to support loading files from the project, and have it figure out which cabal components to load.

The way to do this is `stack ghci`, then within the repl, `:load foo.hs`.  Or, within a project, `stack exec ghci` followed by `:load foo.hs`.

**Comment by mitchellwrosen** [comment]
Within a project, is `stack ghci` not equivalent to `stack exec ghci`?

**Comment by mgsloan** [comment]
It isn't - with v0.1.6, `stack ghci` loads up every cabal component for every project.  On the latest dev branch, it now loads up all the library / executable components, consistent with `stack build`.  I did consider having `stack ghci` load up no components - see #1307.  If there's demand for this behavior, I wouldn't mind making the change.

**Comment by mgsloan** [comment]
It'd also be good to be able to support `stack ghci Foo.Bar.Baz`, or `stack ghci --module Foo.Bar.Baz` (otherwise we might be overloading TARGET with a few too many ways to parse)

**Comment by mgsloan** [comment]
This has been implemented!  One caveat is that you cannot specify both normal targets and file targets.  The logic for specifying both would have been complicated, so I took the easy way out.
