### ISSUE TITLE
--cabal-verbose should allow setting verbosity level

### ISSUE THREAD

**Issue by mwu-tow** [commercialhaskell/stack#1369]
From what I observed, using `--cabal-verbose` passes `--verbose` to Setup program. However, the resulting output is not as detailed is it could be. The `--verbose` flag takes an 0..3 int parameter. 
Passing `--verbose` without value is equivalent to ``--verbose=2`. I'd like to be able to obtain cabal output from `--verbose=3`.

The seemingly natural solution would be to add the same value parameter to `--cabal-verbose` and pass it to Setup.

**Comment by borsboom** [comment]
Perhaps, like with Stack's `--verbose`/`--verbosity`, we should add a `--cabal-verbosity` option.  I think I'd rather it take Stack's standard verbosity values and converts them to cabal-install's numeric ones (perhaps, in addition, accepting cabal-install's numeric values).

**Comment by lucamolteni** [comment]
Mmhhh.. It seems like we've broken the old behaviour, sorry.

We're working on a fix :)

**Comment by nadirs** [comment]
The thing is, we should probably implement a unified `--cabal-verbose[=N]`. That is, you can supply a value or if you don't it should use a default value. So, there are 3 cases:
1) no option at all (so it uses a default value, e.g. 1)
2) option is used but with no value (so it uses another default value, e.g. 2)
3) option is used with an explicit value (e.g. --cabal-verbose=3)

The library optparse-applicative doesn't seem to expose a combinator for this case, so the solution would be to compose two parsers for case 2 and 3 using Alternative (<|>), both wrapped by an `optional` combinator.

**Comment by ndmitchell** [comment]
FWIW if you get to a "missing header file" the only sane way to figure out how it's missing is to pass `-v3` to cabal, as per https://github.com/haskell/cabal/issues/1747. Without a way to get that to Cabal, I've got to get creative...

**Comment by mpilgrem** [comment]
I have a fix that implements this feature with the addition of new build option `--cabal-verbosity=VERBOSITY`, which accepts Cabal's numerical and extended syntax. I'll propose a pull request.
