### ISSUE TITLE
Stack init could accept explicit versions

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1370]
For my test suite, I run things like hlint through `stack init` then `stack build`. At the moment, haskell-src-exts is not correct in the latest lts, so stack init fails. I would like to do:

    stack init --resolver "haskell-src-exts-1.17.0"

Whether resolver takes package names, or I use `--extra haskell-src-exts-1.17.0` doesn't matter, but it would be nice to `init` with explicit constraints for when stack otherwise fails.

**Comment by mgsloan** [comment]
Makes sense!  `--package haskell-src-exts-1.17.0` would be consistent with `stack ghci`'s CLI.  I'm in favor of such an addition.

**Comment by harendra-kumar** [comment]
With the changes in pull request #1583 you can achieve this by putting your preferred resolver and `haskell-src-exts-1.17.0` in extra-deps and then using `stack solver`.

**Comment by ndmitchell** [comment]
@harendra-kumar - that doesn't help if I don't have a `stack.yaml` already, and here my use case is `stack init` to create the `stack.yaml`.

**Comment by mgsloan** [comment]
You can, however do `stack init --force`, and then add `haskell-src-exts-1.17.0` to your extra-deps.

To me, this seems to handle the usecase nicely.  I wouldn't be opposed to adding a `--package` flag if you still think it's needed and if it's easy to implement.

**Comment by ndmitchell** [comment]
As soon as it involves the step "edit the stack.yaml" then it's no longer really suitable for running automatically on a buildbot for my use case, and I'd have to go and create a manual stack file, which is a bit of a shame. But maybe that's not a use case you support.

**Comment by harendra-kumar** [comment]
> At the moment, haskell-src-exts is not correct in the latest lts, so stack init fails.

#1583 does everything possible to make stack init succeed. With that merged you can just use `stack init --solver` and it will should give you a working stack.yaml with a snapshot resolver and `haskell-src-exts` in extra-deps. You can also use `stack init --solver --resolver` if you want to init with a specific resolver.

**Comment by ndmitchell** [comment]
Ah, awesome :) - in that case I think there is enough to consider this fixed.
