### ISSUE TITLE
"stack haddock" fails to generate Haddocks

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#1371]
Running from inside a project:
```
$ stack haddock Cabal --resolver lts-2.22
Updating Haddock index for snapshot packages in
/home/simon/.stack/snapshots/x86_64-linux/lts-2.22/7.8.4/doc/index.html
```

This results in the index.html being generated but the links to e.g. `Distribution.Package` lead to non-existent files.

Trying again with gitrev:
```
$ stack haddock gitrev --resolver lts-2.22
gitrev-1.0.0: copying precompiled package
```
The index.html file is unchanged. It doesn't even contain a link to `Development.Gitrev`.

Retrying from outside the project:
```
~ $ stack haddock gitrev --resolver lts-2.22
Run from outside a project, using implicit global project config
Using resolver: lts-2.22 specified on command line
```
The index.html file remains unchanged.

``` 
$ stack --version
Version 0.1.7.0, Git revision f02d74469a5fa4972b8c382dbbadd935a8edd861 (dirty) (2589 commits) x86_64
```
The haddock functionality in this version should be equal to that in https://github.com/commercialhaskell/stack/commit/77a049de14a1a41603d26fabf7f6d4fbb359e64b.

**Comment by borsboom** [comment]
It's likely this has the same root cause as #1317, which I just pushed a
fix for.  Can you try the latest master?

**Comment by sjakobi** [comment]
That was quick! :)

Seems to work too (apparently except for packages where the precompiled binaries have already been copied)! :+1:
