### ISSUE TITLE
Where do the haddocks for non-snapshot packages go?

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#1372]
Running from outside any project:

```
$ stack haddock discrete-space-map --resolver lts-2.22
Run from outside a project, using implicit global project config
Using resolver: lts-2.22 specified on command line
discrete-space-map-0.0.4: download
discrete-space-map-0.0.4: configure
discrete-space-map-0.0.4: build
discrete-space-map-0.0.4: haddock
discrete-space-map-0.0.4: copy/register
```

So where can I find the haddocks now?

Turns out they installed in

```
/home/simon/.stack/global/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/doc/discrete-space-map-0.0.4/
```

Sadly they are unlinked and there is no index file at

```
/home/simon/.stack/global/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/doc/index.html
```

**Comment by borsboom** [comment]
Right, there's no index of all the packages in the databases; only an index
for packages that are actually part of the project or snapshot is
generated.  Adding an index of all packages in the databases is a good idea.

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because `stack haddock acme-missiles` outside of a Stack project does report the location of a Haddock index.
