### ISSUE TITLE
increment building on windows: GHC crash

### ISSUE THREAD

**Issue by Heather** [commercialhaskell/stack#1380]
![](http://i.imgur.com/SEEBz4e.jpg)

```
--  While building package stack-0.1.7.0 using:
      ...\Roaming\stack\setup-exe-cache\setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe --builddir=.stack-work\dist\d96ab9d9 build lib:stack exe:stack --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 255
```

but

```
stack clean
stack install
```

works fine

**Comment by mgsloan** [comment]
Hey, thanks for the report.  Does this happen with all projects?  If not, can you point us at a project that reliably reproduces this?

**Comment by Heather** [comment]
@mgsloan not sure about other projects but stack itself reproduces it well

**Comment by borsboom** [comment]
We do regularly incrementally build stack with itself on Windows and
haven't run into this.  Is there anything strange about your environment?
How much memory does the machine have?

This is probably a GHC issue and not a Stack one.  Have you tried building
stack using cabal-install on this machine?

**Comment by Heather** [comment]
@borsboom yes it works, even stack clean + stack install works fine but okay, I'm closing this for now and if this will happen again - I will reopen
