### ISSUE TITLE
LLVM under OSX

### ISSUE THREAD

**Issue by fatlazycat** [commercialhaskell/stack#1383]
Hi, was trying to build my own version of bytestring-arbitrary to get it working with GHC 7.10 - it's just not version bumped and released.

It uses the ghc option for llvm, when attempting to compile it errors with 
<no location info>:
    Warning: Couldn't figure out LLVM version!
             Make sure you have installed LLVM
ghc: could not execute: opt

Should it be using cc from OS X ? Tried installing LLVM from homebrew and adding

    # Extra directories used by stack for building
    extra-include-dirs: [/usr/local/opt/llvm/include]
    extra-lib-dirs: [/usr/local/opt/llvm/lib]

and then locally setting the path to find opt e.g. export PATH=/usr/local/opt/llvm:$PATH

but makes no difference.

Any ideas ? Anything stack specific I should be doing ?

Thanks

**Comment by fatlazycat** [comment]
Managed to get this to work ( well invoke opt ) via ghc settings file. I assume there is a better way with stack to specify the path to ghc ?

**Comment by borsboom** [comment]
I'm not sure.  I don't believe Stack has any specific functionality for this, but it's not something I've ever tried to do.  I'm guessing that the reason changing your PATH didn't help might be because the GHC settings file already had an absolute path.  Or perhaps Stack's PATH modification prepended something that interfered to your PATH (running `stack exec sh -c 'echo $PATH'` will show you how it modifies the PATH, so you could check for that).

@snoyberg, do you have any wisdom to share?

**Comment by fatlazycat** [comment]
That shows up the path with llvm on it but it appears that stack build has a different path or ghc itself isn't searching it ?

**Comment by snoyberg** [comment]
Sorry, no wisdom here, I've never tried the LLVM backend.

**Comment by fatlazycat** [comment]
Problem only really exists on OSX given Apple ship their own. 

From what I understand 3.5.2 is the current for ghc, When you install this off Homebrew you need to manually specify the paths during compilation rather than just putting it in /usr/local/bin etc given the clash with Apple's.

Ideally need someway on stack to specify addition to the path for ghc ?!?!!?

**Comment by fatlazycat** [comment]
Does stack and / or ghc create a new clean path ?

**Comment by borsboom** [comment]
Stack only adds to the beginning of PATH, it doesn't delete what's already there.  You can see what the path will look like using `stack exec -- sh -c 'echo $PATH'`.  Does the output of that give you any clues?

**Comment by fatlazycat** [comment]
Hmm sorry must have been PEBKAC somewhere along the line, installed a new llvm of 3.5.2 and it works prepended to the path.
