### ISSUE TITLE
FAQ: automatic installation of extra-libraries

### ISSUE THREAD

**Issue by amigalemming** [commercialhaskell/stack#1384]
I scanned the FAQ and GUIDE but could not find an answer to this question: Does `stack` also install C libraries for me? There are several packages like `hmatrix` or `cuda` that depend on external C libraries. Could you please add an item to the FAQ, telling whether `stack` can install external C libraries or whether it is intended to support that in the future? Such support would mean that different Linux distributions, Mac and Windows would need individual information on how to install these libraries.

**Comment by borsboom** [comment]
Stack does not install system libraries; that is out of scope.  Would you
be willing to make a pull request to add this to the FAQ?

**Comment by mgsloan** [comment]
Definitely out of scope for stack.  However, maybe it's within the scope of Cabal to allow meta-data which can give suggestions for library installation?  If such meta-data existed, I'd be in favor of stack displaying it.

**Comment by amigalemming** [comment]
On Fri, 20 Nov 2015, Michael Sloan wrote:

> Definitely out of scope for stack. However, maybe it's within the scope 
> of Cabal to allow meta-data which can give suggestions for library 
> installation? If such meta-data existed, I'd be in favor of stack 
> displaying it.

You can use the pkgconfig-depends field of Cabal for showing external 
dependencies. An automated tool could scan available packages of Ubuntu or 
Debian or MSYS/Arch for the according .pc files.

**Comment by mgsloan** [comment]
This is now resolved!  I've split off https://github.com/commercialhaskell/stack/issues/2448 for adding user suggestions for how to install system libs.

**Comment by sjakobi** [comment]
Fixed via https://github.com/commercialhaskell/stack/pull/2403 and https://github.com/commercialhaskell/stack/commit/59c3db29764de5c7065f8c4332b45e5c02cca340.
