### ISSUE TITLE
Yaml issues

### ISSUE THREAD

**Issue by fatlazycat** [commercialhaskell/stack#1385]
Trying to put in a a unreleased test dependency into my projects stack.yaml file.

It's fine with 

    packages:
    - '.'
   - /Users/graham/Development/GitHub/tsuraan/bytestring-arbitrary

but if I try to state it's an extra sep to stop testing etc

with 

    packages:
    - '.'
    - /Users/graham/Development/GitHub/tsuraan/bytestring-arbitrary
      extra-dep: true

Then it fails to build with yams parsing issues.

Am trying to follow https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md#packages

What obviously stupid thing am I getting wrong ? :)

Thanks

**Comment by borsboom** [comment]
I think that should be:

    packages:
    - '.'
    - location:
'/Users/graham/Development/GitHub/tsuraan/bytestring-arbitrary'
      extra-dep: true

This YAML syntax creates an array item that's an object.

**Comment by fatlazycat** [comment]
Thanks
