### ISSUE TITLE
Ensure all uses of Codec.Archive.Tar don't use lazy I/O

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#1386]
#1344 fixed this for `stack sdist`, but Codec.Archive.Tar is used in several other places as well.

**Comment by mgsloan** [comment]
Usage in [`Stack.PackageIndex.populateCache`](https://github.com/fpco/stack/blob/2413d2be3c45d07c28b2b7f77d61353f33eb375f/src/Stack/PackageIndex.hs#L78) seems fine - the data from the lazily read tarball is promptly consumed

Usage in [`Stack.Config.resolvePackageLocation`](https://github.com/fpco/stack/blob/2413d2be3c45d07c28b2b7f77d61353f33eb375f/src/Stack/Config.hs#L455) is also fine - it promptly consumes the whole tarball as its unpacking it.

Usage in [`Stack.Fetch.fetchPackages'`](https://github.com/fpco/stack/blob/2413d2be3c45d07c28b2b7f77d61353f33eb375f/src/Stack/Fetch.hs#L474) is also fine - it promptly consumes the whole tarball as its unpacking it.
