### ISSUE TITLE
Have the travis 7.8 build use stack-7.8.yaml

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1398]
Travis uses cabal to build, to ensure that we can always bootstrap.  However, this means that we can end up pulling in different versions than used by stack-7.8.yaml.  In particular, this can cause issues because it isn't build against `Cabal-1.18.*` - see [sjakobi's comment](https://github.com/commercialhaskell/stack/pull/1334#discussion_r45548676).

**Comment by borsboom** [comment]
Travis is intentionally configured to use cabal-install instead of `stack`, to ensure that Stack can always be bootstrapped that way.  Instead, I'll get our Jenkins server to run the integration tests using stack-7.8.yaml as well, so that'll catch these problems pretty quickly.

**Comment by phadej** [comment]
I'll setup travis to /also/ build with stack.
