### ISSUE TITLE
Fix warnings and 7.10 compatibility

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#140]
Got lots of warnings. Searched Github issues, didn't see anything about warnings or 7.10 (independent searches).

1. What versions of GHC are supposed to work right now?

2. May I ifdef the warnings out? Noisy builds drive me nuts.

**Comment by snoyberg** [comment]
I think this is resolved, and we _are_ testing on Travis with 7.10. Closing.
