### ISSUE TITLE
`stack path` don't work with ghcjs project.

### ISSUE THREAD

**Issue by yihuang** [commercialhaskell/stack#1402]
I've already set `compiler: ghcjs-0.2.0_ghc-7.10.2` to `stack.yaml` to make it a ghcjs project, but `stack path` don't work anymore, which cause `codex` can't find the dependencies to create `tags` file.
```
$ stack path --snapshot-pkg-db
No compiler found, expected minor version match with ghcjs-0.2.0_ghc-7.10.2 (x86_64) (based on resolver setting in /home/vagrant/src/reflex-dom/stack.yaml).
Try running "stack setup" to install the correct GHC into /home/vagrant/.stack/programs/x86_64-linux/
```

**Comment by yihuang** [comment]
It seems I need to run `stack setup` first, after that, `stack path` works as expected.

**Comment by mgsloan** [comment]
Yep, `stack path` requires stack to know the exact version of ghc it's using.
