### ISSUE TITLE
How to collect stack compiled test programs

### ISSUE THREAD

**Issue by tel** [commercialhaskell/stack#1403]
When running a command like `stack build --test --no-run-tests` it would appear that the test executables could be collected and run at a later time... but they don't seem to show up in the `.stack-work` tree. Is there a way to collect these compiled artifacts?

**Comment by mgsloan** [comment]
They should end up at `PKG/$(stack path --dist-dir)/build/TEST/TEST`, where `PKG` is the path to the package, and `TEST` is the name of the test.

**Comment by tel** [comment]
Ahhhh, I never realized there were `.stack-work` directories my subprojects.

**Comment by tel** [comment]
Thanks!
