### ISSUE TITLE
Better error message when profiling versions of ghc libraries are missing

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1407]
See #1331.  The haskell platform apparently lacks profiling versions of libraries, which causes issues for `--enable-executable-profiling`.  Instead of getting a comprehensible error message, it outputs a build plan failure, recommending:

```
Recommended action: try adding the following to your extra-deps in my-project-dir/par-tutorial/prof-example/stack.yaml
- base-4.8.1.0
- ghc-prim-0.4.0.0
```

Suggested implementation: notice when [`wiredInPackages`](https://github.com/fpco/stack/blob/44da1c1bdfa3fb6d0f62a54f05859d80b0efd34b/src/Stack/Constants.hs#L275) are being ignored due to needing profiling.  It's probably best to store this away and wait for the build plan to actually fail before outputting the more informative error message, though.

**Comment by snoyberg** [comment]
Since we now default to `--no-system-ghc`, this is a much lesser concern. Closing, though PR still welcome.
