### ISSUE TITLE
'stack upgrade' to post-check if new version is really accessible on PATH

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#1409]
Windows 10 x64

Currently `stack upgrade` is putting Stack on a place like %PATH%\AppData\Roaming\local\bin, but after that there is no guarantee that new stack will be available. 
It could be good if it warns user if newly installed stack is not accessible on the PATH. Currently I do each time manually `stack --version` after `stack upgrade` to verify that.

**Comment by mgsloan** [comment]
Thanks for the idea, I agree.  This is already tracked by https://github.com/commercialhaskell/stack/issues/1362 , so closing as duplicate.
