### ISSUE TITLE
Only run benchmarks specified as build targets

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1412]
Currently which benchmark targets are selected is ignored when actually running them - see [this FIXME](https://github.com/fpco/stack/blob/master/src/Stack/Build/Execute.hs#L559).  Should be as simple as providing the benchmarks as component parameters [here](https://github.com/fpco/stack/blob/master/src/Stack/Build/Execute.hs#L1281), and testing that it works properly.

**Comment by rvion** [comment]
@mgsloan the here link is broken

**Comment by mgsloan** [comment]
Ah, yes, fixed.  That's what I get for using unpushed SHAs! (I've got an emacs keybinding that creates a github url based on the current SHA + line)
