### ISSUE TITLE
stack new broken?

### ISSUE THREAD

**Issue by halarnold2000** [commercialhaskell/stack#1413]
I've been using stack new my-project with/without new-template.

suddenly, I don't know what I did, but sometime in the last several days, it just returns:

stack new my-project
Usage: stack new ([--solver] | [--resolver RESOLVER] | [--prefer-lts] |
                 [--prefer-nightly]) [--force] [--ignore-subdirs]
  Create a brand new project

I've updated my stack, erased any 'extra' junk in my ~/myMachine/haskell directory [the root where my projects live] and everything else I could think of. I'm running on Mac. It used to work flawlessly.
Anything I did?

/Hal

**Comment by mgsloan** [comment]
Hmm, are you sure you're on the latest version - what does `stack --version` say?  v0.1.8 has the following output for `stack new`

```
Usage: stack new PACKAGE_NAME [--bare] [TEMPLATE_NAME] [-p|--param KEY:VALUE]
                 ([--solver] | [--resolver RESOLVER] | [--prefer-lts] |
                 [--prefer-nightly]) [--force] [--ignore-subdirs] [--help]
  Create a new project from a template. Run `stack templates' to see available
  templates.
```

I'd be surprised if `stack new` stopped working for an older version, though, the format hasn't changed recently.

**Comment by halarnold2000** [comment]
✔ ~/haskell
21:42 $ stack --version
Version 0.1.2.0

I 'updated' stack, how do I get the newest?

**Comment by mgsloan** [comment]
If you're updating via `stack upgrade`, make sure that `~/.local/bin` is on your PATH - add `export /home/username/.local/bin:$PATH` to some script that gets run before your shell, like `~/.bashrc`.

There's an open issue to make this circumstance a bit clearer: https://github.com/commercialhaskell/stack/issues/1362

**Comment by halarnold2000** [comment]
okay, figured it out, or at least got it back to where it was and got the version right too.
Someone that I was pairing with, modified my .bash_profile's path to be:
export PATH="$PATH:$HOME/.local/bin:$HOME/software/bin”
from
export PATH="$HOME/.local/bin:$HOME/software/bin:$PATH"
I put it back, and voila, life is good. I will have to reflect as to why that is

**Comment by halarnold2000** [comment]
as per your just issued comment: you can see that /.local/bin is in my path in both cases, it's the order that something is being used..some older stack or component of ghci ..gotta think about it some more. 
thanks!
