### ISSUE TITLE
Allow dependencies between test-suites and benchmarks in stack.yaml

### ISSUE THREAD

**Issue by taladar** [commercialhaskell/stack#1416]
We have a number of projects where each includes a REST service and an admin backend web interface for that REST service. The name of the REST service package changes depending on the project. The name of the admin backend stays the same. The admin backend is compiled as a git submodule of the REST service repository and both are in the packages section of the same stack.yaml file. Neither depends on the other but they do depend on other local packages.

The test suite for the REST service creates a database and preloads data from CSV (which can take in the order of minutes in some cases). Because of this and to test consistency of the database contents with some hard-coded settings in the backend, the test suite for the admin backend uses the same database.

This seems to work fine for projects where the REST service package is named something before the backend package name in lexicographical order but does not work otherwise.

My suggestion would be to allow a dependency between test suites (and benchmarks which might be in the same boat) which affect the order of test suite runs only if both will be run as part of the current stack call anyway and no existing dependency information contradicts the specified order (in this case an error would be nice of course).

Maybe if one of them is running alone and is marked to depend on another test suite or benchmark a helpful message could be printed too so people know the reason it might fail.

**Comment by mgsloan** [comment]
Thanks for bringing this up!  I think it'd be too much added complexity to support this specialized case.  I'd recommend having your test-suites be independent of eachother - how about allowing either of them to initialize the database?

Even if this were implemented, it would most fit as a Cabal feature, since cabal-install also supports running all the test-suites together.

My suggestion would be to have a `dev-scripts/test.sh` script like this:

```sh
#!/bin/sh
stack test pkg:services-test
stack test pkg:admin-test
```

**Comment by taladar** [comment]
I can see how you would think it is too complex and specialized. I am not sure what you mean about the Cabal feature considering Cabal does not deal with more than one package at a time at all.

**Comment by mgsloan** [comment]
Cabal does allow for multiple test-suites and multiple benchmarks in a package, though.  So if you wanted to specify execution ordering amongst components, it'd be most natural to do so within the cabal file itself.

**Comment by taladar** [comment]
The components in question are not in the same package though (just to clarify for people who might look at this ticket in the future)
