### ISSUE TITLE
Passing flag to stack ghci doesn't work

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#1419]
I remember recently feature of being able to pass a flag to `stack ghci` was implemented (thanks!). Unfortunately, it doesn't quite work.

Here, I created a repository with simple project which should print "True" when flag `production` is set, but it doesn't: https://github.com/k-bx/stack-bug-flag

Please check it out. Thank you!

**Comment by mgsloan** [comment]
Thanks for the report!  Fixed in https://github.com/commercialhaskell/stack/commit/7a004b489a4a2cc67b1b1558f3c566f47bdc85e1
