### ISSUE TITLE
Ambiguous module name ‘Crypto.Hash’

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stack#1421]
![image](https://cloud.githubusercontent.com/assets/2150990/11380175/ccd341c8-92f4-11e5-8a47-ad5ca7b2554d.png)

 https://github.com/lukexi/stack-ide-sublime doesn't work correctly because of this :/

**Comment by mgsloan** [comment]
Thanks!  I've cherry-picked this atop master.

**Comment by mrkkrp** [comment]
As far as I know `cryptonite` is not a dependency of Stack, so there is no problem here. I've fixed similar issue in Flycheck for Emacs, so shouldn't this be fixed in Sublime, not source code of Stack?

**Comment by mgsloan** [comment]
Yes, I agree that would be a preferable fix.  Otherwise, we're in a circumstance where there's a property we'd like to have - "no ambiguous imports" - but no way to ensure that we're preserving that property.

**Comment by rvion** [comment]
@mrkkrp I agree with you and made the same diagnostic, but I don't feel like fixing sublime-stack-ide, I've spent enough time tweaking it already, and I'm not a python / sublime expert.

I personally think it is an improvement anyway, because ambiguous module are bad.
