### ISSUE TITLE
stack rebuilds `Stack.Upgrade` when you change the git index at all

### ISSUE THREAD

**Issue by kadoban** [commercialhaskell/stack#1425]
When you're developing on `stack` itself and modify the git index (aka the cache or staging area), it causes the `Stack.Upgrade` module to need to be rebuilt.

It's not exactly the end of the world, but it adds an extra delay in certain cases, like when you are running tests and it lengthens the time between iterations of what you're trying to mess with.

```
~/projects/stack (upstream)$ stack build
~/projects/stack (upstream)$ touch bogus.txt
~/projects/stack (upstream %)$ git add bogus.txt 
~/projects/stack (upstream +)$ stack build
stack-0.1.9.0: unregistering (local file changes: .git/index)
stack-0.1.9.0: build
Preprocessing library stack-0.1.9.0...
[73 of 76] Compiling Stack.Upgrade    ( src/Stack/Upgrade.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/Stack/Upgrade.o ) [~/projects/stack/.git/index changed]
In-place registering stack-0.1.9.0...
Preprocessing executable 'stack' for stack-0.1.9.0...
[2 of 2] Compiling Main             ( src/main/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/stack/stack-tmp/Main.o ) [~/projects/stack/.git/index changed]
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/stack/stack ...
stack-0.1.9.0: copy/register
Installing library in
~/projects/stack/.stack-work/install/x86_64-linux/lts-3.14/7.10.2/lib/x86_64-linux-ghc-7.10.2/stack-0.1.9.0-K5i01b4VNwNJsmjPkKylJf
Installing executable(s) in
~/projects/stack/.stack-work/install/x86_64-linux/lts-3.14/7.10.2/bin
Registering stack-0.1.9.0...
~/projects/stack (upstream +)$ stack build
~/projects/stack (upstream +)$ 
```

Since the `bogus.txt` file doesn't matter at all, I would have ideally expected the second `stack build` to do nothing, but it spends some time rebuilding instead.

As pointed out in a short discussion about it on IRC, this is caused by the use of `$gitHash` [here](https://github.com/commercialhaskell/stack/blob/09991d98ed034e036668721de966c199e2e40642/src/Stack/Upgrade.hs#L45)

This may actually be more of a [gitrev](https://github.com/acfoltzer/gitrev/blob/master/src/Development/GitRev.hs#L74) issue actually since we're only using `gitHash`, which doesn't appear to care about the index at all, but since it shares an underlying implementation between that and `gitDirty`, it sets the index as a dependent file (`addDependentFile` from TH).

But I'm not sure that's the correct place to fix this, or if there's something different to do on our side instead, so I'll add this issue here for discussion.

**Comment by rvion** [comment]
I'm also annoyed by this

**Comment by kadoban** [comment]
I tried to fix this upstream in a gitrev fork with [https://github.com/kadoban/gitrev/commit/33ce352e2c8ce0b5735c13c081eb5e928071dacd](this small change to gitrev), but ... it doesn't seem to actually fix it. It *changes* the behavior, but I wouldn't say it's really fixed.

The first time I change the index it then rebuilds *everything* (some unrelated bug maybe?), and then after that it gives:
```
~/projects/stack (upstream *+)$ echo "blahity" >> bogus.txt 
~/projects/stack (upstream *+)$ git add bogus.txt 
~/projects/stack (upstream *+)$ stack build
stack-0.1.9.0: unregistering (local file changes: .git/index)
stack-0.1.9.0: build
Preprocessing library stack-0.1.9.0...
In-place registering stack-0.1.9.0...
Preprocessing executable 'stack' for stack-0.1.9.0...
[2 of 2] Compiling Main             ( src/main/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/stack/stack-tmp/Main.o ) [~/projects/stack/.git/index changed]
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/stack/stack ...
stack-0.1.9.0: copy/register
Installing library in
~/projects/stack/.stack-work/install/x86_64-linux/lts-3.14/7.10.2/lib/x86_64-linux-ghc-7.10.2/stack-0.1.9.0-KLa5ipxwlXfL87Of5k6lCx
Installing executable(s) in
~/projects/stack/.stack-work/install/x86_64-linux/lts-3.14/7.10.2/bin
Registering stack-0.1.9.0...
```

You'll note it doesn't rebuild `Stack.Upgrade` anymore, but it still rebuilds `Main`, and I have no idea why yet.

**Comment by borsboom** [comment]
I think if we want the correct git revision/dirtiness embedded in the executable (which we do), there's not much way around it.  I suppose you could add a Cabal flag to disable this behaviour (using CPP), but by default it should be enabled.

**Comment by kadoban** [comment]
Okay, thanks much; that was going to be my next line of inquiry. A flag would be fine for the only use-case I have that I'd notice this behavior. I'll write up a quick PR.
