### ISSUE TITLE
Allow to specify a subdirectory of a git repo

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#1426]
E.g. if I want to depend on a specific version of Cabal, I may try to write

```
- location:
    git: https://github.com/haskell/cabal.git
    commit: f217c479fc28b16ca33c3971d75826a27f7577d4
```

but this will fail since Cabal is not at the root of that repository, but in a subdirectory. It would be nice to support repos like this.

**Comment by borsboom** [comment]
This is supported by the `subdirs` option.  See: http://docs.haskellstack.org/en/stable/yaml_configuration.html#packages
