### ISSUE TITLE
stack init --solver should look for where it installs cabal

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1428]
If you `stack install cabal-install`, it puts it at `C:\Users\appveyor\AppData\Roaming\local\bin`. If you `stack init --solver` it looks for `cabal.exe` on `$PATH`. I suggest that if `stack` doesn't find `cabal` it should check where it would have installed it, so the instructions are correct regardless of `$PATH`.

**Comment by mgsloan** [comment]
There's actually already a warning about this, but it's a bit buried in the output - see https://github.com/commercialhaskell/stack/issues/1362

It also could use improvements because it doesn't detect the case where a cabal binary is in a directory in an earlier part of `PATH`.

**Comment by ndmitchell** [comment]
But in this case there's no reason you can't find cabal where you put it even if it's not on PATH. I appreciate for stack you do have to have it on the PATH because the user invokes it, but not cabal.

**Comment by mgsloan** [comment]
Ahh, that's a good point!

Yes, I agree that it makes sense to have `stack solver` invoke the cabal that's found in the snapshot's bin directory or the local bin directory.  Maybe it's sensible to actually stick these dirs on the front of the PATH?  That way, if you've installed a version of cabal for a particular snapshot, you'll get that version when running `stack solver` for a project that uses the snapshot.

**Comment by ndmitchell** [comment]
For `cabal`, whether you modify the `$PATH` or search for the things you would have put on the new `$PATH` first is merely an implementation detail. I guess it makes more of a difference for other tools, e.g. `happy` etc. Modifying the `$PATH` seems reasonable.

**Comment by mgsloan** [comment]
Yes, it's really just a matter of whether these directories are going on the front or end of the `PATH`, and I think it'd be consistent for them to be put on the front.

**Comment by snoyberg** [comment]
We've removed the solver support in #4670
