### ISSUE TITLE
stack test with detailed-0.9 fails (executable not found)

### ISSUE THREAD

**Issue by michaxm** [commercialhaskell/stack#1429]
Hi,

stack test does not execute the detailed-0.9 test suite, see minimal example (including working instructions for cabal-install):
https://github.com/michaxm/test-detailed-example

> stack test
Test suite test-detailed-example-test executable not found for test-detailed-example
Test suite failure for package test-detailed-example-0.1.0.0
    test-detailed-example-test:  executable not found

Tested with 1.6 and current master, same result:
> stack --version
Version 0.1.6.0, Git revision e22271f5ce9afa2cb5be3bad9cafa392c623f85c (2313 commits) x86_64
> ~/projects/stack/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0/build/stack/stack --version
Version 0.1.9.0, Git revision 1482c5c52a59c7a6f607570c65be5dc3f0387bcf (2663 commits) x86_64

**Comment by michaxm** [comment]
related to  #1399 ?

**Comment by mgsloan** [comment]
Yes, likely the same bug.  I think it's worthy of a hotfix.

Closing as a duplicate, please reopen if this also happens with master version.  You can

**Comment by luigy** [comment]
@mgsloan I don't think stack supports detailed-0.9 tests currently.
The process is a bit different and I'm surprised it took this long to come up unless I'm totally misinterpreting the code xD

In a detailed-0.9 test when searching for the test executable it should have "Stub" appended to name & dir and it should pass [this](https://github.com/haskell/cabal/blob/e99ed843539efd868af593c0c9e4c51d1defaf39/Cabal/Distribution/Simple/Test/LibV09.hs#L104) in to have the test "run"

This will require knowing the `TestSuiteInterface` (from the cabal file unless we have this information ready somewhere else already) to run the test with the correct behavior

I can take this one if no one else is up

**Comment by mgsloan** [comment]
Ah, yes, you're right.  Thanks for the repro @michaxm , somehow I missed the bit where you mentioned it also reproing on master.

@luigy Sure, a PR for this would be great!

**Comment by luigy** [comment]
pushed first working stab

ping @mgsloan for feedback
