### ISSUE TITLE
stack --ghc-version 7.8.4

### ISSUE THREAD

**Issue by gfixler** [commercialhaskell/stack#1432]
I'm not sure this even makes sense (and I'd like to understand why it doesn't, if it doesn't), but it was the main thing I wanted to use stack for, and it surprised me that this wasn't one of its big features. I don't use Haskell for work, and don't tend to do a lot with packages, nor make my own packages, so I rarely care what plays well together. I just use Haskell atm for learning FP and the language itself, and also for teaching and doing demos, especially during meetups and at my work. I tend to use a mix of GHCi and runhaskell. For 2 years now I've basically never used ghc itself (a few times, here and there).

I was glad when the FTP hit, but I'd also like to use 7.8.4 sometimes when I just want the simpler types for didactic purposes. This lead me to search for an easy to way to say "Launch ghci at version 7.8.4," but I found it required looking up LTS versions for stack instead. I really just always want whatever the latest LTS version is that serves up a particular GHCi. I also sometimes help people on older versions of GHC, and it would be nice to say "Wow, you're still on 7.6.3? Okay, one sec..." and just `stack --ghc-version 7.6.3 ghci` and then start seeing what existed back then in the REPL.

**Comment by mgsloan** [comment]
You probably want `stack ghci --resolver ghc-7.8`.  Unlike the snapshot resolvers, these only specify a compiler version.

Stack doesn't officially support 7.6, but it might work.

**Comment by gfixler** [comment]
I get the following:

    $ stack ghci --resolver ghc-7.8
    Run from outside a project, using implicit global project config
    Using resolver: ghc-7.8 specified on command line
    Compiler version mismatched, found ghc-7.6.3 (x86_64), but expected minor version match with ghc-7.8 (x86_64) (based on resolver setting in /home/gfixler/.stack/global/stack.yaml).
    Try running "stack setup" to install the correct GHC into /home/gfixler/.stack/programs/x86_64-linux/

If I just run `ghci`, I get version 7.6.3, so apparently I have that installed outside of stack. `stack ghci` gives me 7.10.2.

**Comment by mgsloan** [comment]
Right, you do need ghc-7.8 installed.  After you do `stack setup --resolver ghc-7.8` that should work.
