### ISSUE TITLE
stack build fails to pass haskell-gi to cabal

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/stack#1436]
When `haskell-gi` and `haskell-gi-base` are both specified as `extra-deps` in `stack.yaml`:

```
extra-deps:
- haskell-gi-base-0.10
- haskell-gi-0.10.1
- xdg-basedir-0.2.2
```

The project fails to build with:

```
$ stack build
xdg-basedir-0.2.2: configure
xdg-basedir-0.2.2: build
haskell-gi-base-0.10: configure
haskell-gi-base-0.10: build
xdg-basedir-0.2.2: copy/register
haskell-gi-base-0.10: copy/register
haskell-gi-0.10.1: configure
haskell-gi-0.10.1: build
haskell-gi-0.10.1: copy/register
hgitest-0.1.0.0: configure
Configuring hgitest-0.1.0.0...
setup-Simple-Cabal-1.22.4.0-x86_64-linux-ghc-7.10.2: At least the following
dependencies are missing:
haskell-gi -any
```

Note that `stack exec -- ghc-pkg list | grep haskell-gi` only lists `haskell-gi-base-0.10` and not `haskell-gi`.

Steps to reproduce:
* Create a new project with `stack new`.
* Add `haskell-gi` to `build-depends` in the `.cabal` file.
* Add the following to `extra-deps` in `stack.yaml`:
```
- haskell-gi-base-0.10
- haskell-gi-0.10.1
- xdg-basedir-0.2.2
```
* Run `stack build`.

Expected result: The project builds without errors.
Actual result: The project fails to build, see above.

Here's the full project demonstrating the issue: https://github.com/koterpillar/hgitest

**Comment by koterpillar** [comment]
I found that the problem is `haskell-gi` not providing a library, only an executable. Not sure whether this is something either Stack or Cabal can warn about, closing.

**Comment by rvion** [comment]
@koterpillar I wish it would work anyway, could you reopen just to let someone comment about if it's normal or not ?

**Comment by mgsloan** [comment]
This is normal, the error message is occurring while configuring `hgitest`, because it can't find the `haskell-gi` library - see [this cabal issue](https://github.com/haskell/cabal/issues/779).  You probably want to add `haskell-gi` the `build-tools` list in your cabal file.
