### ISSUE TITLE
stack setup ghcjs fails

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1437]
Running `stack  setup --compiler ghcjs-0.1.0.20150924_ghc-7.10.2` with Stack `Version 0.1.9.0, Git revision 1482c5c52a59c7a6f607570c65be5dc3f0387bcf i386` on Windows it proceeds for a while (maybe 30 mins?) then gets stuck. The console says:

    Documentation created: .\dist\doc\html\ghcjs-base\.\index.html
    Creating package registration file:
    C:\Users\NDMIT_~1\AppData\Local\Temp\pkgConf-ghcjs-base-0.1.017178692.0
    Installing library in
    C:\Users\ndmit_000\AppData\Roaming\ghcjs\i386-mingw32-0.1.0.20150924-7.10.2\ghcjs/lib\ghcjs-base-0.1.0.0
    Registering ghcjs-base-0.1.0.0...
    Installed ghcjs-base-0.1.0.0
    Booting GHCJS (this will take a long time) ...

Stack has spawned:

    "C:\Users\ndmit_000\AppData\Local\Programs\stack\i386-windows\ghcjs-0.1.0.20150924_ghc-7.10.2\src\.stack-work\install\279c57b7\bin\ghcjs-boot.exe" "--clean"

There is also a node process with the command line:

    "C:\Program Files\nodejs\node.exe" "C:\Users\ndmit_000\AppData\Roaming\ghcjs\i386-mingw32-0.1.0.20150924-7.10.2\ghcjs\thrunner.js"

Neither of the processes are taking any CPU or have any visible signs of further progress after waiting an hour.

**Comment by mgsloan** [comment]
Perhaps it's related to node version?  See https://github.com/commercialhaskell/stack/issues/1629 / https://github.com/commercialhaskell/stack/issues/1496
