### ISSUE TITLE
Set default STACK_ROOT in windows installer

### ISSUE THREAD

**Issue by mdxbhmt** [commercialhaskell/stack#1443]
Not a big deal since I can install manually, but I'd guess something's wrong  with the path? 

**Steps to reproduce:**
           stack upgrade
**Expected:**
          compiled and upgraded stack
**Actual:**
          File not found

```
[2 of 2] Compiling Main             ( src\main\Main.hs, .stack-work\dist\d96ab9d9\build\stack\stack-tmp\Main.o )
(...)*
gcc.exe: error: CreateProcess: No such file or directory

--  While building package stack-0.1.8.0 using:
      C:\Users\(...)\AppData\Roaming\stack\setup-exe-cache\setup-Simple-Cabal-1.22.4.0-x86_64-windows-ghc-7.10.2.exe --builddir=.stack-work\dist\d96ab9d9\ build lib:stack exe:stack --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

```

(...)\* is a very long list of gcc.exe warnings, not sure if related.

**Comment by mdxbhmt** [comment]
Nevermind, saw the notice about the installer. Sorry!

**Comment by mdxbhmt** [comment]
This happened again on 1.8,  even though I used the installer provided.

It was solved with `set STACK_ROOT=c:\stack_root`

Maybe it's  a good idea to include this in the installer.

**Comment by mpilgrem** [comment]
Closing given the passage of time and because STACK_ROOT is set in the Windows installer.
