### ISSUE TITLE
Modify Stack.Fetch to use the Network.HTTP.Download.Verify module

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#145]
There's already a FIXME in there. The code is pretty well duplicated from what you wrote in .Verify, so the task is simply: use .Verify instead to avoid code duplication.

**Comment by DanBurton** [comment]
I've addressed the comments in #177 via the download-enhancements branch. @snoyberg confirm? Anything else needed for this issue?

**Comment by snoyberg** [comment]
I'll close this, we can follow up on the PR.
