### ISSUE TITLE
stack 0.1.5 fails to build with GHC 7.8

### ISSUE THREAD

**Issue by wwaites** [commercialhaskell/stack#1450]
Apparently not just for me:

    http://matrix.hackage.haskell.org/package/stack#GHC-7.8/stack-0.1.5.0

    Configuring stack-0.1.5.0...
    Building stack-0.1.5.0...
    Preprocessing library stack-0.1.5.0...
    [ 1 of 69] Compiling Data.Set.Monad   ( src/Data/Set/Monad.hs, dist/dist-sandbox-e3575889/build/Data/Set/Monad.o )
    [ 2 of 69] Compiling Data.Attoparsec.Combinators ( src/Data/Attoparsec/Combinators.hs, dist/dist-sandbox-e3575889/build/Data/Attoparsec/Combinators.o )
    [ 3 of 69] Compiling Network.HTTP.Download.Verified ( src/Network/HTTP/Download/Verified.hs, dist/dist-sandbox-e3575889/build/Network/HTTP/Download/Verified.o )

    src/Network/HTTP/Download/Verified.hs:205:17:
        Couldn't match expected type ‘Control.Retry.RetryStatus -> IO a0’
                    with actual type ‘IO ()’
        In the second argument of ‘($)’, namely
          ‘flip runReaderT env $ withResponse req (go h)’
        In a stmt of a 'do' block:
          recovering drRetryPolicy handlers
          $ flip runReaderT env $ withResponse req (go h)
        In the expression:
          do { recovering drRetryPolicy handlers
               $ flip runReaderT env $ withResponse req (go h) }
    Failed to install stack-0.1.5.0
    cabal: Error: some packages failed to install:
    stack-0.1.5.0 failed during the building phase. The exception was:
    ExitFailure 1

This is produced from a reasonably clean environment:

    % rm -rf ~/.cabal ~/.cabal-sandbox ~/.ghc
    % rehash
    % cabal update
    % cabal install cabal-install
    % rehash
    % cabal sandbox init
    % cabal install stack

There are links to ~/.cabal/bin/cabal in ~/bin so after the second "rehash" this is the
current version of cabal that is being run.

This is the Haskell version in question:

    % ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.3

Versions >= 0.1.6 also do not build because of a dependency on a 
certain version of TemplateHaskell that requires base >= 4.8.

It is quite important to retain support for GHC 7.8 for a while because it will
be some time before 7.10 is in enough operating system distributions to be
considered ubiquitous. Until then, requiring a new version of GHC in order
to build and install stack undermines the main purpose of having a convenient
way to repeatably build and install software. As well the places that are 
likely to have not-quite-bleeding-edge versions of GHC can often be places
where users will not have root access to install software (such as computer
science departments at some universities).

**Comment by borsboom** [comment]
I've relaxed the lower version bound for `template-haskell` on Hackage (and also tightened the bounds for `retry` with stack-0.1.5.0).  You should be able to build with GHC 7.8 now.

This makes me wonder if it was wise to start using `--pvp-bounds=both` when uploading `stack` to Hackage.  It would have prevented the problem with building stack-0.1.5.0 (since that was due to missing upper bound on `retry`), but caused the problem building stack-0.1.6.0 and later (due to the too-restrictive lower bound on `template-haskell`).  On balance, I think sticking with `--pvp-bounds=both` is good, but we should configure Travis to catch problems like this earlier (it currently uses the `stack.cabal` from the repo rather than the `stack.cabal` that would be uploaded to Hackage).

**Comment by borsboom** [comment]
I've updated Travis to use the `stack.cabal` generated by `stack sdist --pvp-bounds=both` now, so in future this kind of problem will be caught before it hits Hackage.

I can't seem to get the [Hackage matrix](http://matrix.hackage.haskell.org/package/stack) to let me queue another build (it rejects my Hackage username/password), so I can't be certain that my metadata revisions resolve all problems there, but I think they should.

**Comment by simonmichael** [comment]
Thanks! I think you need to be an admin for that - just ask on #hackage and they'll queue it.

**Comment by wwaites** [comment]
Works for me now:

    % ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.3
    % stack --version
    Version 0.1.5.0 X86_64

thank you!

**Comment by borsboom** [comment]
Looks like the [Hackage Matrix Builder](http://matrix.hackage.haskell.org/package/stack#GHC-7.8/stack-0.1.10.0) is still failing with GHC 7.8:

```
During interactive linking, GHCi couldn't find the following symbol:
  templatezmhaskell_LanguageziHaskellziTHziSyntax_zdfMonadQzuzdczgzgze_closure
```

I've investigated, and written up the likely cause here: https://github.com/commercialhaskell/stack/issues/1351#issuecomment-162186143
