### ISSUE TITLE
Consider allowing flags to be set for all local packages

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#1452]
It is now possible to set `ghc-options` for all packages or just selected ones. The original reason why cabal flags can't be set for all packages is to avoid having too many copies of snapshot packages and because flags have no agreed global meaning. However, within the scope of a single multi-package project, there very much _can_ be a project-global meaning for a given flag name. And it can be tedious to have to override flag selection on the command line one-by-one for each package in a large project.

So this ticket is to propose allowing:

```
flags:
  "*":
    flag-name: true
```

As is currently the case, this would _not_ apply to snapshot packages. Only local packages. All of them...

**Comment by mgsloan** [comment]
Makes sense to me!  How would this look on the commandline?  I'm thinking it'd be consistent with the `:component` target syntax to use the CLI syntax `--flag :flag-name`.

**Comment by snoyberg** [comment]
This is supported via `$locals`
