### ISSUE TITLE
Recommended way to remove extra dips for global

### ISSUE THREAD

**Issue by fatlazycat** [commercialhaskell/stack#1454]
I install the toolchain using a global stack yaml file.

If I put in things such as 

- Strafunski-StrategyLib-5.0.0.8
- ghc-mod-5.4.0.0
- rosezipper-0.2
- syz-0.2.0.0

to build HaRe, what should I do if I want to change the version of one of the extra-deps ?

Wipe it all out ? Remember to unregister ? Should I have made a local copy of the tool and installed it that way ?

Thanks

**Comment by mgsloan** [comment]
> Wipe it all out ? Remember to unregister ? Should I have made a local copy of the tool and installed it that way ?

None of this is necessary.  Just modify the exta-deps and rebuild.

**Comment by fatlazycat** [comment]
Great thanks !
