### ISSUE TITLE
Strange `stack setup` behaviour when `DESTDIR` is set

### ISSUE THREAD

**Issue by ehamberg** [commercialhaskell/stack#1460]
Calling `stack setup`, with `DESTDIR` set fails since it will end up being installed in `$DESTDIR$HOME/.stack/programs/x86_64-linux/ghc-7.10.2/`. This happened on a CI server that called `make DESTDIR=$BUILD_DIR install` and relied on the fact that the `install` target was calling other targets that eventually called `stack setup`.

Here's what happens on Debian 8.2 for a user with `HOME=/var/lib/buildkite-agent`:

    $ rm -rf ~/.stack/
    $ DESTDIR=/tmp/test stack setup
    Downloaded lts-3.16 build plan.
    Caching build plan
    Fetched package index.
    Populated index cache.
    Preparing to install GHC to an isolated location.
    This will not interfere with any system-level installation.
    Downloaded ghc-7.10.2.
    Installed GHC.
    Executable named ghc not found on path: ["/var/lib/buildkite-agent/.stack/programs/x86_64-linux/ghc-7.10.2/bin","/usr/local/bin","/usr/bin","/bin","/usr/local/games","/usr/games"]
    $ ls var/lib/buildkite-agent/.stack/programs/x86_64-linux/ghc-7.10.2/
    bin  lib  share

Note that the install ends up in `$DESTDIR$HOME` which here is `/tmp/test/var/lib/buildkite-agent`.

(This was solved by changing the build to be `make && make DESTDIR=$BUILD_DIR install` so that `DESTDIR` is only set for the `install` target.)

**Comment by ehamberg** [comment]
To clarify: Even if `stack setup` is meant to honour `DESTDIR` (is it?), it looks like the files end up being installed into `$DESTDIR$HOME`, which to me looks like it's definitely a bug.

**Comment by mgsloan** [comment]
I don't think `stack setup` is meant to honour `DESTDIR`, that's part of the ghc makefile.  I think we should filter this from the environment when installing GHC, and possibly other env vars.

So in your particular case, during build, other makefiles get invoked which use `DESTDIR`?  Or does `cabal-install` use `DESTDIR` (doesn't afaict).

**Comment by ehamberg** [comment]
> So in your particular case, during build, other makefiles get invoked which use DESTDIR? Or does cabal-install use DESTDIR (doesn't afaict).

We specified `DESTDIR` ourselves when calling `make` from our build server. On a fresh server, where `stack setup` was called, this would lead to it being set for that invocation, making `stack setup` fail.

**Comment by borsboom** [comment]
Sounds like we should just remove DESTDIR from the environment when installing GHC.

**Comment by mgsloan** [comment]
That sounds like a good resolution to me!  It should warn about unsetting the env var, incase the user is doing it intentionally.

**Comment by mgsloan** [comment]
Fixed!  Feel free to re-open if not.
