### ISSUE TITLE
stack does not say which were the invalid flags

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1461]
In the nested submodes, Stack doesn't say what flags are invalid, which is a pain:

      C:\Neil\shake>stack --version
      Version 0.1.9.0, Git revision c7178d4d7fa779aafc67a2b48485d01b9435739f i386

      C:\Neil\shake>stack build --foo=1
      Usage: stack build [TARGET] [--library-profiling] [--executable-profiling]
                         [--haddock] ([--haddock-deps] | [--no-haddock-deps])
                         [--dry-run] [--pedantic] [--fast] [--ghc-options OPTION]
                         [--flag PACKAGE:[-]FLAG] [--copy-bins] [--prefetch]
                         ([--dependencies-only] | [--only-snapshot] |
                         [--only-dependencies]) ([--file-watch] | [--file-watch-poll])
                         ([--keep-going] | [--no-keep-going]) [--force-dirty] [--test]
                         [--no-rerun-tests] [--test-arguments TEST_ARGS] [--coverage]
                         [--no-run-tests] [--bench] [--benchmark-arguments BENCH_ARGS]
                         [--no-run-benchmarks] [--exec CMD [ARGS]] [--only-configure]
                         [--reconfigure] [--cabal-verbose] [--help]
        Build the package(s) in this directory/configuration

**Comment by drwebb** [comment]
I submitted this as an issue on optparse-applicative's issue tracker, it was fixed in a recent commit.

https://github.com/pcapriotti/optparse-applicative/issues/164

**Comment by HuwCampbell** [comment]
Upgrading to optparse 12.1 should fix this issue.

**Comment by mgsloan** [comment]
Stack now uses `optparse-applicative-0.12.1.0`

```
mgsloan@computer:~/fpco/stack$ stack build --foo=1
Invalid option `--foo=1'

Usage: stack build [--trace] [--profile] [TARGET] [--[no-]library-profiling]
                   [--[no-]executable-profiling] [--[no-]haddock]
                   [--[no-]haddock-deps] [--dry-run] [--pedantic] [--fast]
                   [--ghc-options OPTION] [--flag PACKAGE:[-]FLAG]
                   [--[no-]copy-bins] [--prefetch] ([--dependencies-only] |
                   [--only-snapshot] | [--only-dependencies]) ([--file-watch] |
                   [--file-watch-poll]) [--[no-]keep-going] [--force-dirty]
                   [--[no-]test] [--[no-]rerun-tests]
                   [--test-arguments TEST_ARGS] [--coverage] [--no-run-tests]
                   [--[no-]bench] [--benchmark-arguments BENCH_ARGS]
                   [--no-run-benchmarks] [--exec CMD [ARGS]] [--only-configure]
                   [--reconfigure] [--cabal-verbose] [--help]
  Build the package(s) in this directory/configuration
```
