### ISSUE TITLE
unrecognized option `--dependency=array=array-0.5.0.0-ce080a527b3819e94d851f7f80ca77dd'

### ISSUE THREAD

**Issue by mwu-tow** [commercialhaskell/stack#1464]
I use latest released `stack` — `Version 0.1.8.0 x86_64`

When building the package that depends transitively on `pango` it fails with the following error:
```
--  While building package pango-0.13.1.0 using:
      /home/krzys/dev/farm/barn1/flowbox/third-party/gtk2hs/pango/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 configure --with-ghc=/usr/bin/ghc --with-ghc-pkg=/usr/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/krzys/.stack/snapshots/x86_64-linux/lts-2.22/7.8.4/pkgdb --package-db=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/pkgdb --libdir=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/lib --bindir=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/bin --datadir=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/share --libexecdir=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/libexec --sysconfdir=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/etc --docdir=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/doc/pango-0.13.1.0 --htmldir=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/doc/pango-0.13.1.0 --haddockdir=/home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/install/x86_64-linux/lts-2.22/7.8.4/doc/pango-0.13.1.0 --dependency=array=array-0.5.0.0-ce080a527b3819e94d851f7f80ca77dd --dependency=base=base-4.7.0.2-cb23b5265b6e147094c0cd9ac819acb1 --dependency=cairo=cairo-0.13.1.0-9f1735045cd577b67e3dcb90384ac8e5 --dependency=containers=containers-0.5.5.1-d7910f1cd81272c1f31ca9f71d0f206e --dependency=directory=directory-1.2.1.0-1b239651bf547478c9e952c1e47c8fbe --dependency=glib=glib-0.13.2.1-90cbbe46c71a0e27d523dc717d2ef6f4 --dependency=mtl=mtl-2.1.3.1-96f1a7910a7553352339ed05fb61c269 --dependency=pretty=pretty-1.1.1.1-0984f47ffe93ef3983c80b96280f1c3a --dependency=process=process-1.2.0.0-ac5f66ef47c8e6680cd098551063b07c --dependency=text=text-1.2.1.1-7eaa47815a996f8fd6cdfc4eb431a601 --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/krzys/dev/farm/barn1/flowbox/dist/graphics-build/.stack-work/logs/pango-0.13.1.0.log

    unrecognized option `--dependency=array=array-0.5.0.0-ce080a527b3819e94d851f7f80ca77dd'
    
    unrecognized option `--dependency=base=base-4.7.0.2-cb23b5265b6e147094c0cd9ac819acb1'
    
    unrecognized option `--dependency=cairo=cairo-0.13.1.0-9f1735045cd577b67e3dcb90384ac8e5'
    
    unrecognized option `--dependency=containers=containers-0.5.5.1-d7910f1cd81272c1f31ca9f71d0f206e'
    
    unrecognized option `--dependency=directory=directory-1.2.1.0-1b239651bf547478c9e952c1e47c8fbe'
    
    unrecognized option `--dependency=glib=glib-0.13.2.1-90cbbe46c71a0e27d523dc717d2ef6f4'
    
    unrecognized option `--dependency=mtl=mtl-2.1.3.1-96f1a7910a7553352339ed05fb61c269'
    
    unrecognized option `--dependency=pretty=pretty-1.1.1.1-0984f47ffe93ef3983c80b96280f1c3a'
    
    unrecognized option `--dependency=process=process-1.2.0.0-ac5f66ef47c8e6680cd098551063b07c'
    
    unrecognized option `--dependency=text=text-1.2.1.1-7eaa47815a996f8fd6cdfc4eb431a601'
```

It seems that stack badly formats the dependencies.
Interestingly a number of other dependencies before has correctly build.

Note: I have recently upgraded Cabal on the compiler with `stack setup 7.8.4 --upgrade-cabal` to recently released 1.22.5.0 version, not sure if that could've break something. The OS is Fedora 20.
The same package builds fine on my Windows machine. I don't have good repro scenario now, please let me know if you need more info.

**Comment by mgsloan** [comment]
Hmm, this is a strange bug indeed.  The formatting of those options seems fine.  Glancing at the rest of the arguments, those seem fine too..

I can't reproduce the issue with the following versions:

* `ghc-7.10.2` + `Cabal-1.22.4.0`
* `ghc-7.8.4` + `Cabal-1.22.4.0`

It'd be quite surprising if this is caused by the bump from `1.22.4.0` to `1.22.5.0`, but stranger things have happened.

**Comment by mwu-tow** [comment]
Update from my side:
`stack` indeed does not seem to be at fault here. I observed the same issue happening with `cabal-install`. It happened with `pango` package once again, all other dependencies (~100 packages) built fine. Likely it has something to do with how `pango`'s `Setup.hs` is built.

It happened only on one of the several machines where we ran the build. I found that this machine had installed cabal (and some other Haskell tools, like alex) using the Fedora's package manager. That were very old version of packages (Cabal 1.14 or something like that).

I have no idea how that could affect build. Still, after we removed them, the said error did not happen never again. I'm not even sure if that was the real reason behind the issue… but that's the best explanation I got. The issue is not reproducible to me anymore and I really don't want to try.

Unless you have some idea what could have gone wrong, you can close this issue.

**Comment by mgsloan** [comment]
Cool, thanks for the additional info.  It'd be good to resolve the issue in cabal, maybe open an issue there?  Though I realize that's tricky since the repro is fuzzy.
