### ISSUE TITLE
Remove specific warning permanently? (stack runghc)

### ISSUE THREAD

**Issue by Korpen** [commercialhaskell/stack#1468]
Is there some way to permanently remove the Tab character warning? 
"Warning: Tab character"

I prefer using tabs over spaces and so far I have not encountered any problems with using tabs. Is there some reason as to why this would be stupid and if not, is there some way to permanently remove those warnings?

Thanks

PS. If the answer is in one of your docs or some other place and I have just been unable to find them I apologize for the unneccesary issue and I would greatly appreciate a nudge in the right direction.

**Comment by mgsloan** [comment]
This is a warning generated by ghc rather than stack.  Add the following to your stack.yaml to disable the tab character warning:

```yaml
ghc-options:
  "*": -fno-warn-tabs
```
