### ISSUE TITLE
Assume verbosity as silent when invoked in interpreter mode

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1472]
Please refer to #1394 for the original discussion.

* Currently stack prints some output of its own before running the script:

> Run from outside a project, using implicit global project config
> Using resolver: lts-3.14 from implicit global project's config file: /var/home/harendra/.stack/global-project/stack.yaml

When used as interpreter no other output is desirable other than the script's output itself. In fact this should hold true for any _stack exec_ command. That might interfere with the processing of the script output.

We can fix this by assuming `--verbosity silent` when invoked as interpreter.

**Comment by mgsloan** [comment]
Yup, makes sense to me! Thanks for opening an issue

**Comment by sjakobi** [comment]
This just bit me, when I tried to do some simple timings with a script and see what stack internally does.

I ended up running `stack -v runghc script.hs` but I'm not entirely sure it does the same thing.

Wouldn't it be enough to have `--verbosity silent` as default but make it overrideable?

**Comment by harendra-kumar** [comment]
I am closing this. Let's keep track of fixing the override issue in #2343.
