### ISSUE TITLE
Proper support for names with apostrophes

### ISSUE THREAD

**Issue by liamoc** [commercialhaskell/stack#1475]
My name has an apostrophe in it, which is parsed just fine by Cabal in cabal files, but Stack seems to HTML escape it when generating license files, cabal files, etc. This is quite annoying as I have to change the `&#39;` back to an apostrophe in all these files.

**Comment by mgsloan** [comment]
Ouch, looks like hastache defaults to html escaping.  Fixed!

Now time to change my `author-name` back, was fun being Michael O'Sloan for a bit ;)
