### ISSUE TITLE
Problem with stack upgrade

### ISSUE THREAD

**Issue by FranklinChen** [commercialhaskell/stack#1477]
I am using an ancient Mac OS X laptop where the Stack dependency `cryptonite` requires me to pass a custom flag to Cabal https://github.com/haskell-crypto/cryptonite/issues/21 but I don't know how to pass this flag to `stack upgrade`. (Note that this laptop is sufficiently old that I cannot just download and use the prebuilt binary for Stack for more modern OS X, but have to build Stack from source.)  Without the flag, I cannot do `stack upgrade`.

How do I hook in the config into `stack upgrade`?

```
  cryptonite:
    support_aesni: false
```

**Comment by luigy** [comment]
hmm I don't think there is support for that but I always build my `stack` executable from repo clone and another alternative would also be to use `stack unpack`:
```sh
stack unpack stack-0.1.10.0
cd stack-0.1.10.0
# make your modifications to stack.yaml
stack install
```
you wouldn't have to use package version to it have always download latest (ala stack upgrade) but currenlty stack would pick up deprecated versions #1391

**Comment by mgsloan** [comment]
It wouldn't be too strange to add the `build` options to `upgrade`.  At once, I like that `stack upgrade --help` is so simple.  Adding all the build options would make it more complicated.

I'm thinking that for this (hopefully) rare case, @luigy's solution is sufficient.  So, closing as wontfix.

**Comment by FranklinChen** [comment]
Yeah, this is a rare case. I've been building from source this whole time so it's not a showstopper that `stack upgrade`.

**Comment by FranklinChen** [comment]
For reference, in case anyone needs a bootstrapped `stack` executable for old Mac OS X, I put one up: https://github.com/FranklinChen/haskell-stack-for-old-mac-os-x
