### ISSUE TITLE
Add stack version requirement to stack.yaml

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#148]
Motivation: a team could have a stack.yaml file in their project that would force the team to update. Ties in with #74

**Comment by manny-fp** [comment]
@snoyberg confirmed?

**Comment by snoyberg** [comment]
Two things:

1. Can you add a description of this to https://github.com/commercialhaskell/stack/wiki/stack.yaml ?
2. In the `Monoid` instance, instead of simply taking the latest version range, I'd recommend using `intersectVersionRanges` so that we get the requirements from all stack.yaml files being used. It may make sense to get rid of the `Maybe` wrapping and default to `anyVersion` in that case.

**Comment by manny-fp** [comment]
@snoyberg Alright, now it uses `intersectVersionRanges`.  And this time I've pushed my change to stack.yaml.md.

**Comment by snoyberg** [comment]
Awesome!
