### ISSUE TITLE
Running Stack from an independent install of MSYS2 can results in errors like "/usr/bin/rm: missing operand"

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/stack#1482]
To reproduce:
- clone the msys-draft branch of enolan/Idris-dev
- With MSYS2 installed, run C:\msys64\mingw64_shell.bat
- make sure you have `make binutils msys2-w32api-runtime mingw-w64-x86_64-gcc mingw-w64-x86_64-pkg-config mingw-w64-x86_64-libffi perl` from the MSYS2 pacman
- cd into the Idris-dev directory
- stack build --verbose

Relevant section of log is:

```
2015-12-09 12:13:41.663419: [info] make: Entering directory '/c/Users/Echo/Idris-dev/rts' @(stack_FTGa6UJ1S63F2CVTFkcIz4:Stack.Build.Execute src/Stack\Build\Execute.hs:1310:35)
2015-12-09 12:13:41.675419: [info] rm -f idris_rts.o idris_heap.o idris_gc.o idris_gmp.o idris_bitstring.o idris_opts.o idris_stats.o idris_utf8.o idris_stdfgn.o mini-gmp.o getline.o windows/idris_net.o windows/win_utils.o libidris_rts.a  @(stack_FTGa6UJ1S63F2CVTFkcIz4:Stack.Build.Execute src/Stack\Build\Execute.hs:1310:35)
2015-12-09 12:13:41.692420: [warn] /usr/bin/rm: missing operand @(stack_FTGa6UJ1S63F2CVTFkcIz4:Stack.Build.Execute src/Stack\Build\Execute.hs:1310:35)
```

I think rm is called with no arguments despite make claiming to call it with `-f idris_rts.o ...`. If I run `stack exec make -- -C rts clean IDRIS=idris` (which is what Idris' custom `Setup.hs` calls) I get the same thing. However, if I run `stack exec make --plain -- -C rts clean IDRIS=idris` it works fine. So it has something to do with environment variables? [Here are the environment variable from `stack exec` and `stack exec --plain`.](https://gist.github.com/enolan/52cfcc0a0e9e1fe66ce6)

Expected behavior is to build successfully, or at least get farther. I have the same problem later in the build when it calls `mkdir -p $PATH_TO_RTS_INSTALL_DIR`. I'm in the process of fixing up the Windows build.

**Comment by enolan** [comment]
Oh,
```
Echo@Behemoth-W7 MINGW64 ~/Idris-dev
$ stack --version
Version 0.1.10.0, Git revision a25892f8374d4bcbed6dd0f0c3bcb6cb93df490c (2778 commits) x86_64
```
I got this from [the Windows 64 bit installer](https://www.stackage.org/stack/windows-x86_64-installer)

**Comment by mgsloan** [comment]
I suspect it has something to do with http://stackoverflow.com/questions/10870666/cygwin-difference-between-rm-fr-and-rm-fr-command

Relevant line of the Makefile: https://github.com/idris-lang/Idris-dev/blob/ed5ecbccb906cd45b163575bd16c6e138180c094/rts/Makefile#L42

**Comment by enolan** [comment]
That sounds likely, but unfortunately adding a backslash to the makefile doesn't help, and:
```
Echo@Behemoth-W7 MINGW64 ~/Idris-dev
$ stack exec bash -- -c "type -a rm"
rm is /usr/bin/rm
rm is /c/msys64/usr/bin/rm
rm is /c/msys64/usr/bin/rm

Echo@Behemoth-W7 MINGW64 ~/Idris-dev
$ stack exec bash --plain -- -c "type -a rm"
rm is /usr/bin/rm
rm is /usr/bin/rm

Echo@Behemoth-W7 MINGW64 ~/Idris-dev
$ sha1sum.exe /usr/bin/rm.exe /c/msys64/usr/bin/rm.exe
45a5d8068e3b10b356c8841edd80856d2ec0d217 */usr/bin/rm.exe
45a5d8068e3b10b356c8841edd80856d2ec0d217 */c/msys64/usr/bin/rm.exe
```

The first alternative for rm is the same, and all the alternatives are the same file.

**Comment by enolan** [comment]
Okay, I figured this out. Multiple independent installations of MSYS2 do not play well together at all. What was happening is that Stack was launching the copy of Make from the MSYS2 install in C:\msys64, which in turn launched rm, mkdir etc from C:\Users\Echo\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512 which causes the problem. Stack should probably completely rewrite %PATH% so it's impossible to accidentally run programs from the wrong MSYS2.

To reproduce:
- install MSYS2 from [here](https://msys2.github.io/)
- launch "MSYS2 Shell" from the Start menu
- `pacman -S make`
- (if you have it) `stack exec -- pacman -R make`
- `mkdir foo`
- place a trivial Makefile in it
- `stack exec make`

[Here's a log](https://gist.github.com/enolan/8c24ad877e37c4067ca8).
