### ISSUE TITLE
Allow overriding nix section options on command-line

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#1483]
Currently, `stack --nix-help` gives one command line option I can play with, `--nix-shell-options`. But I can't override packages or the name of a shell file, much in the way I can override pretty much any Docker option on the command line. We should have:

* `--nix-packages`
* `--nix-shell-file`

**Comment by YPares** [comment]
See commit 41de6fc17bfdf9c4f2950f9c9045ef4928e5d16a which adds these features.
