### ISSUE TITLE
Not a bug - stack twitter account

### ISSUE THREAD

**Issue by yamafaktory** [commercialhaskell/stack#1484]
I just noticed that stack recently got a new [domain name](http://haskellstack.org) (please enable https!). I also noticed that the matching twitter account, i.e. `haskellstack` was still available. In order to avoid to find another great tool attached to some random crappy thing on twitter, I just created this account: [https://twitter.com/haskellstack](https://twitter.com/haskellstack).

I have no personal use for it and just want to give it to the community!

**Comment by snoyberg** [comment]
If you'd like to transfer this to me, please reach out on Twitter with a DM. I'm snoyberg there too.
