### ISSUE TITLE
Prevent extra-deps / packages from overriding GHCJS boot packages

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1486]
Related to https://github.com/ghcjs/ghcjs/issues/434

**Comment by tolysz** [comment]
My solution would be to:
redo `ghcjs-boot` with the `extra` packages set if they are used in the boot; then filter them from the extra section in `stack.yaml`
Still looking hard how to boot ghcjs purely on the packages from stackage (+ patches); 

For sure we might need some extra resolver just for booting `ghcjs-boot-lts-3.17.yaml`
So we can keep sane collections of bootable set.

This will require splitting the setup phase into 2 sections:
1) install ghcjs
2) boot it with a suitable `-B` directory.

**Comment by mgsloan** [comment]
@tolysz Thanks for the input.  I should have made the issue clearer.

The idea is to detect the circumstance where something bad will happen due to using an unpatched ghcjs package, and error out in this case.  It might need to be just a noisy warning when it's a local package, though, as the user might have a patched version in that case.

**Comment by mgsloan** [comment]
Here's how I think this should work:

* Ensure that the patched packages (+ deps) come from the global DB.  This is the list from [this closed PR](https://github.com/commercialhaskell/stack/pull/1514).  Throw errors if they're found in other DBs.

* Throw errors if the user attempts to override these packages with hackage versions.  Perhaps warn when they attempt to override some other way (local package, git repo)?

* Allow any boot package to differ from the version specified by the snapshot.  This means that you can use the booted `ghcjs-base` without having it in your packages list.

I haven't fully thought out the ramifications of this change.  In particular, the case of installing a custom ghcjs-base and updating the other deps seems tricky.

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
