### ISSUE TITLE
GHC 7.10.3 has been released

### ISSUE THREAD

**Issue by wismill** [commercialhaskell/stack#1488]
Hi, GHC 7.10.3 [has been released](https://www.haskell.org/ghc/download_ghc_7_10_3). It notably solves important issues for Windows users.

Could `stack` and its ecosystem be updated to use it? For instance, `stack setup 7.10.3` returns `No information found for ghc-7.10.3.`

```
stack --version
Version 0.1.11.0, Git revision a874a3bd9f834fa0cdbbfd50c8d0373c221a820b (dirty) (2810 commits) x86_64```

**Comment by k-bx** [comment]
Also, nothing builds with 7.10.3 installed currently, as snapshots are for 7.10.2:

```
root@main:~/tmp/ghcver# stack build --resolver=nightly-2015-12-10
Downloaded nightly-2015-12-10 build plan.
Caching build plan
Compiler version mismatched, found ghc-7.10.3 (arm), but expected minor version match with ghc-7.10.2 (arm) (based on resolver setting in /root/tmp/ghcver/stack.yaml).
Try running "stack setup" to install the correct GHC into /root/.stack/programs/arm-linux/
```

**Comment by borsboom** [comment]
The [compiler-check option](http://docs.haskellstack.org/en/stable/yaml_configuration.html#compiler-check) will let you override the default behaviour.  If you add `compiler-check: newer-minor` to your project's stack.yaml or ~/.stack/config.yaml, it'll use ghc-7.10.3 if it's installed.  You can use `stack setup 7.10.3` to install GHC 7.10.3.

**Comment by borsboom** [comment]
Also, see https://github.com/fpco/stackage/issues/1029#issuecomment-163347439 for more information about the plans for Stackage snapshots.  Basically, sounds like nightly and LTS 3 snapshots will be upgrading to GHC 7.10.3 as soon as possible (i.e. if all packages build and pass their tests).

**Comment by k-bx** [comment]
Ok, thank you!
