### ISSUE TITLE
Print out less severe wording when running GHCi outside project

### ISSUE THREAD

**Issue by asampal** [commercialhaskell/stack#1494]
When running `stack ghci` outside a project directory I get the following output:
```
$ stack ghci
Run from outside a project, using implicit global project config
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?
Warning: build failed, but optimistically launching GHCi anyway
Configuring GHCi with the following packages:
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
Ok, modules loaded: none.
Prelude>
```
This sounds kind of harsh, IMO. I would suggest that if it's pretty clear stack isn't in a project directory, the message "Error parsing targets: The specified targets matched no packages." up to "Warning: build failed, but optimistically launching GHCi anyway" should not be output. 

Instead, something like "It seems this is not a project directory, but launching GHCi anyway. If this location is intended to be a project directory, perhaps you need to run 'stack init'.", or something of that nature would be friendlier.

**Comment by mgsloan** [comment]
Agreed.  I'm guessing this message comes from the build step, and likely happens because `stack build` doesn't make sense outside of a project.

**Comment by mgsloan** [comment]
Fixed - see https://github.com/commercialhaskell/stack/issues/2176
