### ISSUE TITLE
Clearly document the distinction between local packages and dependencies

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1501]
Split off from #1217.  Should be done after #863, #849, and #1265, as those will change things a bit.

It would also be good to consider terminology.  I use the term "local packages" for the non-dependencies in `packages`, but perhaps they should be referred to as "project packages".

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and the changes to the online documentation in the interim.
