### ISSUE TITLE
stack seems to ignore system ghc when ~/.stack/programs/ exists?

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#1512]
Not sure if this is a "feature" but stack seems to ignore system installed ghc after setting up a user ghc version with "stack setup":

```
$ rpm -q ghc
ghc-7.8.4-46.fc23.x86_64
$ stack install yi
Run from outside a project, using implicit global project config
Using resolver: lts-2.18 from implicit global project's config file: /home/petersen/.stack/global/stack.yaml
Compiler version mismatched, found ghc-7.10.2 (x86_64), but expected minor version match with ghc-7.8.4 (x86_64) (based on resolver setting in /home/petersen/.stack/global/stack.yaml).
Try running "stack setup" to install the correct GHC into /home/petersen/.stack/programs/x86_64-linux/
```

Well I guess workaround/fix is simple enough but I'd really like to be able to continue using the system installed ghc version with stack without having it to re-install it under `~/.stack/programs/`.
(I didn't try to look at the related stack code yet, so not sure if this is an oversight or by design.)

**Comment by mgsloan** [comment]
I've tried some to reproduce this issue, but haven't gotten it to ignore the system ghc.  So, a few questions:

Does using the flag `--system-ghc` fix it?

Hmm, what do `which ghc` and `ghc --version` yield?  Also ghc 7.8?

Similarly, what do  `stack exec -- which ghc` and `stack exec -- ghc --version` yield?

**Comment by juhp** [comment]
My apologies: user error on my part...
I had forgotten I had ghc-7.10.2 installed in `~/.local/bin/ghc`.
