### ISSUE TITLE
stack setup on OSX El Capitan fails with --version: command not found

### ISSUE THREAD

**Issue by smoothdeveloper** [commercialhaskell/stack#1515]
I'm trying to run stack setup to install ghc under OSX El Capitan but it results with this output:

```
$ stack setup
Run from outside a project, using implicit global project config
Using resolver: lts-3.18 from implicit global project's config file: /Users/tejasvinee/.stack/global-project/stack.yaml
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                 
Configuring GHC ...Running /private/var/folders/nq/2r9cgdrn5d538hjt7dmydgfc0000gn/T/stack-setup526/ghc-7.10.2/configure --prefix=/Users/tejasvinee/.stack/programs/x86_64-osx/ghc-7.10.2/ exited with ExitFailure 1
checking for path to top of build tree... /private/var/folders/nq/2r9cgdrn5d538hjt7dmydgfc0000gn/T/stack-setup526/ghc-7.10.2
Build platform inferred as: x86_64-apple-darwin
Host platform inferred as: x86_64-apple-darwin
Target platform inferred as: x86_64-apple-darwin
GHC build  : x86_64-apple-darwin
GHC host   : x86_64-apple-darwin
GHC target : x86_64-apple-darwin
checking for perl... /opt/local/bin/perl
checking for a BSD-compatible install... /opt/local/bin/ginstall -c
checking whether ln -s works... yes
checking for gsed... /opt/local/bin/gsed
checking XCode version... 7.2
configure: XCode version component 1: 7
configure: XCode version component 2: 2
checking for gcc... /opt/local/bin/gcc
checking for llc-3.5... no
checking for llc... no
checking  is version 3.5... no
checking for opt-3.5... no
checking for opt... no
checking  is version 3.5... no
checking for ld... /opt/local/bin/ld
checking for gcc... /opt/local/bin/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... 
/private/var/folders/nq/2r9cgdrn5d538hjt7dmydgfc0000gn/T/stack-setup526/ghc-7.10.2/configure: line 3861: --version: command not found
/private/var/folders/nq/2r9cgdrn5d538hjt7dmydgfc0000gn/T/stack-setup526/ghc-7.10.2/configure: line 4108: --version: command not found
configure: error: in `/private/var/folders/nq/2r9cgdrn5d538hjt7dmydgfc0000gn/T/stack-setup526/ghc-7.10.2':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
```

Any idea what could be wrong with my environment?

**Comment by rvion** [comment]
@smoothdeveloper can you give more infos ?

what are the results of 
```shell
uname -a
```
and
```shell
stack --version
```

**Comment by smoothdeveloper** [comment]
```
$ uname -a
Darwin Tejaswinis-MacBook-Pro.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
$ stack --version
Version 0.1.10.1, Git revision 83ec40fc5fd6d300c73d23deb1f41d30168fc236 (2783 commits) x86_64
```

**Comment by luigy** [comment]
>checking for gcc... /opt/local/bin/gcc

woah looks like some random `gcc` (macports?) is getting in the way.

  
try out the following:
assuming `stack` is found in the following `$PATH` and you have command line tools installed (`xcode-select --install`) 

`PATH=$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin stack setup -v`

**Comment by smoothdeveloper** [comment]
@luigy thanks for heads-up, I'll check as soon as I get the machine at hand.

**Comment by smoothdeveloper** [comment]
@luigy apparently running `xcode-select --install` fixed the issue, the mac was updated recently to this OS and I'm not sure what was the previous version of xcode installed on it.

`stack ghci` and others seems to work, it might seem obvious but I think adding a note under _Using Homebrew_ asking to check that `xcode-select --install` outputs ```xcode-select: error: command line tools are already installed, use "Software Update" to install updates``` might help others facing same situation.

Thanks all for your help!

**Comment by borsboom** [comment]
@smoothdeveloper: would you mind making a PR to add such a note to the docs?

**Comment by davidsiefert** [comment]
I was getting the same error, however I'm on linux.
```
$ uname -a
Linux myhost 4.2.0-23-generic #28-Ubuntu SMP Sun Dec 27 17:47:31 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ stack --version
Version 1.0.0 x86_64
```
I installed clang through nix.

**Comment by davidsiefert** [comment]
Figured it out--my binutils package installed through nix-env was not sufficient for building, so uninstalled and reinstalled through apt-get.  Thanks.

**Comment by smoothdeveloper** [comment]
@borsboom I made a small edit to the documentation #1740 to mention about running `xcode-select --install`

**Comment by mgsloan** [comment]
Cool, I added this formatting commit https://github.com/commercialhaskell/stack/commit/89e03e48ad4c343b9b6235b46a18179f93fe7a0a

**Comment by teuffy** [comment]
Hi
on my side I had the same problem and went and change the settings file in the ghc folder
which ghc -> Path to ghc -- where the settings file is located .. do cp settings settings.back in case 
which gcc -> Path to ghc
Change the line (with emacs - vim ..) where you see the gcc with the path/gcc of the correct installed version of gcc
hope it helps
