### ISSUE TITLE
Provide better error reporting in interpreter mode

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1516]
There are multiple ways in which we can fail while trying to execute a file using stack as interpreter. For example:
* The file may not exist 
* or it may not have a stack comment at expected position 
* or the comment may have an unterminated string 
* or a block comment may be unterminated
* or the command parsing may encounter an error

Currently for all the cases we just provide a single blanket error message. It would be helpful for the users if we could provide better error reporting pointing out the source of error.

**Comment by mgsloan** [comment]
Makes sense.
