### ISSUE TITLE
Installing executables (was: yesod-bin as "extra build tool")

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#153]
## *Is* yesod-bin an "extra build tool"?

From the FAQ:

> **How do I get extra build tools?**
> 
> stack will automatically install build tools *required by your packages* [emphasis mine] or their dependencies, in particular alex and happy.

yesod-bin is not technically required, as anyone can use Yesod libraries without bothering with yesod-bin. However, I want it to be available to my project's contributors with a minimum of fuss. Should stack solve this problem for me?

Self-answer: Yes. I can add yesod-bin as an extra-dep, and then 'stack exec yesod' works. Still, the difference between yesod-bin and e.g. happy are a bit magical to me. Do you just have a list of packages known to need a particular tool? What distinguishes them from tool XYZ, needed to build XYZmabob? Will I still need another build tool on top of stack to solve the general problem? Why don't I have to add 'happy' as an extra-dep?

The following issue seems sufficiently related:

## yesod-bin as extra-dep

After I add yesod-bin to extra-deps and rebuild, the following occurs:

    $ stack exec yesod devel
    Yesod devel server. Press ENTER to quit
    Application can be accessed at:

    http://127.0.0.1:3000
    https://127.0.0.1:3443
    If you wish to test https capabilities, you should set the following variable:
      export APPROOT=https://127.0.0.1:3443

    WARNING: the following source files are not listed in exposed-modules or other-modules:
    ./Handler/About.hs
    ./SnowdriftEmailDaemon.hs
    ./SnowdriftSendmail.hs
    yesod: cabal: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)

**Comment by snoyberg** [comment]
This is now implemented. Some details:

* Running `stack install-exe` will install executables for the "wanted" targets, following the same rules as `stack test`, for example
* It gives a warning when the destination directory is not on the PATH
* On Windows, this cannot be used to upgrade stack yet, since we need to do some fancy footwork about moving the exe around (TODO added)

Now that I've implemented this, I'm beginning to think I made a mistake about saying we should give it a name besides `install`. Just because cabal has weird nomenclature doesn't mean we should do. What does everyone think about renaming the command to `install` instead?

**Comment by snoyberg** [comment]
Fixing the Windows upgrade problem was easy, and I've implemented it. But I forgot to mention: there's some discussion warranted around the path on Windows. Currently, it's using directories like C:\Users\Michael\AppData\Roaming\local\bin. Any better ideas?

**Comment by feuerbach** [comment]
I have no problem with `install`.

Does it work for non-local targets? E.g. I may want to just say `stack install pandoc`.

**Comment by snoyberg** [comment]
Yes, it should. One thing we could consider is figuring out good behavior for running `stack install` outside of a project directory, presumably working the same way `stack exec` will end up working.

**Comment by chreekat** [comment]
My real preference is to have two commands with the same distinction as
exists between 'apt-get install' and 'make install'. The latter makes no
sense in a non-project directory, and the former doesn't care about $PWD at
all.

If a command is to do both, it may as well be called `install`. :P Maybe
we'll advance to a bright future where I can just apt-get install the
latest binaries from LTS Stackage anyway...

**Comment by snoyberg** [comment]
Right now, if you run stack install pandoc outside of a project directory, you'll be guaranteed to get the version from upstream, which may be pretty close to what you're looking for

**Comment by chreekat** [comment]
Aye, but if I run `stack install pandoc` *inside* a project, it.... oh. Hm! It does a smart thing. I am satisfied.

Well, except for the following:

    Couldn't find executable make-pandoc-man-pages in directory /home/b/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/bin/
    Copying from /home/b/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/bin/pandoc to /home/b/.local/bin/pandoc
    Couldn't find executable trypandoc in directory /home/b/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/bin/

**Comment by snoyberg** [comment]
That might be that the buildable flag isn't being tracked properly right
now. There's a todo in the codebase to track that.
