### ISSUE TITLE
stack --nix exec -- bash fails

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#1538]
The following works:

```
$ stack new foo
$ cd foo
$ stack exec bash
```

However, the following does not:

```
$ stack exec -- bash
/nix/store/gb2dwphbdjk56h0lbbyma32rlid022ad-bash-4.3-p42/bin/bash: --extra-lib-dirs=/nix/store/gf16fp2wxbfq0c6r7j6386gkk4r3aqdr-apache-maven-3.3.3/lib : option non valable
```

The problem seems to be that if you use `--` to delimit arguments passed to the subcommand, Stack for some reason passes extra arguments to the subcommand, which it of course fails to recognize. Without `--` this seems to work fine.

**Comment by luigy** [comment]
This is similar to #1536

**Comment by peti** [comment]
Is there going to be a bug-fix release for this soon? Unfortunately, the `exec` command is pretty much useless for most purposes with that bug present because one cannot pass any options to the executed program.

**Comment by borsboom** [comment]
You can use `stack upgrade --git` to upgrade to the latest master version now.  We're planning on a new release next week.
