### ISSUE TITLE
stack build failure relating to the network package on Windows 10

### ISSUE THREAD

**Issue by dpratt71** [commercialhaskell/stack#1540]
I ran into an error trying to setup/build a project that uses the ghcjs compiler. The network package seemed to be the source of the error, so I created a new project using the 'simple' template and added the network package to it (`network >= 2.6 && < 3`). The `stack build` command failed with the same message:

> Could not resolve file C:\Users\DANIEL~1.PRA\AppData\Local\Temp\stack20944\network-2.6.2.1\NetworkSocketTypes.hsc

What's weird (I think) is that the network package at that version does not have a file with that name in it. It *does* have a file 'Network/Socket/Types.hsc'.

The resolver for this project is `lts-3.18`. `stack --version` reports:

> Version 0.1.10.0, Git revision a25892f8374d4bcbed6dd0f0c3bcb6cb93df490c (2778 commits) x86_64

**Comment by dpratt71** [comment]
I'm continuing to try to chase this down and it's getting weird. At this point I'm not at all confident the problem lies with stack.

So I think I've figured out that *something* (GHC?) generates temporary `.hscpp` files from `.hsc` files during the build. The weird thing is that it looks like the generated `.hscpp` file is cut off right in the middle of a line.

To wit, here's the last 10 lines or so of the `.hscpp` file that is (apparently) generated from `Types.hsc`:

    {-# LINE 990 "Network\Socket\Types.hsc" #-}

    peek32 :: Ptr a -> Int -> IO Word32
    peek32 p i0 = do
        let i' = i0 * 4
            peekByte n = peekByteOff p (s6_addr_offset + i' + n) :: IO Word8
            a `sl` i = fromIntegral a `shiftL` i
        a0 <- peekByte 0
        a1 <- peekByte 1
        a2 <- peekByte 2
        a3 <- peekByte 3
        return ((a0 `sl` 24) .|

**Comment by mgsloan** [comment]
Very strange!  Could be a GHCJS bug.  Since it uses GHCJS to build Setup.hs (and the whole Cabal library), a compiler or boot library bug could cause funky cabal behavior.

**Comment by dpratt71** [comment]
@mgsloan Are problems with the MSYS tooling in scope for this project? Because that's where I think this is headed. I tried to build the network package directly (from source) under stack and got the same error(s). This last experiment didn't involve GHCJS.

**Comment by dpratt71** [comment]
I'm now considering the possibility that I'm seeing a bug in Windows 10.

The good news is that I've learned a lot about how Haskell packages get installed. It turns out that `hsc2hs` gets run while building the network package. It generates a file `Types_hsc_make.c`, compiles it, runs it, and captures the output and sends it to a file `Types.hs`.

On my machine, if I run the `Types_hsc_make.exe` file created by `hsc2hs`, it generates the correct output to the console. If I redirect the output of that program to a file, it gets truncated in exactly the same manner as happens during the full build process. When I copied `Types_hsc_make.exe` to a Windows 7 machine and ran it, it generated the correct output, whether or not the output was redirected to a file.

How weird is that?

**Comment by mgsloan** [comment]
Wow, that is indeed a really strange bug.  Thanks for investigating further!

**Comment by hiratara** [comment]
I get similar errors when I build [hlibgit2](https://hackage.haskell.org/package/hlibgit2) .

The real file name is `Bindings\Libgit2\Windows.hsc`.

```
$ stack build
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
hlibgit2-0.18.0.15: configure
hlibgit2-0.18.0.15: build
Could not resolve file C:\msys64\tmp\stack3104\hlibgit2-0.18.0.15\BindingsLibgit2Windows.hsc
```

I'm using Surface Book, i.e. MSYS2 on Windows10. 

```
$ stack --version
Version 0.1.10.1, Git revision 83ec40fc5fd6d300c73d23deb1f41d30168fc236 (2783 commits) x86_64
$ /c/Users/hiratara/AppData/Local/Programs/stack/x86_64-windows/ghc-7.10.3/bin/hsc2hs.exe --version
hsc2hs version 0.67
$ pacman -Ss msys2-runtime
msys/msys2-runtime 2.4.0.16814.ac5d7ed-1 (base) [installed]
    Posix emulation engine for Windows
msys/msys2-runtime-devel 2.4.0.16814.ac5d7ed-1 (MSYS2-devel) [installed]
    MSYS2 headers and libraries
$ systeminfo
... snip ...
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.10586 N/A Build 10586
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
... snip ...
```

**Comment by dpratt71** [comment]
I was rather unpleasantly surprised to discover that the problem I was experiencing was due to using [cmder](http://cmder.net/) as my console emulator. Apparently it injects itself into hosted processes and mucks around with standard input/output streams. Sorry for the false alarm.
