### ISSUE TITLE
File name does not match module name: Saw: `Main'

### ISSUE THREAD

**Issue by hanjoosten** [commercialhaskell/stack#1549]
I made a minor modification of a file. When I want to build again, ( `stack build` ) I get the following output, containing an error:

```
Setting codepage to UTF-8 (65001) to ensure correct output from GHC
ampersand-3.3.0: build
Static files unchanged, no need to update src/Database/Design/Ampersand/Prototype/StaticFiles_Generated.hs

Preprocessing executable 'ampersand' for ampersand-3.3.0...

D:\data\hjo20125\Git\ampersand\src\Database\Design\Ampersand\Core\AbstractSyntaxTree.hs:1:1:
    File name does not match module name:
    Saw: `Main'
    Expected: `Database.Design.Ampersand.Core.AbstractSyntaxTree'

--  While building package ampersand-3.3.0 using:
      D:\data\hjo20125\Git\ampersand\.stack-work\dist\2672c1f3\setup\setup --builddir=.stack-work\dist\2672c1f3 build exe:ampersand --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

```

I have been googling around, and I found [a very comparable issue](https://github.com/haskell/cabal/issues/883) at cabal. However, it was closed stating it isn't a cabal issue. 

I do not know what is wrong. The file name is for sure correct. If it isn't a bug, how can I work around it? I de-installed all haskell related stuff (ghc, stack, cabal etc) and installed it again, but the issue stays the same. (looks like maybe something is cached)

**Comment by mgsloan** [comment]
This means that GHC can't parse out the module name.   Is there something broken about your module header syntax?  Maybe try deleting everything before the `module Database.Design.Ampersand.Core.AbstractSyntaxTree  where` declaration.  Try deleting the exports list?  Of course, these deletions aren't the solution, but if it changes the error, then you know it's a parse issue due to something in the deleted text.

**Comment by hanjoosten** [comment]
Oh, this is embarrasing. It was a plain parse error indeed. I must have accidently pasted in some text without noticing doing so. When I doublechecked the modification, Git showed it to me right in my face..

Thanks anyway!
