### ISSUE TITLE
Wildcard issue when using `stack build --flag`

### ISSUE THREAD

**Issue by geraldus** [commercialhaskell/stack#1560]
Hi friends!
Running `stack build --flag *:hans` gives me error:

```
No matches for wildcard “*:hans”.
```

Am I missing something?

```
$ stack --version
Version 0.1.10.1, Git revision 83ec40fc5fd6d300c73d23deb1f41d30168fc236 (2783 commits) x86_64
```

**Comment by geraldus** [comment]
Oh, sorry, this is not `stack` issue, this is because of `fish` shell.  Apologize!  Running above command in `bash` works as expected!

**Comment by geraldus** [comment]
I did some research and decided to reopen this will some additions, but feel free to close this.

Fish shell tries to expand `*` wildcard for all command, `stack build --flag *:whatever` does not work.  It is possible to escape wildcard with backslash, but in this case Aeson fails to parse this:
```
AesonException "failed to parse field 'flags': Invalid package name: \"*\""
```
I've tried `"*:..."`, `"*":`, `'*':` also but nothing works.  A way to use wildcards in `stack.yaml` (disscussed here #1452) will solve this issue (or `bash` as I mentioned before).

However, I want to mention edge case:
```
$ bash
$ touch :-hans
$ stack build --flag *:-hans
option --flag: Invalid package name:
# fail ^
$ rm :-hans
$ stack build --flag *:-hans
# ^ works now
```
So, in fact `bash` tries to expand wildcard, but if it can't it leaves `*` as is.  I don't think in real life this will hurt anyone, but I think there should be to use quoted wildcard also.

**Comment by kadoban** [comment]
That looks like still a shell issue to me. If I understand correctly, it shouldn't be passing the literal quotes to the `stack` command. There should be a way to tell the shell "don't interpret this `*` as a glob, just pass it to the command as-is", without having it additionally send literal quotes around what it gives to `stack` as the arguments. I don't know `fish` at all, so I have no idea what that would be if it's not quoting it or using backslash for escaping.

For example when I do `stack --build "*":blah` in `bash` it works fine. What `fish` seems to be doing is something like what `stack --build "\"*\"":blah` would do in `bash`, which probably means that double-quotes like that aren't actually `fish`'s syntax for what you're trying to do.

**Comment by snoyberg** [comment]
Closing as a shell issue
