### ISSUE TITLE
Ubuntu 14.04 x32. Installing issue.

### ISSUE THREAD

**Issue by Losiara** [commercialhaskell/stack#1566]
Downloaded x32 from download page. 
- First it coldn't find libgmp, so I symlinked it in /usr/lib from /usr/lib/x86_64-linux-gnu/libgmp.so.10
- After that there is error:

stack: error while loading shared libraries: libgmp.so.10: wrong ELF class: ELFCLASS64

"sudo apt-get install libgmp-dev" tells that it is already installed.

**Comment by borsboom** [comment]
It seems to work for me.  I created Ubuntu 14.04 32-bit VM using:

```
$ vagrant init ubuntu/trusty32 && vagrant up && vagrant ssh
```

Then ran:

```
$ lsb_release -r
Release:	14.04

$ uname -p
i686

$ sudo apt-get install -y libgmp10
[...]

$ curl -L https://www.stackage.org/stack/linux-i386 | tar xzf -
[...]

$ stack-1.0.0-linux-i386/stack --version
Version 1.0.0, Git revision 3bc26237b5b3c387b8fd564459ea4dd88fd58b30 (2939 commits) i386

$ file stack-1.0.0-linux-i386/stack
stack-1.0.0-linux-i386/stack: ELF 32-bit LSB  executable, Intel 80386, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.26, BuildID[sha1]=6e66c01ec8dc3d0eefc8c9e25c9aef71e1b7e538, stripped

$ ldd stack-1.0.0-linux-i386/stack
	linux-gate.so.1 =>  (0xb7752000)
	libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xb7719000)
	libz.so.1 => /lib/i386-linux-gnu/libz.so.1 (0xb76ff000)
	librt.so.1 => /lib/i386-linux-gnu/librt.so.1 (0xb76f6000)
	libutil.so.1 => /lib/i386-linux-gnu/libutil.so.1 (0xb76f1000)
	libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xb76ec000)
	libgmp.so.10 => /usr/lib/i386-linux-gnu/libgmp.so.10 (0xb7667000)
	libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xb7621000)
	libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xb7604000)
	libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xb7455000)
	/lib/ld-linux.so.2 (0xb7753000)
```

It's strange that your 32-bit Ubuntu system has a `/usr/lib/x86_64-linux-gnu` directory, since that's for 64-bit shared libraries.

**Comment by Losiara** [comment]
Its strange.
Cabal works, stack prints error.
Realy can't understand the reason.
Sudo apt-get install libgmp10 
prints that it is installed.

**Comment by borsboom** [comment]
What do the following commands output?

```
uname -p
ldd `which cabal`
```

My suspicion is that you're trying to run 32-bit Stack on a 64-bit Ubuntu system.  If so, is there any particular reason?  Have you tried running `apt-get install libgmp10:i386` to install the 32-bit version of libgmp10?

**Comment by Losiara** [comment]
System is x32. I managed issue with libgmp10:i386.deb and apt-get install -f.
But also can't understand what happened.

Thank you!
