### ISSUE TITLE
Write a Wikipedia entry for Stack

### ISSUE THREAD

**Issue by beerendlauwers** [commercialhaskell/stack#1573]
I noticed Wikipedia refers to the Haskell Platform on [the page on GHC](https://en.wikipedia.org/wiki/Glasgow_Haskell_Compiler). Perhaps we should also make a page for Stack, add it to the disambiguation page for "Stack" and refer to it via the GHC page?

**Comment by borsboom** [comment]
It would be worth having a presence on Wikipedia, but I don't think this is something we can do.  I'm fuzzy on the details, but I'm pretty sure it's frowned upon for people to add their own project to Wikipedia.  There are supposed to be secondary sources in reliable publications that can be referenced, and I'm not sure if Stack has been around long enough for those to exist.  I would certainly encourage someone who is not directly involved with Stack development to do the research to find acceptable sources and then add an entry once it's possible to do so while following Wikipedia's guidelines.  A good place to start might be [Article creation and notability](https://en.wikipedia.org/wiki/Wikipedia:Contributing_to_Wikipedia#Article_creation_and_notability).

**Comment by bkaestner** [comment]
> it's frowned upon for people to add their own project to Wikipedia. 

It's fine, but [they most not have a promotional tone](https://en.wikipedia.org/wiki/Wikipedia:PROMO). However if you just start a [stack article](https://en.wikipedia.org/wiki/Stack_(Software)), you're usually ending up with a orphaned page.

Instead, I suggest to update the articles on Cabal and the Haskell platform. Introduce examples of existing criticism into them (with sources) and have a remark like 

> ... which spawned the development of \[\[Stack (Software)|stack}]\]`<ref>{{cite web|title=What do Haskellers want? Over a thousand tell us|https://www.fpcomplete.com/blog/2015/05/thousand-user-haskell-survey|quote=Package management with cabal is the single worst aspect of using Haskell. Asked if improvements to package management would make a difference to their future choice of Haskell for a project, 38% said it would be "crucial" and a further 29% said it would be "important". Comments connected cabal with words like hell, pain, awful, sucks, frustrating, and hideous. Only this topic showed such grave dissatisfaction.}}</ref>` [probably more sources here]

This will not only introduce a "red link" (a link to an article that doesn't exist yet), but also provide a source for an interested reader who wants to start the article.

**Comment by borsboom** [comment]
Would you like to perform that update?  Sounds like you have far more experience with the ways of Wikipedia than I do.

**Comment by bkaestner** [comment]
The aforementioned [criticism](https://en.wikipedia.org/wiki/Cabal_%28software%29#Criticism) is now in the article. However, the article [Stack (software)](https://en.wikipedia.org/w/index.php?title=Stack_%28software%29&redirect=no) already exists, but redirects to the "Stack" disambiguation. Therefore, a link to `[[Stack (software)]]` doesn't turn red.

**Comment by borsboom** [comment]
Thanks!

**Comment by bkaestner** [comment]
The [article seems to exist now](https://en.wikipedia.org/wiki/Stack_%28software%29). Maybe someone wants to add `stack` to the [disambiguation](https://en.wikipedia.org/wiki/Stack).

**Comment by lwm** [comment]
@bkaestner @borsboom Looks safe to close off? There is now a wikipedia entry for Stack!

**Comment by beerendlauwers** [comment]
Yup, looks good! I'll close it off.
