### ISSUE TITLE
Git should use --git-dir and --work-tree not changing directory

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1577]
If the git process used gitdir/worktree arguments instead of changing process directory it would be easier to debug unexpected failures because you could copy/paste the command lines anywhere. See http://stackoverflow.com/questions/1386291/git-git-dir-not-working-as-expected for advice on how to use it.

**Comment by ndmitchell** [comment]
#1578 alleviates this a bit, but using just flags would still be more convenient.

**Comment by mgsloan** [comment]
Makes sense to me, I agree it's nice when the command lines in the verbose log can be copy-pasted.

**Comment by snoyberg** [comment]
With the new Pantry approach, I don't think this is relevant on master anymore.
