### ISSUE TITLE
Need better error reporting when stack.yaml is empty

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1585]
When `stack.yaml` is empty we see this:

```
cueball $ stack init
Could not parse '/vol/hosts/cueball/workspace/cabal-test/stack.yaml':
UnexpectedEvent {_received = Just EventStreamEnd, _expected = Just EventDocumentStart}
See http://docs.haskellstack.org/en/stable/yaml_configuration.html.
```

We could do better here by handling this case and providing a nicer message.

**Comment by mgsloan** [comment]
I'm not sure if handling this specific case is worthwhile, however I agree that the message isn't so great.

Maybe this should be solved by having a more plain-text pretty print of the parse error message?  Might be a good thing to contribute to the yaml package.

**Comment by snoyberg** [comment]
I now see the IMO clear enough error message:

```
Could not parse '/Users/michael/Desktop/stack.yaml':
Aeson exception:
Error in $: expected ProjectAndConfigMonoid, encountered Null
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```
