### ISSUE TITLE
Missing transitive dependencies are not listed the first time around

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#159]
'github' depends on 'failure', but failure isn't listed as a missing dep at first:

    $ b@fuzzbomb ~/tmp/snowdrifft (master) $ stack build
    Checking against build plan lts-2.11
    Checking against build plan lts-2.10
    Checking against build plan lts-1.15
    Checking against build plan nightly-2015-06-01
    Writing default config file to: /home/b/tmp/snowdrifft/stack.yaml
    stack: The following packages do not exist in the build plan:
    github (used by Snowdrift)
    mime (used by Snowdrift)
    titlecase (used by Snowdrift)
    yesod-markdown (used by Snowdrift)
    Recommended action: modify the extra-deps field of /home/b/tmp/snowdrifft/stack.yaml to include the following:
    - github-0.13.2
    - mime-0.4.0.2
    - titlecase-0.1.0.1
    - yesod-markdown-0.9.4

    $ (1) b@fuzzbomb ~/tmp/snowdrifft (master) $ vim stack.yaml
    $ b@fuzzbomb ~/tmp/snowdrifft (master) $ stack build
    stack: The following packages do not exist in the build plan:
    failure (used by github)
    Recommended action: modify the extra-deps field of /home/b/tmp/snowdrifft/stack.yaml to include the following:
    - failure-0.2.0.3

**Comment by snoyberg** [comment]
Let's merge in #178 here as well. Idea is that, once we're able to determine what should be added to extra-deps, we'll also provide a flag (e.g. `--assume-latest`) and automatically upgrade the stack.yaml file.

**Comment by snoyberg** [comment]
I've just added a new command, `stack solver`, which I believe addresses this pretty well. When run, it will run the `cabal` dependency solver on your project to determine what extra-deps are needed. Hopefully in the future we'll be able to switch it over to a better SAT-based solver.

Pinging @bitemyapp as well based on the request in #178.

**Comment by mboes** [comment]
> a better SAT-based solver.

for the public record, "better" very likely implies "off-the-shelf" IMHO. :)
