### ISSUE TITLE
Move utility code elsewhere?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1592]
Do we want to move some of stack's more substantial utility code out into separate packages?  The main downside of this is that it makes it harder to make a change in stack which requires a corresponding utilities change (though, the overhead isn't too bad, you just need to know to temporarily add it as a package in a git submodule).  There are, however, numerous upsides:
- More people can use and benefit from the code.
- More testing of the code, due to more usage.  This usage would also lead to more contribution to the utilities code.  
- The utilities would be generalized and cleaned up.  This can potentially lead to clearer / better code within stack.

I've taken a look at the utility code, and I think the following are good candidates for being moved to external packages:
- [Warnings for aeson parsers](https://github.com/commercialhaskell/stack/blob/master/src/Data/Aeson/Extended.hs).  Could be made into a new package or added to aeson. (122 SLOC)
- Utilities for [tagged binary serialization / deserialization](https://github.com/commercialhaskell/stack/blob/master/src/Data/Binary/VersionTagged.hs) (75 SLOC)
- [Utilities for downloading a url and verifying contents](https://github.com/commercialhaskell/stack/tree/master/src/Network/HTTP). (479 SLOC)
- [IO](https://github.com/commercialhaskell/stack/blob/master/src/Path/IO.hs) and [other utilities](https://github.com/commercialhaskell/stack/blob/master/src/Path) for `Path`.  There are a lot of additional utilities that could be added to the IO part.  I know there're quite a few spots in stack code where `toFilePath` is used that could be turned into useful `Path.IO` utilities.  These could either be added directly to `path`, or a new `path-io` package. (269 SLOC)
- [Process utilities](https://github.com/commercialhaskell/stack/tree/master/src/System/Process), which could probably use an API cleanup before releasing. (525 SLOC)

Not that SLOC really matters, but it is a rough indicator of the amount of code we're talking about.  Moving all the above utilities out of stack would be a reduction of `~1470 SLOC`, where there's currently `~21806 SLOC` in `src`.

Misc side note:  [We've found](https://github.com/commercialhaskell/stack/pull/1289) that it's best to use `toFilePathNoTrailingSlash` when passing arguments.  Maybe it's newtype overkill, but it might be nice to have a newtype for program arguments which encourages use of some `toFileArg :: Path r File -> Arg` or `toDirArg :: Path r Dir -> Arg`.

**Comment by borsboom** [comment]
Yes, this is one of the things we should do as part of the stabilization phase once it hits.  I'll put this issue in a new "Stabilization" milestone.

**Comment by snoyberg** [comment]
This has been happening on an ongoing basis, and will continue into the future. Closing.
