### ISSUE TITLE
Have "stack init" accept a list of sub-directories

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1593]
Currently, there's no way to selectively consider cabal files for `init`.  I think it makes sense to have it take a list of sub-directories to search in, defaulting to `.`.  This'd be consistent with `stack build` taking a list of sub-directories and building all projects in those sub-directories.

The `--ignore-subdirs` flag would still work - it'd mean that cabal files in sub-directories of the specified dirs are ignored.

I'd hope that this would work with bash expansion, so that if you do `stack init --ignore-subdirs *`, it'd build all the packages that are immediate subdirs (to faciliate this, merely warn when a path to a file is specified).

**Comment by harendra-kumar** [comment]
That's cool!

**Comment by achernyak** [comment]
@mgsloan Is there any difference between how `build` would handle the `--ignore-subdirs` flab and the expected `init` handling of this flag?

If there are no differences, I will go ahead and get started on this one over the weekend.

**Comment by mgsloan** [comment]
Well, `build` doesn't take `--ignore-subdirs`.  It's not very useful for build, because usually you only use directory arguments when you have a dir that contains lots of packages (but not all of them).  In the case where you'd use `--ignore-subdirs` with init, you may as well just specify the target normally, using the package name.

But, yes, how `build` 's handles directory arguments is the same as how this would.

Great, certainly feel free to work on this!  Particularly timely, as @harendra-kumar 's large set of changes to init / solver just got merged.

**Comment by harendra-kumar** [comment]
Fixed by PR #1780 .
