### ISSUE TITLE
Clone stack templates repo instead of using github API

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1595]
In order to resolve #1251, and support #1571, we need to clone the templates repository.  Here's how this would work:

1) If it doesn't exist yet, clone the templates repo to some location in `~/.stack/`.

2) If the repo is dirty, complain to the user about it and skip step (3).  This allows you to easily modify existing templates / add new ones.

3) Fetch and reset to the latest master.  If the user passes `--offline`, then errors while running these git commands will be ignored.  When `--offline` isn't passed and an error occurs, the exception will mention that you can use `--offline`.  See also this issue about `-offline`: #1594

4) Load the template from the file in the cloned repo.

Another detail here is windows newline normalization, as recently mentioned by Lokathor in the #haskell-stack IRC channel.  Since we're using the github API to fetch the file, we currently get `\n` rather than `\r\n`.  This is something that [git can deal with](https://help.github.com/articles/dealing-with-line-endings/#platform-all), at least if we prefer using `\r\n` on windows.

**Comment by normenmueller** [comment]
Want to `stack new foobar new-template` w/o an internet connection but get failed internet connection while stack tries to download `new-template`. I already created several projects w/ stack, so the template is already there. Is there an option to run stack in offline mode or is what this issue is about? Is there a workaround w/ the current version?

**Comment by mgsloan** [comment]
There is not, this issue is tracking the resolution of that problem.

**Comment by bitemyapp** [comment]
>2) If the repo is dirty, complain to the user about it and skip step (3). This allows you to easily modify existing templates / add new ones.

I like this part.

@mgsloan seems like this would trigger a dep. Is there a preferred git client library? I'm having a hell of a time figuring out how to clone a repo with `gitlib`. Should I just invoke git via the command line?

**Comment by mgsloan** [comment]
One downside of this is that it would cause us to really require git.  Stack doesn't currently require git - it's just used as an optimized way of fetching the hackage index, if available.

**Comment by snoyberg** [comment]
The new approach to templates does not require `git` commands or API calls, but downloads from raw.githubusercontent.com instead. Closing.
