### ISSUE TITLE
"stack new --bare" will overwrite files

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1597]
It seems like somewhere along the line, the intention of https://github.com/commercialhaskell/stack/commit/9b2c44186785bbc0c99450f6749211dd24d3b5d1 was lost (to have `stack new --force` indicate that overwriting files is ok).  Maybe `--bare` without `--force` should require that the current directory is empty?

**Comment by borsboom** [comment]
Agreed.

**Comment by mgsloan** [comment]
Fixed!
