### ISSUE TITLE
Add ability for single-directory sandboxing via .stack-work

### ISSUE THREAD

**Issue by MichaelXavier** [commercialhaskell/stack#1602]
Hi!

I discussed this today with the nice folks in the irc channel and they mentioned what I was trying to do is not currently supported but may be straightforward to implement.

The short version is that I'm looking for a way to have _all_ dependencies and build products funneled into `.stack-work` just like cabal does with `.cabal-sandbox`. I will forgo the sharing benefits of re-using libraries in the global `~/.stack-work` for this.

Some background: I've got a project which is built on a build box and shipped to a production box. My project has many dependencies, a library component and some executable components. One of the features of my project involves compiling some runtime-generated code which may have access to my project's library as well as any of its dependencies. Now, since I've already built all those libraries on a comparable machine/OS, I'd like to treat them as installed and to not have to distribute my project's source code to production to achieve this.

This project currently runs using cabal sandboxes and I'm porting it to stack. Currently, we can just ship off `.cabal-sandbox` and everything I need to build the runtime-generated code is _installed_ in there. With stack, the dependencies partially also live in the global repo, which is shared with other projects, so I can't really pick it up and move just what i need. I would be totally fine whether this was a `stack.yaml` option, a CLI flag, or both.

**Comment by borsboom** [comment]
One way to achieve this might be to set STACK_ROOT to a location inside your project (e.g. `export STACK_ROOT=$PWD/.stack`), and then all the snapshot packages will go in there as well.  Would that work for your use case?

**Comment by mgsloan** [comment]
Good point, I forgot about that! Could even do something like `export STACK_ROOT=$PWD/.stack-work/root`, so that everything ends up inside `.stack-work`.

**Comment by MichaelXavier** [comment]
@borsboom Yesterday I had come back to this issue for another try and @mgsloan was helping me out and told me to post my progress to see if you had any ideas. Evidently something with the build process builds libraries with absolute paths, such that if you build libraries with this totally isolated approach (placing STACK_ROOT inside your .stack-work) on your build machine at `/foo/bar` and then ship it to production and try to load it while your cwd is `/baz/quux`, it won't be able to find the library.

So I'm already using the stack docker integration to build for a fixed, consistent set of system deps (don't run it as a docker container though). The next idea was maybe if I could get stack's docker integration to build in the same path that I will move it to in production it would work out. The way I tried was to create a stack.yaml with docker options to mount `/dev/project/path:/prod/project/path`, and set env for `STACK_ROOT=/prod/project/path/.stack-work/root` and `STACK_YAML=/prod/project/path/stack.yaml`. The idea is you get stack's docker integration to build in a *different* directory than on the host machine.  This however started failing with `/tmp/precompiled-lib/.stack-work/root/build-plan: createDirectory: permission denied (Permission denied)`. This appears to be because it creates a its `STACK_ROOT` as the root user rather than as the same uid/gid of the host's user.

Do you have any ideas of how we could get past this blocker or maybe an alternative strategy? I'm still trying my best to achieve the goal of compiling my very large set of dependencies offline once and "installing" it to my farm of machines rather than having each machine having to independently compile them from source.

**Comment by mgsloan** [comment]
@borsboom I was thinking maybe you'd have an idea about what's going on here?  Seems to me like this approach should work, but I'm not sure if you're allowed to virtual mount the project dir twice (the stack default + the repositioned one).

Also, one thing to note is that docker isn't being used in production.

**Comment by borsboom** [comment]
@MichaelXavier: In general, the approach you describe seems like it should work.  As for ownership of STACK_ROOT: `docker-engine`, which runs as `root`, creates the host volume if it doesn't already exist.  Your best bet is to `mkdir -p /dev/project/path` before invoking `stack`.  Stack could try to create non-existent host volumes itself before passing control to `docker-engine`, which would cause them to be created as the current user instead of root.  That should be a pretty easy change, and a pull request would be welcome.

**Comment by neongreen** [comment]
@MichaelXavier do you by any chance remember if that approach worked out for you in the end? (More than two years ago, I know, I know)

**Comment by MichaelXavier** [comment]
@neongreen We stopped compiling things in production, so no need to carry a complete sandbox into production. App architecture changed such that just building a package on a build server and shipping from that worked.

**Comment by snoyberg** [comment]
It looks like the original request is no longer relevant, closing.
