### ISSUE TITLE
GHCi has difficulty when "-main-is Module.main" is specified in ghc-options

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1606]
The issue is that it expects the `main-is: ` cabal field to be a Main module.  When it isn't, we get duplicate modules.  Take, for example [ndmitchell/ghcid](https://github.com/ndmitchell/ghcid):

```
mgsloan@computer:~/oss/ndmitchell/ghcid$ stack ghci --test
ghcid-0.5: Test running disabled by --no-run-tests flag.

* * * * * * * *
The main module to load is ambiguous. Candidates are: 
1. Package `ghcid' component exe:ghcid with main-is file: /home/mgsloan/oss/ndmitchell/ghcid/src/Ghcid.hs
2. Package `ghcid' component test:ghcid_test with main-is file: /home/mgsloan/oss/ndmitchell/ghcid/src/Test.hs
You can specify which one to pick by: 
 * Specifying targets to stack ghci e.g. stack ghci ghcid:exe:ghcid
 * Specifying what the main is e.g. stack ghci --main-is ghcid:exe:ghcid
 * Choosing from the candidate above [1..2]
* * * * * * * *

Specify main module to use (press enter to load none): 1
Loading main module from cadidate 1, --main-is /home/mgsloan/oss/ndmitchell/ghcid/src/Ghcid.hs

The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: ghcid
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
unknown option: 'c'

<no location info>:
    module ‘main@main:Ghcid’ is defined in multiple files: /home/mgsloan/oss/ndmitchell/ghcid/src/Ghcid.hs
                                                           /home/mgsloan/oss/ndmitchell/ghcid/src/Ghcid.hs
Failed, modules loaded: none.

<no location info>:
    Could not find module ‘Ghcid’
    It is not a module in the current program, or in any known package.
```

**Comment by luigy** [comment]
> The issue is that it expects the main-is: cabal field to be a Main module. When it isn't, we get duplicate modules.

What do you mean? :notes: 

So [Test.Polling](https://github.com/ndmitchell/ghcid/blob/22a5e762f0eed7bc4054b5764382fd1673c0b2da/src/Test/Polling.hs#L21) is importing `Ghcid` which is the _main_ module for the [`ghcid`](https://github.com/ndmitchell/ghcid/blob/22a5e762f0eed7bc4054b5764382fd1673c0b2da/ghcid.cabal#L51) exe component that is getting loaded in the example above.  Are we saying the same thing? the title had me thinking otherwise

Stack already checks for duplicates and it could be extended to remove a Module (Ghcid) if it's the same file that is being loaded, but should it really?  `ghcid` can also be refactored to avoid this :P

**Comment by mgsloan** [comment]
The issue is `ghc-options: -main-is Ghcid.main -threaded`.  This allows a module named something other than "Main" to be the main module.

Here's a more direct repro: `stack ghci --test --main-is ghcid:exe:ghcid`

Using `-v` to find out the invocation, to find out the path to the tmp ghci-script file, reveals that this is the script being provided to ghci:

```
:load "/home/mgsloan/oss/ndmitchell/ghcid/src/Ghcid.hs" "Ghcid" "Language.Haskell.Ghcid" "Language.Haskell.Ghcid.Parser" "Language.Haskell.Ghcid.Terminal" "Language.Haskell.Ghcid.Types" "Language.Haskell.Ghcid.Util" "Test.HighLevel" "Test.Parser" "Test.Polling" "Test.Util" "Wait"
:module + Ghcid Language.Haskell.Ghcid Language.Haskell.Ghcid.Parser Language.Haskell.Ghcid.Terminal Language.Haskell.Ghcid.Types Language.Haskell.Ghcid.Util Test.HighLevel Test.Parser Test.Polling Test.Util Wait
```

It doesn't realize that `/home/mgsloan/oss/ndmitchell/ghcid/src/Ghcid.hs` and `Ghcid` refer to the same module, because it thinks the first one is a `Main` module..

**Comment by luigy** [comment]
>It doesn't realize that /home/mgsloan/oss/ndmitchell/ghcid/src/Ghcid.hs and Ghcid refer to the same module

...

> Stack already checks for duplicates and it could be extended to remove a Module (Ghcid) if it's the same file that is being loaded...

we are saying the same thing :)

Just to be sure,  `ghciSetup`'s behavior is correct then? 
it is just that it should be removing a module if it is already being loaded as a file.

also wouldn't  a flag that filters out the duplicates and loads as much as it can be a nice addition?
the code seems in place already

**Comment by mgsloan** [comment]
Yes, `ghciSetup`'s behavior is correct for this.  I actually don't think it's possible for us to do perfectly in this circumstance, because we don't know if `Ghcid.hs` contains a `module Main` or `module Ghcid`.  I think we'd have to go as far as parsing ghc-options for the presence of `-main-is`!

However, I think it'd be unreasonable for the project to have a `main/Ghcid.hs` file with `module Main` inside it, as well as a `src/Ghcid.hs` file with `module Ghcid` in it.

So, it seems perfectly reasonable to filter the module list with the name of the main file (without extension).  Considering that we can't do this perfectly, a warning should be emitted.

**Comment by luigy** [comment]
>also wouldn't a flag that filters out the duplicates and loads as much as it can be a nice addition?

by duplicates I meant that [here](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Ghci.hs#L473) it currently either throws if duplicates are found or loads everything it can if it didn't find any, but there is no option for a middle ground like load everything excluding the duplicates

> So, it seems perfectly reasonable to filter the module list with the name of the main file (without extension). Considering that we can't do this perfectly, a warning should be emitted.

:+1:  seems doable, but ghcid should still refactor :joy:

**Comment by mgsloan** [comment]
> by duplicates I meant that here it currently either throws

Oh, I see.  This is actually what used to happen, and I don't think it should be enableable even with a flag.  It would nub the list of module names, and supply ghci with the hs-source-dirs search path.  This meant that the first discovered module would be used.  This would result in bizzarre compile errors because you're compiling some module `src/B.hs` against `src1/A.hs` when it expects `src/A.hs`.  This could even result in some unexpected behavior if the definitions `B` uses happen to be defined in both.

**Comment by mgsloan** [comment]
Fixed using the approach described! (exclude loading modules that match the main-is target's filepath)

**Comment by spl** [comment]
I just wanted to add, in case others come upon this issue, that I ran into a similar problem when running `stack ghci`:

```
<no location info>: error:
    module ‘main@main:Main’ is defined in multiple files:
      .../src/Main.hs
      .../src/Main.hs
```

The problem was that I had `Main` in both the `main-is` and `other-modules` sections:

```
main-is: Main.hs

other-modules: ... Main ...
```

The solution is to remove `Main` from `other-modules`.

**Comment by mgsloan** [comment]
Thanks for the report, @spl, I've opened an issue tracking its resolution.
