### ISSUE TITLE
`stack clean` option to fully clean all `.stack-work` directories

### ISSUE THREAD

**Issue by blitzcode** [commercialhaskell/stack#1609]
```
stack new test
cd test
stack build
stack clean
```

The executable generated by the default template will still be in the `.stack-work` folder. Tested with stack 1.0 on OS X 10.10.

**Comment by mgsloan** [comment]
`stack clean` may be a little confusing in this respect.  The docs say `Clean the local packages`.  In other words, this cleans the `dist` dirs for packages, and nothing more.

If you want the sort of clean that you want, just delete the root `.stack-work` directory.

**Comment by blitzcode** [comment]
Thanks for the quick reply. I just noticed this and wasn't sure if the executable was considered a local Cabal package and would've intuitively expected a clean command to remove all build artifacts. Just removing the entire folder is of course perfectly fine.

**Comment by borsboom** [comment]
It might be nicer to provide an option to `stack clean` to do this, which would also remove all the packages' `.stack-work` directories as well.  Typing `stack clean --fully` (or whatever the option is called) would be much nicer than `find . -name .stack-work -exec rm {} \;`.

**Comment by panamiga** [comment]
Hello,
Could you assign me to the issue?
I have a patch already and plan to make pull request tomorrow.

**Comment by borsboom** [comment]
I can't assign you, but I'll set the in-progress tag and looking forward to your PR.

**Comment by panamiga** [comment]
Ok, thanks.
PR #1649 created for this issue passed all the checks.
Any comments appreciated.

**Comment by panamiga** [comment]
PR updated.

**Comment by pjdelport** [comment]
#1649 has been merged: can this be closed?

**Comment by mgsloan** [comment]
Yup!
