### ISSUE TITLE
`stack update` for all global packages?

### ISSUE THREAD

**Issue by sid-kap** [commercialhaskell/stack#1610]
I just updated `~/.stack/global/stack.yaml` to use the latest LTS resolver. I now want to update all of my globally installed packages to their versions on the latest Stackage LTS (including binaries installed to `~/.local/bin`). Is there a way to do this? I tried `stack update` but this did not do anything.

**Comment by mgsloan** [comment]
There isn't any direct way to do this.  `stack build some-package` just builds `some-package` and installs it into the package database.  There is no special tracking of which packages you've installed.

A couple options here:

1) Create a project, and add the packages you want as dependencies.

2) Have a text files somewhere that stores your `stack build`

In general, stack is concerned with managing a local build sandbox for a project.  It isn't intended to be a global package manager.  See, for example, `stack uninstall`:

```
mgsloan@computer:~$ stack uninstall 
stack does not manage installations in global locations
The only global mutation stack performs is executable copying
For the default executable destination, please run 'stack path --local-bin-path'
```

**Comment by raxod502** [comment]
> It isn't intended to be a global package manager.

Then what is the correct way to install `hindent` and other similar packages for editor integration, if not via `stack install hindent`?

**Comment by sid-kap** [comment]
@raxod502 your OS's package manager?

**Comment by raxod502** [comment]
@sid-kap Homebrew for one does not package all Haskell packages, and in particular not `hindent`. (I don't really understand why it would—that sounds like a huge duplication of effort.) When I go to install Python packages, I use Pip. When I install Node.js packages, I use NPM. Ruby packages, `gem`. TeX packages, `tlmgr`. And so on. I've never had trouble with this before.

**Comment by sid-kap** [comment]
@raxod502 Yep, I feel you. I also wish Stack was a package manager like pip and npm.
One thing you could try is make a dummy project where `packages` in `stack.yaml` includes all the projects you want. Do a `stack build`, and then the built executables will be in `.stack-work`. Whenever you want to update to the latest version of the packages, update the lts version in `stack.yaml` and do `stack build` again, and the new executables will be there (in a new subdirectory of `.stack-work` for the new lts version).

**Comment by raxod502** [comment]
I encountered trouble doing that. As per the contribution guidelines, however, I will move further discussion [to StackOverflow](https://stackoverflow.com/q/49504206/3538165).

**Comment by sid-kap** [comment]
Okay. You can send me an email or something if you have a specific problem with this approach
