### ISSUE TITLE
allow stack.yaml to set a generic resolver 

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#1612]
AFAICT stack only allows specific Stackage (ghc) versions to be listed in stack.yaml.
I for one at least sometimes would like to use say the latest lts-3 or nightly by default without having to constantly update `~/.stack/global/stack.yaml` etc.

ie I would like to be able to put:
`resolver: lts-3` or `resolver: nightly` or `resolver: lts`, etc in `stack.yaml`
and have stack work out that I want to use `lts-3.20` or `lts-4.0` etc.

I suspect that the current behavior is a design decision but how does this change sound?

**Comment by mgsloan** [comment]
The discussion here is relevant: https://github.com/commercialhaskell/stack/issues/1590

> I suspect that the current behavior is a design decision but how does this change sound?

Indeed, it's quite nice to keep the property that a given stack.yaml has good chances of working into the future.  That said, I think a resolver that says "use the latest lts-3" also has good chances of preserving that property.

One good alternative to supporting this in the stack.yaml files would be to support it in `stack config`.  In other words, as described in #1590, commandline arguments would be allowed to pick the "latest" snapshot, but `stack.yaml` fields would not.

This way, if you want your continuous integration testing to try using the latest snapshot, you can just script it to first do `stack config set resolver lts-3-latest`.

So, I lean towards adding CLI syntax for this, but keeping it out of stack.yaml, in the name of deterministic builds.

**Comment by juhp** [comment]
I see, thanks.  Probably I would just use `stack --resolver lts-3 ...` though instead of `stack config set resolver lts-3-latest` since it is shorter. (Personally my vote goes for avoiding the `-latest` suffix here too if possible, but maybe there is an ambiguity there?)

**Comment by harendra-kumar** [comment]
I agree with @juhp. lts-3 in itself is not a 'concrete' resolver since it does not specify a minor version, therefore it can be assumed to be the latest available lts-3.x. There is a chance of confusing it with lts-3.0 though.

**Comment by mgsloan** [comment]
Makes sense to me!

**Comment by mgsloan** [comment]
Closing in favor of a newer discussion of the same topic - https://github.com/commercialhaskell/stack/issues/2476
