### ISSUE TITLE
Solver can automatically suggest changes when there is an unresolvable conflict

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1616]
See https://github.com/commercialhaskell/stack/pull/1583#issuecomment-169319773.

We can automatically determine the minimal number of user packages to remove to be able to come up with a workable build plan. We can do this automatically when init/solver is used with `--force` and write the removed packages commented out in the config with an appropriate conflict reason comment. This allow diagnosing and fixing dependency problems quickly.

This will perhaps depend on #1615 .

**Comment by mgsloan** [comment]
Makes sense!  https://github.com/commercialhaskell/stack/issues/1593 is also relevant, as otherwise you can't really select just the cabal files that are needed.  Might be good to provide the commandline options along with the suggestion.
