### ISSUE TITLE
Add haddock to travis CI

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1623]
I attempted to add haddock to CI, in [this commit](https://github.com/commercialhaskell/stack/commit/92da37a463a444dcdc94cb64f9bac14c74cb7e8a), however, the failure doesn't cause the test to fail: https://travis-ci.org/commercialhaskell/stack/jobs/100989663#L1035

I'm guessing this is a bug with `cabal haddock`, where it doesn't return a failing exit code.  I haven't yet tried locally with cabal.  `stack haddock` does yield an exit code when haddock fails.

**Comment by borsboom** [comment]
Why not add `--haddock --no-haddock-deps` to the `stack test` step instead of doing `cabal haddock`?

**Comment by mgsloan** [comment]
Ahah, good point!
