### ISSUE TITLE
Getting HTTPS working for docs.

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1625]
https://haskellstack.org fails.

![screenshot from 2016-01-08 11-54-13](https://cloud.githubusercontent.com/assets/320177/12205167/8cbb7eb6-b5fe-11e5-82a4-9666919c6855.png)

**Comment by borsboom** [comment]
We're using readthedocs.org to host the docs, which [doesn't support HTTPS for CNAMEs](http://docs.readthedocs.org/en/latest/alternate_domains.html?highlight=https#cname-ssl).  While they do have a workaround (basically running our own reverse-proxy against their site) probably the way to solve this and a few other issues around documentationwould be to build and host our own docs on our own server.

**Comment by bitemyapp** [comment]
@borsboom wfm as long as you don't break "haskellstack.org" :+1:

**Comment by borsboom** [comment]
This is now setup, and you should be auto-redirected to HTTPS automatically.  If it's not working for you, give it 24 hours for the nameserver change to propagate.
