### ISSUE TITLE
`stack runghc`, interplay of `--package` and `--no-ghc-package-path`

### ISSUE THREAD

**Issue by sgraf812** [commercialhaskell/stack#1626]
Hi,

I'm writing a `turtle` script which compiles packages through `cabal`. As noted in the stack docs, `GHC_PACKAGE_PATH` interferes with `cabal` builds, so I currently unset it manually before executing `cabal`.

I however think it would be more elegant if I could specify `--no-ghc-package-path` in the 2nd line stack comment, like:
```
-- stack --resolver lts-3.20 --install-ghc runghc --no-ghc-package-path --package turtle 
```
But then `runghc` complains that it can't find `Turtle` et al. I suspect that you can't have both the package dependency on turtle resolved and no `GHC_PACKAGE_PATH` set, am I right?

**Comment by borsboom** [comment]
Right, the GHC_PACKAGE_PATH needs to be set so that `runghc` can find packages. The best way around this sort of thing is to compile your script to an executable and then run the executable outside the Stack context.

**Comment by sgraf812** [comment]
OK, thanks for the clarification. I'll stay with `unset`ing then.
