### ISSUE TITLE
Docker Derivative Images

### ISSUE THREAD

**Issue by KyleOndy** [commercialhaskell/stack#1627]
I am in the position of needing an additional application installed in my docker image. However using the docker [derivative images](http://docs.haskellstack.org/en/latest/docker_integration.html#derivative-image) instructions fail.

    $ stack --version
    Version 1.0.1, Git revision b10bee1d0e49aa230e9929c3a9e797581b250ebe x86_64

    $ stack --docker-persist --docker-container-name=temp docker exec bash
    Invalid argument `exec'
    Auxiliary command not found in path `stack---docker-persist'
    File does not exist or is not a regular file `--docker-persist'
    
    Usage: stack docker COMMAND|FILE [--help]
      Subcommands specific to Docker use
    $

Is this feature implemented? If not, should the documentation contain this information?

**Comment by borsboom** [comment]
The command should be
```
stack  --docker-persist --docker-container-name=temp exec --plain bash
```
I've fixed the docs.

**Comment by KyleOndy** [comment]
Thanks!
