### ISSUE TITLE
Wrong path to BASH on NixOS

### ISSUE THREAD

**Issue by Pitometsu** [commercialhaskell/stack#1630]
```
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-7.10.3.                                     
Configuring GHC ...Running /tmp/stack-setup13263/ghc-7.10.3/configure --prefix=/home/netsu/.stack/programs/x86_64-linux/ghc-7.10.3/ exited with ExitFailure 1
checking for path to top of build tree... 
/tmp/stack-setup13263/ghc-7.10.3/configure: utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: /bin/bash: bad interpreter: No such file or directory
configure: error: cannot determine current directory
```
This PATH Posix incompatible.
```
 > which bash
/run/current-system/sw/bin/bash
```
Should use `/usr/bin/env bash` or `/bin/sh`.

**Comment by Pitometsu** [comment]
Oh, [sorry](https://github.com/commercialhaskell/stack/issues/826)

But how migrate to other LTS with other GHC? Probably it's NixOS issue...

**Comment by borsboom** [comment]
You can install the newer GHC version manually (or using Nix's packages).  Just make sure the GHC version on your PATH matches that required by LTS.  Unfortunately it does make switching between LTS major versions annoying (although using [`compiler-check: newer-minor`](http://docs.haskellstack.org/en/stable/yaml_configuration.html#compiler-check) may help).
