### ISSUE TITLE
Have setup for ghcjs check installed node, possibly also setting it up

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1632]
Node versions bit us in https://github.com/commercialhaskell/stack/issues/1496

The reason this wasn't handled before is that there was no clear way to pick a version, and at the time, no known issues due to node version.

Here's how I think this should work:
- Have a special comment in ghcjs's stack.yaml file like `-- node >= 0.10 && < 1.0`.  When this comment is missing, assume a default.
- Check the version of the installed node?  Maybe we always want to install a sandboxed version so that later on, PATH variations don't affect things.
- Install the latest version of node that matches the constraint.  We'll either need to add info to our setup-info yaml, or possibly scrape the info from elsewhere.

**Comment by yamafaktory** [comment]
Hi @mgsloan,

Many thanks for solving the referenced issue!

One reliable way to get sandboxed node versions is to use something like [nvm](https://github.com/creationix/nvm). The only caveat is that Windows is not currently supported.

**Comment by 3noch** [comment]
Has anyone been found a more recent version of node that does not have this issue? Or is it an interface mismatch between our toolchain and node?

**Comment by mgsloan** [comment]
I haven't investigated the actual underlying issue.  I've heard that node 5.0 works fine.  5.3 is known to be broken.

**Comment by geraldus** [comment]
@mgsloan can you give a try to `node` v5.5.0?

**Comment by mgsloan** [comment]
Uhh, I could.  Note to everyone that I am not prioritizing investigating the details of this issue, I'm pretty happy with figuring out that it's a node problem.  I know very little about node, and so I don't think I'll be very effective at tracking it down.

I think it makes sense to determine what the actual root issue is before trying to enforce version constraints based on it.

**Comment by geraldus** [comment]
@mgsloan I understand, the reason I've asked you because I did not faced this issue myself; if you can confirm that v5.5.0 works fine it will help other people I guess (:
I know about node as much as you, and still can't find a way to contribute to this amazing project.

**Comment by rbtcollins** [comment]
Hi, got here following the reports of issues - FWIW 5.6 shows the breakage for me. Using a comment seems odd in a structured file - surely some actual key would be more appropriate?

**Comment by mgsloan** [comment]
Here's the ghcjs issue with the most up-to-date info: https://github.com/ghcjs/ghcjs/issues/453

So, I think the following should happen:

* Determine the best node version which is known to work, and automate setting it up.

* Choose later versions of node if the ghcjs version is recent enough (after luite's fix)?  Then again in the linked ticket, luite says "Once the fix is in a released version of node.js, a version check should probably be added, or at least a comment.", so I suppose using the hack isn't so ideal.

I'm thinking we should always install our own node version and ignore the system version, since node is small.

Unfortunately, I don't think luite's tarballs have the version in the ghcjs cabal file modified with the date, so we can't reliably change stack's behavior based on these versions.  So, conservatively with these tarballs we will need to use an old node when the ghcjs version lacks a date (when it's just `0.2.0`)

**Comment by mgsloan** [comment]
In https://github.com/commercialhaskell/stack/issues/2364 , it sounds like node 6.3 is broken, not sure what version introduced the issue.

**Comment by gleachkr** [comment]
6.2.2 works fine, so it seems like it probably started with 6.3

**Comment by tolysz** [comment]
Hi is anyone working on something?
I would need some setting to say which nodejs to pass to ghcjs (while doing setup on it). The argument is: `--with-node`
I need it as I would like to start testing my (stack ghcjs) bundles across multiple nodejs versions

**Comment by mgsloan** [comment]
@tolysz I don't think anyone is actively working on this.  If you want to work on it, feel free to assign it to yourself and open a PR.

A very useful thing would be to figure out which node versions and ghcjs versions work well.  Something complicating this is that some newer tarballs include fixes that work around node issues, that aren't in older tarballs.  They all claim to be 0.2.0, so it is tricky to do anything systematic about this until ghcjs has a proper release process.

**Comment by tolysz** [comment]
Looks like `ghcjs` should have the option already
https://github.com/ghcjs/ghcjs/blob/7aa7bae05b306bdb8f7a9c6e292ce74736e4541d/src-bin/Boot.hs#L508

So I would need to add something to yaml... maybe in the setup section? What do you think.

"Figuring out" is really a devops task, setup "docker" with diferent nodes and have some test projects to build.

"They all claim to be 0.2.0" the version will be always wrong (I use - http://tolysz.org/ghcjs/ ). We need some dual versioning- one for the `ghcjs` one for `resolver`, or maybe ghcjs respecting resolvers?

**Comment by mgsloan** [comment]
We already have dual versioning as you can override the compiler setting via, e.g.

```
compiler: ghcjs-0.1.0.20150924_ghc-7.10.2
compiler-check: match-exact
```

Heck it's really triple versioning, as you specify both the GHCJS and GHC version.

**Comment by tolysz** [comment]
We need a triple versioning :)
1 for ghcjs, 1 for resolver, 1 for compiler

**Comment by mgsloan** [comment]
We already have that!  How is compiler and ghcjs version different?

**Comment by tolysz** [comment]
Ok maybe I am looking at it wrong: resolver -> (compiler, boot package versions).
thus the minimum is (`ghcjs-version` + `resolver version`) as version

**Comment by mgsloan** [comment]
Right!  But stack's ghcjs support has a hack where it ignores version differences between snapshot package versions and packages in the global DB.

So it is really:

1) resolver -> (GHC version wanted, versions of non-boot packages)
2) compiler -> overrides to instead use GHCJS.  Can specify any version, doesn't need to match the GHC version in the resolver.
3) `compiler-match: exact` -> allows using a full version number, instead of matching based on just the first 2 numbers in the compiler version (`minor` is the default).

**Comment by tolysz** [comment]
:) hack or not; I use the exact versions that the resolver has to create `boot.tar` ;) including `base`...

**Comment by mgsloan** [comment]
That is super awesome @tolysz !! Great work :)

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
