### ISSUE TITLE
Stack setup error

### ISSUE THREAD

**Issue by ShobhitMaheshwari** [commercialhaskell/stack#1633]
When I run stack setup, I get following error. The system is Ubuntu 14.04.3 LTS

2d [shobhit:~/IdeaProjects/HaskellTutorial] $ stack setup                                                                                      
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                 
Running /tmp/stack-setup12713/ghc-7.10.3/configure --prefix=/home/shobhit/.stack/programs/x86_64-linux/ghc-7.10.3/ exited with ExitFailure 77
checking for path to top of build tree... /tmp/stack-setup12713/ghc-7.10.3
Build platform inferred as: x86_64-unknown-linux
Host platform inferred as: x86_64-unknown-linux
Target platform inferred as: x86_64-unknown-linux
GHC build  : x86_64-unknown-linux
GHC host   : x86_64-unknown-linux
GHC target : x86_64-unknown-linux
checking for perl... /usr/bin/perl
checking for a BSD-compatible install... /usr/bin/install -c
checking whether ln -s works... yes
checking for gsed... sed
checking for gcc... /usr/bin/gcc
checking for llc-3.5... no
checking for llc... no
checking  is version 3.5... no
checking for opt-3.5... no
checking for opt... no
checking  is version 3.5... no
checking for ld... /usr/bin/ld
checking for gcc... /usr/bin/gcc
checking whether the C compiler works... no

/tmp/stack-setup12713/ghc-7.10.3/configure: line 3866: --version: command not found
/tmp/stack-setup12713/ghc-7.10.3/configure: line 4113: --version: command not found
configure: error: in `/tmp/stack-setup12713/ghc-7.10.3':
configure: error: C compiler cannot create executables
See `config.log' for more details

Configuring GHC ...2d [shobhit:~/IdeaProjects/HaskellTutorial] 12s 1 $

**Comment by mgsloan** [comment]
Looks like your system gcc is broken.  What happens if you just run `gcc`?  Perhaps try reinstalling gcc, or installing a newer version?

**Comment by ShobhitMaheshwari** [comment]
gcc was the problem. I reinstalled it. It's working.

**Comment by ashishsc** [comment]
Hmm, I have the latest gcc on ubuntu 16.04, yet I still have this problem, what distro are you on @ShobhitMaheshwari ?

**Comment by Gothdo** [comment]
@ashishsc For me installing `build-essential` and `zlib1g-dev` (`sudo apt-get install -y build-essential zlib1g-dev`) solved this problem.

**Comment by FelschR** [comment]
On Solus `sudo eopkg it -c system.devel` did the trick.
