### ISSUE TITLE
Can Stack make sure that dependencies aren't tampered with?

### ISSUE THREAD

**Issue by ppetr** [commercialhaskell/stack#1636]
I asked [this question on SO](http://stackoverflow.com/q/34698377/1333025), and as suggested, I'm re-posting it here, as it seems questions are allowed here:

One problem with Cabal is that it pulls packages from Hackage, and as [it's been discussed](https://mail.haskell.org/pipermail/haskell-cafe/2013-January/106051.html) some time ago, there are many ways how a piece of malicious code can get in. Does Stack improve the situation and does it take any precautions against that? Is it possible to make sure that all code downloaded externally for a given project is verified? This includes extra dependencies - if there are any declared, is it possible to let stack verify them, for example to give an expected hash of the downloaded package?

**Comment by mgsloan** [comment]
Yup, stack has had security for this for nearly half a year.  Here's a relevant blogpost: https://www.fpcomplete.com/blog/2015/07/package-security-in-stack
