### ISSUE TITLE
Only build profiling libraries on demand

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#165]
Motivation: faster initial builds, work in use cases where GHC's profiling libraries aren't available.

We should have a user friendly error message when trying to build a profiling library and a profiling version of base is unavailable.

**Comment by codygman** [comment]
> We should have a user friendly error message when trying to build a profiling library and a profiling version of base is unavailable.

I was about to file an issue for this since I ran into this problem, but looks like it'll be in the next stack release. :+1: 

Thanks for all your hard work!
