### ISSUE TITLE
Allow stack test to skip certain test suites

### ISSUE THREAD

**Issue by dmcclean** [commercialhaskell/stack#1659]
It would be great to have a flag like `stack test --skip long-tests` that would skip the test suite named `long-tests` in the cabal file.

Duration isn't the only reason for wanting something like this. Some tests are also difficult to get running on older LTS versions (because they are on old versions of various libraries that are used by the tests but not the library under test). Some tests are difficult to get running on the CI server because they require external resources like a database.

For symmetry it would be good if it was also accepted by `stack bench`. I'm not sure if cabal allows a benchmark and a test suite from the same project to have overlapping names, but if it does then there might need to be two flags instead, `--skip-tests` and `--skip-benchmarks`.

**Comment by borsboom** [comment]
Agreed, that would be handy.  A pull request adding this feature would be welcome.

Note: It's possible to achieve something like this using flags that enable or disable tests in the .cabal file (see Stack's own stack.cabal for an example with the `integration-tests` flag).

**Comment by mgsloan** [comment]
Adding `--skip COMPONENT` to `build` options makes sense to me, and probably everywhere else that takes per-component targets.  In other words, the feature can be part of determining targets, not specific to tests / benchmarks.

**Comment by snoyberg** [comment]
This is implemented via #3148, closing.
