### ISSUE TITLE
More control over searching for stack.yaml file?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1662]
Sometimes, you want a `stack.yaml` in a subdirectory to be preferred over your main project `stack.yaml`.  For example, this is convenient when you have a sub-directory for your clientside code, which is built with GHCJS.  This is the current behavior.

Other times, such as when you have a git submodule with a `stack.yaml`, you'd prefer to use the outer project `stack.yaml` instead.

Should we do something about this?  It seems complicated to allow both of these usecases to exist at once (would require fine grained configuration).  Maybe it'd be good to have a plain boolean flag that allows switching to this alternative behavior.

The downside of this is that every stack invocation would need to first find and parse the outermost stack.yaml.

**Comment by silky** [comment]
you could have a `.stack` file that, when in the current directory, forces stack to prefer the stack.yaml in that directory? (maybe there could be some data in it, or it could simply be empty)

**Comment by mgsloan** [comment]
Hmm, that's an interesting idea!  We could make this part of the behavior of `stack.local.yaml`, described [here](https://github.com/commercialhaskell/stack/issues/846#issuecomment-169455997).  While this feels a bit arbitrary, I think it could work well.  Having a local configuration is a pretty clear "opt-in" that that stack.yaml is the primary one for the project.
