### ISSUE TITLE
Building with ghcjs: "ghc-pkg: Prelude.chr: bad argument: 2980338"

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#1665]
I'm trying to build a hello-world app with reflex-dom. The build keeps dying with the error message mentioned in the title.

Also,

1. The build gets a little further (compiles/registers a few more libraries) every time.
2. The "bad argument" changes from one big number to another.

Here's two examples. The first is verbose, and with some older version of stack. The second is not verbose, and run with master as of this very moment. (`Version 1.0.1, Git revision c4d36d888f01b9467c4cfbe612461e126330677a (dirty) (3075 commits) x86_64`)

* [Example 1, verbose](http://lpaste.net/149824)
* [Example 2, not verbose but current master](http://lpaste.net/149829)

Repro could take a long time because of all the upfront building that has to happen, but here are the steps:

    git clone --recursive https://github.com/chreekat/multi-fladdermus.git
    cd multi-fladdermus/fladdermus-client
    git checkout 306df51724a9e8ccae4a7262d0b3d3613caa8c65
    stack setup
    stack build

A conflating factor could be:

* I'm using https://github.com/nrolland/ghcjs/releases/tag/v.0.2.0.20151230.3 as my version of ghcjs.

***********************

This is probably unrelated, but I find it strange that I see this message at the beginning of every run:

    data-default-class-0.0.1: using precompiled package

**Comment by chreekat** [comment]
Ah! I did a `while ! stack build; do sleep 5; done` loop, and hit a fix point. :)

Here is the verbose output I get every time now: http://lpaste.net/149831

**Comment by mgsloan** [comment]
Interesting, thanks for the report!  Still building that version of GHCJS, so I haven't tested your repro.  I have pushed a probable fix, though.  Does it resolve the issue for you?

**Comment by chreekat** [comment]
Success! I had to unregister data-default-class, but after doing so `stack build` ran successfully and my hello-world app ran correctly in the browser. Thanks!
