### ISSUE TITLE
Include packunused feature

### ISSUE THREAD

**Issue by wereHamster** [commercialhaskell/stack#1667]
[packunused](http://hackage.haskell.org/package/packunused) doesn't work with stack, it requires cabal. Would be nice to have such a tool included in stack itself, and use it for example as part of the checks performed in `sdist` or `upload` (see #1334).

**Comment by mgsloan** [comment]
This is actually a dupe of our oldest open issue - https://github.com/commercialhaskell/stack/issues/39 :D
