### ISSUE TITLE
Stack fails to download build plan on Windows

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#1668]
Recently I had to build some projects on *Windows*. I decided to use Stack this time, but it failed to download build plan with something like this:

```
TlsExceptionHostPort (HandshakeFailed (Error_Protocol ("certificate has unknown CA"))) "raw.githubusercontent.com" 443
```

I didn't try again and resorted to ~~good~~ old Cabal boilerplate with MinGHC. I thought I'd better report this.

**Comment by borsboom** [comment]
See http://stackoverflow.com/questions/32654493/stack-haskell-throws-tlsexception-in-windows/32654494#32654494 and #234.  Please re-open this issue if following the advice in those doesn't help.

**Comment by dysinger** [comment]
I removed internet explorer from my Windows 7 install so the advice above "visit the TLS site with IE & it will add the CA" doesn't work for me.
