### ISSUE TITLE
Dependency of 1.0.2 prevents installation with stock GHC 7.10.3 collection

### ISSUE THREAD

**Issue by felixonmars** [commercialhaskell/stack#1670]
I have noticed that the new 1.0.2 release requires Cabal >=1.22.6.0, while the latest GHC 7.10.3 contains 1.22.5.0. Since I am packaging for Arch and we are not providing a separate Cabal package currently, I would like to have some suggestions on the situation.

Should we 1) stuck on stack 1.0.0 until next GHC release or 2) consider unpacking GHC and provide a separated cabal package?

Or it would be simpler if stack would consider to release a new release that could work with older Cabal.

Thanks!

**Comment by borsboom** [comment]
I've adjusted the lower bound.  That one just snuck in there when we upgraded to LTS 4.

Long term, I'd say "2) consider unpacking GHC and provide a separated cabal package" would be a good idea.  Cabal is bundled with GHC but is not one of its core packages, so it should be possible to use a later version (the same goes for some other packages that are bundled with GHC).

**Comment by felixonmars** [comment]
I see, thanks!
