### ISSUE TITLE
On travis, stack fails with "InvalidAbsFile"

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#1671]
Calling stack on travis with `--stack-yaml stack.yaml` fails with

```
$ ./travis_long stack --no-terminal --skip-ghc-check --stack-yaml $STACK_CONFIG test
InvalidAbsFile "stack.yaml"
stack --no-terminal --skip-ghc-check --stack-yaml stack.yaml test finished.
```

https://travis-ci.org/alanz/HaRe/jobs/103193382#L298

If the `--stack-yaml` parameter is left out it fails with the same problem.

If the `stack-yaml` parameter has a full path (`/home/travis/build/alanz/HaRe/stack.yaml`) then it builds.

$ stack --version
Version 1.0.2, Git revision fa09a980d8bb3df88b2a9193cd9bf84cc6c419b3 (3084 commits) x86_64

**Comment by silky** [comment]
maybe i'm missung something, but your travis build failed because `stack.yaml` wasn't found; it seems like your stack file is called `stack-travis.yaml` ?

**Comment by alanz** [comment]
Yes it does. And it builds if It is set via STACK_YAML environment variable,  but the tests can't can't have that set.

**Comment by borsboom** [comment]
Huh, that's weird, because it seems to mean that `canonicalizePath` isn't returning an absolute path in this case.  The code for handling STACK_YAML seems to take a different approach to the same thing, so that probably explains the difference in behaviour.  I don't think there's any reason they shouldn't share the same code to resolve the file.

**Comment by mgsloan** [comment]
I've pushed a refactoring to use the `parseRelAsAbsDir` utility.  The code is essentially the same, though, so I don't anticipate that it will fix it.  Strange issue indeed!

**Comment by borsboom** [comment]
The STACK_YAML code does it this way:

```
            liftM Just $ case parseAbsFile fp of
                Left _ -> do
                    currDir <- getWorkingDir
                    resolveFile currDir fp
                Right path -> return path
```

I wonder if it could make sense to have `parseRelAsAbsDir` work the same way.

**Comment by mgsloan** [comment]
Ah, yeah, good point!  Seems reasonable to me.

**Comment by mgsloan** [comment]
Old ticket, closing.  Please reopen if it's still an issue.

I took a look at the code, and STACK_YAML / --stack-yaml use the same approach - `resolveFile'`

**Comment by 23Skidoo** [comment]
This started happening on Cabal Travis all of a sudden: https://travis-ci.org/haskell/cabal/jobs/333032268

**Comment by mgsloan** [comment]
@23Skidoo Thanks for pinging me on this!  I have opened a PR that might fix it https://github.com/haskell/cabal/pull/5071 .  Theory is that it was using an old version of stack.
