### ISSUE TITLE
Check for recent version during calls?

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#1681]
The [cocoa pods](https://cocoapods.org) `pod` command checks for the latest version upon each invocation, and lets one know if there is a newer version available. I would like to see such a feature added to `stack`.

**Comment by mgsloan** [comment]
Hmm, interesting idea!  Thoughts:

* May be worthwhile to have logic for doing this request occasionally rather than every stack invocation.

* It'd be good to have a way to disable it.  The [offline](https://github.com/commercialhaskell/stack/issues/1594) flag is also relevant.

*

**Comment by angerman** [comment]
I guess it depends on:
- how fast ist the check? Say if haskellstack.org/latest returns just the version number, that could be pretty quick.
- how frequent do we want to check (once per day?)

For disabling it: 
- allow option to disable it; this could be considered tracking  
  *NB: cocoa pods even does some additional tracking on which packages are used; this rubs some the very wrong way, understandably.*

So either go with `~/.stack/config.yaml` and or an environment variable?

**Comment by mgsloan** [comment]
Once per day seems reasonable.  Doing a check is fast, but it's still a network request, seems best to avoid doing lots of them. 

> NB: cocoa pods even does some additional tracking on which packages are used; this rubs some the very wrong way, understandably.

It'd be cool to have an opt-in option for this.  It'd be cool to see what things are most popular, and infer related sets of packages ("often used with: ...").

> So either go with ~/.stack/config.yaml and or an environment variable?

Yeah, makes sense!

**Comment by angerman** [comment]
Ohh there's another thing, I did not mentioned. When something goes wrong, they basically provide you all the information to create a useful issue, though they advise you to clean up all potential private data.

**Comment by angerman** [comment]
Here's the relevant statistics post from cocoa pods, for the record:
- http://blog.cocoapods.org/Stats/

**Comment by mgsloan** [comment]
I'm bumping this to P2: Should, because I've been seeing lots of bug reports from people using their distro version and encountering things that have been fixed.  While this won't solve things for those current versions, once the distro versions ship the thing with the check, this will hopefully happen less.

**Comment by borsboom** [comment]
I just added a note to CONTRIBUTING.md to check using the latest version
before reporting a bug.  Not everyone actually looks at that before
reporting, but hopefully it will at least reduce the number of incidences.

>

**Comment by mgsloan** [comment]
It would also be nice to have this check for deprecated versions.  Would be really handy in circumstances like #2000 where we'd like to get users off affected versions.

**Comment by chrisdone** [comment]
I'd also suggest doing the check when in the **terminal**. Many stack invocations are run by other tooling, so it would be hidden, and a waste of resources. In the terminal at least gives a higher probability of the user actually seeing it.

**Comment by sjakobi** [comment]
@borsboom commented on #2355 (duplicate):

> It would make sense to implement this in conjunction with #1238 (have stack upgrade download a new binary when possible rather than building from source).
