### ISSUE TITLE
build progress counter is no longer visible

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/stack#1685]
I noticed this after upgrading to 1.0.2, the progress counter never shows when building multiple packages, instead there's just an empty line. If i hit Ctrl-C the progress prints before stack exits

```
test-1: build
^CProgress: 0/37user interrupt
Progress: 1/37⏎
```

**Comment by mgsloan** [comment]
Hmm, good point!  Regression caused by https://github.com/commercialhaskell/stack/commit/3003354cb2823703bd691044364c7896a51b7b24 , should have tested that more thoroughly.  The fix is to flush stderr after writing the sticky message.
