### ISSUE TITLE
--prefetch --dry-run intermittently hangs with a large number of dependencies - Windows

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/stack#1689]
Sometimes, when I run `stack build --only-snapshot --prefetch --dry-run` Stack hangs after the last download message is printed. Process Explorer and Resource Monitor report there are no network connections open, stack.exe is using ~12% CPU which corresponds to pegging one virtual core on my machine, and the vast majority of the CPU time is spent in kernel. The active thread, according to Process Explorer, is in `ntdll.dll!ZwDeviceIoControlFile+0xa` most of the time.

To reproduce:
- Grab the repo at https://github.com/enolan/stack-download-hang
- Clear `%APPDATA%\Roaming\stack\indices\Hackage` and `%APPDATA%\Roaming\stack\snapshots`
- `stack build --only-snapshot --prefetch --dry-run --verbose`

Here's a log https://gist.github.com/enolan/25aad1613c42fee5fcbf

**Comment by mgsloan** [comment]
Wow, thanks for figuring out the GHC issue and writing a blogpost about it http://www.echonolan.net/posts/2016-05-10-a-debugging-horror-story.html

Hopefully there will be a GHC release soon with the fix.  Once released, I wonder if we should only release the windows version compiled with that GHC.

**Comment by enolan** [comment]
@mgsloan The fix didn't make it into GHC 8.0 unfortunately. :(

I wrote a workaround in `network` but that has its own problem - another crash. I made have added it when doing the workaround, or it may have always been there. Here's the `network` PR if anyone wants to take a look: haskell/network#192. If you can tell me why it's still crashing I'd be happy.

**Comment by mgsloan** [comment]
Closing as an upstream issue
