### ISSUE TITLE
Error on NixOs when fresh install Stack

### ISSUE THREAD

**Issue by AlleaRizary** [commercialhaskell/stack#1694]
Hi, i got this error when i run stack setup in global config:

Configuring GHC ...Running /tmp/stack-setup6107/ghc-7.10.3/configure --prefix=/home/rizimain/.stack/programs/x86_64-linux/ghc-7.10.3/ exited with ExitFailure 1
checking for path to top of build tree... 
/tmp/stack-setup6107/ghc-7.10.3/configure: utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: /bin/bash: bad interpreter: No such file or directory
configure: error: cannot determine current directory

i haven't install cabal-install nor GHC, so i presume that stack would install the ghc itself. I am not using root when i do this.

at first it asked for make, and i already install gnumake, but getting those error.

Thanks for your help

**Comment by mgsloan** [comment]
What does `which bash` return?  I bet it's not `/bin/bash`.  I'm not very familiar with NixOS, so not sure why you wouldn't have `/bin/bash`.  As a hack, you could probably symlink your bash (maybe `/usr/bin/bash`?) to `/bin/bash`.

**Comment by mboes** [comment]
`stack setup` doesn't work on NixOS. The issue is that NixOS requires specific bindists of GHC and virtually everything else to work properly, seeing as the paths are very different from what they normally are on other distros.

So you have three options:

* use a GHC installed via `nix-env -i ghc`;
* use `stack --nix` and configure stack's [integration with the Nix package manager](http://docs.haskellstack.org/en/stable/nix_integration.html) (independent of the distro);
* use `stack --docker` and configure stack's [Docker integration](http://docs.haskellstack.org/en/stable/docker_integration.html) (i.e. build inside a container that includes another distro than NixOS).

**Comment by Pitometsu** [comment]
@mboes second option do not work :(

```
$ tail -n 23 stack.yaml 

# Nix integration
nix:
  enable: true
  # because cabal dependencies also depend
  # on next external packages, but don't
  # require it explicitly...
  #
  #packages: [ postgresql95, zlib.dev ] # zlib gcc git
  #pure: false
  # ...let's load it from nix script directly
  #shell-file: shell.nix
  # because git ssl broken on nix, should use script
  shell-file: stack_shell.nix

# pretty printing for GHCi
#
# be careful here:
# it looks good in plain stack ghci
# but conflict with interactive-haskell in emacs
#
ghc-options:
  "*": -ghci-script .ghci_conf
netsu@hackbook [02:28:21 PM] [~/Projects/Kelecorix/admerge] [nix *] 
-> % cat stack_shell.nix
# not sure why this not working and how pass lts from stack to nix here
# {ghc}:

with (import <nixpkgs> { config.allowUnfree = true; });

haskell.lib.buildStackProject {
  inherit ghc;
  name = "stackDevEnv";
  buildInputs = [ bash git postgresql95 zlib gcc pkgconfig openssl cacert ];
  shellHook = ''
    export GIT_SSL_CAINFO='/etc/ssl/certs/ca-certificates.crt'
  '';
}
$ stack setup
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                 
Running /run/user/1000/stack-setup16536/ghc-7.10.3/configure --prefix=/home/netsu/.stack/programs/x86_64-linux/ghc-7.10.3/ in directory /run/user/1000/stack-setup16536/ghc-7.10.3/ exited with ExitFailure 1

checking for path to top of build tree... 
/run/user/1000/stack-setup16536/ghc-7.10.3/configure: utils/ghc-pwd/dist-install/build/tmp/ghc-pwd-bindist: /bin/bash: bad interpreter: No such file or directory
configure: error: cannot determine current directory

Configuring GHC ...%                                                                                                                                                                                                                                                            $ 
```

**Comment by Pitometsu** [comment]
Even in case if I will install it via nix, how can I pass proper required by stack GHC version to nix?

**Comment by Pitometsu** [comment]
It works e.g. with `ghc = haskell.packages.lts-5_15.ghc;` But stack should pass which `lts` exactly in use.

**Comment by Pitometsu** [comment]
Oh, maybe I just use old
```
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
```
Sorry for noise.
