### ISSUE TITLE
Stack fails to find cabal even though it's in PATH

### ISSUE THREAD

**Issue by k0ral** [commercialhaskell/stack#1696]
I'm running stack on NixOS, and here is what I have:

```bash
> echo $PATH
/home/koral/bin /var/setuid-wrappers /home/koral/.nix-profile/bin /home/koral/.nix-profile/sbin /home/koral/.nix-profile/lib/kde4/libexec /nix/var/nix/profiles/default/bin /nix/var/nix/profiles/default/sbin /nix/var/nix/profiles/default/lib/kde4/libexec /run/current-system/sw/bin /run/current-system/sw/sbin /run/current-system/sw/lib/kde4/libexec

> /home/koral/.nix-profile/bin/cabal --version
cabal-install version 1.22.7.0
using version 1.22.5.0 of the Cabal library

> stack --nix solver
Solver requires that cabal be on your PATH
Try running 'stack install cabal-install'
```

Could you please assist ?

**Comment by k0ral** [comment]
Solution was to add `cabal-install` to the packages list included in the nix environment (in `stack.yaml`):

```
nix:
  enable: true
  packages: [cabal-install]
```

Maybe it ought to be better advertised by the documentation.

**Comment by YPares** [comment]
Actually, it's because Stack builds in a pure shell by default.

Running `stack --no-nix-pure solver` would find your system cabal-install.

2016-01-23 19:46 GMT+01:00 k0ral <notifications@github.com>:

**Comment by mboes** [comment]
> Running `stack --no-nix-pure solver` would find your system cabal-install.

FTR, @k0ral original solution is better: using `--no-nix-pure` hinders build reproducibility. The fact that Nix shells created by Stack are "pure" is prominently documented [here](http://docs.haskellstack.org/en/stable/nix_integration.html#the-nix-shell), but I guess a note could be added to the Guide's section about using a solver.
