### ISSUE TITLE
Use a separate package instead of `Path.IO` helper module

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#1701]
Recently I've released [`path-io`](https://hackage.haskell.org/package/path-io) package that provides well-typed interface to `directory` and some extra functions like recursive scanning and copying of directories. I made this mainly for my personal needs, but I'll be glad if more people find it useful.

Now I've got [an issue](https://github.com/mrkkrp/path-io/issues/2) asking to add missing functions from Stack's `Path.IO` and proposing that Stack could switch to depending on the package. I'm fine with adding more functions to `path-io` if you think that depending on it is a good idea. Otherwise I just don't need those functions myself and there is no point in wasting time writing them.

In the case if you are fine with switching I could even prepare a PR for this. What do you think?

**Comment by mgsloan** [comment]
Sure!  I like where you've gone with the API and docs.

If some of the functions in stack's `Path.IO` seem too specialized, they can get moved to `Path.IO.Extra`.

**Comment by mrkkrp** [comment]
Great, I'll add this to my TODO list then :-)
