### ISSUE TITLE
ghcjs: stack install doesn't copy the file. Does Setup.hs work?

### ISSUE THREAD

**Issue by emmanueltouzery** [commercialhaskell/stack#1708]
In https://github.com/commercialhaskell/stack/issues/337#issuecomment-174625103 I mentioned that `stack install` does not copy the generated files over for `ghcjs` projects.
I think it might make sense to make it work out of the box, and there it was mentioned to maybe open a separate bug, so that's it.

However while I'm at it, I also have a related question. Since it doesn't copy the files for me, I decided that I'll do it myself with a custom `Setup.hs` and a cabal `Build-type: Custom`, but my `Setup.hs` doesn't seem to get invoked. Looking a bit with `strace`, I'm actually wondering if `ghcjs` is not invoked in place of `ghc` for the `Setup.hs`, and if that is the case, I'm wondering whether it's a good thing or not?

**Comment by mgsloan** [comment]
> In #337 (comment) I mentioned that stack install does not copy the generated files over for ghcjs projects.

Certainly a reasonable thing to track, thanks!

> However while I'm at it, I also have a related question. Since it doesn't copy the files for me, I decided that I'll do it myself with a custom `Setup.hs` and a cabal `Build-type: Custom`, but my `Setup.hs` doesn't seem to get invoked. Looking a bit with `strace`, I'm actually wondering if `ghcjs` is not invoked in place of `ghc` for the `Setup.hs`, and if that is the case, I'm wondering whether it's a good thing or not?

This should work.  The `Setup.hs` files get compiled by `ghcjs`, and the result gets run by `node` to execute the build.

**Comment by emmanueltouzery** [comment]
ok so if we focus on the second issue for now, the Setup.hs (maybe I should open two bugs.. although I guess the issues are kind of connected) -- with the Setup.hs, we don't strictly need the install support. Without it... it's very complicated (not sure how to get the stack/cabal installation folders to copy files from).

Here is a sample project where I get the issue:
https://www.dropbox.com/s/e3j6l9ukb0zzp2j/test-ghcjs.tgz?dl=0

* in the .cabal file, the Build-Type is Custom
* in the Setup.hs, I do putStrLn of the build folder. This is a Setup.hs I have on a non-ghcjs project and it works fine there. Same I issue if I also do a trivial Setup.hs.
* node works because if I run `node /home/emmanuel/home/2/test-ghcjs/.stack-work/install/x86_64-linux/lts-3.10/ghcjs-0.1.0.20150924_ghc-7.10.2/bin/cigale-web.jsexe/all.js` that works fine.
* `ghcjs Setup.hs` does work, and then `node Setup.jsexe/all.js` works (prints `no command given (try --help)`

Maybe I'm doing something wrong... but right now I can't see what :-(

**Comment by mgsloan** [comment]
Are you sure the output is absent? I see it:

```
web-gui-0.1: configure
[1 of 1] Compiling Main             ( /home/mgsloan/fpco/test-stack/issue1708/test-ghcjs/Setup.hs, /home/mgsloan/fpco/test-stack/issue1708/test-ghcjs/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/setup/Main.js_o )
Linking /home/mgsloan/fpco/test-stack/issue1708/test-ghcjs/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/setup/setup.jsexe (Main)
Configuring web-gui-0.1...
web-gui-0.1: build
Linking /home/mgsloan/fpco/test-stack/issue1708/test-ghcjs/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/setup/setup.jsexe (Main)
Preprocessing executable 'cigale-web' for web-gui-0.1...
[1 of 1] Compiling Main             ( App.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/cigale-web/cigale-web-tmp/Main.js_o )
Linking .stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/cigale-web/cigale-web.jsexe (Main)
appDataDir => /home/mgsloan/fpco/test-stack/issue1708/test-ghcjs/.stack-work/install/x86_64-linux/lts-3.10/ghcjs-0.1.0.20150924_ghc-7.10.2/share/x86_64-linux-ghcjs-0.1.0.20150924-ghc7_10_2/web-gui-0.1
web-gui-0.1: copy/register
Linking /home/mgsloan/fpco/test-stack/issue1708/test-ghcjs/.stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/setup/setup.jsexe (Main)
Installing executable(s) in
/home/mgsloan/fpco/test-stack/issue1708/test-ghcjs/.stack-work/install/x86_64-linux/lts-3.10/ghcjs-0.1.0.20150924_ghc-7.10.2/bin
Warning: the following files would be used as linker inputs, but linking is not being done: .stack-work/dist/x86_64-linux/Cabal-1.22.4.0_ghcjs/build/cigale-web/cigale-web
```

The line is `appDataDir => /home/mgsloan/fpco/test-stack/issue1708/test-ghcjs/.stack-work/install/x86_64-linux/lts-3.10/ghcjs-0.1.0.20150924_ghc-7.10.2/share/x86_64-linux-ghcjs-0.1.0.20150924-ghc7_10_2/web-gui-0.1`

**Comment by emmanueltouzery** [comment]
ok I see... It does run, but only the first time I run `stack install`. That may be normal though. I expected it to run every time I run stack install. After the first time I ran stack install, I must delete the `.stack-work` folder to make it run again. There's probably a command like `stack clean install` to make it run again though. So i guess that bit is OK and we can refocus the bug on the automatic file copy part.

**Comment by mgsloan** [comment]
Yeah, the post build hook won't be run if the build doesn't need to happen (it detects if nothing has changed).

Since most of the discussion here isn't about the main topic, I've opened this issue #1710, and closing this one.

**Comment by emmanueltouzery** [comment]
ok. The reason I expected the Setup.hs to be re-run is because I changed it. So in a way, something did change. Makes developing/coding the Setup.hs a bit annoying. But I understand the logic.

**Comment by mgsloan** [comment]
@emmanueltouzery Ahhh, excellent point!  That is a rather unfortunate bug with the package dirtiness check https://github.com/commercialhaskell/stack/issues/1711 - `--force-dirty` causes the rebuild to happen properly.

**Comment by mgsloan** [comment]
#1711 is now fixed!
