### ISSUE TITLE
`stack setup` and `stack build` using different versions of GHC

### ISSUE THREAD

**Issue by bendmorris** [commercialhaskell/stack#1709]
```
bmorris (master)$ stack build
No GHC found, expected version 7.10.3 (x86_64) (based on resolver setting in /Users/bmorris/Dev/mydir/stack.yaml). Try running stack setup

bmorris (master)$ stack setup
Already downloaded.
Installed GHC.
Would add the following to PATH: /Users/bmorris/.stack/programs/x86_64-osx/ghc-7.10.2/bin

bmorris (master)$ stack build
No GHC found, expected version 7.10.3 (x86_64) (based on resolver setting in /Users/bmorris/Dev/mydir/stack.yaml). Try running stack setup
```

**Comment by mgsloan** [comment]
Strange!  What's the contents of `/Users/bmorris/Dev/mydir/stack.yaml`?

**Comment by harendra-kumar** [comment]
It seems setup and build are not agreeing on the compiler version. Setup is installing 7.10.2 and build is asking 7.10.3. What does your `stack.yaml` look like? What does `stack path` say?

**Comment by mgsloan** [comment]
Would also be good to know `stack --version`

**Comment by bendmorris** [comment]
```
$ cat stack.yaml
resolver: lts-4.1
$ stack --version
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
```

Running `stack path` seems to have the same issue as `stack build`:

```
$ stack path
No GHC found, expected version 7.10.3 (x86_64) (based on resolver setting in /Users/bmorris/Dev/mydir/stack.yaml). Try running stack setup
```

**Comment by harendra-kumar** [comment]
You seem to be running a pretty old version of stack. Can you try upgrading or installing the latest version?

**Comment by mgsloan** [comment]
Yeah, that's 7 months old, which is an aeon ago in terms of stack's development

**Comment by khazhyk** [comment]
Homebrew packages provide this version as the newest version.

**Comment by bendmorris** [comment]
It's also the version I get from `cabal install stack`.

**Comment by mgsloan** [comment]
@bendmorris  There are two possible explanations for that.  One is that your hackage index is very old (run `cabal update`).  The other possible reason is that you have old packages installed.  In this case, `cabal install` will pick a version of stack that is compatible with the installed packages, even if it's quite old.  This is one of the reasons stack exists.  With cabal-install, its behavior is determined by the state of the package DB, often with unintended results.

**Comment by borsboom** [comment]
Try forcing cabal-install to install the latest version using `cabal install stack-1.0.2`.  If you get dependency errors with that, building in a cabal sandbox may help.  And there's always the nuclear option:  `rm -rf ~/.cabal ~/.ghc` and start from scratch :)

**Comment by devonhollowood** [comment]
I've been having the same issue, with the same version of stack (0.1.2.0). It's the version that is [included](https://launchpad.net/ubuntu/+source/haskell-stack) in Ubuntu's main repository, in the `haskell-stack` package. Is that package no longer considered a good way to install `stack`?

**Comment by harendra-kumar** [comment]
Stack has undergone rapid development and has changed a lot since. The standard distro repositories might have older versions. You can try uninstalling the one from ubuntu repository and try this one: http://docs.haskellstack.org/en/stable/install_and_upgrade.html#ubuntu.

**Comment by devonhollowood** [comment]
That worked, thanks. Another workaround that I found was passing the `--install-ghc` flag to each `stack` command, although that seemed like overkill. So I'm glad using the fpcomplete repository worked!

**Comment by harendra-kumar** [comment]
This is an obsolete issue. Newer versions don't have it.
