### ISSUE TITLE
Setup.hs does not fire when adding package folders

### ISSUE THREAD

**Issue by emmanueltouzery** [commercialhaskell/stack#1712]
In bug #1708 I said that Setup.hs did not work for my ghcjs project. I then gave a sample project, for which it did work, but only the first time. But now I tried again with my real project, and even with `-force-dirty` the Setup.hs is never executed.

I noticed that the trigger is the `- reflex-dom/` line in my `stack.yaml`. If I do list that external package folder, then the `Setup.hs` is not executed. If I don't list it, then it is executed.

See the sample project there:
https://www.dropbox.com/s/0on768rn5yuz7q8/test-ghcjs2.tgz?dl=0

Now if it is indeed a bug, I would also be interested for a workaround so I don't have to wait for a new `stack` release?

**Comment by mgsloan** [comment]
On HEAD there are a few things that have been fixed which may be relevant.  Since this is an old issue, closing.  Feel free to reopen / open a new issue  if it's still problematic.
