### ISSUE TITLE
Link to stack guide broken

### ISSUE THREAD

**Issue by xrisk** [commercialhaskell/stack#1717]

**Comment by mgsloan** [comment]
I'm guessing you're talking about this issue https://github.com/commercialhaskell/stack/issues/1506 ?  Reopen with description if not.

**Comment by xrisk** [comment]
Ah, my bad. I attempted to click on a link from the Github repo, which obviously 404ed, being relative.

**Comment by mgsloan** [comment]
No worries, it's confusing and really ought to be fixed.
