### ISSUE TITLE
Precompiled binaries fail on RedHat 4.1.2-54

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1721]
Using the normal binaries I get:

    $ ./stack
    ./stack: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory

Using the CentOS 6.x binaries, I get:

    $ ./stack
    ./stack: /lib64/libpthread.so.0: version `GLIBC_2.12' not found (required by ./stack)
    ./stack: /lib64/libc.so.6: version `GLIBC_2.10' not found (required by ./stack)
    ./stack: /lib64/libc.so.6: version `GLIBC_2.11' not found (required by ./stack)
    ./stack: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by ./stack)

Not sure if there's anything that can be done about this. Any chance of reducing the dependencies of stack, e.g. by linking in more stuff?

I appreciate this system is ancient, and understand you may not want to bother fixing it.

Originally submitted to the wrong bug tracker at https://github.com/ndmitchell/shake/issues/411, but @vasiliyl made the good comment:

> You can compile stack as a static binary. Unfortunately glibc can't be linked statically, so you should use some other C library like musl. After that will "weight" tens of megabytes, but it will work anywhere.

**Comment by mgsloan** [comment]
`stack build --flag stack:static` seems relevant https://github.com/commercialhaskell/stack/pull/1654

**Comment by borsboom** [comment]
Even if we fix Stack for this case, do the GHC bindists work on this version of Red Hat?  We only release Stack binaries for platforms that GHC bindists support because otherwise `stack setup` won't work anyway.

When I'm preparing the next Stack release, I may try releasing static binaries as well and see how those are received.

**Comment by ndmitchell** [comment]
Hmm, true, I think we might have had to build our GHC from scratch. If so, seems reasonable that Stack doesn't work. However, I think static binaries can only be a good thing, given they should work in more places and let people bootstrap more easily. Feel free to either repurpose this ticket for putting static binaries in the latest release, or just close it.

**Comment by borsboom** [comment]
FYI: I tried a static Stack build (using `--flag stack:static` on Ubuntu 14.04) and the resulting binary segfaults if you actually try to make it do any real work.  This doesn't come as a shock (I wasn't expecting it to work; see https://www.reddit.com/r/haskell/comments/37m7q7/ghc_musl_easier_static_linking/cro3crs), but I thought I'd mention it.

I think before it becomes really practical to distribute static binaries, it would be best to have well supported GHC bindists that use musl.
