### ISSUE TITLE
Build command help - target syntax

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1723]
`stack build --help` does not provide any help or pointers for the TARGET syntax. So one has to search where it can be found. Can we put a pointer to the online docs with the version replaced with the corresponding stack version? e.g.:

```
TARGET                   If none specified, use all packages. See http://docs.haskellstack.org/en/v1.0.2/build_command.html#target-syntax for details.
```

Maybe we can omit `#target-syntax` to keep the link more stable.

A link to http://docs.haskellstack.org/en/v1.0.2 in the help global footer may also be helpful.

**Comment by mgsloan** [comment]
Good idea!  

Perhaps this is getting a little too fancy, but it'd be nice to have a way to get strings that stabley reference the docs, in general.  I'm imagining something like `$(docSection "build_command", "target-syntax"), which would check if the build_command.md file exists, and that the anchor "target-syntax" exists.

**Comment by harendra-kumar** [comment]
Yeah, it will be nice if we can check for broken refs. A broken reference can be fixed manually once we know its broken.

**Comment by mgsloan** [comment]
Probably only worth it if we make a concerted effort to link to the docs a lot from CLI output, which could be a rather good thing to do.

**Comment by sjakobi** [comment]
Also useful in this context is the `stack ide targets` command.

**Comment by sjakobi** [comment]
I have added a link to `https://docs.haskellstack.org/en/v$VERSION/build_command/#target-syntax` to the help section for now (https://github.com/commercialhaskell/stack/commit/1d03be1bbaf6469fd7bfd9c7d0726aaf49a52134).

Also, the target syntax section in the docs now has a note regarding `stack ide targets`.

**Comment by sjakobi** [comment]
> A link to http://docs.haskellstack.org/en/v1.0.2 in the help global footer may also be helpful.

Addressed in https://github.com/commercialhaskell/stack/commit/4dc0a075b039e807f701f1396df60035508e2090.

**Comment by sjakobi** [comment]
I have pulled the stable reference helpers idea out into https://github.com/commercialhaskell/stack/issues/2481.
