### ISSUE TITLE
cache extra-deps globally

### ISSUE THREAD

**Issue by ghorn** [commercialhaskell/stack#1732]
My project at work has a few `extra-deps` from hackage/github which take a very long time to build. Our continuous integration builder spends 95% of its time building the deps, and 5% building and testing our software. Is there any reason stack cannot cache the builds of these `extra-deps` globally in `$HOME/.stack`, instead of locally in the `.stack-work`?

**Comment by mgsloan** [comment]
Yup, you are correct that this is possible.  [This issue](https://github.com/commercialhaskell/stack/issues/1265) is tracking doing exactly that.
