### ISSUE TITLE
Export stack's `other-modules` so they aren't forgotten?

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#1733]
I just implemented a function that is really similar to [`findDirUp` in `Path.Find`](https://github.com/commercialhaskell/stack/blob/8b010060b0d79f8455562a2716c68b72796f25b6/src/Path/Find.hs#L28). I happened to find `Path.Find` only by chance after the fact.

I believe I would have known about `Path.Find` if it appeared in the generated haddocks for stack, which it doesn't because it's listed as an `other-module` in `stack.cabal`.

As stack doesn't intend to be a library anyways, would it hurt to export the `other-modules`?

If we don't end up exporting these modules I'd really like to have something like `stack haddock --other-modules`.

**Comment by mgsloan** [comment]
I think the reasoning is that if stack was to be used as a library, those module names could conflict.

Considering how these affect haddocks, though, I agree, everything should be exposed.  Feel free to open a PR!
