### ISSUE TITLE
Clarifying/amending docs regarding extra-deps

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1734]
http://docs.haskellstack.org/en/stable/yaml_configuration.html#extra-deps

Uses the wording:

>augment an LTS Haskell or Stackage Nightly snapshot with a package that is not present or is at an older version than you wish to use.

Does this not work for newer versions you might want as well?

Incidentally, I'm having trouble specifying `  - monad-logger-0.3.8` under my `extra-deps`. Spews package conflicts when I do.

**Comment by mgsloan** [comment]
Good point!  Fixed
