### ISSUE TITLE
More concise, directed error messages when there are dependency errors

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1739]
See the beginning of the discussion of https://github.com/commercialhaskell/stack/issues/1735 .  Leaving this as a stub for now.

**Comment by sjakobi** [comment]
For reference: There's some discussion in https://github.com/commercialhaskell/stack/issues/713 on this topic and https://github.com/commercialhaskell/stack/issues/1790 contains another example case.

**Comment by mgsloan** [comment]
Done!
