### ISSUE TITLE
Consider allowing newer versions of Cabal library

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#174]
Considering how slow/buggy older versions can be...

**Comment by etorreborre** [comment]
Coming from #494.

I had a quick look at the code and I had the impression that the `getCabalPkgVer` function could try to get it version number from the `EnvOverride` but I don't know the code base enough to really tell.

**Comment by snoyberg** [comment]
The way is works now is that stack will always use the version of Cabal in the global package database. So one option for a short-term hack is to do something like `cabal install --global Cabal`. I think a better long term solution is having some kind of extra package database available which contains the Cabal library, and then provide a stack command to install new versions of the Cabal library. We could also have some kind of a field in stack.yaml which specifies which version of Cabal is necessary, and automatically install it if missing.

**Comment by etorreborre** [comment]
That works for me in the short term, thanks. In the long run it would be nice to be able to specify the Cabal version in the stack.yaml file.

**Comment by snoyberg** [comment]
Based on that answer, the easiest solution to this is to provide a `stack upgrade-cabal` command or similar that installs a new version of Cabal to the global database.

**Comment by snoyberg** [comment]
I'm thinking of bundling this with `stack setup`, as a flag `--upgrade-cabal`, and having it simply automate downloading the most recent Cabal library and doing a global install of it.
