### ISSUE TITLE
Better error message for `stack ghci`

### ISSUE THREAD

**Issue by vijaykiran** [commercialhaskell/stack#175]
I just installed stack from master, and tried to run stack ghci - IMHO, the message could be better (I'm running on OS X, ghc 7.10.1)

```
➜  zenith git:(master) ✗ stack ghci
stack: GHCVersionMismatch (Just 7.10.1) 7.8.4
```

**Comment by snoyberg** [comment]
@vijaykiran This error message has been cleaned up, please reopen if there's a problem with the new behavior.
