### ISSUE TITLE
Error installing: The following signatures couldn't be verified because the public key is not available:

### ISSUE THREAD

**Issue by GildedHonour** [commercialhaskell/stack#1753]
Ubuntu 14.04

```
Reading package lists... Done
W: GPG error: http://download.fpcomplete.com trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 575159689BEFB442
```

**Comment by mgsloan** [comment]
This is covered by the ubuntu installation instructions: http://docs.haskellstack.org/en/stable/install_and_upgrade.html#ubuntu

> 1. Get the FP Complete key:
>
> sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442

**Comment by GildedHonour** [comment]
@mgsloan , of course I've gotten it.

**Comment by GildedHonour** [comment]
$ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.uSNFyp3GOT --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/danielrichter2007-grub-customizer.gpg --keyring /etc/apt/trusted.gpg.d/mc3man-trusty-media.gpg --keyring /etc/apt/trusted.gpg.d/webupd8team-atom.gpg --keyring /etc/apt/trusted.gpg.d/yannubuntu-boot-repair.gpg --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442
gpg: requesting key 9BEFB442 from hkp server keyserver.ubuntu.com
gpg: key 9BEFB442: public key "FPComplete <dev@fpcomplete.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

**Comment by mgsloan** [comment]
Does `sudo apt-get update` fix it?  Suggestion from http://askubuntu.com/a/15272

Seems like this isn't a stack bug, I suggest installing from tarball http://docs.haskellstack.org/en/stable/install_and_upgrade.html#linux

**Comment by GildedHonour** [comment]
sudo apt-get update doesn't fix it:

Reading state information... Done
The following NEW packages will be installed:
  stack
0 upgraded, 1 newly installed, 0 to remove and 37 not upgraded.
Need to get 8,359 kB of archives.
After this operation, 35.8 MB of additional disk space will be used.
Get:1 http://download.fpcomplete.com/ubuntu/ trusty/main stack amd64 1.0.2-0~trusty [8,359 kB]
Fetched 399 B in 15s (26 B/s)             
E: Failed to fetch http://download.fpcomplete.com/ubuntu/pool/s/st/stack_1.0.2-0~trusty_amd64.deb  Size mismatch

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

I'll try the tarball

**Comment by mgsloan** [comment]
Oh, that's an interesting error message.  Based on "Fetched 399 B in 15s", I'm guessing the server is sending an error response.

**Comment by GildedHonour** [comment]
I moved to another place and have been able to install.
