### ISSUE TITLE
How'd you get haskellstack.org to redirect?

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1754]
Doing this for a domain of mine.

I'm hoping there's a way to do this without a web server. Currently the CNAME record works fine, but don't know what to do with @.

dig brings this up:

```
haskellstack.org.	10734	IN	A	217.70.184.38
```

But it's not clear to me if you've just assigned it to RTD's gateway server and it'll break if they change IPs or something.

**Comment by bitemyapp** [comment]
Nevermind, looks like you're using this service to do it: http://wiki.gandi.net/en/domains/management/domain-as-website/forwarding/faq

**Comment by borsboom** [comment]
Yeah, there has to be a web server involved unfortunately.  Many DNS providers include this service with a domain (such as gandi.net, which is where haskellstack.org is registered).

**Comment by bitemyapp** [comment]
@borsboom luckily Google Domains has this too. Thank you :)
