### ISSUE TITLE
Would you be interested in supporting arm64 (aarch64)?

### ISSUE THREAD

**Issue by gitfoxi** [commercialhaskell/stack#1755]
I have built ghc, cabal and stack for aarch64.

Ghc is passing most (but not all) tests. Stack can build quite a few packages but has a few problems I'm working on.

Would you be interested in hosting these packages on stackage.org? If so, in what format can I deliver them and how can we stay up-to-date?

If you want to build things rather than use mine (for security and maybe convenience) there's no real difficulty. Let me know how I can help.

**Comment by borsboom** [comment]
Once things are working reliably, we'd be happy to host these and support.

For GHC, the format we need is a bindist structured like those at http://downloads.haskell.org/~ghc/7.10.3/ that can be installed using the standard `./configure && make install` process.  We rely on third parties (mostly the GHC release team) to provide GHC bindists, so for this case you could continue providing them directly, or ideally work with the GHC release team to make official GHC bindists for arm64.

For `stack` itself, best would be to use [etc/scripts/release.hs](https://github.com/commercialhaskell/stack/tree/master/etc/scripts#releasehs) to build the bindist.  In theory, it could "just work", but since we've never tried it with arm64 I wouldn't be surprised if you run into trouble.  Since Stack releases are fairly frequent, having the process well documented so we can add it to the semi-automated release process would be best.

**Comment by gitfoxi** [comment]
I think it will be working reliably today or tomorrow. There’s been some recent patches to fix the failing tests in GHC so should just be a matter of building and testing.

Do you know how I can contact the GHC release team?

**Comment by borsboom** [comment]
I'm not certain, but the [ghc-devs mailing list](
https://mail.haskell.org/mailman/listinfo/ghc-devs) might be a good place
to start.

>

**Comment by gitfoxi** [comment]
As a first crack at this, I have built ghc-7.10.3 and stack-1.0.2 for aarch 64 and placed the results here:

https://s3-us-west-1.amazonaws.com/stack-aarch64/ghc-7.10.3-aarch64-unknown-linux.tar.bz2
https://s3-us-west-1.amazonaws.com/stack-aarch64/stack

It would be good to make an Ubuntu PPA. I looked into it and they will enable arm64 builds in PPAs if you ask nicely. So I asked nicely and am waiting to hear back.

This version of GHC does not pass all tests. There's a version that does pass all tests but it is HEAD and there will be some different issues for using it. I'm building that now and will post when complete.

Even though GHC doesn't pass all tests -- most problems have to do with using the GHC-API -- stack can build most of lts-5.1. The packages that don't build are:

```
ngel-0.6.2
TaxonomyTools-1.0.0
atomic-primops-0.8.0.2
DAV-1.2
arbtt-0.9.0.7
blake2-0.1.0
argon-0.4.0.0
cabal-src-0.3.0.1
charsetdetect-ae-1.1.0.1
RNAlien-1.0.0
calculator-0.4.1.1
apply-refact-0.1.0.0
amqp-0.13.1
clientsession-0.9.1.1
HTF-0.13.1.0
courier-0.1.1.1
dbmigrations-1.0
fast-builder-0.0.0.2
diagrams-haddock-0.3.0.10
cheapskate-0.1.0.4
dice-0.1
diversity-0.8.0.0
gl-0.7.8.1
ghcid-0.5
gsasl-0.3.6
clash-ghc-0.6.9
hackage-mirror-0.1.1.1
hfsevents-0.1.6
haddocset-0.4.1
hgettext-0.1.30
haskintex-0.6.0.0
holy-project-0.2.0.1
htaglib-1.0.1
criterion-1.1.0.0
hmatrix-gsl-stats-0.4.1.3
inline-r-0.8.0.1
ignore-0.1.1.0
hsx2hs-0.13.4
latex-formulae-pandoc-0.2.0.3
libnotify-0.1.1.0
lentil-0.1.9.0
derive-2.5.23
libsystemd-journal-1.4.0
json-autotype-1.0.10
microformats2-parser-1.0.1.3
language-glsl-0.2.0
msi-kb-backlit-0.1.0.1
misfortune-0.1.1.2
mysql-0.1.1.8
nettle-0.2.0
network-anonymous-tor-0.11.0
pager-0.1.1.0
omnifmt-0.2.1.1
morte-1.4.2
modify-fasta-0.8.0.4
postgresql-schema-0.1.10
pureMD5-2.1.2.1
fay-0.23.1.12
hlint-1.9.26
pretty-show-1.6.9
pusher-http-haskell-0.3.0.1
resolve-trivial-conflicts-0.3.2.2
postgresql-orm-0.4.1
sandman-0.2.0.0
scrypt-0.5.0
sdl2-2.1.1
seqalign-0.2.0.4
rasterific-svg-0.2.3.2
mangopay-1.12
skeletons-0.4.0
simple-0.11.1
servant-docs-0.4.4.6
tellbot-0.6.0.11
tls-debug-0.4.1
wai-app-static-3.1.4.1
smallcaps-0.6.0.1
jmacro-0.6.13
wordpass-1.0.0.4
xml-to-json-2.0.1
xml-to-json-fast-2.0.0
tttool-1.5.1
yesod-bin-1.4.17.1
yes-precure5-command-5.5.2
zeromq4-haskell-0.6.4
xmonad-0.12
vty-5.4.0
shake-0.15.5
hprotoc-2.1.12
xlsx-0.2.0
darcs-2.10.3
purescript-0.7.6.1
sbv-5.11
pandoc-1.16.0.2
Agda-2.4.2.5
```

**Comment by gitfoxi** [comment]
The stack-release-tool worked great @borsboom. The only problem is the readme says that it can make ubuntu packages but it wouldn't even pretend to try to do that. Message was something like "no such target ubuntu-package".

**Comment by borsboom** [comment]
Sorry, the README was out of date (I've now updated it).  The target should be something like `build-ubuntu-14.04`.  Have you tried your GHC bindist with `stack setup --ghc-variant=aarch64 --ghc-bindist=<url>`?

**Comment by borsboom** [comment]
Do you have any suggestions for how I could try this out?  I use Mac OS X on my workstation, and have no idea how to get Ubuntu for arm64 running in an emulator.  Would the free 1-core VPS on armcloud (which I think you mentioned in another issue) make sense?

**Comment by gitfoxi** [comment]
I haven’t tried emulation recently. I’m sure it’s very slow. I do recommend the armcloud. It’s working nicely for me. I think I had to email them to get access since it’s in beta and it took about a day. It’s easy to setup. The only problem is very limited disk space and no clear way to attach another volume.

Also, I can just make you an account on mine if you want to e-mail your public key to 415fox@gmail.com

**Comment by gitfoxi** [comment]
@borsboom That works:

```
$ stack setup --ghc-variant=aarch64 --ghc-bindist=https://s3-us-west-1.amazonaws.com/stack-aarch64/ghc-7.10.3-aarch64-unknown-linux.tar.bz2
Run from outside a project, using implicit global project config
Using resolver: lts-5.1 from implicit global project's config file: /home/admin/.stack/global-project/stack.yaml
Caching build plan
Preparing to install GHC (custom-aarch64) to an isolated location.
This will not interfere with any system-level installation.
No sha1 found in metadata, download hash won't be checked.
Downloaded ghc-custom-aarch64-7.10.3.
Installed GHC.
stack will use a locally installed GHC
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
```

**Comment by gitfoxi** [comment]
I built ghc HEAD and put it here: https://s3-us-west-1.amazonaws.com/stack-aarch64/ghc-8.1.20160209-aarch64-unknown-linux.tar.xz

```
stack setup --ghc-variant=aarch64-HEAD --ghc-bindist=https://s3-us-west-1.amazonaws.com/stack-aarch64/ghc-8.1.20160209-aarch64-unknown-linux.tar.xz
```

Too soon to know if this works better than 7.10. I will try building stackage again. Experience says this takes days.

The key is to change the `--ghc-variant` to something you haven't used before.

**Comment by gitfoxi** [comment]
The above doesn't work. I think you want something more like

```
stack setup 8.1.20160209 --ghc-variant=aarch64-HEAD --ghc-bindist=https://s3-us-west-1.amazonaws.com/stack-aarch64/ghc-8.1.20160209-aarch64-unknown-linux.tar.xz
```

But that fails too with

```
make[1]: *** No rule to make target `utils/haddock/dist/build/tmp/haddock', needed by `install_libexecs'.  Stop.
make[1]: *** Waiting for unfinished jobs....
make: *** [install] Error 2

Installing GHC ...[2]-  Terminated
```

**Comment by niwolive** [comment]
@gitfoxi I couldn't find useful instructions for building ghc on aarch64. Could you give some insights on how to proceed?

I'm confused by the official [instructions of the GHC wiki](https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation/Linux) as it seems you need to have ghc installed to build ghc?

My purpose is to set-up an Elm development environment. My distro is arch-arm.

**Comment by gitfoxi** [comment]
@niwolive I gave that hobby almost a year ago, but look a few messages back for my pre-built ghcs which you can use to booststrap your build. It actually isn't that hard to get going, but you end up with a compiler that uses the compile-to-C method rather than the native method. This works just fine and I'm not aware of any disadvantages. Maybe its slower but I don't notice because my 48-core ThunderX is so very fast.

On the other hand, since Elm compiles to Javascript you might just want to skip the hassle and do your development on a better-supported architecture then deploy to your arm server.

**Comment by thekyriarchy** [comment]
I'd like to get GHC working on my 64-bit ARMv8 scaleway VPS. Does this depend on this? https://ghc.haskell.org/trac/ghc/ticket/11578

**Comment by peterbecich** [comment]
@thekyriarchy Not sure about that ticket, but I was able to install GHC 8.0.2 on my Scaleway VPS running Ubuntu Zesty straight from the official repository:

```
root@scw-724255:~# apt-cache show ghc
Package: ghc
Priority: extra
Section: universe/haskell
...
Architecture: arm64
Version: 8.0.2-1~build1
```
