### ISSUE TITLE
`stack install` quits without explanation on ARM

### ISSUE THREAD

**Issue by gitfoxi** [commercialhaskell/stack#1756]
stack install

Installs some packages from build-depends then quietly and without explanation stops doing that. Is there a log or something I can check?

Long story is that I copied the contents of lts-5.1 into my build-depends. I don't know much about stack, but after deleting lines with the word "install", stack started building and installing things in alphabetical order. Great.

Later, I returned hoping to see progress but, after installing most packages starting with `a`, stack decided to call it a day and head the pub. Seeing no messages or logs, I tried it again

    stack install

This time she finished building everything starting with `a` and a few things starting with `b` (up to `base-unicode-symbols-0.2.2.4`) before nodding off in a drunken stupor.

Stack is running on Ubuntu 14.04, ghc-10.7.3, aarch64 on a 12-core, 25GB armcloud instance with only 30GB disk. I checked that she hadn't run out disk, and she hadn't. But the other thing is that it's day-1 for me on this hardware platform -- just built ghc yesterday; cabal and stack this morning -- so probably not everything has been tested that well.

**Comment by borsboom** [comment]
ARM is an untested architecture for Stack, so it's not surprising that you're having trouble.  As a first step, I'd recommend running `stack --verbose | tee stack.log` to get the verbose output to help determine what Stack is doing when it dies, and then debug from there.

Possibly related: #1332

**Comment by gitfoxi** [comment]
Thanks. It’s not going to be untested for long.

**Comment by borsboom** [comment]
I'm going to close this support issue, but there is plenty of discussion going on around ARMv7 support in #2103, where a number of people report successfully using Stack on ARMv7.
