### ISSUE TITLE
How do you run tests with profiling?

### ISSUE THREAD

**Issue by chris-martin** [commercialhaskell/stack#1759]
The [guide](https://github.com/commercialhaskell/stack/blob/master/doc/GUIDE.md#debugging) discusses generating profiling information when running an executable, but what flags do I need to get that information when running `stack test`?

**Comment by sjakobi** [comment]
Looks like the guide needs some updating.

Try `stack test --profile`.

**Comment by mgsloan** [comment]
@sjakobi has updated the docs for this.
