### ISSUE TITLE
stack crashes when run without absolute path

### ISSUE THREAD

**Issue by ijt** [commercialhaskell/stack#1760]
I just installed stack like this on Mac OS X:

    $ cabal install --constraint 'mono-traversable >= 0.9' stack

Here's what happens if I try running it:

    $ stack
crackhdr core: No such file or directory
crackhdr a.out: No such file or directory
no stack frame

It works okay if I run it with an absolute path though:

    $ ~/.cabal/bin/stack
stack - The Haskell Tool Stack

Usage: stack [--help] [--version] [--numeric-version] [--docker*] [--nix*]
...

**Comment by luigy** [comment]
What do you get from `which -a stack` ?
I suspect  another dir in your PATH probably has precedence over ~/.cabal/bin with a conflicting `stack`

**Comment by ijt** [comment]
/Users/issactrotts/.cabal/bin/stack

/usr/local/plan9/bin/stack

Interesting. If I move plan9 out of the way the problem goes away. Thanks!

**Comment by harendra-kumar** [comment]
It looks to me the /usr/local/plan9/bin/stack is not the haskell stack but a plan9 binary for something else.
