### ISSUE TITLE
"stack init" doesn't explain that it's searching for cabal files

### ISSUE THREAD

**Issue by tomkludy** [commercialhaskell/stack#1762]
**Steps to reproduce:**
1. Run command ```stack init``` (this is on OSX El Capitan)

**Expected:** the command to complete

**Actual:** the command hangs and never completes

Here's the ```stack --version``` output:

    ~|⇒ stack --version
    Version 1.0.2, Git revision fa09a980d8bb3df88b2a9193cd9bf84cc6c419b3 (3084 commits) x86_64

Here's the command I ran with ```--verbose```:

    ~|⇒ stack init --verbose
    Version 1.0.2, Git revision fa09a980d8bb3df88b2a9193cd9bf84cc6c419b3 (3084 commits) x86_64
    2016-02-08 09:34:55.137879: [debug] Checking for project config at: /Users/tomkludy/stack.yaml @(stack_4KzSHGzdHbhGf9lPuwG7Iq:Stack.Config src/Stack/Config.hs:660:9)
    2016-02-08 09:34:55.138585: [debug] Checking for project config at: /Users/stack.yaml @(stack_4KzSHGzdHbhGf9lPuwG7Iq:Stack.Config src/Stack/Config.hs:660:9)
    2016-02-08 09:34:55.138630: [debug] Checking for project config at: /stack.yaml @(stack_4KzSHGzdHbhGf9lPuwG7Iq:Stack.Config src/Stack/Config.hs:660:9)
    2016-02-08 09:34:55.138668: [debug] No project config file found, using defaults. @(stack_4KzSHGzdHbhGf9lPuwG7Iq:Stack.Config src/Stack/Config.hs:687:13)

Please let me know if there is any further detail needed.  Thanks!

**Comment by tomkludy** [comment]
After trying a couple of things I believe this is because I ran 'stack init' outside of a project folder.  While the usability could be improved by having the tool detect & exit with an appropriate error, I am happy to close the issue.

BTW my expectation as a naive user was that running "stack init" would initialize any global things such as GHC, happy, alex, etc.  But on reflection it makes sense that really nothing is global, everything is in the context of the project being built.

**Comment by harendra-kumar** [comment]
It should not hang irrespective of whether you run it in or outside the project context. I would like to root cause the problem if you can reproduce it. I cannot reproduce it on my machine running stack 1.0.2 on OSX El Capitan.

**Comment by sjakobi** [comment]
I tried to reproduce this by running `stack init` in my home folder and while `stack` didn't exactly hang, it took a very long time.

The output looks roughly like this:
```
~ $ stack init
Using cabal packages:

... list of every cabal file below ~/ ....

Cabal file warning in <x>
Cabal file warning in <y>
...

Please fix the following packages and try again:
... a lot of cabal files ...
```

Could we simply limit the number of directory levels that `stack init` searches, say to 2, i.e. the current directory and the directory level below?

**Comment by mgsloan** [comment]
How about when `--ignore-subdirs` is specified, output `Looking for cabal files, without recursing into subdirectories...`.  When it isn't output `Looking for cabal files, recursing into subdirectories...`.  This way if there are tons of cabal files, the user will at least have some idea of what's going on.

**Comment by sjakobi** [comment]
> How about when --ignore-subdirs is specified, output Looking for cabal files, without recursing into subdirectories.... When it isn't output Looking for cabal files, recursing into subdirectories.... This way if there are tons of cabal files, the user will at least have some idea of what's going on.

Sounds good!

**Comment by harendra-kumar** [comment]
How about changing the default as well to not include subdirs?

**Comment by aBathologist** [comment]
I just *thought* `stack init` was hanging, but it just took awhile and gave no indication that anything was working. My concerns would have been entirely avoided had it first printed

```
$ stack init
initializing...
```

Or something like that. Just my 1/2 cent.

```
$ stack --version
Version 1.0.4.3 x86_64
```

**Comment by mgsloan** [comment]
@aBathologist Upgrade to 1.1, I think this got fixed and never closed

```
mgsloan@computer:~$ stack init
Looking for .cabal or package.yaml files to use to init the project.
```
