### ISSUE TITLE
Unfriendly error message for invalid package names

### ISSUE THREAD

**Issue by rossng** [commercialhaskell/stack#1763]
The stack CLI produces a fairly unhelpful error message when you try to create a new project with an invalid package name. For example:

```
$ stack new lab-2 new-template
Expected valid package name, but got: lab-2
```

As a Haskell novice, it wasn't immediately obvious to me what was happening here. It took me a couple of minutes to figure out that I needed to remove the hyphen. The fact that template names _can_ contain hyphens is doubly confusing!

Suggested solution: change the error message to include a description of what package names are acceptable.

**Comment by sjakobi** [comment]
Yes, the error message could be more helpful.

Maybe we could simply cite https://www.haskell.org/cabal/users-guide/developing-packages.html#developing-packages:

> A package is identified by a globally-unique package name, which consists of one or more alphanumeric words separated by hyphens. To avoid ambiguity, each of these words should contain at least one letter. 

Or is there a better reference?

**Comment by kadoban** [comment]
A nicer fix might be to give a parsec-style error output, like 'unexpected end of input, expecting letter' or whatever the real wording is, but I don't offhand if the parser being used can do that.

This would probably have to be in addition to what @sjakobi suggests, since the format is a bit ... specific with the whole "must have a letter in each 'word'" part, so a paragraph summarizing it would be nice.

**Comment by mgsloan** [comment]
Giving a specific error message would be nice, but I agree that the error should at least include a description of the restrictions on package names.

**Comment by kadoban** [comment]
I wonder if this is good enough now. The current error message gives a nice concise description of the required format at least.

I'm having trouble thinking up what else we could actually do. For example for `stack new lab-2`, the best we'd get out of a good generic parser would be something like "unexpected end, expecting some letter", which is not that great anyway, right?

Maybe we could make a special-purpose check for cases where a "word" isn't valid and point that word out? Is that worth doing?

**Comment by sjakobi** [comment]
```
➤ stack new lab-2
Expected valid package name, but got: lab-2
Package names consist of one or more alphanumeric words separated by hyphens.
To avoid ambiguity with version numbers, each of these words must contain at least one letter.


Usage: stack new PACKAGE_NAME [--bare] [TEMPLATE_NAME] [-p|--param KEY:VALUE]
...
```

Seems pretty good to me.

> Maybe we could make a special-purpose check for cases where a "word" isn't valid and point that word out? Is that worth doing?

Maybe. I'd propose waiting for further user feedback before investing more time here.

Closing for now.
