### ISSUE TITLE
Stack upgrade failing with Aeson 0.10.0/0.11.0-related message

### ISSUE THREAD

**Issue by ldcasillas-progreso** [commercialhaskell/stack#1770]
I have this version:

    % stack --version
    Version 1.0.0, Git revision 3bc26237b5b3c387b8fd564459ea4dd88fd58b30 (2939 commits) x86_64

And I just attemtped to upgrade, and it failed:

    % stack upgrade
    Fetched package index.
    Populated index cache.
    stack-1.0.2: download
    Warning: /private/var/folders/xq/khbxznb55f58rs735ngcz3dspy_1gq/T/stack-upgrade13312/stack-1.0.2/stack.yaml: Unrecognized field in ImageOptsMonoid: containers
    Downloaded lts-4.0 build plan.
    Caching build plan
    Preparing to install GHC to an isolated location.
    This will not interfere with any system-level installation.
    Downloaded ghc-7.10.3.
    Installed GHC.
    While constructing the BuildPlan the following exceptions were encountered:

    --  Failure when adding dependencies:    
          aeson: needed ((>=0.8.0.2 && <0.10) || (>=0.11 && <0.12)), 0.10.0.0 found (latest applicable is 0.11.0.0)
        needed for package: stack-1.0.2

This seems to be related to the following commits: 

* https://github.com/commercialhaskell/stack/commit/3e0538aea237fed06446abcaa847f2c321d1245a
* https://github.com/commercialhaskell/stack/commit/744b7c33572bc0aeba43d9a95984e301f855efb9

**Comment by borsboom** [comment]
`stack upgrade` is of course using the stack.yaml from hackage which still uses lts-4.0, which has aeson-0.10.  I shouldn't have modified the constraints on hackage to prevent aeson-0.10.  I've now relaxed the constraint on Hackage.  Can you try it again?

**Comment by ldcasillas-progreso** [comment]
Ooops, I did a `stack upgrade --git` between now and then, so now the upgrade command is a no-op at my end.

**Comment by borsboom** [comment]
Ok, I'll close this since it should be fixed
