### ISSUE TITLE
Can't use `--profile` and `--benchmark-arguments` simultaneously.

### ISSUE THREAD

**Issue by ldcasillas-progreso** [commercialhaskell/stack#1772]
When I run the following command my benchmark suite runs with profiling enabled (except for the issue I reported in https://github.com/commercialhaskell/stack/issues/1771):

    % stack bench --profile 

When I run this command my benchmark runs without profiling (as it should), and the argument is passed to Critierion to select a subset of the tests:

    % stack bench --benchmark-arguments='theo1'

But when I try to combine them both I get an error:

    % stack bench --profile --benchmark-arguments='theo1'
    tau-sigma-0.5.1: benchmarks
    Running 1 benchmarks...
    Benchmark bench: RUNNING...
    Usage: bench ([-I|--ci CI] [-G|--no-gc] [-L|--time-limit SECS]
                 [--resamples COUNT] [--regress RESP:PRED..] [--raw FILE]
                 [-o|--output FILE] [--csv FILE] [--junit FILE]
                 [-v|--verbosity LEVEL] [-t|--template FILE] [-m|--match MATCH]
                 [NAME...] | [-n|--only-run ITERS] [-m|--match MATCH] [NAME...] |
    Benchmark bench: ERROR
                 [-l|--list] | [--version])

    --  While building package tau-sigma-0.5.1 using:
          /Users/luis.casillas/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.22.4.0-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0 bench bench "--benchmark-options=theo1+RTS -p"
        Process exited with code: ExitFailure 1

More info:

    % stack --version
    Version 1.0.3, Git revision 260ea31e787593fe27d002985f45739d8a04a498 x86_64

Resolver is `lts-3.20`.

**Comment by mgsloan** [comment]
Good catch! `+RTS` options were not being terminated with `-RTS`.

**Comment by ldcasillas-progreso** [comment]
I can confirm that the following command no longer gets an error:

     stack bench --profile --benchmark-arguments='theo1'

Stack version:

    Version 1.0.3, Git revision 3f7b50fe598ec83eda5d393fe5b08a99ce5ac1e9 x86_64
