### ISSUE TITLE
Directory ownership test fails with docker

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1777]
`stack build` in a repo that builds in a docker container results in

> You are not the owner of '/home/mgsloan/.stack/'. Aborting to protect file permissions.
> Retry with '--allow-different-user' to disable this precaution.

Despite me owning that folder.  `stack exec --allow-different-user -- whoami` reports `stack`, and `stack exec --allow-different-user -- ls -la /home/mgsloan` shows a `.stack` folder owned by `stack`, so I'm not sure what's going wrong here.  I haven't looked at the code yet, could be something simple.

Docker is discussed a bit in the PR - https://github.com/commercialhaskell/stack/pull/1599 - but I didn't test it.

**Comment by mgsloan** [comment]
Pinging @sjakobi

**Comment by sjakobi** [comment]
I should have done some testing with Docker in the first place…

I just reproduced the bug on my system but don't currently have the time to look into this more closely. I'd propose that I revert my commits (https://github.com/commercialhaskell/stack/commit/2c2e15ae63fa3e1bd32a1b752994c9d3b0ebf4f3 and https://github.com/commercialhaskell/stack/commit/260ea31e787593fe27d002985f45739d8a04a498) and look into this next week.

**Comment by mgsloan** [comment]
@sjakobi No worries, that's why it's a development branch!  I've reverted the merge.  This means that your new PR should start with the commit that's created by reverting the revert, via `git revert 0a89c9c29d744a4955e62b59774036e98d6b1e8e` (as described in "reverting the revert" [here](https://git-scm.com/blog/2010/03/02/undoing-merges.html)).

**Comment by sjakobi** [comment]
Thanks! I've also reverted the relevant changelog edit
(260ea31e787593fe27d002985f45739d8a04a498).

2016-02-12 0:23 GMT+01:00 Michael Sloan <notifications@github.com>:

**Comment by borsboom** [comment]
My guess is that the ownership test is being done by the `stack` process in the container before it has `setuid` itself to the the host user (since processes in Docker containers run as root by default).  The simplest solution is probably to disable the check when re-spawned in Docker (use `Stack.Docker.getInContainer` to check).

**Comment by mgsloan** [comment]
That makes sense.  The checks for the outer stack invocation work, but not the inner.  I did a little bit of print debugging yesterday, and stack thought it was user 0, whereas `~/.stack` is owned by user 1000.
