### ISSUE TITLE
Just pick the latest and give it a shot.

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#178]
Don't make me type all this in.

```
stack: The following packages do not exist in the build plan:
dynamic-state (used by yi)
dyre (used by yi)
oo-prototypes (used by yi)
pointedlist (used by yi)
vty (used by yi)
word-trie (used by yi)
xdg-basedir (used by yi)
yi-language (used by yi)
yi-rope (used by yi)
```

Toss it in the deps with the latest version that is on Hackage, and if you can't figure it out, ask me to fix it.

**Comment by snoyberg** [comment]
I think we need to hold off on this until #116 is implemented, deferring

**Comment by snoyberg** [comment]
Merging this functionality in with #159, closing.
