### ISSUE TITLE
slow compilation times

### ISSUE THREAD

**Issue by timchu** [commercialhaskell/stack#1783]
I'm working with a project that has 77 modules and 12,000 lines of code, and it takes on the order of two minutes to compile using stack install. I have set -O0.
However, using stack ghci, it takes about 15 seconds to build my whole project.  What explains the difference between these two?

**Comment by mgsloan** [comment]
I suppose that means codegen is taking a minute and 45 seconds - https://www.reddit.com/r/haskell/comments/309430/where_does_ghc_spend_most_of_its_time_during/cpq9wmg

**Comment by timchu** [comment]
Linking takes very little time -- about 5 seconds tops. -O0 should prevent optimization from taking too long.
I'm told by people who are experienced build similar size projects for Cabal using Ghc that this is an unusually long compilation time,and that this is likely not a GHC problem.

**Comment by mgsloan** [comment]
Well, it certainly isn't unusual, I'd be interested to know the full explanation as well.  For me, compiling stack with `stack build` takes **2m45s**, whereas loading the project into ghci via `stack ghci` takes **14s**.  It'd be nice to have some `-ddump-*` flag for dumping timing info for different parts of compilation.

Could it possibly be related to TH?  Maybe when loading things in ghci it's easy to just directly execute the TH in the interpreter, whereas when compiling the code it needs to initialize a new interpreter.  I thought GHC reused the interpreter session for each module, but maybe it doesn't!
