### ISSUE TITLE
Is there a way to build all of stackage against ghc-HEAD?

### ISSUE THREAD

**Issue by gitfoxi** [commercialhaskell/stack#1784]

**Comment by mgsloan** [comment]
Since this was also posted here http://stackoverflow.com/questions/35323714/how-can-i-test-a-new-ghc-build-against-stackage , with infinitely more description, I'm closing this in favor of that.

**Comment by gitfoxi** [comment]
Thank you.

**Comment by mgsloan** [comment]
Reposting a couple helpful links:

https://github.com/fpco/ghc-rc-stackage
https://github.com/haskell/cabal/issues/3163
