### ISSUE TITLE
Additional Distribution Request

### ISSUE THREAD

**Issue by robcore** [commercialhaskell/stack#1785]
Hi there! Would you please consider making stack (it's awesome, by the way) available for Kali Linux?  It's pretty much entirely debian-based so I imagine maintaining it wouldn't be too much of a drain...

I know it's ridiculous, but I use Kali strictly for android/kernel programming...

Thanks so much!
Rob

**Comment by borsboom** [comment]
Have you tried the packages from [our Debian repository](http://docs.haskellstack.org/en/stable/install_and_upgrade.html#debian)?  According to [this](http://docs.kali.org/policy/kali-linux-relationship-with-debian):

> The Kali Linux distribution is based on Debian Wheezy. Therefore, most of the Kali packages are imported, as-is, from the Debian repositories. In some cases, newer packages may be imported from Unstable (“Sid”) or Experimental (“Jessie”), either to improve user experience, or to incorporate needed bug fixes.

So it seems likely standard Debian packages will work.  If not, have you tried using downloading a [generic Linux binary](http://docs.haskellstack.org/en/stable/install_and_upgrade.html#linux)?

**Comment by robcore** [comment]
Actually I was about to retract my request... I was using the standard version but then upon searching harder found it already maintained under "Haskell-stack."

My mistake! Thanks for being awesome and sorry to waste your time!
