### ISSUE TITLE
stack setup --nix fails: "attribute ‘lts-3_22’ missing"

### ISSUE THREAD

**Issue by chris-martin** [commercialhaskell/stack#1787]
```
> stack setup --nix
error: attribute ‘lts-3_22’ missing, at (string):1:240
(use ‘--show-trace’ to show detailed location information)
```

And the error message seems wrong, as well. because:

```
> stack setup --show-trace
Invalid option `--show-trace'

Usage: stack setup [GHC_VERSION] [--[no-]reinstall] [--[no-]upgrade-cabal]
                   [--stack-setup-yaml ARG] [--ghc-bindist URL] [--help]
  Get the appropriate GHC for your project
```

```
> stack --version
Version 1.0.2 x86_64
```

**Comment by chris-martin** [comment]
Nevermind, it just took me way to look to find the [Nix integration](https://github.com/commercialhaskell/stack/blob/master/doc/nix_integration.md) documentation.

**Comment by riaqn** [comment]
For those encountering the same problem: it's because the absence of `haskell.packages.lts-3_22`(or whatever `resolver` in your `stack.yaml`) in your `nixpkgs`.

You can solve this problem by either using an older resolver that exists in your `nixpkgs`(use `nix-repl` as in the link given by @chris-martin ), or using a newer `nixpkgs`(say, the one from github) that has this resolver.

**Comment by atc-** [comment]
I'm still getting:

```
error: undefined variable ‘haskellcompilerghc7102’ at (string):1:233
(use ‘--show-trace’ to show detailed location information)

```
despite setting the following in my `stack.yml`:

`resolver: ghc-7.10.2`

I installed both 7.10.2 and 7.10.3 of GHC via `nixos-rebuild`:

```
    stack
    haskell.compiler.ghc7102
    haskell.compiler.ghc7103
```
and it's available on my path:

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2
```
Any ideas please?

**Comment by mgsloan** [comment]
@atc- Try upgrading stack version?  Please open a new issue rather than commenting on a closed issue.

**Comment by YPares** [comment]
Do you have any news? It's very weird it looks for `haskellcompilerghc7102`,
it should be `haskell.compiler.ghc7102`
If the error persists with newer stack (possibly built from master), can
you give your project configuration?

2016-07-22 12:36 GMT+02:00 Alex Collins <notifications@github.com>:

**Comment by 41px** [comment]
same problem
