### ISSUE TITLE
Add stack executable to docker image?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#179]
If I use this config:

```haskell
resolver: lts-2.9
docker: {}
packages:
  - .
```

However, running `stack build` yields:

```
mgsloan@computer:~/fpco/schoolofhaskell$ stack -v build
2015-06-04 06:42:01.848406: [debug] Checking for project config at: /home/mgsloan/fpco/schoolofhaskell/stack.yaml @(stack-0.0.0:Stack.Config src/Stack/Config.hs:336:9)
2015-06-04 06:42:01.848737: [debug] Loading project config file stack.yaml @(stack-0.0.0:Stack.Config src/Stack/Config.hs:357:13)
/bin/bash: stack: command not found
mgsloan@computer:~/fpco/schoolofhaskell$ which stack
/home/mgsloan/.cabal/bin/stack
```

I asked @snoyberg about this, and it turns out that the issue is that `stack` isn't in the docker image.  We can either require that stack be in the docker image, or automate a fix, by copying stack into `.docker-sandbox/.home/bin`.

Suggested implementation: creating a hard link with `ln -P`.

Alternatively, I suppose it could automatically create a docker layer for it?

**Comment by snoyberg** [comment]
@mgsloan have you reviewed this?

**Comment by mgsloan** [comment]
Confirmed fixed!

**Comment by mgsloan** [comment]
@manny-fp Actually, hmm, I'm not getting the error I was getting before.  However, I would expect `stack exec -- which stack` to yield a result, and currently it doesn't.

**Comment by manny-fp** [comment]
Right, the directory where stack gets bind-mounted isn't on the PATH.  I'll update the image build tool to add that to the PATH for future images.

**Comment by manny-fp** [comment]
@mgsloan lts-2.14 images just uploaded, and include the host-mounted `stack` executable in the PATH.  Note you need to be on the latest version of `stack`.

**Comment by mgsloan** [comment]
Cool!  This is resolved, then

**Comment by kxra** [comment]
not sure who best to contact but i saw schoolofhaskell mentioned here and I was wondering if this was progress towards v 2.0?

**Comment by mgsloan** [comment]
Yes, this was involved.  SoH 2.0 is on its way!  However, now that stack can manage its own ghcjs, docker is no longer necessary.

**Comment by kxra** [comment]
@mgsloan cool, thanks for the response! is there a good way to keep up to date with progress? perhaps a (very vague) ETA?

**Comment by mgsloan** [comment]
Currently progress is just as time allows.  The website code should be released in the next couple of weeks, but it's not yet integrated with the new client / service.

**Comment by kxra** [comment]
Was the website code released on GitHub or elsewhere? A couple of weeks went by a month ago but I haven't heard of or been able to find anything

**Comment by snoyberg** [comment]
Do you mean this? https://github.com/fpco/stackage-server

**Comment by kxra** [comment]
Unless that's what @mgsloan meant by "the website codew" I don't think so

**Comment by mgsloan** [comment]
@kxra SoH is now opensourced!  It's status is described [here](https://www.fpcomplete.com/blog/2016/01/soh-status)
