### ISSUE TITLE
First-class support for re-running applications like `ordeal`

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1802]
https://github.com/reiddraper/ordeal

I use Yesod which means I have `yesod devel` so I don't need this for my 9-5, but for Scotty, Snap, really anybody, this could be a really nice thing to have.

**Comment by mitchellwrosen** [comment]
What does first-class support mean from stack's perspective? It looks like ordeal is already made stack-aware from its README.

    ordeal stack ghci

**Comment by bitemyapp** [comment]
@mitchellwrosen I mean built into Stack.

**Comment by mitchellwrosen** [comment]
@bitemyapp Ah, so like a combination of `stack ghci` and `stack build --file-watch`? `stack ghci --file-watch`?

**Comment by bitemyapp** [comment]
@mitchellwrosen with customizable init. yes.

**Comment by mgsloan** [comment]
Yeah, it's a good idea.  It's kindofa hack to drive ghci directly, compared to using the GHC API.  I'm hoping https://github.com/haskell/haskell-ide-engine/ will have something to fill this niche.  We could bake in something, but I'd rather wait for a proper solution rather than hacks.

You can use `stack ghci --with-ghc my-devel-exec-thing`.  A plugin could also be written that made `stack devel` an alias for this.

**Comment by mgsloan** [comment]
On second thought, if there's enough demand and we keep it simple, this could be an ok thing to add to stack.  I just don't want it to become a time sink as people start asking for things like reverse proxy support etc.

**Comment by bitemyapp** [comment]
>On second thought, if there's enough demand and we keep it simple, this could be an ok thing to add to stack. I just don't want it to become a time sink as people start asking for things like reverse proxy support etc.

That's fine by me, but I'm open to seeing if they'd be willing to do it as a plugin. I think it's a strong candidate for being a plugin personally.

**Comment by mgsloan** [comment]
Definitely!

**Comment by mgsloan** [comment]
Looks like ghcid handles this case as well, and @luigy is adding some awesomesauce:

https://github.com/ndmitchell/ghcid/pull/51
 https://cldup.com/zU-xtcjhZW.mp4
