### ISSUE TITLE
yesod keter fails in stack project

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1807]
```
$ make hestia keter
make -C hestia/ keter
make[1]: Entering directory '/home/callen/work/solo/hestia'
STACK_YAML="../stack.yaml" stack exec -- yesod keter
Getting project config file from STACK_YAML environment
cleaning...
cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
Cabal. Use the flag --package-db to specify a package database (it can be used
multiple times).
Makefile:10: recipe for target 'keter' failed
make[1]: *** [keter] Error 1
make[1]: Leaving directory '/home/callen/work/solo/hestia'
Makefile:15: recipe for target 'hestia' failed
make: *** [hestia] Error 
```

I'm a bit baffled. Builds fine if I just run stack build. What am I doing wrong?

**Comment by bitemyapp** [comment]
```
$ echo $GHC_PACKAGE_PATH

$ stack exec -- echo $GHC_PACKAGE_PATH

```

**Comment by luigy** [comment]
does `stack exec --no-ghc-package-path -- yesod keter` take care of it?

I'm not sure how to escape it, but this should also show what it is set to
`$ stack exec -- bash -c 'echo $GHC_PACKAGE_PATH'`

**Comment by bitemyapp** [comment]
Just bumped into this, slightly caremad

```
$ stack exec -- env | grep GHC
GHC_DOT_APP=/Applications/ghc-7.8.3.app
GHC_PACKAGE_PATH=/home/callen/work/solo/.stack-work/install/x86_64-linux/lts-5.1/7.10.3/pkgdb:/home/callen/.stack/snapshots/x86_64-linux/lts-5.1/7.10.3/pkgdb:/home/callen/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/package.conf.d
```

Going to see if what you suggested works.

**Comment by bitemyapp** [comment]
```
$ stack exec -- bash -c 'echo $GHC_PACKAGE_PATH'
/home/callen/work/solo/.stack-work/install/x86_64-linux/lts-5.1/7.10.3/pkgdb:/home/callen/.stack/snapshots/x86_64-linux/lts-5.1/7.10.3/pkgdb:/home/callen/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/package.conf.d
```

hurr durr hurr i kno how2bash

thank you @luigy 

```
$ stack exec --no-ghc-package-path -- yesod keter
cleaning...
Resolving dependencies...
Configuring hestia-0.0.0...
cabal: At least the following dependencies are missing:
aeson >=0.6 && <0.11,
bcrypt -any,
case-insensitive -any,
classy-prelude >=0.10.2,
classy-prelude-conduit >=0.10.2,
classy-prelude-yesod >=0.10.2,
clientsession -any,
composition-extra -any,
conduit >=1.0 && <2.0,
data-default -any,
either -any,
email-validate -any,
errors -any,
esqueleto -any,
fast-logger >=2.2 && <2.5,
file-embed -any,
free -any,
hashable -any,
hjsmin ==0.1.*,
http-client -any,
http-client-tls -any,
http-conduit ==2.1.*,
lens -any,
lens-aeson -any,
mandrill -any,
monad-control >=0.3 && <1.1,
monad-logger >=0.3.8 && <0.4,
mtl -any,
persistent >=2.0 && <2.3,
```

I've gotten yesod keter to run, but my new problem is more keter specific so work on that now. Thank you!

**Comment by bitemyapp** [comment]
Waaaaiiiiit a second

https://github.com/yesodweb/yesod/commit/a7cccf2a7c5df8b26da9ea4fdcb6bac5ab3a3b75

We need to use the GHC_PACKAGE_PATH or keter can't use the deps provided by Stack.

wtf is going on here?

**Comment by luigy** [comment]
I [think](https://github.com/yesodweb/yesod/blob/master/yesod-bin/Keter.hs#L77-L82) you might be able to just `yesod keter` if you have a `stack.yaml` in the same directory you invoke it from. Man stack detection in yesod-bin is not robust.  Maybe I should PR something that if `STACK_EXE`(this var is set only by `stack exec` and not used) to kick it into stack instead of cabal so that `stack exec -- yesod keter` works

**Comment by bitemyapp** [comment]
https://github.com/yesodweb/yesod/blob/master/yesod-bin/main.hs#L109-L114 is something missing here?

**Comment by bitemyapp** [comment]
@luigy can't really do that without duplicating information due to relatively pathed packages in the stack.yaml

**Comment by luigy** [comment]
In the  meantime you can probably do the building that keter does explicitly in your Makefile with this to get around it:
```sh
mkdir -p ./dist/bin
stack clean
stack --local-bin-path ./dist/bin build --copy-bins
yesod keter --nobuild
```

**Comment by bitemyapp** [comment]
![screenshot from 2016-02-18 15-32-01](https://cloud.githubusercontent.com/assets/320177/13158913/c504060a-d654-11e5-9023-8a1c3e23b023.png)

it's a bit weird getting trolled by your tool

**Comment by bitemyapp** [comment]
@luigy the `--nobuild` solution has me good to go for now, will write a script for it. Thank you! Hopefully someone can figure out why this is broken.

**Comment by borsboom** [comment]
I'm not quite clear from the thread whether this is a Stack issue or a Keter issue.  If the former, any idea what Stack should be doing differently to make this work?

**Comment by bitemyapp** [comment]
@borsboom I'm leaning towards it being yesod-bin not handling `GHC_PACKAGE_PATH` correctly but triage from @snoyberg would probably be best. I don't think Stack has a means of transmuting the env into arguments for keter here.

For the sake of cleanliness, I'll close but would like to see triage conclusion if possible -- this is a well worn path for people using Stack/Yesod together and all the docs say to `stack exec -- yesod keter`.

**Comment by luigy** [comment]
@borsboom I would say is `yesod keter` not properly detecting in more cases that `stack` can be used to build the executables and falling back to cabal without it handling `GHC_PACKAGE_PATH`.

Another way would be if it parsed `GHC_PACKAGE_PATH` and passed it properly to cabal like it does with `yesod devel`.  I can go either way depending on what gets agreed, but I started a PR for `yesod-bin` to use `stack` if  `STACK_YAML` is present
