### ISSUE TITLE
Paths module in generated cabal file breaks Cabal

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#1814]
stack regenerates my cabal file from the hpack package.yaml (great!). But hpack (0.9.0 according to the generated file) adds:
```
other-modules
  Paths_hledger-lib
```
which Cabal chokes on:
```
Unable to parse cabal file /Users/simon/src/hledger/hledger-lib/hledger-lib.cabal: NoParse "other-modules" 101
```
The module name seems to be what it doesn't like.

`ghc-pkg list Cabal` reports version 1.22.5.0, `cabal --version` reports cabal-install version 1.22.7.0
and Cabal version 1.22.6.0 (with or without `stack exec`).

**Comment by mgsloan** [comment]
Looks to me like `other-modules` is missing a colon?

**Comment by mgsloan** [comment]
Since this is now being tracked on the hpack tracker, closing as an upstream issue.

**Comment by sol** [comment]
`hpack-0.9.1` addresses this issue.
