### ISSUE TITLE
1.0.4 doesn't build with aeson 0.11.0.0

### ISSUE THREAD

**Issue by felixonmars** [commercialhaskell/stack#1818]
I am getting the following error when trying to build stack 1.0.4 with aeson 0.11.0.0:

```
src/Stack/Types/Image.hs:46:82:
    Overlapping instances for FromJSON (ImageDockerOpts, [JSONWarning])
      arising from a use of `..:?'
    Matching instances:
      instance (FromJSON a, FromJSON b) => FromJSON (a, b)
        -- Defined in `aeson-0.11.0.0:Data.Aeson.Types.Instances'
      instance FromJSON (ImageDockerOpts, [JSONWarning])
        -- Defined at src/Stack/Types/Image.hs:62:10
    In the first argument of `jsonSubWarningsT', namely
      `(o ..:? imgDockerOldArgName)'
    In a stmt of a 'do' block:
      (oldDocker :: Maybe ImageDockerOpts) <- jsonSubWarningsT
                                                (o ..:? imgDockerOldArgName)
    In the expression:
      do { (oldDocker :: Maybe ImageDockerOpts) <- jsonSubWarningsT
                                                     (o ..:? imgDockerOldArgName);
           (dockers :: [ImageDockerOpts]) <- jsonSubWarningsT
                                               (o ..:? imgDockersArgName ..!= []);
           let imgMonoidDockers = dockers ++ maybeToList oldDocker;
           return (ImageOptsMonoid {..}) }
```

**Comment by phadej** [comment]
I see, you use `allow-newer: true` or similar to build with `aeson-0.11`?

**Comment by phadej** [comment]
I could fix this, but only after `persistent-template` is lifted `aeson` bounds.

**Comment by borsboom** [comment]
I've uploaded stack-1.0.4.1 to Hackage which fixes the build with aeson-0.11.0.0.  I've also adjusted the bounds for stack-1.0.4 to disallow aeson-0.11.

**Comment by felixonmars** [comment]
@phadej I am packaging for Arch and building stack in a new batch of dependencies, including `aeson-0.11`.

Thanks for the quick fix!

**Comment by phadej** [comment]
@felixonmars AFAIK `persistent-template` bounds don't allow `aeson-0.11`. I'm not sure if it's a good idea to include into distributions something that authors are not aware of. Imagine situation where someone fills issue to `persistent` issue tracker that it doesn't work for some reason - and that reason is `aeson-0.11`. It probably isn't, but as history shows with `0.10` it could been.

At least, please open issue to `persistent` tracker, that you did so. Then the actual maintainers of the package are aware of that downstream change.

**Comment by felixonmars** [comment]
I went ahead after waiting for a few days, because a PR was opened 11 days ago and didn't receive any attention so far: https://github.com/yesodweb/persistent/pull/539

But you are right, I'll be more careful next time.
