### ISSUE TITLE
File watch doesn't trigger build when package.yaml changes

### ISSUE THREAD

**Issue by tfausak** [commercialhaskell/stack#1819]
If I edit my `package.yaml` (for hpack) while running `stack build --file-watch`, a new build doesn't start. Seems like it should.

**Comment by mitchellwrosen** [comment]
The list of watched files is populated with:
- all local packages' files
- stack.yaml

Perhaps `Stack.Build.Source.getPackageFilesSimple` should be made aware of `package.yaml`?

**Comment by mgsloan** [comment]
@tfausak Good catch, should be fixed - reopen if not.
