### ISSUE TITLE
Multiple-package stack ghci gets confused on camel-cased module names in explicit packages

### ISSUE THREAD

**Issue by ozataman** [commercialhaskell/stack#1827]
My apologies if this is an already known issue - I wasn't able to find a matching item in a quick scan just now.

Here's the setting where I've run into this issue (proprietary codebase, so I can't just share the entire setting unfortunately):

- Latest released stack (via `stack upgrade`)
- GHC 7.8
- Shell is on ZSH (via oh-my-zsh)
- Multiple package stack project
- One of the packages has module names that are camel cased. In this case, the module in question is `RedSql.Types`.
- `stack build` by itself runs just fine and builds all of the packages in the project. No issues there.
- `stack repl` seems to have the behavior of re-interpreting ALL of the modules in every package explicitly included in the project.
- Loading a specific ad-hoc haskell file up in `stack repl` via `:load`
- Loaded file imports `RedSql.Types`, which is one of the packages in the project. This is where the problem is.

Trying to do the above load produces the following error:

```
/..../myProject/vendor/aws-redshift/src/Redsql/Types.hs:17:8:
    File name does not match module name:
    Saw: ‘RedSql.Types’
    Expected: ‘Redsql.Types’
Failed, modules loaded: none.
Prelude>
```

Please note there is in fact no issue with the path or folder names. In the filesystem, the folder is called 'RedSql' and not 'Redsql'. Something somewhere seems to lose the case information and just convert module segments to titlecase, which I believe is in turn confusing GHC.

**Comment by mgsloan** [comment]
GHC seems to think that the folder is called `Redsql`.  The error message starts with `/..../myProject/vendor/aws-redshift/src/Redsql/Types.hs:17:8:`.  Are you sure that path doesn't exist?

Could be some crazy unicode thing, but that seems unlikely.

**Comment by ozataman** [comment]
@mgsloan Thanks for looking into this so quickly! 

It seems like the issue was a temporary/local artifact that I wasn't able to rule out when I filed the ticket. I just started fresh (new clone, fresh stack init, etc.) to make sure and everything seems OK. Sorry for the scare - I'm closing the issue.
