### ISSUE TITLE
`stack build` with hpack notifies about cabal being up-to-date twice

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack#1828]
it probably shouldn't even tell me this at all, but certainly not twice.

to reproduce just have a 'package.yaml' file, and build the project once (so the .cabal is generated) then build the project again without changes; all that is emitted by stack is, say:

````
11:09 AM noon ∈ dev-dashboard>stack build
/home/noon/dev/dev-dashboard/dev-dashboard.cabal is up-to-date
/home/noon/dev/dev-dashboard/dev-dashboard.cabal is up-to-date
````

(edit): stack version:

````
11:33 AM noon ∈ dev-dashboard>stack --version
Version 1.0.5, Git revision 0ce4c9d51d830456e57a0da347fbb8971d3919ad x86_64
````

**Comment by silky** [comment]
relatedly, the issue is more pronounced with `stack ghci`:


````
11:13 AM noon ∈ dev-dashboard>stack ghci
/home/noon/dev/dev-dashboard/dev-dashboard.cabal is up-to-date
/home/noon/dev/dev-dashboard/dev-dashboard.cabal is up-to-date
/home/noon/dev/dev-dashboard/dev-dashboard.cabal is up-to-date
/home/noon/dev/dev-dashboard/dev-dashboard.cabal is up-to-date
/home/noon/dev/dev-dashboard/dev-dashboard.cabal is up-to-date
/home/noon/dev/dev-dashboard/dev-dashboard.cabal is up-to-date
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Using main module: 1. Package `dev-dashboard' component exe:dev-dashboard-exe with main-is file: /home/noon/dev/dev-dashboard/app/Main.hs
Configuring GHCi with the following packages: dev-dashboard
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
[1 of 3] Compiling Paths_dev_dashboard ( /home/noon/dev/dev-dashboard/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/autogen/Paths_dev_dashboard.hs, interpreted )
[2 of 3] Compiling Lib              ( /home/noon/dev/dev-dashboard/src/Lib.hs, interpreted )
[3 of 3] Compiling Main             ( /home/noon/dev/dev-dashboard/app/Main.hs, interpreted )
Ok, modules loaded: Lib, Paths_dev_dashboard, Main.
````

**Comment by luigy** [comment]
this looks related to #1813, but I think it would be better to not log these to stdout

**Comment by silky** [comment]
well it seems that at least hpack shouldn't be actually getting run more than once for any single given execution of stack, right?

**Comment by luigy** [comment]
indeed, are you using a `stack` using your PR #1822? :P 
`findCabalFiles` is probably getting called that many times as your log is showing and causing this behavior

**Comment by silky** [comment]
ah, haha, nup, my stack version is:

````
11:33 AM noon ∈ dev-dashboard>stack --version
Version 1.0.5, Git revision 0ce4c9d51d830456e57a0da347fbb8971d3919ad x86_64
````

**Comment by luigy** [comment]
hehe, so then it has to be `findOrGenerateCabalFile` that gets called multiple times.
This shows where it happens for [ghci](https://github.com/commercialhaskell/stack/blob/704764f472d2542658a48c8ce5b16c03a99e6f43/src/Stack/Ghci.hs#L302) 

#1815 should help with this

**Comment by mgsloan** [comment]
I've merged the PR.  Please reopen if still an issue.

**Comment by silky** [comment]
thanks that PR fixed it :)

**Comment by luigy** [comment]
Btw this takes care of it only while the modification time of package.yaml is lower than the cabal file, otherwise you'll get the same behavior

**Comment by mgsloan** [comment]
This is more fully resolved by https://github.com/commercialhaskell/stack/commit/872ff1eae6ff58851361de9335fc1d82539b66f7
