### ISSUE TITLE
datadir for `stack install`ed executables points to project folder

### ISSUE THREAD

**Issue by lspitzner** [commercialhaskell/stack#1829]
Steps to reproduce:

~~~~
> mkdir temp-foo
> cd temp-foo
> cabal get $SOME_PACKAGE_WITH_DATA_DIR
> cd "$SOME_PACKAGE_WITH_DATA_DIR-$SOME_VERSION"
> stack init
> stack install
> cd ../..
> rm -rf temp-foo
> ~/.local/bin/$SOME_PACKAGE_WITH_DATA_DIR
*accesses temp-foo/../data/...*, breaking if stuff is not there anymore.
~~~~

Expected behaviour: Either

1) the executable in `.local/bin` keeps working after removing `temp-foo` (by properly setting the data-dir to `.local/share` or something; or
2) the executable in `.local/bin` is just a link to somewhere inside `temp-foo`, so it completely stops working.

Actual:

The executable is still there, but breaks when/if it accesses its data-dir. Also, it may re-create the `temp-foo` directory if it uses some `mkdir -p`, which is annoying.

~~~~
$ stack --version
Version 0.1.10.1 x86_64
~~~~

[Edit:] Reproduced with
~~~~
Version 1.0.4.1 x86_64
~~~~

**Comment by mgsloan** [comment]
Yes, this would be good.  We're tracking this feature with this issue: https://github.com/commercialhaskell/stack/issues/848
