### ISSUE TITLE
should `resolver` be a required field in `stack.yaml`?

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack#1831]
i just found myself wanting a `stack.yaml` that doesn't specify a resolver, because i'll do that in a travis build config matrix.

so i need to set a dummy resolver that will always be overwritten

does it make sense to not require `resolver` for this case? or is it better just to live with it being required, and set it to a dummy value? or is there another, better solution?

**Comment by mgsloan** [comment]
How about using a compiler resolver like `ghc-7.10.3`?

**Comment by silky** [comment]
i see.

i guess the only option then would be to fail with a slightly different error message to the current one, stating that a snapshot must be set, or something?

**Comment by mgsloan** [comment]
We could conceivably delay parsing the resolver field until it's actually needed (and not require that it parse if `--resolver` is passed)

**Comment by silky** [comment]
okay fair enough.
