### ISSUE TITLE
Using nix & haddock fails

### ISSUE THREAD

**Issue by aspiwack** [commercialhaskell/stack#1832]
Stack systematically fails building with the an error such as the following when using both `--nix` (or if `nix` is activated in the `stack.yaml`) and `--haddock`.
```
$ stack --nix build --haddock
[…]
Updating Haddock index for local packages and dependencies in
[…]/.stack-work/install/x86_64-linux-nix/nightly-2016-02-03/7.10.3/doc/all/index.html
[…]/.stack-work/install/x86_64-linux-nix/nightly-2016-02-03/7.10.3/doc/ghc-prim-0.4.0.0/src: copyFile: permission denied (Permission denied)
```

It would seem that when constructing the `doc/all/index.html` stack (but only when nix is on) will look for all the doc in the `.stack-work` even when it is located in the snapshot.

This is a regression between 1.0.0 and 1.0.4.

**Comment by YPares** [comment]
I'm able to reproduce it. For my part it blocks on creating the doc for `directory-1.2.2.0`
```
/home/ywen/tweag/sage-pr-review/src/pepin/.stack-work/install/x86_64-linux-nix/nightly-2016-02-03/7.10.3/doc/directory-1.2.2.0/src: copyFile: permission denied (Permission denied)
```
Two strange things:
- the folder `directory-1.2.2.0` doesn't even exists here (and yet it fails with "permission denied", not with "copyFile: does not exist (No such file or directory)")
- it's perfectly able to write the docs for other packages

**Comment by YPares** [comment]
Minimal repro: `stack new foo ; cd foo ; stack --nix build --haddock`

**Comment by YPares** [comment]
Okay, after performing a bisect, the first commit to exhibit the bug is 46a7c463106b5b2c0cb32333f054fadd9367380e

**Comment by mrkkrp** [comment]
Can you reproduce this if stack is built with `path-io-1.0.1`, not `path-io-1.0.0`?

**Comment by YPares** [comment]
@mrkkrp Same problem with `path-io-1.0.1`. I located the source of the bug, it's there: https://github.com/commercialhaskell/stack/blob/master/src/Stack/Build/Haddock.hs#L231
It's because with using Nix, GHC comes from the nix store, and so does the doc cabal tries to copy.
And as everything is readonly is the nix store, permissions aren't changed, copied dirs remain readonly, hence the "permission denied" error.

**Comment by YPares** [comment]
@mrkkrp So yes, it comes from the differences between the old stack's `copyDirectoryRecursive` ( https://github.com/commercialhaskell/stack/commit/46a7c463106b5b2c0cb32333f054fadd9367380e?diff=split#diff-b3aa59d1fdddae4facaecf2ace6c9675L233 ) and the new path-io's `copyDirRecur` ( http://hackage.haskell.org/package/path-io-1.0.1/docs/src/Path-IO.html#copyDirRecur )

Perms shouldn't be applied at each level of recursion I think, or else after you're shallow-copied one dir A into destination B, if you set B to be readonly like A then you can't recursively copy anymore into B.

**Comment by mrkkrp** [comment]
Perhaps I need to abandon the idea with permission preserving for directories. Or at least change permissions when directory tree is already copied. I'll push necessary changes tomorrow and release version 1.0.2 which should resolve the problem.

**Comment by mrkkrp** [comment]
@YPares, OK, my idea so far is to make `copyDirRecur` copy permissions after entire directory tree is recreated. For convenience I will also expose `copyDirRecur'` function that won't copy permissons.

**Comment by mrkkrp** [comment]
@YPares, please try with `path-io-1.1.0`. Now `copyDirRecur` can fully copy read-only directories, but you probably need to replace `copyDirRecur` with `copyDirRecur'` anyway (this does not preserve directory permissions).

**Comment by YPares** [comment]
@mrkkrp Thanks! Yes, it works with `path-io-1.1.0`, both with `copyDirRecur` and `copyDirRecur'`, although neither ignore permissions: in both cases files copied in .stack-work are readonly after.
To be sure nobody has any issue with that change, I'm issuing a PR.

**Comment by mrkkrp** [comment]
> in both cases files copied in .stack-work are readonly after

This would really suprsize me, since `copyDirRecur'` does not run any code to copy permissions and it's even tested that read-only directories became editable after copying. Are you sure that this is what is happening with it?

**Comment by YPares** [comment]
I'm using commit
https://github.com/commercialhaskell/stack/commit/fa7df8492ac3f04845343a84d0be10dcc928e143
(my PR),
and after building:

```
$ ls -la
.stack-work/install/x86_64-linux-nix/lts-5.2/7.10.3/doc/ghc-prim-0.4.0.0/
total 2592
dr-xr-xr-x 3 ywen ywen   4096 mars   5 18:31 .
drwxr-xr-x 7 ywen ywen   4096 mars   5 19:34 ..
dr-xr-xr-x 2 ywen ywen   4096 mars   5 18:31 src
-r--r--r-- 1 ywen ywen   3159 mars   5 18:31 doc-index-42.html
-r--r--r-- 1 ywen ywen   2848 mars   5 18:31 doc-index-43.html
-r--r--r-- 1 ywen ywen   2848 mars   5 18:31 doc-index-45.html
-r--r--r-- 1 ywen ywen   3168 mars   5 18:31 doc-index-47.html
-r--r--r-- 1 ywen ywen   3479 mars   5 18:31 doc-index-60.html
-r--r--r-- 1 ywen ywen   2866 mars   5 18:31 doc-index-61.html
-r--r--r-- 1 ywen ywen   3479 mars   5 18:31 doc-index-62.html
-r--r--r-- 1 ywen ywen   7845 mars   5 18:31 doc-index-A.html
-r--r--r-- 1 ywen ywen 263740 mars   5 18:31 doc-index-All.html
-r--r--r-- 1 ywen ywen   8105 mars   5 18:31 doc-index-B.html
-r--r--r-- 1 ywen ywen  14798 mars   5 18:31 doc-index-C.html
```

2016-03-05 19:00 GMT+01:00 Mark Karpov <notifications@github.com>:

**Comment by mrkkrp** [comment]
I'm talking only about directories. Files are copied by `copyFile` which alwas tries to copy permissions. Directories themselves should be editable though.

**Comment by YPares** [comment]
I agree, but the line

dr-xr-xr-x 2 ywen ywen   4096 mars   5 18:31 src

shows that `src` is still readonly.

2016-03-06 5:51 GMT+01:00 Mark Karpov <notifications@github.com>:
