### ISSUE TITLE
Add mega-sdist/upload functionality

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#184]

**Comment by mgsloan** [comment]
@snoyberg This can be closed, right?

**Comment by snoyberg** [comment]
I don't believe mega-sdist functionality (comparing generated sdists to what's available on Hackage already) has been implemented.

**Comment by mgsloan** [comment]
Gotcha, yeah, I wasn't sure what that term meant.

**Comment by snoyberg** [comment]
This is obscure enough that I'll close this. If I have a burning desire for it in the future, I'll merge in the separate tool then.
