### ISSUE TITLE
Have list-dependencies command default to using "-" as a separator

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1844]
Currently, `stack list-dependencies` separates packages from their version with a space like `pkg 1.0`.  I don't like this behavior, because it makes it uglier to do cool things like `stack list-dependencies --separator "-" | while read pkg; do stack unpack $pkg; done`.  Pretty much every tool expects `pkg-1.0.` not `pkg 1.0`.

This could break people's scripts though, best to combine this with some other breaking change to the functionality, like https://github.com/commercialhaskell/stack/issues/1614

**Comment by markus1189** [comment]
I totally agree with you that for use cases like above `-` is more useful, so changing the default to `-` would be okay from my side, such that you only get ` ` if you explicitly want it.  In the original implementation I just took the same output as `cabal list --installed` so there have been no deeper thoughts ;)

**Comment by mgsloan** [comment]
Ah, I see!  That makes more sense, thanks for the explanation.  For the reader, it's `cabal list --installed --simple-output` that currently matches `stack list-dependencies`.  Considering it's already this behavior and I suppose it is easier to parse, I'm fine leaving it.
