### ISSUE TITLE
Funky OS X travis failure (transient issue)

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1848]
https://travis-ci.org/commercialhaskell/stack/jobs/112195924

```
  1) Stack.BuildPlan finds missing transitive dependencies #159
       uncaught exception: HttpException (TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")) "raw.githubusercontent.com" 443)
```

**Comment by phadej** [comment]
That *might* happen on linux too. Happens quite often in `github` tests. I'm not sure whether the problem is in `tls` or GitHub servers

**Comment by rzabcik** [comment]
Can confirm this error happens on Linux. When attempting to `stack templates` I got:

```
Failed to download templates. The HTTP error was: TlsExceptionHostPort (HandshakeFailed (Error_Packet_unexpected "Alert [(AlertLevel_Fatal,BadRecordMac)]" " expected: change cipher")) "api.github.com" 443

**Comment by silky** [comment]
it's not github specific; i get this often, via the wreq library, when doing a lot of queries to the bitbucket api.

**Comment by rzabcik** [comment]
I fixed this problem by making sure my `tls` package was up-to-date. It needs to be at least 1.3.5.

**Comment by mgsloan** [comment]
@radix Ah, interesting!  Thanks for the info.  Looks like we'll want to wait for lts to include `1.3.5`
