### ISSUE TITLE
stack build --docker: stack-1.0.3 executable not found for linux64

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stack#1861]
In https://hub.docker.com/r/fpco/stack-build/, I see

> GHC (patched), tools (stack, cabal-install, happy, alex, etc.), and system developer libraries required to build all Stackage packages

but it seems that stack is not found inside the image:

I'm on mac:
```
$ uname -a
Darwin MacBook-Air-de-AAA.local 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
```

Using stack 1.0.3
```
$ stack --version
Version 1.0.3, Git revision 280c5d443d47afd72e6746c87d85ff90cc437903 x86_64
```

Using fpco/stack-build:lts-3.9
```
$ stack docker pull
Pulling image from registry: 'fpco/stack-build:lts-3.9'
lts-3.9: Pulling from fpco/stack-build
[...]
```

and stack tool is not found:
```
$ stack build --docker
Downloading Docker-compatible stack executable
stack-1.0.3 executable not found for linux64
Use the 'stack-exe' option to specify a location
```

Can't `stack build --docker` use the bundled stack tool even if it doens't mach host stack version ?

**Comment by borsboom** [comment]
Sorry for late reply, but this is because only stable/released versions of Stack (that is, those with an even third component, such as 1.0.2 and 1.0.4) have linux64-compatible binaries available for use with Docker.
