### ISSUE TITLE
'stack ghc' doesn't run C preprocessor?

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#1869]
Sorry, hit submit on accident... filling out details now

**Comment by mitchellwrosen** [comment]
I was trying to verify a bug in the latest `mwc-random`:

```
> stack unpack mwc-random-0.13.4.0
> cd mwc-random-0.13.4.0
```
Give it a stack.yaml...
```
> cat <<EOF >stack.yaml
resolver: lts-5.5
EOF
```
Make a file to compile...
```
> cat <<EOF >foo.hs
import System.Random.MWC
main = pure ()
EOF
```
Compile it
```
> stack ghc foo.hs

System/Random/MWC.hs:103:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_primitive(0,6,0)
     ^

System/Random/MWC.hs:115:0:
     error: missing binary operator before token "("
     #if !MIN_VERSION_base(4,8,0)
     ^

System/Random/MWC.hs:482:0:
     error: missing binary operator before token "("
     #if MIN_VERSION_primitive(0,6,0)
```

It seems to work fine with `mwc-random-0.13.4.0` in the package database, rather than the local database.

This is stack ver `1.0.4`

**Comment by mgsloan** [comment]
`stack ghc` is pretty much just an alias for `stack exec ghc`, with a bit of extra smarts to handle the `--package` flag.  In other words, it does not use any cabal information at all, but will use the right GHC and package databases.

There's a PR in limbo state that tries adding something like this, see the discussion here - https://github.com/commercialhaskell/stack/pull/1737 .

Anyway, the main problem is probably that your "foo.hs" is at the root dir of mwc-random and uses modules from it, and it lacks a `src` dir.  This means that ghc will find these modules and try to compile them.  Instead, put `foo.hs` in a subfolder.  Then, you can do `stack ghc foo.hs --package mwc-random` (the `--package` part is only necessary if you don't want to first do a `stack build`)
