### ISSUE TITLE
Stack ghci with test dependencies installed

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#1871]
When I run `stack ghci --no-load` I typically have a `.ghci` file in my local directory which loads both the executable and some of the test suite. However, `stack ghci` doesn't ensure the test suite dependencies are already installed. Is there some flag I can add to `stack ghci` to make sure all the dependencies for all targets are installed? Should `--no-load` imply that, since you are kind of saying you are going to load something special anyway?

**Comment by luigy** [comment]
after 3348ec867bb339ff5f525f68f2e40248d5bfedce `stack ghci` now takes build options so `stack ghci --test --no-load` should do it

**Comment by ndmitchell** [comment]
Thanks!
