### ISSUE TITLE
Cannot create a project with a hyphen in the name

### ISSUE THREAD

**Issue by cokleisli** [commercialhaskell/stack#1873]
> stack new h-99                                                                                                                                                         
> Expected valid package name, but got: h-99
> 
> Usage: stack new PACKAGE_NAME [--bare] [TEMPLATE_NAME] [-p|--param KEY:VALUE]
>                  ([--resolver RESOLVER] | [--prefer-lts] | [--prefer-nightly])
>                  [--solver] [--force] [--ignore-subdirs] [--help]
>   Create a new project from a template. Run `stack templates' to see available
>   templates.
> 
> stack new h99                                                                                                                                                                     Downloading template "new-template" to create project "h99" in h99/ ...
> Using cabal packages:
> - h99/h99.cabal
> 
> Selecting the best among 4 snapshots...
> 
> * Selected lts-5.1
> 
> Initialising configuration using resolver: lts-5.1
> Writing configuration to file: h99/stack.yaml
> All done.
>

**Comment by mgsloan** [comment]
From the cabal docs:

> A package is identified by a globally-unique package name, which consists of one or more alphanumeric words separated by hyphens. To avoid ambiguity, each of these words should contain at least one letter. 

I have added similar text to stack's output in this circumstance:

```
stack new h-99
Expected valid package name, but got: h-99
Package names consist of one or more alphanumeric words separated by hyphens.
To avoid ambiguity with version numbers, each of these words must contain at least one letter.


Usage: stack new PACKAGE_NAME [--bare] [TEMPLATE_NAME] [-p|--param KEY:VALUE]
                 [DIRS] [--solver] [--omit-packages] [--force]
                 [--ignore-subdirs] [--help]
  Create a new project from a template. Run `stack templates' to see available
  templates.
```
