### ISSUE TITLE
buildStackProject in lib.nix

### ISSUE THREAD

**Issue by AlleaRizary** [commercialhaskell/stack#1879]
Hi, I have got an error when integrate nix with stack.

the error was 
`error: getting status of ‘/home/user/nixpkgs/pkgs/development/development/haskell-modules/generic-stack-builder.nix’: No such file or directory
`

the way i do it is change the buildStackPackage from:

` buildStackProject = pkgs.callPackage ../development/haskell-modules/generic-stack-builder.nix { };`

into 

` buildStackProject = pkgs.callPackage ../haskell-modules/generic-stack-builder.nix { };`

i remove the '/development' and it works perfectly..

the question is, is it okay to do it this way??? and when i enter nix-shell, i should install stack again or not?

thanks

**Comment by mboes** [comment]
This is a bug upstream: https://github.com/NixOS/nixpkgs/pull/13709.
