### ISSUE TITLE
Bug when a package is specified by a url to a tarball

### ISSUE THREAD

**Issue by paul-rouse** [commercialhaskell/stack#1884]
This is a small, but serious, error introduced in https://github.com/commercialhaskell/stack/commit/99eb520bc3099afacb1403098838a5280ee76e32 (on 27 Jan).  I'll send a PR in a few minutes to fix it and provide a test case.

Using a reference like this in `stack.yaml` is now broken:
```
packages:
- https://hackage.haskell.org/package/half-0.2.2.3/half-0.2.2.3.tar.gz
```
It produces an error along the lines of "Archive extraction failed. We support tarballs and zip, couldn't handle the following URL, ...", but the underlying problem is that it is trying to use the tarball file name as the directory into which to unpack!

[This is nothing to do with the particular package, which has been chosen here simply because it is a small one for testing purposes.]

**Comment by mgsloan** [comment]
Good catch, thanks for the PR!
