### ISSUE TITLE
Custom Preprocessed Files Don't Rebuild

### ISSUE THREAD

**Issue by deech** [commercialhaskell/stack#1891]
I have a custom preprocessor that converts files in my `src` directory to Haskell files. However when any of those originals change `stack build` doesn't appear to reprocess. If I do  `stack clean` first that works.

**Comment by mgsloan** [comment]
Are those files listed in `extra-source-files` in your cabal file?  If so, this could be a bug.  It seems prudent to treat a package as being dirty if these files are changed.  I don't see this being done anywhere [here](https://github.com/commercialhaskell/stack/blob/2bf17fbc2e84faadf13fe7a29d5954635e646b73/src/Stack/Package.hs#L223)

**Comment by deech** [comment]
Yes they are. If it helps in my scenario I'm only building executables (no library). As I found out `extra-source-files` is only allowed once at the top of the Cabal file. If I put it in each executable's stanza, Cabal complains.

**Comment by NicolasT** [comment]
I believe I'm having a similar issue: a source file is listed in `extra-source-files` in the global section of my package, and then converted into a `data-files` member (also listed in the global section) through ` Custom` build (`Setup.hs` calling out to some tool in the `buildHook`).

Unexpectedly, whenever I modify the source file, no rebuild is triggered: not when using `stack build --file-watch`, nor when running plain `stack build` multiple times.

**Comment by borsboom** [comment]
I think this is resolved by the merge of #2362.  Please re-open if not.
