### ISSUE TITLE
Format of target for stack ghci

### ISSUE THREAD

**Issue by fatlazycat** [commercialhaskell/stack#1893]
Appears to be of the format project:test:test-suite for a test target etc.

Is this documented anywhere ? Can't seem to find it or on the cmd line help.

Thanks
Graham

**Comment by mgsloan** [comment]
@fatlazycat It's the same format as the targets taken by the build command http://docs.haskellstack.org/en/stable/build_command/

At some point in the future, ghci will probably support more targets than the build command, such as filepaths https://github.com/commercialhaskell/stack/issues/1361 .  I would also like to support loading a particular module by name.

There probably ought to be a doc page for ghci - I've opened [this issue](https://github.com/commercialhaskell/stack/issues/1896) about that.

**Comment by fatlazycat** [comment]
@mgsloan thanks
