### ISSUE TITLE
Failing build can cause spurious test successes

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1895]
`STACK_YAML="../stack.yaml" stack build --test --file-watch --fast "proj:proj" 2>&1`

can just run a pre-existing binary. This leads to a spurious ExitSuccess!

**Comment by mgsloan** [comment]
I believe the concise repro is `stack test stack:stack`.

The problem is likely that you are specifying an explicit target component and then asking for tests to be built.  `--test` doesn't add in all test components, it enables tests for targets like `stack` (without a component spec)

**Comment by luigy** [comment]
@bitemyapp bro, --file-watch is so 2015... jk :joy: 

hello ghcid + stack https://cldup.com/zU-xtcjhZW.mp4 (not merged, yet)

**Comment by bitemyapp** [comment]
@luigy is that in a branch somewhere?
