### ISSUE TITLE
Documentation for "stack ghci"

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1896]
`stack ghci` now has quite a few features, and full usage of it is getting a git complicated.  It'd be good to have a documentation page dedicated to it.

If someone wants to take a swing at this, feel free!  I will probably get around to it at some point - I'll assign the issue to myself if I start working on it.

**Comment by simonmichael** [comment]
For the record, after the command-line help the place I looked next for `stack ghci` docs was the stack user guide (which itself should be linked more prominently I think), at http://docs.haskellstack.org/en/stable/GUIDE/#ghci-the-repl . Here might be a good place to mention that stack ghci accepts the same options as stack build (according to #2104), and link to the doc describing those.

**Comment by simonmichael** [comment]
PS also note `stack gchi`  typo there.

**Comment by mpilgrem** [comment]
Closing as, in 2023, there is a dedicated page: https://docs.haskellstack.org/en/stable/ghci/.
