### ISSUE TITLE
upgrade global packages

### ISSUE THREAD

**Issue by legrostdg** [commercialhaskell/stack#1899]
There should be a way to upgrade globally installed packages (other than running "stack install mypackage" for each package).

**Comment by mgsloan** [comment]
I don't understand what you want that `stack install mypackage` does not provide.

**Comment by legrostdg** [comment]
I mean something like "npm upgrade -g": upgrade all the global packages, without having to do "stack install package1", "stack install package2", etc. to upgrade everything

**Comment by mgsloan** [comment]
Ah, I see!  Yes, others have wanted this as well - see the discussion [here](https://github.com/commercialhaskell/stack/issues/1610).

I've opened an issue with a potential resolution - https://github.com/commercialhaskell/stack/issues/1904 .  Shouldn't be very hard, but I think some other things should happen first.

**Comment by flip111** [comment]
Is there any way to get a list of packages that get loaded when you are not in a project (but in global project instead)? Is it then from there possible to remove all dependencies from that list? That way you only get the packages of which you would need to type `stack install package` to update them.

**Comment by mgsloan** [comment]
test

**Comment by mgsloan** [comment]
@flip111 Not sure I follow.  The global project works exactly like a normal project, except that by default it has no local packages.

**Comment by flip111** [comment]
@mgsloan in the other discussion you say

> There is no special tracking of which packages you've installed.

However when i run `stack exec ghci` i can import packages that at some point in time where installed with `stack install package`. But also dependencies of those package would have been installed. 

For example, i `stack install a` which depends on `b` and `n` and i `stack install x` which depends on `y` and `n`. Now when i start `stack exec ghci` i can import packages `a`, `b`, `n`, `x` and `y` right?

Can i get this list `a`, `b`, `n`, `x`, `y` somehow? Can i then backwards figure out that only `a` and `x` where "top-level" packages (or whatever is an appropriate name here) and the rest are dependencies? If i get back `a` and `x` i can then run `stack install a x` to upgrade my global project.

It's just an idea .. not sure if this will work ..

**Comment by mgsloan** [comment]
True, `stack exec ghci` does let you access packages that you've installed.  This is one thing that's rather nice about stack's approach to package DBs, which I believe that the new-build nix style cannot support.

`stack exec -- ghc-pkg list` may give you what you're looking for, as far as getting the full list.  However, stack does not write down what has been asked for explicitly via install.

Also, note that for most packages `build` is the exact same as `install`.  The only difference is if the package has an executable, `install` copies it into `~/.local/bin`.

**Comment by mgsloan** [comment]
You probably want to ignore packages from the global package DB (stuff that comes with GHC).  You can do this by running the following two commands in bash:

```
stack exec -- ghc-pkg list --package-db=$(stack path --snapshot-pkg-db)
stack exec -- ghc-pkg list --package-db=$(stack path --local-pkg-db)
```

**Comment by flip111** [comment]
thx @mgsloan next time i want to upgrade my global project i'll use that to grab the package list before i update the resolver

```
stack exec -- ghc-pkg list --package-db=$(stack path --local-pkg-db) | tail -n+2 | head -n-1 | sed -E -e 's/\s*([a-z-]+)-.*/\1/' | tr '\n' ' '
```
