### ISSUE TITLE
More beautiful output during build

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#190]
Imagine if we had an output screen that looked something like:

```
Packages remaining: 32

text-1.2.0.5: build
attoparsec-1.3.0: configure
...
```

That updated as each task finished. Then, when we get to the final package, we switch to standard stdout of all the output (like we do right now). Thoughts?

**Comment by qnikst** [comment]
Seems can go into this issue, currently `Progress:` is not updated if there is nothing to do, as a result, user got smth like

````
qnikst@qwork ~/path $ stack  build --system-ghc --no-install-ghc
Progress: 0/3
````

so it's not obvious if process if finished or exited too early with silent error.

**Comment by chrisdone** [comment]
@qnikst Fixed in e20f8ec. Thanks for reporting it.

@snoyberg Closing as this seems done.

**Comment by qnikst** [comment]
@chrisdone seems fix was not final, if there were jobs (but some noops) I still see:
```
cloud-haskell-0.2.1.0: install
Progress: 14/16
```
However if there were no real jobs, then it's fine. Should I write a new report?

**Comment by chrisdone** [comment]
@qnikst I improved the calculation so it only considers things actually to be installed. I believe this is correct, but @snoyberg can confirm.

**Comment by snoyberg** [comment]
This feels slightly strange. Why wouldn't we want to count the fact that a test suite is going to be run as part of the total progress? Shouldn't the change instead to be incrementing the completed step count after running a test suite?
