### ISSUE TITLE
Prefer stack installed GHC even if it's the same as the system GHC

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1901]
See e.g. the issue here: https://github.com/commercialhaskell/stack/issues/1728#issuecomment-194820115

**Comment by mgsloan** [comment]
Some discussions of why the system ghc is preferred:

https://groups.google.com/forum/#!topic/haskell-stack/-XaXiq5Wdo8
#1129
I'm not sure if I buy it, I'm leaning towards making "system ghc" usage opt-in, but this would be a breaking change...

**Comment by sjakobi** [comment]
Closing this in favor of the more decided https://github.com/commercialhaskell/stack/issues/2221.
