### ISSUE TITLE
Stack (1.0.4.2) doesn't work with ghc-7.10

### ISSUE THREAD

**Issue by wdanilo** [commercialhaskell/stack#1907]
Hello!
I've just updated stack to new version (I was using the 1.0 release before) and now when I'm trying to compile the project (that compiled succesfully with the older stack) I get very trange error:
```
Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-3.10.7 (x86_64) (based on resolver setting in <path>/stack-develop.yaml).
Try running "stack setup" to install the correct GHC into<homepath>/.stack/programs/x86_64-osx/
```

the stack.yaml looks like:

``` 
resolver: lts-4.1
packages:
    - ..
    - ../../../libs/some_lib

extra-deps:
    - ghc-session-0.1.2.0
    - graphviz-2999.18.0.2
    - string-qq-0.0.2
    - error-util-0.0.1.1
    - cond-0.4.1.1
    - tuple-0.3.0.2
    - OneTuple-0.2.1
    - prologue-1.0.6
    - typelevel-1.0.3
    - container-1.0
    - convert-1.0.1
    - data-construction-1.0
    - data-layer-1.0.3
    - data-repr-1.0
    - lens-utils-1.0
    - functor-utils-1.0

ghc-options:
    "*": -DFastCompilation -threaded -funbox-strict-fields -O

local-bin-path: ./dist/bin
```

As I understand correctly, the `lts-4.1` should work well with my ghc, shouldn't it?

**Comment by wdanilo** [comment]
Ok, I see it is related to another bug here (https://github.com/commercialhaskell/stack/issues/1903) and installing stack from homebrew solved the issue. Still installing it via cabal breaks the reasoning about versions down.

**Comment by mgsloan** [comment]
Apparently this is due to a bug in vector-binary-instances: https://github.com/bos/vector-binary-instances/issues/6
