### ISSUE TITLE
Use a pretty-printer and polish formatting of output

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1912]
I think it'd be a good idea to start using a pretty printer! [ansi-wl-pprint](https://hackage.haskell.org/package/ansi-wl-pprint-0.6.7.3/docs/Text-PrettyPrint-ANSI-Leijen.html) fits the task quite nicely.

Bonus points would be to use [annotated-wl-pprint](https://hackage.haskell.org/package/annotated-wl-pprint-0.7.0/docs/Text-PrettyPrint-Annotated-Leijen.html), and use the annotations to do the same thing that `ansi-wl-pprint` can do with coloring text and such.  (I imagine those annotations would also make a good addition to that libary)

I'm imagining having some utility functions that allow you to do `$logPretty`, `$logPrettyError`, or `$logPrettyWarn`.  When used, these would have the type `(MonadLogger m, HasPrettyOptions env, MonadReader env m) => Doc -> m ()`.  In other words, we need to be able to log the output and have pretty options to pass to the pretty printer.  These changes would mostly happen in `Stack.Types.StackT`.

**Comment by luigy** [comment]
Wut?! No reactions :disappointed: 

I'm pumped for this!
--

Unless the point got a bit blurred out without screenshots; I feel a bit lonely in haskellandia

**Comment by mgsloan** [comment]
I imagine that the lack of responses is more representative of there not being more info to add / not wanting to paint the bikeshed.  In other words, people may be tacitly excited.  Feel free to implement! :D

**Comment by mgsloan** [comment]
I've implemented this!

Check it out: https://github.com/commercialhaskell/stack/pull/2236
