### ISSUE TITLE
Benchmarks are executed in parallel with other tasks

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1913]
This probably isn't what we want, as it can affect benchmark results!

**Comment by rrnewton** [comment]
Yes, this makes the benchmark results by default corrupt!

**Comment by mgsloan** [comment]
Agreed, bumping to P1

**Comment by mgsloan** [comment]
Hah, upon looking into this I found that the logic is already there to run tests and benchmarks sequentially: https://github.com/commercialhaskell/stack/blob/d63395e0db3cb5de814859877d36fd36d94d839b/src/Control/Concurrent/Execute.hs#L111
