### ISSUE TITLE
Installation Instructions Keyserver

### ISSUE THREAD

**Issue by mpdehnel** [commercialhaskell/stack#1914]
Hi,

The installation instructions state that you need to run the following command:
`sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 575159689BEFB442`

This is fine if your firewall doesn't block it, but this isn't the case for many people (port 11371 is often blocked). The workaround for this is to use the following key server instead:

`sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442`

If you could update the installation instructions to reflect this option, I'm sure it will save a lot of people a load of work!

Thanks,

Martin Dehnel-Wild

**Comment by mgsloan** [comment]
Good idea!  Feel free to open such a PR changing the docs in the repo!
