### ISSUE TITLE
Prevent stack from recompiling external dependencies

### ISSUE THREAD

**Issue by callmeyesh** [commercialhaskell/stack#1915]
I am relatively new to stack and I wasn't able to figure out if this feature already exists. Before I explain my question, let me explain our development setup. We use **jenkins** to build our repo. The haskell project will be a small subset of a larger python project. The haskell project is mainly used to generate artifacts. 

The jenkins master does a `git clean` each time before building a git branch. My haskell project has some external dependency like `argparser` & `aeson`. Each time my build scripts execute a `stack build`, these external dependencies get compiled because they are deleted when jenkins executes the git clean command. 

Is there anyway to tell stack to download the external deps to a global folder outside the project folder? Like the `global-pkg-db` path instead of the `.stack-work` folder? What is the best way to prevent stack from recompile the external dependencies? 

This is my stack.yaml file:

    # This file was automatically generated by stack init
    # For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration/
    
    # Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
    resolver: lts-5.8
    
    # Local packages, usually specified by relative directory name
    packages:
    - '.'
    # Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
    extra-deps:
    - aeson-0.11.1.1
    - argparser-0.3.4
    - text-1.2.2.0
    
    # Override default flag values for local packages and extra-deps
    flags: {}
    
    # Extra package databases containing global packages
    extra-package-dbs: []

**Comment by mgsloan** [comment]
By having extra-deps versions of `aeson` and `text`, anything that depends on them (many packages) will be built and compiled to your local project directory.  This may be resolved by https://github.com/commercialhaskell/stack/issues/1265, which will hopefully happen soon.

**Comment by callmeyesh** [comment]
Awesome, that will improve the compilation time. Is there anyway to specify the location where the extra-deps will get compiled?

**Comment by mgsloan** [comment]
You can change the work-dir location, but due to the intersection of various issues, it isn't as flexible as we'd like: https://github.com/commercialhaskell/stack/issues/1731

Once extra-deps are compiled to something like a snapshot, those dependencies will be outside of your project dir.
