### ISSUE TITLE
list-dependencies also includes test dependencies

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/stack#1919]
Would be nice if `list-dependencies` also shows test dependencies. For example with test flag.

**Comment by mgsloan** [comment]
Good point!  Really, it should take a subset of build options (things that affect targets and flags)

**Comment by rikvdkleij** [comment]
@mgsloan 
I would be very pleased if you could take a look to this issue.

**Comment by mgsloan** [comment]
@rikvdkleij Thanks for the ping!

It turned out to not be too much trouble to add support for `TARGET` syntax, `--test`, `--bench`, and `--flag` to both `stack dot` and `stack list-dependencies`

**Comment by rikvdkleij** [comment]
@mgsloan 
Thanks!! Solution looks fine to me. I will try to build Stack from master so I can test it.

**Comment by rikvdkleij** [comment]
Yes, it works!! :+1:

**Comment by rikvdkleij** [comment]
Btw, https://github.com/commercialhaskell/stack/issues/2603 is also fixed!
