### ISSUE TITLE
Upper bound for hpack on Hackage

### ISSUE THREAD

**Issue by sol** [commercialhaskell/stack#1921]
I just noticed that the dependency `hpack` has an upper bound on Hackage (`hpack >=0.9.0 && <0.10`) for `stack-1.0.4.2`.  I don't see that reflected on GitHub (https://github.com/commercialhaskell/stack/blob/v1.0.4.2/stack.cabal#L210), nor is there a corresponding edit to the cabal file on Hackage.

Does anybody know where this upper bound comes from?

**Comment by borsboom** [comment]
We upload to Hackage using 'stack upload --pvp-bounds=both', which adds
upper bounds if missing from the original cabal file.

**Comment by DanBurton** [comment]
Just throwing the relevant stackage notification onto this ticket:

hpack-0.11.2 depended on by:
- [ ] stack-1.0.4.2 (>=0.9.0 && < 0.10). Emanuel Borsboom <manny@fpcomplete.com> @borsboom. @commercialhaskell

**Comment by borsboom** [comment]
I've updated the hackage metadata to allow hpack >= 0.9.0 && < 0.12 for stack-1.0.4.2 (after running the tests).

**Comment by sol** [comment]
@borsboom Thanks :)
