### ISSUE TITLE
`stack new` requires `.cabal` file even if `package.yaml` is present

### ISSUE THREAD

**Issue by tfausak** [commercialhaskell/stack#1926]
If you make a Stack template that does not include a `.cabal` file, `stack new` will refuse to use it. In general this makes sense, but not when `package.yaml` is present. If there is a `package.yaml`, I would expect `stack new` to use it to generate the `.cabal` file.

This is the error that I get:

> The template "..." is invalid and could not be used. The error was: "Template does not contain a .cabal file"

I ran into this problem while working on https://github.com/commercialhaskell/stack-templates/pull/45. It's easy to work around: Just provide a barebones `.cabal` file with the `name` and `version` set.

**Comment by harendra-kumar** [comment]
Makes sense. `package.yaml` support needs to be added to templates too.

**Comment by mgsloan** [comment]
This is already supported in HEAD - https://github.com/commercialhaskell/stack/issues/1927

**Comment by silky** [comment]
i guess you actually meant this pr - https://github.com/commercialhaskell/stack/pull/1822 - not 1927 :)

**Comment by mgsloan** [comment]
Oh, yeah! Dunno how that happened, heh
