### ISSUE TITLE
Fix `--file-watch` / `hspec` interaction

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1928]
Using Hspec's very handy `--rerun` functionality doesn't work with `--file-watch`, I get this after a failed test and a file save:

```
Progress: 1/2WARNING: Could not read environment variable HSPEC_FAILURES; `--rerun' is ignored!
```

The command I'm using is:

`STACK_YAML="../stack.yaml" stack build --test --test-arguments '--rerun' --file-watch --fast $(PROJECT) 2>&1`

Did I get something wrong?

**Comment by mgsloan** [comment]
It seems like hspec is expecting environment variables to be preserved between invocations?

It uses `setEnv` [here](https://github.com/hspec/hspec/blob/bd06049cc954fc20a481c962dffe0caae73bdde3/hspec-core/src/Test/Hspec/FailureReport.hs#L36), but it seems to me like that would only work if you ran hspec in ghci and didn't reload.  In other words, `setEnv` only affects the current process, not the parent process.

```
Prelude System.Posix.Env> setEnv "TEST" "hullo" True
Prelude System.Posix.Env> :q
Leaving GHCi.
mgsloan@computer:~$ echo $TEST

mgsloan@computer:~$
```

**Comment by luigy** [comment]
Unless the help output is outdated, it looks like that is the expected behavior outside of `ghci`
```sh
$ spec --help
...
 -r            --rerun             rerun all examples that failed in the
                                    previously test run (only works in GHCi)
...
```

I'm gonna plug `ghcid` once more because it is so awesome :stuck_out_tongue: 
here is a [clip](https://cldup.com/_-eR3itPtI.mp4) of it in action for the interaction in this issue

**Comment by mwotton** [comment]
for ease of copypasta:

```
ghcid --command='stack exec ghci --test -- -isrc -itest test/Spec.hs'  --test $':main --rerun --color'
```

**Comment by mwotton** [comment]
so, i ended up writing this little thing, if anyone's interested.
https://github.com/mwotton/hspec-stack-rerun

**Comment by soenkehahn** [comment]
I can confirm that the `--rerun` feature is only meant to work in `ghci`.

@bitemyapp: Can this be closed then?

**Comment by sol** [comment]
Yes, this is only meant to work in `ghci`.

Running tests outside of `ghci` is slow. If you care about productivity, then you really want to fix that first (e.g. use [hspec/sensei](https://github.com/hspec/sensei))!

@mgsloan it works in `ghci`, even if you use `:reload`.
