### ISSUE TITLE
CSRF rejections should be logged by default

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1929]
I've made a custom CSRF middleware privately that logs that a request was rejected. This is needed because the user will never see any of the log output from their handler and the body seems to be empty when this happens.

I could respin this with a parameterization that takes a logLevel and then update the scaffolds if people are open to this.

**Comment by mgsloan** [comment]
I'm guessing this was supposed to go to the yesod repo?

**Comment by bitemyapp** [comment]
Sigh, yes. Sorry :(

**Comment by mgsloan** [comment]
No worries!
