### ISSUE TITLE
stack test: binary file not created with explicit module name

### ISSUE THREAD

**Issue by Javran** [commercialhaskell/stack#1930]
stack version is `Version 1.0.4.2 x86_64`

to reproduce:

```shell
$ stack new prj new-template
$ cd prj/test
```
then edit `Spec.hs`:

```haskell
module Spec where
main :: IO ()
main = putStrLn "Test suite not yet implemented"
```

then `stack test` will report:
```
Test suite failure for package prj-0.1.0.0
    prj-test:  executable not found
Logs printed to console
```

**Comment by mgsloan** [comment]
This is just how GHC works.  If you want to put your main function in a different file, pass `-main-is Spec.main`

**Comment by mgsloan** [comment]
This is a legitimately stupid thing, though.  GHC < 8 emits a warning for this case when it really should emit an error.  In particular, it can cause you to accidentally use old executables. https://github.com/commercialhaskell/stack/issues/1846

**Comment by Javran** [comment]
@mgsloan since in `new-template`, test suite has already specified `main-is: Spec.hs` so I expect it to link the binary.

A little off topic, but I'm getting confused here because GHC's `-main-is` somewhat inconsistent with that of cabal's:

GHC's `-main-is` accepts an identifier or a module name:
https://downloads.haskell.org/~ghc/7.8.4/docs/html/users_guide/options-phases.html

while you need to give cabal's "main-is" a path:
https://www.haskell.org/cabal/proposal/x611.html

so to give `Spec.hs` an explicit module name other than `Main`, you end up having:

```cabal
test-suite prj-test
  type:                exitcode-stdio-1.0
  hs-source-dirs:      test
  main-is:             Spec.hs
  build-depends:       base
                     , prj
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N -main-is Spec.main
  default-language:    Haskell2010
```

**Comment by mgsloan** [comment]
Yes, cabal's `main-is` doesn't allow you to specify a different module name, it must be a module that has the name `Main` (either lacking a module header or having an explicit `module Main`.  Gross, I know.  Main modules are much wackier than they should be.
