### ISSUE TITLE
stack setup: not able to install ghc

### ISSUE THREAD

**Issue by thalesrodolfo** [commercialhaskell/stack#1932]
Hi,

I'm trying to install ghc with stack but I'm getting the following error:
![captura de tela de 2016-03-19 09-41-26](https://cloud.githubusercontent.com/assets/10382097/13898669/54cb6552-edb7-11e5-8c24-7efe660f9ce2.png)

I'm new to haskell, so I hope you guys can help me.

** I'm using solus OS [https://solus-project.com/](url)

Thank you!

**Comment by mgsloan** [comment]
I suggest installing ghc manually for now.  It is unfortunate that ghc's Makefile requires a working C compiler, I doubt the install process requires it

**Comment by cblp** [comment]
I suggest installing *gcc* instead.

**Comment by mgsloan** [comment]
@cblp Hahah very true.

Closing this out since it's an old support thread
