### ISSUE TITLE
APT repository signature warning

### ISSUE THREAD

**Issue by Xaositect** [commercialhaskell/stack#1934]
Starting from version 1.2.7, Debian package management tool APT issues warnings about signatures using SHA1 digest:
> W: gpgv:/var/lib/apt/lists/download.fpcomplete.com_debian_dists_jessie_Release.gpg: The repository is insufficiently signed by key C5705533DA4F78D8664B5DC0575159689BEFB442 (weak digest)

Signatures using SHA1 will not be trusted in the next releases of Debian and Ubuntu (see https://juliank.wordpress.com/2016/03/14/dropping-sha-1-support-in-apt/). Please use a more secure digest algorithm.

**Comment by mgsloan** [comment]
Pinging @borsboom

**Comment by borsboom** [comment]
I've added `--gpg-options=--digest-algo=sha512` arguments to to the deb-s3 command, so future releases should use a SHA512 digest.

**Comment by borsboom** [comment]
v1.0.4.3's release has used the SHA512 digests.
