### ISSUE TITLE
brew install haskell-stack fails

### ISSUE THREAD

**Issue by pkamenarsky** [commercialhaskell/stack#1935]
$ brew install haskell-stack
    Warning: You are using OS X 10.8.
    We (and Apple) do not provide support for this old version.
    You may encounter build failures or other breakages.
    ==> Installing dependencies for haskell-stack: xz, ghc, cabal-install
    ==> Installing haskell-stack dependency: xz
    dyld: DYLD_ environment variables being ignored because main executable (/usr/bin/sudo) is setuid or setgid
    ==> Downloading https://fossies.org/linux/misc/xz-5.2.2.tar.gz
    ################################################################          89.0%
    ==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/xz/5.2.2
    ==> make install
    🍺  /usr/local/Cellar/xz/5.2.2: 59 files, 1.4M, built in 29 seconds
    ==> Installing haskell-stack dependency: ghc
    dyld: DYLD_ environment variables being ignored because main executable (/usr/bin/sudo) is setuid or setgid
    ==> Downloading https://downloads.haskell.org/~ghc/7.10.3/ghc-7.10.3b-src.tar.bz2
    ####################################################################      95.7%
    ==> Downloading http://ftpmirror.gnu.org/gmp/gmp-6.1.0.tar.bz2
    ==> Downloading from http://gd.tuwien.ac.at/gnu/gnusrc/gmp/gmp-6.1.0.tar.bz2
    ####################################################                      72.3%
    ==> ./configure --prefix=/usr/local/Cellar/ghc/7.10.3b/libexec/integer-gmp --with-pic --disable-shared
    ==> make
    ==> make check
    ==> make install
    ==> Downloading https://downloads.haskell.org/~ghc/7.10.3/ghc-7.10.3-x86_64-apple-darwin.tar.xz
    #######################################################################   99.7%
    ==> ./configure --prefix=/private/tmp/ghc20160321-24599-17miv71/ghc-7.10.3/binary --with-gmp-includes=/usr/local/Cellar/ghc/7.10.3b/libexec/integer-gmp/includ
    ==> make install
    ==> ./configure --prefix=/usr/local/Cellar/ghc/7.10.3b --with-gmp-includes=/usr/local/Cellar/ghc/7.10.3b/libexec/integer-gmp/include --with-gmp-libraries=/usr
    ==> make
    Last 15 lines from /Users/phil/Library/Logs/Homebrew/ghc/08.make:
    libraries/binary/src/Data/Binary/Get.hs:424:1: Warning:
        Rule "getWord64le/readN" may never fire
          because ‘getWord64le’ might inline first
        Probable fix: add an INLINE[n] or NOINLINE[n] pragma on ‘getWord64le’
    [ 7 of 90] Compiling Data.Binary.Put  ( libraries/binary/src/Data/Binary/Put.hs, bootstrapping/Data/Binary/Put.o )

    libraries/binary/src/Data/Binary/Put.hs:3:14: Warning:
        ‘Data.Binary.Put’ is marked as Trustworthy but has been inferred as safe!
    [ 8 of 90] Compiling Data.Binary.Class ( libraries/binary/src/Data/Binary/Class.hs, bootstrapping/Data/Binary/Class.o )

    libraries/binary/src/Data/Binary/Class.hs:447:14:
        The last statement in a 'do' block must be an expression
          n <- get :: Get Int getMany n
    make[1]: *** [utils/ghc-cabal/dist/build/tmp/ghc-cabal] Error 1
    make: *** [all] Error 2

**Comment by borsboom** [comment]
This looks like the failure is when Homebrew is installing `ghc`, long before it starts trying to build `haskell-stack`.  I'd say that makes it a Homebrew issue rather than a Stack issue.  What happens when you run `brew install ghc`?

You might try installing the "bottle" instead of building from source, or just [download the binary](https://www.stackage.org/stack/osx-x86_64).
