### ISSUE TITLE
Allow installing from vc and archive urls

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1941]
I'd prefer to make this opt-in, to avoid security issues, and to reduce the amount of aliasing in the TARGET syntax.  Something like `stack install --download https://github.com/ndmitchell/hoogle/archive/master.zip`.

Usecase that made me consider this is installing HEAD version of hoogle - https://github.com/commercialhaskell/stack/pull/1939

**Comment by luigy** [comment]
looks like it includes #1278

**Comment by mgsloan** [comment]
Good point!  Infact, I'd say this is a dupe :D
