### ISSUE TITLE
Caching / avoiding rebuilding dependencies specific to .stack-work

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#1942]
![screenshot from 2016-03-22 20-38-48](https://cloud.githubusercontent.com/assets/320177/13973193/2b66952e-f06e-11e5-9668-e2b08fd6c68d.png)

Our CI server keeps rebuilding these every time we run the tests. I'm trying to prebuild the dependencies but that doesn't seem to work. I believe they're partly a result of our extra-deps in the `stack.yaml`:

```yaml
extra-deps:
- gravatar-0.8.0
- hashids-1.0.2.2
- uuid-aeson-0.1.0.0
- monad-logger-0.3.18
```

I remember there being a ticket about this before, but I couldn't find it via Github or Google search. Is there anything we can do?

**Comment by mgsloan** [comment]
You could cache your root .stack-work directory

This will also be resolved by https://github.com/commercialhaskell/stack/issues/1265
