### ISSUE TITLE
Getting error decoding stream of UTF-8 bytes

### ISSUE THREAD

**Issue by alcidesv** [commercialhaskell/stack#1945]
When building a rather large project I get the following:

    2016-03-23 22:02:31.576489: [debug] Run process: C:\Users\alcides\AppData\Roaming\stack\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1f3 build lib:shimmer-cat exe:shimmercat --ghc-options " -ddump-hi -ddump-to-file" @(stack_7LDm9brrZDRGPali8XJ7ve:System.Process.Read src/System\Process\Read.hs:287:3)
    Data.Conduit.Text.decode: Error decoding stream of UTF-8 bytes. Error encountered in stream at offset 101048. Encountered at byte sequence "\229r i"

This is happening on Windows. I know that this bug report is not particularly helpful because I can not give a minimal example. I wouldn't know where to start. In fact, stack in Windows compiles fines both a very basic project and a ton of libraries. 

I will try to find what the problem is tomorrow. But if anybody can provide some guidance that would help a lot.

**Comment by mgsloan** [comment]
See https://github.com/commercialhaskell/stack/issues/793 for some suggestions of things to try for this.  Could be that GHC is confused about the locale.

However, I don't think it makes sense for us to do a strict UTF8 decode here.  I've pushed a commit that switches it to a lenient decode.  Can you please confirm that this resolves the issue (re-open if not).  Use `stack upgrade --git` to use the latest development version.

**Comment by alcidesv** [comment]
Thanks you very much! I can confirm that this commit fixes the issue. For the record, my Windows is in Swedish, and setting the LANG environment variable  to en_US.UTF-8 didn't help before this commit.
