### ISSUE TITLE
cannot import libraries on ghci

### ISSUE THREAD

**Issue by rwobben** [commercialhaskell/stack#1956]
Hello, 

IWhen I do : 

stack ghci 
- :l:  Spec,hs 

I see this error message : 

Spec.hs:3:8:
    Could not find module ‘Test.QuickCheck’
    It is a member of the hidden package ‘QuickCheck-2.8.1@Quick_8UnGnTXfSEEClQczG6tI7s’.
    Use -v to see a list of the files searched for.

but quickCheck is already in the .cabal file.

See the code here : https://github.com/rwobben/haskellbook/tree/master/chapter_14/qcExercises

**Comment by silky** [comment]
you need to run `stack ghci --test` to load the test dependencies

**Comment by rwobben** [comment]
Thanks, now it worked and found my bug
