### ISSUE TITLE
Pretty print cabal solver messages

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1958]
It will be cheaper to fix the solver error messages than entertaining support requests/issues/emails, diagnosing problems and telling users what is wrong with their config.

This message:

```
>>>> Cabal errors begin
cabal: Could not resolve dependencies:
trying: hspec-snap-0.4.0.1 (user goal)
next goal: snap-core (user goal)
rejecting: snap-core-1.0.0.0 (conflict: hspec-snap => snap-core>=0.9 && <0.10)
rejecting: snap-core-0.9.8.0, 0.9.7.2, 0.9.7.0, 0.9.6.4, 0.9.6.3, 0.9.6.2,
0.9.6.1, 0.9.6.0, 0.9.5.0, 0.9.4.1, 0.9.4.0, 0.9.3.1, 0.9.3, 0.9.2.2, 0.9.2.1,
0.9.2, 0.9.0, 0.8.1, 0.8.0.1, 0.8.0, 0.7.0.1, 0.7, 0.6.0.1, 0.6.0, 0.5.5,
0.5.4, 0.5.3.1, 0.5.3, 0.5.2, 0.5.1.4, 0.5.1.3, 0.5.1.2, 0.5.1.1, 0.5.1,
0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0.2, 0.4.0.1, 0.4.0, 0.3.1.1, 0.3.1, 0.3.0,
0.2.16, 0.2.15.1, 0.2.15, 0.2.14, 0.2.13, 0.2.12, 0.2.11, 0.2.10, 0.2.9,
0.2.8.1, 0.2.8, 0.2.7.1, 0.2.7, 0.2.6, 0.2.5, 0.2.4, 0.2.3, 0.2.2, 0.2.1,
0.1.2, 0.1.1 (global constraint requires ==1.0.0.0)
Dependency tree exhaustively searched.
<<<< Cabal errors end
```

can be parsed and printed something to the effect of:

```
Package hspec-snap-0.4.0.1 requires snap-core >= 0.9 && < 0.10 but snap-core-1.0.0.0 provided.
Please fix your packages' version constraints and try again.
```

More details on how to do it follow.

Classification:

We classify the packages involved in a error message in the following buckets:
1. User packages
2. Snapshot packages or extra-deps as specified by the user in the config file
3. External packages - these will be suggested by the solver as extra-deps to be added

We know the list of user, snapshot and extra-deps so we can identify those. Everything else should be labeled as an external package. 

Note that the  `global constraints` as described by the cabal solver will always be either user packages, snapshot packages or extra-deps already specified (i.e. anything except external packages). 

Suggesting a resolution:

Conflicting packages can be extracted from a 'rejecting:' message in the cabal output which has a 'conflict' clause in it. Each conflicting package is classified in one of the above categories. 

The resolution of the problem depends on the type of conflict and we can provide an appropriate action based on that:
- user-user package conflict - user has to fix his packages' version bounds
- user-snapshot/extra-deps - fix the snapshot/extra-deps versions being used or fix the package to match the snapshot versions
- snapshot-extra deps or extra-deps-extra-deps - Download and fix the packages yourself before using or contact the maintainers of the packages involved in the conflict.

**Comment by mgsloan** [comment]
This would be awesome indeed, good idea!

**Comment by snoyberg** [comment]
Solver is removed, closing
