### ISSUE TITLE
Make "stack image container" documentation for discoverable

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#1959]
While adding a comment [here](https://www.reddit.com/r/haskell/comments/4c3qgc/haskell_builds_at_thoughtbot_video/), I noticed that the docker page doesn't really mention `stack image container`.  The existing docs aren't bad, but it'd be good to have a mention on that page.

Existing docs:

http://docs.haskellstack.org/en/stable/yaml_configuration/#image
http://docs.haskellstack.org/en/stable/GUIDE/#docker

**Comment by robinp** [comment]
For reference, see also tutorials http://www.yesodweb.com/blog/2015/12/yesod-hosting-docker-kubernetes and http://mdjnewman.me/2016/01/haskell-stack-yesod-docker/ .

**Comment by arianvp** [comment]
This feature isn't documented at all anymore. It isn't mentioned in the yaml configuration docs. (The links above are dead). Is that on purpose?

**Comment by qrilka** [comment]
This command was removed in #4620 and there is a changelog entry telling about this fact.
@snoyberg I suppose it's time to close this ticket?

**Comment by arianvp** [comment]
I see. then lets close this :)
