### ISSUE TITLE
"stack test <pkg>" does not run tests?

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#1961]
Running `stack test <pkg>` does not seem to run the testsuite of `<pkg>` unlike running `stack test` in the unpacked `<pkg>` directory.  Is this expected behaviour?  It would be nice sometimes to be able to run the testsuites of a package directly.

**Comment by mgsloan** [comment]
This is expected behavior - we never run tests or benchmarks for snapshot deps.  However, when they are explicitly listed as a target, it does seem surprising that the tests don't get run.  I'm in favor of a change of behavior here.
