### ISSUE TITLE
Stack init fails after the 'fetching package index' step

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#1962]
I am seeing this type of message quite often now, during stack init. It fails the first time but succeeds the next time. I have not checked what's going on, just putting it down as an issue for tracking.

```
Downloaded nightly-2016-03-29 build plan.    
Caching build plan
Fetched package index.                                                                                    
The following package identifiers were not found in your indices: avers-0.0.15, avers-api-0.0.4, avers-server-0.0.3, codex-0.4.0.10, hsdev-0.1.7.2, machines-io-0.2.0.10, semiring-simple-1.0.0.1, stylish-haskell-0.5.16.0, texmath-0.8.6, th-expand-syns-0.4.0.0, webkitgtk3-javascriptcore-0.13.1.2, yesod-1.4.2.1, yesod-bin-1.4.18, yesod-table-2.0.3, yesod-test-1.5.1.0
```

**Comment by mgsloan** [comment]
Thanks for reporting!  I've seen this too and tried to figure out what's going wrong.  Current theory is that I introduced a regression in https://github.com/commercialhaskell/stack/commit/7132c34698bafa6cf3a880e742157ac6c6f98943

**Comment by borsboom** [comment]
I'm pretty sure you're right about where the regression was introduced, because this started happening on Jenkins soon afterward.

**Comment by mgsloan** [comment]
Pretty sure I've fixed it.  In some cases, it was updating the indices without clearing the in-memory cache.  It's tricky to test, because you need to have an out of date hackage index cache, so time will tell if this is the correct fix.

**Comment by mgsloan** [comment]
Yup, confirmed the fix by adding a dep on  https://hackage.haskell.org/package/acme-left-pad-1.0
