### ISSUE TITLE
Undefined Refrences when building. 

### ISSUE THREAD

**Issue by mckeankylej** [commercialhaskell/stack#1964]
Project: https://github.com/mckeankylej/laura
Steps to reproduce:

1. Clone the project
2. sudo stack build

Expected: 
I expected the project to build succesfully

Actual 
http://lpaste.net/157564

**Comment by mckeankylej** [comment]
Turns out I needed to reference a file in my .cabal, this is a terrrible uninformative error.

**Comment by mgsloan** [comment]
I agree that the error is non-ideal.  Unfortunately, we don't control the messaging, it comes from `ld` which is invoked by `Cabal`..  However, we should be able to do something better by either analyzing ddump files or analyzing compilation output.  I've noted down in my TODO list to get around to opening an issue on the subject.
