### ISSUE TITLE
Building a container image drops a .stack-work dir in the current working (sub)directory

### ISSUE THREAD

**Issue by dysinger** [commercialhaskell/stack#1975]
I built an image with stack image container in a subdir and I see a left-over cruft directory left behind in the sub-directory.

~~~
% find .stack-work 
.stack-work
.stack-work/image
.stack-work/image/0
.stack-work/image/0/usr
.stack-work/image/0/usr/local
.stack-work/image/0/usr/local/bin
.stack-work/image/0/usr/local/bin/xyz
.stack-work/image/0/Dockerfile
~~~

**Comment by dysinger** [comment]
I built an image with `stack image container` in a subdir and I see a left-over cruft directory left behind in the sub-directory.

% find .stack-work 
.stack-work
.stack-work/image
.stack-work/image/0
.stack-work/image/0/usr
.stack-work/image/0/usr/local
.stack-work/image/0/usr/local/bin
.stack-work/image/0/usr/local/bin/xyz
.stack-work/image/0/Dockerfile

**Comment by mgsloan** [comment]
Hmm, yeah, that should probably go in the `.stack-work` at the project root (next to stack.yaml)
