### ISSUE TITLE
`stack test` and unpacked `packages`.

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#1978]
Assume we have a package `X`, which we need to slightly modify, hence we use `stack unpack`, to get a local copy, and make the modifications, and add it to the `packages:` section in the `stack.yaml` file.

Now running `stack test`, will try to run the tests in the unpacked package as well, which might be undesirable. How would one prevent `stack test` to run those tests?

**Comment by ghorn** [comment]
I think adding `extra-dep: true` will solve this for you

**Comment by angerman** [comment]
@ghorn thanks. That did fix it indeed!

This raises another question:

should `stack unpack`, add
`
- location: ...
  extra-dep: true
`
to the `packages:` section?

**Comment by harendra-kumar** [comment]
Not sure what you mean by stack unpack modifying the packages section. stack unpack just unpacks a package into a directory. It doesn't do anything more than that. It does not modify your stack.yaml, since it has no knowledge of where or in which context you are unpacking the package.

Though `stack init` does create a stack.yaml for you and therefore can take dependencies into account. See #1968 for a relevant issue.

**Comment by angerman** [comment]
Fair enough. Maybe I'm using it wrong then. I usually use `unpack`, if I need to make local modifications to a package to suite my needs (and later turn those into a proper PR for the package).
Hence the workflow is `stack unpack XYZ`, edit the `stack.yaml` and extend the `packages: ` section. Thus, if `stack` could do that for me automatically, that would be great. Am I making any sense?

**Comment by harendra-kumar** [comment]
Yeah, it definitely makes sense. We need something for "I want to pull a package from an index and add it as a local dependency package to my project". I think I thought about this before. I am imagining a `stack add`  sort of command which:
* adds a new package to an existing project
* solves the dependencies for the whole project with the new package
* adds any extra dependencies if needed just like stack init/solver
* keeps all other stack.yaml settings intact

Now we can add a `--dep` option to this new command which will solve your workflow. I guess we have all the pieces in stack init/solver to do this, just a little bit of glue work is needed. 

With that your workflow will be `stack unpack X; stack add --dep X`. You have the motivation, would you have time for doing that :-)

**Comment by mgsloan** [comment]
Yep, this has been discussed before.  Here's a comment I wrote on the topic: https://github.com/commercialhaskell/stack/issues/1365#issuecomment-158229262

**Comment by harendra-kumar** [comment]
Ok we are tracking this via the other issue now.
