### ISSUE TITLE
Short alias for '--verbosity silent'

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#1981]
When running `stack test`, I'm often only interested in the test result, and not necessarily in the compilation and other notifications.

Example:
```
x-0.1.0.0: unregistering (local file changes: src/Lib.hs)
x-0.1.0.0: build (lib + exe + test)
Preprocessing library x-0.1.0.0...
[2 of 2] Compiling Lib              ( src/Lib.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/Lib.o )

/path/to/x/src/Lib.hs:8:1: Warning:
    The qualified import of ‘Z.Y’ is redundant
      except perhaps to import instances from ‘Z.Y’
    To import instances alone, use: import Z.Y()

/path/to/x/src/Lib.hs:41:1: Warning: Defined but not used: ‘someFunc’

/path/to/x/src/Lib.hs:61:1: Warning: Defined but not used: ‘otherFunc’
In-place registering x-0.1.0.0...
Preprocessing executable 'x' for x-0.1.0.0...
Preprocessing test suite 'x-test' for x-0.1.0.0...
x-0.1.0.0: copy/register
Installing library in
/path/to/x/.stack-work/install/x86_64-osx/lts-5.10/7.10.3/lib/x86_64-osx-ghc-7.10.3/x-0.1.0.0-6aBYtgTxB781Cngkx5i7vH
Installing executable(s) in
/path/to/x/.stack-work/install/x86_64-osx/lts-5.10/7.10.3/bin
Registering x-0.1.0.0...
x-0.1.0.0: test (suite: x-test)
<Test / Results>
```

What I'm actually only interested in are primarily the `<Test / Results>` part, and potentially the `warnings`. Even though I might not actually care about the warnings; and only about errors that prevent compilation.

Is there a `--silent` switch I'm missing?

**Comment by sjakobi** [comment]
> Is there a --silent switch I'm missing?

Try `stack --verbosity silent test`. Is this good enough for your needs?

**Comment by angerman** [comment]
@sjakobi thanks! That's what I was looking for. Should there be an `alias` that does `--silent` as `--verbosity silent`?

**Comment by sjakobi** [comment]
> Should there be an alias that does --silent as --verbosity silent?

I guess that would be pretty handy.

But we must also take care not to clutter up the `stack --help` output too much. So creating aliases for all the verbosity options in the name of consistency probably wouldn't be a good idea or should at least wait until we have more fine-grained control of the help output.

**Comment by angerman** [comment]
I wouldn't advice to create aliases for *all* verbosity levels; yet `--silent` sticks out. At least for me.

**Comment by borsboom** [comment]
Makes sense.  A pull request would be welcome.

**Comment by angerman** [comment]
OMG. Awesome!
