### ISSUE TITLE
Comment in Stack.Fetch references comment in Stack.Build that doesn't exist

### ISSUE THREAD

**Issue by enolan** [commercialhaskell/stack#1986]
[This line](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Fetch.hs#L524) references a comment about `liftBaseWith` in Stack.Build but I can't find any instance of `liftBaseWith`, `liftWith` or `runInBase` there. Should it just be deleted?

The pattern `runInBase <- liftBaseWith $ \run -> return (void . run)` is used 7 times in Stack by my count. Personally, `MonadBaseControl` and friends make my head hurt. I'd love for there to be an explanation for the `runInBase` incantation, and/or for it to be turned into a function.

**Comment by mgsloan** [comment]
Yeah, `MonadBaseControl` is confusing.  It would be nice to turn it into a function, but stack has sofar managed to avoid creating a utils / import module.  It seems a bit much to create a new module for this one function.

This pretty much just says "I want to be able to run this monad within IO, and discard any result / monadic state".  By discarding the result, we can skip over the gnarly part of MonadBaseControl, which is handling the monadic state at the end of these inner actions.

**Comment by sjakobi** [comment]
The codebase also uses `monad-unlift` which seems to serve a similar purpose as `monad-control`. It would be nice to standardize this.

**Comment by mgsloan** [comment]
`monad-unlift` is built atop `monad-control`, and simplifies usage of it.

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and the fact that there is no `Stack.Fetch` module in the current code.
