### ISSUE TITLE
Update from 1.0 -> 1.0.4 stack build w/docker now fails to parse DockerEntrypoint

### ISSUE THREAD

**Issue by lloucas-imvu** [commercialhaskell/stack#1996]
Version 1.0.4, Git revision cf18703b1392a96a5a4896a560309e501af63260 (3220 commits) x86_64

Docker version 1.9.0, build 76d6bc9

Docker image currently in use (works with 1.0.0) https://github.com/sweeks-imvu/ghc-musl/tree/master/ghc-musl
## Output:

stack build
option --internal-docker-entrypoint: cannot parse value `DockerEntrypoint {deUser = Just (DockerUser {duUid = 1001, duGid = 1001, duGroups = [4,27,108,124,130,1001,2000], duUmask = 2})}'

Usage: stack [--help] [--version] [--numeric-version] [--docker*] [--nix*]([--verbosity VERBOSITY] | [-v|--verbose]) [--work-dir WORK-DIR]([--system-ghc] | [--no-system-ghc]) ([--install-ghc] |
             [--no-install-ghc]) [--arch ARCH] [--os OS] [--ghc-variant VARIANT]
             [-j|--jobs JOBS] [--extra-include-dirs DIR] [--extra-lib-dirs DIR]([--skip-ghc-check] | [--no-skip-ghc-check]) ([--skip-msys] |
             [--no-skip-msys]) [--local-bin-path DIR]([--modify-code-page] |
             [--no-modify-code-page]) [--resolver RESOLVER]
             [--compiler COMPILER]([--terminal] | [--no-terminal])
             [--stack-yaml STACK-YAML] COMMAND|FILE

**Comment by borsboom** [comment]
I suspect what's happening here is that the Docker image can't run the host's version of the Stack executable (because it's musl based) and so it falls back to using the version in the image which is older.  The `stack` version in the image should match the `stack` version on the host.

**Comment by mgsloan** [comment]
Sounds like this can be closed as a support ticket.
