### ISSUE TITLE
Any luck installing on the raspberry pi?

### ISSUE THREAD

**Issue by ChristopherKing42** [commercialhaskell/stack#1998]
I tried installing it on the raspberry pi with the generic linux option, but it said "error, incorrect exec format" or something like that (I can't copy and paste from it and the momenty). The debian option didn't work either.

Any tips?

**Comment by ChristopherKing42** [comment]
(I'm using [this](http://stackoverflow.com/a/36341642/1172541) right now, but direct installation would be better.)

**Comment by borsboom** [comment]
Closing this issue in favour of #2103
