### ISSUE TITLE
Listing packages available in current resolver

### ISSUE THREAD

**Issue by shanemikel** [commercialhaskell/stack#1999]
It would be nice to get an analog to `cabal list`.  I guess it would be reasonable to list what's available in the resolver for the current project.  I don't think it's necessary to print a bunch of stuff (like descriptions), though it might be nice; A simple list would suffice.

**Comment by harendra-kumar** [comment]
#1614 is an umbrella issue for list and show commands. Listing packages in a resolver/snapshot is one of them.

**Comment by mpilgrem** [comment]
Closing, as `stack list` exists.
