### ISSUE TITLE
Specify intra-package target (like 'cabal build COMPONENTS')

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#201]
This may fit in with the talk of building test suites somewhat independently of a project itself.

Suggest keeping `stack build TARGET` syntax, just making TARGET more flexible — So I can do any of

    stack build .              # everything
    stack build Snowdrift      # Snowdrift package
    stack build exe:Snowdrift  # Snowdrift component

May be slightly ambiguous, but I doubt that would be a problem very often.

**Comment by snoyberg** [comment]
@chreekat This is now implemented. This does require prefixing the component name with the package name (doing otherwise would have led to ambiguities with the current syntax). This, for example, works:

    stack build stack:lib:stack

Can you try it out?

**Comment by chreekat** [comment]
Looks good

**Comment by snoyberg** [comment]
FYI, with the latest stack, running `stack build :Snowdrift` will build the component named Snowdrift, wherever it's defined in a local package.

**Comment by chreekat** [comment]
Great!

**Comment by RasmusWL** [comment]
For reference I will point to [#1406 (stack 0.1.8 lost ability to build individual executables or library) ](#1406) so other people will realise faster that they are not idiots, and that this feature is just not working right now.
