### ISSUE TITLE
`stack clean --full` tries to delete .stack-work/docker/_home which is mounted on docker enabled projects

### ISSUE THREAD

**Issue by dysinger** [commercialhaskell/stack#2010]
Create a docker enabled project (builds the project in a docker container)

run `stack clean --full` and you'll see it break with an error

**Comment by dysinger** [comment]
FYI: .stack-work/docker/_home is the $HOME directory of the `stack` user inside the container.  We can't delete that because when you are inside the container this directory is mounted and in use. 

The solution would be to do the `stack clean --full` outside of the docker container (not inside).

**Comment by angerman** [comment]
Ran into this as well:
```
$ stack --docker --docker-image img clean --full
~/p/s/cd/.stack-work/docker/_home: removeDirectoryRecursive: resource busy (Device or resource busy)
```

**Comment by mgsloan** [comment]
Fixed!
