### ISSUE TITLE
Stack templates can't declare extra-deps

### ISSUE THREAD

**Issue by jsteiner** [commercialhaskell/stack#2014]
We're trying to write a stack template that depends on packages that aren't in Stackage. Thus, we want to supply our own `stack.yaml`. Unfortunately, when using `stack new` with the template, it ignores our supplied `stack.yaml` and fails because the LTS doesn't have all the packages to match our requirements. I should note that we are using `--force`, so the `stack.yaml` is being written, but isn't being used for the initialize step.
## Expected:

`stack new` uses the supplied `stack.yaml`, including `extra-deps` in the initialize step.
## Actual:

`stack new` fails because the `lts-5.11` does not have all the package to match our requirements.
## Stack version

```
$ stack --version
Version 1.0.4 x86_64
```

**Comment by mgsloan** [comment]
`stack new --solver` should do the trick.

Also related to https://github.com/commercialhaskell/stack/issues/1390

**Comment by snoyberg** [comment]
In newer Stack versions, if a `stack.yaml` is declared in the template then it is used.
