### ISSUE TITLE
"libutil.so.8" not found on FreeBSD 10.3

### ISSUE THREAD

**Issue by Cipherwraith** [commercialhaskell/stack#2019]
I ran this command to init stack using a cabal file, and it ran fine until the GHC installation.
`# stack init --solver --install-ghc`

    Preparing to install GHC to an isolated location.
    This will not interfere with any system-level installation.
    Downloaded ghc-7.8.4.
    Running /tmp/stack-setup3684/ghc-7.8.4/configure --prefix=/root/.stack/programs/x86_64-freebsd/ghc-7.8.4/ in directory /tmp/stack-setup3684/ghc-7.8.4/ exited with ExitFailure 1

    checking for path to top of build tree...
    Shared object "libutil.so.8" not found, required by "ghc-pwd"
    configure: error: cannot determine current directory

    Configuring GHC ...root@localhost:/root #

So then I installed `misc/compat8x` to see if that would clear up the problem. Rerun `# stack init --solver --install-ghc` and then it barfs this out:

    Preparing to install GHC to an isolated location.
    This will not interfere with any system-level installation.
    Already downloaded.
    Running /usr/bin/make install in directory /tmp/stack-setup5725/ghc-7.8.4/ exited with ExitFailure 1
    
    
    make: stopped in /tmp/stack-setup5725/ghc-7.8.4
    
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 13: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 26: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 29: warning: duplicate script for target "default" ignored
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 20: warning: using previous script for "default" defined here
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 36: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 135: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 137: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 139: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 142: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 144: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 146: Need an operator
    make: "mk/mk/config.mk" line 91: Need an operator
    make: "mk/mk/config.mk" line 93: Need an operator
    make: "mk/mk/config.mk" line 95: Need an operator
    make: "mk/mk/config.mk" line 104: Need an operator
    make: "mk/mk/config.mk" line 106: Need an operator
    make: "mk/mk/config.mk" line 119: Need an operator
    make: "mk/mk/config.mk" line 121: Need an operator
    make: "mk/mk/config.mk" line 123: Need an operator
    make: "mk/mk/config.mk" line 125: Need an operator
    make: "mk/mk/config.mk" line 138: Need an operator
    make: "mk/mk/config.mk" line 142: Need an operator
    make: "mk/mk/config.mk" line 144: Need an operator
    make: "mk/mk/config.mk" line 146: Need an operator
    make: "mk/mk/config.mk" line 187: Need an operator
    make: "mk/mk/config.mk" line 189: Need an operator
    make: "mk/mk/config.mk" line 191: Need an operator
    make: "mk/mk/config.mk" line 198: Need an operator
    make: "mk/mk/config.mk" line 200: Need an operator
    make: "mk/mk/config.mk" line 202: Need an operator
    make: "mk/mk/config.mk" line 208: Need an operator
    make: "mk/mk/config.mk" line 210: Need an operator
    make: "mk/mk/config.mk" line 212: Need an operator
    make: "mk/mk/config.mk" line 216: Need an operator
    make: "mk/mk/config.mk" line 218: Need an operator
    make: "mk/mk/config.mk" line 220: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 45: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 50: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 52: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 53: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 61: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 71: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 77: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 78: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 79: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 80: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 82: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 99: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 110: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 165: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 167: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 169: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 184: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 186: Need an operator
    make: "mk/mk/config.mk" line 244: Need an operator
    make: "mk/mk/config.mk" line 246: Need an operator
    make: "mk/mk/config.mk" line 381: Need an operator
    make: "mk/mk/config.mk" line 383: Need an operator
    make: "mk/mk/config.mk" line 384: Need an operator
    make: "mk/mk/config.mk" line 386: Need an operator
    make: "mk/mk/config.mk" line 430: Need an operator
    make: "mk/mk/config.mk" line 434: Need an operator
    make: "mk/mk/config.mk" line 456: Need an operator
    make: "mk/mk/config.mk" line 458: Need an operator
    make: "mk/mk/config.mk" line 477: Need an operator
    make: "mk/mk/config.mk" line 479: Need an operator
    make: "mk/mk/config.mk" line 481: Need an operator
    make: "mk/mk/config.mk" line 496: Need an operator
    make: "mk/mk/config.mk" line 498: Need an operator
    make: "mk/mk/config.mk" line 500: Need an operator
    make: "mk/mk/config.mk" line 555: Need an operator
    make: "mk/mk/config.mk" line 557: Need an operator
    make: "mk/mk/config.mk" line 562: Need an operator
    make: "mk/mk/config.mk" line 564: Need an operator
    make: "mk/mk/config.mk" line 567: Need an operator
    make: "mk/mk/config.mk" line 572: Need an operator
    make: "mk/mk/config.mk" line 573: Need an operator
    make: "mk/mk/config.mk" line 574: Need an operator
    make: "mk/mk/config.mk" line 575: Need an operator
    make: "mk/mk/config.mk" line 576: Need an operator
    make: "mk/mk/config.mk" line 579: Need an operator
    make: "mk/mk/config.mk" line 584: Need an operator
    make: "mk/mk/config.mk" line 586: Need an operator
    make: "mk/mk/config.mk" line 588: Need an operator
    make: "mk/mk/config.mk" line 594: Need an operator
    make: "mk/mk/config.mk" line 596: Need an operator
    make: "mk/mk/config.mk" line 598: Need an operator
    make: "mk/mk/config.mk" line 635: Need an operator
    make: "mk/mk/config.mk" line 637: Need an operator
    make: "mk/mk/config.mk" line 689: Need an operator
    make: "mk/mk/config.mk" line 691: Need an operator
    make: "mk/mk/config.mk" line 693: Need an operator
    make: "mk/mk/config.mk" line 695: Need an operator
    make: "mk/mk/config.mk" line 697: Need an operator
    make: "mk/mk/config.mk" line 708: Need an operator
    make: "mk/mk/config.mk" line 711: Need an operator
    make: "mk/mk/config.mk" line 714: Need an operator
    make: "mk/mk/config.mk" line 717: Need an operator
    make: "mk/mk/config.mk" line 718: Need an operator
    make: "mk/mk/config.mk" line 719: Need an operator
    make: "mk/mk/config.mk" line 721: Need an operator
    make: "mk/mk/config.mk" line 724: Need an operator
    make: "mk/mk/config.mk" line 727: Need an operator
    make: "mk/mk/config.mk" line 778: Need an operator
    make: "mk/mk/config.mk" line 782: Need an operator
    make: "mk/mk/config.mk" line 787: Need an operator
    make: "mk/mk/config.mk" line 789: Need an operator
    make: "mk/mk/config.mk" line 791: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 38: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 135: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 137: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 139: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 142: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 144: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/project.mk" line 146: Need an operator
    make: "mk/mk/config.mk" line 91: Need an operator
    make: "mk/mk/config.mk" line 93: Need an operator
    make: "mk/mk/config.mk" line 95: Need an operator
    make: "mk/mk/config.mk" line 104: Need an operator
    make: "mk/mk/config.mk" line 106: Need an operator
    make: "mk/mk/config.mk" line 119: Need an operator
    make: "mk/mk/config.mk" line 121: Need an operator
    make: "mk/mk/config.mk" line 123: Need an operator
    make: "mk/mk/config.mk" line 125: Need an operator
    make: "mk/mk/config.mk" line 138: Need an operator
    make: "mk/mk/config.mk" line 142: Need an operator
    make: "mk/mk/config.mk" line 144: Need an operator
    make: "mk/mk/config.mk" line 146: Need an operator
    make: "mk/mk/config.mk" line 187: Need an operator
    make: "mk/mk/config.mk" line 189: Need an operator
    make: "mk/mk/config.mk" line 191: Need an operator
    make: "mk/mk/config.mk" line 198: Need an operator
    make: "mk/mk/config.mk" line 200: Need an operator
    make: "mk/mk/config.mk" line 202: Need an operator
    make: "mk/mk/config.mk" line 208: Need an operator
    make: "mk/mk/config.mk" line 210: Need an operator
    make: "mk/mk/config.mk" line 212: Need an operator
    make: "mk/mk/config.mk" line 216: Need an operator
    make: "mk/mk/config.mk" line 218: Need an operator
    make: "mk/mk/config.mk" line 220: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 45: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 50: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 52: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 53: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 61: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 71: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 77: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 78: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 79: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 80: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 82: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 99: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 110: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 165: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 167: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 169: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 184: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/mk/install.mk" line 186: Need an operator
    make: "mk/mk/config.mk" line 244: Need an operator
    make: "mk/mk/config.mk" line 246: Need an operator
    make: "mk/mk/config.mk" line 381: Need an operator
    make: "mk/mk/config.mk" line 383: Need an operator
    make: "mk/mk/config.mk" line 384: Need an operator
    make: "mk/mk/config.mk" line 386: Need an operator
    make: "mk/mk/config.mk" line 430: Need an operator
    make: "mk/mk/config.mk" line 434: Need an operator
    make: "mk/mk/config.mk" line 456: Need an operator
    make: "mk/mk/config.mk" line 458: Need an operator
    make: "mk/mk/config.mk" line 477: Need an operator
    make: "mk/mk/config.mk" line 479: Need an operator
    make: "mk/mk/config.mk" line 481: Need an operator
    make: "mk/mk/config.mk" line 496: Need an operator
    make: "mk/mk/config.mk" line 498: Need an operator
    make: "mk/mk/config.mk" line 500: Need an operator
    make: "mk/mk/config.mk" line 555: Need an operator
    make: "mk/mk/config.mk" line 557: Need an operator
    make: "mk/mk/config.mk" line 562: Need an operator
    make: "mk/mk/config.mk" line 564: Need an operator
    make: "mk/mk/config.mk" line 567: Need an operator
    make: "mk/mk/config.mk" line 572: Need an operator
    make: "mk/mk/config.mk" line 573: Need an operator
    make: "mk/mk/config.mk" line 574: Need an operator
    make: "mk/mk/config.mk" line 575: Need an operator
    make: "mk/mk/config.mk" line 576: Need an operator
    make: "mk/mk/config.mk" line 579: Need an operator
    make: "mk/mk/config.mk" line 584: Need an operator
    make: "mk/mk/config.mk" line 586: Need an operator
    make: "mk/mk/config.mk" line 588: Need an operator
    make: "mk/mk/config.mk" line 594: Need an operator
    make: "mk/mk/config.mk" line 596: Need an operator
    make: "mk/mk/config.mk" line 598: Need an operator
    make: "mk/mk/config.mk" line 635: Need an operator
    make: "mk/mk/config.mk" line 637: Need an operator
    make: "mk/mk/config.mk" line 689: Need an operator
    make: "mk/mk/config.mk" line 691: Need an operator
    make: "mk/mk/config.mk" line 693: Need an operator
    make: "mk/mk/config.mk" line 695: Need an operator
    make: "mk/mk/config.mk" line 697: Need an operator
    make: "mk/mk/config.mk" line 708: Need an operator
    make: "mk/mk/config.mk" line 711: Need an operator
    make: "mk/mk/config.mk" line 714: Need an operator
    make: "mk/mk/config.mk" line 717: Need an operator
    make: "mk/mk/config.mk" line 718: Need an operator
    make: "mk/mk/config.mk" line 719: Need an operator
    make: "mk/mk/config.mk" line 721: Need an operator
    make: "mk/mk/config.mk" line 724: Need an operator
    make: "mk/mk/config.mk" line 727: Need an operator
    make: "mk/mk/config.mk" line 778: Need an operator
    make: "mk/mk/config.mk" line 782: Need an operator
    make: "mk/mk/config.mk" line 787: Need an operator
    make: "mk/mk/config.mk" line 789: Need an operator
    make: "mk/mk/config.mk" line 791: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 40: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 41: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 42: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 43: Need an operator
    make: "mk/mk/custom-settings.mk" line 4: Need an operator
    make: "mk/mk/custom-settings.mk" line 5: Could not find mk/validate-settings.mk
    make: "mk/mk/custom-settings.mk" line 7: Need an operator
    make: "mk/mk/" line 1: warning: Zero byte read from file, skipping rest of line.
    make: "mk/mk/" line 1: Need an operator
    make: "mk/mk/" line 3: warning: Zero byte read from file, skipping rest of line.
    make: "mk/mk/" line 3: Need an operator
    make: "mk/mk/" line 5: Need an operator
    make: "mk/mk/custom-settings.mk" line 9: Need an operator
    make: "mk/mk/custom-settings.mk" line 11: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/bindist.mk" line 6: Need an operator
    make: "mk/mk/custom-settings.mk" line 13: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 48: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 49: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 50: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 51: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 52: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 70: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 73: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 74: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 75: warning: duplicate script for target "ifneq" ignored
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 72: warning: using previous script for "ifneq" defined here
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 75: warning: duplicate script for target """" ignored
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 72: warning: using previous script for """" defined here
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 76: warning: duplicate script for target "ifneq" ignored
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 72: warning: using previous script for "ifneq" defined here
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 76: warning: duplicate script for target """" ignored
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 72: warning: using previous script for """" defined here
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 77: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 85: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 86: warning: duplicate script for target """" ignored
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 72: warning: using previous script for """" defined here
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 87: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 91: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 101: warning: duplicate script for target "show" ignored
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 24: warning: using previous script for "show" defined here
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 103: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 106: Need an operator
    make: "/tmp/stack-setup5725/ghc-7.8.4/Makefile" line 112: Need an operator
    make: Fatal errors encountered -- cannot continue
    Installing GHC ...root@localhost:/root #

**Comment by Cipherwraith** [comment]
This problem was solved by installing `gmake`. 
`gmake` didnt come pre-packaged with my install of freebsd10.3.

**Comment by mgsloan** [comment]
Should installing `gmake` be added to the FreeBSD instructions?  Or perhaps to this http://stack-pkg.applicative.tech/ - were you using that?

**Comment by borsboom** [comment]
I believe the FreeBSD packages do now include gmake as a dependency, and the FreeBSD installation instructions now include installing it.

**Comment by Cipherwraith** [comment]
Its been a year and I have run into this problem again.

`Shared object "libutil.so.8" not found, required by "ghc-pwd"`

I fixed it again by installing `gmake`. 

@borsboom Could you double check if the FreeBSD instructions now include installing it or not? Thanks.

```
$ stack setup --install-ghc
Warning: Specified resolver could not satisfy all dependencies. Some external packages have been added as dependencies.
You can suppress this message by removing it from stack.yaml

Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-7.10.3.
Running /home/redacted/.stack/programs/x86_64-freebsd/ghc-7.10.3.temp/ghc-7.10.3/configure --prefix=/home/redacted/.stack/programs/x86_64-freebsd/ghc-7.10.3/ in directory /home/redacted/.stack/programs/x86_64-freebsd/ghc-7.10.3.temp/ghc-7.10.3/ exited with ExitFailure 1

checking for path to top of build tree...
Shared object "libutil.so.8" not found, required by "ghc-pwd"
configure: error: cannot determine current directory


Error: Error encountered while configuring GHC with
         /home/redacted/.stack/programs/x86_64-freebsd/ghc-7.10.3.temp/ghc-7.10.3/configure --prefix=/home/redacted/.stack/programs/x86_64-freebsd/ghc-7.10.3/
         run in /home/redacted/.stack/programs/x86_64-freebsd/ghc-7.10.3.temp/ghc-7.10.3/

The following directories may now contain files, but won't be used by stack:
  - /home/redacted/.stack/programs/x86_64-freebsd/ghc-7.10.3.temp/
  - /home/redacted/.stack/programs/x86_64-freebsd/ghc-7.10.3/
```

```
$ stack --version
Version 1.4.0 x86_64
```

```
$ uname -a
FreeBSD redacted 11.0-RELEASE-p1 FreeBSD 11.0-RELEASE-p1 #0 r306420: Thu Sep 29 01:43:23 UTC 2016     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by Cipherwraith** [comment]
It seems libutil.so.9 is installed by default on FreeBSD 11.0. 

```# locate libutil
/lib/libutil.so.9```

I suppressed this error by symlinking 9 to 8:

`# ln -s /lib/libutil.so.9 /lib/libutil.so.8`

Everything installed just fine after symlinking. Not sure of the differences between 8 and 9, but hopefully it doesnt cause problems down the road.

@borsboom Please consider bumping the `libutil.so.8` requirement to `libutil.so.9`.
