### ISSUE TITLE
Could use a UNIX man page

### ISSUE THREAD

**Issue by drwebb** [commercialhaskell/stack#202]
Related to #74

It would be nice to provide a man page with the distribution packages that are installed on the user's system.

**Comment by drwebb** [comment]
If there are no other takers, I'll try to throw up something for the next release and we can refine the generation later if I end up just writing it by hand.

**Comment by snoyberg** [comment]
Sold!

**Comment by drwebb** [comment]
Added a basic man page in c2e5af39679439921570552e3e722f6819f4f4bf. It's mostly hand written. Are we going to keep all the config parsers in Main.hs? It makes the a little inaccessible to an auto generation using pandoc.

pinging @manny-fp and @dysinger to remember to include them in their distro releases

**Comment by drwebb** [comment]
Closing this now for the moment, we should move to improving the current man page as part of the release process and look to auto generation in the future.
