### ISSUE TITLE
Stack templates cannot declare package build options

### ISSUE THREAD

**Issue by aleator** [commercialhaskell/stack#2021]
In addition to stack templates being unable to generate extra-deps (see #2014) they also
cannot add build options to packages. This is required, for example, with `llvm-general`
package, which requires `--shared` so that it won't crash ghci.

**Comment by mgsloan** [comment]
Thanks!

Since the only reasonable resolution of #2014 would also resolve this (allow `stack.yaml` inclusion in templates), I am going to close this as a dupe of that.
