### ISSUE TITLE
standalone script referencing custom packages??

### ISSUE THREAD

**Issue by timbod7** [commercialhaskell/stack#2027]
I'm trying to use stack in the "script interpreter" mode as [described in the user guide][1]. Is there any way to reference a package that is not part of the snapshot. I don't seem to be able to pass a filesystem path to the `--package` argument. For example with a script starting with:

```
#!/usr/bin/env stack   # https://www.haskell.org/downloads#stack
{- stack --resolver lts-5.5 runghc --package ../../filetree --install-ghc -}
```

I get the following error:

```
Error parsing targets: No local directories found as children of ../../filetree
```

[1]:http://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter

**Comment by mgsloan** [comment]
Use a stack.yaml file and refer to the package by name.

**Comment by timbod7** [comment]
Thanks - it's not quite as clean as a standone script, but works ok.

**Comment by mgsloan** [comment]
We could consider allowing standalone scripts to specify a stack.yaml

**Comment by lynnard** [comment]
Can we reopen this issue? I'm trying to pass `--stack-yaml` flag but it says `Ignoring override stack.yaml file for script command'. This would be a useful feature for one off scripts that make use of local packages.

**Comment by mgsloan** [comment]
@lynnard The script command is a bit different.  It would be nice to have a mode for it that uses stack.yaml, but it has a bit of a different intent implementation atm, worth considering, feel free to open a new issue about it.

As a workaround for now, you can use `runghc` in place of `script`, and it can use a stack.yaml

**Comment by lynnard** [comment]
Thanks, will try that out - alternatively is it easy to make `package` flag accept more variants of specification e.g., github repo, filepath, etc.?

**Comment by mgsloan** [comment]
Hmm, yeah, that could work alright.  Off the top of my head I can't think of any reasons not to do it.
