### ISSUE TITLE
`stack deps hscolour` does nothing

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#203]
`stack deps hscolour` doesn't seem to do anything, it just exits without any output.  If I add `- hscolour-1.23` to `extra-deps` in stack.yaml, it just downloads hscolour but doesn't install it:

```
$ stack deps hscolour
Downloading hscolour-1.23
$
```

(related to #87)

**Comment by chris-martin** [comment]
Note for future readers: It seems that `deps` has been renamed to `install`, so the command to get hyperlinked sources is `stack install hscolour`.
