### ISSUE TITLE
`stack upgrade` show `user-message` from the `stack.yaml` in cwd

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#2030]
Happend to have the following in the `stack.yaml` in the current working directory:
```yaml
user-message: ! 'Warning: Specified resolver could not satisfy all dependencies. Some
  external packages have been added as dependencies.

  You can suppress this message by removing it from stack.yaml

'
```
when trying to run `stack upgrade`, that message is displayed.

```bash
$ stack upgrade
Warning: Specified resolver could not satisfy all dependencies. Some external packages have been added as dependencies.
You can suppress this message by removing it from stack.yaml
```

Maybe I'm mistaken, but I doubt that message should be displayed.

**Comment by mgsloan** [comment]
Fair point.  Now the message is only displayed when loading the build config.  Not 100% sure this is the right change, but it can always be reverted if uses of this field spans beyond build concerns.
