### ISSUE TITLE
LTS resolver doesn't find preinstalled global packages

### ISSUE THREAD

**Issue by manny-fp** [commercialhaskell/stack#204]
WIth `resolver: lts-1.9`, stack is not able to find the custom packages installed in GHC's global package database in a custom Docker image.  I had to use `resolver: ghc-7.8` instead.  The output looks like:

```
$ stack build
host-stack: Exception: Stack.Build.ConstuctPlanExceptions
While constructing the BuildPlan the following exceptions were encountered:

--  Exception Stack.Build.Couldn'tMakePlanForWanted
    Couldn't make build plan while adding local packages:
      custom-a
      custom-b
```

**Comment by snoyberg** [comment]
@manny-fp Just as a sanity check, can you try this again? If the problem still exists, I'd like to work with you on resolving it, as a good introduction to the internals of stack.

**Comment by manny-fp** [comment]
I'm afraid the problem still seems to exist.

**Comment by snoyberg** [comment]
@mgsloan is taking a look at this now

**Comment by manny-fp** [comment]
This seems to be fixed in the current version of stack.
