### ISSUE TITLE
stack fails with a fatal error when it tries to glob for source/data files mentioned in .cabal

### ISSUE THREAD

**Issue by Peaker** [commercialhaskell/stack#2042]
When a .cabal file uses a "Custom" build, it can generate extra source files or data files in its hooks.

Stack checks that all source/data files mentioned in the .cabal exist, and warns if they don't (e.g: before Setup.hs got a chance to run and generate them).

However, this warning degrades to a fatal error when the .cabal file mentions the files using a glob pattern on a directory that has yet to be created.

If stack is globbing the directory only in order to emit warnings - it would make sense to allow the directory itself to also be missing.

**Comment by mgsloan** [comment]
Hmm, yeah, sounds like a good thing to fix.

**Comment by mgsloan** [comment]
Fixed in https://github.com/commercialhaskell/stack/commit/31c55d036064b1945e1636fd5e7475c17f01dbc8 I believe, reopen if not.
