### ISSUE TITLE
Incorrect handling of wildcards in data-files section in .cabal

### ISSUE THREAD

**Issue by apriori** [commercialhaskell/stack#2046]
##### Some packages assume data-files to be generated and not existing prior building the package. One example is: https://github.com/chetant/LibClang. According to cabal documentation, this is fine, because "data-files" states nowhere that the referenced files need to exist at a certain time (e.g. before install). 

https://www.haskell.org/cabal/users-guide/developing-packages.html#package-properties

## Reproduction

(make sure to clean before every try using stack clean; cabal clean)

1. Create a simple stack project, using 'stack new wildcardfailure simple'
2. Edit the wildcardfailure.cabal and add: data-files: build/*.h
3. Execute stack build on the project and investigate the error
```
/home/user/wildcardfailure/build/: getDirectoryContents: does not exist (No such file or directory)
```

### Differences in behaviour of stack and plain cabal
Cabal only allows extension wildcards. Stack allows all common usages of wildcards, and will warn, but continue, if it doesn't find any matches. This example is an exception, though.
If one e.g. uses "build/*, one gets this error:

```
setup-Simple-Cabal-1.22.5.0-ghc-7.10.3: invalid file glob 'build/*'.
Wildcards '*' are only allowed in place of the file name, not in the directory
name or file extension. If a wildcard is used it must be with an file
extension.
```

**Comment by mgsloan** [comment]
Thanks for the report

**Comment by mgsloan** [comment]
Fixed!
