### ISSUE TITLE
Spurious local package rebuilding after a failed build

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#205]
Using

```
$ stack --version
Version 0.0.0, Git revision 484d676f8a29281b87c0baf8685b0cd6b9f2d59a
```
with GHC 7.10 and Cabal 1.22 and e.g. the following .cabal file:

```
name:                b
version:             0.0.0.0
build-type:          Simple
cabal-version:       >=1.10

library
  build-depends:       base >=4.8 && <5
                     , binary >= 0.7
                     , text
  exposed-modules:     SomeModule
  default-language:    Haskell2010
```

results in a build error if the source file for SomeModule doesn't exist, as it should. However, when calling `stack build` again, `stack` tells me it went ahead and  unregistered a bunch of packages that it had just installed. e.g. in the above, with

```
packages:
- '.'
- vendor/binary
resolver: nightly-2015-06-05
extra-deps:
- binary-0.7.5.0
```

stack first installs my local checkout of the `binary` github repo, then `text`, then fails, then when attempting a build the second time stack unregisters `text`, spends a while  rebuilding `text`, before failing again.

**Comment by snoyberg** [comment]
@mboes I believe this is now resolved, could you test?

**Comment by mboes** [comment]
yep.
