### ISSUE TITLE
hpack doesn't pick up changes to project folders and files

### ISSUE THREAD

**Issue by lukexi** [commercialhaskell/stack#2051]
As a knock-on effect of https://github.com/commercialhaskell/stack/pull/1815, hpack's excellent feature of automatically generating the exported modules list from the source directory doesn't get triggered when I add new modules. This is presumably also relevant to its globbing capabilities.

So, the modification time of the package.yaml file is not the only criterion for when hpack should be run...

**Comment by mgsloan** [comment]
This is also relevant to file-watch.  Since hpath can watch globs, we also need to watch directories for additions that match the globs

**Comment by mitchellwrosen** [comment]
Ahh, I was wondering why my workflow felt so awkward lately! I've found myself constantly `touch`ing my cabal file as I rename modules, etc, whereas before, `hpack` would take care of updating the cabal file automatically.

**Comment by mgsloan** [comment]
#1813 was resolved more properly by #2011, so I've reverted the old resolution of it, so this is now also fixed!
