### ISSUE TITLE
How do I add a dependency I expect to be locally installed?

### ISSUE THREAD

**Issue by bananu7** [commercialhaskell/stack#2055]
Let's say I have two projects, `A` and `B`, `B` depending on `A`. Neither of them is on Stackage. I clone and build `A`, then do `stack install`. At this point, I can globally run any executables provided by it and  I'd expect it to be available to other libraries as well.

However, when doing `stack build` in `B`, it doesn't want to pick up `A`. It only looks in the relative path, namely `.../B/A/`, fails to see `A` there and fails.

How do I specify that a dependency is expected to be locally installed?

**Comment by mgsloan** [comment]
You need to create a stack.yaml file has both projects.  See [the docs](http://docs.haskellstack.org/en/stable/yaml_configuration/#project-config) - there are a variety of ways to specify this.  Easiest would be to write a stack.yaml file like the following:

```yaml
packages:
- A
- B
```

> However, when doing stack build in B, it doesn't want to pick up A. It only looks in the relative path, namely .../B/A/, fails to see A there and fails.

I don't follow the reasoning here

> How do I specify that a dependency is expected to be locally installed?

For dependencies outside of snapshots, you need to have them in your stack.yaml project.  Alternatively, you can use custom snapshots.  It is on the agenda to improve such package sharing - https://github.com/commercialhaskell/stack/issues/1265

**Comment by xpe** [comment]
@bananu7 Have you seen the `extra-dep: true` option, as mentioned at http://docs.haskellstack.org/en/stable/yaml_configuration/#project-config? It may help you.

**Comment by mgsloan** [comment]
Gonna go ahead and close this, feel free to reopen

**Comment by bananu7** [comment]
Oh sorry, I got kinda swamped with other things.

> You need to create a stack.yaml file has both projects.

That's what I did, except I did put `.` and `A` there; and that prompted stack to look for `A` relatively to the `B`s path, despite the fact I did `stack install` in `A`'s folder

>  Have you seen the `extra-dep: true option`

Yeah, I did use it, but it still required me to pass relative path there.

**Comment by mgsloan** [comment]
> Yeah, I did use it, but it still required me to pass relative path there.

Yes.  Perhaps it is too stringent of a restriction, but relative paths are preferred to make it so that you can move your packages / send the code to someone else.

> PS Oh also, if you were wondering about the use case, I'm developing both of those packages at the same time; that's why I need dev snapshots of both of them locally installed and available.

Makes sense.  In that circumstance, I have a stack.yaml file which includes both of them.
