### ISSUE TITLE
Ubuntu on Windows: stack fails to run

### ISSUE THREAD

**Issue by lilred** [commercialhaskell/stack#2057]
Windows 10, build 14328. Enabled Linux Subsystems for Windows (Beta). Ran "Bash on Ubuntu on Windows".

I installed `stack` with the following puppet script:

```
#!/usr/bin/puppet apply
package { 'stack' : require => Apt::Source['fpcomplete'], }

apt::key { 'fpcomplete':
  id      => 'C5705533DA4F78D8664B5DC0575159689BEFB442',
  server  => 'keyserver.ubuntu.com',
}

apt::source { 'fpcomplete':
  location => 'http://download.fpcomplete.com/ubuntu',
  release  => $lsbdistcodename,
  repos    => 'main',
  require  => Apt::Key['fpcomplete'],
}
```

Unfortunately, `stack` does not work.

```
carl@DESKTOP-39664B8:~$ stack ghci
stack: timer_create: Invalid argument
```

**Comment by lilred** [comment]
Relevant: Microsoft/BashOnWindows#112

**Comment by mgsloan** [comment]
Thanks for trying it out, sounds to me like an issue with window's implementation.  Please reopen if otherwise.

**Comment by lilred** [comment]
Forgive me for being a massive noob, but isn't it worth it to keep a tracking issue open even though the issue is upstream? Just for documenting.

I assume the stack workflow is to close upstream issues, are you using GH Issues as a backlog?

**Comment by mgsloan** [comment]
This seems like a usecase we don't explicitly support, and so is out of the scope of the project.  If something is impacting a lot of users, then it may well be valuable to have an issue to track some upstream issue.

We tend to try to keep the GH issues to things where there is some conceivable future action for us to take in stack particularly - either implementation or further discussion.  Problems like "ghc compiled binaries don't work on windows' linux emulation layer" is not really within scope.
