### ISSUE TITLE
Request for support for Ubuntu on Pine A64

### ISSUE THREAD

**Issue by hukuzatuna** [commercialhaskell/stack#2059]
Subject says it all. Would really like to have this supported on the Pine A64 running Ubuntu.

Cheers,
Phil

**Comment by borsboom** [comment]
The first step for supporting new platforms is to make fully working GHC bindists available for the platform, preferably officially released by the GHC release team (but, in some cases, community-provided bindists can be used as well if there's a commitment to keep them up to date).  So I'm going to flag this as blocked until such GHC bindists are available.

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time. 

If I understand correctly, the Pine A64 had a 1.2 GHz Quad-Core ARM Cortex-A53 64-Bit Processor, which implements the ARMv8-A 64-bit instruction set, which is also known as AArch64. AArch64 versions of GHC are provided by the GHC developers and AArch64 versions of Stack are available.
