### ISSUE TITLE
Need documentation explicitly specifying how to enable profiling builds by default

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2074]
Presumably in `~/.stack/global-project/stack.yaml`

There's no examples of enabling executable/library profiling for a one-off project.

Documentation mentions --enable-\* but it was the flags sans `enable-` prefix that worked.

<img width="708" alt="screen shot 2016-04-27 at 8 19 41 pm" src="https://cloud.githubusercontent.com/assets/320177/14872807/62f127e4-0cb5-11e6-90f8-df5aa2da7252.png">

**Comment by bitemyapp** [comment]
This worked, but is a one-off build invocation.

![screen shot 2016-04-27 at 8 20 06 pm](https://cloud.githubusercontent.com/assets/320177/14872812/750f7200-0cb5-11e6-82fc-73508dd9ab41.png)

**Comment by mgsloan** [comment]
The docs probably ought to be updated to mention `--profile` there as well.  It's equivalent to `--executable-profiling --library-profiling`.

**Comment by sjakobi** [comment]
You can specify

```
build:
  library-profiling: true
  executable-profiling: true
```

in a `stack.yaml` or even the global `~/.stack/config.yaml`.

Not sure if we should also have

```
build:
  profile: true
```

in analogy to `--profile`?

**Comment by mgsloan** [comment]
I'd rather not have `profile:`, since we'd probably want to have some logic checking for redundant / inconsistent settings.  I suppose we might want that on the CLI level too

**Comment by sjakobi** [comment]
The original issue here appears to be fixed but maybe we should track @mgsloan's idea:?

> we'd probably want to have some logic checking for redundant / inconsistent settings. I suppose we might want that on the CLI level too

@mgsloan: Could you take care of this? I don't have a good idea of what that settings checking should look like.

**Comment by snoyberg** [comment]
Since original topic is addressed, closing.
