### ISSUE TITLE
rebuild when switching between `stack build` and `stack test`

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#208]
```
git clone https://github.com/yesodweb/yesod
cd yesod/yesod-core
stack build
stack test  # core re-built
stack build # core re-build
```

Because the tests depend on the yesod-core library there should be no need to recompile it when switching between building and testing. This may have to do with being defensive avout CPP: the first re-build module uses CPP.

**Comment by snoyberg** [comment]
Please confirm on the 283-test-suite-fix branch.

**Comment by gregwebs** [comment]
283-test-suite-fix branch is merged to master, so I am testing that. Works great!
