### ISSUE TITLE
Avoid loading hackage index cache for extra-deps which are already installed?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2081]
This may have some relation to https://github.com/commercialhaskell/stack/pull/2070 - the ability to ensure that we are always using the same cabal file.

As discussed [here](https://github.com/commercialhaskell/stack/pull/2077#issuecomment-215600720), it extra-deps cause the hackage cache to get loaded, as we need to get their cabal description.  I haven't thought through all the details, but this doesn't seem necessary.  The fix may be complicated, though: 

There are two spots that need the cabal file:

https://github.com/commercialhaskell/stack/blob/dd98fbcc821890df46d7e3eb4f2fe4a28b493ff1/src/Stack/Build/ConstructPlan.hs#L286
https://github.com/commercialhaskell/stack/blob/dd98fbcc821890df46d7e3eb4f2fe4a28b493ff1/src/Stack/Build/ConstructPlan.hs#L320

In the case that we already have this package installed, there should be enough info in the package db, potentially even in `ghc-pkg` queries stack already made, to not need to load the cache.

We're going to be swapping out `binary` with faster serialization soon, so it may be that soon there won't be as much motivation for doing something sophisticated to avoid this 0.3s load time.

**Comment by snoyberg** [comment]
This is no longer relevant with Pantry, which stores these files in a quickly accessible SQLite database.
