### ISSUE TITLE
init flag `--omit-packages` is without effect when not using `--solver`

### ISSUE THREAD

**Issue by lspitzner** [commercialhaskell/stack#2082]
expected: `stack init --omit-packages` produces a `stack.yaml` file.
actual: "will need external packages: [non-empty list]", no `stack.yaml`.

```
> stack --version
Version 1.0.4.1 x86_64
```

**Comment by mpilgrem** [comment]
Closing because, with Stack 2.15.1, `stack init --omit-packages` produces a `stack.yaml` file.
