### ISSUE TITLE
Update msys2? 

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2091]
Discussed in #ghc, our current version is about a year old: https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml#L56

Not sure when we should bump the version.  It would be kinda nice to specify the version in the snapshot, for reproducibility (potentially with an opt-out).  

Is it even reasonable for us to bump the setup-info version?  This will put us in a situation where users that already have it installed will use the old version, but new users who run `stack setup` will get the new version.

**Comment by snoyberg** [comment]
PR opened: https://github.com/fpco/stackage-content/pull/41

Plus a doc update PR: #4043
