### ISSUE TITLE
Failed to download template info

### ISSUE THREAD

**Issue by Skyfold** [commercialhaskell/stack#2101]
Version 1.1.0, Git revision c545ececef000bef7eb79a48045bf7d1a7bbf067 (3539 commits) x86_64 hpack-0.13.0

ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1713

I ran, `stack templates` outside of a project and got:

Failed to download template info. The HTTP error was: StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) [("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'"),("X-XSS-Protection","1; mode=block"),("X-Frame-Options","deny"),("X-Content-Type-Options","nosniff"),("Strict-Transport-Security","max-age=31536000"),("X-GitHub-Request-Id","17EB2914:3F20:1C5845C:572B2E28"),("Content-Length","9"),("Accept-Ranges","bytes"),("Date","Thu, 05 May 2016 11:27:37 GMT"),("Via","1.1 varnish"),("Connection","keep-alive"),("X-Served-By","cache-syd1621-SYD"),("X-Cache","MISS"),("X-Cache-Hits","0"),("Vary","Authorization,Accept-Encoding"),("Access-Control-Allow-Origin","*"),("X-Fastly-Request-ID","f0dc2d065045b3bde88aa390785834676b391ef3"),("Expires","Thu, 05 May 2016 11:32:37 GMT"),("Source-Age","0"),("X-Response-Body-Start","Not Found"),("X-Request-URL","GET https://raw.githubusercontent.com:443/commercialhaskell/stack-templates/master/template-info.yaml")] (CJ {expose = []})

Same error, but with some formating:

```
Failed to download template info. 
The HTTP error was: 
    StatusCodeException (Status {statusCode = 404, statusMessage = "Not Found"}) 
    [  ("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'")
      ,("X-XSS-Protection","1; mode=block")
      ,("X-Frame-Options","deny")
      ,("X-Content-Type-Options","nosniff")
      ,("Strict-Transport-Security","max-age=31536000")
      ,("X-GitHub-Request-Id","17EB2914:3F20:1C5845C:572B2E28")
      ,("Content-Length","9"),("Accept-Ranges","bytes")
      ,("Date","Thu, 05 May 2016 11:27:37 GMT")
      ,("Via","1.1 varnish")
      ,("Connection","keep-alive")
      ,("X-Served-By","cache-syd1621-SYD")
      ,("X-Cache","MISS")
      ,("X-Cache-Hits","0")
      ,("Vary","Authorization,Accept-Encoding")
      ,("Access-Control-Allow-Origin","*")
      ,("X-Fastly-Request-ID","f0dc2d065045b3bde88aa390785834676b391ef3")
      ,("Expires","Thu, 05 May 2016 11:32:37 GMT")
      ,("Source-Age","0"),("X-Response-Body-Start","Not Found")
      ,("X-Request-URL","GET https://raw.githubusercontent.com:443/commercialhaskell/stack-templates/master/template-info.yaml")
    ] 
(CJ {expose = []})
```

**Comment by mgsloan** [comment]
Good catch!  Fixed after merging https://github.com/commercialhaskell/stack-templates/pull/53
