### ISSUE TITLE
sdist --sign does not work

### ISSUE THREAD

**Issue by wereHamster** [commercialhaskell/stack#2102]
```
Error extracting a GPG fingerprint unable to extract fingerprint from output
: 
```

The problem appears to be that stack expects certain output from `gpg --verify - <path>` (a line with "Primary key fingerprint:") but it's not there. The actual output is this:

```
$ cat sig | gpg --verify - <path>
gpg: Signature made Thu May  5 13:44:35 2016 CEST using RSA key ID 67FB0B4A
gpg: Good signature from "Tomas Carnecky <...>"
```

Looking through the code, stack should probably use `gpg --status-fd=X` insead of parsing the standard output. See also https://www.gnupg.org/documentation/manuals/gnupg/Automated-signature-checking.html and https://www.gnupg.org/documentation/manuals/gnupg/Unattended-Usage.html

**Comment by mgsloan** [comment]
Pinging @dysinger

**Comment by dysinger** [comment]
If fixed this with a patch to both stable & master (about the same time you filed this). The problem is that the full fingerprint isn't being shown in the sign/verify combo.

If you add 

```
with-fingerprint
```

to your gpg.conf it will work until we get the next release out.  Sorry about this.

**Comment by mgsloan** [comment]
Seems like this is resolved!  Closing

**Comment by qrilka** [comment]
Using stack-1.1.2 I get the same error message.
Adding `with-fingerprint` to `gpg.conf` doesn't change the situation

**Comment by mgsloan** [comment]
Pinging @dysinger

**Comment by ju1m** [comment]
Hit this bug with `stack` `cebe10e845fed4420b6224d97dcabf20477bbd4b`, this workaround seems to work: `LANG=C stack sdist --sign`

**Comment by snoyberg** [comment]
Removing this code in #4677, closing
