### ISSUE TITLE
stack ghci --fast seems undocumented

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#2104]
I wonder what the ghci command's `--fast` flag does, and I don't see it in the user guide.

**Comment by mgsloan** [comment]
It comes from `stack ghci` taking all the same options as `stack build`.  For `stack build`, it uses `-O0`.  For ghci itself it doesn't do much, except for when ghci does an initial build (which can be suppressed via `--no-build`, something I use with most of my invocations).

`stack ghci` has gotten quite powerful, and a little tricky to use to its full potential.  I think it really needs its own dedicated documentation page https://github.com/commercialhaskell/stack/issues/1896

**Comment by simonmichael** [comment]
Ha.. I tried stack -h, not stack --help. Thanks.
