### ISSUE TITLE
Does docker mounting work properly when the host and container userrnames match?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2108]
See the concern mentioned by @gregwebs [here](https://github.com/commercialhaskell/stack/pull/1951#issuecomment-217072594).  Just making sure we track looking into that at some point

**Comment by kanishka-azimi** [comment]
If the uid's are different, I doubt it will work.

At work, we have started to chown all files produced into mounted volumes when building JS to the uid of the current user. I will try to remember to provide the snippet here soon.

**Comment by mgsloan** [comment]
From the following discussion on that issue, seems like this isn't an issue - closing
