### ISSUE TITLE
Add useful Show instances for exception types

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#211]
* [x] Plugins.PluginException
* [x] Exception types in Network.HTTP.Download (please unify into a single exception type, there are three right now)

**Comment by radix** [comment]
I don't know if this is the right ticket, but I had an idea:

- [ ] write documentation for each directive in stack.yaml
- [ ] make errors about each directive in stack.yaml link to specific sections in that documentation

**Comment by snoyberg** [comment]
@radix I think that comment was intended for a different issue.

**Comment by radix** [comment]
@snoyberg yeah, I actually made the same comment on a more appropriate issue: #269. It can safely be ignored here :)
