### ISSUE TITLE
"Stack new" goes through normal init process, loads existing stack.yaml

### ISSUE THREAD

**Issue by rrnewton** [commercialhaskell/stack#2110]
Is this the intended behavior?  I was just in an empty directory, trying to initialize it with:

```
$ stack new simple-library
Cannot find 'docker' in PATH.  Is Docker installed?
```

Why the error?  Well, that's because this is a checkout of a repo that has a `stack.yaml` higher up, in a parent directory.  The stack.yaml in the parent directory has docker enabled, and I happen to have it checkout out on a machine that doesn't have Docker.

I assumed that since `stack new` is about creating new projects, it would not go through the normal search process for a `stack.yaml` configuration.

In my case, I could move the directory somewhere else, `stack new`, and then move it back.  Subsequently everything would work fine of course.

stack version: 1.1.0

**Comment by mgsloan** [comment]
@rrnewton Good point, fixed in HEAD.
