### ISSUE TITLE
CA cert issue on Windows 7 for Stack 1.1.0

### ISSUE THREAD

**Issue by dysinger** [commercialhaskell/stack#2116]
![stack on windows 7](https://cloud.githubusercontent.com/assets/447/15131936/29621b8e-1609-11e6-9002-9533f29c11cd.PNG)

Fresh install of stack on Windows 7 x86_64 w/ all updates

Stack update works

Stack setup does not work

**Comment by dysinger** [comment]
Navigating to www.stackage.org on FireFox on Windows is not a problem though.

**Comment by mgsloan** [comment]
Is this helpful? https://github.com/commercialhaskell/stack/issues/1668

**Comment by dysinger** [comment]
The first thing I did when I installed Windows 7 was remove everything that wasn't necessary (including the horrid IE browser) So that "visit the site with IE first" hack doesn't work. I'll have to figure out another way to update the system CA certs.
