### ISSUE TITLE
stack test re-installs the package

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#212]
running `stack test` on a package re-installs it. This means that if I do a `stack build` for a project containing multiple packages, all the packages get re-installed.

My ideal behavior would be

```
stack build # installs package
stack test   # only runs the test
touch Project/File.hs
stack test # build and install the package and run the tests
```

This is related to #208 because testing re-configures Cabal.

**Comment by snoyberg** [comment]
Please confirm on the 283-test-suite-fix branch.

**Comment by gregwebs** [comment]
great! I don't need the flag now :)
