### ISSUE TITLE
Bugfix release 1.1.1?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2127]
Perhaps we should do a bugfix release of `1.1.0`?  And by that I mean cherry-pick some fixes onto `stable` and release that as `1.1.1`.  The following seem like good things to release fixes for:

* https://github.com/commercialhaskell/stack/issues/2123
* https://github.com/commercialhaskell/stack/issues/1418
* https://github.com/commercialhaskell/stack/pull/2107 and potentially other gpg fixes

Why not just do a release of master, including other enhancements / fixes that have happened since `1.1.0`?  Because I want to have further testing on the changes merged in with https://github.com/commercialhaskell/stack/pull/2098 and the upcoming changes in https://github.com/commercialhaskell/stack/issues/1265

**Comment by mgsloan** [comment]
On the other hand, since #1265 isn't implemented yet and https://github.com/commercialhaskell/stack/tree/wip-store hasn't been merged, we could do a minor version bump release now-ish.

Hows that sound, @borsboom ?

**Comment by borsboom** [comment]
Sure, I'm back from camping and can get started on that.  This would be a release from the `master` branch, correct?

**Comment by mgsloan** [comment]
Yeah, I think it's reasonable to do a release of `master` soon!

**Comment by borsboom** [comment]
[stack-1.1.2](https://github.com/commercialhaskell/stack/releases/tag/v1.1.2) has been released.
