### ISSUE TITLE
`stack exec sudo ...` no longer works on Ubuntu 16.04

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2140]
I realize this is _probably_ not entirely Stack's fault, but the way it invokes programs makes it impossible to quote things like `stack exec "sudo program"`. It seems like the `sudo` is over-eager in some new version that came with 16.04.

Since this is not an entirely unheard of pattern (cf. Snowdrift issues — they mention `stack exec sudo`), it's a bit worrying that a popular distro upgrade broke this. It caused problems for us when writing the final chapter of the book.

Still not entirely sure of what's causing this, lost a couple hours to it.

**Comment by snoyberg** [comment]
The pattern in Stack is to do `stack exec -- sudo program`, closing.
