### ISSUE TITLE
Need means to propagate haddock-specific command-line options, e.g. "--source-entity-line"

### ISSUE THREAD

**Issue by kostmo** [commercialhaskell/stack#2144]
Instead of re-publishing a copy of the syntax-highlighted source code with the documentation, I would like to instead link to the source code as hosted on BitBucket via the `--source-entity-line` option.

There doesn't appear to be a way to pass in options to `haddock` from the `stack` command, in contrast with the mechanism `--test-arguments` that is able to forward arbitrary options to a test program.

**Comment by mgsloan** [comment]
Makes sense! Could either be accomplished much like existing options or via https://github.com/commercialhaskell/stack/issues/652

**Comment by Gabriel439** [comment]
Yes, we've been wanting this, too, so that we could pass through `haddock`'s `--qual` option

**Comment by mgsloan** [comment]
@yogsototh just implemented this as a new `--haddock-arguments`!  So this is now available on HEAD

**Comment by Gabriel439** [comment]
Thanks! :)
