### ISSUE TITLE
Stack setup fails with busybox tar

### ISSUE THREAD

**Issue by kfigiela** [commercialhaskell/stack#2146]
`stack setup` relies on compression autodetection feature of `tar`. However, some versions of `tar` (i.e. that one shipped with busybox or Alpine Linux) don't autodetect compressed archives, so that Stack fails.

**Steps to reproduce**
Use GHC + Alpine Linux docker image (https://github.com/mitchty/alpine-ghc)
```shell
$ docker run --rm -it mitchty/alpine-ghc 
# apk update && apk add xz make # stack asks to install them
# stack setup --resolver ghc-7.10.2`
```

**Expected behavior:**  Stack installs GHC
**Actual behavior:** Stack fails to extract GHC source archive, as existing `tar` implementation doesn't autodetect compression. Installing GNU tar (`apk add tar`) solves is a workaround.

```shell
# stack setup --resolver ghc-7.10.2
Run from outside a project, using implicit global project config
Using resolver: ghc-7.10.2 specified on command line
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.
Running /bin/tar xf /root/.stack/programs/x86_64-linux/ghc-7.10.2.tar.xz in directory /tmp/stack-setup29074/ exited with ExitFailure 1


tar: invalid tar magic

Unpacking GHC into /tmp/stack-setup29074/ ...
```

**Comment by mgsloan** [comment]
Pinging @borsboom , thoughts on what should be done about this?  A few options:

* On failure, retry tar with a guessed format specific arg.  So, it'd see `.tar.xz` in the URL and guess to use the `-J` flag.

* Detect these tar versions and install a newer one.

**Comment by mgsloan** [comment]
@kfigiela This should now be addressed by https://github.com/commercialhaskell/stack/commit/0ae54114de8c5427858c5997b64e6b7365244962 , let me know if not
