### ISSUE TITLE
Should `stack build` automatically install the needed ghc?

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack#215]
Or should it simply suggest that you run `stack setup` in order to do that? I think we agree that the `stack build --auto-setup` flag should exist, we just need to discuss whether the default for it should be on or off.

**Comment by mboes** [comment]
> I may just need to adjust my PATH, and I could be on a bad network (cell phone WiFi, etc) so I think it is best to not install ghc by default

:+1:

**Comment by 3noch** [comment]
Is there a way to specify which GHC arch is needed?

**Comment by snoyberg** [comment]
I think the verdict is pretty clearly that we shouldn't download by default. Let's make that change, together with a config file option.

@3noch Not right now. I'm guessing you're asking regarding Windows 32-bit vs 64-bit? At @ndmitchell's recommendation, I've been avoiding 64-bit whenever possible, including in Stack.Setup (look in there for a comment about this). I don't mind making it an option to use 64-bit, but I think we have the right default currently.

**Comment by snoyberg** [comment]
Alright, default changed and `install-ghc` config option added. I'm going to consider this closed. If I missed something, speak up :)

**Comment by 3noch** [comment]
@snoyberg I see the comment! I have not had any troubles with 64-bit GHC on Windows, but my use-case is pretty light. Where/how can I start the discussion to get 64-bit Windows back?

**Comment by snoyberg** [comment]
Just open another issue and let's discuss. I'm in favor of doing it, we
just need to figure out the right defaults and ui for overriding them.
