### ISSUE TITLE
Provide a way to exclude tests

### ISSUE THREAD

**Issue by facundominguez** [commercialhaskell/stack#2150]
This is a feature request.

```
stack build --test package-a:-testsuite-a package-a:-testsuite-b
```
Should build and run all tests in `package-a`, except for `testsuite-a` and `testsuite-b` which should be ignored.

Similarly:
```
stack build --test :-testsuite-a
```
should ignore any `testsuite-a` appearing in any package.

The workaround now is to list in the command line all tests that should run:
```
stack build --test package-a:testsuite-c package-a:testsuite-d ...
```
which requires modifying both the .cabal file and the CI configuration whenever a test is added.

Flags are not convenient to use to filter test, because `stack` insists in rebuilding the package when flags change, even though they don't affect the test executables.

**Comment by mgsloan** [comment]
Good idea!

**Comment by sjakobi** [comment]
I think the `--skip` option proposed in https://github.com/commercialhaskell/stack/issues/1659 is more general and simpler, too.

**Comment by mgsloan** [comment]
Agreed!  Closing in favor of #1659
