### ISSUE TITLE
Stack SRPM

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#2156]
Unless I'm mistaken, there seems to be no Stack source RPM (SRPM) in the fpco repository. Might it be possible to add one? Perhaps simply by folding the one created by @juhp into the fpco repository: https://copr.fedorainfracloud.org/coprs/petersen/stack/.

**Comment by mgsloan** [comment]
Pinging @borsboom

**Comment by borsboom** [comment]
I don't really know anything about SRPMs (we just use [fpm](https://github.com/jordansissel/fpm) to build RPMs).  I don't object to adding it as long as somebody volunteers to maintain it (or teaches me how).

**Comment by snoyberg** [comment]
We no longer provide such packages, closing
