### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#216]
C:\Neil\hlint>stack build
    Downloading lts-2.13 build plan ...
    Downloaded lts-2.13 build plan.
    Populating index cache, may take a moment ...
    Updating package index hackage.haskell.org ...
    Cloning package index ...
    Done populating index cache.
    Checking against build plan lts-2.13
    Writing default config file to: C:\Neil\hlint\stack.yaml
    Downloading ghc-7.8.4 ...
    Downloaded ghc-7.8.4.
    InvalidUrlException "7z" "Invalid URL"

    C:\Neil\hlint>ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.3

So it tries to download GHC 7.8.4, even though I have 7.8.3 installed (which seems like a bug). It also fails to do that.

**Comment by snoyberg** [comment]
What does `stack --version` say?

**Comment by ndmitchell** [comment]
C:\Neil\hlint>stack --version
    Version 0.0.0, Git revision 6bf1ba3a7a3fdf92fa4af2ccb148ee2004dd607a (dirty)

I'm using the version from https://github.com/commercialhaskell/stack/wiki/Downloads#windows

**Comment by snoyberg** [comment]
Ouch, OK, testing now

**Comment by snoyberg** [comment]
Downloading 7.8.4 is intentional: it requires at least the tested version of GHC from the snapshot, and that LTS snapshot was built with 7.8.4. I haven't reproed that problem yet, still trying

**Comment by snoyberg** [comment]
OK, reproed, now fixing

**Comment by snoyberg** [comment]
Found the bug, slipped in after my testing:

https://github.com/commercialhaskell/stack/commit/d9f2f668958b183e506571c856889d4c6a857c96#diff-4968f87e674615592e572f2ec593e5b0L550

**Comment by snoyberg** [comment]
OK, pushed a fix for it. I'm just rebuilding everything locally and then I'll upload a new executable.

**Comment by snoyberg** [comment]
@ndmitchell I've uploaded a new binary, can you confirm that this works? Everything is running correctly for me.

**Comment by ndmitchell** [comment]
Still doesn't work:

    C:\Users\NDMIT_~1\AppData\Local\Temp\stack2856\happy-1.19.5\dist: MoveFileEx "C:
    \\Users\\NDMIT_~1\\AppData\\Local\\Temp\\stack2856\\happy-1.19.5\\dist" "C:\\Use
    rs\\NDMIT_~1\\AppData\\Local\\Temp\\stack2856\\happy-1.19.5\\dist-stack\\i386-wi
    ndows\\Cabal-1.18.1.5\\": permission denied (Access is denied.)

**Comment by ndmitchell** [comment]
In particular, `C:\\Users\\NDMIT_~1\\AppData\\Local\\Temp\stack2856` doesn't exist, but I don't know if that was because `stack` cleaned it up on exception.

**Comment by ndmitchell** [comment]
I confirm this happens repeatably.

**Comment by snoyberg** [comment]
Different issue: this only applies to `happy`, because of the terrible workaround it requires to build. The `dist` directory needs to get renamed. Testing if this is still Windows-only before fixing.

**Comment by ndmitchell** [comment]
Why is it building happy anyway? I have it installed and on my PATH. Or does it require happy build with its GHC?

**Comment by snoyberg** [comment]
It builds the version of happy in the snapshot to be on the safe side. It's also to do with the fact that build-tools fields in .cabal files are undefined, and may refer to either an executable or a package, so the fact that you have happy.exe available doesn't prove that you have the right build tool... it's quite a mess actually. Anyway, there's an easy fix I'll push immediately, and then a better one to be worked out.

**Comment by ndmitchell** [comment]
It's a mess, which is why I want to use `stack` in the first place :)

**Comment by snoyberg** [comment]
Hah, true. OK, can you pull master and see if that lets you build hlint? It seems to be working for me now.

**Comment by snoyberg** [comment]
And I'm wondering if this should be opened as a bug against directory, since the behavior on Windows and Linux is difference for `renameDirectory`. That might just be an inherent OS difference though.

**Comment by snoyberg** [comment]
Turns out that this is a documented difference in `renameDirectory`:

> On Win32 platforms, renameDirectory fails if the new directory already exists.

Anyway, the fix in place is the correct one (use `Path.parent` which is aware of the trailing-slash issue). takeDirectory was following it's documented behavior, which happens to not work well with Path's way of doing directories.

**Comment by ndmitchell** [comment]
OK, with the git version it all worked.

**Comment by snoyberg** [comment]
W00t. Thanks again for catching these, I'll add "build hlint" to the release checklist, and make sure that there aren't more commits added after we've gone through the checklist next time.

**Comment by Timp-ELS** [comment]
Hi, this seems to have resurfaced: 

Everything is Ok

Folders: 520
Files: 11779
Size:       2080675659
Compressed: 2090035200
C:\Users\pizeyt\AppData\Local\Programs\stack\x86_64-windows\ghc-8.4.3-tmp23292\ghc-8.4.3\: renamePath:MoveFileEx "C:\\Users\\pizeyt\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.4.3-tmp23292\\ghc-8.4.3\\" "C:\\Users\\pizeyt\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.4.3\\": permission denied (Access is denied.)

**Comment by dbaynard** [comment]
@Timp-ELS Which `stack` version?

**Comment by Aarskin** [comment]
@dbaynard I'm seeing this with Stack v.1.9.1 (Windows 10 Enterprise, Version 1709, Build 16299.726)

> stack --version
> Version 1.9.1, Git revision f9d0042c141660e1d38f797e1d426be4a99b2a3c (6168 commits) x86_64 hpack-0.31.0

**Comment by dbaynard** [comment]
And what's the precise error (please run with `--verbose` and paste the log)?

**Comment by Aarskin** [comment]
> stack ghci --verbose > log.txt

This isn't piping all of the output to the file; here is what gets piped (processing ghc-8.6.3.tar.xz)

[stack_ghci_failure.txt](https://github.com/commercialhaskell/stack/files/2737392/stack_ghci_failure.txt)

Here's the rest of the output that dumps to the console

[stack_ghci_failure2.txt](https://github.com/commercialhaskell/stack/files/2737398/stack_ghci_failure2.txt)
