### ISSUE TITLE
"stack config set" fails with "only set resolver is implemented"

### ISSUE THREAD

**Issue by Unode** [commercialhaskell/stack#2160]
Using `stack Version 1.1.0 x86_64 hpack-0.13.0`:

Tried:

    stack config set local-bin-path ~/bin

And obtained:

    stack: parse stack config set field: only set resolver is implemented

According to `stack config set --help` this seems like it should work.

**Comment by mgsloan** [comment]
Yep, this should be fixed, it's tracked by https://github.com/commercialhaskell/stack/issues/115

**Comment by mgsloan** [comment]
We should really have that feature more clearly marked as experimental
