### ISSUE TITLE
local-bin-path doesn't accept tilde syntax

### ISSUE THREAD

**Issue by Unode** [commercialhaskell/stack#2161]
I'm not sure if I'm doing something wrong but if I add:

    {
        local-bin-path: ~/bin
    }

to my `config.yaml` file, `stack path` complains that:

    No directory could be located matching the supplied path: ~/bin

Is there any other way to refer to this location with a relative path or something like `$HOME`?

**Comment by cheecheeo** [comment]
@Unode this works for me:
```
{
    local-bin-path: bin
}
```

**Comment by Unode** [comment]
@cheecheeo it doesn't work for me.

If I set it up like you mentioned it becomes relative to the current path.
It only works if I'm on `~/` when I run `stack install` which is hardly ever.

**Comment by sjakobi** [comment]
I think this issue would already be solved with https://github.com/commercialhaskell/stack/issues/1375.

The issue with tildes (`~`) is that they are AFAIK legal filenames in their own right, so it's never clear whether `~/x` refers to `$HOME/x` or `$PWD/~/x`.

I'm closing this in favor of #1375 but feel free to reopen this if you would like to discuss this further.
