### ISSUE TITLE
Discover .stack-work/dist/<number>

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#2164]
For ghcid I sometimes need to pass flags such as `-i.stack-work/dist/95439361/build/autogen`. Is there any way to compute the `95439361` portion? Is the highest such number always the latest value? Context at https://github.com/ndmitchell/ghcid/issues/71#issuecomment-220157981

**Comment by mgsloan** [comment]
Nope, those are hashes.  Use `stack path --dist-dir`.
