### ISSUE TITLE
Add --verbose flag

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#217]
Seems like it would help diagnose issues such as #216 if you gave a complete listing of everything you were doing, particularly what command lines you run.

**Comment by snoyberg** [comment]
Try `--verbosity debug`. @chrisdone what do you think about making `--verbose` a synonym for it?

**Comment by ndmitchell** [comment]
Also make sure you list it on the `--help` output:

    C:\Neil\hlint>stack build --verbose
    Usage: stack build [TARGET] ([--library-profiling] | [--no-library-profiling])
                       ([--executable-profiling] | [--no-executable-profiling])
                       ([--optimizations] | [--no-optimizations]) [--dry-run]
                       [--ghc-options OPTION] [--flag PACKAGE:[-]FLAG]
      Build the project(s) in this directory/configuration

**Comment by snoyberg** [comment]
If you run `stack --help`, it tells you about global options, but it seems very peculiar that we don't show *all* options for `stack build --help`. @chrisdone does that need to be fixed in optparse-simple?

**Comment by chrisdone** [comment]
There is already `-v`?

**Comment by chrisdone** [comment]
> If you run stack --help, it tells you about global options, but it seems very peculiar that we don't show all options for stack build --help. @chrisdone does that need to be fixed in optparse-simple?

Yeah, that's because those options aren't cmd-line specific. We can possibly do something in optparse-simple to re-inject these somehow.

**Comment by chrisdone** [comment]
@ndmitchell Confirm? We already have -v, but I added --verbose as the long form.

**Comment by chrisdone** [comment]
Oh, let me also do something about showing global options on subcommands.

**Comment by chrisdone** [comment]
@snoyberg @ndmitchell I don't yet see a way to make
optparse-applicative print out global options for a subcommand's
`--help` output.

The below is the best I can achieve, by moving all global options into
each command parser, if there are any.

In the case of no commands:

``` haskell
λ> let noCommandsCase args = do (opts,()) <- withArgs args (simpleOptions "" "" "" (optional (strOption (long "verbose"))) empty); print opts
λ> noCommandsCase []
Nothing
λ> noCommandsCase ["--help"]
Usage: <interactive> [--version] [--help] [--verbose ARG]

Available options:
  --version                Show version
  --help                   Show this help text
*** Exception: ExitSuccess
λ> noCommandsCase ["--verbose=true"]
Just "true"
```

In the case of commands specified:

``` haskell
λ> let commandsCase args = do (opts,run) <- withArgs args (simpleOptions "" "" "" (optional (strOption (long "verbose"))) (addCommand "build" "do the thing" pure (pure ()))); print opts; run
λ> commandsCase []
Usage: <interactive> [--version] [--help] COMMAND

Available options:
  --version                Show version
  --help                   Show this help text

Available commands:
  build                    do the thing
*** Exception: ExitSuccess
λ> commandsCase ["build","--help"]
Usage: <interactive> build [--verbose ARG]
  do the thing
*** Exception: ExitSuccess
λ> commandsCase ["build","--verbose=true"]
Just "true"
λ> 
```

**Comment by snoyberg** [comment]
Perhaps it's worth opening up an issue against optparse-applicative on this?

**Comment by chrisdone** [comment]
I'm not sure that what we're trying to do makes sense in the optparse world, but I'll open an issue to ask.

**Comment by chrisdone** [comment]
The `--verbose` long-form flag is added, so marking this issue as done, and splitting off the general question of showing global options in subcommand's `--help` output in https://github.com/pcapriotti/optparse-applicative/issues/138.
