### ISSUE TITLE
Figure out a way to get dependency info from GHC more efficiently

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2171]
Currently, we use `-ddump-hi`.  However, the result files can be quite large and I imagine cost quite a bit to synthesize, and time to parse.  This is particularly costly when there are lots of inlineable functions.

We may need to add `-ddump-deps` or something to ghc, which would contain a subset of the interface ddump.

**Comment by snoyberg** [comment]
Closing in favor of #4545 and #4541
