### ISSUE TITLE
stack-8.0.yaml doesn't work for global-project

### ISSUE THREAD

**Issue by tswilkinson** [commercialhaskell/stack#2174]
Making a new project with the stack-8.0.yaml works fine, but when I use it for `.stack/global-project/stack.yaml` I get:

    Run from outside a project, using implicit global project config
    Using resolver: nightly-2016-05-13 from implicit global project's config file: /home/tom/.stack/global-project/stack.yaml
    No .cabal file found in directory /home/tom/.stack/global-project/

Should I make a .cabal file in this folder?  What should I put in it?

**Comment by silky** [comment]
what command are you running? the `stack-8.0.yaml` in this project is for building stack itself; so i'm not sure why you'd be using that in your global-project? 

what is the contets of `/home/tom/.stack/global-project/stack.yaml` ?

i suspect you have a non-empty `packages` entry.

**Comment by tswilkinson** [comment]
I was running `stack ghci` but they all give the same output, I think.

Sorry, I thought `stack-8.0.yaml` was for anything, not just stack!  My mistake.  I literally just copied the contents of `stack-8.0.yaml` into my `.stack/global-project/stack.yaml`.  There is no `packages` section though.

**Comment by silky** [comment]
there's a `packages` section of `stack-8.0.yaml` in line 41:  https://github.com/commercialhaskell/stack/blob/master/stack-8.0.yaml

however, definitely don't copy that file to your global project :)

you should leave your global project stack.yaml quite sparse (i.e. as it was), in general (you can add more depending on what you want to do; i.e. for making later versions of GHC available; say).

for reference, here is mine:

````
cat ~/.stack/global-project/stack.yaml                                                   
# This is the implicit global project's config file, which is only used when
# 'stack' is run outside of a real project.  Settings here do _not_ act as
# defaults for all projects.  To change stack's default settings, edit
# '/home/noon/.stack/config.yaml' instead.
#
# For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
flags: {}
extra-package-dbs: []
packages: []
extra-deps: []
resolver: lts-5.17
````

you may wish to, say, update the resolver, if you feel like it.

**Comment by tswilkinson** [comment]
flags: {}
    extra-package-dbs: []
    packages: []
    extra-deps: []
    resolver: nightly-2016-05-13
    compiler: ghc-8.0.1

works!  Thanks.  Sorry for being a complete moron.
