### ISSUE TITLE
stack ghci outside of project prints error about no targets

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack#2176]
consider

```
07:17 PM noon ∈ ~>stack --version
Version 1.1.3, Git revision 8f7e62fbe3620a4b0ae5eb833cebfa50820f5050 (dirty) (3661 commits) x86_64 hpack-0.14.0
07:17 PM noon ∈ ~>stack ghci     
Run from outside a project, using implicit global project config
Using resolver: lts-5.17 from implicit global project's config file: /home/noon/.stack/global-project/stack.yaml
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?
Warning: build failed, but optimistically launching GHCi anyway
Configuring GHCi with the following packages: 
GHCi, version 7.10.3: http://www.haskell.org/ghc/  :? for help
Ok, modules loaded: none.
ϟ> 
````

glancing around the code
 - https://github.com/commercialhaskell/stack/blob/b6e01f2339a084a6345a4dfdbc4694a7168e3ae9/src/Stack/Ghci.hs#L280
 - https://github.com/commercialhaskell/stack/blob/0f1d6d1e8f86a1388b23a0b743a613adaeac406e/src/Stack/Build/Target.hs#L304

i feel like `AllowNoTargets` should be the value at this point and thus no error; but it doesn't appear to be the case, and i can't figure out why right this minute. i'm sure i'm missing something quite obvious ...

**Comment by silky** [comment]
ah

it's because it's also trying to build and `build` itself always sets `NeedTargets`; if i run with `stack ghci --no-build` then everything works fine.

**Comment by silky** [comment]
actually, i'll re-open for consideration of perhaps making it still not emit this.

options:

 - make it a warning?
 - avoid `build`ing if we're in the global project?


or is there a better idea? or just ignore this?

**Comment by mgsloan** [comment]
> avoid `build`ing if we're in the global project?

How about avoiding building if there's nothing to build.  Then there's no need to have a special case for the global project!  (very little is special about it)

**Comment by silky** [comment]
> How about avoiding building if there's nothing to build. Then there's no need to have a 
> special case for the global project! (very little is special about it)

good point; i like it!

**Comment by mgsloan** [comment]
Fixed!
