### ISSUE TITLE
stack build fails with wrong package versions when compiling using ghcjs

### ISSUE THREAD

**Issue by mkawalec** [commercialhaskell/stack#2177]
When building my package with ghcjs I get the following error

```
--  Failure when adding dependencies:
      aeson: needed (==0.11.*), 0.9.0.1 found (latest applicable is 0.11.2.0)
    needed for package email-0.1.0.0
```

but `stack solve` says that all dependencies are correct. Adding `aeson` to `extra-deps` fixes the problem, but it should be something that `stack solve` notices.

My working stack.yaml:

```
flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- async-2.0.2
- data-default-0.6.0
- ipprint-0.6
- mime-0.4.0.2
- monadIO-0.10.1.4
- rolling-queue-0.1
- sr-extra-1.46.3.1
- strptime-1.0.10
- aeson-0.11.2.0
resolver: nightly-2016-05-19
compiler: ghcjs-0.2.0_ghc-7.10.3
```

**Comment by tolysz** [comment]
@mkawalec I will be closing this ticket, could you check if it is still the issue when using any of the recommended resolvers?
https://docs.haskellstack.org/en/stable/ghcjs/

In the above example `aeson` is part of a special package set which can not be upgraded/modified after the `ghcjs-boot`. Thus this is expected.
