### ISSUE TITLE
Remove "stack ide" command

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2178]
Since we're no longer working on / maintaining https://github.com/commercialhaskell/stack-ide , it makes sense to remove it from `stack`.

**Comment by mgsloan** [comment]
Done

**Comment by chrisdone** [comment]
`stack ide targets` which is used by intero for target completion is still there though right?

**Comment by borsboom** [comment]
@chrisdone: Looks like it's still there.
