### ISSUE TITLE
Give a way to copy the dist products onto the PATH

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#218]
Assuming I'm in the `stack` source directory, I can `stack build` it, but there's no obvious way to `stack install` - copy it onto the PATH somewhere.

**Comment by snoyberg** [comment]
See #153, I think this can be closed as a duplicate.

**Comment by ndmitchell** [comment]
This is made harder because I have:

* C:\Neil\stack\.stack-work\install\i386-windows\lts-2.9\7.8.4\bin
* C:\Neil\stack\dist-stack\i386-windows\Cabal-1.18.1.5\build\Stack

These both have `stack.exe`. One is 17Mb, one is 30Mb, so they aren't the same size.

**Comment by snoyberg** [comment]
Yeah, that's Cabal behavior: it automatically strips on installation, not on build, so the copy inside .stack-work should be smaller. In #153, Roman brought up the point of stripping, and Mathieu raised concerns about losing DWARF debugging info.
