### ISSUE TITLE
Allow limiting the scope of `allow-newer`

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2189]
See https://github.com/haskell/cabal/issues/2756 .  We don't need to deal with allowing specific pkg1 <-> pkg2 constraints, though.  Instead I think it's sufficient to just list which packages are allowed to differ from the constraints placed on them.

This is clearer than `allow-newer: True` about the reason for the `allow-newer`.

**Comment by mjrussell** [comment]
This is quite an old request but I was surprised to find out cabal.project supports this while stack does not. Any chance of getting this implemented?

**Comment by mgsloan** [comment]
Hey Matt!  Agreed this would be much better than the heavy hammer that is `allow-newer: true`.  I think it would also be good to fix the naming - unfortunately `allow-newer` ignores all bounds, not just upper bounds.

**Comment by mjrussell** [comment]
Look at this small world :) 

So maybe the way forward should be to create a new flag for this new behavior that is more clearly defined and eventually depreciate the existing `allow-newer` so users can transition to a more flexible and better named option?

**Comment by fosskers** [comment]
This would be great to have.

**Comment by recursion-ninja** [comment]
Maybe try to resolve [this outstanding issue](https://github.com/commercialhaskell/stack/issues/4495) that was prematurely closed before perpetuating the poor semantics of `allow-newer`?

**Comment by isomorpheme** [comment]
It seems like this is solved now by the [`allow-newer-deps` option](https://docs.haskellstack.org/en/stable/yaml_configuration/#allow-newer-deps)? Though it is still labeled as experimental currently.

**Comment by mpilgrem** [comment]
I am closing this issue, as it was implemented in Stack 2.9.3. See also: https://github.com/commercialhaskell/stack/pull/5910.
