### ISSUE TITLE
c_poll: permission denied

### ISSUE THREAD

**Issue by agocorona** [commercialhaskell/stack#2193]
When building the last task of this Dockerfile:

     RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442 \
        && echo 'deb http://download.fpcomplete.com/debian jessie main'| tee /etc/apt/sources.list.d/fpco.list \
        && apt-get update &&  apt-get install stack -y
     RUN stack setup --allow-different-user --compiler ghc-7.10.2
     RUN apt-get install nodejs -y \
       && ln -s /usr/bin/nodejs /usr/bin/node
     RUN stack --compiler ghcjs-0.1.0.20150924_ghc-7.10.2
............
polyparse-1.11: download
polyparse-1.11: configure
polyparse-1.11: build
polyparse-1.11: copy/register
stack: c_poll: permission denied (Operation not permitted)
vector-0.10.12.3: copy/register
sendWakeup: invalid argument (Bad file descriptor)
stack: ioManagerDie: write: Bad file descriptor
The command '/bin/sh -c stack setup --allow-different-user --compiler ghcjs-0.1.0.20150924_ghc-7.10.2' returned a non-zero code: 1

**Comment by mgsloan** [comment]
Closing in favor of https://github.com/commercialhaskell/stack/issues/2194
