### ISSUE TITLE
c_poll: permission denied

### ISSUE THREAD

**Issue by agocorona** [commercialhaskell/stack#2194]
When building the last task (STEP 5) of this Dockerfile:

```
 FROM heroku/cedar
 RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442 \
    && echo 'deb http://download.fpcomplete.com/debian jessie main'| tee /etc/apt/sources.list.d/fpco.list \
    && apt-get update &&  apt-get install stack -y
 RUN stack setup --allow-different-user --compiler ghc-7.10.2
 RUN apt-get install nodejs -y \
   && ln -s /usr/bin/nodejs /usr/bin/node
 RUN stack setup --allow-different-user  --compiler ghcjs-0.1.0.20150924_ghc-7.10.2
```

............
polyparse-1.11: download
polyparse-1.11: configure
polyparse-1.11: build
polyparse-1.11: copy/register
stack: c_poll: permission denied (Operation not permitted)
vector-0.10.12.3: copy/register
sendWakeup: invalid argument (Bad file descriptor)
stack: ioManagerDie: write: Bad file descriptor
The command '/bin/sh -c stack setup --allow-different-user --compiler ghcjs-0.1.0.20150924_ghc-7.10.2' returned a non-zero code: 1

**Comment by mgsloan** [comment]
Gnarly looking bug!  Can you please post the full DockerFile?

Also,
> stack setup --allow-different-user --compiler ghc-7.10.2

Why not 7.10.3?

Also, that is old-base ghcjs, you'll want something else for any recent ghcjs code.

**Comment by agocorona** [comment]
The full docker file is the one above.
I'll try 7.10.3

**Comment by mgsloan** [comment]
Oh, I didn't see `FROM heroku/cedar` in there before. Thanks!

7.10.3 probably isn't the issue.  The ghcjs version could potentially be, not sure.

**Comment by snoyberg** [comment]
Unclear repro, and old unsupported GHC version, closing.
