### ISSUE TITLE
Better handling of case where local package is named the same as a snapshot package but does not define a library component

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2195]
There is a bit of a funky corner case where you can have a package named the same as some snapshot package, but if it doesn't define a library it doesn't shadow the snapshot.

For example, with this commit on stackage-server: https://github.com/fpco/stackage-server/commit/5142f09ad5ea790d08678894791e178ef986bfb6

If you already have hoogle-4 built, then it will actually just use that one.  Since the git repo of hoogle 5 doesn't provide a library component, it doesn't end up shadowing the snapshot hoogle-4.

If you don't have hoogle-4 built, you'll get

```
setup-Simple-Cabal-1.22.7.0-ghc-7.10.3: At least the following dependencies
are missing:
hoogle -any
```

**Comment by snoyberg** [comment]
Implemented via #3505
