### ISSUE TITLE
Detecting pkg-config versions

### ISSUE THREAD

**Issue by hamishmack** [commercialhaskell/stack#2197]
Now that the same `haskell-gi` generates bindings automatically we need to be able to detect what version a user has when building Leksah.  We are using Cabal flags in `leksah.cabal`:

```
flag gtk-318
    description:
        GTK+ is 3.18 or later

flag gtk-320
    description:
        GTK+ is 3.20 or later
```

Then later we have:

```
    if flag(gtk-318)
        pkgconfig-depends: gtk+-3.0 >= 3.18
        cpp-options:       -DMIN_VERSION_GTK_3_18

    if flag(gtk-320)
        pkgconfig-depends: gtk+-3.0 >= 3.20
        cpp-options:       -DMIN_VERSION_GTK_3_20
```

When using `cabal-install` the flags are disabled automatically when the `pkgconfig-depends` are not met.

It is not entirely satisfactory because:
- It does not work automatically with `stack` (this is the biggest drawback and why I am putting the issue here)
- You have to add a flag for every version check
- If the someone upgrades the underlying `pkg-config` library without rebuilding `haskell-gi` we will think they have newer bindings than they do.

Is there a way to make this work automatically with Stack?  Alternatively can you suggest a better way to do this detection that will work automatically with Stack?

**Comment by mgsloan** [comment]
I cannot think of a better way to do this.  For now the flags will just need to be in the user's stack.yaml I suppose.

In the future there may be something like "stack hooks" these would allow for similar things as Setup.hs, and likely be supported by a `Setup.hs` shim.  One big difference with cabal's hooks is that stack hooks would use a serialization format for info, probably yaml, and support invoking arbitrary processes for the hooks.

**Comment by mgsloan** [comment]
Copying from my [reddit comment](https://www.reddit.com/r/haskell/comments/76m4je/installing_stack_for_haskell/doiz089/):

Cabal's automatic flag resolution is a very surprising feature. It would make way more sense if automatic flags had explicit conditions. This is a feature we could support. However, the automagic flags are way too much magic when you want reliability and predictability. Yes, some convenience is sacrificed.
Unfortunately, cabal_macros.h lacks pkgconfig dependency version info. If it had it, the solution would be clear - just use CPP and no flag automagic. So, we have two clear options:

* Add pkgconfig dependency info to cabal_macros.h
* Add explicit conditionals to cabal flags

In the meantime, I suggest adding a Setup.hs configure hook which checks the pkgconfig version and sets the flag as appropriate.

@hamishmack I'd really appreciate it if you could open an issue on the cabal issue tracker , ideally implement a fix for one or both of these there?

**Comment by hamishmack** [comment]
I like the sound of `Add explicit conditionals to cabal flags`, but I imagine that is a big job.

> @hamishmack I'd really appreciate it if you could open an issue on the cabal issue tracker ,

Not sure I understand the issue well enough to explain it.

> ideally implement a fix for one or both of these there?

I wish I had that sort of time.

**Comment by hamishmack** [comment]
This is also related (from the reddit comment):

> All of the flags and extra-deps can disappear if these packages get added to stackage. Simple!

Many of them are already in stackage, but they are automatic flags. If we remove the flag and extra-dep for `gi-atk` we get:

    In the dependencies for gi-atk-2.0.14:
        haskell-gi-overloading-0.0 must match ==1.0.* (latest applicable is 1.0)
    needed due to ltk-0.16.1.0 -> gi-atk-2.0.14

If we leave the flag, but remove the `extra-deps` we get:

    - Attempted to set flag on snapshot package gi-atk, please add to extra-deps

**Comment by hamishmack** [comment]
@mgsloan I thought more about explicit conditions overnight.  Would they be more like sort of "half automatic and half manual" conditions?  Each one would flag would have a implicit condition that you can derive from the `build-depends`, `pkgconfig-depends` and `if`s in the body of the cabal file that would need to be treated manually as well as the explicit condition (which would be treated by both stack and cabal as automatic).

I think it might be better to ban `build-depends` and `pkgconfig-depends` inside `if` statements that use explicit flags.  Instead you would have to include them in the .  This way they could not be in a half automatic state.  That would make them easier to reason about and make it easier for them to be implemented in the cabal solver.

Unfortunately that would also mean all the build depends for the flag would need to be the same across all build infos in the cabal file (since you would have to put the `build-depends` in the flags section`).

Perhaps someone (who has more time than us) could write some code to work out the implicit condition for an automatic flag from existing cabal files.  Then stack could have an option to treat these as if they were explicit (where possible).  In the future if someone works out a nice way to express explicit conditions in cabal files we could update stack to use those.

**Comment by mgsloan** [comment]
> Not sure I understand the issue well enough to explain it.

Fair!

> I wish I had that sort of time.

Same!  This is why this is still an open issue, this particular problem only affects a few packages.  For things other than pkg config deps, cabal_macros.h usually provides the necessary info.

> If we leave the flag, but remove the extra-deps we get:

This is now fixed, but not yet released.

> Perhaps someone (who has more time than us) could write some code to work out the implicit condition for an automatic flag from existing cabal files.

I'm not sure how much work it would be to add automatic flags to stack.  I think a primary qualm here is that automatic is the default for flags, and this is surprising.  I found out about them after quite a few years of using cabal had already passed..

Perhaps if the automatic flag code can be adopted from cabal, then we could have explicit opt-in of automatic flag use.  I'm guessing it's not easily adaptable, because it is likely part of the solver.

**Comment by hamishmack** [comment]
I am closing because I think this will be mostly resolved by https://github.com/haskell/cabal/issues/4237

It won't be possible to change `build-depends:`, but I think that is far less important than being able to change the code for issues like https://github.com/haskell-gi/haskell-gi/issues/228
