### ISSUE TITLE
Installing "nightly" at first uses "lts" resolver

### ISSUE THREAD

**Issue by adamsmd** [commercialhaskell/stack#2198]
When setting up stack for the first time, the `--resolver` flag appears at first to not have an effect.  See for example, the following.

```
$ ./stack-1.1.2-linux-x86_64/stack setup --resolver nightly-2016-05-26
Run from outside a project, using implicit global project config
Using latest snapshot resolver: lts-6.0
Writing implicit global project config file to: /home/adamsmd/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Downloaded nightly-2016-05-26 build plan.
...
```

Notice the line `Using latest snapshot resolver: lts-6.0`.  I say "appears" because later at the `Downloaded nightly-2016-05-26 build plan.` line it seems to use the requested resolver.  I am not sure which one actually takes effect.  In either case it is confusing, and it would help if the output were clearer in this regard. (The first time I saw this, I aborted the install and tried to figure out what had gone wrong.)

Steps to reproduce are as follows.

```
$ ls ~/.stack # Make sure ~/.stack doesn't exist
ls: cannot access '/home/adamsmd/.stack': No such file or directory

$ pwd
/home/adamsmd/o/haskell/stack

$ ls
stack-1.1.2-linux-x86_64.tar.gz

$ md5sum stack-1.1.2-linux-x86_64.tar.gz 
c4d00a508ef5ca2006325035da603d4b  stack-1.1.2-linux-x86_64.tar.gz

$ sha1sum stack-1.1.2-linux-x86_64.tar.gz 
7147c2c912e7c12ebe81c6f3d3cf1e128f7b40fb  stack-1.1.2-linux-x86_64.tar.gz

$ tar -zxf stack-1.1.2-linux-x86_64.tar.gz 

$ ls
stack-1.1.2-linux-x86_64  stack-1.1.2-linux-x86_64.tar.gz

$ ./stack-1.1.2-linux-x86_64/stack setup --resolver nightly-2016-05-26
Run from outside a project, using implicit global project config
Using latest snapshot resolver: lts-6.0
Writing implicit global project config file to: /home/adamsmd/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Downloaded nightly-2016-05-26 build plan.
...
```

**Comment by mgsloan** [comment]
Thanks, good point!  We should probably move that line of output (`Using latest snapshot resolver: lts-6.0`) to elsewhere in the code, more command specific.

**Comment by mpilgrem** [comment]
I am closing this issue as Stack 2.13.1 respects the `--resolver` option with `stack setup`.
