### ISSUE TITLE
Ubuntu 16.04 package error 

### ISSUE THREAD

**Issue by Rajeshonze** [commercialhaskell/stack#2200]
Hi 
As i am trying to install libapache2-­mod-­tile on ubuntu 16.04
Before this I added repository as sudo add-apt-repository ppa:kakrueger/openstreetmap
But when i executed command sudo apt-get update . I got error 

Err:7 http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu xenial/main amd64 Packages
  404  Not Found
Err:8 http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu xenial/main i386 Packages
  404  Not Found
Ign:9 http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu xenial/main all Packages
Ign:10 http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu xenial/main Translation-en_US
Ign:11 http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu xenial/main Translation-en
Fetched 94.5 kB in 2s (39.6 kB/s)
Reading package lists... Done
W: The repository 'http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu xenial Release' does not have a Release file.
N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: Failed to fetch http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
E: Failed to fetch http://ppa.launchpad.net/kakrueger/openstreetmap/ubuntu/dists/xenial/main/binary-i386/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead

After this i am not able to install lib-apache2-mod-tile and getting error 
Unable to locate package libapache2-mod-tile

Note : I am using Ubuntu 16.04
Please help me regarding this issue. I will be very thankful for this.

**Comment by sjakobi** [comment]
This looks entirely unrelated to stack.

Please reopen if I'm wrong on this.
