### ISSUE TITLE
stack setup fails for nightly-2016-05-27 because of missing `xz` exe on OS X

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#2203]
Is `xz` really an external dependency on OS X? I recall that on Windows `stack` packages this dependency with it. I have not had this error with any other resolvers, so perhaps `stack` just started using xz files on OS X?

```bash
$ stack setup
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.0.1.
The following executables are missing and must be installed: xz
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.0

$ brew install xz
$ stack setup
# SUCCESS
```

**Comment by borsboom** [comment]
Past releases of GHC's official bindists came in both `.bz2` and `.xz` versions, and I always pointed the setup-info to the `.bz2` version on OS X for exactly this reason.  It looks like the GHC 8.0.1 bindists only come in `.xz` and it it hadn't occurred to me that this would be a problem on OS X when I updated the setup-info.  While I would much prefer to use unmodified official GHC bindists, I suppose we should probably repackage it as a `.bz2` for OS X.

**Comment by borsboom** [comment]
Ok, I've update the setup-info to use a .bz2.  Seems to work:

```
manny@eb-mbp14a:~/Downloads$ brew unlink xz
Unlinking /usr/local/Cellar/xz/5.2.2... 53 symlinks removed
manny@eb-mbp14a:~/Downloads$ hash -r
manny@eb-mbp14a:~/Downloads$ xz
-bash: xz: command not found
manny@eb-mbp14a:~/Downloads$ stack --resolver=ghc-8.0.1 setup
Run from outside a project, using implicit global project config
Using resolver: ghc-8.0.1 specified on command line
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.0.1.
Installed GHC.
stack will use a locally installed GHC
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
```

**Comment by 3noch** [comment]
Sweet!
