### ISSUE TITLE
How to pass argument with spaces to test

### ISSUE THREAD

**Issue by maxigit** [commercialhaskell/stack#2206]
I know I can pass argument to test using `--test-arguments` however, it doesn't seem to allow spaces. For example I'm trying to run one test called "empty file". I can do so running the test binary and pass `-m"empty file"`. If try do the same using stack `stack test --test-arguments -m"empty file"`, the quotes are ignored I get the following error message 

    The following target packages were not found: file
I've tried all sort of things, adding `\`, `\\`, `\\\` etc but it doesn't work.
I'm not sure if it's a problem in the parser or that the arguments are not escaped properly when passed to the executable.

**Comment by sjakobi** [comment]
Can give `stack test --test-arguments "-m\"empty file\""` a try?

**Comment by maxigit** [comment]
It works, thank !

**Comment by ghorn** [comment]
Something like `--test-arguments='-m "empty file"'` works for me

**Comment by maxigit** [comment]
It also works. In fact, I use a wrapper around stack so it's partly my fault that I couldn't make it work. Your solution work but not with my wrapper and I forgot It was there. However, it's a bit surprising that it didn't work out of the box and the work around is not that straight forward. It might be worth documenting it somewhere (or make it work without the single quotes).
