### ISSUE TITLE
Add "--no-color" option for new use of ansi color codes?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2208]
The resolution of https://github.com/commercialhaskell/stack/issues/1912 includes use of ansi color codes.  Perhaps the heuristic detection of terminal support is sufficient, but we may also want a flag.  The heuristic detection does pay attention to the `DUMB` envar set by emacs, so perhaps that's sufficient.

**Comment by kadoban** [comment]
This is implemented as `--color never` currently.
