### ISSUE TITLE
Build failure with  "ld returned 1 exit status" ---plzz help

### ISSUE THREAD

**Issue by DeepakKapiswe** [commercialhaskell/stack#2209]
Giving this error on build ....can someone help me what is going on ?

[1 of 1] Compiling Main             ( /tmp/stack3344/Setup.hs, /tmp/stack3344/Setup.o )
Linking /home/deepak/.stack/setup-exe-cache/i386-linux/tmp-setup-Simple-Cabal-1.22.5.0-ghc-7.10.3 ...
/usr/bin/ld: cannot find -lgmp
collect2: error: ld returned 1 exit status
Exit code ExitFailure 1 while running ["ghc","-clear-package-db","-global-package-db","-hide-all-packages","-package","base","-package","Cabal-1.22.5.0","/tmp/stack3344/Setup.hs","-o","/home/deepak/.stack/setup-exe-cache/i386-linux/tmp-setup-Simple-Cabal-1.22.5.0-ghc-7.10.3","-rtsopts"] in /tmp/stack3344/

**Comment by sjakobi** [comment]
Maybe you're missing the gmp library?

Try installing `libgmp-dev`.

2016-05-30 15:06 GMT+02:00, Deepak Kapiswe <notifications@github.com>:

**Comment by DeepakKapiswe** [comment]
Thanks a Lot sjakobi ....yes the same prob was there and now its ok after installing "libgmp-dev".

Problem Solved thanks again for quick response !!

**Comment by sjakobi** [comment]
@DeepakKapiswe: Can you tell me what operating system you use and in which way you installed `stack`?

If you installed `stack` through a package repository, the package should have had a dependency on `libgmp-dev`.

**Comment by DeepakKapiswe** [comment]
I use debian 8.2 32 bit
and I Installed stack by downloading .deb files.

**Comment by borsboom** [comment]
@DeepakKapiswe Where did you find a 32-bit `.deb`?  We only release 64-bit `.deb`s, so it must have come from a third-party.

**Comment by DeepakKapiswe** [comment]
Extremely sorry... actually I have downloaded this file <stack-1.1.2-linux-i386-gmp4.tar.gz> from this link  <http://docs.haskellstack.org/en/stable/install_and_upgrade/#linux> and just followed the instructions.

**Comment by sjakobi** [comment]
@borsboom: I think it would be a good idea to list the packages/libraries that are necessary for using stack and ghc in the installation guide.

Alternatively, if there's a good external source, we could have a link to that?!

**Comment by borsboom** [comment]
I've added the requirements and instructions how to install them on Fedora/CentOS and Debian/Ubuntu to the installation guide.

**Comment by sjakobi** [comment]
Awesome! Thanks!
