### ISSUE TITLE
stack init ignores `--stack-yaml`

### ISSUE THREAD

**Issue by hpdeifel** [commercialhaskell/stack#2216]
I frequently want to try out different resolvers and settings in temporary stack.yaml files, so I'd like to do

```
stack init --stack-yaml tmp.yaml
```

Expected results: A new file tmp.yaml is created and initialized like `stack init` would do for `stack.yaml`.

Actual results: stack-1.1.2 gives me:

```
Stack configuration file stack.yaml exists, use 'stack solver' to fix the existing config file or '--force' to overwrite it.
```

**Comment by mgsloan** [comment]
Good idea!  PRs appreciated! :)

**Comment by NorfairKing** [comment]
Any progress on this?

**Comment by snoyberg** [comment]
This command will now generate an error about `--stack-yaml` being unsupported for `stack init` and `stack new`.
