### ISSUE TITLE
stack repl doesn't search in test subfolder

### ISSUE THREAD

**Issue by TimoFreiberg** [commercialhaskell/stack#2218]
I want to write tests for different modules in separate test modules and import them in a main test file, `Spec.hs`.

**Steps to reproduce**
1. Run `stack new blah` and `cd blah`
2. Run `echo "module A where" > test/A.hs`
3. Run `echo "import A" > test/Spec.hs`
4. Run `stack repl` and enter `:l test/Spec.hs` 

**Expected:**

Loading `Spec.hs` in `stack repl` works.

**Actual:**

Test modules imported in `Spec.hs` aren't found since the `test/` directory is not in the module import search paths.

Are there workarounds other than typing `:set -itest` in the repl?

**Comment by mgsloan** [comment]
This is because `stack ghci` with no arguments means "load executable and library components", so it does not include the test dir.  Try `stack ghci --test`.
