### ISSUE TITLE
Have verbose stack log indicate that it was built via cabal-install, and if so, which dependencies were used 

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2222]
When installed via cabal-install, `stack` could potentially exhibit different behavior when compiled with different dependency versions.  This sometimes makes it troublesome to diagnose stack issue reports, as it can take a long time to reach the eventual conclusion that a dependency is to blame.

See the most recent instance here - https://github.com/commercialhaskell/stack/issues/2182

When run in verbose mode, stack should warn that it was built via cabal-install, and enumerate all the dependencies chosen.  This way it's apparent that a difference in dependencies might be a suspect cause of the issue.  We may also want a shorter warning when run without `-v`.

Similarly, when stack is built with stack, we should log which build configuration was used.

**Comment by borsboom** [comment]
In conjunction with #1238, we could also log whether they're using an official binary.

**Comment by Blaisorblade** [comment]
Closing. I'd say this was fixed by #2222 (except for #2450) and that 

> In conjunction with #1238, we could also log whether they're using an official binary.

is (now) tracked by #1238.
