### ISSUE TITLE
Can't specify --test-arguments more than once

### ISSUE THREAD

**Issue by cblp** [commercialhaskell/stack#2226]
```
$ stack test --test-arguments "a b" --test-arguments "c d"
Invalid option `--test-arguments'
```

stack=1.1.2

expected: testArguments == ["a", "b", "c", "d"]

**Comment by mgsloan** [comment]
I'm not opposed to this, but what's the intended usecase?  I can also see value in the reset semantics and this would be a behavior change.

**Comment by cblp** [comment]
Intended usecase:

1. Write a script with persistent arguments

        # ./test.sh
        stack test --test-arguments="--report --verbose" "$@"

2. Invoke it with ad hoc arguments

        ./test.sh --test-arguments="--parallel --filter=abc"

**Comment by mgsloan** [comment]
Makes sense!  I think the resolution of this ticket should be that all command-argument like options have this combining semantics.

**Comment by snoyberg** [comment]
See #4748
