### ISSUE TITLE
Cannot generate internal documentation

### ISSUE THREAD

**Issue by osbugs** [commercialhaskell/stack#2229]
Perhaps I did miss something, but it seems to me that generating internal documentation is not possible.

With cabal, I just use the following command line: `cabal haddock --internal`. Is there some similar switch for stack?

**Comment by osbugs** [comment]
I think this bug/feature request is distinct from #2165. The difference is that I do not want to provide arguments to haddock but I do want haddock to be run on a different target than the one provided.

**Comment by mgsloan** [comment]
I see!  Yes, currently I don't think we have `--internal`, but it'd be a great thing to add.  Not sure if we want to call it that, though.

**Comment by taphu** [comment]
Hi guys. I really needed this for a project I'm working on, so I went ahead and took a swing at it. This is my first contribution to stack, so let me know if there is anything I missed in the way of completeness/style/policy. Thanks.

**Comment by osbugs** [comment]
Updated PR in #2598

**Comment by sjakobi** [comment]
Closed via #2598
