### ISSUE TITLE
doesn't seem to work on Ubuntu 12.04

### ISSUE THREAD

**Issue by b21e** [commercialhaskell/stack#223]
Apparently didn't found the key at the given url?

**Comment by snoyberg** [comment]
I'm assuming you followed the steps at https://github.com/commercialhaskell/stack/wiki/Downloads#ubuntu, correct? Can you clarify what exact error message you got?

Pinging @dysinger

**Comment by b21e** [comment]
Did run the script again. Everything worked fine now!
Thanks!

**Comment by snoyberg** [comment]
No problem, I think someone corrected a typo since you tried it last.
