### ISSUE TITLE
stack new to read from ~/.stack/templates/...

### ISSUE THREAD

**Issue by sboosali** [commercialhaskell/stack#2231]
given:

```
~/.stack/templates/my-template.hsfiles
```

this should work:

```
$ stack new my-package my-template
```

or:

```
$ stack new my-package my-template.hsfiles
```

**Comment by mgsloan** [comment]
See also https://github.com/commercialhaskell/stack/issues/1595 and https://github.com/commercialhaskell/stack/issues/1980#issuecomment-204156582

**Comment by snoyberg** [comment]
This does in fact now work.
