### ISSUE TITLE
Changing resolver from lts-5.11 to lts-6.1 triggers "Missing build tools" error

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#2235]
Snowdrift at [eabedbd](https://github.com/snowdriftcoop/snowdrift/commit/eabedbda11077fe7edff3b88cd9a633efd61cd61) builds fine. If I change to using lts-6.1, however, I get the error that mentions #595 (reproduced below).

```
$ stack build
No packages found in snapshot which provide a "hsc2hs" executable,
which is a build-tool dependency of "skein". Missing build-tools may be
caused by dependencies of the build-tool being overridden by
extra-deps. This should be fixed soon - see this issue
https://github.com/commercialhaskell/stack/issues/595

No packages found in snapshot which provide a "hsc2hs" executable,
which is a build-tool dependency of "postgresql-libpq" Missing
build-tools may be caused by dependencies of the build-tool being
overridden by extra-deps. This should be fixed soon - see this issue
https://github.com/commercialhaskell/stack/issues/595

While constructing the BuildPlan the following exceptions were
encountered:

--  Failure when adding dependencies:
      hjsmin: needed (>=0.1 && <0.2), 0.2.0.1 found (latest applicable is 0.1.5.3)
    needed for package Snowdrift-0.1.4 with flags:
      dev: True
```

**Comment by sigrlami** [comment]
Noticed this in docker when moved from 5.15 to 6.5, local build doesn't bring this error

**Comment by chreekat** [comment]
Update: the error about hsc2hs is spurious. There's nothing wrong with it. The actual error preventing the build was at the bottom: Snowdrift.cabal needed to relax its restriction on hjsmin.

I think the issue still stands, but it is about **spurious errors**.

**Comment by mgsloan** [comment]
I've fixed this - it now checks if the tool is on the PATH before warning.
