### ISSUE TITLE
Can't pass extra cabal parameters for readline on Mac OS X

### ISSUE THREAD

**Issue by edyu** [commercialhaskell/stack#2237]
My project needs _readline_, so I added a line under **build-depends**. However, on Mac OS X, _readline_ needs the Gnu c _readline_ to be installed and if I use _homebrew_ to install it, cabal install would need the following extra flags: --extra-include-dirs=/usr/local/opt/readline/include --extra-lib-dirs=/usr/local/opt/readline/lib readline --configure-option=--with-readline-includes=/usr/local/opt/readline/include --configure-option=--with-readline-libraries=/usr/local/opt/readline/lib
How do I pass to Stack those extra flags in order to build _readline_ for my project?

I get the following error if I don't supply those flags:
    Linking /private/var/folders/pf/fjqk_sm161dc2_hnvqr99q280000gn/T/stack95780/readline-1.0.3.0/.stack-work/dist/x86_64-osx/Cabal-1.22.5.0/setup/setup ...
    Warning: defaultUserHooks in Setup script is deprecated.
    Configuring readline-1.0.3.0...
    checking for gcc... gcc
    checking for C compiler default output file name... a.out
    checking whether the C compiler works... yes
    checking whether we are cross compiling... no
    checking for suffix of executables... 
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking for GNUreadline.framework... checking for readline... no
    checking for tputs in -lncurses... yes
    checking for readline in -lreadline... yes
    checking for rl_readline_version... yes
    checking for rl_begin_undo_group... no
    configure: error: readline not found, so this package cannot be built
    See `config.log' for more details.

**Comment by mgsloan** [comment]
Are these config options sufficient? http://docs.haskellstack.org/en/stable/yaml_configuration/#extra-include-dirsextra-lib-dirs

**Comment by edyu** [comment]
No,they are not. They are meant to be used when compiling my own package not for being part of the cabal dependencies in **build-depends**.

**Comment by edyu** [comment]
Some new hooks may need to be exposed in order for build dependencies to be customized.

**Comment by mgsloan** [comment]
These options go in your stack build configuration.

**Comment by edyu** [comment]
I have them in my stack build configuration. They are not enough. Also
there is a bug in parsing the cabal file for extra-include-dirs in that
it's not recognized.

Even if I add them to the yaml file directly, I'm still missing a way to
pass in --configure-option.

**Comment by mgsloan** [comment]
Yeah, that's tracked by https://github.com/commercialhaskell/stack/issues/1438 which I've bumped to P1

**Comment by aymanosman** [comment]
@edyu  See [this](http://stackoverflow.com/a/43189865/1545549) stackoverflow answer.


Say your are on OSX


```
$ brew install readline
[...]
For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/readline/lib
    CPPFLAGS: -I/usr/local/opt/readline/include
```

Now you know where the library got installed you can set some environmental variables that `./configure` will pick up

```
LDFLAGS=-L/usr/local/opt/readline/lib \
CFLAGS=-I/usr/local/opt/readline/include \
stack install readline --extra-include-dirs=/usr/local/opt/readline/include --extra-lib-dirs=/usr/local/opt/readline/lib
```

**Comment by edyu** [comment]
@aymanosman that actually works! thank you.
Back on this issue: I still don't think it was properly fixed as technically those should be specified somehow in a config file instead of specifying in the command line.

**Comment by brendanzab** [comment]
So I've put the following in my `~/.stack/config.yaml`:

```yaml
extra-include-dirs:
- /usr/local/opt/readline/include
extra-lib-dirs:
- /usr/local/opt/readline/lib
```

Alas readline still won't build. Do I need to put the environment variables somewhere? If so, how do I scope that to the build of readline specifically without going via the command line?
