### ISSUE TITLE
Use Stack's GHC version when using --nix and a custom shell file

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#2243]
Stack's Nix support has two modes:

1. get Stack to auto-generate a `shell.nix` shell file based on stack.yaml data.
1. write the `shell.nix` file manually and point Stack to that.

In the former case, Stack generates a shell file that pulls in whatever version of GHC it sees fit (i.e. something matching the current snapshot). But in the latter case reproducibility can be compromised, because the GHC version used is whatever corresponds to the `ghc` top-level attribute in Nixpkgs. That version changes regularly. The user can always hardcode a specific version, but best to DRY and let Stack decide, as in (1).

The right way to do this is expect the `shell.nix` file to express a function. Then Stack can use

```
$ nix-shell --arg ghc <some-ghc-version-that-stack-chooses>
```

when entering the shell. This is completely backwards compatible with existing shell.nix files that are not function expressions. In that case the `--arg ghc` just gets ignored.

**Comment by YPares** [comment]
Given it's backward-compatible, I directly pushed on master a commit implementing this and updating the docs

**Comment by YPares** [comment]
Ok, I actually didn't take into account the current behaviour of `haskell.lib.buildStackProject` nix function. See https://github.com/NixOS/nixpkgs/pull/15989
So I'm reopening the issue

**Comment by YPares** [comment]
Ok, this has been statued in NixOS/nixpkgs#15989, so I'm closing the issue.
I updated stack's doc accordingly. For now, until the NixOS PR is merged the `ghc` field will just be ignored.
