### ISSUE TITLE
Reduce disk space

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack#2244]
My 64GB laptop SSD is getting rather full and i saw that stack takes up a lot of diskspace. I tried putting all my projects on the same LTS version and clear out the snapshot folder. Also i delete a tar.xz file in the programs folder. Is there anything else that can be done?

**Comment by mgsloan** [comment]
`stack clean --full` in your different projects to remove all build files.

NOTE: only do that on >= 1.0.4.3, see https://github.com/commercialhaskell/stack/issues/2000

**Comment by sid-kap** [comment]
@flip111, in your experience is it safe to delete the `~/.stack/snapshots/x86_64-linux/lts-XXX` folder if `lts-XXX` is a snapshot that I no longer care about? I think I tried this at some point, but it led to weird ghc-pkg errors related to alex/happy when I was using a different lts later on.

**Comment by sid-kap** [comment]
Actually, looks like this was discussed at https://github.com/commercialhaskell/stack/issues/1847 and https://github.com/commercialhaskell/stack/issues/133. I'll just take a look at the discussion there. Sorry for the noise.

**Comment by flip111** [comment]
indices is now 1.3G .. perhaps anyone knows a list of directories/files that are safe to remove? Could just store that as a shell script and run that once in a while ...

**Comment by flip111** [comment]
> stack clean --full in your different projects to remove all build files.

Then i have to go into all those projects. But i mainly want to clean out lts versions which i'm no longer using and also tar.xz archives if they are not needed. Why are those `tar.xz` files kept actually?

**Comment by flip111** [comment]
```
104M	build-plan
14M	build-plan-cache
12K	config.yaml
1,5M	global-project
1,3G	indices
26M	loaded-snapshot-cache
22M	precompiled
5,4G	programs
45M	setup-exe-cache
108K	setup-exe-src
3,9G	snapshots
52K	templates
```

11G total .. it's quite a lot

**Comment by flip111** [comment]
The binaries in `~/.stack/snapshots/x86_64-linux/*/*/bin` also take a lot of space. Are they still needed after being copied to `~/.local/bin` ?

**Comment by flip111** [comment]
What about when running this function https://github.com/commercialhaskell/stack/blob/6ec4ac4ee5016e2ecd86af2abfa722b94d2a56c3/src/Stack/Setup.hs#L938-L956 the archive gets removed from disk ?
