### ISSUE TITLE
Build output munging breaks the network build on Windows

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#2245]
The `network` package doesn't build on Windows with a default `stack.yaml`:

```
$ stack init
$ stack setup
$ stack build
[...]
network-2.6.2.2: build
Preprocessing library network-2.6.2.2...

InvalidAbsFile "C:\\network\\<command-line>"
Command exited with code 1
```

The reason this happens is because by default Stack munges build output to remove spurious TH output and to absolutize file names. It's the absolutization that's the problem here.

A workaround is to set `hid-th-loading: false` in the `stack.yaml`. This works because absolutization is done iff TH output suppression is performed, for some reason. That's just a workaround though: ideally the absolutization code should be fixed.

**Comment by mboes** [comment]
Possibly related: #1671.

**Comment by borsboom** [comment]
I know at some time in the past I made it more forgiving about invalid paths in the GHC output (Stack should just ignore them), but I suspect that got lost in refactoring to use path-io.  I should have made an integration test back then.

**Comment by mgsloan** [comment]
Haven't tested on windows, but I've made it so it won't munge the path when there's a parse error.
