### ISSUE TITLE
Cannot decode byte '\xf8': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

### ISSUE THREAD

**Issue by mageshb** [commercialhaskell/stack#2248]
Stack is unable to fetch the following packages when the package index is pointing to Hackage
download-prefix: https://hackage.haskell.org/package/
http: https://hackage.haskell.org/00-index.tar.gz

memory-0.13
bytestring-builder-0.10.8.1.0
cereal-0.5.2.0
auto-update-0.1.4
directory-1.2.6.2

Stack version:
 Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
Resolver: nightly-2016-06-06
GHC: 8.0.1

I changed it to point to FPComplete's repo and then things started to work fine normally
Changes were
 download-prefix: https://s3.amazonaws.com/hackage.fpcomplete.com/package/
 http: https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz

**Comment by borsboom** [comment]
What was the exact error?  I recently made a fix related to downloading from Hackage: https://github.com/commercialhaskell/stack/commit/311b8584cefd99579a48f22954b82a6d0071edb1.  Can you try that commit?

**Comment by manojgudi** [comment]
I am getting similar issue
Here's my stack.yaml : http://lpaste.net/169985

The exact error when I do *stack build* is
$ stack build
 stack: Cannot decode byte '\x8b': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream

Using upgraded stack 1.1.2  Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b on ubuntu 16.04 amd64

**Comment by sjakobi** [comment]
@manojgudi: The error you're reporting has been fixed on `master`.

You can upgrade with `stack upgrade --git` but that will cause all your `extra-deps` to rebuild after the upgrade, and very likely again after an upgrade to the next released version.

**Comment by sjakobi** [comment]
As I can confirm the fix, I'm closing this. But please reopen this in case the issue reappears.
