### ISSUE TITLE
Auto-detection for nix?

### ISSUE THREAD

**Issue by fmthoma** [commercialhaskell/stack#2249]
My problem: I have two dev machines, one running NixOS and one running Ubuntu. On the NixOS machine, I want to use `stack --nix` for all projects, on the Ubuntu machine `stack` without nix support.

Setting
```yaml
nix:
  enable: true
```
in the `stack.yaml` forces everyone to use stack with nix, even if it is not installed, like on my Ubuntu machine. So using `enable: true` limits portability of the build to systems where nix is available.

```yaml
nix:
  enable: false
```
on the other hand forces me to always add `--nix` explicitly on my NixOS machine, which does not play well with some tooling (e.g. the new [intero](http://commercialhaskell.github.io/intero/) emacs mode, which just calls `stack` and not `stack --nix`).

Proposal: with `enable: true`, stack could check whether nix is available, and otherwise fall back to normal behavior. That way, `stack.yaml` files would be portable between nix users and others.

**Comment by YPares** [comment]
@fmthoma Actually you can now set 
```yaml
nix:
    enable: true
```
in your `~/.stack/config.yaml` and just leave out the `enable` in the project configuration.
I think it's included in the last release.

**Comment by fmthoma** [comment]
@YPares Thank you, that is an even better solution! Please add this to the documentation (https://github.com/commercialhaskell/stack/blob/master/doc/nix_integration.md)!

One thing though: I have to depend on an extra library in my `stack.yaml` (which is a problem on its own, since the `terminfo` library cannot be built without this):
```yaml
nix:
  packages [ ncurses ]
```
This seems to silently also turn on the `enable: true` flag, overriding the global configuration. Which means that I am still stuck with the problem that I cannot use the same `stack.yaml` both on NixOS and non-nix systems at the same time :-(
So it would be great if the presence of the `nix` section (or `nix: packages`) would not silently force the `nix: enable` flag...

**Comment by YPares** [comment]
@fmthoma Normally this has been fixed by https://github.com/commercialhaskell/stack/pull/2080
What is your version of stack?

**Comment by fmthoma** [comment]
@YPares 1.0.2 (which comes with NixOS 16.03), so I will just have to wait for 1.1.0 to arrive in NixOS stable. Thank you for the info!

**Comment by YPares** [comment]
Welcome :)
