### ISSUE TITLE
Add upload support

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#225]
Should be based on `stackage-upload`, and ultimately support GPG signature uploads to sig archive.

**Comment by gregwebs** [comment]
Can stackage-upload stay separate and `stack upload` would install stackage-upload and invoke it?

**Comment by snoyberg** [comment]
We could go that route. What's the motivation?

**Comment by gregwebs** [comment]
The main motivation is really to experiment with keeping up the modular architecture of `stackage-*`. 

Minor points are that it can
* avoid bloat: The majority of packages built by stackage will be applications that are not uploaded to hackage
* make https upload more accessible to those not using `stack`. (once this functionality is merged, there will not be a desire to maintain `stackage-upload`).

The main downside of this approach is

* introducing an extra step of installing stackage-upload which could fail (but it should succeed if we peg dependencies)
* complicating feature discovery.

The latter point was a big issue for `stackage-cli`. However, if `stack` knows ahead of time that the upload functionality exists, then this seems solvable.

This modular architecture means that `stackage-upload` development can occur independently of `stack` This could actually create downside if `stackage-upload` wants to ask questions to `stack`, but I don't think it does.

**Comment by snoyberg** [comment]
It seems like there's a much simpler option available if we want: depend on the library exposed by `stackage-upload`. I like the fact that we have a batteries-included tool now, I'm hesitant to go in the opposite direction.

That said, I'm not even sure if I want to depend on an external library instead of just including the code here.

And I'm not concerned about bloat: the addition of the necessary 200-ish lines of code will not add any significant load to the binary size or source size.

**Comment by gregwebs** [comment]
Batteries included is definitely good. The goal with the modular architecture is to supply that same experience for most features, only adding a little delay sometimes to install a package needed for extra functionality.

But I can see how it is probably a lot easier to just add the module into `stack` in this case.

**Comment by snoyberg** [comment]
Added in cf8716911c63b1ba7535b52fed8b696aed5e63c9
