### ISSUE TITLE
Auto-add extra-deps

### ISSUE THREAD

**Issue by tonyday567** [commercialhaskell/stack#2250]
Is there an easy way to get stack to add extra-deps automatically?  The suggestion is always right, and since extra-deps propagate down-stream, leads to an awful lot of boiler-plate.

**Comment by mgsloan** [comment]
Yeah, it's a good idea.  Dupe of https://github.com/commercialhaskell/stack/issues/115

The suggested extra-deps aren't always right.  They could cause constraints that don't work out.
