### ISSUE TITLE
stack solver does not consider flags when looking at the GHC dependency

### ISSUE THREAD

**Issue by nomeata** [commercialhaskell/stack#2253]
I have this cabal fragment:

```
Flag ghc_7_7

Flag ghc_8_0

Library
  if flag(ghc_7_7)
    build-depends: ghc >= 7.7 && < 8
    cc-options: -DGHC_7_7
    cpp-options: -DGHC_7_7
  else
    if flag(ghc_8_0)
      build-depends: ghc >= 8
      cc-options: -DGHC_8_0
      cpp-options: -DGHC_8_0
    else
      build-depends: ghc < 7.7
```

yet I get

```
$ stack solver --resolver nightly  --update-config
Selected resolver: nightly-2016-06-07
Using configuration file: stack.yaml
Using cabal packages:
- ghc-heap-view.cabal

Resolver 'nightly-2016-06-07' does not have a matching compiler to build some or all of your package(s).
ghc-8.0.1 cannot be used for these packages:
    - ghc-heap-view
ghc version 8.0.1 found
    - ghc-heap-view requires >=7.7 && <8

This may be resolved by:
    - Using '--resolver' to specify a matching snapshot/resolver
```

It looks as if the solver special-cases dependencies on the `ghc` library, and does not take flag resolution into account here.

**Comment by mgsloan** [comment]
Is it possible that you're getting bit by https://github.com/commercialhaskell/stack/issues/1313 ?

For plain flags, Cabal parses them as `automatic: True` + `default: True`.  Since stack ignores the automatic stuff, this means that plain flags default to `True`.

We should probably change that, but it would be a behavior change..

**Comment by nomeata** [comment]
I was under the impression that cabal solver (in contrast to cabal build) would figure out flag assignments, as in the cabal-install world, that is part of dependency resolution. If that's not the case, this issue can be closed.

**Comment by mgsloan** [comment]
What's your stack version?  I can not find the error message text in HEAD.

There is indeed some compiler specific logic.  In HEAD, the issue is probably here: https://github.com/commercialhaskell/stack/blob/96fc30325a2adcd22dc08bdb8cf5bbe7d55fce4b/src/Stack/BuildPlan.hs#L739

**Comment by nomeata** [comment]
Version 1.1.2 x86_64 hpack-0.14.0

**Comment by mgsloan** [comment]
Happily, can no longer repro:

```
mgsloan@computer:~/fpco/test-stack/issue2253/ghc-heap-view$ stack solver --resolver nightly
Selected resolver: nightly-2017-03-17
Downloaded nightly-2017-03-17 build plan.    
Using configuration file: stack.yaml
Using cabal packages:
- ghc-heap-view.cabal


The following changes will be made to stack.yaml:
* Resolver changes from lts-8.5 to nightly-2017-03-17
To automatically update stack.yaml, rerun with '--update-config'
```
