### ISSUE TITLE
Only run hpack on local packages?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2255]
See https://github.com/commercialhaskell/stack/issues/2254 .  While the root cause is hpack's name defaulting, perhaps we shouldn't be using hpack with hackage packages in the first place.  Instead, it makes sense to use the direct cabal info even if a hpack file is present.

It's a bit weird that an unpacked package could act differently if the cabal file generated via hpack is different than the tarball cabal file.  In practice, this shouldn't happen much, and likely not problematic when it does, so I think it's worth it.

**Comment by quasicomputational** [comment]
Would this apply to `extra-deps` coming from Github too? I agree it makes no sense to run hpack on a tarball from Hackage, but I suspect many (if not most) projects using hpack don't commit the generated `.cabal` files. Maybe an explicit toggle to run hpack or not makes sense for dependencies coming from a repo or a tarball or other non-Hackage sources.

**Comment by borsboom** [comment]
Another reason to ignore `package.yaml` for Hackage packages: metadata updates on Hackage will update the `.cabal` file but not the `package.yaml`, so the two can be out of sync.

**Comment by dbaynard** [comment]
> extra-deps for github

#4267 is relevant here

**Comment by snoyberg** [comment]
We explicitly have requests to support `package.yaml` files from non-local sources, so closing. See #4439
