### ISSUE TITLE
Create default stack.yml with documentation comments and commented out options

### ISSUE THREAD

**Issue by taladar** [commercialhaskell/stack#226]
Many popular open source projects ship with config files with all or most available options in the file in comment form with documentation comments in between. It would probably be helpful if stack did the same.

**Comment by snoyberg** [comment]
Good idea. I'm going to put this to a later milestone as we'll almost certainly be tweaking the configuration file options in the next few weeks.

**Comment by snoyberg** [comment]
Implemented, thanks for the idea!
