### ISSUE TITLE
Deprecate specification of compiler resolver with only major version ("resolver: ghc-8")

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2260]
Major-only versions get interpreted like `ghc-8.0.0.0`.  This is inconsistent with resolvers like `lts-5`, which means the latest `lts-5.`

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time. A GHC snapshot is interpreted like a package version. So, `ghc-8` does not equate to `ghc-8.0.0.0`.
