### ISSUE TITLE
Check out git packages to a better dir name

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2261]
See https://github.com/commercialhaskell/stack/issues/2254 and https://github.com/sol/hpack/issues/109

Beyond fixing this issue, this is nice because it makes it clearer what these paths are.  As is, the paths can appear in lots of places without it being clear which package they are for / from.

**Comment by mitchellwrosen** [comment]
What should the path contain? Since we don't know the package name(s) contained within before downloading and building, does that mean the only thing we have is the URL?

But the problem with that is `http://foo.com/../my-package.git` is a valid url (I think) but an invalid `Path Rel Dir`

**Comment by sjakobi** [comment]
Maybe [`System.FilePath.makeValid`](https://hackage.haskell.org/package/filepath-1.4.1.0/docs/System-FilePath-Posix.html#v:makeValid) could help us here.

**Comment by mgsloan** [comment]
Yeah, that is a bit tricky, could try using the last component of the URL.

**Comment by snoyberg** [comment]
I believe the way Pantry clones Git repos fully addresses this, closing
