### ISSUE TITLE
Stack overwrites .cabal file when using haskeleton template

### ISSUE THREAD

**Issue by YPares** [commercialhaskell/stack#2274]
I'm using stack `1.1.2 x86_64 hpack-0.14.0` on OSX.
After creating a project with `stack new test haskeleton`, I edit `library/Example.hs`
to contain `import Control.Monad.Reader`
and add `mtl` to the build deps in `test.cabal`

Then `stack build` fails with:
```
/Users/yves/plop/library/Example.hs:4:8:
    Could not find module ‘Control.Monad.Reader’
    Use -v to see a list of the files searched for.
```

And if I look at the `test.cabal` the mtl mention is gone! The cabal file has been edited back to its original version.

I don't have this problem with the default stack template.

**Comment by YPares** [comment]
Okay, I've been able to reproduce on Ubuntu too.

**Comment by YPares** [comment]
Even voiding completely the cabal file yields the same result: the cabal file is completely re-generated before stack attempts to build.

**Comment by YPares** [comment]
Ok, I've been told that it's normal and that I'm missing the point of hpack here.
Sorry, closing the issue!

**Comment by tylerjl** [comment]
I hit this exact problem and couldn't figure it out until I appended a newline to `stack.yaml`, does `stack build` choke with unexpected formatting in `stack.yaml`?
