### ISSUE TITLE
A command to update the project resolver

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2276]
It would be nice if one could update the resolver for a project in one step while keeping all the other settings.

Possibly the `extra-deps` should be filtered for now redundant entries.

cc @jwaldmann

**Comment by harendra-kumar** [comment]
We have two commands related to this right now:
* `stack config set resolver` sets the resolver and does nothing else
* `stack solver --resolver`  (with the fix for #2252) changes the resolver and adjusts the extra-deps

**Comment by sjakobi** [comment]
Ah thanks, I hadn't been aware that `stack config set resolver lts` would pretty much do what I want. It does reformat the stack.yaml though and deletes the comments.

Looks like `stack solver --resolver` could work well once #2252 is fixed.

Closing as duplicate of #2252.
