### ISSUE TITLE
changing ghc-options in stack.yaml should trigger a rebuild

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/stack#2277]
When I add or change a `ghc-options` section in my stack.yaml, like this
```
ghc-options:
  my-project: -fno-omit-yields
```
where `my-project` is the current (local) package, I expect that the next `stack install` rebuilds this project, but it does not.

**Comment by harendra-kumar** [comment]
I too have encountered this many times. I have to do a stack clean when I change any compiler flags e.g. when I add  or remove `-fllvm`.

**Comment by jwaldmann** [comment]
Ok, thanks.

**Comment by mgsloan** [comment]
This is tracked by https://github.com/commercialhaskell/stack/issues/2063
