### ISSUE TITLE
Documentation of profiling options and behavior of --profile

### ISSUE THREAD

**Issue by gromakovsky** [commercialhaskell/stack#2285]
As a user of `stack` I find profiling options of `stack build` command a little confusing. There are three options:

```
  --profile                Enable profiling in libraries, executables, etc. for
                           all expressions and generate a profiling report in
                           exec or benchmarks
  --[no-]library-profiling Enable/disable library profiling for TARGETs and all
                           its dependencies
  --[no-]executable-profiling
                           Enable/disable executable profiling for TARGETs and
                           all its dependencies
```

If we want to profile something, we need to do two things: compile it with proper arguments (e. g. `-prof`) and run it with proper RTS options. It is not clear if these options (I mean profiling options mentioned above, not RTS options) affect both parts or only one. Also from the description of `--executable-profilig` it is not clear whether benchmarks and tests are affected.

Another problem is with description of `--profile` option. It is not clear what it does and how it is related to `--library-profiling` and `--executable` profiling. [This comment](https://github.com/commercialhaskell/stack/issues/2074#issuecomment-215282877) states that `--profile` is equivalent to passing these two options. If it was true, it would be good to write about it in description (it's my personal subjective opinion as user of `stack`). However, I also think that it's not true. The reason is that if I run benchmark using `--library-profiling --executable-profiling --benchmark-arguments "+RTS -pa -RTS"` then it works as expected, `-pa` option is used and I get report which respects it. However, if I add `--profile` to this list of options, then `-p` RTS option is added and benchmark is run with `+RTS -pa -p -RTS`. As I can see from report, `-p` wins and report is as if it was run w/o `-pa`. That's why I don't think that `--profile` is equivalent to `--library-profiling --executable-profiling`.

**Comment by mgsloan** [comment]
Good point, I've updated my comment.  Yeah, the cli args here are a bit confusing.  We could also discuss doing something better.

**Comment by gromakovsky** [comment]
Well, I think that `--[no-]library-profiling` and `--[no-]executable-profiling` options are almost good if I understand correctly that they affect only how things are compiled, but not how they are run (i. e. they add compiler flag like `-prof`, but don't add any RTS options). Maybe it should be explicitely stated that these options only affect compilation flags, but not RTS (because there is another option which also adds RTS flag, `--profile`). Also it should be clear from documentation that `--executable-profiling` also affects benchmarks and tests (I guess it does).

`--profile` option also makes sense, in my opinion it should build everything with profiling enabled and then pass `+RTS -p -RTS` to test/benchmark (it is `build` command, so it can't run executables). But it should be documented better: it should be clear that it uses `-p` option, because there are `-P` and `-pa` and sometimes one wants to use one of them. Maybe it makes sense to add another option that will determine which profiling option to use (`-p`/`-pa`/`-P`).

Also for consistency it may be good idea to add `--profile` option to `stack exec`, which will check that executable is built with profiling enabled and exec it with profiling RTS option.

**Comment by snoyberg** [comment]
From my reading, the main issue here is addressed. If additional doc changes are desired, please consider opening a PR.
