### ISSUE TITLE
Check `gmake` version before assuming it is GNU make

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#2286]
As mentioned in #2284, `gmake` isn't always GNU make (it could be CMake), so Stack should perform a `--version` check on it (and maybe `make` as well) to determine whether it should be used.

**Comment by Cipherwraith** [comment]
I have ran into this bug multiple times too. Stack doesnt seem to build packages correctly without `gmake` installed. Please add a check for this.

**Comment by mpilgrem** [comment]
I am closing this given the passage of time and because I could not identify anything to suggest that `gmake` could be other than GNU make.
