### ISSUE TITLE
Possibility to not build the 'executable'

### ISSUE THREAD

**Issue by agrafix** [commercialhaskell/stack#2291]
Is it possible to provide an option/multiple options to `stack build` such as that only the library and tests or benchmarks are built? 
I my case I can't build the executable on my machine due to missing link-targets, but I can and still would like to run tests/benchmarks w/o removing the executable from the cabal file.

**Comment by sjakobi** [comment]
> Is it possible to provide an option/multiple options to stack build such as that only the library and tests or benchmarks are built?

No, AFAIK this currently not possibly and being tracked in #1406.
