### ISSUE TITLE
Missing .deb dependency: netbase

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#2293]
When installing Stack in a blank Xenial docker container, we get

```
FailedConnectionException2 "raw.githubusercontent.com" 443 True getProtocolByName: does not exist (no such protocol name: tcp)
```

As pointed out [here](https://github.com/bos/wreq/issues/5), the reason for this is because the `netbase` package has not been installed on the system. It should be added to the .deb dependencies for Stack.

**Comment by mboes** [comment]
By the same token, `ca-certificates` should be added too. `stack setup` fails otherwise due to TLS errors.

**Comment by borsboom** [comment]
Updated the release script so the next release's `.deb`s will include netbase and ca-certificates as dependencies.
