### ISSUE TITLE
Failed connection exception

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#2297]
When I try to build a new project, I'm getting the following excption:

```
stack build
Progress: 1/2FailedConnectionException2 "s3.amazonaws.com" 443 True connect: does not exist (Connection refused)
```

Not sure if it's my mistake or some sort of temporary problem with Stackage.

**Comment by sjakobi** [comment]
There were more reports of connectivity problems around that time, e.g. #2290, and they appear to have been fixed.

I'll close this but please do report any connectivity issues if they reappear!
