### ISSUE TITLE
ghc installed by stack setup fails on fedora 24 (libinfo-5 missing)

### ISSUE THREAD

**Issue by emmanueltouzery** [commercialhaskell/stack#2300]
fedora 24 was released this tuesday and upgrades ncurses (which contains libtinfo) from version 5 to version 6. Therefore my stack-installed ghc was broken by the upgrade to fedora 24 (cannot find libtinfo.so.5).

This is the same as issue #257 for arch, except that it seems that arch has at least for now a way to parallel install the old version of the library, while [i can't find a mechanism in fedora](https://ask.fedoraproject.org/en/question/89534/parrallel-install-ncurses-6-ncurses-5-on-fedora-24/).

I tried wiping the ~/.stack and re-running `stack setup`, but that doesn't help, fails due to libinfo-5 missing. Also note that fedora ships with ghc 7.8.4 only, making the situation even worse.

I think more and more distributions will ship with ncurses6. Also the arch workaround is temporary and requires "expert" manual intervention. If it's not possible to statically link it, maybe stack needs two binaries, or to do the linking on the client?

**Comment by borsboom** [comment]
I've opened #2302 to cover the general issue with `stack setup` supporting libtinfo6 distributions out of the box.  In the meantime, let's use this issue to determine what (if any) workarounds exist to support Fedora 24 right now.

**Comment by emmanueltouzery** [comment]
the good news is that I got a solution on [superuser.com](http://superuser.com/a/1093075/214371):

    sudo dnf install ncurses-compat-libs-6.0

I guess you can close this bug, except if maybe this could be documented somewhere (I guess for both arch & fedora), though I don't know where... Maybe some stack wiki?

**Comment by borsboom** [comment]
I've updated [doc/install_and_upgrade.md](https://github.com/commercialhaskell/stack/blob/stable/doc/install_and_upgrade.md) with Fedora 24 instructions.  I've also uploaded a Fedora 24 package that has `ncurses-compat-libs` as a dependency, and updated [get-stack.sh](https://github.com/commercialhaskell/stack/blob/stable/etc/scripts/get-stack.sh) to support it.

**Comment by afcowie** [comment]
@emmanueltouzery 's suggestion at https://github.com/commercialhaskell/stack/issues/2300#issuecomment-228412509 to install **ncurses-compat-libs** worked. Thanks!

AfC
