### ISSUE TITLE
How to add non-Stackage GitHub dependency

### ISSUE THREAD

**Issue by ooblahman** [commercialhaskell/stack#2303]
It's unclear to me from the docs how to do so. I've added the following to my `stack.yaml`:

    packages:
    - location: .
    - location: 
        git: git@github.com:atzeus/HMap
        commit: c6fbde4aaeb7dff42f157f6fdd3f95375852f065
        extra-dep: true

Yet `stack install` still yields

    --  Failure when adding dependencies:    
         hmap: needed (-any), stack configuration has no specified version
         needed for package alphasheets-0.1.0.0

**Comment by mgsloan** [comment]
Package names are case sensitive.  You want `HMap` in build-deps.

It would be great to have typo suggestions in more places - https://github.com/commercialhaskell/stack/issues/1748
