### ISSUE TITLE
Source code documentation

### ISSUE THREAD

**Issue by AaronFriel** [commercialhaskell/stack#2304]
The internal source code could use some documentation to understand its structure and the meaning of various acronyms. I am trying to resolve the regression found in #2289 and it is very frustrating that I do not know _why_ something is an "extraPackage" (is that just extra-deps?), or what a "gpdPackages" is. Many/most of the functions lack documentation or explanation for their existence.

I think I am close to resolving #2289, but to elaborate on the difficulty of the problem:

Why was `getDefaultPackageConfig` added in c891a247cead52bcc18c079bdaa91ab8980a834b and used in two places where the refactored `getPackageConfig` can be used? There's enough information in both places where `getDefaultPackageConfig` is used to utilize `getPackageConfig`.

There is no comment on `getDefaultPackageConfig` and no explanation for its introduction or use. It was a red herring because it was an obvious place where ghc options were being set to an empty list, but it did not solve my problem.

**Comment by sjakobi** [comment]
> what a "gpdPackages" is

"gpd" stands for [`GenericPackageDescription`](https://www.stackage.org/haddock/lts-6.4/Cabal-1.22.8.0/Distribution-PackageDescription.html#t:GenericPackageDescription) which is the type that `Cabal` uses to represent `.cabal` files.

I agree that navigating stack's source code is currently a pretty frustrating experience. Often, when I find a comment in the source code it has already fallen out of date and is actually worse than no documentation at all.

I'm not sure what to do about it though. Are there other projects that handle this well?

**Comment by AaronFriel** [comment]
I feel like most Hackage libraries do better. Perhaps because Stack is not a "library" except to be consumed by itself, that same work is not done?

**Comment by mgsloan** [comment]
> Why was getDefaultPackageConfig added in c891a24 and used in two places where the refactored getPackageConfig can be used? There's enough information in both places where getDefaultPackageConfig is used to utilize getPackageConfig.
>
> There is no comment on getDefaultPackageConfig and no explanation for its introduction or use. It was a red herring because it was an obvious place where ghc options were being set to an empty list, but it did not solve my problem.

It is a default package configuration, where there are no flags or ghc-options.  I didn't document it because I found the name sufficient, sorry you did not.

It was added because the interface to `getPackageConfig` was getting more complicated.  The code is copied because I did not want to need to reason about whether or not `getPackageConfig` would yield the results I wanted (no flags, no ghc-options).

I agree that there is a lot of cleanup and documentation to be done.

> I feel like most Hackage libraries do better. Perhaps because Stack is not a "library" except to be consumed by itself, that same work is not done?

Part of it, not a good reason, though.

**Comment by AaronFriel** [comment]
@mgsloan: Doesn't `getDefaultPackageConfig` risk throwing away `ghc-options: ...` and `apply-ghc-options: everything`? I was tempted to include reverting that function in my pull request but I didn't want to make a controversial change without understanding the code.

You have to admit that it kind of flies in the face of the stated config options to allow package configs to disregard the explicit `config.yaml`.

**Comment by mgsloan** [comment]
There are cases where you don't care about those, for example when producing source distributions - https://github.com/commercialhaskell/stack/blob/c891a247cead52bcc18c079bdaa91ab8980a834b/src/Stack/SDist.hs#L172 

I could certainly imagine reversing this decision, I probably did not spend this much time thinking about it before.
