### ISSUE TITLE
Command line help pages and unix man pages for stack sub-commands and stack.

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#2308]
We should start with a man page for `stack` itself first. 

The next step would be to have man pages for each subcommand in git style e.g. `man git-status` opens a help page for the `status` subcommand. The same man page is used for `git status --help` while `git status -h` provides a shorter summary of the command options. We can apply similar style to stack help as well. The same pages can be used to generate online reference documentation.

Maybe we can learn from [git](https://github.com/git/git/blob/master/Documentation). git uses `asciidoc` to convert plain text man pages into other formats. See the git [makefile](https://github.com/git/git/blob/master/Documentation/Makefile) for doc generation details. As an example of a man page source see - [git-status](https://github.com/git/git/blob/master/Documentation/git-status.txt). Pandoc also supports conversion from asciidoc.

Other option is to use markdown formatted pages and convert them using pandoc or [ronn](https://github.com/rtomayko/ronn).

For content, we can pull out relevant stuff from the current stack documentation and put that into appropriate help pages of commands wherever applicable.

**Comment by sjakobi** [comment]
I agree that a comprehensive command reference would be a great thing to have!

Actually `stack` used to have a man page, but it fell out of date and was removed: https://github.com/commercialhaskell/stack/issues/986

From https://github.com/commercialhaskell/stack/issues/956 it sounds like @drwebb intended to work on an autogenerated manpage but it seems like nothing came from it?

I have actually been dreaming about something like a command reference interleaved with actual integration tests that make sure that the documented behaviour is really happening… not sure if that's too utopian though.

**Comment by mpilgrem** [comment]
Closing because, in 2024, Stack has comprehensive online help.
