### ISSUE TITLE
undefined variable error in nix.packages

### ISSUE THREAD

**Issue by jjl** [commercialhaskell/stack#2309]
Seems that when i try to use stack in the way that is documented for integration with nix, i get a strange error trying to specify which packages are needed from nix. Here's the error:

```
$ stack build
error: undefined variable ‘icu4c’ at (string):1:245
(use ‘--show-trace’ to show detailed location information)
```

Here's the snippet of my stack.yaml:

```yaml
nix:
  enable: true
  packages: [ icu4c ]
```
And my version:

```
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
```

**Comment by mckeankylej** [comment]
This means the package doesn't exist test for it existing with
```sh
nix-env -qaP | grep icu4c
```

**Comment by mgsloan** [comment]
Closing, feel free to re-open.
