### ISSUE TITLE
`stack build` in an empty directory downloads a new package cache

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#231]
b@fuzzbomb ~/tmp/foo $ stack build
    PackageNoCabalFileFound "/home/b/tmp/foo/"
    Writing default config file to: /home/b/tmp/foo/stack.yaml
    Downloading build plan from: https://raw.githubusercontent.com/fpco/lts-haskell/master/lts-2.13.yaml

That seems like extra work for a failure condition.

**Comment by snoyberg** [comment]
Well, it's not exactly a failure condition. There are legitimate use cases here, e.g.:

```
$ stack build
$ stack deps vector
$ stack ghci
```

So it seems at least somewhat reasonable for it to behave this way IMO.

**Comment by chrisdone** [comment]
Perhaps an improvement to this behaviour would be explaining its intentions. I.e. "I don't have anything to do and I didn't find a cabal file, so I'm going to assume you want a configuration."

**Comment by chreekat** [comment]
What is `stack build` being used for in that case?

How does that mesh with #59, and the idea that "It also caters to newbies reading books who just want to run ghc on a file. You can run stack ghc X.hs and it will download GHC if necessary, etc...". Would a yaml  be created in the latter scenario? It would be nice if it wasn't necessary, since it is likely X.hs will be in a home directory, or in a directory full of other one-off test files.

**Comment by snoyberg** [comment]
Fair point, maybe we should just change behavior to exiting if there's no .cabal file present. We already have plans to improve `stack ghci` and friends so that they can run without a stack.yaml file, so perhaps this all adds up nicely.

**Comment by chreekat** [comment]
@chrisdone, or: "I don't have anything to do. Shall I run `stack init` for you?"

**Comment by chrisdone** [comment]
Fair points, indeed. I'm not really sure on this one. Going to think about it.

**Comment by snoyberg** [comment]
Discussed with @chrisdone, we'll just exit `stack.yaml` construction if no .cabal file exists, and leave the rest of init to #253.

**Comment by snoyberg** [comment]
OK, this is implemented, with the real solution to be handled via #253. Closing.
