### ISSUE TITLE
Add `stack hoogle --server` command

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#2310]
Which would run `stack hoogle -- --server --local`. `--local` is  needed to be able to click links to local files.

**Comment by ndmitchell** [comment]
I wonder if Hoogle should launch a web browser on --server, and then when the web browser disappears it could close the server. Maybe as a `stack hoogle --launch`? I'm quite happy to adjust the semantics/API of Hoogle to make this better for stack users.

**Comment by chrisdone** [comment]
It could be a handy shortcut. The only reason you start the server is to see the web page after all.

**Comment by ndmitchell** [comment]
Ticket raised at https://github.com/ndmitchell/hoogle/issues/175.

**Comment by jhance** [comment]
Small correction, I think it should actually be `stack hoogle -- server --local`.

**Comment by ndmitchell** [comment]
`stack hoogle -- server --local` works today so I think everything is good.
