### ISSUE TITLE
Can't build within Docker

### ISSUE THREAD

**Issue by sigrlami** [commercialhaskell/stack#2311]
Trying to build my application with 
- stack   v1.1.2
- cabal   v1.22.5 
- docker v1.10.3 
- on Fedora 24 image

Previously, worked perfectly with stack and lts-5.15, 7.10.3 but after upgrading and switching to 6.5 output gives a lot of errors like
```
...
  /code/.stack-work/downloaded/tYY2vA9pEWVl/src/Afftrack/API/Common.hs:20:8:
        Could not find module `Network.HTTP.Client'
        There are files missing in the `http-client-0.4.29@httpc_0UHz6nNJST1L9wd9Mv1sd3' package,
        try running 'ghc-pkg check'.
        Use -v to see a list of the files searched for.
    
    /code/.stack-work/downloaded/tYY2vA9pEWVl/src/Afftrack/API/Common.hs:21:8:
        Could not find module `Data.Text'
        There are files missing in the `text-1.2.2.1@text_HmqVQnZSpjaC156ABqPhne' package,
        try running 'ghc-pkg check'.
        Use -v to see a list of the files searched for.
...
```

While running `ghc-pkg` gives lots of this errors

```
...
Warning: haddock-interfaces: /home/sigrlami/work/projects-hs/admerge/.stack-work/install/x86_64-linux/lts-6.5/7.10.3/doc/uuid-types-1.0.3/uuid-types.haddock doesn't exist or isn't a file
  Warning: haddock-html: /home/sigrlami/work/projects-hs/admerge/.stack-work/install/x86_64-linux/lts-6.5/7.10.3/doc/uuid-types-1.0.3 doesn't exist or isn't a directory
  import-dirs: /home/sigrlami/work/projects-hs/admerge/.stack-work/install/x86_64-linux/lts-6.5/7.10.3/lib/x86_64-linux-ghc-7.10.3/uuid-types-1.0.3-1jYi9RR4Gf08rGU1w6xxPr doesn't exist or isn't a directory
  cannot find any of ["Data/UUID/Types.hi","Data/UUID/Types.p_hi","Data/UUID/Types.dyn_hi"]
  cannot find any of ["Data/UUID/Types/Internal/Builder.hi","Data/UUID/Types/Internal/Builder.p_hi","Data/UUID/Types/Internal/Builder.dyn_hi"]
  cannot find any of ["Data/UUID/Types/Internal.hi","Data/UUID/Types/Internal.p_hi","Data/UUID/Types/Internal.dyn_hi"]
  cannot find any of ["libHSuuid-types-1.0.3-1jYi9RR4Gf08rGU1w6xxPr.a","libHSuuid-types-1.0.3-1jYi9RR4Gf08rGU1w6xxPr.p_a","libHSuuid-types-1.0.3-1jYi9RR4Gf08rGU1w6xxPr-ghc7.10.3.so","libHSuuid-types-1.0.3-1jYi9RR4Gf08rGU1w6xxPr-ghc7.10.3.dylib","HSuuid-types-1.0.3-1jYi9RR4Gf08rGU1w6xxPr-ghc7.10.3.dll"] on library path
There are problems in package direct-sqlite-2.3.17:
  Warning: library-dirs: /home/sigrlami/work/projects-hs/admerge/.stack-work/install/x86_64-linux/lts-6.5/7.10.3/lib/x86_64-linux-ghc-7.10.3/direct-sqlite-2.3.17-D3duxzilrPKH1oKv2GTiAL doesn't exist or isn't a directory
...
```
Can't understand why those are coming and seems like combination of several existing issues. 
Tried without success:
- run `clean`
- upgrade to `master` version

How can I fix this?

P.S: Building locally (not inside Docker) on Fedora 23 with same versions doesn't bring this errors

**Comment by sigrlami** [comment]
I think partially related to #595

**Comment by mgsloan** [comment]
Run `stack exec -- ghc-pkg check`?  It seems like there are cases where packages start out or become broken, and are still in the DB.  You can use `stack exec -- ghc-pkg unregister pkg` to uninstall these when they.  I would like to have stack automatically run this - https://github.com/commercialhaskell/stack/issues/1811

**Comment by sigrlami** [comment]
@mgsloan the problem, that ghc-pkg check gives arounf half packages as broken, so if I even pipe output to `unregister` not sure how this will help, I'm  actually need some of those

**Comment by mgsloan** [comment]
@sigrlami Stack will notice that the packages are missing and rebuild them.  I have pushed this branch which has an `unregister-broken` command: https://github.com/commercialhaskell/stack/tree/1811-wip-unregister-broken .  Should work fine, but I don't want to commit to these CLI choices / etc yet and so not yet committing it to master.

**Comment by sigrlami** [comment]
ok, thanks! I use right now 
```
for p in `stack exec -- ghc-pkg check --simple-output`; do stack exec -- ghc-pkg unregister $p --user --force; done
```
before `build`, which is similar to you commit

**Comment by mgsloan** [comment]
Sounds like things are workable right now.  Once #1811 is implemented, we can more systematically detect why this can happen, and automatically fix it.
