### ISSUE TITLE
"stack build" on Windows cannot load stdc++.dll

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#2313]
Windows 8
stack 1.1.2

> <command line>: can't load .so/.DLL for: stdc++.dll (addDLL: could not load DLL)
> ghc.exe: stdc++: The specified module could not be found.

**Comment by mgsloan** [comment]
Is this with the system installed ghc mentioned in https://github.com/commercialhaskell/stack/issues/2314 ?  We need more info, as this isn't affecting others as far as we know.

Will re-open upon further details.

**Comment by varosi** [comment]
Hm, I cannot remember now how I produced that bug. But the setup is on the same system as that mentioned in #2314
