### ISSUE TITLE
Scripts don't use ~/.stack/config.yaml

### ISSUE THREAD

**Issue by puffnfresh** [commercialhaskell/stack#2319]
My `~/.stack/config.yaml` file has:

``` yaml
nix:
  enable: true
```

This config is not used when running a script via `stack example.hs`.

**Comment by puffnfresh** [comment]
What config should be used for a script? Global? User? <del>Project</del>?

**Comment by YPares** [comment]
@puffnfresh Can you paste the version of stack you're using?

**Comment by YPares** [comment]
Also, what package from nixpkgs does `example.hs` need to use?

**Comment by harendra-kumar** [comment]
If your `pwd` is inside a project then the project's config is used otherwise global project config (`~/.stack/global-project/stack.yaml`) is used. I would expect the settings in `~/.stack/config.yaml` to be effective everywhere unless overridden by global or project config.

**Comment by harendra-kumar** [comment]
I added a note in the guide (b726bb5). Let me know if that's not how it is or that's not how it should be.

**Comment by puffnfresh** [comment]
@YPares stack 1.1.2 and just trying to compile with a base GHC. You can this problem if you have a shell without GHC on the PATH.

@harendra-kumar that's not how it is. No configuration is used in scripts.

**Comment by harendra-kumar** [comment]
@puffnfresh can you try setting a particular resolver in your project or global config and then verify which resolver is used in the script using `stack runghc -v` in the script. You should see the project resolver being used when in project dir and global resolver when outside any project dir. Make sure you do not use a `--resolver` option in the script.

**Comment by snoyberg** [comment]
Addressed by #4701
