### ISSUE TITLE
Wishlist: stack ide-backend-client

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#232]
This can be added directly or implemented as a plugin. But preconfiguring ide-backend-client ready for loading in a project or project(s) would be the missing magic that ide-backend-client has been waiting for.

**Comment by snoyberg** [comment]
Pinging @mgsloan

**Comment by bitemyapp** [comment]
Vigorous (+1)

**Comment by mgsloan** [comment]
Vigorous (+1) from me as well!  This would be fantastic

**Comment by cocreature** [comment]
+1 from me!

**Comment by rvion** [comment]
+1 :cake:

**Comment by snoyberg** [comment]
This looks like a good project for @mgsloan to spearhead, given your work on ide-backend-client recently for School of Haskell.

**Comment by krgn** [comment]
I have been digging around in the documentation and source for `ide-backend` & `ide-backend-server` and its not clear to me how it would be possible to automate building the server part, as it relies on patched ghc's. Is the intention to eventually require this to be done by the user?

**Comment by cocreature** [comment]
GHC 7.10 doesn't require any patches anymore, so I think it would be fine to only support that.

**Comment by krgn** [comment]
@cocreature OK, thats good news. But the server part still needs to be built and installed separately in that scenario, correct?

**Comment by cocreature** [comment]
I don't see why stack can't built that for you.

**Comment by krgn** [comment]
Yep true. I think the biggest question mark in my mind was the question regarding patched `ghc`. I'm tinkering around to get something working, so maybe I can send a patch at some point.

**Comment by cocreature** [comment]
I suppose it's not fully implemented yet, but for the record:

When I try to run `stack ide` on the `stack-ide` repo (which contains the ide-backend-server package) I get the following error
```
{"tag":"ResponseWelcome","contents":[0,1,0]}
stack-ide: user error (Could not find ide-backend-server)
```

**Comment by drwebb** [comment]
I'm a little bit further along than you, but not by much. (Apparently there has been some code shifting around recently that leaves stack-mode in emacs broken), but are you sure ide-backend-server is on your path? Did you follow the instructions at the `stack-ide` repo?

**Comment by cocreature** [comment]
> Did you follow the instructions at the stack-ide repo?

Obviously not, sorry :/

**Comment by thomasjm** [comment]
@drwebb I have a possibly dumb question for you...I've been googling around for a while and I'm very confused about the state of Emacs support for `ide-backend`. Chris Done's `ide-backend-mode` is 404ing for me (https://github.com/chrisdone/ide-backend-mode), and your mention of "stack-mode" leaves me extra confused. Is it possible to get a working Emacs setup using `ide-backend` (or better still, `stack-ide`) right now?

**Comment by cocreature** [comment]
@thomasjm It's now called [stack-mode](https://github.com/commercialhaskell/stack-ide/tree/master/stack-mode). I got it working for the stack-ide repo but not for any other repo so I would say it's of limited use right now :)

**Comment by drwebb** [comment]
@thomasjm Yeah everything @cocreature says is correct, and at the moment it's a bit rough and I've not personally gotten a "usuable" client up and running because things are changing so rapidly, but it's there for you to experiment with. pinging @chrisdone for a stack-mode update

**Comment by chrisdone** [comment]
I'm currently tied up with other things for the next couple weeks, but will come back to it later.

**Comment by thomasjm** [comment]
@chrisdone is there anything I could do to help contribute? I'm especially interested in getting Flycheck checkers working

**Comment by krgn** [comment]
@thomasjm I use this snippet atm, if thats any help..

```lisp
(flycheck-define-checker haskell-stack
  "A Haskell syntax and type checker using ghc.

See URL `http://www.haskell.org/ghc/'."
  :command ("~/.local/bin/stack" "ghc" "--" "-Wall" "-fno-code"
            (option-flag "-no-user-package-db"
                         flycheck-ghc-no-user-package-database)
            (option-list "-package-db" flycheck-ghc-package-databases)
            (option-list "-i" flycheck-ghc-search-path concat)
            ;; Include the parent directory of the current module tree, to
            ;; properly resolve local imports
            (eval (concat
                   "-i"
                   (flycheck-module-root-directory
                    (flycheck-find-in-buffer flycheck-haskell-module-re))))
            (option-list "-X" flycheck-ghc-language-extensions concat)
            (eval flycheck-ghc-args)
            "-x" (eval
                  (pcase major-mode
                    (`haskell-mode "hs")
                    (`literate-haskell-mode "lhs")))
            source)
  :error-patterns
  ((warning line-start (file-name) ":" line ":" column ":"
            (or " " "\n    ") "Warning:" (optional "\n")
            (message
             (one-or-more " ") (one-or-more not-newline)
             (zero-or-more "\n"
                           (one-or-more " ")
                           (one-or-more not-newline)))
            line-end)
   (error line-start (file-name) ":" line ":" column ":"
          (or (message (one-or-more not-newline))
              (and "\n"
                   (message
                    (one-or-more " ") (one-or-more not-newline)
                    (zero-or-more "\n"
                                  (one-or-more " ")
                                  (one-or-more not-newline)))))
          line-end))
  :error-filter
  (lambda (errors)
    (flycheck-sanitize-errors (flycheck-dedent-error-messages errors)))
  :modes (haskell-mode literate-haskell-mode)
  :next-checkers ((warning . haskell-hlint)))
```

**Comment by thomasjm** [comment]
Awesome!!! Many thanks @krgn , I'll try it out!

**Comment by chrisdone** [comment]
This week I pushed some updates to `stack` and `stack-ide` and `stack-mode`. If you pull them all you should be able to:

* Remove any hooks about interactive-haskell-mode:

``` lisp
(remove-hook 'haskell-mode-hook 'interactive-haskell-mode)
```

* Add a hook for stack-mode:

``` lisp
(add-hook 'haskell-mode-hook 'stack-mode)
```

Then when you open a file it will enable flycheck automatically and configure it with the stack checker in this buffer, which will in turn try to use the stack backend which will automatically start that too, configured with the cabal project you're in using the stack configuration that's in.

Then the things that work are:

* Flycheck: i.e. type checking on the fly as you type and underlining
  with squiggly lines the problem.
* Get type of identifier / selected expression.
* Go to definition.

Currently missing things:

* Show use sites.
* Completion.
* REPL.

**Comment by chrisdone** [comment]
Added explanatory section here: https://github.com/commercialhaskell/stack-ide#emacs

**Comment by lukerandall** [comment]
Thanks @chrisdone. This is very exciting stuff!

**Comment by chrisdone** [comment]
Moving to the stack-ide repo.
