### ISSUE TITLE
Can't find a package database package.conf.inplace

### ISSUE THREAD

**Issue by sigrlami** [commercialhaskell/stack#2320]
Trying to run my application built with 
- stack   v1.1.2
- cabal   v1.22.5 
- docker v1.10.3 
- on Ubuntu 14.04 image

and have 
```
can't find a package database at .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/package.conf.inplace
```
How can I fix this? Not sure maybe it's Cabal's error? 

Application buit in one place and then copied to another when it runs with specific parameters. I think it might depend on something pre-built?

**Comment by mgsloan** [comment]
Sorry for the delay on getting back to this.  It's Cabal's error message.  Is it still affecting you?  I'll re-open if so.

I would suggest doing `stack clean --full` and then `stack build`.  What commands are you running?

**Comment by mgsloan** [comment]
Likely the same issue as https://github.com/commercialhaskell/stack/issues/2424 , now fixed on master
