### ISSUE TITLE
`ghcjs-boot` not enough flexibility

### ISSUE THREAD

**Issue by tolysz** [commercialhaskell/stack#2330]
I am playing with `ghcjs@8.0` and as it happens it needs more love from `stack`.

    logProcessStderrStdout Nothing "ghcjs-boot" menv' ["--clean"]

is not enough, as the upstram bundle does not have working `boot.tar` in it. However hardcoding:

    logProcessStderrStdout Nothing "ghcjs-boot" menv'
                         [ "--clean"
                         , "--dev"
                         , "--ghcjs-boot-dev-branch", "ghc-8.0"
                         , "--shims-dev-branch", "ghc-8.0"
                         ]

works for my very case, but is not good either. 
Maybe if we could pass some extra options from the command line so we could instrument `ghcjs-boot` somehow easier.

ps.
with this you can boot, but template linking will be broken later...

**Comment by mgsloan** [comment]
https://github.com/commercialhaskell/stack/issues/652 should cover supporting `ghcjs-boot-options`
