### ISSUE TITLE
stack build does not rebuild executable without other-modules

### ISSUE THREAD

**Issue by spl** [commercialhaskell/stack#2341]
This may be a known issue. If so, I think it could be documented better. I could not find a clear answer in the issue archive to match this, so, at the very least, this issue might help others who encounter the problem.

**Steps to reproduce:**

1. Create a `.cabal` for an executable.
  * Include the `hs-source-dirs` field mentioning the source directories with the modules.
  * Do _not_ include the `other-modules` field with the modules listed.
2. Create a `stack` from that `.cabal`.
3. `stack build` the first time.
4. Change a module in the package.
5. `stack build` to rebuild.

**Expected:**

The project rebuilds.

**Actual:**

The project does not rebuild.

**Discussion:**

I couldn't figure out why my project wasn't rebuilding. Then, I found that if I include `other-modules` with a module `M` and update `M`, the project would rebuild. If I then change `N`, a module _not_ listed in `other-modules`, the project would _not_ rebuild.

**Related:**

These issues seem to be related:

* Detect when a module is compiled but not listed in the cabal file #32
* Respect TemplateHaskell addDependentFile dependency changes #105
* Stack not detecting changes for incremental builds #481
* Stack not rebuilding #573
* `stack test` not detecting changes to the test suite #556

From my cursory reading, it seems like this issue was supposed to be fixed in:

* Detect unlisted modules and TH dependent files #734

There seems to be a currently undocumented `--force-dirty` flag added in 09a9fa46fd1d8174ececf4a53774a05b36641457 to deal with this kind of issue.

I believe I did see a warning for unlisted modules (added in 31712d302058d4fff3b0effb33f35035106d2f7d?), but I wasn't sure what the warning was for. I wasn't even sure what an “unlisted module” was. Why would unlisted modules be a problem? If this issue is the reason for that warning, then the warning text could be improved.

**Questions:**

If this is a known issue with no fix currently planned, could it be documented better or handled by `stack`?
  * One option would be to mention it somewhere in the guide. The “Build command” section would be a good place to start with.
  * Another option would be to automate the check with `stack` and report it.

**Comment by mgsloan** [comment]
I tried

```
name:                issue2341
version:             0.1.0.0
synopsis:            Initial project template from stack
description:         Please see README.md
homepage:            https://github.com/mgsloan/issue2341#readme
license:             BSD3
license-file:        LICENSE
author:              Michael Sloan
maintainer:          mgsloan@gmail.com
copyright:           2015 Michael Sloan
category:            Web
build-type:          Simple
-- extra-source-files:
cabal-version:       >=1.10

executable issue2341-exe
  main-is:             Main.hs
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N
  build-depends:       base
  default-language:    Haskell2010
```

With Main.hs

```
import Lib

main = putStrLn "hi"
```

and Lib.hs

```
module Lib where
```

**Comment by spl** [comment]
@mgsloan: Thanks for trying to reproduce it. I take it from your response that this is _not_ a known problem?

Two things to add:

* I don't see `hs-source-dirs` in your `.cabal`. I had `hs-source-dirs: src` with all modules under the `src/` directory.
* This is a `ghcjs` project. I'm not sure if that makes a difference.

**Comment by spl** [comment]
Also, thanks for improving the documentation. 💯

**Comment by jasonzoladz** [comment]
I'm unexpectedly having the same the problem.  `--force-dirty` doesn't help.

I'm using `nightly-2016-08-21`.

The `library` portion of my `.cabal` file looks like this:

```haskell
library
  hs-source-dirs:      src
  exposed-modules:     Application
                       Imports
                       StaticAssetsURLs
                       Models.ApplicationTypes
                       Models.PersistentModels
                       Models.AuthModels
                       Models.General
                       Actions.AuthDatabase
                       Utils.ActionUtils
                       Utils.AuthUtils
                       Utils.JwtUtils
                       Utils.EmailUtils
                       Utils.LucidUtils
                       Actions.Auth
                       Actions.Email
                       Emails.SampleEmails
                       LucidViews.SampleViews
                       LucidViews.Components.Common
                       LucidViews.Components.SemanticUI
                       LucidViews.Home
                       LucidViews.About
                       LucidViews.PatternLib
                       LucidViews.ReactApp
                       LucidViews.Notes
                       Parsers.StoreCSVParsers
                       Routes
```
When I change `LucidViews.Home` and the rebuild does nothing.  (This applies to `:r` in ghci as well.)  Yet if introduce an error, it will not compile.  

Just started this morning.  Appeared out of nowhere.

**Comment by jasonzoladz** [comment]
Note:  Even adding a new module to the `.cabal` file and `src` -- e.g., `LucidViews.Another` -- will not alter the executable.  Oddly, this is true even when I delete my local repo and `git clone` again.

**Comment by mgsloan** [comment]
This is indeed related to using GHCJS.  With GHC I get:

![2016-10-10-180042_845x78_scrot](https://cloud.githubusercontent.com/assets/22570/19255500/833d3f84-8f13-11e6-9c47-d320a88200ae.png)

However, GHCJS doesn't seem to output these `ddump-hi` files, and so we can't keep track of dirtiness.

**Comment by mgsloan** [comment]
@spl I believe I've resolved the issue.  Now, all local ghcjs packages will be assumed to be dirty, because we can't be sure.

**Comment by spl** [comment]
Nicely done. I think that's a reasonable solution. Thanks!

**Comment by mgsloan** [comment]
Welcome, thanks for bringing up the issue!

**Comment by mgsloan** [comment]
@spl I have figured out why ddump-hi files aren't being produced - see https://github.com/commercialhaskell/stack/issues/2714 .  I've fixed that issue, and reverted the special case of assuming ghcjs local packages are dirty.
