### ISSUE TITLE
Not mirroring hackage

### ISSUE THREAD

**Issue by andrewthad** [commercialhaskell/stack#2342]
I've got a library named `colonnade` on hackage. I released version 0.3 yesterday, and it looks like the stackage mirror still isn't seeing it. That is, if I add this to `stack.yaml`:

```
extra-deps:
  - 'colonnade-0.3'
```

And then I add `colonnade` to my cabal file as well, I end up with the following error:

```
The following package identifiers were not found in your indices: colonnade-0.3
```

I've been using `stackage` and `stack` for over a year, and I've never seen a package fail to mirror like this before.

**Comment by phadej** [comment]
atm https://github.com/commercialhaskell/all-cabal-hashes/ says update 20 hours ago: *Travis job Update from Hackage at 2016-07-05T16:25:35+0000*, just before `colonnade-0.3` was released at *Tue Jul 5 16:37:56 UTC 2016*.

There was plenty of packages released after that too: http://hackage.haskell.org/packages/recent

Some indicator of `all-cabal-hashes` updates would be great to have, to see when updates are happend after one released a package. Also this happens from time to time it seems, would be easire to troubleshoot (https://github.com/commercialhaskell/all-cabal-hashes/issues/6)

**Comment by leohaskell** [comment]
That's strange, since [all-cabal-files](https://github.com/commercialhaskell/all-cabal-files) is up to date.

**Comment by sjakobi** [comment]
The problem is being tracked at https://github.com/commercialhaskell/all-cabal-files/issues/10.

Maybe we should emit a warning in this case if the package name is known and the specified version number is larger than all the known ones?! We could suggest to add the package as a github extra-dep.

I don't think it's worth adding code to workaround the problem though…

**Comment by mgsloan** [comment]
I'd like to be able to have it fall back on using hackage directly.  This would be helpful when releasing packages to hackage.  Otherwise, you have to wait for the updates to propagate before checking whether your other projects build against the hackage version.

**Comment by snoyberg** [comment]
This problem has been resolved
