### ISSUE TITLE
stack init should allow a different minor version of compiler

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#2349]
Even with the `--force` flag it does not generate a stack.yaml when the minor version of compiler mismatches.

```
$ stack init --resolver lts-3 --solver --force
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- SourceGraph.cabal

Selected resolver: lts-3.22
Selected resolver: lts-3.22
*** Resolver lts-3.22 will need external packages: 
    Graphalyze not found
        - SourceGraph requires >=0.14.1.0 && <0.15
    graphviz not found
        - SourceGraph requires >=2999.15.0.0 && <2999.19

Using resolver: lts-3.22
Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-7.10.2 (x86_64) (based on command line arguments).
Compiler version (ghc-7.10.2) required by your resolver specification cannot be found.

Please use '--install-ghc' command line switch to automatically install the compiler or '--system-ghc' to use a suitable compiler available on your PATH.
```

**Comment by sjakobi** [comment]
Maybe the `--force` flag should be named `--overwrite` to make clear that it can't force anything but the replacement of an existing `stack.yaml`.

What you want should be possible if you set `compiler-check: newer-minor` in your `~/.stack/config.yaml`.
Does that work?

**Comment by harendra-kumar** [comment]
That's what I did. I created a stack.yaml using a resolver for which I had the compiler installed and then changed the resolver to correct one, `compiler-check` to `newer-minor` and then ran `stack solver` to fix the extra deps. 

But it would be nice to have the ability to generate the `stack.yaml` in the first place. One should at least have a starting point to tweak.

**Comment by snoyberg** [comment]
This doesn't look like something we're going to address, closing
