### ISSUE TITLE
Cannot install package from AUR4

### ISSUE THREAD

**Issue by CodyReichert** [commercialhaskell/stack#235]
Trying to install [haskell-stack](https://aur4.archlinux.org/packages/haskell-stack/) from the Arch User's Repository gives a 404 error when running `makepkg`. It looks like the `PKGBUILD` is trying to retrieve the source file from `http://download.fpcomplete.com/archlinux/`, but there's nothing at that URL.

Steps:

    $ git clone https://aur4.archlinux.org/haskell-stack.git/
    $ cd haskell-stack
    $ makepkg

Output:

    $ makepkg
      ==> Making package: haskell-stack 0.0.0-1 (Tue Jun  9 12:39:59 CDT 2015)
      ==> Checking runtime dependencies...
      ==> Checking buildtime dependencies...
      ==> Retrieving sources...
              -> Downloading haskell-stack_0.0.0-x86_64.tar.gz...
              % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                             Dload  Upload   Total   Spent    Left  Speed
               0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     
            curl: (22) The requested URL returned error: 404 Not Found
      ==> ERROR: Failure while downloading haskell-stack_0.0.0-x86_64.tar.gz
             Aborting...

It looks like it's just the source URL that's incorrect. The current `PKGBUILD` in master has a source URL to AWS, so I'm sure which URL is supposed to be correct or else I'd PR.

**Comment by drwebb** [comment]
Thanks, I'll look into it.

**Comment by drwebb** [comment]
In the mean time this is the correct url
http://download.fpcomplete.com/archlinux/stack_0.0.0-x86_64.tar.gz

**Comment by drwebb** [comment]
This should be fixed, this was due to there already being a "stack" package in the AUR so I needed to rename the package to "haskell-stack" put kept the old variable in the PKGBUILD. Should be working, could you please confirm? I plan to push a new version of the binaries tonight, but you may want to try building the git version as well. It's good to have another Archer for testing.

**Comment by donnut** [comment]
I have the same problem and indeed, overridding ${pkgname} with 'stack' does the job.

**Comment by CodyReichert** [comment]
Great, looks like that does the trick. Thanks. I'll be using the packages from AUR, so I'll keep an eye out for updates.
