### ISSUE TITLE
Cabal warns about using deprecated profiling flag 

### ISSUE THREAD

**Issue by hesiod** [commercialhaskell/stack#2350]
Upon running `stack --profile` on an executable, cabal warns about using the deprecated `--enable-executable-profiling` flag:
```
Warning: The flag --enable-executable-profiling is deprecated. Please use
--enable-profiling instead.
```
The related code seems to be [here](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Types/Build.hs#L620).

Using latest stack (1.1.2).

**Comment by sjakobi** [comment]
Thanks for the report!

Care to make a PR? You can find the cabal version in `envConfigCabalVersion`.
