### ISSUE TITLE
Notify users about new stack releases

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2355]
[As already promised on r/haskell](https://www.reddit.com/r/haskell/comments/4ghznv/improved_hpcaballess_wwwhaskellorg_in_the_works/d2kfr6i) stack should notify users when a new version of stack exists.

I'd suggest that the notifcation be shown once a day.

**Comment by borsboom** [comment]
It would make sense to implement this in conjunction with #1238 (have `stack upgrade` download a new binary when possible rather than building from source).

**Comment by sjakobi** [comment]
I somehow missed https://github.com/commercialhaskell/stack/issues/1681 when opening this. Closing as a duplicate and moving @borsboom's comment to #1681.
