### ISSUE TITLE
missing links (in hyperlinked source files) with --haddock-deps

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/stack#2356]
When I run 

```
stack haddock --haddock-arguments=--hyperlinked-source --haddock-deps
```

in the html versions of source files of local packages, hyperlinks for identifiers from global packages (in $HOME/.stack) are missing (but linking between packages in .stack-work is fine).

hyperlinked source is generated for global packages, but there, all links to identifiers in different modules (even from the same package) are missing.

**Comment by jwaldmann** [comment]
test case for reproducing the behaviour: https://github.com/jwaldmann/stack-haddock-test

**Comment by mgsloan** [comment]
Thanks for the repro!  I don't currently have time to look into this, but I hope someone will soon!

Feel free to figure it out yourself and open a PR with a fix, that would be awesome!

**Comment by snoyberg** [comment]
When I look at documentation generated on Hackage, for instance, I don't see any cross-package links created. Are you sure this is something `haddock` is capable of producing?

**Comment by snoyberg** [comment]
Closing, no response, and suspected upstream issue

**Comment by jwaldmann** [comment]
Yes, you're probably right with upstream. Thanks for your time.
