### ISSUE TITLE
re-running Setup.hs and change detection

### ISSUE THREAD

**Issue by emmanueltouzery** [commercialhaskell/stack#2357]
I took the habit of managing my post-install setup things in the `Setup.hs`. The advantages are clear: it's coded in haskell, and it has access to the app data directory, where the binary will get installed.

I'm using it now for instance, to copy the QML data files and icons that a haskell QML application needs to the installation folder.

My issue is with stack optimizing the build with dirty checking, and if it detects that no haskell files changed, it won't re-trigger the Setup.hs. That obviously doesn't work for me, because I'd like my QML files and icons to get copied every time I run stack install during development. stack is so smart that not even touch Setup.hs or of another .hs file helps to re-trigger its execution. I must physically change the contents of one file.

I can't find a flag for stack that would trigger just the Setup.hs and nothing else (or little else; certainly `clean` and `--reconfigure` force rebuilding too many things).

Should I write a shell script? I found I could leverage `stack path` to get the installation folder, but it's less portable that the haskell in my Setup.hs, and haskell is nicer...

Maybe it could make sense to add a new flag in stack to just re-run the `postBuild` hook in the Setup.hs? Something like `--force-setup-postbuild`?

**Comment by mgsloan** [comment]
You can use `--force-dirty` to cause the install to happen again.  `--reconfigure` to cause reconfiguration.

**Comment by mgsloan** [comment]
We could consider supporting `Setup.hs` extra dependencies, maybe if Cabal had that feature.  Lets track that in a different issue, if at all.  I'd prefer to move things away from Cabal hooks, though, they're messy.

**Comment by emmanueltouzery** [comment]
`--force-dirty` also forces rebuilding a lot of things. I understand I'm asking a support question at this point, but I tried on [stackoverflow](http://stackoverflow.com/questions/38250173/re-running-setup-hs-and-change-detection) and [the stack mailing list](https://groups.google.com/forum/#!topic/haskell-stack/Vj-9j8P4nek). I'm not sure how to handle this with `stack`. Maybe a turtle script separate from the app, so that I don't have to write a shell script? I feel currently stack doesn't cater for this use-case, there must be a solution that I don't see.
