### ISSUE TITLE
Panic when compiling in a sandbox on OS X

### ISSUE THREAD

**Issue by acfoltzer** [commercialhaskell/stack#236]
Decided to install `stack` in a sandbox on my OS X machine with GHC 7.10.1. It gets to the end, then panics:

```
[45 of 45] Compiling Stack.Config     ( src/Stack/Config.hs, dist/dist-sandbox-a33f8d48/build/Stack/Config.o )
ghc: panic! (the 'impossible' happened)
  (GHC version 7.10.1 for x86_64-apple-darwin):
	Loading temp shared object failed: dlopen(/var/folders/qk/bpmfcc8s3pq64gs7bn80k60r0000gp/T/ghc12790_0/libghc12790_228.dylib, 5): Symbol not found: _stackzuIf4F8EsotzzFA5770kfJV6V_StackziTypesziFlagName_zdfBinaryFlagName_closure
  Referenced from: /var/folders/qk/bpmfcc8s3pq64gs7bn80k60r0000gp/T/ghc12790_0/libghc12790_228.dylib
  Expected in: flat namespace
 in /var/folders/qk/bpmfcc8s3pq64gs7bn80k60r0000gp/T/ghc12790_0/libghc12790_228.dylib

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

Failed to install stack-0.0.1
```

Full verbose log here: https://gist.github.com/acfoltzer/6a757ed21205b325f804

**Comment by FranklinChen** [comment]
Same here.

**Comment by snoyberg** [comment]
@manny-fp did our OS X builds, can you chime in? I think he used 7.8.4 instead of 7.10.1.

**Comment by arkravitz** [comment]
Same problem here by the way with 7.10.1

**Comment by snoyberg** [comment]
Would anyone be able to report this upstream to GHC?

**Comment by acfoltzer** [comment]
It looks to be this bug, which will be fixed in 7.10.2: https://ghc.haskell.org/trac/ghc/ticket/10322

**Comment by snoyberg** [comment]
It doesn't seem like there's a good workaround. In that case, should we close this issue with the understanding that stack needs to be built with GHC 7.8 for now on Mac?

**Comment by acfoltzer** [comment]
I think so. From a documentation point of view, it might be good to call this out elsewhere, otherwise I bet others will open a duplicate ticket.

**Comment by snoyberg** [comment]
Maybe the download wiki page. Could you update it? I'm no longer at my
computer

**Comment by acfoltzer** [comment]
Done!

**Comment by snoyberg** [comment]
Thank you
