### ISSUE TITLE
stack ghci doesn't re-use generate object files (-fobject-code)

### ISSUE THREAD

**Issue by lostman** [commercialhaskell/stack#2368]
I have `:set -fobject-code` set in `~/.ghci`

Inside `stack exec bash` running `ghci` for the first time:
```
λ load src/Main.hs
...
[98 of 98] Compiling Main             ( src/Main.hs, src/Main.o )
Ok, modules loaded: ...
(21.55 secs, 15,353,064,024 bytes)
```
And subsequently:
```
λ :load src/Main.hs
Ok, modules loaded: ...
(0.42 secs, 402,213,392 bytes)
```

However, `stack ghci` *always* rebuilds everything:
```
❯ stack ghci
[  1 of 104] Compiling ...
```

```
❯ stack --version
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
```

**Comment by mgsloan** [comment]
You're encountering https://github.com/commercialhaskell/stack/issues/1364 - you probably want to use `--no-build`.  I have a WIP solution to this, hopefully ready soon!
