### ISSUE TITLE
Add options to override locations of programs called from stack

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2369]
(This issue is split off from https://github.com/commercialhaskell/stack/issues/593.)

It should be possible to specify the locations of the programs that stack calls, like `ldd` or `strip`.

The location of `gcc` can be specified via `--with-gcc` since https://github.com/commercialhaskell/stack/pull/2264.

**Comment by mgsloan** [comment]
Good idea!  Should also share code with https://github.com/commercialhaskell/stack/issues/652

**Comment by nh2** [comment]
This would allow stack users to link with the `lld` linker, see https://www.reddit.com/r/haskell/comments/63y43y/liked_linking_3x_faster_with_gold_link_10x_faster/

**Comment by kgadek** [comment]
I published #3118 as a quick solution to overriding `ld` and `strip`.

Also, my cabal (`1.24.0.2`) reports:
```
The flags --with-PROG and --PROG-option(s) can be used with the following programs:
  alex ar c2hs cpphs gcc ghc ghc-pkg ghcjs ghcjs-pkg greencard haddock happy
  haskell-suite haskell-suite-pkg hmake hpc hsc2hs hscolour jhc ld lhc lhc-pkg
  pkg-config strip tar uhc
```
Quite a few. The complete solution should cover them all.

I've started playing around more comprehensive code.

**Comment by dukedave** [comment]
Hi, sorry if this is unrelated:
Could this (and #593) be and underlying reason for the issue mentioned in [this comment](https://github.com/LumiGuide/haskell-opencv/issues/104#issuecomment-358023847)?

**Comment by mgsloan** [comment]
I've commented on that issue, I don't think it's related

**Comment by snoyberg** [comment]
Would #1438 (adding a `configure-options`) fully subsume this? At least for the examples given, I don't believe Stack calls these executables directly.

**Comment by snoyberg** [comment]
I believe the new `configure-options` feature on master will address this, closing. If someone has a use case which isn't addressed, please add some clarification.
