### ISSUE TITLE
configuring gcc path seems not to work as intended for dependencies

### ISSUE THREAD

**Issue by simonjantsch** [commercialhaskell/stack#2370]
Pullrequest #2264 added an option to specify which gcc should be used by stack when building a project. I tried this with a project that requires a specific gcc version to build a dependency and it still seems to use the global gcc in $PATH. 

The project I'm trying to build is: https://github.com/simonjantsch/vvt

When running `stack clean; stack build --verbose --cabal-verbose` I get the output in the attached file. bindings-llvm is the relevant dependency.
[stack.txt](https://github.com/commercialhaskell/stack/files/359861/stack.txt)

When manually changing the gcc in path to the right one (gcc version 4.9.3 works for instance) the project compiles.

**Comment by sjakobi** [comment]
Which gcc version is the build supposed to fail with?

**Comment by sjakobi** [comment]
When using `--with-gcc /usr/bin/gcc-4.8` I already get a compile failure for `bindings-llvm`'s custom Setup.hs which, so I suspect, isn't compatible with Cabal-1.24… :(

**Comment by sjakobi** [comment]
Ok, using Cabal-1.22.5.0 I get a bit further until

```
    Configuring bindings-llvm-0.1...
    Warning: Instead of 'ghc-options: -cpp -cpp' use 'extensions: CPP CPP'
    setup: The program 'llvm-config' is required but it could not be found.
```

I can see though that the `--with-gcc` option is correctly passed to the various `setup configure` calls, so I'm currently assuming that some other issue is at play in either `bindings-llvm` or `vvt`.

@simonjantsch: Can you build your project with `cabal --with-gcc` and the "wrong" gcc on the PATH?

I'd also be more convinced of a problem with `stack` if someone could demonstrate the problem on a different project that doesn't use `bindings-llvm`.

**Comment by simonjantsch** [comment]
@sjakob After looking at this again I believe your right, this has something to do with the llvm-config invoking gcc. Too bad, I was hoping for this to fix my issue. I'm closing the issue, thanks for the support!
