### ISSUE TITLE
error: package id couldn't be found

### ISSUE THREAD

**Issue by donnut** [commercialhaskell/stack#238]
Installed `stack` on Arch Linus. cabal and ghc are installed using `nix`. Running `stack build` in an empty directory gives the output:

    No .cabal file found in directory /home/donnut/dev/haskell/test/
    Writing default config file to: /home/donnut/dev/haskell/test/stack.yaml
    After installing Cabal, the package id couldn't be found (via ghc-pkg describe Cabal). This shouldn't  happen, please report as a bug

I tried `stack build --system-ghc`, with the same result. 
Running `stack ghc` outputs:

    ghc: can't find a package database at /nix/store/dhwpkyhh5fc7093695n3bi022zfdrp3q-haskell-aeson-ghc7.8.4-0.8.0.2-shared/lib/ghc-7.8.4/package.conf.d/aeson-0.8.0.2.installedconf/

Is `nix` the problem here? Is it correct to say that I don't need `nix` anymore to use different versions of ghc?

**Comment by bitemyapp** [comment]
@donnut if you're on Nix I wouldn't recommend attempting to use the system ghc and instead let stack use its own GHC if possible. Much of the benefit of Nix+Haskell is in caching/managing package dependencies, but if you're using Stack you're using Stackage/LTS snapshots anyway.

**Comment by snoyberg** [comment]
Fairly certain nix is the issue, what do you get when you run:

    ghc-pkg list Cabal

Since stack uses the Cabal library to do the building, it requires it to be already present.

Also, can you try with `--no-system-ghc`?

If this turns out to be the issue, it would be good to get this documented in the Wiki's FAQ page.

**Comment by donnut** [comment]
ghc-pkg list Cabal issues a long list:
    /home/donnut/.nix-profile/bin/../lib/ghc-7.8.4/package.conf.d/aeson-0.8.0.2.installedconf
    ...

and `stack build --no-system-ghc` did oke, but when I try `stack ghc` it outputs:

    GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
    ghc: can't find a package database at /nix/store/dhwpkyhh5fc7...

**Comment by snoyberg** [comment]
You'd need to use `--no-system-ghc` for all commands, otherwise it will keep reverting back to the nix-installed one. Perhaps we should have a config options about whether to use the system GHC.

**Comment by snoyberg** [comment]
If you're building stack from master, you can now add `system-ghc: false` to ~/.stack/stack.yaml to get the desired behavior. Modifying your PATH to not include GHC will also work.

**Comment by snoyberg** [comment]
@donnut Should we consider this issue resolved?

**Comment by donnut** [comment]
Yes, it works when I keep using `--no-system-ghc.
Thanks!
