### ISSUE TITLE
Can't use component syntax with hackage package TARGETs

### ISSUE THREAD

**Issue by dschalk** [commercialhaskell/stack#2382]
stack build --file-watch --test --copy-bins --haddock wai-extra :warp warp:doctest --exec 'echo Yay, it worked!'  returns  "Could not find a component named warp". I am using 64 bit Ubuntu 14.04. Prior to running the code, I entered "stack install wai warp". I can import Network.Wai in stack ghci.

**Comment by sjakobi** [comment]
This sounds like `warp` is not one of your local packages. As documented [here](http://docs.haskellstack.org/en/stable/build_command/#components) you can only address the components of your local packages, not dependencies.

**Comment by sjakobi** [comment]
@dschalk: I have opened #2384 for improvement of the error message.

A PR would be most welcome!

**Comment by mgsloan** [comment]
I've moved the title to body and made the title a summary of the issue.  Which is that you can't currently ask stack to build + run the test of a dependency, it must be a local package.

**Comment by sjakobi** [comment]
> Which is that you can't currently ask stack to build + run the test of a dependency, it must be a local package.

Actually it's not even clear from the original issue description whether wai-extra and warp were dependencies of the project.

@dschalk: Can you give us the output of `stack list-dependencies` for your project?

> I don't see any reason we shouldn't lift this restriction.

I'm a bit worried that the distinction between local (project) packages and others might become even more fuzzy.

Would `stack ide targets` then list targets for both project packages and dependencies? Should we add a flag `--include-dependencies`?

Apart from these concerns, I do agree though, that having an easy way to run the test suites or benchmarks for a dependency would be a nice thing to have.

**Comment by mgsloan** [comment]
> I'm a bit worried that the distinction between local (project) packages and others might become even more fuzzy.

True!  It would have some funny interactions with `--test` and targets like `:comp-name`

**Comment by snoyberg** [comment]
Closing, it seems like the original problem is still unclear
