### ISSUE TITLE
Improve error message for bad build targets

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2384]
See #2382.

The error message "Could not find a component named warp" could be a lot better:

It could:
- point out the available targets (or refer to `stack ide targets`)
- detect that a target refers to a non-local package
- link to documentation

**Comment by v0d1ch** [comment]
Is this ticket still needed? When running:

```
stack build --file-watch --test --copy-bins --haddock wai-extra :warp warp:doctest 
  --exec 'echo Yay, it worked!'
```
I get:

```
- warp doesn't seem to be a local target. Run 'stack ide targets' for a list of available targets
- Unknown local package: warp

```

So it seems we have the information that warp is probably not a local target. 

If we still need to implement this what should be the best error message here @mgsloan ?

**Comment by sjakobi** [comment]
@v0d1ch Thanks for the update!

I think that error message is good enough to close the issue. Feel free to re-open if you disagree of course!
