### ISSUE TITLE
Can't install stack from cabal on FC20

### ISSUE THREAD

**Issue by chris-martin** [commercialhaskell/stack#239]
The docs say

> stack is available on Hackage (`cabal install stack`)

so I just ran that. Result:

```
> cabal install stack
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: stack-0.0.0
rejecting: base-4.6.0.1/installed-8aa... (conflict: stack => base>=4.8 && <5)
rejecting: base-4.8.0.0, 4.7.0.2, 4.7.0.1, 4.7.0.0, 4.6.0.1, 4.6.0.0, 4.5.1.0,
4.5.0.0, 4.4.1.0, 4.4.0.0, 4.3.1.0, 4.3.0.0, 4.2.0.2, 4.2.0.1, 4.2.0.0,
4.1.0.0, 4.0.0.0, 3.0.3.2, 3.0.3.1 (global constraint requires installed
instance)
```

I don't really know what this means because I've never been able to understand cabal.

**Comment by snoyberg** [comment]
You've just discovered why we wrote stack :)

That error message means "you need GHC 7.8 or higher, but you don't have it." Recommendations:

* Install GHC 7.8 and then retry with cabal
* Just download the stack binary

I recommend the latter

**Comment by snoyberg** [comment]
If you don't mind, I'd like to close this issue, as using the binaries or upgrading GHC should fix the problem. If the issue remains, please reopen.

**Comment by chris-martin** [comment]
Sigh, I guess it'll be easy once I upgrade to FC22. Thanks.
