### ISSUE TITLE
Run integration tests on Windows

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2391]
(This is split off from #2331)

@borsboom commented:

> We did try to run integration tests on AppVeyor at one point, but they were always timing out. If someone wants to take a stab at getting it working again, that would be great. Another approach would be setting up a Jenkins slave running Windows on AWS.

Typical jobs on Appveyor currently take ~18 minutes. With [a job time limit of 60 minutes](https://www.appveyor.com/pricing) I think we should be able to fit in the integration tests somehow.

**Comment by snoyberg** [comment]
We're running these on Azure now!
