### ISSUE TITLE
Add `stack travis` command for generating Travis CI config

### ISSUE THREAD

**Issue by TerrorJack** [commercialhaskell/stack#2396]
It would be nice to have a `stack travis` command to generate a config file for Travis CI, and authors of new packages can easily get that green little badge on project homepage. Similarly this can be implemented for other CI services (like AppVeyor).

In its simplest form, the command simply accepts some flags (CI platform/architecture/ghc and stackage resolver version/extra dependencies, etc) and generate configs with a mustache template. We may also try to determine extra dependencies to install from the cabal file, generate commands to install the dependencies, and raises an error if the dependency is not available on the CI platform.

**Comment by mgsloan** [comment]
Interesting idea!  One thing that this could also address is allowing stack to update the travis script template.  This way we can improve the way the travis setup works, and have these changes affect all projects that use stack + travis.  Currently, each user needs to manually update their travis script.

On the other hand, I'm not sure if this automation would be worth its complexity.  Worth considering, though

**Comment by steshaw** [comment]
Just to note obvious places to crib from:

- https://github.com/hvr/multi-ghc-travis
- https://github.com/phadej/travis-meta-yaml

**Comment by snoyberg** [comment]
We include Travis configuration files in the docs directory, I think this is as far as we're going to go with this for now.
