### ISSUE TITLE
Delete Stack.Types to improve build times

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2405]
(Split off from #2334)

> Modules would then only depend on the Stack.Types.* modules that they actually need and e.g. Stack.Clean wouldn't have to be recompiled after a change in Stack.Types.Nix.

**Comment by Blaisorblade** [comment]
Done for the library, doing it for tests.
According to the PVP, this would forces a version bump to 1.2. Should I readd Stack.Types in or bump the version?

In my last change related to #2334 (0628ff1752793d3323bf68e8c31f8d7d967771bc), I left reexports in to keep the same API and didn't wonder about the PVP.
