### ISSUE TITLE
Split Stack.Options up and move option parsers to option types

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2406]
(Split off from #2334)

> Because Stack.Options has a lot of dependencies it is currently recompiled after most changes.
Splitting it up would also make changes on option types more localized.

**Comment by lucamolteni** [comment]
Any idea on how to split it?

**Comment by Blaisorblade** [comment]
@lucamolteni
IIUC, "move option parsers to option types" is to move each `Parser X` together with the definition of `X` in package `Foo`. A smaller `Stack.Options` with leftovers without a good place might be fine.

I'd wait the merge of #2437 though (should be today or tomorrow) to avoid conflicts.

**Comment by Blaisorblade** [comment]
@lucamolteni Now #2437 is merged. Do you want to try this? Otherwise I might get to it... (I'm also somewhat new here).

**Comment by lucamolteni** [comment]
@Blaisorblade Not sure I can try it in these days, since I'm almost going on vacation. Have fun with that :)

**Comment by lwm** [comment]
Hey folks, this seems like a good first bite for me. 

Expect something soon-ish, just wanted to give a heads up.

**Comment by lwm** [comment]
Please give #2587 a review if you have time! :beers:
