### ISSUE TITLE
Move command definitions out of Main

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2408]
(Split off from #2334)

It would be really nice if all code that is specific for a command could be defined in the same module (and a separate types module ;)). E.g. I wish that in `Stack.Clean` I could define something like

```
cleanCommand :: Command CleanOpts
cleanCommand = Command
    { commandName = "clean"
    , commandDescription = "Delete build artifacts in the current project"
    , commandAction = withEnvConfigNoLock (\globalOpts cleanOpts -> clean cleanOpts)
    , commandOptsParser = cleanOptsParser
    , commandAvailableInInterpreterMode = False
    }
```

In order not to introduce a dependency on `Stack.Setup`, `withEnvConfigNoLock` would only be a smart constructor for some datatype that defines actions that run in the various `StackT` environments.

The `Command` type above needs some fleshing out to allow for subcommands (as needed for e.g. `stack ide targets`) etc.

I'd also propose to move `Main.commandLineHandler` into a module `Stack.CLI`. At the core of `commandLineHandler` should probably be something like

```
traverse
  addCommand
  [ buildCommand
  , setupCommand
  , ...
  ]
```

@chrisdone commented on #2334: 

> Your proposal here sounds like a nice way to reduce compilation too, and clear up the way commands are declared nicely.

**Comment by vanceism7** [comment]
I can try my hand at this one

**Comment by dbaynard** [comment]
👍 I don't think the PR from 2016 is forthcoming — I'll leave the tag for you @vanceism7 ?

The specific details have changed, somewhat. In particular, there are a few PRs which massively change the internals — would you make sure that changes you make are compatible?

Also there are some other related issues.

**Comment by vanceism7** [comment]
Hey @dbaynard, I was actually wondering if the state of the app was still the same since this was from a while back. Are the PRs you speak of already merged into master? Thanks!

**Comment by vanceism7** [comment]
Oh gotcha, well if this issue isn't as important as it would've been before, I'm happy to work on something else. I don't know the priorities of the project so whatever direction you can provide is greatly appreciated!

**Comment by dbaynard** [comment]
Well, in general there's https://github.com/commercialhaskell/stack/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22 (also there's a 'Newcomer friendly' label — I don't know whether that would be appropriate.

There are also milestones — e.g. https://github.com/commercialhaskell/stack/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22P1%3A+Must%22

Then there are issues I'd like to resolve/see resolved (e.g. #3887).

Oh, and I'm untagging 'awaiting pull request'
