### ISSUE TITLE
bad resolver recommends "nightly-2015-01-01", which confused me

### ISSUE THREAD

**Issue by radix** [commercialhaskell/stack#241]
If I put `resolver: nightly` in my stack.yaml file (which I just tried), I got this message

```
AesonException "Invalid resolver value: nightly. Possible valid values include lts-2.12, nightly-2015-01-01, and ghc-7.10."
```
This made me think that `nightly-2015-01-01` was the only nightly I could use for some reason. Of course I read "include" as "are", which was my mistake, but an easy one to make.

Showing the *entire* list of possible values would be nice, but perhaps infeasible? It would presumably require an HTTP request to Stackage, and may also be overwhelming given that there are presumably hundreds of nightlies.

**Comment by bitemyapp** [comment]
@radix that or demonstrated the date format, explaining nightly as a special case.

**Comment by drwebb** [comment]
It would be nice to just have 'nightly' as an option, can we use
http://www.stackage.org/download/snapshots.json

**Comment by snoyberg** [comment]
I'm definitely open to improvements to the wording to be less confusing. In fact, if you have a better approach, feel free to just edit it!

@drwebb Taking that approach would remove the possibility of having reproducible builds, as suddenly a new Stackage Nightly would change what your code is built against.

**Comment by snoyberg** [comment]
Thanks for the PR. Should we close this issue?

**Comment by radix** [comment]
Yeah, I'll close it. I mentioned what I think is a nice longer-term solution in https://github.com/commercialhaskell/stack/issues/211#issuecomment-110510693.

Thank you for the review/merge!
