### ISSUE TITLE
"stack install ghc" generates "a specified local key could not be updated from a keyserver."

### ISSUE THREAD

**Issue by gdennie** [commercialhaskell/stack#2411]
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
==> Updating trust database...
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
gpg: refreshing 8 keys from hkp://pool.sks-keyservers.net
gpg: requesting key 9CC35CF1 from hkp server pool.sks-keyservers.net
gpg: requesting key CA25678A from hkp server pool.sks-keyservers.net
gpg: requesting key AEEA755C from hkp server pool.sks-keyservers.net
gpg: requesting key 3E0D0813 from hkp server pool.sks-keyservers.net
gpg: requesting key 3E652008 from hkp server pool.sks-keyservers.net
gpg: requesting key A47D45A1 from hkp server pool.sks-keyservers.net
gpg: requesting key F93FC717 from hkp server pool.sks-keyservers.net
gpg: requesting key 4CA56930 from hkp server pool.sks-keyservers.net
gpgkeys: key 197B51FF0E441E4EAE58DC2A93E65E2D9CC35CF1 not found on keyserver
gpg: DBG: armor-keys-failed (KEY 0x197B51FF0E441E4EAE58DC2A93E65E2D9CC35CF1 BEGIN
) ->0
gpg: DBG: armor-keys-failed (KEY 0x197B51FF0E441E4EAE58DC2A93E65E2D9CC35CF1 FAILED 6
) ->6
gpg: key CA25678A: "Alexey Pavlov (Alexpux) <alexey.pawlow@gmail.com>" 4 new signatures
gpg: key AEEA755C: "Martell Malone (martell) <martellmalone@gmail.com>" 3 new signatures
gpg: key 3E0D0813: "Ray Donnelly (MSYS2 Developer - master key) <mingw.android@gmail.com>" 2 new signatures
gpg: key 3E652008: "Ignacio Casal Quinteiro <icquinteiro@gmail.com>" 2 new signatures
gpg: key A47D45A1: "Alexey Pavlov (Alexpux) <alexpux@gmail.com>" 1 new signature
gpg: key F93FC717: "Martell Malone (martell) <me@martellmalone.com>" not changed
gpg: key 4CA56930: "Ray Donnelly (MSYS2 Developer) <mingw.android@gmail.com>" 2 new signatures
gpg: Total number processed: 7
gpg:              unchanged: 1
gpg:         new signatures: 14
gpg: keyserver communications error: key not found
gpg: keyserver communications error: bad public key
gpg: 3 marginal(s) needed, 1 complete(s) needed, PGP trust model
gpg: depth: 0  valid:   1  signed:   4  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   4  signed:   3  trust: 0-, 0q, 0n, 4m, 0f, 0u
gpg: depth: 2  valid:   3  signed:   0  trust: 3-, 0q, 0n, 0m, 0f, 0u
gpg: keyserver refresh failed: bad public key
==> ERROR: A specified local key could not be updated from a keyserver.

**Comment by mgsloan** [comment]
Typically gpg is not involved in `stack build` / `stack install`.  Do you have `gpg-verify` set to `true`?  If so, then you need a working gpg configuration (not too knowledgeable about that myself - pinging @dysinger and @borsboom )

Also, this is not how you install ghc, since it is not a hackage package.  Instead, use `stack setup` to install it.

**Comment by RieksJ** [comment]
I used `stack setup` to install haskell. I have the same error.
~~~
gpg: keyserver refresh failed: bad public key
==> ERROR: A specified local key could not be updated from a keyserver
~~~
earlier in the output, I have seen
~~~
[Extracting very many files]
Extracting  msys64\var\log
Extracting  msys64\var\log\old
Extracting  msys64\var\log\pacman.log
Extracting  msys64\var\opt
Extracting  msys64\var\tmp

Everything is Ok

Folders: 546
Files: 12804
Size:       155115162
Compressed: 165253120
mkdir: cannot change permissions of '/dev/shm': Permission denied
mkdir: cannot change permissions of '/dev/mqueue': Permission denied
~~~
Might that be related?

**Comment by mgsloan** [comment]
Seems likely to be related.

Closing this, as it's an old support ticket.  If you think this is in error, please comment with more info.
