### ISSUE TITLE
Investigate whether generating docker containers requires using docker for build

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2416]
Split off from https://github.com/commercialhaskell/stack/issues/2337 - is using docker to build required for generating docker containers?

**Comment by borsboom** [comment]
No, I don't believe it is required.  I've accidentally used `stack image container` on my Mac without enabling Docker, and it happily built a Linux image containing a Mac executable.

**Comment by mgsloan** [comment]
Cool, makes sense to me!
