### ISSUE TITLE
Clear Travis cache periodically

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stack#2428]
As discussed, the build cache for cabal builds can mask circumstances where cabal will generate by default faulty plans; we lacked an issue for this.

We discussed this before in #2390 and in
https://github.com/commercialhaskell/stack/pull/2273#issuecomment-234756651, and the idea was to clear the cache periodically.

> > I wonder if we should get it to nuke the build cache periodically (every 24 hours?) in order to catch problems like the one currently masked.
> 
> That sounds like a good idea! Maybe we could have a cron job that runs true | travis cache --delete or so. Here are the relevant docs: https://docs.travis-ci.com/user/caching/#Clearing-Caches

I guess one just needs a machine for the cron job with the needed Travis credentials.

**Comment by borsboom** [comment]
We could probably put something like that on our Jenkins server.  OTOH, maybe it would be possible right in the `.travis.yml` to check the age of the cache and clear it if it's older than N hours.

**Comment by Blaisorblade** [comment]
I think our `.travis.yml` takes control *after* setting up the travis cache. Still, one might remove the cached directories, and hopefully Travis won't mind. I'd restrict that to builds on the master branch for faster feedback on PRs.

Also, travis cache does show "last modified" timestamps. We'd only need to ensure there are enough credentials to run Travis.

```
$ travis cache
On branch master:
cache-linux-precise-0a5796697ef961b8ec0b10ad2046fa9e0610eb05ad66eddcdd7689105865556e--compiler-GHC7.10.3.tgz   last modified: 2016-08-07 16:51:38  size: 211.68 MiB
cache-linux-precise-26448bcc13f848f908b3b6a4a2720b96fbbd0ac8ffa4d7f58ade4575f13fc866--compiler-GHC8.0.1.tgz    last modified: 2016-08-07 16:58:02  size: 196.25 MiB
cache-linux-precise-44fb974767d48bcb72af3ab721f20e457ed98d0c8abf0ce531a5ec264d0e6bd3--compiler-stack7.8.4.tgz  last modified: 2016-08-07 16:41:35  size: 110.66 MiB
cache-linux-precise-60c7285ab21b73cf9f12fede2336a91bba7340b9a92b9ad4dbac5c671afbe722--compiler-GHC7.8.4.tgz    last modified: 2016-08-07 16:59:52  size: 209.02 MiB
```


Meanwhile, testing this *once*—will we stay in the time limits?
I've cleared caches for two configs on master and restarted their builds.
```
$ travis cache -m cache-osx-precise-a936a61f4b32fb2eb0674c2685ef6397b590ad5d55f6164d9b5ae9f0060aa3d6--compiler-stack7.10.3osx.tgz -df
$ travis cache -m cache-linux-precise-bd99150129df4d553fecbdda2c14319bef5c32ac46903fefad285b1e40afa398--compiler-stack8.0.1.tgz -df
```
https://travis-ci.org/commercialhaskell/stack/jobs/152181608
https://travis-ci.org/commercialhaskell/stack/jobs/152181609

**Comment by Blaisorblade** [comment]
Meanwhile, Travis added cron jobs! https://docs.travis-ci.com/user/cron-jobs/

**Comment by snoyberg** [comment]
We're no longer using Travis, closing
