### ISSUE TITLE
Source directory pollution with `build: haddock: true`

### ISSUE THREAD

**Issue by ekmett** [commercialhaskell/stack#2429]
Building with

```
build: 
  haddock: true
```

is dropping `highlight.js` and `style.css` into my `src` directory.

**Comment by mgsloan** [comment]
I can indeed reproduce this, but it doesn't seem to happen for all builds.  Building some dependency is causing them to get created.  I suspect that [this function in haddock](https://github.com/haskell/haddock/blob/a0ddf910f08e1e1848bb36db202c18c42f15cc07/haddock-api/src/Haddock/Backends/Hyperlinker.hs#L25) is getting called with `outdir == "."` or similar.  Not sure why that's happening, but the results line up.

**Comment by mgsloan** [comment]
I've created https://github.com/haskell/haddock/issues/545 and worked around the issue in stack.
