### ISSUE TITLE
If ghc --version fails for an installed GHC, recover more intelligently

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stack#2430]
In https://github.com/commercialhaskell/stack/issues/2415#issue-167686050 @jhance reported that stack has 

> no way to recover from the --version failing and treating that as "ghc is not installed"'

while this is probably a seldom occurrence, it could certainly happen in strange scenarios. I'm not sure we should detect all of them (what if ghc --version works but half of the libraries were deleted?) but at the very least a `setup` option for "setup GHC again" sounds useful. Also, if `ghc --version` fails, error messages could mention this option, or even do it automatically.

Could we at least accept a PR for this?

**Comment by Blaisorblade** [comment]
>  I think that a broken --version is definitely something that could be reasonably handled, though, or at least give the user instructions on how to purge the broken ghc manually.

At least the non-automated part is uncontroversial then 😄 

And IIUC the automation could be a regression for those who install special GHCs with `--ghc-bindist`.

Thinking more, "remove an installed GHC" is probably even more useful. I do it by hand hesitantly often, by also remove the `.installed` part, even just to save space.

In sum, it'd be nice to have options to:
- force setup again. I do see `stack setup --reinstall` here though, so that doesn't need to be added! Or did it fail somehow for you?
- mention "force setup again" in the error when `--version` fails.
- separately, allowing to remove downloaded GHCs would be a nice (but separate) addition.

**Comment by mgsloan** [comment]
> mention "force setup again" in the error when --version fails.

Makes sense!  In the future we might actually skip the version check in many cases: https://github.com/commercialhaskell/stack/issues/2433

> separately, allowing to remove downloaded GHCs would be a nice (but separate) addition.

Covered by https://github.com/commercialhaskell/stack/issues/133

**Comment by snoyberg** [comment]
This was addressed in #4714, closing.
