### ISSUE TITLE
stack install requires (empty) file named .cabal in global, outside project?

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#2434]
On Windows 10, and version 1.1.2 of stack, I was trying to use `stack install ghc-mod` outside of a project, but could only make it build and install the package if an (empty) file named `.cabal` was included in the `global` folder (the one that holds `stack.yaml`). Is that intended?

**Comment by mgsloan** [comment]
Is the line `packages: []` present in your global project `stack.yaml`?  If not, why not?

**Comment by mpilgrem** [comment]
Thank you. That line was not there and including it removed the need for the file named `.cabal`.

The line was not there because I 'cleaned-up' `stack.yaml` and did not appreciate a difference between the `packages` field not being present at all and `packages: []`.

**Comment by mgsloan** [comment]
Yeah, the idea is it's more common to have a single package config than a packageless config.
