### ISSUE TITLE
Nix: use makeSearchPathOutput

### ISSUE THREAD

**Issue by puffnfresh** [commercialhaskell/stack#2435]
At the moment, some users on recent nixpkgs have to explicitly include two different outputs of packages:

```yaml
nix:
  packages: [ncurses.out, ncurses.dev]
```

This is because nixpkgs split headers and libraries apart for some packages and the Stack Nix code does not use the helpers to generate paths. Normally pkg-config handles these things but Stack explicitly passes extra-lib-dirs and extra-include-dirs which don't work when pkg-config isn't involved.

The lib path should be obtained via:

```nix
lib.makeLibraryPath packages
```

And the include path should be obtained via:

```nix
lib.makeSearchPathOutput "dev" "include" packages
```

I'm not sure that explicit references to binary paths are needed, but they should be obtained via:

```nix
lib.makeBinPath packages
```

**Comment by puffnfresh** [comment]
If Stack used the above, we'd be able to just go back to:

```yaml
nix:
  packages: [ncurses]
```

And everything should work fine.

**Comment by YPares** [comment]
Does this work with packages which don't have two splitted outputs?

> Normally pkg-config handles these things but Stack explicitly passes
extra-lib-dirs and extra-include-dirs which don't work when pkg-config
isn't involved.

Are you certain of this? Or did you mean "when pkg-config *is* involved"?

2016-08-04 3:29 GMT+02:00 Brian McKenna <notifications@github.com>:

**Comment by puffnfresh** [comment]
@YPares yes, it defaults to ".out" if there's no ".lib" or ".dev" output.

Yes, if there's a Cabal package which doesn't use pkg-config to find paths then the include and library directories are sometimes not found (but it depends on the package, but ncurses is a common example with Stack) - if Stack uses these helpers, they should always be found.

**Comment by YPares** [comment]
Okay!
Do you think this should be applied also to
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/generic-stack-builder.nix
too?
This provides the `buildStackProject` nix function, used instead of
`mkDerivation` by people making their own custom shell.nix file.

Or should we leave it up to the developers to use makeLibraryPath &
makeSearchPathOutput themselves in their shell.nix?

2016-08-04 10:13 GMT+02:00 Brian McKenna <notifications@github.com>:

**Comment by puffnfresh** [comment]
@YPares yes, you can see that it already uses `makeLibraryPath` in one place. It should be consistent with that.

**Comment by YPares** [comment]
@puffnfresh Do you have a simple example using ncurses so I can run some tests?

**Comment by YPares** [comment]
@puffnfresh Ok, I had a go at it. I'm sending the PR

**Comment by YPares** [comment]
Given the PR has been accepted, I'm closing it
