### ISSUE TITLE
Creating derivative docker image

### ISSUE THREAD

**Issue by hamishmack** [commercialhaskell/stack#2441]
I tried following [these](https://docs.haskellstack.org/en/stable/docker_integration/#derivative-image) instructions, but it looks like maybe they are out of date:

```
$ stack --docker --docker-persist --docker-container-name=temp exec bash
stack@moby:/Users/hamish/test$ apt-get update
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)
E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?
stack@moby:/Users/hamish/test$ sudo apt-get update
sudo: unable to resolve host moby
[sudo] password for stack: 
Sorry, try again.
```

Is there something I need to do to set get root access or is this approach for creating a derivative image no longer supported?  If so what is the best alternative?

**Comment by borsboom** [comment]
You can prefix your `stack --docker` command with `sudo` to get a prompt as root (which the referenced docs already seem to indicate).

**Comment by hamishmack** [comment]
Ah when I did that I got this:

```
$ sudo stack --docker --docker-persist --docker-container-name=temp exec bash
You are not the owner of '/Users/hamish/.stack/'. Aborting to protect file permissions.
Retry with '--allow-different-user' to disable this precaution.
```

So I added a `docker` shell script to run docker with sudo as described [here](https://github.com/commercialhaskell/stack/blob/master/doc/docker_integration.md#security).

I just tried adding `--allow-different-user` instead and that works.

**Comment by mgsloan** [comment]
Cool, sounds like this is resolved!
