### ISSUE TITLE
.ghci support

### ISSUE THREAD

**Issue by ethanpailes** [commercialhaskell/stack#2443]
It would be really nice if there was some way to get `stack ghci` to pick up .ghci files. Right now it seems to be impossible.

It looks like this does not happen automatically right now because `stack ghci` is actually `ghc --interactive`. The -ghci-script option to ghc does not help because `stack ghci` already uses this option to do useful things like loading the project modules, and it looks like there is only one ghci-script allowed at a time.

I would be happy to try to implement this, but I'm having a little trouble getting getting stack to build.

**Comment by hesiod** [comment]
Hmm, for me `stack ghci` picks up `.ghci` files automagically - stack/ghci should output something along the lines of this:
```
Configuring GHCi with the following packages: some-package
GHCi, version 8.0.1: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/username/some-package/.ghci
<snip>
```
AFAIK, there is no limitation of the number of `.ghci` files you can load, in my case, GHCi happily loads three in total (one temporary one created by stack in `/tmp` and two custom ones I wrote).

Are you running on stack 1.1.2? And while this is not really on topic, I'm wondering what kind of issues you have getting stack to build?

**Comment by mgsloan** [comment]
Use `--no-load` to omit the script, or at least, the load portions of the script.

**Comment by ethanpailes** [comment]
@hesiod I notice you are using GHC 8.0.1. My issue might be related to using an older version (7.10). In any case this obviously isn't that important..

My problems building stack are pretty much those described in this thread https://github.com/commercialhaskell/stack/issues/2130. I used nixpkgs master to try to build against. None of the tricks or workarounds in the thread seemed to help stack find zlib.

**Comment by ethanpailes** [comment]
For anyone having similar problems building stack under nix in the future, it may have something to do with the issue mentioned in section 8.5.4.6 of the nix manual. (https://nixos.org/nixpkgs/manual/#builds-using-stack-complain-about-missing-system-libraries)
