### ISSUE TITLE
`stack upload` should allow supplying a URL to upload to a private Hackage server

### ISSUE THREAD

**Issue by lexi-lambda** [commercialhaskell/stack#2446]
Currently, if I am running a custom Hackage server, it would seem that I need to run `stack sdist`, then manually upload the produced tarball. Using `stack upload` is a much nicer interface when uploading to the main Hackage server, so it would be nice if `stack upload` could accept a flag to upload to a different location, instead.

**Comment by snoyberg** [comment]
This was added in version 1.9.1 in the YAML configuration:

    ### hackage-base-url
    
    Sets the address of the Hackage server to upload the package to. Default is
    `https://hackage.haskell.org/`.
    
    ```yaml
    hackage-base-url: https://hackage.example.com/
    ```
    
    Since 1.9.1
