### ISSUE TITLE
Please submit stack to the RHEL EPEL

### ISSUE THREAD

**Issue by silkvine** [commercialhaskell/stack#2447]
Hi, my company uses RHEL. Anything distributed as an RHEL or EPEL package is easily approved for use.  Ev, the Haskell platform. 
I have no experience submitting software to inclusion in the EPEL but I offer to help. 
Thank you

**Comment by borsboom** [comment]
We don't have any experience either, but maybe @juhp has some ideas?  We're happy to work with someone who wants to take on making this happen, and will update our release process once it's done to ensure things stay up to date in the future.

**Comment by juhp** [comment]
Thanks for bringing this to my attention: I need to get stack built for epel 8 and 9.

**Comment by mpilgrem** [comment]
@juhp, I closed this because nothing had happened in 7 years and nobody else had 'liked' it. If it is still live, please do reopen it.

**Comment by juhp** [comment]
Sure, thanks - I think it is fine: it is really a downstream issue, but I had forgotten about this, so it was a good reminder for me. I wanted to do it already last year but I think I got blocked on some dependency, so I need to revisit it.
