### ISSUE TITLE
'stack docker pull` should display progress

### ISSUE THREAD

**Issue by manny-fp** [commercialhaskell/stack#245]
It looks like System.Process.Read.callProcess has different behaviour than System.Process.callProcess, despite what the comment says.  In particular, System.Process.callProcess display stdout/stderr, whereas System.Process.Read.callProcess seems to send it to sinkNull.

@snoyberg @chrisdone Should I modify the comment and create an alternate version that doesn't send stdout/stderr to the bit bucket?

**Comment by snoyberg** [comment]
I leave this to @chrisdone, he was the last one to be playing with how we display output from tools.

**Comment by chrisdone** [comment]
I'd rather rename the command and documentation; I think our default behaviour should be to launch processes silently and not introduce stray stdout writing that doesn't go through monad-logger, as it interrupts our ability to do properly managed output.

The function [sinkProcessStdout](https://github.com/commercialhaskell/stack/blob/master/src/System/Process/Read.hs#L130..L149) is specifically intended for the use-case of running a process (like docker pull) and consuming its output to display progress, although we could make a `runProcessLogging :: (MonadIO m,MonadBaseControl IO m,MonadLogger m) => …` in terms of that which will conveniently run a process and spit everything out as `$logInfo`.

I noticed Dan wrote some progress code which I'll review too. Can you hold off on progress reporting stuff until then?

**Comment by manny-fp** [comment]
Yeah, no big rush, and I can understand why the current _System.Process.Read.callProcess_ behaviour is desirable in most cases (it just isn't in this one, and when I was porting Docker the code from _System.Process.callProcess_ I assumed its behaviour would actually be the same).

Ordinarily I'd be all for using _sinkProcessStdout_, but in this case a disadvantage is that `docker pull` has nicer progress reporting when it's running on a terminal, and "piping" its output through a sink will disable that.  I could probably use `runIn` for this case and be done with it.

Another thing need is a way to display the stderr, which it looks like _sinkProcessStdout_ sends to sinkNull.  That applies to places I'm calling _readProcessStdout_ as well.

I'm happy to make these changes myself, but some direction about the recommended API would be appreciated.

**Comment by chrisdone** [comment]
In that case, `callProcess` isn't used anywhere, so feel free to change its implementation to inherit stdout and stderr.
