### ISSUE TITLE
"invalid argument" error with `stack haddock` and Nixpkgs

### ISSUE THREAD

**Issue by seagreen** [commercialhaskell/stack#2452]
### General summary/comments (optional)

`stack haddock` doesn't work for the `tf-random` package if Nix is set to `enable: true` in the `stack.yml` file.

### Steps to reproduce

```
darcs get http://hub.darcs.net/michal.palka/tf-random
cd tf-random
# set `stack.yml` to `resolver: nightly-2016-07-04`
stack haddock # this works
# switch to the `shell.nix` and `stack.yml` files below
stack haddock
```

shell.nix:
```
with (import <nixpkgs> {});

haskell.lib.buildStackProject {
  name = "none";
  ghc = haskell.compiler.ghc801;
  buildInputs = [
  ];
}
```

stack.yml:
```
resolver: nightly-2016-07-04
nix:
  enable: true
  shell-file: shell.nix
```

### Expected

The last `stack haddock` command to run without errors.

### Actual

Key excerpt
```
2016-08-06 21:10:22.895780: [info] haddock: internal error: src/System/Random/TF/Gen.hs: hGetContents: invalid argument (invalid byte sequence) @(stack-1.1.2-DgLojysm1GF2dDrMpykv6D:Stack.Build.Execute src/Stack/Build/Execute.hs:911:67)
```

Full stderr output: https://gist.github.com/seagreen/4fa489ad9c658fa93591ad0ed0e35dc8

### Stack version

```
$ stack --version
Version 1.1.2 x86_64 hpack-0.14.1
```

### Method of installation

From NixOS 16.09.git.125ffff (Flounder)

**Comment by mgsloan** [comment]
Weird!  Possibly a haddock bug.

**Comment by seagreen** [comment]
Perhaps, or maybe it's an issue with environment variables?

```
$ echo $LANG
en_US.UTF-8
$ nix-shell -pure
$ echo $LANG # nothing, LANG is no longer set
```

Env. variable changes with `nix-shell --pure` are discussed some here: https://github.com/NixOS/nix/issues/318.

Also I just realized that when I set `pure: false` for nix in `stack.yml` the problem goes away, so that should narrow it down some.

**Comment by mgsloan** [comment]
Ahh, could be!

**Comment by chris-martin** [comment]
Does `stack haddock` not use `shell.nix` in the same way that other Stack commands do?

I've added `LANG = "en_us.UTF-8";` to my `shell.nix` to work around a similar problem when running `stack exec`, but it doesn't seem to have any effect when running `stack haddock`.

**Comment by chris-martin** [comment]
You can also work around by adding `LANG = "en_us.UTF-8";` to `shell.nix`.

**Comment by domenkozar** [comment]
Duplicates https://github.com/commercialhaskell/stack/issues/2358

**Comment by chris-martin** [comment]
I kind of think that the dependency on the `LANG` variable is a Haddock bug, though. It seems to be using that even to decode dependency source files, which doesn't make sense since my system's default locale has no bearing on how dependencies are encoded?

**Comment by seagreen** [comment]
@domenkozar: Agreed this is a duplicate. I didn't realize `LANG` was the cause of this problem when I opened the issue. If the Stack team wants to close this one to centralize discussion on the original, go for it.

**Comment by mgsloan** [comment]
Sure, may as well centralize on one issue.
