### ISSUE TITLE
`stack solver` creates a build plan that `stack build` can't follow.

### ISSUE THREAD

**Issue by DanielWaterworth** [commercialhaskell/stack#2453]
### Steps to reproduce

For example:

1. `git clone https://github.com/DanielWaterworth/editor.git&& cd editor&& git checkout stack_bug`
2. Run command `stack solver`.
4. Run command `stack build`.

### Expected

A successful build, or at least successful dependency resolution.

### Actual

https://gist.github.com/DanielWaterworth/e83cded59a6d7f4a3335f4ffb3d177ca

### Stack version

```
$ stack --version
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
```

### Method of installation

* Installed via curl command.

**Comment by DanielWaterworth** [comment]
It looks like `stack solver` doesn't take into account dependencies that are forced by the ghc version. In this case template-haskell.

**Comment by harendra-kumar** [comment]
In the second retry phase when it relaxes the hard constraints to soft preferences it treats even the ghc wired-in packages as preferences. ghc packages should still remain as hard constraints only other packages should be relaxed. I am fixing it.
