### ISSUE TITLE
Don't use ghc-variant with GHCJS

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2463]
See [this ghcjs issue](https://github.com/ghcjs/ghcjs/issues/503).  Something like `ghc-variant: gmp4` may be present in the user's `config.yaml`.  This will break the build of GHCJS projects.  Suggested fix is just to not support ghcjs variants until there's a reason to have a similar feature for it.

**Comment by borsboom** [comment]
This may have gotten fixed in 05ba87e4eb00f491208463520e83caf87c84ced4.  It wasn't my aim, but I made some changes in this area (in particular, GHC builds like gmp4 and libtinfo6 are considered a different concept than GHC variants like integersimple).  Can someone confirm?

**Comment by mgsloan** [comment]
Hmm, indeed it seems like build functionality is fixed in https://github.com/commercialhaskell/stack/commit/05ba87e4eb00f491208463520e83caf87c84ced4#diff-4968f87e674615592e572f2ec593e5b0R384

However, it does appear in `stack path`:

```

stack-root: /home/mgsloan/.stack
project-root: /home/mgsloan/fpco/test/reflex
config-location: /home/mgsloan/fpco/test/reflex/stack.yaml
bin-path: /home/mgsloan/.stack/snapshots/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3/bin:/home/mgsloan/.stack/programs/x86_64-linux-dke0281e10d26d5658794da13e9341f627/ghcjs-0.2.0.20160628_ghc-7.10.3/bin:/home/mgsloan/fpco/test/.stack-work/install/x86_64-linux-dke0281e10d26d5658794da13e9341f627/lts-3.13/7.10.2/bin:/home/mgsloan/.stack/snapshots/x86_64-linux-dke0281e10d26d5658794da13e9341f627/lts-3.13/7.10.2/bin:/opt/host/bin:/home/mgsloan/fpco/test/.stack-work/docker/_home/.local/bin:/opt/host/bin:/opt/stackage/lts-3/extra/bin:/opt/stackage/lts-3/packages/bin:/opt/stackage/lts-3/ghc/bin:/opt/stackage/lts-3/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
programs: /home/mgsloan/.stack/programs/x86_64-linux-dke0281e10d26d5658794da13e9341f627
compiler-exe: /home/mgsloan/.stack/programs/x86_64-linux-dke0281e10d26d5658794da13e9341f627/ghcjs-0.2.0.20160628_ghc-7.10.3/bin/ghcjs
compiler-bin: /home/mgsloan/.stack/programs/x86_64-linux-dke0281e10d26d5658794da13e9341f627/ghcjs-0.2.0.20160628_ghc-7.10.3/bin
local-bin: /home/mgsloan/fpco/test/.stack-work/docker/_home/.local/bin
extra-include-dirs: 
extra-library-dirs: 
snapshot-pkg-db: /home/mgsloan/.stack/snapshots/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3/pkgdb
local-pkg-db: /home/mgsloan/fpco/test/reflex/.stack-work/install/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3/pkgdb
global-pkg-db: /home/mgsloan/fpco/test/.stack-work/docker/_home/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/package.conf.d
ghc-package-path: /home/mgsloan/fpco/test/reflex/.stack-work/install/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3/pkgdb:/home/mgsloan/.stack/snapshots/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3/pkgdb:/home/mgsloan/fpco/test/.stack-work/docker/_home/.ghcjs/x86_64-linux-0.2.0-7.10.3/ghcjs/package.conf.d
snapshot-install-root: /home/mgsloan/.stack/snapshots/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3
local-install-root: /home/mgsloan/fpco/test/reflex/.stack-work/install/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3
snapshot-doc-root: /home/mgsloan/.stack/snapshots/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3/doc
local-doc-root: /home/mgsloan/fpco/test/reflex/.stack-work/install/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3/doc
dist-dir: .stack-work/dist/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/Cabal-1.22.8.0_ghcjs
local-hpc-root: /home/mgsloan/fpco/test/reflex/.stack-work/install/x86_64-linux-dke0281e10d26d5658794da13e9341f627-custom-gmp4/lts-3.13/ghcjs-0.2.0_ghc-7.10.3/hpc
local-bin-path: /home/mgsloan/fpco/test/.stack-work/docker/_home/.local/bin
ghc-paths: /home/mgsloan/.stack/programs/x86_64-linux-dke0281e10d26d5658794da13e9341f627
```

**Comment by borsboom** [comment]
Did you include `ghc-variant: gmp4` in your stack.yaml?  Ordinarily that wouldn't be done; the gmp4 variant was auto-detected based on which version of libgmp was installed on the system (e.g. if you're running CentOS 6).  Nevertheless, this could still be an issue when really using a GHC variant (e.g. integersimple or a genuine custom variant).

I'll bet the reason is that lots of the code uses [platformGhcRelDir](https://github.com/commercialhaskell/stack/blob/b79dae1d554ccee5036f15afc58218110f3e5437/src/Stack/Types/Config.hs#L1288) which includes the GHC variant.  That might need to be modified to leave out the GHC variant when the compiler is GHCJS.  Although having it the path probably won't actually hurt anything.

**Comment by mgsloan** [comment]
Yes, this is with an explicit `ghc-variant: gmp4` setting.

Indeed, it won't hurt anything, but it's not so good that the setting invalidates your ghcjs dbs.

**Comment by dmvianna** [comment]
I reported the original `ghcjs` issue. With `stack-1.2.0` `ghcjs` is set up without issues. :)

**Comment by mgsloan** [comment]
Cool!  I'm going to close this as wontfix.  I looked into leaving GHC version out of `platformGhcRelDir`, and it wasn't straightforward.  There are places where we use that path without knowing which compiler version we are using.
