### ISSUE TITLE
`stack update` not run automatically after deleting/corrupting repo

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stack#2466]
From https://github.com/commercialhaskell/stack/issues/2175#issuecomment-238709383

> I've just gotten `Left ...` after rm -rf ~/.stack/indices/Hackage/git-update—somehow, stack did not figure out it needed to refetch the repo.

This might relate to @rainbyte and @schell's `Left ...` messages in #2175, though those both mention `Left ~/.stack/indices/Hackage/git-update/all-cabal-hashes/.git/objects/pack` and are in Docker containers.
Can we get reproductions of the issue when passing `-v` to `stack`, to get better logs?

**Comment by mgsloan** [comment]
These errors no longer get outputted, closing.
