### ISSUE TITLE
Windows installer and the stack_root env var

### ISSUE THREAD

**Issue by KeeperB5** [commercialhaskell/stack#2468]
The Install/upgrade docs advises to set stack_root env variable, but does so in the hardest possible way for new users. The SET command only sets the variable for current session, after closing command prompt the variable is gone. If I have understood correctly, this variable is needed for many of the stack commands even after the initial setup.

There is too high a chance that either users don't realize they need to type the SET command again when they open new command prompt window with the intention of using stack, or they don't know they can set the variable permanently in system settings.

This is obviously not a good thing. The installer already adds %userprofile%\AppData\Roaming\local\bin to the Path variable, so the installer should also add the stack_root variable.

Thanks for your hard work in supporting Windows too. :)

**Comment by mgsloan** [comment]
Good idea, feel free to open a PR to the stable branch, with such additions.

**Comment by Blaisorblade** [comment]
I've found the right location and sketched a PR; I'll try to compile/test/iterate later today.

**Comment by Blaisorblade** [comment]
Under what conditions can a user write to `C:\sr`? If not, this PR breaks things. #2548 maybe me realize that's probably not the default, especially in enterprise environment.
Reopened to figure out this.

**Comment by mgsloan** [comment]
I'd say it's a better default.  For the enterprise environment, STACK_ROOT can be set.

So to me it is fairly cut and dry.
