### ISSUE TITLE
Docs should mention git as a recommended dependency

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stack#2469]
@KeeperB5 suggested in https://github.com/commercialhaskell/stack/issues/2175#issuecomment-238822435

> Perhaps install documentation should mention requirement for Git?

We should probably mention that Git is recommended for best performance:
1. it allows updating the index incrementally hence faster
2. it's required for stack.yaml mentioning git projects, though it can be installed later.
3. we're not giving good enough errors, see #2241. Though we should just fix this.
4. stack without Git is less tested, so I'm afraid of more bugs like #2241.

I suspect we don't want it as a strict requirement, simply because installing Git on Windows is not entirely trivial and a stack without Git is better than no stack.

**Comment by KeeperB5** [comment]
What's non-trivial about it? I just ran the Git installer and that was it. Of course, command prompt has to be restarted if it was open, because otherwise env vars are not updated.

**Comment by Blaisorblade** [comment]
Disclaimer: not a Windows user, and I'm happy to link to some perfect Git for Windows installer if it exists. In any case Git should be a recommended dependency, since Stack can work without Git.

But I can't pick an installer myself, though I did some googling.

Re installation difficulties: that's hearsay (from a reliable colleague), and expected (*nix on Windows is hard), but it seems the situation has recently much improved and there's *one* standard installer. It seems to be the perfect Git for Windows installer.
The Internet is still littered with references to the troubled history of Git for Windows.
https://github.com/git-for-windows/git/wiki/The-difference-between-MINGW-and-MSYS2

The other installer, though, seems to be GitHub Desktop... not 100% sure which is best.

**Comment by KeeperB5** [comment]
GitHub Desktop bundles Git like most other GUI tools, such as SourceTree. But I do not think (haven't tested) they add location of git executables to PATH.
