### ISSUE TITLE
Prepend warnings with "Warning:" outside verbose mode so they're not taken as errors

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stack#2470]
Here's this happening:
https://github.com/commercialhaskell/stack/issues/2175#issuecomment-238827816

Since users all over the world confuse warnings with errors, I assume this is more widespread.
OTOH, I'm not sure how to change this non-invasively :-(.

**Comment by Blaisorblade** [comment]
BTW: @KeeperB5, would this idea have avoided confusing you?

**Comment by KeeperB5** [comment]
Adding Info, Warning and Error prefixes to messages would certainly go a long way informing user what's what. But on the other hand, would it have a side-effect where proper bugs remain ignored because they're merely warnings?

**Comment by mgsloan** [comment]
Some warnings and errors already do prepending, so it's a little tricky to modify the utilities directly.  However, the new pretty print stuff does add some functions like `prettyWarning` / `prettyError` / etc.  I think it makes sense to add prefixing to these utils and move as much of our warning / error logging to pretty printing as possible.

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and the developments over time in Stack's reporting. If specific issues remain, they can be identified and dealt with individually.
