### ISSUE TITLE
New release & current state of nix support

### ISSUE THREAD

**Issue by YPares** [commercialhaskell/stack#2472]
Due to some shifts in the nixpkgs, stack has received several PRs (esp. this one https://github.com/commercialhaskell/stack/pull/2354 ) lately that make it keep up to date.
But that means the current stack version is not convenient to use with current state of the nixpkgs.
So we were wondering when the new release was planned, and if it was possible to have one soon, so stack's nix support doesn't become out of date.
(ping @mgsloan @borsboom)

**Comment by mgsloan** [comment]
Yup, a new release is certainly long due, and I think is mostly unblocked.  I'd like to have a decent swing at some of the P1 issues - https://github.com/commercialhaskell/stack/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22P1%3A+Must%22 .  But it should be possible to release something soon!

**Comment by mgsloan** [comment]
I believe we can close this now, as we've made a release!  Re-open if in error.
