### ISSUE TITLE
missing OS version info

### ISSUE THREAD

**Issue by haroldcarr** [commercialhaskell/stack#248]
In the OS X section, there is no mention of the minimal version of OS X needed.  There may be similar missing minimal info in the other OS sections too.

**Comment by manny-fp** [comment]
I'll just mention we've only tested on Yosemite.  No reason it shouldn't work on recent older versions, but YMMV.

**Comment by snoyberg** [comment]
@haroldcarr Would you be able to update the Wiki page with that information, and mention if you got the binary working on any other Mac version?

**Comment by jhedev** [comment]
For reference: For me it's working on Mavericks (10.9.5).

**Comment by haroldcarr** [comment]
@snoyberg I can try that.  But before I do, what is this install going to do to my existing gch/etc?  Where does this install put things (which also be useful info to add to the wiki)?

**Comment by snoyberg** [comment]
It puts it all under your .stack directory in your home directory. It
should not affect your existing installation at all.

If you could add that to the wiki, that would be great.

**Comment by manny-fp** [comment]
@snoyberg Do you know the minimum version of Windows?  Which version have you tested on?

**Comment by manny-fp** [comment]
I've added the version info to the OS X section.  Reassigning to @snoyberg to add it to Windows.

**Comment by haroldcarr** [comment]
@snoyberg I added the info about .stack and non-interference to the FAQ.

**Comment by haroldcarr** [comment]
I tried it on an old mac : 10.7.5: did not work:

    ./stack-0.0.0-x86_64-osx
    Illegal instruction: 4

**Comment by snoyberg** [comment]
I've added information on the Windows version I've been building with. I think the issue can be closed, agreed?
