### ISSUE TITLE
aeson-1.0.0.0

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2483]
`stack` should widen its upper bound for `aeson` in the next release. Currently that change is still pending on a new version of `persistent-template`:

```
In the dependencies for persistent-template-2.5.1.6:
    aeson-1.0.0.0 must match >=0.7 && <0.12 (latest applicable is 0.11.2.1)
needed due to stack-1.1.3 -> persistent-template-2.5.1.6
```

**Comment by borsboom** [comment]
I'm tracking the associated Stackage issue (https://github.com/fpco/stackage/issues/1764).  Hopefully it'll just be a version bounds change that can be made in the `stable` branch and a metadata update on Hackage.

**Comment by sjakobi** [comment]
I have started to work on this on the [`2483-aeson-1.0` branch](https://github.com/commercialhaskell/stack/tree/2483-aeson-1.0).

I encountered a few overlapping instances errors like

```
/home/simon/src/stack/src/Stack/Types/BuildPlan.hs:218:30:
    Overlapping instances for FromJSON (Map FlagName Bool)
      arising from a use of ‘.:’
    Matching instances:
      instance (aeson-1.0.0.0:Data.Aeson.Types.FromJSON.FromJSONKey k,
                Ord k, FromJSON v) =>
               FromJSON (Map k v)
        -- Defined in ‘aeson-1.0.0.0:Data.Aeson.Types.FromJSON’
      instance FromJSON a => FromJSON (Map FlagName a)
        -- Defined in ‘Stack.Types.FlagName’
    In a stmt of a 'do' block: pcFlagOverrides <- o .: "flags"
    In the expression:
      do { pcVersionRange <- (o .: "version-range")
                             >>= either (fail . show) return . simpleParse;
           pcTests <- o .: "tests";
           pcHaddocks <- o .: "haddocks";
           pcBuildBenchmarks <- o .: "build-benchmarks";
           .... }
    In the second argument of ‘($)’, namely
      ‘\ o
         -> do { pcVersionRange <- (o .: "version-range")
                                   >>= either (fail . show) return . simpleParse;
                 pcTests <- o .: "tests";
                 .... }’
```

which I naively solved by removing `stack`'s `FromJSON Map x y` instances and adding `FromJSONKey` instances like [here](https://github.com/commercialhaskell/stack/commit/5f6fb5be5e43be9a6ae76b854917cdef3fc2e68d#diff-71ce620143b676503a511e3c4658e502R76).

Yet now I get exceptions when decoding existing `stack.yaml`s and snapshot definitions:

```
~/s/stack (aeson-1|…) $ stack install --ghc-options -j2 --fast
Could not parse '/home/simon/src/stack/stack.yaml':
Aeson exception:
Error in $.flags: failed to parse field 'flags': expected Map k v, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/.
```

Clearly we don't want to change the existing `stack.yaml` format.

@phadej or @bergmark: Can you give a recommendation on how to solve this situation? Add a `FlagMap` newtype that uses the old `FromJSON` instance?

**Comment by bergmark** [comment]
The derived key instances may not be what you expect, see https://github.com/bos/aeson/issues/463

The default instance produces an array of arrays which allows keys to be more complex than just a string.

**Comment by sjakobi** [comment]
Ah, thanks for clearing that up. I guess I'll wait until it's clear how bos/aeson#463 will be resolved then.

**Comment by borsboom** [comment]
@bergmark: any thoughts on when a fix to bos/aeson#463 will be released and/or how we can work around it for now?

**Comment by bergmark** [comment]
There's no schedule for a release atm. The workaround is to write the instance manually using `ToJSONKeyText`.

**Comment by dbaynard** [comment]
This was resolved a while ago. Closing.
