### ISSUE TITLE
Odd error while resolving packages, when building ide-backend-server

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#249]
If I create a `stack.yaml` file which builds ide-backend-server, I get this output from `stack build`: `The following package identifiers were not found in your indices: ghc-7.8.4`

Repro:

```
git clone --recursive https://github.com/mgsloan/stack-issue-249
cd stack-issue-249
stack build
```

@manny-fp helped look into this a bit, and found that if you comment out the ghc sections of ide-backend-server.cabal, it will start buildling:

https://github.com/fpco/ide-backend/blob/e25398990d2267f690b640ac9e8b7dc75102514e/ide-backend-server/ide-backend-server.cabal#L33
https://github.com/fpco/ide-backend/blob/e25398990d2267f690b640ac9e8b7dc75102514e/ide-backend-server/ide-backend-server.cabal#L64..L70

**Comment by manny-fp** [comment]
An important thing to note ] is that this happens when building with Docker, and the Docker image has `ghc-7.8.4.20141229`, rather than `ghc-7.8.4`.  So question is: why is it looking for ghc-7.8.4 when nothing in the cabal file refers specifically to that exact version?

**Comment by snoyberg** [comment]
It's because that's what the snapshot requires. We can add a special case
for ghc that it simply use whatever version is available, since we can't
install a new version anyway.

**Comment by snoyberg** [comment]
@mgsloan Can this be closed?
