### ISSUE TITLE
Travis with caching config installs two ghcs per point in matrix

### ISSUE THREAD

**Issue by steshaw** [commercialhaskell/stack#2494]
This may be a well-known point. The [docs on using Stack with Travis](https://docs.haskellstack.org/en/stable/GUIDE/#travis-with-caching) recommend a configuration which ends up installing two ghcs for each point in the matrix. The first ghc is the one installed by the apt addon via hvr-ghc. The second is the one installed by stack. These two downloads take some time slowing down the process of CI.

Perhaps this has been recommended because the hvr-ghc installation ensures that some required dependencies are present? I'm thinking libgmp but there could be others. I did try just using `stack setup` to get the correct ghc but it fails with a sanity check because it can't find libgmp. However, when [I install libgmp-dev with the apt addon](https://github.com/steshaw/stack-example/blob/f464a2306a6688f7a23898546a8a7b9a3e8c1aa0/.travis.yml), I don't have any trouble with Stack's download of ghc-7.10.3. However, I haven't tested for other versions of ghc.

Would it be considered worthwhile to optimise the configuration to remove the double-downloading of ghc?

**Comment by Blaisorblade** [comment]
Improvements are probably possible and this would be bad—nobody wants to wait longer.

But stack should reuse the downloaded GHC, *as long as it finds it in the PATH*. I've found your build log showing the double-download (https://travis-ci.org/steshaw/stack-example/builds/152204969#L200), but the associated config (https://github.com/steshaw/stack-example/blob/8b388363aa86014cb61ec70b319894270edf707d/.travis.yml), does not add GHC to the PATH—see this line in our config:

```
export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$HOME/.local/bin:/opt/alex/$ALEXVER/bin:/opt/happy/$HAPPYVER/bin:$HOME/.cabal/bin:$PATH
```

And stack reuses the downloaded GHC in our stack's config ([logs](https://travis-ci.org/commercialhaskell/stack/jobs/152280904#L209-L212)).

Does that explain what you've seen, or am I missing something?

## Travis configs are a pain and should be generated

Missing that line is too easy. Maintaining Travis configs is a pain. Especially if you want to support both cabal and stack. Ideally
- you'd have a small stack-only config that you can write by hand—as in https://docs.haskellstack.org/en/stable/travis_ci/. But this is unfriendly to cabal-install users.
or
- you'd *generate* a config for both, using a variant of 
https://github.com/hvr/multi-ghc-travis (https://github.com/hvr/multi-ghc-travis/issues/34).
or
- you'd copy the entire config and beware of changes.

It's especially unfortunate that the easier-to-maintain config is on the specialized page.

# Needed dependencies
Regarding dependencies: `libgmp-dev` should be enough in general—Stack's config shows an example, though I'm not sure what `libgmp` is doing there (at least Ubuntu 14.04 doesn't have it).
```
env: BUILD=stack ARGS="--resolver nightly"
    compiler: ": #stack nightly"
    addons: {apt: {packages: [libgmp,libgmp-dev]}}
```

**Comment by steshaw** [comment]
Thanks @Blaisorblade. I didn't realise that Stack reuses the ghc that's in the PATH if it's the correct version (even when asked to --install-ghc). I've changed my Travis config back to using `hvr-ghc` and it works as expected (i.e. no double download).

In some ways, it would be nicer to have less busy Travis configs which use Stack to work out which ghc to use rather than pre-installing a ghc via the apt addon. I noticed that there's already an issue open for generating the Travis config for a stack project.

Thanks for taking the time to look into this issue. Sorry it wasn't more productive.

**Comment by Blaisorblade** [comment]
> (even when asked to --install-ghc)

Yes, I realize that might be somewhat of a misnomer.

> In some ways, it would be nicer to have less busy Travis configs which use Stack to work out which ghc to use rather than pre-installing a ghc via the apt addon.

Agreed, `libgmp-dev` is enough and that requires less maintenance. Is apt-get any faster than stack in installing GHC?

>  I noticed that there's already an issue open for generating the Travis config for a stack project.

Ah, #2396 :-)

> Thanks for taking the time to look into this issue. Sorry it wasn't more productive.

No worries 😄 —again, Travis is hard!

**Comment by steshaw** [comment]
> Agreed, libgmp-dev is enough and that requires less maintenance. Is apt-get any faster than stack in installing GHC?

I'm not sure. I imagined that it would be about the same but I suppose Travis could have a APT cache or something to speed up `apt-get install`s which would be very common. Still `curls` would be pretty common too (and Travis may have a squid proxy or something to speed up static downloads). Would need to measure :).

**Comment by borsboom** [comment]
Possibly relevant are these two issues against Travis so that Stack can be installed using apt: https://github.com/travis-ci/apt-source-whitelist/pull/7, https://github.com/travis-ci/apt-package-whitelist/issues/379

**Comment by Blaisorblade** [comment]
@borsboom A Stack package could maybe simplify the setup with appropriate dependencies (say, `libgmp-dev`, or maybe GHC itself?). But the Travis team stopped reviewing whitelist requests (probably because they have no good way to review them)—
https://github.com/travis-ci/apt-source-whitelist/pull/295#issuecomment-233153461.

**Comment by Blaisorblade** [comment]
FWIW https://github.com/travis-ci/apt-source-whitelist/pull/295 was finally merged; I don't get if https://github.com/travis-ci/apt-package-whitelist/issues/379 is still needed (which I guess).
