### ISSUE TITLE
Extra-dep which provides an executable doesn't get built

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#250]
I'm not sure if this bug is as generic as the issue title implies, as I've only tried this one case.  Repro:

1) `git clone git@github.com:fpco/stackage-view.git`
2) Add `extra-deps: [ ide-backend-server-0.9 ]` to `stack.yaml`
3) `stack build`
4) Try `stack exec -- which ide-backend-server`

Expected: Path to the executable, as it's been installed

Actual: No results from `which`

I'm not 100% sure if this is a bug or not, but it would be nice to be able to add extra executable dependencies.

**Comment by snoyberg** [comment]
Not a bug, dependencies aren't built like that. Use the deps command to
install that package. You can also list ide-backend-server as a build tool
in the cabal file, which should have the same effect.

**Comment by mgsloan** [comment]
Hmm, in this case if I do `stack deps ide-backend-server`, I get:

```
 While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package ide-backend-server in known packages
```

**Comment by snoyberg** [comment]
> `extra-deps: [ ide-backend-server-0.9 ]`

Did you mean `ide-backend-server-0.9.0`?

**Comment by mgsloan** [comment]
Yes, but that doesn't change the results.  `stack deps` seems to be the right solution here, but it's not working out for me
