### ISSUE TITLE
Weekly collaborators' hangout

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#2504]
@sjakobi @mgsloan @Blaisorblade (and any other collaborators who'd like to join): I'd like to set up a weekly hangout that we can all join to discuss Stack work.

When would be good times of day for all of you?  Perhaps around noon PDT (GMT-7), which would be around 9pm CEST (GMT+2).  

Are any particular days of the week best?

**Comment by sjakobi** [comment]
The time of day is ok for me, although it might make participation difficult for @harendra-kumar who is in Bangalore (GMT+5:30) according to his Github profile.

Regarding days of the week, my preference would be Monday, Tuesday or Wednesday. On Thursday evenings I'd always be unavailable.

**Comment by harendra-kumar** [comment]
Yeah I am at GMT+5:30 but noon PDT would usually work for me. I will try joining whenever I can.

**Comment by Blaisorblade** [comment]
Tuesdays and Wednesdays are not perfect for me—among the available days, that leaves Monday as the best.
I'll try my best to join whenever I can.

Also: what kind of topics do you have in mind @borsboom, that are best discussed in a meeting rather than issues? Do you have some agenda in mind? I'm asking to try to guess which stack-related topics are best left for elsewhere. (Say, for the first meeting).

**Comment by sjakobi** [comment]
> Tuesdays and Wednesdays are not perfect for me—among the available days, that leaves Monday as the best.

To be clear, if Friday, Saturday or Sunday work better for you (or anyone else) I'll usually be able to attend, too.
I only have a slight preference for Monday, Tuesday or Wednesday as it's less probable that there are alternative events that I would like to attend on these days.

**Comment by Blaisorblade** [comment]
Monday *is* fine with me, and avoiding the weekend if possible makes sense.
I guess we're waiting for @mgsloan's times?

**Comment by mgsloan** [comment]
Oh, thought I'd commented on this.  Noon sounds good to me, I prefer that to an earlier time, but as early as 10 am is good too.  I'm flexible on the day of the week.

**Comment by borsboom** [comment]
I've sent out a calendar invite for the upcoming Monday.  Looking forward to "meeting" those of you I haven't met yet!
