### ISSUE TITLE
stack dot doesn't show dependencies like it should

### ISSUE THREAD

**Issue by dysinger** [commercialhaskell/stack#2511]
### General summary/comments (optional)

`stack dot` doesn't seem to work

### Steps to reproduce

go to any complex stack project directory and type `stack dot`

### Expected

I expected to see all my project dependencies

### Actual

I only see top level projects in the graph

```
$ cd ~/src/github.com/commercialhaskell/stack
$ stack dot | dot -Tpng >stack.png
<picture that shows only stack>
```

### Stack version

```
1.1.2, stable & master
```

### Method of installation

* Unofficial static binary I compiled myself

**Comment by dysinger** [comment]
![image](https://cloud.githubusercontent.com/assets/447/17754900/b4ea3080-648b-11e6-8b4b-1ba05510f42d.png)

**Comment by Blaisorblade** [comment]
Confirmed with both 1.1.2 and master on OS X.

**Comment by dysinger** [comment]
I didn't RTFM well. @mgsloan pointed out that there's docs & I'm doing it wrong. https://docs.haskellstack.org/en/stable/dependency_visualization/

while `stack dot --help` says the default depth is "no limits" you must add the --external if you want the dependencies listed in your cabal file to show up.  I didn't know this.

**Comment by mgsloan** [comment]
I've opened https://github.com/commercialhaskell/stack/issues/2520 for improving `--help` for flags that can be either enabled or disabled (`--no-external` vs `--external`)
