### ISSUE TITLE
Stack ignores Cabal-Version requirements

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stack#2518]
Stack currently uses Cabal-1.22.8, so in theory it should fail building cabal files using `Cabal-Version:  >= 1.24`. This way, when a new version is out and new Cabal files require it, the user will learn he needs to upgrade stack. This _might_ be just a warning though, to improve resiliency.
Noticed in #2515.

This should wait on upgrading to 1.24 (#2517), but can be done before supporting the new features (e.g. #2515), even though the point is of course to actually support them.

Ideally, stack right now should admit it doesn't handle `Cabal-Version:  >= 1.24`, but in practice we'd rather hack our way through (as currently) than reject them altogether.

But maybe somebody has different ideas on handling this.

**Comment by mgsloan** [comment]
I think we do get a warning for this case - see https://github.com/commercialhaskell/stack/issues/3029
