### ISSUE TITLE
How to specify a subset of tests to run?

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/stack#2519]
My cabal file contains several tests. I can do `cabal test Foo` and it will run just this one.
What is the stack equivalent? `stack test Foo` does not work.

Example: https://github.com/jwaldmann/haskell-obdd

```
$ stack test obdd-queens
The following target packages were not found: obdd-queens
```

**Comment by Blaisorblade** [comment]
Nontrivial question. `stack test` means `stack build --test`.
Looking at `stack build --help` I'd try `stack build --test --no-run-tests --exec obdd-queens`, even though that feels a bit awkward. Does that help for now?

We should maybe have a more memorable way to do that, like `stack test --suite obdd-queens`.
Thoughts?

**Comment by sjakobi** [comment]
The documentation for stack's target syntax is here: https://docs.haskellstack.org/en/stable/build_command/#target-syntax

In this case the shortest command is `stack test :obdd-queens`. 

>
```
$ stack test obdd-queens
The following target packages were not found: obdd-queens
```

Maybe we should provide a link to the target syntax docs in this error message?!

**Comment by Blaisorblade** [comment]
> Maybe we should provide a link to the target syntax docs in this error message?!

Ah! Maybe in the error message, more likely inside `--help`.

**Comment by Blaisorblade** [comment]
Separately, we might need a Rosetta stone for Cabal users, given that Stack's syntax is different enough.
