### ISSUE TITLE
Can't load tests of a Stack project if they don't compile

### ISSUE THREAD

**Issue by gracjan** [commercialhaskell/stack#2523]
Reporting from here: https://github.com/haskell/haskell-mode/issues/1411

**Comment by mgsloan** [comment]
I believe the issue here is that since the test fails to build, the library doesn't get installed.  Solution probably looks like always doing an implicit "Only deps" build.

**Comment by mgsloan** [comment]
This will be resolved as a side effect of https://github.com/commercialhaskell/stack/pull/2697

**Comment by mgsloan** [comment]
#2697 got merged!  Please re-open if this is still an issue.
