### ISSUE TITLE
shebang solver - automatically generate shebang line for scripts

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#2533]
Support a script shebang solver. Given a script like this:

```
$ cat diagram.hs
{-# LANGUAGE NoMonomorphismRestriction #-}

import System.Environment
import Diagrams.Prelude
import Diagrams.Backend.SVG.CmdLine

main = mainWith $ beside (r2 (1,1)) sq c1
...
```

It should suggest an appropriate shebang line like this:

```
$ stack runghc --solver diagram.hs
#!/usr/bin/env stack
{- stack runghc
    --install-ghc
    --resolver lts-6.7
    --package base
    --package diagrams-lib
    --package diagrams-svg
    --
    -hide-all-packages
-}
```

Sometimes its possible that it is not able to find packages corresponding to the modules or there are multiple of them. In those cases it should show appropriate incompleteness warnings.

When there is an existing shebang line it will use that as the pivot and suggest additional updates to it. When `PackageImports` is in use it can extract the packages from the imports.

There can also be an auto update option to update the script with the shebang changes suggested by the solver.

```
$ stack runghc --solver --update
```

**Comment by harendra-kumar** [comment]
See #1944 as well.

**Comment by Blaisorblade** [comment]
> Sometimes its possible that it is not able to find packages corresponding to the modules or there are multiple of them. In those cases it should show appropriate incompleteness warnings.

So basically this is stack solver with a different input/output format, right? Not only should we share code, but stuff like `--update` would make sense for general `solver` too and should arguably have the same UI—so maybe this should be an option in `solver`, not sure.

**Comment by harendra-kumar** [comment]
> So basically this is stack solver with a different input/output format, right? 

The solver takes a stack.yaml, cabal files and determines extra-deps required to build the project. The cabal files explicitly list the packages and we trust that. 

On the other hand, the primary purpose of shebang solver is to determine the packages needed since there is no cabal file. We will have to determine that by reverse lookup (i.e. map module names to packages). 

We can go a step further and solve for extra-deps as well using the dependency solver but that's going to be expensive unless we cache the results. And each script will need its own private extra-deps (maybe extensible snapshots can be useful here) since different scripts may have conflicting requirements.

**Comment by harendra-kumar** [comment]
> so maybe this should be an option in `solver`

It is already there in solver `--update-config`.

**Comment by mgsloan** [comment]
Yeah, this would be really cool.  We'll need to pick a good metric for resolving modules that are present in multiple packages.  May also be interesting to add support to stackage for listing the module names that are aliased.

**Comment by harendra-kumar** [comment]
I found this interesting repo https://github.com/yamadapc/stack-run-auto. This seems to be already doing essentially what we want here. @yamadapc would you have time to explain how that works or contribute that piece of code here? #1944 also requires a similar functionality.

**Comment by snoyberg** [comment]
I think the new `script` command does essentially the same thing (though I was unaware of this issue). Does the new feature address your goals?

**Comment by harendra-kumar** [comment]
@snoyberg yeah `script` command does the same thing. Is there a way to generate (and maybe update the script as well using a flag) a full she-bang line after a successful import resolution? A complete shebang line is still preferable for fully reproducible scripts.

**Comment by snoyberg** [comment]
By full shebang, you mean including the explicit package list? What makes
that more reproducible?

**Comment by yamadapc** [comment]
I'm sorry, I had never seen this. `stack-run-auto` is separated in a couple of packages for each of the tasks it does: parsing imports, finding local module dependencies recursively, hitting hayoo for finding packages that contain the modules that are necessary.

Since it depends on a 3rd party service I don't think it'd make sense inside stack. `stack script` looks like something that would render it obsolete 😃

**Comment by snoyberg** [comment]
Import resolution depends on metadata in the snapshot itself, which fully
specifies precise versions of all available packages, their flags, and
thereby their exposed modules. There should be no change to that metadata
ever.

**Comment by harendra-kumar** [comment]
Snapshot packages are perfectly fine as long as a module is available only in one package, I was only worried about "extra-deps" i.e. packages which are not in the resolver snapshot and also modules which are available in multiple packages in the snapshot. How does it select  one from multiple possible packages? Or does it ask the user to explicitly specify the package in that case?

**Comment by snoyberg** [comment]
It's stronger than that: it doesn't allow packages outside the snapshot at
all.

**Comment by harendra-kumar** [comment]
That's limiting but ensures reproducibility, I guess one can use `stack runghc` for using packages outside stackage. How about choosing from multiple possible packages from the specified snapshot itself? Does it select one automatically or bails out?

**Comment by snoyberg** [comment]
If there are two packages providing a module, it is considered a conflict
and an error is reported. A snapshot may mark some packages as hidden, and
then that package will not be considered for this logic.

**Comment by harendra-kumar** [comment]
Alright then, I think most of the functionality proposed here is satisfied by the script command. Closing this.
