### ISSUE TITLE
Document extensible snapshots

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#2535]
I wanted to know more about using `extensible snapshots` but could not find any mention in the documentation. Are extensible snapshots same as custom snapshots and the same existing documentation apply? Is the custom snapshot documentation complete and up to date? I do not see `drop-packages` documented anywhere in the documentation. 

Ping @mgsloan.

**Comment by mgsloan** [comment]
Agreed that this is important to have!  I will document it soon.

**Comment by mgsloan** [comment]
Done!  Documented [here](https://github.com/commercialhaskell/stack/blob/master/doc/custom_snapshot.md).
