### ISSUE TITLE
package indirectly depends on multiple versions of the same package.

### ISSUE THREAD

**Issue by JakeEhrlich** [commercialhaskell/stack#2539]
I'm getting a conflict where two copies of deepseq are being requested by different dependencies and it isn't being resolved.
### Steps to reproduce
1. make a new stack project
2. include the following in your extra-deps
3. ansi-wl-pprint-0.6.7.3
4. megaparsec-5.0.1
5. ghc-prim-0.4.0.0
6. include the following in your cabal build-depends
   base >= 4.7 && < 5,
   megaparsec >= 5.0.1,
   ansi-wl-pprint >= 0.6.7.0,
   ghc-prim >= 0.4.0.0
### Expected

Lib and Main to compile without error
### Actual

```
$ stack build --verbose
```

I get the following: https://gist.github.com/JakeEhrlich/3f55c2bd5bcadf529d159fb29b9b1206
### Stack version

```
$ stack --version
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
```
### Method of installation

Installed via `haskell-stack-tool` from the Arch Haskell haskell-core repo: https://wiki.archlinux.org/index.php/ArchHaskell

**Comment by Blaisorblade** [comment]
Basically we're depending indirectly twice on the same package `deepseq-1.4.1.1` with different package ids.
It'd be good to have the actual project files involved. The logs show the resolver was `lts-6.14`. My first guess is that this shouldn't happen unless package databases are corrupted, so this should succeed on a clean system.

```
Warning: This package indirectly depends on multiple versions of the same
    package. This is highly likely to cause a compile failure.
    package deepseq-1.4.1.1 requires array-0.5.1.0
    package deepseq-1.4.1.1 requires array-0.5.1.0
    package pretty-1.1.2.0 requires deepseq-1.4.1.1
    package tagged-0.8.4 requires deepseq-1.4.1.1
    Building tagged-0.8.4...
    Preprocessing library tagged-0.8.4...
    <command line>: cannot satisfy -package-id deepseq-1.4.1.1-9e4eede21ad1dd757949f1f397a13ead: 
        deepseq-1.4.1.1-9e4eede21ad1dd757949f1f397a13ead is shadowed by package deepseq-1.4.1.1-614b63b36dd6e29d2b35afff57c25311
        (use -v for more information)
```

**Comment by mgsloan** [comment]
Does putting `system-ghc: false` in your `config.yaml` cause ghc to need to be installed?  If so, consider running stack setup to get a fresh GHC.  I don't have a link to the relevant discussion, but I recall that GHC's usage of GHC_PACKAGE_PATH is not quite as documented / expected, causing issues like this.

**Comment by filterfish** [comment]
I've just had the same problem and `system-ghc: false` worked. I hate the fact that I have to have an instance of ghc for each project but it solved my problem and, at least for the time being, that makes me happy!

**Comment by Blaisorblade** [comment]
@filterfish 
> I hate the fact that I have to have an instance of ghc for each project

There might be a misunderstanding. Stack will install GHC inside `~/.stack` (or analogue on your system) and it will reuse it across projects needing the same GHC. If you have one system-wide GHC you get at most *one* other copy of that version.

**Comment by filterfish** [comment]
Ah, ok. Thanks for clearing that up.

**Comment by mgsloan** [comment]
Cool, sounds like the suggested workaround works!
