### ISSUE TITLE
On Windows, TH tries to use static version of libsndfile (cause unclear)

### ISSUE THREAD

**Issue by mtolly** [commercialhaskell/stack#2547]
I have narrowed down a bug I've encountered for a while when trying to build my stack-based project on Windows, which uses the C library `libsndfile`. Template Haskell fails with errors related to the C library, because it's trying to use the wrong version for linking. However, I am not entirely sure where the problem lies. For all I know, it could be an error in Stack, GHC, `libsndfile`, or `msys2`/`mingw-w64`. Hopefully someone can point me in the right direction if Stack is not to blame.
### Steps to reproduce

The example and instructions are at [https://github.com/mtolly/win-sndfile-th-bug](https://github.com/mtolly/win-sndfile-th-bug) . The repo contains 2 `stack.yaml`s. The one that works has a single executable module which binds to a `libsndfile` function. The one that does not has two packages, where the first one binds to the `libsndfile` function and the second one is an executable that uses it.

When building the two-package version on Windows, after installing `libsndfile` through `pacman`, errors relating to `libsndfile.a` are printed:

```
ghc.exe: unable to load package `the-dep-0.1.0.0'
ghc.exe: C:\Users\Mike\AppData\Local\Programs\stack\i386-windows\msys2-20150512\mingw32\lib\libsndfile.a: unknown symbol `_FLAC__StreamDecoderErrorStatusString'


ghc.exe: Could not on-demand load symbol '_flac_open'

ghc.exe: C:\Users\Mike\AppData\Local\Programs\stack\i386-windows\msys2-20150512\mingw32\lib\libsndfile.a: unknown symbol `_flac_open'

ghc.exe: Could not on-demand load symbol '_sf_error_number'

ghc.exe: C:\Users\Mike\git\win-sndfile-th-bug\doesnt-work\.stack-work\install\ecb21d6a\lib\i386-windows-ghc-8.0.1\the-dep-0.1.0.0-AIVaSDrcVq78aqf7K5aad6\HSthe-dep-0.1.0.0-AIVaSDrcVq78aqf7K5aad6.o: unknown symbol `_sf_error_number'
```

This is erroneous, since it should not be loading the static version for TH when the dynamic version exists.

This bug happens using either `pkgconfig-depends` or `extra-libraries` to connect to `sndfile`. It also happens if the more complete binding [`hsndfile`](http://hackage.haskell.org/package/hsndfile) is used.

I did discover a workaround, and it basically amounts to deleting the static version entirely and copying the dynamic version to `/mingw32/lib`, then recompiling the dependency package, so the dynamic version is used. I've had to consult [this info](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/4/html/Using_ld_the_GNU_Linker/win32.html) in the past regarding the strange rules by which Unix-style C libraries are linked to on Windows, so maybe something is not configured correctly in how GHC is searching for libraries, or in how the `mingw-w64` `pacman` package for `libsndfile` installs the files.

[Here](http://pastebin.com/Jnm0VN8U) is the verbose build log for the `doesnt-work` package.
### Stack version

```
C:\Users\Mike\git\win-sndfile-th-bug\doesnt-work>stack --version
Version 1.1.2, Git revision c6dac65e3174dea79df54ce6d56f3e98bc060ecc (dirty) (3647 commits) i386 hpack-0.14.0
```
### Method of installation

`stack-1.1.2-windows-i386-installer.exe`

**Comment by mgsloan** [comment]
Not sure if we can fix anything in stack here, closing as an old support ticket.  Glad there's a workaround.
