### ISSUE TITLE
Resolver: lts-6.* of the stack.yaml is interpreted as lts-6_* (NixOS)

### ISSUE THREAD

**Issue by yamafaktory** [commercialhaskell/stack#2551]
Hi,

I am a NixOS user and my current stack version is 1.1.2.

### Steps to reproduce

When trying to boot up Intero, everything goes perfectly well up to **lts-5.9** but fails with any of the **6.x** versions with the following error message:

```sh
error: attribute ‘lts-6_0’ missing, at (string):1:320
```

I've already posted an issue https://github.com/commercialhaskell/intero/issues/203 and sadly using the latest stack version didn't solve it.

**Comment by borsboom** [comment]
@YPares, any ideas?

**Comment by yamafaktory** [comment]
@YPares @borsboom any news on that one? Thank you!

**Comment by yamafaktory** [comment]
@borsboom @mgsloan Switching to NixOS 16.09 did actually help (now can use lts7.x versions). By the way, NixOS has dropped support for LTS, see https://nixos.org/nixos/manual/release-notes.html#sec-release-16.09 :

> Previous versions of Nixpkgs had support for all versions of the LTS Haskell package set. That support has been dropped. The previously provided haskell.packages.lts-x_y package sets still exist in name to aviod breaking user code, but these package sets don't actually contain the versions mandated by the corresponding LTS release. Instead, our package set it loosely based on the latest available LTS release, i.e. LTS 7.x at the time of this writing. New releases of NixOS and Nixpkgs will drop those old names entirely. The motivation for this change has been discussed at length on the nix-dev mailing list and in Github issue #14897. Development strategies for Haskell hackers who want to rely on Nix and NixOS have been described in another nix-dev article.

**Comment by mgsloan** [comment]
@yamafaktory Yes, we are aware of this change.  Glad that the issue has been aided by updating nix.  Please re-open or add additional comments if there is more to do here.
