### ISSUE TITLE
ghc-8.0.1-x86_64-deb7-linux.tar.xz doesn't contain GHC user's guide

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2555]
(I'm opening this issue here because https://github.com/commercialhaskell/ghc doesn't have an issue tracker)

While e.g. [ghc-8.0.1-x86_64-portbld-freebsd.tar.xz](https://github.com/commercialhaskell/ghc/releases/download/ghc-8.0.1-release/ghc-8.0.1-x86_64-portbld-freebsd.tar.xz) contains a full GHC user's guide in HTML and as a pdf in the `/ghc-8.0.1/docs/users_guide/` directory, [ghc-8.0.1-x86_64-deb7-linux.tar.xz](https://github.com/commercialhaskell/ghc/releases/download/ghc-8.0.1-release/ghc-8.0.1-x86_64-deb7-linux.tar.xz) doesn't. As a result, on my machine the link from `~/.stack/programs/x86_64-linux/ghc-8.0.1/share/doc/ghc-8.0.1/html/index.html` to the user's guide goes to a missing file.

**Comment by mgsloan** [comment]
Seems like this should go on ghc trac! https://ghc.haskell.org/trac/ghc/
