### ISSUE TITLE
stack path documentation unclear about dist-dir

### ISSUE THREAD

**Issue by ezyang** [commercialhaskell/stack#2560]
`stack path` outputs a `dist-dir` entry. This entry clearly must be per-package. But the docs for the command give no indication on how Stack decides *which* package to output the dist-dir for (after all, Stack projects are multi-package). My guess is that it's based on your current working directory? Worth an explicit note.

**Comment by mgsloan** [comment]
The `dist-dir` is relative to the package directory.  I've updated the CLI help with the new text with `Dist work directory, relative to package directory`
