### ISSUE TITLE
Simplifying Fedora installation

### ISSUE THREAD

**Issue by dag** [commercialhaskell/stack#2569]
The repository files can be unified into a single one using repo variables (`man 5 dnf.conf`):

```
[fpco]
name=FP Complete packages
baseurl=http://download.fpcomplete.com/fedora/$releasever
enabled=1
gpgcheck=1
gpgkey=https://s3.amazonaws.com/download.fpcomplete.com/fedora/RPM-GPG-KEY-FPCO
```

Alternatively `/etc/os-release` can be used to get the release version to instead unify the command (`man 5 os-release`):

``` shell
$ source /etc/os-release
$ echo $VERSION_ID
```

Adding new repositories is more properly done using the `config-manager` dnf plugin (`man 8 dnf.plugin.config-manager`):

``` shell
$ sudo dnf config-manager --add-repo "https://download.fpcomplete.com/fedora/$(source /etc/os-release && echo $VERSION_ID)/fpco.repo"
```

**Comment by mgsloan** [comment]
Pinging @borsboom , seems like your domain!

**Comment by borsboom** [comment]
We'll be dropping our own Fedora repos soon.  These kinds of issues are why people who actually understand the distros should be making and distributing the packages :)

**Comment by borsboom** [comment]
BTW, do these changes also work with CentOS 6 and `yum`, or are they `dnf`-only?

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because this is no longer within the scope of the Stack project.
