### ISSUE TITLE
Could I change ghc install path to STACK_ROOT or other place?

### ISSUE THREAD

**Issue by dontdieych** [commercialhaskell/stack#2574]
### General summary/comments (optional)

Windows 7 64bit

I'm trying to install stack on usb stick.

I've installed msys2 on usb and copy stack.exe to /usr/bin on msys2-shell(mintty). Then changed STACK_ROOT to usb drive at '~/.bashrc' and changed 'local-bin-path' to usb drive at project's 'stack.yml'.

So almost everything installed in usb drive but ghc. `stack path` output show still ghc in C: drive

```
compiler-exe: C:\Users\Administrator\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.3\bin\ghc.exe
compiler-bin: C:\Users\Administrator\AppData\Local\Programs\stack\x86_64-windows\ghc-7.10.3\bin

```

Could I change this path to custom location?

Thanks

### Stack version

```
 stack --version
Version 1.1.2, Git revision c6dac65e3174dea79df54ce6d56f3e98bc060ecc (3647 commits) x86_64 hpack-0.14.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment]
I agree that this should be implemented.  See this old issue, which I believe this is a duplicate of: https://github.com/commercialhaskell/stack/issues/998
