### ISSUE TITLE
Global project generation should use the current `--resolver` setting

### ISSUE THREAD

**Issue by lwm** [commercialhaskell/stack#2579]
### Comments

Starting from a fresh stack install.
### Steps to reproduce
1. `sudo apt-get install stack -y  #ubuntu setup`
2. `stack setup --resolver nightly 2016-09-10`
### Expected

Have `GHC 8.0.1` installed and my `.stack/global-project/stack.yaml` contain `resolver: nightly-2016-09-10`
### Actual

My `.stack/global-project/stack.yaml` has `resolver: lts-6.16`.
### Logs

```
[~] λ stack setup --resolver nightly 2016-09-10
Run from outside a project, using implicit global project config
Using latest snapshot resolver: lts-6.16
Writing implicit global project config file to: /home/lwm/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Downloaded nightly-2016-09-10 build plan.    
Fetching package index ...remote: Counting objects: 226071, done.
remote: Compressing objects: 100% (182392/182392), done.
remote: Total 226071 (delta 60226), reused 178752 (delta 41368), pack-reused 0
Receiving objects: 100% (226071/226071), 53.19 MiB | 464.00 KiB/s, done.
Resolving deltas: 100% (60226/60226), completed with 1 local objects.
From https://github.com/commercialhaskell/all-cabal-hashes
 * [new tag]         current-hackage -> current-hackage
Fetched package index.    
Populated index cache.    
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.0.1.                                      
Installed GHC.                                   
stack will use a locally installed GHC
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
```
### Stack version

```
$ stack --version
Version 1.1.2, Git revision cebe10e845fed4420b6224d97dcabf20477bbd4b (3646 commits) x86_64 hpack-0.14.0
```
### Method of installation
- Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by lwm** [comment]
Bump! Is this a bug from first glance? Would like to submit a PR if so, otherwise, will close.

**Comment by sjakobi** [comment]
Firstly, the generation of the global project doesn't have any particular link to the `setup` command. I'm under the impression that any stack command outside of a stack project will result in the creation of the global project if it doesn't already exist.

So, while this behaviour is "implicit" (which according to the [Zen of Python](https://www.python.org/dev/peps/pep-0020/) is worse than explicit) and may be surprising depending on context, it is somewhat consistent in itself and I wouldn't call it a bug.

OTOH I don't see why we shouldn't pick up the current `--resolver` setting and only default to the latest LTS snapshot if `--resolver` isn't specified. In the case of `stack setup --resolver X` that would have the benefit that the compiler that is set up can be used in the global project, which currently isn't guaranteed.

At some point we should probably discuss whether other settings like e.g. `--compiler` should also be picked up, but I don't think that's urgent.
