### ISSUE TITLE
flags like `--verbose` not passed to sub commands like `stack ghc`

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/stack#258]
I assumed that `stack ghc --SOME_FLAG` would call `ghc` and pass it `--SOME_FLAG`.  However, this does not seem to work all the time.

In the following example, I expected to get the `ghc` version, not the `stack` version:

```
$ stack ghc --version
Version 0.0.1.1, Git revision 99963c0e2259514b853c206c79496d74c6e7d443 (dirty)
```

I expected the output of the following two commands to be the same, but they differ:

```
$ stack ghc --some-flag-that-doesnt-exist main.hs
Usage: stack ghc [ARGS]
  Run ghc
$ ghc --some-flag-that-doesnt-exist main.hs
ghc: unrecognised flag: --some-flag-that-doesnt-exist

Usage: For basic information, try the `--help' option.
$
```

**Comment by chrisdone** [comment]
This is a problem with optparse-applicative, it makes it difficult to do pass-through. The solution at the moment is:

    stack ghc -- --version

To indicate to optparse to interpret the rest of the arguments as a string instead of snatching them up as global options.

We can potentially make flags coming after `ghc` implicitly quoted. What do people feel about that?

**Comment by mitchellwrosen** [comment]
What about making `--help` simply remind you how to pass args through?
```
> stack ghc --help
Usage: stack ghc [ARGS] [-- [GHC_ARGS]]
  Run ghc
```

**Comment by chrisdone** [comment]
One does not simply do anything with ~~mordor~~ optparse-applicative. But I'll see what can be done; it's possible to prompt the user to always pass `--` after GHC by inspecting the arguments manually.

**Comment by mitchellwrosen** [comment]
Oh, you mean the usage strings are automatically generated? Hm. Bummer.

**Comment by chrisdone** [comment]
They are indeed.

**Comment by mitchellwrosen** [comment]
Pardon the ignorance, but is `--` a unix shell thing, or is optparse-applicative just re-using it as the familar end-of-args delimiter?

**Comment by chrisdone** [comment]
This behavior is a unix command thing, it comes from the programs, not the shell itself.

**Comment by chrisdone** [comment]
@cdepillabout @mitchellwrosen In 76abc18 I added better help to the process running commands:

```
$ stack ghc --help
Usage: stack ghc [-- ARGS (e.g. stack ghc -- X.hs -o x)]
  Run ghc
```

**Comment by chrisdone** [comment]
I think this is a pretty good compromise. Closing.

**Comment by cdepillabout** [comment]
Sounds like a good compromise.  Thanks!
