### ISSUE TITLE
stack solver not working with cabal 1.24

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#2585]
Solver seems to be broken again due to cabal out format changes in cabal 1.24. Has anyone else seen this problem?

```
Could not parse cabal-install errors:

>>>> Cabal errors begin
cabal: Could not resolve dependencies:
trying: getopt-generics-0.13 (dependency of xls-0.1)
next goal: base-compat (dependency of getopt-generics-0.13)
rejecting: base-compat-0.9.1, base-compat-0.9.0, base-compat-0.8.2,
base-compat-0.8.1.1, base-compat-0.8.0.1, base-compat-0.8.0,
base-compat-0.8.1, base-compat-0.7.1, base-compat-0.7.0 (constraint from main
config /tmp/cabal-solver26506/cabal.config requires ==0.6.0)
rejecting: base-compat-0.6.0 (conflict: getopt-generics => base-compat>=0.8)
rejecting: base-compat-0.5.0, base-compat-0.4.2, base-compat-0.4.1,
base-compat-0.4.0, base-compat-0.3.0, base-compat-0.2.1, base-compat-0.2.0.2,
base-compat-0.2.0.1, base-compat-0.2.0, base-compat-0.1.0.1,
base-compat-0.1.0, base-compat-0.0.0 (constraint from main config
/tmp/cabal-solver26506/cabal.config requires ==0.6.0)
Dependency tree exhaustively searched.
```

```
$ cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 
$ stack --version
Version 1.2.1, Git revision ffaf1b494044abd98297df080cb4ec190e3f68d0 (dirty) (4056 commits) x86_64 hpack-0.14.1
```

**Comment by mgsloan** [comment]
Marking this as a P1 so that it gets noticed before the next release.  If it's not fixed before the release, we should check the cabal-install version and tell the user to downgrade in order for `--solver` to work.

**Comment by mgsloan** [comment]
I've investigated this a bit, and the issue appears to be that there is no line like `next goal: Pkg (user goal)`, indicating which package in the user's goals is causing issues.  This info collection is used for the `--omit-packages` feature of `stack init`.

One option that is seeming appealing is to drop the `--omit-packages` option, and remove parsing of cabal errors.  While it is a convenient feature, it is also a bit arbitrary.

**Comment by qrilka** [comment]
@harendra-kumar I think this was resolved in some previous versions but now we have problems with newer `cabal-install`, what do you think about closing this one?

**Comment by harendra-kumar** [comment]
Yes, we can close it, 1.24 is anyway quite old now.
