### ISSUE TITLE
Detect change in pvp upper bounds and reset

### ISSUE THREAD

**Issue by harendra-kumar** [commercialhaskell/stack#2595]
I need a workflow where I want to always keep "working upper bounds" in a package and I want to shift them to higher versions whenever a new dependency version arrives and a test passes using that version. The test result tells me to look into it when it fails and shift it when it succeeds, not do anything when there is no change.

To support that in my tests I want:
- a way to detect if there are newer versions available i.e. the diff between pvp-bounds currently set and latest available versions. Whenever a diff is found I will fire a test with new bounds.
- A way to move the upper bounds. stack command `sdist --pvp-bounds upper` only sets when there are no upper bounds. I need a command which can set it even if it is already set. I will use that whenever I want to shift the bounds to newer ones after a successful test.

Something like:

```
stack sdist --pvp-bounds show-upgrade
stack sdist --pvp-bounds upgrade
```

**Comment by mgsloan** [comment]
I agree that this would be a valuable workflow!  Not sure what the CLI should look like, I don't think I like putting it on the `sdist` command.  Maybe make it part of the `stack status` - https://github.com/commercialhaskell/stack/issues/2393 ?  We could also add it to `stack query`, but it doesn't seem like a natural fit there.  I'd prefer to fold `query` into status or vice versa.

**Comment by snoyberg** [comment]
The `packdeps` executable can tell you about restrictive upper bounds. We're not going to be adding cabal file modification capabilities to Stack
