### ISSUE TITLE
Custom flags for stack.yaml and stack command line tool

### ISSUE THREAD

**Issue by mchaver** [commercialhaskell/stack#2597]
I may be mistaken but it seems like this doesn't exist. Sometimes I make multiple stack.yaml files for differing package dependencies, different compilers, etc., but it involves a lot of repetition and shared similarities must be maintained. It would be better if I could make one stack.yaml file and have some set of flags for specific behavior depending on values I pass to stack at the command line.

A simple example is ghc vs ghcjs. Sometimes I want extra packages specifically for ghcjs so it would be nice if setup a single stack.yaml that says if I use a ghc flag it will compile the package with ghc and install one set of pacakges, if I use a flag for ghcjs, it will compile with ghcjs, a set of packages for both compilers and a set of packages for just ghcjs.

Another use case would be testing one package against different versions of a package.

**Comment by harendra-kumar** [comment]
#2559 may be the issue you are looking for.

**Comment by mgsloan** [comment]
Yes, this has been discussed quite a bit, but there is not yet a clear implementation path.  Along with #2559, see also:

* https://github.com/commercialhaskell/stack/issues/1568
* https://github.com/commercialhaskell/stack/issues/732
* https://github.com/commercialhaskell/stack/issues/392
