### ISSUE TITLE
Transitioning to a full clone of package index can fail

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#2602]
Example (from https://travis-ci.org/fpco/stackage/builds/160335230):

```
Shallow package index repo detected, transitioning to a full clone...
Updating package index Hackage (mirrored at https://github.com/commercialhaskell/all-cabal-hashes.git) ...Running /usr/bin/git fetch --unshallow in directory /home/travis/.stack/indices/Hackage/git-update/all-cabal-hashes/ exited with ExitFailure 128
fatal: error in object: unshallow 05a8ba81a30b775e3aab8269642317345708bcfa
```

The `--unshallow` option was added in git 1.8.2, released in early 2013.  It's entirely possible that Travis and other users could have an older version.

@snoyberg suggested a fallback incase of failure of deleting the directory and re-cloning.

I believe a workaround would be to delete `~/.stack/indices/Hackage/git-update/all-cabal-hashes/` and then try again.  Another workaround would be to upgrade `git`.

**Comment by Blaisorblade** [comment]
BTW: We have similar fallback code for checking out packages.

**Comment by snoyberg** [comment]
For anyone reading this with a failing Travis build: you can work around the problem by clearing the cache.

**Comment by Blaisorblade** [comment]
@borsboom's right about the old Git version. The offending Travis build runs Ubuntu Precise from 2012 (https://travis-ci.org/fpco/stackage/builds/160335230#L6) that uses git 1.7.9.5 (http://packages.ubuntu.com/precise/git-core). Giving this a try.
