### ISSUE TITLE
`--no-load` is ignored with `--test`

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/stack#2603]
### Expected
When starting repl with:
` stack repl  --no-load --test`
I expect no prompt which asks for which module to load

### Actual
I get prompt which ask which module to load.

Looks like a regression issue.

### Stack version
stack-1.2.0 via Ubuntu repo

**Comment by mgsloan** [comment]
Hi, thanks for the report!

Can you please try with the git version of stack, or perhaps even the latest stable?  `stack upgrade --git` and `stack upgrade`, respectively.  I believe that this is already fixed.

**Comment by mgsloan** [comment]
Nevermind, I can reproduce the issue!  Working on a fix.

**Comment by rikvdkleij** [comment]
Thanks! I can also still reproduce this issue with version,
```Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42```

**Comment by mgsloan** [comment]
Fixed!  Not sure how that regressed, thanks a bunch for the report!
