### ISSUE TITLE
Fix building Stack on ARM

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#2604]
Stack now uses `store`, which does not currently build ARM and some other processors (see https://github.com/fpco/store/issues/37).  First `store` will need to be fixed, and then Stack will have to use the new `store` version.

ping @mgsloan

**Comment by mgsloan** [comment]
I have a patch for review on store: https://github.com/fpco/store/pull/78

Pending someone actually testing it on ARM, and perhaps more code review.

**Comment by mgsloan** [comment]
I've updated stack to use store-0.3  In theory this is now resolved.  Pending test by someone who has an ARM machine - pinging @dysinger

**Comment by mitchty** [comment]
If you like I can give it a test on my arm port. Is the master branch the thing to test?

**Comment by mgsloan** [comment]
Yep it'd be the master branch.  Crossing my fingers that it works!

**Comment by borsboom** [comment]
@mgsloan: I've tested the master branch on armv7 (only took 20 hours to build using qemu) and get the following test failures:

```
      test/Data/Store/StreamingSpec.hs:52:
      1) Data.Store.Streaming.decodeMessage.ByteString Throws an Exception on messages that are shorter than indicated.
           uncaught exception: PokeException (PokeException {pokeExByteIndex = 4, pokeExMessage = "encode undershot end of 8 byte long buffer"})

      test/Data/Store/StreamingSpec.hs:53:
      2) Data.Store.Streaming.decodeMessage.ByteString Throws an Exception on messages that are longer than indicated.
           uncaught exception: PokeException (PokeException {pokeExByteIndex = 16, pokeExMessage = "encode undershot end of 20 byte long buffer"})
```

Full log is at https://gist.github.com/borsboom/7bd922f62e62c42f4aaa3c5f4e24cad6.

**Comment by mgsloan** [comment]
I believe those failures are due to the tests assuming that the size of `Int` is 64 bits.  So happily, I think unaligned access is working fine.  If you still have that emulator handy, I've pushed a commit disabling those tests.

**Comment by borsboom** [comment]
The tests now pass, and `stack` passes its tests when built against this version of `store`.

**Comment by mgsloan** [comment]
Woohoo!  I think we can consider this resolved.

**Comment by mitchty** [comment]
Yep, I managed to get it to build, forgot to post that bit (had some build issues that were just no swap space due to a reboot):

```
# file ./.stack-work/install/arm-linux/lts-7.0/8.0.1/bin/stack
./.stack-work/install/arm-linux/lts-7.0/8.0.1/bin/stack: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-armhf.so.1, stripped
# ./.stack-work/install/arm-linux/lts-7.0/8.0.1/bin/stack --version | head -n 3
Version 1.2.1, Git revision 89c699b4083953406336647c52b42acbf48beac2 (dirty) (4308 commits) arm
Compiled with:
```

**Comment by borsboom** [comment]
stack-1.3.0 ARM binary is now uploaded to the release: https://github.com/commercialhaskell/stack/releases/download/v1.3.0/stack-1.3.0-linux-arm.tar.gz
