### ISSUE TITLE
Allow test suites to integrate additional .tix files to be used in the unified report

### ISSUE THREAD

**Issue by bitonic** [commercialhaskell/stack#2609]
`stack test --coverage` is very useful to get a unified coverage report, and it works by copying each `.tix` file generated after the execution of each test in a project-global directory and unifying all those files at the end.

However, sometimes tests invoke Haskell executables produced in the same project, which are also built with coverage. It would be convenient to allow users to copy or redirect the `.tix` files generated when running these executables to the directory used by `stack` so that these reports would be included in the unified report.

The simplest way to do this would probably be to have a `stack path` command to do that.

**Comment by mgsloan** [comment]
Is `stack path --local-hpc-root` sufficient?  Seems to be to me!  Please re-open if it is insufficient.

**Comment by bitonic** [comment]
It's not sufficient because it doesn't specify a place to place tix files. If one wants to add tix files to the report of a package, or to the unified report, he needs to rely on implementation details, for example creating a dummy directory in `stack path --local-hpc-root`.

I'd like a contract that lets me place additional `.tix` files into the package-specific HPC directory, with those `.tix` files appearing in the report for the package and in the unified report.

**Comment by mgsloan** [comment]
@bitonic Makes sense!  So the task here is to have it slurp in additional `.tix` files - should be doable.

**Comment by mgsloan** [comment]
@bitonic I have documented code coverage here - https://github.com/commercialhaskell/stack/blob/master/doc/coverage.md - are the features of the `stack hpc report` command sufficient?  Unfortunately, I found that they were broken in recent releases.  I have committed some fixes.

**Comment by bitonic** [comment]
@mgsloan that is very helpful, thanks.

However, it's still not clear how I would go to build this in a robust manner.

Let's say I have a `stack.yaml` with package `foo`, which has a test target `foo:test` and an executable target `foo:app`.

`foo:test`, to perform its tests, executes `foo:executable` and has it perform various tasks.

Now, I'd like it to be so that if `stack test --coverage` is run, there is a report for `foo:test` which integrates the coverage data generated by the runs of `foo:executable`. Right now I don't think there is a way to do this.

What we can do (and do it in some internal projects) is to move the `.tix` files generated by runs of `foo:executable` in a custom `$(stack path --local-hpc-root)/dummy-folder/dummy-folder/dummy-file.tix`. It so happens that, to generate the unified report, `stack test --coverage` essential globs all files that match `$(stack path --local-hpc-root)/*/*/*.tix`, and so the data _will_ appear in the unified report.

However, we're looking for a way to
* Not rely on this globbing "getting lucky", 
* Being able to store files to be used in reports for specific tests which spawn processes.

**Comment by mgsloan** [comment]
I believe these concerns are all addressed by the `stack hpc report` command.  It does have to generate a whole new report, but I think this is cleaner than having people stick .tix files in magic places.

**Comment by bitonic** [comment]
Mhm, I don't see how `stack hpc report` fixes the problem. I'd like to be able to have it so that `stack test --coverage` generates the report with the expected files, while I think `stack hpc report` would have to be invoked manually.

In any case, the solution that we have now is OK, so I think this is pretty low priority.

**Comment by mgsloan** [comment]
@bitonic While I am still not convinced of the elegance of this feature, I have implemented it.  Can you please test it?  I do not have a suitable usecase in front of me.

**Comment by bitonic** [comment]
@mgsloan , your changes do not seem to kick in when I do `stack test --coverage`. I believe this is since they're in `generateHpcReportForTargets` but not in `generateHpcReport`.

I've created a repo to demonstrate this: https://github.com/bitonic/coverage-test .

Doing `stack test --coverage` inside that repo should cause both `func1` and `func2` to be covered, but currently they aren't.

**Comment by mgsloan** [comment]
Good catch, thanks for trying it out and making a repro.  I've changed the implementation to only consider the `extra-tix-files` dir with the main unified report.  It no longer is used with the `stack hpc report` command, having it be used there was a mistake I think.
