### ISSUE TITLE
stack build gives InvalidAbsDir

### ISSUE THREAD

**Issue by leohaskell** [commercialhaskell/stack#2614]
I just updated to stack 1.2.0
and my `stack build` is failing with the following error:
`option --extra-lib-dirs: InvalidAbsDir "/home/me/XX/YY/../ZZ/UU/VV/WW"`

The command I'm running is
`stack build --extra-lib-dirs="$lib"`
where `$lib` is the path mentioned above.

Note: The same command ran successfully before the update.

Edit: Seems like it's failing because of the `..`, since given the same path without it works perfectly fine.

**Comment by mgsloan** [comment]
Not sure what we should do about this.  I think this general issue affects everything that uses the funcions like `absDirOption` / `relDirOption` / etc.

@chrisdone Maybe we should put `FilePath` in our config types?  Seems like a cop-out!

**Comment by chrisdone** [comment]
It's true that fundamentally a user's input is incomplete and we need IO to fill in the gaps. Ideally we'd resolve the user input into a normalised absolute directory, via resolveDir' from path-io. I don't know whether optparse-applicative is capable of running as a monad transformer like Web formlets, that would allow us to do the resolving before it gets into our configuration types.

What type would this be?

**Comment by mgsloan** [comment]
I'm not sure, how about `LenientPath Dir` ?

**Comment by leohaskell** [comment]
Any updates on this?

**Comment by leohaskell** [comment]
Is there any progress on that issue? Still happening with 1.4.0.

**Comment by mgsloan** [comment]
Fixed in HEAD - see https://github.com/commercialhaskell/stack/issues/2830
