### ISSUE TITLE
linker error when compiling with `inline-c`

### ISSUE THREAD

**Issue by charles-cooper** [commercialhaskell/stack#2624]
not sure if this is a cabal / ghc bug or not but i have a race condition where saving a file in the middle of compiling (which triggers recompilation of some input files) results in a linker error. i have never seen this besides when i am compiling a project with inline-c quasiquotes. luckily this is not too bad because rerunning the build results in a successful compilation.

this is the error

```
/usr/bin/ld: .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/ace/ace-tmp/src/Database/PostgreSQL/C.o: relocation R_X86_64_PC32 against undefined symbol `PQgetvalue' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
```

my `.cabal` file contains the following

```
c-sources:           src/Database/PostgreSQL/C.c
extra-libraries:
  pq, m
```

stack command

```
stack build ace:ace --file-watch --exec "./r"
```

version info

```
$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

**Comment by mgsloan** [comment]
Hi Charles!

I'm not sure what could cause this either.  It is possible for you to provide me a repro?  Perhaps I can privately access your project?  Unfortunately, even then I'm not sure if I would have success debugging it, the linking side of things is a weak spot in my knowledge.

**Comment by mgsloan** [comment]
Not sure stack can do anything to resolve this, closing as an old support issue.  Glad there's a workaround!
