### ISSUE TITLE
Multi-module haskell script files

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2627]
I think we should add a `--multi-module` option to `runghc` / `runhaskell`.  This way, standalone scripts can be multiple modules.  On its own, this might seem confusing - why support that if ghc doesn't support it?  The motivation is to support use-cases like [School of Haskell](https://www.schoolofhaskell.com/), where we need to have multiple files in one "snippet".

The more ideal implementation would be to implement this as part of ghc - https://ghc.haskell.org/trac/ghc/ticket/2551 - however that ticket was closed due to lack of interest.

Here's how the stack implementation would look:

1) Assume that a line that starts with `module` are located at a module header.  This can be invalidated by strange module indentation, quasi-quotes, or multi-line strings.  The answer to these corners is "don't do that".

2) Consume pragma comments backwards, for every pragma type that is allowed atop module declarations.

3) Create a temp dir and populate it with the modules

4) Provide these modules to `runhaskell`

Could also consider supporting this with ghci, but `:reload` won't work right.  We could add direct support for this in [intero](https://github.com/commercialhaskell/intero), though.

**Comment by rcook** [comment]
Hey Michael,

It's been a couple of years since you created this issue. Have you or anyone else had any more thoughts on how this might work? Is there any demand from it?

-Richard

**Comment by mgsloan** [comment]
Hi Richard!

I haven't thought much more about how this might work, but it would be quite nice.  I think the best place to implement this would be in GHC proper, first via a proposal https://github.com/ghc-proposals/ghc-proposals.

Not sure how much demand there is for it.  Notably, stack scripts can already load modules that are in the current directory, so I'm not sure when this would be useful.  Perhaps it could be nice to `wget` a single file and use `runhaskell` on it.

Now that I've reconsidered this, I think it's probably out of scope for stack.
