### ISSUE TITLE
stack haddock can't find ghc settings

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/stack#2631]
### General summary/comments (optional)

Running `stack haddock` fails with `2016-09-25 13:22:09.796552: [info] /Users/adam.bergmark/.stack/programs/x86_64-osx/ghc-8.0.1/lib/ghc-8.0.1/settings: openFile: does not exist (No such file or directory)` but `cabal install --enable-doc` succeeds.

### Steps to reproduce

```
$ stack unpack reedsolomon-0.0.4.1
$ cd reedsolomon-0.0.4.1/
$ printf "flags:\n  reedsolomon:\n    llvm: false" >> stack.yaml # might not be needed
$ stack haddock
```

### Expected

Haddock to succeed

### Actual

```
Running Haddock for reedsolomon-0.0.4.1...
Preprocessing library reedsolomon-0.0.4.1...
haddock: internal error: The Glorious Glasgow Haskell Compilation System, version 8.0.1
/Users/adam.bergmark/ghc/8.0.1/lib/ghc-8.0.1/settings: openFile: does not exist (No such file or directory)

--  While building package reedsolomon-0.0.4.1 using:
      /Users/adam.bergmark/repos/3rd/reedsolomon-0.0.4.1/reedsolomon-0.0.4.1/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 haddock --html --hoogle --html-location=../$pkg-$version/ --haddock-option=--hyperlinked-source
    Process exited with code: ExitFailure 1
```

verbose log: https://gist.github.com/bergmark/a21a4043dd0de7717c2b06d4c6d3753b

### Stack version

```
$ stack --version
Version 1.2.0 x86_64 hpack-0.14.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by NicolasT** [comment]
See https://github.com/NicolasT/reedsolomon/issues/53 for a discussion. I don't believe this is a Stack issue.

**Comment by bergmark** [comment]
Cool, thanks!
