### ISSUE TITLE
Better error messaging for `stack setup` on Nix / NixOS

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2634]
See https://github.com/commercialhaskell/stack/issues/2586 and https://github.com/commercialhaskell/stack/issues/1882#issuecomment-194180059 .  Based on my read of the latter comment, `stack setup` should never be used with nix.  Is this correct, @YPares ?

If so, we should have `stack setup` exit with a nicer error message.

**Comment by YPares** [comment]
@mgsloan `stack setup` can be used with --nix. As any use of `--nix` the `nix-shell` will download ghc if you don't have it. I answered on https://github.com/commercialhaskell/stack/issues/2586 to clarify, because this issue isn't a use case of the nix support.

**Comment by mgsloan** [comment]
Thanks for the input @YPares !  Perhaps if `stack setup` fails in nix mode, we should append a message saying that it is not a supported use-case.  Perhaps even prepend such a message.  So, I will leave this open to address that concern.

**Comment by YPares** [comment]
But stack setup (from what I read) doesn't fail in Nix mode.
It failed on NixOS without the nix mode.

2016-09-27 1:22 GMT+02:00 Michael Sloan <notifications@github.com>:

**Comment by mgsloan** [comment]
Good point!  I will just close this issue :)
