### ISSUE TITLE
Nix integration does not work on NixOS 16.03

### ISSUE THREAD

**Issue by ElvishJerricco** [commercialhaskell/stack#2635]
#2435 advocated making use of `makeSearchPathOutput`, which was implemented in #2444, and which isn't present in NixOS 16.03. So now, you can't use stack without switching to nixpkgs-unstable. That said, I believe it works fine on unstable.

### Steps to reproduce

First, [get stack 1.2.0 on NixOS](https://www.reddit.com/r/haskell/comments/5491df/using_newer_stack_ltss_with_nixos/).

```bash
$ stack new test
$ cd test
$ stack setup --nix
```

### Expected

Successful setup.

### Actual

```
[debug] Run process: /run/current-system/sw/bin/nix-shell --pure -E "with (import <nixpkgs> {}); let inputs = [haskell.compiler.ghc801]; libPath = lib.makeLibraryPath inputs; stackExtraArgs = lib.concatStrings (lib.foldl' (acc: p: acc ++ [\" --extra-lib-dirs \" p]) [] (lib.splitString '':'' libPath) ++ lib.foldl' (acc: p: acc ++ [\" --extra-include-dirs \" p]) [] (lib.splitString '':'' (lib.makeSearchPathOutput ''dev'' ''include'' inputs))); in runCommand ''myEnv'' { buildInputs = lib.optional stdenv.isLinux glibcLocales ++ inputs; STACK_PLATFORM_VARIANT=''nix''; STACK_IN_NIXSHELL=1; LD_LIBRARY_PATH = libPath;STACK_IN_NIX_EXTRA_ARGS = stackExtraArgs; } \"\"" --run "'/home/will/bin/stack' $STACK_IN_NIX_EXTRA_ARGS '--internal-re-exec-version=1.2.0' '--verbose' 'setup'"
@(Stack/Exec.hs:65:5)
error: attribute ‘makeSearchPathOutput’ missing, at (string):1:318
(use ‘--show-trace’ to show detailed location information)
```

### Stack version

Version 1.2.0 x86_64

### Method of installation

I installed stack with a convoluted method of installing an old version with nix, then manually building 1.2.0 using stack, because [`nixpkgs/master` couldn't build it](https://github.com/NixOS/nixpkgs/issues/18942), and `unstable` doesn't have 1.2.0 anywhere.

```bash
$ nix-env -i stack # 1.0.2
$ nix-shell -p haskell.compiler.ghc801
$ stack new build-stack
$ cd build-stack
$ # Edit stack.yaml's extra-deps to include `stack-1.2.0`
$ stack install stack
$ exit # exit nix-shell
$ nix-env -e stack
```

**Comment by mgsloan** [comment]
Pinging @YPares / @mboes , since the nix stuff isn't my specialty

**Comment by YPares** [comment]
@ElvishJerricco Thanks for reporting it. Can you tell me whether the `lib.getLib` and `lib.getDev` functions?
If they are, that's going to simplify this code. So that was something I was intending to do anyway.

**Comment by ElvishJerricco** [comment]
It would appear those are present.

**Comment by YPares** [comment]
@ElvishJerricco Then can you check out da1102b ?
This ought to fix it.

**Comment by ElvishJerricco** [comment]
It looks like that works!

**Comment by mgsloan** [comment]
Great!  Closing this as it's fixed.
