### ISSUE TITLE
Restrict git version?  Manage git installation?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2639]
We recently ran into an issue where old git versions don't work with some options we were passing - https://github.com/commercialhaskell/stack/issues/2602 .  That specific issue has been worked around by falling back to doing a reclone.  However, there is nothing stopping a similar situation from happening again.

I think it would make sense for stack to treat `git` as another controlled external dependency, in the same way that tools like ghc, mingw, 7zip are treated.  This would amount to doing the following:
- Hardcoding a range of allowed git versions
- If the git version is not in range, ask the user to use `setup` to install git.  Should it require a `--upgrade-git` flag?

There is another issue where I am suspecting that having too _new_ of a git version might cause problems - https://github.com/commercialhaskell/stack/issues/2201 - it would be great to systemically eliminate this potential source of error.

We also have a similar issue for controlling node version https://github.com/commercialhaskell/stack/issues/1632

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and the lack of support for the suggestion at the time. I suspect Git in 2024 is very different to what it was in 2016.
