### ISSUE TITLE
Re-enable -rtsopts for stack + document RTS opts via exec

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2640]
I am forking this off from #2022 because that thread got rather involved.  I think the summary is:

1) `stack exec -- exeName +RTS ...` works fine to pass RTS options because `--` causes further RTS arguments to not be processed.

2) `stack exec exeName -- +RTS ..` doesn't work because the `--` is also visible to the `exeName` process.

One option for resolving this would be to deprecate the `stack exec exeName -- ARGS` form, perhaps even the `stack exec exeName` form.  How can we deprecate it though?  That would require adding stuff to stdout or stderr.

Either way, we should re-enable `-rtsopts` for stack, may as well have them if they are being parsed out of the commandline.  Either way, we should thoroughly document using RTS options with exec.

**Comment by AndreasPK** [comment]
This is not correct. Under windows 10 with Stack 1.3.2 and GHC 8.0.2 I get

```
> stack exec -- echo test +RTS -s1 -RTS -s2
test -s2

> stack exec echo -- test +RTS -s1 -RTS -s2
test -s2

> stack exec -- echo -- test +RTS -s1 -RTS -s2
-- test -s2

```

In ALL cases stack consumes the RTS options.

Passing --RTS works but is not an options since we would have to pass that to stack BEFORE the runtime can parse it:
```
> stack exec -- echo --RTS test +RTS -s1 -? -RTS -s2
test +RTS -s1 -? -RTS -s2
```

 I wrote up code that adds an rts-options flag to explicitly pass RTS options along and will submit that as pull request when it's fleshed out. The result will be:

```
> stack exec --rts-options="-s" -- echo test
test +RTS -s -RTS
```

**Comment by rwbarton** [comment]
The original issue description *is* correct, except to the extent that there's a bug on Windows only (which @AndreasPK identified and reported) that causes RTS options (or more properly, options that look like RTS options) that come after a `--` not to be included in the program's argument list as returned by `getArgs`.

**Comment by AndreasPK** [comment]
Can this be closed via (https://github.com/commercialhaskell/stack/pull/3012)?

**Comment by mgsloan** [comment]
@AndreasPK Yep, thanks for noticing that!
