### ISSUE TITLE
Unable to build with GHCJS / Node 6.6.0 when following the Stack GHCJS Documentation

### ISSUE THREAD

**Issue by jonathanknowles** [commercialhaskell/stack#2642]
When following the [Stack GHCJS Instructions](https://docs.haskellstack.org/en/stable/ghcjs) and using the latest version of Node (6.6.0), building fails (even for a simple project).
## Reproduction Steps

**Check software versions**

```
$ node --version
v6.6.0
$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
```

**Use stack to create a new, empty project**

```
$ stack new ghcjs
Downloading template "new-template" to create project "ghcjs" in ghcjs/ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ghcjs/ghcjs.cabal

Selecting the best among 9 snapshots...

* Matches lts-7.1

Selected resolver: lts-7.1
Initialising configuration using resolver: lts-7.1
Total number of user packages considered: 1
Writing configuration to file: ghcjs/stack.yaml
All done.
```

**Attempt to build the project with GHCJS**

```
$ cd ghcjs
$ stack build --compiler ghcjs-0.2.0_ghc-7.10.3
Ignoring that the GHCJS boot package "aeson" has a different version, 0.9.0.1, than the resolver's wanted version, 0.11.2.1
Ignoring that the GHCJS boot package "attoparsec" has a different version, 0.13.0.1, than the resolver's wanted version, 0.13.1.0
Ignoring that the GHCJS boot package "unordered-containers" has a different version, 0.2.5.1, than the resolver's wanted version, 0.2.7.1
Ignoring that the GHCJS boot package "scientific" has a different version, 0.3.3.8, than the resolver's wanted version, 0.3.4.9
Ignoring that the GHCJS boot package "case-insensitive" has a different version, 1.2.0.4, than the resolver's wanted version, 1.2.0.7
Ignoring that the GHCJS boot package "hashable" has a different version, 1.2.3.2, than the resolver's wanted version, 1.2.4.0
Ignoring that the GHCJS boot package "async" has a different version, 2.0.1.6, than the resolver's wanted version, 2.1.0
Ignoring that the GHCJS boot package "text" has a different version, 1.2.1.1, than the resolver's wanted version, 1.2.2.1
Ignoring that the GHCJS boot package "syb" has a different version, 0.5.1, than the resolver's wanted version, 0.6
Ignoring that the GHCJS boot package "stm" has a different version, 2.4.4, than the resolver's wanted version, 2.4.4.1
Ignoring that the GHCJS boot package "parallel" has a different version, 3.2.0.6, than the resolver's wanted version, 3.2.1.0
Ignoring that the GHCJS boot package "dlist" has a different version, 0.7.1.1, than the resolver's wanted version, 0.8.0.2
Ignoring that the GHCJS boot package "process" has a different version, 1.2.3.0, than the resolver's wanted version, 1.4.2.0
Ignoring that the GHCJS boot package "directory" has a different version, 1.2.2.0, than the resolver's wanted version, 1.2.6.2
Ignoring that the GHCJS boot package "time" has a different version, 1.5.0.1, than the resolver's wanted version, 1.6.0.1
Ignoring that the GHCJS boot package "filepath" has a different version, 1.4.0.0, than the resolver's wanted version, 1.4.1.0
Ignoring that the GHCJS boot package "binary" has a different version, 0.7.5.0, than the resolver's wanted version, 0.8.3.0
Ignoring that the GHCJS boot package "pretty" has a different version, 1.1.3.2, than the resolver's wanted version, 1.1.3.3
Ignoring that the GHCJS boot package "containers" has a different version, 0.5.6.3, than the resolver's wanted version, 0.5.7.1
Ignoring that the GHCJS boot package "bytestring" has a different version, 0.10.6.0, than the resolver's wanted version, 0.10.8.1
Ignoring that the GHCJS boot package "deepseq" has a different version, 1.4.1.1, than the resolver's wanted version, 1.4.2.0
Ignoring that the GHCJS boot package "transformers" has a different version, 0.4.3.0, than the resolver's wanted version, 0.5.2.0
Ignoring that the GHCJS boot package "array" has a different version, 0.5.1.0, than the resolver's wanted version, 0.5.1.1
ghcjs-0.1.0.0: configure
Configuring ghcjs-0.1.0.0...
setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3:
.stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs/: does not exist

--  While building package ghcjs-0.1.0.0 using:
      /home/jsk/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.22.8.0-ghcjs-0.2.0_ghc-7.10.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.8.0_ghcjs configure --with-ghc=/usr/bin/ghc --with-ghc-pkg=/usr/bin/ghc-pkg --with-ghcjs=/home/jsk/.stack/programs/x86_64-linux/ghcjs-0.2.0.20160414_ghc-7.10.3/bin/ghcjs --with-ghcjs-pkg=/home/jsk/.stack/programs/x86_64-linux/ghcjs-0.2.0.20160414_ghc-7.10.3/bin/ghcjs-pkg --user --package-db=clear --package-db=global --package-db=/home/jsk/.stack/snapshots/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/pkgdb --package-db=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/pkgdb --libdir=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/lib --bindir=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/bin --datadir=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/share --libexecdir=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/libexec --sysconfdir=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/etc --docdir=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/doc/ghcjs-0.1.0.0 --htmldir=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/doc/ghcjs-0.1.0.0 --haddockdir=/private/jsk/projects/current/ghcjs/.stack-work/install/x86_64-linux/lts-7.1/ghcjs-0.2.0_ghc-7.10.3/doc/ghcjs-0.1.0.0 --dependency=base=base-4.8.0.0-b9e000fb6d6d99911bd8359d1b255fbf --ghcjs --enable-tests --enable-benchmarks
    Process exited with code: ExitFailure 1
```
## Notes

This issue appears to be similar to [issue 2364](https://github.com/commercialhaskell/stack/issues/2364) (which is closed at the time of writing).
## Known Workarounds

Use a later version of GHCJS and a later resolver version:

```
$ cat stack.yaml
resolver: lts-7.1
compiler: ghcjs-0.2.1.9007001_ghc-8.0.1
compiler-check: match-exact
extra-deps:
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007001_ghc-8.0.1:
          url: http://tolysz.org/ghcjs/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
          sha1: e640724883238593e2d2f7f03991cb413ec0347b
```

**Comment by mgsloan** [comment]
I think we need to update the instructions to newer tarballs.  I'm not sure if those ones include fixes that are relevant to newer node releases.

**Comment by tolysz** [comment]
How do we choose which tarball to use? (for the sample page). In practice, every `lts` needs to have a different version of ghcjs.

Unfortunately there is no "official" package per resolver of ghcjs, the work to repack with the right versions it seems to produce good results: https://www.reddit.com/r/haskell/comments/54knub/ghcjs_dedupe/

E.g Ignoring that the GHCJS boot package "aeson" has a different version, 0.9.0.1, than the resolver's wanted version, 0.11.2.1 will be gone as the aeson used will be 0.11.2.1

**Comment by jonathanknowles** [comment]
For what it's worth, I was able to fix this problem by using a more recent version of GHCJS (ghcjs-0.2.1.9007001_ghc-8.0.1) and a more recent resolver (lts-7.1):
```
$ cat stack.yaml
resolver: lts-7.1
compiler: ghcjs-0.2.1.9007001_ghc-8.0.1
compiler-check: match-exact
extra-deps:
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9007001_ghc-8.0.1:
          url: http://tolysz.org/ghcjs/ghc-8.0-2016-09-26-lts-7.1-9007001-mem.tar.gz
          sha1: e640724883238593e2d2f7f03991cb413ec0347b
```
This is with Node version 6.6.0 and stack version 1.2.0:
```
$ node --version
v6.6.0
$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
```

**Comment by mgsloan** [comment]
Good question @tolysz !  We would really appreciate it if you would add commits to our stable branch [here](https://github.com/commercialhaskell/stack/tree/stable), updating the docs when you release new tarballs.  Naturally, we can give you commit bits to make this easy.

**Comment by tolysz** [comment]
Commit bits would be nice, but I guess I could simply create a PR each time.

I see 3 problems:
1) versioning, is the scheme I use any good? 
     I use: `.9007001` for `lts`, and `.820160926` for `nightly`.
2) hosting i.e. finding a bit more permanent home for those snapshots.
    My hosting is not made for scale...
3) testing, I build only a small app... should we build something bigger like pandoc? which node versions to test?

**Comment by tolysz** [comment]
I added the current `lts` and `lts6` https://github.com/commercialhaskell/stack/pull/2644
we will need to decide how to move forward

**Comment by mgsloan** [comment]
Yes!  Also, if possible, can you edit the version number in the cabal file before creating the sdist?  This will allow it to be possible to keep the ghcjs tarball versions distinct, and I think avoid some of the bugs we've been seeing.

I have given you commit bits!  Thanks for making GHCJS tarballs, it is very helpful :)

**Comment by tolysz** [comment]
Thanks!
Those versions are edited by the script which repacks those bundles. 
Later will add a table: 

|resolver|url|sha1|
|---|---|---| 
|||
Thus if someone ;) decide to move those snapshots to `s3..`  they would be welcome to do so.they would just update the url... or if the url patter will be solid we could have `stack` downloading the right compiler without the setup section ;)

@jonathanknowles  is there anything outstanding?
Could you update: https://github.com/tolysz/stack/blob/master/doc/ghcjs.md so following instructions work?

**Comment by tolysz** [comment]
@jonathanknowles Can I assume this ticket is resolved?

**Comment by jonathanknowles** [comment]
@tolysz Sorry for the delay in getting back to you!

By following the updated Stack GHCJS instructions, I am now able to successfully build. For me, at least, this issue is now resolved. 

Regarding the list of older resolver versions: I think having this list is very helpful (especially for cases where one cannot yet upgrade). However, would it be more helpful if there were also a column that displayed the appropriate GHCJS compiler version to use for a given resolver version?

At the moment, we have:

resolver | url | sha1
----------- | ----|--------
lts-7.13 | http://ghcjs.tolysz.org/ghc-8.0-2016-12-18-lts-7.13-9007013.tar.gz | 530c4ee5e19e2874e128431c7ad421e336df0303
lts-7.8 | http://ghcjs.tolysz.org/ghc-8.0-2016-11-07-lts-7.8-9007008.tar.gz | 190300a3725cde44b2a08be9ef829f2077bf8825
... | ... | ...

But it's not clear how to derive the GHCJS compiler name for a given resolver version (i.e., the value to put in the `compiler` field within a `stack.yaml` file). Sorry if I've missed something obvious!

Thanks for your help!

**Comment by tolysz** [comment]
Yes, you are right, but the table would be too wide. Maybe just have (`compiler`) column rather then resolver.
I will need to find a bit more dynamic way of generating new snapshots i.e. if you need an older resolver, you still should be able to get the latest ghcjs... The essential difference between those resolvers is package name and boot.tar

**Comment by tolysz** [comment]
I will close this one, as the original issue is resolved and will try to take suggestions on board while updating documentation.
