### ISSUE TITLE
how to install hakyll3.x on linux vps?

### ISSUE THREAD

**Issue by luckypoem** [commercialhaskell/stack#2652]
the version of hakyll installed with "stack install hakyll" is 4.8.3.2;
    
if i want to install hakyll3.x,what should i do?

**Comment by sjakobi** [comment]
Assuming that you have a cabal package you could add a constraint like `hakyll >= 3 && < 4` to your cabal file and then `stack solver --update-config` or `stack init --solver` depending on whether you already have a stack project.

BTW, note that `stack install` is only a shortcut for `stack build --copy-bins'.
hakyll-3 doesn't seem to have any executables so you can't really "install" it in stack terminology.

If you would like to gain a better understanding of stack, maybe take a look at the [user guide](https://docs.haskellstack.org/en/stable/GUIDE/).

**Comment by mgsloan** [comment]
If you want to install a specific version of hakyll, you can do `stack install hakyll3.0` (or some valid version).  If that doesn't work, then you may also want to override the current resolver.  It seems like hakyll has quite tight version bounds, though, and isn't in stackage.  @sjakobi 's suggestion is your best bet.

In the future this will be automated: https://github.com/commercialhaskell/stack/issues/2656

**Comment by luckypoem** [comment]
@mgsloan , actually "stack install hakyll3.0" doesn't work at all.

**Comment by mgsloan** [comment]
@luckypoem Yes, I left out a dash, it is `stack install hakyll-3.0`, and it depends on which stack.yaml config you are using.
