### ISSUE TITLE
`stack install --solver target`

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2656]
This issue is documenting a design for an enhancement.  Closing issues #1693 and #2039 in favor of this one.
- [ ] Implement [`--no-config` or `--standalone` option](https://github.com/commercialhaskell/stack/issues/1388).
- [ ] Have `stack install --solver` mean to use `stack init --solver` logic along with the targets.  Also implies `--no-config`, and causes a `--resolver` to be chosen.  A warning will be issued when this is used on local packages, mentioning that it is ignoring the current project config and creating a temporary project.  Should also warn when it isn't used with `--copy-bins`, and if there are targets that don't have executables, as these both indicate a misunderstanding about how it works.
- [ ] Suggest `stack install --solver` when there is a build plan failure for target hackage packages that contain executable stanzas, as this is the common case that this is intended for.

**Comment by snoyberg** [comment]
We've removed the solver support in #4670
