### ISSUE TITLE
Add a way to reference local repositories by commit

### ISSUE THREAD

**Issue by seagreen** [commercialhaskell/stack#2670]
This can currently be done for remote repositories using:
```
- location:
    git: git@github.com:foo/bar
    commit: 2f8a8e1b771829f4a8a77c0111352ce45a14c30f
```

It would be nice to be able to do:
```
- location:
    git: ~/path/to/bar
    commit: 2f8a8e1b771829f4a8a77c0111352ce45a14c30f
```

Without the ability to do this I'm worried I'll have trouble building older commits that depend on local packages if I ever have to come back to them. This is because I don't know the exact commit of the dependency being used.

(Note that isn't a problem if you're disciplined about bumping versions in local packages if you modify them, but I'd prefer not to rely on discipline, it doesn't seem very Haskell-ey).

Additionally, if we decide this is a bad idea, we can still improve Stack by changing the error message if a local path is used for `git:`. Right now it gives: `/path/to/quux/.stack-work/downloaded/sUd3RZ-3e2Hj/: getDirectoryContents: does not exist (No such file or directory)`. Instead it could say `Invalid .git URI: ~/path/to/bar`.

**Comment by seagreen** [comment]
Update: this is a `nix` issue. I'll file a full bug report in a minute.

**Comment by seagreen** [comment]
It turns out local paths for `git:` only given an error when `nix: pure:` is set to `true` (this is the default). When it's set to `false` the build succeeds. I've made a self-contained reproduction of this issue here: https://github.com/seagreen/stack-nix-issue

**Comment by YPares** [comment]
Can you try to add `git` to your nix packages?

**Comment by seagreen** [comment]
Oh snap, that worked! :zap: Thanks.

I'm now taken care of, but I recommend we improve the error message. `/path/to/quux/.stack-work/downloaded/sUd3RZ-3e2Hj/: getDirectoryContents: does not exist (No such file or directory)` could be more helpful.

**Comment by mgsloan** [comment]
I get `Executable named git not found on path:` if git isn't on my path.

I've added a check that the dir exists after the clone step.  Let me know if the `getDirectoryContents` message still occurs.
