### ISSUE TITLE
Broken option parsing for subcommands

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2676]
See the usage info for commands that have subcommands:

```
~ $ stack ide --help
Usage: stack ide COMMAND|FILE [--help]
...
~ $ stack config --help
Usage: stack config COMMAND|FILE [--help]
...
```

If you to try run such a command on a file:

```
~ $ stack config turtle.hs
Invalid argument `config'
Error executing interpreter command: stack config --resolver lts-3.2 --install-ghc runghc --package turtle -- turtle.hs
…
```

This is not a recent regression, stack-1.1.0 shows the same usage info, although the error is different when run.

**Comment by mgsloan** [comment]
Seems like a bug to me!  Good catch

**Comment by mgsloan** [comment]
Fixed!

Unfortunately, I can't see a straightforward way to make the error message better.
