### ISSUE TITLE
`stack config set resolver` doesn't accept `ghc-X` type resolvers

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2678]
```
~ $ stack config set resolver ghc-7.10.3
Invalid snapshot name: ghc-7.10.3
~ $ stack config set resolver ghc-7.10
Invalid snapshot name: ghc-7.10
~ $ stack config set resolver ghc-7
Invalid snapshot name: ghc-7
```

The error probably comes from [this line](https://github.com/commercialhaskell/stack/blob/a11c2c2c43f779c6fe7086a2e4c8d974305609a0/src/Stack/ConfigCmd.hs#L87).

Once this is fixed, the help text for the `RESOLVER` argument should be enhanced to suggest e.g. `ghc-7.8` as a valid argument.

**Comment by mgsloan** [comment]
Agreed!  Marking this as a P2 bug!

**Comment by mgsloan** [comment]
Fixed!
