### ISSUE TITLE
Does it really need to write dist-stack directory tree?

### ISSUE THREAD

**Issue by afcowie** [commercialhaskell/stack#268]
You've already got a hidden directory _.stack-work/_. Is it necessary to write the **un**hidden tree at _dist-stack/_? Surely that could be embedded in a single common _.stack[-work]_ tree and not polute the project root?

AfC

**Comment by snoyberg** [comment]
We tried this previously with #92, and ran into Cabal bugs on Windows when dealing with absolute paths. Perhaps we can do something simpler though: just move dist-stack into .stack-work and keep it relative. This won't work particularly well for multi-package projects, as each package directory will end up with its own .stack-work, but perhaps this is still an improvement.

And as to your implied "should we rename to .stack", it's something worth discussing, I've never been happy with .stack-work (it was a quick decision).

**Comment by chrisdone** [comment]
Done. Want to try it out? Working fine here.

**Comment by snoyberg** [comment]
Seems to work for me.

**Comment by afcowie** [comment]
Looks good. You guys rock.

AfC
