### ISSUE TITLE
Spare Chris having to explain semver over and over

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2680]
I'd like `elm-package`, but in Stack. Bump my versions for me. Diff the APIs to figure out what the (minimum) new version should be.

Before the Well-Actually's roll in: yes, we know it can't check changes in semantics. This is getting you an idea of the bare minimum grade of version change. That's still an improvement.

Cf. https://github.com/elm-lang/elm-package#publishing-for-the-first-time

**Comment by bitemyapp** [comment]
Bonus points if it explains why a particular version bump was recommended.

Still more if it just writes it into the package.yaml / *.cabal file.

**Comment by mgsloan** [comment]
This would be cool, but seems like something that would require a quite fancy implementation so putting it on the "Future" milestone.  Perhaps someone would like to develop an external solution, and we can add integration in stack?

Stack already causes GHC to output `.ddump-hi` files, which contain imminently parseable details of all exports.

Also, it is hard to fully automate PVP due to judgement calls regarding the addition and removal of instances, etc.

**Comment by bitemyapp** [comment]
@mgsloan I figured this would be wishlisty, so that all makes sense.

I think a uniform (pessimistic) rule for instance removal/addition is sufficient, as long as you explain (priority ordered) what caused the recommended version. Human can then use judgment if they want to override. Providing a link or means of getting further explanation (like Rust's compiler errors) would be better still.

**Comment by mgsloan** [comment]
A while back I hacked up an api compatibility thing based on text diffs.  Check it out!  https://github.com/mgsloan/api-compat/tree/master/examples

**Comment by domenkozar** [comment]
This would essentially superseed stack, but you'd need to make hackage disallow non-major package bumps on types api changes.

**Comment by harendra-kumar** [comment]
I am very much interested in the API signature based automation to provide hints on version bounds or suggest version bumps. I looked at it sometime back and found these which might be relevant:

http://hackage.haskell.org/package/precis
http://code.haskell.org/gtk2hs/tools/apidiff

**Comment by berdario** [comment]
There's also

https://hackage.haskell.org/package/hackage-diff

(I haven't used yet any of these tools, so I'm not sure if this is any better than the others that have been mentioned)

**Comment by snoyberg** [comment]
Not going to happen, closing.
