### ISSUE TITLE
Caching profiling/non-profiling dependencies independently

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2684]
Per. https://twitter.com/mwotton/status/784112209878069248

Quote:

> so, is there a sane workflow for having profiling switchable in stack projects? I don't want to have always build with profiles.

So far as I'm aware and have seen in my own projects, switching profiling on/off forces a rebuild which is kinda gnarly. Could this be lifted into how builds are cached?

**Comment by mgsloan** [comment]
Things should be much better on master, now that implicit snapshots is merged.  This means that even if you have lots of extra-deps it'll still used cached builds of packages.

Where it won't help so much is avoiding rebuilds of local packages.  Something like https://github.com/commercialhaskell/stack/issues/1634 might help here.

**Comment by ntc2** [comment]
Duplicate of #1132?

**Comment by snoyberg** [comment]
Mostly addressed via implicit snapshots, the rest is tracked with #4032.
