### ISSUE TITLE
stack doesn't work on IPv6 only hosts

### ISSUE THREAD

**Issue by TobyGoodwin** [commercialhaskell/stack#2686]
Trying to install stack on a host with only an IPv6 address I ran into the following issues:
- no AAAA record for get.haskellstack.org
- no AAAA record for download.fpcomplete.com

Fortunately I have access to a NAT64 resolver / gateway, so I was able to proceed, but it would be great if you could be directly available to IPv6-only hosts.

**Comment by mgsloan** [comment]
Seems like a reasonable thing to support!  Pinging @borsboom

**Comment by mpilgrem** [comment]
I am closing this issue because of the passage of time and because (a) Stack does not use `download.fpcomplete.com` and (b) on Windows, `nslookup -q=aaaa get.haskellstack.org` yields AAAA record(s).
