### ISSUE TITLE
"Did not find .cabal file" messages in integration tests

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#2691]
The integration tests currently spew our well-known "Did not find .cabal file for…" messages to stderr as can be seen for example [here](https://jenkins-public.fpcomplete.com/job/stack-integration-tests/356/consoleFull).

The excessive output makes it less fun to work on the integration tests so I think we should try to make it go away.

I see the same behaviour locally, so I don't think it's related to the setup of the integration server.

I somewhat suspect that it might be related to the [`toCopyRoot` function](https://github.com/commercialhaskell/stack/blob/ccca86d73cf1008edb37f75560f9470e9da9aa82/test/integration/IntegrationSpec.hs#L128) that controls which files are copied into the individual stack root directories for each test case.

**Comment by mgsloan** [comment]
I think this got resolved at some point - no longer seeing it in the integration tests output https://jenkins-public.fpcomplete.com/job/stack-integration-tests/650/console
