### ISSUE TITLE
Need to display output when a tool fails

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#270]
Currently, if configuring GHC fails, all of the output from the `./configure` process is swallowed. Similarly for things like sanity check, Git clone, etc. We should have logic in place that, if the process exits unsuccessfully, we print the stdout and stderr for the user to review.

Pinging @chrisdone

**Comment by chrisdone** [comment]
:+1:

**Comment by chrisdone** [comment]
I changed it so that everything is implemented in terms of @manny-fp's recent `sinkProcessStdoutLogStderr`. On stderr, that's printed immediately. On failure, it prints all collected stdout so far.

Now on master we have:

``` shell
chris@retina:~/Work/stack$ cat X.hs
main = do putStrLn "Some stdout!"
          error "Some stderr!"
chris@retina:~/Work/stack$ ghc --make X -o /opt/ghc/7.8.4/bin/ghc
Some stdout!
ghc: Some stderr!
chris@retina:~/Work/stack$ stack install stack 
ghc --numeric-version: ghc: Some stderr!
ghc --numeric-version: Some stdout!

No GHC found, expected version 7.8.4 (based on resolver setting in /home/chris/Work/stack/stack.yaml). Try running stack setup
```

**Comment by chrisdone** [comment]
Also, all processes run are automatically logged with `$logDebug`, so you don't have to explicitly mention it in calling code anymore.
