### ISSUE TITLE
`{}` in config.yaml is confusing

### ISSUE THREAD

**Issue by Blaisorblade** [commercialhaskell/stack#2700]
I've often seen `{}` as a default in config.yaml. That's confusing—assuming that comes from Stack-generated config, is there something else we can use going forward by default for an empty config? I guess that's allowed because you could use JSON-like map literals, but that's not an intentional part of Stack's interface...

I've filed this issue because I was confused by this, and others might be too—see https://github.com/commercialhaskell/stack/issues/2575#issuecomment-252951103 (not arguing "that user is confused", just that he might be, and I'd like to reduce the possibility).

**Comment by mgsloan** [comment]
Good point!  I believe an empty file / one with comments is equivalent.

**Comment by lwm** [comment]
https://github.com/commercialhaskell/stack/commit/e4092597ca6238022437192057512f384d33e2dc is merged, this can be closed :rocket:

**Comment by mgsloan** [comment]
Yup!
