### ISSUE TITLE
Idea: `stack try` to open a one-off REPL with certain packages loaded

### ISSUE THREAD

**Issue by devlinzed** [commercialhaskell/stack#2701]
Check out [lein-try](https://github.com/rkneufeld/lein-try).  I built a cabal-based tool and one exists for NPM in JavaScript-land as well.  I think it would be a good addition to stack.

If other people agree and can give me some tips for how to implement this feature (I've never worked on stack directly) I would be happy to take it on.

**Comment by lwm** [comment]
Nice idea. Seems like it would be nice as a plugin, just like 'lein try'. This made me think: Is Stack pluggable? Can you write 3rd party code that can hook into Stack? I don't think so. Just rambling here ;)

**Comment by mgsloan** [comment]
Cool idea indeed!  You can already do `stack ghci --package aeson --no-load` and then do ":m + Data.Aeson".  Should it automatically import the exported modules from the packages?  What if there is a bunch of name aliasing between modules (like if you did `stack try containers`).

So, could just make this a convenient alias for a `stack ghci` invocation.

**Comment by lwm** [comment]
>  What if there is a bunch of name aliasing between modules (like if you did stack try containers).

User beware, I suppose? Could be documented. 

Would like to see this @devlinzed!!!
