### ISSUE TITLE
"Stack configuration has no specified verson" - could this error be improved?

### ISSUE THREAD

**Issue by chrissound** [commercialhaskell/stack#2713]
Just a suggestion, I was including a package of `missingh` instead of `MissingH` which gave me an error message of (upon `stack build`):

```
While constructing the build plan, the following exceptions were encountered:

In the dependencies for hackerrank-0.1.0.0:
    missingh must match -any, but the stack configuration has no specified version

Plan construction failed.
```

What exactly is the 'stack configuration'? Perhaps we could improve the error message to say the package could not be found?

**Comment by mgsloan** [comment]
Your stack configuration consists of your selection of resolver, extra-deps, and packages.  The package `missingh` 

I think the ideal way to resolve this would be to implement fuzzy name matching of all hackage packages - see https://github.com/commercialhaskell/stack/issues/1748 .  Perhaps only do the fuzzy name match for "local packages".

**Comment by chrissound** [comment]
![2016-10-18-06 00 26](https://cloud.githubusercontent.com/assets/1499652/19464932/4122e956-94f8-11e6-8023-061ec6452e92.png)

There isn't a single occurrence of "stack configuration" on the google search for "haskell stack configuration". Is this term well known?

Regardless of fuzzyfinder suggestions I still think the above error message could be improved.

**Comment by mgsloan** [comment]
@Cypher1 No specific documentation.  Could add it to the FAQ I suppose.

The errors have gotten a bit better since this was reported, and the first google result for "haskell stack configuration" is a reasonable result.  It is a valid term, referring to the combination of CLI, stack.yaml, config.yaml, etc.

**Comment by Cypher1** [comment]
The problem with this is that
```-any, but the stack configuration has no specified version``` doesn't seem like an error.
I.e. We asked for any, and stack didn't specify a version (so shouldn't it use any version?).

Thanks

**Comment by quickdudley** [comment]
I'm currently getting this error even though the stack configuration **does** specify not just a version but a specific git commit.

**Comment by cestrand** [comment]
For me, this occured when i've tried to add "HTTP" library as dependency of my freshly created project. I've realized that I've been typing "http" whereas "HTTP" solved the problem.

**Comment by marcosh** [comment]
I just run into this issue, which was caused by a typo.

Maybe the error message could be rephrased to something like
```
missingh must match -any version, but no version is present in the stack configuration and hence the package cannot be found. Please check if there is a typo in your package name.
```
with a hint to rule out immediately the stupid issues

**Comment by statusfailed** [comment]
This can also happen if your `stack.yaml` syntax for extra dependencies is wrong. I had the same problem as in [this stackoverflow post](https://stackoverflow.com/questions/43789271/stack-yaml-not-pulling-in-dependency-from-github) (I was missing the `extra-dep: true`).

I like the error message suggested by @marcosh, I found it much more explicit. At the risk of being too verbose, I might suggest the following addition:

`missingh must match -any version, but no version is present in the stack configuration and hence the package cannot be found. Please check if there is a typo in your package name and that your stack.yaml configuration's "packages" section is correctly specified.`
