### ISSUE TITLE
"stack haddock" gives up early on a source file error

### ISSUE THREAD

**Issue by jchia** [commercialhaskell/stack#2719]
### General summary/comments (optional)

`stack haddock` fails and gives up when it encounters a compile error in MemoTrie-0.6.4. Other packages that should be unrelated to MemoTrie are unprocessed.
### Steps to reproduce
1. Make a simple project with `stack --resolver=lts-7.4 new x`.
2. Add classy-prelude and units as the library build-depends in the project cabal file.
3. Clean out the snapshots/x86_64-linux/lts-7.4/8.0.1/doc subdirectory in the .stack directory so that `stack haddock` will be forced to do some work.
4. From the project directory, run `stack haddock`
### Expected

MemoTrie gets a compile error that is reported on the console, but `stack haddock` should continue processing unrelated packages that have no errors as far as possible, at least when `--keep-going` is specified.
### Actual

`stack haddock` gives up immediately upon encountering the compile error and exits. `--keep-going` makes no difference. Output from subsequent retries of `stack haddock` indicates that the retries do cause the number of items to process ("Progress : #/#") to decreases, suggesting that additional packages were successfully processed in some of the retries. Additionally, on the retries, the console displays the packages that are being processed and the list of packages changes across different retries, eventually decreasing to only include MemoTrie. If `stack haddock` were proactive about processing as much as possible, subsequent retries would have yielded no progress and every retry would have yielded the same "Progress" value and list of packages.
### Stack version

``````
$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0```

### Method of installation
fpcomplete's package repository for Fedora 22.
``````

**Comment by mgsloan** [comment]
I've tried reproducing this with stack-1.4, and happily it seems to work fine.  I get the MemoTrie error, but it manages to continue building as much as possible.  Please re-open if it's still problematic for you.
