### ISSUE TITLE
No ddump files are generated

### ISSUE THREAD

**Issue by wdanilo** [commercialhaskell/stack#2720]
# bug report

### General summary/comments (optional)
According to documentation:

> Where does the output from --ghc-options=-ddump-splices (and other -ddump* options) go?
> These are written to *.dump-* files inside the package's .stack-work directory.

The problem is, that the files are not generated there, at least in my use case.

### Steps to reproduce

1. Running the command: `stack build --ghc-options=-ddump-splices --stack-yaml build/stack-develop.yaml`
2. the `stack-develop.yaml` looks like:
```
resolver: lts-7.4

packages:
    - ..
    <...>
extra-deps:
   <...>
ghc-options:
    "*": -DFastCompilation -threaded -funbox-strict-fields -O0 -fprint-potential-instances -fconstraint-solver-iterations=10 -F -pgmF preskell -optF --source=../toolchain/ghc/extensions -ddump-cs-trace

local-bin-path: ./dist/bin
```
where `<...>` means that there is more text.

3. there are no `*.dump-*` files in any .stack-work directory (by any I mean the `project/.stack-work` and `project/build/.stack-work`.

### Stack version

```
`Version 1.1.2 x86_64 hpack-0.14.0`

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment]
I've updated the faq to be clearer about the location of the resulting ddump files:

> These are written to `*.dump-*` files inside the package's `.stack-work`
directory. Specifically, they will be available at `PKG-DIR/$(stack path
--dist)/build/SOURCE-PATH`, where `SOURCE-PATH` is the path to the source file,
relative to the location of the `*.cabal` file.

Are they not available there?  By default stack causes `.ddump-hi` files to exist in that location.

**Comment by wdanilo** [comment]
Ok, I've got them. So here are two other things to fix:

1. The option is `--dist-dir`, not `--dist`
2. When looking for the files from Main module, the path is different, in my case it was: `PKG-DIR/$(stack path --dist)/build/<projectname>/<projectname-tmp>/<main-module-dir>/...`

Thank you for your help!

**Comment by mgsloan** [comment]
You're welcome, and good point!  I have amended the faq based on your feedback.
