### ISSUE TITLE
user interface/accessibility features: Please revert (color) pretty-printing of errors

### ISSUE THREAD

**Issue by phlummox** [commercialhaskell/stack#2725]
### General summary/comments (optional)

Version 1.2.0 introduces pretty-printing of dependency resolution errors (#1912). This is unsuitable for users who may have vision impairment issues, and who have set their terminal colors to meet their own needs.
 
Please revert the change, or provide the option to disable colored output. (Such an option is standard for most command-line software; a flag like "--color={never,always,auto}" is provided for even basic command utilities like "ls" and "grep".)

### Steps to reproduce

Attempt to build any project with dependencies not found in the snapshot.

### Expected

Displays errors in color.

### Actual

Displays errors in color.

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment]
Thanks for bringing up the issue, certainly an oversight.  I think we should definitely provide a `--color` flag as described.  We are only going to be adding more usage of color.

Perhaps it is possible to disable color in the terminal in general?  This would be a way for vision impaired individuals to not need to provide such flags.

**Comment by mgsloan** [comment]
This is now implemented as described!  `--color never` can now be passed to stack.

**Comment by phlummox** [comment]
Many thanks :)
&nbsp; &nbsp; In response to the [previous comment](https://github.com/commercialhaskell/stack/issues/2725#issuecomment-255498471) - yes, it's possible to disable colour in a terminal completely, but that means you can't make use of any useful color schemes you *have* set up. And what's useful for one sort of vision impairment (e.g. red-green colour blindness) may not be useful for another (e.g. yellow-blue colour blindness - tritanopia). But a general `--color never` flag is great, cheers!
