### ISSUE TITLE
How do I get extra tools

### ISSUE THREAD

**Issue by s-trooper** [commercialhaskell/stack#273]
How to install ghc-mod, hoogle and such stuff global (as not per project)?

I have tried "stack deps ghc-mod" but get it only in the project ".stack-work" sub folder, i would like to have the binaries in %APPDATA%\local\bin or other already PATH'ed path.

**Comment by snoyberg** [comment]
I recently added the `install` command, which copies executables to ~/.local/bin on POSIX systems and %APPDATA%\Roaming\local\bin on Windows. Can you try building the latest master and testing it out?

**Comment by snoyberg** [comment]
Also, this may be of interest: https://github.com/commercialhaskell/stack/wiki/Downloads#path

**Comment by s-trooper** [comment]
thank you very much "stack install ghc-mod" install ghc-mod to %APPDATA%\local\bin that is great! hoogle and hlint work nicely but ghc-mod don't work i get this:

"launching operating system process `cabal configure` failed: cabal: readProcessWithExitCode: does not exist (No such file or directory)"

**Comment by snoyberg** [comment]
Awesome, thank you!

**Comment by jbpotonnier** [comment]
I used the install command to install ghc-mod, but I'm not able to run it because it cannot find ghc, even when I use the `--with-ghc` option. I think there is something that I don't understand with path management in stack.
I've let stack install ghc.

An entry in the FAQ on how to use "external" tools (ghc-tools, stylish-haskell, etc.) could be nice.

Maybe @s-trooper can help me ;)

**Comment by s-trooper** [comment]
@jbpotonnier i have had exactly the same issues, sadly i don't have The solution for you, but i will write down my story may be it will help.

At first i got same no ghc found problem, so i put "stack setup"paths to my PATH (because on Win "stack setup" don't was capable to do this automaticlly) . Then ghc was accessible but i get this cabal "readProcessWithExitCode" error.

Next i have done some random actions to get error down. I got rid off "stack setup" paths in PATH so ghc was not visible. Then i went to my %APPDATA%\local\bin folder and run hgc-mod from there, and it worked!? After that ghc-mod works for me, even with "stack setup" paths in PATH. As you see i have no idea what was happen.

**Comment by snoyberg** [comment]
AFAICT, this is a problem with ghc-mod, not stack, though I could be mistaken. I unfortunately don't have any experience with ghc-mod, so I can't speak to that point. In my testing, other external tools just work without issue.

**Comment by jbpotonnier** [comment]
FYI, I could go one step further adding ~/.stack/programs/x86_64-osx/ghc-7.8.4/bin to my path.
But ghc-mod seems to heavily use the cabal command, I think it does not play well with stack.

I use ghc-mod for error checking, types tooltips and completion in my editor. 
For now I'll give up using stack and stick to my cabal only workflow.

**Comment by snoyberg** [comment]
Would you consider opening an issue on ghc-mod about using stack, and linking to it here? I think others would find that useful.

**Comment by PGGB** [comment]
>`stack path --dist-dir` gives us the directory containing `setup-config` for some version of Cabal that stack uses. In my current experiment stack seems to install the version of Cabal it's using into the directory returned by `stack path --snapshot-pkg-db`.

>So theoretically we just have to pass that stack dist-dir to cabal-helper and it'll figure out the rest. Unfortunately stack doesn't seem to have a `configure` command so we'll have to keep using cabal-install to maintain our own setup-config somewhere :/ Unless someone feels like patching stack?

>To work around this we can ask stack for the paths to it's package-dbs and pass those down to cabal configure, i.e. `cabal configure --package-db=clear --package-db=global --package-db=$(stack path --snapshot-pkg-db) --package-db=$(stack path --local-pkg-db)` support for doing this would have to be added to cabal-helper.

>One thing I'm still not sure about is how to decide weather to use stack or cabal directly to configure a project if both a cabal and a stack.yml file exist.

https://github.com/kazu-yamamoto/ghc-mod/issues/498#issuecomment-118322260 by @DanielG

Not sure what side makes more sense to patch.
