### ISSUE TITLE
improve missing package error

### ISSUE THREAD

**Issue by zkessin** [commercialhaskell/stack#2744]
When getting an error because of a package missing from the cabal file it would be very useful to have a link in the file to the actual cabal file. This would both prevent a user from editing the wrong one by mistake and for users in emacs and the like it would allow them to go directly to the file with the compile mode's next error function

```
[1 of 1] Compiling Main             ( tests/test.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.0.0/build/test/test-tmp/Main.o )

/home/zkessin/Documents/Atidot/arena/packages/cluster/arena-nomad/tests/test.hs:17:1: error:
    Failed to load interface for ‘Control.Lens’
    It is a member of the hidden package ‘lens-4.14’.
    Perhaps you need to add ‘lens’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
Progress: 1/2
--  While building package arena-nomad-0.1.0.0 using:
      /home/zkessin/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 build lib:arena-nomad test:test --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
Makefile:40: recipe for target 'test-arena-nomad' failed
make: *** [test-arena-nomad] Error 1

```

**Comment by mgsloan** [comment]
It's a good idea, but I don't think ghc knows where the cabal file is, and ghc is emitting that error.

**Comment by zkessin** [comment]
Ok, but stack knows where it is, so why can't stack issue a 2nd error message or supliment it?

**Comment by mgsloan** [comment]
We'd need to parse all of the output of GHC, currently we're only doing that minimally.  Could be hard to maintain such a parser across variation in GHC versions.

**Comment by zkessin** [comment]
it seems that this is an issue that can't easily be fixed in GHC as it does not know where the cabal file is, or fixed outside of GHC.
