### ISSUE TITLE
--jobs option to limit concurrency

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#275]
Currently Slack will happily saturate all cores that are available. Sometimes it may be useful to limit the concurrency factor (debugging, lap-burning avoidance...).

It should be possible to say:
```
$ stack build --jobs=N
```
for some arbitrary integer N. For `stack test`, this even more crucial, because some test suites may (rightly or wrongly) depend on shared system resources that they need exclusive access to (e.g. port numbers) therefore should be run in sequence.

**Comment by snoyberg** [comment]
I actually have a TODO about this in the codebase already, it's trivial to implement. Doing so now.

**Comment by snoyberg** [comment]
OK, implemented. @mboes confirmed?

**Comment by mboes** [comment]
Works well!
