### ISSUE TITLE
Documentation should mention hpack

### ISSUE THREAD

**Issue by chris-martin** [commercialhaskell/stack#2750]
Stack's support for hpack `package.yaml` files as an alternative to `.cabal` files seems to be [missing from the documentation](https://readthedocs.org/search/?q=hpack&check_keywords=yes&area=default&project=stack&version=stable&type=file). Having never heard of hpack before, this caused me [much confusion](https://stackoverflow.com/questions/40332040/what-goes-in-a-stack-package-yaml-file). The docs ought to discuss this feature a bit.

**Comment by lwm** [comment]
Fair enough. I also didn't know what a `package.yaml` was either.

**Comment by Blaisorblade** [comment]
Agreed, PRs welcome (traveling & busy right now, sorry).

**Comment by chris-martin** [comment]
My point in raising this issue was to make it possible to figure out what a "package.yaml" file does in a Stack project by reading the Stack documentation, so IMO it's not resolved since the Stack docs still don't mention package.yaml.

**Comment by lwm** [comment]
@chris-martin, can you amend the documentation entry then?
