### ISSUE TITLE
Can't link libcurl from external project

### ISSUE THREAD

**Issue by reygoch** [commercialhaskell/stack#2752]
I have 2 projects :

+ site-browser (stack lte-5.4)
+ simple-reporting (stack lte-6-20)

site browser has curl as one of the dependencies, and curl package installed successfuly (after some annoying setup).

When I do `stack build` in `site-browser` library it builds it successfully, but when I add `site-browser` as dependency in `simple-reporting` project and try to build `simple-reporting` than I get the following error :

    --  While building package site-browser-0.1.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\setup-Simple-Cabal-1.22.5.0-ghc-7.10.3.exe --builddir=.stack-work\dist\2672c1f3 build lib:site-browser exe:site-browser-exe --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\reygoch\Documents\Posao\company\Repositories\simple-reporting\.stack-work\logs\site-browser-0.1.0.0.log

    Configuring site-browser-0.1.0.0...
    Preprocessing library site-browser-0.1.0.0...
    [ 1 of 13] Compiling Browser.Common   ( src\Browser\Common.hs, .stack-work\dist\2672c1f3\build\Browser\Common.o )
    [ 2 of 13] Compiling Browser.Network  ( src\Browser\Network.hs, .stack-work\dist\2672c1f3\build\Browser\Network.o )
    [ 3 of 13] Compiling Browser.TypeList ( src\Browser\TypeList.hs, .stack-work\dist\2672c1f3\build\Browser\TypeList.o )
    [ 4 of 13] Compiling Browser.Types    ( src\Browser\Types.hs, .stack-work\dist\2672c1f3\build\Browser\Types.o )
    [ 5 of 13] Compiling Browser.MailVerification ( src\Browser\MailVerification.hs, .stack-work\dist\2672c1f3\build\Browser\MailVerification.o )
    [ 6 of 13] Compiling Browser.Connections ( src\Browser\Connections.hs, .stack-work\dist\2672c1f3\build\Browser\Connections.o )
    [ 7 of 13] Compiling Browser.Profile  ( src\Browser\Profile.hs, .stack-work\dist\2672c1f3\build\Browser\Profile.o )
    [ 8 of 13] Compiling Browser.Action   ( src\Browser\Action.hs, .stack-work\dist\2672c1f3\build\Browser\Action.o )
    [ 9 of 13] Compiling Browser.Action.Monad ( src\Browser\Action\Monad.hs, .stack-work\dist\2672c1f3\build\Browser\Action\Monad.o )
    [10 of 13] Compiling Browser.siteSession ( src\Browser\siteSession.hs, .stack-work\dist\2672c1f3\build\Browser\siteSession.o )
    [11 of 13] Compiling Browser.Messages ( src\Browser\Messages.hs, .stack-work\dist\2672c1f3\build\Browser\Messages.o )
    <command line>: can't load .so/.DLL for: C:/Users/reygoch/AppData/Local/Programs/stack/x86_64-windows/ghc-7.10.3/mingw/bin/libcurl.dll (addDLL: could not load DLL)
    ghc.EXE: C:/Users/reygoch/AppData/Local/Programs/stack/x86_64-windows/ghc-7.10.3/mingw/bin/libcurl: The specified module could not be found.

**Comment by LukaHorvat** [comment]
I'm building the same codebase and I'm facing similar issues. For me the first module fails to build at the same point but the error is the following

    ghc.EXE: unable to load package `curl-1.3.8'
    ghc.EXE: C:\Users\darwi\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib\libcurl.a: unknown symbol `ERR_clear_error'

ERR_clear_error is a symbol from the `OpenSSL` library if I'm not mistaken but I have no idea what to do with this information.

Both mine and OP's machines are running Windows 10.

**Comment by LukaHorvat** [comment]
I've narrowed down the issue to the following steps needed to reproduce it (in my case at least).

Make a new stack project (lts-5.3 in my case). `stack new curl-test -resolver=lts-5,3 `
Add `curl` and `lens` as a dependency to the library.
Modify the `Lib` file to the following 

```haskell
{-# LANGUAGE TemplateHaskell #-}
module Lib where

import Control.Lens

data T = T String deriving (Eq, Ord, Read, Show)
makeLenses ''T

someFunc :: IO ()
someFunc = return ()
```

Try to build the project.

The `makeLenses` line triggers the error so this obviously has something to do with TH.

**Comment by LukaHorvat** [comment]
I believe this is the relevant GHC ticket. I've left a comment with additional info that might be relevant https://ghc.haskell.org/trac/ghc/ticket/9010#comment:20

**Comment by lwm** [comment]
Following from https://ghc.haskell.org/trac/ghc/ticket/9010#comment:20 and https://ghc.haskell.org/trac/ghc/ticket/12806#ticket (**very** briefly), it seems like this an upstream issue. I'll close, but please re-open if there is something to do in Stack land.
