### ISSUE TITLE
Stuck linking in Docker when using `run-args` in stack.yaml

### ISSUE THREAD

**Issue by Tehnix** [commercialhaskell/stack#2754]
I'm not entirely sure if this is a _stack_ or a _docker_ problem, since it's a combination of the two.

It seems I'm getting stuck in the linking (i.e. `Linking .stack-work/dist/x86...`) phase when trying to build my project using docker, and using `run-args` in my `stack.yaml`.

My project is a website using the [Yesod](http://www.yesodweb.com) framework. The full code is at [Tehnix/campaigns](https://github.com/Tehnix/campaigns/tree/610550e6575575d4f4cb46703a943cd9101734e9), if anyone needs to try and build it.

For the record, it builds rather quick in a vagrant vm, so I know the project can build.

### Steps to reproduce

For example:

1. `git clone https://github.com/Tehnix/campaigns.git`
2. `cd campaigns`
3. `stack  --stack-yaml=stack-docker.yaml clean`
4. `stack --stack-yaml=stack-docker.yaml build`

The `stack-docker.yaml` contains,

```yaml
resolver: lts-6.20
packages:
- '.'
extra-deps: []
flags: {}
extra-package-dbs: []
docker:
  enable: true
  auto-pull: true
  container-name: "yesod-server"
  run-args: ['--net=bridge', '--publish=3000:3000', '--env-file', '.env']
```
### Expected

I expect the linking phase to finish, and the project to build as normal.

### Actual

The build gets stuck linking. I've tried letting it run for 8 hours, and no luck (and it normally doesn't take long to finish).

The output when running `stack --stack-yaml=stack-docker.yaml build --verbose` https://gist.github.com/Tehnix/61795276c72c50db0922ca6c252bd4a4. 

There's no way of quitting the process (`ctrl-c` etc doesn't work) except for restarting Docker and letting it get `Error response from daemon: Bad response from Docker engine`.

__Now here's the kicker!__ If I remove `run-args: ['--net=bridge', '--publish=3000:3000', '--env-file', '.env']` from the `stack-docker.yaml` file, the project builds! The output from `stack --stack-yaml=stack-docker.yaml build --verbose` with the adjustment https://gist.github.com/Tehnix/edb443aea57d3a0aaf292eaad21236fa.

### Stack version

The newest stack version,

```
$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
```

### Docker version

I'm using Docker for Mac on macOS Sierra.

```
$ docker --version
Docker version 1.12.1, build 6f9534c
```

Configured to use CPUs: 4 and Memory: 6 GB.

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment]
Curious!  While I don't use OS X, I have seen some similar behaviors.  It seemed to help things out to restart the docker engine.  It seems like this is likely some upstream bug in docker on mac os.

**Comment by mgsloan** [comment]
Closing as an old support ticket.
