### ISSUE TITLE
Do you have official prebuilt docker images?

### ISSUE THREAD

**Issue by netroby** [commercialhaskell/stack#276]
Do you have official prebuilt docker images?

**Comment by gregwebs** [comment]
No. But there is support for Docker workflows, see the [FAQ](https://github.com/commercialhaskell/stack/wiki/FAQ). What is the workflow you have in mind?

**Comment by manny-fp** [comment]
It depends on what exactly you mean.  There is no  [blessed-by-Docker-Inc Official Repository](https://docs.docker.com/docker-hub/official_repos/) for stack, and there probably never will be.  FP Complete *is* pushing Docker images for use with stack to the [fpco/dev repo on Docker Hub](https://registry.hub.docker.com/u/fpco/dev/).  These images are really big, over 10 GB, and include all of Stackage LTS pre-installed.  The way these are used is that you still install stack on your host OS, but you add a bit of configuration in stack.yaml which causes stack to actually perform builds in a Docker container behind the scenes.  See the "I heard you can use this with Docker?" entry in the [FAQ](https://github.com/commercialhaskell/stack/wiki/FAQ) for a bit more info on this, and I will soon be adding more detailed documentation to the wiki.  The main purpose for using stack/docker this way is for teams to ensure they are building in an exactly consistent environment without team members needing to deal with Docker themselves. 

We are also pushing images to [fpco/ghcjs-dev](https://registry.hub.docker.com/u/fpco/ghcjs-dev/), which is the the same as fpco/dev but adds GHCJS as well.

There's the other use case where you just want to have an image with GHC and stack built-in that you'll then use to run stack inside yourself.  The current images we are pushing don't include itself stack yet, but the next ones (for LTS-2.14) will.  In addition, @gregwebs has provided a [Dockerfile](https://github.com/commercialhaskell/stack/blob/master/etc/docker/haskell-stack/Dockerfile) that looks like it augments the [Official Haskell image](https://registry.hub.docker.com/_/haskell/) with stack and a couple of other things.  I don't believe images generated by @gregwebs' Dockerfile are being pushed anywhere, but that may be something to consider doing.

@snoyberg @gregwebs: what do you think about pushing images generated by @grebwebs' Dockerfile?  I'm a bit concerned we'll end up causing some confusion if there are two ways to use Docker with stack (one where stack uses it under the surface, and the other where a user actually runs stack in a container themselves), so we'll need to find a way to make sure we're really clear that these are two separate use cases.

**Comment by gregwebs** [comment]
yes, I can push the *Dockerfile* to the registry, but I also wanted to wait until I understood everything. I think that pushing an *image* rather than a *Dockerfile* to the registry is a really bad idea. There may be some use case where this is desireable because the build times out or something, but we should first figure out if pushing the *Dockerfile* works.

**Comment by manny-fp** [comment]
Quite right, I meant making an image available on the registry as opposed to specifically pushing it, and in your case doing so by putting the Dockerfile there makes the most sense.

**Comment by manny-fp** [comment]
First draft of Docker docs are on the [wiki](https://github.com/commercialhaskell/stack/wiki/Docker).

**Comment by snoyberg** [comment]
Is there more to be done on this issue, or can it be closed?

**Comment by netroby** [comment]
Ok， cose it
