### ISSUE TITLE
Run fetch on git / hg packages

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2762]
Currently, if you change the SHA of a downloaded git repo, it will try to do a `git reset` (`hg update`).  If this doesn't work, then we do a full `git clone`.  It would be more efficient to do a `git fetch` followed by `git reset`.

**Comment by snoyberg** [comment]
The new architecture of Pantry—which no longer keeps the repos on the filesystem—wouldn't allow for this. We could add back storage of the repos, but IMO that's overall a pessimization. Closing.
