### ISSUE TITLE
Setup of GHCJS fails on NixOS

### ISSUE THREAD

**Issue by ElvishJerricco** [commercialhaskell/stack#2763]
[Related](https://github.com/commercialhaskell/stack/issues/2586). In order to setup GHCJS on NixOS, Stack has to download GHC so that it can build GHCJS. But, as with the linked issue, Stack fails to install GHC on NixOS. The error is the same; the binary downloaded is not compatible with NixOS (dynamic linker is wrong). So it is unable to proceed to build GHCJS.

A workaround is to enter a nix shell with GHC already on the path a la nix.

```bash
$ nix-shell -p haskell.compiler.ghc801
...
[nix-shell] $ stack setup
```

But this is a workaround. Stack should be able to do this on its own when nix integration is enabled. Instead, stack reports that it cannot use nix integration when using GHCJS.

---

Stack version 1.2.0

**Comment by divipp** [comment]
I have tried the workaround and it does not work for me. In the nix-shell, stack still downloads GHC and fails with a linker error later.
What did I do wrong?

**Comment by mgsloan** [comment]
@divipp Hey!  I don't use nix much, but I think the solution is to entirely skip having stack download a GHC.  Instead set `system-ghc: false` in your config.yaml or pass `--system-ghc`, so that it will use the ghc installed by nix.

**Comment by ElvishJerricco** [comment]
Yea at he time this issue was opened, stack would always use the system GHC if it was available, even without the flag. I guess that's no longer true?

**Comment by mgsloan** [comment]
Yep!  Could make sense to change the default for --nix, though.

**Comment by divipp** [comment]
Thanks for the suggestions.
Unfortunately adding `system-ghc: true` to config.yaml or passing `--system-ghc` at command line has no effect. Even `--skip-ghc-check` has no effect.
If I run `stack` in verbose mode I see

    ...
    [debug] Using standard GHC build
    [info] Preparing to install GHC to an isolated location.
    ...

I have stack version 1.4.0 x86_64

Maybe `system-ghc: true` does not work well together with `compiler: ghcjs` so the workaround above does not work?

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
