### ISSUE TITLE
stack doesn't respect Buildable:False in tests

### ISSUE THREAD

**Issue by qnikst** [commercialhaskell/stack#277]
If package has a conditionally enabled test, then stack writes a error message.

How to reproduce:

1. take a package with conditional test, that is disabled (for example `network-transport-tcp`)
2. run stack test

Excepted results:
1. output that doesn't mention disable test
2. exit code is `ExitSuccess` (0)

Actual results:
```
Test suite failure for package network-transport-tcp-0.4.1
    TestQC:  executable not found
```
1. Exit code is non zero

**Comment by snoyberg** [comment]
Thanks for the report, this is actually a known issue in the code base:

https://github.com/commercialhaskell/stack/blob/64ff652ba3d7e4a6532276a165a8661de86c4f3b/src/Stack/Package.hs#L226

It's probably not too difficult to address this, just using `pkg` instead of `gpkg`. Want to take a crack at it?

**Comment by qnikst** [comment]
Yes, will try to fix that, thanks for the pointers.

**Comment by snoyberg** [comment]
Cool!

**Comment by qnikst** [comment]
Fixed in https://github.com/commercialhaskell/stack/pull/278 , do I need to do the same for benchmarks? (The only thing that I don't have a good examples under the hands, but can write some).

**Comment by snoyberg** [comment]
Benchmarks aren't necessary (we don't run them ourselves yet), but I wouldn't object to them being added now if you're up for it. It would be very useful to have this same approach used for the executables though, would you be up for adding that to the PR?

**Comment by qnikst** [comment]
Yes, of cause, I'll add this to benchmarks.

**Comment by qnikst** [comment]
Done.

**Comment by snoyberg** [comment]
Merged, thank you!
