### ISSUE TITLE
stack should support XDG_CONFIG_HOME/XDG_DATA_HOME

### ISSUE THREAD

**Issue by legrostdg** [commercialhaskell/stack#2775]
It would be great if stack could use XDG_CONFIG_HOME/XDG_DATA_HOME, and $HOME/.stack as a fallback.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by mgsloan** [comment]
I don't think we want to change this, as it would mean that the stack root would change directories.  So the user would be left with an old unused stack root, and a new one.

This may well be more "correct", though.  One possible option might be to check for `$HOME/.stack` first, and if it doesn't exist, also look for `$XDG_DATA_HOME/stack`, orso.

**Comment by damienflament** [comment]
See #4243.
