### ISSUE TITLE
Can't use GHCJS from $PATH

### ISSUE THREAD

**Issue by TravisWhitaker** [commercialhaskell/stack#2777]
It doesn't seem to be possible to use stack 1.2.0 with an externally available ghcjs. Most operations fail with:

```
After installing Cabal, the package id couldn't be found (via ghc-pkg describe Cabal). This shouldn't happen, please report as a bug
```

### Steps to reproduce

Install ghcjs and Cabal where ghcjs-pkg can find it (e.g. via cabal). `ghcjs-pkg describe Cabal` should be able to find the package. Then:

```
stack new sus
cd sus
stack build --compiler ghcjs-0.2.1_ghc-8.0.1 # or set in stack.yaml
```

### Expected

`stack build`, `stack clean`, `stack ghc`, etc. succeed.

### Actual

```
After installing Cabal, the package id couldn't be found (via ghc-pkg describe Cabal). This shouldn't happen, please report as a bug
```

### Stack version

1.2.0

### Method of installation

Via nix.

**Comment by tolysz** [comment]
A couple pointers: stack ignores a bunch of wired-in packages - `Cabal` is one of them.
Which resolver are you using to build something, as the Cabal version from it and Cabal version from ghcjs might differ?

**Comment by TravisWhitaker** [comment]
Apologies for forgetting about this issue. @tolysz was correct, it was a mere resolver version mismatch.

**Comment by mstksg** [comment]
@TravisWhitaker How did you resolve this?  did you change the resolver in your project?

**Comment by TravisWhitaker** [comment]
@mstksg Yep, I ended up just picking the nightly with the Cabal version my GHCJS expected.
