### ISSUE TITLE
make stack shebang statement work with markdown-unlit

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack#2783]
it would be awesome if one could have a "literate readme" file under stack

@sol has created this awesome thing - https://github.com/sol/markdown-unlit

so i was trying to use it like so (in a file called `Test.lhs`)

```
#!/usr/bin/env stack
-- stack --install-ghc runghc --package markdown-unlit -- "-pgmL markdown-unlit"

# nifty-library: Do nifty things (effortlessly!)

Here is a basic example:

~~~ {.haskell}
main :: IO ()
main = putStrLn "That was easy!"
~~~
```

but it doesn't work, i get:
```
stack: WARNING! Parse error
stack: WARNING! Missing or unusable stack options specification
stack: WARNING! Using runghc without any additional stack options
Test.lhs line 12: unlit: No definitions in file (perhaps you forgot the '>'s?)
phase `Literate pre-processor' failed (exitcode = 1)
```

i'm not sure if i'm missing something, because running it directly works:

```
stack --install-ghc runghc --package markdown-unlit -- "-pgmL markdown-unlit" Test.lhs
```

thoughts?

**Comment by silky** [comment]
nevermind, my bad, this works simply with bird tracks on the second line:

```
#!/usr/bin/env stack
> -- stack --install-ghc runghc --package markdown-unlit -- "-pgmL markdown-unlit"

# nifty-library: Do nifty things (effortlessly!)

Here is a basic example:

```haskell
main :: IO ()
main = putStrLn "That was easy!"
```
```

**Comment by newhoggy** [comment]
How did you get this to work?

I got this:

    10:05 $ cat ./Example.lhs
    #!/usr/bin/env stack
    > --install-ghc runghc --package markdown-unlit -- "-pgmL markdown-unlit"
    
    # nifty-library: Do nifty things (effortlessly!)
    
    Here is a basic example:
    
    ```haskell
    main :: IO ()
    main = putStrLn "That was easy!"
    ```
    
    10:06 $ ./Example.lhs
    stack: WARNING! Parse error
    stack: WARNING! Missing or unusable stack options specification
    stack: WARNING! Using runghc without any additional stack options
    
    Example.lhs:3:1: error: parse error on input ‘#’

**Comment by newhoggy** [comment]
Hmmm:

    10:17 $ cat ./example.lhs
    #!/usr/bin/env stack
    > --stack --install-ghc runghc --package markdown-unlit -- "-pgmL markdown-unlit"
    
    # nifty-library: Do nifty things (effortlessly!)
    
    Here is a basic example:
    
    ```haskell
    main :: IO ()
    main = putStrLn "That was easy!"
    ```
    
    10:17 $ ./example.lhs
    That was easy!

**Comment by mgsloan** [comment]
@newhoggy I'm surprised that `--stack --install-ghc ...` works, but yes, it's expected that you'd need `-- stack --install-ghc ...`

**Comment by 0atman** [comment]
This doesn't work for me, in 2020 :wave: 

```haskell
#!/usr/bin/env stack
> --stack --install-ghc runghc --package markdown-unlit -- "-pgmL markdown-unlit"

# nifty-library: Do nifty things (effortlessly!)

Here is a basic example:

```haskell
main :: IO ()
main = putStrLn "That was easy!"
``
```
(only two closing backticks for formatting, but my file has 3)

Running this yields:

```
./hask.lhs

hask.lhs:4:1: error: parse error on input ‘#’
  |
4 | # nifty-library: Do nifty things (effortlessly!)
  | ^
```

**Comment by 0atman** [comment]
Running directly does work:

```
stack --install-ghc runghc --package markdown-unlit -- "-pgmL markdown-unlit" hask.lhs
That was easy!
```
