### ISSUE TITLE
`stack upload` ought to reject uploading packages with the default synopsis/description boilerplate

### ISSUE THREAD

**Issue by hvr** [commercialhaskell/stack#2786]
I've notice that  users keep uploading packages to Hackage without noticing they didn't properly fill out the `synopsis` and `description` fields, e.g. the most recent one

https://hackage.haskell.org/package/haskelisp-0.1.0.0

but that's not the only one, the Hackage index is full of such examples. If you don't believe me I can produce a list of several such incidents. Point being, it's becoming a problem and affects the quality and perception of Hackage.

The other day [tried to explain how synopsis/description/README relate to each other and how they interact with tooling](https://mail.haskell.org/pipermail/haskell-cafe/2016-November/125541.html) as there appears to be misconceptions about it; and consequently, I suggest that `stack upload` prevents uploading to Hackage when the `synopsis`/`description` hasn't been altered from its default placeholder values that Stack appears to fill in.

Thanks

----

PS: I even found a few such incidents in the latest Stackage snapshots such as e.g.

![say](https://cloud.githubusercontent.com/assets/285533/20640335/557f5b12-b3db-11e6-8827-efb5171873e0.png)

**Comment by kadoban** [comment]
Would it be a better idea to just change the template(s) so that the synopsis and description aren't already filled in? We could have commented-out example lines so the user must go in and put in real data there.

**Comment by hvr** [comment]
That would work too (that's basically what `cabal init` does). And btw, it appears that stack also pre-fills github urls in the style of `http://github.com/githubuser/$PKGNAME` for homepage and git repo locations, as those are showing up surprisingly often on packages belonging to different maintainers...

**Comment by lwm** [comment]
Following @kadoban's recommendation and submitted https://github.com/commercialhaskell/stack-templates/pull/91.

**Comment by mgsloan** [comment]
Leaving default synopsis / description out of the templates should do the trick - closing.
