### ISSUE TITLE
Feature request: An option to load stack interpreter script in ghci

### ISSUE THREAD

**Issue by psibi** [commercialhaskell/stack#2788]
Say, I have a haskell script like this:
```
#!/usr/bin/env stack
{- stack
     --resolver lts-6.24
     ghci
     --package yesod-core
     --package text
-}

main = print 3
```

Now, I want stack to start gchi and load the related packages and the functions defined in that file.
Something like this:

```
stack --loadfile ~/hello.hs
```

Use case: While developing the script using stack, I sometimes would like to load it in ghci and inspect it's type, execute the function etc.

**Comment by harendra-kumar** [comment]
How about using `exec ghci` instead:

```
#!/usr/bin/env stack
{- stack
     --resolver lts-6.24
     exec ghci
     --package yesod-core
     --package text
-}

main = print 3
```

I had enabled this use case a while back.

**Comment by harendra-kumar** [comment]
This does not seem to be documented in the user guide though. It will be nice to make it more discoverable.

**Comment by psibi** [comment]
Thanks, that's exactly what I want. In fact, I read the documentation to see if something like that was available. I will leave this issue open untill someone adds this up in the documentation (or I will send a PR by this weekend.)

**Comment by psibi** [comment]
Closing the issue as the docs have been updated.
