### ISSUE TITLE
Building project dependent on gtk2hs fails on lts-7.8 and later

### ISSUE THREAD

**Issue by fujiyan** [commercialhaskell/stack#2795]
### General summary
Building project dependent on glib fails on lts-7.8 and later after Cabal becomes 1.24.1.0.

### Steps to reproduce

1. Add glib to a project's .cabal file
('gtktest' is the project name.)
```
    build-depends:       base
                       , gtktest
                       , glib

```
2. Run following commands

```
    stack install gtk2hs-buildtools
    stack build

```

### Expected

I expected that the build will succeed.

### Actual

The following error occurred
verbose : [failure.txt](https://gist.github.com/fujiyan/973a506b0e30aef429fed24261134b65)
```
...

2016-11-17 22:07:54.899952: [debug] Getting Cabal package version
@(Stack\GhcPkg.hs:171:5)
2016-11-17 22:07:54.900952: [debug] Run process: C:\Users\foo\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc-pkg.EXE --no-user-package-db field --simple-output Cabal version
@(System\Process\Read.hs:277:3)
2016-11-17 22:07:54.900952: [debug] Getting global package database location
@(Stack\GhcPkg.hs:54:5)

...

[debug] Ignoring package Cabal due to wanting version 1.24.1.0 instead of 1.24.0.0
@(Stack\Build\Installed.hs:196:5)

...

--  While building package glib-0.13.4.1 using:
  C:\Users\foo\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.EXE --make -odir C:\Users\foo\AppData\Local\Temp\stack5512\glib-0.13.4.1\.stack-work\dist\b7fec021\setup -hidir C:\Users\foo\AppData\Local\Temp\stack5512\glib-0.13.4.1\.stack-work\dist\b7fec021\setup -i -i. -package=Cabal-1.24.0.0 -clear-package-db -global-package-db -package-db=C:\sr\snapshots\a78c6a89\pkgdb C:\Users\foo\AppData\Local\Temp\stack5512\glib-0.13.4.1\Setup.hs -o C:\Users\foo\AppData\Local\Temp\stack5512\glib-0.13.4.1\.stack-work\dist\b7fec021\setup\setup
Process exited with code: ExitFailure 1
Logs have been written to: C:\Users\foo\Documents\Files\Haskell\gtktest\.stack-work\logs\glib-0.13.4.1.log

    [1 of 1] Compiling Main             ( C:\Users\foo\AppData\Local\Temp\stack5512\glib-0.13.4.1\Setup.hs, C:\Users\foo\AppData\Local\Temp\stack5512\glib-0.13.4.1\.stack-work\dist\b7fec021\setup\Main.o )
    
    C:\Users\foo\AppData\Local\Temp\stack5512\glib-0.13.4.1\Setup.hs:8:29: error:
        窶｢ Couldn't match expected type ‘Distribution.Simple.UserHooks.UserHooks’
                      with actual type ‘Cabal-1.24.1.0:Distribution.Simple.UserHooks.UserHooks’
          NB: ‘Cabal-1.24.1.0:Distribution.Simple.UserHooks.UserHooks’
                is defined in ‘Distribution.Simple.UserHooks’
                    in package ‘Cabal-1.24.1.0’
              ‘Distribution.Simple.UserHooks.UserHooks’
                is defined in ‘Distribution.Simple.UserHooks’
                    in package ‘Cabal-1.24.0.0’
        窶｢ In the first argument of ‘defaultMainWithHooks’, namely
            ‘gtk2hsUserHooks’
          In the expression: defaultMainWithHooks gtk2hsUserHooks
          In an equation for ‘main’:
              main = defaultMainWithHooks gtk2hsUserHooks

```

I thought that Cabal-1.24.0.0 in the ghc-8.0.1 global package was causing problems, and succeeded building it after installing Cabal-1.24.1.0 in ghc 's global package .

`
stack exec -- ghc-pkg update [Cabal-1.24.1.0.conf]
`
```

C:\Users\foo\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\lib\package.conf.d
    Cabal-1.24.1.0
...

```

verbose : [success.txt](https://gist.github.com/fujiyan/973a506b0e30aef429fed24261134b65)

### Stack version

```
Version 1.2.0, Git revision 123819b7d65df2ad7fe63fb5eb39a98536acb5f3 (4055 commits) x86_64 hpack-0.14.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository
(Windows 64-bit Installer)

**Comment by Blaisorblade** [comment]
I took a (rather inconclusive) look.
I first guessed that lack of support for custom-setup bites again, but the offending build command has `-package=Cabal-1.24.0.0 -clear-package-db -global-package-db`. Then, I expected the problem might be that `-hide-all-packages` is not in there, and it can't be till we support `custom-setup`. But then it seems this would hit any package with a non-default `Setup.hs`!?

FWIW, the failing `glib-0.13.4.1` has the following snippet in [its cabal file](https://github.com/gtk2hs/gtk2hs/blob/1a934b1131247f7778e35e964f46e67504e3a855/glib/glib.cabal#L33-L36), which is fine with any `Cabal-1.24.*`:

```
custom-setup
  setup-depends: base >= 4.6,
                 Cabal >= 1.24 && < 1.25,
                 gtk2hs-buildtools >= 0.13.2.0 && < 0.14
```

**Comment by barryfm** [comment]
It's been two months and Stack LTS has progressed to 7.14.

How should I build "glib", "gtk", etc with Stack?  Since they are in the list of Stack supported packages, I must be missing something.  I've tried explicitly installing Cabal-1.24.0.0 and Cabal-1.24.2.0, without any effect.

**Comment by Blaisorblade** [comment]
> Since they are in the list of Stack supported packages, I must be missing something

While I can't fully answer, I expect you're likely not missing much.

I'm not 100% sure what's going on, and how Stackage manages to build those packages, but `stack build/install` is the documented API for those packages too.
There are known stack issues with custom-setup, which happen to only affect gtk2hs-based projects, like #2515 and #2094 (see https://github.com/commercialhaskell/stack/issues/2094#issuecomment-221758288 for an old workaround).

> I've tried explicitly installing Cabal-1.24.0.0 and Cabal-1.24.2.0, without any effect.

Beware @fujiyan had to install a newer Cabal in the GHC global package repository, which is destructive and tricky. If that breaks things, be ready to reinstall the involved GHC.
I can't provide tested step-by-step instructions. If you understand what that command entails, there's a chance something like `stack --resolver lts-7.14 exec -- cabal install --global Cabal-1.24.2.0` could work.

> I thought that Cabal-1.24.0.0 in the ghc-8.0.1 global package was causing problems, and succeeded building it after installing Cabal-1.24.1.0 in ghc 's global package .

Pinging @mgsloan on this.

**Comment by SheliakLyr** [comment]
@barryfm @fujiyan Try:

`
stack setup --upgrade-cabal
`

This command solved the problem for me. I'm using lts-7.14.

**Comment by barryfm** [comment]
Thanks @SheliakLyr, this works for me also.  It seems like something that should be mention in the stack
build instructions.

**Comment by fujiyan** [comment]
@Blaisorblade @barryfm @SheliakLyr, I really appreciate your help.
Since I also confirmed that it will work, I close this issue.
I wish the Stack community's further success.
