### ISSUE TITLE
Stack won't resolve shared `.so` files on OS X?

### ISSUE THREAD

**Issue by o1lo01ol1o** [commercialhaskell/stack#2798]
Sorry for the question-post in the issue-tracker, but I've gotten no love on [stackoverflow](http://stackoverflow.com/questions/40713673/force-stack-to-look-for-so-files-instead-of-dylib-on-os-x), `freenode #haskell-stack`, or fp `#haskell` slack.  

See above linked, but the short of it is that have a `_.so` shared object on OS X and stack can't find it or the linked `_.so` files because it looks for `_.dylib`.  

Is there any way to change that?

Thanks.

**Comment by Blaisorblade** [comment]
I answered you on StackOverflow—feel free to answer there. I hope you don't mind if I close the issue. I've corrected myself after reading http://stackoverflow.com/a/2339910/53974, but that confirms that Stack (or rather, GHC itself) should *not* attempt linking against `.so` files.
