### ISSUE TITLE
Feature request: provide a way to run tests for all packages even if some tests fails

### ISSUE THREAD

**Issue by qnikst** [commercialhaskell/stack#280]
In a setup with many packages in may be useful to be able to run tests for all the packages that could be built, even if some tests are failing. This may be useful in cases where packages depend on another in complicated way and it worth knowing all breakages, not just the first one. Also it may be useful for reports and in cases if there's a test that could not be fixed due to it's complexity or rareness. 

If it's not hard I can implement that myself, but I an agreement that this feature is needed, and possibly pointers to relevant pieces of code.

**Comment by chrisdone** [comment]
Personally I prefer failing early -- it bugs me that `cabal install` will continue trying to build packages after one failed, wastes my time. But as an option this could be good?

**Comment by qnikst** [comment]
Of cause this should be optional, I'm also prefer this only for special kinds of projects.

**Comment by snoyberg** [comment]
If we figure out a good solution to #283, then hopefully this kind of option will be trivial to implement. As it stands, doing this well would be very difficult.

**Comment by qnikst** [comment]
Closed via #283
