### ISSUE TITLE
Bump stack dependency versions

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack#2803]
As reported by stackage-curator:

aeson-1.0.2.1 (Adam Bergmark <adam@bergmark.nl> @bergmark) is out of bounds for:
- [ ] stack-1.2.0 (>=0.8.0.2 && < 0.10 || ==0.11.*). Emanuel Borsboom <manny@fpcomplete.com> @borsboom. @commercialhaskell. Used by: library

mono-traversable-1.0.1 is out of bounds for:
- [x] stack-1.2.0 (>=0.10.2 && < 0.11). Emanuel Borsboom <manny@fpcomplete.com> @borsboom. @commercialhaskell. Used by: test-suite

store-0.3 is out of bounds for:
- [x] stack-1.2.0 (>=0.2.1.0 && < 0.3). Emanuel Borsboom <manny@fpcomplete.com> @borsboom. @commercialhaskell. Used by: library, test-suite

template-haskell-2.11.0.0 is out of bounds for:
- [x] stack-1.2.0 (>=2.10.0.0 && < 2.11). Emanuel Borsboom <manny@fpcomplete.com> @borsboom. @commercialhaskell. Used by: library, test-suite

unicode-transforms-0.2.0 (Harendra Kumar <harendra.kumar@gmail.com> @harendra-kumar) is out of bounds for:
- [x] stack-1.2.0 (==0.1.*). Emanuel Borsboom <manny@fpcomplete.com> @borsboom. @commercialhaskell. Used by: library

**Comment by mgsloan** [comment]
Other than the aeson dependency, these are already resolved in HEAD.

**Comment by mgsloan** [comment]
Once this PR is merged - https://github.com/commercialhaskell/stack/pull/2815 - we'll support the new aeson as well!

**Comment by lwm** [comment]
Well, I think we've moved on from these bounds issues (Stack is still blocked on Stackage though).
