### ISSUE TITLE
Use multiple compilers/compiler versions: GHC, GHCJS, others

### ISSUE THREAD

**Issue by agocorona** [commercialhaskell/stack#2807]
My concrete need is to compile a project both with GHC and GHCJS, but this feature request can be generalized.  Little more to say. The build flags in the cabal file would generate server and browser code using the same stack.yaml file.

Currently it is necessary to have two separate stack.yaml file. This is not optimal. In particular it disables the great advantage of building and running web programs in the command line.

**Comment by mgsloan** [comment]
This actually can already be achieved by the `--compiler` flag to stack.  However, you do need to specify the full ghcjs version.

**Comment by agocorona** [comment]
I mean to build the project with two or more compilers instead of one in a single build. I know that I can choose the compiler. What I would need is the option to specify two or more compiler options:
-- compiler  ghc......
-- compiler  ghcjs...
.

**Comment by mgsloan** [comment]
I see!  Unfortunately, I think this is out of scope for stack (can't add everything), so closing as wontfix.
