### ISSUE TITLE
Don't do anything to packages with no test/bench suite when running stack test/bench

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#281]
I ran `stack test` on a 25-package project and only a few of them have a test suite but of course it unregistered, configured, built, tested and installed them all. Perhaps we can have ones without a test suite be a no-op?

**Comment by snoyberg** [comment]
Should be handled by #283.

**Comment by snoyberg** [comment]
Please confirm on the 283-test-suite-fix branch.

**Comment by chrisdone** [comment]
Confirmed.
