### ISSUE TITLE
runghc/runhaskell command doesn't respect "packages" in stack.yaml

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#2814]
### Steps to reproduce

For example:

1. Setup some basic project with some dependency to other local project in stack.yaml and .cabal files
2. Run stack runghc Src\Main.hs --install-ghc

### Expected

If I run: stack runghc Src\Main.hs --install-ghc --package MyDependantPackage
it will work fine. But why do command-line need this if it's already in stack.yaml file of the project. It'll be best if there is stack.yaml file - it to be respected for dependency packages.

### Stack version

```
stack --version
Version 1.2.0 x86_64 hpack-0.14.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment]
If I understand correctly, the proposal is to build all of the dependencies of local packages before `runghc` executes?  This could add unnecessary overhead for packages the script does not depend on.

The necessity of `--package` is to specify additional packages to install before running the script.  These may or may not be dependencies of your local packages.

>  It'll be best if there is stack.yaml file - it to be respected for dependency packages.

If the stack.yaml specifies a version for `MyDependentPackage`, it should be respected by this invocation.

**Comment by varosi** [comment]
There is section "packages:" where I add my additional packages to be built. And I ran stack from directory where stack.yaml is situated. So you mean that stack.yaml is readed actually, but not all sections from it are respected (particularly "packages:" section)?

**Comment by mgsloan** [comment]
If you run `stack build`, then the packages in that section will be available to runghc

**Comment by varosi** [comment]
Thank you!
