### ISSUE TITLE
stack setup fails on Windows 10

### ISSUE THREAD

**Issue by Tritlo** [commercialhaskell/stack#2816]
### General summary/comments (optional)

Stack setup fails for me with a weird error, saying that `Rts.h` is missing.

### Steps to reproduce

For example:

+ Download the 64-bit Windows binary
+ Open PowerShell and run `stack setup`

### Expected

`stack setup` succeeds and installs the latest GHC.

### Actual

What actually happened.

If you suspect that a stack command misbehaved, please include the output of that command in `--verbose` mode.
If the output is larger than a page please paste the output in a [Gist](https://gist.github.com/).

```
PS C:\Users\MatthíasPáll\AppData\Local\Temp> stack setup
Run from outside a project, using implicit global project config
Using resolver: lts-7.11 from implicit global project's config file: C:\sr\global-project\stack.yaml
The GHC located at C:\Users\Matth├¡asP├íll\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.EXE failed to compile a sanity check. Please see:

    http://docs.haskellstack.org/en/stable/install_and_upgrade/

for more information. Exception was:
Running C:\Users\Matth├¡asP├íll\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.1\bin\ghc.EXE C:\Users\MATTHA~1\AppData\Local\Temp\stack-sanity-check89976\Main.hs -no-user-package-db in directory C:\Users\MATTHA~1
\AppData\Local\Temp\stack-sanity-check89976\ exited with ExitFailure 1

[1 of 1] Compiling Main             ( C:\Users\MATTHA~1\AppData\Local\Temp\stack-sanity-check89976\Main.hs, C:\Users\MATTHA~1\AppData\Local\Temp\stack-sanity-check89976\Main.o )
Linking C:\Users\MATTHA~1\AppData\Local\Temp\stack-sanity-check89976\Main.exe ...

C:\Users\MATTHA~1\AppData\Local\Temp\ghc89108_0\ghc_4.c:1:17: fatal error: Rts.h: No such file or directory
compilation terminated.
`gcc.exe' failed in phase `C Compiler'. (Exit code: 1)
```

### Stack version

```
PS C:\sr> stack --version
Version 1.2.0, Git revision 123819b7d65df2ad7fe63fb5eb39a98536acb5f3 (4055 commits) x86_64 hpack-0.14.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository (Windows 64-bit)

**Comment by mgsloan** [comment]
Based on the unicode munging in the output - C:\Users\Matth├¡asP├íll - I'm guessing this is a unicode issue.  One option might be to upgrade to the unreleased stack version, and use the new `local-programs-path` in stack.yaml.  Unfortunately, `stack upgrade --git` is unlikely to work unless you have ghc-7.10 already installed.

**Comment by mpilgrem** [comment]
I am closing this issue due to the passage of time and no similar reports for modern versions of Stack.
