### ISSUE TITLE
Relationship between stack and .cabal files unclear

### ISSUE THREAD

**Issue by johnynek** [commercialhaskell/stack#282]
In the FAQ it implies that you will need to write .cabal files for your project, but it is not 100% clear exactly how stack uses these. I guess stack is giving you more control over how .cabal dependencies are resolved, and that's pretty much it, right?

It would be nice to clear the relationship between stack, cabal, and .cabal files more explicitly (and earlier) in the FAQ.

**Comment by snoyberg** [comment]
Can you look at [the terminology section](https://github.com/commercialhaskell/stack/wiki/Architecture#terminology) of the architecture page, specifically the package vs project distinction, and see if that clears things up? If so, it would be great to link to it from the FAQ

**Comment by bitemyapp** [comment]
I don't think "more control" is accurate, as it's narrowing what must be determined dynamically from constraints to make things simpler and less churn-y through the reliance on a mixture of Stackage/LTS snapshots and concretely specified extra dependencies. It's also a big UX sweep of papercuts associated primarily with cabal-install specifically.

I think a solver backend is being explored (proper SAT/SMT I hope is what comes out of it), but right now, that's not provided for.

@snoyberg I looked at the terminology. It doesn't really explain the relationship between Stack and Cabal.

This would be a good documentation fix-up ticket for someone wanting to try staking an explanation into the ground, but whomever does it will need to either already understand what's going on or pester somebody that does.

**Comment by snoyberg** [comment]
Well, I'll write up some short thoughts here, perhaps @johnynek can ask for clarification and then update the documentation with something that answers his questions?

* Cabal-the-library is used by stack to build your Haskell code
* cabal-install (the executable) is not used at all by stack
* A .cabal file is provided for each package, and defines all package-level metadata just like it does in the cabal-install world: modules, executables, test suites, etc. No change at all on this front.
* A stack.yaml file references a number of packages, and provides information on where dependencies come from

Does that clarify any questions you have? What other things are still unclear?

**Comment by johnynek** [comment]
@snoyberg yes this clears up most of my questions on the matter. Thanks! Maybe being slightly more precise, I'd suggest "A stack.yaml file references 1 or more packages, ..."

One last one (though I should experiment and answer, but hey, the FAQ could also explain it): does the stack templating for new projects include setting up an skeleton .cabal, or is that done otherwise by the user?

**Comment by snoyberg** [comment]
The exact process for project initialization is still TBD, there's an issue tracking the details at https://github.com/commercialhaskell/stack/issues/253. Currently, it just generates a stack.yaml based on your existing .cabal file.

**Comment by johnynek** [comment]
Added to the FAQ: https://github.com/commercialhaskell/stack/wiki/FAQ/87ff7a3e8cf388b07e211cf44c65eb3926a4e60f

**Comment by bitemyapp** [comment]
@johnynek :clap:

**Comment by snoyberg** [comment]
Thank you!
