### ISSUE TITLE
Stack hoogle --rebuild is broken in 1.3.1

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/stack#2829]
### General summary/comments (optional)
After upgrading to version 1.3.1 Hoogle rebuild option gives error.

### Steps to reproduce
Run `stack hoogle --rebuild`

### Expected
Rebuild

### Actual
Error:`
Rebuilding database ...
readelf: Error: '/home/rik/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/ghc_0AG9TOjDEtx4Ji3wSwHOBe/libHSghc-7.10.3-0AG9TOjDEtx4Ji3wSwHOBe-ghc7.10.3.a': No such file
readCreateProcess: readelf "--debug-dump=info" "--dwarf-depth=1" "/home/rik/.stack/programs/x86_64-linux/ghc-7.10.3/lib/ghc-7.10.3/ghc_0AG9TOjDEtx4Ji3wSwHOBe/libHSghc-7.10.3-0AG9TOjDEtx4Ji3wSwHOBe-ghc7.10.3.a" (exit 1): failed
`

What actually happened.
Nothing, only error. Same problem for ghc 8.0.1

### Stack version

```
$ stack --version
Version 1.3.1, Git revision 737ee751654cba4b2547b50628c9a5a78ddc6f8b x86_64 hpack-0.15.0
```

### Method of installation
stack upgrade --git

**Comment by sjakobi** [comment]
I see a very similar issue with `stack haddock`:

```
~/tmp $ stack new haddock-issue
~/tmp $ cd haddock-issue/
~/t/haddock-issue $ stack haddock
Warning: File listed in haddock-issue.cabal file does not exist: README.md
readelf: Fehler: '/home/simon/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/ghc-8.0.1/libHSghc-8.0.1-ghc8.0.1.a': Keine solche Datei
readCreateProcess: readelf "--debug-dump=info" "--dwarf-depth=1" "/home/simon/.stack/programs/x86_64-linux/ghc-8.0.1/lib/ghc-8.0.1/ghc-8.0.1/libHSghc-8.0.1-ghc8.0.1.a" (exit 1): failed
~/t/haddock-issue $ stack --version
Version 1.3.1, Git revision 737ee751654cba4b2547b50628c9a5a78ddc6f8b (dirty) (4364 commits) x86_64 hpack-0.15.0
```

**Comment by borsboom** [comment]
Also similar: #2851.  All appear to be related to the state tracking for whether different versions of packages have been built (haddocks, profiling, dwarf).

**Comment by borsboom** [comment]
ping @SASinestro
