### ISSUE TITLE
--extra-lib-dirs should accept relative paths

### ISSUE THREAD

**Issue by YPares** [commercialhaskell/stack#2830]
What is the rationale behind forbidding relative paths in the stack.yaml for `extra-lib-dirs`?
I often need to add a path to a local C lib, and that's not convenient to have to build it via:
`stack build --extra-lib-dirs $PWD/my/path`

**Comment by lwm** [comment]
https://github.com/commercialhaskell/stack/commit/679e3eda1ca07eb6f4dfb2dcd498ec8eeabb1123 looks relevant. /cc @sjakobi.

**Comment by sjakobi** [comment]
> 679e3ed looks relevant. /cc @sjakobi.

Right, that probably wasn't a good idea. I think it would be nice to have something stronger than a `FilePath` in the option parser, and working with `Path Abs Dir` internally is also desirable, but of course that shouldn't come at the cost of user convenience.

**Comment by mgsloan** [comment]
Implemented!

This was a bit tricky, because we want these paths to be relative to the config file.  Similarly, for CLI args it is relative to current work dir.  Now that this info is plumbed through, it will be straightforward to add support for relative paths elsewhere in configuration.
