### ISSUE TITLE
`stack image container` does not tag the resulting container

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#2832]
```
$ stack image container
Sending build context to Docker daemon 73.52 MB
Step 1 : FROM fpco/stack-run
 ---> 1d7ea82b1782
Step 2 : ADD ./ /
 ---> Using cache
 ---> 638c0c70fde7
Successfully built 638c0c70fde7
Sending build context to Docker daemon 73.52 MB
Step 1 : FROM app
 ---> 638c0c70fde7
Step 2 : ENTRYPOINT /usr/local/bin/app-backend
 ---> Using cache
 ---> 75cf3bd59e58
Step 3 : CMD
 ---> Using cache
 ---> 1b30971e5d3c
Successfully built 1b30971e5d3c
```

It's the temporary docker image that is called `app`, not the one with the correct entrypoint.

This is the `stack.yaml` section for the image:

```
image:
  containers:
  - name: app
    base: fpco/stack-run
    add:
      production/app-backend/conf/: /etc/accounting
    entrypoints:
    - app-backend
```

**Comment by alexanderkjeldaas** [comment]
To clarify *`Step 1 : FROM app`* is the "wut?" thing here.  The `1b30971e5d3c` container should be `app`, not `638c0c70fde7`.

**Comment by ketzacoatl** [comment]
While th issue about tags seems separate, I was curious about your question about there being two image builds so I went looking through the source. I think https://github.com/commercialhaskell/stack/blob/master/src/Stack/Image.hs#L54-L179 makes that clear - the first image is built from the `base` image, and has all the static assets, and then there is an extension of that "general purpose" image with entrypoints.

Going back to the original issue about tagging, can you confirm which image is tagged and what you get for a tag? I would expect the `1b30971e5d3c` image would have `app:latest`, is that what you see?

**Comment by alexanderkjeldaas** [comment]
I get it now.  Actually `638c0c70fde7` is `app:latest`, but `1b30971e5d3c` is called `app-app-backend:latest`.
