### ISSUE TITLE
Stack doesn't seem to be able to notice updated package info on Hackage

### ISSUE THREAD

**Issue by mrkkrp** [commercialhaskell/stack#2836]
Suppose I have a package `X` which I want to add to `extra-deps`, but it has conflicting dependencies with my some other package in `extra-deps`. I have updated lower version bound on Hackage (for `aeson` in my case to allow `0.9`) for that package, but `stack` still tells me that

```
In the dependencies for X-0.1.0:
    aeson-0.9.0.1 must match >=0.11 && <1.1 (latest applicable is 1.0.2.1)
needed due to some-project-0.1.0.0 -> X-0.1.0
```

I.e. it still thinks that `X` requires at least `0.11`. Several hours passed, it does not pick it up.

**Comment by phadej** [comment]
have you run `stack update` (note it takes some time to changes to propagate)?

**Comment by mrkkrp** [comment]
No, I'll try that.

**Comment by mrkkrp** [comment]
Seems to work, closing.
