### ISSUE TITLE
feedback on files being processed by build-tools 

### ISSUE THREAD

**Issue by PierreVDL** [commercialhaskell/stack#2843]
Calling "stack build" currently doesn't report the files that are being processed by build-tools such as happy and alex.
When multiple files are processed by build-tools,
it is no longer clear to which file the reported errors and/or warnings belong.

Could the files being processed by build-tools be echoed,
such that it becomes clear to which file a message belongs?

**Comment by PierreVDL** [comment]
To give an example:
I prefer
```
alex sys/front/TxsAlex.x
alex sys/smt/RegexAlex.x
alex sys/smt/SMTAlex.x
alex sys/smt/SMTStringAlex.x
happy sys/front/TxsHappy.y
unused rules: 4
unused terminals: 3
happy sys/smt/RegexPosixHappy.y
happy sys/smt/RegexSMTHappy.y
shift/reduce conflicts:  15
happy sys/smt/SMTHappy.y
happy sys/smt/SMTStringHappy.y
```
over the current output
```
unused rules: 4
unused terminals: 3
shift/reduce conflicts:  15
```

**Comment by mgsloan** [comment]
Hi, sorry for the delay!  Running build tools is the responsibility of [cabal](https://github.com/haskell/cabal), perhaps report an issue there on the subject?
