### ISSUE TITLE
Add lint command

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#285]
Should be a way to point out which modules/libraries are declared in .cabal but not actually used. Perhaps run automatically on upload? This information can be determined by generating GHC make files. There is already a tool to do part of this, but I haven't had much success with it.

**Comment by mgsloan** [comment]
More things that a lint command might do

* Run hlint

* Let you know when test / benchmark / executable stanzas also are building the library (see #1008)

* Tell you when build-depends are unused

**Comment by chrisdone** [comment]
Also because we're able to run `Setup.hs build` directly of a project, we get the compile warnings messages which puts us in a position to use the compiler for linting.

This would let us eliminate unused package dependencies from a cabal file by simply removing one by one and seeing if the build succeeds.

**Comment by ndmitchell** [comment]
I think generating a Makefile with the right settings gives you a list of package dependencies, so you don't even need to repeatedly compile with the missing modules.

Despite being the author of hlint, I would not recommend that `stack lint` does an `hlint` - this ticket was about linting the `.cabal` file (which `stack` in some ways understands and consults), not the source. Of course, having `stack hlint` (or even `stack lint --hlint`) would be pretty cool, especially if it installed `hlint` for the user first - but given my biased view point, I leave it up to others to suggest if they want it.

**Comment by sjakobi** [comment]
Should this command also encompass the functionality of `cabal check`, i.e. make sure that a package satisfies Hackage requirements?

**Comment by mgsloan** [comment]
Yeah, should probably do the same checks that `stack upload` does.

**Comment by snoyberg** [comment]
Let's defer this kind of functionality to external tools like weeder.
