### ISSUE TITLE
stack config can't set system-ghc true without a compiler

### ISSUE THREAD

**Issue by unhammer** [commercialhaskell/stack#2852]
### General summary/comments (optional)
stack config can't set system-ghc true without a compiler

### Steps to reproduce
On Ubuntu 16.04,
* Install ghc-7.8.4 from http://ppa.launchpad.net/hvr/ghc/ubuntu 
* `export PATH="/opt/ghc/7.8.4/bin:$PATH"`
* `stack config set system-ghc --global true`

### Expected

~/.stack/config.yaml should say system-ghc:true

### Actual

stack complains 

```
No compiler found, expected minor version match with ghc-7.8.4 (x86_64) (based on resolver setting in /home/kiwibird/src/app/stack.yaml).
To install the correct GHC into /home/kiwibird/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```

### Stack version

```
$ stack --version
Version 1.3.0, Git revision 99b910d3c8e183aa376cb1e6f0341d86aed6d00e (4372 commits) x86_64 hpack-0.15.0
```

### Method of installation

* Official binary from fpcomplete's apt repo

**Comment by mgsloan** [comment]
This actually turned out to be a trivial fix!

**Comment by LukeHoersten** [comment]
@mgsloan was the default changed here? Why does this flag need to be set now instead of stack automatically searching for my system ghc first?
