### ISSUE TITLE
get-stack.sh installs wrong binary on ARM

### ISSUE THREAD

**Issue by blender** [commercialhaskell/stack#2856]
### General summary/comments (optional)

Generic Install instruction for linux installs wrong binary on ARM

### Steps to reproduce

Run `curl -sSL https://get.haskellstack.org/ | sh` 

### Expected

Command should install bindist for ARM

### Actual

Incompatible architecture binary was installed 

### Stack version

Irrelevant

### Method of installation

This ticket is about the method of installation

**Comment by borsboom** [comment]
It does appear that the script assumes an x86 architecture.

**Comment by blender** [comment]
@borsboom , yes I have submitted a pull request #2857  to fix that.
