### ISSUE TITLE
"stack config set system-ghc --global true" needs "--system-ghc" flag to work

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#2858]
`stack-1.3.0` says that you can configure it to accept the system compiler by running 

    stack config set system-ghc --global true

..., but that command won't work when it's run inside of a stack project, because before stack sets that option it tries to detect the compiler -- and fails. So the command that actually needs to be run is:

    stack config --system-ghc set system-ghc --global true

**Comment by LukeHoersten** [comment]
Same issue here.

**Comment by borsboom** [comment]
This looks like a duplicate of #2852.

**Comment by borsboom** [comment]
@LukeHoersten To answer your question, the change in defaults was intentional.  See #2221.
