### ISSUE TITLE
Support of passing flags to arbitrary programs

### ISSUE THREAD

**Issue by PierreVDL** [commercialhaskell/stack#2868]
On haskell-stack different questions are asked to add arguments to particular programs.
See e.g. https://groups.google.com/forum/#!topic/haskell-stack/6sYk9V5IuNI
and https://groups.google.com/forum/#!topic/haskell-stack/9oKeSo-nz7U

Cabal states it can accept arguments to arbitrary programs : https://www.haskell.org/cabal/users-guide/installing-packages.html#programs-used-for-building
> --prog-options=options  Specify additional options to the program prog. Any program known to Cabal can be used in place of prog. For example: --alex-options="--template=mytemplatedir/". 

Can stack support this as well?

**Comment by lwm** [comment]
Don't think this is supported yet.

**Comment by mpilgrem** [comment]
@tiansivive, it is still an unfulfilled request. (Note to self: the modern Cabal link is https://cabal.readthedocs.io/en/stable/setup-commands.html#programs-used-for-building.)

**Comment by mpilgrem** [comment]
@tiansivive, I think the version of Stack in branch `fix2868` now adds what you are seeking to the command line. See #6083. I have reasoned that it works, but could you test that it actually solves your problem (or specify some minimal example that I could use to test it)?

If it does work, I'll merge it and then turn to adding something also to Stack's YAML configuration files separately.

**Comment by mpilgrem** [comment]
Re-opening issue, as I have realised that 9ebe1fc259592d98bf93f641823966b9dd22066a does not address the hash that ensures builds are reproducible. I'll address that separately.
