### ISSUE TITLE
--local-bin-path should warn if --copy-bins is not set

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/stack#2870]
I was confused that `--local-bin-path` doesn't work, but really I needed to pass `build --copy-bins`.

For UX reasons it's best to warn in such cases.

**Comment by lwm** [comment]
Ahoy there ;)

They're unrelated though? They are options for different commands.

Did your confusion start from here (Got from `stack build --help`)?

```
  --[no-]copy-bins  Enable/disable copying binaries to the local-bin-path (see 'stack path')
```

Oh, also, `--local-bin-path` is being deprecated, `local-bin` is taking it's place. So, we should probably update that help string as well.

**Comment by domenkozar** [comment]
@lwm I wanted to say setting `--local-bin-path` doesn't have effect until you invoke `stack build --copy-bins` or `stack install`
