### ISSUE TITLE
tensorflow/haskell#56

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#2872]
### General summary/comments (optional)

The haskell bindings for tensorflow are built in a docker container.  For me that fails as documented in tensorflow/haskell#56 

### Steps to reproduce

Build instructions documented https://github.com/tensorflow/haskell/blob/master/README.md

```
git clone --recursive https://github.com/tensorflow/haskell.git tensorflow-haskell
cd tensorflow-haskell
IMAGE_NAME=tensorflow/haskell:v0
docker build -t $IMAGE_NAME docker
# TODO: move the setup step to the docker script.
stack --docker --docker-image=$IMAGE_NAME setup
stack --docker --docker-image=$IMAGE_NAME test
```

The `stack  --docker --docker-image=$IMAGE_NAME setup` fails for me.  I am guessing that this could be a stack issue in the docker integration.

### Expected

munch munch profit

### Actual

see tensorflow/haskell#56

### Method of installation

`stack upgrade` from previous version to 1.3.0.

Ubuntu 16.04

**Comment by alexanderkjeldaas** [comment]
Actually this was a mixup of docker environments.  The docker environment was pointing to a remote docker swarm.

I guess there is an issue here - that `stack  --docker --docker-image=$IMAGE_NAME setup` should detect/warn about docker possibly not being able to bind mound from the local file system.

But this issue should be closed.

**Comment by nyck33** [comment]
@alexanderkjeldaas Can you explain how to fix this? I'm having similar problems.
