### ISSUE TITLE
stack ghci cannot find imported module in non-project local directory 

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2878]
Was looking into this: https://github.com/pushcx/stack-bug

The following worked, which surprised a user:

```
Prelude> :l Foo.hs Bar.hs 
[1 of 2] Compiling Bar              ( Bar.hs, interpreted )
[2 of 2] Compiling Foo              ( Foo.hs, interpreted )
Ok, modules loaded: Foo, Bar.
```

Just loading `Foo.hs` by itself does not with `stack ghci` whereas `ghci` does. Is there a good reason for this difference in behavior? If there isn't a strong reason I'd rather the difference be harmonized.

**Comment by bitemyapp** [comment]
User's workaround was `stack ghci --ghci-options -i.`.

**Comment by mgsloan** [comment]
Good point!  I've changed `stack ghci` to include the current work dir if the config contains no packages (like the global config).
