### ISSUE TITLE
Script interpreter can't add extra-deps to snapshot

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2879]
Following does not work:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-7.10 --install-ghc runghc --package turtle --package FailureT-15778.1

{-# LANGUAGE OverloadedStrings #-}

import Turtle

main = echo "Hello World!"
```

**Comment by lwm** [comment]
`FailureT-15778.1` isn't on [that Stackage LTS](https://www.stackage.org/lts-7.10/hoogle?q=FailureT-15778.1), so this is expected?

**Comment by bitemyapp** [comment]
That's my point, I specified the version. That's why I said `extra-deps` in the title.

**Comment by mgsloan** [comment]
The issue is actually that the script interpreter was running things with silent verbosity.  I've changed it to output error logging, so now the following is outputted:

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for FailureT-15778.1:
    mmtl must match -any, but the stack configuration has no specified version (latest applicable is 0.1)

You may also want to try the 'stack solver' command
Plan construction failed.
```

**Comment by bitemyapp** [comment]
@mgsloan eggscellent, thank you!
