### ISSUE TITLE
Multi-line script interpreter opener

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#2883]
In the book I am working on, I am going to be limited to either 43 or 59 columns. Accordingly, this script interpreter opener isn't going to work on a single line:

```
-- stack --resolver lts-6.27 --install-ghc runghc --package aeson --package raw-strings-qq
```

Is there a way for me to split it across lines? `\` didn't work.

**Comment by harendra-kumar** [comment]
Use a multiline haskell comment and write the comment whatever way you want.

```
{- stack 
... 
-}
```

**Comment by bitemyapp** [comment]
Ah, perfect!

```{-
stack --resolver lts-6.27 --install-ghc
      runghc --package aeson
      --package raw-strings-qq
-}
```

This worked great, thank you!

**Comment by harendra-kumar** [comment]
BTW, this was my first commit to stack a year ago!
