### ISSUE TITLE
No package names in haddock index

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#2886]
The package index generated by `stack haddock` does not contain the package names. The package names seem to be present for the packages distributed with ghc but not for the packages installed with stack.

Here's a screenshot of my `~/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/doc/index.html`. Notice the difference between, say, `BasicTypes` (distributed with ghc) and `Bio.Core` (from the `biocore` package, installed with stack from hackage).

![stack-haddock](https://cloud.githubusercontent.com/assets/24844/21567209/0a0bcfc4-ceb3-11e6-9356-6bf57548cb18.png)

It's been a while since I looked at haddock, but my guess is that it has a command line option to specify the package name that stack does not pass.

The practical significance of this is that it makes it harder to search the index page, especially for packages that are named differently from their modules.

### Stack version

```
$ stack --version
Version 1.3.3, Git revision 87068d8edb64e81f4062ae889472ef74452a2b97 (4441 commits) x86_64 hpack-0.15.0
```

### Method of installation

from git master

**Comment by mgsloan** [comment]
Hmm, not sure why that would be, considering we are essentially using `runhaskell Setup.hs haddock`, which should know about the package name / version.  I tried passing them in manually at https://github.com/commercialhaskell/stack/blob/1020a2f7f82967c4701526115e4e7c431f573b4c/src/Stack/Build/Execute.hs#L1306 with

```haskell
                                 ,"--haddock-options=--package-name=" ++ packageNameString (packageName package) ++ " --package-version=" ++ versionString (packageVersion package)
```

But no difference in the index :/

**Comment by snoyberg** [comment]
PR #3226 has been merged.

**Comment by feuerbach** [comment]
Thanks a lot!

**Comment by snoyberg** [comment]
Sure, thanks goes to @judah for figuring out the problem and writing the patch!
