### ISSUE TITLE
Backslash should NOT be appended in stack.yaml created on Windows

### ISSUE THREAD

**Issue by igrep** [commercialhaskell/stack#2887]
### Steps to reproduce

1. Run `stack init` for some multi-package-project on Windows.
    For example:
    ```
    $ git clone git clone https://github.com/haskell/haddock.git
    $ cd haddock
    $ stack init
    ```

### Expected

A stack.yaml like below should be created:

```yaml
# ... snip ...
packages:
- '.'
- haddock-api/
- haddock-library/
- haddock-test/
# ... snip ...
```

### Actual

```yaml
# ... snip ...
packages:
- '.'
- haddock-api\
- haddock-library\
- haddock-test\
# ... snip ...
```

#### Why this is bad:

Using backslash as the path separator causes a cryptic error like below, when **porting the stack.yaml file to non-Windows environment such as Linux.**

```
/home/yu/prg/foreign/haddock/haddock-api\: canonicalizePath: does not exist (No such file or directory)
```

### Stack version

```
$ stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 x86_64 hpack-0.15.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by lwm** [comment]
> causes a cryptic error

That error is not very cryptic?

However, I don't see why we output the `/` or `\` anyway, since it isn't necessary.
