### ISSUE TITLE
hs-source-dirs starting with `../` are not included in the -i<dir> arguments when using `stack ghci file.hs`

### ISSUE THREAD

**Issue by tallen-imvu** [commercialhaskell/stack#2895]
### Summary
`stack ghci <target file>` will correctly determine include directories using the cabal file's hs-source-dirs property unless the source directory starts with a `../`
`stack build` however deals with this correctly.

### Steps to reproduce

1. add a relative path to hs-source-dirs:
    ex:
          `hs-source-dirs:      . ../extra`

2. Add a module to the ../extra directory and import it in your main file
3. run command `stack build`
    everything should work
4. run command `stack ghci <path to main>`

### Expected

ghci launched with package loaded

### Actual

Error in compiling due to failing to load the extra module. Because it cannot find it.

running the `stack ghci` command with `--version` shows that the `../extra` directory is not being added to the list of `-i<directory>` flags passed to ghci.
If the module is moved to a directory that does not require a `../` prefix, then that directory is included properly.

### Stack version

```
$ stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0
```

### Method of installation

* static binary from https://www.stackage.org/stack/linux-x86_64-static

**Comment by mgsloan** [comment]
Hmm, I cannot reproduce the issue.  For me if I have

```
library
  hs-source-dirs:      src ../issue2895-extra
  exposed-modules:     Lib Huh
```

It works (`Huh.hs` is in `../issue2895-extra`).  Perhaps your module is not listed in `exposed-modules` / `other-modules`?

**Comment by tallen-imvu** [comment]
I put up a reproducing repo [here](https://github.com/tallen-imvu/stack-ghci-i)

**Comment by tallen-imvu** [comment]
Oh, there it is.
It is the `parseRelDir` on line 423 of src/Stack/Package.hs
Pull request incomming

**Comment by mgsloan** [comment]
Thanks for finding and fixing!!
