### ISSUE TITLE
Why was #2827 not included in v1.3.2?

### ISSUE THREAD

**Issue by xtendo-org** [commercialhaskell/stack#2896]
My colleagues are reporting me that the initial installation and run of Stack takes too long (described in #2780) which is a serious barrier to introduce Haskell into my company. Thankfully @snoyberg has made a Pull Request to switch the default backend to the tarball one to avoid the connectivity issue with GitHub. It has been merged about a month ago. But it wasn't included in v1.3.2 release.

I'm probably asking this because I have little idea about the development practice of Stack, but I see many other PRs that emerged later than #2827 now included in the official release. So, why was #2827 not included in v1.3.2? When will it be released? Will it be released at all? Is there anything I can do to help getting it released?

Thanks in advance.

**Comment by borsboom** [comment]
Yes, that PR will be included in v1.4.0.  v1.3.2 only cherry-picked some simple commits that fixed regressions that affected many people.
