### ISSUE TITLE
get-stack.sh script does not first apt-get update

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#2898]
Actions:

1. Spin up brand new Ubuntu 16.04 EC2 instance
2. Run the get-started script via `wget -qO- https://get.haskellstack.org/ | sh`

Expected:

All system packages will be installed

Actual:

I get an error message because I haven't yet run `apt-get update`, system package installation fails, but Stack installation succeeds. In order to get the necessary packages, I then need to either (1) manually `apt-get install` them, or delete `/usr/local/bin/stack` and rerun the script after running `apt-get update`. I would expect one of two behaviors to occur:

1. If system package installation fails, do not install the stack exe
2. If apt-get install fails, run apt-get update

I'm guessing the former is more practical, while the latter could be tweaked to _always_ run `apt-get update`

**Comment by borsboom** [comment]
Yeah, I think #1 with a friendly error message ("please run `apt-get update` and try again" or the equivalent for yum/dnf/apk) is the way to go.

**Comment by alexeyzab** [comment]
Hey there! I would like to try implementing this. Here's what I have so far, let me know if this is the right way to approach it. If it is, I'll go ahead and add similar functionality for yum/dnf/apk. Thanks!

**Comment by borsboom** [comment]
@alexeyzab That looks like the right approach to me!

**Comment by alexeyzab** [comment]
@borsboom Great! I've added similar warnings for other package managers.

**Comment by borsboom** [comment]
Fixed by #2909
