### ISSUE TITLE
Add entry to FAQ about how to use Stack with Travis

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#291]
Using Stack as part of one's favourite CI setup for open source software could do with a bit of documentation. Currently, Stack's own `.travis.yml` file isn't an example of best practice, because for various reasons it's currently `cabal-install` based rather than `stack` based. So we should document the best practice as a FAQ entry.

**Comment by gregwebs** [comment]
I added a placeholder answer to the FAQ (the answer for now is: don't do this yet).

**Comment by mboes** [comment]
The following works pretty well:

```
language: haskell

before_install:
  - wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
  - echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main' | sudo tee /etc/apt/sources.list.d/fpco.list
  - sudo apt-get update
  - sudo apt-get install stack -y

install:
  - stack setup

script:
  - stack test
```

The `before_install` lines are a copy/paste from the Downloads page.

@gregwebs any objection to me adding the above to the FAQ now while retaining the caveat you mentioned about `stack` being in beta?

**Comment by mboes** [comment]
Note that the `install:` step will benefit from #310 when that eventually happens.

**Comment by gregwebs** [comment]
Sounds good
