### ISSUE TITLE
stack setup --nix --upgrade-cabal fails

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#2911]
### Steps to reproduce

```
$ stack new foo
$ cd foo
$ stack --nix setup --upgrade-cabal
```

### Expected

For subsequent `stack build` in the local project to be built using the latest Cabal library. Or to display an error saying that `--upgrade-cabal` is not supported in conjunction with `--nix` (arguably the Cabal library should be set in a `shell.nix` file).

### Actual

```
[...]
/nix/store/cff78wmha1b363jkhxfsxp4vg1vyslz2-ghc-8.0.1/new-cabal:
createDirectory: permission denied (Read-only file system)
Exit code ExitFailure 1 while running ["/run/user/1000/stack-cabal-upgrade6275/Cabal-1.24.2.0/Setup","install"] in /run/user/1000/stack-cabal-upgrade6275/Cabal-1.24.2.0/
```

### Stack version

```
$ stack --version
Version 1.3.2 x86_64
```

cc @robinbb @YPares @facundominguez

**Comment by mboes** [comment]
Related: #2910.

**Comment by YPares** [comment]
Opened a PR for that: https://github.com/commercialhaskell/stack/pull/2912
