### ISSUE TITLE
Stack fails to build with profiling

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/stack#2917]
```
$ stack build --profile --executable-profiling --library-profiling
stack-1.3.3: build (lib + exe)
Preprocessing library stack-1.3.3...
In-place registering stack-1.3.3...
Preprocessing executable 'stack' for stack-1.3.3...
[2 of 2] Compiling Main             ( src/main/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/stack/stack-tmp/Main.p_o )
/home/syd/stack/src/main/Main.hs:121:10:
    cannot find normal object file ‘.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/build/stack/stack-tmp/Paths_stack.dyn_o’
    while linking an interpreted expression

--  While building package stack-1.3.3 using:
      /home/syd/stack/.stack-work/dist/x86_64-linux/Cabal-1.22.5.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.22.5.0 build lib:stack exe:stack --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

```
$ stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0
```

```
$ git rev-parse HEAD
c67b7f93c92294889574a8216edc724576657357
```

**Comment by tolysz** [comment]
`Cabal-1.22.5.0` ?? Could you upgrade cabal?

**Comment by NorfairKing** [comment]
$ cabal --version
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library 

Stack must have installed that version itself.

**Comment by lwm** [comment]
> How do I upgrade cabal?

I think that's `stack setup --upgrade-cabal` (can also be combined with `--reinstall`, (guessing!))

**Comment by NorfairKing** [comment]
@lwm, Sure I can do thata, but I shouldn't have to, right?

In any case, I ubgraded Cabal and now I got this:

$ stack build --profile --executable-profiling --library-profiling
stack-1.3.3: build (lib + exe)
Preprocessing library stack-1.3.3...
Preprocessing executable 'stack' for stack-1.3.3...
[2 of 2] Compiling Main             ( src/main/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/stack/stack-tmp/Main.p_o )
/home/syd/stack/src/main/Main.hs:121:10:
    cannot find normal object file ‘.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/stack/stack-tmp/Paths_stack.dyn_o’
    while linking an interpreted expression

--  While building package stack-1.3.3 using:
      /home/syd/stack/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:stack exe:stack --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1

**Comment by NorfairKing** [comment]
I know I'm being annoying, but once I figure out how to profile stack, I'll make a PR to add some docs about it. I don't think there are any currentl.

**Comment by lwm** [comment]
No stress @NorfairKing! :) I'm glad to see you pushing this one.

I was unable to reproduce your error. Maybe nuke your local `.stack-work` and try again.

**Comment by NorfairKing** [comment]
```
~/stack $ rm -r .stack-work
~/stack $ which stack
/home/syd/.local/bin/stack
~/stack $ stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0
~/stack $ stack build --profile --executable-profiling --library-profiling
[...]
[121 of 121] Compiling Stack.SDist      ( src/Stack/SDist.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/Stack/SDist.p_o )
Preprocessing executable 'stack' for stack-1.3.3...
[1 of 2] Compiling Paths_stack      ( .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/autogen/Paths_stack.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/stack/stack-tmp/Paths_stack.p_o )
[2 of 2] Compiling Main             ( src/main/Main.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/stack/stack-tmp/Main.p_o )
/home/syd/stack/src/main/Main.hs:121:10:
    cannot find normal object file ‘.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/stack/stack-tmp/Paths_stack.dyn_o’
    while linking an interpreted expression
Completed 23 action(s).

--  While building package stack-1.3.3 using:
      /home/syd/stack/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 build lib:stack exe:stack --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by lwm** [comment]
In the comment about, you are using Stack 1.3.2, and further above, you are using Stack 1.3.3?

I'm on a clean build of master, and it works, so I think you need to check your env :|

**Comment by NorfairKing** [comment]
#lwm Aha, it seems you were right
```
$ rm -rf .stack-work 
$ stack clean
$ stack install
$ stack --version
Version 1.3.3, Git revision c67b7f93c92294889574a8216edc724576657357 (4476 commits) x86_64 hpack-0.16.0
$ stack build --executable-profiling --library-profiling --ghc-options="-fprof-auto -rtsopts" --ghc-options="-fprof-auto -rtsopts" --copy-bins
[...]
Copied executables to /home/syd/.local/bin:
- stack
```
