### ISSUE TITLE
stack doesn't pick the Cabal library from the LTS Haskell snapshot

### ISSUE THREAD

**Issue by asr** [commercialhaskell/stack#2918]
I reported the issue in stackoverflow in [this](http://stackoverflow.com/questions/41597013/why-stack-doesnt-pick-the-cabal-library-from-the-lts-haskell-snapshot) link.

In the above link, user sjakobi wrote:
> Looks like a bug triggered by the `explicit-setup-deps setting`. Can you open a bug report?

**Comment by mgsloan** [comment]
Unfortunately, I don't think there's anything we can do about this, at least without a breaking changing behavior.  What's happening is that it's building the Setup.hs with the globally installed Cabal, but other packages are built with the snapshot Cabal.

I do have a suggestion for a workaround, though - use the `custom-setup` stanza introduced with Cabal-1.24.  This will require installing the git version of stack (`stack upgrade --git`), as there are no released versions that support custom-setup.
