### ISSUE TITLE
Allow use of custom haddock binary to generate the documentation

### ISSUE THREAD

**Issue by wereHamster** [commercialhaskell/stack#2922]
I compiled my own version of haddock which generates a much nicer looking documentation. But there doesn't seem to be a way to tell stack to use my binary instead of the one which comes with the installed GHC.

See also http://stackoverflow.com/questions/41628606/how-to-use-a-custom-haddock-executable-to-generate-documentation-with-stack

**Comment by mgsloan** [comment]
Should work if you have your own custom haddock version installed in your project's local bin path (`$(stack path --local-install-root)/bin`)

**Comment by wereHamster** [comment]
Hm, that will only generate new documentation for my packages. Documentation for base, bytestring and other basic packages will still look old. For consistency it's probably best to use a whole custom compiler snapshot.

**Comment by wereHamster** [comment]
Is there a guide how to create a custom compiler snapshot (the tarballs one can list under `setup-info`)?

**Comment by mgsloan** [comment]
@wereHamster They're just plain distribution tarballs of ghc, so documentation of that is part of ghc.

**Comment by mgsloan** [comment]
Closing as an old support ticket.
