### ISSUE TITLE
Stack setup fails with -fPIC error

### ISSUE THREAD

**Issue by MaximilianAlgehed** [commercialhaskell/stack#2923]
I'm on Debian sid. When I run `stack setup` in a project (in my case liquidhaskell, which uses ghc-7.10.3)
after having deleted `~/.stack` ghc installation seems to work fine until the very last moment, when
stack suddenly prints a dizzying array of error messages all related to the -fPIC issue. Furthermore
when I then run `stack build` I get the same series of `-fPIC` errors.

The fix suggested in https://github.com/commercialhaskell/stack/issues/2712 does nothing.

**Comment by lwm** [comment]
@MaximilianAlgehed, is the suggested fix the same as the documentation entry over at https://docs.haskellstack.org/en/stable/faq/#i-get-strange-ld-errors-about-recompiling-with-fpic? Is this still happening? Is there a minimal reproduction?

**Comment by MaximilianAlgehed** [comment]
@lwm I'm sorry to say I completely gave up on this and I'm not sure I can produce a minimal failing example any more.
