### ISSUE TITLE
generic linux stack binary not generic enough

### ISSUE THREAD

**Issue by mzero** [commercialhaskell/stack#293]
If you built the generic linux binary against Debian Wheezy (7) - as GHC does (and HP will), then the resulting stack executable will install and run on a wide variety of distributions without modificaiton: Debian 7 and later, Ubunutu 12.04 and later, Fedora 20 and later, RHEL/CentOS 7 and later, and openSUSE 13.1 and later.

If you do that, then you can distribute a single build, packaged as a deb, as and rpm, and as a tarball - and have it install on all those systems.

The current stack distributions, with separate repos and versions and builds for many versions of each distro is unnecessary.

**Comment by snoyberg** [comment]
Thanks for the feedback. Assigning to @dysinger, who put together the Ubuntu debs, and pinging @drwebb who put together the Arch distro, for comments.

**Comment by drwebb** [comment]
I'm all up for a universal binary, I just tested the generic linux binary on the wiki's download page and it seemed to work on my Arch install. Having a single up to date 32-bit and 64-bit binary could make our lives easier, which is a good thing. That being said, it's not huge hassle for me at the moment to manually recompile a new binary.

I would suggest that we still make a point to provide support for different distro's package managers, so user's can track updates, find it easier, etc.

**Comment by snoyberg** [comment]
I think we have the right plan in place: the binary on the releases page appears to be generic, and we'll provide packages for a number of distros. Closing.

**Comment by dysinger** [comment]
https://github.com/commercialhaskell/stack/issues/461 hard with wildly different gmp versions (on older linux)
