### ISSUE TITLE
More detailed output with ` --verbosity debug`

### ISSUE THREAD

**Issue by deech** [commercialhaskell/stack#2930]
Hi,
I'm trying to compile + link a library on Windows 10 using `stack build` and am getting a slew of `undefined reference` errors. To debug this I want to see the exact linker command used so I tried `stack build --verbosity debug` but it doesn't display (or log) it. I'm probably missing something but if not can that feature be added to `--verbosity debug`?

**Comment by deech** [comment]
I also tried `stack build --verbosity debug --dump-logs` but since I have more than one target in my project  nothing was logged. The same when I added `dump-logs: all` to `stack.yaml`.

**Comment by mgsloan** [comment]
Perhaps the `--cabal-verbose` flag will cause the info to be outputted?

**Comment by deech** [comment]
Hadn't tried that. Thanks! I did work around this issue by setting `ghc-options: -v` in my `.cabal` file. It took me a while to figure out so it might be worth adding that to the `stack` docs. If you like the idea I'll put up a PR.

**Comment by mgsloan** [comment]
Sure, a documentation PR would be appreciated.
