### ISSUE TITLE
stack profiling build results in plan construction failure.

### ISSUE THREAD

**Issue by jeiea** [commercialhaskell/stack#2935]
### Steps to reproduce
1. Checkout from [here](https://github.com/jeiea/cpphs).
2. Run `stack build --executable-profiling` on Windows 10 RS.

### Environment
```
cabal-install version 1.24.0.0
compiled using version 1.24.0.0 of the Cabal library
```

### Expectation & Result
I have no system ghc and have tried with `--no-system-ghc`, there was no difference.
Verbose log is uploaded on [gist](https://gist.github.com/jeiea/734befde241e11d7913b960610e44850).
Adding extra-deps entries also made no difference.

### Maybe related
#2655 #1331

**Comment by lwm** [comment]
I'm pretty sure Stackage hasn't caught up [with your compiler setting](https://github.com/jeiea/cpphs/blob/master/stack.yaml#L19). You'll have to wait for https://github.com/fpco/stackage/issues/2203?

**Comment by jeiea** [comment]
Well, certainly `lts-7.16` is not for ghc 8.0.2.  I'm curious why non-profiling build success and it still can be a problem if I didn't use #2203 listed packages.

**Comment by jeiea** [comment]
I checked Stackage Nightly 2017-01-25 (ghc-8.0.2) has the same problem.
I used stack of master branch this time.
