### ISSUE TITLE
("RTS expects libdw","NO") with GHC 8.0.1 supplied by Stack

### ISSUE THREAD

**Issue by tebello-thejane** [commercialhaskell/stack#2939]
### General summary/comments

I'm not entirely sure if this is a bug, or if `stack` is to blame, since [the library documentation for this feature](https://hackage.haskell.org/package/base/docs/GHC-ExecutionStack.html) leaves a lot to be desired.

The promise is that GHC now supports yet-another-mechanism for stack traces, but either GHC needs to have been compiled with `libdw` support, or `libdw` needs to exist on the system (I'm not sure, and documentation is very scant).

**Assuming** that GHC should be compiled with `libdw` support, **and** that the `stack` team compiles their own GHC binaries, then I would consider the following to be a bug or oversight in the greater `stack` infrastructure.

### Steps to reproduce

1. Set up your global or local resolver to `lts-7.16`.
2. Run command `stack setup` if you need to download GHC.
3. Run command `stack exec -- ghc --info | grep libdw`.

### Expected

` ,("RTS expects libdw","YES")`
### Actual

` ,("RTS expects libdw","NO")`

### Stack version

```
$ stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0
```

### Method of installation

Downloaded initially, with `stack upgrade` used to upgrade about two weeks ago (which downloaded a binary instead of building from scratch).

**Comment by snoyberg** [comment]
We use the upstream GHC bindists, and do not build our own. Closing
