### ISSUE TITLE
debian packaging has graphic dependencies

### ISSUE THREAD

**Issue by mzero** [commercialhaskell/stack#294]
If you install the stack.deb for Ubuntu 14.04 on a pristine, bare system (the docker image, for example), it pulls in many graphics libs:

    fontconfig fontconfig-config fonts-dejavu-core git git-man gnupg-agent
    gnupg2 hicolor-icon-theme krb5-locales libasn1-8-heimdal libassuan0
    libatk1.0-0 libatk1.0-data libavahi-client3 libavahi-common-data
    libavahi-common3 libcairo2 libcups2 libcurl3-gnutls libdatrie1 libedit2
    liberror-perl libfontconfig1 libfreetype6 libgdk-pixbuf2.0-0
    libgdk-pixbuf2.0-common libglib2.0-0 libglib2.0-data libgmp10 libgraphite2-3
    libgssapi-krb5-2 libgssapi3-heimdal libgtk2.0-0 libgtk2.0-bin
    libgtk2.0-common libharfbuzz0b libhcrypto4-heimdal libheimbase1-heimdal
    libheimntlm0-heimdal libhx509-5-heimdal libjasper1 libjbig0 libjpeg-turbo8
    libjpeg8 libk5crypto3 libkeyutils1 libkrb5-26-heimdal libkrb5-3
    libkrb5support0 libksba8 libldap-2.4-2 libpango-1.0-0 libpangocairo-1.0-0
    libpangoft2-1.0-0 libpixman-1-0 libpth20 libroken18-heimdal librtmp0
    libsasl2-2 libsasl2-modules libsasl2-modules-db libthai-data libthai0
    libtiff5 libwind0-heimdal libx11-6 libx11-data libxau6 libxcb-render0
    libxcb-shm0 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxdmcp6
    libxext6 libxfixes3 libxi6 libxinerama1 libxml2 libxmuu1 libxrandr2
    libxrender1 openssh-client patch pinentry-gtk2 rsync sgml-base
    shared-mime-info stack xauth xml-core

That's a lot of stuff!

**Comment by snoyberg** [comment]
Assigning to @dysinger

**Comment by dysinger** [comment]
This is coming from the dependecy on gnupg2 which we desire to use for package signature verification.  Unfortunately it depends on pinentry-gtk2 which pulls in all the X libs.  We will discuss options.

**Comment by dysinger** [comment]
OK we are going to remove gpg for now.

**Comment by radix** [comment]
Wow, this is ridiculous. Apparently it's gnupg2 depends on gnupg-agent depends on (pinentry-gtk2 | pinentry-curses | pinentry) -- that is, gnupg-agent depends on any one of those three packages, and apparently the package manager is just picking the first one, regardless of what other dependencies are installed. I don't know how kosher this would be, but perhaps by making stack depend on `pinentry` this would be avoided, by ensuring that a baseline pinentry mechanism is installed so it won't try to install the gtk2 version?

**Comment by radix** [comment]
Hm. apparently some work went into the gnupg2 package to address this issue this month: see the last message at  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=764292

**Comment by dysinger** [comment]
I just made git & gnupg2 "recommended" packages for now.  Stack is usable today without these.

**Comment by dysinger** [comment]
I just made gnupg2 a 'recommended' dependency for now.
