### ISSUE TITLE
"stack upgrade" doesn't work on Raspberry Pi 3

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#2941]
### General summary/comments (optional)
Usual steps for installing stack on Raspberry Pi 3 doesn't work. When I ran them I got message, that I already have "stack" so I should do "stack upgrade".

### Steps to reproduce
1. Have old stack
2. run "stack upgrade"

### Expected

Download latest version instead of compiling it on upgrade step.

### Actual

It blocks Raspberry Pi 3, because of too much memory used during compilation (more than 1Gb RAM + 1Gb swap).

### Stack version

```
$ stack --version
Version 1.1.2, Git revision 6bca6d8eaf542c5bd4b5c83d23670137249f2145 (3663 commits) arm hpack-0.14.0
```

### Method of installation

* stack upgrade

**Comment by borsboom** [comment]
stack-1.1.2 doesn't support binary upgrade.  That was first introduced in stack-1.3.0.  You can grab a binary for stack-1.3.2 here and copy it over the old one manually: https://github.com/commercialhaskell/stack/releases/download/v1.3.2/stack-1.3.2-linux-arm.tar.gz

**Comment by varosi** [comment]
Thanks, it works!
