### ISSUE TITLE
stack template with .ghci warning

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack#2947]
When there is a stack template with a `.ghci` file, like [this one](https://github.com/commercialhaskell/stack-templates/blob/master/servant-0.4.hsfiles#L41-L42) then when you start `stack ghci` you get this warning: `*** WARNING: /home/flip111/blabla/.ghci is writable by someone else, IGNORING!`

Is there a way for stack to support doing chmod so that this warning does not occur?

**Comment by lwm** [comment]
That'd be cool! Even better when it would be upstream in `GHCi` :)

Oh wait, it's highly contested: https://ghc.haskell.org/trac/ghc/ticket/8248

Stack probably shouldn't diverge on behavior here.

**Comment by flip111** [comment]
I think the behavior of the warning is ok, no fix needed in ghci (or if people in ticket 8248 decide otherwise .. so be it). But it's stack who write this file when you use a certain stack template. I suggestion would be to use chmod so that the warning doesn't pop up anymore. I think the gist of the warning is to make the `.ghci` file more secure, so let stack make this file "more secure" by default. You can always choose to reverse it manually with chmod after `stack new` did it's work. I forgot to mention that i created this ticket specifically for the behavior around `stack new`, sorry that i didn't mention this before.

**Comment by snoyberg** [comment]
This is probably best handled by setting `umask` to not make files group or world writable by default. On my system, for example, I get no warning.

**Comment by snoyberg** [comment]
Closing as wontfix
