### ISSUE TITLE
Small and equal for upper bound in cabal file is not working with Stack

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#2948]
### General summary/comments (optional)
Small **and equal** for upper bound in cabal file is not working with Stack. It works only with Small **without equal**.

### Steps to reproduce
1. Modify your cabal file with:
       base-4.9.0.0 must match >=4.6 && <=4.9
2. stack build

### Expected

To build well. If I modify upper bound to "< 5.0" (without equal operation) it will work.

### Actual
```
base-4.9.0.0 must match >=4.6 && <=4.9 (latest applicable is 4.8.2.0)
```

### Stack version

```
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 x86_64 hpack-0.15.0
```

### Method of installation

* Official binary

**Comment by tfausak** [comment]
This is not a Stack bug. The version `4.9.0.0` is greater than the version `4.9`.

``` hs
>>> import Data.Version
>>> makeVersion [4, 9, 0, 0] <= makeVersion [4, 9]
False
```

**Comment by varosi** [comment]
Thanks! I have filed a ticket in GHC Trac:
https://ghc.haskell.org/trac/ghc/ticket/13235
