### ISSUE TITLE
(Possible regression) stack ghci fails to open TH files

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#2953]
### General summary/comments (optional)

I think `stack ghci` worked well for our project previously but got broken, but I am not 100% sure about this. Specific project layout is that we have a single `stack.yaml`, multiple inter-dependent projects and they use TH+filesystem.

### Steps to reproduce

I created a minimal repo with a README showing the problem https://github.com/k-bx/haskell-mode-th-bug

### Expected

I expect `stack ghci` to be consistent with `stack build / stack exec` and "just work", finding the file included from TH.

### Actual

TH file is not found.

### Stack version

```
$ stack --version
Version 1.3.2 x86_64 hpack-0.15.0
```

### Method of installation

* brew

**Comment by lwm** [comment]
The errors in your repo look like application errors?

> data/file.txt: openBinaryFile: does not exist (No such file or directory)

> Could not find module ‘BaseLib’ ... It is a member of the hidden package ...

Didn't get a deep look at it though. Can your confirm they are not relevant?

**Comment by k-bx** [comment]
@lwm it compiles and runs well via `stack build` / `stack exec`. It fails to compile `subproj-base` because of TH-file error and thus it can't then load `BaseLib` from this base project

**Comment by mgsloan** [comment]
Unfortunately, this is expected.  Options:

1) Use something like https://hackage.haskell.org/package/th-utilities-0.2.0.1/docs/TH-RelativePaths.html

2) Only use `stack ghci` on one package at a time, and start it in the directory of the package.
