### ISSUE TITLE
Stack does not accept absolute directories as its `--work-dir`

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/stack#2954]
```
Command: stack build --work-dir /home/syd/whatever/.stack-work
Stderr:
option --work-dir: InvalidRelDir "/home/syd/whatever/.stack-work"
```

**Comment by lwm** [comment]
Please see https://github.com/commercialhaskell/stack/issues/2721#issuecomment-254968564.

**Comment by NorfairKing** [comment]
@lwm Thank you for the quick response.
If it's a known limitation, it might be nice to direct the user to an explanation of why that is.

Closing this is in the meantime.

**Comment by lwm** [comment]
> If it's a known limitation, it might be nice to direct the user to an explanation of why that is.

:+1: :+1: :+1:

**Comment by mgsloan** [comment]
I looked around and found this comment from @borsboom - https://github.com/commercialhaskell/stack/issues/1178#issuecomment-162255770

I've made it output more in the error message:

```
option --work-dir: InvalidRelDir "../test"
Note that --work-dir must be a relative child directory, because work-dirs outside of the package are not supported by Cabal.
See https://github.com/commercialhaskell/stack/issues/2954
```

**Comment by lwm** [comment]
Awesome. :beers:
