### ISSUE TITLE
race condition with multiple --file-watch commands

### ISSUE THREAD

**Issue by mwotton** [commercialhaskell/stack#2958]
admittedly this is user error, but sometimes I accidentally leave a "stack test --file-watch" command running in a hidden terminal and start another. This leads to git errors - my git-based dependencies will get downloaded, corrupted, and re-downloaded. might it make sense to have some locking, at least at the level of git commands on a particular directory?

**Comment by Blaisorblade** [comment]
Also had the same issue—it's easy-ish in my workflow to forget a running `--file-watch` instance in some hidden terminal.

**Comment by mgsloan** [comment]
Solution here is indeed probably some variety of locking, sounds like other build issues can happen as well - https://github.com/commercialhaskell/stack/issues/3227

**Comment by tswelsh** [comment]
Having multiple simultaneous builds triggered by `--file-watch` has bitten more than one of my colleagues.  Presumably this isn't a `--file-watch` specific thing, but comes down to concurrent builds using the same `work-dir`?  I'd like to help out with this one if possible, any guidance would be appreciated.

Is this related to #2730?  Or could it help to alleviate it at least?  Smoothly building our projects with different configurations is also something that would help us.

**Comment by Blaisorblade** [comment]
@tswelsh I do assume this is a dup of #2730, thanks for finding it, so I’m closing this issue in favor of that one. That one seems to have the best ideas on how to proceed, though I’m afraid it’s somewhat vague?

Indeed, I also assume you’d get the same bug if you run two `stack build` in parallel without `--file-watch`, this option just helps triggering it by accident: we all launch `--file-watch`, forget it, then decide we need a build.
