### ISSUE TITLE
Cache downloads

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#297]
From IRC (this was about Cabal, but still holds)

```
04:25 < Birch> I'm going to be stepping on a plane in a few hours, and would like to get some programming done on the 
               flight. Does anyone have any tips for helping me be productive on the flight? Like making sure my 
               hoogle data is up to date and the like?
04:26 < Birch> Like will I be able to rebuild a sandbox without an internet connection if I once downloaded the 
               dependencies, a la maven?
```

**Comment by snoyberg** [comment]
This sounds like a good flag to `build` and `test`, perhaps --prefetch`, like `--dry-run` works right now. Should actually be pretty easy to implement.

**Comment by snoyberg** [comment]
@bitemyapp I just added the `--prefetch` option, which combined with `--dry-run` gives the behavior I think you're describing here. Can you give it a shot?

**Comment by bitemyapp** [comment]
@snoyberg 
```
boura:lens callen$ stack --prefetch --dry-run
Invalid option `--prefetch'
```

from Stack master SHA1: ce0e8d8104e5f7abf403250ef8e29ca18eb0f05a

What am I missing?

**Comment by bitemyapp** [comment]
@snoyberg it worked for Bloodhound, thank you!
