### ISSUE TITLE
Dependency count tool

### ISSUE THREAD

**Issue by jmn** [commercialhaskell/stack#2972]
As a complement to stack dot, what about a tool that could show something like this:
e.g. 

`stack deps`:
```
|----------------------+-------+--------+----------+------|
| package              | total | direct | indirect | used |
|----------------------+-------+--------+----------+------|
| text                 |    10 |      5 |        5 | X    |
| lens                 |    20 |     10 |       10 | X    |
| optparse-applicative |    10 |      6 |        4 | X    |
|----------------------+-------+--------+----------+------|


```

**Comment by mgsloan** [comment]
Not sure when this would be useful.  Could be interesting statistics, but I don't see making any decisions based off of it.

**Comment by jmn** [comment]
We need tools to speed up builds. Partly by keeping a check on the size of the dependency tree!
