### ISSUE TITLE
get-stack.sh installs broken file

### ISSUE THREAD

**Issue by cobodo** [commercialhaskell/stack#2973]
### General summary/comments (optional)
https://github.com/commercialhaskell/stack/blob/master/etc/scripts/get-stack.sh#L462
Script must check return code before `sudocmd install`.

### Steps to reproduce

1. `curl -sSL https://get.haskellstack.org/ | sh`
2. Amazon S3 (sometimes) suddenly disconnects because of slow (<200kbps) connection speed.

### Expected

Script checks return codes of both `curl` and `tar`. If failed, it tries to resume some (3-5) times. 

### Actual

`curl` and `tar` write to stderr as follows:

> curl: (56) GnuTLS recv error (-54): Error in the pull function.
> gzip: stdin: unexpected end of file

but script ignored them, and installed broken file.

**Comment by mgsloan** [comment]
Good catch!  Pinging @borsboom
