### ISSUE TITLE
Provide nightly builds

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#2974]
In some situations that would be very helpful in CIs, currently one have to either host binary itself somewhere, or do expensive `stack update --git` (though it can be cached).

**Comment by snoyberg** [comment]
With the Azure jobs we now provide nightly builds. Unfortunately it looks a bit involved to ask Azure for the latest binary release, but the documentation is available here:

* https://docs.microsoft.com/en-us/rest/api/azure/devops/build/builds/list?view=azure-devops-rest-5.0
* https://docs.microsoft.com/en-us/rest/api/azure/devops/build/artifacts/get%20artifact?view=azure-devops-rest-5.0_
