### ISSUE TITLE
"stack upgrade --git" no longer works

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#2977]
I believe this is a regression due to adding support for binary downloads in 1.3.

```
mgsloan@computer:~$ stack upgrade --git
Current Stack version: 1.3.3, available download version: 1.3.2
Skipping binary upgrade, your version is already more recent
```

**Comment by mgsloan** [comment]
Fixed!

**Comment by lwm** [comment]
> Fixed!

Phew!

**Comment by sectore** [comment]
@mgsloan How did you fixed your issue with `stack upgrade --git`? Just jumped into the same thing...

```
$ git pull -r
stack upgrade --git
Current Stack version: 1.3.3, available download version: 1.3.2
Skipping binary upgrade, your version is already more recent

```

**Comment by borsboom** [comment]
@sectore: `stack upgrade --git --source-only` worked for me when `stack upgrade --git` didn't.

**Comment by sectore** [comment]
@borsboom Thanks, works great w/ `--source-only`.
