### ISSUE TITLE
How can I use --flag with repl command?

### ISSUE THREAD

**Issue by jeiea** [commercialhaskell/stack#2986]
I checked `stack repl --flag package:flag` works on stack v1.1.0, but now it seems that v1.3.2 reject it as invalid flag.
What's an alternative to this?

**Comment by lwm** [comment]
Seems to have moved over to `stack build`?

**Comment by jeiea** [comment]
Then, should I use `stack build --flag PACKAGE:FLAG --exec "ghci Main.hs"?
Is there any reason of moving?

**Comment by borsboom** [comment]
There was a significant refactoring of build arguments a while back (in order to support including build arguments in `stack.yaml`) and it's possible this was removed from `stack repl` by accident.

**Comment by jeiea** [comment]
I've just bisected and found the commit 3347bcb8efa6ca5d8d65177e2ee91000e5539b84. But I can't determine whether it is indended.

**Comment by mgsloan** [comment]
Hmm, yes, that was an unintended consequence of that change.  Most of the things in BuildOptsCLI aren't useful for ghci, but `--flag` and `--ghc-options` are, so I've added just those ones back in.
