### ISSUE TITLE
Unexpected Cabal version warning

### ISSUE THREAD

**Issue by PierreVDL** [commercialhaskell/stack#2988]
When I run stack (Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 x86_64 hpack-0.15.0) with a stack.yaml file that contains as resolver lts-7.19
and a cabal file that requires a cabal-version of at least 1.23 (i.e. cabal-version:      >=1.23)
I get the following warning:
Cabal file warning in <file.cabal>: This package requires at least Cabal version 1.23

However, lts 7.19 has Cabal-1.24.2.0 according to https://www.stackage.org/lts-7.19.
So I don't understand the warning!

Also running `stack install Cabal` yields the same error.
When I run `stack install Cabal` at another location, it succeeded. See the zipped version of the log file at
C:\sr\global-project\\.stack-work\logs\Cabal-1.24.2.0.log
[Cabal-1.24.2.0.zip](https://github.com/commercialhaskell/stack/files/760100/Cabal-1.24.2.0.zip)

Yet, I keep getting the same Cabal file warning!

**Comment by lwm** [comment]
What does `stack setup --upgrade-cabal` get you?

**Comment by PierreVDL** [comment]
It helps: I still get the warning, however my package is build again:
```
C:\>stack build
Cabal file warning in <file.cabal>: This package requires at least Cabal version 1.23
[1 of 2] Compiling Main             ( C:\sr\setup-exe-src\setup-Z6RU0evB.hs, C:\sr\setup-exe
-src\setup-Z6RU0evB.o ) [Distribution.Simple changed]
[2 of 2] Compiling StackSetupShim   ( C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\sr\setu
p-exe-src\setup-shim-Z6RU0evB.o ) [Distribution.Simple.LocalBuildInfo changed]
Linking C:\sr\setup-exe-cache\x86_64-windows\tmp-Cabal-simple_Z6RU0evB_1.24.2.0_ghc-8.0.1.ex
e ...
Name-0.1.0.0: unregistering (local file changes: Name.cabal gen\GenName.hs src\Name.hs src\N
ameImpl.hs src\test\TestName.hs)
Name-0.1.0.0: configure (lib)
Configuring Name-0.1.0.0...
Name-0.1.0.0: build (lib)
Preprocessing library Name-0.1.0.0...
[1 of 2] Compiling NameImpl         ( src\NameImpl.hs, .stack-work\dist\ca59d0ab\build\NameI
mpl.o )
[2 of 2] Compiling Name             ( src\Name.hs, .stack-work\dist\ca59d0ab\build\Name.o )
Name-0.1.0.0: copy/register
Installing library in
C:\.stack-work\install\10ee698a\lib\x86_64-windows-ghc-8.0.1\Name-0.1.0.0-58ky20TNxZCEuoUZ3Nwp6E
Registering Name-0.1.0.0...
```
and rerun it again gives just the warning:
```
C:\>stack build
Cabal file warning in <file.cabal>: This package requires at least Cabal version 1.23
```

**Comment by PierreVDL** [comment]
Just for your information, cabal was upgrade to `1.24.2.0`.

```
C:\>stack setup --upgrade-cabal
Currently installed Cabal is 1.24.2.0, newest is 1.24.2.0. I'm not upgrading Cabal.
```

**Comment by lwm** [comment]
Hmmm, make sure you ran `stack setup --upgrade-cabal` in your project directory, and not your global project? It looks like you are doing it in the global project (at `C:\>`)? What does `stack exec ghc-pkg describe Cabal | grep -i version | head -1` get you (when run in the project directory)?

Perhaps https://github.com/commercialhaskell/stack/pull/2970 should be extended to tell the user to upgrade their cabal locally ...

**Comment by PierreVDL** [comment]
1. I run it in my project (I shortened the path, since it was long and not relevant)
2. I run on windows, so grep is not available. I used 'find' to make a windows equivalent:
```
C:\Project>stack exec ghc-pkg describe Cabal | find "version"
version: 1.24.2.0
version: 1.24.2.0
version: 1.24.0.0
```
The complete output without the pipes is:
[output.zip](https://github.com/commercialhaskell/stack/files/760547/output.zip)

**Comment by lwm** [comment]
@PierreVDL, are you still seeing this issue? Was it resolved?

**Comment by PierreVDL** [comment]
I just checked: it seems to be resolved
