### ISSUE TITLE
stack haddock --haddock-arguments "--odir=/my/doc/folder" does not work properly

### ISSUE THREAD

**Issue by fredericcogny** [commercialhaskell/stack#2993]
### General summary
I'm trying to generate the docs in a chosen folder rather than deep down inside `.stack-work`.
Following the help I'm trying to pass the following command
```
stack haddock --haddock-arguments "--odir=/Users/Fred/git/Haskell/simwork-maths/doctest"
```

### Actual behaviour
Some files [including the index.html] are produced in the desired directory
<img width="408" alt="screen shot 2017-02-09 at 6 17 25 pm" src="https://cloud.githubusercontent.com/assets/15909740/22794905/f58a1d78-eef4-11e6-9583-f081f1b39f12.png">

But all the other ones are still deep down in `.stack-work`
the final output of the command is:
```
Updating Haddock index for local packages in
/Users/Fred/git/Haskell/simwork-maths/.stack-work/install/x86_64-osx/lts-7.18/8.0.1/doc/index.html
Updating Haddock index for local packages and dependencies in
/Users/Fred/git/Haskell/simwork-maths/.stack-work/install/x86_64-osx/lts-7.18/8.0.1/doc/all/index.html
Updating Haddock index for snapshot packages in
/Users/Fred/.stack/snapshots/x86_64-osx/lts-7.18/8.0.1/doc/index.html
```

### Stack version

```
$ stack --version
Version 1.3.2 x86_64 hpack-0.15.0
```

### Method of installation
* Via brew

### Stack env

**Comment by lwm** [comment]
[This SO question](http://stackoverflow.com/questions/41662105/usage-of-buildhaddock-arguments-option-of-stack-yaml) seems relevant.

**Comment by Fuuzetsu** [comment]
I didn't see this issue earlier but it has been fixed by https://github.com/commercialhaskell/stack/pull/3102
