### ISSUE TITLE
Drop formatting dependency

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#300]
double-conversion is not Windows-friendly, and therefore the formatting dependency causes Windows builds to fail:

```
[ 9 of 46] Compiling System.Process.Read ( src\System\Process\Read.hs, dist-stack\i386-windows\Cabal-1.18.1.5\build\System\Process\Read.o )
ghc.exe: stdc++: The specified module could not be found.
<command line>: can't load .so/.DLL for: stdc++.dll (addDLL: could not load DLL)
Loading package double-conversion-2.0.1.0 ...

--  While building package stack-0.0.2 using:
      C:\\Users\\Michael\\AppData\\Local\\Programs\\stack\\i386-windows\\ghc-7.8.4\\bin\\runhaskell.exe -package=Cabal-1.18.1.5 -clear-package-db -global-package-db C:\Users\Michael\Documents\stack\Setup.hs --builddir=dist-stack\i386-windows\Cabal-1.18.1.5\ build
    Process exited with code: ExitFailure 1
```

We need to get rid of the formatting dependency, either entirely, or at least on Windows, though I'd prefer to avoid conditional compilation if we can.

**Comment by gregwebs** [comment]
It adds the same dependency for Linux

**Comment by snoyberg** [comment]
@gregwebs I wasn't having any problem with building the dependency on Linux, just on Windows, which is why I was making this a Windows-specific issue. Did you have trouble building on Linux?

**Comment by gregwebs** [comment]
I needed to add it to my Docker build image (will PR soon).

**Comment by snoyberg** [comment]
@chrisdone I just pushed ca93c89 that drops the dependency. Feel free to tweak the output as desired, but I want to move ahead with this now so I can get a 0.0.2 release out the door.

**Comment by chrisdone** [comment]
So basically Windows users can't use formatting. Good to know.

**Comment by chrisdone** [comment]
FYI, `formatting` now doesn't depend on `text-format` (which appears to be unmaintained as of today) and therefore doesn't depend on `double-conversion`.
