### ISSUE TITLE
sinkCheckHash should not be case sensitive

### ISSUE THREAD

**Issue by luochen1990** [commercialhaskell/stack#3005]
When finished running `stack setup`, the following messages printed:

![swhk x x0 c0 i5xg5thr](https://cloud.githubusercontent.com/assets/2309868/22931699/925bbf12-f300-11e6-8929-9a509d5953b6.png)

But I don't think there is any error during the downloading, maybe the hash checking logic should not be case sensitive here?

The suspected related code: https://github.com/commercialhaskell/stack/blob/master/src/Network/HTTP/Download/Verified.hs#L160

**Comment by mgsloan** [comment]
Hmm, do you have a custom setup-info (https://docs.haskellstack.org/en/stable/yaml_configuration/#setup-info or `--setup-info-yaml`)?

That hash isn't present in https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml .  I think I'd prefer that we just consistently use lowercase hashes everywhere!

**Comment by luochen1990** [comment]
Yes, I'm using `setup-info: "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"` to speed up the installation.

It seems that it is'nt a problem of this project, but a case-insensitive comparation of hash will be better :)

**Comment by mgsloan** [comment]
The hashes in that file seem to be lowercase as they should be, so not sure why that would happen.

Closing as wontfix
