### ISSUE TITLE
Speed up Store instances for (Byte)Strings of known size

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#3006]
`Stack.Types.BuildPlan.GitSHA1` currently derives its `Store` instance from the underlying ByteString, so store must assume a variable size. A handwritten instance could use the fact that a SHA1 digest has 20 bytes and would probably be a bit faster, and – depending on architecture – 4 or 8 bytes shorter.

The same could be done for `Stack.Types.PackageIndex.PackageDownload.pdSHA256` and probably other types.

If there isn't already a set of helpers for ByteStrings of known size in `store`, maybe it should be added! :)

**Comment by sjakobi** [comment]
> If there isn't already a set of helpers for ByteStrings of known size in store, maybe it should be added! :)

See [`StaticSize`](https://hackage.haskell.org/package/store-0.3.1/docs/Data-Store-Internal.html#t:StaticSize).

**Comment by mgsloan** [comment]
Yep, I think `StaticSize` is our answer to this, closing

**Comment by sjakobi** [comment]
Reopening, as stack's Store instances still need to make use of `StaticSize`, right?!

**Comment by mgsloan** [comment]
Oh, true!  I thought this was on the store tracker.

**Comment by alexeyzab** [comment]
Hi there!

I'd like to try implementing this. I'll be sending a PR shortly, let me know if I am on the right track. Thanks!

**Comment by alexeyzab** [comment]
I believe this can be closed.

**Comment by snoyberg** [comment]
Sounds good, thanks for catching that!
