### ISSUE TITLE
Passing cabal flags

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack#301]
I am trying to pass an argument, so I put
```
flags: { demos: true }
```
in my `stack.yaml`.
However when I try to run `stack build` this results in the error
```
AesonException "failed to parse field flags: when expecting a HashMap Text a, encountered Boolean instead"
```
I tried figuring out what the correct syntax should be, but I couldn't. It would be great if you could add the documentation for that.

**Comment by snoyberg** [comment]
There's an open issue for documenting stack.yaml correctly. In the meanwhile: you need to set it up by package name, e.g.:

```yaml
flags:
  package-name:
    flag-name: true
```

**Comment by cocreature** [comment]
Thanks, added the example to the wiki.

**Comment by snoyberg** [comment]
Thank you!
