### ISSUE TITLE
integer-simple not support on 8.0.2 (and linux)

### ISSUE THREAD

**Issue by PierreVDL** [commercialhaskell/stack#3010]
stack setup 
with resolver lts7.19 (https://www.stackage.org/lts-7.19) and integer-simple (ghc-variant: integersimple) works fine.
However, with resolver lts 8.0 (https://www.stackage.org/lts-8.0) and integer-simple (ghc-variant: integersimple), I get
```
No information found for ghc-8.0.2.
Supported versions for OS key 'windows64-integersimple': GhcVersion 7.8.4, GhcVersion 7.10.1
, GhcVersion 7.10.2, GhcVersion 7.10.3, GhcVersion 8.0.1
```

From a collegae who wants to build our software on linux, I understood that on linux
integer-simple is not supported at all.
Why? 
Now we need two *.yaml files to build on the different platforms,
while integer-simple is preferable on all platforms: has never license issues!

**Comment by borsboom** [comment]
There are no official integersimple binaries built by the GHC release team, so we rely on third-parties to provide the bindists.  @leohaskell, are you able to provide one for GHC 8.0.2, since you provided the ones for 7.10.3 and 8.0.1?

**Comment by leohaskell** [comment]
Sure, I'll provide it tomorrow.

**Comment by leohaskell** [comment]
@PierreVDL, the license issues with integer-gmp affect only windows, because on linux it's dynamically linked.
Also, you can build your project with a single .yaml file, using the `--ghc-variant` flag on windows.

**Comment by leohaskell** [comment]
@borsboom excuse my delay, [here](https://drive.google.com/open?id=0Bx1PZr9g0_7cQkVpM0p0R0NoUHc) is the 8.0.2, tested with `stack setup`.

**Comment by PierreVDL** [comment]
@borsboom Should still something be done, since I still get an error:

> c:\>stack setup
> No information found for ghc-8.0.2.
> Supported versions for OS key 'windows64-integersimple': GhcVersion 7.8.4, GhcVersion 7.10.1
> , GhcVersion 7.10.2, GhcVersion 7.10.3, GhcVersion 8.0.1

**Comment by PierreVDL** [comment]
@leohaskell  passing the  --ghc-variant=integersimple  flag to the  stack build  command on windows is not enough: I also need for a number of packages (such as text) that also depend on integer-gmp:

> extra-deps:
>  - text-1.2.2.1
> 
> flags: 
>   text: 
>     integer-simple: true

@leohaskell Our main platform is windows, and we would like that the build on the different platforms are as identical as possible: when we find an error, we would like to be certain it is due to the platform and not due to another library!

**Comment by leohaskell** [comment]
@PierreVDL - you could also add the following: `--flag text:integer-simple`.

**Comment by borsboom** [comment]
@PierreVDL I have not yet updated the `stack setup` metadata with information about the bindists.  I'll update here when that's done.

**Comment by borsboom** [comment]
@PierreVDL @leohaskell I've uploaded the bindist to the [Github release](https://github.com/commercialhaskell/ghc/releases/tag/ghc-8.0.2-release) and added the metadata to [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml).  I don't have a Windows machine handy right now to test, so can one of you try `stack setup` to make sure it is found?

**Comment by PierreVDL** [comment]
Thanks! 
It works...
```
c:\>stack setup
Preparing to install GHC (integersimple) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-integersimple-8.0.2.
Already downloaded.
Already downloaded.
....
Everything is Ok

Folders: 407
Files: 8819
Size:       1431875559
Compressed: 1438883840
GHC installed to C:\Users\...\AppData\Local\Programs\stack\x86_64-windows\ghc-integersimp
le-8.0.2\
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
```
