### ISSUE TITLE
Feature request: `stack repl --file-watch`

### ISSUE THREAD

**Issue by metaleap** [commercialhaskell/stack#3015]
In a directory with `stack.yaml` (or descendant), `stack repl` loads up GHCi with project modules. So far so neat.

I suggest to extend the already existing `--file-watch`er to `repl` mode where "on change" (as per already implemented file checks) either a `:reload\n` could be sent via the sub-process' stdin or the running `ghci` killed and restarted as if `stack repl` were invoked. Would be incredible for productivity in all .. "sub-customizable" editors out there!

**Comment by mgsloan** [comment]
In the meantime, https://github.com/ndmitchell/ghcid is worth a look!

**Comment by phadej** [comment]
I really think it's more job for `ghcid` (or `stack ghcid`). Reloading repl on external event seems defeat purposes of repl...

**Comment by mgsloan** [comment]
Agreed, I don't think we necessarily want to extend stack's feature scope to include this, so closing.  IIRC, `stack ghci --with-ghc=ghcid` works quite nicely.

**Comment by revmischa** [comment]
Maybe alias `stack ghcid` to `stack ghci --with-ghc=ghcid`?
Personally I'd love to have this feature for live editing/testing of code

**Comment by revmischa** [comment]
```
 $ stack ghci --with-ghc=ghcid
ddb-0.1.0.0: initial-build-steps (lib + exe)
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: ddb
Using main module: 1. Package `ddb' component exe:ddb-exe with main-is file: /Users/cyber/dev/ddb/app/Main.hs
Unknown flag: --interactive
```

**Comment by rteabeault** [comment]
@revmischa Did you ever figure out how to fix the `Unknown flag: --interactive` error?

**Comment by ToxiCore** [comment]
I get the same error. However, for me this seems to work:
`ghcid "--command=stack ghci src/Main.hs"`
