### ISSUE TITLE
GHCJS - ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)

### ISSUE THREAD

**Issue by tonyday567** [commercialhaskell/stack#3017]
See https://travis-ci.org/tonyday567/ghcjs-testing/builds/203649380

Firstly, thank you stack for the helpful message.  It looks like travis is running out of memory on the haskell-src-ext build.  I set up travis to use https://github.com/tonyday567/ghcjs-testing/blob/master/stack-travis.yaml which contains this:

~~~
ghc-options:
    # All packages
    "*": -j1
# some-package: -DSOME_CPP_FLAG
~~~

Is this ghc-option getting through to the right spot?  Is there anything else I could try?

**Comment by mgsloan** [comment]
The option is probably going through.  However, AFAIK `-j1` is already a ghc default.  It might be helpful to pass `-j1` to stack directly.

**Comment by mgsloan** [comment]
Closing as an old support issue.

**Comment by zwpaper** [comment]
I am trying to install intero, and meet the `ExitFailure (-9)` error too when building `Cabal-2.0.1.1`.
Error message:
```
--  While building custom Setup.hs for package Cabal-2.0.1.1 using:
      /root/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86
_64-linux/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure (-9) (THIS MAY INDICATE OUT OF MEMORY)
    Logs have been written to: /root/.stack/global-project/.stack-work/logs/Cabal-2.0.1.1.log
```

down there is build log:
```
```

**Comment by mgsloan** [comment]
`-j1` can help.  It is not surprising that 2G of memory is not enough.  If adding a swap file fixed it, then yes, definitely the issue was running out of memory.
