### ISSUE TITLE
User test -- don't know how to configure stack.yaml to download dependencies

### ISSUE THREAD

**Issue by kevinsullivan** [commercialhaskell/stack#302]
Hi. I can serve as an articulate new user. I'm evaluating languages and environments for possible use in an intro CS class this fall. I've so far stayed away from Haskell because of the complexity of getting it running properly on multiple platforms. Stack looks  promising. So far this AM I have it running on both Windows and a OS X. 

Here's where I'm now stuck: I want to use stack to compile and run a single-file Haskell program that depends on a library (here Graphics.UI.Gtk). I don't quite know how to get stack to download and install this dependency. In particular, I'm not sure quite how to configure stack.yaml so that "stack build" will do the right thing. If someone could take just a few seconds to tell me what changes to make to the default (empty) stack.yaml, I'd  appreciate it. The answer could perhaps also go into the nacent Wiki page on the stack.yaml file.

**Comment by snoyberg** [comment]
This *may* fall into the category of "you don't need to do anything." Did you try just running `stack install library-name` and see what happens?

**Comment by kevinsullivan** [comment]
Thanks. My understanding was that I would enter information into stack.yaml to specify packages on which my code depends, and that stack would then download and install those required packages. Is this correct?

On the other hand, in response to your suggestion, I tried explicitly installing the "gtk" library and then running "stack deps gtk" (not "stack install gtk"). It looked like it might work, but it failed with "Cannot find gtk2hsC2hs ... Please install `gtk2hs-buildtools` first and check that the install directory is in your PATH."

I am not certain how to extend my path to point to the newly installed files. Where are they?

I went ahead anyway and ran "stack deps gtkhs-buildtools" and that seems to have worked without error.

I then retried "stack deps gtk." It made more progress but eventually failed with "setup.exe: The program pkg-config version >=0.9.0 is required but it could not be found."

I'm assuming it's not found because I haven't set my path.

All of this is on Windows 7, by the way.

**Comment by kevinsullivan** [comment]
Further update. I switched from Windows to Ubuntu 14.04 (fresh install). 

- A fresh install of stack produced errors saying that libgmp couldn't be found. I used apt-get install to install it.
- The problem with cairo was that I had not installed gtk on my system. I installed gtk3 and gtk2. That got me past that error and through the installation of gtk.
- I still can't run my code. Two packages are missing **and I do not know what name to use with stack deps to get them installed** 

I thought that perhaps I needed to install gtkglext, but "stack deps gtkglext" returns an error saying that that package is unknown. Is stack searching the right repository to find this package?

Here's the error message I get when I try to "stack runghc Hello.hs"

Hello.hs:5:18:
    Could not find module ‘Graphics.UI.Gtk.OpenGL’
    Perhaps you meant
      Graphics.UI.Gtk.Gdk.GC (from gtk-0.13.7)
      Graphics.UI.Gtk.Cairo (from gtk-0.13.7)
      Graphics.UI.Gtk.Gdk.Gdk (from gtk-0.13.7)
    Use -v to see a list of the files searched for.

Hello.hs:7:8:
    Could not find module ‘Graphics.Rendering.OpenGL’
    Perhaps you meant
      Graphics.Rendering.Pango (from pango-0.13.1.0)
      Graphics.Rendering.Cairo (from cairo-0.13.1.0)
    Use -v to see a list of the files searched for.

**Comment by snoyberg** [comment]
@kevinsullivan Try upgrading to the latest release of stack (or, better yet, running from master on Github). Remember, this is beta software, so bugs are getting fixed fairly regularly.

I think you're getting confused about *system libraries* and *Haskell libraries*. stack does nothing about the former, but should install the latter for you without question. Don't worry about where things get installed, stack adds them to your PATH automatically. (If you're curious for its own sake, run `stack exec env`.)

On my system with latest stack, running `stack install cairo` automatically installs the necessary build tools and then builds the package successfully.

**Comment by snoyberg** [comment]
@kevinsullivan Did you have a chance to try this out on a newer stack?

**Comment by snoyberg** [comment]
Haven't heard feedback on this, closing.

**Comment by kevinsullivan** [comment]
THank you.
