### ISSUE TITLE
mktemp command in get.haskellstack.org fails on os x Yosemite 10.10.5

### ISSUE THREAD

**Issue by sordina** [commercialhaskell/stack#3021]
Reproduce:

> curl -sSL https://get.haskellstack.org/ | sh

Output:

	usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
				mktemp [-d] [-q] [-u] -t prefix
	Warning: Failed to create the file /osx-x86_64.bindist: Permission denied
	curl: (23) Failed writing body (0 != 16347)
	curl download failed: https://www.stackage.org/stack/osx-x86_64

The version of mktemp doesn't work in the fashion described, but there are several fixes that should be portable.

Apologies if this isn't the right place to report stack install script problems!

**Comment by borsboom** [comment]
@sordina: Thanks for the report!  Should be fixed now, please give it a try and re-open this issue if it still doesn't work.

**Comment by sordina** [comment]
@borsboom Thanks!
