### ISSUE TITLE
Dockerized stack-build quits during stack setup

### ISSUE THREAD

**Issue by ath** [commercialhaskell/stack#3025]
As I can’t do a stack setup under Windows 10, where GHCjs is used, I pulled `fpco/stack-build:lts-7.19` and mounted it via:
```
docker run --rm -it ^
  -v c:/Users/haskelluser/reflex-starter-master:/home/hskl/ghcjstest ^
  -v c:/Users/haskelluser/.docker-stack:/home/hskl/.stack ^
  -e "STACK_ROOT=/home/hskl/.stack" ^
  fpco/stack-build:lts-7.19
```
Note that the caret `^` allows to continue the current line in a .bat file.
On my local system I created an empty folder .docker-stack, which I mounted into the container. Now my plan was to run `stack setup` in this mounted folder. This works fine. However, as building ghcjs takes a very long time I would like to save the results, and downloaded files. This is why I mounted a folder into the container, as the .stack directory. So the stack inside docker would store its downloaded and compiled files, and next time when I run the image everything will be done immediately.

However, as soon stack (inside the docker) tries to save any file I get this error:
`hClose: hardware fault (Input/output error)`

When I don’t mount a windows folder into the container then this problem does not arise. I didn’t continue testing this, as I can’t accept recompile times of 30+ minutes, for _everything_, when I change a line of code in my own app. Always when I run a fresh container it wouldn’t find ghcjs and recompile it from scratch.

**Comment by borsboom** [comment]
Stack's Docker integration doesn't support Windows yet.
