### ISSUE TITLE
Cancelling fetching index cache causes subsequent stack commands to fail

### ISSUE THREAD

**Issue by manny-fp** [commercialhaskell/stack#303]
```
$ stack build
Downloaded lts-2.14 build plan.
Populated index cache.
Fetched package index.
^Cuser interrupt
$ stack build
Populating index cache ...truncated tar archive
$
```

**Comment by snoyberg** [comment]
@manny-fp Confirmed?

**Comment by bitonic** [comment]
I encountered this as well.  Is this solved in a recent `stack` version?  I'm installing mine from the Ubuntu 14.04 repositories.

**Comment by bitonic** [comment]
And for people with the same problem, the workaround is to

    rm ~/.stack/indices/Hackage/00-index.tar

**Comment by rvion** [comment]
@bitonic 

> Is this solved in a recent stack

yes: https://github.com/commercialhaskell/stack/commit/4849bb44f98728e1f6824fdb64447497dbdb2f66

**Comment by bitonic** [comment]
@rvion 

I'm running
```
vagrant@v ~/src/fpco/smart-device-sw (git)-[master] % stack --version
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911 (dirty)
```

which includes that fix, and I still stumbled upon this problem.  Maybe it's not exactly the same issue as what @manny-fp encountered, but the fact that it was solved by removing that `tar` file makes me think it's a related issue.
