### ISSUE TITLE
Submitting bindists for inclusion?

### ISSUE THREAD

**Issue by iand675** [commercialhaskell/stack#3030]
### General summary/comments (optional)

I'd like to provide an OSX + GHC 8.0.2 integer-simple bindist, but I'm not clear on where to submit it or if there's anything special I have to do besides configure, make, and tar my build.

Any guidance on this would be appreciated.

**Comment by borsboom** [comment]
Basic steps to follow:

- Adapt the process here to build a bindist: https://docs.haskellstack.org/en/stable/MAINTAINER_GUIDE/#building-ghc

- Make a local copy of [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml)

- Edit your local `stack-setup-2.yaml` to add your bindist

- Use `stack setup --setup-info-yaml=<PATH-TO-FILE>` to test that it is installed correctly.

- Submit a PR to https://github.com/fpco/stackage-content with the updated `stack-setup-2.yaml`, and ping me (@borsboom) on it.

I'll copy your bindist to our CDN and adjust the stack-setup-2.yaml to reference the CDN before merging, so we don't end up using a bunch of your bandwidth.

**Comment by mgsloan** [comment]
Closing as a support issue.
