### ISSUE TITLE
stack ghci fails for a package with RebindableSyntax

### ISSUE THREAD

**Issue by michalkonecny** [commercialhaskell/stack#3043]
### Steps to reproduce

1. Write a simple cabal package with the RebindableSyntax extension (see a minimal example [test.zip](https://github.com/commercialhaskell/stack/files/818953/test.zip), also listed below)
2. Write a minimal stack.yaml with resolver lts-8.3 (an example is in the zip file, also listed below)
3. Run command `stack repl`

The bug does not occur with an older resolver. I tested it with lts-6.5.

```
$ cd test
$ cat stack.yaml
resolver: lts-8.3
packages:
- '.'
$ cat Test.hs
module Test where
$ cat test.cabal
name:           test
version:        0.1.0.0
build-type:     Simple
cabal-version: >= 1.2

library
  hs-source-dirs:  .
  build-depends:
    base == 4.*
  extensions:
    RebindableSyntax
  exposed-modules:
    Test
```

### Expected

```
$ stack repl
...
*Test Test>
```

### Actual

```
$ stack repl
test-0.1.0.0: configure (lib)
Configuring test-0.1.0.0...
test-0.1.0.0: initial-build-steps (lib)
Configuring GHCi with the following packages: test
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help

<interactive>:1:6: error: Not in scope: ‘>>’

<interactive>:1:70: error: Not in scope: ‘>>’

<interactive>:1:135: error: Not in scope: ‘return’
```

A log of a run with `--verbose`:  [log.txt](https://github.com/commercialhaskell/stack/files/818955/log.txt)

### Stack version

```
$ stack --version
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment]
@michalkonecny Good catch!  Looks like an upstream ghc issue - https://ghc.haskell.org/trac/ghc/ticket/13385#ticket
