### ISSUE TITLE
Update to use ghc from the edge testing repository for alpine linux vagrantfile

### ISSUE THREAD

**Issue by mitchty** [commercialhaskell/stack#3045]
Opening this issue as an alert to anyone on github that appears to be using my ghc port.

Ghc and cabal are now upstreamed for x86_64 on alpine linux edge. Ghc requires alpine linux 3.5 or higher to run. But otherwise the upstreamed package is the same as my old port. With a caveat that the profiled ghc libraries are now in a sub package named ghc-dev.

Either add the edge testing repository to /etc/apk/repositories, or alternatively you may install ghc/cabal via:
```
# apk --no-cache add --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing ghc ghc-dev cabal
```

For an up to date list of what is ported and where reference this search:
https://pkgs.alpinelinux.org/packages?name=&branch=&repo=&arch=&maintainer=Mitch+Tishmack

As a side note for stack specifically, I added a flag to the stack cabal file that makes it easy to build stack statically.
https://github.com/commercialhaskell/stack/commit/cda4c091a95b9753818bebb0530cfa460b5f039b

The way stack is being built statically in this vagrantfile is unnecessary, and the c runtime changes are also unnecessary and will only produce a larger static binary. Recommend you change to using the existing flag instead of the glibc gcc runtime hacks in use here.

Also note, I also ported upx to alpine edge, so you can also add upx from the edge testing repo if you want to test and validate that as well. Note however, upx does NOT compress dynamic musl binaries however, this is a upx limitation not the ports.

**Comment by borsboom** [comment]
Ok, I'll take all of this into consideration when building the static binary for the next stack release (likely happening this week).

**Comment by borsboom** [comment]
Looks like only GHC 8.0.2 is in the edge testing repository, so I'll hold off using this for the v1.4.0 release (which still needs GHC 7.10.3).  I expect the next release after this will be built with GHC 8.0.2.
