### ISSUE TITLE
'You are not the owner of .stack-work/. Aborting to protect file permissions.'

### ISSUE THREAD

**Issue by tsoernes** [commercialhaskell/stack#3048]
I'm getting this error:
```
You are not the owner of '<somedir>.stack-work/'. Aborting to protect file permissions.
Retry with '--allow-different-user' to disable this precaution.
```
I have tried `chown -R tsoernes somedir` and `chmod -R 777 somedir` but it does not help. 
`--allow-different-user` does work, but causes issues with `ghc-mod` and is very tiresome to type.
I found similar reports of this issue, but contrary to them all I'm **not** running docker.

Note: somedir is on a mounted NTFS disk containing Windows.

Fedora 25 x64 4.9
Stack Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 

```
drwxrwxrwx. 1 root root    0 Mar  7 01:14 app
drwxrwxrwx. 1 root root 4.0K Mar  6 21:09 dist
-rwxrwxrwx. 1 root root 1.5K Mar  5 23:09 LICENSE
-rwxrwxrwx. 1 root root   46 Mar  5 23:09 Setup.hs
drwxrwxrwx. 1 root root 4.0K Mar  6 02:20 src
drwxrwxrwx. 1 root root    0 Mar  5 23:17 .stack-work
-rwxrwxrwx. 1 root root 2.2K Mar  6 21:30 stack.yaml
drwxrwxrwx. 1 root root    0 Mar  5 23:09 test
-rwxrwxrwx. 1 root root 1.1K Mar  6 21:07 W5.cabal

# in project folder: 
$ stack --allow-different-user exec -- whoami 
tsoernes
# in homedir where --allow-different-user is not necessary: 
$ stack exec -- whoami 
tsoernes


$ which stack
/usr/local/bin/stack
$ lsl /usr/local/bin
-rwxr-xr-x. 1 root root  21M Mar  2 00:54 stack

```
Project `stack.yaml` contains `resolver: lts-7.19`, the rest is default (blank).

**Comment by mgsloan** [comment]
You can put `allow-different-user: true` in your `$STACK_ROOT/config.yaml`, and have it work everywhere.  See https://docs.haskellstack.org/en/stable/yaml_configuration/#allow-different-user

Does it really cause issues with ghc-mod, or is it just that ghc-mod also errors out in this situation?  Maybe report to the ghc-mod bug tracker?
