### ISSUE TITLE
stack ide integration service

### ISSUE THREAD

**Issue by krgn** [commercialhaskell/stack#305]
`stack`s approach to handling packages and the dependency tree breaks (all?) existing tools that rely on cabal for providing mechanisms such as code completion, extract type at point and go-to definition to name a few. 
Hence I propose to integrate a json web service that exposes this type of information. The command could be called `stack boot` and could include a `-w` flag* to enable watching for changes in the cabal file/source code.

[*] this flag could also be made global and exposed as a hook in different parts of the application to support other behavior proposed  [here](https://github.com/commercialhaskell/stack/issues/113)

**Comment by snoyberg** [comment]
I know I'd like to see something like this. There's also a related issue at #232 for ide-backend-client support.

@chrisdone and @mgsloan, do either of you have thoughts on this one?

**Comment by gregwebs** [comment]
Don't the tools that run cabal just need to be configured to run stack? Ultimately they both use Cabal and GHC

**Comment by snoyberg** [comment]
That's entirely possible. Let me go on record as saying I know next to nothing about how those tools work since I don't use them myself (yes, I know I should start using them.... I'm lazy :) ). So take anything I say here with a big grain of salt.

**Comment by chrisdone** [comment]
@krgn 
> the dependency tree breaks (all?) existing tools that rely on cabal for providing mechanisms such as code completion

@gregwebs 
> Don't the tools that run cabal just need to be configured to run stack? Ultimately they both use Cabal and GHC

With haskell mode I just run `stack exec ghci-ng` and I still have type information and go to definition, etc. so that still works fine.

However, moving forward, integrating with ide-backend, either via ide-backend-client or directly via a plugin e.g. `stack ide-backend` or whatever would be ideal. This issue duplicates #232 so it should probably be closed.

**Comment by snoyberg** [comment]
Again, speaking from ignorance: is there a reason why someone would specifically want to use an existing tool instead of the work we're planning on doing with ide-backend-client?

**Comment by chrisdone** [comment]
hdevtools and ghc-mod already have Emacs, Sublime and Vim integration and for those who've gotten it working they're likely to want to keep using it. I think it's a small portion of the community, though, compared to the mass of people coping with a dumb "edit, recompile' workflow.

**Comment by krgn** [comment]
I'd be happy to give a hand with this if a consensus emerges which service to integrate with. It would be neat if such a service could be integrated with `stack` itself, as this makes things considerably easier for users without an intricate knowledge of the available tooling in the haskell ecosystem. Without having looked at `ide-backend-client` in great detail (and having looked at some alternatives) it seems it could be the way forward. If so, this issue should probably be closed.

**Comment by krgn** [comment]
Ah sorry, I just read the other related ticket and realized somebody is already on it. Closing.
