### ISSUE TITLE
stack image container's weird behavior

### ISSUE THREAD

**Issue by pythonissam** [commercialhaskell/stack#3050]
### General summary/comments (optional)

My understanding is that
`stack image container` embeds a normal executable into an image and 
`stack --docker image container` embeds an executable created in a container.

I found that
`stack --docker image container` doesn't include an executable if there were no executables.
However, `stack image container` **builds an executable to include it** if there were no executables.

I'm so confused with this behavior. Why is it like this?

### Steps to reproduce

For example:

1. Use `fpco/stack-run` as a base image
2. Run `stack image container`
3. Set an entry point to that created executable

### Expected
No build with `stack image container` command

### Actual

It builds a normal executable to embed it into an image.

### Stack version

```
$ stack --version
Version 1.3.2 x86_64 hpack-0.15.0
```

### Method of installation

* Via apt-get; `apt-get install haskell-stack`

**Comment by mgsloan** [comment]
> stack --docker image container embeds an executable created in a container.

Hmm, yeah, I think that's the case.

> However, stack image container builds an executable to include it if there were no executables.

Not sure if I follow.  So there are no executable stanzas in your .cabal but it is putting one into the container?

The difference in behavior could be due to `stack image container` defaulting to using all executables from `stack path --local-bin`.  This path will be different when docker is enabled.  So, perhaps locally you already have some executables in the bin dir, even if you don't have executables in the project.

I've committed a change which notifies the user of this behavior, when `executables` is not specified for a container - https://github.com/commercialhaskell/stack/commit/203b319d9eb1ea8342b4635b731074057817db83

**Comment by pythonissam** [comment]
Excuse me. My description wasn't good. Though your commit would be helpful, an `executable` I meant is **the `app` of a project**.

Suppose we haven't build our app and these commands below returns no locations.
```
$ stack exec -- which ourapp
$ stack --docker exec -- which ourapp
```

Then,

```
$ stack image container
```
This command **would build `ourapp`** and create an image embedding `ourapp` built on the host into.
If we type
```
$ stack exec -- which ourapp
```
This command would show its path somewhere in `.stack-work/`.

But if we run
```
$ stack --docker image container
```
This command **won't build `ourapp`** and therefore won't embed `ourapp` into an image.
Also,
```
$ stack --docker -- which ourapp
```
doesn't show its location.

I know we can build Docker's image using following commands:
```
$ stack --docker build
$ stack --docker image container
```

But why don't we need to build `ourapp` when we execute `stack image container`?
This is my question. Is this intended? Thank you.

**Comment by mgsloan** [comment]
Hmm, no, I don't think that's intended.  For me it seems to work - the executable builds with and without `--docker`.

Could you please create a git repo or tarball of a minimal reproduction of the issue?

**Comment by pythonissam** [comment]
[ourapp.tar.gz](https://github.com/commercialhaskell/stack/files/849697/ourapp.tar.gz)

Sure. Please use this and follow what I mentioned.

**Comment by mgsloan** [comment]
Thanks for the repro tarball!  Even then I can't reproduce it :/

```
mgsloan@computer:~/fpco/test-stack/issue3050/ourapp$ stack --docker exec -- which ourapp
mgsloan@computer:~/fpco/test-stack/issue3050/ourapp$ stack --docker image container
Warning: File listed in ourapp.cabal file does not exist: README.md
ourapp-0.1.0.0: unregistering (old configure information not found)
ourapp-0.1.0.0: configure (lib + exe)
Configuring ourapp-0.1.0.0...
ourapp-0.1.0.0: build (lib + exe)
Preprocessing library ourapp-0.1.0.0...
In-place registering ourapp-0.1.0.0...
Preprocessing executable 'ourapp' for ourapp-0.1.0.0...
Linking .stack-work/dist/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/Cabal-1.22.5.0/build/ourapp/ourapp ...
Warning: File listed in ourapp.cabal file does not exist: README.md
ourapp-0.1.0.0: copy/register
Installing library in
/home/mgsloan/fpco/test-stack/issue3050/ourapp/.stack-work/install/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/lts-6.23/7.10.3/lib/x86_64-linux-ghc-7.10.3/ourapp-0.1.0.0-3YzTjqL5jTHAw7btmgrE0Q
Installing executable(s) in
/home/mgsloan/fpco/test-stack/issue3050/ourapp/.stack-work/install/x86_64-linux-dkda49f7ca9b244180d3cfb1987cbc9743/lts-6.23/7.10.3/bin
Registering ourapp-0.1.0.0...
```

One thing to note is that I'm using stack-1.4.0 whereas you are on 1.3.2.  Perhaps upgrading will fix the problem?

**Comment by pythonissam** [comment]
Agh... I finally figured out what the cause is. It seems that I forgot to `stack --docker clean` app while I did clean a normal version. Thank you for carefully considering my request and I apologize for taking your time.

**Comment by mgsloan** [comment]
Glad things are working properly!
