### ISSUE TITLE
Segfault with official Stack ARM binary

### ISSUE THREAD

**Issue by Phyks** [commercialhaskell/stack#3051]
Hi,

### General summary/comments (optional)

I am trying to install Haskell Stack on a Raspberry Pi (first iteration). I came across http://allocinit.io/haskell/haskell-on-raspberry-pi-3/ and https://github.com/commercialhaskell/stack/pull/2857 which makes me think it is indeed possible to run Haskell Stack on a Raspberry Pi. However, I am getting a segfault.

### Steps to reproduce

1. curl -sSL https://get.haskellstack.org/ | sh
2. Stack is installed correctly in `/usr/local/bin/stack`. Try to run any `stack` command (`stack upgrade`, `stack setup` etc), there is a segfault.

### Stack version

```
$ stack --version
Latest installed by get.haskellstack.org as of today.
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

Thanks!

**Comment by flounders** [comment]
I don't think anything less than ARMv7 is supported at this point. Stack is installed on my Raspberry Pi 2 B running Arch, but the shell script failed to detect that it was an ARMv7 chip, and it just gave me an Intel binary. You can check this by running file on /usr/local/bin/stack. What I had to do was manually install from the releases page [here](https://github.com/commercialhaskell/stack/releases). It's still not quite working for me yet, but at least it's not segfaulting. You may have success at this point.

**Comment by Phyks** [comment]
Seems to be ok concerning the arch of the binary file:

```
/usr/local/bin/stack: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, BuildID[sha1]=a6a1c2b73b931880a43c964a64139956f8588bd9, stripped
```


> I don't think anything less than ARMv7 is supported at this point.

I guess you are right, but there is no mention of this anywhere. :/

**Comment by borsboom** [comment]
A PR in the docs making them clearer would be welcome (as would a PR on the [get-stack.sh](https://github.com/commercialhaskell/stack/blob/master/etc/scripts/get-stack.sh) to make it detect the architecture properly).  ARMv7 isn't really "officially" supported because there are still too many major pain points; we just release the binary as a convenience to make it less painful for folks to bootstrap it.
