### ISSUE TITLE
Unable to install stack-run on Windows 7 64bit

### ISSUE THREAD

**Issue by fstiffo** [commercialhaskell/stack#3053]
Official binary, downloaded from stackage.org or fpcomplete's package repository Windows 64-bit

OS: Windows 7 64-bit

Stack version:
Version 1.3.2, Git revision 3f67514 x86_64 hpac
k-0.15.0

my command:
install stack-run

gives this error:

Error: While constructing the build plan, the following exceptions were encounte red: In the dependencies for unix-2.7.2.1: unbuildable must match <0, but the stack configuration has no specified vers ion Plan construction failed.

**Comment by fstiffo** [comment]
Official binary, downloaded from stackage.org or fpcomplete's package repository Windows 64-bit

OS: Windows 7 64-bit

Stack version:
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 x86_64 hpac
k-0.15.0

my command: 
install stack-run

gives this error: 

Error: While constructing the build plan, the following exceptions were encounte red:  In the dependencies for unix-2.7.2.1:     unbuildable must match <0, but the stack configuration has no specified vers ion  Plan construction failed.

**Comment by mgsloan** [comment]
`stack-run` depends on `vty` which depends on the `unix` package, which isn't supported on windows - see https://hackage.haskell.org/package/vty .  Perhaps bring up windows support in the stack-run tracker? https://github.com/yamadapc/stack-run
