### ISSUE TITLE
~/.ssh: createSymbolicLink: already exists (File exists)

### ISSUE THREAD

**Issue by smobs** [commercialhaskell/stack#3056]
### Steps to reproduce

Run `stack build`

stack.yaml:
```
resolver: lts-8.5
docker:
  enable: true
  require-docker-version: "> 17.0"
```
### Expected

Docker building

### Actual

```
stack build --verbose
Version 1.4.1, Git revision bac50451b559a8ad4cf8d40b56ea007cf4154324 x86_64 hpack-0.17.0
2017-03-12 22:28:28.125324: [debug] Checking for project config at: /Users/toby/ElmGame/stack.yaml
@(Stack/Config.hs:935:9)
2017-03-12 22:28:28.126457: [debug] Loading project config file stack.yaml
@(Stack/Config.hs:960:13)
2017-03-12 22:28:28.128904: [debug] Run process: /usr/local/bin/docker --version
@(System/Process/Read.hs:306:3)
2017-03-12 22:28:28.147971: [debug] Process finished in 18ms: /usr/local/bin/docker --version
@(System/Process/Read.hs:306:3)
2017-03-12 22:28:28.148524: [debug] Run process: /usr/local/bin/docker inspect fpco/stack-build:lts-8.5
@(System/Process/Read.hs:306:3)
2017-03-12 22:28:28.176492: [debug] Process finished in 27ms: /usr/local/bin/docker inspect fpco/stack-build:lts-8.5
@(System/Process/Read.hs:306:3)
/Users/toby/.ssh: createSymbolicLink: already exists (File exists)
```

### Stack version

```
stack --version
Version 1.4.1, Git revision bac50451b559a8ad4cf8d40b56ea007cf4154324 x86_64 hpack-0.17.0
```
Originally encountered on stack 1.3.2

### Docker version

```
docker --version
Docker version 17.03.0-ce, build 60ccb22
```

### OS 

OSX 10.11.4

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository
* (1.4.1) `stack upgrade --git --source-only`

**Comment by borsboom** [comment]
Is this your first time using Stack's docker support for this project, or did it work in the past but has stopped working since upgrading Stack?

**Comment by smobs** [comment]
I had it working with docker on vagrant a while back (stack 1.1 perhaps).

**Comment by borsboom** [comment]
Was that in the same project on the same system with the same `.stack-work` directory?

**Comment by smobs** [comment]
Same project, same system, same directory. May have nuked .stack-work at
some point.

**Comment by borsboom** [comment]
I might suggest trying moving `.stack-work/docker` out of the way (rename it, in case we want to see what's in the old one later) and see if that helps.

**Comment by smobs** [comment]
Aha that looks like it's fixed it (or rather I've hit another error because there is no tag for 1.4.1).
I'm reinstall 1.3.2 and will confirm that that works.
Thank you for your help.

**Comment by smobs** [comment]
Awesome that is working. 
Thank you very much.
