### ISSUE TITLE
stack build --verbose doesn't call cabal configure with -v3

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3061]
Using stack-1.4.0 on Windows x64:

1. Using any project (I picked HLint)
2. `touch hlint.cabal`
3. `stack build --only-configure --verbose`

I expect `configure` to be called with `-v3` (debug level verbosity), but instead I get a lot of information about what stack does, but nothing on what `configure` did. This issue is compounded by #1438, which means I can't just pass `-v3` myself.

**Comment by sjakobi** [comment]
There's a separate flag `--cabal-verbose` for that. Does that one fit your needs?

**Comment by ndmitchell** [comment]
Thanks, that's what I was looking for, but entirely failed to find.
