### ISSUE TITLE
Cannot run stack exec as other non root users

### ISSUE THREAD

**Issue by eborden** [commercialhaskell/stack#3062]
### General summary/comments (optional)
After upgrading stack I can no longer run `stack exec` from another user via `sudo -u some_other_user`

### Steps to reproduce
1. `sudo -u some_non_root_user stack exec my_project`

as well

1. `sudo -u some_non_root_user stack update`

### Expected

Previously this has run without issue.

### Actual

Previously I had run `sudo -u some_other_user stack exec my_project` and it worked fine, but now I am getting:

```
Populated index cache.    
~/.stack/indices/Hackage/00-index.cache: openBinaryFile: permission denied (Permission denied)
```

This seemed like issue #303, which recommends:
```
$ rm ~/.stack/indices/Hackage/00-index.tar
```

This then results in:

```
Fetching package index ...error: cannot open .git/FETCH_HEAD: Permission denied                           

Process exited with ExitFailure 255: /usr/bin/git --git-dir=.git fetch --tags
Failed to fetch package index, retrying.
~/.stack/indices/Hackage/git-update/all-cabal-hashes/.git/config: removeDirectoryRecursive: permission denied (Permission denied)
```

After digging around this led me to issue #2426, which eventually led to
```
rm -rf ~/.stack/indices/Hackage/git-update/all-cabal-hashes
```

Which results in:
```
Updating package index Hackage (mirrored at https://github.com/commercialhaskell/all-cabal-hashes.git) ...Running /usr/bin/git clone https://github.com/commercialhaskell/all-cabal-hashes.git all-cabal-hashes/ -b display in directory /home/eborden/.stack/indices/Hackage/git-update/ exited with ExitFailure 128


fatal: could not create work tree dir 'all-cabal-hashes': Permission denied
```

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

### Method of installation
* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by eborden** [comment]
It seems there is also related https://github.com/commercialhaskell/stack/issues/2188

**Comment by mgsloan** [comment]
Hmm, what does `sudo -u some_non_root_user stack --version` say?  Since `sudo -u` changes the PATH it's possible that it is using a different version of stack.  In particular, it won't see `~/.local/bin`.

**Comment by eborden** [comment]
Good question!
```
$ sudo -u some_non_root_user stack --version                                                                       
Version 1.3.2, Git revision 3f675146590da4f3edf768b89355f798229da2a5 (4395 commits) x86_64 hpack-0.15.0
```

It seems it is out of sync.

**Comment by eborden** [comment]
```
$ sudo -u some_non_root_user which stack
/usr/bin/stack
```
vs
```
$ which stack
~/.local/bin/stack
```

**Comment by eborden** [comment]
Looks like that fixed it :) Thank you very much.
