### ISSUE TITLE
Allow setting STACK_WORK as a global env for --work-dir

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/stack#3063]
Dealing with `MAX_PATH` issue on windows mean setting short `STACK_ROOT`, but working directory also can trigger the limit.

See https://github.com/commercialhaskell/stack/issues/1947

Currently I pass `--work-dir` to all stack commands, but it would be more convenient to also set `STACK_WORK`.

**Comment by mgsloan** [comment]
Sure, I've added support for a `STACK_WORK` env var.

**Comment by domenkozar** [comment]
Thanks!
