### ISSUE TITLE
Request: change to ghc-7.10.3 settings

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#3072]
On ubuntu 16.10 and up, and debian testing, there is a linker problem under some circumstances:

https://ghc.haskell.org/trac/ghc/ticket/12147

This can be sorted out by changing the `settings` file for GHC 7.10.3 to

```
 ("C compiler flags", "-fno-PIE -fno-stack-protector -Wa,-mrelax-relocations=no"),
```

**Comment by borsboom** [comment]
Is there a set of GHC bindist `./configure` options or environment variables that will achieve that?

**Comment by alanz** [comment]
I have not idea. I just edited the file directly, after some discussion on IRC in #ghc

**Comment by borsboom** [comment]
Stack should already be setting some no-pie options on Ubuntu 16.10: https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml#L210

**Comment by alanz** [comment]
its not the no-pie, its the `-Wa,-mrelax-relocations=no` that is needed in this case.

**Comment by alanz** [comment]
In addition to the existing `no-pie`

**Comment by borsboom** [comment]
@alanz Do you think those should be applied to all no-pie distros, or is this Ubuntu 16.10 specific?  I try to avoid adding more platform variations unless necessary as each one increases the maintenance and testing burden.

**Comment by alanz** [comment]
I would imagine so. The original thread discussing this noted it on Arch Linux and Ubuntu, and I hit it on Debian testing. It is the underlying binutils or whatever that are used everywhere.

See the whole thread at https://github.com/DanielG/ghc-mod/issues/762#issuecomment-213743585

**Comment by borsboom** [comment]
Can you try making a local copy of [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml), adjusting the configure options for the `linux..-nopie` variants as you see fit, and then use `stack setup --stack-setup-yaml=<<PATH-TO-LOCAL-FILE>>` to test it?  You should move your current `~/.stack/programs` out of the way first.  If that works, please open a PR against the fpco/stackage-content repo with the changes.

**Comment by alanz** [comment]
I am travelling at the moment with bad connectivity. I will do this when I get back, early next week.

**Comment by lwm** [comment]
Any updates @alanz?

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because the `master` branch version of Stack does not support LTS < 12.0.
