### ISSUE TITLE
Is it possible to use cpp preprocessors

### ISSUE THREAD

**Issue by apolishch** [commercialhaskell/stack#3075]
Is it possible to use cpp preprocessors,

e.g:

```{-# LANGUAGE CPP #-}
module MyModule (
  main
  #ifdef TEST
    ,functionUnderTest
    ,functionAlsoUnderTest
  #endif
  ) where ....```


with cabal, the following settings in .cabal appear to work:
```cpp-options:         -DTEST``` 
is it possible to reproduce this with stack?

**Comment by mgsloan** [comment]
Sure, stack uses .cabal files, so it works the same.  Often `cpp-options` are put under cabal conditionals.  For example, when building stack itself, if you pass `--flag stack:hide-dependency-versions`, it'll enable the HIDE_DEP_VERSIONS flag.  See https://github.com/commercialhaskell/stack/blob/master/stack.cabal#L327

**Comment by VictorYYW** [comment]
I have a question that might be a little relevant. When Stack builds dependencies (snapshot packages), would the cpp preprocessors specified here be use?
