### ISSUE TITLE
ghc build tool absent from the build plan

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#308]
While trying to build cabal with stack (haha), I get the following:

```
% stack build
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      ghc: needed (-any), but not present in build plan
    needed for package: HTTP-4000.2.19

--  Failure when adding dependencies:    
      HTTP: needed (>=4000.2.5 && <4000.3), but couldn't resolve its dependencies
    needed for package: cabal-install-1.23.0.0

--  While attempting to add dependency,
    Could not find package ghc in known packages
```

**Comment by feuerbach** [comment]
Looking at `HTTP.cabal`, `ghc` refers to a build tool, not to the ghc package.

**Comment by snoyberg** [comment]
Can you paste your stack.yaml file?

**Comment by feuerbach** [comment]
``` yaml
resolver: lts-2.9
packages: ["Cabal", "cabal-install"]
```

**Comment by snoyberg** [comment]
I'm not reproducing. What version of stack are you running (`stack --version`)?

**Comment by feuerbach** [comment]
```
% stack --version
Version 0.0.1.1, Git revision 03097806d88d700b94b6152e73ff2d78be95010f (dirty)
```

**Comment by feuerbach** [comment]
In case it wasn't clear, I'm doing this in a git checkout of the cabal repo (commit 0c353c1c68cd928b93a79d31ffc633c866f82766).

**Comment by snoyberg** [comment]
I tried that commit for both stack and cabal, and was unable to reproduce the issue. What's your output of `stack exec env | grep PATH` in the cabal directory? And would you be able to test with the most recent stack master?

**Comment by feuerbach** [comment]
Here's the (somewhat filtered) output:
```
GHC_PACKAGE_PATH=/home/feuerbach/prog/cabal/.stack-work/install/x86_64-linux/lts-2.9/7.8.4/pkgdb/:/home/feuerbach/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/pkgdb/:/home/feuerbach/.stack/programs/x86_64-linux/ghc-7.8.4/lib/ghc-7.8.4/package.conf.d/
PATH=/home/feuerbach/prog/cabal/.stack-work/install/x86_64-linux/lts-2.9/7.8.4/bin:/home/feuerbach/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/bin:/home/feuerbach/.stack/programs/x86_64-linux/ghc-7.8.4/bin:/home/feuerbach/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/bin:/home/feuerbach/.local/bin:[...]
```

I'll try stack master.

**Comment by snoyberg** [comment]
Hmm, especially strange given that you're using the stack-installed GHC like I am, and on the some OS/architecture.

**Comment by feuerbach** [comment]
I can reproduce with stack master

**Comment by snoyberg** [comment]
Just to confirm: have you tweaked your package index in any way? Or are you using the standard package index configuration?

**Comment by feuerbach** [comment]
Nope, everything should be standard.

Perhaps you could add some debug output for that code path?

**Comment by snoyberg** [comment]
There's already `--verbose`, could you copy that in?

**Comment by feuerbach** [comment]
I know, but it doesn't tell much at the moment.

```
% stack build --verbose
2015-06-15 11:36:34.678916: [debug] Checking for project config at: /home/feuerbach/prog/cabal/stack.yaml @(stack-0.0.2:Stack.Config src/Stack/Config.hs:560:9)
2015-06-15 11:36:34.679047: [debug] Loading project config file stack.yaml @(stack-0.0.2:Stack.Config src/Stack/Config.hs:581:13)
2015-06-15 11:36:34.68455: [debug] Run process: ghc --numeric-version @(stack-0.0.2:System.Process.Read src/System/Process/Read.hs:235:3)
2015-06-15 11:36:34.703481: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack-0.0.2:System.Process.Read src/System/Process/Read.hs:235:3)
2015-06-15 11:36:34.71737: [debug] Run process: ghc-pkg --no-user-package-db list --global @(stack-0.0.2:System.Process.Read src/System/Process/Read.hs:235:3)
2015-06-15 11:36:34.734553: [debug] Run process: ghc-pkg --no-user-package-db --package-db=/home/feuerbach/.stack/programs/x86_64-linux/ghc-7.8.4/lib/ghc-7.8.4/package.conf.d/ describe Cabal @(stack-0.0.2:System.Process.Read src/System/Process/Read.hs:235:3)
2015-06-15 11:36:34.748377: [debug] Checking resolver: lts-2.9 @(stack-0.0.2:Stack.Build.Source src/Stack/Build/Source.hs:66:13)
2015-06-15 11:36:34.957097: [debug] Run process: ghc-pkg --global --no-user-package-db dump --expand-pkgroot @(stack-0.0.2:System.Process.Read src/System/Process/Read.hs:235:3)
2015-06-15 11:36:34.99157: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /home/feuerbach/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/pkgdb/ dump --expand-pkgroot @(stack-0.0.2:System.Process.Read src/System/Process/Read.hs:235:3)
2015-06-15 11:36:35.083685: [debug] Run process: ghc-pkg --user --no-user-package-db --package-db /home/feuerbach/prog/cabal/.stack-work/install/x86_64-linux/lts-2.9/7.8.4/pkgdb/ dump --expand-pkgroot @(stack-0.0.2:System.Process.Read src/System/Process/Read.hs:235:3)
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      ghc: needed (-any), but not present in build plan
    needed for package: HTTP-4000.2.19

--  Failure when adding dependencies:    
      HTTP: needed (>=4000.2.5 && <4000.3), but couldn't resolve its dependencies
    needed for package: cabal-install-1.22.0.0

--  While attempting to add dependency,
    Could not find package ghc in known packages
```

**Comment by snoyberg** [comment]
Can you try running with the 308-debugging branch? Also, what's the output for `stack exec ghc-pkg list ghc`?

**Comment by feuerbach** [comment]
```
% stack exec ghc-pkg list ghc
/home/feuerbach/.stack/programs/x86_64-linux/ghc-7.8.4/lib/ghc-7.8.4/package.conf.d/
   ghc-7.8.4
/home/feuerbach/.stack/snapshots/x86_64-linux/lts-2.9/7.8.4/pkgdb/
/home/feuerbach/prog/cabal/.stack-work/install/x86_64-linux/lts-2.9/7.8.4/pkgdb/
```

**Comment by feuerbach** [comment]
https://gist.github.com/a8b355f88c38a8649c10

**Comment by snoyberg** [comment]
Reviewing, I'll probably push another commit and ask for another run of output. Thanks for stepping through this :)

**Comment by snoyberg** [comment]
Weird, you don't have `ghc` in your `installedMap`, but I do.

**Comment by snoyberg** [comment]
Alright, what's the output of:

```
/home/feuerbach/.stack/programs/x86_64-linux/ghc-7.8.4/bin/ghc-pkg --global --no-user-package-db dump --expand-pkgroot
```

And please try out the latest commit on the branch.

**Comment by feuerbach** [comment]
https://gist.github.com/dfba36a4e1c1517cef85

**Comment by feuerbach** [comment]
and https://gist.github.com/a63b828ea6cefc57f092

**Comment by snoyberg** [comment]
Well, part of this sort of makes sense: if you're working on the Cabal package, you can't use the global Cabal, which with GHC 7.8 means you can't use the ghc library (which depends on it). I'm still not certain why (1) I don't reproduce, and (2) it's trying to install HTTP-package tests.

**Comment by feuerbach** [comment]
That's true, but another source of the problem seems to be that stack doesn't distinguish between ghc-the-package and ghc-the-build-tool.

**Comment by snoyberg** [comment]
I can special-case that, but it's not a bug as-is. The Cabal format doesn't tell you what build-tools mean, so that "ghc" could mean "the executable ghc," "the system package ghc," or "the Haskell package ghc which provides a differently-named executable." I believe all of those exist today on Hackage.

Looking at HTTP.cabal, the build-tool dep on ghc is in the library, not the test suite (not sure why I thought it was the latter). That's bizarre, there's no reason for it.

Anyway, special-casing ghc seems like the right thing to do here. That's an easy fix.

**Comment by snoyberg** [comment]
OK, I was able to reproduce by using an empty snapshot database. Alright, special casing it will be. I've just pushed to master, can you confirm that this fixes it for you?

**Comment by feuerbach** [comment]
> The Cabal format doesn't tell you what build-tools mean, so that "ghc" could mean "the executable ghc," "the system package ghc," or "the Haskell package ghc which provides a differently-named executable." I believe all of those exist today on Hackage.

Can you point me to some examples of build-tool referring specifically to installed libraries?

**Comment by snoyberg** [comment]
I thought gtk and cairo depended on gtk2hs-buildtools by name, but upon checking that appears to be wrong. Perhaps we can simplify our logic then in generating the tool map and assume it's referring to executable names.

At least part of the problem is that the [buildTools](http://haddock.stackage.org/lts-2.14/Cabal-1.18.1.5/Distribution-PackageDescription.html#v:buildTools) field is defined as `[Dependency]`, which is explicitly based on `PackageName`.

**Comment by feuerbach** [comment]
I confirm that stack master works for me.

> Perhaps we can simplify our logic then in generating the tool map and assume it's referring to executable names.

That sounds right to me.

**Comment by snoyberg** [comment]
I'll make that change to the code base, and add a note referring to this conversation.
