### ISSUE TITLE
The download break, need resume download ,do not try to download from zero

### ISSUE THREAD

**Issue by netroby** [commercialhaskell/stack#3085]
I am try to download ghc with stack, the network not stable, and the download progress was broken, 
I tried again, the download progress start from zero..

```bash
PS C:\Users\huzhifeng> stack runghc --install-ghc
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
ghc-8.0.2:    3.67 MiB / 142.18 MiB (  2.58%) downloaded...Error_Packet "partial packet: expecting 16384 bytes, got: 150
98"

```

**Comment by mgsloan** [comment]
This has come up before and the decision at the time was that it wasn't worth the added complexity.  I'm not committed to that decision, though.  What do folks think?  Does someone want to implement it?

**Comment by netroby** [comment]
curl, wget both got their continue download arguments. 
Saved lot's of time waste for broken download. and save bandwidth of your server

**Comment by dulguun0225** [comment]
I'm also getting same thing
`stack setup
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
ghc-8.2.2:   11.36 MiB / 121.89 MiB (  9.32%) downloaded...Error_Packet "partial packet: expecting 16384 bytes, got: 249"`

**Comment by jmatsushita** [comment]
Hi @mgsloan just ran into the problem trying to install while on a throttled internet connection. Is there any workaround to do this manually? Either by finishing a download from the stack tmp folder or downloading with curl or wget to where stack expects it? Bonus question: can we do the same for snapshots?

**Comment by prophile** [comment]
Why was this closed?

**Comment by afcady** [comment]
See #2899 which is still open.l
