### ISSUE TITLE
Long argument list on Windows call to "Setup" - 'does not exist' error

### ISSUE THREAD

**Issue by supergrade** [commercialhaskell/stack#3089]
### General summary/comments (optional)

"make: rawSystem does not exist (No such file or directory) on windows, seems similar in tone to these

https://github.com/commercialhaskell/stack/issues/723
https://github.com/haskell/process/issues/37

But with the call to start process in a different location to the fix/workaround at 
https://github.com/commercialhaskell/stack/commit/881023eb156626961f7803845fdfec4db16e7ddb

### Steps to reproduce

1. Pull https://github.com/bamboo/idris-cil
2. stack setup, etc. . .
3. stack build idris

### Expected

Successful build

### Actual

(This is rerunning build after a failure - repeated on 2 machines with 1.4.1/tip-built stack)

https://gist.github.com/supergrade/1cdea9f72c08f0270784906cf3d9c88f

(both machines gave an equivalent failure)

```
Configuring idris-0.99...
make: rawSystem: does not exist (No such file or directory)

--  While building package idris-0.99 using:
      C:\t\idris-cil\.stack-work\downloaded\ILugaAamj5ea\.stack-work\dist\b7fec0
21\setup\setup --builddir=
```

### Stack version

```
$ stack --version
On one machine:
Built via stack
Version 1.4.1, Git revision eb243b99985d2d2e102075d91beb61014da55089 (4730 commits) x86_64 hpack-0.17.0

On another machine, built via cabal:
https://gist.github.com/supergrade/69fdb57ec6b5e184068a8baf504c54f5


```

### Method of installation

Repeated on 2 machines - A stack 1.4.1 built on windows using the Haskell-package's own stack, and one built via Cabal

**Comment by mgsloan** [comment]
That `make` invocation looks to be coming from idris itself:

Idris is called here - https://github.com/bamboo/idris-cil/blob/master/Setup.hs#L16 - and the rawSystem invocation of make is likely here - https://github.com/idris-lang/Idris-dev/blob/674c2141797b447bfcafd497b927637dacdb7ec3/src/Idris/Package.hs#L446

Perhaps you don't have `make` (try `stack exec -- which make` - or I guess it might be `where make` on windows).  Do you have `gmake`?  Perhaps making `make` be a symlink to `gmake` could resolve the problem.

**Comment by supergrade** [comment]
So sorry, gravely misinterpreted what was happening. You were right. Thanks for the work tracking this down, and thanks (all) for the work on this remarkable piece of software (Stack).

**Comment by mgsloan** [comment]
Welcome!
