### ISSUE TITLE
Ubuntu packages: depend on necessary system libraries

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#309]
If I start a clean Ubuntu image (via Docker in my case), installing stack via the download instructions works great (yay!). When I try to do some work, I get told I need to install GHC via `stack setup` (not surprising). When I do so, I get prompted with:

> The following executables are missing and must be installed:xz, make

It would be ideal if the necessary system packages were automatically installed. (May go together well with #294).

Pinging @drwebb, same logic would apply to Arch Linux, though I haven't tested it over there.

**Comment by snoyberg** [comment]
I *think* the right set of system packages to install is `build-essential xz-utils`.

**Comment by rvion** [comment]
I confirm for xz-utils, but build-essential is a huge mega-packages containing much more than just make.
It usually is a must-install when developping on linux, but it may not be needed for stack

**Comment by snoyberg** [comment]
Also `libgmp-dev`.

@rvion I think- but could be mistaken- that most of build-essential will be necessary for actually building code with GHC.

**Comment by snoyberg** [comment]
And perhaps recommending (or requiring) common system libraries like zlib1g-dev.

**Comment by rvion** [comment]
from http://packages.ubuntu.com/trusty/build-essential, build-essentials contains:

- dpkg-dev (Debian package development tools)
- g++  (GNU C++ compiler)
- gcc (GNU C compiler)
- libc-dev (Embedded GNU C Library: Development Libraries and Header Files)
- make (An utility for Directing compilation.)

I tried to insall build-essential in a fresh ubuntu and here is what I got:

-------
root@ubuntu:/# **apt-get install build-essential**
Reading package lists... Done
Building dependency tree       
Reading state information... Done

#### The following extra packages will be installed:
  binutils cpp cpp-4.8 dpkg-dev fakeroot g++ g++-4.8 gcc gcc-4.8
  libalgorithm-diff-perl libalgorithm-diff-xs-perl libalgorithm-merge-perl
  libasan0 libatomic1 libc-dev-bin libc6-dev libcloog-isl4 libdpkg-perl
  libfakeroot libfile-fcntllock-perl libgcc-4.8-dev `**libgmp10**` libgomp1 libisl10
  libitm1 libmpc3 libmpfr4 libquadmath0 libstdc++-4.8-dev libtimedate-perl
  libtsan0 linux-libc-dev `**make**` manpages manpages-dev patch `**xz-utils**`

#### Suggested packages:
  binutils-doc cpp-doc gcc-4.8-locales debian-keyring g++-multilib
  g++-4.8-multilib gcc-4.8-doc libstdc++6-4.8-dbg gcc-multilib autoconf
  automake1.9 libtool flex bison gdb gcc-doc gcc-4.8-multilib libgcc1-dbg
  libgomp1-dbg libitm1-dbg libatomic1-dbg libasan0-dbg libtsan0-dbg
  libbacktrace1-dbg libquadmath0-dbg binutils-gold glibc-doc libstdc++-4.8-doc
  make-doc man-browser ed diffutils-doc

#### The following NEW packages will be installed:
  binutils build-essential cpp cpp-4.8 dpkg-dev fakeroot g++ g++-4.8 gcc
  gcc-4.8 libalgorithm-diff-perl libalgorithm-diff-xs-perl
  libalgorithm-merge-perl libasan0 libatomic1 libc-dev-bin libc6-dev
  libcloog-isl4 libdpkg-perl libfakeroot libfile-fcntllock-perl libgcc-4.8-dev
  `**libgmp10**` libgomp1 libisl10 libitm1 libmpc3 libmpfr4 libquadmath0
  libstdc++-4.8-dev libtimedate-perl libtsan0 linux-libc-dev `**make**` manpages
  manpages-dev patch `**xz-utils**`

0 upgraded, 38 newly installed, 0 to remove and 12 not upgraded.
Need to get **29.2 MB of archives.**
After this operation, **106 MB of additional disk space** will be used.

-------

both `make` and `xz-utils` and `libgmp10`are included by default
106MB added

**Comment by davidsiefert** [comment]
What is the outcome of this?  I checked out stack, built the docker dev env image and am running into this problem (not having build-essential).  Maybe I can add build-essential to the docker dev env image at least?
