### ISSUE TITLE
--test-arguments fails to interpret single-quoted literals

### ISSUE THREAD

**Issue by ExpHP** [commercialhaskell/stack#3091]
### Haiku

    stack pretends to be
    a shell, but it is no shell.
    showers in april

---

### Steps to reproduce

    stack new badtest && cd badtest

    echo "import System.Environment" > test/Spec.hs
    echo "main = getArgs >>= print" >> test/Spec.hs

    stack test # let it build

    stack test --test-arguments='"a double-quoted string"'
    stack test --test-arguments="'a single-quoted string'"
    # this as well
    stack test --test-arguments='a\ string\ with\ escaped\ characters'

### Expected

    ["a double-quoted string"]
    ['a single-quoted string']
    ["a string with escaped characters"]

### Actual

    ["a double-quoted string"]
    ["'a","single-quoted","string'"]
    ["a\\","string\\","with\\","escaped\\","characters"]

---

### More information

**This issue easily arises from QuickCheck's suggestion to use --quickcheck-replay,** as the suggestion is formatted with single quotes:

```
  Properties
    Quoted subst:                      FAIL
      *** Failed! (after 13 tests and 4 shrinks): 
      Exception:
        reScanner
        CallStack (from HasCallStack):
          error, called at ./Text/RE/Internal/NamedCaptures.lhs:139:15 in regex-0.10.0.2-6gmqeUX1uPmHalsE8FKV3i:Text.RE.Internal.NamedCaptures
      "\n"
      Use --quickcheck-replay '12 TFGenR 0000252A8229C2B1000000001DCD6500000000000000E1EF00000006FC1469C0 0 8191 13 0' to reproduce.
    Quoted template:                   OK (0.13s)
      +++ OK, passed 100 tests.
```

```
$ stack test --test-arguments="--quickcheck-replay '12 TFGenR 0000252A8229C2B1000000001DCD6500000000000000E1EF00000006FC1469C0 0 8191 13 0'"
Warning: File listed in terrible-filepath-subst.cabal file does not exist: README.md
terrible-filepath-subst-0.1.0.0: test (suite: subst-test, args: --quickcheck-replay '12 TFGenR 0000252A8229C2B1000000001DCD6500000000000000E1EF00000006FC1469C0 0 8191 13 0')

option --quickcheck-replay: Could not parse quickcheck-replay
```

**Args printed by --verbose look just fine:**

```
2017-03-27 22:10:26.599978: [debug] Creating process:
/home/lampam/cpp/badtest/.stack-work/dist/x86_64-linux-ncurses6/Cabal-1.24.2.0/build/badtest-test/badtest-test 'a single-quoted string'
```

As far as I can tell, this is only because the debug renderer doesn't care about single quotes either:
https://github.com/commercialhaskell/stack/blob/6aad5b43f/src/System/Process/Log.hs#L66-L74
(at least it's _consistent_; this perhaps isn't so much a _bug_ as a _misfeature_)

If stack had **taken the `stack test TARGETS -- ARGS` approach** [**when it had the chance**](https://github.com/commercialhaskell/stack/issues/172), then we wouldn't have this problem. Just sayin'. :innocent:*

(the most recent update I can find on the matter is #2210, from which I gather that such a change now has to go through a process)

---

### Stack version
Tested on two versions:

```
$ stack --version
Version 1.4.0 x86_64
$ ~/stack/.stack-work/install/x86_64-linux-ncurses6/lts-8.5/8.0.2/bin/stack --version
Version 1.4.1, Git revision dec53be0d1f1e777239246e0d615a0eea71f32a2 (4735 commits) x86_64 hpack-0.17.0
```

### Method of installation

* 1.4.0:  archlinux (pacman)
* 1.4.1:  built from github today

---

(*I say this tongue-in-cheek, knowing that such usage of `--` contorts its meaning and likely requires special handling)

**Comment by kirelagin** [comment]
I mean, stack could just take the string it receives and pass it to the shell and let the shell do the parsing 🙄.

**Comment by JoergBrueggmann** [comment]
I just tried to pass two arguments to test and Tasty.

The test (`stack test`) just printed:

    Use --quickcheck-replay=596272 to reproduce.
    Use -p '/test case #6/' to rerun this test only.

Than tried the following commands beside others:

    stack test --test-arguments "--pattern='/test case #6/' --quickcheck-replay=596272"
    stack test --test-arguments '--pattern="/test case #6/" --quickcheck-replay=596272'

Is this the same issue? Is there any other possibility to pass multiple test arguments?

**Comment by JoergBrueggmann** [comment]
> ### Haiku
> 
> ```
> stack pretends to be
> a shell, but it is no shell.
> showers in april
> ```
> 
> ### Steps to reproduce
> 
> ```
> stack new badtest && cd badtest
> 
> echo "import System.Environment" > test/Spec.hs
> echo "main = getArgs >>= print" >> test/Spec.hs
> 
> stack test # let it build
> 
> stack test --test-arguments='"a double-quoted string"'
> stack test --test-arguments="'a single-quoted string'"
> # this as well
> stack test --test-arguments='a\ string\ with\ escaped\ characters'
> ```
> 
> ### Expected
> 
> ```
> ["a double-quoted string"]
> ['a single-quoted string']
> ["a string with escaped characters"]
> ```
> 
> ### Actual
> 
> ```
> ["a double-quoted string"]
> ["'a","single-quoted","string'"]
> ["a\\","string\\","with\\","escaped\\","characters"]
> ```
> 
> ### More information
> 
> **This issue easily arises from QuickCheck's suggestion to use --quickcheck-replay,** as the suggestion is formatted with single quotes:
> 
> ```
>   Properties
>     Quoted subst:                      FAIL
>       *** Failed! (after 13 tests and 4 shrinks): 
>       Exception:
>         reScanner
>         CallStack (from HasCallStack):
>           error, called at ./Text/RE/Internal/NamedCaptures.lhs:139:15 in regex-0.10.0.2-6gmqeUX1uPmHalsE8FKV3i:Text.RE.Internal.NamedCaptures
>       "\n"
>       Use --quickcheck-replay '12 TFGenR 0000252A8229C2B1000000001DCD6500000000000000E1EF00000006FC1469C0 0 8191 13 0' to reproduce.
>     Quoted template:                   OK (0.13s)
>       +++ OK, passed 100 tests.
> ```
> 
> ```
> $ stack test --test-arguments="--quickcheck-replay '12 TFGenR 0000252A8229C2B1000000001DCD6500000000000000E1EF00000006FC1469C0 0 8191 13 0'"
> Warning: File listed in terrible-filepath-subst.cabal file does not exist: README.md
> terrible-filepath-subst-0.1.0.0: test (suite: subst-test, args: --quickcheck-replay '12 TFGenR 0000252A8229C2B1000000001DCD6500000000000000E1EF00000006FC1469C0 0 8191 13 0')
> 
> option --quickcheck-replay: Could not parse quickcheck-replay
> ```
> 
> **Args printed by --verbose look just fine:**
> 
> ```
> 2017-03-27 22:10:26.599978: [debug] Creating process:
> /home/lampam/cpp/badtest/.stack-work/dist/x86_64-linux-ncurses6/Cabal-1.24.2.0/build/badtest-test/badtest-test 'a single-quoted string'
> ```
> 
> As far as I can tell, this is only because the debug renderer doesn't care about single quotes either: https://github.com/commercialhaskell/stack/blob/6aad5b43f/src/System/Process/Log.hs#L66-L74 (at least it's _consistent_; this perhaps isn't so much a _bug_ as a _misfeature_)
> 
> If stack had **taken the `stack test TARGETS -- ARGS` approach** [**when it had the chance**](https://github.com/commercialhaskell/stack/issues/172), then we wouldn't have this problem. Just sayin'. 😇*
> 
> (the most recent update I can find on the matter is #2210, from which I gather that such a change now has to go through a process)
> ### Stack version
> 
> Tested on two versions:
> 
> ```
> $ stack --version
> Version 1.4.0 x86_64
> $ ~/stack/.stack-work/install/x86_64-linux-ncurses6/lts-8.5/8.0.2/bin/stack --version
> Version 1.4.1, Git revision dec53be0d1f1e777239246e0d615a0eea71f32a2 (4735 commits) x86_64 hpack-0.17.0
> ```
> 
> ### Method of installation
> 
>     * 1.4.0:  archlinux (pacman)
> 
>     * 1.4.1:  built from github today
> 
> 
> (*I say this tongue-in-cheek, knowing that such usage of `--` contorts its meaning and likely requires special handling)

### Haiku ###

Solutions push to the surface
they are not yet within reach

**Comment by mpilgrem** [comment]
In PowerShell:
~~~text
stack test '--test-arguments="''a single-quoted string''"'
["'a single-quoted string'"]
~~~

`optparse-applicative` receives `--test-arguments="'a single-quoted string'"`

or

~~~text
stack test --test-arguments '"''a single-quoted string''"'
["'a single-quoted string'"]
~~~

`optparse-applicative` receives `--test-arguments`, `"'a single-quoted string'"`
