### ISSUE TITLE
stack --docker build fails when there are extra-deps

### ISSUE THREAD

**Issue by dzhus** [commercialhaskell/stack#3095]
### Steps to reproduce

stack.yaml:
```
resolver: lts-8.6
- acme-missiles-0.3
```

command run:
```
stack --docker build
```

### Expected

The build works.

### Actual

```
dmitrydzhus$ stack --docker build
Could not parse '/Users/dmitrydzhus/projects/test/stack.yaml':
YAML parse exception at line 1, column 0,
while parsing a block mapping:
did not find expected key
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

Building outside of Docker (`stack build`) works as expected.

### Stack version

My host machine runs macOS 10.12.2: 

```
dmitrydzhus$ uname -a
Darwin <hostname> 16.3.0 Darwin Kernel Version 16.3.0: Thu Nov 17 20:23:58 PST 2016; root:xnu-3789.31.2~1/RELEASE_X86_64 x86_64
```

```
dmitrydzhus$ stack --version
Version 1.4.0 x86_64
```

Stack installed via `brew install haskell-stack`

**Comment by borsboom** [comment]
I recall something like this happening to me on macOS once as well, and the problem was with Docker itself and/or its VM not properly mounting files, not Stack.  I believe that I destroyed my Docker VM and re-created it, and that resolved the problem.

**Comment by dzhus** [comment]
Never happened again ever since Docker for Mac went "native". Doesn't reproduce with docker-edge `Version 18.06.0-ce-mac69 (26398)`, so naturally I'll just close the bug.
