### ISSUE TITLE
No incremental test output on AppVeyor

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#3097]
In [the path project](https://github.com/commercialhaskell/path) we have a testsuite that runs very slowly on Windows but not on *nixy platforms. It simply lacks some Windows-specific optimizations in its QuickCheck generators.

What makes these performance issues a bit harder to diagnose though, is that we don't get incremental output while the test-suite runs. In particular, if the test-suite causes the AppVeyor job to time out (as in [this case](https://ci.appveyor.com/project/chrisdone/path/build/1.0.203#L296)), we don't get any output at all and can't tell which test cases were slow.

We run our tests with the following command:

```
echo "" | stack --no-terminal build --haddock --no-haddock-deps --bench --test
```

Should we change anything about that command in order to get incremental output?

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and because the [path project](https://github.com/commercialhaskell/path) now uses GitHub actions for its CI.
