### ISSUE TITLE
Make --hyperlinked-source for haddock optional

### ISSUE THREAD

**Issue by Fuuzetsu** [commercialhaskell/stack#3099]
### General summary/comments (optional)
I would like to be able to tell stack to not give `--hyperlinked-source` to haddock with `stack --haddock`. Currently it always invokes this flag if it's supported.

### Steps to reproduce
1. stack --haddock -v

### Expected

Configurable option.

### Actual

Option always passed in without means to turn it off.

### Stack version

1.4.0, checked source and no reason to believe it's any different in git master

### Method of installation
N/A

**Comment by mgsloan** [comment]
Not sure why you'd want to turn this off, but sure, being able to disable it makes sense.

**Comment by Fuuzetsu** [comment]
In my particular case it's to workaround a Haddock bug. In general though we may want to host documentation and show it around without exposing source (for whatever reason).
