### ISSUE TITLE
--only-deps flag to `stack build`

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#310]
For CI, it's useful to distinguish build dependencies from building project packages. Granted, in principle with Stackage the dependency building part of the build should not fail, but there might be combinations of flags for which it could, and it's useful to have the build time for the project counted separately from the build time for the rest.

*Also,* Travis CI now [supports caching](http://docs.travis-ci.com/user/caching/). With `--only-deps`, we could in theory builds the deps once, then have Travis cache that, then in subsequent runs it won't be necessary to rebuild the deps.

**Comment by snoyberg** [comment]
Huh, interesting. I'll be interested to check out the caching support.

**Comment by mboes** [comment]
As noted somewhere at the bottom of that page, we need to be careful not to
touch the folder that includes the dependencies artifacts when we build the
project packages, in order to avoid invalidating the cache. This may or may
not be an issue - depends if we're already doing that!

**Comment by snoyberg** [comment]
Oh, it's the same caching I saw last time, which won't work on non-container builds (where container builds don't allow you to run `sudo`). That's disappointing.

Given that, I don't see any urgency on this feature, so deferring to later milestone.

**Comment by mboes** [comment]
well, but do we need `sudo`? If we build stack from source, then build deps from source, and cache that, then this could significantly speed up the build process for most people.

Alternatively install the `stack` binary in a non-global location.

**Comment by snoyberg** [comment]
I'm thinking about system libraries like gmp and zlib. I suppose we could put them in a user location and then LD_LIBRARY_PATH to make them available... that feels like a bad thing to do on a CI system though.

**Comment by radix** [comment]
gmp and zlib should already be installed on the travis nodes, so it shouldn't be necessary, right?

**Comment by snoyberg** [comment]
I thought they weren't, but I haven't tested. I guess that's what we really need: a test project to try this out on. Someone wanna take a stab at it?

**Comment by mboes** [comment]
Building stack from scratch on the Travis nodes works fine. I tried it this
weekend:
https://travis-ci.org/haskell-distributed/cloud-haskell/builds/66650203#L270

**Comment by snoyberg** [comment]
`--only-snapshot` flag added. @mboes confirmed?
