### ISSUE TITLE
Add support to wpad/pac proxy

### ISSUE THREAD

**Issue by marceloslacerda** [commercialhaskell/stack#3107]
I'm trying to use stack with wpad type of proxy but I'm getting a InvalidProxyEnvironmentVariable error:

    $ stack new my-project

    Downloading template "new-template" to create project "my-project" in my-project/ ...
    HttpExceptionContentWrapper {unHttpExceptionContentWrapper = InvalidProxyEnvironmentVariable "http_proxy" "[our proxy host IP]:3128/wpad.dat"}

If I supply the proxy host manually in the form "http_proxy=[host]:[port]" stack works fine, but it would be nice if stack were able to parse proxy wpad. If you are using it, libproxy has support for that type of configuration.

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

### Method of installation

* Script from haskellstack.org

**Comment by mgsloan** [comment]
Feel free to open an issue on http-client!  https://github.com/snoyberg/http-client/issues

Once it supports wpad, so will stack.
