### ISSUE TITLE
Plugin interaction with Docker

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#311]
(continued from https://github.com/fpco/stackage-dot/issues/1#issuecomment-110750487)

The plugin mechanism currently doesn't interact so well with Docker usage.  That is to say, if you run `stack dot` on the host, it requires stack-dot to exist on the host even if Docker use is enabled and stack-dot exists in the image.  And that stack-dot will be running on the host, not in a container (meaning it won't see the preinstalled libraries, tools, etc.).  So currently you'd really need to run  `stack exec stack dot`.

Perhaps stack process should be:

1. Look for the plugin on the host, and if it exists bind-mount it in the Docker container and launch it in there.
2. If it does not exist on the host, look for it in the Docker image and, if it exists in the image, run it in a container.

**Comment by rvion** [comment]
can't we just move stackage-dot code here ?

build-depends are really small:
```
executable stackage-dot
  main-is:             Main.hs
  build-depends:       base >=4.7 && <4.8
                     , conduit >= 1.2
                     , conduit-combinators >= 0.3
                     , containers >= 0.5
                     , monad-logger >= 0.3
                     , stackage-build
                     , text >= 1.2
```

**Comment by manny-fp** [comment]
@rvion I'm using stack-dot as the example, but this issue covers the general case of plugins for docker-enabled projects (it would be rare to actually run `stack --docker`, so plugins should work whether docker is enabled for a project or not).  Might be worth repeating your comments specific to stackage-dot in https://github.com/fpco/stackage-dot/issues/1.

**Comment by rvion** [comment]
Oh, ok. So, after your explanation, I am not quite 100% sure plugins are a real need according to the new architecture, but I'll be happy to repeat my arguments in the other issue. :)

**Comment by snoyberg** [comment]
Since we've disabled plugins and don't have plans to reenable, I'd recommend closing this.
