### ISSUE TITLE
Build order changes all the time when using `stack build --fast --file-watch`

### ISSUE THREAD

**Issue by minad** [commercialhaskell/stack#3114]
### General summary/comments (optional)

I am using `stack build --fast --file-watch` for rebuilding in a separate window. When I fixed an error in one file, stack doesn't rebuild that file but another one.

### Expected

Deterministic build order

### Actual

Random or rotating build order?

### Stack version

```
$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment]
Is the file you changed referenced in your .cabal file?

**Comment by minad** [comment]
yes

**Comment by minad** [comment]
@mgsloan Did you observe this behaviour too or do you need more input? This is annoying if you use stack for quick rebuilding and fix a series of errors in a file while developing. Most people might not observe that since they use some ide tools like intero or ghc-mod, I think. Unfortunately intero doesn't work well for me because of memory leaks and so I am using stack as poor man ide.

**Comment by mgsloan** [comment]
I don't see the issue, but then again I don't usually use --file-watch.  It sounds strange that the build behavior would be different, that should always rebuild what has changed (--file-watch just causes file changes to be triggers for the build, it does not tell the build what to rebuild).

**Comment by minad** [comment]
This happens for both the old release and the newest stack release. Assume that I have multiple files and do a refactoring which leads to type errors in many files. I use stack in another terminal window to rebuild automatically and then the behaviour described here is annoying since stack or cabal in the back doesnt rebuild the last file but some other file in some cylic manner. But I dont ask for stack to rebuild the file I edited, just for determinism. Determinism should be sufficient.

I didnt understand from your comment - can you observe this or not? Or did you mean that you use a different workflow (if yes I would be interested in what you suggest)? Thx!

**Comment by minad** [comment]
sth like ghci or similar tools provide the right behaviour, however I just had problems all the time with those breaking for whatever reasons such that I just rely on stack for rebuilding.

**Comment by Blaisorblade** [comment]
@minad One source of non-deterministic build order would be parallel builds, which speed up things, enabled by `-jN` build option for GHC. Maybe that's the reason?

`-j` can be passed in various places—I pass it in `~/.stack/config.yaml`:

```
ghc-options:
  "*": -j3
```

I don't know if the build order is otherwise deterministic, and I agree this would be useful—that's decided by GHC though.

> I didnt understand from your comment - can you observe this or not? Or did you mean that you use a different workflow (if yes I would be interested in what you suggest)? Thx!

If I may rephrase—he only uses `--file-watch` seldom. When he uses it, he hasn't noticed the issue.

**Comment by minad** [comment]
I tried with -j1 but this doesn't fix it.

**Comment by snoyberg** [comment]
This is an upstream issue in GHC, Stack does not determine module build order itself. Closing.

**Comment by minad** [comment]
agree :+1:
