### ISSUE TITLE
`build-type: Configure` makes stack complain about `custom-setup`

### ISSUE THREAD

**Issue by endgame** [commercialhaskell/stack#3115]
### General summary/comments

I'm writing a binding to a C library, and need to use `autoconf` and `pkg-config` to determine additional flags. If the `.cabal` file has `build-type: Configure`, `stack` will complain about a missing `custom-setup` stanza. If I create a `custom-setup` stanza, `Cabal` warns that it's unused because the build type is not `Custom`.

### Steps to reproduce

Set up a new project, and change the `build-type` to `Configure`. [The Cabal docs](https://www.haskell.org/cabal/users-guide/developing-packages.html) say that this must be the contents of `Setup.hs`:

```haskell
import Distribution.Simple
main = defaultMainWithHooks autoconfUserHooks
```

Run `stack build`. Stack will complain:

```
Package foo uses a custom Cabal build, but does not use a custom-setup stanza
Not using the explicit setup deps approach based on configuration
Strongly recommend fixing the package's cabal file
```

Put a `custom-setup` stanza into the `.cabal` file:

```
custom-setup
  setup-depends:       base >= 4.7 && < 5
                     , Cabal >= 1.10
```

Run `stack build`. Cabal will complain:

```
Warning: Ignoring the 'custom-setup' section because the 'build-type' is not
'Custom'. Use 'build-type: Custom' if you need to use a custom Setup.hs
script.      
```

### Expected

`stack` should not generate warnings for `build-type: Configure`.

### Actual

It's impossible to please both `stack` and `Cabal`.

### Stack version

```
$ stack --version
Version 1.4.0 x86_64 hpack-0.17.0
```

### Method of installation

Official binary, downloaded from stackage.org or fpcomplete's package repository. Later upgraded with `stack upgrade`.

**Comment by mgsloan** [comment]
Good point!  I've pushed a fix.

**Comment by endgame** [comment]
What a quick turnaround. Thank you very much.
