### ISSUE TITLE
Cannot install ghc-ng

### ISSUE THREAD

**Issue by Gurkenglas** [commercialhaskell/stack#3116]
### General summary/comments (optional)

In the process of installing live-haskell (see https://github.com/viveksjain/live-haskell/issues/1 (note a second problem where some sort of "'libpcre' package" is missing)), installing ghci-ng failed.

### Steps to reproduce

`stack install ghci-ng --verbose`

### Expected

It works.

### Actual

Some sort of '"dyn" library' is missing.

https://gist.github.com/Gurkenglas/34c8a1a45f6d97ca2a284c46797f4557

### Stack version

```
C:\Users\Gurkenglas>stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd x86_64 hpack-0.17.0
```

### Method of installation

Oof, it's a while back. I guess I followed https://docs.haskellstack.org/en/stable/README/ ? I just upgraded from 1.3.2, it didn't work before either.

**Comment by Blaisorblade** [comment]
Seems ghci-ng just doesn't work on Windows (I just built it on Mac)—see details on https://github.com/viveksjain/live-haskell/issues/1#issuecomment-292799589. Luckily, ghci-ng isn't needed any more. I hope you don't mind me closing.
