### ISSUE TITLE
Windows 10 Creators Update

### ISSUE THREAD

**Issue by Mistuke** [commercialhaskell/stack#3117]
Hi All,

Sorry for the very late notice. I was hoping to have a story for fixing this by now. But unfortunately all the time went into the GHC 8.2.1 release.

Unfortunately the Windows Creators Update which should start rolling out slowly tomorrow will cripple all existing GHC compilers on Windows. This is because of a bug in our wrapper code. GHC 8.2.1 will contain a fix for this but it means in the mean time no GHC compilers will work.

Now while we will likely re-release a fixed version of `8.2.1` I may not be able to convince people to release a fixed `7.10.3`.

As it stands we likely have to patch these downstream. To make it easier I have done the work of backporting the fix and rebuilding the wrapper.

I currently have it here https://github.com/Mistuke/ghc-compat and will get someone to upload the binaries to Haskell.org so they can be taken from there.

I wanted to raise this issue to see how to best solve it, but in either case, this likely means a repackaging of platform/stack.

Tamar

**Comment by borsboom** [comment]
Stack itself shouldn't need to be repackaged (since it doesn't bundle GHC).

We can repackage all the Windows GHC bindists referenced in [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml), so new installations using `stack setup` will work out of the box.  Existing users who upgrade Windows would have to run `stack setup --reinstall`.

**Comment by Mistuke** [comment]
Ah that sounds good. We'll have a repackaged version soon. I'm guessing stack just uses the tarballs from GHC? or do you guys compile your own GHC compilers?

**Comment by borsboom** [comment]
As much as possible, we use the official tarballs that GHC releases.  However, we do build a few variants for different versions of libtinfo/libncurses as well.

**Comment by Mistuke** [comment]
The binaries are available now. https://mail.haskell.org/pipermail/ghc-devs/2017-April/014131.html

**Comment by chiguire** [comment]
Thanks for providing the binaries, the update effectively broke gcc, and just replacing gcc.exe made everything work out again.

**Comment by bermanjosh** [comment]
@borsboom 
Are you going to be updating the stack-setup-2.yaml file? I did a stack setup --reinstall, and the old binaries were downloaded. Thanks.

**Comment by gzh** [comment]
Thank you!

**Comment by borsboom** [comment]
I've now updated [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml) with the new `win10` bindists.  @bermanjosh please give `stack setup` another try.

**Comment by bermanjosh** [comment]
@borsboom 
Yup, that worked, thanks.

**Comment by varosi** [comment]
*integersimple* versions doesn't work right now on Windows 10.

**Comment by borsboom** [comment]
Paging @leohaskell, who has provided Windows integersimple bindists the past.

**Comment by leohaskell** [comment]
@borsboom, here are the patched integersimple bindists:
[7.10.3](https://drive.google.com/open?id=0Bx1PZr9g0_7cMGJnOGhobHdVNnM)
[8.0.1](https://drive.google.com/open?id=0Bx1PZr9g0_7cSHBmd0xBTkNNemM)
[8.0.2](https://drive.google.com/open?id=0Bx1PZr9g0_7ceURjTi1XUXY0bTg)

**Comment by varosi** [comment]
Great! Thanks!

2017-05-26 15:30 GMT+03:00 Daniel Taskoff <notifications@github.com>:

**Comment by leohaskell** [comment]
@borsboom, will you update the Windows GHC bindists in stack-setup-2.yaml with the ones I provided above?

**Comment by varosi** [comment]
@borsboom, is there a plan to add integer-simple builds to the CI system, so they are deployed faster and in par with other builds? Currently because of license of default large integer library, GHC could not be used for non-open source production.

**Comment by borsboom** [comment]
@varosi: no GHC builds are currently being run by any CI system controlled by the Stack team.  Generally, GHC builds are the responsibility of the GHC release team, and we also accept community contributions like these integer-simple builds to add to the stack-setup metadata.

**Comment by varosi** [comment]
Thank you! I'll write to GHC team if they could make such.
