### ISSUE TITLE
`stack install` could be more clear about how to run installed commands

### ISSUE THREAD

**Issue by radix** [commercialhaskell/stack#312]
Right now when you run `stack install`, you get this rather verbose message at the end of a ton of output:

```
Copying from /Users/radix/.stack/snapshots/x86_64-osx/lts-2.14/7.8.4/bin/happy to /Users/radix/.local/bin/happy
```

How about something like this?

```
Installed the following executables to $HOME/.local/bin
- happy
```

Finally, it'd be nice if stack could detect when the install path is not in $PATH, and print a message (ideally with some colorizing to call attention to it) indicating that the the user should add it to their $PATH.

**Comment by snoyberg** [comment]
The second one is done (though not colorized). I like your version of output better than what we have now. Are you interested in trying to pretty up the output on this? It's a pretty self-contained bit of code.

**Comment by radix** [comment]
@snoyberg Oh, I guess I was confused about the `$PATH` because the time I ran `install` without my PATH set up was with an older stack.

Yeah, I'd be happy to take a look at cleaning up that output.

**Comment by snoyberg** [comment]
PR merged, thanks!
