### ISSUE TITLE
stack build uses cc1 not gcc as set by CC environment variable when building llvm-hs

### ISSUE THREAD

**Issue by amcphail** [commercialhaskell/stack#3123]
### General summary/comments (optional)

When trying to build accelerate libraries on a RHEL 6.3 cluster configure of llvm-hs fails.

cc1 has no option -Werror=date-time but gcc does

$ cc1 --version
-bash: cc1: command not found
$ gcc --version
gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### Steps to reproduce

Initialise a new project: stack new project
Add accelerate-llvm-ptx, accelerate-llvm to build depends in .cabal file
Add accelerate-llvm-ptx, accelerate-llvm to extra deps in stack.yaml
stack setup
stack build 

### Expected

Success

### Actual

```
$ stack build --verbose
```
[gist](https://gist.github.com/amcphail/ccda0890516b47d7300a30f303526b9e)

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0

```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by amcphail** [comment]
test.c:
```
#include <stdio.h>

int main(int argc, char* argv[])
{
   printf("Hello, World!\n");

   return 0;
}
```

compile and run:
```
$ gcc -o testit -Werror=date-time test.c
$ ./testit 
Hello, World!
```

**Comment by amcphail** [comment]
I now have this problem.  And I can't set --with-g++=`which g++`

```
$ which gcc
/share/easybuild/RHEL6.3/sandybridge/software/GCCcore/6.3.0/bin/gcc
$stack build --with-gcc=`which gcc`
```

[gist](https://gist.github.com/amcphail/6eb47f24fbbbe18f09d7e5c3cb534fe8#file-stack-build-log-2)

**Comment by amcphail** [comment]
```
$ stack build --with-gcc=`which g++`
```

```
...
    [101 of 101] Compiling LLVM             ( src/LLVM.hs, .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/build/LLVM.o )
    cc1plus: error: unrecognized command line option "-Wdelete-non-virtual-dtor"
    cc1plus: error: -Werror=date-time: No option -Wdate-time
    cc1plus: error: unrecognized command line option "-std=c++14"
    cc1plus: error: unrecognized command line option "-std=c++11"
    cc1plus: warning: unrecognized command line option "-Wno-maybe-uninitialized"
    `gcc' failed in phase `C Compiler'. (Exit code: 1)
```

**Comment by mgsloan** [comment]
Curious!  `--with-gcc` ought to work.

**Comment by amcphail** [comment]
Create a project with `stack init` and add `accelerate-llvm` and `accelerate-llvm-ptx` to used modules in `.cabal` and `extra-deps` in `stack.yaml`.

this is called by

```
$ which gcc
/share/easybuild/RHEL6.3/sandybridge/software/GCCcore/5.4.0/bin/gcc
$ gcc --version
gcc (GCC) 5.4.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ which ghc
/share/apps/Stack/1.4.0/programs/x86_64-linux/ghc-8.0.2/bin/ghc
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2

$ stack build [-v] --with-gcc=`which g++`
```

[llvm-hs-build.txt](https://github.com/commercialhaskell/stack/files/963629/llvm-hs-build.txt)
[llvm-hs-build-not-v.txt](https://github.com/commercialhaskell/stack/files/963630/llvm-hs-build-not-v.txt)

**Comment by amcphail** [comment]
I can reproduce the error using cabal not stack.  So the problem might not be stack unless it is a problem with the Cabal library.

Simpler steps to reproduce:

```
$ cabal get llvm-hs
$ cd llvm-hs-4.0.1.0
$ cabal configure -f -shared-llvm --with-gcc=`which g++`
$ cabal build -v
```

[llvm-hs.cabal-build.txt](https://github.com/commercialhaskell/stack/files/982021/llvm-hs.cabal-build.txt)

**Comment by amcphail** [comment]
I have narrowed the problem down to `llvm-hs` calls to `llvm-config`
