### ISSUE TITLE
Upload to hackage without cabal-install

### ISSUE THREAD

**Issue by andrewthad** [commercialhaskell/stack#313]
If I'm using stack to build a library that I want to upload to hackage, how can I build something that hackage will accept? I can't find any mention of this in the wiki, and [hackage's upload page](https://hackage.haskell.org/upload) doesn't give any instructions on how to make the tarball on your own.

**Comment by snoyberg** [comment]
I actually just added `stack upload` support, which if given a directory will generate the tarball and then upload it. Under the surface right now, it actually does call out to cabal-install, but in the future we can change this. I originally wrote the code to do `runghc Setup.hs sdist`, but that generate tarballs in the wrong format.

I'd like to leave this open to track doing sdist without `cabal-install`. It shouldn't actually be that difficult, we'd want to:

* Call `runghc Setup.hs sdist --list-sources=tmpfile`
* Process the tmpfile for a list of all filenames
* Generate the tarball

If you or someone else reading is interested in taking a crack at this, let me know, it shouldn't be too hard.

**Comment by andrewthad** [comment]
If I remember this when I'm less busy a week from now (and if no one has already done it), I may give it a try. If I switch to using the master branch of stack (which I assume has the upload command) instead of the beta that I downloaded a week ago, should that give me the ability to upload? Also, in your opinion, does that seem like a reasonably safe idea?

**Comment by andrewthad** [comment]
I'm renaming this to be more consistent with its purpose on the milestone.

**Comment by gregwebs** [comment]
@andrewthad given that it uses cabal-install it shouldn't have any bugs (other than those in cabal-install). I would recommend using `stack` or `stackage-upload` as soon as you can because they at least use https.

**Comment by andrewthad** [comment]
I'd like to use stack right now, especially I don't even have cabal-install installed anymore. Given that `stack upload` doesn't seem to be available in the version of stack in the ubuntu repository, is it safe to use the master branch of this github repo?

**Comment by snoyberg** [comment]
Yes, it's safe to use master, but unfortunately (because of what I mentioned earlier) it still depends on cabal-install being available. It shouldn't be hard to overcome that though.

**Comment by andrewthad** [comment]
Thanks. That shouldn't be a problem.

**Comment by andrewthad** [comment]
@snoyberg I'm using the master branch of stack, and it doesn't recognize `stack upload`. Is this still on another branch, or am I supposed to be running it differently?

**Comment by snoyberg** [comment]
It's the master branch. Are you certain that the executable you're running is the one you built? What's the output of `stack --version`?

**Comment by andrewthad** [comment]
0.0.2

**Comment by snoyberg** [comment]
What Git revision does it say? If it doesn't have one, it means you installed from a tarball, which means you're not running master :)

**Comment by andrewthad** [comment]
Ah, thanks. That's much better. Now I've got it to say:

    Version 0.0.2, Git revision 2736115d1fac7670e587b617c0cc1f7fefc35d52

So, I think I should be good now.

**Comment by mgsloan** [comment]
I'll be working on removing the dependency on the cabal binary.

**Comment by mgsloan** [comment]
Done!  I've tested it by uploading a new package, [yesod-media-simple](http://hackage.haskell.org/package/yesod-media-simple), an old project I cleaned up for release today.

@snoyberg Confirmed?
