### ISSUE TITLE
Install stack on macOS Sierra using homebrew

### ISSUE THREAD

**Issue by xeoneux** [commercialhaskell/stack#3131]
macOS Sierra warning: Homebrew's haskell-stack formula may not currently work on Sierra, so we suggest using the manual method above for now.

Is this issue in the docs resolved? I tried installing the `haskell-stack` formula on macOS Sierra and it installed the bottle perfectly.

**Comment by borsboom** [comment]
You're right, that's probably resolved now.  A PR removing that warning would be welcome.
