### ISSUE TITLE
`stack config set resolver foo` doesn't edit in-line

### ISSUE THREAD

**Issue by decentral1se** [commercialhaskell/stack#3136]
Seems to me that it should edit in-line? `resolver:` should stay where it is?

``` bash
λ ~/hobby/stack/ master stack config set resolver "$(stackage latest nightly)"
/home/lwm/hobby/stack/stack.yaml has been updated.
```

``` diff
diff --git a/stack.yaml b/stack.yaml
index 53efef8..9a8a456 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -1,18 +1,10 @@
-resolver: lts-8.5
-# docker:
-#   enable: true
-#   repo: fpco/stack-full
-# image:
-#   containers:
-#     - base: "fpco/stack-base" # see ./etc/docker/stack-base/Dockerfile
-#       name: "fpco/stack-test"
-nix:
-  # --nix on the command-line to enable.
-  enable: false
-  packages:
-    - zlib
 flags:
   stack:
     hide-dependency-versions: true
+nix:
+  packages:
+  - zlib
+  enable: false
 extra-deps:
 - store-0.4.1
+resolver: nightly-2017-04-24
```

**Comment by borsboom** [comment]
Sadly, we do not have a format-and-comment-preserving YAML parser/writer available that I'm aware of.  There are other cases where Stack has to modify the the `stack.yaml` with the same problem.  It's really annoying.

**Comment by lwm** [comment]
I see. Yes, it kinda blows up the feature ... needs some work then!

**Comment by philderbeast** [comment]
> Sadly, we do not have a format-and-comment-preserving YAML parser/writer available that I'm aware of.

@borsboom #5813 uses the original YAML to preserve ordering and to "redress" it with blank lines and comments after update.
