### ISSUE TITLE
Consider reconfiguring if $PATH changes

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3138]
As per https://github.com/haskell/cabal/issues/2015, it seems Cabal caches the `$PATH` when running `configure` and reuses it later. As a result, if a package needs a particular program on `$PATH` at compile time, a user who modifies their `$PATH` after a failure will continue to remain in a failure state until running a `stack clean`. Perhaps the `$PATH` should be considered an input dependency of configure steps?

**Comment by mgsloan** [comment]
Good to know!  Yes, I think it makes sense to do a reconfigure.  The alternative would be to just make this a warning, but that could easily be ignored.  Marking as P1 since it has to do with build determinism

**Comment by mgsloan** [comment]
Fixing this will probably invalidate previous configure cache info, so ideally would be batched with any other pending changes to it

**Comment by snoyberg** [comment]
See #4740
