### ISSUE TITLE
confusing description in yaml configuration doc

### ISSUE THREAD

**Issue by albertnetymk** [commercialhaskell/stack#3140]
In https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md

> *Note:* When stack is invoked outside a stack project it will source project
specific options from `~/.stack/global-project/stack.yaml`.  Options in this file will
be ignored for a project with its own `<project dir>/stack.yaml`.

If stack is invoked outside a stack project, where does the `<project dir>` come from? Or, is my interpretation off somehow?

**Comment by lwm** [comment]
> If stack is invoked outside a stack project, where does the <project dir> come from?

It is then the `~/.stack/global-project/` directory. This note means, when you are **not** in the global project, options will be taken from the directory you are in, if that is a stack managed project directory.

Feel free to submit a pull request if you can improve the wording of this.

**Comment by albertnetymk** [comment]
Thank you very much for the clarification. Hope the revised text is more clear.
