### ISSUE TITLE
process 1.6 + stack

### ISSUE THREAD

**Issue by curtisalexander** [commercialhaskell/stack#3145]
### General summary/comments (optional)
I am unable to install ghc utilizing `stack setup` on Windows 7.  When attempting to run, I receive the error
```
CreateDirectory "C:\\Users\\calex\\AppData\\Local\\Programs\\stack\\x86_64-windows": invalid argument (The system cannot find the path specified.)
```
I don't know the exact reason for the issue but wonder if this is at all related to this [fix](https://github.com/haskell/process/pull/80) within the Haskell `process` library.  I opened an [issue](https://github.com/haskell/process/issues/95) at the `process` repo wondering if version 1.6 is being used within the `stack` machinery.  @snoyberg [suggested](https://github.com/haskell/process/issues/95#issuecomment-297613845) I open an issue here asking that the Windows binaries be built with `process` 1.6.

I'll be glad to assist in any further troubleshooting to determine the exact root of the issue.  Or I can open two issues - one asking for `process` 1.6 to be used within the Windows binaries and a separate issue working through my specific issue (if it isn't related).

### Steps to reproduce

1. Download the [Windows x86 64-bit installer](https://github.com/commercialhaskell/stack/releases/download/v1.4.0/stack-1.4.0-windows-x86_64-installer.exe).
2. Install `stack` using the defaults.  Note that my `STACK_ROOT` is set to `C:\sr`.
3. Open a Windows command prompt.
4. Run `stack new my-project simple`.  This executes and completes with out error.
5. `cd` into the `my-project` directory.
6. Run `stack setup` to install a compiler.

### Expected

Would expect to have `ghc` installed.

### Actual

I receive the following error.

```
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
CreateDirectory "C:\\Users\\calex\\AppData\\Local\\Programs\\stack\\x86_64-windows": invalid argument (The system cannot find the path specified.)
```

If I run `stack setup --verbose` I receive the following error.

```
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd x86_64 hpack-0.17.0
2017-04-27 20:43:01.194106: [debug] Checking for project config at: C:\Users\calex\my-project\stack.yaml
@(Stack\Config.hs:935:9)
2017-04-27 20:43:01.209707: [debug] Loading project config file stack.yaml
@(Stack\Config.hs:960:13)
2017-04-27 20:43:01.209707: [debug] Trying to decode C:\sr\build-plan-cache\x86_64-windows\lts-8.12.cache
@(Data\Store\VersionTagged.hs:68:5)
2017-04-27 20:43:01.225307: [debug] Success decoding C:\sr\build-plan-cache\x86_64-windows\lts-8.12.cache
@(Data\Store\VersionTagged.hs:72:13)
2017-04-27 20:43:01.225307: [debug] Using standard GHC build
@(Stack\Setup.hs:600:9)
2017-04-27 20:43:01.724507: [info] Preparing to install GHC to an isolated location.
@(Stack\Setup.hs:816:5)
2017-04-27 20:43:01.740107: [info] This will not interfere with any system-level installation.
@(Stack\Setup.hs:825:5)
CreateDirectory "C:\\Users\\calex\\AppData\\Local\\Programs\\stack\\x86_64-windows": invalid argument (The system cannot find the path specified.)
```

### Stack version

```
> stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd x86_64 hpack-0.17.0
```

### Method of installation

* Official [binary](https://github.com/commercialhaskell/stack/releases/download/v1.4.0/stack-1.4.0-windows-x86_64-installer.exe), downloaded from Github.

**Comment by mgsloan** [comment]
@curtisalexander Sorry for taking so long to respond to this.  It may be worth trying to build stack with process-1.6 to make sure that this fixes it.  This'd look like adding `process-1.6` to extra-deps.  This may require bumping / adding other extra-deps, or perhaps using `allow-newer: true` to ignore bounds.

**Comment by curtisalexander** [comment]
@mgsloan I'm re-reviewing your last comment just now.  Were you asking that I attempt to build stack with `process-1.6`?  If that is the case, then I misread your response -- my apologies!  

If you do want me to try and build stack with `process-1.6` and have some documentation you can direct me to, I'll make a go of it.

Alternatively, I can wait until [ghc-8.2.1](https://ghc.haskell.org/trac/ghc/wiki/Status/GHC-8.2.1/Libraries) is released on stack nightly as mentioned at https://github.com/fpco/stackage/issues/2528.

**Comment by mgsloan** [comment]
@curtisalexander ghc-8.2.1 is released!  I don't really have documentation I can point at, it's easiest to build stack with stack.

> If you do want me to try and build stack with process-1.6 and have some documentation you can direct me to, I'll make a go of it.

Add `- process-1.6` under the `extra-deps:` in `stack.yaml` in the stack dir.  Then, run `stack install`.  That should be it.

**Comment by snoyberg** [comment]
This should already be addressed, closing. If there is still a problem, please add a comment.
