### ISSUE TITLE
MSYS2 version is too old

### ISSUE THREAD

**Issue by jokusi** [commercialhaskell/stack#3146]
This is a Windows only problem, but it affects all windows installations.

The MSYS2 version on Windows is way too old to work properly. Normally it can be easily updated with `stack exec -- pacman -Syuu` (or `pacman -Syuu` if you are running the bash shell). This is working fine with the newest MSYS2 version, but the one that stack downloads still need the old update procedure, which is quite complicated:

```
stack exec -- pacman --needed -Sy bash pacman pacman-mirrors msys2-runtime msys2-runtime-devel
stack exec -- pacman -Syu
stack exec -- pacman -Syuu
```

Packages like Gtk3 cannot be loaded and do not work without this update.

I would like to request that `stack setup` loads a newer MSYS2 version, that comes with a properly working pacman installation.

**Comment by mgsloan** [comment]
Seems like a good thing to address!  Setting P1 priority

**Comment by Anrock** [comment]
Any progress on this?

**Comment by snoyberg** [comment]
PR opened: https://github.com/fpco/stackage-content/pull/41

Plus a doc update PR: #4043
