### ISSUE TITLE
New option for stack build

### ISSUE THREAD

**Issue by psibi** [commercialhaskell/stack#3147]
To understand the context of this issue, reading this will be helpful:
https://github.com/yesodweb/yesod/issues/1384

Proposal: A new option named `--external` for `stack build` which will
be used along with the `--file-watch` option.

This feature is needed for the yesod development server specifically
to fix the above bug. When the option `--external` is given, the
`stack build --file-watch --external` won't recognize external
commands like `watching` or `help` in that mode. It will only
recognize `quit` and `rebuild` and the Return key for rebuild. On
giving some dummy text, it will just ignore the input and won't emit
anything. This feature is necessary for the `yesod-bin` package.

I would like to know what other's think of this.

**Comment by kadoban** [comment]
From reading #3165 it sounds like the decision was to go a different way than this proposal (fixing the problem on the yesod side). Let me know if I misunderstood.

**Comment by psibi** [comment]
Yeah, youre right. The plan is to handle it in devel code itself.
