### ISSUE TITLE
proxy with https scheme not allowed

### ISSUE THREAD

**Issue by typetetris** [commercialhaskell/stack#3157]
### General summary/comments (optional)

https scheme in https_proxy url not allowed.

### Steps to reproduce

```
~$ export https_proxy=https://webproxy.<removed>:8000/
~$ stack upgrade
Exception occured when trying to perform binary upgrade:
HttpExceptionContentWrapper {unHttpExceptionContentWrapper = InvalidProxyEnvironmentVariable "https_proxy" "https://webproxy.<removed>:8000/"}
Falling back to source upgrade
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...HttpExceptionContentWrapper {unHttpExceptionContentWrapper = InvalidProxyEnvironmentVariable "https_proxy" "https://webproxy.<removed>:8000/"}
~$ export https_proxy=http://webproxy.<removed>:8000/
~$ stack upgrade
Current Stack version: 1.4.0, available download version: 1.4.0
Skipping binary upgrade, your version is already more recent
```

### Expected

That it just works, as for example git or google-chrome do. Maybe my expectation is
wrong, as I don't know if there is a spec for the environment variables like https_proxy
which forbids this or something.

### Actual

See above.

### Stack version

```
~$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

### Method of installation

Official binary, downloaded from stackage.org or fpcomplete's package repository
https://www.stackage.org/stack/linux-x86_64-static

**Comment by ivan-m** [comment]
I don't think I've ever seen `https_proxy` have `https://` in it, and usually set it as an alias of `http_proxy`.

**Comment by erwo42** [comment]
Maybe it is rare, but is there a reason to plainly reject it?

All the other programs use it just fine.

I will change my config, but I think it would be nicer to accept this.

**Comment by mgsloan** [comment]
This'd need to be fixed in https://github.com/snoyberg/http-client/issues , maybe open a ticket there?

**Comment by cblp** [comment]
If you connect to your HTTPS proxy via HTTP (sic) then `https_proxy=http://...` is valid.

**Comment by typetetris** [comment]
Should be fixed upstream like @mgsloan suggests and workaround is available.
