### ISSUE TITLE
`stack --prefetch --dry-run` error should suggest that I meant to specify a task like build or run

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#316]

**Comment by snoyberg** [comment]
@chrisdone Thoughts? I don't know how feasible this is with optparse-applicative.

**Comment by snoyberg** [comment]
I'm going to close it. The rules here seem like they'd be very ad hoc, and we could probably come up with about a dozen different cases of "maybe we should recommend the user do something else."
