### ISSUE TITLE
`stack clean` ignores `postClean` UserHooks with Custom build-type?

### ISSUE THREAD

**Issue by wangbj** [commercialhaskell/stack#3161]
### General summary/comments (optional)
`stack clean` ignores `postClean` `UserHooks` in `Setup.hs`

### Steps to reproduce
1. Use `Custom` build-type in .cabal file
2. In Setup.hs, use postClean hook, such as:

```haskell
defaultMainWithHooks (simpleUserHooks {preBuild = somePreBuildCmd, postClean = somePostCleanCmd } )
```
3. `somePostCleanCmd` is supposed to remove some file generated by somePreBuildCmd.

4. run `stack build`, then `stack clean`
5. `postClean` isn't called

Include any `.yaml` configuration if relevant.

### Expected

`postClean` is called

### Actual

`postClean` is ignored, files generated by `preBuild` remains on disk.

### Stack version

```
$ stack --version
Version 1.4.0, Git revision 5986498a9d1073e8d58c79ec1302bb2a7847a396 (4642 commits) x86_64 hpack-0.17.0
```

**Comment by mgsloan** [comment]
Currently stack deletes the dist dir.  Not sure if we will switch over to using Cabal to clean, other than this case, deleting the dist dir is a reliable way to clear all state.

Perhaps consider having the `preBuild` store things in the dist dir?

**Comment by wangbj** [comment]
Thanks for clarifying this. cleaning dist won't work in my case, because ``preBuild`` generates some Haskell code by using ``haskell-src-exts`` in project directory, my expectation was ``postClean`` could remove those files, but it shouldn't be a big deal overall.

**Comment by mgsloan** [comment]
Great, closing as an old support issue.
