### ISSUE TITLE
Is invoking nix-shell necessary for using stack path?

### ISSUE THREAD

**Issue by adrianparvino** [commercialhaskell/stack#3169]
### Steps to reproduce

For example:

1. Run command `stack path`.
2. Run command `stack blah --no-nix`.

The time difference easily reaches 1 second due to nix-shell.

### Stack version
```
$ stack --version
Version 1.4.0 x86_64
```

### Method of installation

Installed from nixpkgs.

**Comment by mgsloan** [comment]
Yes, it is necessary.  If you have `system-ghc: true` (often so on builds with nix), the the path to GHC depends on the environment, similarly for the global DB.

It may be possible to do something clever when `system-ghc: false`, but I'm not confident that it would work properly.  If you need to do a number of these calls, perhaps do it from within `stack exec` and pass the --no-nix to the calls to `path`.
