### ISSUE TITLE
Creators update - Breaking changes WP8.1 Map control

### ISSUE THREAD

**Issue by StanleyBroo** [commercialhaskell/stack#3176]
The Map control Creators update has not been compatibility tested for WP8.1 and since we still stand between 8.1 and win 10 devices this is crucial to us while we work on a full UWP 10 App

RemoveRoute - crash App
3D perspective of Map wrong center point
GeocodeQuery missing street address
GeocodeQuery ignoring  query.GeoCoordinate 

What's a quick solution?
-Target the old map control? possible?
-Roll back OS update on the phone?

**Comment by Blaisorblade** [comment]
That does not seem a stack issue. This is a Haskell build tool. I'm a stack dev and have no idea of most of what you're saying. Closing—please reopen and clarify if I'm wrong.
