### ISSUE TITLE
Location where dependencies are built.

### ISSUE THREAD

**Issue by deech** [commercialhaskell/stack#3186]
I'm noticing that on some platforms (Arch) when I have a single project folder with a 'stack.yaml' dependencies get built and stored in the local '.stack-work'. In others (Debian, Windows) they seem to end up in some temp directory like 'stack12345'. Same project, same version of Stack (1.4.0). Is there a reason for this difference?

**Comment by mgsloan** [comment]
Hmm, currently local packages should always end up in `.stack-work`.  Things end up in the temp dir if they are upstream packages (part of the snapshot).
