### ISSUE TITLE
travis-complex.yml does not run the tests with cabal?

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#3199]
Hi,

I've been migrating my projects to stack's recommended travis template. But now I noticed that it doesn't seem to run the tests when building with cabal. Is that intentional?

**Comment by mgsloan** [comment]
I think maybe the idea there is that it's almost always sufficient to run the tests with stack, and just verify that the build succeeds with cabal.  Might be worth commenting on it in the file / docs.

**Comment by feuerbach** [comment]
The reason it was not enough in my case is that cabal builds cover more ghc versions than stack builds, and in the library I maintain (temporary) there were version-dependent ifdefs. I agree that it's not a common case; but it'd be good to mention this prominently somewhere.

**Comment by snoyberg** [comment]
I'm pretty sure it's just a "typo" (almost) because of the change in behavior in cabal from `--enable-tests` meaning "build and run" to "just build," though it could be for another reason. Want to send a PR to update it?
