### ISSUE TITLE
Stack YAML has a Nix section, if this is enabled, this prevents usage on non-nix systems

### ISSUE THREAD

**Issue by CMCDragonkai** [commercialhaskell/stack#3200]
I work on both Nix-enabled and Non-nix systems, is there a way to enable nix integration on the nix system but disable the nix integration on non-nix system without changing the stack.yaml file?

This is what I'm referring to:

```yaml
nix:
  enable: true
  shell-file: shell.nix
```

When that's placed inside a stack.yaml, any system that doesn't have nix has to remove that section from the stack.yaml before continuing? Perhaps there should be a way to make it optional?

For reference here are my 2 files:

* https://github.com/MatrixAI/haskell-multiaddr/blob/master/stack.yaml
* https://github.com/MatrixAI/haskell-multiaddr/blob/master/shell.nix

**Comment by snoyberg** [comment]
If you change it from `enable: true` to `enable: false`, then you have to explicitly pass a `--nix` argument on the command line to trigger the Nix behavior.

**Comment by snoyberg** [comment]
Closing as addressed.
