### ISSUE TITLE
Docker Image `fpco/stack-build` LTS version does not match TAG

### ISSUE THREAD

**Issue by kykim** [commercialhaskell/stack#3201]
When using the Docker Image with the TAG `LTS-8.17` from https://hub.docker.com/r/fpco/stack-build/tags/, the version in the resulting container appears to report `8.0`

```
root@b743c0b6b032:~/.stack/snapshots/x86_64-linux# pwd
/root/.stack/snapshots/x86_64-linux
root@b743c0b6b032:~/.stack/snapshots/x86_64-linux# ls
lts-8.0
root@b743c0b6b032:~/.stack/snapshots/x86_64-linux# 
```

**Comment by mpilgrem** [comment]
I am closing given the passage of time and because the `master` branch of Stack no longer supports LTS < 12.0.
