### ISSUE TITLE
Output of ide commands goes to stderr

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/stack#3204]
Each one of 
`stack ide targets`
and
`stack ide packages`
sends correct output to stderr and nothing to stderr.

Is this on purpose?

**Comment by mgsloan** [comment]
@rikvdkleij I don't think it is on purpose, but unfortunately these are already used by tools that likely depend on the output going to stderr.

I think an ok way to resolve this would be to entirely deprecate `stack ide` and have `stack query targets` /  `stack query packages`, which use stdout.

**Comment by rikvdkleij** [comment]
@mgsloan Thanks for your explanation.

I understand and will close this issue.
