### ISSUE TITLE
Revise the docs/README.md file

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3206]
I'm writing somewhat as the chair of the Haskell Website Working Group.

Currently the README has a section on "Why Stack?". While that content was useful right at the beginning of the project, I think it can now be summarised as "reproducible builds; multiple-library projects". I suggest rewriting along those lines.

Similarly, Stack builds on the important work done by the Cabal community. I suggest explicitly mentioning that Stack builds on GHC as the compiler, Cabal as the library configuration and install, then adds the features I mentioned above.

**Comment by ndmitchell** [comment]
Ping @snoyman, as this is relevant to email discussions we've been having.

**Comment by snoyberg** [comment]
Fixed, closing.
