### ISSUE TITLE
Simplify the Windows setup instructions

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3207]
The current Windows instructions at https://docs.haskellstack.org/en/stable/install_and_upgrade/#windows are not user friendly. In particular:

* It advises setting your PATH. Is that still required? Seemingly the temporary workarounds it points at got solved some time ago.
* It discourages use of both 32 bit and 64 bit code. I recommend only offering the 64bit version now (possibly with a small postscript to the 32bit one).
* Phrases about unsupported windows version and asking people to update the page are out of place.

**Comment by snoyberg** [comment]
Fixed, closing.
