### ISSUE TITLE
Installer fails on macOS High Sierra

### ISSUE THREAD

**Issue by tfausak** [commercialhaskell/stack#3208]
Stack's installer fails on the macOS High Sierra developer beta because `/usr/local/bin` doesn't exist.

``` sh
$ curl -sSL https://get.haskellstack.org/ | sh
Using generic bindist...
 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   619    0   619    0     0   1013      0 --:--:-- --:--:-- --:--:--  1013
100 13.2M  100 13.2M    0     0  2619k      0  0:00:05  0:00:05 --:--:-- 3266k
Password:
install: /usr/local/bin/stack: No such file or directory
Install to /usr/local/bin/stack failed
```

Running `sudo mkdir /usr/local/bin` and then re-running the installer fixes it.

**Comment by mgsloan** [comment]
Thanks for the report!  Pinging @borsboom

**Comment by borsboom** [comment]
@tfausak Is `/usr/local/bin` in the default user PATH?

**Comment by tfausak** [comment]
I don't have that machine handy, but I think `/usr/local/bin` is in the `$PATH` by default.

**Comment by borsboom** [comment]
Ok, and looks like get.haskellstack.org already checks for presence in the PATH and warns if it is not there.

**Comment by cannc4** [comment]
I am getting the same error. I am guessing it's fixed as you closed the issue?

**Comment by borsboom** [comment]
It means the fix is on `master` but not necessarily released yet.
