### ISSUE TITLE
Early indications High Sierra might have bumped load limit

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#3209]
https://www.reddit.com/r/haskell/comments/6gboq1/ghc_and_stack_on_macos_high_sierra/diq2th3/

Nothing actionable yet, this is just a posterboard notice for when more people are able to test High Sierra that the end might be in sight.

I'll see if my developer account is still active.

**Comment by bitemyapp** [comment]
Dev Beta 1 of High Sierra (10.13) is apple developer program only FWIW

**Comment by bitemyapp** [comment]
Nope, same problem, same load limit.

```
ghc: panic! (the 'impossible' happened)
      (GHC version 8.0.2 for x86_64-apple-darwin):
    	Loading temp shared object failed: dlopen(/var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/T/ghc19023_0/libghc_38.dylib, 5): no suitable image found.  Did find:
    	/var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/T/ghc19023_0/libghc_38.dylib: malformed mach-o: load commands size (35352) > 32768
    	/var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/T/ghc19023_0/libghc_38.dylib: stat() failed with errno=25
```

/cc @tfausak 

Might just take a higher dep load before the build obviously fails.

**Comment by domenkozar** [comment]
One solution would be to reduce library names since they can become really long, for example: `@rpath/libHSdata-default-instances-containers-0.0.1-bob6IQGdJq92c061H46zK-ghc8.0.2.dylib`

Source code: https://github.com/haskell/cabal/blob/master/Cabal/Distribution/Simple/BuildPaths.hs#L196

**Comment by domenkozar** [comment]
@bitemyapp for posterity, could you paste (and attach) the output of `otool -l /var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/T/ghc19023_0/libghc_38.dylib`

**Comment by bitemyapp** [comment]
```
otool -l /var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/T/ghc19023_0/libghc_38.dylib
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: '/var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/T/ghc19023_0/libghc_38.dylib': No such file or directory
```

```
$ sudo find /var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn -name "*ghc*"
find: /var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/0/SafariFamily: Operation not permitted
find: /var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/0/com.apple.LaunchServices.dv: Operation not permitted
find: /var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/0/Library/com.apple.nsurlsessiond: Operation not permitted
find: /var/folders/gq/rh0h8yns2p1bb5d31mdx69b40000gn/0/com.apple.routined: Operation not permitted
```
