### ISSUE TITLE
Logo?

### ISSUE THREAD

**Issue by twopoint718** [commercialhaskell/stack#321]
Does the Stack tool have a logo?

**Comment by chrisdone** [comment]
Not at the moment. :-)

**Comment by snoyberg** [comment]
Let's put this in later improvements with no assignee. Perhaps someone could email the Commercial Haskell list and ask for people to submit ideas?

**Comment by drwebb** [comment]
I was a bit bored this afternoon, so I made a logo for anyone who likes ASCII art
```
                                        
____ __         ________       ________ 
__\ \\ \_____  ______  /_____ ______  / 
___\ \\ \___/ _/ ___> __> __ >/ ___> / >
___/ //  \_/ _(___   /_  /_/   /__  /<  
__/_//_/\_\ ______/\__/\__,_/\___/_/ _> 
                                        

```

**Comment by snoyberg** [comment]
Let's bring this up on the stack mailing list instead of the issue tracker, as the latter will hopefully get more publicity to it.
