### ISSUE TITLE
Error while loading so/dll: cannot allocate memory in static TLS block

### ISSUE THREAD

**Issue by anton-k** [commercialhaskell/stack#3220]
### General summary/comments (optional)

I run:

~~~
stack install
~~~

While compiling project with dependency on rocksdb I get a strange error:

<command line>: can't load .so/.DLL for: /home/anton/dev/hex/ap/.stack-work/install/x86_64-linux-ncurses6/lts-8.11/8.0.2/lib/x86_64-linux-ghc-8.0.2/libHSrocksdb-0.1.0.1-On13JiUzWK8FSLPBSQ9gr-ghc8.0.2.so (/usr/lib/libjemalloc.so.2: cannot allocate memory in static TLS block)

### Expected

To compile. It was compiling fine.

### Actual

It was compiling fine but now it's not the case.

### Stack version

```
stack --version                                      
Version 1.4.0 x86_64
```

### Method of installation

* Installed via pacman from ArchLinux distro

**Comment by anton-k** [comment]
Problem happens with dependency jemalloc:

jemalloc-5.0.0-2-x86_64

When I downgrade to 

jemalloc-4.5.0-1-x86_64

It goes well again

**Comment by mgsloan** [comment]
Sounds like a problem quite specific to those particular dependencies.  Good to note for others that might run into this, closing as a support issue.
