### ISSUE TITLE
linux-arm bindist has vanished

### ISSUE THREAD

**Issue by eamsden** [commercialhaskell/stack#3222]
### General summary/comments (optional)

The script hosted at https://get.haskellstack.org, when run on an ARM platform, will try to download
https://www.stackage.org/stack/linux-arm. However, that URL returns a 404 not found error.

This may be due to the linux-arm tarball not being included in the [1.4.0 release](https://github.com/commercialhaskell/stack/releases/tag/v1.4.0), but no notation of its removal from this release appears in the release notes.

The tarball is present for the [1.3.2 release](https://github.com/commercialhaskell/stack/releases/tag/v1.3.2)

### Steps to reproduce

Either
  - Run `curl -sSL https://get.haskellstack.org | sh -` on an ARM platform, i.e. Raspberry Pi or C.H.I.P.
  - Browse to https://www.stackage.org/stack/linux-arm

### Expected
There should be a tar archive here for the script to unpack.

### Actual
404 not found

### Stack version
N/A

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository
(attempted)

**Comment by mgsloan** [comment]
Thanks for the report!  See the discussion at https://github.com/commercialhaskell/stack/issues/2103 for the current status of ARM support.

Seems like the issue here is modifying the installer script to just error.

**Comment by borsboom** [comment]
stack-1.5.0 and 1.5.1 once again have ARM binaries.  ARM support isn't official and building on ARM tends to be a bit tricky, so getting those binaries out for new versions is "best effort".

**Comment by eamsden** [comment]
@borsboom I've successfully built stack on arm from source once or twice. I'd be happy to be one of the people making the "best effort", if you'd like to ping me whenever a release is forthcoming.

Regarding the installer script, if it could, instead of erroring, install the last version of stack for which there is an arm build, perhaps with a notice that this is the latest arm version, not the latest released version, that might be a more graceful degradation of functionality.

Stack is about the only way to sanely do Haskell-on-ARM right now, so having it be uninstallable is a big setback for those of us experimenting with Haskell on ARM platforms.

**Comment by borsboom** [comment]
> Regarding the installer script, if it could, instead of erroring, install the last version of stack for which there is an arm build, perhaps with a notice that this is the latest arm version, not the latest released version, that might be a more graceful degradation of functionality.

This is actually something that would have to be implemented in [stackage-server], since it's what provides the redirects to the latest version at https://www.stackage.org/stack, which the script uses.

[stackage-server]: https://github.com/fpco/stackage-server
