### ISSUE TITLE
Impossible to install cabal with `stack install cabal`

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stack#323]
I can't install cabal with stack
Is that normal ?

```
➜  pick git:(master) ✗ stack install cabal
Populated index cache.
The following target packages were not found: cabal
```

```
➜  pick git:(master) ✗ < stack.yaml
flags:
  pick: {}
packages:
- '.'
extra-deps:
- ncurses-0.2.11
resolver: lts-2.13
```

it's strange because I can see it here :http://www.stackage.org/lts-2.13

**Comment by snoyberg** [comment]
Do you mean cabal-install?

**Comment by snoyberg** [comment]
Fairly certain this is just a typo, so closing. If there's something else going on, please reopen.

**Comment by rvion** [comment]
oups... yes, I was meaning cabal-install.
