### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#324]
Will consist of:

* [ ] Generate stack binaries for all platforms
* [ ] Full integration test suite (being worked on by @drwebb) run against each of those binaries
* [ ] Upload binaries to S3, Github releases, and wherever else necessary
* [x] Updated the Downloads wiki page (no longer necessary)
* [ ] Email the relevant mailing lists about the release, possibly put up a blog post

We want to get this as automated as possible. I'm assigning this issue to @manny-fp for now to spearhead, though others will need to be part of it too.

**Comment by manny-fp** [comment]
Getting this all automated is, I think, too ambitious to do for the first release milestone.  Perhaps we should start by all documenting here the (semi-)manual processes we're using for the various builds.  Then we can start seeing the common patterns and figure out how to best approach automating it all.  I can volunteer to put together the framework and then will ask for help filling it in with the particulars of various platforms.  Initially it probably makes sense to have the "release tool" be something that's manually run on each platform, and once that's working well we can considering using AWS etc. to be able to automatically run on all platforms.

@snoyberg: Linux general, Windows
@dysinger: Ubuntu
@drwebb: Arch
@manny-fp: OS X

Did I miss anyone?

Can we consider making the Downloads page not link to a particular version's binaries but instead just have it link to the [latest release](https://github.com/commercialhaskell/stack/releases/latest) on Github and have users find the right file for their platform there?  The Ubuntu and Arch instructions will already install the latest automatically, and this way we don't need to worry about automating modifying the wiki page.

**Comment by snoyberg** [comment]
Agree with all points, especially the Downloads wiki page

**Comment by manny-fp** [comment]
I'll start us off:

#### OS X release process

Build: 
```
git clone -b v0.0.2-beta git@github.com:commercialhaskell/stack.git
(cd stack && stack build)
cp stack/.stack-work/install/x86_64-osx/lts-*/*/bin/stack ./stack-0.0.2-x86_64-osx
strip stack-0.0.2-x86_64-osx
gzip stack-0.0.2-x86_64-osx
gpg --detach-sig --armor -u manny@fpcomplete.com stack-0.0.2-x86_64-osx.gz
```

Test:
- Copy the binary to my Mac Mini "media server" (mostly fresh install of Yosemite).
- On that machine, `rm -rf ~/.stack`.
- Run through the [checklist](https://github.com/commercialhaskell/stack/wiki/Checklist).

Upload:
- Upload `stack-0.0.2-x86_64-osx.gz` and `stack-0.0.2-x86_64-osx.gz.asc` to the Github releases page for the tag.
- Update OS X links on the [download](https://github.com/commercialhaskell/stack/wiki/Downloads) page.

**Comment by snoyberg** [comment]
My flow on both Windows and Linux is virtually identical, just changing the filenames and signing key as necessary (and, on Windows, deleting the appropriate %APPDATA%\stack instead of ~/.stack).

**Comment by drwebb** [comment]
My build process is currently to use my haskell-stack-git PKGBUILD to grab the revision at the release tag and build stack. Then I manually tar up the file and upload to AWS. Then I need to bump the SH1SUMs and links in the binary PKGBUILD and resubmit to the AUR. 

The AUR is moving to git, so you can actually see the two lines I need to manually change, it's something I could probably script to make fully automated in a couple hours. 

https://aur4.archlinux.org/cgit/aur.git/commit/?h=haskell-stack&id=937f676e830354189c3a39a9810a38bb80211109

**Comment by manny-fp** [comment]
@drwebb Does you process need to be run on Arch?  Is it Dockerable so that it could be run from non-Arch systems?

**Comment by manny-fp** [comment]
Another step to the release process is uploading stack to Hackage.

**Comment by manny-fp** [comment]
Ubuntu process:

a) need docker installed
b) make sure you have deb-s3 rubygem installed (`sudo gem install deb-s3`)
c) gpg installed, and dev@fpcomplete.com secret key in keyring
d) apt-cacher-ng installed (`sudo apt-get install apt-cacher-ng`), or disable in the Dockerfile.
d) export AWS env vars
e) `make release`

**Comment by drwebb** [comment]
So here are the steps

- Compiling: Arch could use the generic linux build 
- Updating the PKGBUILD: Requirements `sha1sum` and `sed`.
- Pushing to the AUR: requirements git

However before a new version of a PKGBUILD can be pushed to the AUR you must run `mksrcinfo` from the directory. This is found in this following package, I believe the only dependency is bash, but I don't know how well it would run on an Ubuntu system at the moment. 

https://github.com/falconindy/pkgbuild-introspection

So yeah, pretty Dockerable (if that's not a word already, now it is)

**Comment by snoyberg** [comment]
I've added a link to this issue from the checklist page. Closing for now, I think we've determined the steps in the release process, and over time we'll automate it.

**Comment by drwebb** [comment]
Just chiming in here to state that I'm adding a review man page box to the checklist, nothing worse than out of date documentation!

**Comment by manny-fp** [comment]
Beginning of stack release automation: https://github.com/commercialhaskell/stack/blob/master/etc/release-tool/README.md
