### ISSUE TITLE
Travis CI timeouts

### ISSUE THREAD

**Issue by lwm** [commercialhaskell/stack#3242]
It's pretty crazy that the builds are running over the 50 minute build time of Travis and can be disheartening when merge requests fail because of them.I was wondering, does anyone have any ideas how to solve this without compromising the extensive testing done with both stack/cabal. That would be nice.

**Comment by snoyberg** [comment]
Should be addressed with 5c61387f6ab624dd9a6b3acadc3d4370fb319399
