### ISSUE TITLE
ghcjs requires alex

### ISSUE THREAD

**Issue by Gurkenglas** [commercialhaskell/stack#3243]
### General summary/comments (optional)
Building miso with --install-ghc fails at the step where alex needs to be used.

### Steps to reproduce

For example:

0. Don't have alex installed.
1. Clone miso.
2. Run command `stack build --install-ghc`.

I don't know if the .yaml configuration is relevant, but here's the one: https://github.com/dmjio/miso/blob/master/stack/ghcjs801/stack.yaml

### Expected

It builds.

### Actual

It doesn't.
https://gist.github.com/Gurkenglas/a92ab3ca53deb8f71a491067b4c8ff2e
Not sure how to give verbose output since I've since installed alex using `stack install alex` outside the project.

### Stack version

```
C:\Users\Gurkenglas>stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd x86_64 hpack-0.17.0
```

### Method of installation

I don't know, it's been years, but I probably used the installer?

**Comment by mgsloan** [comment]
@Gurkenglas Can you please try out the potential fix on https://github.com/commercialhaskell/stack/pull/3321 ? It hasn't been tested yet, but it should work.

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
