### ISSUE TITLE
stack exec messes up command on Windows

### ISSUE THREAD

**Issue by arrowd** [commercialhaskell/stack#3246]
```
stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd x86_64 hpack-0.17.0

stack exec -- cmd /c set
'"set' is not recognized as an internal or external command,
operable program or batch file.
```

Note `"set` in the error message. Something clearly goes wrong there.

**Comment by mgsloan** [comment]
I don't have a windows haskell development setup at the moment.  It'd be great if someone that does could look into this!  Want to try figuring out what's going wrong @arrowd?

**Comment by tswelsh** [comment]
I had a look at this, and was able to reproduce the error message with just with the `process` library.  It is probably related to this long standing issue: https://github.com/haskell/process/issues/51.

**Comment by snoyberg** [comment]
Closing as an upstream issue. If someone wants to work on getting this fixed in process, I'd be happy to work with them on it (I maintain the library)
