### ISSUE TITLE
HsColour cannot be opened because of a problem (macOS)

### ISSUE THREAD

**Issue by klaperman** [commercialhaskell/stack#3247]
### General summary

When I run `stack build`, I get a bunch of alarming system dialogs, but the build appears to complete successfully.

### Steps to reproduce

1. `stack new example`
2. `cd example`
3. `stack build`
4. `stack ghci`

### Expected

The project builds on step 3 and I get a functioning ghci on step 4.

### Actual

On step 3, the project seems to build fine (because ghci works on the next step), but I also get a stack of error dialogs from macOS, e.g.:

![image](https://user-images.githubusercontent.com/1173465/27844065-285932fe-60d1-11e7-8da3-c8bf0800663e.png)

The programs that are implicated in these dialogs are `HsColour`, `happy`, `alex`, and `cpphs`.

[See the verbose output for step 3.](https://gist.github.com/klaperman/feb3c4058d210c0a449ada41d51481b5)

### Stack version

```
$ stack --version
Version 1.4.0 x86_64
Compiled with:
- Cabal-1.24.2.0
[...long list of packages]
```

I'm on macOS Sierra 10.12.5.

### Method of installation

```
brew install stack
```

**Comment by Blaisorblade** [comment]
GHC < 8.0.2 and OS X Sierra run into trouble (https://docs.haskellstack.org/en/stable/install_and_upgrade/#macos).

IIUC, OS X now refuses to run some binaries that used to work (https://ghc.haskell.org/trac/ghc/ticket/12479#comment:13)—that's most/all binaries produces by GHC < 8.0.2, and some binaries produced by GHC 8.0.2 with lots of dependencies.

So you'll need to rebuild with GHC 8.0.2 anything built by older GHCs. I'd guess all those programs that fail were built with older GHCs.

Usually `stack new` doesn't use any of those programs, and the verbose log you attach doesn't mention them either—maybe you're using `stack new` with some custom template doing something special, somehow?

Clicking on the "Report..." button will show a detailed stack trace which might be useful to get more details, but I'd first verify or falsify the above working hypothesis.

**Comment by snoyberg** [comment]
This appears to be resolved with newer Stack/GHC versions, so closing. If this still affects you, please add a comment.
