### ISSUE TITLE
Upgrading hpack to v0.18.1?

### ISSUE THREAD

**Issue by mgattozzi** [commercialhaskell/stack#3255]
Recently hpack gained the ability to recognize Alex and Happy files. This allows projects to use it to generate cabal files to build it. While stack has hpack built into it, it's currently using the older version that doesn't recognize those files, meaning one can't build projects with hpack and stack.

I was wondering if there was a want or need to upgrade to the newer version of hpack before submitting a PR or if there was a better way to go about it with how I implemented it on my branch located [here](https://github.com/mgattozzi/stack/tree/hpack). If this is a wanted feature I'll be more than happy to open up the PR and put it through review.

**Comment by snoyberg** [comment]
I haven't handled an hpack upgrade before, but I think simply sending a PR that updates the stack.cabal and stack\*.yaml files to use the newest version (and fix any code breakage than ensues) should be sufficient.

**Comment by tfausak** [comment]
This would be great! As far as I can tell, this was the last hpack upgrade: https://github.com/commercialhaskell/stack/pull/2961

**Comment by mgattozzi** [comment]
It looks like there was some min versioning going on [here](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Package.hs#L1189) but I've bumped the minimum version so that all users should have it.

**Comment by lwm** [comment]
This was done in 97e9f60a :+1:
