### ISSUE TITLE
Ease new issue creation (stack bugreport + new issue button on readme)

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stack#326]
following https://github.com/commercialhaskell/stack/issues/322

Other ideas:

1. add a new issue button on readme that prefill the new issue using something like that:
```
 [Report bug](https://github.com/commercialhaskell/stack/issues/new?body=%23 Description%0A%0A%23 How to reproduce%0A%0A%23 Environnement)
```
(It works well, newlines need to be escaped in readme, but espaces will be handled by markdown renderer itslef)

2. add a stack bugreport command that open new issue page on this repo with infos prefilled

**Comment by snoyberg** [comment]
I'm -1 on both tbh. They both add clutter to places where we need to have as directed a message as possible (the homepage of the project and the help output).

**Comment by rvion** [comment]
I'm sold
