### ISSUE TITLE
Stack cant find GHC

### ISSUE THREAD

**Issue by denumerate** [commercialhaskell/stack#3268]
A project that already has been set up is unable to find the GHC.
stack build results in:
```
No compiler found, expected minor version match with ghc-8.0.2 (x86_64-ncurses6-nopie) (based on resolver setting in /home/iam/Work/has/grove/stack.yaml).
To install the correct GHC into /home/iam/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```

stack setup results in:
```
Unable to find installation URLs for OS key: linux64-ncurses6-nopie
```

However, in .stack-work, in the install file there is a folder called `x86_64-linux-ncurses6`, not `linux64-ncurses6-nopie`

Stack was installed by pacman.
 Version 1.4.0 x86_64, the project is using resolver: lts-8.21

Edit: I've been trying to figure out what is going on, and i think i might have a clue.  I'm not certain, but arch linux just enabled PIE for the gcc (https://www.reddit.com/r/archlinux/comments/6n5tkp/arch_now_enables_pie_and_ssp_by_default_in_gcc/?st=j53afy9q&sh=15e6c62a) and this fits the time table and might explain that nopie at the end of the os key.

**Comment by dschrempf** [comment]
I can confirm this issue.
`uname -a`

    Linux schwarzbaer 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux
`stack --version`

    Version 1.4.0 x86_64

**Comment by borsboom** [comment]
It's because we don't (yet) have GHC bindists that link against ncurses6 on nopie distributions.  Have you tried installing [ncurses5-compat-libs](https://aur.archlinux.org/packages/ncurses5-compat-libs/)?

**Comment by borsboom** [comment]
It would also be super helpful to other Arch users to help work toward having a GHC bindist that works "out of the box".  There are [instructions for building a Stack-compatible GHC bindist](https://docs.haskellstack.org/en/stable/MAINTAINER_GUIDE/#building-ghc), and then you can modify a local copy of [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml) with the additional bindist and use `stack setup --setup-info-yaml=<PATH>` to try it out.

**Comment by TimoFreiberg** [comment]
After installing [libtinfo](https://aur.archlinux.org/packages/libtinfo/), `stack setup` installed `ghc-tinfo6-nopie-8.0..2`.

Trying to run (for example) `stack install hindent`, fails when trying to link `old-time-1.1.0.3` with the following error:
`configure: error: cannot run C compiled programs.`
[(See old-time-1.1.0.3.txt)](https://github.com/commercialhaskell/stack/files/1148998/old-time-1.1.0.3.txt)

Another failed linking attempt for the dependency `clock-0.7.2`:
`/usr/bin/ld: .stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/build/System/Clock_hsc_make.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output`
[(See clock-0.7.2.txt)](https://github.com/commercialhaskell/stack/files/1149015/clock-0.7.2.txt)

`$ uname -r`
`4.11.9-1-ARCH`
`$ stack --version`
`Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0`

I'll look into trying to build a Stack-compatible GHC soon @borsboom

**Comment by dawei-dev** [comment]
@TimoFreiberg I ran into the same problem. After installing `ncurses5-compat-libs`, everything back to normal.

**Comment by TimoFreiberg** [comment]
@dawei-dev awesome, now it works again.

**Comment by denumerate** [comment]
@borsboom the `ncurses5-compat-libs` package worked. Thanks. But since its on the AUR it can't be added to stack's dependencies, so sadly doesn't work 'out of the box'

**Comment by cocreature** [comment]
I just built a bindist of 8.0.2 on Archlinux following the instructions provided by @borsboom and it seems to work just fine. What is needed to make an official bindist so we get back to stack working out of the box on Archlinux?

**Comment by borsboom** [comment]
Please make a pull request against https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml

**Comment by borsboom** [comment]
This was handled in https://github.com/fpco/stackage-content/pull/26.  A similar issue exists for GHC 8.2.2 though: https://github.com/commercialhaskell/stack/issues/3636
