### ISSUE TITLE
Unable to run `stack setup` on Arch Linux

### ISSUE THREAD

**Issue by johannesgerer** [commercialhaskell/stack#3272]
### Steps to reproduce

1. Delete `~/.stack`
2. Install stack `curl -sSL https://get.haskellstack.org/ | sh`
3. Run `stack setup`

### Expected

No error

### Actual

````
Unable to find installation URLs for OS key: linux64-ncurses6-nopie
````

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

**Comment by johannesgerer** [comment]
Duplicate #3268

**Comment by flounders** [comment]
This seems to be related to this issue: https://github.com/commercialhaskell/stack/issues/3268

I was having issues building packages, you may wish to try installing ncurses5-compat-libs. I'm pretty sure that will clear it up.

**Comment by johannesgerer** [comment]
Yes solved it. Thanks
