### ISSUE TITLE
Document available variables

### ISSUE THREAD

**Issue by wdanilo** [commercialhaskell/stack#3282]
Hi!
I've found here https://github.com/commercialhaskell/stack/issues/496 that there are some variables we can use in stack config files, like mentioned `$benchmark`, which is a benchmark name. Is there any documentation regarding available variables? (I haven't found any so far).

**Comment by mgsloan** [comment]
The PR referenced in that commit - https://github.com/commercialhaskell/stack/pull/512/files - doesn't seem to add support for `$benchmark`, I don't think that feature got implemented.  AFAIK there are no variables that can be interpolated in stack's args or config.
