### ISSUE TITLE
Stack ghci feature requests

### ISSUE THREAD

**Issue by andrewthad** [commercialhaskell/stack#329]
I just realized that `stack ghci` is little bit lacking compared to `cabal repl`. It would probably be desirable for it to enable extensions in `projectname.cabal` and to load all the modules when it starts. If there is a workaround or something you can stick in the `.ghci` file to get some of this behavior, it would be good to document that.

**Comment by snoyberg** [comment]
Check out PR #328 and issue #130

**Comment by andrewthad** [comment]
I like the direction that the other opened issue went in. Glad to hear features for this got merged in.
