### ISSUE TITLE
`stack exec` stopped propagating paths

### ISSUE THREAD

**Issue by leohaskell** [commercialhaskell/stack#3292]
### Steps to reproduce

1. `stack setup`
2. `stack install happy`
2. `stack exec --no-ghc-package-install-path mintty`
3. `ghci`
4. `happy`

### Expected
Before some time, this opened ghci and ran happy without any problems.

### Actual
`bash: ghci: command not found`
`bash: happy: command not found`

I think that for some reason, stack stopped propagating the needed paths.

*Note:* I'm sure this was working before, because that was the way I was building GHC bindists. It was quite convenient, because there was no need to manually install the needed packages somewhere beforehand.

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd x86_64 hpack-0.17.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by Blaisorblade** [comment]
Can you reproduce this with stack exec bash or stack exec --no-... bash?  Otherwise, who knows what mintty is running and whether it's clearing the environment. I'm not sure, but there are many scenarios where mintty, or scripts it launches, should/could (say, launching a login shell).

**Comment by Blaisorblade** [comment]
(And if you need a new mintty session, I'd try launching a new mintty session and launching this inside; I guess this could even be scriptable somehow, but would have to look closer to confirm).
Caveat: All of this is IIUC.

**Comment by leohaskell** [comment]
The issue doesn't exist when launching `stack exec bash`.

**Comment by Blaisorblade** [comment]
> The issue doesn't exist when launching stack exec bash.

OK, good to confirm.

Great! Is there a problem in using `stack exec bash` for your goal of building GHC bindists? If there is, maybe that can be helped.

I expect stack is not involved in the mintty case and for now I'm closing this—though I'm very willing to be proven wrong.

**Comment by leohaskell** [comment]
`stack exec bash` worked just fine for my task. I'll let you know if anything else pops out.
