### ISSUE TITLE
Confusing Stack Version After Run `stack upgrade`

### ISSUE THREAD

**Issue by wisn** [commercialhaskell/stack#3297]
My current Stack version is 1.4.0. I'm trying to upgrade to the latest version which is 1.5.0. But it's never reach 1.5.0 because whenever run command `stack upgrade` it's always said the version is still 1.4.0 and if I'm use the [this steps](https://docs.haskellstack.org/en/stable/install_and_upgrade/#installupgrade) the output always said it's has been the latest one which is 1.5.0. What should I do? Delete Stack and reinstall again?

### Steps to reproduce

1. Check the Stack version with `stack --version`.
2. Run command `stack upgrade`.
3. Check the Stack version again with `stack --version`.
4. Since the message is still `1.4.0`, run command `curl -sSL https://get.haskellstack.org/ | sh`.
5. Check the Stack version again with `stack --version`.

### Expected

Expected output for the version after running upgrade command is `1.5.0`.

### Actual

First, check the Stack version.

```
$ stack version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

Then, run command `stack upgrade --verbose`.

```
$ stack upgrade --verbose
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
2017-07-28 14:59:42.581714: [info] Current Stack version: 1.4.0, available download version: 1.5.0
@(Stack/Upgrade.hs:152:17)
2017-07-28 14:59:42.607774: [info] Newer version detected, downloading
@(Stack/Upgrade.hs:168:13)
2017-07-28 14:59:42.607857: [info] Querying for archive location for platform: linux-x86_64-static
@(Stack/Setup.hs:1712:13)
2017-07-28 14:59:42.607943: [info] Downloading from: https://github.com/commercialhaskell/stack/releases/download/v1.5.0/stack-1.5.0-linux-x86_64-static.tar.gz
@(Stack/Setup.hs:1728:5)
2017-07-28 15:03:45.799281: [info] Download complete, testing executable
@(Stack/Setup.hs:1737:5)
Version 1.5.0, Git revision 63267f94d7c819cbecc2d59aa259d17240838e43 (4845 commits) x86_64 hpack-0.17.1
2017-07-28 15:03:45.810714: [info] New stack executable available at /home/wisnu/.local/bin/stack
@(Stack/Setup.hs:1756:5)
```

It's said that the stack has been upgraded. So, check the version again.

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

The output is weird. Yes, the version still the same. Try to upgrade with [this manual](https://docs.haskellstack.org/en/stable/install_and_upgrade/#installupgrade). I'm use the `Linux generic option`. I'm use Ubuntu by the way.

```
$ curl -sSL https://get.haskellstack.org/ | sh -f
Stack Version 1.5.0 already appears to be installed at:
  /home/wisnu/.local/bin/stack
Use 'stack upgrade' or your OS's package manager to upgrade,
or pass '-f' to this script to over-write the existing binary.
```

It's said the version is `1.5.0`. I'm trying to run `stack --version` again to make sure.

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

It's still the same. If you run `stack upgrade` command again, Stack will upgrading to 1.5.0 and said my Stack version is 1.4.0. This is an endless.

### Stack version

```
$ stack --version
Version 1.4.0, Git revision e714f1dd3fade19496d91bd6a017e435a96a6bcd (4640 commits) x86_64 hpack-0.17.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by borsboom** [comment]
Does your PATH have `/home/wisnu/.local/bin` near the front (before any system bin directories like /usr/bin and /usr/local/bin)?

If so, try running `hash -r` to get bash to forget its cached location for `stack` so that it uses the one in `/home/wisnu/.local/bin`.  Another approach would be to copy `/home/wisnu/.local/bin/stack` to wherever your old stack binary was installed (`command -v stack` might help; chances are it's /usr/local/bin).  The next version of Stack will offer to do this automatically when you `stack upgrade`.

By the way `curl -sSL https://get.haskellstack.org/ | sh -f` won't work because you're passing `-f` to `sh`, _not_ to the script itself.  The way you do that is `curl -sSL https://get.haskellstack.org/ | sh -s - -f`).

**Comment by wisn** [comment]
I just need to use `hash -r`. Thanks! You may now close this issue.
