### ISSUE TITLE
Stack doesn't rebuild on test suite changes

### ISSUE THREAD

**Issue by meteficha** [commercialhaskell/stack#330]
On a package that was already built and `stack test`ed before:

```
$ stack build
```

Great, nothing was done as expected:

```
$ touch tests/Main.hs 
$ stack build
```

Expected test suite to be rebuilt, nothing is done.

```
$ touch src/Web/ServerSession/Core.hs 
$ stack build
serversession-1.0-cd6dc198bb7e213ff4f5bd018f30345a: unregistering
serversession-1.0: configure
Configuring serversession-1.0...
...
```

Rebuilds the package *and* the test suite.

The same happens when using `stack test` instead of `stack build`.  The only difference is that `stack test` runs the stale test suite after not rebuilding.

**Comment by meteficha** [comment]
```
$ stack --version
Version 0.0.2.1
$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library 
```

**Comment by snoyberg** [comment]
This should be fixed on master, @chrisdone implemented it today. Can you confirm?

**Comment by meteficha** [comment]
Works on master, thanks!
