### ISSUE TITLE
`--ghc-options` only takes a single option

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3315]
From the comment here https://github.com/commercialhaskell/stack/issues/758#issuecomment-319676025 : 

```
$ stack ghci --ghc-options="-ddump-simpl -dsuppress-idinfo"
Configuring GHCi with the following packages:
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
ghc.EXE: unrecognised flag: -ddump-simpl -dsuppress-idinfo

Usage: For basic information, try the `--help' option.
```

Curiously, the documentation on the `argsOption` function that handles this mentions --ghc-options, but it isn't currently used:

```haskell
-- | An option which accepts a list of arguments e.g. @--ghc-options="-X P.hs \"this\""@.
argsOption :: O.Mod O.OptionFields [String] -> O.Parser [String]
```

Fix is to use this for `ghc-options` and make sure it's also used for other similar options fields

**Comment by lwm** [comment]
Done in https://github.com/commercialhaskell/stack/commit/9e2bd404dd46d043a9a3d289db23a878a911510a.

**Comment by mgsloan** [comment]
Re-opening this.  Here's what happened:

* The fix broke another usecase - https://github.com/commercialhaskell/stack/issues/3353

* We want to do a release soon.

* I don't want to try implementing any complex solution this close to release, so I reverted the fix to this.

Note that any future fix to this should also consider the usecase in #3353.  It is also worthwhile to take a look at how `ghc-options` and `ghcjs-options` work in the stack configuration, and have it be consistent with the CLI in its parsing.

**Comment by sclausen** [comment]
@mgsloan I would be glad, if you could tell, what the status of this is.

**Comment by mgsloan** [comment]
@sclausen I think the proper steps forward were in the other issue https://github.com/commercialhaskell/stack/issues/3353#issuecomment-330394011 .  Copying what I said there:

Actually, I think that this was never a problem for configure-options, just an issue when invoking ghci directly with multi-ghc-options. I noticed that the configuration parsing code for stack.yaml uses argument parsing for "ghc-options", when it probably shouldn't. So, steps would be:

* Use parseArgs for options passed to ghci
* Remove use of parseArgs for --ghc-options in cli and ghc-options: in config

Also I will add one more step:

* Add tests for mutltiword options that both build and invoke ghc
* Add tests for multiword options that include RTS options.

**Comment by sclausen** [comment]
@mgsloan thansk for the quick answer!

**Comment by snoyberg** [comment]
See #4747
