### ISSUE TITLE
GHC 8.2.1 integer-simple bindist

### ISSUE THREAD

**Issue by leohaskell** [commercialhaskell/stack#3335]
### Summary
Since stackage nightly already uses ghc-8.2.1, it'd be nice to have an integer-simple bindist, which I'm providing here: [ghc-8.2.1-integer-simple](https://drive.google.com/open?id=0Bx1PZr9g0_7cU1NDTmwtREotSkU).

**Comment by borsboom** [comment]
Alright, I've added it to [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml#L455)
