### ISSUE TITLE
Download script issues

### ISSUE THREAD

**Issue by ekmett** [commercialhaskell/stack#3350]
When I use the download script obtained from https://haskell-lang.org/get-started it complains if there is already a system stack installed even if I go to use -d to manually pick a different location (e.g. a local install inside of another directory explicitly avoiding the global install)

```
/Users/edward/toy-project> ./download_stack.sh -d .
Stack Version 1.1.2 already appears to be installed at:
  /usr/local/bin/stack
Use 'stack upgrade' or your OS's package manager to upgrade,
or pass '-f' to this script to over-write the existing binary, e.g.:
  curl -sSL https://get.haskellstack.org/ | sh -s - -f
```

But note that the instructions for using -f seem to imply that writing it to this new location (not the same one as before) will over-write the other location? I'd expect that if I explicitly name a different download location and there isn't a file at that location that I shouldn't have to -f or that the error message would be less misleading when it isn't going to actually clobber something at the current target location.

This may belong against another repository. I didn't actually track down where the script was created.

**Comment by mgsloan** [comment]
Thanks for reporting, @ekmett ! Pinging @borsboom
