### ISSUE TITLE
Only build specific executables

### ISSUE THREAD

**Issue by lostman** [commercialhaskell/stack#336]
Suppose I have a package `foo` which defines executables `exe1`, `exe2` and `exe3`.

With `cabal build` I can compile a single executable:
```
cd foo/
cabal build exe1
```

This is incredibly useful for development. Otherwise, even for small incremental changes, all executables are rebuilt and the bulk of time is spent on that.

**Comment by snoyberg** [comment]
Please see #201, which I just implemented. It should now work to run `stack build foo:exe1`. If not, let's discuss on #201.

**Comment by RasmusWL** [comment]
For reference I will point to [#1406 (stack 0.1.8 lost ability to build individual executables or library) ](#1406) so other people will realise faster that they are not idiots, and that this feature is just not working right now.
