### ISSUE TITLE
Profiling with -Werror and GHC 8.2 is broken

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3360]
Using Windows 64bit, Stack 1.5, if I create a stack file for the Shake package pointing at `nightly-2017-08-17` (a GHC 8.2 nightly), then run:

```
stack build --executable-profiling --library-profiling --ghc-options=-Werror
```

I get the error:

```
Configuring shake-0.15.11...

<no location info>: error:
Failing due to -Werror.

on the commandline: warning:
    -auto-all is deprecated: Use -fprof-auto instead

on the commandline: warning:
    -caf-all is deprecated: Use -fprof-cafs instead
```

The cause is https://github.com/commercialhaskell/stack/blob/aa5003a153504f54051e42a844a0c1c3d7f82163/src/Stack/Build/Source.hs#L160. I suggest either using the new flags (if you only care about newer GHC's), or doing a GHC version test.

I tested this with Shake, but I believe the problem applies to all packages.

**Comment by mgsloan** [comment]
Thanks for reporting! Looks like these have been old flags even when it was implemented.  From the [latest docs](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/profiling.html)

> -fprof-auto was known as -auto-all prior to GHC 7.4.1.

And indeed, the earliest supported ghc, 7.8 has -prof-cafs as well: https://downloads.haskell.org/~ghc/7.8.1/docs/html/users_guide/flag-reference.html

So, no version check is needed.

**Comment by ndmitchell** [comment]
Did you intend to close this issue?

**Comment by mgsloan** [comment]
Oh yeah forgot to mention i pushed a fix to master https://github.com/commercialhaskell/stack/commit/e21bfd9d6434d115e4adfb01ba838cf06da605d3

**Comment by ndmitchell** [comment]
Thanks!
