### ISSUE TITLE
'stack hoogle generate' erroneously considers packages to be missing documentation

### ISSUE THREAD

**Issue by jchia** [commercialhaskell/stack#3362]
### General summary/comments (optional)
"stack hoogle generate --rebuild -- --local" gives "Packages missing documentation" for 'vector' package. This is a regression from Stack 1.4.0 to 1.5.0. The issue remains in 1.5.1.

### Steps to reproduce
This was reproduced on Fedora 22 using downloaded stack binary ~/.local/bin/stack.
```
$ stack upgrade --binary-version 1.5.1 # Also repros with 1.5.0 but not with 1.4.0.
$ rm -rf ~/.stack
$ stack new --resolver=lts-9.1 doc
$ cd doc
$ vim doc.cabal # Add vector to the library build-depends
$ stack setup
$ stack haddock
$ stack hoogle generate --rebuild -- --local
```
The `stack hoogle` command complains about "Packages missing documentation" and 'vector' is one of the affected packages. There's nothing special about 'vector'. I'm just using it as an example of a package affected by this issue.

### Expected

'vector' should not be one of the "packages missing documentation".

### Actual

```
...
Generated DB.
Starting generate
Reading ghc-pkg... 0.02s
[6/30] containers... 0.11s
[10/30] ghc... 1.87s
[26/30] xhtml... 0.05s
Packages missing documentation: doc primitive rts vector
Found 42 warnings when processing items
...
```
### Stack version
Repros with 1.5.0 & 1.5.1 but not with 1.4.0.

```
$  stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

### Method of installation
* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by kadoban** [comment]
Thanks for the report!

I'm trying to narrow down the commit that caused this change, but it's taking a while (having trouble coming up with a reproduction script that takes less than about an hour per test). I should be able to narrow it down eventually though.

Or someone that actually knows what they're doing might come along first :)

**Comment by bmjames** [comment]
I spent some time investigating this and determined that the missing modules don't have the `<module>.txt` file (produced by haddock for consumption by the hoogle indexer) in their docs directory. I didn't get as far as determining whether this is caused by a problem in haddock, cabal, or stack.

**Comment by ndmitchell** [comment]
The bug was introduced at https://github.com/commercialhaskell/stack/commit/d0ab69c266c99611cc3c4dbfe24e95bb15956977#diff-890614cc04afa326f5d48aac897e4aa8 - specifically it added support for haddock-arguments and removed `hoogle`. I'll send a PR.

**Comment by ndmitchell** [comment]
Rather than raise a PR, since I'm an idiot with too many permissions, I accidentally pushed direct to the Stack repo. Ticket to review/revert the patches is at #3478.
