### ISSUE TITLE
Drop GHC 7.10 support in the Stack codebase?

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#3373]
To clarify the title: should we drop support for building Stack itself with GHC 7.10? We will continue to support _using_ GHC 7.10 from Stack for other projects.

The reason for this is logging. Beginning with GHC 8.0, the `monad-logger` library provides a new module, `Control.Monad.Logger.CallStack`, which leverages the recent callstack feature for getting source location information. The old method uses Template Haskell to do the same job. My hope is that, by switching away from TH, we may be able to disable its usage in many modules, and perhaps speed up compilation time.

Downside: we're dropping GHC 7.10 support. I'm not sure if this affects anyone, which is why I'm opening (and subsequently will publicize) this issue. As is often the case: please use the thumbs up/thumbs down reactions for voting. Thumbs up: drop GHC 7.10 support. Thumbs down: don't do it yet.

**Comment by fosskers** [comment]
Most of us probably get it as a binary through our distros anyway.

**Comment by snoyberg** [comment]
The biggest concern with this change is that some distro out there is building Stack with older GHC versions and this will break things for them. Or something similar. Hopefully that's not the case. I agree that this should ideally have no impact on the vast majority of users.

**Comment by DanBurton** [comment]
Would it be a lot of work to CPP around this in order to get the faster compile times if GHC 8 is in use?

**Comment by snoyberg** [comment]
I can't think of a way of doing it that doesn't triple the verbosity of all the logging code.

**Comment by borsboom** [comment]
Could one not define CPP macros in a `.h` file that switch the behaviour depending on GHC version and `#include` it in any module that does logging?  Then you just replace calls to the logging TH with the macros.

Note: I am not actually advocating this, just mentioning it as a possibility.

**Comment by snoyberg** [comment]
It's possible. I had assumed that CPP would choke on the difference between `$logDebug` and `logDebug`, but maybe we could make it work. Nonetheless: the fixed overhead of an extra `#include` in each file plus running CPP itself in all of these files makes me think it's worse than sticking with the status quo.
