### ISSUE TITLE
readthedocs.org search is broken

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3376]
Thinking this is likely a readthedocs bug, but perhaps it is some configuration issue.  Seems that the search on https://docs.haskellstack.org/en/stable/README/ doesn't work.  If I input keywords that are definitely used, like `stack`, I get no results - https://readthedocs.org/search/?q=stack&check_keywords=yes&area=default&project=stack&version=stable&type=file

Pinging @borsboom

**Comment by lwm** [comment]
https://github.com/commercialhaskell/stack/issues/3298 :disappointed:

**Comment by mgsloan** [comment]
This guy's workaround - https://github.com/rtfd/readthedocs.org/issues/1487#issuecomment-323290547 - seems ok: https://github.com/nodemcu/nodemcu-firmware/commit/7dd89dd15ef993c9740ba4d4361e6be8edd1284b .  Stack's docs are not huge, so doing clientside search seems fine.

**Comment by borsboom** [comment]
That workaround certainly seems like a reasonable thing to try.  We'd probably need to add an `extra_javascript` clause to mkdocs.yml (like [this](https://github.com/nodemcu/nodemcu-firmware/blob/7dd89dd15ef993c9740ba4d4361e6be8edd1284b/mkdocs.yml#L18))

**Comment by lwm** [comment]
Nice detective work :shipit:

**Comment by borsboom** [comment]
The docs for the branch, for whatever reason, decided to build successfully (even though most builds are still failing).  In the JS console, I get a 404 when it tries to load `https://docs.haskellstack.org/en/fixup-search/etc/mkdocsjs/searchhack.js`.  That's because the `extra_javascript` setting in `mkdocs.yml` should be within the `doc` directory.  I've pushed a new branch `3376-fix-search` that fixes that... hopefully mkdocs will build it.

**Comment by borsboom** [comment]
Mkdocs does seem to have rendered the docs: https://docs.haskellstack.org/en/3376-fix-search/README/.

However, search still doesn't work.

**Comment by borsboom** [comment]
I suspected that the `if (window.location.origin.indexOf('readthedocs') > -1)` check was the reason, so I tried using http://stack.readthedocs.io/en/stable/README/ instead but also didn't work at that URL.

**Comment by borsboom** [comment]
Oh, woops, I pointed to the wrong branch on `stack.readthedocs.io`.  If I go to http://stack.readthedocs.io/en/3376-fix-search/README/ the search box actually disappears, but there's this much more informative error in the JS console:
>  ReferenceError: determineSelectedBranch is not defined
>   at MutationObserver.<anonymous> (searchhack.js:16)

**Comment by borsboom** [comment]
I've pushed a fix, trying to force a build again.

**Comment by borsboom** [comment]
Fix seems to have worked!  Try it out at https://docs.haskellstack.org/en/3376-fix-search/README/.  I've opened PR #3415 with @lwm's original changes plus my fixes.

**Comment by borsboom** [comment]
Incidentally, you may be amused at my way of getting RTFD to render the docs:
```
while ! curl --fail https://docs.haskellstack.org/en/3376-fix-search/README/ >/dev/null; do curl -v -F 'version_slug=3376-fix-search' https://readthedocs.org/build/41861; sleep 60; done
```

**Comment by lwm** [comment]
Heroic effort @borsboom! :clap:
