### ISSUE TITLE
Flag for turning off progress indicator

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#338]
Sometimes the environment claims to be a real interactive terminal where cursor movement makes sense when actually it's more like a log file (e.g. in Travis CI, see [here](https://github.com/travis-ci/travis-ci/issues/1337)). In this case, standard output is connected to a "terminal", but the user will want to omit "Progress N/M" indicators in the output, or make them appear on their own line properly (and less frequently). The easiest option here is to the user request progress not to appear, say by passing a `--no-progress` flag.

**Comment by chrisdone** [comment]
There're other cases where terminal support is assumed besides progress, so probably `--no-terminal` or something like it would apply more generally. It'll be easy to add this.
