### ISSUE TITLE
Only run hpack once per package.yaml

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3382]
Currently, hpack gets invoked a fair number of times, I count 6 times for a `stack build` on a trivial project.  This is usually pretty quick, but I'm not sure how smart it is about avoiding work.  This is particularly important if there's an option to use the `hpack` executable - https://github.com/commercialhaskell/stack/issues/3179 .

**Comment by snoyberg** [comment]
I'm fairly certain this is no longer the case, please reopen if you're still seeing it with the latest `master`.
