### ISSUE TITLE
Have build output explain where package is installed to

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3401]
When considering https://github.com/commercialhaskell/stack/issues/3398 , the thought occurred to me that it might be helpful for the user to know where a particular package is being installed to.  Experienced stack users can usually tell this by looking at a stack.yaml, but I think it might be helpful for folks to understand its behavior if the `copy / register` step was annotated with where it is being installed to.  Doesn't need to be detailed.  Instead:

```
yaml-0.8.23.3: copy/register (snapshot)
path-0.6.1: copy/register (local extra-dep)
stack-1.5.1: copy/register (local project)
```

I think it would also be helpful to explain where the package comes from (`hackage`, `git`, `hg`, `local`, etc), but not sure where a good place to put that info would be.

**Comment by mpilgrem** [comment]
I am closing given the passage of time and because current versions of Stack do report where libraries are being installed.
