### ISSUE TITLE
Consider whether there are issues with SIGKILLing stack and lockfiles

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3407]
I have a suspicion that the use of lock files is broken if stack gets killed instead of terminated.  Not sure how to solve that, I can think of two things that would help:

1) Let the user know when it has been blocked on a lock file for more than a second.  Let them know about the workaround to delete the lockfile.

2) Perhaps just (1) is sufficient, but it could make sense to have some expiration on the lockfile.  This seems not-so-useful, because to be safe the expiration should be huge, like an hour.

Thinking (1) is the right resolution.

**Comment by SimSaladin** [comment]
Since `System.FileLock` just uses `flock(2)` on non-windows platforms, the OS should take care of everything in case of `SIGKILL` and such, see https://stackoverflow.com/questions/12651068/release-of-flock-in-case-of-errors#12652718.

No idea what are the implications for a Windows system though.

**Comment by borsboom** [comment]
Alternatively, Stack could have a background thread that writes the lockfile once per second.  A lockfile that's more than five seconds old could be considered expired.  A KILLed `stack` would stop updating the lockfile, so this should be safe.  Of course letting the OS take care of these details, as recommended by @SimSaladin, would be better.

**Comment by snoyberg** [comment]
As mentioned, System.FileLock properly handles this, closing
