### ISSUE TITLE
Installing stack in the home directory

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack#3418]
It would be nice to have an option to install stack in the home directory. My situation is that i don't have sudo rights to install into `/usr/local/bin/stack`. I installed rust too with [rustup](https://www.rustup.rs/) and with this installer there was no problem.

**Comment by mattaudesse** [comment]
Hi @flip111 - do the "manual install" directions [here](https://docs.haskellstack.org/en/stable/install_and_upgrade) work for you?

You can definitely put `stack` in your home directory but it's slightly more involved than the CLI one-liner that a lot of folks use.

**Comment by borsboom** [comment]
You can pass `-d path/to/destination` to the get-stack script.  E.g.

```
curl -sSL https://get.haskellstack.org/ |  sh -s - -d $HOME/.local/bin
```

Note, however, that the script will still `sudo` in order to install dependencies.  In theory it would be possible for the script to skip that as well, but it doesn't support that feature yet.

**Comment by flip111** [comment]
@mattaudesse do you mean this section of the manual? https://docs.haskellstack.org/en/stable/install_and_upgrade/#manual-download_3

@borsboom your suggestion worked for me, thx

**Comment by mattaudesse** [comment]
@flip111 I didn't know which platform you were using based on your first post, but yup: there are manual installation instructions for a number of OSes on that page.

I'm glad you were able to make it work.

**Comment by dchiu911** [comment]
Hi @mattaudesse @borsboom is there a way to bypass `sudo` using the installer script 
```sh
wget -qO- https://get.haskellstack.org/ | sh
```
I keep getting prompted for `sudo` even when I tried to pass `-d $HOME/.local/bin`

**Comment by mattaudesse** [comment]
Hey @dchiu911, based on [Borsboom's comment above](https://github.com/commercialhaskell/stack/issues/3418#issuecomment-327268570) and looking at the script itself, it seems like `sudo` is still necessary for installing dependencies via your system's package manager.

**Comment by borsboom** [comment]
In theory, the script could offer a "sudo-less" mode where it would just tell you the commands to run to install the dependencies rather than doing it for you.  A PR implementing that would certainly be welcome.
