### ISSUE TITLE
Whether or not support arm64

### ISSUE THREAD

**Issue by longquan7** [commercialhaskell/stack#3419]
I don't know the file of stack-1.5.1-linux-arm.tar.gz whether or not support arm64 architecture?

**Comment by mgsloan** [comment]
I believe the most up-to-date info on this is here: https://github.com/commercialhaskell/stack/issues/1755

So, unfortunately I think the answer seems to be that it is not officially supported, but it might be possible to get it working.

**Comment by longquan7** [comment]
@mgsloan OK,thanks
