### ISSUE TITLE
chroot untar fail

### ISSUE THREAD

**Issue by jmikedupont2** [commercialhaskell/stack#3425]
on gnuroot debian on android untar of the ghc is failing because utime is not supported on the filesystem.

On ```stack setup```
Error message looks like this 
```tar <filename> Cannot utime: Operation not permitted```

**Comment by jmikedupont2** [comment]
This seems to be related to se linux and the way the homedir is mounted on the gnuroot. I have replaced tar with a shell script to squash the return value of tar, but get into more issues.

**Comment by jmikedupont2** [comment]
workaround 
```
mkdir /root2
mv /home/.stack  /root2/.stack
export HOME=/root2
stack setup
```

**Comment by jmikedupont2** [comment]
please close

**Comment by mattaudesse** [comment]
Closing for @jmikedupont2

**Comment by jmikedupont2** [comment]
I published a post of setting up haskell and debian 
on my android https://libertyformobile.wordpress.com/2017/09/13/installing-glasgow-haskell-compiler-ghc-8-0-4-via-stack-on-samsung-s6-active-android
