### ISSUE TITLE
feature request download restart

### ISSUE THREAD

**Issue by jmikedupont2** [commercialhaskell/stack#3426]
using my mobile phone to run stack is problematic because the stack setup download is large and sometimes the connection breaks. having a feature to restart the download would be helpful.

**Comment by lwm** [comment]
> using my mobile phone to run stack

Awesome!

This is a duplicate of https://github.com/commercialhaskell/stack/issues/3085, so I'll close.

Please do voice your opinion on #3085, or better, consider submitting a PR!
