### ISSUE TITLE
Hackage support

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#343]
*stack build* could not download library from Hackage

> Checking against build plan lts-2.14
> Checking against build plan lts-1.15
> Downloading nightly-2015-06-17 build plan ...
> Downloaded nightly-2015-06-17 build plan.
> Updating package index hackage.haskell.org ...
> Populating index cache, may take a moment ...
> Done populating index cache.
> Checking against build plan nightly-2015-06-17
> Writing default config file to: D:\temp\test\stack.yaml
> While constructing the BuildPlan the following exceptions were encountered:
> 
> --  Failure when adding dependencies:
>       hS3: needed (-any && -any), but not present in build plan
>     needed for package: test
> 
> --  While attempting to add dependency,
>     Could not find package hS3 in known packages
> 
> D:\temp\test>stack deps hS3
> While constructing the BuildPlan the following exceptions were encountered:
> 
> --  While attempting to add dependency,
>     Could not find package hS3 in known packages

**Comment by snoyberg** [comment]
The newest code on master gives a clearer error message with instructions. You need to add the package to your `extra-deps`, something like:

```yaml
extra-deps:
- hS3-0.5.9
```

**Comment by varosi** [comment]
After this change, now it give:

> While constructing the BuildPlan the following exceptions were
encountered:
>
> --  Failure when adding dependencies:
>       hS3: needed (-any && -any), but not present in build plan
>     needed for package: test
>
> --  While attempting to add dependency,
>     Could not find package hS3 in known packages

2015-06-17 23:34 GMT+03:00 Michael Snoyman <notifications@github.com>:

**Comment by drwebb** [comment]
Could you try updating your version of stack to the latest version for download (0.0.3 should also be out soon), and try again after running a `stack update`. Also please post your full `stack.yaml`.

**Comment by varosi** [comment]
I have updated it and I saw my mistake. I had to add extra-deps in stack.yaml and not in .cabal file. 
Now it is working well! Thanks!

My ask is if it is possible to extract that information from .cabal instead from stack.yaml, since this information is already in .cabal file.

**Comment by snoyberg** [comment]
It's not possible to get this information from the .cabal file. The .cabal file gives a range of versions for a package, but doesn't tell us:

* A specific version
* Whether it should come from the package index, local file, Git, HTTP, etc

Said another way: there are certain corner cases where stack *could* guess how to install an extra dependency based on a .cabal file's contents, but it wouldn't work reliably, and wouldn't be reproducible over time, so we don't do it.
