### ISSUE TITLE
Output a warning when extra-deps no longer need to be extra-deps

### ISSUE THREAD

**Issue by lwm** [commercialhaskell/stack#3437]
Whether the package should stay defined in the `extra-deps` field is not something that can be checked without manually looking, which is boring - so, I'm sure Stack can output a warning here.

**Comment by mgsloan** [comment]
Makes sense to me!

**Comment by kadoban** [comment]
What would be the logic here though? Are we talking about when an extra dep is specified that exactly matches what's already in the resolver? Doesn't seem like that would come up too much, wouldn't the version usually be different? And if the version is different, we can't really warn for that, right? (since that's a common use-case _for_ using extra deps)

**Comment by lwm** [comment]
Well, as far as I understand, we normally add a package to the extra-deps field when we can't find it in the resolver (it's on hackage though) - at some point, it gets into one of the resolvers (maintainer adds it to stackage ecosystem) and then hey, we don't need it in our extra-deps any more!  I'm still really fuzzy on Stack internals (still!), but that is my simple motivation. I'm not sure if anyone actually cares about packages lurking in their extra-deps field, but it bugs me ;)

**Comment by kadoban** [comment]
Right, that's one very common use-case for extra deps. But the other one I use is if the version of a package in a resolver isn't the one you need, you can override the version with an extra-dep. So I'm not sure how we'd give a warning for your case without also giving a warning for my case (which isn't actually wrong at all).

Maybe if the version number between what's in the extra dep and what's in the resolver were too close we could warn? But I'm not sure what the logic for that could be, concretely.

Maybe if there is a version constraint in the .cabal file and both the extra dep and the resolver would satisfy that constraint? That might make sense to warn on.

**Comment by lwm** [comment]
Ah, I see - I didn't know people used it like that! So, I think you're right, warning for my case would give false warnings for the other. I'll close this off then, thanks!
