### ISSUE TITLE
`stack hoogle` doesn't recognize /usr/bin/hoogle (5.0.1) from apt

### ISSUE THREAD

**Issue by unhammer** [commercialhaskell/stack#3440]
### Steps to reproduce

```
$ sudo apt install hoogle --no-install-recommends
…

$ stack hoogle --no-setup data

```

### Expected

Hoogle creating its magic database

### Actual

Stack thinks my hoogle is too old:
```
$ stack hoogle --no-setup data
Hoogle isn't installed or is too old. Not installing it due to --no-setup.
Hangup
```

Even though I have
```
$ hoogle --version
Hoogle 5.0.1, http://hoogle.haskell.org/

$ command -V hoogle
hoogle is hashed (/usr/bin/hoogle)

$ dpkg -s  hoogle|grep ^V
Version: 5.0.1+dfsg1-2build1
```

and
```
$ stack hoogle --setup data
Hoogle isn't installed or is too old. Automatically installing (use --no-setup to disable) ...
Minimum version is hoogle-5.0. …
```
says 5.0 is the minimum.

### Stack version

```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

### Method of installation

github release
stack-1.5.1-linux-x86_64

**Comment by lwm** [comment]
What does `stack exec -- hoogle -- --version` give you? I thought you needed to install `hoogle` with stack first, not by package manager, to get this functionality. It seems like this should work though - since you have a perfectly fine and up to date `hoogle` installed ...

**Comment by unhammer** [comment]
Oh right, I had an old one lying around :(

```
$ stack exec hoogle -- --version
Hoogle v4.2.43, (C) Neil Mitchell 2004-2012
http://haskell.org/hoogle
```

Thanks; removing the bin there helped. 

That turns this into a feature request: When `stack hoogle` tells me my version is out of date, could it print the absolute path to the hoogle it found?

**Comment by mgsloan** [comment]
@unhammer Good point!  There were actually quite a few things that were iffy about the old code, like it wouldn't check if hoogle is on path after installing it.  I've fixed those things along with this.  It now says:

> Installed Hoogle is too old, /home/mgsloan/.local/bin/hoogle has version 4.2.41 but >= 5.0 is required. Automatically installing (use --no-setup to disable) ...
