### ISSUE TITLE
I can't even get Stack started!

### ISSUE THREAD

**Issue by BigTone2009** [commercialhaskell/stack#3452]
I've just installed the latest Windows 64 Bit stack (v1.5.1) and when I run Stack to create a new project 

`stack new helloworld new-template`

 I am met with this stream of nonsense:-
```
Downloading template "new-template" to create project "helloworld" in helloworld\ ...
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/commercialhaskell/stack-templates/master/new-template.hsfiles"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
(InternalException (HostCannotConnect "raw.githubusercontent.com" [Network.Socket.connect: <socket: 672>: failed (Connection timed out (WSAETIMEDOUT))]))
```

What on earth is going on?
Can anyone out there help?

**Comment by lwm** [comment]
There are a number of outstanding network related issues but this seems to be a case of github down time (the template you tried to access is in a repo hosted there). Please try again.

**Comment by BigTone2009** [comment]
@lwm Thanks for responding. I've tried again but to no avail. If I point my browser at the [raw.githubusercontent.com](url) site I get a timeout error. I don't get this error with any other sites. Is the problem with me or the remote site. Is the problem with my firewall, if so, how should I correct it?

**Comment by lwm** [comment]
What happens when you:

``` bash
$ curl -X GET https://raw.githubusercontent.com/commercialhaskell/stack-templates/master/new-template.hsfiles
```

A timeout? That's the exact file Stack is trying to get.

Looks like you might be facing some firewall issue - that's beyond me!

**Comment by BigTone2009** [comment]
@lwm When I try curl in the Windows command window, I get the following which is at least consistent.
```
curl -X GET https://raw.githubusercontent.com/commercialhaskell/stack-templates/master/new-template.hsfiles

curl: (7) Failed to connect to raw.githubusercontent.com port 443: Timed out
```

**Comment by lwm** [comment]
I see. You might want to look [at some firewall related issues](https://github.com/commercialhaskell/stack/issues?utf8=%E2%9C%93&q=is%3Aissue%20%22firewall%22) for debugging. 

It appears to not be a Stack issue though.

**Comment by BigTone2009** [comment]
@lwm I finally found the reason why I couldn't get Stack to work. Unbeknownst to me, my ISP was blocking access to the site [raw.githubusercontent.com](url). It seems it is regarded, by them, as a hotbed of Phishing & Malware. The problem was righted by allowing access through the router's Web Browser.

This is troubling, as I thought GitHub was regarded as a respected place for thousands of programmers to share code. Albeit, this says nothing about what dasterdly deeds the Brainiacs are really up to!

Thanks for your help

**Comment by lwm** [comment]
Glad you got it working! You might considering adding something to the FAQ for debugging this kind of error for other stack users.
