### ISSUE TITLE
Figure out why build of stack with cabal keeps timing out on CI

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3458]
In builds like this, https://travis-ci.org/commercialhaskell/stack/jobs/279757391 , the build runs for 6 hours and then times out, on the step of attempting to "cabal install" stack from the generated sdist.

For now, I am just disabling this configuration in travis, but it would be good to have this configuration building reliably in travis.

**Comment by 23Skidoo** [comment]
I saw similar behaviour on the Cabal CI recently, looks like flakiness on the Travis side. Restarting the build fixed it.

**Comment by lwm** [comment]
I wonder is it possible to hack something into `after_failure` to check if some timeout occured, and if so, fire another build and output a message.

**Comment by mgsloan** [comment]
@23Skidoo Interesting!  Yes, it does seem to be a bit non deterministic.

@lwm Perhaps so.  If doing that, we'd definitely want to reduce the timeout.  6hr is already way too long of a delay for CI feedback.

**Comment by mgsloan** [comment]
Argh, a build using stack also timed out similarly - https://travis-ci.org/commercialhaskell/stack/jobs/279845285

**Comment by jgm** [comment]
I've been experiencing timeouts with cabal builds of pandoc recently, too.
e.g. https://travis-ci.org/jgm/pandoc/builds/286869989
It happens even when all the dependencies have been cached, so that only pandoc itself is being built.
I never have problems with cabal + ghc 7.8 or with stack, but only with cabal + other ghc versions.
I'm building with `-O0`.
This didn't used to happen, so it seems something has changed on the travis side.
The other strange thing is that, even though the build times out after 50 minutes or so, travis doesn't record a failure for several hours after that.

**Comment by mgsloan** [comment]
@snoyberg https://github.com/commercialhaskell/stack/pull/3536 added a bunch more travis configurations, in particularly ones that use cabal to do the build.  So now the bug is back where it randomly times out some builds.  https://travis-ci.org/commercialhaskell/stack/jobs/295537272

Should we disable the builds via cabal-install on CI, or dig into what's actually breaking here?

**Comment by snoyberg** [comment]
@mgsloan I don't think that PR is related to Travis configs.

If I was to take a guess as to why Travis fails more often with Cabal than Stack, it's simply that Stack configs are using snapshots which change less over time, and therefore caching works more effectively. Cabal-based builds are subject to changes in the build plan on each subsequent build, making the cache less effective. But that's just a guess.

**Comment by mgsloan** [comment]
@snoyberg Oh huh, I should have looked more carefully.  There was a commit updating travis configs in one of your PRs at some point, right?  Perhaps it was in a different project.

I figured out what was confusing here.  The failure comes from the stable branch, which does not have the change to allow more failures.

**Comment by snoyberg** [comment]
Yes, I updated optparse-simple recently, by copying over the standard configuration file from the Stack docs.

**Comment by snoyberg** [comment]
Closing, since we've moved over from Travis to Azure and are no longer experiencing issues
