### ISSUE TITLE
update README to reflect current usage

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/stack#346]
The README says to run `stack build` in order to create a configuration file and build the project.

However, when I actually try this, it gives me the following error:

```
$ stack build
Unable to find a stack.yaml file in the current directory (/home/illabout/temp/servant-persistent/) or its ancestors
Recommended action: stack init
$
```

It would be nice to update the README to say that you must run `stack init` if a stack.yaml file doesn't exist.

**Comment by cdepillabout** [comment]
It also looks like `stack setup` doesn't get run automatically anymore, so adding a note about that would be nice as well.

Also, as a user, I am interested in where the downloaded `ghc` is installed.  Adding a small note about it would please curious users like myself.

**Comment by snoyberg** [comment]
@cdepillabout Thanks for the catch, can you review the wording?

I'm of two minds about including the installation path information in the README. It's there right now, but it may be better to simply tell users about `stack path` (once it's implemented) as that will give them much more information.

**Comment by cdepillabout** [comment]
@snoyberg The wording looks good!

> it may be better to simply tell users about stack path (once it's implemented) as that will give them much more information.

I think you are right.  Telling the user about `stack path` is probably the best bet.
