### ISSUE TITLE
Stack init fails with compiler resolver (regression)

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3463]
Same repro as https://github.com/commercialhaskell/stack/issues/3453

With stack-1.5.1, it uses the solver.  If on cabal-install-2.0 that bit won't work due to issues parsing the output, but if on earlier cabal, it will.  However, on master, regardless of cabal-install version it will fail with

```
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- junk.cabal

Selected resolver: ghc-8.2.1
Resolver 'ghc-8.2.1' does not have a matching compiler to build some or all of your package(s).
ghc-8.2.1 cannot be used for these packages:
    - junk
base not found
    - junk requires >=4.9 && <5

This may be resolved by:
    - Using '--omit-packages to exclude mismatching package(s).
    - Using '--resolver' to specify a matching snapshot/resolver
```

Marking as P1 since it's best to not regress behavior.  Looked into it a little bit, but don't have the time right now to go in depth.

**Comment by snoyberg** [comment]
Newest master should have resolved this; see #3498.
