### ISSUE TITLE
Stack GHCI shows error while running in windows 7 power shell . 

### ISSUE THREAD

**Issue by AiDinho** [commercialhaskell/stack#3465]
I am a newbie in stack and haskell in general ,If I run stack ghci in powershell I dont see the repl and I see the error 

ghc-pkg.EXE: C:\sr\snapshots\6195b930\pkgdb\package.cache: GHC.PackageDb.readPackageDb: inappropriate type (not a ghc-pkg db file, wrong file magic number)

my stack version is 
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682 ecfd694e x86_64 hpack-0.17.1

os - windows7

**Comment by mgsloan** [comment]
How did you install stack and ghc?  This generally indicates that it is trying to use a package DB intended for a different version of GHC.  This should never happen if you installed ghc via `stack setup`.

One way or another, something is screwed up.  Maybe try deleting your stack root (located at `stack path --stack-root`), and then doing `stack setup` again?  If that doesn't work, please paste the results of `stack path`.

**Comment by creepystranger** [comment]
I installed via the stack set up file for windows and installed ghc via stack setup command . 
I tried several times by unstalling /installing stack but its not working. and it does not work from cmd as well.

**Comment by mgsloan** [comment]
Well, that's a real mystery! Are there perhaps some locale settings (non english language)?  While that *shouldn't* effect this, I wouldn't be surprised if there were bugs lurking there.

**Comment by creepystranger** [comment]
No there isnt any non english language settings in my pc .  I cant make it work even if uninstall /reinstall :( 
is there a way I can cleanly uninstall (deleting files/clearing registry or something like that) .,so that I can use stack /haskell .

**Comment by mgsloan** [comment]
Ah, one thing I forgot is that on windows stack installs ghc to a different dir that's more of a windows convention.  If you delete the directory at `stack path --stack-root` and `stack path --programs` that should be sufficient to start from a clean slate.

This is highly unlikely / a long shot, but it might be worthwhile to delete / uninstall stack, redownload, reinstall.

You may also want to try updating your windows.  I realize that Windows 7 was pretty nice, for being windows..

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and that Windows 7 was end of life on 14 January 2000.
