### ISSUE TITLE
`stack clean --full` may not work properly with docker + nix

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3471]
To fix #2010, "stack clean" was made to no longer run within a docker or nix environment.  This broke cleaning within the nix-shell as described in #3468.   The solution in https://github.com/commercialhaskell/stack/pull/3470 is to not enter docker for `stack clean --full`, but enter into nix.  I don't think this will work properly for docker + nix.

A better solution might be to make `stack clean --full` work within the containers, by not trying to delete the `_home` dir mentioned in #2010

**Comment by snoyberg** [comment]
I've reworked `stack clean` to no longer use an `EnvConfig` at all, which should fully address these concerns. Closing.
