### ISSUE TITLE
stack list-dependencies --license yields Invariant violated error

### ISSUE THREAD

**Issue by pjljvandelaar** [commercialhaskell/stack#3475]
### General summary/comments (optional)
Running `stack list-dependencies --license` in the directory obtained by cloning
https://github.com/TorXakis/TorXakis
yields an invariant violated error.

### Steps to reproduce
1. Clone https://github.com/TorXakis/TorXakis
2. execute the following steps:
```
C:\TorXakis>stack upgrade
Current Stack version: 1.5.1, available download version: 1.5.1
Skipping binary upgrade, you are already running the most recent version

C:\TorXakis>stack list-dependencies --license
Invariant violated: Expected to find wired-in-package integer-gmp in global DB
CallStack (from HasCallStack):
  error, called at src/Stack\Dot.hs:232:22 in stack-1.5.1-6vAgdEAY6cq2iNQCmZsucn
:Stack.Dot
```
### Expected

I expected to see the licenses.

### Actual
I got an error.

### Stack version

```
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e x86_64 hpac
k-0.17.1
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository
* On windows

### possible reason

We don't use integer-gmp due to license issues.

stack.yaml contains
```
resolver: lts-9.1
ghc-variant: integersimple
```

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and because the `master` branch version of Stack no longer supports LTS < 12.0.
