### ISSUE TITLE
Revert/review my patches

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3478]
I inadvertently clicked a button in my editor that committed my changes to the main repo, rather than going via a pull request. Sorry! The two patches are:

* 00bfaf6010748b000304d2e9f74499c822999512
* 2e73aa1b91d53d0ec1ae07edc17566bffecdbf4b

I suggest you remove my permissions to push direct to the repo (they are a holdover from when the project was very young - and I don't seem to have sufficient permissions to remove my own permissions...).

Can you please either review the patches, or revert them, and I'll send them via a PR. Given my git knowledge, trying to fix it myself seems dangerous.

**Comment by ndmitchell** [comment]
If trying to review, the ticket they relate to is #3362, which is itself reverting a change made as part of https://github.com/commercialhaskell/stack/commit/d0ab69c266c99611cc3c4dbfe24e95bb15956977#diff-890614cc04afa326f5d48aac897e4aa8. The change to remove `--hoogle` was not called out in the documentation, and my best guess is it was an inadvertent change.

**Comment by ndmitchell** [comment]
You might also wish to consider turning on branch protections, to stop anyone merging to master: https://help.github.com/articles/configuring-protected-branches/

**Comment by mgsloan** [comment]
This change seems fine to me, but I haven't dug into the haddock / hoogle side of the code much.  Pinging @borsboom @Fuuzetsu .  I think it makes sense to go back to default generation of hoogle.

**Comment by Fuuzetsu** [comment]
Changes seem ok.
