### ISSUE TITLE
`stack link` for specifying local installations of packages

### ISSUE THREAD

**Issue by spinda** [commercialhaskell/stack#348]
Say I have two packages in different repositories, package foo and package bar, where bar depends on foo. I might have a `stack.yaml` in bar that looks like this:

```yaml
resolver: nightly-2015-06-17
packages:
- .
- location:
    git: git@github.com:spinda/foo
    commit: master
```

If I make a change to foo and want to test it with bar, I wouldn't want to have to push foo to the remote repository before running `stack build` in bar. And that `stack build` command, from my testing, wouldn't reuse the previously-built version of foo in the other directory: it would pull a new copy of foo and compile it in bar's `.stack-work`.

Essentially, there's no way to tell stack that I personally have a locally-installed version of foo which I'd like my clone of bar to use. I could change `stack.yaml` in bar to point to the local path, but not everyone who clones bar will have their workspace set up the same way as me. I'd like to be able to configure this in a way that stays local to my clone and doesn't enter the revision history.

Perhaps there could be something like `stack link foo ../foo` to locally override the configuration for foo in bar with a manually-specified path. This could be persisted somewhere in `.stack-work`, where it would exist safely away from the tracked source files.

**Comment by snoyberg** [comment]
I can think of two ways to achieve this with the current stack functionality (both pretty similar ideas). Create the modified stack.yaml you'd like to use, and then either:

* Save it in the same directory with a different name, and set the `STACK_YAML` environment variable to point at it
* Save it in a different directory and name it `stack.yaml`, and run your `stack` commands from in there

I think the former is a bit easier. I'm not a fan of having some invisible modifications lurking inside `.stack-work` that may trip you up later.

Can you give this a shot and let me know if it works for your use case?

**Comment by mboes** [comment]
As an example, the Cloud Haskell project is currently experimenting with the following solution to the same problem:

* each package is a submodule of the top-level repository.
* `stack.yaml` includes each package directory (i.e. each submodule) as a local package in the `packages` field.
* Tools like e.g. Travis automatically checkout out the submodules too so nothing special needs to be done.
* You can push very easily from any submodule back to the upstream repo.
* You can use `git submodule update --remote` at any time to update the refs in the top-level repo if you want to pull in new changes from upstream and then `git commit && git push` to publish the changes to those refs.
* You therefore still get the same level of control on package versions and the same level of reproducibility as listing explicit commit hashes in `stack.yaml`.

It works quite well, so I'm not sure a `stack link` command is ultimately needed.

**Comment by spinda** [comment]
@snoyberg The first solution works okay, with the caveat of having to specify `STACK_YAML` with each execution of `stack` (or `export`ing it every time I enter the project/terminal session). What about having stack look for a `stack.local.yaml` file that overrides `stack.yaml` if present?

@mboes "foo" and "bar" in my example are really [liquid-fixpoint](https://github.com/ucsd-progsys/liquid-fixpoint) and [liquidhaskell](https://github.com/ucsd-progsys/liquidhaskell), respectively. I tried out the submodule approach in [this repository](https://github.com/spinda/liquid). Having everything in one workspace seems attractive, but I'm not sure how well managing divergent lines of development would work under this model. For example, it took some effort to get a `gsoc2015` branch set up, which adds a submodule and pulls from a different remote and branch for liquidhaskell. Switching to this branch requires `git checkout gsoc2015 && git submodule sync && git submodule update --init && stack build`. This seems like it would come as unwelcome hassle for others working on the project. But maybe I'm going about this the wrong way&mdash;advice would be appreciated here.

**Comment by snoyberg** [comment]
I'm not sold on the idea of having a `stack.local.yaml`. While code wise it's simple to implement, it carries the cost of (1) potential confusion to users, needing to remember that there's another file, on top of the stack.yaml file and STACK_YAML environment variable, and (2) people planning on writing add-on tools but not reusing the stack library would have something else they'd have to take into account to stay compatible.

**Comment by chrisdone** [comment]
The precedent for a `.stack-work/` config wouuld be in Git, i.e. `.gitignore` vs `.git/info/exclude`, the former is included in source control, the latter isn't.

I'm not sure what solution would be best.

**Comment by mboes** [comment]
@spinda 
> Switching to this branch requires git checkout gsoc2015 && git submodule sync && git submodule update --init && stack build. This seems like it would come as unwelcome hassle for others working on the project.

That's true (though `git checkout gsoc2015 && git submodule update && stack build` should be sufficient for the common case when the submodule set doesn't change). But hold on - isn't that still better that what people would have to do manually without submodules? If I have both `liquid-fixpoint` and `liquidhaskell` checked out (not as submodules), how do I switch branches in both repos simultaneously? Using submodules here gives you a way to coordinate checking out a branch between multiple repos. Though there are other mechanisms to do that too (`gclient`, `repo`, etc). Do you already have scripts to do so?

Either way, would you agree that the mechanism for switching branches is orthogonal to whether `stack` ought to have a `link` command? Whether you use submodules or not, in principle you no longer need `stack link` if all repos are somehow checked out locally, i.e. in subdirs of the repo that contains the `stack.yaml` file.

**Comment by spinda** [comment]
@mboes 

> But hold on - isn't that still better that what people would have to do manually without submodules? If I have both `liquid-fixpoint` and `liquidhaskell` checked out (not as submodules), how do I switch branches in both repos simultaneously? Using submodules here gives you a way to coordinate checking out a branch between multiple repos. Though there are other mechanisms to do that too (gclient, repo, etc). Do you already have scripts to do so?

That's a good point. Previously I would switch branches, do clones, etc. manually.

After trying this submodule setup for a while, it's actually working pretty smoothly. I worried that the added `submodule` commands might be too much overhead, but they really don't get in the way all that much in practice.

> Either way, would you agree that the mechanism for switching branches is orthogonal to whether stack ought to have a link command? Whether you use submodules or not, in principle you no longer need stack link if all repos are somehow checked out locally, i.e. in subdirs of the repo that contains the stack.yaml file.

Yes, I agree there.

**Comment by snoyberg** [comment]
From the last comment it sounds like we're in agreement that the current functionality of stack is acceptable, so closing. Please ping if I've misread that.
