### ISSUE TITLE
Prevent --file-watch from watching test suites

### ISSUE THREAD

**Issue by JoeMShanahan** [commercialhaskell/stack#3483]
How appropriate would it be to allow a new argument which prevents `stack` from triggering a rebuild when a test suite changes?

During development of a web app using `yesod`, we're in the situation where I'm running the server with `yesod devel` (which uses `stack ... --file-watch` underneath).

Our selenium test suite is attached to the server `devel` is running. I'm altering some selenium tests which I have loaded with GHCi. When I change the selenium tests, `stack` notices, which signals to `devel` that a rebuild is required even though it's not! This really just slows down development.

I propose something like `stack build --file-watch --no-watch-tests` . What do you think?

**Comment by snoyberg** [comment]
It may even be reasonable to have that behavior automatically implied based on which components are being built. I don't see a downside to such a change.

**Comment by JonnyRa** [comment]
I was about to log an issue for this but looking at the linked issue it seems to be fixed in 1.6.

I've updated and just tested on my setup and I'm not seeing changes to the tests retriggering builds when they shouldn't now.  Woohoo!

Can probably be closed as fixed now?

Nice one!

Cheers

Jonny

**Comment by lwm** [comment]
Thanks @JonnyRa, will close this off!
