### ISSUE TITLE
Handle change tracking for pre-processor files / don't warn about them

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3491]
In https://github.com/commercialhaskell/stack/issues/479#issuecomment-322025290 , warnings are emitted for modules that are defined via preprocessor.  Since module name -> file path resolution is used for knowing when to rebuild, I think there is likely a rebuild issue here.

Not sure how to unambiguously resolve module names to files that do not have .hs or .lhs extensions, though.  A hack could be to assume that it is the correct file if the name matches, ignoring the extension, and if it's listed in extra-source-files as suggested by the warning text.  Currently it seems like extra-source-files is not taken into account here.  So, either the warning text should be fixed or the behavior should make it so that its suggestion works.

Repro is at https://github.com/adituv/protobuf/tree/testpreprocess

**Comment by adituv** [comment]
Perhaps there could be a stack.yaml field to list extensions there are custom preprocessors for?

**Comment by mgsloan** [comment]
Not a bad idea!
