### ISSUE TITLE
Report progress on STDOUT/STDERR during compilation of individual modules

### ISSUE THREAD

**Issue by saurabhnanda** [commercialhaskell/stack#3508]
Following-up from https://github.com/commercialhaskell/stack/issues/426#issuecomment-338386315

Would it be possible to output a `.` for every compiled module. Use-cases:

* Avoid hitting timeouts [1] on some CI environments.
* Reporting progress is important for impatient devs :)

[1] https://discuss.circleci.com/t/too-long-with-no-output-while-building-docker-image/12275

**Comment by snoyberg** [comment]
I'm about to take a stab at #3225, which will address this desire as well.

**Comment by snoyberg** [comment]
Relevant PR: https://github.com/commercialhaskell/stack/pull/4097
