### ISSUE TITLE
Missing package in indices (1.6.0)

### ISSUE THREAD

**Issue by JoeMShanahan** [commercialhaskell/stack#3514]
Following on from @snoyberg's [call to action](https://groups.google.com/forum/#!msg/haskell-stack/SEvMu1yymWk/phVkkc9VBwAJ).

With the up to date release of Stack, our project builds correctly.

With `stack upgrade --git`, I run in to the following:

    joeshanahan@js-ubuntu:~/project$ stack --version
    Version 1.6.0, Git revision 0e756d486a5a4d6fe03e0d448bb8e706c5834ca1 x86_64 hpack-0.18.1

    joeshanahan@js-ubuntu:~/project$ stack build
    Downloaded lts-8.24 build plan.
    Didn't see Agda-2.5.2@sha256:4db0b12bc07e72fe1b180acad2a0d59ac11d9a1d45698b46cede7b634fb6bfff,27524 in your package indices.
    Updating and trying again.
    Downloading package index from https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz
    No updates to your package index were found
    Update complete
    Unable to load cabal files for snapshot
    
    ----
    Deleting cached snapshot file: /home/joeshanahan/.stack/build-plan/lts-8.24.yaml
    Recommendation: try running again. If this fails again, open an upstream issue at:
    https://github.com/fpco/lts-haskell/issues/new
    ----
    
    The following package identifiers were not found in your indices: Agda-2.5.2@sha256:4db0b12bc07e72fe1b180acad2a0d59ac11d9a1d45698b46cede7b634fb6bfff,27524
    The specified revision was not found.
    Possible candidates: Agda-2.5.2@sha256:28af7449a60bce1d020020524e72779415d04dd2a83dee57ec62eff484834282, Agda-2.5.2@sha256:16152f1ea7f461dfc48aee61a75a7f1018832e9bcbcae45eba3a7d08ff1f28c9.

With `--resolver lts-9.1` the error is slightly different:

    Didn't see avers-0.0.17.1@sha256:dae0e728b26b259e31a731fcb73a9b724c58c81a8f09e795c1918a1388ee701b,3710 in your package indices.

I'm reluctant to provide our project yaml / cabals as they're quite large and I'd need to anonymise them somewhat. I can work on getting a minimal project together than reproduces the problem if the above is not enough to go on.

**Comment by JoeMShanahan** [comment]
On nightly:

```
$ stack build --resolver nightly
Selected resolver: nightly-2017-10-25
Downloaded nightly-2017-10-25 build plan.
Didn't see hjsonpointer-1.3.0@sha256:f0313aea24be91eb183e8417988987e3e467419ed61a745152cce4c27149cb34,1433 in your package indices.
Updating and trying again.
Downloading package index from https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz
No updates to your package index were found
Update complete
Unable to load cabal files for snapshot

----
Deleting cached snapshot file: /home/joeshanahan/.stack/build-plan/nightly-2017-10-25.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/stackage-nightly/issues/new
----

The following package identifiers were not found in your indices: hjsonpointer-1.3.0@sha256:f0313aea24be91eb183e8417988987e3e467419ed61a745152cce4c27149cb34,1433
The specified revision was not found.
Possible candidates: hjsonpointer-1.3.0@sha256:4dbe3247d398311ff7de9484fa45cda295b4afa224655cd342aefe797c047d14, hjsonpointer-1.3.0@sha256:b1cce4fd4f6273bc3998bdb6057baead577751d71fb0695c29fd81f0c2d5029d.
```

**Comment by snoyberg** [comment]
It looks like you're overriding the package index section to use the
00-index files, which do not provide the Hackage cabal file revisions,
which is where the error message is coming from. Is there a reason for this
change in settings?

**Comment by JoeMShanahan** [comment]
Looking through our commit history it appears we've been using the following for the entire usage of `stack` (since 2015-09-01). 

```package-indices:
- name: trackage
  download-prefix: http://trac-leeds-21/trackage/package/
  http: http://trac-leeds-21/trackage/00-index.tar.gz```

Should this _not_ be here? I'm aware that `stack init` now certainly doesn't use this. The person that added this code has since left the company so I'm scratched my head as to why this is here. I wasn't working here myself at that time!

After removing a now-unused extra-dep from a forked package, the building completes. The above snippet is still present.

Apologies for the extremely vague report - thanks for pointing me in the right direction!
