### ISSUE TITLE
How do you specify use of the ghc library for a non-released compiler?

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#352]
This is quite likely impossible at the moment, but I am trying to set up stack for https://github.com/alanz/ghc-exactprint/tree/wip, which has to build with the current ghc-7.10 branch of GHC.

The stack.yaml is

```yaml
flags: {}
packages:
- '.'
extra-deps:
  - ghc-7.10.1.20150612
  - ghc-syb-utils-0.2.3
resolver: nightly-2015-06-16
```

If I do `ghc-pkg list` I get

```
/opt/ghc/7.10.1.20150617/lib/ghc-7.10.1.20150617/package.conf.d:
    Cabal-1.22.4.0
    array-0.5.1.0
    base-4.8.1.0
    bin-package-db-0.0.0.0
    binary-0.7.5.0
    rts-1.0
    bytestring-0.10.6.0
    containers-0.5.6.2
    deepseq-1.4.1.1
    directory-1.2.2.0
    filepath-1.4.0.0
    ghc-7.10.1.20150617
    ghc-prim-0.4.0.0
    haskeline-0.7.2.1
```

where ghc the library is listed, no parentheses after `ghc-pkg expose ghc-7.10.1.20150612`

Running

    stack build

Results in

```
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package ghc in known packages

--  Failure when adding dependencies:    
      ghc: needed (-any && -any), but not present in build plan
      ghc-syb-utils: needed (-any), but couldn't resolve its dependencies
    needed for package: ghc-exactprint-0.3

--  Failure when adding dependencies:    
      ghc: needed (-any), but not present in build plan
    needed for package: ghc-syb-utils-0.2.3
```

Is there a way to specify the ghc library?

```
stack --version
Version 0.0.3.1, Git revision 282034ab1ca059598a5fcfff0f5d13358dbb0ab4
```

**Comment by snoyberg** [comment]
It should work if you just remove the `ghc` entry in extra-deps entirely. @mgsloan was working on something similar, and added some logic to handle wired-in packages specially. What happens if you remove that line?

**Comment by alanz** [comment]
Exactly the same

**Comment by snoyberg** [comment]
@alanz OK, I reproduced this with GHC 7.10.2 and pushed a fix. Can you try out master?

Pinging @mgsloan as well. What I did here was ensure that all wired-in installed packages are treated as having all their dependencies met, even if the snapshot chooses a different version for a dependency.

**Comment by alanz** [comment]
Yes, it does resolve it. Thanks for being so responsive, this looks like a great tool.

    stack --version
    Version 0.0.3.1, Git revision ee3c11f8eb36cd15fc79ac829be9b1c9af8dd921

**Comment by snoyberg** [comment]
Cool, thanks for the testing!
