### ISSUE TITLE
Relax strict Hackage revision matching?

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#3520]
I've seen a few different people report the same "not actually a bug" in the Stack prerelease (or from Arch users using a master-based build). The case is:

* They've got a custom package-index set up
* That package index is pointing at a 00-index.tar.gz file (which doesn't keep all revisions) instead of 01-index.tar.gz
* The new Stack release is stricter about matching revisions listed in a snapshot, erroring out
* As a result, `stack build` et al suddenly stop working with the new Stack release

There's a strong argument in favor of keeping this behavior: it provides for proper reproducibility, and usage of 00-index.tar.gz should basically be considered unsupported. On the other hand, revisions are unlikely to break snapshots (though it happens), and therefore we may be able to get away with sweeping this under the rug.

I see a few different options for this next release:

* Keep the behavior as-is, and tell users that they have a bug
* Change the behavior back to just warning on a revision mismatch
* Make a new option to change the behavior on revision mismatch
* Possibly unrelated: give a warning (that can be silenced via config) when you point at a package index named `00-index.tar.gz`

I'm mostly leaning towards no changes, but wanted to open the discussion.

**Comment by mgsloan** [comment]
> Possibly unrelated: give a warning (that can be silenced via config) when you point at a package index named 00-index.tar.gz

I like this option + keeping current behavior.

**Comment by NorfairKing** [comment]
I prefer the `Make a new option to change the behavior on revision mismatch` option. Compromising reproducability for everyone by default does not sound like a good idea.

**Comment by snoyberg** [comment]
@ruuda I've pushed a commit with a clarification about the two files here:

cbf79864

If you have ideas for improvements there, please send a PR to update the text.

**Comment by snoyberg** [comment]
Alrighty, PR created for the rest of this:

https://github.com/commercialhaskell/stack/pull/3541

I've both added a new flag `ignore-revision-mismatch`, and a simple heuristic to give a nice error message if you're using a `00-index.tar.gz` tarball. Hopefully should address all common cases.

**Comment by ruuda** [comment]
Looks good to me, thanks for the clarification!

**Comment by snoyberg** [comment]
Fixed by PR #3541 and cbf7986, closing.
