### ISSUE TITLE
Offer Stack on Stackage?

### ISSUE THREAD

**Issue by habemus-papadum** [commercialhaskell/stack#3522]
It seems that the last LTS to offer stack was [LTS 7.24 w/ stack v1.1.2](https://www.stackage.org/package/stack).  Is there a reason that this was discontinued, and are there plans to reintroduce this in the future?  

In my case, this question arose when I was considering rewriting my [`stack notebook`](https://github.com/habemus-papadum/stack-notebook) script  as a [stack script](https://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter).  My script is currently written in Bash, and shells out to `stack path` etc to do its work. 

While a `stack script` version could of course do the same thing, this feels very inelegant -- might as well stay with bash...  Instead, it would be nice if the script could simply use the `stack` modules directly with e.g. `package: stack`.   And in general this seems like the sort of use case that would be applicable to many `stack script`'s.    

I would guess that even full fledged stack projects would enjoy having "lts pure" (i.e. not use `extra-deps`) access to the stack api (intero, IHaskell, etc) -- I understand in this case that relying on `extra-deps` and pulling `stack` from Hackage is a viable option, but I think it is a testament to the tyrrany of success of `stack` that I think long and hard before going down the `extra-deps` route.  

Perhaps you might consider this if nothing else as a matter of personal pride... that `stack` should be on Stackage...  maybe a baby step would be to have it on `nightly`?

Thanks for your consideration!  cheers, nehal

**Comment by borsboom** [comment]
There's a maintenance burden to keeping it "stackage pure", even if it would be nice.  Stack releases are infrequent enough that updating it when it becomes incompatible isn't always possible within the short timeframe that Stackage curators prefer.   Stack isn't really intended to be used as a library, and we make no effort whatsoever to give it a stable API, so we eventually let it drop out of Stackage.

All that being said, if having Stack part of Stackage snapshots would make things significantly better for a lot of people, we're not against it -- it's just that the benefits need to be clear since there is a cost to it.

**Comment by habemus-papadum** [comment]
Thanks, I understand better.  While I don't know enough of `stack` internals to propose a complete plan of action, I guess I would propose the following high level objectives:

* Using `stack script` to cleanly script `stack` seems like a useful thing to enable.  (`stack script`'s should, in general, remain relocatable (they should not need their own .stack-work, they should be "stackage pure", they should not support extra-deps, flags, etc)).     

* Probably the most useful part of the `stack` api to make available on Stackage would be project introspection e.g. list targets, paths, location of build artefacts, environment variables that should be set, etc.   Being able to deeply query into the underlying cabal files would really be nice.  A script I would like to write is `stack bindoctor` which would tell me what native libraries are required by my project's dependency tree.   Introspection should be possible for both `stack.yaml` as well as from `stack script` header comments  (so intero, etc, could provide proper ide support for `stack script`)

* Initially, solving for a build plan, downloading from stackage, grabbing the compiler, creating projects from templates, init from cabal files, or anything else involving hard disk mutation, should be left out of the api living on Stackage.

Perhaps something along these lines would attractive to enough people to make it worthwhile?

**Comment by mgsloan** [comment]
I think it makes sense to get it back in stackage.  I'd be surprised if there are any tricky blockers for that right now.

**Comment by borsboom** [comment]
Yes, should be easy right now -- there's only one needed extra-dep for nightly and that's just because the package isn't on stackage at all (so if we add stack it'll be pulled in automatically).  It tends to be more of a burden between stack release when there's a new package in nightly that breaks Stack, and then we have to do a point release just to make things compatible with nightly again (and sometimes have to do CPP to keep it compatible with both the old version and the new version).

**Comment by mgsloan** [comment]
I see!  Yeah, there are actually good reasons to leave it out of stackage too.  People might expect `stack install stack` to upgrade their stack version, when they should really use `stack upgrade`.

Perhaps it makes sense to wait until someone actually wants to use stack as a library, and that thing gets added to stackage.

**Comment by borsboom** [comment]
The OP wants to use Stack as a library from `stack script`, so for them it would be helpful.

**Comment by habemus-papadum** [comment]
It seems possible that "Stack from `stack script`" might be useful internally -- the wildly useful `stack dot` might be maintained as a script; currently `stack solve` prompts the user to `stack install cabal-install` -> perhaps it should just be a script?  In general, it could lower the bar for contributions from the community.    

Concerns about adding to the maintenance burden is something I respect as a legitimate concern, not just the Stackage maintenance requirements but as well has the fact that the move at the very least starts making stability promises w/ regard to the api.   It seems like not rushing into this but also keeping it in mind for something in the future be best for now?

**Comment by mgsloan** [comment]
Hmm, that seems reasonable!  I'm in favor of it, but lets have a policy that every module is considered "internal" and therefore doesn't follow the PVP ;)

**Comment by juhp** [comment]
I added stack-1.5.1 to Stackage LTS 9.11

https://www.stackage.org/lts-9.11/package/stack-1.5.1

**Comment by mgsloan** [comment]
Great!  And indeed it is already the policy that minor versions can break apis:

```
description:         Please see the README.md for usage information, and
                     the wiki on Github for more details.  Also, note that
                     the API for the library is not currently stable, and may
                     change significantly, even between minor releases. It is
                     currently only intended for use by the executable.
```

**Comment by habemus-papadum** [comment]
Whoa -- awesome!  Thanks for this.  nehal

**Comment by borsboom** [comment]
Well, I guess I'll _have_ to make sure stack-1.6 goes in nightly then.  I reserve the right to pull it if it turns out to be too annoying though. :)
