### ISSUE TITLE
Stack upgrade --git keeps failing

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3524]
On Windows 64bit, using stack 1.5.1, I do `stack upgrade --git` and it gets through a few packages before failing with:

```
C:\Users\ndmit_000\AppData\Roaming\stack\precompiled\x86_64-windows\ghc-8.0.2\1.24.2.0\ZmlsZS1lbWJlZC0wLjAuMTBAc2hhMjU2OjlhZDY2YThhNWIyYzRkN2IwMjU5Mjk3NTMzMjUwMWUxZTRmYTcxMDBlYTQyNjhmM2MwYmU0MzdlN2M1MmYwOTgsMTMyNQ==\dHVrITXhQmaAZb_tzwqsXe00QecTnKuJiXMJZfge7ek=: openBinaryFile: does not exist (No such file or directory)
```

Retrying gets through a handful more packages before I encounter the error once more. I've currently experienced the failure about 7 times, with each retry getting a bit further.

**Comment by ndmitchell** [comment]
Rerunning with `-j1` it's been impossible to upgrade, I always start from `Cabal` and get traces such as:

```
Cloning stack
Cloning into 'stack'...
remote: Counting objects: 639, done.
remote: Compressing objects: 100% (481/481), done.
remote: Total 639 (delta 58), reused 376 (delta 26), pack-reused 0
Receiving objects: 100% (639/639), 688.88 KiB | 924.00 KiB/s, done.
Resolving deltas: 100% (58/58), done.
[0mCabal-2.0.0.2: configure[0m
[0mCabal-2.0.0.2: build[0m
[0mCabal-2.0.0.2: copy/register[0m
[0mcabal-doctest-1.0.2: configure[0m
[0mcabal-doctest-1.0.2: build[0m
[0mcabal-doctest-1.0.2: copy/register[0m
[0mextra-1.6: configure[0m
[0mextra-1.6: build[0m
[0mextra-1.6: copy/register[0m
[0mhsc2hs-0.68.2: configure[0m
[0mhsc2hs-0.68.2: build[0m
[0mhsc2hs-0.68.2: copy/register[0m
[0mmintty-0.1.1: configure[0m
[0mmintty-0.1.1: build[0m
[0mmintty-0.1.1: copy/register[0m
[0mecho-0.1.3: configure[0m
[0mecho-0.1.3: build[0m
[0mecho-0.1.3: copy/register[0m
[0mrandom-1.1: configure[0m
[0mrandom-1.1: build[0m
[0mrandom-1.1: copy/register[0m
[0mregex-applicative-0.3.3: configure[0m
[0mregex-applicative-0.3.3: build[0m
[0mregex-applicative-0.3.3: copy/register[0m
Progress: 8/121C:\Users\ndmit_000\AppData\Roaming\stack\precompiled\x86_64-windows\ghc-8.0.2\1.24.2.0\cmVnZXgtYXBwbGljYXRpdmUtMC4zLjNAc2hhMjU2OjMyMTI5YjRmMGIyYTNkMzcwZmIxODJkZWE0YTJlZTEzYWExMjcyODVmMzU4ZjJmMjIyNGZmZTk4MjU4MWRmODIsMjAwMQ==\gVhwp4iMBZcXv_F6KDACbOFsiSlG02GFS-LftJZQjKE=: openBinaryFile: does not exist (No such file or directory)
```

I'm making no progress.

**Comment by mgsloan** [comment]
Hmm, are you sure that's stack 1.5.1?  The hashes in that path seem huge.  Unless it's a cabal thing, pretty sure all our hashes used on windows are restricted to be much shorter.

You are probably running into MAX_PATH.  God I hate windows.  Anyway, you can hopefully make progress by setting STACK_ROOT to "C:\sr" or something similarly short.

**Comment by ndmitchell** [comment]
I confirm this is definitely stack 1.5.1.

```
C:\Neil>stack --version
Version 1.5.1, Git revision 2e73aa1b91d53d0ec1ae07edc17566bffecdbf4b (5245 commits) x86_64 hpack-0.18.1
```

Changing the STACK_ROOT fixes it. Any chance of reporting this upstream and getting it fixed? It provides a terrible user experience...

Alternatively, someone could fix the Haskell API's so use `\\?\` paths as per https://msdn.microsoft.com/en-us/library/aa365247.aspx (although that's probably a rabit hole that people will have to keep running down for a while).

**Comment by mgsloan** [comment]
> Changing the STACK_ROOT fixes it. Any chance of reporting this upstream and getting it fixed?

Feel free to contact Microsoft.  Hah, I kid, I kid.

This may have already been fixed in Cabal 2.0 .  Haven't checked if this PR was included in 1.24.2.0 https://github.com/haskell/cabal/pull/3431

> Alternatively, someone could fix the Haskell API's so use \\?\ paths as per https://msdn.microsoft.com/en-us/library/aa365247.aspx (although that's probably a rabit hole that people will have to keep running down for a while).

Could be good to do that.  I hadn't heard about that before.

**Comment by borsboom** [comment]
There's already a GHC issue for using windows long paths in the base libraries: https://ghc.haskell.org/trac/ghc/ticket/13373

**Comment by ndmitchell** [comment]
It looks like the Cabal thing mostly fixes it, and the GHC long-paths stuff will take out the rest. Closing.
