### ISSUE TITLE
1.6 prerelease doesn't work with offline-stack

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3527]
I changed the scripts at https://github.com/ndmitchell/offline-stack to work with a 1.6 prerelease. It fails. Specifically, I get the errors:

```
The following package identifiers were not found in your indices: blank-canvas-0.6.1@sha256:7ed3baf69e4aa56a4ec63545e6fbf827b0686fbb2b6f8e489a6e894b10c83631,7201
The specified revision was not found.
Possible candidates: blank-canvas-0.6.1@sha256:1ecfe227ead93e8e4c92748a5c3751f4b3cefeb14cc37f3b514da4321b84219b, blank-canvas-0.6.1@sha256:bd2953cc6e004f7aa7699f1ae15a43110ee967e35faed02a7b43b8fa4aa97fc4.
```

Quite a few commercial companies run Stack offline, using scripts based around the example script in offline-stack, so this change would be very problematic.

**Comment by ndmitchell** [comment]
Failure with:

```
Version 1.6.0, Git revision 1a9d326230139b0437cf1c35192cfd5488e86062 x86_64 hpack-0.18.1
```

Worked with 1.5.1.

**Comment by mgsloan** [comment]
Hmm, can you please update the project's README with a clear way to try this thing out?  I'm not really sure how to use this together with the mirror script, I don't feel like trying to cobble together scripts at the moment.

**Comment by ndmitchell** [comment]
The whole point about this project is that it isn't trivial to run Stack offline, so it gives scripts that are a known good state, then you spend a week or so smashing that into your environment (the entire process is long and painful - this script just gives you the confidence that when you arrive you have something that works).

I can try and produce Windows reproduction instructions if that's of use - or are you Linux only?

**Comment by borsboom** [comment]
This might be related to https://github.com/commercialhaskell/stack/issues/3514

**Comment by mgsloan** [comment]
@ndmitchell I'm on linux only.  Oh yeah I totally agree that stack should support offline use better, I'm in favor of merging PRs that make this possible in a more native way.

My current workflow when I know I'm going to be offline is to ensure I've pulled everything I need.  I can certainly understand that it's annoying when working offline and you realize you need a new dep.

**Comment by ndmitchell** [comment]
Note that offline above is offline in the sense your computer is never connected to the internet, but sits behind a corporate firewall.

**Comment by ndmitchell** [comment]
So the fundamental issue is that if you use the 00- index file, Stack raises an error. I've raised #3529 to update the docs, and changing it with offline-stack fixes the issues.

**Comment by ndmitchell** [comment]
Closed, since it now does work offline.
