### ISSUE TITLE
1.6 prerelease failed to install HsColour

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3528]
On Windows, using `Version 1.6.0, Git revision 1a9d326230139b0437cf1c35192cfd5488e86062 x86_64 hpack-0.18.1`, I typed `stack install hlint` and got:

```
mmWhpHwQRVjkjSBA
    Installing executable(s) in C:\sr\snapshots\3c4ad812\bin
    C:\Users\ndmit_000\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\mingw\bin\strip.exe: unable to rename 'C:\sr\snapshots\3c4ad812\bin\HsColour.exe'; reason: File exists

Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
* A cabal file that refers to nonexistent other files (e.g. a license-file that doesn't exist). Running 'cabal check' may point out these issues.
```

I tried it a second time and it worked. Perhaps an aborted compile had produced HsColour.exe but not registered it?

**Comment by mgsloan** [comment]
Hard to say, it works for me.

**Comment by ndmitchell** [comment]
It works for me the second time, and then I deleted my STACK_ROOT and that worked too. Perhaps the thing invoking `strip` should check the output file has been deleted first?

**Comment by mgsloan** [comment]
@ndmitchell Interesting!  Can you please submit an upstream issue about it to cabal?  Here's where strip gets invoked:  https://github.com/haskell/cabal/blob/49f2eac1ae8e0b005fd17fd327900d932bb5933b/Cabal/Distribution/Simple/Program/Strip.hs
