### ISSUE TITLE
Could you fellows upload stack to the normal AUR until AUR 4 becomes standard?

### ISSUE THREAD

**Issue by pharpend** [commercialhaskell/stack#353]
For the uninitiated: Arch Linux has a repository of user-uploaded packages. Previously, this was managed somewhat like Hackage (i.e. poorly or not at all). AUR 4 is managed like Stackage, where there's a git repository, and people send merge requests to the git repository.

At the moment, there's only a Stack package in AUR 4. AUR 4 will become standard in August. However, at the moment, AUR package managers all use the normal AUR. With that in mind, could you upload Stack to the normal AUR?

**Comment by drwebb** [comment]
Right, I'm just about to put the binary versions in the normal AUR. There has been a cabal hell situation in the haskell-stack-git PKGBUILD, so I'm holding off pushing that PKGBUILD to the normal AUR. I intend to switch the haskell-stack-git PKGBUILD to use the stack binary to build itself, which should prevent future breakages.

**Comment by drwebb** [comment]
Leaving this issue open to track fixing the haskell-stack-git PKGBUILD to use stack.

**Comment by snoyberg** [comment]
Can this issue be closed now?

**Comment by vyp** [comment]
Correct me if I'm wrong but the old AUR becomes obsolete in a few days right?

**Comment by drwebb** [comment]
Yeah let's close it. The issue has been resolved for a while now.

@vyp The official switch will be August 8th. After July 8th any package not on AUR4 is up for grabs, as in you can take it over. Might be a good time to take over some Haskell binaries and switch them to building with stack, if you are so inclined. :)

**Comment by pharpend** [comment]
On Thu, Jul 02, 2015 at 02:44:59PM -0700, RWS wrote:
> Correct me if I'm wrong but the old AUR becomes obsolete in a few days right?

[August 8, 2015](https://wiki.archlinux.org/index.php/AUR#AUR_4)

Peter Harpending
