### ISSUE TITLE
Please provide a method for building stack that does not rely on having stack installed.

### ISSUE THREAD

**Issue by R030t1** [commercialhaskell/stack#3532]
### General summary/comments (optional)

Please provide a method for building stack that does not rely on already having stack installed. I have seen this pattern with many Haskell projects, and it makes them hard to integrate with distributions like Gentoo. It makes reproducible builds hard or impossible.

### Steps to reproduce

N/A?

### Expected

N/A?

### Actual

N/A?

### Stack version

Not installed.

### Method of installation

Not installed.

**Comment by mgsloan** [comment]
There is a method of building stack that does not require stack, you can generate the cabal file via [hpack](https://github.com/sol/hpack) and then use whatever approach you like.

**Comment by borsboom** [comment]
The sdists on Hackage will also include a `stack.cabal` file.  To ensure that your version of Stack behaves the same way as the official releases, we recommend that after you build a bootstrap `stack` with cabal-install, you then re-build Stack with `stack` which will ensure the dependency versions are exactly what we tested with.
