### ISSUE TITLE
Automatically run autoreconf in git repos?  Alternatively, add configure script to upstream packages

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3534]
It looks like some fairly core packages like `process` and `time` do not include the `configure` script, instead requiring the user to run `autoreconf -i`.  The source dist, on the other hand, includes the configure script.  This causes issues when those packages are referenced by git repo - see [this](https://github.com/commercialhaskell/stack/issues/1543) and [this](https://stackoverflow.com/questions/47012909/building-the-latest-version-of-process-as-a-dependency).

Two options here:

1. Run `autoreconf -i` automatically?  Seems ok.  Does cabal-install do this?  Do we care what it does?  Perhaps we should just detect the absence of a configure script, and try this incase it works.

2. Fix the packages to include the configure script.

Thoughts?

For those who are visiting this issue, the workaround is straightforward.  Just check out the dependency as a git repo, add it to your `packages` list, and run `autoreconf -i`

**Comment by snoyberg** [comment]
See #3598
