### ISSUE TITLE
stack build silently removes build-depends

### ISSUE THREAD

**Issue by MarcelineVQ** [commercialhaskell/stack#3539]
While running commit cfdde45bd4af32a7304d5eb24f7d98ee19041d07 of stack, adding a build dependency to the library section and then building will silently eat the dependency.
Steps to reproduce:

`stack new test`
`cd test`

change test.cabal:
```
  build-depends:
      base >= 4.7 && < 5
```
to
```
  build-depends:
      base >= 4.7 && < 5, ncurses
```
`stack build`
recheck test.cabal file which will look like
```
  build-depends:
      base >= 4.7 && < 5
```

Apologize if this is fixed already, I'm unable to build a newer git version to see due to arch linux shenanigans.

**Comment by MarcelineVQ** [comment]
addendum, test.cabal file includes this at the top:
```
-- This file has been generated from package.yaml by hpack version 0.18.1.
--
-- see: https://github.com/sol/hpack
```
I don't believe it used to say this on `stack new` projects.

**Comment by borsboom** [comment]
This looks related to https://github.com/commercialhaskell/stack-templates/pull/112, where the `stack new` template was updated to use an [hpack package.yaml](https://github.com/sol/hpack#readme) instead of a .cabal file.  Each time Stack builds, it replaces the .cabal file with one generated from the `package.yaml`.  ping @snoyberg

**Comment by MarcelineVQ** [comment]
Oh I see, yes there was a package.yaml created. This isn't a bug after all then it's simply unexpected.
Seems like an odd thing though, would have expected it under a template like
`stack new <projectname> hpack` rather than a default.

**Comment by AndrewQuinn2020** [comment]
Commenting to add visibility to this.

I'm running through an older copy of _Haskell Programming from First Principles_; it often asks you to update `.cabal` files by hand to add dependencies.

**⚠ #HPFFP fans: As of November 2021, if you're using the latest version of Stack, adding dependencies to your `.cabal` file directly won't work. Add them to your `package.yaml` instead.**

![add-containers](https://user-images.githubusercontent.com/53230903/142383469-0fdf980f-0bff-4e82-b24b-e697bacafb64.gif)

For example, `morse` asks you to add `containers` as a dependency to your `.cabal` file; what you should actually do, however, is add it to `package.yaml`.
