### ISSUE TITLE
--terminal-width printed twice 

### ISSUE THREAD

**Issue by MaxGabriel** [commercialhaskell/stack#3542]
### General summary/comments (optional)

The `--terminal-width` option of `stack image` is printed twice in the help text. I'm actually not positive this is a bug—I haven't used `stack image` yet—but it looked like a simple oversight. If there really are meant to be two, maybe their purpose should be disambiguated somehow?

### Steps to reproduce

For example:

1. Run `stack image --help`

### Expected

One instance of `--terminal-width` is printed

### Actual

Two instances are printed, i.e.:

```
maximiliantagher@Maximilians-MBP ~/D/M/h/mercury-web-backend> stack image --help
Usage: stack image [--terminal-width INT] COMMAND [--terminal-width INT]
                   [--help]
  Subcommands specific to imaging

Available options:
  --terminal-width INT     Specify the width of the terminal, used for
                           pretty-print messages
  --terminal-width INT     Specify the width of the terminal, used for
                           pretty-print messages
  --help                   Show this help text

Available commands:
  container                Build a Docker image for the project

Run 'stack --help' for global options that apply to all subcommands.
```

### Stack version

Note: I'm using the new 1.6 prerelease.
```
$ stack --version
Version 1.6.0.20171022, Git revision 7bddfaf7f9f8cd9ec1c710fa83e77262e494eee4 (5285 commits) x86_64 hpack-0.18.1
```

### Method of installation

* Other: Official pre-release download

**Comment by lwm** [comment]
Looks like it is not being hidden from the `globalOpts` correctly? It's a bug, I think.

**Comment by mgsloan** [comment]
Yep, @lwm 's got it!  Just needed a `<> hide` - feel free to push small fixes directly to master

**Comment by lwm** [comment]
Awesome, will do! Done in https://github.com/commercialhaskell/stack/commit/2634f80de079879a4fc3ee173e16900944db838c, closing 👍
