### ISSUE TITLE
troubleshooting package index download fail

### ISSUE THREAD

**Issue by dmvianna** [commercialhaskell/stack#3543]
### General summary/comments (optional)

I had a hard time troubleshooting `stack`. The initial problem was that it failed downloading anything from `hackage`. 

However, I believe a more relevant problem is that `stack` seems to **try downloading prior to doing anything else**. That means I cannot use commands like `stack path` to get an insight on what's going on.

### Steps to reproduce

1. Install stack on Windows 10
2. Open Git bash
3. `$ stack path`

### Expected

For `stack path` I would expect to see where, if any, stack config files are.

### Actual

```bash
$ stack path -v
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e x86_64 hpack-0.17.1
2017-11-02 10:06:14.594700: [debug] Checking for project config at: H:\Data\admin-vic5tpm_docs\Source\Repos\stack.yaml
@(Stack\Config.hs:974:9)
2017-11-02 10:06:14.610307: [debug] Checking for project config at: H:\Data\admin-vic5tpm_docs\Source\stack.yaml
@(Stack\Config.hs:974:9)
2017-11-02 10:06:14.610307: [debug] Checking for project config at: H:\Data\admin-vic5tpm_docs\stack.yaml
@(Stack\Config.hs:974:9)
2017-11-02 10:06:14.610307: [debug] Checking for project config at: H:\Data\stack.yaml
@(Stack\Config.hs:974:9)
2017-11-02 10:06:14.610307: [debug] Checking for project config at: H:\stack.yaml
@(Stack\Config.hs:974:9)
2017-11-02 10:06:14.610307: [debug] No project config file found, using defaults.
@(Stack\Config.hs:1003:13)
2017-11-02 10:06:14.610307: [debug] Run from outside a project, using implicit global project config
@(Stack\Config.hs:536:13)
2017-11-02 10:06:14.610307: [debug] Trying to decode C:\sr\build-plan-cache\x86_64-windows\lts-9.11.cache
@(Data\Store\VersionTagged.hs:72:5)
2017-11-02 10:06:14.625948: [debug] Success decoding C:\sr\build-plan-cache\x86_64-windows\lts-9.11.cache
@(Data\Store\VersionTagged.hs:76:13)
2017-11-02 10:06:14.625948: [debug] Using standard GHC build
@(Stack\Setup.hs:606:9)
No compiler found, expected minor version match with ghc-8.0.2 (x86_64) (based on resolver setting in C:\sr\global-project\stack.yaml).
To install the correct GHC into C:\Users\admin-vic5tpm\AppData\Local\Programs\stack\x86_64-windows\, try running "stack setup" or use the "--install-ghc" flag.
```
And `stack setup`:

```bash
...

Extracting  ghc-8.0.2\perl\perl.exe
Extracting  ghc-8.0.2\perl\perl56.dll

Everything is Ok

Folders: 408
Files: 8819
Size:       1428273210
Compressed: 1435248640
C:\Users\myUser\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2-tmp25204\ghc-8.0.2\: renamePath:MoveFileEx "C:\\Users\\myUser\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.0.2-tmp25204\\ghc-8.0.2\\" "C:\\Users\\myUser\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.0.2\\": permission denied (Access is denied.)
```

### Stack version

```bash
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e x86_64 hpack-0.17.1
```

### Method of installation

I installed `stack` with the Windows installer, and I'm using `Git bash` as my shell. Windows 10 is the OS.

**Comment by dmvianna** [comment]
An update: After an unsuccessful run of `stack setup` using `cmd.exe` as shell, it seems `GHC` is installed. I tried running `stack setup` again from `Git bash` (to install `msys`) and it failed multiple times with the same `permission denied` message when trying to write to the `msys` directory. Then I ran it from `cmd.exe`. That time `msys` seems to have been installed successfully.

I think we need documentation describing this issue with using `Git bash` in Windows. It is a common enough tool, and developers are bound to prefer using `bash` as a shell rather than `cmd.exe`.

**Comment by dmvianna** [comment]
I think I figured it out. I wasn't able to install `GHC-8.0.1` after many `stack setup` runs. Then I just went to `~/AppData/Local/Programs/stack/x86_64-windows` (which I found running `stack path --ghc-paths` outside of my project) and created the `ghc-8.0.1/` directory. The following `stack setup` run did it.

**Comment by mgsloan** [comment]
@dmvianna Interesting, thanks for reporting the problem!  Not sure what to do about the permissions thing.  I'm surprised that creating the directory would fix the issue, because the current way installing on windows works is just:

1. Download 7z archive
2. Unpack it to a temporary location
3. Move to destination location

So I would have expected step 3 to fail after creation of the `ghc-8.0.1` directory.  Curious!

I did a blame on the relevant code and found a change that went in 1.5.0 - https://github.com/commercialhaskell/stack/commit/177d31 .  Can I possibly recruit your help in tracking this down?  It would be interesting to see if it works by either reverting that change or using 1.4

The other issue here is that stack path does not work if there is no GHC installed.  For some of the paths this is necessary, it does not know the Cabal version until after it is installed.  However, it could probably give reasonable outputs if just the snapshot is downloaded.  I've split off https://github.com/commercialhaskell/stack/issues/3548

**Comment by dmvianna** [comment]
@mgsloan, my Data Engineer came up with a reasonable explanation for the permission issue. He thinks stack was being disallowed to create the directory because the directory structure was created by me running stack through the Git bash shell. Because Windows distrusts the shell, my user not given write permission (even when I’m an administrator and I created it). We manually changed the permissions, so the problem should not resurface.

If you can, though, it would be interesting if you reproduce the problem and the diagnosis. Other users are bound to run slack in a shell when first setting it up.

-- 
Daniel Vianna

**Comment by dmvianna** [comment]
@mgsloan After adding permissions to `C:\sr\` as suggested by my Data Engineer, I was able to install a minor release of `GHC` through `stack` with no issues.

**Comment by mgsloan** [comment]
Ah cool, sounds like this is resolved.  Indeed, having a short stack root like that is recommended. Perhaps we should make it a default.

**Comment by dmvianna** [comment]
I went through another long test/fail run. So as I understand the recipe is: run `stack` as an **administrator** from `cmd.exe` run as and **administrator**. Anything else will cause permission issues. If that happens, they'll have to be fixed manually, and that will involve creating the `stack-root` directory manually to ensure the right permissions. Fixing the permissions after the fact doesn't seem to work well.

**Comment by mgsloan** [comment]
@dmvianna Hmm, not sure I follow what stack should change here.  Feel free to open a new issue about it or PR

**Comment by dmvianna** [comment]
I can’t. I don’t understand the windows architecture enough to make it worthwhile. But I do think the windows documentation is lacking at explaining how to install to non-default locations taking into consideration the security status of the user and the target directory.

-- 
Daniel Vianna
