### ISSUE TITLE
Warn when `stack repl` or `stack ghci` are run in a non-project

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/stack#3544]
### General summary/comments (optional)

When you run `stack repl` in a non-stack Haskell project, `stack` happily opens a GHCi in the implicit global project. [This can sometimes be confusing](https://stackoverflow.com/questions/47065821/ghci-failed-to-load-interface-for/47065994#47065994).

`stack build` properly fails without a `stack.yaml` in the directory. Should `stack ghci` and `stack repl` warn if they're in a non-project and the current working directory has a `*.cabal` file? Should they prompt a call to `stack init`?

### Steps to reproduce

For example:

1. `git clone https://github.com/ndmitchell/hoogle`
2. `cd hoogle`
3. `stack repl`
4. `:l src/Hoogle.hs`

### Expected

Users will probably expect to see the `hoogle` package loaded.
If the project isn't a `stack` project, then it may make sense to show a warning and suggest a `stack init`.

### Actual

```
λ > :l src/Hoogle.hs 
[ 1 of 27] Compiling Input.Settings   ( src/Input/Settings.hs, interpreted )

src/Input/Settings.hs:17:1: error:
    Failed to load interface for ‘Paths_hoogle’
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
```

### Stack version

```
λ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by lwm** [comment]
> stack build properly fails without a stack.yaml in the directory. Should stack ghci and stack repl warn if they're in a non-project and the current working directory has a *.cabal file? Should they prompt a call to stack init?

Sounds like a good idea to me.

**Comment by mgsloan** [comment]
Thank you for the report!  Yes, I think it makes sense to have `stack ghci` noisily warn when it is run without any targets.  I've pushed a PR that when merged will cause it to output:

![2017-11-02_585x199_scrot](https://user-images.githubusercontent.com/22570/32321632-f89ff05e-bf7e-11e7-8833-5908d0c69db8.png)
