### ISSUE TITLE
Unable to configure stack to use X.509 client certificates

### ISSUE THREAD

**Issue by meangrape** [commercialhaskell/stack#3545]
### General summary/comments (optional)

I've set up an internal hackage server for my company. We have users across multiple timezones and countries. I want to use X.509 client certificates for user authentication. This works in a straightforward manner for web browsers and assorted command-line tools (openssl s_client and curl, for instance). 

The only support that stack seems to have for certificates is for verification of server-side certificates (configurable via `export SYSTEM_CERTIFICATE_PATH`).

### Steps to reproduce

Add a `download-prefix` to your stack.yaml that points at a hackage URL where the proxying web server (nginx in this case) has `ssl_verify_client on`.

### Expected

That stack will have a mechanism for explicitly identifying client certificates for authentication.

### Actual

```
$ stack build --verbose
```

```Selected mirror https://hackage.sentenai.net/                                  
Downloading root                                                               
Updating package index sentenai (mirrored at https://hackage.sentenai.net/) ...VerificationErrorDeserialization (TargetPathRepo (Path "root.json")) (DeserializationErrorMalformed "(line 1, column 1):\nunexpected \"<\"\nexpecting white space or JSON value")
```

It appears stack is attempting to parse the error message from the nginx server:
```
<html>
<head><title>400 No required SSL certificate was sent</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>No required SSL certificate was sent</center>
<hr><center>nginx/1.12.1</center>
</body>
</html>
```

### Stack version

```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

### Method of installation

FreeBSD ports

**Comment by mgsloan** [comment]
Odd, that should be working according to the FAQ https://docs.haskellstack.org/en/stable/faq/#other-nix-oss .  Could be an issue with the `http-client-tls` or `x509-system` packages

**Comment by jayed** [comment]
@mgsloan The FAQ is correct -- we're dealing with an issue of the word `certificate` being overloaded. The information in the FAQ is about how to add a server-side certificate to your client so that the client may verify the server has a trusted certificate.
Roughly speaking, I'm doing the opposite. I've generated certificates that will authenticate the *user* to the server. (It's like a password on steroids). Client-side certificates are uncommon but widely used especially in corporate and government circles. Stack has no mechanism to expose and send these client-side certificates.

**Comment by mgsloan** [comment]
I see!  I did not read your initial post carefully enough, thanks for the clarification.

Is there a standard way to let programs know about client certificates - like a similar env var?  Or is it pretty much a per application configuration?  If there is a standard way to specify it, then it seems like a good idea to add it to `http-client-tls` / possibly `x509-system`

**Comment by jayed** [comment]
Unfortunately, there is no standard method. However the library that provides your TLS capabilities does it is what you're stuck with.
