### ISSUE TITLE
Notify when test suites complete

### ISSUE THREAD

**Issue by tswelsh** [commercialhaskell/stack#3552]
Sort of similar to #3508.  We have a project with many packages and test suites, some of which are very quick unit tests and some of which are long integration tests.  When doing a full build +test (especially for newcomers to the project, the natural thing is to do something like `stack build --test` after getting the repository), the whole thing just looks like it's hanging when it's running the tests.  In reality, nearly all tests have completed almost immediately but there are some long ones which don't.  So we see e.g.

```
> stack test
long-tests-0.1.0.0: configure (test)
short-tests-0.1.0.0: configure (test)
long-tests-0.1.0.0: build (test)
long-tests-0.1.0.0: test (suite: long-test-suite)
short-tests-0.1.0.0: build (test)
short-tests-0.1.0.0: test (suite: short-test-suite)
```
with no indication of which one is hanging.  A notification of a test suite completing would help to diagnose this.  The situation is a bit better with just builds, but the  `copy/register` line indicates when a particular build is finished.

I can submit a pull request if you think this is an appropriate change, looks simple enough - just adding another call to `announce` in `Stack.Build.Execute.singleTest`.

**Comment by mgsloan** [comment]
Having trouble easily digging out the issue, but I think somewhere there is a proposal to have the last line of the output be a summary of "Here are the things stack is working on right now".  Then, the lines that actually end up permanently in the output would be indications that something has finished, rather than indications that something has started.

**Comment by lwm** [comment]
> I can submit a pull request if you think this is an appropriate change, looks simple enough

I'd definitely like to see with what you come up with!

**Comment by mgsloan** [comment]
Indeed, a PR is appreciated!  It doesn't need to be the full blown "use a sticky log to show what's currently being worked on" that can come later :)

**Comment by tswelsh** [comment]
PR made. I had a poke around for the issue that was mentioned by @mgsloan but couldn't find it either, so I just did the simplest thing possible (it does look a bit ad hoc, but solves my original issue at least).

**Comment by lwm** [comment]
Done in #3552! Nice one @tswelsh.
