### ISSUE TITLE
stack 1.6.0 doesn't return path to inbuilt-ghc when building packages using ghcjs

### ISSUE THREAD

**Issue by mands** [commercialhaskell/stack#3553]
### General summary/comments

We're in the process of moving to using the `v1.6.0.20171022` prerelease as it has a certain bugfix we require (#3476), however the behaviour appears to have changed when running `Setup.hs` during compilation with `ghcjs`.

The particular package failing is `entropy` (https://github.com/TomMD/entropy), it works when using stack `1.5.1` but fails on `v1.6.0.20171022`. 

### Steps to reproduce

Using the following test-case, with empty `.stack-work` and `~/.stack` cache directories, and no system-wide `ghc` installed,

`stack.yaml`

```yaml
resolver: lts-8.11
compiler: ghcjs-0.2.1.9008011_ghc-8.0.2
ghc-build: tinfo6
compiler-check: match-exact
setup-info:
  ghcjs:
    source:
      ghcjs-0.2.1.9008011_ghc-8.0.2:
        url: https://github.com/matchwood/ghcjs-stack-dist/raw/master/ghcjs-0.2.1.9008011.tar.gz
        sha1: a72a5181124baf64bcd0e68a8726e65914473b3b

packages:
- '.'
```

cabal file (`stack-ghcjs-test.cabal`)
```
name:                stack-ghcjs-test
version:             0.0.1
cabal-version:       >=1.22
build-type:          Simple
license:             AllRightsReserved
license-file:        LICENSE
category:            Web

executable nstack-frontend
  ghc-options: -Wall -dedupe
  cpp-options: -DGHCJS_BROWSER

  hs-source-dirs:      src

  main-is:             Main.hs
  build-depends:       ghcjs-base
                     , base
                     , entropy

  default-language:    Haskell2010
```

and a trivial `src/Main.hs`

```haskell
module Main where
main :: IO ()
main = return ()
```

then running the following commands,
```bash
$ stack setup
$ stack build
```

works for 1.5.1, but fails using 1.6.0

### Expected

1.6.0 to build as 1.5.1 does

### Actual

1.6.0 fails during the `build` stage of `entropy` with the following error,

```bash
Linking /home/mandeep/.stack/setup-exe-cache/x86_64-linux/tmp-Cabal-simple_mPHDZzAJ_1.24.2.0_ghcjs-0.2.1.9008011_ghc-8.0.2.jsexe (Main,StackSetupShim)
entropy-0.3.7: download
entropy-0.3.7: configure
entropy-0.3.7: build
Progress: 1/2
--  While building package entropy-0.3.7 using:
      /tmp/stack7376/entropy-0.3.7/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs/setup/setup --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs build --ghcjs-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/mandeep/Dev/Projects/NStack/scratch/stack-ghcjs-test/.stack-work/logs/entropy-0.3.7.log

    [1 of 2] Compiling Main             ( /tmp/stack7376/entropy-0.3.7/Setup.hs, /tmp/stack7376/entropy-0.3.7/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs/setup/Main.js_o )
    [2 of 2] Compiling StackSetupShim   ( /home/mandeep/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack7376/entropy-0.3.7/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs/setup/StackSetupShim.js_o )
    Linking /tmp/stack7376/entropy-0.3.7/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0_ghcjs/setup/setup.jsexe (Main,StackSetupShim)
    Configuring entropy-0.3.7...
    Could not determine C compiler
    CallStack (from HasCallStack):
    error, called at /tmp/stack7376/entropy-0.3.7/Setup.hs:22:54 in main:Main
```

The package `Setup.hs` is at https://github.com/TomMD/entropy/blob/master/Setup.hs - from my understanding it tries to use uses Cabal to find the location for `ghc` and use it to compiles a sample C source file.

Interestingly installing a system-wide ghc, e.g. from a linux package manager, allows the build to succeed, suggesting that `lookupProgram` is failing to return the path to the `stack`-installed `ghc` when using `ghcjs`.

### Stack version

Working with 1.5.1
```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

Broken with 1.6.0 (prerelease)
```
$ stack --version
Version 1.6.0.20171022, Git revision 7bddfaf7f9f8cd9ec1c710fa83e77262e494eee4 (5285 commits) x86_64 hpack-0.18.1
```

### Method of installation

* Official linux64 prerelease binary from https://github.com/commercialhaskell/stack/releases/tag/v1.6.0.20171022

**Comment by mgsloan** [comment]
I am surprised that the behavior changed here between stack 1.5.1 and 1.6.0 .

Not sure what the best way is to resolve this.  I suppose the solution is to derive the ghc version from the ghcjs version.  It might not be that hard to require that GHC is installed as well as GHCJS.

See also https://github.com/commercialhaskell/stack/issues/1258 .  There, I say that this would be a pain because we currently have an assumption of just having one compiler version.   However, I realized that it wouldn't necessarily need to be so.  Going to go ahead and close that issue in favor of this one.

That said, it'd seem pretty ad-hoc to put ghc on the PATH but not have anything other than the global DB in GHC_PACKAGE_PATH (no ghc snapshot / project means no user DBs).  Perhaps this is such a squirrely case that it should be left manual.

**Comment by mands** [comment]
Just to follow up, adding the location of the `ghc` installed by stack to setup `ghcjs` itself to the PATH works and solves the issue for us - thanks for the tip!

I think many users would hit this issue when using `ghcjs`, as several common dependencies have similar requirements, e.g. `clock` needs the `ghc` version of `hsc2hs`. Perhaps documentation informing `ghcjs` users to add the matching `ghc` to their PATH would suffice.

**Comment by mgsloan** [comment]
Hmm, yeah, how about warning if the `ghc` on the PATH does not match the ghc version of GHCJS?

**Comment by mands** [comment]
Yeah, that would work well and let the user decide how to proceed.

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
