### ISSUE TITLE
Disable "shadowed dependencies" workaround when GHC is new enough

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3554]
This is a task for a release of GHC beyond 8.2.2.  Here's what's going on:

* There is a bug with ghc-pkg, see https://github.com/haskell/cabal/issues/4728

* There is a patch on phabricator that will hopefully land after 8.2.2: https://phabricator.haskell.org/D4159

* Reconfigure is currently forced when deps are rebuilt - https://github.com/commercialhaskell/stack/pull/3503

So, this issue is tracking disabling the reconfigure workaround when upstream is fixed, as this will make builds faster.

**Comment by snoyberg** [comment]
See #4741
