### ISSUE TITLE
Use equality constraints for all dependencies in stack's executable?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3558]
Since we sometimes want to use stack as a library, particularly in scripts (https://github.com/commercialhaskell/stack/issues/3522), we want it to work with many dependency versions.  However, particularly for releases, we want the executable to only use very specific dependency versions.  In order to have cabal-install use these versions, equality constraints could be added to the executable stanza.  A cabal flag would need to be added, to toggle buildability of the executable.

One downside of this approach is that `stack install stack` would no longer install an executable.  This could potentially be resolved by having it detect the existence of a stack.yaml in the hackage package - see https://github.com/commercialhaskell/stack/issues/2122 .  It seems good to address this, because it's another way that stack could be installed without using the standard set of dependencies.

**Comment by borsboom** [comment]
Hmm, I think this might be going a bit far.  This would, for example, make it really hard to try an executable built with stack-nightly.yaml.  I suppose we could have a flag that also toggles the equality constraints on the executable.

**Comment by mgsloan** [comment]
Yeah, I think it is more effort than it is worth.

The only way to make it practical would be to somehow hook into the hpack generation step to set the constraints on the executable.  Going to go ahead and close.
