### ISSUE TITLE
Stack.Solver needs to ignore cabal sandbox files WAS: [Question] stack can't find packages

### ISSUE THREAD

**Issue by vlatkoB** [commercialhaskell/stack#356]
Hi,

`stack init` produces `resolver: ghc-7.8` because two packages couldn't be found in `LTS`es:
```
2015-06-19 11:02:43.976672: [debug] Package not present: SafeSemaphore @(stack-0.0.3.1:Stack.BuildPlan src/Stack/BuildPlan.hs:534:19)
2015-06-19 11:02:43.976784: [debug] Package not present: rdtsc @(stack-0.0.3.1:Stack.BuildPlan src/Stack/BuildPlan.hs:534:19)
```
`cabal build` builds without problems, but `stack build` produces many
```
--  While attempting to add dependency,
    Could not find package HTTP in known packages
...
--  Failure when adding dependencies:    
      HTTP: needed (-any), but not present in build plan, latest is 4000.2.19
...
Recommended action: try adding the following to your extra-deps in /home/vlatko/Haskell/StdImports2/stack.yaml
- HTTP-4000.2.19
...
```

Is there some config option that I missed?

GHC 7.8.4, cabal 1.20.1.0, Arch

br,
vlatko

**Comment by snoyberg** [comment]
Could you provide your generated stack.yaml and the original .cabal file?

**Comment by vlatkoB** [comment]
Hi Michael,

Thanks for quick response.
Found the problem. I had LTS 2.14 `cabal.sandbox.config` file left in the project's root folder. The generated stack.yaml was:
```
flags: {}
packages:
- '.'
extra-deps: []
resolver: ghc-7.8
```
When I removed `cabal.sandbox.config`, `stack init` still uses `ghc-7.8` resolver, but fills `extra-deps` correctly.

.cabal file is quite simple:
```
library
  build-depends:
                   async,
                   base >= 4.7,
                   classy-prelude,
                   containers,
                   data-default,
                   deepseq,
                   directory,
                   filepath,
                   errors,
                   hslogger,
                   HTTP,
                   MissingH,
                   network-uri,
                   old-locale,
                   rdtsc,
                   SafeSemaphore,
                   split,
                   text,
                   time
```
I assume, since `stack init` falls back to `ghc` resolver which reports all packages are present, `extra-deps` is not filled.
Maybe that could be mentioned in docs, or I missed it?

**Comment by snoyberg** [comment]
Ouch, that's why I hate working with cabal, there's always a corner case. It should be able to work around the sandbox somehow, I'll try this on Sunday.

**Comment by snoyberg** [comment]
Alright, this should now be fixed, thanks again for the report.
