### ISSUE TITLE
How to uninstall stack

### ISSUE THREAD

**Issue by MatthiasKauer** [commercialhaskell/stack#3563]
Hi,
I installed stack from https://get.haskellstack.org/ and now I'd like to remove it from this computer.
I know it has files in ~/.stack and the binary in /usr/local/bin. As far as I can tell the installer used the "sloppy" method (on LInuxmint) and downloaded a static binary.

Does it reside in other locations? Is there a more canonical approach?

Best regards,
Matthias

**Comment by mgsloan** [comment]
Removing `~/.stack` and `/usr/local/bin/stack` should be sufficient.  I don't think there's anything else.  That's it, right @borsboom ?  You may want to delete `.stack-work` folders in any Haskell projects that you have built.

Sorry that stack or haskell didn't work out for you!  Anything in particular amiss?  Or just trying it out and deciding not to pursue further?

> As far as I can tell the installer used the "sloppy" method (on LInuxmint) and downloaded a static binary.

I do not see how this is sloppy, it is way more reliable to ship static binaries.

**Comment by MatthiasKauer** [comment]
Thank you for the quick feedback.

Stack works just fine for me. I'm just having trouble on this machine right now.

Regarding "sloppy": This was a reference to the method you called
"do_sloppy_install()" in https://get.haskellstack.org/
I realize now that it came across in the wrong way. I'm sorry.

**Comment by mgsloan** [comment]
> Stack works just fine for me. I'm just having trouble on this machine right now.

I'm glad :D Feel free to create more issues in the future if you encounter any difficulties or if there are features you'd like.

> I realize now that it came across in the wrong way. I'm sorry.

Oh, I see. I should have guessed by sloppy being in quotes.  No worries!  I think it being called sloppy isn't due to the static vs dynamic.  Instead, it's just that it doesn't know how to install the dependencies.  If you're having trouble with it on that machine, it's likely due to these dependencies.

**Comment by iambugra** [comment]
I cannot remove /usr/local/bin/stack , i get "permission denied". I am trying to change the permissions, but still it doesn't work.

**Comment by MuhammadSawalhy** [comment]
> I cannot remove /usr/local/bin/stack , i get "permission denied". I am trying to change the permissions, but still it doesn't work.

Just use `sudo rm /usr/local/bin/stack`

**Comment by VALENTINAMOVILSANDOVAL** [comment]
I did what you say. However I can still using stack command and it looks like everything was fine

**Comment by mpilgrem** [comment]
@VALENTINAMOVILSANDOVAL, I could not follow your comment above. Are you saying that you have tried to uninstall Stack but Stack still seems to be present? If yes, what operating system are you using?
