### ISSUE TITLE
Flags passed to snapshot packages from local stack.yaml

### ISSUE THREAD

**Issue by dbaynard** [commercialhaskell/stack#3564]
According to the `stack.yaml` docs,

> ## flags
>
> Flags can be set for each package separately, e.g.
> 
>     flags:
>       package-name:
>         flag-name: true
> 
> Flags will only affect packages in your packages and extra-deps settings. Packages that come from the snapshot global database are not affected.

Using `2d97213` I was able to supply a flag (`example: false`) to the `wai-websockets` contained in my custom (extensible) snapshot, from a project's stack.yaml.

The behaviour doesn't match the docs; one should change. I'd suggest changing the behaviour if setting the flag differently in another package using the same snapshot doesn't lead to recompilation. I haven't yet had a chance to investigate.

I suspect this has crept in through extensible snapshots, though I can't say for certain.

**Comment by mgsloan** [comment]
Thanks for the report, I've pushed a fix that changes the text to

> If a specified flag is different than the one specified for a snapshot package,
> then the snapshot package will automatically be promoted to be an extra-dep.
