### ISSUE TITLE
Allow to pass '.cabal' files to 'stack build' command

### ISSUE THREAD

**Issue by ChShersh** [commercialhaskell/stack#3566]
When I type the following in my shell:

```bash
stack build pro TAB
```

I see

```bash
stack build project-long-name.cabal
```

Autocompletion in shell works in the way that it autocompletes to file. Even if I have next lines in my `~/.bashrc`:

```bash
# enable stack autocompletion
eval "$(stack --bash-completion-script stack)"
```

It's not very convenient because I need to press `BACKSPACE` key 6 times to build project after pressing `TAB` key. It would be really nice if `stack` could handle this situation and allowed building project by specifying `.cabal` file of the project from project inside.

**Comment by mgsloan** [comment]
@ChShersh Which version of stack are you using?  Recent stack does have targets completion. It's imperfect - unfortunately you do need to hit backspace twice - https://github.com/commercialhaskell/stack/issues/3571

**Comment by ChShersh** [comment]
@mgsloan My version of `stack`:

```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

Maybe my proposal is not necessary because you can just type `stack build` without any arguments to build whole project. No need in typing extra arguments. But I'm not sure how well it interacts with building multipackage projects if you need to build only one package...

**Comment by mgsloan** [comment]
>  But I'm not sure how well it interacts with building multipackage projects if you need to build only one package...

Yeah, in that case you will want to have the script.

Perhaps you have multiple versions of stack installed?  Like maybe your stack is in `~/.local/bin` (a quite reasonable place for it), but there may be an older version elsewhere.  It could be that the autocompletion script is getting run for an old version of stack.  So, make sure that the location of stack is on the PATH when evaluating the completion script.

**Comment by snoyberg** [comment]
Are you aware that you can provide a directory name as a target already?

**Comment by ChShersh** [comment]
@snoyberg No, I wasn't aware of such feature :disappointed:

**Comment by snoyberg** [comment]
Does that address your issue here, since you can just tab-complete to the directory instead of the cabal file?

**Comment by ChShersh** [comment]
@snoyberg Not exactly. Because I use `stack build pro TAB` command inside project. After creating issue I discovered that I don't actually need to type name of my project because `stack build` already builds my current project. No need in extra keystrokes!

**Comment by mgsloan** [comment]
@ChShersh `stack build ` + TAB does complete both options and targets.  Though, it's currently a bit slower than I'd like.  Perhaps your bash completions aren't set up properly?

Going to close this as a support issue.
