### ISSUE TITLE
Stack sdist option to place build artefacts elsewhere

### ISSUE THREAD

**Issue by tmcgilchrist** [commercialhaskell/stack#3568]
Currently running `stack sdist` places the build artefacts into a directory like `.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/`

eg
```shell
1.22s$ stack --no-terminal $ARGS sdist
Getting file list for /home/travis/build/riak-haskell-client/riak-haskell-client/
Building sdist tarball for /home/travis/build/riak-haskell-client/riak-haskell-client/
Checking package 'riak' for common mistakes
Wrote sdist tarball to /home/travis/build/riak-haskell-client/riak-haskell-client/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/riak-1.1.2.1.tar.gz
Getting file list for /home/travis/build/riak-haskell-client/riak-haskell-client/protobuf-lens/
Building sdist tarball for /home/travis/build/riak-haskell-client/riak-haskell-client/protobuf-lens/
Checking package 'riak-protobuf-lens' for common mistakes
Package check reported the following warnings:
No 'description' field.
Wrote sdist tarball to /home/travis/build/riak-haskell-client/riak-haskell-client/protobuf-lens/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/riak-protobuf-lens-0.22.0.0.tar.gz
Getting file list for /home/travis/build/riak-haskell-client/riak-haskell-client/protobuf/
Building sdist tarball for /home/travis/build/riak-haskell-client/riak-haskell-client/protobuf/
Checking package 'riak-protobuf' for common mistakes
Wrote sdist tarball to /home/travis/build/riak-haskell-client/riak-haskell-client/protobuf/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/riak-protobuf-0.22.0.0.tar.gz
```

What would be ideal is for `stack sdist` to either:
 1. Have an option to copy the result to another directory, or
 2. Place it in the same location as `cabal sdist` which uses `dist/package.tar.gz`

Personally I would favour the second option but having an escape option 1 would also work.

**Comment by snoyberg** [comment]
I'm in favor of the first option; we don't use the `dist` directory at all as it would conflict with cabal, and I don't think this is a good time to change that. But if you're interested, the first route shouldn't be too difficult to add.

**Comment by Asalle** [comment]
Hi there, can I work on this issue? How can I assign myself?

**Comment by mgsloan** [comment]
@Asalle That'd be great!  Indicating your interest in working on it here is sufficient.  Feel free to add comments here asking questions about implementation, and once you have an initial version, you can put up a PR for review, iteration, and merge

(ignore my self assignment above, mispressed a button)

**Comment by Asalle** [comment]
> Currently running stack sdist places the build artefacts into a directory like .stack-work/dist/x86_64-linux/Cabal-1.24.2.0/
1. Is it correct that by `building artefacts` you understand the tarballs?
2. In case of the first option, do you want all the tarballs in the same directory you specified?

**Comment by snoyberg** [comment]
1. That was my understanding
2. I would understand it to copy all of the generated tarballs into the same directory

**Comment by Asalle** [comment]
Thanks for the quick reply!
Could you please check if I'm moving in the right direction? https://github.com/Asalle/stack/commit/b2cdffcd03b6b1ae6d9105086dd4fccfe907729d

Somehow I cannot add `optional strOption`, 

    • Couldn't match type ‘Maybe (Parser String)’
                     with ‘Parser (Maybe String)’
      Expected type: Mod OptionFields String -> Parser (Maybe String)
        Actual type: Mod OptionFields String -> Maybe (Parser String)
    • The function ‘optional’ is applied to two arguments,
      its type is ‘f0 a0 -> f0 (Maybe a0)’,
      it is specialized to ‘(Mod OptionFields String -> Parser String)
                            -> Mod OptionFields String -> Maybe (Parser String)’
      In the second argument of ‘(<*>)’, namely
        ‘optional
           strOption
           (long "tar-path"
            <> help "If specified, copy all the tar to this dir")’
      In the expression:
        SDistOpts
        <$> many (strArgument $ metavar "DIR" <> completer dirCompleter)
        <*> optional pvpBoundsOption
        <*> ignoreCheckSwitch
        <*>

but my understanding is that this tarpath option should not be required, what should I do? Declare a new type of `optional strOption`?

**Comment by snoyberg** [comment]
I think you need an extra wrapping of parens, e.g. `optional (strOption (...))`.

**Comment by BraulioVM** [comment]
I believe this issue got fixed in https://github.com/commercialhaskell/stack/commit/ff72d07bbc25545c5354d95b958c44641221ec89

Should it be closed?

**Comment by tmcgilchrist** [comment]
Yes, looks good.

**Comment by mihaimaruseac** [comment]
Reported to be closed, checked on my end and is closed.
