### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#357]
Stack is big enough that people are asking questions. At the moment they are going on the commercial haskell mailing list, but it seems Stack is really a bit different from the goals of that list, so probably deserves its own mailing list.

**Comment by bitemyapp** [comment]
:+1:

**Comment by snoyberg** [comment]
OK, I've created this:

https://groups.google.com/d/forum/haskell-stack

Can you guys join and advertise appropriately? I'll include this information in README and future announcements too.

**Comment by radix** [comment]
It looks like posts to the group aren't visible unless you're a member. Not sure if that's intended.

**Comment by snoyberg** [comment]
It was not, thanks for catching that.

**Comment by snoyberg** [comment]
I sent off an email to the cafe and Commercial Haskell lists, so closing this. Others should feel free (and encouraged) to mention the list too.

**Comment by ndmitchell** [comment]
Thanks. I was going to do that when I reached a machine with email, google groups, GitHub and a keyboard - but that hasn't happened yet...
