### ISSUE TITLE
Warning: Installation path not in PATH: even forced export

### ISSUE THREAD

**Issue by wizzup** [commercialhaskell/stack#3570]
### General summary/comments

What could be the reason I get following WARNING?

    WARNING: Installation path /home/wizzup/.local/bin not found on the PATH environment variable

### Steps to reproduce

Given following `test.sh`

    export PATH=~/.local/bin:$PATH
    echo $PATH
    PATH=$PATH stack install ghc-mod hlint hasktags

When running with `./test.sh 2>&1 | tee log.txt` yield following `log.txt`

    /home/wizzup/.local/bin:/nix/store/r3jxn4r0lssd0my8s0ndcc72np96gcid-stack-1.5.1/bin:/nix/store/yhlvb9aiya369qn2r5jz9k1q6qqg5m3w-patchelf-0.9/bin:/nix/store/azzl0bvmzsqc999mg9rgk37pr64wfdz0-paxctl-0.9/bin:/nix/store/0abay33zgwqgchdzzq6h88ac4963smwf-coreutils-8.28/bin:/nix/store/rix7drclds895majp75f4imqh09w9bvb-findutils-4.6.0/bin:/nix/store/jxa512mq3hyrbqwdhlkc7q1xxh538x4z-diffutils-3.6/bin:/nix/store/arcyymlgk8nh0flbb4hb2m287byfswkr-gnused-4.4/bin:/nix/store/jnflx7xcqjkn7lkkr8hiv0y284fdz0qf-gnugrep-3.1/bin:/nix/store/1yqmx3rl2hmz78992i9k8l4y88r42gm1-gawk-4.2.0/bin:/nix/store/7lx6bha6l22vi5h9c31nri1p7rqs7v1d-gnutar-1.29/bin:/nix/store/smx6lirinf04qkm5i9hxrfg9psl7jlsz-gzip-1.8/bin:/nix/store/fw1ixc551hm7mvpfxcmlzr6y1x3ck2hv-bzip2-1.0.6.0.1-bin/bin:/nix/store/caq1vyjkcgfrnxkynizn1bxw1vwazl0n-gnumake-4.2.1/bin:/nix/store/4ada72n7785wwazv42fhsnxjvilaa3aj-bash-4.4-p12/bin:/nix/store/v06ybx67cflsmcgjhs260wzclglrjg0p-patch-2.7.5/bin:/nix/store/r556bjkg62fh4mxpfqpa9rpjcvbylg6z-xz-5.2.3-bin/bin:/home/wizzup/bin:/run/wrappers/bin:/etc/per-user-pkgs/wizzup/bin:/home/wizzup/.nix-profile/bin:/nix/var/nix/profiles/default/bin:/run/current-system/sw/bin
    Copying from /home/wizzup/.stack/global-project/.stack-work/install/x86_64-linux-nix/lts-9.12/8.0.2/bin/ghc-mod to /home/wizzup/.local/bin/ghc-mod
    Copying from /home/wizzup/.stack/global-project/.stack-work/install/x86_64-linux-nix/lts-9.12/8.0.2/bin/ghc-modi to /home/wizzup/.local/bin/ghc-modi
    Copying from /home/wizzup/.stack/global-project/.stack-work/install/x86_64-linux-nix/lts-9.12/8.0.2/bin/hasktags to /home/wizzup/.local/bin/hasktags
    Copying from /home/wizzup/.stack/snapshots/x86_64-linux-nix/lts-9.12/8.0.2/bin/hlint to /home/wizzup/.local/bin/hlint

    Copied executables to /home/wizzup/.local/bin:
    - ghc-mod
    - ghc-modi
    - hasktags
    - hlint

    WARNING: Installation path /home/wizzup/.local/bin not found on the PATH environment variable

### Stack version

    $ stack --numeric-version
    1.5.1

### Method of installation

* An unofficial package repository : NixOS

**Comment by mgsloan** [comment]
@wizzup Strange!  What is in the stack.yaml?

Checking the output of `stack path --bin-path` may be helpful

**Comment by wizzup** [comment]
There is nothing but 2 files in the directory. I made some update to be more verbose, here

[log.txt](https://github.com/commercialhaskell/stack/files/1464650/log.txt)

[test.sh.txt](https://github.com/commercialhaskell/stack/files/1464651/test.sh.txt) (github doesn't allowed `.sh` upload)

**Comment by mgsloan** [comment]
I cannot reproduce it on ubuntu, I suspect it has something to do with NixOS.  Perhaps you have stack's nix integration enabled, or perhaps it gets enabled by default on NixOS, I don't recall.  In that case, stack is effectively executing in a nix sandbox and will ignore environment variables when it is invoked.

**Comment by wizzup** [comment]
Seem reasonable. I have nix enable in my configuration.

Since it is not major and non reproducible, I am going to close this issue. 

Thank for your time.

**Comment by isnullxbh** [comment]
@wizzup, can you tell me about changes you have made to config.yaml?
I installed the Haskell stack and  tried to create project using next command:
`stack new projectName`
As result I got an error related to 'bytestring'. I upgraded stack, but at the end of operation I got warning similar to the one you have described. Thanks.

**Comment by isnullxbh** [comment]
@wizzup, no problem, thanks for reply! I fixed it by adding **local-bin-path** parameter to configuration file.
