### ISSUE TITLE
Some bug in the Ubuntu-package

### ISSUE THREAD

**Issue by BernwardWeigand** [commercialhaskell/stack#3577]
### General summary
Hello I tried to use stack for a project I work with under Ubuntu 16.04LTS. Somehow it din't work correctly and I got some error. Then I searched for a fix on stackoverflow and found the follwing [workaround](https://stackoverflow.com/questions/42269549/weird-error-with-haskell-stack-it-doesnt-install-anything-anymore):

### Steps to reproduce

1. Installation of stack form aptitude
2. Tried to build some project.

My **stack.yaml** was this one:
```
flags: {}
packages:
- '.'
extra-deps:
resolver: lts-9.9
```

### Expected

I expected to build my project correctly.

### Actual
This just happend:
```
Invalid package ID: "array-0.5.1.1 base-4.9.1.0 binary-0.8.3.0 bytestring-0.10.8.1"
```

### Stack version
My used stack version is:
```
Version 1.5.1
```

### Method of installation

The aptitude-package of haskell-stack
```
apt install haskell-stack
```

**Comment by mgsloan** [comment]
This looks like a bug from a version of stack much older than 1.5.1 - https://github.com/commercialhaskell/stack/issues/1758

Indeed, when I do `apt show haskell-stack` on ubuntu 16.04 I get "0.1.10", which is a rather old version of stack.  We do not usually recommend installing stack via distro package manager, for this very reason.  `stack upgrade` may work.  If it doesn't, please follow https://docs.haskellstack.org/en/stable/README/

**Comment by BernwardWeigand** [comment]
Sry, my mistake. I checked the stack-version after fixing the bug.
An Update for the distro package would be great.
