### ISSUE TITLE
Prerelease stack links to broken target docs

### ISSUE THREAD

**Issue by MaxGabriel** [commercialhaskell/stack#3578]
### General summary/comments (optional)

When using a prerelease, the link to the TARGET syntax is broken. This may be expected for the prerelease version of Stack, in which case you can ignore this.

### Steps to reproduce

For example:

1. `stack build --help`
2. Find the TARGET docs
3. Open the link, e.g. https://docs.haskellstack.org/en/v1.6.0.20171022/build_command/#target-syntax

### Expected

The link takes me to the docs

### Actual

The link gives a "Permission Denied" error
### Stack version

```
$ stack --version
Version 1.6.0.20171022, Git revision 7bddfaf7f9f8cd9ec1c710fa83e77262e494eee4 (5285 commits) x86_64 hpack-0.18.1
```

### Method of installation

Prerelease download

**Comment by lwm** [comment]
Perhaps we can update that help documentation with a note about pre-release versions of stack and pointing to the latest version of the documentation - https://docs.haskellstack.org/en/latest/README/. Otherwise, I have no idea how to fix this.

**Comment by borsboom** [comment]
I'll make a note to activate the pre-release tag for documentation generation next time, then it should "just work".
