### ISSUE TITLE
Unable to get off ground 

### ISSUE THREAD

**Issue by kevinsullivan** [commercialhaskell/stack#358]
New install. Stack 0.0.3. Ubuntu 14.04. Created directory for project. Added nat.hs file to directory. Tried to get it to load (in several ways). I thought stack would download GHC, and I thought it would create an empty stack.yaml. Here's a session log. What am I missing? Thanks, and sorry for newbie questions.

cs1@cs1:~/CS1/nat$ stack ghci nat.hs
Using resolver: lts-2.14 from global config file: /home/cs1/.stack/global/stack.yaml
No GHC found, expected version 7.8.4 (x86_64) (based on resolver setting in /home/cs1/.stack/global/stack.yaml). Try running stack setup

cs1@cs1:~/CS1/nat$ stack setup
Unable to find a stack.yaml file in the current directory (/home/cs1/CS1/nat/) or its ancestors
Recommended action: stack new

cs1@cs1:~/CS1/nat$ stack new
new command not yet implemented, check out https://github.com/commercialhaskell/stack/issues/137 for status and to get involved

**Comment by drwebb** [comment]
If you have an existing cabal file already for your project you can call stack init. You'll have to write one, because currently your project needs a cabal file in order to get started.

**Comment by chreekat** [comment]
To be clear, it is a design goal that stack will get you started in the
scenario of a single bare source file. (I am not the one to ask about the
status of that feature, however.)

**Comment by spinda** [comment]
Note that, for now, you can have `cabal` generate the initial .cabal file via `cabal init` (including an attempt at detecting package dependencies).

**Comment by snoyberg** [comment]
`stack new` is now implemented with latest `stack`, please give that a shot. It looks like we have a corner case right now because `stack setup` is requiring a stack.yaml when it should just fall back to the implicit global, I'll fix that.

**Comment by snoyberg** [comment]
OK, this should be fixed with the newest stack on master.

**Comment by kevinsullivan** [comment]
*Thanks*
