### ISSUE TITLE
`stack templates --help` should mention stack-templates repo

### ISSUE THREAD

**Issue by wizzup** [commercialhaskell/stack#3584]
### General summary/comments

Lots of templates listed from `stack templates` provide no description, so I have some research and found [stack-templates](https://github.com/commercialhaskell/stack-templates) repository.

I think that others might want to know abot it. Forgive me if it was in documentation somewhere already, I can't find any.

I think the best place to mention the repo would be when running

    stack templates --help

**Comment by mgsloan** [comment]
This seems reasonable to me, feel free to open a PR adding a mention of this.
