### ISSUE TITLE
Terminal width detection isn't done on Windows

### ISSUE THREAD

**Issue by kadoban** [commercialhaskell/stack#3588]
The terminal width detection (that is used for pretty-printing log/warning/error output) is not done on Windows.

If anyone is interested in contributing that, it should be fairly trivial for the right person. It should go in ```windows/System/Terminal.hs``` and do something similar in function to what is done in ```unix/System/Terminal.hsc```

**Comment by mgsloan** [comment]
@eye942 Approach (1) seems good to me.  I don't think anyone is working on this, feel free to have at it

**Comment by ndmitchell** [comment]
I recommend the terminal-size library which does this in a cross platform manner. It's used in ghcid with much success.

**Comment by snoyberg** [comment]
Fixed by #4797
