### ISSUE TITLE
Offline builds

### ISSUE THREAD

**Issue by davidsiefert** [commercialhaskell/stack#359]
Would it be possible to support offline builds where `stack` commands just rely on cached downloads?  I cannot do any builds while I'm traveling to/from work. :sob: :panda_face:

**Comment by bitemyapp** [comment]
Think we had a ticket before to this effect.

https://github.com/commercialhaskell/stack/issues/316 and
https://github.com/commercialhaskell/stack/issues/297

`--dry-run` and `--prefetch` I think.

Let me know if this solves your problem for you.

**Comment by gregwebs** [comment]
I am trying to cache my dependencies for a continuous integration build. So I tried using `--dry-run` and `--prefetch`, but that is not quite what I wanted: I would like to install the dependencies. So the behavior I really want is the same as `cabal install --only-dep --enable-tests`.

Would it make sense to have a `stack test --dry-run --install-deps` command?

A somewhat related note is that `--prefetch` does not seem useful without `--dry-run`, but this is not enforced.
So one option would be for the behavior of `--prefetch` to be download and install, but when `--dry-run` is given it only downloads.

Another option would be to dedicate a separate top-level command: `stack install-deps`. By default, I usually want to install test dependencies, so it would need a flag to indicate that test dependencies should not be installed.

**Comment by snoyberg** [comment]
Did you see the --only-snapshot flag?

**Comment by gregwebs** [comment]
yes, that is what I was looking for! I can confirm that `--dry-run --prefetch` builds from cached downloads

**Comment by davidsiefert** [comment]
The ```--dry-run --prefetch``` also worked for me.  However, I'm wondering would it be possible to create a new project offline as well?

**Comment by snoyberg** [comment]
How would stack be able to know which build plan and packages to download in advance in that case?

**Comment by davidsiefert** [comment]
I'm wondering if things could be cached from other prior builds at a higher level.  For example, my prior project build has a certain set of dependencies that were downloaded, so if my new project has a subset of those dependencies then what would prevent me from using those artifacts?  If stack is running 'offline', look in the local project cache, if nothing there, goto the next level cache (a user-level cache?), and if missing information then fail.

Doing some experimenting, if I create an empty cabal file (contents of: "") it already goes to the internet to get ```snapshots.json```....  Let me try to prototype what I'm talking about and see what points it fails miserably. :smile:

**Comment by snoyberg** [comment]
It's only `snapshots.json` that gets downloaded each time, since that information is temporal. Packages and indices are cached and shared among projects already.

**Comment by borsboom** [comment]
Potential approach: #3813

**Comment by neerajb1** [comment]
Hi All,

I am very new on ducling using stack. I had installed duckling on windows but don't know to run . Anyone knows how to run it. I am very new to it. Could you please let me know how to run ducling as local host

Thanks in advance

**Comment by bitemyapp** [comment]
@neerajb1 this is the repository for Stack the build tool, not the Duckling project. We can't tell you how to run Duckling, you'll need to ask them.
