### ISSUE TITLE
(windows) stack build fails due to encoding of setup-shim-******.hs

### ISSUE THREAD

**Issue by OlivierSohn** [commercialhaskell/stack#3599]
### General summary/comments (optional)

After installing stack (latest official 64bit installer for windows), when building a package, build fails with an error concerning the encoding of file setup-shim-******.hs which is part of the stack installation. Replacing the content of the file with the content of https://raw.githubusercontent.com/commercialhaskell/stack/2d2fdd7e8d7bfc6cf554c9d22105e99ae414074f/src/setup-shim/StackSetupShim.hs fixes the problem

```shell
--  While building package network-2.6.3.2 using:
      C:\Users\Olivier\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc.EXE --make -odir C:\Users\Olivier\AppData\Local\Temp\stack8692\network-2.6.3.2\.stack-work\dist\ca59d0ab\setup -hidir C:\Users\Olivier\AppData\Local\Temp\stack8692\network-2.6.3.2\.stack-work\dist\ca59d0ab\setup -i -i. -package=Cabal-1.24.2.0 -clear-package-db -global-package-db -package-db=C:\sr\snapshots\aefe70d8\pkgdb C:\Users\Olivier\AppData\Local\Temp\stack8692\network-2.6.3.2\Setup.hs C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs -main-is StackSetupShim.mainOverride -o C:\Users\Olivier\AppData\Local\Temp\stack8692\network-2.6.3.2\.stack-work\dist\ca59d0ab\setup\setup -threaded
    Process exited with code: ExitFailure 1
    Logs have been written to: C:\Users\Olivier\Dev\hs.maze\.stack-work\logs\network-2.6.3.2.log
[network-2.6.3.2.log](https://github.com/commercialhaskell/stack/files/1497638/network-2.6.3.2.log)

    C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs:1:1: error:
        lexical error (UTF-8 decoding error)
```

When opening the file  C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs I could see that the encoding was wrong (the file was not readable in Notepad++, see attached file)

### Steps to reproduce

1. Install stack (latest stable 64 bit installer)
2. git clone https://github.com/OlivierSohn/hamazed.git
3. Run command `stack build`.

### Expected

The build shoud be ok

### Actual

The build failed with error

```
   C:\sr\setup-exe-src\setup-shim-Z6RU0evB.hs:1:1: error:
        lexical error (UTF-8 decoding error)

```
(could not reproduce it once the module was built, the result of the build must have been cached somewhere)

### Stack version

```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e x86_64 hpack-0.17.1
```

### Method of installation

* Official binary, downloaded from stackage.org

[wrong.setup-shim-Z6RU0evB.hs.zip](https://github.com/commercialhaskell/stack/files/1506626/wrong.setup-shim-Z6RU0evB.hs.zip)

**Comment by mgsloan** [comment]
Hmm, it is frustrating that functions like `writeFile` can use the wrong locale.  I imagine that we're running into https://stackoverflow.com/a/28011954 , and should have a custom writeFile

**Comment by snoyberg** [comment]
The code is already using `Data.ByteString.writeFile`, which should avoid character encoding issues. Something else seems to be going on here.

@OlivierSohn I don't see the attached file demonstrating the original file contents.

**Comment by OlivierSohn** [comment]
@snoyberg I updated the issue to attach a .zip containing the file prefixed with "wrong."

I think the original upload failed because the extensions .hs is not supported for upload but I didn't see the error message at the time.

**Comment by snoyberg** [comment]
This doesn't look like a file encoding error, since the entire file consists of nulls. I'm going to guess that the `writeFile` call was interrupted. Can you test what happens if you wipe our `c:\sr` and let Stack rewrite that file?

**Comment by OlivierSohn** [comment]
Yes, after deleting sr and running stack build, the file is written correctly.

I don't recall exactly what I did during installation but it's possible that at some point I had to kill the process since it seemed to be blocked (maybe it was writing the file at that moment).

**Comment by snoyberg** [comment]
It might make sense to try and replace all usages of `writeFile` (in all its variations) in the Stack codebase with a cautious-write variant that does the file rename trick. @borsboom do you think that's a logical thing to do?

**Comment by mgsloan** [comment]
I think that it makes sense for select uses of `writeFile`, but not as much for things like the binary caches.  If those are interrupted, then it will just regenerate them.

**Comment by snoyberg** [comment]
See #4742
