### ISSUE TITLE
Nix doesn't work on Windows

### ISSUE THREAD

**Issue by domenkozar** [commercialhaskell/stack#3600]
Given `stack.yaml`:

```
...
nix:
  enable: true
...
```

The project can't be build on Windows, since stack will try to use Nix also there. While it's possible to use Nix via cygwin or WSL, that's rarely done.

I suggest we disable Nix on Windows (and optionally support forcing it if really wanted).

**Comment by mgsloan** [comment]
I hear that nix on wsl can work - https://www.tweag.io/posts/2017-11-10-nix-on-wsl.html - though noidea if that would work with stack.

IMHO it'd make sense to just not have `enable: true`.  There are a few other stack.yaml options that allow you to break builds for users with configurations different than yours, for example, `extra-lib-dirs`.  Not saying this is ideal, but it's the way things are, currently.  Definitely some interesting tradeoffs between configurability and universality.

**Comment by domenkozar** [comment]
@mgsloan we do default to `false` currently, but that trips people since they forget to pass `--nix` and stack doesn't warn about it. I'd like to make default configuration sane, but Windows prevents that.

**Comment by mgsloan** [comment]
I see!  This is another potential usecase for https://github.com/commercialhaskell/stack/issues/3369

**Comment by mgsloan** [comment]
I've opened a PR, https://github.com/commercialhaskell/stack/pull/3833 which always overrides with `enable: false` on windows.

Previously when I suggested that #3369 be implemented for this, I didn't properly consider that when using WSL it will be built as an ELF binary that thinks it's targeting linux.

**Comment by mgsloan** [comment]
Fixed!
