### ISSUE TITLE
extra-lib-dirs is ignored on OSX, requiring manually setting DYLD_LIBRARY_PATH

### ISSUE THREAD

**Issue by austinvhuang** [commercialhaskell/stack#3603]
### General summary/comments

`extra-lib-dirs` seems to be ignored on OSX. I need to set DYLD_LIBRARY_PATH in the shell for the shared libraries to be visible.

It's slightly unclear whether this is what this particular FAQ question refers to:

https://github.com/commercialhaskell/stack/blob/2c59d33b2231ebd522a4c94377f508fe2da91ce7/doc/faq.md#why-is-dyld_library_path-ignored

For me DYLD_LIBRARY_PATH is not ignored, the problem is that extra-lib-dirs seems to unable to automate the functionality of the DYLD_LIBRARY_PATH environment variable: 

Not being able to specify shared library directory dependencies from stack.yaml causes other problems, for example, I'm unable to launch the ghci repl from intero/spacemacs because of the missing shared libraries.

This is on OSX El Capitan 10.11.5 (15F34).

### Steps to reproduce

1. Use a shared library dependency that located in a directory specified by specified `extra-lib-dirs` and _not_ in DYLD_LIBRARY_PATH

2. Include -l parameter in ghc-options in `stack.yaml`, for example 
```
ghc-options:
  "myproject:" -lmylib
```

3. `stack exec` or `stack test`

### Expected

Shared library is discovered and loaded.

### Actual

From intero:

```
<command line>: can't load .so/.DLL for: /XXX/.stack-work/install/x86_64-osx/nightly-2017-11-22/8.2.1/lib/x86_64-osx-ghc-8.2.1/XXX-1DOtHgcV85WI6SI6J1yOxJ-ghc8.2.1.dylib (dlopen(/XXX/.stack-work/install/x86_64-osx/nightly-2017-11-22/8.2.1/lib/x86_64-osx-ghc-8.2.1/libHSXXX-0.1.0.0-1DOtHgcV85WI6SI6J1yOxJ-ghc8.2.1.dylib, 5): Library not loaded: libEHX.dylib
  Referenced from: /XXX/.stack-work/install/x86_64-osx/nightly-2017-11-22/8.2.1/lib/x86_64-osx-ghc-8.2.1/XXX-1DOtHgcV85WI6SI6J1yOxJ-ghc8.2.1.dylib
  Reason: image not found)

Process intero exited abnormally with code 1
```

Similarly with `stack test` or `stack exec` on the command line:

```
dyld: Library not loaded: libEHX.dylib
  Referenced from: /XXX/.stack-work/dist/x86_64-osx/Cabal-2.0.0.2/build/tests/tests
  Reason: image not found
```
When I add the path manually `export DYLD_LIBRARY_PATH=...` in a shell, the program/test is able to discover the shared library dependency and the issue was resolved. However, this solution is not ideal as it requires manually changing the environment and doesn't help with intero.

I have a linux build as part of my CI which also builds the shared libraries in question and there stack has no problem locating the shared library files, which leads me to think this is OSX specific.
 
### Stack version

```
$ stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e (4861 commits) x86_64 hpack-0.17.1
```

### Method of installation

https://docs.haskellstack.org/en/stable/README/

**Comment by borsboom** [comment]
Stack doesn't do anything anything with runtime dynamic library paths that can be set using environment variables (e.g. `LD_LIBRARY_PATH` on Linux, `DYLD_LIBRARY_PATH` on macOS).  It only manages compile-time library paths, since those have to be set by passing arguments to the linker (there are no system environment variables that can set these paths).

I'd recommend finding a way to make sure DYLD_LIBRARY_PATH is set correctly when Intero is invoked, perhaps by making sure Emacs's environment has it set correctly.
