### ISSUE TITLE
Windows install missing libglib-2.0-0.dll, intl.dll

### ISSUE THREAD

**Issue by 0x6a62** [commercialhaskell/stack#3610]
### General summary/comments (optional)

On Windows 8.1, when running `stack build` I receive modal error messages that the following files are missing (they are not on my machine): libglib-2.0-0.dll, intl.dll. I believe pkg-config.exe crashed due to the error.

Of note, I have another Windows machine where stack runs successfully. I happen to have those 2 dlls on that machine (installed from an unrelated app) in my path. As a test, I copied the dlls over to the failing machine, and the errors went away.  From a personal perspective, I probably have a workaround in the short-term (assuming I'm not inadvertently mixing dll versions).

### Steps to reproduce

Install Windows 64bit from stackage.

```
stack new foo simple
cd foo
stack build
```

### Expected

No error messages.

### Actual

Modal error messages pop up, halting the build until I click OK. Once I do, the build completes successfully.

### Stack version

Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e x86_64 hpack-0.17.1

### Method of installation

Installed `stack-1.5.1-windows-x86_64-installer.exe` from stackage (https://www.stackage.org/stack/windows-x86_64-installer)

**Comment by mgsloan** [comment]
Interesting, thanks for the report!  Seems likely to be an issue with the msys install.  Hopefully in the future the issue can be diagnosed to a cause.  I wouldn't be surprised if deleting the msys install and doing `stack setup` again also resolved it.

**Comment by 0x6a62** [comment]
Thanks for the reply.  I did some more research and realized the problem was on my end; sorry for the false alarm. A different application (Mono) had it's own pkg-config.exe, which was in the path. Once I took it out of my path, things magically started working.
