### ISSUE TITLE
GHC 8.2.2 integer-simple bindist for Windows

### ISSUE THREAD

**Issue by leohaskell** [commercialhaskell/stack#3618]
As the nigthlies are already using 8.2.2, let me provide [the bindist](https://drive.google.com/file/d/1ke3gg5tpHfu29R34SGdg3aqCpF2NaIFS).

**Comment by borsboom** [comment]
Mirrored and added to the metadata in https://github.com/fpco/stackage-content/commit/7773ed2b3eaec09d91ef1b3a4fe0ebf876296747

**Comment by pjljvandelaar** [comment]
I get
```
PS C:\TorXakis> stack test
Downloaded lts-12.8 build plan.
No setup information found for ghc-8.4.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'windows64-integersimple'.
Supported versions: ghc-7.8.4, ghc-7.10.1, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
```
Did I do something wrong? 
Or should a bindist for ghc-8.4.3 still be made?

**Comment by leohaskell** [comment]
@pjljvandelaar, you are getting this, because there isn't an integer-simple 8.4.3 bindist yet.
I'll try to build such one soon, but if you're in a hurry, here is how I build those bindists:

```bash
stack setup
stack install alex happy
stack exec --no-ghc-package-path bash # the --no-ghc-package-path is important!

pacman -Syuu
pacman -S --needed git tar binutils autoconf make \
  curl libtool automake python python2 p7zip patch \
  mingw-w64-$(uname -m)-gcc mingw-w64-$(uname -m)-python3-sphinx

./configure --enable-tarballs-autodownload

# copy the mk/build.mk.sample to mk/build.mk and add INTEGER_LIBRARY=integer-simple

make
make binary-dist
```

I hope that I haven't missed something.
