### ISSUE TITLE
Solving many compilation problems related to gi-gtk on Windows

### ISSUE THREAD

**Issue by bigos** [commercialhaskell/stack#3619]
Please provide your comments on my approach to using stack on Windows.

I have Instatalled and updated MSYS2 and installed gtk libraries needed for my project. Later I have installed Haskell core platform that comes with stack and cabal. The installation destination folder was on a path WITHOUT SPACES. After that I have modified global stack configuration and added to it the following line:
`skip-msys: true`
Also I have modified cabal user-config file and stack.yaml file

```
extra-prog-path:
- C:\Users\Jacek\AppData\Roaming\cabal\bin
- c:/msys64/mingw32/bin
```

```
# Extra directories used by stack for building
extra-include-dirs:
- c:/msys64/mingw64/include
extra-lib-dirs:
- c:/msys64/mingw64/lib
```
The cmd script that starts my stack terminal has following set
```
SET PATH=C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%
set XDG_DATA_DIRS=c:/msys64/mingw64/share
set PKG_CONFIG_PATH=c:/msys64/mingw64/lib/pkgconfig
set INCLUDE=c:/msys64/mingw64/include
set HASKELL_GI_GIR_SEARCH_PATH=c:/msys64/mingw64/share/gir-1.0
```
Also I have added these to my stack.yaml file.

```
resolver: nightly-2017-12-01

# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps:
- gi-gtk-hs-0.3.5.0
- gi-gdk-3.0.14
- gi-gdkpixbuf-2.0.14
- gi-gtk-3.0.17
- gi-gio-2.0.14
- gi-pango-1.0.15
```

Please let me know if I am going in the right direction. I have tried it on a VM downloaded from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ . It seems I was able to go past this error https://github.com/commercialhaskell/stack/issues/3154. I did not understand the solution presented there so I have tried my own solution. Please can someone verify if I am going in the right direction.

**Comment by bigos** [comment]
Premature joy :-(. It doesn't work on the other machine.

**Comment by bigos** [comment]
https://mail.haskell.org/pipermail/haskell-cafe/2015-October/121980.html perhaps this will help tomorrow.

**Comment by mgsloan** [comment]
I do not see anything particularly wrong with this setup.  However, it seems much more complicated than what should be needed.  It should be sufficient to just install stack and run `stack setup`, and it will correctly setup msys for you

**Comment by bigos** [comment]
I will try and let you know the results.

**Comment by bigos** [comment]
it did not work
```
    Could not resolve symbol "cairo_gobject_context_get_type" in namespace "cairo"
    CallStack (from HasCallStack):
      error, called at lib\Data\GI\CodeGen\LibGIRepository.hs:167:8 in haskell-gi-0.20.3-GKLAhZ0MlhlAgwOPj4g0Nq:Data.GI.CodeGen.LibGIRepository
    ** (setup.exe:12348): WARNING **: Failed to load shared library 'libcairo-gobject-2.dll' referenced by the typelib: 'libcairo-gobject-2.dll': The specified procedure could not be found.
```
time to try different approach

**Comment by bigos** [comment]
The problem was with ghc version used. Going back to 8.0.2 seems to solve the problem.

**Comment by mgsloan** [comment]
Interesting!  May be worthwhile to report an issue to ghc.

**Comment by bigos** [comment]
The bug is known and I suppose someone has already reported it.

**Comment by Anrock** [comment]
I'm having same thing on 8.4.3.

**Comment by jokusi** [comment]
And same problem on version 8.8.4.

The problem seems to be stack only. [This](https://github.com/haskell-gi/haskell-gi/issues/234) thread suggests it works on cabal. It links to issue #4886, where we can find a "solution" which actually works (at least for me), but that solution is more of a workarround then an acceptable actual solution. It might even cause other problems. I guess there is a reason for the different zlibs?

I suggest this issue or issue #4886 should be reopend (also duplications links would be nice).
