### ISSUE TITLE
Specify User-Agent to get over my company's firewall

### ISSUE THREAD

**Issue by igrep** [commercialhaskell/stack#3628]
# Problem

My colleagues and I are using stack behind a (weirdly) strong firewall, which denies http requests whose User-Agent header and the destination URL match with the preset white list, since the recent change by the infra team.
So I asked the infra team to add stack and s3.amazonaws.com (and so on) to the white list, but he declined because stack accesses to various domains without any User-Agent header!!

# Solution

If you don't have a problem, I'll make a PR to add some User-Agent header (["The Haskell Stack" looks good](https://github.com/commercialhaskell/stack/blob/2d9721356270e11a37add59b772bde7174ebeb67/src/Network/HTTP/Download.hs#L115).
So can you tell me where I should fix?

# Version of stack I'm using

```
> stack --version
Version 1.5.1, Git revision 600c1f01435a10d127938709556c1682ecfd694e x86_64 hpack-0.17.1
```

**Comment by mgsloan** [comment]
Sure, this would be an appreciated PR!  There are a fair number of places that do downloads.  Searching for `Network.` should turn up most of the modules that do web requests.

**Comment by igrep** [comment]
Now I'm trying to which functions to wrap.
Then, I have a question: Shouldn't I touch `Hackage.Security.Client.Repository.HttpLib.HttpClient`?
Because that module said to be copied from the other. So is it better to keep as is?

**Comment by mgsloan** [comment]
@igrep You might need to make some changes to hackage-security itself, I'm not sure if it sets user-agent.
