### ISSUE TITLE
stack 1.6.1-rc1 with -jN fails after N packages build with N x "openBinaryFile: doesn't exist

### ISSUE THREAD

**Issue by ruomad** [commercialhaskell/stack#3629]
I'm running stack -jN on windows 64bit 
it fails after N successfully built packages with N errors like : 

```
Progress: 14/52C:\Users\XXX\AppData\Local\Programs\stack\x86_64-windows\root\precompiled\x86_64-windows\ghc-8.2.2\2.0.1.0\cmVnZXgtdGRmYS0xLjIuMkBzaGEyNTY6MGEyZjY5N2E0YTExNmYxMmFiMjYzMDk1MzcyZmY1M2VkMmVhZTVlMTgzYmQwZjZiNzUzYmJlOTVmMTg0YThjYSwzMDgz\4eF6xk9yvpsnNgtCqiVJdL0RXSz-nATQXHOLD0A44HI=: openBinaryFile: does not exist (No such file or directory)

C:\Users\XXX\AppData\Local\Programs\stack\x86_64-windows\root\precompiled\x86_64-windows\ghc-8.2.2\2.0.1.0\dmVjdG9yLTAuMTIuMC4xQHNoYTI1NjowYjgzODA3MTQ0OTAyMTA0MGI0MzY2MjAxZWI1ZTUxNzkwYTg5NDZhMWI4NWMzMGQ4MjNiZjU2OTBlNDI1YmY2LDcwNzM=\1Bg9r_zZlzDyieViOKgxRvpM04EiQA0FKe2DNhLiz18=: openBinaryFile: does not exist (No such file or directory)

C:\Users\XXX\AppData\Local\Programs\stack\x86_64-windows\root\precompiled\x86_64-windows\ghc-8.2.2\2.0.1.0\emxpYi0wLjYuMS4yQHNoYTI1NjphMGFjMmI2NTBlYzNjMzhmZjA0MWU0ZGE1YTNiNjk2OWMxY2E2OGE3MzBmY2Q5NWQ5ZWQ3ODI5NDMwNWM2NzY4LDQxMjE=\uCvt9dqb3LAG64VPb-b3ZXW6ZWwk2naKoO4P3lMMfyI=: openBinaryFile: does not exist (No such file or directory)

C:\Users\XXX\AppData\Local\Programs\stack\x86_64-windows\root\precompiled\x86_64-windows\ghc-8.2.2\2.0.1.0\dW5peC1jb21wYXQtMC41LjAuMUBzaGEyNTY6YjI1MDY2ZmIzNjM1YmExNTdhZTJiYTZiODYwNzU3N2E4MWRmZDUwYzg5MGU3ZDg0ZjYwYzk2MjFiMGMzMGJhYSwxOTQz\pSpozZxcghowRQtp_lLjbi1bLxPNAOYb0Hp54bsYqsA=: openBinaryFile: does not exist (No such file or directory)
```

**Comment by borsboom** [comment]
Does this happen if you use `-j1`?

It looks like those paths all exceed 260 characters, which is the maximum path length on Windows when using the old Windows API (which are what GHC's base libraries, and therefore Stack, Cabal, and GHC, use).  Try setting the `STACK_ROOT` environment variable to a short path like `C:\sr`.

**Comment by ruomad** [comment]
yes, it fails in the same way after 1 successfull build
Actually it's not that consistent for n>4 (Irun a quad core), it sometimes fails before N
And I'll test what you suggest but I why are there so long paths ? If I launch stack again after failure it works for N more packages so I end up building the whole thing successfully, but it's quite annoying

**Comment by borsboom** [comment]
I believe those long strings of random-looking characters are generated by Cabal (@snoyberg please correct me if I'm wrong).  The path length issues are a longer-standing problem on Windows, and the true fix is to make GHC base libraries support longer paths on Windows.  In the meantime, a workaround is to set STACK_ROOT to a shorter path (the Windows installer offers to do this for you).  Did you try a shorter STACK_ROOT?

**Comment by ruomad** [comment]
yes it must be what you say, because with a short path it doesn't fail.
Guess I'll have to live with that then until the fix is implemented
Anyway it didn't happen so consistently with previous versions of stack (it did fail quite offen though but with a "permission denied" error if I remember correctly)

**Comment by ruomad** [comment]
Anyway it fails again but with "unsatisfied constraints (non-empty directory) which seems to be a different problem (and happened before)
Still works and completes full build after a few fails / restarts so it's not somuch of a problem even if it's annoying

**Comment by borsboom** [comment]
Yeah, the "permission denied" is a different upstream issue (also Windows-only).  I'm really hoping the base libraries are fixed someday soon, but I'm not holding my breath... this has been a known issue for _years_.

**Comment by ruomad** [comment]
OK thanks ! I'll manage with the current status for the time being, it's still usable (and very nicely apart these errors)

**Comment by ruomad** [comment]
for the record, --keep-going is a very handy workaround
