### ISSUE TITLE
Building of telegram-api in dependencies runs out of memory

### ISSUE THREAD

**Issue by viviag** [commercialhaskell/stack#3637]
```
$ stack --version
Version 1.6.1, Git revision f25811329bbc40b0c21053a8160c56f923e1201b (5435 commits) x86_64 hpack-0.20.0
```
I'm building package with [telegram-api](https://github.com/Velrina/haskell-telegram-api) in dependencies. It runs out of memory and take a lot of time (such I've never seen it ended) while building `telegram-api`. Same thing with `--fast`.
`stack build` on standalone package works with memory consumption less than 1G.

With version 1.5.1 everything ends.

**Comment by mgsloan** [comment]
I ran it, and stack has typical memory usage.  GHC uses a fair bit and takes a while to compile.  I took a look at the package, and it has large datatypes and uses generic deriving.

This is not a stack bug.  It would be great if GHC was faster for this, but that's a complex upstream issue.
