### ISSUE TITLE
Feature request: stack init --latest-nightly

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3641]
I usually want to `stack init` with the latest nightly - having stack go back through all the old LTS releases looking for a suitable build plan isn't necessary. Any chance of a `stack init --latest-nightly` which downloads the latest nightly, checks if it is compatible, and if so writes out a `stack.yaml`, otherwise fails? You might also want a `--latest-lts` for those people who think LTS is useful.

**Comment by mgsloan** [comment]
`stack init --resolver nightly` should do the trick!  Please re-open if not.

It is perhaps a bit confusing that it's not in `stack init --help`, but it is mentioned in `stack --help`.  I've opened a ticket for that.

**Comment by ndmitchell** [comment]
Yep, I did `stack init --help` - that confused me a lot. Thanks for the solution!
