### ISSUE TITLE
building a statically linked executable with nix

### ISSUE THREAD

**Issue by wfranzini** [commercialhaskell/stack#3646]
Hi,

I'm trying to build a statically linked executable using stack 1.6.1 and nix, I've created a small project to 
demonstrate how, however I'm stuck with Cabal segfaulting. 

The project is available at https://github.com/wfranzini/stack-nix-static-linking 
Basically I've created a shell.nix file that:
* use a nix provided ghc-8.2.2 with integer-simple support (to avoid gmp);
* use nativeBuildInputs instead of buildInputs to link statically with glibc.static.

I was expecting at most a linking error but got Cabal segfaulting.

`stack build --nix` will show the issue

I'm reporting the problem here since, as I understand, the cabal executable is provided by stack,  Should I report the problem to cabal maintainers?

**Comment by mgsloan** [comment]
That's a compiled version of a simple Setup.hs built with Cabal-1.24.2.0 and ghc-8.0.2.  You can safely remove it to cause it to be rebuilt, which has a small chance of fixing the issue.

**Comment by wfranzini** [comment]
Thanks, it seems ghc with integer-simple is producing broken executables.

**Comment by wfranzini** [comment]
@mgsloan Setup.hs is a dynamic executable linked with host's glibc (2.19) and with libgcc_s from nix's glibc-2.26.  Is it possible to link it as a static executable?

**Comment by wfranzini** [comment]
@mgsloan don't mind, it's enough to add glibc, the shared variant, to nativeBuildinputs. At first it is counterintuitive, but it makes sense since setup.hs is executed during the build phase.

**Comment by mgsloan** [comment]
Interesting!  Would be good to make it so that the environment doesn't have to be just right for it to work.  Alternatively, might be good to add it to the documentation

**Comment by wfranzini** [comment]
Trying to build a real project I've discovered that different package use different flags to select the integer library.
So far I've found `integer-gmp` and `integer-simple`.  I've also found a package (text-format) using gmp conditionally, but teaching it to use integer-simple is beyond my haskell knowledge.

BTW is possible, using stack,  to list flags accepted by dependencies?  To discover `integer-gmp` and `integer-simple` I've consulted the `.cabal` file of each package.

**Comment by mgsloan** [comment]
> BTW is possible, using stack, to list flags accepted by dependencies? 

I don't think so.  I had a related idea a while back: https://github.com/commercialhaskell/stack/issues/2393

Could also potentially fit into "stack show", or, probably less of a fit, "stack query"

**Comment by domenkozar** [comment]
Afaik you'll need to use `musl` instead of glibc to statically link correctly. That's what Alpine linux uses. Good luck! :)

**Comment by wfranzini** [comment]
Hi @domenkozar  

I'm currently using alpine linux in a docker container with ghc-8.0.2, however I'm trying to migrate to 8.2.2 to verify if an intermittent bug related to c_poll has gone away.  ghc-8.2.x is not available on alpine.

**Comment by nh2** [comment]
> Afaik you'll need to use musl instead of glibc to statically link correctly. [...] Good luck! :)

It has been done :)

https://github.com/nh2/static-haskell-nix

Full static link with `musl`, and I managed to build `stack` that way which probably means we can build other projects with lots of dependencies with roughly similar ease.

**Comment by snoyberg** [comment]
It looks like @nh2's static-haskell-nix is the way forward here, closing
