### ISSUE TITLE
How to build Stack from source without having Stack?

### ISSUE THREAD

**Issue by kozross** [commercialhaskell/stack#3659]
I'm trying to set up an Alpine Linux chroot on my rooted Android tablet. Currently, there is no 32-bit ARM build of Stack available for Alpine (according to the official installer), so I decided to try and build it myself. However, I found no instructions for building, nor any ``.cabal`` file in the repo. Is it actually possible to build Stack without Stack, and if so, how does one do that? 

As this currently appears to be impossible, I have to ask why this choice was made - it seems incredibly unfriendly to porting, as well as people in my situation.

**Comment by mgsloan** [comment]
The `.cabal` file is generated via hpack from `package.yaml`, and it's best not to check in generated files (avoid merge conflicts, etc).  You can install hpack as an executable and use it to generate the cabal file.  Then it should be possible to use cabal-install to install stack.

To install using the official versions, should then use stack to build stack.  This is one reason to avoid building with cabal-install , you'll get whatever it chooses as dependencies, which may vary the behavior of stack.  We should probably generate a cabal freeze file, but I don't think there's any tooling for that currently.

**Comment by kozross** [comment]
I would prefer to use Stack to build Stack. However, in my situation this is basically not possible as far as I can tell - there's no official binary (according to the official installer) for 32-bit ARM on Alpine.

**Comment by mgsloan** [comment]
I guess what I mean is the ideal process would look like using cabal-install to build an initial version of stack.  Then, after that, using that stack to build the version of stack with the correct dependency versions.  It probably isn't a big deal, though, it just isn't as certain to have the same behavior.

**Comment by borsboom** [comment]
@kozross: `cabal install stack` should work.  Stack is on Hackage and it has a .cabal file with dependency version bounds there.

**Comment by lwm** [comment]
> there's no official binary (according to the official installer) for 32-bit ARM on Alpine.

You may want to look into the efforts on https://github.com/commercialhaskell/stack/issues/2387.
