### ISSUE TITLE
Error in $.copyright: expected String, encountered Number

### ISSUE THREAD

**Issue by bidhan-a** [commercialhaskell/stack#3660]
Just upgraded Stack to version 1.6.1 and when I do `stack new myproject`, it gives the following error:  `Error in $.copyright: expected String, encountered Number`. It doesn't show this error when I create a new project using the "simple" template however. I'm on a Windows machine.

Any ideas? 

Thanks

**Comment by lwm** [comment]
Hey @bidhan-a, just passing through but it might be related to something that was merged over in https://github.com/commercialhaskell/stack-templates. You can find the file of the template you're using that is showing this error and try to track down from there.

**Comment by mgsloan** [comment]
Also reported here - https://github.com/commercialhaskell/stack-templates/issues/115

@snoyberg @borsboom I've also seen a couple stackoverflow questions where people haven't updated their stack and are confused about the cabal file overwriting behavior.  Maybe it makes sense to revert, and have a better solution for the escaping of copyright?  Alternatively, maybe adding quotes to the template will fix it?

**Comment by snoyberg** [comment]
It seems like putting quotes around the fields is an obvious "yes," is
there a downside? I'd rather try that first and see if it addresses the
concerns before moving away from hpack.

**Comment by mgsloan** [comment]
I think so.  It will not handle escaping properly in the general case (backslashes), but I think it will work for the common case.

**Comment by mgsloan** [comment]
This is now resolved in https://github.com/commercialhaskell/stack-templates/commit/eb21bb92b5e2a21b2bfdfe11f657685927b81f8b
