### ISSUE TITLE
Stack list-dependencies : Bring it under the new ls umbrella command

### ISSUE THREAD

**Issue by psibi** [commercialhaskell/stack#3669]
This [PR](https://github.com/commercialhaskell/stack/pull/3252) introduces new `ls` umbrella sub-command. `list-dependencies` needs to be brought as `dependencies` under `ls`.

Do you folks think, we can remove the existing `list-dependencies` or just deprecate it for the current time being ?

Also I'm assigning the issue to myself, if someone else wants to pickup and do - please let me know. (Edit: It seems I can't assign the issue to myself!)

**Comment by borsboom** [comment]
I think deprecate it for one major version cycle (e.g. keep with deprecation warning in v1.7 and then remove in v1.8), since it's possible people are using this in automation.
