### ISSUE TITLE
Why does PSUpstream contain Location?

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#367]
I'm going through stacks' code, and notice this (in 99d5213a8d46f5acd825cc972da75bdacbb93983):

``` haskell
data PackageSource
    = PSLocal LocalPackage
    | PSUpstream Version Location (Map FlagName Bool)

data Location = Snap | Local
```

I don't know if it's plain wrong or just unfortunately named, but it seems strange that a local package can be represented as both `PSLocal` and `PSUpstream Local`.

**Comment by snoyberg** [comment]
There's two aspects to this:

* The package database that it will be installed into (that's what `Location` is about)
* Where the source code is located. `PSLocal` means it's a directory on the local system, `PSUpstream` means it's in the package index

`PSLocal` implies automatically that it will be installed in the local database. Upstream packages could be installed in either local or snapshot databases.

The naming could definitely be improved here, recommendations welcome.

**Comment by feuerbach** [comment]
How about `InstallLocation`?

**Comment by snoyberg** [comment]
Sounds fine to me. You up for making the change?

**Comment by feuerbach** [comment]
Also, I now see the documentation for `Location`... somehow didn't see it the first time, it'd probably suffice for me.

**Comment by feuerbach** [comment]
Sure.
