### ISSUE TITLE
Add missing Win32 installer for stack 1.6.1

### ISSUE THREAD

**Issue by gbaz** [commercialhaskell/stack#3677]
There's a win32 binary available for download, but the installer link still 404s from https://www.stackage.org/stack

It would be useful to have the installer as well.

**Comment by mgsloan** [comment]
Pinging @borsboom

**Comment by borsboom** [comment]
It seems to be working for me with 1.6.3.

**Comment by mgsloan** [comment]
Yup, works for me too
