### ISSUE TITLE
Upgrade stack in fpco/stack-build image

### ISSUE THREAD

**Issue by jkarni** [commercialhaskell/stack#3684]
### General summary/comments (optional)

The `fpco/stack-build` image still has `stack == 1.5`, despite the fact that the last image was uploaded three days ago. Could it be moved to `stack >= 1.6`?

### Steps to reproduce

```
$ docker run --rm -it fpco/stack-build "/bin/bash"
root@fea1fbae02eb:/# stack --version
```

### Expected

Version 1.6.*

### Actual

```
Version 1.5.0, Git revision 63267f94d7c819cbecc2d59aa259d17240838e43 (4845 commits) 
```

### Stack version

Not relevant

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository
* Via cabal-install
* An unofficial package repository (please specify which)
* Other (please specify)

**Comment by borsboom** [comment]
I've pushed an updated lts-9.20 image with stack-1.6.1, and updated the release process to include ensuring that subsequent Docker images have the most recent release.

**Comment by jkarni** [comment]
Thanks a lot!
