### ISSUE TITLE
allow-newer in global-project doesn't work

### ISSUE THREAD

**Issue by jeiea** [commercialhaskell/stack#3685]
I expected `allow-newer` in `global-project\stack.yaml` affects in all path, but it seems not. Is it expected behavior?

### Steps to reproduce
1. Make the `C:\sr\global-project\stack.yaml` content as the follows.
```
packages: []
resolver: lts-10.0
allow-newer: true
```
2. Run `stack install intero-0.1.23` on the path where `stack.yaml` doesn't exists.

### Expected

```
C:\sr\global-project> stack install intero
WARNING: Ignoring out of range dependency (allow-newer enabled): ghc-8.2.2. intero requires: >=7.8 && <8.2.2
...
```
### Actual

```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for intero-0.1.23:
    ghc-8.2.2 from stack configuration does not match >=7.8 && <8.2.2 (latest matching version
              is 8.2.1)
needed since intero is a build target.

Some potential ways to resolve this:

  * Recommended action: try adding the following to your extra-deps
    in C:\sr\global-project\stack.yaml:

- ghc-8.2.1

  * Set 'allow-newer: true' to ignore all version constraints and build anyway.

  * You may also want to try using the 'stack solver' command.

Plan construction failed.
```

### Stack version

```
PS> stack --version
Version 1.6.1, Git revision f25811329bbc40b0c21053a8160c56f923e1201b (5435 commits) x86_64 hpack-0.20.0
```

### Method of installation

* Official binary, downloaded from Github releases

**Comment by mgsloan** [comment]
See the description of the config files in https://docs.haskellstack.org/en/stable/yaml_configuration/ , you want to edit `C:\sr\config.yaml` instead.

**Comment by letmaik** [comment]
Please re-open. In the error message the user is advised where to put `extra-deps`, and assumes that this applies to the following point. Since that's not the case, this should be added:

Instead of:
```
* Set 'allow-newer: true' to ignore all version constraints and build anyway.
```

It should something like:
```
* Set 'allow-newer: true' in C:\sr\config.yaml to ignore all version constraints and build anyway.
```

**Comment by mgsloan** [comment]
@letmaik Good point!  Re-opening this issue as a problem with the clarity of output.

**Comment by mpilgrem** [comment]
I understand the original issue as this: the online documentation states that non-project-specific configuration options (such as `allow-newer`) can be included in project-level configuration files. However, that is **not** the case for the  project-level configuration file in the `global-project` directory. Non-project-specific configuration options (such as `allow-newer`) in that file are ignored.
