### ISSUE TITLE
stack resolver lts-10.0 error: AesonException

### ISSUE THREAD

**Issue by rimbaudcode** [commercialhaskell/stack#3686]
When I start a new project, I get an `AesonException`:

```
$ stack new hello
Downloading template "new-template" to create project "hello" in hello/ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- hello/hello.cabal

Selecting the best among 12 snapshots...

Downloaded lts-10.0 build plan.
AesonException "Error in $.packages.cassava.constraints.flags: failed to parse field packages: failed to parse field constraints: failed to parse field flags: Invalid flag name: \"bytestring--lt-0_10_4\""
```

I'm using:
* stack Version 1.2.0 x86_64 hpack-0.14.0
* stack installed using Mac's homebrew
* ghc version 8.2.2
* macOS High Sierra 10.13.2 (17C88)

Cheers!

**Comment by kadoban** [comment]
Thanks for the report.

This is actually due to using an old version of stack. 1.2.0 is a few versions back. You'll have to upgrade unfortunately. `stack upgrade` is usually the easiest way.

**Comment by lwm** [comment]
Should we add a warning for this issue? A lot of tickets are being raised. A warning for 1.5.1?

**Comment by rimbaudcode** [comment]
Great! Upgrading `stack` fixed the problem. I'm now running `Version 1.6.1.1 x86_64 hpack-0.20.0` and the `AesonException` is gone.

However, I should point out that, before opening the current issue (#3686), I tried first `stack update`, with no change. Then, I uninstalled `stack` (and related files) and installed `stack` back, with no change either:

```
$ brew uninstall stack
$ trash ~/.stack ~/.cabal ~/.ghc
$ brew update && brew upgrade && brew cleanup && brew prune
$ brew install stack
$ stack new hello
Downloading template "new-template" to create project "hello" in hello/ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- hello/hello.cabal

Selecting the best among 12 snapshots...

Downloaded lts-10.0 build plan.
AesonException "Error in $.packages.cassava.constraints.flags: failed to parse field packages: failed to parse field constraints: failed to parse field flags: Invalid flag name: \"bytestring--lt-0_10_4\""
```

Maybe, the problem is due to an old version being of `stack` served by `homebrew`.

**Comment by lwm** [comment]
Yep - brew probably puts it in /usr/bin and stack puts executables in ~/.local/bin. A `stack upgrade` should have warned about not having ~/.local/bin on your $PATH if that was the case - otherwise, I think the original executable would take precedence?

**Comment by rimbaudcode** [comment]
I think you're right. Homebrew puts stuff in `/usr/local/bin` (https://docs.brew.sh/FAQ.html). In my `$PATH`, that dir is before `stack`'s `~/.local/bin`. So the original executable was being called. However, `stack upgrade` fixed the exception.

**Comment by mgsloan** [comment]
Sounds like the overall issue here is resolved, so closing.

I'm not sure if 1.2.0 was recent enough, but at some point a warning was added to `upgrade` in the case that the destination location is not on your PATH.
