### ISSUE TITLE
Missing changelog entry for 1.6.1.1

### ISSUE THREAD

**Issue by asr** [commercialhaskell/stack#3689]
Note that the [changelog](https://hackage.haskell.org/package/stack-1.6.1.1/changelog) hasn't an entry for 1.6.1.1.

**Comment by borsboom** [comment]
1.6.1.1 has no changes, and is not a "real" release.  It just makes it possible to build Stack with the latest versions of unliftio and smallcheck dependencies.

**Comment by asr** [comment]
You just described the change.

**Comment by asr** [comment]
You just described the change. I suggest to add that chance to the changelog.

**Comment by borsboom** [comment]
5cddf28f44c602090cfcfafcdc6a3206a3e606e0
