### ISSUE TITLE
stack upgrade --source-only gets a warning about using the .cabal file instead of package.yaml

### ISSUE THREAD

**Issue by kadoban** [commercialhaskell/stack#3694]
### Steps to reproduce

1. Run ```stack upgrade --source-only --git-branch v1.6.1.1```
2. Watch the output

```
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading timestamp                                                                            
Downloading snapshot                                                                             
Updating index                                                                                   
Updated package index downloaded                                                                 
Update complete                                                                                  
Populated index cache.    
stack-1.6.1.1: download

Warning: WARNING: /tmp/stack-upgrade22121/stack-1.6.1.1/stack.cabal was modified manually. Ignoring package.yaml in favor of cabal file. If you want to use package.yaml instead of the cabal file, then please delete the cabal file.
```

Note that last warning. It keeps building after that (output removed), but at least that warning is not very reassuring. I'm not actually sure if it'll end up using the correct stack.cabal (generate from the package.yaml) or what it's doing exactly, so I stopped it building there.

Since there is no `stack.cabal` file in the stack repo, I guess it must be generating the stack.cabal file from package.yaml and then getting itself confused somehow? But I'm not sure how that's happening yet. This warning is a bit unfortunate at least.

### Stack version

```
~$ stack --version
Version 1.6.1, Git revision f25811329bbc40b0c21053a8160c56f923e1201b (5435 commits) x86_64 hpack-0.20.0

```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository
and then I assume I've run `stack upgrade` a time or two since then

**Comment by mgsloan** [comment]
Curious!  Certainly worth investigating.  I tried to reproduce it but I'm already on the latest version, and at the moment don't feel like digging deeper.

Could be an issue with hpack itself, and the new modification detection code.

**Comment by kadoban** [comment]
I looked into this a little bit, it seems like what it's doing is *not* using git to get the source code, instead it must be doing something like `stack unpack` does. I can tell because it includes the stack.cabal that has the version bounds on dependencies, unlike the one hpack creates. So yeah, it is modified.

So I'm getting the source code from hackage? It's totally ignoring the version too then of course, so it's actually now installing v1.6.3 for me. Which makes sense since it's not using git, so the branch would have no meaning.

But I'm not following why it's using hackage to get the files to build instead of git like I told it to. Will have to peruse the manpage and make sure I'm actually calling the thing correctly maybe and/or examine the logic it uses to decide where to get the sourcecode from.

**Comment by borsboom** [comment]
The initial upload to Hackage (revision 0) matches what is in the repo (no bounds), but then I update the metadata there to include bounds for the convenience of people who have to bootstrap Stack using cabal-install (revision 1).

@mgsloan / @snoyberg : perhaps `stack upgrade` should always use revision 0 when downloading from Hackage.

**Comment by kadoban** [comment]
@borsboom Ah thanks much, I didn't see that revisions thing, it hides pretty well.

I'm really curious why they chose to not have it modify the tarballs, that just seems like a mistake.

**Comment by mgsloan** [comment]
> So hmm, what should we do about that one exactly?

I think best to just ignore it.  I guess could have a special case to ignore the discrepancy when downloaded from hackage.

I wonder if it's using the stack.yaml from the archive?  Would be nice to support this for hackage packages in general - https://github.com/commercialhaskell/stack/issues/2122

**Comment by borsboom** [comment]
I suppose we could also leave the `package.yaml` out of the hackage sdist, since it'll be out of sync for any revisions.

**Comment by snoyberg** [comment]
This no longer occurs, I think since we no longer check in the `.cabal` files to the Git repo.
