### ISSUE TITLE
"stack upgrade" should overwrite current program location if it's writable

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3708]
I propose that `stack upgrade` should overwrite the current location of the stack executable if possible, and otherwise use the default install location.  Perhaps it should demand to be able to overwrite the executable / invoke sudo if it exists?  Here's why:

Due to the cassava kerfuffle, people keep on needing to upgrade their stacks.  Of the maybe 10 times I've seen people run into cassava's awful choice of flag, and get confused about it, leading to

```
Downloading lts-10.0 build plan Downloaded lts-10.0 build plan.
AesonException "Error in $.packages.cassava.constraints.flags['bytestring--lt-0_10_4']: Invalid flag name: \"bytestring--lt-0_10_4\""
```

, maybe around half of the time I tell them to run stack upgrade and they say it didn't work.  It seems that either most of them are on really old stack, or they ignore the warning that the default install location isn't on the PATH.  For example: https://stackoverflow.com/questions/47962377/cannot-build-a-hello-world-program-with-stack-because-of-flag-bytestring-lt-0-1

The workaround is to put it on the PATH, but maybe we should make "stack upgrade" more reliable.

**Comment by lwm** [comment]
It's true, there are a lot of reports like that.

I always liked the suggestion of: https://github.com/commercialhaskell/stack/blob/8266a06536ecf87a9755e7800a3f4496fb10c61b/etc/scripts/get-stack.sh#L655

We can also add colouring or bigger warnings to make it more visible?

A lot of CLI tools demand that user manage their own `$PATH`.

**Comment by snoyberg** [comment]
I wrote code in the upgrade code path that does exactly this, I just don't remember which version of Stack it went out with... *looks things up*

Commit: 74f4daed07bf977a61912b2e72b52f2ba1e96eff  
Issue: #3232  
PR: #3234 
Released in:  1.6.1

So it seems like we just have to wait for everyone to finish this upgrade cycle.

**Comment by mgsloan** [comment]
@snoyberg Ahh, I thought it seemed familiar.  Great!

**Comment by amigalemming** [comment]
I think it is a bad idea. I maintain multiple versions of stack and called my current executable `stack-2.9.1`. After `stack upgrade` I have two files `stack` and `stack-2.9.1` in `.local/bin` and both are actually version 2.9.3 and the real `stack-2.9.1` is lost.

**Comment by mpilgrem** [comment]
@amigalemming, you are correct, on Linux, Stack's `upgrade` command:
1. puts the latest executable in Stack's 'local-bin' directory, named `stack`; and
2. (if different) changes `<running_executable>` to the latest executable.

I wondered if a new flag would meet your use-case, such that you could command `stack-2.9.1 upgrade --only-local-bin` and skip the second step?

**Comment by amigalemming** [comment]
On Tue, 9 May 2023, Mike Pilgrem wrote:

> @amigalemming, you are correct, on Linux, Stack's upgrade command:
>
>  1. puts the latest executable in Stack's 'local-bin' directory, named stack; and
>  2. (if different) changes <running_executable> to the latest executable.
> 
> I wondered if a new flag would meet your use-case, such that you could command stack-2.9.1 upgrade
> --only-local-bin and skip the second step?

Not really, because I just do not expect that stack-2.9.1 ends up being 
stack-2.9.3 without a warning.

**Comment by mpilgrem** [comment]
@amigalemming, if you expect `<running_executable> upgrade` to fail/do nothing if `<running_executable>` is not named `stack`, the default could be `--only-local-bin` if `<running_executable>` is not `stack` and `--no-only-local-bin` if `<running_executable>` is `stack`.

**Comment by amigalemming** [comment]
On Tue, 9 May 2023, Mike Pilgrem wrote:

> @amigalemming, if you expect <running_executable> upgrade to fail/do nothing if <running_executable>
> is not named stack, the default could be --only-local-bin if <running_executable> is not stack and
> --no-only-local-bin if <running_executable> is stack.

I think I expected that 'stack' would install and overwrite 
.local/bin/stack, only.

If I run 'cabal-3.8 install cabal-install' then 'cabal' is overwritten, 
not 'cabal-3.8'. Ok this would be different, if the executable in 
cabal-install.cabal would be named cabal-3.8.

**Comment by mpilgrem** [comment]
@amigalemming, I think that Cabal (the tool)'s `install` command is more like Stack's `install` (or `build --copy-bins`) command than `stack upgrade`. `cabal install cabal-install` does not 'know' that it is building and installing its own replacement; ditto `stack install stack`.

**Comment by mpilgrem** [comment]
@amigalemming, the version of Stack in the `rc/v2.11` release candidate branch should now behave as you would wish, by default. I'm planning to include this in the coming release of Stack 2.11.1.
