### ISSUE TITLE
bug-reports URL is invalid in stack.cabal: superfluous .git

### ISSUE THREAD

**Issue by Rufflewind** [commercialhaskell/stack#3711]
### General summary/comments

The `bug-reports` GitHub URL in the generated `stack.cabal` is invalid.  It has a superfluous `.git` in the middle.

### Steps to reproduce

Visit: https://hackage.haskell.org/package/stack-1.6.1.1

Click the link to the right of “Bug tracker”.

### Expected

HTTP 200

### Actual

HTTP 404

**Comment by borsboom** [comment]
Duplicate of https://github.com/commercialhaskell/stack/issues/3691

**Comment by borsboom** [comment]
While this has been fixed in `master`, I've now made metadata revisions on Hackage and cherry-picked it into the `stable` branch so that current and future minor versions also have the correct URL.
