### ISSUE TITLE
"stack setup --verbose" should also cause verbose output of GHC configure process if possible

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3716]
See https://github.com/commercialhaskell/stack/issues/3712#issuecomment-354206927

>  It's too bad stack setup --verbose doesn't also cause the GHC configure step to show all output.

**Comment by krisis** [comment]
I can work on this issue if no one is looking into it already.

**Comment by snoyberg** [comment]
Implemented via #3740, thanks!
