### ISSUE TITLE
Protractor Issue with await/asynch.  #Protractor

### ISSUE THREAD

**Issue by KavitaForProtractor** [commercialhaskell/stack#3724]
I am getting an errror : Failed Timeout waiting for asynchronous Angular task to finish after 11 seconds. This is may be because the current application is not an angular application.

//import {browser, element, ElementFinder} from 'protractor';
//import { element } from 'protractor';
var screenshotUtil = require('../utils/screenshot.js');
var HomePage = require('../pageobjects/pageObjects_home');
var Login = require('../pageobjects/pageObjects_SignIn');
var Usage = require('../pageobjects/pageObjects_Usage');
var Dashboard = require('../pageobjects/pageObjects_dashboad');
var testData = require('../testData/testData.json');
var Global = require('../global.js');

describe('Take a closer look button navigate user to User summary page.', function(){

   it('Take a closer look button navigate user to User summary page.', async function(){
   
        
        //browser.get(HomePage.url);
        //console.log("Opening the URL");
        //await screenshotUtil.saveScreenShot(browser,  "Signup"+new Date().toDateString() + '.jpg');
        //browser.sleep(3000);
        //var originalTimeout;
        //originalTimeout = jasmine.DEFAULT_TIMEOUT_INTERVAL;
        //jasmine.DEFAULT_TIMEOUT_INTERVAL = 50000;
        
        await HomePage.sigIn().click();
        await Login.username_txt().sendKeys(Global.EMAIL);
        await Login.password_txt().sendKeys(Global.PASSWORD);
        await Login.next_btn().click();
        //Click on Usage from the bottom shell
        //Tap on Usage Detail as Take a closer look button is not available for now. 
        debugger;
        await Dashboard.usage_menu().click();
        //browser.sleep(7000); 
        //To click on Usage detail
        await Usage.daily_tab_btn().click();
        //browser.driver.sleep(7000);
        //To enable expect statement here to confirm that we are on User summary Page.
        //expect(await Usage.days_month_lbl().getText()).toBe("Saturday, December 31st");
        
        expect(await element(by.class('oeb-usage-date')).getText()).toBe("Saturday, December 31st");
        //done();
        
   });

});

**Comment by kadoban** [comment]
Hi there. Did you end up on the wrong issue tracker? I am not seeing how that question belongs here. Feel free to comment if it does and I missed it.
