### ISSUE TITLE
The specification of old-style extra-deps has been removed from the documentation

### ISSUE THREAD

**Issue by kadoban** [commercialhaskell/stack#3729]
I love the new way to specify fancy extra-deps, but in this transitional period where most people are still using the old style, we really should have the documentation for how that used to work up somewhere, and maybe even a short guide showing how to transition.

It doesn't seem to be available at https://docs.haskellstack.org/en/stable/README/ at all, unless I'm just missing it. I had to go to SO just to remember how it was supposed to work, which is really unfortunate. (never could remember all of the details)

Note: I'm talking about the extra-deps that used to have to be specified in the `packages:` section of stack.yaml

**Comment by borsboom** [comment]
If you click on the bottom-left of docs.haskellstack.org, you can view documentation for older versions.  Perhaps it would be a good idea include a link link directly to the v1.5.1 extra-deps docs from the stable extra-deps docs (similar to what I did [here](https://github.com/commercialhaskell/stack/pull/3725/files#diff-2e69fdb5c4abb5fedfcbdb7acbc2c915R432)).

**Comment by kadoban** [comment]
Ah, thanks. I didn't see that (the dangers of surfing with JS off).

But yeah, I think we should either have something specifically in the new docs about it or prominently link to a likely old version. Especially given #3728, I would think we're going to have quite a few people looking for that syntax for various reasons.

It can go away eventually of course, but temporarily it seems like a good idea to me.

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and that the historical approach to extra-deps was phased out from December 2017 (Stack 1.6.1) and ended in June 2019 (Stack 2.1.1).
