### ISSUE TITLE
stack install "could not resolve directory" in /tmp on OSX

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#374]
On a mac, running the stack install command in /tmp (which is a symlink) gives the error below. It runs normally in a non-symlinked directory.

```
/$ uname -a
Darwin silver 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
/tmp$ cd /tmp
/tmp$ pwd -P
/private/tmp
/tmp$ stack install darcs --verbosity debug
Version 0.1.0.0, Git revision 323415315f44ee9b2d8d7d156de26e4da4050bc8
2015-06-22 15:31:02.92923: [debug] Checking for project config at: /private/tmp/stack.yaml @(stack-0.1.0.0:Stack.Config src/Stack/Config.hs:473:9)
2015-06-22 15:31:02.929727: [debug] Loading project config file stack.yaml @(stack-0.1.0.0:Stack.Config src/Stack/Config.hs:494:13)
Could not resolve directory /private/tmp/darcs
```

**Comment by chrisdone** [comment]
The codepath is here: https://github.com/commercialhaskell/stack/blob/master/src/Path/IO.hs#L39..L82

But it's not apparent to me why this would fail in your case. Do you reproduce the below on your system?

``` haskell
chris@retina:~$ ln -s /tmp/ x
chris@retina:~$ ghci -v0
Prelude> import System.Directory 
Prelude System.Directory> doesDirectoryExist "/home/chris/x"
True
Prelude System.Directory> 
```

**Comment by simonmichael** [comment]
No:
```
~$ ln -s /tmp/ x
~$ ghci -v0
>>> import System.Directory 
>>> doesDirectoryExist "/home/chris/x"
False
```

**Comment by chrisdone** [comment]
@simonmichael Can you replace `/home/chris/x` with your own home directory? ;-)

**Comment by simonmichael** [comment]
Doh, rookie mistake :)
```
>>> doesDirectoryExist "/Users/simon/x"
True
```

**Comment by chrisdone** [comment]
I'm not able to reproduce this example exactly. Let's confirm some things:

1. `/private/tmp/darcs` actually exists. Does `doesDirectoryExist "/private/tmp/darcs"` yield true? And does `/tmp/darcs`?

**Comment by simonmichael** [comment]
No, neither of these exists right now. And.. I'm not able to reproduce the problem now. :( Feel free to close.

**Comment by chrisdone** [comment]
The output here:

```
Version 0.1.0.0, Git revision 323415315f44ee9b2d8d7d156de26e4da4050bc8
2015-06-22 15:31:02.92923: [debug] Checking for project config at: /private/tmp/stack.yaml @(stack-0.1.0.0:Stack.Config src/Stack/Config.hs:473:9)
2015-06-22 15:31:02.929727: [debug] Loading project config file stack.yaml @(stack-0.1.0.0:Stack.Config src/Stack/Config.hs:494:13)
Could not resolve directory /private/tmp/darcs
```

Implies that there was a stack.yaml file in your /tmp and that it referenced a `darcs` directory in the packages list. If that were the case, it'd be correct to say that it can't resolve the directory, if you didn't have a `darcs` directory in /tmp.

**Comment by simonmichael** [comment]
Ah, that makes sense, and I can reproduce it that way. I must have had such a file temporarily as I tried to get it working. Sorry, and thanks for the rapid support.

**Comment by chrisdone** [comment]
No problem. Thanks for reporting!
