### ISSUE TITLE
Should support "--no-project" flag

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3743]
It should be possible to have a `stack build` CLI invocation use a specific build environment unaffected by the user's local or global projects.  Usage of this flag would require specification of a `--resolver` flag.  Alternatively, it could take a resolver as a 

Motivating usecase is making it so that `stack build --no-project --resolver lts-10.1 --copy-compiler-tool intero` works regardless of the user's local or global projects (config.yaml would still apply, though)

**Comment by mgsloan** [comment]
An alternative to this flag that I think I prefer is to:

1. Remove the concept of global project.  It seems to mostly cause confusion.  Big behavior change, though.

2. Stack would be able to run without a project.  If we stuck to similar semantics as stack.yaml this would mean you would need to specify `--resolver`.  One option might be to default to `--resolver lts`, to use the latest lts resolver.  This way you can still do `stack ghci file.hs` without having a project.

**Comment by ncaq** [comment]
Can you stack script in case?

[Script interpreter · commercialhaskell/stack Wiki](https://github.com/commercialhaskell/stack/wiki/Script-interpreter)
