### ISSUE TITLE
Add CLI support for installing latest hackage version of a package

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3744]
See my comment on https://github.com/commercialhaskell/intero/pull/505 for motivation.  It would be nice to have a way to say something like `stack build --resolver lts-10.1 intero-latest`.  This doesn't quite work because `intero-latest` is a valid package name.  I can't seem to think of any good syntaxes for this.  Thoughts?

**Comment by varosi** [comment]
hm, I have tried with that and it works:

> stack build --resolver lts-10.1 intero

**Comment by mpilgrem** [comment]
I am closing because `stack build` does accept packages in the package index as targets: https://docs.haskellstack.org/en/stable/build_command/#target-package.
