### ISSUE TITLE
Stack install fails with hGetBufSome: illegal operation (handle is not open for reading)

### ISSUE THREAD

**Issue by sergey-kintsel** [commercialhaskell/stack#3749]
### General summary/comments (optional)

I am trying to install threadscope-0.2.x with lts-9.x and it fails on
```
/.stack-work/logs/cairo-0.13.4.2.log: hGetBufSome: illegal operation (handle is not open for reading)
```

### Steps to reproduce

1. Run command `stack install cairo-0.13.4.2 --resolver lts-9.21` or `stack install threadscope-0.2.7 ghc-events-0.4.4.0 --resolver lts-9.21`.

### Expected

Suddenly, I'd like it to be installed :-D

### Stack version

```
$ stack --version
Version 1.7.0, Git revision c447ed63b9279d0c7659ac18c63553b9abd36193 x86_64 hpack-0.20.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository (with `stack upgrade ---git` after it)

### System

Ubuntu 16.04

**Comment by mgsloan** [comment]
Hmm, it works fine for me.  Which version of stack?

**Comment by sergey-kintsel** [comment]
```
$ stack --version
Version 1.7.0, Git revision c447ed63b9279d0c7659ac18c63553b9abd36193 x86_64 hpack-0.20.0
```

**Comment by sergey-kintsel** [comment]
@mgsloan 
I did `stack upgrade --git` and now it gives me:
```
Linking /tmp/stack5583/cairo-0.13.4.2/.stack-work/dist/x86_64-linux/Cabal-1.24.2.0/setup/setup ...
    Configuring cairo-0.13.4.2...
    setup: The pkg-config package 'cairo' version >=1.2.0 is required but it could
    not be found.
```
so, it looks like the problem is that I have an unstable stack version. is there a way to downgrade it to 1.6.3? or I need to reinstall it completely?

**Comment by sergey-kintsel** [comment]
anyway, I ran 
```bash
rm -rf ~/.stack
rm -rf ~/.local/bin
```
and then installed stack again using 
```bash
curl -sSL https://get.haskellstack.org/ | sh
```
after that I ran `stack setup`, it installed ghc 8.0.2 for me
`stack --version` gives me `Version 0.1.10.0 x86_64`
and, now I try to run `stack upgrade` and it fails on `Invalid package ID: "array-0.5.1.1 base-4.9.1.0 binary-0.8.3.0 bytestring-0.10.8.1"`
Internet says I can easily fix that with `stack upgrade --git`
but then I'll get to the same unstable version.
the question is: can I somehow pass a commit hash that is tagged as the release one for 1.6.3 to `stack upgrade --git`? also, maybe I do something really wrong, so could you please point me to the mistake?

**Comment by sergey-kintsel** [comment]
ok, so
`curl -sSL https://get.haskellstack.org/ | sh -s - -f` worked.
Thanks for the help!
