### ISSUE TITLE
Stack does not respect ghc-options in user config

### ISSUE THREAD

**Issue by centromere** [commercialhaskell/stack#3753]
The `ghc-options` setting only seems to be respected in the project-specific `stack.yaml` file. When it is in `~/.stack/config.yaml` or `/etc/stack/config.yaml` it is not respected.

### Steps to reproduce

```
% stack --version
Version 1.7.0, Git revision 6b9da26bf17c682a5db583f1a5484d4762467a82 x86_64 hpack-0.20.0
% cat ~/.stack/config.yaml
ghc-options:
  "$everything": "isdfsdf-split-sectionslsdjfhsljdf"
% stack new test
Downloading template "new-template" to create project "test" in test/ ...
% cd test
% stack build
Building all executables for `test' once. After a successful build of all of them, only specified executables will be rebuilt.
test-0.1.0.0: configure (lib + exe)
Configuring test-0.1.0.0...
test-0.1.0.0: build (lib + exe)
Preprocessing library for test-0.1.0.0..
Building library for test-0.1.0.0..
[1 of 2] Compiling Lib              ( src/Lib.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/Lib.o )
[2 of 2] Compiling Paths_test       ( .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/autogen/Paths_test.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/Paths_test.o )
Preprocessing executable 'test-exe' for test-0.1.0.0..
Building executable 'test-exe' for test-0.1.0.0..
[1 of 2] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/test-exe/test-exe-tmp/Main.o )
[2 of 2] Compiling Paths_test       ( .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/test-exe/autogen/Paths_test.hs, .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/test-exe/test-exe-tmp/Paths_test.o )
Linking .stack-work/dist/x86_64-osx/Cabal-2.0.1.0/build/test-exe/test-exe ...
test-0.1.0.0: copy/register
Installing library in /Users/alex/test/.stack-work/install/x86_64-osx/lts-10.2/8.2.2/lib/x86_64-osx-ghc-8.2.2/test-0.1.0.0-LK8fulHuYNc5gAYF1YHqqE
Installing executable test-exe in /Users/alex/test/.stack-work/install/x86_64-osx/lts-10.2/8.2.2/bin
Registering library for test-0.1.0.0..
```

## Expectation

```
stack build --force-dirty
test-0.1.0.0: configure (lib + exe)
Configuring test-0.1.0.0...
<command line>: does not exist: isdfsdf-split-sectionslsdjfhsljdf
```

Note that the [documentation](https://docs.haskellstack.org/en/latest/yaml_configuration/#ghc-options) lists `ghc-options` under the heading "Non-project-specific config".

**Comment by mgsloan** [comment]
Hmm, curious!  I can indeed reproduce the issue.  Guessing the Monoid for the ConfigMonoid does an unconditional override of ghc-options - haven't looked at the code.

PRs of fixes are appreciated!

**Comment by mgsloan** [comment]
I've opened https://github.com/commercialhaskell/stack/pull/3781 to fix the inheritance of ghc-options that apply to categories of packages.  

This does bring up a question, though, what's the expected behavior for having this in your `config.yaml`:

```yaml
ghc-options:
  aeson: -O2
```

And in your stack.yaml

```yaml
ghc-options:
  aeson: -ddump-splices
```

Do we expect `-O2 -ddump-splices` to get passed, or just `-ddump-splices`?

Current implementation is to overwrite rather than combine these flags.  This is also consistent with how flags and ghc-options work with snapshot packages.  So, I'm keeping the behavior there the same.

**Comment by snoyberg** [comment]
Unless I'm mistaken, the original issue is addressed, and there's no clear path forward on other points, closing
