### ISSUE TITLE
Update documentation to use package.yaml

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3755]
From https://github.com/commercialhaskell/stack/issues/3633#issuecomment-355841756

> FYI the section on [Listing Dependencies](https://github.com/commercialhaskell/stack/blob/98c51cafb038bf09b58d5607956fb199d3660735/doc/GUIDE.md#listing-dependencies) still needs updating to reference `package.yaml` instead of the `.cabal`, > i.e: > https://github.com/commercialhaskell/stack/commit/6a091f8dfc7e2d821a2c065517833ecbc5fd0285#diff-4f532e9d254305a02dab50da05285712R318

Also worthwhile to skim the rest of the docs and see if anything needs updating.

**Comment by dukedave** [comment]
Working on this now.
