### ISSUE TITLE
stack upgrade fails if ~/.local/bin/stack is a directory

### ISSUE THREAD

**Issue by godzsa** [commercialhaskell/stack#3767]
I downloaded stack as a part of haskell-platform, and run `stack upgrade`
After running `stack --version` I still get 1.2.0, which won't let me build my project. I get:

```
Error in $: failed to parse field 'resolver': key "resolver" not present
```

**Comment by kadoban** [comment]
Was there an error or warning from `stack upgrade` ? What is your PATH? (ie what does `echo $PATH` output?). What about `which stack` ?

**Comment by godzsa** [comment]
I do have `/home/david/.local/bin/stack/` on my path, `which stack` displays `/home/david/.local/bin/stack//stack` I guess that is good. 
I got these warnings:

```
WARNING: Ignoring unknown field "custom-setup" in package description
No packages found in snapshot which provide a "hsc2hs" executable, which is a build-tool dependency of "stack"
No packages found in snapshot which provide a "hsc2hs" executable, which is a build-tool dependency of "stack"
Missing build-tools may be caused by dependencies of the build-tool being overridden by extra-deps.
This should be fixed soon - see this issue https://github.com/commercialhaskell/stack/issues/595
```

I get this at the end, it might be a problem: 
`/home/david/.local/bin/stack: copyFile: inappropriate type (is a directory)`

**Comment by godzsa** [comment]
I solved this issue with `rm -rf ~/.local/bin/stack` and installing again based on the documentation, which installs it to `/usr/local/bin/stack`. So I had to add it to my path manually again. Although this might be a problem for other users as well, if they install it with haskell-platform and try to update, so please consider solving this issue :)

**Comment by kadoban** [comment]
Thanks, that does look like a problem. I'm not sure the right way to fix it though. The only real way would probably be for `stack upgrade` to completely delete that `~/.local/bin/stack/` directory and then copy in, but that sounds dangerous. It depends what's in there, which we have no way of knowing how important that stuff is to the user.

**Comment by mgsloan** [comment]
> Error in $: failed to parse field 'resolver': key "resolver" not present

I believe this is always an error, no matter the stack version.

While perhaps 
> /home/david/.local/bin/stack: copyFile: inappropriate type (is a directory)

Isn't super clear, this seems like an unusual case.  Also, the upgrade logic for recent stack is much better, so this will be fixed.  Unfortunately, we can't modify the upgrade logic for old stack.

> if they install it with haskell-platform and try to update

Installing stack via haskell-platform is not recommended, generally installing haskell-platform is not recommended because it is a frequent source of broken setups.
