### ISSUE TITLE
Documentation guides are inconsistent (nodify package.yaml vs cabal file)

### ISSUE THREAD

**Issue by EncodePanda** [commercialhaskell/stack#3769]
When reading about stackage recently I found that documentation is not consistent after changes made in `1.6.1`. Two examples:

1.  Complete user  guide [mentions](https://docs.haskellstack.org/en/stable/GUIDE/#files-in-helloworld) default behavior is that cabal should not be modified as it should be derived from `stack.yaml` and `package.yaml`. In [next section called "adding dependencies"](https://docs.haskellstack.org/en/stable/GUIDE/#adding-dependencies) we see this explicitly where we modify `package.yaml` and cabal file is being updated automatically. However in [next section called "listing dependencies"](https://docs.haskellstack.org/en/stable/GUIDE/#listing-dependencies) we are told to modify cabal file.

2. [Quick start](https://docs.haskellstack.org/en/stable/README/#quick-start-guide) only mentions cabal file (no `package.yaml)

I'm happy to provide PR to docs fixing this, just need to know if my intuition is correct and in fact those files need to change

**Comment by kadoban** [comment]
Yep, nicely spotted. The first thing looks like what's being fixed in #3757, but hasn't been merged yet.

The second one I don't think has a PR yet, definitely looks like something that should change if you're interested in doing that.

**Comment by rabbitonweb** [comment]
Yeah, happy to deliver PR. I will take care of it.

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because the specific examples no longer apply.
