### ISSUE TITLE
Allow specification of `color: never` in config.yaml

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3778]
See https://stackoverflow.com/questions/48256095/how-do-i-make-stack-not-pass-fdiagnostics-color-always-to-ghc - currently you can only disable terminal coloring via a CLI argument.  This is because the logger settings need to be setup before loading the config.  However, it may well make sense to do the following:

* Default to no terminal coloring before `config.yaml` is read / project config / etc, unless `--color` is specified.

* Once config.yaml is read, use what it specifies for the rest of execution (unless overridden in project config or the `--color` cli arg)

A bit complicated for something that should be very simple.  Worth it?

**Comment by Lokathor** [comment]
The currently default of always forcing color makes stack borderline unusable with `cmd.exe`, the standard windows command prompt. It's also similarly broken with PowerShell, and any programs that use a cmd.exe or PowerShell process for their terminal (eg: the VS Code terminal).

If you don't want to do the two-stage thing, at least just make the windows build of stack always do `--color never`.

**Comment by kadoban** [comment]
@Lokathor  Is only the output from GHC messed up in cmd.exe and in PowerShell? Or is it any color from stack at all? For example, how's the output from `stack uninstall` ?

(Note: the command is not dangerous, it essentially does nothing except output a helpful message that happens to have some colors in it)

**Comment by mgsloan** [comment]
@Lokathor It seems that colors do work for some users of powershell + ansi-terminal:

* https://github.com/feuerbach/ansi-terminal/issues/19
* https://github.com/feuerbach/ansi-terminal/issues/36

Which version of windows are you on?  From https://github.com/feuerbach/ansi-terminal/issues/12 it seems like you'd have to be on recent windows 10

**Comment by Lokathor** [comment]
@kadoban stack itself doesn't use color, and `stack uninstall` displays perfectly. What happens is that stack is placing `-fdiagnostics-color=always` into its argument list to GHC, and what's worse is that it gets placed after the GHC args from my project.cabal file, so even if I specify `-fdiagnostics-color=never` in my project file it gets overriden by stack.

@mgsloan I am on Windows 7. The ansi-terminal package normally works quite well for me. I can run the demos and they display just fine.  Some ansi-terminal things, like cursor moving commands, will crash a program, but you can set colors all you want with no issues.

**Comment by Lokathor** [comment]
Wait, wait, I take it back a bit, I _have_ experienced a form of the #19 bug with the cmd.exe that runs inside VS Code. `setSGR [Reset]` doesn't always work quite right: If you an an ansi-terminal program with non-reset colors applied that sets the new default for the terminal and then if you try to "reset" it later things stay weird until you open a new shell.

**Comment by mgsloan** [comment]
> stack itself doesn't use color, and stack uninstall displays perfectly

Hmm, so does it use color or not (without giving `--color never`)?

![2018-01-15_1406x106_scrot](https://user-images.githubusercontent.com/22570/34933167-ab7f4464-f98a-11e7-8651-ec3a13c723d1.png)

**Comment by kadoban** [comment]
That sounds really odd. IIRC stack is supposed to be using the same logic to determine if it should use color itself as it uses to decide if it should pass `-fdiagnostics-color=always` to GHC. I'm not really sure why those wouldn't be lining up.

@Lokathor just as a test, what about `stack uninstall --color always` ? Does that have color, or is the output screwed up?

My best current guess is something like: stack is deciding it can and should use color, and it tries to, but the library we're using to do that figures out it's a bad idea, or it does it in a way that the shell ignores and you don't notice, but the the stuff from GHC isn't quite as lucky? Really not sure if that actually makes sense.

**Comment by Lokathor** [comment]
@mgsloan sorry if i was unclear. stack has normally never tried to do colors (or tried and failed to do colors) for me on windows, and when i tried `stack uninstall` for the post above it also didn't use color. Just now I tried `stack uninstall --color always` as suggested by @kadoban and it's still no colors applied (tried both cmd.exe and powershell).

So the only current offender is GHC being told to do colors and somehow producing bad escape codes instead of either colors or nothing at all like should normally happen with the ansi-terminal package.

**Comment by mgsloan** [comment]
Hmm, that is really strange, because as far as I can tell, if stack isn't using color codes then it also won't pass `-fdiagnostics-color=always` to ghc.  Here're the relevant bits:

* Checking if it should supply the flag https://github.com/commercialhaskell/stack/blob/construct-plan-error-improvements-3766/src/Stack/Types/Config.hs#L2009
* Setting `logUseColor` based on `hSupportsANSI` if `ColorAuto` (default) https://github.com/commercialhaskell/stack/blob/construct-plan-error-improvements-3766/src/Stack/Types/Runner.hs#L269

**Comment by Lokathor** [comment]
Yeah, and both stderr and stdout give True for hSupportsANSI on my machine.

But the other weird part is, how is GHC even getting the raw escape sequences into the console? The ansi-terminal package should be sufficiently guarded to prevent that.

**Comment by mgsloan** [comment]
@Lokathor What's happening is that stack isn't sending Cabal / GHC output to the terminal.  Instead it's sending it log files and sometimes displaying it to the user.  It actually has code to strip the color sequences when writing to the log files.  So, GHC's stdout isn't connected to your terminal.  That is probably the root of the issues.

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because Windows Terminal is the default terminal on Windows 11 and freely available for Windows 10.
