### ISSUE TITLE
For ghc >= 8.2, default to -fhide-source-paths

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3784]
See http://hsyl20.fr/home/posts/2018-01-15-ghc-hiding-source-and-object-paths.html .  Makes ghc build output look much nicer.

I see no strong downside, can probably be re-enabled with `-fno-hide-source-paths`.  So, it should come before user-provided ghc-options.

**Comment by ElvishJerricco** [comment]
I'd **much** rather see this made the default in GHC than see Stack do some special stuff and basically reimplement it.

Plus, if it were default in GHC, Stack could drop its existing munging, in favor of just telling the user that if they want the verbosity of paths at all, it might as well be absolute ones.

**Comment by mgsloan** [comment]
We're already doing the munging.  I agree with disabling it where possible and instead using the flag for GHC >= 8.2 .  Here are the gory details of what it currently does: https://github.com/commercialhaskell/stack/blob/fix-category-ghc-options-in-config-yaml-3753/src/Stack/Build/Execute.hs#L1804

**Comment by mauriciofierrom** [comment]
Hello. I would like to work on this, if that's ok.

**Comment by snoyberg** [comment]
Sounds great @mauriciofierrom! I think you'll basically be looking at two parts to this modification:

1. Adding a new config setting to `Config` and `ConfigMonoid` in `Stack.Types.Config` for whether `hide-source-paths` should be passed, with a default of `True`. There are lots of other examples of such configuration values, such as `configHideTHLoading`. This will also need a new entry in the `doc/yaml_configuration.md` docs.
2. Applying this setting when generating the configure options. This would be in `Stack.Types.Build.configureOptsNoDir` (the docs there explain the funny name). The trick would be to add in `--ghc-option=-fhide-source-paths` if the setting in (1) is `True` (the default) AND the actual GHC version is 8.2 or later.

Does that give enough direction to get started?

**Comment by mauriciofierrom** [comment]
Yes, thank you very much!

**Comment by snoyberg** [comment]
Implemented in #4736, thanks @mauriciofierrom!

**Comment by mauriciofierrom** [comment]
Thanks for the great pointers @snoyberg 🙂
