### ISSUE TITLE
Stack fails when run via System.Process

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3785]
Using stack-1.6.3 binary on Windows 64bit, I create a repo as per https://github.com/ndmitchell/weeder/issues/32#issuecomment-357441284, then type `stack init` and `stack build`. After that running `stack query locals` results in:

```
Warning: File listed in test.cabal file does not exist: ChangeLog.md
test:
  path: C:\Neil\temp\weeder-32\
  version: '0.1.0.0'
```

With the `Warning` in Yellow and the `ChangeLog.md` in Blue - how pretty. Running that from `ghci` with `System.Process` gives an exception:

```
C:\Neil\temp\weeder-32>ghci
GHCi, version 8.2.1: http://www.haskell.org/ghc/  :? for help
Prelude> import System.Process
Prelude System.Process> readCreateProcess (shell "stack query locals") ""
ConsoleException 6
*** Exception: readCreateProcess: stack query locals (exit 1): failed
```

So when run without a shell it causes the process to die with `ConsoleException 6`, which is terrible, and breaks [`weeder`](https://github.com/ndmitchell/weeder), and potentially anything else invoking `stack` as a process on Windows.

I suspect this is another case of https://github.com/feuerbach/ansi-terminal/issues/47 bubbling up - and strongly suggest the authors of `ansi-terminal` make their Windows escape sequence code total - I'm going to reopen that bug as well.

**Comment by ndmitchell** [comment]
Still broken - not even an improvement in the error message:

```
C:\Neil\temp\weeder-32>ghci
GHCi, version 8.2.1: http://www.haskell.org/ghc/  :? for help
Prelude> import System.Process
Prelude System.Process> readCreateProcess (shell "stack query locals") ""
ConsoleException 6
*** Exception: readCreateProcess: stack query locals (exit 1): failed
Prelude System.Process> system "stack --version"
Version 1.7.0, Git revision 066e7ce0c0f82dbc914a3e7be51fc356b42df737 x86_64 hpack-0.20.0
ExitSuccess
```

**Comment by mgsloan** [comment]
Darn, well, then I suppose the ansi-terminal issue should be re-opened because it looks like 0.8 doesn't resolve the problem.

**Comment by mpilgrem** [comment]
@mgsloan, does updating the project configuration to `ansi-terminal-0.8.0.1` help?

**Comment by mgsloan** [comment]
@mpilgrem Thanks for looking into this.  I take it there are changes in that version that might fix things?  I don't have a windows computer handy, just user reports of these issues.

**Comment by mpilgrem** [comment]
Yes, `ansi-terminal-0.8.0.1` now assumes that a valid but non-ConHost handle is ANSI-enabled, which I hope will handle redirection of standard output. It also sends the informative error message on any failure to standard error.

**Comment by mgsloan** [comment]
Great, thanks @mpilgrem !  I've updated the build configurations to use those versions.

@ndmitchell Does this resolve the issue?

**Comment by mpilgrem** [comment]
I think it does resolve the issue. I built `stack Version 1.7.0, Git revision cfdd8d7e397a890591ec4ee76f3ee78fbe537c89 (dirty) (5641 commits) x86_64 hpack-0.21.2` using GHC 8.2.2 (see #3797). This code then works as expected on Windows 10 (version 1709) without failing:

```(haskell)
module Main where

import System.Console.ANSI
import System.Process

main :: IO ()
main = do
    setSGR [Reset]  -- Switch on ANSI-enabled stdout, by calling on ANSI

    result <- readCreateProcess (shell "stack uninstall") ""
    print result
```

**Comment by mgsloan** [comment]
Woohoo, thanks @mpilgrem !

Feel free to reopen if it still reproduces with stack build from HEAD

**Comment by ndmitchell** [comment]
Confirmed, this resolves the issue (sorry for the delay!)
