### ISSUE TITLE
Adjust `-i` paths used by ghci to point to autogen / etc files generated by newer Cabal

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3791]
I think this change was introduced in `Cabal >= 2`.  `stack ghci` currently adds `dist/build/autogen` and similar dirs to the source search path.  Cabal's per component build instead puts them in `dist/build/$COMPONENT/autogen`.

**Comment by gahag** [comment]
This also affects flycheck for emacs. It reports it can't find autogen modules, as stack ghci does. Downgrading the resolver from lts-10.3 to lts-9.21 seems to be a temporary solution.

**Comment by mgsloan** [comment]
@gahag I've opened a PR which fixes this - https://github.com/commercialhaskell/stack/pull/3795

**Comment by dbaynard** [comment]
Is this supposed to fix `stack ghci` for libraries with internal library modules? (If not, I'll open a new issue).

**Comment by borsboom** [comment]
@mgsloan Does this still need to be a blocking issue?  Hoping to get 1.7 out the door before too long.

**Comment by mgsloan** [comment]
I think it would be good to merge https://github.com/commercialhaskell/stack/pull/3795 before the release.  Shoudla merged it earlier for more testing, but hey.  I've pushed a rebased version, will merge after that passes CI.
