### ISSUE TITLE
Alternative to "global-hints" result from stack query?

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3796]
I merged https://github.com/commercialhaskell/stack/pull/3761 without properly considering the `global-hints` field.  We should be sure we want this to end up in a release.  Perhaps have a `configuration.packages` result instead?

**Comment by borsboom** [comment]
@mgsloan Does this still need to be a blocking issue?  Hoping to get 1.7 out the door before too long.

**Comment by mgsloan** [comment]
@borsboom Since the output of `stack query` is yaml, I've added code to insert a yaml comment indicating that `global-hints` is experimental.  Downgrading this to P2
