### ISSUE TITLE
Docs: The Debugging section could use some love

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#3798]
I'm not completely happy with:

https://docs.haskellstack.org/en/stable/GUIDE/#debugging

The problem is that it only explains what the various flags do in terms of other flags.  That's somewhat useful, but only if you know what the other flags mean.

And in effect, it's hard to get useful information from that section without reading the GHC manual, and then the GHC manual is using different concepts.  So should the cabal manual be read instead? Too many turtles for no good reason.

What's needed?

The various profiling flags should *at least* describe their actual effects such as "executable-profiling" will not compile dependent libraries with profiling, but only executables.

Also, describe why and if libraries are recompiled when these flags are used.  Why stack recompiles everything when switching profiling on and then off again (when it should have had the old stuff already compiled) should be explained.

**Comment by mpilgrem** [comment]
The corresponding URL in 2024 is https://docs.haskellstack.org/en/stable/debugging/.
