### ISSUE TITLE
Fails to parse the output of cabal 2.0.0.1

### ISSUE THREAD

**Issue by BlackCapCoder** [commercialhaskell/stack#3799]
`stack solver` fails with the following error message:
```
Using configuration file: stack.yaml
Using cabal packages:
- ./

Using resolver: nightly-2018-01-21

Warning: Installed version of cabal-install (2.0.0.1) is newer than stack has been tested with.  If you run into difficulties, consider downgrading.
         
Using compiler: ghc-8.2.2
Asking cabal to calculate a build plan...
Trying with packages from nightly-2018-01-21 and 2 external packages as hard constraints...
The following lines from cabal-install output could not be parsed: 
fibonacci-0.2.0.1 (via: algos-0.1.0.0 algos-0.1.0.0 algos-0.1.0.0) (new
package)
infinite-search-0.12 (via: algos-0.1.0.0 algos-0.1.0.0 algos-0.1.0.0) (new
package)
CallStack (from HasCallStack):
  error, called at src/Stack/Solver.hs:173:16 in stack-1.6.3-29yGLWFZzMc4kc0GGcUpok:Stack.Solver
```

Cabal correctly identifies the packages that I want, and stack can indeed build the project if I add them to the extra deps manually, stack just fails to do so automatically.

### Stack version
```
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0
```

**Comment by mgsloan** [comment]
Thanks for the report!  This is a known issue - https://github.com/commercialhaskell/stack/issues/3453 .  Really ought to be fixed, but it isn't a very urgent pain point because I, and likely most others that work on stack a lot, don't use the solver much.  So yeah, that component of things is falling behind.  Workaround for now is to have cabal-install 1.24 installed instead, but I suppose that won't handle some of the newer Cabal features.

**Comment by Josef-Vonasek** [comment]
```
stack install cabal-install-1.24.0.2

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for cabal-install-1.24.0.2:
    Cabal-2.0.1.1 from stack configuration does not match >=1.24.2 && <1.25  (latest matching
                  version is 1.24.2.0)
    process-1.6.1.0 from stack configuration does not match >=1.1.0.2 && <1.5  (latest matching
                    version is 1.4.3.0)
needed since cabal-install is a build target.
```

**Comment by mgsloan** [comment]
@Josef-Vonasek Sorry for the delay in response.  Here's what I did to figure out how to install cabal-install:

* I visited https://www.stackage.org/package/cabal-install/ and clicked "see all snapshots"
* Text search for `1.24`, and found that `lts-9.21` was the most recent snapshot with old cabal.
* `stack install --resolver lts-9.21 cabal-install`.  I have not tested this, but should work.

**Comment by dadepo** [comment]
Hit this issue while walking through the[ Existing projects section](https://docs.haskellstack.org/en/stable/GUIDE/#existing-projects) of the user guide.

Perhaps:
1. Mention this issue in the user guide?
2. Have the main issue fixed? (That will be ideal!)
3. Or do nothing about this and leave it as an exercise for the reader? :)

If the preferred option is 1, then I can help update the docs. 
If the preferred option is 2, then maybe my future self, after more Haskell experience can help with this
If the preferred option is 3, then we have a noops situation in our hands :)
