### ISSUE TITLE
LANG and GHCi via `stack repl`

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#3802]
Per: https://www.reddit.com/r/haskell/comments/7s4yrv/i_figured_out_how_to_display_chineseunicode_in/dt3cv3t/

Is `LANG` getting passed to ghci from the enclosing environment when `Stack` executes it? GHCi isn't defaulting to a UTF-8 encoding when initiated via Stack.

**Comment by bitemyapp** [comment]
```
Prelude> :! env | grep LANG
LANGUAGE=en_US
GDM_LANG=en_US
LANG=en_US.UTF-8
```

from `stack ghci` but I don't know if that's representative of what `ghci` receives or not.

**Comment by mgsloan** [comment]
Based on the code [here](https://github.com/commercialhaskell/stack/blob/2631803b/src/Stack/Setup.hs#L1727) and [here](https://github.com/commercialhaskell/stack/blob/2631803b/src/Stack/Setup.hs#L1691), stack does indeed set the LANG variable but only if LANG / etc variables aren't already specified in the outer environment.  So, it should work.

**Comment by bitemyapp** [comment]
Seems that way to me as well, wanted to double-check. I'll assume they had something weird going on on their computer.

Sorry for the distraction!
