### ISSUE TITLE
LTS-6 broken by new semigroupoids revision

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/stack#3803]
My package `xlsx` was using last LTS 6 in Travis and yesterday new build go broken because of new revision of `semigroupoids` package (see https://hackage.haskell.org/package/semigroupoids-5.0.1/revisions/ ). The error was:
```
Error: While constructing the build
plan, the following exceptions were
encountered:
In the dependencies
for semigroupoids-5.0.1:
    tagged-0.8.4 from stack
                 configuration does not
                 match >=0.8.5 && <1
                 (latest matching
                 version is 0.8.5)
needed due to xlsx-0.6.0
               -> semigroupoids-5.0.1
```
Full Travis log is at https://travis-ci.org/qrilka/xlsx/jobs/332505589

Bumping versions of `tagged` and `transformers-compat` resolves the problem - see https://github.com/qrilka/xlsx/commit/d6c93402f39334938c72385c184755ac02eebf04

Doesn't `stack` pin revisions so packages won't get broken?

**Comment by phadej** [comment]
in https://github.com/fpco/stackage/issues/3185#issuecomment-356523896 @mgsloan said that LTS-6 has pinned versions.

**Comment by DanBurton** [comment]
How odd. I'm not able to reproduce.

```
$ cat stack.yaml
resolver: lts-6.35
packages: []
$ stack build semigroupoids --dry-run
```

On my machine, this constructs a valid build plan without complaining about the fact that it is using tagged-0.8.4.

Could you add `stack --version` to your travis script? Is it possible that it is using a cached, old version of stack? Or is it really that the way your script is calling stack is hitting some weird corner case bug in stack?

**Comment by qrilka** [comment]
I could not reproduce it that way too, as for the version - Travis downloads the latest, see - https://travis-ci.org/qrilka/xlsx/jobs/332740178#L512
As for the script I think I use nothing unusual - Travis script is taken from the stack docs.

**Comment by qrilka** [comment]
In the end I've just merged that commit above, feel free to close this issue if it couldn't be reproduced other way

**Comment by DanBurton** [comment]
I attempted to emulate the original environment more closely:

```bash
$ git clone git@github.com:qrilka/xlsx
$ cd xlsx
$ git checkout e3774a62a0762affaa1129e9b83efdec372408a6
$ stack --no-terminal --skip-ghc-check --stack-yaml=stack-lts-6.yaml test --only-dependencies --dry-run
```

But it still constructed a valid build plan without error.

**Comment by qrilka** [comment]
So it looks like something related to Travis, probably even for this Travis project but I'm not sure how to investigate it properly. Do you think @DanBurton it's worth to do it?

**Comment by DanBurton** [comment]
I don't think it's worth it. My opinion is that we can wait and see if any similar bug reports come in before attempting to investigate further.

**Comment by Ferdinand-vW** [comment]
I ran into the same problem when compiling a project (which does not use Travis) in Ubuntu LTS 16.04.
The following version of stack was installed at that time: 0.1.10.0 x86_64
After upgrading stack to version 1.6.3 the problem went away and I could compile the project.

**Comment by qrilka** [comment]
Looks like it doesn't make sense to investigate this Travis quirk further
