### ISSUE TITLE
Github repo comes up in search results instead of official readthedocs website

### ISSUE THREAD

**Issue by MaxGabriel** [commercialhaskell/stack#3804]
### General summary/comments

This is low-priority, and the source code in Github helpfully has a big warning pointing you to the real docs, but is there some reason that the official docs don't seem to show up in google results? The main annoying thing about this is that when you click on the link from the Github source code page, it redirects you to the home page of the docs, so you then have to re-find what you were looking for.

### Steps to reproduce

For example:

1. Google something about Stack, e.g. "stack custom package flags"

### Expected

The official docs website is the first result

### Actual

The github repo is the first result. The official docs are the 13th result (on the second page)

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because Stack's online documentation does rank quite highly in Google's search results.
