### ISSUE TITLE
local file archive paths in custom-snapshot should be relative to snapshot yaml

### ISSUE THREAD

**Issue by loewenstein** [commercialhaskell/stack#3812]
### General summary/comments (optional)
If I use local file archives in custom snapshots the relative path is resolved against either pwd or project root (difference is hard to tell as I usually call stack from project root).

This is imho unintuitive (or worse) and doesn't help towards reproducible builds.

### Steps to reproduce

For example:
1. Create a new project, e.g. `stack new custom-snapshot simple-hpack`
2. `cd custom-snapshot`
3. `mkdir -p some/path`
4. `touch some/path/archive.tar.gz`
5. Create file `some/snapshot.yml`
```
---
resolver: ghc-8.2.2
name: vendored # For user display only
packages:
- archive: ./path/archive.tar.gz
```
6. Use some/snapshot.yml as resolver
7. `stack build`

Result:
```
23:51 $ stack build
Unable to load cabal files for snapshot
InvalidUrlException "./path/archive.tar.gz" "Invalid URL"
```

If you instead have `./some/path/archive.tar.gz` stack correctly complains about the invalid archive. 

### Stack version

```
$ stack --version
Version 1.6.3, Git revision b27e629b8c4ce369e3b8273f04db193b060000db (5454 commits) x86_64 hpack-0.20.0
```

**Comment by loewenstein** [comment]
The error seems to appear at https://github.com/commercialhaskell/stack/blob/master/src/Stack/PackageLocation.hs#L72. Apparently, `System.Directory.doesFileExist` resolves a relative path against $PWD, which on its own is pretty much what it should do. 
As we don't have a snapshot location in `Stack.PackageLocation.resolveSinglePackageLocation` I suppose we should resolve the relative path relative  to the snapshot yaml much closer to the loading/parsing of the custom snapshot, i.e. in `Stack.Snapshot`. 

@snoyberg @mgsloan WDYT?

**Comment by snoyberg** [comment]
Yes, that makes perfect sense, the current behavior as described is just a
bug. Interested in trying out a PR to fix it?

**Comment by loewenstein** [comment]
@snoyberg in principle yes. Still have to figure out how and where to fix it.
