### ISSUE TITLE
Remove uses of throwString / any other sources of CallStack in non-panic exceptions

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3824]
Currently `throwString` is used in 38 places.  However, it includes a callstack, which I think is ugly for non-panic situations - https://github.com/commercialhaskell/stack/issues/3823 .  Probably better to use `fail`, or potentially add or own utility that directly throws a string.

**Comment by rajcspsg** [comment]
@mgsloan Any update on my previous comment. Can I take this issue to work?

**Comment by mgsloan** [comment]
Hey, sure, that'd be great, thanks!

**Comment by snoyberg** [comment]
@rajcspsg Bumping, were you still planning on working on this?

**Comment by rajcspsg** [comment]
@snoyberg - I'm really sorry. I'm not able to work on this in near future.

**Comment by snoyberg** [comment]
No problem, thanks for the update

**Comment by tjlaxs** [comment]
What would be a panic case? I went through these and I think in every case we pretty much know the state and there is no panic in my understanding. So this would end up being either just a search and replace. And it compiles so I guess it works... just kidding 😄 

Also testing these would turn pretty long in many cases (and maybe pointless). I did a quick Hspec test to see what it would look like with Stack.Upload.uploadBytes:
```haskell
  it "uploadBytes fails without callstack" $ example $ do
    let hc = HackageCreds "a" "b" "c"
        up = uploadBytes "http://hackage.haskell.org/" hc "nonexistent.tar" ""
    catch up (\e -> displayException (e :: IOException) `shouldBe` "user error (Authentication failure uploading to server)")
```
(I did this purely to brush up my exception understanding and also exposed the data constructor for the HackageCreds while doing so for being a bit lazy.)

Would you like a PR without the testing part?

**Comment by snoyberg** [comment]
PR sounds good, thanks!
