### ISSUE TITLE
Have `--prefer-package` option for `stack script`

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#3825]
See https://github.com/commercialhaskell/stack/issues/3823 - there, importing a module that is in multiple packages requires you to list every `--package` explicitly if there is just one ambiguity.  I think it would be nice to instead be able to specify `--prefer-package mustache` or `--prefer-package stache` to just disambiguate that one package without disabling the unambiguously inferred packages.

**Comment by kadoban** [comment]
Would it be sane to just first remove any modules from autosensing that are covered by supplied --package arguments, and then do the autosensing? That way we wouldn't need a separate flag

**Comment by mgsloan** [comment]
Another approach might be to use `{-# LANGUAGE PackageImports #-}` and correctly parse package qualification.  Not sure if the current code does that.  Kinda preferring that, no special flag that way.

Part of the error message improvement in #3823 would be suggesting to use package qualified imports.

**Comment by snoyberg** [comment]
This is already addressed by `PackageImports`, and we can add more hidden packages upstream at Stackage. Closing as wontfix
