### ISSUE TITLE
Workaround for 'cabal/4728' seems to be disabled in 'stack-1.7.0' (while it shouldn't)

### ISSUE THREAD

**Issue by ChShersh** [commercialhaskell/stack#3828]
I'm trying to build `cardano-sl` locally from scratch using GHC-8.2.2 and LTS-10.3 and `stack-1.7.0`. My work is in this PR:

* https://github.com/input-output-hk/cardano-sl/pull/2327

I've ensured that I don't have any `stack` cache problems. So I did:

```
rm -rf ~/.stack
rm -rf .stack-wok
```

Unfortunately, I see this error:

```
$ stack build --ghc-options=" -Wwarn" --test --no-haddock-deps --bench --jobs=4 --no-run-tests --no-run-benchmarks --fast  cardano-sl-crypto

cardano-sl-crypto-1.0.3: build (lib)
Preprocessing library for cardano-sl-crypto-1.0.3..
Building library for cardano-sl-crypto-1.0.3..
<command line>: cannot satisfy -package-id cardano-sl-util-1.0.3-G5HFXANN25G9a0KpoRTcat: 
    cardano-sl-util-1.0.3-G5HFXANN25G9a0KpoRTcat is unusable due to shadowed dependencies:
      cardano-sl-networking-1.0.3-6tqSgFZHWWmH386RlBU8vY
    (use -v for more information)
```

Here is full build log:

* http://lpaste.net/8431203862144090112

AFAIU, it's related to some bug in `ghc-pkg`:

* https://github.com/haskell/cabal/issues/4728

Though, as I understand, `stack` has some workaround for this.

* https://github.com/commercialhaskell/stack/pull/3503

And this workaround should be removed in future:

* https://github.com/commercialhaskell/stack/issues/3554

Though, it seems that this workaround disappeared in `stack-1.7.0` while it shouldn't.
 
Stack version:
```
$ stack --version
Version 1.7.0, Git revision cfdd8d7e397a890591ec4ee76f3ee78fbe537c89 x86_64 hpack-0.20.0
```
OS:
```
$ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

**Comment by snoyberg** [comment]
I was unable to reproduce this issue on my machine. Can you check if `stack clean --full` has any impact?

**Comment by ChShersh** [comment]
@domenkozar I've tried to build with `stack-1.6.3` (which I have currently) and, unfortunately, project doesn't build as well 😞

**Comment by ChShersh** [comment]
`stack clean --full` resolves the issue. Thanks! I tried with both `stack-1.6.3` and `stack-1.7.0`. Everything works fine, it was my mistake.
