### ISSUE TITLE
Multiple flags passed to ghc-options get parsed as one option

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#3829]
Transcripts follow.

One flag, works fine:

```
$ stack ghci --ghc-options="-Wall"           
Prelude> let Just a = Just 1
Prelude> let Just a = Just 1

<interactive>:2:10: warning: [-Wname-shadowing]
    This binding for ‘a’ shadows the existing binding
      defined at <interactive>:1:10
Prelude> 
Leaving GHCi.
```

Multiple flags (one bogus, but reported as one) passed as a double-quoted string:

```
 stack ghci --ghc-options="-Wall -Widentity"
on the commandline: warning:
    unrecognised warning flag: -Wall -Widentity
GHCi, version 8.2.2: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/callen/.ghci
Loaded GHCi configuration from /private/var/folders/hy/dsc_gjcn02z2tn2zmqj8bhnw0000gn/T/ghci73086/ghci-script
Prelude> let Just a = Just 1
Prelude> let Just a = Just 1
Prelude> 
Leaving GHCi.
```

Also note the warning didn't emit this time. Are you meant to invoke `--ghc-options` multiple times for multiple arguments? This doesn't seem prima facie like the argument is getting parsed correctly.

**Comment by mgsloan** [comment]
Yes, this is a known bug unfortunately - https://github.com/commercialhaskell/stack/issues/3315

I have some details there on how to resolve.  Shouldn't be all that hard, want to have a swing at it?  Swamped with other stuff atm.
