### ISSUE TITLE
`stack test` logs missing

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#383]
If I run `cabal test` I end up with a directory `dist/test` with the various test logs in it.

If I run `stack test` this directory/logs does not get created, even though the tests run (and fail).

    stack --version
    Version 0.1.0.0, Git revision c2e5af39679439921570552e3e722f6819f4f4bf

Testing with hspec and cabal configuration for `exitcode-stdio-1.0`. Unfortunately I found this on a private repo, can recreate publicly if needed.

**Comment by snoyberg** [comment]
I believe this is intentional. When running a single test suite, stack does not redirect the output to a file, but instead sends it to stdout so that- when relevant- things like colored output work. I believe the `--no-terminal` flag will prevent this behavior.

**Comment by alanz** [comment]
Ok.

**Comment by snoyberg** [comment]
Just to confirm: does the current behavior work for you?

**Comment by alanz** [comment]
Yes. On deeper investigation the project is using `hspec-jenkins` to generate a `results.xml` file, and this is produced with the expected contents.
