### ISSUE TITLE
stack spins at 100% CPU forever while populating/reading index cache

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#3830]
Not exactly sure if this is a bug or not..

I've noticed that every part of stack that downloads from central repos is super-slow.  So maybe this is by design.  Typical download speeds is around 200kB/s.

But anyways, this is what I'm getting:

```
+ stack build --only-dependencies -j8
Populating index cache ...
Populated index cache.
```

..and it's been sitting there for 70 minutes.

This is on a docker gitlab instance with no cache.  I.e. it's the first priming of the CI build cache.  Still, it's just too slow!

**Comment by alexanderkjeldaas** [comment]
Oh, it's stuck at 100% CPU for the whole time.

**Comment by alexanderkjeldaas** [comment]
A retry continued through this.

But this is something I've seen from time to time.. it must be a bug where `stack` gets into this 100% CPU state and gets stuck.

IIRC this always happens when it's a clean slate - when bootstrapping a new gitlab docker compute instance for example.

**Comment by alexanderkjeldaas** [comment]
No it's always stuck on one CI compute node, and not on others.

**Comment by mgsloan** [comment]
Very curious!  At least it's deterministic.  I wonder what it's doing.  Perhaps somewhere there's a potential for a loop but it only happens under very particular conditions.

**Comment by alexanderkjeldaas** [comment]
if you're on #haskell-stack or there's some other rendezvous, I can organize access.

**Comment by mgsloan** [comment]
Hmm, I unfortunately don't have time for such diagnosis right now :/  I wish ghci had a debugger with a pause button!  Best way to figure out an infinite loop is to just hit the pause button..

**Comment by alexanderkjeldaas** [comment]
I got into this again with a PR that added
`allow-newer: true`
and a few packages.  Downgrading the packages somewhat to remove `allow-newer: true` removed the issue.

**Comment by alexanderkjeldaas** [comment]
How can I investigate this?  Can I run a stack "with debug" on the CI machine, attach to it and print some useful data?

If possible, could you give me the magic commands necessary to do this?

**Comment by Firehed** [comment]
Hi,

I've run into what I think is this issue (or at least something very similar to it) when trying to build and deploy my application inside of Docker. I ran `stack build` through `strace` and after a bunch of incremental progress, saw it spit out these pair of messages for as long as I let it run:

```
open("/root/.stack/indices/Hackage/00-index.tar.gz", O_RDWR|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
rt_sigreturn()                          = 2
open("/root/.stack/indices/Hackage/00-index.tar.gz", O_RDWR|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
rt_sigreturn()
```

There were also tons of `SIGVTALRM`s firing which were filtered out of the above strace output.

That file exists at that location. If I removed the indices directory (`rm -rf ~/.stack/indices`) it was able to proceed past this in a normal amount of time.

Based on that, I'm inclined to believe there's some sort of deadlock occurring when stack tries to open the file.

My dockerfile is (roughly) as follows:

```Dockerfile
FROM haskell:latest as buildenv
WORKDIR /app
RUN apt-get update && apt-get -y install make xz-utils libpq-dev
RUN stack upgrade
RUN stack update && stack setup --resolver lts-11.1
RUN stack build Cabal --resolver lts-11.1
RUN stack build haskell-src-exts --resolver lts-11.1
RUN stack build lens --resolver lts-11.1
RUN stack build aeson --resolver lts-11.1
RUN stack build http-conduit --resolver lts-11.1
RUN stack build servant-server --resolver lts-11.1
COPY stack.yaml .
COPY package.yaml .
RUN rm -rf ~/.stack/indices/ # This was the fix
RUN stack build --dependencies-only
COPY . .
RUN stack build
CMD stack exec my-app
```

The individual packages being built are entirely so Docker layer caching works moderately well and doesn't force a rebuild of absolutely everything when our dependencies change - but we only encountered this issue after adding a new dependency.

```
root@713e6e7ad365:/app# ls -lat /root/.stack/indices/Hackage/
total 1046768
drwxr-xr-x 1 root root      4096 Mar 27 19:49 packages
drwxr-xr-x 1 root root      4096 Mar 27 19:26 .
-rw-r--r-- 1 root root  15045331 Mar 27 19:26 01-index.cache
-rw-r--r-- 1 root root 492711424 Mar 27 19:25 00-index.tar
-rw-r--r-- 1 root root   3473320 Mar 27 19:25 00-index.tar.idx
-rw-r--r-- 1 root root 492711424 Mar 27 19:25 01-index.tar
-rw-r--r-- 1 root root  67905401 Mar 27 19:24 00-index.tar.gz
-rw-r--r-- 1 root root       407 Mar 27 19:24 mirrors.json
drwxr-xr-x 1 root root      4096 Mar 27 19:24 ..
-rw-r--r-- 1 root root         0 Mar 27 19:24 hackage-security-lock
-rw-r--r-- 1 root root      3850 Mar 27 19:24 root.json
-rw-r--r-- 1 root root       969 Mar 27 19:24 snapshot.json
-rw-r--r-- 1 root root       464 Mar 27 19:24 timestamp.json
```

I have an environment that I should be able to get additional debugging info, if it helps.

**Comment by IvanMalison** [comment]
Nice find @Firehed . I was having this issue too, Your fix should be made way more visible. Took me a bunch of searching to find this.

**Comment by alexanderkjeldaas** [comment]
I can verify that I see the same strace output looping forever:
```
open("/home/cibuild/.stack/indices/Hackage/00-index.tar.gz", O_RDWR|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
rt_sigreturn({mask=[]})                 = 2
open("/home/cibuild/.stack/indices/Hackage/00-index.tar.gz", O_RDWR|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
rt_sigreturn({mask=[]})                 = 2
open("/home/cibuild/.stack/indices/Hackage/00-index.tar.gz", O_RDWR|O_CREAT|O_NOCTTY|O_NONBLOCK, 0666) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_timerid=0, si_overrun=0, si_value={int=0, ptr=0}} ---
rt_sigreturn({mask=[]})                 = 2
```

**Comment by snoyberg** [comment]
The codepath for this has completely changed. Can someone see if they can reproduce this against master? Otherwise, I'm going to close

**Comment by alexanderkjeldaas** [comment]
This will not be reproduced in the near future by me unfortunately.

**Comment by tejon** [comment]
FWIW, I can report that `stack-2.1.1` does not appear to have this issue. (This is the same project @Firehed discussed last year.)
