### ISSUE TITLE
Is there a way to "hide" a package from a snapshot?

### ISSUE THREAD

**Issue by kindaro** [commercialhaskell/stack#3835]
There is a [note in the docs](https://docs.haskellstack.org/en/stable/faq/#i-need-to-use-a-different-version-of-a-package-than-what-is-provided-by-the-lts-haskell-snapshot-im-using-what-should-i-do) about using a package of a version different from that in snapshot. There are also ways of adding packages not in snapshot. However, I have a case where it's best to ignore a package from snapshot altogether (due to module name clash), at least until a more integrable solution is prepared. I don't see an option for this. Is it possible, short of patching a snapshot?

**Comment by mgsloan** [comment]
Hmm, do you want it to be hidden for `stack runhaskell` / `stack runghc`?  For those you can do manual package hiding if you want like `-hide-all-packages -package base -package aeson`.  If you want something somewhat more automated, take a look at the hack I describe in https://github.com/commercialhaskell/stack/issues/3338#issuecomment-321719239 .  Ideally this would be wrapped up in a friendlier interface, but not sure what it should look like.

Note that `stack build` and `stack ghci` both use package hiding, so you shouldn't need to hide a package from a snapshot.

Also note that for commands that aren't using package hiding, they will only see packages that have been built + installed, and not every package in the snapshot.  If you just want to remove the conflicting package you can do `stack exec -- ghc-pkg unregister the-unwanted-package`

**Comment by kindaro** [comment]
Yes, the case is such that I have to build and run a handful of source files separately with `stack exec ghc`. I did not even realize that I have a conflicting module name at first, because at `stack build` everything was smooth. Then I discovered that some essential automation (that runs with `stack exec ghc`) is broken after updating snapshot version.

Is it intentional that `stack exec ...` and `stack build` operate differently in the aspect of hiding module name conflicts? How do you see it be in a perfect world?

**Comment by mgsloan** [comment]
Not sure what the perfect world scenario would be.  Specifying package hiding on the CLI isn't so bad.   It would be nice if ghc could take some file that specified a subset of a stack of package DBs, or something like that.

**Comment by soenkehahn** [comment]
@kindaro: Do you know `PackageImports`? That might also help. (https://downloads.haskell.org/~ghc/8.2.2/docs/html/users_guide/glasgow_exts.html?highlight=packageimports#ghc-flag--XPackageImports)

**Comment by snoyberg** [comment]
There is a new field available on `master` called `drop-packages` which allows dropping a package entirely from a snapshot. There is already support for this field in custom snapshots on 1.9.3.
