### ISSUE TITLE
stack init in multi-package project should use local packages for dependency checking

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#384]
For example: if you have two packages foo and bar, and bar depends on foo, `stack init` won't find a matching snapshot since none of them provide foo. Instead, we should include information about the provided local packages.

**Comment by tel** [comment]
Is doing this documented anywhere? The test directory lacks a stack.yaml so I'm not sure how to replicate it.

**Comment by tel** [comment]
Oh, nevermind. It's documented under "multi-package".
