### ISSUE TITLE
How to build stack-1.6.3-linux-arm

### ISSUE THREAD

**Issue by mayeranalytics** [commercialhaskell/stack#3840]
I just built `stack-1.6.3` on `linux-arm` and I want to write up a brief how-to. It may be of use to others.

**Distro**: Ubuntu Xenial (16.04)
**Metal**: C1 instance on [scaleway.com](https://scaleway.com) 2GB RAM + 4GB swap (2GB RAM is very neat, 4GB would be grand). Scaleway's pricing is reasonable, I think (Disclaimer: I have *no affiliation* with them).

Use `stack-1.6.1-linux-arm` as a starting point, install it in `.local/bin`, for example. Don't install any haskell packages via `apt`. If you have, get rid of them.

`stack upgrade --install-ghc` fails with a GHC error, so don't do that. Instead, compile `ghc-8.0.2` manually and install it somewhere. You'll need to `apt install llvm-3.7` beforehand.

Then `stack upgrade --system-ghc` will work fine.

```bash
root@scw-710dff:~# stack --version
Version 1.6.3 arm hpack-0.20.0
```

With the `stack-1.6.3` installed complete the cycle with `stack setup--install-ghc`. For `ghc-8.2.2` you need to `apt install llvm-3.9`.

And that's it.

(Don't try this on a Rasp.)

**Comment by koflerdavid** [comment]
I tried :)

First, it is necessary though to install `llvm-3.9` and to create two symlinks: `/usr/bin/opt` to `/usr/bin/opt-3.9` and `/usr/bin/llc` to `/usr/bin/llc-3.9`.

**Comment by borsboom** [comment]
> C1 instance on scaleway.com 2GB RAM + 4GB swap (2GB RAM is very neat, 4GB would be grand)

I'm so glad to hear this worked for you on Scaleway!  I couldn't get it to work when I tried a year or two ago because of an error from `llvm` due to lack of NEON support on Scalewayt (see https://github.com/commercialhaskell/stack/issues/2103#issuecomment-220727107 and https://github.com/commercialhaskell/stack/issues/2103#issuecomment-226349134).  Sounds like it's time to revisit.

**Comment by borsboom** [comment]
Scaleway worked for me too, using Ubuntu xenial, so now there's a stack-1.6.5 bindist: https://github.com/commercialhaskell/stack/releases/download/v1.6.5/stack-1.6.5-linux-arm.tar.gz

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and because Stack provides binary distributions for Linux/AArch64.
