### ISSUE TITLE
TlsNotSupported HttpExceptionRequest for any command using network when using Arch Linux package

### ISSUE THREAD

**Issue by m0ar** [commercialhaskell/stack#3848]
### General summary/comments (optional)
`stack` refuses to work at all after a fresh install. Everything requiring networking fails with a `HttpExceptionRequest`, ending with `TlsNotSupported`.

### Steps to reproduce
Very unclear what causes this, but stand in a new directory and running `stack new test` or `stack templates`. I am not behind a proxy, nor have any other problems with networking/internet access what so ever. I've nuked my `.stack` folder too so the installation is very vanilla.

### Expected

A new stack setup / list of templates.

### Actual

**Instantly** (no noticeable timeout, everything in one go):

```
$ stack new test
Downloading template "new-template" to create project "test" in test/ ...

Warning: Retry number 0 after a total delay of 0 us
         If you see this warning and stack fails to download, but running the command again solves the problem,
         please report here: https://github.com/commercialhaskell/stack/issues/3510

Warning: Retry number 1 after a total delay of 100000 us
         If you see this warning and stack fails to download, but running the command again solves the problem,
         please report here: https://github.com/commercialhaskell/stack/issues/3510

Warning: Retry number 2 after a total delay of 200000 us
         If you see this warning and stack fails to download, but running the command again solves the problem,
         please report here: https://github.com/commercialhaskell/stack/issues/3510

Warning: Retry number 3 after a total delay of 300000 us
         If you see this warning and stack fails to download, but running the command again solves the problem,
         please report here: https://github.com/commercialhaskell/stack/issues/3510
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/commercialhaskell/stack-templates/master/new-template.hsfiles"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 TlsNotSupported

```

Similarly for `stack templates`:

```
$ stack templates          
Failed to download templates. The HTTP error was: HttpExceptionRequest Request {
  host                 = "api.github.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept","application/json"),("Accept","application/vnd.github.v3+json"),("User-Agent","The Haskell Stack")]
  path                 = "/repos/commercialhaskell/stack-templates/contents/"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 TlsNotSupported

```

```
$ stack <your command here> <args> --verbose
<output>
```

### Stack version

Version 1.6.3 x86_64

### Method of installation

[Archlinux package](https://www.archlinux.org/packages/community/x86_64/stack/)

**Comment by snoyberg** [comment]
Can you try downloading the binary from the releases here on Github and see how it behaves? https://github.com/commercialhaskell/stack/releases/download/v1.6.3/stack-1.6.3-linux-x86_64-static.tar.gz

**Comment by ljwall** [comment]
Hi, I have the exact same issue and also am running Arch and have installed from the Archlinux package.

The linked binary works fine

```
~liam/stack-1.6.3-linux-x86_64-static ➜  ./stack new foobarbaz
Downloading template "new-template" to create project "foobarbaz" in foobarbaz/ ...

The following parameters were needed by the template but not provided: author-email, author-name, category, copyright, github-username
You can provide them in /home/liam/.stack/config.yaml, like this:
templates:
  params:
    author-email: value
    author-name: value
    category: value
    copyright: value
    github-username: value
Or you can pass each one as parameters like this:
stack new foobarbaz new-template -p "author-email:value" -p "author-name:value" -p "category:value" -p "copyright:value" -p "github-username:value"

Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- foobarbaz/

Selecting the best among 12 snapshots...

* Matches lts-10.4

Selected resolver: lts-10.4
Initialising configuration using resolver: lts-10.4
Total number of user packages considered: 1
Writing configuration to file: foobarbaz/stack.yaml
All done.
```

**Comment by borsboom** [comment]
This is also being reported in https://github.com/commercialhaskell/stack/issues/3510#issuecomment-363070343.

@felixonmars It looks like the Arch package upgraded the version of http-client-tls it's build with [yesterday](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/stack&id=16aa88f9e53ae5fad17a35b8bb381c07f7712539), so that's a bit suspicious since it was around then that people started having trouble.

**Comment by borsboom** [comment]
@felixonmars We would also very much appreciate if the Arch package was built without the `hide-dependency-versions` and `supported-build` flags unless you're building the Stack binaries using _exactly_ the dependency versions specified in `stack.yaml` and its snapshot.  It's quite common for bugs to sneak in via dependencies and without that information it's a lot harder to figure out.

**Comment by borsboom** [comment]
Upstream issue for http-client-tls filed: https://github.com/snoyberg/http-client/issues/325

**Comment by borsboom** [comment]
Issue for Arch's `stack` package: https://bugs.archlinux.org/task/57390

**Comment by borsboom** [comment]
Closing this as a downstream issue.

**Comment by felixonmars** [comment]
@borsboom I did disable those flags explicitly since some versions ago: `-f-hide-dependency-versions -f-supported-build`.

As for the above issue, it was actually catched by the test suite, but I overlooked it as I thought it was a temporary network issue. I'll be more careful next time.
