### ISSUE TITLE
Allow for * pattern in source-dirs setting.

### ISSUE THREAD

**Issue by wdanilo** [commercialhaskell/stack#3852]
The idea is very simple. When working on a library I often have some scratch code whcih should eventually become libraries in the future. My project structure have both `src` and `libs` folders in root. In `src` I keep current lib sources, while in `libs` i keep folders with some lib names, that will eventually be extracted in the future to become real libraries. 

Having such structure I will very benefit for being able to write in package.yaml:

```
library:
  source-dirs:
    - src
    - libs/*
```

And not list every folder in libs by hand.

**Comment by wdanilo** [comment]
Oh thanks! So I should rewrite it to Cabal / hpack repo?

**Comment by mgsloan** [comment]
@wdanilo Yep, thanks!
