### ISSUE TITLE
Automatic choice of commit of a Git dependency by Tag

### ISSUE THREAD

**Issue by nikita-volkov** [commercialhaskell/stack#3853]
It is a widely accepted standard to use Git tags to associate the commits with release versions of a package, e.g., https://github.com/nikita-volkov/hasql/releases. 

When dependencies are specified as Git references in Stack, it can be very convenient not to have to provide a specific commit, but to have Stack pick the one that satisfies the Cabal dependency bounds by the release tags of the package.

E.g., if I have a Cabal dependency like `hasql >=0.19 && <0.20`, Stack can automatically derive that the `39a54c7` commit should be installed, which has the tag `0.19.18.2` set on it, which matches the latest version that satisfies the range. More so, in case of failed dependency compilation, Stack can also try all the other tags matching the range.

**Comment by mgsloan** [comment]
Well, stack.yaml files always specify a specific dependency version.  I can see this potentially being useful for `stack solver`, but I have no idea how that would be implemented, it would probably require support from cabal-install.

So while I appreciate the idea, I don't think we are going to implement this as specified.  Note that you can already add git dependencies which use tags to identify the version you are installing.
