### ISSUE TITLE
Nix integration fails with latest nixUnstable

### ISSUE THREAD

**Issue by TerrorJack** [commercialhaskell/stack#3855]
Steps to reproduce:

```
nix-env -iA nixpkgs.bash nixpkgs.nixUnstable nixpkgs.stack
stack --nix --nix-add-gc-roots --resolver ghc-8.2.2 setup
```

It worked previously, but has begun to fail with:

```
Writing implicit global project config file to: /root/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using resolver: ghc-8.2.2 specified on command line
error: unrecognised flag '--indirect'
Try '/root/.nix-profile/bin/nix-shell --help' for more information.
```

In recent versions of `nixUnstable`, the `--indirect` flag is gone. Is it possible to workaround this problem?

Just FYI, a quick round of googling lead to the same issue for other Haskell projects:

https://github.com/NixOS/nix/issues/1830
https://github.com/reflex-frp/reflex-platform/issues/216

**Comment by nh2** [comment]
CC @mboes

**Comment by YPares** [comment]
@TerrorJack Indeed the flag is gone. I'll have a look at the docs to see if it's been replaced...

**Comment by YPares** [comment]
@TerrorJack In the meantime, you can bypass this bug by deactivating the symlink of nix gc roots (this means that `nix-collect-garbage` will remove all you dependencies so beware):
```nix:
    add-gc-roots: false```

**Comment by regnat** [comment]
@YPares @TerrorJack https://github.com/NixOS/nix/commit/19477e8815a7c9b91c82278ec0e22957c97bec16 restores the `--indirect` flag (and ignores it as it is now the default), so this shouldn't be a problem anymore with the latest versions of `nixUnstable` (or won't be once the fix reaches `nixpkgs` if this isn't already the case).

**Comment by YPares** [comment]
@regnat Ok, so we'll be able to remove `--indirect` in the future (but not now because that's not the default in stable nix)

**Comment by mboes** [comment]
@YPares I think we'll want to keep it. It has an effect with past and present Nix, and is the default in future Nix. By keeping it you don't break BC.

**Comment by domenkozar** [comment]
This was fixed in Nix 3 years ago.
