### ISSUE TITLE
valid-wanted is a confusing option name

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#386]
Its behavior also isn't documented in the stack.yaml wiki page.

I think it would be better to name the option after the difference it makes in stack's behavior

**Comment by snoyberg** [comment]
Any suggestions?

**Comment by snoyberg** [comment]
Oh, I think I've got it. The flag should just be dependency. If set to true, it behaves just like an extra-dep.

**Comment by gregwebs** [comment]
yes, `dependency` (or even `extra-dep`) would be much better

**Comment by snoyberg** [comment]
OK, change made, as well as updating the stack.yaml Wiki page:

https://github.com/commercialhaskell/stack/wiki/stack.yaml/_compare/d0c136324d6123820aa0554adc2de392b011760c...ac0c4b9d7cefa8625b3db71686141cf064cd4a89

**Comment by gregwebs** [comment]
Thanks!

**Comment by snoyberg** [comment]
Thanks for pointing out how bad the name was, it was one of those things that just happened, and we have to fix those problems early :)
