### ISSUE TITLE
Stack patching policy

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#3866]
See blog post at https://www.snoyman.com/blog/2018/02/stack-patching-policy

**Comment by tfausak** [comment]
From the linked post, these are the options being discussed:

1. Continue using the officially released upstream version of hackage-security, bugs and all
2. Fork hackage-security on Hackage, and depend on the fork
3. Inline the code from hackage-security into Stack itself, and drop the explicit dependency on hackage-security
4. Include hackage-security via an extra-dep pointing at a Git commit. Our official builds will use the patched version of hackage-security, and anyone building from Hackage will end up with the unpatched version
    1. we can use an extra-dep, but we must ensure that the Stack codebase continues to build against the Hackage version of the package, even if it's missing a bug fix, performance enhancement, or whatever else we wrote
    2. free-for-all: use whatever extra-deps we want, and state that there is no support for building from Hackage alone.

Like Michael, I also lean towards option 4a (shown as 4i in the list above). It seems like most of the situations that require this type of workaround will be bug fixes, which means that working with both the patched and unmatched versions of the packages should be relatively easy.

**Comment by borsboom** [comment]
I'd say 4a is a small tweak to the current situation (not really a radical departure at all).  The main disadvantage there is the same disadvantage that already exists: people using `stack` built with cabal-install may end up with bugs from different versions of dependencies (like we saw in #3848 and others).  The difference is that it may take longer for the upstream bug to get fixed on hackage and so users of binaries built that way (like the Arch Linux package) will be stuck with the bug for longer.  We're currently in a middle ground where we recommend against building Stack with cabal-install, but still make it possible for convenience.

If we were to opt for (4b), which I have to say is very tempting, we'd have to provide a way to bootstrap the build on new platforms (currently we rely on cabal-install, which has its own bootstrap script).  

The other use case for continuing to support building Stack from Hackage is for people that want to use it as a library.  This is not the most common, but there are definitely people who do so.  That said, these people are almost certainly using Stack which means they're actually building from Stackage not Hackage -- but Stackage currently can only source packages from Hackage.  We could potentially split Stack into separate packages for the library and executable, and still upload the library to Hackage but only support building the executable from the source repo (alternatively, add a flag the defaults to _not_ building executables).

**Comment by ElvishJerricco** [comment]
What about option 4b, but with the stipulation that it's only for development purposes? That is, Stack should never make an official release based on dependencies not on Hackage, but it might as well be a free for all between releases, just so that Stack development can continue and users can build from `master` if they so please.

**Comment by wiz** [comment]
What's the point of a working development version if you can't cut a release? The users then would be forced to stick to rolling dev builds because there's always one more bug that can't be fixed right away.

**Comment by mgsloan** [comment]
I see nothing wrong with releasing stack built against a slightly forked dependency.  Building via cabal-install already yields different dependency versions and so yields an executable which may behave differently.  It's good to preserve the property that it's buildable, but it seems pointless to attempt to make any guarantees for this usage.  It is no the recommended way to install stack.

**Comment by snoyberg** [comment]
It seems like there's pretty close to universal consensus here (and elsewhere) that

* 4a is absolutely acceptable
* We should always try to upstream fixes
* 4b _may_ be acceptable in some extreme circumstances, but we should avoid it if at all possible

Since we're already following 4a on master now, I'm going to close this issue as resolved. Thanks for the discussion everyone. If there are further points that need to be addressed, feel free to add a comment.
