### ISSUE TITLE
Allow github shorthand for extra-deps

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#3873]
It's quite common to include an `extra-dep` from Github. The common way to do it, via a `git: https://github.com/...` URL, is actually _not_ the best. It's better to instead use a link to the archive, since this doesn't require downloading the entire Git history, and results in a faster transport. For example, see this commit:

https://github.com/commercialhaskell/stack/pull/3831/commits/638efeaef17a02cb00201bf85d9ef557999ae83f

I'd like to recommend that we add a convenience syntax that does the right thing, namely, replacing:

```
- https://github.com/commercialhaskell/rio/archive/09654f9fcbdcd96d0f5102796b32fdac5da7260e.tar.gz
```

with

```
- github: commercialhaskell/rio
  commit: 09654f9fcbdcd96d0f5102796b32fdac5da7260e
```

Or perhaps even:

```
- github: commercialhaskell/rio@09654f9fcbdcd96d0f5102796b32fdac5da7260e
```

And have this generate the archive link described above.

**Comment by mgsloan** [comment]
:+1:

**Comment by lhcopetti** [comment]
Hello! This is issue is marked as friendly for beginners. Identifying myself as such, I would love to contribute. Are there any time constraints for the resolution of this issue?

**Comment by mgsloan** [comment]
@lhcopetti Great, that'd be much appreciated!

There are no time constraints on resolving this.  If you do want to claim the issue (perhaps have it assigned to you), then it'd be good to have some code for it in a reasonably timely manner.  Perhaps within a couple weeks.  Not a strict rule, but if you didn't end up doing it, it'd be good for it to be available for others to work on.

Feel free to ask any questions about implementation here.

**Comment by lhcopetti** [comment]
Sounds great! I will definetely go for it then. Thanks!

**Comment by mitchellwrosen** [comment]
Hi @lhcopetti - are you still working on this? I have a patch ready to go, didn't notice that you had expressed interest :)

**Comment by lhcopetti** [comment]
@mitchellwrosen I would work on it the following week, so no work was lost! I will still play around with this issue on my own and maybe use your patch to compare with my own solution and learn even more from it. So, don't worry!

**Comment by andrewufrank** [comment]
I found that i can get from github directly the following string when copy the link form "commit" field of the archive:

    https://github.com/mitchellwrosen/stack/commit/f702547f133c34bf7ca1f5cdbbee95bd436ec14a

which is easy to split in 

    - git: https://github.com/mitchellwrosen/stack/
      commit:  /f702547f133c34bf7ca1f5cdbbee95bd436ec14a

to satisfy the new (extensible) snapshot syntax (16.5) - but would it not be simpler to allow just the string githup gives directly?

**Comment by alexanderkjeldaas** [comment]
I'll just leave a vote for the 2-line version where the commit is clearly a separate token (which can easily be replaced).
