### ISSUE TITLE
Suggestion: treat WSL differently

### ISSUE THREAD

**Issue by JulianBirch** [commercialhaskell/stack#3874]
Haskell 8 has serious problems on WSL at the time of writing. Whilst not a complete solution, it would be nice if when stack was running under WSL it built GHC and executables using `--disable-large-address-space`.

**Comment by hvr** [comment]
@JulianBirch you may be interested in https://launchpad.net/~hvr/+archive/ubuntu/ghc-wsl

**Comment by borsboom** [comment]
I believe Microsoft has already made a lot of improvements to this in their "insider" releases which presumably will make it to a regular release at some point, so I'm not sure how much effort we will put into this right now.  Of course, a pull request would be welcomed gratefully.

In the meantime, a workaround may be to use `stack setup --ghc-bindist <URL>` to point Stack to the WSL-optimized bindist mentioned [here](https://mail.haskell.org/pipermail/haskell-cafe/2018-February/128587.html).  Note: I have not tried this, so I'm just guessing.

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and the improvements in WSL.
