### ISSUE TITLE
--system-ghc no longer works

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#3875]
Using Stack 1.6.3 on Windows x64, if I run:

```
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.2.1

$ stack exec --no-ghc-package-path --system-ghc -- ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.2

$ stack exec --no-ghc-package-path --system-ghc -- which ghc
/c/Users/ndmit_000/AppData/Local/Programs/stack/x86_64-windows/ghc-8.0.2/bin/ghc
```

Note that even when running `stack exec` with `--system-ghc` it has decided to put it's own GHC on the PATH in front of the one that was already there.

**Comment by mgsloan** [comment]
The --help for "--system-ghc" says "Enable/disable using the system
installed GHC (on the PATH) if available and a matching version."  Grammar
isn't so great on that, I've pushed a small fix of the wording.

Perhaps the behavior of requiring a match isn't so good.  Maybe something
like the following should be outputted?

> Warning: Command-line options or configuration specified "system-ghc:
true", but the compiler on the path does not match "ghc == 8.0.2", so
instead the compiler located at /c/Users/ndmit_000/AppData/
Local/Programs/stack/x86_64-windows/ghc-8.0.2/bin/ghc will be used. Pass
"--skip-ghc-check" or specify "skip-ghc-check: true" to skip the
requirement that compiler version matches and use the one on the PATH.

That would have clarified things, right?

I think it would have been better to have --system-ghc imply
--skip-ghc-check, but not sure if it's worth the behavior change.

**Comment by ndmitchell** [comment]
I didn't read the help for `system-ghc` close enough to see that, so all the grammar fixes in the world wouldn't have helped... Not a bad thing to tidy it up though.

Perhaps given that nowadays everyone is by default using the GHC installed by Stack then anyone who says `--system-ghc` isn't making a passive choice, but a very active choice to use the GHC on their system. As a result, I suggest that falling back to the one installed by Stack isn't something it should ever do.

I'd also be quite happy with `--skip-ghc-check` always being off, since it is only relevant in the corner-case of installing your own GHC, and you can screw that up in other ways if you really want.

For info, the _actual_ reason I was using stack was to do `stack exec --no-ghc-package-path --system-ghc cabal install old-time`, since in Windows the `old-time` won't install normally, but thanks to Stack's MinGW environment it will.

**Comment by mgsloan** [comment]
Hmm, yeah, it may make sense to have `--system-ghc` straight up fail if the system one doesn't match.

**Comment by rikvdkleij** [comment]
I'm also confused by this option.

I have installed: GHC 8.4.3.

I want to install HLint from LTS-11 in an isolated environment. To prevent GHC 8.2.2 is downloaded , when it's installed on the system, I pass `--system-ghc`. But installing failed because Stack is using the GHC version from the `stack.yaml` (8.4.2).
Also Stack has installed GHC version 8.4.2 in the isolated environment while I pass to the command `--resolver lts-11`

```
/usr/local/bin/stack --stack-root /Users/rik/.intellij-haskell/lts-11 --resolver lts-11 --system-ghc --local-bin-path /Users/rik/.intellij-haskell/lts-11/bin install hlint:   
			Selected resolver: lts-11.13
			happy-1.19.9: configure
			--  While building custom Setup.hs for package happy-1.19.9 using:
			/private/var/folders/fg/3071_gkd5p92vmb9884sxtt00000gn/T/stack55283/happy-1.19.9/.stack-work/dist/x86_64-osx/Cabal-2.2.0.1/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-2.2.0.1 configure --with-ghc=/Users/rik/.intellij-haskell/lts-11/programs/x86_64-osx/ghc-8.4.2/bin/ghc ....
```

**Comment by rikvdkleij** [comment]
Hmm, sorry, this a different issue. Stack uses the GHC version of the `stack.yaml` and not the GHC version of the resolver which is passed on the command. It looks like I also have to force the GHC version with `--compiler`.

**Comment by snoyberg** [comment]
Closing, this is the intended way for this feature to work
