### ISSUE TITLE
single test suite failure should show entire log

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#388]
In a multi-cabal file project build, if one test suite fails, I should see the test log. Instead stack only tells me where the log is.
This is a regression that I thought I reported a while back and was fixed once before, although I am having trouble finding the actual github issue.
We are using the 0.1 release

```
Progress: 9/10
Completed all 10 actions.
Test suite failure for package fr-0.1.0.0
    fr-test:  exited with: ExitFailure 1

Full log available at /home/ubuntu/backend/.stack-work/logs/fr-0.1.0.0.log
```

**Comment by gregwebs** [comment]
The command we are running is `stack test`. `stack build` works at least to some degree in this scenario

**Comment by snoyberg** [comment]
@gregwebs Could catch, should be fixed on master.
