### ISSUE TITLE
Make `--fast` the default

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#3881]
I'd like to propose making `--fast` (`-O0`) the default when using `stack build` in order to reduce compile time.

**Comment by mgsloan** [comment]
I don't think we should do that, then if you did, say, `stack install intero`, you would get the unoptimized version.  Could have `install` have a different default, but then it would no longer be a simple synonym for `stack build --copy-bins`

**Comment by mitchellwrosen** [comment]
That's true! `stack build` does a lot.

- When developing an executable component, I want `stack build` to be fast, I don't care about optimized code, and I don't like typing `--fast`.
- When running tests, it's less clear to me what the right default is. I'd probably prefer no optimizations.

- When benchmarking, I'm interested in optimized code, and I'd hate to have to type `stack build --bench --optimize`
- When installing software globally from Hackage, using `stack` like a package manager, I'd also hate to have to type `stack build --copy-bins --optimize`

By the way, @mgsloan, do you happen to know the `ghc-options` field overrides options like `--fast`, or vice-versa? Thank you!

**Comment by mgsloan** [comment]
Yes, I think it is best to leave things as they are.

I am not 100% sure, but I believe that the `-O0` option implied by `--fast`
comes after `ghc-options` in cabal files.  It definitely comes before
options specified by via passing `--ghc-options` to stack, though.

I have considered maybe adding "pseudo targets" to stack, which would
specify a set of packages and options to use.  Could consider having a
pseudo target that is used by default which specifies "--fast".  Dunno,
though, there is always a tricky balance between complexity and powerful
conveniences.

**Comment by alexanderkjeldaas** [comment]
There are also two possible `--fast` modes:

1.   In one the focus is on development of packages in the `packages:` section.  In this case, don't compile dependencies using `--fast`, only what is in `packages:`.

2. The other case might be CI or situations where you need to get from zero to finished build quickly.  In this case you want all packages to be built with `-O0`.

Modus 1 is likely to cause less damage as a default as packages that need to be optimized will be dependencies of some "app" package typically.  It will also make the typical recompile cycle fast.

**Comment by mgsloan** [comment]
The true fast recompile for development is `stack ghci` :)

Closing this as wontfix

**Comment by aryairani** [comment]
> The true fast recompile for development is `stack ghci` :)

Am I wrong in understanding that `stack ghci` and `:r` will only load/check 0-1 `Main` modules per launch, regardless of how many you may have referenced in your `stack.yaml`?
