### ISSUE TITLE
Stack new on current directory

### ISSUE THREAD

**Issue by CMCDragonkai** [commercialhaskell/stack#3882]
Just wondering why there isn't an option to run `stack new` on the current directory? Sometimes I have created a project directory already, and i want to fill it up with files. I guess the main problem is what to do if the directory already contains files that exists. To be safe, you can report that such a file already exists, and you didn't replace it (rerun the command while removing the old file to replace the file).

**Comment by mgsloan** [comment]
I think that `stack new --bare` does what you want.  Not sure if I like the flag name `--bare`.  I guess it comes from `git init --bare`, but the analogy falls apart a bit.

What flag name would be clearer?  `stack new --current-dir`?

**Comment by CMCDragonkai** [comment]
Why not just make `stack new` support directories that already exists. So you can then use `.` or `./somedirthatalreadyexists`?

**Comment by mgsloan** [comment]
Because it doesn't take a directory name as an argument, it takes a package
name.

**Comment by snoyberg** [comment]
Answers provided, closing
