### ISSUE TITLE
Will binaries inside x86_64-linux-nix work on all Linuxes (Ubuntu, Debian, NixOS) running on x86_64 CPUs?

### ISSUE THREAD

**Issue by hydramo** [commercialhaskell/stack#3885]
I'm wondering about the "robustness" of the stuff inside `.stack-work/install/x86_64-linux-nix`.

For example, if I compile using `stack build` on an Ubuntu build server, can I with absolute certainty run the same binary on a server machine with NixOS? (Assuming both are running an x86_64 CPU, of course.)

**Comment by qrilka** [comment]
https://github.com/nh2/static-haskell-nix allows something like this to become possible

**Comment by snoyberg** [comment]
Sounds like this issue is addressed, closing
