### ISSUE TITLE
`stack script` ignores `local-programs-path` in ~/.stack/config.yaml

### ISSUE THREAD

**Issue by sgraf812** [commercialhaskell/stack#3887]
### General summary/comments

Also found #3705, so I assume `stack script` ignores ~/.stack/config.yaml completely.

### Steps to reproduce

For example:

1. Edit ~/.stack/config.yaml with a setting for `local-programs-path` to point somewhere else than ~/.stack/programs
2. Run `stack stream-fusion.hs`, where stream-fusion.hs is the attached file

### Expected

Just run the thing after initial setup

### Actual

Re-downloads GHC 8.2.2 and errors (might be machine-specific) while unpacking it into ~/.stack/programs. Also complains with `The following directories may now contain files, but won't be used by stack <some ~/.stack/programs paths>`, which it wouldn't in the first place.

```
$ stack stream-fusion.hs --verbose
Already downloaded.
Unpacking GHC into /$HOME/.stack/programs/x86_64-linux/ghc-nopie-8.2.2.temp/ ...
```

### Stack version

```
$ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

Installed 1.6.3 through `nix-env`, but then did `stack upgrade` and used the downloaded exe for this reproduction (didn't want to wait for the upgrade of my whole distribution).

**Comment by sgraf812** [comment]
Worked around this by just symlinking ~/.stack somewhere else altogether.

**Comment by mgsloan** [comment]
Yes, it looks like `stack script` does not read `config.yaml`.  This is likely for reproducibility, but I'm thinking that it should read it.  The reasoning is that the options allowed in `config.yaml` are mostly intended to configure stack to work properly with their system and change some CLI defaults.  So, hopefully having `stack script` read `config.yaml` would not greatly negatively affect reproducibility, and instead just allow scripts to work in more cases.

**Comment by snoyberg** [comment]
I don't know all of the different options allowed in config.yaml, but I'm imagining some of them should be allowed, and others shouldn't. local-programs-path seems like one that should be parsed by script.

**Comment by snoyberg** [comment]
I'm going to make this change
