### ISSUE TITLE
Stack fails to install GHC on Arch Linux

### ISSUE THREAD

**Issue by Peachball** [commercialhaskell/stack#3889]
### General summary/comments (optional)
On Arch linux, it stack does not build ghc correctly

### Steps to reproduce
After downloading a copy of stack, running `stack ghc` downloads ghc and attempts to install it.

### Expected
The appropriate ghc version should be installed.

### Actual
Stack crashes.

The output of `stack ghc --verbose` is [here](https://gist.github.com/Peachball/cf90241374cddb73ecb9b475e59a3d9d)

### Stack version

```
$ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation
Downloaded `stack-1.6.5-linux-x86_64-static.tar.gz` from [releases](https://github.com/commercialhaskell/stack/releases), and moved into `~/.local/bin` (which is in my PATH).

I have the `ghc-static` package from the arch repositories installed.

The workaround I'm currently using is to use the system ghc, but as a result, I can't use multiple ghc versions easily.

**Comment by ibung** [comment]
That's weird, your method of installation works on my Arch machine, and I don't even have `ghc-static` installed (if it has anything to do with this at all).

```
λ › stack --version                                                                                                                                                                                                                          ~
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

**Comment by Peachball** [comment]
The problem seems to be related to how stack interacts with the NTFS filesystem on my hard drive.
