### ISSUE TITLE
Detect unused dependencies

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#39]
Would be nice. Based on whatever code we're using to detect dependencies for the setup code, we could use that to detect what's _not_ being used to aid in cleaning up dependencies.

**Comment by mgsloan** [comment]
As noted in #1667, it would be good to involve this check in sdist / upload.

**Comment by mgsloan** [comment]
Here's a cool project that does this:  https://github.com/afcady/packunused

Perhaps it could be integrated with stack?  It does need to be compiled with the version of Cabal used in the user's project, though (whereas stack does not need to be compiled with the same Cabal version).

**Comment by nh2** [comment]
> Perhaps it could be integrated with stack? It does need to be compiled with the version of Cabal used in the user's project, though

@mgsloan Is that really the case? It seems to me that you just have to compile with `-ddump-minimal-imports` and then `packunused` picks up the (text format) outputs, or am I misunderstanding?

There also does seem to be support for stack, e.g. `packunused --help` from https://github.com/hvr/packunused/pull/23 prints:

```
In order to use this tool you should set up the package to be analyzed as
follows, before executing 'packunused':

For stack:  stack clean
            stack build --ghc-options=-ddump-minimal-imports
            packunused
```

Only problem with GHC 8: https://ghc.haskell.org/trac/ghc/ticket/12474

**Comment by mgsloan** [comment]
> @mgsloan Is that really the case? It seems to me that you just have to compile with -ddump-minimal-imports and then packunused picks up the (text format) outputs, or am I misunderstanding?

Could be!  Worth giving it a try.  I just saw that it's using lots of stuff from `Cabal`, and figured that the versions would need to match

**Comment by nh2** [comment]
The GHC ticket, and `packunused` were both fixed.

**Comment by lwm** [comment]
Trying to move this one along via https://github.com/hvr/packunused/issues/27.

**Comment by jmn** [comment]
Any updates on this? Does the introduction of hpack in stack change anything?

**Comment by lwm** [comment]
Another option - https://hackage.haskell.org/package/weeder!

Nothing moved along much with the packunused plan. Don't think people had time.

**Comment by snoyberg** [comment]
Given that external tooling like weeder addresses this now, let's call this out of scope.
