### ISSUE TITLE
Symbolic nightly resolvers

### ISSUE THREAD

**Issue by zudov** [commercialhaskell/stack#390]
Let's say that I want to use the latest nightly snapshot when working on my unreleased WIP project (the one which is resolved by non-canonical stackage URL  http://www.stackage.org/nightly) and I don't care that the build [is unreproducible](https://github.com/commercialhaskell/stack/issues/241#issuecomment-110494626) because I am the only person who performs the builds.

At the moment I would have to check the current date and put `resolver: nightly-YYYY-MM-DD`. The next day I would have to go and update that date, not very nice. I think it would be useful if I could simply put `resolver: nightly` and that would symbolically link to the latest nightly release.

Another disadvantage of always using the latest nightly release is that I would have to rebuild snapshot dependencies every day. This can be avoided by switching to a latest nightly snapshot once a week instead of once a day. It would be interesting to have something like `resolver: weekly` which would resolve to the latest Monday/Sunday snapshot.

That feature is quite arguable because at the moment there is no way that I know of to get an unreproducible build with stack (snapshot version has to be explicitly specified, package versions has to be explicitly specified) and that feature would introduce such a way.

What do you think?

**Comment by zudov** [comment]
Some related discussions:
 - https://github.com/commercialhaskell/stack/issues/224#issuecomment-110642280
 - https://github.com/commercialhaskell/stack/issues/241#issuecomment-110494626

**Comment by radix** [comment]
Just an idea, what about only allowing such a symbolic `nightly` with a --nightly parameter? That might drive home the fact that it becomes non-reproducible? I dunno.

**Comment by zudov** [comment]
@radix Yes, that makes sense. The disadvantage is that during development you would have to always put that parameter which might be a bit annoying. Especially if in the future there would appear more of such command-line options only for development.

I am thinking of a second config file `stack-devel.yaml`. Which would handle various unsafe options that are needed only for development. This config would be used only when some flag is given (e.g. `--dev`) users who want to use it often might create an alias `stack-dev=stack --dev`.

**Comment by drwebb** [comment]
@zudov 

You do know about the existence of STACK_YAML? It might be way forward to write a plugin that interacts more with that file and wraps other stack commands.

**Comment by zudov** [comment]
@drwebb I know, it wouldn't be hard to write a wrapper around stack which would provide this functionality.

**Comment by rjayatilleka** [comment]
+1 to the idea of having a `resolver: nightly` option, without requiring a flag. It doesn't create unreproducible builds as such, since stack will presumably let you know the specific resolver you're building against when you run `stack build`. You can always manually change the resolver if you want to reproduce a specific build.

Also, if using the latest `nightly` snapshot fails, should this backtrack through nightly snapshots, or just go to the latest LTS, and continue on the regular sequence of resolver attempts? Or it could check whatever is in the global stack.yaml? I'll throw my vote in for just trying the latest LTS and following the normal retry sequence from there.

**Comment by snoyberg** [comment]
There's more than just unreproducible builds going on here. It's also a big performance problem. Running `stack build` would require querying S3 from scratch each time to determine the newest nightly. I think the right approach is to have a `stack config` command for easily modifying the resolver, and have one of those options be "use the latest nightly."

**Comment by rjayatilleka** [comment]
Well, that sounds good by me too. Updating the resolver group automatically in a build is probably a bit excessively non-transparent too. Would an API look something like `stack config [--global] core.resolver [lts-x.xx/nightly-2015-xx-xx/latest]` be good? It's leaning heavily on the git config API. We could get rid of the core bit and just make it resolver. Resolver is a top level property of a stack.yaml file after all.

It doesn't seem like there's an open issue for a `config` command. Is this the only idea for it? If there are others maybe we should gather those into an issue.

**Comment by snoyberg** [comment]
#115 is tracking the general feature. I hadn't thought on the specific syntax, but your recommendation sounds good to me.

**Comment by rjayatilleka** [comment]
Actually, we might want it to be like this:

- `lts-x.xx`, `lts-2.15` picks a specific lts resolver.
- `lts-x`, `lts-2` picks the latest version of an lts.
- `nightly-xxxx-xx-xx`, `nightly-2015-06-24` picks a specific nightly.
- `nightly` picks the latest nightly.

I'm not too clear on the current or planned methods to automatically solve for dependencies, but a `solved` option might be useful too.

**Comment by alanz** [comment]
How about publishing a URL http://www.stackage.org/weekly that is updated once a week? Similar to the current nightly symlink.

**Comment by zudov** [comment]
@alanz I am not sure why it's needed. `/nightly` and `/lts` endpoints are needed to allow linking to the latest versions, but why would someone want to link to the last Monday option.

**Comment by alanz** [comment]
If you are developing against the bleeding edge, but don't want to rebuild
every day

**Comment by zudov** [comment]
@alanz Ohh. I forgot that you can use stackage snapshots not only with stack.

**Comment by zudov** [comment]
I like the config idea

**Comment by alanz** [comment]
You would also then be able to do

    resolver : weekly

**Comment by snoyberg** [comment]
I've added a comment to #115 about this issue, will continue tracking this there.
