### ISSUE TITLE
stack cannot upgrade itself

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#3903]
```
$ stack --version
Version 1.4.0, Git revision 5986498a9d1073e8d58c79ec1302bb2a7847a396 (4642 commits) x86_64 hpack-0.17.0
$ stack upgrade --git
Cloning stack
Cloning into 'stack'...
remote: Counting objects: 727, done.
remote: Compressing objects: 100% (536/536), done.
remote: Total 727 (delta 63), reused 452 (delta 33), pack-reused 0
Receiving objects: 100% (727/727), 717.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (63/63), done.
Checking connectivity... done.
Could not parse '/tmp/stack-upgrade40/stack/stack.yaml':
Aeson exception:
Error in $['extra-deps'][1]: failed to parse field 'extra-deps': expected PackageIdentifier, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

**Comment by mgsloan** [comment]
Good catch, I've opened https://github.com/commercialhaskell/stack/pull/3905 to resolve this.

**Comment by yihuang** [comment]
Is there any way to workaround this currently?

**Comment by alexanderkjeldaas** [comment]
Do an update first

**Comment by mgsloan** [comment]
I believe that the only way we can close this issue is to excise cassava from stackage

**Comment by CodyReichert** [comment]
Same issue here (upgrading from 1.2). @yihuang's suggestion worked for me as well, you just have to pass the -f flag as described here: https://docs.haskellstack.org/en/stable/install_and_upgrade/#upgrade

**Comment by mgsloan** [comment]
For some older versions, source upgrade might not work.  The merge of https://github.com/commercialhaskell/stack/pull/3905 makes it work for some more recent historical versions.
