### ISSUE TITLE
Better error message for empty stack.yaml

### ISSUE THREAD

**Issue by josefs** [commercialhaskell/stack#3906]
### General summary/comments (optional)

The error message for an empty stack.yaml file could be better.

### Steps to reproduce

1. Create an empty stack.yaml file
  `> touch stack.yaml`
2. Run stack with some command e.g.
  `> stack ghc`
3. Observe the error message

### Expected

I would have expected some nice error message indicating what things are missing from the stack.yaml file

### Actual

```
Could not parse 'C:\msys64\home\esvejos\FreeMonad\test\stack.yaml':
Aeson exception:
Error in $: expected ProjectAndConfigMonoid, encountered Null
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```
### Stack version

```
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by snoyberg** [comment]
Closing as wontfix, for 2 reasons:

1. I don't think the error message is that bad
2. I haven't seen this reported as a common stumbling block

That said, if you'd like to open a doc or code PR, I'd be happy to review
