### ISSUE TITLE
Add shortcut for "build --copy-compiler-tool"

### ISSUE THREAD

**Issue by AshleyYakeley** [commercialhaskell/stack#3908]
Suggestion: make `stack install-tool` a shortcut for `stack build --copy-compiler-tool`.

**Comment by mgsloan** [comment]
Hmm, perhaps!  Not sure I see this as a super common command for people to use.  Also I'm not sure how clear that is given that it doesn't mention "compiler".  This only really makes sense when installing tools that are compiled against a particular ghc version.

I guess I don't see any convincing reason *not* to add it, but also not sure if it's worth a new command.  Hmm!

**Comment by chrisdone** [comment]
I think this is consistent with `stack install`, but I think the `install` command is already considered a regrettable presence (a misleading name, and needless overhead for learning) - instead preferring `--copy-bins`. Just recently I saw a reddit thread of people asking what the difference between `stack build` and `stack install` was - so previous worries about needless confusion/overhead are confirmed for me. We also wanted to encourage more composable use of the commandline e.g. `stack build --haddock --test --copy-compiler-tool` you can add/remove flags to control behaviors easily.

So I think this'll get more push-back than go-aheads.  I vote :-1: (I assume that we can just vote on things like this).

**Comment by snoyberg** [comment]
Closing as wontfix
