### ISSUE TITLE
Directory symlinks for latest install

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#391]
The idea is to have `stack build` (and other commands which involve a build) add directory symlinks to `.stack-work` which point to the latest install and logs folders.  In other words, after a build which puts its files in `.stack-work/install/x86_64-linux/lts-2.14/7.8.4/`, `.stack-work/install/latest` will also point to the directory.

This is useful to the user, as it provides a short path to the latest binaries / docs.  It's also useful for other tools / build scripts which need to access the results of `stack build`.  Instead of hardcoding paths that depend on OS version and need to be updated when we change ghc version / docker image tag, we can use paths that don't change.

**Comment by snoyberg** [comment]
What's wrong with `stack exec` for running executables? It also seems like `stack path` will go a long way towards answering these questions.

**Comment by snoyberg** [comment]
I'm overall against this idea since it introduces state that doesn't need to be there. With this in place, we suddenly have a piece of metadata floating around that could contradict what's in `stack.yaml` because we haven't yet run `stack build`.

**Comment by alanz** [comment]
What about a specific command in stack to symlink the current context? This will help for people using traditional tooling.

e.g. I would be interested in being able to have a symlink from a given .stack-work context to .dist

**Comment by snoyberg** [comment]
If `stack path` gave you the directory you were looking for, how different would that be from `ln -s $(stack path --dist-dir) dist`?

(Pinging @chrisdone, perhaps the `stack path` output should be modified to make the above command actually work.)

**Comment by alanz** [comment]
That would do it, but I suspect it may be a fairly common operation
(initially at least), and it may be useful to give it a synonym as a stack
command.

**Comment by chrisdone** [comment]
@snoyberg I agree with this. I'd considered it while implementing; specifically requesting one item should omit the key. I'll do it now.

**Comment by chrisdone** [comment]
Done.

    $ stack path --dist-dir
    .stack-work/dist/x86_64-linux/Cabal-1.18.1.5/

**Comment by mgsloan** [comment]
Having such a command is sufficient, cool!

I've edited the issue to make it clear that this isn't about logs.  That was a mistaken afterthought.

**Comment by snoyberg** [comment]
After speaking with @mgsloan about this yesterday, I think I understand the motivation a bit better, and it makes sense. Let's move ahead with it.

**Comment by snoyberg** [comment]
One thing to note: we'll want to use unix-compat to implement this to avoid conditional Unix compilation, but nonetheless will need exception handling since unix-compat's symlink support on Windows just throws an exception.

**Comment by mgsloan** [comment]
As mentioned in #470, we're not going to add this.

**Comment by k-bx** [comment]
The motivation to have something like this is to extract executable to further pack & deploy it. But `stack path --local-install-root` does seem to solve this, thanks.
