### ISSUE TITLE
Add stack-version field to stack.yaml

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#3911]
I propose to add `stack-version` field to `stack.yaml`.
The samantics are simple, `stack` should (note: not must) behave as the version
specified version. In particular:
- if `stack` is older (but recognises such field), it *at least* warns the
  user that author of `stack.yaml` used newer stack, so `stack.yaml` might
  have new fields which older `stack` simply ignores. Also if older `stack`
  fails to parse new `stack.yaml`, the version information would provide
  means for better diagnostics
- if `stack` is newer, it should
  - either behave as old `stack`
  - or (less preferred) warn if something in `stack.yaml` have changed semantics
    which might or might not cause failures.

For reproducibility of builds (backward-compat) as well as forward-compatibility this is IMO
mandatory feature to have.

Forward-compatibility by an example: `github` shorthand for extra-dep https://github.com/commercialhaskell/stack/pull/3890 will break older `stack`s.
Backward-compatibility: new stack could have separate parsers for `stack.yaml` for different `stack-version`s.
I'm not sure if user could currently mix old and new ways of specifying `extra-deps`, which might turn confusing.

**Comment by snoyberg** [comment]
We already have a `require-stack-version` field.

**Comment by phadej** [comment]
@snoyberg great, I didn't know. should readl the manual better next time.
