### ISSUE TITLE
stack setup --arch=i386 failed

### ISSUE THREAD

**Issue by denisshevchenko** [commercialhaskell/stack#3913]
I'm trying to install GHC for i386. I'm using Debian 9.3 x86_64, but I need to compile program that will run on i386 platform.

My `stack`-version is:

```
$ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

My command:

```
$ stack setup --arch=i386
```

I see that compiler is downloading and installation is starting:

```
Preparing to install GHC (nopie) to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-nopie-8.2.2.
...
```

But after that I get an error:

```
...
"utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist" copy libraries/ghc-prim dist-install "strip" '' '/home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2' '/home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2/lib/ghc-8.2.2' '/home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2/share/doc/ghc-8.2.2/html/libraries' 'v p dyn'
ghc.mk:986: recipe for target 'install_packages' failed
Makefile:51: recipe for target 'install' failed

utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist: line 3: /home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2.temp/ghc-8.2.2/utils/ghc-cabal/dist-install/build/tmp/ghc-cabal: No such file or directory
make[1]: *** [install_packages] Error 127
make: *** [install] Error 2


Error: Error encountered while installing GHC with
         make install
         run in /home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2.temp/ghc-8.2.2/

       The following directories may now contain files, but won't be used by stack:
         - /home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2.temp/
         - /home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2/
```

But it's strange, because I do see that file:

```

$ ls /home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2.temp/ghc-8.2.2/utils/ghc-cabal/dist-install/build/tmp/ghc-cabal
/home/denis/.stack/programs/i386-linux/ghc-nopie-8.2.2.temp/ghc-8.2.2/utils/ghc-cabal/dist-install/build/tmp/ghc-cabal
```

How can I fix it?

**Comment by denisshevchenko** [comment]
I'm trying to define i386 in `stack.yaml` - the same error.

**Comment by borsboom** [comment]
This is a GHC issue, not a Stack one (those error messages comes from GHC's setup process).  I'm not sure if GHC can support this use case at all, but I've never tried it.  In theory, running i386 GHC on x86_64 _should_ be possible but you would need to have i386 shared libraries installed on your system (see https://unix.stackexchange.com/questions/12956/how-do-i-run-32-bit-programs-on-a-64-bit-debian-ubuntu).

I'd recommend first making sure that you can run other 32-bit binaries on your system, then try installing a 32-bit GHC bindist manually (see https://www.haskell.org/ghc/download_ghc_8_2_2.html#linux_i386) and see if that works.  Once you have all that working, I think Stack should work for this use case but, again, never tried it.

Or just run a virtual machine with a 32-bit Linux installed :)
