### ISSUE TITLE
Feature request : multiple build configurations

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#392]
At the moment there is no way to override the `stack.yaml` config file for a project.

Certain packages need to support multiple compiler versions, and it would be useful to be able to run a `stack test` against each of these in turn.

Perhaps provide a command line flag to specify the particular `stack.yaml` to be used for a given operation.

Alternatively the stack.yaml format could support multiple configurations, but I think that would be unnecessarily complex.

Current context

    Version 0.1.0.0, Git revision 67893a83d55810f2592c0073bae51aeaff14f142

**Comment by snoyberg** [comment]
There's already support for a `STACK_YAML` environment variable to choose an alternate config file. Issue #378 is tracking making that a command line option as well.

**Comment by alanz** [comment]
Ok, sorry. I scanned over the issues before posting but missed that.

**Comment by snoyberg** [comment]
No problem. If you have an idea of a way to make it more prominent in the docs, that would be great.

**Comment by alanz** [comment]
I think having a `--stack-yaml` command line option will document it
sufficiently.
