### ISSUE TITLE
Stack and intero integration broken on variuos platforms

### ISSUE THREAD

**Issue by OmanF** [commercialhaskell/stack#3921]
### General summary/comments
Using stack/Haskell 8.2.2 (with stack 1.6.5) that was installed using the `asdf` version manager, starting Haskell buffers in both Spacemacs and Visual Studio Code produces errors that render the `intero` plugin useless as the buffer can't communicate with the intero backend. 

### Steps to reproduce
On Spacemacs, see the issue here: https://github.com/commercialhaskell/intero/issues/536

On VSCode, the following is a snippet from the `output` tab, once a Haskell tab is used (using `Haskero` plugin):
```
Initializing Haskero...
Spawning process 'stack' with command 'stack ghci --with-ghc intero "--ghci-options=-ignore-dot-ghci -Wall" --no-build --no-load'
[Error - 12:31:19] Server initialization failed.
  Message: Request initialize failed with message: process exited with code 1

stdout:


stderr:
Invalid option `-Wall'

Usage: stack ghci [TARGET/FILE] [--ghci-options OPTIONS] [--ghc-options OPTIONS]
                  [--flag PACKAGE:[-]FLAG] [--with-ghc GHC] [--[no-]load]
                  [--package ARG] [--main-is TARGET] [--load-local-deps]
                  [--[no-]package-hiding] [--only-main] [--trace] [--profile]
                  [--no-strip] [--[no-]test] [--[no-]bench] [--help]
  Run ghci in the context of package(s) (experimental)


  Code: -32603 
```

### Stack version
`Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0`

### Method of installation
As noted, using `asdf` version manager (https://github.com/asdf-vm/asdf) with its Haskell plugin.

### Operating system and misc.
MacOS High Sierra.
Both Spacemacs (and underlying Emacs) and VSCode are running latest *stable* version, all plugins updated daily.

**Comment by mgsloan** [comment]
Hmm, looks like something is splitting `"--ghci-options=-ignore-dot-ghci -Wall"`.  My guess is that the editor plugin is spawning it incorrectly.  It should work in spacemacs, though, since that should use the official elisp.

The commandline seems to be passing ghci-options correctly, so not sure what could be going wrong here.  Perhaps it's a windows thing.

**Comment by OmanF** [comment]
Maybe I misunderstood the reply, but, as I mentioned, I'm on `macOS High Sierra`, not Windows.

Also, for the `Spacemacs`, I again refer you to https://github.com/commercialhaskell/intero/issues/536. There's seems to be a problem with Spacemacs integration as well.

**Comment by chrisdone** [comment]
Try running this in your Emacs:

```lisp
(start-file-process "stack"
                    (switch-to-buffer (get-buffer-create "*process-output*"))
                    intero-stack-executable
                    "ghci"
                    "--docker-run-args=--interactive=true --tty=false")
```

**Comment by Zeeker** [comment]
Okay, I've boiled it down to the usage of `asdf`. I've reinstalled everything via `homebrew` and not it works.

`asdf` "shims" the binary to allow easily switching between versions and it seems it does something odd with the CLI options.

Nothing to do here, I think.

**Comment by chrisdone** [comment]
👍 Cheers

**Comment by chrisdone** [comment]
Oops, thought this was an Intero issue.

**Comment by snoyberg** [comment]
Closing as this seems to be outside of Stack
