### ISSUE TITLE
Could not find .cabal file for path: 

### ISSUE THREAD

**Issue by glasgowm** [commercialhaskell/stack#3932]
Hi all,

Trying to install Haskell 8.0.2 to run software provided by my uni. Managed to get haskell and cabal installed without any errors. When I tried to bash run I got this error

```
 Common.hs:9:1: error:
 Failed to load interface for ‘Graphics.UI.Threepenny.Core’
 Use -v to see a list of the files searched for.
finished
```

So I tried 
`cabal install threepenny-gui
`

But getting the following error

`Resolving dependencies...
Configuring threepenny-gui-0.8.2.2...
Building threepenny-gui-0.8.2.2...
Failed to install threepenny-gui-0.8.2.2
Build log ( /Users/markglasgow/.cabal/logs/threepenny-gui-0.8.2.2.log ):
cabal: Entering directory '/var/folders/m_/w2r49n7s0px2vqp22qz84l7m0000gn/T/cabal-tmp-55723/threepenny-gui-0.8.2.2'
Configuring threepenny-gui-0.8.2.2...
Building threepenny-gui-0.8.2.2...
Preprocessing library threepenny-gui-0.8.2.2...
[ 1 of 29] Compiling Reactive.Threepenny.Types ( src/Reactive/Threepenny/Types.hs, dist/build/Reactive/Threepenny/Types.o )
[ 2 of 29] Compiling Reactive.Threepenny.Monads ( src/Reactive/Threepenny/Monads.hs, dist/build/Reactive/Threepenny/Monads.o )
[ 3 of 29] Compiling Reactive.Threepenny.PulseLatch ( src/Reactive/Threepenny/PulseLatch.hs, dist/build/Reactive/Threepenny/PulseLatch.o )
[ 4 of 29] Compiling Reactive.Threepenny.Memo ( src/Reactive/Threepenny/Memo.hs, dist/build/Reactive/Threepenny/Memo.o )
[ 5 of 29] Compiling Reactive.Threepenny ( src/Reactive/Threepenny.hs, dist/build/Reactive/Threepenny.o )
[ 6 of 29] Compiling Paths_threepenny_gui ( dist/build/autogen/Paths_threepenny_gui.hs, dist/build/Paths_threepenny_gui.o )
[ 7 of 29] Compiling Foreign.RemotePtr ( src/Foreign/RemotePtr.hs, dist/build/Foreign/RemotePtr.o )
[ 8 of 29] Compiling Foreign.JavaScript.Types ( src/Foreign/JavaScript/Types.hs, dist/build/Foreign/JavaScript/Types.o )
[ 9 of 29] Compiling Foreign.JavaScript.Include ( src/Foreign/JavaScript/Include.hs, dist/build/Foreign/JavaScript/Include.o )
[10 of 29] Compiling Foreign.JavaScript.Resources ( src/Foreign/JavaScript/Resources.hs, dist/build/Foreign/JavaScript/Resources.o )

/var/folders/m_/w2r49n7s0px2vqp22qz84l7m0000gn/T/ghc55787_0/ghc_41.hscpp:425:7: error:
    • Exception when trying to run compile-time code:
        Could not find .cabal file for path: /private/var/folders/m_/w2r49n7s0px2vqp22qz84l7m0000gn/T/ghc55787_0/ghc_41.hscpp
CallStack (from HasCallStack):
  error, called at /var/folders/m_/w2r49n7s0px2vqp22qz84l7m0000gn/T/ghc50277_0/ghc_1.hscpp:527:24 in file-embed-0.0.10.1-AZ8NoUy73zGAtI0K1PrKfR:Data.FileEmbed
      Code: include "js/lib/jquery.js"
    • In the untyped splice: $(include "js/lib/jquery.js")
cabal: Leaving directory '/var/folders/m_/w2r49n7s0px2vqp22qz84l7m0000gn/T/cabal-tmp-55723/threepenny-gui-0.8.2.2'
cabal: Error: some packages failed to install:
threepenny-gui-0.8.2.2 failed during the building phase. The exception was:
ExitFailure 1
`

**Comment by mgsloan** [comment]
Note that this is the issue tracker for the `stack` build tool.  The cabal issue tracker is [here](https://github.com/haskell/cabal/issues)
