### ISSUE TITLE
"mingw" top-level field in YAML similar to "nix"

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#3933]
### General summary/comments
It would be very useful if there is a "mingw" top-level field in YAML file similar to "nix" where third party C dependencies are listed. Stack may do "pacman -S {dependency}" for each. This way we would have "nix" for Linux and "mingw" for Windows C dependencies.

**Comment by snoyberg** [comment]
Moved to wishlist https://github.com/commercialhaskell/stack/wiki/Wishlist
