### ISSUE TITLE
'Workflow' section in readme recommends modify cabal file

### ISSUE THREAD

**Issue by ashishsc** [commercialhaskell/stack#3946]
Hello there, Haskell beginner reporting an inconsistency:
https://docs.haskellstack.org/en/stable/README/#workflow

The workflow section on the first page on the docs here recommends:
```
So to manage your library:
...
2. If you need to include another library (for example the package
   [`text`](https://hackage.haskell.org/package/text)):

   - Add the package `text` to the file `my-project.cabal`
     in the section `build-depends: ...`.
   - Run `stack build` another time.
```
However the stack user guide recommends modifying the package.yml (hpack). Should be a quick change and was confusing for a beginner!

Thank you for all the hard work!

**Comment by mpilgrem** [comment]
@ashishsc, thanks for reporting (back in 2018). I am closing this issue because https://docs.haskellstack.org/en/stable/#step-2-next-steps no longer has this inconsistency.
