### ISSUE TITLE
provide a lenient flag to allow building hackages with deps missing in Stackage

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#3949]
Currently stack does not really like building packages from Hackage with missing deps in Stackage.

Workaround seems to be to add all all the missing deps on the command line...
But this is a bit tedious and something that stack could probably do fairly easily if it wanted to. :)

Hope that is enough to make sense otherwise to provide some explicit examples.

**Comment by snoyberg** [comment]
I don't actually know how it would do this without implementing a full dependency solver in Stack, which we explicitly do not want to do.

**Comment by snoyberg** [comment]
Closing as wontfix
