### ISSUE TITLE
How to pass arguments to test

### ISSUE THREAD

**Issue by coubeatczech** [commercialhaskell/stack#395]
I'm using the stack with quickcheck-tasty. When the quickcheck fails, it prints the argument that one should run, so one can reproduce the case.

    Use --quickcheck-replay '2 TFGenR 0000000458DA9F91000000000007A120000000000000DF6D00000045ECA54EC0 0 7 3 0' to reproduce.

I've been unsuccessful with passing that option to do the quickcheck in `stack test`.
This doesn't work:

    stack test --test-arguments="--quickcheck-replay '2 TFGenR 0000000458DA9F91000000000007A120000000000000DF6D00000045ECA54EC0 0 7 3 0'"

How should I quote the test arguments so they are correctly delivered to the test framework (using Bash)?

**Comment by chrisdone** [comment]
stack test --test-arguments="--quickcheck-replay \"2 TFGenR 0000000458DA9F91000000000007A120000000000000DF6D00000045ECA54EC0 0 7 3 0\""

should do the trick.

**Comment by chrisdone** [comment]
Perhaps we could add support for single quotes in our argument parser?

**Comment by coubeatczech** [comment]
Perhaps I'm the only who has poor understanding of bash quoting. @chrisdone thanks!
