### ISSUE TITLE
“Failed to find 'alex' executable after installing it.”

### ISSUE THREAD

**Issue by mietek** [commercialhaskell/stack#3951]
### General summary/comments (optional)

I’m seeing the following error message when trying to build a project that uses GHCJS.

```
Failed to find 'alex' executable after installing it.
This shouldn't happen, because it gets built to the snapshot bin directory, which should be treated as being on the PATH.
```

This is the first time I’m trying to use both Stack and GHCJS, so my `~/.stack` is pristine.

Looking at Stack source code, the error message comes from line 1313 in `Setup.hs`.

https://github.com/commercialhaskell/stack/blob/master/src/Stack/Setup.hs#L1285-L1322

I find it suspicious that `menv'` (with a prime) is used to look for `cabal`, but `menv` (without a prime) is used to look for `alex` and `happy`.

### Steps to reproduce

```
$ git clone https://github.com/dmjio/miso && cd miso/sample-app
$ stack setup && stack build
```

### Expected

I expected the project to build.

### Actual

The project failed to build.

https://gist.github.com/mietek/61f276ab379de158e15c659208fa9772

### Stack version

```
$ stack --version
Version 1.6.5 x86_64 hpack-0.20.0
```

### Method of installation

```
$ brew install stack
```

**Comment by RobertFischer** [comment]
Try with stack 1.7.1 -- there's a fix specifically about this in the changelog.

**Comment by RobertFischer** [comment]
See here: https://github.com/commercialhaskell/stack/pull/3321
