### ISSUE TITLE
Cut a new release version - (v1.6.6 or v1.7)

### ISSUE THREAD

**Issue by recursion-ninja** [commercialhaskell/stack#3954]
I've been waiting to use features added to `Cabal-2.2.*` in conjunction with `stack` for a month now. Unfortunately there's been no traction on the three issues listed as blocking release (#3796, #3791, #3782).

Specifically I need to use the `cxx-options` and `cxx-sources` buildinfo fields for separate compilation of C and C++ source files. `stack`'s lack of support of these features is roadblocking our development and continuous integration efforts.

Could you prioritize resolving issues blocking a release incorporating `Cabal-2.2.*`?

**Comment by borsboom** [comment]
We're hoping to release 1.7 soon, so I've asked @mgsloan about the priotiy on those issues.  The Cabal-2.2 changes are too big to backport to 1.6, so it'll have to be a new major release.

**Comment by recursion-ninja** [comment]
I'm glad to hear the new release is coming soon. Is there a time table for the `v1.7` release somewhere or is that still being determined?

**Comment by dukedave** [comment]
Looks like #3791 was the sole remaining *P0: Blocking release* issue, and AFAICT the the fix has been merged (#3795). Is my hope merited?

**Comment by recursion-ninja** [comment]
@dukedave I think so! I'm sure there's a bit a of a review process in tagging a new release, something I'm unfamiliar with. I'm hoping the Stack team can make progress on that next week!

**Comment by borsboom** [comment]
Release candidate for v1.7.1: https://github.com/commercialhaskell/stack/releases/tag/v1.7.0.1

**Comment by borsboom** [comment]
`tcm-memo.cabal` should specify `cabal-version: 2.2`, otherwise those fields won't be recognized.  Although once you do that, your build will fail with:

> Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: This package description follows
version 2.2 of the Cabal specification. This tool only supports up to version
2.0.1.0

That's because GHC 8.2.2 comes with Cabal-2.0.1.0 and so that is the version that's used to build your package.  Change the resolver in `stack.yaml` to `nightly-2018-04-17`, to use GHC 8.4.1, and it should work.

**Comment by recursion-ninja** [comment]
@borsboom thanks for the technical assistance, let me try to rebuild in the morning with `ghc-8.4.1`.

I did try bumping the `cabal-version` field to `2.2` but was getting parse errors from `cabal` with `ghc-8.2.2`.

**Comment by recursion-ninja** [comment]
@borsboom [the test repository](https://github.com/recursion-ninja/tcm-memo) does build with the release candidate after ensuring that the resolver used `ghc-8.4.1`!

**Comment by borsboom** [comment]
https://github.com/commercialhaskell/stack/releases/tag/v1.7.1 released.
