### ISSUE TITLE
setup fails on FreeBSD - too many open files

### ISSUE THREAD

**Issue by wfvining** [commercialhaskell/stack#3956]
### General summary/comments (optional)
`stack setup` fails with too many open files on FreeBSD 11.1-RELEASE for any lts resolver > 9.*

### Steps to reproduce

```
$ stack new foo simple
[...]
$ cd foo
$ stack setup
Downloaded lts-11.3 build plan.
[...]

Installing library in /usr/home/xxxx/.stack/programs/x86_64-freebsd/ghc-8.2.2/lib/ghc-8.2.2/Cabal-2.0.1.0

strip:/usr/home/xxxx/.stack/programs/x86_64-freebsd/ghc-8.2.2/lib/ghc-8.2.2/Cabal-2.0.1.0/st9dmhdZ/stV1DOAc/TestSuite__2.o: Too many open files
gmake[1]: *** [ghc.mk:991: install_packages] Error 1
gmake: *** [Makefile:51: install] Error 2

                  
Error: Error encountered while installing GHC with
         gmake install
         run in /usr/home/xxxx/.stack/programs/x86_64-freebsd/ghc-8.2.2.temp/ghc-8.2.2/
       
       The following directories may now contain files, but won't be used by stack:
         - /usr/home/xxxx/.stack/programs/x86_64-freebsd/ghc-8.2.2.temp/
         - /usr/home/xxxx/.stack/programs/x86_64-freebsd/ghc-8.2.2/
```
Changing the resolver in `stack.yaml` to lts-10.* results in the same error. lts-9.20 and below seem to work.

### Expected

Should download and install ghc.

### Stack version

```
$ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

* Official binary, downloaded from stackage.org

**Comment by ketzacoatl** [comment]
@wfvining, apologies if this is a dumb question.. does `ulimit` help, or is the problem in stack itself?

**Comment by arrowd** [comment]
Another thing to try is to add `kern.maxfiles="250000"` into `/boot/loader.conf`. You'd need this anyways if you are running KDE Plasma or any other modern desktop.

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and that it seems to have been answered.
