### ISSUE TITLE
.dump-splice files aren't created for sub-packages when passing --ghc-options='-ddump-splices'

### ISSUE THREAD

**Issue by cdepillabout** [commercialhaskell/stack#3957]
`*.dump-splices` files are not created for sub-packages even when passing the flag `--ghc-options='-ddump-splices'` to `stack`.

### Steps to reproduce

1.  Clone my test repository:

    ```sh
    $ git clone git@github.com:cdepillabout/ddump-splices-test.git
    ```

    Template Haskell is being used in one of the modules in one of the packages:

    ```sh
    $ cat subpackage1/src/Subpackage1Lib.hs
    {-# LANGUAGE TemplateHaskell #-}

    module Subpackage1Lib
        ( subpackage1Func
        ) where

    import Hello

    subpackage1Func :: IO ()
    subpackage1Func = putStrLn $(hello)
    ```

2.  I want to know what code the `$(hello)` splice evaluates to, so I try to run `stack` with the `--ghc-options='-ddump-splices'` option:

    ```sh
    $ stack build --ghc-options='-ddump-splices'
    ```

3.  I expect that this creates a `Subpackage1Lib.dump-splices` file somewhere under `.stack-work/`, so I search for it:

    ```sh
    $ find .stack-work/ -iname "*.dump-splices"
    ```

    I find no `.dump-splices` files.

### Expected

I expect to find `*.dump-splices` files if I pass the flag `--ghc-options='-ddump-splices'` to stack.

### Actual

`stack` (well, GHC) doesn't seem to create any `*.dump-splices` files.

### Stack version

```
$ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
```

### Method of installation

I think I used `stack upgrade`.

**Comment by cdepillabout** [comment]
Passing --ghc-options='-ddump-splices' does seem to work for single-package repositories.

Is there any way to get this to work for multi-package repositories as well?

**Comment by snoyberg** [comment]
Have you checked in the `.stack-work` inside the subpackage?

**Comment by cdepillabout** [comment]
You're right, the `*.dump-splices` files *are* getting created under the `.stack-work/` directory in the subpackage!

I didn't realize that there was a `.stack-work/` directory created inside the subpackages, so I didn't think to look there.

Thanks!

I'll go ahead and close this since it has been answered.
