### ISSUE TITLE
Cannot resolve text dependency with ghc-7.8 solver

### ISSUE THREAD

**Issue by hesselink** [commercialhaskell/stack#396]
To reproduce, in an empty directory:

* `stack new`
* Switch resolver to `ghc-7.8`.
* Add `text-1.2.1.1` to `extra-deps`.
* Edit `new-template.cabal`, add `text` to `build-depends`.
* Run `stack build`.

This gives the following error:

```
$ stack build
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package integer-simple in known packages

--  Failure when adding dependencies:
      text: needed (-any), but couldn't resolve its dependencies
    needed for package: new-template-0.1.0.0

--  Failure when adding dependencies:
      integer-simple: needed (>=0.1 && <0.5), but not present in build plan
    needed for package: text-1.2.1.1
```

My GHC is build with `integer-gmp`, but adding that to the `extra-deps` doesn't work either (the error is the same). Text switches between these with a flag, which cabal-install usually toggles automatically to find a suitable plan.

**Comment by snoyberg** [comment]
stack is always explicit rather than implicit about flags (part of the reproducible build approach), so you have to specify the flag value manually if it's different from the default. This can be done with:

```yaml
flags:
  text:
    integer-simple: false
```

Using `stack init --solver` will handle this for you automatically. Another possibility would be to modify text to turn off that flag by default.

**Comment by hesselink** [comment]
Thanks, that's just what I needed! I tried `stack init --solver`, but there are a couple of cabal files in the project that have outdated dependencies, so it didn't work. So I just copied our current cabal freeze file to the `extra-deps`, and am not trying to get it to work. I'm not there yet but this really helps. Perhaps `stack solver` could also print out the missing flags, just like it does the packages?

**Comment by snoyberg** [comment]
It typically does:

```
$ stack solver
This command is not guaranteed to give you a perfect build plan
It's possible that even with the changes generated below, you will still need to do some manual tweaking
Asking cabal to calculate a build plan, please wait
flags:
  text:
    integer-simple: false
extra-deps:
- text-1.2.1.1
```

Unfortunately, I'm just able to mirror the output of `cabal install --dry-run` right now, so if it doesn't include the flags, I don't include the flags. I don't know the circumstances under which it does and doesn't report those. Hopefully we'll get the SAT solver soon and can use that instead.
