### ISSUE TITLE
[OS X 10.10] Cannot upgrade from 1.2.0 to 1.6.5

### ISSUE THREAD

**Issue by amatecha** [commercialhaskell/stack#3960]
I have Stack 1.2.0 installed on my MacBook Pro (OS X Yosemite 10.10.5) and cannot upgrade to the latest version.

### Steps to reproduce

1. Run `stack upgrade`

### Expected

Expected stack to successfully upgrade

### Actual

Received the following error:
```
Could not parse '/private/var/folders/b1/85jf97wd0rv4762btf6qtcd40000gn/T/stack-upgrade45321/stack-1.6.5/stack.yaml':
Aeson exception:
Error in $['extra-deps'][12]: failed to parse field 'extra-deps': failed to parse field extra-deps: expected PackageIdentifier, encountered Object
See http://docs.haskellstack.org/en/stable/yaml_configuration/.
```

### Stack version

```
$ stack --version
Version 1.2.0, Git revision 241cd07d576d9c0c0e712e83d947e3dd64541c42 (4054 commits) x86_64 hpack-0.14.0
```

### Method of installation

Installed via install shellscript (`curl -sSL https://get.haskellstack.org/ | sh`)

**Comment by borsboom** [comment]
Stack didn't support binary upgrades yet in v1.2.0, and the latest source code is uses newer features and so v1.2.0 doesn't know how to build it.  I'd suggest doing an upgrade using get.haskellstack.org first:

```
curl -sSL https://get.haskellstack.org/ | sh -s - -f
```

Newer versions of Stack will do binary upgrades, so this shouldn't be a problem in the future.

**Comment by amatecha** [comment]
OK, I'll give that a shot!  Thank you for the help :)
