### ISSUE TITLE
Proxy detection on Windows seems working wrong [workaround found]

### ISSUE THREAD

**Issue by cblp** [commercialhaskell/stack#3965]
### General summary/comments

I have a Windows with a corporate NTLM proxy. Most application work with it, stack doesn't.

I've looked to the `http-client` sources, looks like it can get proxy settings from registry, but it doesn't work.

### Steps to reproduce

```
C:\>stack setup --verbose
```

### Expected

OK

### Actual

```
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0
2018-04-10 10:53:58.875376: [debug] Checking for project config at: C:\stack.yaml
@(Stack\Config.hs:842:9)
2018-04-10 10:53:58.882367: [debug] No project config file found, using defaults.
@(Stack\Config.hs:872:13)
2018-04-10 10:53:58.905368: [debug] Run from outside a project, using implicit global project config
@(Stack\Config.hs:559:13)
2018-04-10 10:53:58.916364: [info] Writing implicit global project config file to: C:\sr\global-project\stack.yaml
@(Stack\Config.hs:578:20)
2018-04-10 10:53:58.917364: [info] Note: You can change the snapshot via the resolver field there.
@(Stack\Config.hs:579:20)
2018-04-10 10:53:58.923369: [debug] Downloading snapshot versions file from https://s3.amazonaws.com/haddock.stackage.org/snapshots.json
@(Stack\Config.hs:158:5)
HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept","application/json")]
  path                 = "/haddock.stackage.org/snapshots.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HostCannotConnect "s3.amazonaws.com" [Network.Socket.connect: <socket: 536>: failed (Permission denied (WSAEACCESS))]))
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

### Workaround

Set environment variable `HTTPS_PROXY` to `http://YOURNAME:YOURPASSWORD@YOURPROXY`, YOURNAME must not include your Windows domain.

**Comment by snoyberg** [comment]
Can you try setting the `HTTP_PROXY` environment variable and see if that fixes things?

**Comment by cblp** [comment]
I'm not sure how to specify proxy properly. This proxy URL is surely valid on Linux, I checked.

```
Z:\>set HTTP_PROXY=http://MyDomain\MyLogin:MyPassword@MyProxy

Z:\>stack setup
Writing implicit global project config file to: C:\sr\global-project\stack.yaml
Note: You can change the snapshot via the resolver field there.
HttpExceptionContentWrapper {unHttpExceptionContentWrapper = InvalidProxyEnvironmentVariable "http_proxy" "http://MyDomain\\MyLogin:MyPassword@MyProxy"}
```

**Comment by snoyberg** [comment]
I think the issue is that http-client doesn't support authentication to proxies.

**Comment by cblp** [comment]
How does it work on Linux then?

**Comment by snoyberg** [comment]
You're saying that the same env var on Linux works?

**Comment by snoyberg** [comment]
From some quick testing, it looks like you may be running into backslash escaping differences in the shells.

**Comment by cblp** [comment]
> You're saying that the same env var on Linux works?

Exactly.

In more short way, `https_proxy='MyLogin:MyPassword@Myproxy'` it works on Linux, too.

**Comment by snoyberg** [comment]
And does that value work on Windows?

**Comment by cblp** [comment]
> From some quick testing, it looks like you may be running into backslash escaping differences in the shells.

`"http://MyDomain\\MyLogin:MyPassword@MyProxy:80"` in error message does not look like shell problem. `MyDomain\MyLogin` is a valid user id.

**Comment by cblp** [comment]
Hooray!

Setting `HTTPS_PROXY` (note `S`) without Windows domain name gives the stack access!

Seems valid for as a quick solution, but it would be nice to

1. Allow domain name specification on Windows, as is allowed on Linux.
2. Get proxy settings from registry (or some other Windows API, I'm not sure), as other applications do.

**Comment by snoyberg** [comment]
Such improvements would land in http-client, so it's probably worth moving the discussion there. As the maintainer if that package, I can say that a PR is the best shot at getting such improvements into the library.
