### ISSUE TITLE
Environment variable equivalent for `--nix`

### ISSUE THREAD

**Issue by CMCDragonkai** [commercialhaskell/stack#3980]
Just a feature suggestion.

I know there's the `--nix` flag and the `nix` setting on the `stack.yaml`. However I'd prefer there to be a sort of environment variable to utilise instead. Something like `STACK_USE_NIX=1`.

The reason is that I don't want to force nix onto non-nix users by setting it on the `stack.yaml` and using an alias doesn't get inherited by shell scripts: `alias stack='\stack --nix'`.

**Comment by chris-martin** [comment]
You can also put this into `~/.stack/config.yaml`:

```yaml
nix:
  enable: true
```

**Comment by CMCDragonkai** [comment]
That's what I'd like to avoid.

On 3 May 2018 14:05:44 GMT+10:00, Chris Martin <notifications@github.com> wrote:
>You can also put this into `~/.stack/config.yaml`:
>
>```yaml
>nix:
>  enable: true
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/commercialhaskell/stack/issues/3980#issuecomment-386186448

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by CMCDragonkai** [comment]
This is now available inside Nix. Stack just needs to check this variable:

> nix-shell now sets the IN_NIX_SHELL environment variable during evaluation and in the shell itself. This can be used to perform different actions depending on whether you’re in a Nix shell or in a regular build. Nixpkgs provides lib.inNixShell to check this variable during evaluation.

**Comment by enolan** [comment]
That's set when you're inside `nix-shell`, not just any shell on NixOS. I think a reasonable default is to check whether the host OS is NixOS by checking whether `/run/current-system/nixos-version` exists. Overridden by `config.yaml` and the command line `--nix`/`--no-nix`.

Alternatively, it could check whether `/nix` exists, which would include people running MacOS and other Linux distros that have installed Nix as well. I think the default expectation of those people is Stack works the same whether you install Nix or not, so my preference would be to not do that.

**Comment by CMCDragonkai** [comment]
I thought this PR https://github.com/commercialhaskell/stack/pull/3938 would bring in automatic nix integration without the explicit `--nix` flag. But I tried the recent 1.7.1 release, and it still required `--nix` to work. Or maybe that PR did not make it into 1.7.1? I'm not how to check.

**Comment by snoyberg** [comment]
What are the contents of your `/etc/os-release` file?

**Comment by CMCDragonkai** [comment]
I'm not currently using stack anymore because Nix + Cabal is sufficient for now.

**Comment by snoyberg** [comment]
Understood closing
