### ISSUE TITLE
No information found for ghc-8.4.2 (linux64-tinfo6-nopie)

### ISSUE THREAD

**Issue by iamrecursion** [commercialhaskell/stack#3984]
### General Summary
Stack is telling me that there is no available release for my Arch Linux install, where lts-11.4 works absolutely fine. 

### Steps to reproduce

1. Create a package with resolver pointing at `nightly-2018-04-24`
2. Attempt to build the package

### Expected

It should download the new version GHC associated with the set resolver.

### Actual

```
❯ stack build
No information found for ghc-8.4.2.
Supported versions for OS key 'linux64-tinfo6-nopie': GhcVersion 7.8.4, GhcVersion 7.10.2, GhcVersion 7.10.3, GhcVersion 8.0.1, GhcVersion 8.0.2, GhcVersion 8.2.1, GhcVersion 8.2.2, GhcVersion 8.4.1
```

### Stack version

```
❯ stack --version
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0

```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by iamrecursion** [comment]
CC @wdanilo, who has been having a similar issue with OS Key `linux64-tinfo6`.

**Comment by borsboom** [comment]
The `fedora27` GHC bindist (for tinfo6) isn't available yet.  See [bgamari's comment](https://www.reddit.com/r/haskell/comments/8djds5/announce_ghc_842_released/dxogpx0/).  I'm checking the [GHC 8.4.2 download page](https://downloads.haskell.org/~ghc/8.4.2/) daily for it to appear, and as soon as it does I'll add the metadata for it.

**Comment by iamrecursion** [comment]
Ah, thank you for the update!

**Comment by borsboom** [comment]
The fedora27 bindists have appeared, and I've added them to the `stack setup` metadata (https://github.com/fpco/stackage-content/commit/774b24c6977163fbd8f01de94f99e76b626f51da).  Please give it a try and close this issue if fixed.

**Comment by iamrecursion** [comment]
Works for me, thank you!
