### ISSUE TITLE
Support "resolver: nightly"

### ISSUE THREAD

**Issue by ozgurakgun** [commercialhaskell/stack#3986]
I guess this is not really a bug report, but a feature request.

Running `stack install --resolver nightly` selects the latest nightly resolver, which is great.

Seeing this, I assumed specifying the resolver in the stack.yaml file (`resolver: nightly`) would achieve the same thing, but alas.

This may not be considered good practice by some, but I like to keep a separate stack.yaml file for the latest nightly instead of using the command line argument.

I couldn't find a discussion about this in the issue tracker nor the documentation, apologies if I missed something.

**Comment by DanBurton** [comment]
-1

I would be +1 if we adopted the Haskelly convention of giving this option a name that calls out its unsafety. e.g. `resolver: unsafe-latest-nightly`.

**Comment by DanBurton** [comment]
I expect any given stack.yaml file to represent a specific, reproducible build plan.

I don't care so much about whether a particular command line invocation always creates the same yaml file. I do not see this practice as "unsafe" in the same way.

**Comment by dbaynard** [comment]
I've just encountered this when setting up CI script — in this case, I always want the latest nightly. The best option is to add `--resolver nightly` to the command line arguments.
