### ISSUE TITLE
LGPL licensing restrictions on Windows because of integer-gmp

### ISSUE THREAD

**Issue by quyse** [commercialhaskell/stack#399]
Default version of GHC on Windows produces binaries with integer-gmp linked statically. As integer-gmp's license is LGPL, it means that resulting binaries [should be provided with source code or object files](http://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic). I guess that's not a thing everyone would want.

On UNIXes integer-gmp is linked dynamically, so these restrictions don't apply.

So, in order to fix that we can either:
* Provide a version of GHC which builds Windows executables with integer-gmp linked dynamically (haven't tried, but seems like [it's possible](http://haskell.forkio.com/gmpwindows)).
* Provide a version of GHC [with integer-simple wired in](https://code.google.com/p/hmpfr/wiki/GHCWithoutGMP) instead of integer-gmp (some packages have problems, but overall works good for me).
* Or at least write a big red warning on stack's homepage that your Haskell software on Windows has to be essentially a free software.

Additional Links:
[ReplacingGMPNotes](https://ghc.haskell.org/trac/ghc/wiki/ReplacingGMPNotes)

UPDATE:
* More up-to-date link: [Design/IntegerGmp2](https://ghc.haskell.org/trac/ghc/wiki/Design/IntegerGmp2)
* Clarification, just to avoid confusion: license of integer-gmp (the Haskell library) is BSD3, but it uses C library [The GNU Multiple Precision Arithmetic Library](https://gmplib.org/) which is LGPL.

**Comment by vyp** [comment]
Might help: http://copyleft.org/guide/comprehensive-gpl-guidech12.html#x15-11100011.5

N.B. Have no idea if that website/document can be considered legal advice.

**Comment by andrewthad** [comment]
I would love it if there was a way to use integer-simple with stackage. As a warning, `blaze-textual`, which is supported by stackage, has a [very long standing issue](https://github.com/bos/blaze-textual/issues/8) that prevents it from working with `integer-simple` (and this library is used by `postgres-simple`, which is used by a lot of people). If stackage were to start supporting integer-simple GHC builds, some packages would have to get patched first.

**Comment by snoyberg** [comment]
I don't think a big red warning is the right answer, but having this well documented in the FAQ seems reasonable. I would love to get rid of the LGPL code entirely, but as @andrewthad points out, there's no real chance of being able to do that right now.

@quyse Would you be able to add a FAQ entry for this?

**Comment by kantp** [comment]
Having the option of using integer-simple (without compiling ghc oneself) for those projects that do not rely on integer-gmp would be a nice convenience, and greatly appreciated.

**Comment by snoyberg** [comment]
I have no objection to adding such support. Would someone be able to build
Windows bindists for that?

**Comment by kantp** [comment]
I guess if I want the feature, it's only fair if I provide the windows binaries :-)

Which versions of ghc does stack support? 7.8.4 onwards, or also earlier?

**Comment by snoyberg** [comment]
It theoretically supports any version requested by the user, but 7.8.4 and
on is probably what people care about.

**Comment by quyse** [comment]
@snoyberg I've added a short entry to the FAQ pointing to this issue.

By the way, I was thinking it's Windows-only limitation, as I've checked that on Linux GMP is linked dynamically. But now I found [this comment](https://github.com/Homebrew/homebrew/issues/38315#issuecomment-90099988) which made me worried about OS X. I don't work with OS X, does anyone know about the situation there?

**Comment by snoyberg** [comment]
@quyse Thanks!

**Comment by snoyberg** [comment]
@kantp Has provided the following GHC bindists:

* https://s3-eu-west-1.amazonaws.com/ghc-integer-simple/ghc-7.8.4-x86_64-unknown-mingw32.tar.bz2
* https://s3-eu-west-1.amazonaws.com/ghc-integer-simple/ghc-7.10.1-x86_64-unknown-mingw32.tar.bz2

My thought is that we would add a new command line option that- like `--arch`- would control which GHC to use. Either that, or have a fake OS of windowsnolgpl or something like that. What would help with getting this moving is if others could test out these bindists and report results.

**Comment by quyse** [comment]
@snoyberg @kantp That's great, thanks for getting back so quickly! I just tested your GHC (only 7.10.1 for the moment), and I was able to build and run my project which uses about 30 packages, and I wasn't able to build my another project because of issue with `network`. Quick notes:
* Three packages in my experiment required special care, those are `cryptonite`, `hashable` and `text`. They all have configure flags to disable use of integer-gmp. `hashable` also has a [fix on its github](https://github.com/tibbe/hashable/commit/7409adbd314a1ef8f5aefc643879b6f1c06e02c0) which isn't uploaded to hackage yet, so I had to put it locally. Here is excerpt of stack.yaml worked for me:
```
resolver: nightly-2015-06-23
arch: x86_64
extra-deps: ['cryptonite-0.5', 'hashable-1.2.3.2', 'text-1.2.1.1']
flags:
  cryptonite:
    'integer-gmp': false
  hashable:
    'integer-gmp': false
  text:
    'integer-simple': true
packages:
- '../../thirdparty/tibbe-hashable'
```
* I wasn't able to use `network` package because of well-known issue with it:
```
Configuring network-2.6.2.0...
Setup.hs: The package has a './configure' script. This requires a Unix
compatibility toolchain such as MinGW+MSYS or Cygwin.
```
Usually I workaround this by using `cabal install network --configure-option --build=x86_64-w64-mingw32` in Cygwin, but this time it doesn't work, as there's no cabal, and I wasn't able to construct some similar command line with stack instead of cabal, getting the same error. The strange thing is that with default GHC-7.10.1 downloaded by `stack setup` it installs `network` without any trouble (and without using Cygwin). I was setting up custom GHC by just placing it in PATH:
```
set PATH=D:\programs\ghc-7.10.1\bin;D:\programs\ghc-7.10.1\mingw\bin;D:\programs\ghc-7.10.1\mingw\x86_64-w64-mingw32\bin;D:\programs\ghc-7.10.1\mingw\libexec\gcc\x86_64-w64-mingw32\4.6.3;
```
Am I missing something?

**Comment by snoyberg** [comment]
stack typically solves this by including PortableGit's msys implementation on the PATH, which will allow configure scripts to run. Can you try adding that and trying again?

**Comment by 3noch** [comment]
Would it make sense to add a custom "arch" or "os" for GHC's built with no gmp-integer? You could minimally support the last two GHC versions on whatever OS you have a build for. In other words, could you add an "os" that's "windows-no-gmp" for the time being? Or perhaps add it to the arch? That would basically make `stack` the single best way to get a **commercial**-haskell GHC.

**Comment by 3noch** [comment]
Just realized you already had that idea. I'm all for it, or something like it.

**Comment by 3noch** [comment]
If I can get builds working, I'll supply as many builds for Windows as my machine can crank out. This applies to MinGHC too.

**Comment by hvr** [comment]
Minor note:

https://ghc.haskell.org/trac/ghc/wiki/ReplacingGMPNotes is kinda obsolete as the GMP library was rewritten from scratch for GHC 7.10 (https://ghc.haskell.org/trac/ghc/wiki/Design/IntegerGmp2),

Personally, I'd like to get rid of `integer-simple` altogether (to avoid having different surface APIs), and rather be able to select the `integer-gmp` backend at link-time in the same way you can switch between e.g. the threaded and the non-threaded runtime. Therefore allow you to say e.g. `ghc --make -O -finteger-library=bsdnt Hello.hs` and then not link the GMP into your binary, but rather a e.g. a `bsdnt` based implementation of the GMP primitives. It's not difficult to implement... but as usual time is a scarce resource :-/

**Comment by kantp** [comment]
@hvr That sounds like the Right Thing to do, very nice.

In the meantime, if there is a switch for the integer library, I think it would make sense to have this orthogonal to the choice of the operating system.

**Comment by 3noch** [comment]
@quyse hashable was just updated, now for a stackage release including it.

**Comment by 3noch** [comment]
@snoyberg... Wow. You don't miss a beat. Stackage part already being done

**Comment by snoyberg** [comment]
I can't take credit, it's just the daily Stackage builds doing their thing.

IIUC, this means that the LGPL concern will not apply to the normal GHC bindist in the near future. Is that the case? I should probably say that IANAL, so some of this goes over my head. Perhaps we can have a thread on ghc-dev about this, I'd definitely like to understand this better and understand what work still needs to be done.

**Comment by hvr** [comment]
@snoyberg feel free to start a thread, I'll chime in and try to answer as best as I can any questions you put forward

**Comment by tejon** [comment]
[Hackage says](https://hackage.haskell.org/package/integer-gmp) the license is BSD3, and it says so for both versions...

**Comment by quyse** [comment]
@tejon Sorry, I just added an update to the first post with clarification about integer-gmp and GMP. I was using names integer-gmp and GMP interchangeably.

**Comment by quyse** [comment]
@snoyberg Yes, finally I was able to install `network` from MSYS command line, thanks for help! For me everything works now. As a side note, maybe it's worth to implement `--with-compiler` setting similar to cabal's? It would be more convenient to use non-standard compiler rather than manually adding it to PATH, and stack would treat it in the same way as automatically installed ones, i.e. add msys and stuff.

@3noch Cool, that's fast :)

**Comment by 3noch** [comment]
So all we need to do is not link in integer-gmp? No special build of GHC required?

**Comment by 3noch** [comment]
@snoyberg How do you come to the conclusion "IIUC, this means that the LGPL concern will not apply to the normal GHC bindist in the near future." Are you assuming that folks who need this feature (I'm one!) will just install custom builds of GHC?

**Comment by snoyberg** [comment]
I understood Herbert as saying replacing the LGPL library with something
else would become a link time option, in which case we'd all be using the
same GHC and just changing the linker flags when desired.

**Comment by 3noch** [comment]
I see your point. In future GHC releases this will be solved in a nice way. But we still need to get custom builds of 7.8.4, 7.10.1, etc.

**Comment by snoyberg** [comment]
If we can get it into 7.10.3, I'd consider it good enough to be honest. It
seems that even with 7.10.1 we should be able to do something better than
reverting to integer-simple.

**Comment by 3noch** [comment]
I'm all ears for what could be done with 7.10.1. I'm under the impression it's still in the same boat as 7.8.4, albeit with a better implementation of GMP.

**Comment by 3noch** [comment]
This actually correlates to the issue with `stack` only looking at the first GHC on the `PATH`. If I were to install a custom build of for both 32-bit and 64-bit GHC and put them on my `PATH`, `stack` would only ever find one of them. At that point my only option is to switch between the two GHC outside of `stack` *and* tell stack which architecture to expect.

**Comment by 3noch** [comment]
Correction, I probably would not need to tell `stack` which architecture to expect since it wouldn't be relying on its own installations of GHC at all.

**Comment by 3noch** [comment]
If I supplied builds for Windows, would you even consider hosting them so `stack` can use them directly? That would stick require some sort of hack (or feature) to tell stack to use the custom ones.

**Comment by snoyberg** [comment]
I have no problem with that. My big concern with integer-simple is that it
will be incapable of building lots of projects

**Comment by 3noch** [comment]
Yes, that's true. However, when it matters, LGPL is a deal-breaker and libraries can often be patched/replaced.

**Comment by kantp** [comment]
@3noch Absolutely.

**Comment by Jookia** [comment]
Uhh, the statically linking the LGPL doesn't mean your software has to be free - you just have to ship your object files so users can replace the LGPLed portions.

**Comment by 3noch** [comment]
@kantp or anyone else willing to help me get GHC building? I'm having troubles :cry: http://lpaste.net/135610

**Comment by kantp** [comment]
Since it was mentioned here by @andrewthad, that issue in blaze-textual has just been resolved, and blaze-textual-0.2.1.0 supports integer-simple.

**Comment by andrewthad** [comment]
woot!

**Comment by 3noch** [comment]
@kantp Are you able to provide 32-bit versions the bindists you already supplied? I'm having a hard time getting working GHC builds.

**Comment by kantp** [comment]
@3noch Sorry, I just noticed your comment above I didn't respond to. Was that failed build on a 32 bit machine?

**Comment by 3noch** [comment]
@kantp My first attempts at building were for 64-bit. Once I got the build to finish I moved on to 32-bit since those are the remaining builds we need before `stack` can fully support both LTS 2 and nightly with a integer-simple version. I was building 32-bit on a 64-bit machine and realized that the build system was getting quite confused. I'm about to start over on a 32-bit VM in hopes it doesn't get confused. However, if you already have everything setup for these builds, you can produce them much faster than I can (plus I don't really know what I'm doing...yet!). I'll keep trying until I get something working or someone else beats me to it.

P.S. That build error was due to a bug in the build script which was solved by cherry-picking some future commit (@ezyang pointed me to that solution in ghc-devs).

**Comment by 3noch** [comment]
Ok I have a build of 32-bit GHC 7.10.1. Now working on 32-bit 7.8.4. @snoyberg We now have enough to at least support this natively for `nightly` snapshots. I imagine the backend work is pretty straightforward.

**Comment by 3noch** [comment]
If we support nightly snapshots at this point, other resolvers will simply report that GHC is not available for that OS/arch/whatever.

**Comment by 3noch** [comment]
They can be added after the fact without any new releases.

**Comment by 3noch** [comment]
@snoyberg The 32-bit build is temporarily hosted (here)[https://drive.google.com/file/d/0B1Q2wj7eQ5WbVVJOeVdVZUxQZ2s/view?usp=sharing].

**Comment by snoyberg** [comment]
I've uploaded this to:

https://s3.amazonaws.com/download.fpcomplete.com/ghc/ghc-7.10.1-i386-unknown-mingw32-integer-simple.tar.bz2

**Comment by snoyberg** [comment]
I've also just pushed the fake OS `windowsintegersimple` so that a command like `stack build --os windowsintegersimple` should pull the right image. I'm doing some testing, though others are welcome to give it a shot too.

**Comment by 3noch** [comment]
Do you care if I keep the `doc` folder in these bindists? I doubt folks will be referring to the mostly broken docs in a privately maintained `stack` folder.

**Comment by snoyberg** [comment]
I have no opinion on the matter. Since you're driving the usage of this right now, I'd say trust your judgement regarding what functionality is necessary.

**Comment by 3noch** [comment]
Ok, I'll probably get rid of it since it will make the files smaller.

**Comment by 3noch** [comment]
Looks like `stack` is deducing that I need `unix` to be build, which obviously fails:
```
> stack build
th-lift-0.7.2: configure
old-time-1.1.0.3: configure
th-lift-0.7.2: build
th-lift-0.7.2: install
utf8-string-1: configure
old-time-1.1.0.3: build
mtl-2.2.1: configure
utf8-string-1: build
js-flot-0.8.3: configure
mtl-2.2.1: build
syb-0.4.4: configure
old-time-1.1.0.3: install
js-flot-0.8.3: build
utf8-string-1: install
unix-2.7.1.0: configure
syb-0.4.4: build
js-flot-0.8.3: install
mtl-2.2.1: install
syb-0.4.4: install
text-1.2.1.1: configure
unix-2.7.1.0: build
happy-1.19.5: configure
text-1.2.1.1: build
th-expand-syns-0.3.0.6: configure
happy-1.19.5: build
th-expand-syns-0.3.0.6: build
th-expand-syns-0.3.0.6: install
happy-1.19.5: install
text-1.2.1.1: install
Progress: 10/27
--  While building package unix-2.7.1.0 using:
      C:\\Users\\Elliot Cameron\\AppData\\Roaming\\stack\\programs\\i386-windowsintegersimple\\ghc-7.10.1\\bin\\runhask
ll.exe -package=Cabal-1.22.2.0 -clear-package-db -global-package-db -package-db=C:\Users\Elliot Cameron\AppData\Roaming
stack\snapshots\i386-windowsintegersimple\nightly-2015-07-02\7.10.1\pkgdb\ C:\Users\ELLIOT~1\AppData\Local\Temp\stack12
04\unix-2.7.1.0\Setup.hs --builddir=.stack-work\dist\i386-windowsintegersimple\Cabal-1.22.2.0\ build
    Process exited with code: ExitFailure 1
    Logs have been written to: "C:\\Code\\windows-client\\.stack-work\\logs\\unix-2.7.1.0.log"

    Configuring unix-2.7.1.0...
    configure: WARNING: unrecognized options: --with-compiler, --with-gcc
    checking for gcc... gcc
    checking whether the C compiler works... yes
    checking for C compiler default output file name... a.exe
    checking for suffix of executables... .exe
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C compiler... yes
    checking whether gcc accepts -g... yes
    checking for gcc option to accept ISO C89... none needed
    checking how to run the C preprocessor... gcc -E
    checking for grep that handles long lines and -e... /usr/bin/grep
    checking for egrep... /usr/bin/grep -E
    checking for ANSI C header files... yes
    checking for sys/types.h... yes
    checking for sys/stat.h... yes
    checking for stdlib.h... yes
    checking for string.h... yes
    checking for memory.h... yes
    checking for strings.h... yes
    checking for inttypes.h... yes
    checking for stdint.h... yes
    checking for unistd.h... yes
    checking dlfcn.h usability... no
    checking dlfcn.h presence... no
    checking for dlfcn.h... no
    checking for an ANSI C-conforming const... yes
    checking for special C compiler options needed for large files... no
    checking for _FILE_OFFSET_BITS value needed for large files... unknown
    checking for _LARGE_FILES value needed for large files... unknown
    checking dirent.h usability... yes
    checking dirent.h presence... yes
    checking for dirent.h... yes
    checking fcntl.h usability... yes
    checking fcntl.h presence... yes
    checking for fcntl.h... yes
    checking grp.h usability... no
    checking grp.h presence... no
    checking for grp.h... no
    checking limits.h usability... yes
    checking limits.h presence... yes
    checking for limits.h... yes
    checking pwd.h usability... no
    checking pwd.h presence... no
    checking for pwd.h... no
    checking signal.h usability... yes
    checking signal.h presence... yes
    checking for signal.h... yes
    checking for string.h... (cached) yes
    checking sys/resource.h usability... no
    checking sys/resource.h presence... no
    checking for sys/resource.h... no
    checking for sys/stat.h... (cached) yes
    checking sys/times.h usability... no
    checking sys/times.h presence... no
    checking for sys/times.h... no
    checking sys/time.h usability... yes
    checking sys/time.h presence... yes
    checking for sys/time.h... yes
    checking sys/utsname.h usability... no
    checking sys/utsname.h presence... no
    checking for sys/utsname.h... no
    checking sys/wait.h usability... no
    checking sys/wait.h presence... no
    checking for sys/wait.h... no
    checking bsd/libutil.h usability... no
    checking bsd/libutil.h presence... no
    checking for bsd/libutil.h... no
    checking libutil.h usability... no
    checking libutil.h presence... no
    checking for libutil.h... no
    checking pty.h usability... no
    checking pty.h presence... no
    checking for pty.h... no
    checking utmp.h usability... no
    checking utmp.h presence... no
    checking for utmp.h... no
    checking termios.h usability... no
    checking termios.h presence... no
    checking for termios.h... no
    checking time.h usability... yes
    checking time.h presence... yes
    checking for time.h... yes
    checking for unistd.h... (cached) yes
    checking utime.h usability... yes
    checking utime.h presence... yes
    checking for utime.h... yes
    checking for getgrgid_r... no
    checking for getgrnam_r... no
    checking for getpwnam_r... no
    checking for getpwuid_r... no
    checking for getpwnam... no
    checking for getpwuid... no
    checking for getpwent... no
    checking for getgrent... no
    checking for lchown... no
    checking for setenv... no
    checking for sysconf... no
    checking for unsetenv... no
    checking for clearenv... no
    checking for nanosleep... no
    checking for ptsname... no
    checking for setitimer... no
    checking for readdir_r... no
    checking for telldir... yes
    checking for seekdir... yes
    checking for execvpe... yes
    checking for struct stat.st_atim... no
    checking for struct stat.st_mtim... no
    checking for struct stat.st_ctim... no
    checking for struct stat.st_atimespec... no
    checking for struct stat.st_mtimespec... no
    checking for struct stat.st_ctimespec... no
    checking for struct stat.st_atimensec... no
    checking for struct stat.st_mtimensec... no
    checking for struct stat.st_ctimensec... no
    checking for struct stat.st_atime_n... no
    checking for struct stat.st_mtime_n... no
    checking for struct stat.st_ctime_n... no
    checking for struct stat.st_uatime... no
    checking for struct stat.st_umtime... no
    checking for struct stat.st_uctime... no
    checking for struct passwd.pw_gecos... no
    checking for utimensat... no
    checking for futimens... no
    checking for lutimes... no
    checking for futimes... no
    checking for mkstemps... no
    checking for mkdtemp... no
    checking for fsync... no
    checking for fdatasync... no
    checking for posix_fadvise... no
    checking for posix_fallocate... no
    checking for library containing shm_open... no
    checking value of SIGABRT... 22
    checking value of SIGALRM... -1
    checking value of SIGBUS... -1
    checking value of SIGCHLD... -1
    checking value of SIGCONT... -1
    checking value of SIGFPE... 8
    checking value of SIGHUP... -1
    checking value of SIGILL... 4
    checking value of SIGINT... 2
    checking value of SIGKILL... -1
    checking value of SIGPIPE... -1
    checking value of SIGQUIT... -1
    checking value of SIGSEGV... 11
    checking value of SIGSTOP... -1
    checking value of SIGTERM... 15
    checking value of SIGTSTP... -1
    checking value of SIGTTIN... -1
    checking value of SIGTTOU... -1
    checking value of SIGUSR1... -1
    checking value of SIGUSR2... -1
    checking value of SIGPOLL... -1
    checking value of SIGPROF... -1
    checking value of SIGSYS... -1
    checking value of SIGTRAP... -1
    checking value of SIGURG... -1
    checking value of SIGVTALRM... -1
    checking value of SIGXCPU... -1
    checking value of SIGXFSZ... -1
    checking value of SIG_BLOCK... -1
    checking value of SIG_SETMASK... -1
    checking value of SIG_UNBLOCK... -1
    checking value of SIGINFO... -1
    checking value of SIGWINCH... -1
    checking for _SC_GETGR_R_SIZE_MAX... no
    checking for _SC_GETPW_R_SIZE_MAX... no
    checking return type of usleep... int
    checking return type of unsetenv... int
    checking for RTLD_NEXT from dlfcn.h... no
    checking for RTLD_DEFAULT from dlfcn.h... no
    checking for openpty... no
    checking for openpty in -lutil... no
    checking for openpty in -lbsd... no
    checking for /dev/ptmx... yes
    checking for /dev/ptc... no
    checking for library containing dlopen... no
    checking build system type... i686-pc-msys
    checking host system type... i686-pc-msys
    checking target system type... i686-pc-msys
    checking for library containing sem_close... no
    configure: Not found
    configure: creating ./config.status
    config.status: creating unix.buildinfo
    config.status: creating include/HsUnixConfig.h
    configure: WARNING: unrecognized options: --with-compiler, --with-gcc
    Setup.hs: Package unix-2.7.1.0 can't be built on this system.
```

**Comment by snoyberg** [comment]
I know the problem, but can't fix it until tomorrow. We need to have
special handling in Stack.Package for OtherOS "windowsintegersimple" when
resolving flags. This shouldn't be too hard, want to take a crack at it?

**Comment by 3noch** [comment]
Just to prevent confusion, this is still not quite right. Somewhere in the build process `stack` still gets confused, probably because the fake OS is not entirely understood by the system as it should be. More details are in #495.

**Comment by mwu-tow** [comment]
There's one question that's puzzling me. Does anyone know why on Windows all dependencies are statically linked into the final executable?

On Linux there is no issue, because dependencies are dynamically loaded shared libraries. It has also several other advantages, like smaller file size, possibility of linking with multiple Haskell shared libraries (on Windows it would cause errors due to duplicated symbol definitions) and so on.

I checked the relevant documentation page for GHC and it was changed between GHC 7.0.3 and 7.0.4. In 7.0.3 it said 

> In principle you can use -shared without -dynamic in the link step. That means to statically link the rts all the base libraries into your new shared library. This would make a very big, but standalone shared library. Indeed this is exactly what we must currently do on Windows where -dynamic is not yet supported. 

The documention from 7.0.4 removed all mentions of `-dynamic` not being supported on Windows. So I'd guess it was fixed.

So I wonder why it is still not used? Wouldn't compiling the packages with `-dynamic` on Windows solve the issue discussed here? Are there any known reasons or it was simply "no one tried to switch the flag" for Windows GHC builds?

**Comment by 3noch** [comment]
On Windows, even if you use a DLL to get libgmp, it's highly likely that you will *also* be the one conveying this DLL to the end user (via some installer, etc). According to the license, that case is considered equal with conveying an executable that statically links with libgmp. The *only* way to avoid this problem entirely is to use some third-party system to convey libgmp, as you cannot do it yourself. I suppose that on Linux this is accomplished via the package manager. On Windows, it's rare that you have this luxury. Of course, for those who are in a scenario where this limitation is not too onerous, then there are solutions that would help. For many (like myself), however, we cannot expect the end user to install any third-party tooling, etc. as part of our installation process.

**Comment by ezyang** [comment]
I believe this is the reason: https://ghc.haskell.org/trac/ghc/wiki/DynamicByDefault/Windows

Also, `-dynamic-too` doesn't work: https://ghc.haskell.org/trac/ghc/wiki/DynamicGhcPrograms

**Comment by tejon** [comment]
> it's highly likely that you will also be the one conveying this DLL to the end user (via some installer, etc). According to the license, that case is considered equal with conveying an executable that statically links with libgmp.

That's not at all how I read [section 4 of the LGPL](http://www.gnu.org/licenses/lgpl-3.0.en.html#section4), and (brief) Googling doesn't turn up anything that supports your interpretation. Do you have a source?

**Comment by Jookia** [comment]
The GPLv3 and LGPLv3 don't explicitly state anything about static or dynamic linking, and in either case the most you have to provide is instructions on how to replace the library - you don't need to ship third party tooling. Here's a good link explaining how to comply: https://copyleft.org/guide/comprehensive-gpl-guidech12.html#x15-11100011.5

**Comment by 3noch** [comment]
@tejon

> If you distribute the library along with your program, or are the separate distributor of the work in another context or as another product, you must distribute its corresponding source under the terms of LGPLv3 or GPLv3-or-later.

From [here](http://copyleft.org/guide/comprehensive-gpl-guidech12.html#x15-11100011.5).

**Comment by Jookia** [comment]
That's not equal as there's clearly two different cases. Even so, that doesn't say you have to do more than give installation instructions and library source code and why that's a problem.

**Comment by 3noch** [comment]
The first case essentially ends with "this falls under the second case," so I consider them to have equal LGPL implications. My point is merely that *some* software distributions can't easily rely on some third-party distribution to convey the LGPL'ed library. In my case, the end user barely knows how to use a computer in the first place!

**Comment by Jookia** [comment]
You don't need a third party distribution to convey the LGPLed library - just package source and installation information with your software. What's the problem?

**Comment by 3noch** [comment]
That's complying with the requirements of the LGPL and the reason this thread exists...no?

**Comment by Jookia** [comment]
From what I can gather this thread exists to work on allowing removal of an LGPLed library rather than focusing on compliance given people don't want to bother complying. That's okay but I'm just trying to clarify what compliance actually is.

I was responding to you writing "For many (like myself), however, we cannot expect the end user to install any third-party tooling, etc. as part of our installation process." which didn't make much sense at all and seemed to be an incorrect assessment of what it takes to comply, so hopefully with clarification you can comply - I thought this might help in solving the issue you were having.

**Comment by tejon** [comment]
@3noch: Ahh, I think you're tripping over commas. The pronoun matches the object, and the object is not your program:

> If you distribute **the library** along with your program, [...] you must distribute **its** corresponding source

**Comment by 3noch** [comment]
@tejon I hope you're right. Can anyone confirm?

**Comment by 3noch** [comment]
@tejon I think I'm beginning to see it from your perspective. If that's the case, then this *could* be really good news for folks like me, aside from the points brought up by @mwu-tow and @ezyang.

**Comment by Jookia** [comment]
The section says this:

0) Convey the Minimal Corresponding Source under the terms of this License, and the Corresponding Application Code in a form suitable for, and under terms that permit, the user to recombine or relink the Application with a modified version of the Linked Version to produce a modified Combined Work, in the manner specified by section 6 of the GNU GPL for conveying Corresponding Source.

I think this is clear that that's the case.

**Comment by snoyberg** [comment]
Given the work on alternative bindists, should this be closed?

**Comment by rvion** [comment]
would [ghc-musl](https://github.com/nilcons/ghc-musl) make a bette bindist default ?

**Comment by snoyberg** [comment]
I don't think so:

* It's much less tested than standard GHC
* I don't think it works at all on Windows
* Static linking would just make the specific problem being discussed (LGPL libraries being linked in) even worse

**Comment by rvion** [comment]
Thanks for those infos
(not sure about the 3rd point: musl seems to be able to dynamic link anything just fine)

**Comment by snoyberg** [comment]
No objection given to my question about closing.

**Comment by varosi** [comment]
> stack setup  --os windowsintegersimple
> I don't know how to install GHC for (OtherOS "windowsintegersimple",X86_64), please install manually

How it should be used with stack 1.1.2?

**Comment by borsboom** [comment]
@varosi: Don't have a Windows box available right now to try it, but it should be

```
stack setup --ghc-variant=integersimple
```

**Comment by varosi** [comment]
@borsboom, I have got this:

> Downloaded lts-6.4 build plan.
> Fetching package index ...remote: Counting objects: 1590, done.
> remote: Compressing objects: 100% (1192/1192), done.
> rRemote: Total 1590 (delta 403), reused 1427 (delta 365), pack-reused 0
> Receiving objects: 100% (1590/1590), 500.58 KiB | 330.00 KiB/s, done.
> Resolving deltas: 100% (403/403), completed with 199 local objects.
> From https://github.com/commercialhaskell/all-cabal-hashes
>  - [tag update]      current-hackage -> current-hackage
> Fetched package index.
> Populated index cache.
> No information found for ghc-7.10.3.
> Supported versions for OS key 'windows64-integersimple': GhcVersion 7.8.4, GhcVersion 7.10.1, GhcVersion 7.10.2

**Comment by borsboom** [comment]
Looks like @kantp provided the past integer-simple bindists, but we have not received any yet for GHC 7.10.3 or GHC 8.0.1.

**Comment by 3noch** [comment]
I provided the bindists for 7.10.2, but unfortunately I no longer work with Windows and don't have access to my build machines.

**Comment by borsboom** [comment]
@3noch: Ah sorry, I missed that in reading the history of this issue.

In any case, we'll be happy to add the metadata for 7.10.3 and 8.0.1 windows-integersimple bindists when we're provided with them (and, you can always add `setup-info` to your own config for custom bindists).

**Comment by 3noch** [comment]
@borsboom: I followed the instructions on the GHC wiki (https://ghc.haskell.org/trac/ghc/wiki/Building/Preparation/Windows) without too much trouble. Changing out the configuration to use `integer-simple` is not hard, but I don't recall the details. Hopping on to the GHC devs mailing list (I think they have an IRC channel too IIRC). For 32-bit bindists I literally fired up a 32-bit Windows VM, but that might be unnecessary.

**Comment by leohaskell** [comment]
I'd like to provide a 7.10.3 windows-integersimple bindist if possible. Are there any special settings for the other bindists used by stack? BuildFlavor, etc..

**Comment by leohaskell** [comment]
Here is an [integer simple bindist](https://drive.google.com/open?id=0Bx1PZr9g0_7cZjU2MzhWanREMEk) built with the default build options. Please notify me if something else needs to be done.

**Comment by borsboom** [comment]
@leohaskell: did you test this bindist with `stack setup`?  You can do so using  `stack setup --stack-setup-yaml <<<PATH>>>` (with the `<<<PATH>>>` pointing to a modified version of [stack-setup-2.yaml](https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml) that adds your new bindist?  If so, I'll put it somewhere official and add it to the normal stack-setup-2.yaml.

**Comment by leohaskell** [comment]
The following is working:
```
stack setup --stack-setup-yaml <path-to-modified-setup.yaml> --ghc-variant=integersimple
```

**Comment by leohaskell** [comment]
@borsboom, it's still not official?

**Comment by borsboom** [comment]
@leohaskell: Sorry for the delay.  I've put it at https://github.com/commercialhaskell/ghc/releases/download/ghc-7.10.3-release/ghc-7.10.3-x86_64-unknown-mingw32-integer-simple.tar.bz2 and added it to https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml.

**Comment by leohaskell** [comment]
@borsboom, [here](https://drive.google.com/open?id=0Bx1PZr9g0_7cZFRCcmRhSVZvY2M) is a ghc-8.0.1 integersimple bindist (tested with `stack setup`).

**Comment by borsboom** [comment]
@leohaskell Thanks, I've uploaded it to https://github.com/commercialhaskell/ghc/releases/download/ghc-8.0.1-release/ghc-8.0.1-x86_64-unknown-mingw32-integer-simple.tar.xz and added a reference to https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml.

**Comment by PierreVDL** [comment]
With stack [[Version 1.3.0, Git revision 99b910d3c8e183aa376cb1e6f0341d86aed6d00e x86_64 hpack-0.15.0]]
I get when typing 
> stack setup --stack-setup-yaml stack.yaml --ghc-variant=integersimple

```
Warning: stack.yaml: Unrecognized fields in SetupInfo: extra-deps, extra-package-dbs, flags,
 packages, resolver
Unable to find installation URLs for OS key: windows64-integersimple
```
What am I doing wrong?

**Comment by snoyberg** [comment]
I don't think you want to have the `--stack-setup-yaml` argument, especially if it's pointed to your project's stack.yaml file.

**Comment by quyse** [comment]
I have a problem with CI builds on Windows. As I need to set flags for certain packages to allow them to build with integersimple (`text`, `hashable`, `cryptonite`, etc...), these packages and all packages transitively depending on them automatically become `extra-deps`, and compiled binaries end up in `.stack-work` directory. Now the problem is that `.stack-work` got removed (intentionally) before every CI build, for build to be certainly clean, so all those packages got rebuilt every time, which takes forever.

Normally (without integersimple) packages from stackage go into snapshot directories and not cleaned up, so builds on Linux are fast. I've seen the "extensible snapshot" feature which should allow me to make a derived snapshot with changed flags, so all those packages will go to snapshot directory, and therefore won't be rebuilt every time. Unfortunately last time I tried that feature it didn't support setting `ghc-variant` for a custom snapshot. Could such a setting be added please? Or maybe I'm missing something obvious and there is other way?
