### ISSUE TITLE
integer-gmp: unknown symbol `___gmp_rands', when using stack to test haddock

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack#3990]
### General summary/comments

There may be an issue in the way stack installs integer-gmp for ghc-8.4.2.

I'm seeing a strange error message when attempting to run haddock's test suite.

### Steps to reproduce

See the repro as reported on the haddock issue tracker:
https://github.com/haskell/haddock/issues/811
(Context: `git clone https://github.com/haskell/haddock && cd haddock`)

### Expected

This test suite should pass.

### Actual

The test suite fails with the following obscure error message:

```
haddock:
lookupSymbol failed in relocateSection (RELOC_GOT)
/Users/dan/.stack/programs/x86_64-osx/ghc-8.4.2/lib/ghc-8.4.2/integer-gmp-1.0.2.0/HSinteger-gmp-1.0.2.0.o: unknown symbol `___gmp_rands'
```

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

`stack upgrade` (on OSX)

**Comment by Tehnix** [comment]
To consolidate the issues here, these are related:

- https://github.com/sol/doctest/issues/199
- https://github.com/haskell/haddock/issues/767
- https://github.com/haskell/haddock/issues/811

And this GHC trac ticket https://ghc.haskell.org/trac/ghc/ticket/15105.

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and because package `haddock-test` is deprecated: https://hackage.haskell.org/package/haddock-test. I could not build `haddock-test` for reasons unrelated to the issue.
