### ISSUE TITLE
Stack build failure and an unusual version number

### ISSUE THREAD

**Issue by alexeyzab** [commercialhaskell/stack#3991]
Hi! I've run into the following issue while trying to build `stack` for the 2018-04-28 nightly stackage build: https://github.com/fpco/stackage/issues/3563

I've also noticed that the current `stack` version on hackage is `9.9.9`, this doesn't seem right so I wanted to mention it: https://hackage.haskell.org/package/stack-9.9.9

EDIT: On second thought, that version number is probably irrelevant here.

**Comment by mihaimaruseac** [comment]
Oh, the `stack 9.9.9.9` is my fault, I shouldn't have removed that constraint.
