### ISSUE TITLE
src/Stack/Prelude.hs:15:5: error: Ambiguous occurrence `stripCR'

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#3994]
```
Building library for stack-1.7.1..
[  1 of 125] Compiling Network.HTTP.StackClient ( src/Network/HTTP/StackClient.hs, dist/dist-sandbox-66ca79b2/build/Network/HTTP/StackClient.o )
[  2 of 125] Compiling Hackage.Security.Client.Repository.HttpLib.HttpClient ( src/Hackage/Security/Client/Repository/HttpLib/HttpClient.hs, dist/dist-sandbox-66ca79b2/build/Hackage/Security/Client/Repository/HttpLib/HttpClient.o )
[  3 of 125] Compiling Path.Extra       ( src/Path/Extra.hs, dist/dist-sandbox-66ca79b2/build/Path/Extra.o )
[  4 of 125] Compiling Paths_stack      ( dist/dist-sandbox-66ca79b2/build/autogen/Paths_stack.hs, dist/dist-sandbox-66ca79b2/build/Paths_stack.o )
[  5 of 125] Compiling Stack.Prelude    ( src/Stack/Prelude.hs, dist/dist-sandbox-66ca79b2/build/Stack/Prelude.o )
src/Stack/Prelude.hs:15:5: error:
    Ambiguous occurrence `stripCR'
    It could refer to either `X.stripCR',
                             imported from `RIO' at src/Stack/Prelude.hs:19:1-42
                             (and originally defined in `RIO.Prelude.Text')
                          or `Stack.Prelude.stripCR',
                             defined at src/Stack/Prelude.hs:153:1
   |
15 |   , stripCR
   |     ^^^^^^^
```

**Comment by juhp** [comment]
I think because I was building with rio-0.0.3.0.

**Comment by borsboom** [comment]
Why are you building with an old version of `rio`?  `stack.yaml` specifies `rio-0.1.1.0`.

**Comment by juhp** [comment]
Okay I think I can use cabal.config to allow me to build with cabal: I don't want to build stack with stack. :)

**Comment by borsboom** [comment]
The package on Hackage also has version bounds set, or you can use https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-sdist-1.tar.gz which also has version bounds in the contained `stack.cabal` file.   Won't guarantee you'll get a `stack` that behaves the same as one build using `stack.yaml` though, but it will build.  If you need to bootstrap and are building binaries for distribution, I'd recommend first building with cabal-install and then using the resulting `stack` binary to rebuild itself.

**Comment by juhp** [comment]
I am building from Hackage ;-)

**Comment by juhp** [comment]
Nevermind I worked it out: - I need the revised .cabal file ;-)
