### ISSUE TITLE
Build fails with internal libraries that aren't dependencies

### ISSUE THREAD

**Issue by KaneTW** [commercialhaskell/stack#3996]
Test case: https://github.com/KaneTW/stack-internal-lib-bug

`cabal new-build` succeeds.

**Comment by KaneTW** [comment]
There seems to be an issue with dependency resolution. Specifically, sublibs don't count as dependencies that have to be built.

**Comment by mihaimaruseac** [comment]
Thanks for the report. I was able to reproduce and I'll try to get a fix.

**Comment by mihaimaruseac** [comment]
Solved in #4033

**Comment by afcowie** [comment]
Tested here. At first it _failed_ (ie, no change) but it seemed to be using precompiled (thus buggy?) **haddock-library** artifacts. I manually nuked anything by that name in _~/.stack_ with `find ~/stack -name 'haddock-library-*' -type d -print0 | xargs -0 rm --dontcopyandpastethis` (which I'm sure was overkill) and although `stack build` works it is _still failing_ for `stack haddock`.

Please re-open?

**Comment by mihaimaruseac** [comment]
There seems to be another bug regarding pre-existing artifacts. Will test that too and open an issue.

I haven't yet managed to get to `stack haddock`, it's in the plan for this week.
