### ISSUE TITLE
stack upload requires a build plan

### ISSUE THREAD

**Issue by meteficha** [commercialhaskell/stack#400]
On a package without a `stack.yaml`, on a machine without GHC 7.8, `stack upload` doesn't work:

```
$ stack upload
Using resolver: lts-2.15 from global config file: /home/felipe/.stack/global/stack.yaml
Caching build plan
Populated index cache.    
GHC version mismatched, found 7.10.1 (x86_64), but expected version 7.8.4 (x86_64) (based on resolver setting in /home/felipe/.stack/global/stack.yaml). Try running stack setup
```

The older `stackage upload` won't complain:

```
$ stackage upload
Warning: Cannot run preprocessors. Run 'configure' command first.
Building source dist for fb-persistent-0.3.5...
Source tarball created:
/tmp/stackage-upload-tarball13706/fb-persistent-0.3.5.tar.gz
Uploading /tmp/stackage-upload-tarball13706/fb-persistent-0.3.5.tar.gz... done!
```

I'm not sure of the implications of not having a valid build plan before uploading.

**Comment by DanBurton** [comment]
Sounds like a regression to me.

**Comment by snoyberg** [comment]
Fixed for now I believe, though we'll have to think harder about the right way to solve this once #313 becomes a reality. @meteficha confirmed?

**Comment by meteficha** [comment]
I'm take your word for it after reading the commit and seeing it makes sense.  Thanks!
