### ISSUE TITLE
Windows installer not signed

### ISSUE THREAD

**Issue by letmaik** [commercialhaskell/stack#4000]
The pre-built Windows installer is currently not signed which flags up in Windows Defender and requires to confirm an exception.
To create more trust in the binaries it would be good if they could be signed using a certificate (not self-signed).

**Comment by borsboom** [comment]
The options for affordable windows code signing certs for open source projects seem to be rather limited these days.  I tried getting one from certum.eu but thus far have not managed to get it to work.

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and the explanation above.
