### ISSUE TITLE
Requests to Hoogle Server fail

### ISSUE THREAD

**Issue by fosskers** [commercialhaskell/stack#4004]
### General summary

I've never used Hoogle through Stack, but thought I'd try out the new `stack hoogle --server`.
The command itself executes fine and launches the server, but upon accessing `localhost:8080`, I see:

```
user error (Failed: getModificationTime on /home/colin/.stack/snapshots/x86_64-linux/lts-7.14/8.0.1/share/x86_64-linux-ghc-8.0.1/hoogle-5.0.1/html/index.html, /home/colin/.stack/snapshots/x86_64-linux/lts-7.14/8.0.1/share/x86_64-linux-ghc-8.0.1/hoogle-5.0.1/html/index.html: getModificationTime: does not exist (No such file or directory))
```

This occurs even after nuking my global `.stack/` and my project-local `.stack-work/` and then retrying. The strange thing is that I'm not using `lts-7.14` for anything anywhere. Is there a hard-coded value lurking around somewhere?

### Steps to reproduce

1. Nuke global `.stack/` (if that's not too painful)
2. Enter any Haskell project directory
3. `stack hoogle --server`
4. Access `localhost:8080` in browser
5. See error message

### Expected

I expected some cool Hoogle interface to appear.

### Actual

The error posted above.

### Stack version

```
colin@yumi ~/c/h/mapalgebra> stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

`stack upgrade`

**Comment by SkyWriter** [comment]
@fosskers Doesn't seem to happen on my end. I'll try get myself a Linux installation of the latest stack try again.

By the way, what about `hoogle server -p 8080`? Does it work for you? The reason I ask is that stack doesn't seem to do much more than setting up the environment and calling `hoogle server`.

**Comment by fosskers** [comment]
Well look at that. Same error just with `hoggle server -p 8080`!
