### ISSUE TITLE
ghc installation failure should show verbose output

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#4005]
I have a project with docker enabled. Someone tried to build it on Mac (with the latest OS X stack release), and it did not. The reason may be the open file limit on docker. But we had no way to figure out the issue until after running again with the `--verbose` flag. My suggestion is that if the GHC install fails the log from the GHC build (or the stack `--verbose` log) should be either output to the terminal or the location of that log should be output to the terminal.

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time.
