### ISSUE TITLE
hpack regression: null keys in package.yaml break builds

### ISSUE THREAD

**Issue by tejon** [commercialhaskell/stack#4008]
Empty keys in package.yaml used to be fine, now they cause the build to fail. Trivial example:
```yaml
license:
# Error while parsing $.license - expected String, encountered Null
```
This applies to nested keys as well.

Not sure exactly when this happened; I've been using 1.6.1 locally, but the Heroku buildpack pulled in 1.7.1 and everything exploded. This is an upstream issue, but it breaks `stack` and can be fixed by constraining the dependency.

**Comment by snoyberg** [comment]
Can you clarify: why should `license:` like that be allowed? It seems like it was previously a bug that hpack allowed that.

**Comment by snoyberg** [comment]
Closing, upstream issue
