### ISSUE TITLE
Stack upgrade won't work on a freshly installed ubuntu 16.04

### ISSUE THREAD

**Issue by RamiroPastor** [commercialhaskell/stack#4014]
### General summary/comments (optional)

This is madness

### Steps to reproduce

1. Install Ubuntu 16.04 on a 8-year-old laptop (with the "erase everything" option)
2. Click "yes" to the ubuntu updates, restart the computer
3. Open terminal, run `sudo apt-get install haskell-platform` - goes well, but stack is not installed
4. Close terminal, open it again and run `sudo apt install haskell-stack` - goes well
5. Run `stack upgrade`

### Expected

No errors

### Actual

```
ramiro@LifeOnMars:~$ stack upgrade
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpc                                                                                Downloading package index from https://s3.amazonaws.com/hackage.fpcomplete.com/00-index.tar.gz
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpc                                                                                Populated index cache.          
stack-1.7.1: download
Could not parse '/tmp/stack-upgrade7450/stack-1.7.1/stack.yaml':
AesonException "failed to parse field 'extra-deps': (Invalid package identifier: \"rio-0.1.1.0@rev:0\",\"rio-0.1.1.0@rev:0\")"
See https://github.com/commercialhaskell/stack/blob/release/doc/yaml_configuration.md.

```

With verbose: https://pastebin.com/KuhExvBc

### Stack version

```
ramiro@LifeOnMars:~$ stack --version
Version 0.1.10.0 x86_64

```

**Comment by ncaq** [comment]
Can you use `curl -sSL https://get.haskellstack.org/ | sh` ?
> There is also a Ubuntu package for Ubuntu 16.10 and up, but the distribution's Stack version lags behind, so we recommend running stack upgrade --binary after installing it. For older stack versions which do not support --binary, just stack upgrade may work too. The version in Ubuntu 16.04 is too old to upgrade successfully, and so in that case stack should be installed from a release tarball.
> [Install/upgrade - The Haskell Tool Stack](https://docs.haskellstack.org/en/stable/install_and_upgrade/)
