### ISSUE TITLE
It is not possible to use ghcjs from $PATH

### ISSUE THREAD

**Issue by alexanderkjeldaas** [commercialhaskell/stack#4018]
According to docs https://docs.haskellstack.org/en/stable/ghcjs/#custom-installed-ghcjs

It should be possible to specify:

```
compiler: ghcjs-0.2.0_ghc-7.10.2
```

and `stack` should use the GHCJS from $PATH.

That's not what's happening:

```
$ stack build
No setup information found for ghcjs-0.2.0_ghc-7.10.2 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'source'.
Supported versions: ghcjs-0.1.0.20150924_ghc-7.10.2, ghcjs-0.2.1.9007010_ghc-8.0.1
```

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mgsloan** [comment]
Perhaps try `system-ghc: false`?  Sorry for the delay in response.

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
