### ISSUE TITLE
'stack ghci' doesn't add include dirs

### ISSUE THREAD

**Issue by hesselink** [commercialhaskell/stack#402]
If you have a package with an `include-dirs` line in the cabal file, it doesn't load correctly in `stack ghci`. As a workaround, you can pass `--ghc-options -I<path-to-include-dir>`, but I think ideally stack should do this.

**Comment by chrisdone** [comment]
:+1: Can be added [here](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Package.hs#L294). I'll get round to it unless you want to fix it first.

**Comment by mitchellwrosen** [comment]
@chrisdone https://github.com/commercialhaskell/stack/blob/master/src/Stack/Package.hs#L315
```
- map (cabalDir </>) (mapMaybe parseRelDir (hsSourceDirs b))
+ map (cabalDir </>) (mapMaybe parseRelDir (hsSourceDirs b ++ includes b))
```
?

Not exactly sure what cabalDir is, or anything else about the architecture, really :P

**Comment by hesselink** [comment]
@chrisdone I had a fix for this, just created a PR. Hope we didn't do duplicate work...

**Comment by mitchellwrosen** [comment]
@hesselink Mine was shorter :P except s/`includes`/`includeDirs`

**Comment by hesselink** [comment]
But yours added it to the source dirs, which would pass it with `-i` instead of `-I`, right?

**Comment by mitchellwrosen** [comment]
@hesselink Oh... yup :)
