### ISSUE TITLE
Update default msys2 version in stack setup

### ISSUE THREAD

**Issue by hardentoo** [commercialhaskell/stack#4023]
I am using the latest release of stack (1.7.1) on the latest version of Windows 10.

I need the sdl2 library in msys2.  But default msys2 is too old. If I make stack setup, then msys2-20150512 is installed, which is too old and when trying to do pacman -Syyuu in it nothing works. Therefore, I have to download the latest version of msys2 from here http://repo.msys2.org and install it in the "C:\Users\User\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512 directory and then pacman - Syyuu works and I can use the latest version of sdl2.

How to specify to use a more recent build of msys2 in stack setup?  Can you update msys2 in the default installation to recent?

**Comment by snoyberg** [comment]
PR opened: https://github.com/fpco/stackage-content/pull/41

Plus a doc update PR: #4043
