### ISSUE TITLE
static binary of stack is missing

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#4025]
At https://www.stackage.org/stack, the "Linux 64-bit, static" link is giving 404.

**Comment by borsboom** [comment]
Yes, unfortunately due to issues with GHC 8.2 on Alpine Linux we were not able to build stack-1.7 static binaries.

**Comment by simonmichael** [comment]
Thanks @borsboom, the link should probably be removed from that page.

**Comment by simonmichael** [comment]
PS also, I assume the stack installer knows about this ? (I noticed because I'm using a fork of it for hledger's installer.)
