### ISSUE TITLE
GHCJS 8.4 Support

### ISSUE THREAD

**Issue by RobertFischer** [commercialhaskell/stack#4030]
GHCJS runs on 8.4 -- see:
  https://github.com/NixOS/nixpkgs/issues/40140
  https://github.com/ghcjs/ghcjs/issues/602#issuecomment-387087893

What's it going to take to get Stack to have a GHCJS based on 8.4 and a modern LTS?  I'm happy to put in some effort to get it to happen, but I'm not sure what kind of effort is necessary.

**Comment by alexanderkjeldaas** [comment]
Here's a working setup for ghcjs 8.4:

https://gist.github.com/alexanderkjeldaas/4e7418db7cf8536e38dce983eaf77d51

**Comment by alexanderkjeldaas** [comment]
Also https://github.com/alexanderkjeldaas/ghcjs/releases/download/fghcjs-8.4.1/ghcjs.tar.gz can be used directly in your `stack.yaml` file.

**Comment by schell** [comment]
> Also https://github.com/alexanderkjeldaas/ghcjs/releases/download/fghcjs-8.4.1/ghcjs.tar.gz can be used directly in your `stack.yaml` file.

Do you have an example of this anywhere?

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
