### ISSUE TITLE
Add configurable `stack watch`?

### ISSUE THREAD

**Issue by Anrock** [commercialhaskell/stack#4042]
So i'm running `stack build --file-watch --fast --haddock --haddock-deps --haddock-internal --haddock-hyperlink-source --test --rerun-tests --exec "echo All good!"`. 

This is long to type and i sometimes forget to add an argument for something.

It would be much easier if i could store this to config and run it using some short command.

For example:
1. Add a `watch` field to stack.yaml, similar to
```
...
watch:
  - fast
  - haddock
  - haddock-deps
  - haddock-internal
  - haddock-deps
  - haddock-hyperlink-source
  - test
  - rerun-tests
  - exec: echo All good!
...
```
2. Run `stack watch`
3. Stack reads `watch` field from stack.yaml
4. If it's present and non-empty - checks that all commands are valid, otherwise issues a warning and ignores invalid command
5. Does what it usually does when `stack build --file-watch {insert contents from watch field}` is run.

**Comment by mattaudesse** [comment]
That's an interesting idea @Anrock.

I guess one argument against this feature would be that you'd now have two top-level commands that are variations of `build` but work somewhat differently, so there's added complexity overhead. Introducing `watch` would also create some redundancy with the current `build` command since (like you've demonstrated!) it already exposes the same abilities.

I'm sure you've considered that it'd be easy enough to wrap your `watch` routine in a project-specific `Makefile` or something equivalent. OTHO, consolidating it into `stack.yaml` feels pretty clean and convenient too.

I think this deserves discussion - does anyone else want to weigh in?

**Comment by Anrock** [comment]
@malteneuss 
> you'd now have two top-level commands that are variations of build
> redundancy with the current build command since (like you've demonstrated!) it already exposes the same abilities.

Doesn't stack already have multiple top-level variations of `build` that work somewhat differently and create redundancy? I mean thing like `stack haddock`, `stack test`, etc. Personally i treat `build` and all it's options as a low-level API and all mentioned things as a convenient wrappers. And imo `watch` fits here also.

> I'm sure you've considered that it'd be easy enough to wrap your watch routine in a project-specific Makefile or something equivalent.

Honestly i didn't. Just forgot that i can do that.

>  consolidating it into stack.yaml feels pretty clean and convenient too.

You've got me thinking here. Maybe it's over the edge a little but anyway...
Those wrappers can be generalized and all be moved to stack.yaml like npm does with `npm run`. Something like:
```yaml
...
scripts:
 - test: build --test
 - haddock: build --haddock
 - watch: build --file-watch ...
 ...
...
```
This way any user (or get them via project templates) can add any top-level command he wants and stack itself doesn't have to maintain this wrappers as top-level commands. Just provide core functionality as new options for build and maybe some default wrappers in global config.yaml.

**Comment by mattaudesse** [comment]
@Anrock I asked some of the core `stack` developers about this awhile ago and the rough consensus seemed to be that project-specific `Makefile`s (or similar mechanisms) achieve the same outcome and are preferable to taking on additional complexity within `stack` itself, so I'm going to go ahead and close this ticket.

If more people want to weigh in with strong opinions we can always reopen in the future. Thanks for the idea regardless.
