### ISSUE TITLE
Add `--with-package` option to `stack install`

### ISSUE THREAD

**Issue by vrom911** [commercialhaskell/stack#4048]
Sometimes when I want to install some package (which is not at stackage) I get the issue like here:
```
$ stack install summoner-1.0.1
Didn't see summoner-1.0.1 in your package indices.
Updating and trying again.
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Updating index
Updated package index downloaded
Update complete
Populated index cache.

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for summoner-1.0.1:
    tomland must match >=0.2.1, but the stack configuration has no specified version  (latest matching version is 0.2.1)
    universum-1.1.1 from stack configuration does not match >=1.2.0  (latest matching version is 1.2.0)
needed since summoner is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build
    configuration. This can be convenient when dealing with many complicated constraint errors, but results may be
    unpredictable.

  * Recommended action: try adding the following to your extra-deps in /Users/vrom911/.stack/global-project/stack.yaml:

- tomland-0.2.1
- universum-1.2.0
```
Unfortunately, to get it installed I don't see any other option rather than change my global `stack.yaml` adding these versions in there. But this is not convinient at all. Instead I would like to have some CLI option like `--with-package package-name-1.0.0` but I can't found anything like this in `stack install` command.

Could this `--with-package` (or some better name) option be added to `stack install` command?

**Comment by mgsloan** [comment]
It would be nice to have a `--package` flag that lets you specify a dependency version without copying its binaries into the install directory.

In the meantime, `stack install summoner tomland-0.2.1 universum-1.2.0` works fine.  The only case where this doesn't work is if your dependency had an executable that you don't want to be installed.

**Comment by snoyberg** [comment]
I think the current approach of including the dependencies on the command line is sufficient, closing.
