### ISSUE TITLE
Incorrect dirty tracking of dependency shared by multiple projects

### ISSUE THREAD

**Issue by thomasjm** [commercialhaskell/stack#4050]
Apologies if there's already an issue for this, I looked around and couldn't find it.

I have a repo containing three Haskell projects, using the following (simplified) structure:

```
.
├── backend
│   ├── src
│   └── stack.yaml
├── core
│   ├── src
│   └── stack.yaml
└── frontend
    ├── src
    └── stack.yaml
```

Both `frontend` and `backend` depend on `core` via `packages:` in `stack.yaml`, i.e.

```
# frontend/stack.yaml
packages: ["../core"]
```

```
# backend/stack.yaml
packages: ["../core"]
```

I find this to be a convenient way to organize code when there's a common library needed by two other projects. The problem arises when you edit the `core` project:

```
> touch core/src/Something.hs # Make some breaking change
> cd backend && stack build
core-0.1.0.0: unregistering (local file changes: src/Something.hs)
core-0.1.0.0: configure (lib)
core-0.1.0.0: build (lib)
# success

> cd frontend && stack build
# error! core is not considered dirty, so it's not rebuilt. frontend build fails.
```

To work around this I often have to make a trivial edit to `core` and then do `stack build` on `frontend` again, which is a pain. This can also cause trouble in a continuous integration.

I'm guessing `stack`/`cabal` just look at file modification times on `core` to decide whether it's dirty and needs to be rebuilt, but it would be awesome if it were a little smarter about this case. Thanks!

**Comment by mattaudesse** [comment]
Thanks for the detailed report + reproducible case @thomasjm.

**Comment by mgsloan** [comment]
This is indeed already tracked by https://github.com/commercialhaskell/stack/issues/3130 .  The nice repro is appreciated, though.

**Comment by thomasjm** [comment]
Thanks! Closing this then.
