### ISSUE TITLE
stack build fails on long path?

### ISSUE THREAD

**Issue by kniteli** [commercialhaskell/stack#4054]
base path for commands: `C:\Users\knite\Workspace\hackerrank\algorithms\dynamic_programming\`

### Two cases

This works:

```
stack new choosing-white-ba
cd choosing-white-ba
stack build
```

This fails:

```
stack new choosing-white-bal
cd choosing-white-bal
stack build
```

With the following message:

```
[0mBuilding all executables for `choosing-white-bal' once. After a successful build of all of them, only specified executables will be rebuilt.[0m
[0mchoosing-white-bal-0.1.0.0: build (lib + exe)[0m
[0mPreprocessing library for choosing-white-bal-0.1.0.0..[0m
[0mBuilding library for choosing-white-bal-0.1.0.0..[0m
[0mPreprocessing executable 'choosing-white-bal-exe' for choosing-white-bal-0.1.0.0..[0m
[0mBuilding executable 'choosing-white-bal-exe' for choosing-white-bal-0.1.0.0..[0m
[0m[2 of 2] Compiling Paths_choosing_white_bal ( .stack-work\dist\5c8418a7\build\choosing-white-bal-exe\autogen\Paths_choosing_white_bal.hs, .stack-work\dist\5c8418a7\build\choosing-white-bal-exe\choosing-white-bal-exe-tmp\Paths_choosing_white_bal.o )[0m
[0m.stack-work\dist\5c8418a7\build\choosing-white-bal-exe\choosing-white-bal-exe-tmp\.stack-work\dist\5c8418a7\build\choosing-white-bal-exe\autogen\Paths_choosing_white_bal.dump-hi: openFile: does not exist (No such file or directory)[0m

--  While building custom Setup.hs for package choosing-white-bal-0.1.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.0.1.0_ghc-8.2.2.exe --builddir=.stack-work\dist\5c8418a7 build lib:choosing-white-bal exe:choosing-white-bal-exe --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

The full path of failing case: 

`C:\Users\knite\Workspace\hackerrank\algorithms\dynamic_programming\choosing-white-bal>`

Everything shorter seems to work fine, everything longer fails (I discovered because my original project name was *choosing-white-balls*)

I also tested with these two strings, and the pattern seems to hold:

`abcdefghijklmnopqr` and `abcdefghijklmnopq` with the first failing and the second not.

Windows 10, with stack 1.7.1.

**Comment by mgsloan** [comment]
This is due to window's MAX_PATH which limits the length of paths.  Unfortunately, it is not trivial to work around this limitation at every level of the toolchain.  This is why the suggested STACK_ROOT on windows is `C:/sr/`.  Similarly, the locations of your projects should not have long paths.
