### ISSUE TITLE
Code Guidance: where does stack set the output path for libraries?

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#4055]
Stack (as well as Cabal) like to place libraries into their own folders. That is, we create a separate folder for each package, and put the library into said folder.

The result is, that when linking, ghc will collect all the library search paths from the package database, and generate one `-L` argument for each package. Due to aggressive inlining, it is insufficient for GHC to only include the directly linked libraries.  The result therefore is that GHC generate the `-L` for every package in the transitive closure. As such the number of `-L` flags can increase rapidly with the dependency complexity.

On windows, we have a 32k limit for arguments passed on the command line, and as such use a response file (@file) to pass arguments to gcc.  gcc however, only uses a response file to pass certain arguments to its collect2 process. Notably it does *not* pass the `-L` flags via a response file.  This results in the infamous `realgcc.exe: CreateProcess: ...` error.

The proper fix clearly is to rectify this in gcc. It is however easier to just use a patched `stack`, than to inject a newer gcc into ghc.

As such, if we placed all generated libraries into a shared folder, GHC would pass only a single `-L` flag instead of one for each package, and this would for the time being provide a workaround for this issue.

If someone more knowledgable about the stack codebase could point me to the code where stack computes the output path for the library, I'd like to give this a try.

**Comment by mihaimaruseac** [comment]
I guess you want to look at https://github.com/commercialhaskell/stack/blob/master/src/Stack/Build/Execute.hs#L1196-L1212

**Comment by angerman** [comment]
Thanks. I've tried messing with passing additional `--libdir`, `--prefix`, ... flags to the `configure` call. But there seem to be some additional assumptions about the layout somewhere in `stack` I did not find yet.
