### ISSUE TITLE
Stack/GHC Regression with LTS-11.12 from LTS 9.21

### ISSUE THREAD

**Issue by jm4games** [commercialhaskell/stack#4081]
So I'am currently in the process of upgrading my project from LTS 9.21 to LTS 11.12 and have found an issue with how stack/ghc handle build dependencies. I not sure if its GHC or stack causing the issue but for now I am filing it here.  With LTS 9.21 I could have two projects depend on each other indirectly and it would work fine. Meaning I could have a lib Foo and a lib Bar that depends on Foo and then have the tests for Foo depend on Bar. When upgrading to LTS 11.12 this no longer works and the compiler has trouble resolving types in the test project. 

As mentioned this could actually be a GHC issue, so let me know if I need to forward this issue there. I guess next steps might be to try and repro this with only cabal builds?

NOTE: stack.yaml has both LTS versions so that you can see regression.

Here are the test files needed (attached).
stack-regress/stack.yaml
stack-regress/foo/foo.cabal
stack-regress/foo/Foo/Types.hs
stack-regress/foo/tests/TestSuite.hs
stack-regress/bar/bar.cabal
stack-regress/bar/Bar/Types.hs

[regression.tar.gz](https://github.com/commercialhaskell/stack/files/2094631/regression.tar.gz)

### Steps to reproduce
```
stack-regress$ stack setup
stack-regress$ cd foo
stack-regress/foo$ stack test .
```

### Expected
Tests Pass

### Actual
TestSuite.hs Compilation Error
```
  • Couldn't match expected type ‘foo-0.0.1.0:Foo.Types.FooType’
                  with actual type ‘FooType’
      NB: ‘FooType’ is defined in ‘Foo.Types’ in package ‘foo-0.0.1.0’
          ‘foo-0.0.1.0:Foo.Types.FooType’
            is defined in ‘Foo.Types’ in package ‘foo-0.0.1.0’
    • In the first argument of ‘BarType’, namely ‘(FooType "A" "B")’
      In the second argument of ‘assertEqual’, namely
        ‘(BarType (FooType "A" "B") 2)’
      In the first argument of ‘TestCase’, namely
        ‘(assertEqual
            "Bar Types"
            (BarType (FooType "A" "B") 2)
            (BarType (FooType "A" "B") 2))’
```

### Stack version

```
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mihaimaruseac** [comment]
I was able to reproduce both on LTS-11 and on nightly.

**Comment by jm4games** [comment]
FYI, was initially tracking this issue here: https://stackoverflow.com/questions/50807955/haskell-stack-generating-duplicate-dependency

**Comment by tswelsh** [comment]
I think this is a duplicate of #3892, which I traced back to a behaviour change in cabal. That issue links to the corresponding one on the cabal issue tracker, which was recently closed and won't be fixed. We worked round it by splitting the tests out into a separate package (in your example we put the test suite into Bar).

**Comment by jm4games** [comment]
@tswelsh  Thanks for pointing out the dup. This is indeed the same issue.
