### ISSUE TITLE
Stack rebuilds pretty-show and few more packages with no apparent reason

### ISSUE THREAD

**Issue by gromakovsky** [commercialhaskell/stack#4084]
### General summary/comments (optional)

If I build one package, modify one file there and built it again, for some reason more than one package is rebuilt.

### Steps to reproduce

Can be reproduced using this code: https://github.com/serokell/cardano-sl/tree/vanya (`serokell/cardano-sl` repository, `vanya` branch).

1. Build the `cardano-sl-txp` package:
> stack build --fast cardano-sl-txp

2. Modify some file:
> echo "\n -- aa" >> txp/src/Pos/Txp/Base.hs

3. Build `cardano-sl-txp` again:
> stack build --fast cardano-sl-txp

### Expected

Only one file is recompiled and the command finishes quickly.

### Actual

Stack decides to unregister `cardano-sl-core`, `pretty-show`, `cardano-sl-crypto-test` and some other packages. Then it builds these packages:

```
cardano-sl-core-1.2.0: unregistering
cardano-sl-crypto-test-1.1.0: unregistering
cardano-sl-db-1.2.0: unregistering
cardano-sl-infra-1.2.0: unregistering
cardano-sl-txp-1.2.0: unregistering
hedgehog-0.6: unregistering
pretty-show-1.6.16: unregistering
pretty-show-1.6.16: configure
pretty-show-1.6.16: build
pretty-show-1.6.16: copy/register
hedgehog-0.6: configure (lib)
hedgehog-0.6: build (lib) 
hedgehog-0.6: copy/register
cardano-sl-crypto-test-1.1.0: configure (lib)
cardano-sl-crypto-test-1.1.0: build (lib) 
cardano-sl-crypto-test-1.1.0: copy/register
cardano-sl-core-1.2.0: configure (lib)    
cardano-sl-core-1.2.0: build (lib)        
cardano-sl-core-1.2.0: copy/register
cardano-sl-db-1.2.0: configure (lib)
cardano-sl-db-1.2.0: build (lib)   
cardano-sl-db-1.2.0: copy/register
cardano-sl-infra-1.2.0: configure (lib)
cardano-sl-infra-1.2.0: build (lib) 
cardano-sl-infra-1.2.0: copy/register
cardano-sl-txp-1.2.0: configure (lib)
Configuring cardano-sl-txp-1.2.0... 
cardano-sl-txp-1.2.0: build (lib) 
Preprocessing library for cardano-sl-txp-1.2.0..
Building library for cardano-sl-txp-1.2.0..
[23 of 37] Compiling Pos.Txp.Base     ( src/Pos/Txp/Base.hs, .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0/build/Pos/Txp/Base.o )
cardano-sl-txp-1.2.0: copy/register
Installing library in /home/gromak/Work/cardano-sl/.stack-work/install/x86_64-linux-tinfo6/lts-11.2/8.2.2/lib/x86_64-linux-ghc-8.2.2/cardano-sl-txp-1.2.0-kSN1N3EEYBFSpz2b5PzUX
Registering library for cardano-sl-txp-1.2.0..
Completed 7 action(s).            
```

Here is the output in `--verbose` mode: https://gist.github.com/gromakovsky/a23b77cb9bcf3cc0e415b9a65f5f422d

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

I am using version 1.7.1 downloaded from https://github.com/commercialhaskell/stack/releases.

**Comment by nh2** [comment]
We'll be looking into this.

**Comment by snoyberg** [comment]
Note that it's a better idea for repros to give a commit than a branch. Right now, the vanya branch is pointing at 6c109584a6a7f182334eedc79c063a591626cca9.

**Comment by snoyberg** [comment]
Also, as a side note: due to the extremely large number of extra-deps in this stack.yaml, I'd recommend moving over to a custom snapshot, which will allow for more precompiled cache usage.

**Comment by snoyberg** [comment]
I'm going to start a debug log in this comment. I'll be editing it as I move along.

My first step is to confirm that this bug reproduces with the Stack on master. Also, in order to avoid wasting lots of CPU cycles, I'm going to be using the following command as a replacement for step 3 above:

```
stack build --fast cardano-sl-txp --dry-run
```

This way I'll keep the same broken state between attempts to play with this bug. I'm also almost certainly going to throw in a `--verbose`, and then begin adding a bunch of `logInfo` calls to the Stack codebase to get more info on why it's decided to unregister the packages in question.

**Comment by gromakovsky** [comment]
I couldn't fetch `d20833a5c0d3b2b62495fb126ecfd8fdbf1f6864`, so I tried using its parent: `dbc74ecce2e31b47626d87a1cf3ea6129fed1e99`.
`d20833a5c0d3b2b62495fb126ecfd8fdbf1f6864` has only cosmetic changes, so it shouldn't matter.

For me it still unregisters packages that it shouldn't, here's the output of `stack build --fast cardano-sl-txp --dry-run`: https://gist.github.com/gromakovsky/7ca7bac5b4f5fedaf269665985eadb5a

**Comment by dbaynard** [comment]
It might be helpful to have a minimum example, though it seems that might be tricky. Would you try to produce one, @gromakovsky?

**Comment by gromakovsky** [comment]
I was successfully minimizing this example while keeping the bug reproducible, but then I did `stack clean --full` and since then I can't reproduce this bug anymore, even when I return to where I started (6c109584a6a7f182334eedc79c063a591626cca9) and use the same version of `stack` as before (681c800873816c022739ca7ed14755e85a579565) :man_shrugging: 

Probably something bad appeared in `.stack-work`, I don't know how :(

**Comment by dbaynard** [comment]
OK, it's good that there's a resolution. Thank you for digging around (I editied your commit refs to links so I could follow them). I suspect you're right about something in the `.stack-work` folder being a culprit — and the extra-deps appear to have contributed, too.

I'd recommend @snoyberg's advice: it is worth using a custom snapshot.

I'm going to close — do get in touch if there's anything else you'd need, on this.
