### ISSUE TITLE
Recommend rerunning with --verbose on failed setup

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4085]
Motivation: https://stackoverflow.com/questions/50709844/is-there-an-issue-with-haskell-ghc-8-4-3-on-travis.

As can be seen from that discussion, the default output of `ExitFailure 2` is insufficient to debug the problem, which in this case was an "out of space" condition. We should either:

1. Recommend rerunning when setup fails
2. Automatically dump the output

At the very least, this applies to setting up GHC, but may apply to other parts of the codebase as well.

**Comment by aleksejkozin** [comment]
@snoyberg 
I wan't to outline my plan

We are trying to fix an issue: when setting up GHC and having no space then we get an insufficient error message
We want to print a correct error message in this case aka "2. Automatically dump the output" option

In order to fix this issue I should reproduce it
My plan is to add an integration test that will build a dummy stack project in a docker container configured that way that there will be no free space for a GHC installation
After running the build attempt I will insure that a user will see "No space" message

What do you think?

**Comment by snoyberg** [comment]
I think it's a good idea, _however_ I don't think our integration test suite runner will be able to handle that kind of a setup, and it won't be able to test on non-Linux platforms. For your own testing, that will certainly be a good approach, but we'd probably need to think harder about a method to get a regression test in place long term.

**Comment by aleksejkozin** [comment]
@snoyberg I'm sorry, but I don't understand if I should execute my plan or come with another one

Also,
> don't think our integration test suite runner will be able to handle that kind of a setup

In terms of performance? I don't understand this part too

**Comment by aleksejkozin** [comment]
>and it won't be able to test on non-Linux platforms

What are the limitations that not allow us to test on non-Linux?
I've found that you can run `docker` command on windows
https://docs.docker.com/v17.09/docker-for-windows/

**Comment by aleksejkozin** [comment]
>but we'd probably need to think harder about a method to get a regression test in place long term

I've dived in the current integration tests code, looks like we run all tests locally. Do you think it would be better if we run future integration tests in Docker containers? It will allow us to write more reproducible tests + more tricky scenarios like this issue

**Comment by snoyberg** [comment]
> In terms of performance? I don't understand this part too

I mean that the automated testing of this on our CI system probably can't run Docker commands right now.

> What are the limitations that not allow us to test on non-Linux? I've found that you can run docker command on windows https://docs.docker.com/v17.09/docker-for-windows/

True, but

1. that would require setup on the CI system
2. it would actually just be testing the failure case on a Linux system (the one on which Docker Machine is running the actual command)

> Do you think it would be better if we run future integration tests in Docker containers?

The CI server handles the details of this for us, AFAIK.

> I run current integration tests on my MacBook and some of them failed with no obvious reason:

That's annoyed me in the past too. I've tried to make them more reproducible. I've so far only had success with regularly doing a full `git clean -fdx`.

We're in the process of setting up an open Gitlab runner so that the mirror of this repo on gitlab.com will be able to publicly report integration test failures, so stay tuned for that.

**Comment by aleksejkozin** [comment]
@snoyberg I see
Returning to the main question, I need your guidance

- I wan to fix this issuer
- To fix the issue I need to reproduce the problem and write an integration test
- The only reasonable way to reproduce "out of space" error is to run the test in a container
- Travis CI has docker support https://docs.travis-ci.com/user/docker/, so looks like I can technically do it

Should I execute this plan? 
If no, then what is my next step with this issue?

**Comment by snoyberg** [comment]
I don't think Travis will be relevant for this. I'd recommend trying to reproduce the problem _locally_, and using Docker is a good approach to that.

**Comment by aleksejkozin** [comment]
Got it, I will reproduce the problem locally using Docker and then fix it
Alright, let's do it!

**Comment by aleksejkozin** [comment]
I would be able to start solving this only next week, sorry for the delay
