### ISSUE TITLE
Edit on GitHub link from the docs front page is giving a 404

### ISSUE THREAD

**Issue by philderbeast** [commercialhaskell/stack#4098]
On the top right of the front page of the stack [docs](https://docs.haskellstack.org/en/stable/README/), the `Edit on GitHub` link, is broken giving a `404` response when going to;

https://github.com/commercialhaskell/stack/tree/master/doc/edit/master/docs/README.md

**Comment by dbaynard** [comment]
Thank you for the report! The broken link is not very helpful.

There are two issues:

1. it targets the wrong branch (should be `stable`, not `master`), and
2. it targets the wrong folder (should be `doc` not `docs`).

The correct link should be <https://github.com/commercialhaskell/stack/edit/stable/doc/README.md>.

Would you like to help fix it?

**Comment by philderbeast** [comment]
At first glance, the link seems to be generated by readthedocs.

To fix this problem might require authorisation to maintain stack's [readthedocs](https://readthedocs.org/projects/stack/) account.

**Comment by dbaynard** [comment]
I think you're right — I haven't seen anything obvious in the code itself. I'm going to assign to @borsboom who is listed as the maintainer. Thanks, @philderbeast.

**Comment by borsboom** [comment]
Hm, this used to work, but I guess behaviour of RTFD and/or mkdocs changed at some point.  In any case, I've opened #4115 with a fix.

**Comment by snoyberg** [comment]
Looks like this is fixed now with #4115, closing. Please add a comment if this is still a problem.
