### ISSUE TITLE
"ls dependencies" should have an option to maintain the tree structure

### ISSUE THREAD

**Issue by sschuberth** [commercialhaskell/stack#4101]
Currently, "ls dependencies" just outputs a flat list of package names and versions of all transitive dependencies of a project. However, it would be nice to maintain the tree hierarchy of dependencies to see their parent / child relationship. On the console, the tree output could look similar to Maven's `mvn dependency:tree` output, but ideally there would also be an option to output to a machine readable format like JSON.

**Comment by dbaynard** [comment]
Hello @sschuberth . That sounds like a helpful enhancement. How much of what you would like to do can you achieve with `stack dot --external` (perhaps with `--include-base`, too)?

**Comment by sschuberth** [comment]
I was thinking about (mis-)using `stack dot`, too, but while it basically provides the parent -> child relationship, it's a bit inconvenient to parse, also because it repeats the parent for each child. Also the versions are missing, but together with the output from `stack ls dependencies` I could probably get what I want. I'll give it a try.

**Comment by dbaynard** [comment]
That's all useful to know. It may be relatively straightforward to reuse the code required for the dot output. Would you be willing to contribute a PR yourself?

**Comment by sschuberth** [comment]
I'm sorry, I'm not a Haskell guy (and I don't intend to become one 😉), I'm just trying to add basic Haskell support to the [OSS Review Toolkit](https://github.com/heremaps/oss-review-toolkit).

**Comment by dbaynard** [comment]
Oh, that's an interesting project. Is there anything else that would be helpful for you to achieve that, from stack?

It might also be possible for you to do what you intend using the hackage or stackage APIs directly (depending on scale), though they are quite limited. If stack meets your other requirements, then great.

**Comment by sschuberth** [comment]
> Is there anything else that would be helpful for you to achieve that, from stack?

Thanks for asking. Besides listing dependencies as a tree (optionally in a machine readable format), it would be nice if the shown meta-data would not only include the name and version, but also the dependency's declared license (as an [SPDX identifier](https://spdx.org/licenses/)). That would be the very minimum, IMO. More meta-data like the download URL would also be interesting and could be added, or simply a link to the respective hackage or stackage (REST?) APIs endpoints where more information can be gathered by the client (the program using the meta-data output) on demand.

In general, from a performance perspective it would be nice if all this meta-data could be gathered without internally downloading and unpacking the whole (source code of a) package, i.e. ideally meta-data for a package and the package itself should be separated, similar to Maven POM and JAR files.

> using the hackage or stackage APIs directly

While I've found http://hackage.haskell.org/api, I didn't find something similar for stackage. Is there? *Edit:* I just found https://groups.google.com/forum/#!topic/stackage/9h_RA-jNz_g.

**Comment by dbaynard** [comment]
Perhaps we should broaden the issue, then. It seems like a useful addition, though it may not be a priority for the core team.

So to summarize,

- [ ] List dependencies as tree
- [ ] List dependencies in machine readable format
- [ ] List license as [SPDX](https://spdx.org/licenses/) in addition to name and version

    Most cabal files don't use these identifiers; internally `Cabal` (which processes these files and is different to `cabal-install`, the provider of the command line program `cabal`) uses an enumeration, though, so you may wish to take a look thee.
    
- [ ] List URI too

> In general, from a performance perspective it would be nice if all this meta-data could be gathered without internally downloading and unpacking the whole (source code of a) package, i.e. ideally meta-data for a package and the package itself should be separated, similar to Maven POM and JAR files.

`stack` downloads and unpacks the hackage tarball (~100MB compressed), which contains the cabal files where the metadata is located; this might update incrementally (I've never investigated). The cabal files themselves are reachable directly (`/package/:package/:cabal.cabal`). So the trade-off is a space vs latency one. If you're happy with the space use, `stack` would be useful for this.

> I didn't find something similar for stackage

I think I might have just tried the hackage endpoints when I was looking for snapshot information… or I may have checked the api calls in the debugger. I think the hackage api is most relevant, though — I only needed stackage because of stack snapshots. That said, it may be useful to add the hackage mirrors, if you go that way.

**Comment by dbaynard** [comment]
@borsboom — it may be worth supporting this enhancement to support the OSS review toolkit project mentioned earlier.

**Comment by borsboom** [comment]
I'm very much in favour.  I've often wished for an `ls-dependencies` that shows the tree structure.  That said, I'm going to un-assign myself as it's very unlikely I'll actually be able to work on implementing it.

**Comment by sschuberth** [comment]
And so do Maven (`mvn dependency:tree`), Gradle (`gradle dependencies`), and several other package managers / dependency tools / build systems / whatever you call them...

**Comment by creichert** [comment]
NPM does as well: 

```
$ npm ls | head
project@0.1.0 /home/christopher/dev/proj
├── adt@0.7.2
├─┬ babel-core@6.26.0
│ ├─┬ babel-code-frame@6.26.0
│ │ ├─┬ chalk@1.1.3
│ │ │ ├── ansi-styles@2.2.1
│ │ │ ├── escape-string-regexp@1.0.5
│ │ │ ├─┬ has-ansi@2.0.0
│ │ │ │ └── ansi-regex@2.1.1
│ │ │ ├─┬ strip-ansi@3.0.1
```

@sschuberth I'm sure you've seen `stack ls dependencies --license`? It's not SPDX format afaik, but may still be a useful interim solution.

```
$ stack ls dependencies --separator=- --license | head
Cabal-BSD3
HTTP-BSD3
HUnit-BSD3
HsOpenSSL-PublicDomain
JuicyPixels-BSD3
MonadRandom-OtherLicense
QuickCheck-BSD3
RSA-BSD3
SHA-BSD3
StateVar-BSD3
```

@borsboom Why does `--license` discard the versioni number?

**Comment by sschuberth** [comment]
The problem with NPM is that it can only show the tree for installed dependencies. But ideally I'd like to see the list / tree of dependencies *before* I even install them. Maven and Gradle can do that just fine.

Thanks @creichert, I've seen `stack ls dependencies --license`, but I've already implemented a solution that uses a mix of calling `stack` and parsing `*.cabal` files directly from Hackage.

**Comment by dbaynard** [comment]
@akshaymankar For machine readable output I suggest json (unless @sschuberth has a better suggestion). It might be simple enough to implement some aeson instances and then plumb them in.

SPDX is well defined.

For the URI, I'm not sure what to go with. I don't really understand the use case, so perhaps @sschuberth  can explain.

**Comment by sschuberth** [comment]
JSON is indeed fine from my perspective. But if e.g. more common in the Haskell community, YAML could be another option.

URI / URL was referring to the direct download location for the source code to the package. At the example of the `memory` package version 0.14.11, the URL would be https://hackage.haskell.org/package/memory-0.14.11/memory-0.14.11.tar.gz. The use-case is to perform automated license checks by scanning the source code of the package.

**Comment by akshaymankar** [comment]
The URL in the JSON doesn't really work, because a package could either be from hackage, a local package, an archive specified by URL or a git repository. So, I guess a URL to a will not always be possible.

I am not sure what the best possible format for this would be. @sschuberth, do you have any suggestions/preferences?

@dbaynard I also couldn't find a place where stack figures out URL from `PakcageLocation` object. Can you please point me to it, so I don't invent the logic again.

**Comment by qrilka** [comment]
@akshaymankar what's the problem to use `file://` for local packages and `git://` for git?

**Comment by qrilka** [comment]
And I think you'll need a custom function for that, I don't think there's already some code doing that.

**Comment by akshaymankar** [comment]
I think `file://` is a good idea for local packages.
For git and hg repositories, even if we go with any URL specification, we still won't be able to show the commit in the URL. So, I'm leaning towards the second approach of additional metadata.

Maybe it could look something like this for git (and similar for hg):
```json
{
  "name": "foo",
  "version": "1.0.0.0",
  "license": "MIT",
  "location": {
    "type": "git",
    "url": "<URL provided by user>",
    "commit": "<sha>"
  }
}
```

For hackage:
```json
{
  "name": "foo",
  "version": "1.0.0.0",
  "license": "MIT",
  "location": {
    "type": "hackage",
    "url": "<computed hackage URL>"
  }
}
```
