### ISSUE TITLE
Provide a "stack switch <vrn>" command as sugar for STACK_YAML and symlinking

### ISSUE THREAD

**Issue by adinapoli** [commercialhaskell/stack#411]
This possibly overlaps with https://github.com/commercialhaskell/stack/issues/378,
although it can be seen as a complementary machinery.

It would be nice to have stack transparently manage the symlinking to the `stack.yaml` file in case there are multiple in the current folder of the form `stack-vrn.yaml`.

In such scenario, a user which would like to play with a newly released GHC version / resolver, would do something like:

```
stack switch 7.10
```

This would simply symlink `stack.yaml -> stack-7.10.yaml` (possibly checking `stack.yaml` is not a real file to avoid overriding a genuine manifest), and possibly set `STACK_YAML` to point to the selected `stack-7.10.yaml` (although not necessary).

This might shave a bit of pain out of keeping a symlink update and/or calling stack prepending the correct `STACK_YAML` environment variable.

That's more an idea than a real need.

Alfredo

**Comment by snoyberg** [comment]
This seems like it's supporting a pretty ad-hoc usage, depending on the user following specific naming conventions, and just results in using a `stack` command instead of a simpler `ln` call.

**Comment by DanBurton** [comment]
One could implement this leveraging stack's plugin system in order to
invoke `stack switch` as desired, without having to actually add it to
stack.

On Thursday, July 2, 2015, Michael Snoyman <notifications@github.com> wrote:

> Closed #411 <https://github.com/commercialhaskell/stack/issues/411>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/411#event-346726883>.
>


-- 
-- Dan Burton
