### ISSUE TITLE
Export all necessary Network.HTTP.Client functions from Network.HTTP.StackClient

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/stack#4110]
@snoyberg Can you confirm that I understood this correctly before I start work on this?

**Comment by snoyberg** [comment]
Yes. It should cover _all_ of the `Network.HTTP.*` modules I believe, including `.Simple` and `.Conduit`. There may be exceptions to this rule that pop up when reviewing the code, I'm not sure. Please also update the hlint rules to forbid importing those other modules directly in.

**Comment by NorfairKing** [comment]
@snoyberg How about `Network.HTTP.Download` and `Network.HTTP.Download.Verified`?

**Comment by NorfairKing** [comment]
Looks like this is done now.
