### ISSUE TITLE
stack upload freezes forever until it's ctrl+c'd

### ISSUE THREAD

**Issue by mkawalec** [commercialhaskell/stack#4116]
### General summary/comments (optional)

When running `stack upload` it freezes without any output to the user until I ctrl+c and then it asks if I'd like to save credentials to a file twice.

### Steps to reproduce

Run `stack upload` in a package directory

### Expected

No freeze and a package published

### Actual

Freeze until ctrl+c'd

Here's the output https://gist.github.com/mkawalec/0920bb8f0af97c7882d79d7dd381204d

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by ncaq** [comment]
relation?

#4063 
#4069

**Comment by dbaynard** [comment]
Possibly. @mkawalec Would you be able to check with current `master` branch of `stack`? It's possible that #4069 has fixed it.

After the second prompt, does it publish the package?

**Comment by mkawalec** [comment]
Nope, it just prompts twice and exits. I will verify with `master` later today

**Comment by mkawalec** [comment]
Yep, `master` solves the issue, thanks @dbaynard :)
