### ISSUE TITLE
Feature request: global install via `stack install -g`, like `npm install -g`

### ISSUE THREAD

**Issue by luochen1990** [commercialhaskell/stack#4123]
Developing a new package via stack is very convenient. But there is some situation which we want to install some packages just for their compiled binary executable files as a command line tool,  instead of developing a new package.

I have considered about the global project design in stack, but it seems not always works, e.g. when there are two or more tools we want to install which are depending on different LTS versions, we cannot specify them specifically in `~/.stack/config.yaml`.

But in another way, the `npm`'s (npm is a package manager for NodeJS) design is pretty good: when we want to install dependences to develop a new package, we simply use `npm install`,  and when we want to install some package as command line tool, we can use `npm install -g` (`-g` means `--global`), and this command will install the dependences independently for each global packages (from a user's point of view), the redundancy can be reduced by the optimization of the implementation of the package manager (thanks to [symver](https://semver.org)) .  The `-g` option will also tell the package manager to copy the executable binary files into a specific directory which has already added into PATH.

This mechanism makes it very convenient for people to install and use a npm module as command line tool.  I hope there could be a correspondence feature in stack, so that we can use the haskell written tools like [SourceGraph](https://www.stackage.org/package/SourceGraph) and [vacuum-cairo](https://www.stackage.org/package/vacuum-cairo) conveniently too.

**Comment by phadej** [comment]
Doesn't `stack install --resolver=lts-11.0 tool-a` and `stack install --resolver=lts-1.10 tool-b` work? How'd `stack install -g` know which snapshot you need/want to use (if it's different from global one)?

**Comment by mihaimaruseac** [comment]
@luochen1990 Please let us know if the suggestions mentioned by @phadej solve your usecase.

**Comment by luochen1990** [comment]
I tried to execute `stack install --resolver=ghc-7.8 SourceGraph` and it end up with `Plan construction failed`, it seems there is no way to continue unless I `stack new` a project.

**Comment by mihaimaruseac** [comment]
Oh, that's because `SourceGraph` is not within any snapshot. So you have to add it manually to a local snapshot, that is, a project.

**Comment by luochen1990** [comment]
I find that I'm still not able to install SourceGraph successfully,  when I execute `stack init --solver --omit-packages`, there is an error message about confliction of `haskell-src-exts`'s version.  And I can not use something like `stack init --solver --allow-newer` to solve it.

**Comment by mihaimaruseac** [comment]
Can you give us the full list of commands you're trying to run and the error message?

**Comment by luochen1990** [comment]
Following is the commands and messages:
```
$ git clone https://github.com/ivan-m/SourceGraph.git
$ cd SourceGraph
$ stack init --solver

Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- .\

Selecting the best among 13 snapshots...

* Partially matches lts-11.15
    Cabal version 2.0.1.1 found
        - SourceGraph requires ==1.22.*
    Graphalyze not found
        - SourceGraph requires >=0.14.1.0 && <0.15
    fgl version 5.6.0.0 found
        - SourceGraph requires ==5.5.*
    graphviz not found
        - SourceGraph requires >=2999.15.0.0 && <2999.19
    haskell-src-exts version 1.20.2 found
        - SourceGraph requires ==1.16.*

...

Selected resolver: lts-6.35
*** Resolver lts-6.35 will need external packages:
    Graphalyze not found
        - SourceGraph requires >=0.14.1.0 && <0.15
    haskell-src-exts version 1.17.1 found
        - SourceGraph requires ==1.16.*

Using resolver: lts-6.35

Warning: Installed version of cabal-install (2.0.0.1) is newer than stack has been tested with.  If you run into difficulties, consider downgrading.

Using compiler: ghc-7.10.3
Asking cabal to calculate a build plan...
Trying with packages from lts-6.35 as hard constraints...
CallStack (from HasCallStack):
  die', called at .\Distribution\Client\Install.hs:240:21 in main:Distribution.Client.Install
cabal.EXE: Could not resolve dependencies:
trying: SourceGraph-0.7.0.7 (user goal)
next goal: haskell-src-exts (dependency of SourceGraph-0.7.0.7)
rejecting: haskell-src-exts-1.20.2, haskell-src-exts-1.20.1,
haskell-src-exts-1.20.0, haskell-src-exts-1.19.1, haskell-src-exts-1.19.0,
haskell-src-exts-1.18.2, haskell-src-exts-1.18.1, haskell-src-exts-1.18.0
(constraint from main config C:\dev\msys2\tmp\cabal-solver10164\cabal.config
requires ==1.17.1)
rejecting: haskell-src-exts-1.17.1 (conflict: SourceGraph =>
haskell-src-exts==1.16.*)
rejecting: haskell-src-exts-1.17.0, haskell-src-exts-1.16.0.1,

...

haskell-src-exts-0.2.1 (constraint from main config
C:\dev\msys2\tmp\cabal-solver10164\cabal.config requires ==1.17.1)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: haskell-src-exts (85), SourceGraph
(22)
Could not parse cabal-install errors:

>>>> Cabal errors begin
<<<< Cabal errors end

CallStack (from HasCallStack):
  error, called at src/Stack\Solver.hs:130:25 in stack-1.7.1-EmhVRHO1dvE2LPJS2dX4Zb:Stack.Solver

```

**Comment by mihaimaruseac** [comment]
Thanks for the message report.

This seems to be an issue with the dependencies of SourceGraph, not Stack. Probably the owner of the project should update the constraints on some of them.

**Comment by mihaimaruseac** [comment]
In that case you could try adding `allow-newer: true` to the global `config.yaml`. But I don't think it will help, the entire `SourceGraph` project has dependencies in an [unbuildable state](https://matrix.hackage.haskell.org/package/SourceGraph).
