### ISSUE TITLE
Mitigate harm from Stack-repelling cabal packages

### ISSUE THREAD

**Issue by vedksah** [commercialhaskell/stack#4126]
The anti-Stack cabal has found a new way to sabotage Stack users: https://github.com/tonymorris/do-not-use-stack/issues/1

What can be done to prevent this? Maybe if it was harder to detect when Stack is being used that could foil this new petty discrimination against the Stack community?

**Comment by mihaimaruseac** [comment]
IMHO, we should not react to this at the moment. There's no feasible way the `Setup.hs` in that repo can get into other packages on Hackage, unless there is a large group of Haskell developers colluding.

**Comment by 23Skidoo** [comment]
For the record, I'd support banning such custom setups on Hackage if people started using them. That repo seems to be authored by a single individual.

**Comment by harendra-kumar** [comment]
In an _ideal world_ both stack users and cabal users would have some respect for each other.

**Comment by snoyberg** [comment]
Thanks for weighing in @23Skidoo 👍. I definitely owe you a beer or three.

**Comment by mihaimaruseac** [comment]
I propose we close this as won't do until the impossible happens and someone start using such custom setups on Hackage.

**Comment by snoyberg** [comment]
Agreed

**Comment by tonymorris** [comment]
> That repo seems to be authored by a single individual.

FYI, I am not the author of that repo.

**Comment by vedksah** [comment]
@tonymorris who is?
