### ISSUE TITLE
stack new is very slow at compiling Mustache templates

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4133]
Actions:

* Install a recent HEAD version of Stack. I'm using d5b5f77efb9d5fbd667847cb020b545b667bc3fd
* Run `stack new foo yesodweb/simple`

Expect: it will generate the output in under 5 seconds

Actual: it takes a full minute to compile the Mustache template

I'm guessing the move over to `mustache` from `hastache` triggered this. The Yesod templates may be an extreme case because they include large base64-encoded binary blobs for images. I'll try applying the templates to one file at a time instead and see if it speeds things up.

CC @borsboom @JustusAdam

**Comment by snoyberg** [comment]
I've determined that this can be triggered by trying to compile the [bootstrap.css file](https://gist.github.com/snoyberg/05082c63665a0c05becf82a5ff0f4183), which weighs in at 149kb. Proposed workaround: I'm going to add an arbitrary limit to `Stack.New` to only apply mustache to files smaller than 50kb.

**Comment by JustusAdam** [comment]
Hmm ... I wouldn't be surprised if that's the parser. Perhaps someone with more experience in writing parsers can take a look at it?

**Comment by snoyberg** [comment]
@JustusAdam I'd love to do so, but unfortunately I likely won't have time for that in the next few weeks at least, I've got a bunch of major things on my plate I'm going to have to focus on, sorry.
