### ISSUE TITLE
Stack produces wrong terminal color codes for file paths

### ISSUE THREAD

**Issue by pakettiale** [commercialhaskell/stack#4139]
### General summary/comments (optional)

Given that in stack/scr/Stack/PrettyPrint.hs style for the files is
```
styleFile = bold . white . ondullblack
``` 
this should correspond to ANSI code `^[[1m^[[37m^[[40m` however stack outputs `^[[1m^[[97m`.

[See this gist for ANSI codes](https://gist.github.com/chrisopedia/8754917).

### Steps to reproduce

1. Enable script to see raw output: `script debug_stack_output`.
2. Run command `stack ghci` outside of any project.
3. Stack outputs a note regarding missing project and some paths in the note may be printed in a color that's invisible (depands on your terminal color scheme).
4. Type `:q` into ghci propt.
5. Type `control-d` to stop script command.
6. View `debug_stack_output` in an editor `vim debug_stack_output`.
7. You should see a line
```
* If you want to start a different project configuration than ^[[1m^[[97m/home/username/.stack/global-project/stack.yaml^[[0;1m^[[0m,
```
8. Despite the definition in stack/scr/Stack/PrettyPrint.hs
```
styleFile = bold . white . ondullblack
``` 

### Expected

When running `stack ghci` outside of any project the note should have paths printed in bold white on a black backgroud.

### Actual

The paths were printed on bold white on white backgroud.

### Relevant Places in stack Source:
[display stackYaml](https://github.com/commercialhaskell/stack/blob/dd76afa05993eef51631d5121d00e932e930b51c/src/Stack/Ghci.hs#L792)
[instance Display (Path b File)](https://github.com/commercialhaskell/stack/blob/466da22ce21cddc20323fc2611cd2a2d3cc56ec6/src/Stack/PrettyPrint.hs#L219)
[styleFile](https://github.com/commercialhaskell/stack/blob/466da22ce21cddc20323fc2611cd2a2d3cc56ec6/src/Stack/PrettyPrint.hs#L181)

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mihaimaruseac** [comment]
Is this on Windows or any OS?

**Comment by pakettiale** [comment]
Happens on Linux, can't test on Windows.

**Comment by mpilgrem** [comment]
I can't reproduce this (using `Version 1.8.0, Git revision 861cf3229235ba22aa98b1fa8958e208a1cd10cf (dirty) (6002 commits) x86_64 hpack-0.28.2`). I'm on Windows 10, but the underlying `ansi-terminal` package's code is the same for Windows 10 and Unix-like operating systems.

I have `stack` outputting `\ESC[1m\ESC[97m\ESC40m` before the filenames.

Note that `white` in `styleFile = bold . white . ondullblack` refers to 'vivid' white (`\ESC[97m`) and not to 'dull' white (`\ESC[37m`).

If the intent was indeed 'dull' white, the line should be:

`styleFile = bold . dullwhite . ondullblack`

**Comment by mihaimaruseac** [comment]
I was not able to reproduce either, neither on Linux nor on Mac. I think these are changed from between 1.7.1 and 1.8.0.

@pakettiale, can you please try with 1.8.0? Either upgrade to it via `stack upgrade --git` or wait a few days until the release of the new Stack version.

**Comment by pakettiale** [comment]
I can confirm that `Version 1.8.0, Git revision 864c35e23a6f43129e28436b1daac8821be93117 x86_64 hpack-0.29.0` from git solves this issue for me.
