### ISSUE TITLE
install lts-12.0 on Fedor: no GHC bindist

### ISSUE THREAD

**Issue by CarstenKoenig** [commercialhaskell/stack#4147]
### General summary/comments (optional)

I'm reporting this on behalf of this [reddit thread](https://www.reddit.com/r/haskell/comments/8xw4tl/when_will_843_support_fedora_28/)

It seems that right now you cannot install Stack/GHC-8.4.3 on Fedora because some
distribution specific bindings are missing.

### Steps to reproduce
1. setup a VM or container running Fedora
2. curl -sSL https://get.haskellstack.org/ | sh
3. stack --compiler ghc-8.4.3 ghci

### Expected

Stack installs GHC-8.4.3 in a sandbox

### Actual

Error:

```
Writing implicit global project config file to: /home/vagrant/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-12.0
Downloaded lts-12.0 build plan.    
No setup information found for ghc-8.4.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6', 'linux64-tinfo6'.
Supported versions: ghc-7.8.4, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.1, ghc-8.4.2
```

### Stack version

current installed by script at the time of writing (should be `1.7.1`)

### Method of installation

    curl -sSL https://get.haskellstack.org/ | sh

**Comment by ncaq** [comment]
duplicate?
#4144

**Comment by CarstenKoenig** [comment]
@ncaq oh yes - I searched for Fedora and did not find this - sorry
