### ISSUE TITLE
Unable to build a stack project

### ISSUE THREAD

**Issue by asheshambasta** [commercialhaskell/stack#4164]
Please use the following schema for your bug report:

### General summary/comments (optional)

I've been noticing that all builds with older resolvers have started failing on my machine. I'm also not sure I fully understand what is going on, so this bug report might be in vain. But anyway, I'll try my best to explain what is going on.

### Steps to reproduce

1. `git clone git@github.com:sam142/hasencrypt.git`
2. cd hasencrypt
3. 
```
-> % stack setup
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-nopie' [-Wunused-command-line-argument]
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
```
4. `stack build --verbose` (see output below)

### The project I'm talking about has a stack.yaml:

```
resolver: lts-8.12
packages:
- '.'
extra-deps:
- jose-0.6.0.1
flags: {}
```

### Expected

Stack should've installed the GHC relevant to the project and compiled successfully. There's another project that I have that used to work OK for an older version of Stack/Cabal but no longer builds with the same error.

### Actual

Couldn't build.

```
$ stack build --verbose 
```

[See output here.](https://gist.github.com/asheshambasta/dfebaf2141b818f8010307c66b00d1f7)

### Stack version

```
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

[Haskell Platform](https://haskell.org/platform/download/8.4.3/Haskell%20Platform%208.4.3%20Core%2064bit-signed.pkg)

**Comment by mihaimaruseac** [comment]
This doesn't seem to be a stack bug but rather just bad state of dependencies of the package you're trying to build

**Comment by dbaynard** [comment]
Yes, it is concerning that the output gist recommends upgrading base. That means the GHC version is incompatible with the versions of some of the dependencies you are using.

If you just want to build the thing, try `allow-newer`. I was able to get the dependencies to build using a resolver based on lts-10.9… but the package doesn't. There's an aeson/wreq incompatibility. Should be a straightforward fix for that — it's just import issues.

I'm investigating the build with the original resolver — I'll check back in shortly.

**Comment by dbaynard** [comment]
Builds fine for me. Try `allow-newer`; if that fixes it, please close.

**Comment by dbaynard** [comment]
That's a classic. If you want to get your hands dirty on that particular error, try the 'prettyprinter' library.

**Comment by asheshambasta** [comment]
@dbaynard okay, thanks. I'll give this a shot, but it looks like something on my system is totally borked. 

Something as simple as `stack repl --package lens-tutorial` is broken;
[Gist here](https://gist.github.com/asheshambasta/6cab6b150a2b5603aeb9f4bd240a98c4)

So I'm not sure what is going on. Being a Haskell beginner, this error message doesn't really make much sense to me.

Anyway, looks like its time to dig in.

**Comment by asheshambasta** [comment]
Ok, after weeks of dabbling with this (on and off), it all doesn't make any sense to me. The basic question I'm wondering about is: what broke this project all of a sudden?

What stack offers is this:

- I define a project snapshot which has a particular GHC version and packages that play nicely in that snapshot, in this case, it was 8.13
- Stack then figures this out and installs a sandboxed GHC _for this project_.
- Stack versions are backward compatible (?)
- Each stack version specifies a cabal version that it is compatible with
- I upgrade stack/cabal on my system, it _should not break_ a project that used to work as long as stack is compatible with the cabal installed on the system.

So I _did_ upgrade stack and cabal on this system and things broke. Suddenly, without even changing the snapshot, a project that used to build is now broken and `stack ghci` (and other stack commands) exit with a cabal build error.

I think its very important that I understand this correctly (for me) because this is a complete mystery for me. This project is still supposed to be on the same GHC version as before and it should build with newer versions of cabal/stack. I also don't understand: why am I building cabal as a dependency at all? 

I'm new to Haskell and this is really complex and mysterious to me. This project also has months of work which no longer build, so I'd really like to get to the bottom of this so I'm safe from now on.

I'd truly appreciate if someone would clarify that. I'm genuinely interested in understanding these build issues – in my short stint with Haskell, I seem to have run into _a lot_ of issues similar to this, and there doesn't seem to be a clear understanding amongst beginners like myself.

**Comment by asheshambasta** [comment]
So after @cocreature's very generous help on #haskell my understanding of this seems to have advanced a bit.

One of the things that he pointed me to was that the errors looked like the bindist stack caches under ~/.stack aren't stack-version compatible. And since I upgraded stack, stack was still attempting to use the cache stored by a previous version of stack. 

And @cocreature's suggested workaround fixed the issue for me:
```
stack setup --reinstall
```

Which is basically asking stack to reinstall all it caches per project. 

Whats also mysterious (to newbies like myself) is that removing .stack-build seems to have no effect, which is also confusing.

**Comment by dbaynard** [comment]
> What stack offers is this:

The goal is to offer a straightforward build tool with sensible defaults, based on a set of packages that are known to work together. If it doesn't do that, it's a bug — it may be a known, documented bug, but still a bug. If you can't figure out how to do it, the documentation could (almost certainly) be improved.

I'm not familiar with the `--reinstall` command. One way to perform a hard reset is to back up `~/.stack/config.yaml` and `~/.stack/global-project/stack.yaml`, delete the `~/.stack` folder (in addition to any `.stack-work` folders) and begin again.

If you're getting to a point where you're running the repl and then `main` isn't working, it is _probably_ not a stack issue — that said, I haven't tested the hasencrypt project again.

**Comment by asheshambasta** [comment]
@dbaynard Thanks for replying. I think there are a few things at play here:
- how stack treats its caches: and if a cache from a previous version is compatible with the newer
- documentation on how to _reset_ a project
- documentation on what kind of cache goes where – where is the sandboxed GHC installed, and where are the project dependencies etc.

Much of my confusion here seems to have stemmed from a combination of these factors. If my hypothesis above is correct, I'll document what I did (that led to this situation) here:

- worked on a project on `lts-8.13` for a while, all worked as expected
- upgraded to `lts-11.14`, which broke some dependencies (esqueleto in particular, which is not available on >= `lts-10.*`)
- in the process somewhere, out trying several things, I upgraded Stack and Cabal
- that broke the project with the cryptic `cabal-1.24.*` errors that threw me off
- in the process somewhere, I also upgraded MacOS to latest, which seems to have conflated the isssue

Apparently, this was happening because of what @cocreature explained – the bindist in ~/.stack was no longer compatible with the newer version of stack, or something similar happened.

It could've been avoided by (correct me if any of my assertions are wrong here):
- stack keeping version specific caches under `.stack-work` and `~/.stack`

I see that the cache sub-directories under these can be also specified under stack version as  well – making it possible for users to have multiple versions of stack running and each actively using the cache.

What this possibly conflates is the amount of cache-garbage that will collect over time, which can be cleared with a stack option?

And yes, the problem with the `main` function isn't really specific to stack but the ghci settings:

```
Loaded GHCi configuration from /private/var/folders/kx/y9231gps2fldv7xgpk3xpjw00000gn/T/haskell-stack-ghci/6368aa83/ghci-script
λ> main
Too late for parseStaticFlags: call it before runGhc or runGhcT
```
Expunging `/private/var/folders/kx/y9231gps2fldv7xgpk3xpjw00000gn/T/haskell-stack-ghci` seems to correct this issue.

**Comment by asheshambasta** [comment]
Also, contents of the `ghci-script` file in particular:
```
-> % less /tmp/haskell-stack-ghci/6368aa83/ghci-script
:add App.DB.Helpers App.Errors App.Errors.AreaNodes App.Errors.Users App.Logging App.Routes.AreaNodes.Auths App.Routes.AreaNodes.Updates App.Routes.Helpers App.Routes.Hooks.AreaNodes App.Routes.Hooks.Users App.Routes.Users App.Routes.Users.Areas App.Types App.Types.MQ App.Types.Spock Data.Types.Area Data.Types.AreaNode Data.Types.CustomFields Data.Types.Grants Data.Types.Node Data.Types.Permissions Data.Types.Reporting.Backends Data.Types.Reporting.Report Data.Types.Security.Tokens Data.Types.Security.User.Auth Data.Types.Updates Data.Types.User Lib Lib.Ids Lib.JSON Lib.Text Lib.Time /Users/asheshambasta/code/haskell/spock/Spock-rest/app/Main.hs
:module + App.DB.Helpers App.Errors App.Errors.AreaNodes App.Errors.Users App.Logging App.Routes.AreaNodes.Auths App.Routes.AreaNodes.Updates App.Routes.Helpers App.Routes.Hooks.AreaNodes App.Routes.Hooks.Users App.Routes.Users App.Routes.Users.Areas App.Types App.Types.MQ App.Types.Spock Data.Types.Area Data.Types.AreaNode Data.Types.CustomFields Data.Types.Grants Data.Types.Node Data.Types.Permissions Data.Types.Reporting.Backends Data.Types.Reporting.Report Data.Types.Security.Tokens Data.Types.Security.User.Auth Data.Types.Updates Data.Types.User Lib Lib.Ids Lib.JSON Lib.Text Lib.Time
```

I still don't see what could've caused the ghci issue from this file and what changed after removing it.

I only see that invoking `stack ghci` now loads ghci settings from `~/.ghci`.

**Comment by mihaimaruseac** [comment]
This seems like a scenario that is very hard to detect and prevent, unfortunately. However, based on your updates about it, it's clear that we need more documentation to Stack, so I think we all would be glad to see more documentation PRs and updates.

**Comment by asheshambasta** [comment]
@mihaimaruseac while I agree there's room for improvement in documentation, but my assumption of why things broke is because Stack was using the same installation of GHC across its own, or my OS's version. And if that assumption is correct, there's something to be changed in Stack's caching/sandboxing logic as well, no?
