### ISSUE TITLE
No uninstall instructions

### ISSUE THREAD

**Issue by guysoft** [commercialhaskell/stack#4170]
### General summary/comments 
In the docs there is only an install section
The only install instructinons are:

``curl -sSL https://get.haskellstack.org/ | sh``

But there ins not information where things are saved and how to remove them.

### Steps to reproduce

For example:

1. Install
3. Try to uninstall

**Comment by guysoft** [comment]
Might want to include in the docs https://github.com/commercialhaskell/stack/issues/3563#issuecomment-343013109

**Comment by mihaimaruseac** [comment]
Thanks. Would you like to submit a PR adding to the docs?

**Comment by guysoft** [comment]
See #4171

**Comment by guysoft** [comment]
Here #4172

**Comment by mihaimaruseac** [comment]
Thank you.
