### ISSUE TITLE
Allow supplying git credentials

### ISSUE THREAD

**Issue by tejon** [commercialhaskell/stack#4174]
Motivation is to fetch private repos via extra-deps. Not sure if there's a way to enable this e.g. for docker deployment _without_ committing credentials in a Dockerfile, but that's not necessarily an absolute constraint since this is primarily for working with private repos anyway.

A current viable work-around is to manually include the dependency as a git submodule.

**Comment by snoyberg** [comment]
I'm -1, this seems like a security hole waiting to happen. Unless someone has a proposal for doing this safely, I'm going to close

**Comment by snoyberg** [comment]
Closing as wontfix
