### ISSUE TITLE
Suggestion: Make Stack.PrettyPrint's styles background agnostic

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#4183]
Should the _styles_ set in module `Stack.PrettyPrint` force the background to be black ('dull' black)? For example (line 181) `styleFile = bold . white . ondullblack`. Beauty is in the eye of the beholder, but it seems to me that, for people using terminal themes with coloured backgrounds, the result is not pretty. For example, on a Mac Terminal with theme 'Novel':

![image](https://user-images.githubusercontent.com/14206448/43356665-ccd7b8c8-926c-11e8-819f-f639b52d85a3.png)

I suggest it would be better to be agnostic as to background and have (for example): `styleFile = bold . white`.

This is on `stack --version` `Version 1.8.0, Git revision 94d302c40d3d08dcaa0213f3f1ffdc1384842714 (6077 commits) x86_64 hpack-0.29.0` (given #4139).

**Comment by mihaimaruseac** [comment]
The problem is that text becomes harder to read on terminals with white background. So, unless we can find a solution which detects the background before determining what color to use, we will have to also set background color.

**Comment by mpilgrem** [comment]
This comment is also in response to the comments of @mihaimaruseac on the pull request #4184.

I acknowledge that if you do not force the background colour, there will always be some choice of terminal background colour that makes certain coloured foreground text 'invisible' - but perhaps stack does not need to accommodate all possible terminal background colours, only the most likely ones (including the extremes of dull black and vivid white)?

On a white (vivid white) terminal do you think it is only the 'bold vivid white' text on white (used by `styleFile` and `styleUrl`) that is problematic? If it is, perhaps a different foreground colour there would solve the problem.

For example 'vivid black' (black) or 'dull white' (which are both actually rendered as shades of grey on most terminals - [see here](https://en.wikipedia.org/wiki/ANSI_escape_code#3/4_bit)) should have contrast on most terminal backgrounds.

This is 'vivid black' for `styleFile` on macOS Terminal's 'Basic' (white) theme:

![image](https://user-images.githubusercontent.com/14206448/43360601-3bb4c824-92b0-11e8-8a81-b56285362dd8.png)

This is 'vivid black' on Terminal's 'Novel' theme:

![image](https://user-images.githubusercontent.com/14206448/43360592-e79b64e6-92af-11e8-8113-17d8c7fad43c.png)

Alternatively (skipping shades of green and red as having special meaning or colours where the unused dull version is not particularly distinct from the vivid one), 'dull magenta' is currently not used by any style.

If that is an acceptable fix, I'll propose another pull request, accordingly.

**Comment by mihaimaruseac** [comment]
I tend to agree with this.
