### ISSUE TITLE
Avoid build plan download on exec

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack#4193]
When doing `stack exec` when the resolver is not the same as the one that was use last. I think it would be better just to execute the code with a warning about this than to try to update things. Right now it will do something like this:

```
Downloaded lts-12.4 build plan.    
Didn't see OpenGLRaw-3.3.0.2@sha256:34cb6e2c3425bd51721208c5f46d0fb15ce5385d865c857282a1ed1ec03037d7,25006 in your package indices.
Updating and trying again.
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading timestamp                                                                            
UpException user interrupt when using mirror https://s3.amazonaws.com/hackage.fpcomplete.com/      
Selected mirror http://hackage.fpcomplete.com/                                                   
Downloading timestamp                                                                            
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/)
```
(aborted after this)

Would be better to detect if the binary was properly build and then:
```
shell>
Warning: executing <program> based on resolver <resolver> when <resolver> was found in the stack configuration, build again to execute <program> using the configured resolver
<program stdout & stderr>
shell>
```

This helps to avoid unintended download, recompilation, and other things that change what stack is doing.

**Comment by mihaimaruseac** [comment]
Related to #4181, though that one is on clean.

**Comment by dbaynard** [comment]
I think this is intended behaviour. `stack exec` should download the build plan if missing, update the hackage cache if needed, and do everything else needed (e.g. building dependencies) to execute the code.

I'm going to close — do reopen if I've completely misunderstood what you're saying (or just comment if I've slightly misunderstood)

**Comment by flip111** [comment]
@dbaynard the intended behaviour does not work when there are download problems. Right now there is no help from stack to go back to the previous working build. Will trying-to-download-other-resolver leave the previous build intact? What was the previous build? What setting should be changed?
I still think having to do an explicit `stack build` after resolver change makes more sense. But if this undesirable than something like "hello it's stack, i noticed that you have download problems, would you like to execute the previous binary that was build with resolver XXX ? Or would you like to try to rebuild your code based on the old resolve packages?"

**Comment by dbaynard** [comment]
I think I see what you mean. You're saying `stack` should infer from the state of your filesystem that it can build a project without downloading any extra files and offer to do that instead — is that correct?

If so; then I disagree with your statement that the intended behaviour doesn't work. Using anything other than the supplied resolver (specified in the stack.yaml file or on the command line) is problematic as it means builds are not reproducible — a very clear goal of `stack`. And if you can't download the required dependencies, you can't run the code as configured.

---

> Will trying-to-download-other-resolver leave the previous build intact?

Yes

> What was the previous build?

Stack currently does not know this information.

> I still think having to do an explicit stack build after resolver change makes more sense.

What if you don't know you've changed the resolver?

> But if this undesirable than something like "hello it's stack, i noticed that you have download problems, would you like to execute the previous binary that was build with resolver XXX ? Or would you like to try to rebuild your code based on the old resolve packages?"

You can manually set stack to use the previous resolver — would that not suffice for this?
