### ISSUE TITLE
Building dynamic library on linux-x86_64 fails with warning to rebuild RTS with -fPIC

### ISSUE THREAD

**Issue by mgajda** [commercialhaskell/stack#4194]
# General comments

Not sure why `-fPIC` is missing when building RTS? Or should we have one more of RTS-ways?

# Steps to reproduce

1. `git clone https://github.com/mgajda/HaPy` (example shared library project).
2. `cd example/haskell; stack build`

_stack.yaml_:
```
resolver: lts-12.4
```
_*.cabal file_:
```
library
  other-extensions:    ForeignFunctionInterface, TemplateHaskell
  ghc-options: -fPIC -pie -dynamic -shared -dylib-install-name=ExampleModule
  extra-libraries: HSrts
```
### Expected

Compile a `dlopen`able dynamic library, like the same code does on Darwin.

### Actual

A lot of errors about missing `-fPIC` in RTS build:
```
    /usr/bin/x86_64-linux-gnu-ld.gold: error: /home/m/.stack/programs/x86_64-linux/ghc-8.4.3/lib/ghc-8.4.3/ghc-prim-0.5.2.0/libHSghc-prim-0.5.2.0.a(popcnt.o): requires unsupported dynamic reloc 11; recompile with -fPIC
    collect2: error: ld returned 1 exit status
    `gcc' failed in phase `Linker'. (Exit code: 1)
```

I suspect that GHC 8.4.3 RTS is built without `-fPIC` on the Stackage infra.

# Stack version

```
Version 1.8.0, Git revision 78762f94d371e68aaa0dd8071bb9b97c3d7760de (6082 commits) x86_64 hpack-0.29.0
```
Platform is Ubuntu 18.04:
```
Linux pigwa 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

# Method of installation

Stack was built by latest stackage.org (1.7.1) from fpcomplete's GitHub repo (without changes).

**Comment by mgajda** [comment]
Maybe related to issue #2158.

**Comment by mihaimaruseac** [comment]
Tried to reproduce on my end.

First try, the build got stuck on a seemingly infinite loop while trying to build `ExampleModule`. I `Ctrl-C`'ed it and tried building again and then got the linker error messages as reported.

Did another `stack clean` and `stack build` and got it back to the infinite loop/extremely slow build. The linker errors showed up again after <key>Ctrl</key>-<key>C</key>

**Comment by mgajda** [comment]
Continues to be an issue with the current Stack release:
```
Version 1.9.1, Git revision f9d0042c141660e1d38f797e1d426be4a99b2a3c (6168 commits) x86_64 hpack-0.31.0
```

**Comment by mihaimaruseac** [comment]
Still getting the same infinite loop issue :confused:

**Comment by snoyberg** [comment]
We use the upstream GHC releases, not Stack or Stackage specific ones. This should probably be filed upstream with GHC HQ.

**Comment by snoyberg** [comment]
Closing as an upstream issue
