### ISSUE TITLE
Windows 10: Colors get mangled

### ISSUE THREAD

**Issue by Gurkenglas** [commercialhaskell/stack#4199]
### Steps to reproduce

1. Have this Windows 10 Home machine.
2. Run any stack command that produces colored characters.
3. Gouge out eyes.

Analogous to https://github.com/drud/quicksprint/issues/55. Happens in PowerShell and cmd.exe too, even in VS Code.

### Stack version

```
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

HaskellPlatform-8.4.3-core-x86_64-setup.exe

**Comment by dbaynard** [comment]
Hi, I think this has been fixed in the current `master` branch. There'll be a new version out soon, before then you can `stack upgrade --git` to update to that version, and you will no longer _have_ to gouge out your eyes.

**Comment by Gurkenglas** [comment]
Thanks. I suppose I should have removed the "is:open" filter before searching.

**Comment by dbaynard** [comment]
Sadly there's no single issue, otherwise I'd have referenced it. It relates to #3992, #4012, #4091, #4106, with #4121 thrown in for good measure.
