### ISSUE TITLE
Docker Files Verify Checksums 

### ISSUE THREAD

**Issue by ChristopherDavenport** [commercialhaskell/stack#4200]
When integrating the docker images, specifically https://github.com/commercialhaskell/stack/blob/master/etc/dockerfiles/stack-build/lts-12.0/Dockerfile . 

I had this request from my infrastructure team and I would love to get this operational across the community if there is interest for it to be done this way.

**Comment by ChristopherDavenport** [comment]
Specific calls in question are 

https://github.com/commercialhaskell/stack/blob/master/etc/dockerfiles/stack-build/lts-12.0/Dockerfile#L29
https://github.com/commercialhaskell/stack/blob/master/etc/dockerfiles/stack-build/lts-12.0/Dockerfile#L54
https://github.com/commercialhaskell/stack/blob/master/etc/dockerfiles/stack-build/lts-12.0/Dockerfile#L62

Since these are all github releases the checksums are available so if this is desired I can implement this.

**Comment by mihaimaruseac** [comment]
I don't understand exactly what you are proposing, but I marked it as "in progress" anyway and will see on a PR.

**Comment by ChristopherDavenport** [comment]
So it turns out I was operating completely incorrectly and trying to build the final image off the build image, everything is fine the way it is.
