### ISSUE TITLE
Support the NO_COLOR environment variable

### ISSUE THREAD

**Issue by ajgrf** [commercialhaskell/stack#4204]
Currently the only way to tell stack to suppress color is by passing `--color never` as an argument. A user who wishes to never see color might try to define a shell alias, but this is not always interpreted correctly by stack. For example:

    $ alias stack='stack --color never'
    $ stack foo
    Invalid argument `foo'
    File does not exist or is not a regular file `--color'
    
    ...

More importantly, this is stack-specific configuration which does not live in stack's config files. The [NO_COLOR](http://no-color.org/) environment variable is a proposed informal standard for signaling that programs should not emit colored output unless explicitly configured to. It is already used by a number of other popular tools, and might even be set before a user installs stack.

This feature would make stack nicer for users like me, who prefer less color, or whose unusual terminal colors make some of stack's output appear unreadable.

**Comment by snoyberg** [comment]
Looks like this was already added, closing
