### ISSUE TITLE
Allow user specification of stack's colours

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#4205]
See: #4183 (and #4047), #4204 and #2650.

Module `Stack.PrettyPrint` defines 11 colourful styles for stack's output identified as 'error', 'warning', 'good', 'shell', 'file', 'url', 'dir', 'recommendation', 'current', 'target' and 'module', using ANSI codes. However, the SGR sequences are hard coded and cannot be changed from their default by stack's users. No single default choice will work well with all, or even all popular, terminal themes.

Contrast this with [GHC's approach](https://downloads.haskell.org/~ghc/8.4.3/docs/html/users_guide/using.html?highlight=color#ghc-flag--fdiagnostics-color=%E2%9F%A8always%7Cauto%7Cnever%E2%9F%A9), which allows users to vary the default by specifying a colon-separated list of key=value pairs, where the value is the SGR code (or semi-colon delimited list of codes, if more than one code is required). GHC does this through the environment variable `GHC_COLORS` (or `GHC_COLOURS`).

I suggest that (EDIT: to-do list created):
- [x] 0. existing stack be prepared for steps 1 to 6 that follow
- [x] 1. stack allows users to vary the default styles
- [x] 2. stack follow GHC's approach to style definition (the colon-separated list of key=value pairs)
- [x] 3. rather than use an environment variable, this be done via an option `--stack-colors=`
- [ ] 4. `stack-colors` also work in a `config.yaml` file in the same way
- [x] 5. the command `stack ls stack-colors` would list the currently applicable key=value pairs. As a side-effect, this command would also serve to document what 'keys' were applicable from time to time if the 11 styles should ever be extended or renamed.
- [ ] 6. if possible, 'colours' would be a synonym for 'colors' in options and commands.

If acceptable, I would be happy to attempt to implement some or all of the above (although, I might need some help). I am assuming that the `Runner` type would need to be adapted to carry around the various styling functions.

**Comment by ajgrf** [comment]
I'm not sure if it is a coincidence that I happened to submit a color-related issue at the same time as this one, but I guess I should explain how #4204 would interact with this issue.

1. If the environment variable [NO_COLOR](http://no-color.org/) exists, stack would suppress color by default.
2. Color-related settings in stack's config file, like the ones discussed in this issue, would override NO_COLOR.
3. A command line argument like `--color` or `--stack-colors=` would override both the config file and NO_COLOR environment variable.

**Comment by mihaimaruseac** [comment]
That is indeed the better way forward, I think

**Comment by mpilgrem** [comment]
I've been thinking about a 'step 0', which prepares existing stack for 'step 1' above without changing stack's current functionality. Is the following on the correct lines (I hope it makes sense to people in the know)?

My understanding of what currently happens with output is that

- at a relatively low level, stack annotates `Doc`s with lists of `SGR` from the `ansi-terminal` package (which I know well) (so: `newtype AnsiAnn = AnsiAnn [SGR]; type AnsiDoc = Doc AnsiAnn`). The functions that do that do not have access to the `HasRunner env` context (I'm not sure if 'context' is the correct terminology);
- functions `displayAnsi` or `displayPlain` (from module `Text.PrettyPrint.Leijen.Extended`, used in module `Stack.PrettyPrint`) map the annotated `Doc` to `Text`. They also do not have access to the `HasRunner env` context (`displayAnsi :: (Display a, HasAnsiAnn (Ann a)) => Int -> a -> Text`); and
- that happens in `displayWithColor :: (HasRunner env, Display a, HasAnsiAnn (Ann a), MonadReader env m, HasLogFunc env, HasCallStack) => a -> m Text`.

I think that what needs to happen is that, at the 'low level', stack annotates `Doc`s with stack's _styles_ (using say, `data Style = Error | Warning | Good | Shell | ...`) and that `displayAnsi` or `displayPlain` becomes `displayAnsi :: (HasRunner env, Display a, HasAnsiAnn (Ann a), MonadReader env m, HasLogFunc env, HasCallStack) => Int -> a ->  m Text`. That is, I think:
- the description of all the styling that stack does needs to be more 'abstract' than 'annotate Doc as red' (eg 'annotate Doc as Error'); and 
- the functions that translate _styles_ into sequences of virtual terminal codes need to have access to the `HasRunner env` context and that the style-to-codes mapping needs to happen 'near the top' not 'down in the detail'.

**Comment by mpilgrem** [comment]
Following 'step 0', I've been thinking about 'step 5' (as its existence would allow the other steps to be tested more easily): a 'basic' list of styles could simply reproduce the equivalent argument of the option that would set those styles, for example:
````
stack ls stack-colors --basic
error=91:warning=33:good=92:shell=95:file=36:url=36:dir=1;94:recommendation=1;92:current=33:target=96:module=95:package-component=96
````
A 'full' (no-basic) list of styles could involve separate lines like:
````
recommendation=1;92 [SetConsoleIntensity BoldIntensity, SetColor Foreground Vivid Green] Example
````
where the `Example` text would be output applying the style in question (eg bold vivid green). The (optional) list of SGRs could be requested with flag `--[no-]sgr` and the (optional) example text could be requested with flag `--[no]-example`.

The default command could be equivalent to `stack ls stack-colors --no-basic --sgr --example`.

**Comment by mpilgrem** [comment]
If step 0 is acceptable/accepted, I have working pull requests available that implement everything except for step 4 (`config.yaml`) and (nice-to-have only) step 6 ('colour' a synonyn for 'color'). I hope to be able to turn to step 4 soon.
