### ISSUE TITLE
Very misleading error message when extra deps is misconfigured (git) in stack.yaml

### ISSUE THREAD

**Issue by theGhostJW** [commercialhaskell/stack#4223]
### Steps to reproduce

*case 1 ~ Correct Configuration*
```
extra-deps:
- foundation-edge-0.0.3
- git: https://theghostjw@bitbucket.org/principledautomation/extensions.git
  commit: "46245e6"
```

*case 2 ~ Commit not indented*
```
extra-deps:
- foundation-edge-0.0.3
- git: https://theghostjw@bitbucket.org/principledautomation/extensions.git
commit: "46245e6"
```

*case 3 ~ Commit quotes absent*
```
extra-deps:
- foundation-edge-0.0.3
- git: https://theghostjw@bitbucket.org/principledautomation/extensions.git
commit: 46245e6
```

### Expected

A meaningful, or at least not misleading, error message in case 2 and 3.

### Actual

```
$ stack test
Could not parse 'C:\pyrethrum\stack.yaml':
Aeson exception:
Error in $['extra-deps'][1]: failed to parse field 'extra-deps': failed to parse field 'github': key "github" not present
See http://docs.haskellstack.org/en/stable/yaml_configuration/

```

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2

```

**Comment by theGhostJW** [comment]
Hello @malteneuss 

> From a user's perspective it is strange that you'd get an error about GitHub when your repo is >hosted on BitBucket (or that the expected key isn't just "git") - I suppose that part could be changed.

Just removing the misleading information would close this issue. Something like:
```
Could not parse 'C:\pyrethrum\stack.yaml':
Error in $['extra-deps'][1]: Entry is not valid
See http://docs.haskellstack.org/en/stable/yaml_configuration/
``` 
I presume there is an alternative somewhere yielding this error and this case is just the last tried.

If no one else wants to pick this up I'll have a crack at it some time over the coming weeks. 

I am a relative newb so could tak a while.

**Comment by mattaudesse** [comment]
Great, thanks!

**Comment by dbaynard** [comment]
The way stack handles extra-deps has changed. Are you still working on this, @theGhostJW?

**Comment by theGhostJW** [comment]
I'll have a look

**Comment by theGhostJW** [comment]
Yep that's fixed 
Just gives me the line number which removes the misleading part of the info :-).

```bash
$ stack test
Could not parse 'C:\Pyrethrum\stack.yaml':
YAML parse exception at line 56, column 0,
while parsing a block mapping:
did not find expected key
See http://docs.haskellstack.org/en/stable/yaml_configuration/
````
