### ISSUE TITLE
Can't display -ddump-splices result.

### ISSUE THREAD

**Issue by waddlaw** [commercialhaskell/stack#4225]
```shell
$ stack build --ghc-options='-ddump-splices'
```

I want to display on the standard output, not to save to a file.

### Question

Why does the [extraBuildOptions](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Build/Execute.hs#L1948) function specify the `" -ddump-hi -ddump-to-file"` option by default?

```hs
extraBuildOptions wc bopts = do
    colorOpt <- appropriateGhcColorFlag
    let ddumpOpts = " -ddump-hi -ddump-to-file"
        optsFlag = compilerOptionsCabalFlag wc
        baseOpts = ddumpOpts ++ maybe "" (" " ++) colorOpt
    if toCoverage (boptsTestOpts bopts)
      then do
        hpcIndexDir <- toFilePathNoTrailingSep <$> hpcRelativeDir
        return [optsFlag, "-hpcdir " ++ hpcIndexDir ++ baseOpts]
      else
        return [optsFlag, baseOpts]
```

If remove this option, I think it will work as expected.

### Stack version

```
$ stack --version
Version 1.10.0, Git revision 3b61926935c28efd10c8e6870f927a7d8eb5523c (dirty) (6119 commits) x86_64 hpack-0.29.6
```

**Comment by mattaudesse** [comment]
Thanks @waddlaw - that seems like a really good question and I'm not sure what the answer should be!

I think @borsboom might be the best person to ask since that setting seems to have been added in [6e65345](https://github.com/commercialhaskell/stack/commit/6e65345a2779780e62fddb7b0d3fd519a4066d0f#diff-890614cc04afa326f5d48aac897e4aa8R988).

**Comment by snoyberg** [comment]
It's necessary to grab information available in the HI dump files, like `addDependentFile` information. The alternative would require an extra executable of the `ghc` executable for each `.hi` file, which is prohibitively expensive. I agree that the current situation is far from ideal, but it's AFAIK the best trade-off we have.

**Comment by waddlaw** [comment]
Thanks @snoyberg 

What about providing `stack build --ddump-dir` option. For example, following command run listed the outputed dump files.

```shell
$ find $(stack path --dist-dir) -name "*.dump-*"
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/src/Test.dump-simpl
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/src/Ins.dump-stg
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/src/Lib.dump-stg
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/src/Ins.dump-simpl
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/src/Lib.dump-simpl
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/src/Test.dump-stg
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/src/Lib.dump-splices
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/autogen/Paths_th_example.dump-stg
.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/.stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/autogen/Paths_th_example.dump-simpl
```

if these file move to the specified dump-dir, I think better than now (clearly output location). Perhaps not strictly correct the above result, but very useful for me. What do you think about this?

**Comment by snoyberg** [comment]
I'd be OK with such a PR. It may be simpler to copy the files from where they're currently output by GHC to a new location, instead of trying to convince GHC to use a new directory and then parse it. Are you interested in taking a stab at a PR?
