### ISSUE TITLE
`stack ghci` Extension Strangeness

### ISSUE THREAD

**Issue by iamrecursion** [commercialhaskell/stack#4228]
### General Summary
When loading a large [project](https://github.com/luna/luna) via `stack ghci`, where the project contains multiple packages (with different sets of extensions), the repl produces errors that do not occur when running `stack build`.

### Steps to reproduce
The issue can be reproduced as follows.

1. Clone [luna](https://github.com/luna/luna)
2. `cd luna`
3. `stack build --fast` (this will succeed)
4. `stack ghci` (select `2` when prompted for which main)

### Expected
I expect for the project as loaded into `stack ghci` to build if it builds for `stack build`. 

### Actual
The GHCi session fails with the following error: 

```
/home/ara/development/luna/luna/core/src/OCI/Data/Name/Qualified.hs:50:52: error:
    • Ambiguous type variable ‘t0’ arising from a use of ‘convert’
      prevents the constraint ‘(Convertible
                                  t0 Name.Name)’ from being solved.
      Probable fix: use a type annotation to specify what ‘t0’ should be.
      These potential instances exist:
        instance (TypeError ...) => Convertible t t
          -- Defined in ‘Data.Convert.Class’
        instance Convertible Name.Value Name.Name
          -- Defined at /home/ara/development/luna/luna/core/src/OCI/Data/Name/Class.hs:77:10
        instance Convertible Qualified Name.Name
          -- Defined at /home/ara/development/luna/luna/core/src/OCI/Data/Name/Qualified.hs:45:10
        ...plus three others
        (use -fprint-potential-instances to see them all)
    • In the first argument of ‘intersperse’, namely ‘(convert ".")’
      In the second argument of ‘(.)’, namely ‘intersperse (convert ".")’
      In the second argument of ‘(.)’, namely
        ‘Name.concat . intersperse (convert ".")’
   |
50 |     convert = convert . Name.concat . intersperse (convert ".")
   |                                                    ^^^^^^^^^^^

/home/ara/development/luna/luna/core/src/OCI/Data/Name/Qualified.hs:50:60: error:
    • Ambiguous type variable ‘t0’ arising from the literal ‘"."’
      prevents the constraint ‘(IsString t0)’ from being solved.
      Probable fix: use a type annotation to specify what ‘t0’ should be.
      These potential instances exist:
        instance IsString a => IsString (Identity a)
          -- Defined in ‘Data.String’
        instance IsString Name.Name
          -- Defined at /home/ara/development/luna/luna/core/src/OCI/Data/Name/Class.hs:83:10
        instance IsString Name.Value
          -- Defined at /home/ara/development/luna/luna/core/src/OCI/Data/Name/Class.hs:132:10
        ...plus three others
        ...plus 21 instances involving out-of-scope types
        (use -fprint-potential-instances to see them all)
    • In the first argument of ‘convert’, namely ‘"."’
      In the first argument of ‘intersperse’, namely ‘(convert ".")’
      In the second argument of ‘(.)’, namely ‘intersperse (convert ".")’
   |
50 |     convert = convert . Name.concat . intersperse (convert ".")
   |                                                            ^^^
```

The problem here is that the GHCi session is behaving as if `-XOverloadedStrings` is enabled in this package (`core/package.yaml` - it isn't), and this is causing type-variable ambiguity. If you put `{-# LANGUAGE NoOverloadedStrings #-}` at the top of the file, the issue goes away (and more pop up). 

This also seems to occur with the `PolyKinds` extension, and probably others that I've not yet found out. 

It should be noted that the particular error can change based on build order. [This](https://gist.github.com/kustosz/890c345410a4369ee7a93cc7a82fb9a8) is one that one of my teammates has encountered, which I believe is to do with `PolyKinds`. 

I'm reporting this here as I don't know if this is just an artefact of how GHCi works, or something that `stack` is doing, but you never know if you never ask!

### Stack version

```
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by RoelofWobben** [comment]
yes, this looks not right. I will ask the maintainers to look at it.

**Comment by iamrecursion** [comment]
Thank you!

**Comment by RoelofWobben** [comment]
oke, 

I have asked one of the maintainers of stack and it's not a stack problem.
The problem is that ghci cannot load multiple packages with different default-extension fields.

So a way to make this work is only load one package at the time.

**Comment by iamrecursion** [comment]
I did wonder that. I'm actually trying to load it in intero for interactive development, but the same problem occurs. 

This project has lots of dependencies between the packages, but that does answer the question! We'll need to find a process solution to the issue if we want this to work. Thanks for the quick response @RoelofWobben!

**Comment by RoelofWobben** [comment]
YW

**Comment by mgsloan** [comment]
FWIW `stack ghci` has code that will warn about these conflicts, so I would expect that there is a warning in the `stack ghci` output explaining the issue.  Probably got buried in compile errors.

**Comment by sol** [comment]
@iamrecursion when working with GHCi (or tools that build on top of it) the most robust way is still to list language extensions for each file individually and not use `default-extensions`.  This has the obvious downside that you waste cycles on maintaining these lists, but I'm not aware of any better approach.

**Comment by mgsloan** [comment]
@sol Yes, `stack ghci` actually used to do this and also used a special intero-only cd command that also fixed the TH relative path problem.  The problem is it does not work with `:reload` and so the complexity was not worth it.  It might be feasible to rerun the script, but then I don't think you'll get any incrementality in the reload.

I recall having a conversation with dcoutts and ezyang about this at ICFP a few years ago, and ezyang opened this trac ticket about it - https://ghc.haskell.org/trac/ghc/ticket/10827.  I think the best approach would be to address this directly in GHC.  I might get around to it sometime, I have been dabbling in GHC development lately, and this is high on my list of things I want.  No promises though, got a lot of concurrent projects atm, I would be very happy if someone else worked on it.

**Comment by sol** [comment]
@mgsloan oh, yes, you are right, `:reload` does indeed not work.  I would almost consider this a bug.

Your solution is more general which I think is great.  For me language extensions are the critical thing, but of course a more general solution wouldn't hurt.

**Comment by sol** [comment]
>  I would almost consider this a bug.

My reasoning is that I expect `:reload` to reload all modules in the same way (read same language extensions) as they were originally loaded.  But I realize that you might change a module to use some language extension, then use `:set` in `ghci` to enable that extension and then have the reasonable expectation that `:reload` will pick up that extension.  So no clear case here.  Handling this stuff as package properties as per your proposal sounds compelling.

**Comment by iamrecursion** [comment]
@sol This is a good point, and we may be able to standardise flags across the packages. It’s not exactly a long-term solution, however, so I would be quite interested in improving this in the future. Perhaps I’ll find some time to try and fix it at the GHC level once work slows down.

**Comment by mgsloan** [comment]
@sol There is certainly a UI issue here of how to specify which modules get which options.  I like this idea of making it so that GHCi remembers the options that were used at `:load` time.  I agree that it seems a bit bug-like.

It gets a bit tricky when it comes to cases like adding a module to a package.  What settings to use for this module?  In some cases, there may not be a right answer to this, as build units may use some of the same include dirs.  Could have a heuristic solution to this, but probably the best thing to do would be to have ghci consult an external process - in this case, stack.

Consulting an external process for configuration could have other benefits.  You might be able to modify your hpack configuration, and be able to do an incremental reload of it in ghci.  It would be great to have higher confidence that a reload within `stack ghci` indicates buildability via `stack build`.  Not sure what this would look like, only the seed of an idea really.

**Comment by mgsloan** [comment]
@iamrecursion I hope you get the spare cycles to work on it!  I'm in a similar circumstance where some other things are prioritized.  If you do dig into it please comment on https://ghc.haskell.org/trac/ghc/ticket/10827 to indicate that you're working on it and for design discussion

**Comment by iamrecursion** [comment]
I hope so too, but goodness knows if I'll get it soon! Busy busy as always, but we shall see. :)
