### ISSUE TITLE
Improve docs in upgrading the stack for Debian and Ubuntu

### ISSUE THREAD

**Issue by abs-zero** [commercialhaskell/stack#4234]
```
λ. stack upgrade --binary
Invalid option `--binary'

Usage: stack upgrade ([--source-only] | [--binary-platform ARG]
                     [--force-download] [--binary-version ARG]
                     [--github-org ARG] [--github-repo ARG]) ([--binary-only] |
                     [--git] [--git-repo ARG] [--git-branch ARG]) [--help]
  Upgrade to the latest stack
```
In [docs for upgrading stack](https://docs.haskellstack.org/en/stable/install_and_upgrade/#ubuntu), is the line `stack upgrade --binary` outdated and should it be changed?

**Comment by RoelofWobben** [comment]
Which version of stack are you using ?

**Comment by abs-zero** [comment]
Version 1.7.1 x86_64

**Comment by RoelofWobben** [comment]
yep, I see the same. I will ask the right maintainer to solve this ?

**Comment by RoelofWobben** [comment]
Can you maybe make a PR to the documentation is right ?

**Comment by abs-zero** [comment]
I definitely can but I am nut sure if the documentation is outdated or it's a bug in stack.

**Comment by RoelofWobben** [comment]
the documentation is outdated.

**Comment by abs-zero** [comment]
Thanks, I will try to make a PR.

**Comment by RoelofWobben** [comment]
oke, then we wait tlll you are done
