### ISSUE TITLE
error while loading shared libraries: libtinfo.so.6

### ISSUE THREAD

**Issue by crocket** [commercialhaskell/stack#4244]
### General summary/comments (optional)

`stack --resolver lts-12.6 setup` fails on gentoo due to the following error

```
error while loading shared libraries: libtinfo.so.6
```

### Steps to reproduce

```
stack --resolver lts-12.6 setup
```

### Stack version

Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2

### Method of installation

```
stack install stack
```

**Comment by RoelofWobben** [comment]
Can you check if you have ncurses and the libraries are installed ?

**Comment by RoelofWobben** [comment]
We will investigate things .

**Comment by crocket** [comment]
An ebuild for stack-1.7.1 has to require `tinfo` from `ncurses`, but I installed stack-1.7.1 via stack.
stack doesn't know about gentoo package system and cannot make gentoo install ncurses with tinfo.

**Comment by RoelofWobben** [comment]
Im not a gentoo expert but could you install ncursus again but then wirh the tinfo flag ?

**Comment by crocket** [comment]
I installed ncurses with tinfo and executed `stack --resolver lts-12.6 setup` with success. It seems ghc installed by stack shouldn't depend on system ncurses.

**Comment by dbaynard** [comment]
`stack` is often able to work out which variant of ncurses is available and install the correct ghc bindist. I don't think gentoo is supported in that sense.

You can use your stack config file to set this explicitly, as described in the documentation.

> `ghc-build`
> (Since 1.3.0)
>
> Specify a specialized architecture bindist to use. Normally this is determined automatically, but you can override the autodetected value here. Possible arguments include standard, gmp4, tinfo6, and nopie.

The ghc versions available are at <https://github.com/fpco/stackage-content/blob/master/stack/stack-setup-2.yaml> (I've deliberately used a relative url here) and there are versions build for some distributions — but not for gentoo.

**Comment by dbaynard** [comment]
> I installed ncurses with tinfo and executed stack --resolver lts-12.6 setup with success. 

I thought you'd fixed it!
