### ISSUE TITLE
auto-bundle windows executables or installers

### ISSUE THREAD

**Issue by radix** [commercialhaskell/stack#427]
To solve issues like https://github.com/commercialhaskell/stack/issues/425 , it would be nice if Stack could bundle up Windows installers, or at least self-contained executables that include things like the STDC++ dists. Depending on the way this works it may be appropriate as a [plugin](https://github.com/commercialhaskell/stack/issues/136).

I'm not really familiar with windows development/packaging at all so it'd be nice if someone else could clarify the use cases / requirements.

**Comment by snoyberg** [comment]
At this point, I'm going to call this kind of functionality out of scope for Stack.
