### ISSUE TITLE
Improved recompilation avoidance

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4272]
Each module which enables the `TemplateHaskell` language pragma gets recompiled more often than necessary when dependencies change. It would be nice to bypass that by removing the usage of TemplateHaskell. A number of modules in the codebase are only using TemplateHaskell to safely create `Path` values, e.g. `mkRelFile` or `mkRelDir`. I recommend collecting these usages into a single module, likely `Stack.Constants`, and importing for there. That would allow us to reduce recompilation time and improve the project iteration cycle a bit.

I'm open to this being shot down, since I'm not at all the expert on fast iteration cycles :). CC @chrisdone and @bitemyapp.

**Comment by chrisdone** [comment]
Agreed! :ok_hand:

**Comment by snoyberg** [comment]
See #4273.
