### ISSUE TITLE
exact-match for ghc should be default

### ISSUE THREAD

**Issue by andrewufrank** [commercialhaskell/stack#4277]
i had a case where a project (exact copy) compiles on two computers and not on the third - failing stack's guarantee...
the first issue was that for lts 9.9 the failing computer used 8.0.1 in stead of 8.0.2 as required for 9.9. I had to add 
    compiler-check: match-exact
to my config.yaml. 
I think that match -exact should be the default to guarantee that stack build always runs the same way; if one wants to be less strict, then the user should indicate his choice in config.yaml. The default should be strict.

**Comment by dbaynard** [comment]
Can you show the stack.yaml file that you've been using?

`compiler-check` can go in the stack.yaml file, too.

**Comment by snoyberg** [comment]
The described behavior doesn't match up with the current default of match-minor. Without a repro, closing.
