### ISSUE TITLE
improve message for dependency does not match

### ISSUE THREAD

**Issue by andrewufrank** [commercialhaskell/stack#4278]
I have received the message

    In the dependencies for Cabal-1.24.2.0:
    process-1.4.2.0  from stack configuration does not match >=1.1.0.1 && <1.5 (latest matching version is 1.4.3.0)
needed due to ltk-0.16.2.0 -> Cabal-1.24.2.0

and i cannot see where the process-1.4.2.0 comes from. I assume from the lts 9.9 - but it includes process-1.4.3.0. 

I would recommend that the message says something like 
    process-1.4.2.0 from lts-9.9 does not match ...

or indicate precisely wherever the process-1.4.2.0 comes from. 

thank you!

**Comment by qrilka** [comment]
@andrewufrank your proposed message `process-1.4.2.0 from lts-9.9 does not match` won't be correct, as you say above lts-9.9 includes version 1.4.3.0 and not 1.4.2.0 (and it seems that `stack` does say about that in that "latest matching version is 1.4.3.0")
Probably you could show some minimal `stack.yaml` giving that error so the reason could be found?

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because Stack 2.15.5 provides better information about what is meant by 'the stack configuration'.
