### ISSUE TITLE
Ubuntu installation uses insecure HTTP to download key

### ISSUE THREAD

**Issue by hdgarrood** [commercialhaskell/stack#428]
From https://github.com/commercialhaskell/stack/wiki/Downloads#ubuntu:

```
$ wget -q -O- http://download.fpcomplete.com/ubuntu/fpco.key | sudo apt-key add -
```

I'm not an expert but this seems like a bad idea. Could the key be delivered over HTTPS instead, please?

**Comment by snoyberg** [comment]
Since the key is on S3, that should be a trivial URL change in the docs. @dysinger?

**Comment by arianvp** [comment]
Also. the Archlinux AUR package pulls from an HTTP url as well. https://aur4.archlinux.org/packages/haskell-stack/

**Comment by snoyberg** [comment]
Pinging @drwebb on that one.

**Comment by dysinger** [comment]
https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key works.  I'll update the docs.

**Comment by dysinger** [comment]
I would change the deb list url to https too except it breaks apt-cacher-ng. The packages are validated by signature before install though.

**Comment by dysinger** [comment]
"http://download.fpcomplete.com/archlinux/stack_0.1.0.0-.tar.gz" could change to "https://s3.amazonaws.com/download.fpcomplete.com/archlinux/stack_0.1.0.0-.tar.gz"  @drwebb on the archlinux site

**Comment by hdgarrood** [comment]
Wonderful - thanks very much! :)

**Comment by wolftune** [comment]
This seems already fixed, should be closed…

**Comment by drwebb** [comment]
Yes, this is fixed in the AUR package.
