### ISSUE TITLE
compiler-check: match-exact does not work

### ISSUE THREAD

**Issue by andrewufrank** [commercialhaskell/stack#4282]
for lts-9.9 (at least) the compiler is 8.0.2 but stack solver uses ghc-8.0.1 (if installed), despite that `config.yaml` is 
`compiler-check: match-exact`
in `~/.stack`. 

the stack.yaml of the project is 
```
flags: {}
extra-package-dbs: []
packages:
- .
- ../uniform/uniform-algebras
- ../uniform/uniform-strings
- ../uniform/uniform-error
# - ../fromOthers/haskell-partial-order_af
extra-deps:
- test-invariant-0.4.5.0
resolver: lts-9.9 # nightly-2018-04-03
```
and the message from the `stack solver` is:
```
frank@oporto:~/Workspace8/testSome$ stack solver 
Using configuration file: stack.yaml
Using cabal packages:
- ./
- /home/frank/Workspace8/uniform/uniform-algebras/
- /home/frank/Workspace8/uniform/uniform-error/
- /home/frank/Workspace8/uniform/uniform-strings/

Using resolver: lts-9.9
Using compiler: ghc-8.0.1
Asking cabal to calculate a build plan...
Trying with packages from lts-9.9 and 1 external packages as ...
```
stack version is:
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0

This is a serious issue, as it violates the concept of stack that a configuration which once builds builds again - if for an `lts` i get sometimes 8.0.1 and sometimes 8.0.2 (on a different computer) then  different versions of packages (e.g. process-1.4.2 or 1.4.3) are used, with the usual consequences that the build fails.

I have the impression that the compiler-check does not work?

As a work-around, I need to know how to uninstall 8.0.1 on this computer, assuming that lts-9.9 would then install 8.0.2.

**Comment by andrewufrank** [comment]
the installation problem was solved by 
- deinstalling 8.0.1 (with synaptic installed as part of debian stretch)
- getting ghc-8.0.2 as a deb package (the version from ghc download does not work if not another ghc is installed) and install the ghc-8.0.2.deb package into the system.
then stack lts-9.9 works with 8.0.2.

Is there a better way? 
I still feel, that 'exact-match` should be the default and select the compiler indicated in the LTS and never deviate.

**Comment by qrilka** [comment]
@andrewufrank "synaptic" and "deb package" in your message above sound like you use system GHC and this is disabled by default - https://docs.haskellstack.org/en/v1.6.5/yaml_configuration/#system-ghc
and I don't see `system-ghc: true` in your `stack.yaml` above. Reproducible scenario would be helpful to find the roots of your problem

**Comment by andrewufrank** [comment]
what would you need? The Haskell program was trivial and did not matter - it is only used to start `stack solver` to see which ghc version is used. I cannot reproduce the problem here anymore, as I have uninstalled ghc-8.0.1 (it was installed with debian, but `system-ghc: true` is definitely not in the config.yaml (which is only the line included above). I have used (as an experiment) NIX on this computer - where could it have changed the stack configuration?

**Comment by andrewufrank** [comment]
i did not use nix in this moment (indeed not on this project at all) 
the config.yaml did only have the single line i showed. i have since added a template for myself
```
templates:
  params:
    author-name: xx    
    author-email: xx
    copyright: xx
    github-username: xx
compiler-check: match-exact
```
is the match-exact in my version of stack? (i have 1.6.5 and i assume this is automatically updated?). the manual says "since 1.4".  
the default is `match-minor` but it would still not permit to match 8.0.1 with 8.0.2. therefore I think the problem has nothing to do with compiler-check, but stack is tacitly using the system installed 8.0.1 for lts-9.9 - which I would consider counteracting the idea of stack.

**Comment by mihaimaruseac** [comment]
I think you'll need to upgrade to the latest released stack (1.7.1). I don't know for sure if that would solve this, but I guess we can try.

**Comment by qrilka** [comment]
@andrewufrank you could try reproduce that using a Docker image if you have time for it

**Comment by andrewufrank** [comment]
I have not used docker so far; i will come to it, when I see a need in one of my projects. Thank you for the hint!

**Comment by snoyberg** [comment]
We've removed the solver support in #4670
