### ISSUE TITLE
add documentation on temporary directory and minimum size for ghc installation

### ISSUE THREAD

**Issue by trihella** [commercialhaskell/stack#429]
By default stack puts all its temporary stuff on /tmp on linux. When this directory has not enough space left (typically less than 1GB), stack setup fails on ghc installation (extraction after download) with a huge output like :

> ...
> /usr/bin/tar: ghc-7.8.4/utils/compare_sizes : mkdir impossible: no space left
> /usr/bin/tar: ghc-7.8.4/utils/compare_sizes/ghc.mk : open impossible: no such file or directory
> /usr/bin/tar: ghc-7.8.4/utils/compare_sizes : mkdir impossible: ...
> ...

It can be reproduced it by creating a fake (a size limited, here roughly 500MB) tmp dir
```bash
$ dd if=/dev/zero of=~/fakefs bs=4096 count=122070 && \
    mkfs.ext4 ~/fakefs && \
    mkdir ~/tmp && mount ~/fakefs ~/tmp
$ TMPDIR=~/tmp stack setup
```

I spent some time to find the issue and had to run through the code to find out how to change the temporary directory. Then, it would be nice to find easily the following information :  
- The default temporary should have at least 1GB free (to contain extracted GHC)
- Temporary directory can be changed by setting the environement variable by priority order ( see [getTemporaryDirectory](http://hackage.haskell.org/package/directory-1.2.0.1/docs/System-Directory.html#v:getTemporaryDirectory) ): 
    - TMPDIR
    - TMP
    - TEMP
    - USERPROFILE

**Comment by snoyberg** [comment]
Since you've already looked into this and found the relevant information (thank you!), would you be able to add this as a FAQ entry? If you think there's a better place for this (perhaps Downloads?), that would be great too.

**Comment by trihella** [comment]
>  would you be able to add this as a FAQ entry ?

Done ! I think a FAQ entry is sufficient.

**Comment by snoyberg** [comment]
Awesome, thanks!
