### ISSUE TITLE
Unable to get haddock version

### ISSUE THREAD

**Issue by pjljvandelaar** [commercialhaskell/stack#4291]
### General summary/comments (optional)
Unable to get haddock version

### Steps to reproduce

When I run (on Windows 7 in PowerShell)
```
stack haddock --haddock-arguments "--version"
```
### Expected

According to the haddock documentation at https://www.haskell.org/haddock/doc/html/invoking.html
this should result in the version and an immediate exit.

### Actual

However, the project is just build and no version information is provided.

### Stack version

I am running stack 1.7.1 which is according to your documentation not the latest.
However
```
PS C:\> stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
PS C:\> stack upgrade
←[0mCurrent Stack version: 1.7.1, available download version: 1.7.1←[0m
←[0mSkipping binary upgrade, you are already running the most recent version←[0m
```

### Method of installation

* Official binary, downloaded from stackage.org

### Why found

issue was found while trying to solve https://github.com/haskell/haddock/issues/929

**Comment by philderbeast** [comment]
We have these options already;

```
> stack --help
...
  --version                Show version
  --numeric-version        Show only version number
  --hpack-numeric-version  Show only hpack's version number
...

> stack --version
Version 1.9.1, Git revision f9d0042c141660e1d38f797e1d426be4a99b2a3c
(6168 commits) x86_64 hpack-0.31.0

> stack --numeric-version
1.9.1

> stack --hpack-numeric-version
0.31.0
```

**Comment by pjljvandelaar** [comment]
Thanks.
I upgraded, and 
`stack exec -- haddock --version` gives indeed what I had expected to get from `stack exec -- haddock "--version"`.

And indeed `stack exec -- which haddock` gave the windows equivalent (although it included also the compiler) 
```
/c/Users/laarpjljvd/AppData/Local/Programs/stack/x86_64-windows/ghc-integersimple-8.2.2/bin/haddock
```

**Comment by dbaynard** [comment]
> although it included also the compiler

Yes — that's correct. I meant to say: within that directory tree, not the specific directory.

I believe the main issue is that stack does not directly invoke haddock in the straightforward way one might expect. The `stack exec -- ` form is a useful workaround to do this.
