### ISSUE TITLE
Bug in module `Pantry.Repo`?

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#4297]
Module `Stack.Upgrade` explains (at around line 203) an upstream bug in `git clone` and the fix in `stack`:
````haskell
let args = [ "clone", repo , "stack", "--depth", "1", "--recursive", "--branch", branch]
withWorkingDir (toFilePath tmp) $ proc "git" args runProcess_
-- On Windows 10, an upstream issue with the `git clone` command
-- means that command clears, but does not then restore, the
-- ENABLE_VIRTUAL_TERMINAL_PROCESSING flag for native terminals.
-- The folowing hack re-enables the lost ANSI-capability.
when osIsWindows $ void $ liftIO defaultColorWhen
````
I think that module `Pantry.Repo` may now expose `stack` to the same upstream `git clone` bug, at around lines 87 to 91 (`commandName` is `"git"`):
```` haskell
    logInfo $ "Cloning " <> display commit <> " from " <> display url
    void $ proc
      commandName
      ("clone" : cloneArgs ++ [T.unpack url, suffix])
      readProcess_
````
I say that: (1) looking at the code above; and (2) because using (on Windows 10) a version of `stack` derived from the current 'master' branch, I experienced 'raw' ANSI codes in the output stream and I think that was just after the `"Cloning ... from"` had been output. It is difficult for me to reproduce the circumstances where that occurred.

On the assumption that the above diagnosis is correct, I will propose a pull request to include the same fix as in module `Stack.Upgrade`.

EDIT: Actually, that is not straightforward, because the fix depends on modules `Stack.Constants.osIsWindows` and `Stack.DefaultColorWhen.defaultColorWhen`. However, the next version of the `ansi-terminal` package, hopefully on Hackage soon, will include ANSI-enabling code that `stack` and `pantry` can rely upon.

**Comment by mihaimaruseac** [comment]
Thanks for finding this. I agree with your analysis and will look forward to the PR.
