### ISSUE TITLE
Fresh install of Stack has garbled ouput in Windows 7 console

### ISSUE THREAD

**Issue by zxbishop** [commercialhaskell/stack#4304]
On Windows 7, I attempted to install Stack first, but the following errors made me believe I'd done something wrong.  I performed what I thought was a full uninstall of Stack, rebooted, and downloaded Haskell Platform.  Stack still shows garbled output, which leads me to believe this might be a problem with the Stack 1.7.1 installer called by GHC.  
--------------------------------------------------------------------------------------------------------------
Sample garbling from the Windows cmd terminal:

`C:\Users\Zack\code>stack build -v --cabal-verbose
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commi
ts) x86_64 hpack-0.28.2
←[90m2018-09-09 11:34:12.172466: ←[32m[debug] ←[0mChecking for project config at
: C:\Users\Zack\code\stack.yaml←[90m
@(src/Stack\Config.hs:850:9)←[0m
←[90m2018-09-09 11:34:12.173466: ←[32m[debug] ←[0mChecking for project config at
: C:\Users\Zack\stack.yaml←[90m
@(src/Stack\Config.hs:850:9)←[0m
←[90m2018-09-09 11:34:12.173466: ←[32m[debug] ←[0mChecking for project config at
: C:\Users\stack.yaml←[90m
@(src/Stack\Config.hs:850:9)←[0m
←[90m2018-09-09 11:34:12.173466: ←[32m[debug] ←[0mChecking for project config at
: C:\stack.yaml←[90m
@(src/Stack\Config.hs:850:9)←[0m
←[90m2018-09-09 11:34:12.173466: ←[32m[debug] ←[0mNo project config file found,
using defaults.←[90m
@(src/Stack\Config.hs:880:13)←[0m
←[90m2018-09-09 11:34:12.175467: ←[32m[debug] ←[0mRun from outside a project, us
ing implicit global project config←[90m
@(src/Stack\Config.hs:570:13)←[0m
←[90m2018-09-09 11:34:12.176467: ←[32m[debug] ←[0mUsing resolver: lts-8.17 from
implicit global project's config file: C:\sr\global-project\stack.yaml←[90m
@(src/Stack\Config.hs:584:32)←[0m
←[90m2018-09-09 11:34:12.176467: ←[32m[debug] ←[0mDecoding build plan from: C:\s
r\build-plan\lts-8.17.yaml←[90m
@(src/Stack\Snapshot.hs:164:5)←[0m
←[90m2018-09-09 11:34:12.177467: ←[32m[debug] ←[0mTrying to decode C:\sr\build-p
lan-cache\lts-8.17.cache←[90m
@(src/Stack\Snapshot.hs:156:32)←[0m
←[90m2018-09-09 11:34:12.179467: ←[32m[debug] ←[0mSuccess decoding C:\sr\build-p
lan-cache\lts-8.17.cache←[90m
@(src/Stack\Snapshot.hs:156:32)←[0m
←[90m2018-09-09 11:34:12.184467: ←[32m[debug] ←[0mPotential GHC builds: standard
←[90m
@(src/Stack\Setup.hs:632:9)←[0m
←[90m2018-09-09 11:34:12.184467: ←[32m[debug] ←[0mFound already installed GHC bu
ilds: standard←[90m
@(src/Stack\Setup.hs:458:13)←[0m
←[90m2018-09-09 11:34:12.186467: ←[32m[debug] ←[0mGetting global package databas
e location←[90m
@(src/Stack\GhcPkg.hs:47:5)←[0m
←[90m2018-09-09 11:34:12.187467: ←[32m[debug] ←[0mGetting Cabal package version←
[90m
@(src/Stack\GhcPkg.hs:180:5)←[0m
←[90m2018-09-09 11:34:12.188467: ←[32m[debug] ←[0mAsking GHC for its version←[90
m
@(src/Stack\Setup\Installed.hs:98:13)←[0m
←[90m2018-09-09 11:34:12.188467: ←[32m[debug] ←[0mRun process: C:\Users\Zack\App
Data\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc-pkg.EXE --no-user-pac
kage-db list --global←[90m
@(src/Stack\GhcPkg.hs:76:10)←[0m
←[90m2018-09-09 11:34:12.190467: ←[32m[debug] ←[0mRun process: C:\Users\Zack\App
Data\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc-pkg.EXE --no-user-pac
kage-db field --simple-output Cabal version←[90m
@(src/Stack\GhcPkg.hs:76:10)←[0m
←[90m2018-09-09 11:34:12.191467: ←[32m[debug] ←[0mRun process: C:\Users\Zack\App
Data\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc.EXE --numeric-version
←[90m
@(src/Stack\Setup\Installed.hs:99:19)←[0m
WARNING: cache is out WoAfR NdIaNtGe::  Cc:a/cUhsee riss/ Zoauctk /oAfp pdDaatte
a:/ LCo:c/aUls/ePrrso/gZraacmks//AsptpaDcakt/ax/8L6o_c6a4l-/wPirnodgor←[90m2018-
09-09 11:34:12.201468: ←[32m[debug] ←[0mProcess finished in ←[92m9ms←[0m: C:\Use
rs\Zack\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc.EXE --nume
ric-version←[90m
w@(src/Stack\Setup\Installed.hs:99:19)←[0m
asm/s←[90m2018-09-09 11:34:12.201468: ←[32m[debug] ←[0mGHC version is: ghc-8.0.2
←[90m
g/@(src/Stack\Setup\Installed.hs:102:13)←[0m
hsct-a8c.k0/.x28\6l_i6b4\-pwiancdkoawgse/.gchocn-f8..d0\.p2a\clkiabg\ep.accakcah
gee
.gchocn fw.idl\lp asceke aagn eo.lcda cvhieew
 gohfc  twhiilsl  psaecek aagne  odlbd.  vUiseew  'ogfh ct-hpiksg  praecckaacghe
e 'db .t oU sfei x'.g
hc-pkg recache' to fix.
←[90m2018-09-09 11:34:12.247471: ←[32m[debug] ←[0mProcess finished in ←[92m57ms←
[0m: C:\Users\Zack\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc
-pkg.EXE --no-user-package-db field --simple-output Cabal version←[90m
@(src/Stack\GhcPkg.hs:76:10)←[0m
←[90m2018-09-09 11:34:12.248471: ←[32m[debug] ←[0mProcess finished in ←[92m59ms←
[0m: C:\Users\Zack\AppData\Local\Programs\stack\x86_64-windows\ghc-8.0.2\bin\ghc
-pkg.EXE --no-user-package-db list --global←[90m
@(src/Stack\GhcPkg.hs:76:10)←[0m
←[90m2018-09-09 11:34:12.248471: ←[32m[debug] ←[0mResolving package entries←[90m

@(src/Stack\Setup.hs:256:5)←[0m
←[90m2018-09-09 11:34:12.249471: ←[32m[debug] ←[0mTrying to decode C:\sr\loaded-
snapshot-cache\x86_64-windows\ghc-8.0.2\lts-8.17.cache←[90m
@(src/Stack\Snapshot.hs:384:9)←[0m
←[90m2018-09-09 11:34:12.285473: ←[32m[debug] ←[0mSuccess decoding C:\sr\loaded-
snapshot-cache\x86_64-windows\ghc-8.0.2\lts-8.17.cache←[90m
@(src/Stack\Snapshot.hs:384:9)←[0m
←[90m2018-09-09 11:34:12.287473: ←[32m[debug] ←[0mStarting to execute command in
side EnvConfig←[90m
@(src/Stack\Runners.hs:171:18)←[0m
←[90m2018-09-09 11:34:12.287473: ←[32m[debug] ←[0mParsing the targets←[90m
@(src/Stack\Build\Target.hs:460:3)←[0m
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?`

----------------------------------------------------------------------------------------------------

I'm very new to both Haskell and its toolchain, but in my limited experience the `←[0m` and `←[32m` look suspiciously like ANSI color codes; the `WARNING: cache is out WoAfR NdIaNtGe::  Cc:a/cUhsee riss/ Zoauctk /oAfp pdDaatte
a:/ LCo:c/aUls/ePrrso/gZraacmks//AsptpaDcakt/ax/8L6o_c6a4l-/wPirnodgor` might be two threads outputting over each other?  I'm at a loss to say what I could have done that would provoke this, or how to fix it. 

I've tried using Haskell before, and I'm unsure if leftover files from a previous install might be to blame.  Is there a walkthrough of steps to ensure all previous traces of Haskell/Stack/GHC/Cabal/<whatever else> are truly and fully uninstalled?  (On that note, is there a single, canonical installation walkthrough for the brand new user of limited technical acumen?  I've found numerous guides that all seem to be a year or two old, but not only do they differ with each other on precisely what I'm supposed to do and in what order, but a lot of them also seem to assume that a brand new user is on a Linux box and has significant knowledge of that ecosystem.)

**Comment by mpilgrem** [comment]
If using stack v1.7.1 on Windows 7, you need to specify `stack --color=never` when you use its commands. Stack is sending codes to output for colour that the console on Windows 7 (Command Prompt or PowerShell) cannot interpret.

**Comment by dbaynard** [comment]
@zxbishop I'm going to close this — the release candidate will be announced in the next few days and installing that should solve this problem (#4106 is tracking part of that). Do reopen if after that you still have issues.

> I've tried using Haskell before, and I'm unsure if leftover files from a previous install might be to blame. Is there a walkthrough of steps to ensure all previous traces of Haskell/Stack/GHC/Cabal/ are truly and fully uninstalled?

For stack, you'll want to remove your config and cache folder, somewhere in `%APPDATA%` I believe (according to #2959).

> On that note, is there a single, canonical installation walkthrough for the brand new user of limited technical acumen?

I can't contribute here; you may find better luck on the fpchat slack or on IRC.

---

Best of luck with the work!
