### ISSUE TITLE
Save the unnecessary rebuild of libraries with profiling

### ISSUE THREAD

**Issue by konn** [commercialhaskell/stack#4308]
Suppose we had configured with `library-profiling: true` and `executable-profiling: false`, and had built executables without `--executable-profiling` option.

Then, if we wanted to take an executable profiling and passed `--executable-profiling` option to `stack`, then it unregisters all the library consisting stack-project (not all the dependencies) and rebuild them from scratch, due to the change of compiler flags.

I think this behaviour is not optimal; we have built libraries with profiling features (and have `p_o` files already) and only we had to rebuild is executables.

For example, suppose we have the following `stack.yaml`:
```stack.yaml
packages:
- core-libs-and-exe   # package with library and executables
- util-lib -and-exe   # another one
- super-lib-and-exe   # yet another

extra-deps:
- extra-dependent-package-0.1.0.0

build:
  library-profiling: true
  executable-profiling: false
```

If we have once successfully executed `stack build`, `p_o` objects are built.
But if we enter `stack build --executable-profiling` again, Stack will rebuild all libraries and executables of `core-libs-and-exe`, `util-lib -and-exe` and `super-lib-and-exe`, although `extra-dependent-package` will not be rebuilt since they have profiling object files.

My propose is just to avoid rebuild libraries if the library profiling had been already enabled but executable was not.

**Comment by mattaudesse** [comment]
Thanks @konn. Is this something you'd like to submit a PR for?

**Comment by mattaudesse** [comment]
You're welcome! And there's no need to worry about timing (have a great vacation BTW) - I think the profiling UX has been an ongoing focus of discussion for awhile now.

I should add that we've already got quite a few (possibly-)related issues in the tracker:
#2684
#2285
#3798
#2984
[This diff](https://github.com/commercialhaskell/stack/pull/3046/files)
[and many more](https://github.com/commercialhaskell/stack/search?p=1&q=profiling&type=Issues)

I'm not sure if it's relevant to your workflow at all, but this thread describes a trick for people who frequently go back and forth between profiled and non-profiled builds:
 #4032

**Comment by konn** [comment]
Thank you for the pointers! A trick to separate workdir seems working for my case, since vast majority of deps are already on Stackage LTS. I think I can use this  as a tentative workaround until some official support will be implemented. Thanks!

**Comment by dbaynard** [comment]
@mattaudesse It would be good to close all those issues except one — would you like to take the lead?

**Comment by qrilka** [comment]
The problem of rebuilds will be resolved by #3922 and my manual tests of #4412 approve that

**Comment by mattaudesse** [comment]
@dbaynard sure, I can take a look but it'll probably be a few days before I'm able to focus any real attention on it - the Thanksgiving holiday here in the states is always a wacky time of year.

**Comment by qrilka** [comment]
Actually the mentioned #4412 didn't resolve the problem of rebuilds completely but in #4582 I add tests in 58c2cd71dc5814ec9ed941f629b3b5c8ee4695aa and 4b316b82550bf055a434e435969fe17e85f315ab specifically testing rebuilds with profiling

**Comment by mattaudesse** [comment]
In the interest of paring down the backlog I'm going to go ahead and close this issue - if you've arrived here from a search please refer to/continue the discussion at #4032.

Thanks again for the suggestion @konn!
