### ISSUE TITLE
stack dot seems broken

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stack#431]
##### stack dot seems broken

I'm on 
```
stack --version
Version 0.1.1.0, Git revision 2cac22d2a26dab6faa00c6f03edf5798affb7840
```

In stack code directory, I did:

```
$ stack dot > test.dot
$ dot -Tpng < test.dot > graph.png
Fontconfig warning: ignoring UTF-8: not a valid region tag
```

here is the result
![graph](https://cloud.githubusercontent.com/assets/2150990/8389055/e0584320-1c6a-11e5-9353-341ef5fddbe3.png)

but I don't see dependencies.

Here is the exact output given by stack dot
```
$ stack dot
digraph deps {
splines=polyline;
{rank=max; "stack"}
}
```

here is the help for stack dot:
```
stack dot --help
Usage: stack dot
  Visualize your project's dependency graph using Graphviz dot
```

**Comment by zudov** [comment]
It visualizes dependencies of projects with multiple packages. Try to run it on yesod repo, or something else that has multiple packages.

**Comment by markus1189** [comment]
Oh if that is the intendend use case I guess I can delete my branch :)

I also thought like @rvion from the help text that it should display the external dependencies

**Comment by zudov** [comment]
@markus1189 I think it would be great if there was an option to build a graph of external dependencies. Something like `stack dot --external`.

Actually when I first saw help text I also thought that it would give me a graph of external dependencies. Perhaps, if would worth to add notice to the help text, or make the `--external` behaviour default and add an `--internal` flag.

**Comment by rvion** [comment]
@markus1189 Thanks :)

As a side note, I think external being the default would be a bit better, but no strong opinion.

**Comment by snoyberg** [comment]
Let's track the rest of this in the PR to avoid splitting the discussion.
