### ISSUE TITLE
`--system-ghc` also searches for `ghc-x.y.z`

### ISSUE THREAD

**Issue by zilinc** [commercialhaskell/stack#4310]
Currently as https://github.com/commercialhaskell/stack/blob/master/src/Stack/Setup.hs#L760, it seems that stack only searches for `ghc` command to decide if a stack-local ghc needs to be installed. But if multiple system GHCs are installed, only one version can be referred to as `ghc`, and others will be `ghc-8.4.3`, `ghc-8.2.2` etc. Stack should also search for those.

**Comment by dbaynard** [comment]
Hello @zilinc,

These are not supported. I've seen some suggestions to do this before but we can't seem to find them. Would you be willing to make a PR?

**Comment by zilinc** [comment]
Yeah, I'm happy to make a PR. It should be pretty straightforward to implement.

**Comment by snoyberg** [comment]
Implemented in #4668
