### ISSUE TITLE
Connection timed out at `https://s3.amazonaws.com/hackage.fpcomplete.com/`

### ISSUE THREAD

**Issue by rsy56640** [commercialhaskell/stack#4311]
I try to install hindent via `stack install hindent` and `stack install --resolver=nightly hindent stylish-haskell`, but both cause the ` (InternalException (HostCannotConnect "s3.amazonaws.com" [Network.Socket.connect: <socket: 856>: failed (Connection timed out (WSAETIMEDOUT))])))`   

Detail:   
```
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...
SomeRemoteError (HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("Cache-Control","no-transform"),("User-Agent","The Haskell Stack")]
  path                 = "/hackage.fpcomplete.com/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HostCannotConnect "s3.amazonaws.com" [Network.Socket.connect: <socket: 856>: failed (Connection timed out (WSAETIMEDOUT))])))
```
It seems that the mirror at https://s3.amazonaws.com/hackage.fpcomplete.com/ is deprecated. Is there any alternative?

**Comment by dbaynard** [comment]
Hello! It isn't deprecated, but there are occasional connection issues. Which version are you using? The new release candidate (due out in the next few days, if everything goes to plan) includes a partial fix for this (#3510, #4109).

**Comment by rsy56640** [comment]
```
stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```
I look up issuse [#3088](https://github.com/commercialhaskell/stack/issues/3088) and find the solution,  but now I cannot even find my `/.stack/config.yaml`.   
In the folder `/bin` there are only `stack.exe` and `uninstall-stack.exe`.   
I use `stack-1.7.1-windows-x86_64-installer.exe` to install.

**Comment by dbaynard** [comment]
Try `%APPDATA%\stack\config.yaml` (via #2959)

**Comment by dbaynard** [comment]
OK, reopen if you come back to it. As I say, the new version of stack should be better, here.
