### ISSUE TITLE
stack install cannot locate library at unconventional location. 

### ISSUE THREAD

**Issue by shengc** [commercialhaskell/stack#4313]
Please follow the steps below for reporting a bug:

Make sure that you are using the latest release (currently stack-1.9.1).
See the [upgrade instructions](http://docs.haskellstack.org/en/stable/install_and_upgrade/#upgrade) to upgrade.

```bash
shengc@ work $ stack upgrade
Current Stack version: 1.7.1, available download version: 1.7.1
Skipping binary upgrade, you are already running the most recent version
```

Please use the following schema for your bug report:

### General summary/comments (optional)
I am trying to install JuicyPixels-3.2.9.5 using `stack install`, the process failed with `can't load .so/.DLL for: libgmp.so`. The nature of my working environment requires me to install linux libraries at unconventional location with `linuxbrew`. I did included both library path and include path where `libgmp.so` exists using `--extra-lib-dirs` and `--extra-include-dirs`, the error persisted anyway. 

### Steps to reproduce
```bash
PATH=~/.linuxbrew/bin:$PATH stack install JuicyPixels-3.2.9.5 --with-gcc ~/.linuxbrew/bin/gcc --extra-lib-dirs=~/.linuxbrew/lib --extra-include-dirs=~/.linuxbrew/include
```
```bash
shengc@ work $ ls ~/.linuxbrew/lib | grep libgmp
libgmp.a
libgmp.so
libgmp.so.10
libgmp.so.10.3.2
libgmpxx.a
libgmpxx.so
libgmpxx.so.4
libgmpxx.so.4.5.2
```

### Output:
```bash
JuicyPixels-3.2.9.5: configure
JuicyPixels-3.2.9.5: build

--  While building custom Setup.hs for package JuicyPixels-3.2.9.5 using:
      /home/shengc/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/shengc/workspace/work/.stack-work/logs/JuicyPixels-3.2.9.5.log

    Configuring JuicyPixels-3.2.9.5...
    Preprocessing library for JuicyPixels-3.2.9.5..
    Building library for JuicyPixels-3.2.9.5..
    [ 1 of 30] Compiling Codec.Picture.InternalHelper ( src/Codec/Picture/InternalHelper.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/Codec/Picture/InternalHelper.o )
    [ 2 of 30] Compiling Codec.Picture.Metadata.Exif ( src/Codec/Picture/Metadata/Exif.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/Codec/Picture/Metadata/Exif.o )
    [ 3 of 30] Compiling Codec.Picture.Metadata ( src/Codec/Picture/Metadata.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/Codec/Picture/Metadata.o )
    [ 4 of 30] Compiling Codec.Picture.Tiff.Types ( src/Codec/Picture/Tiff/Types.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/Codec/Picture/Tiff/Types.o )
    [ 5 of 30] Compiling Codec.Picture.Tiff.Metadata ( src/Codec/Picture/Tiff/Metadata.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/Codec/Picture/Tiff/Metadata.o )
    [ 6 of 30] Compiling Codec.Picture.Types ( src/Codec/Picture/Types.hs, .stack-work/dist/x86_64-linux/Cabal-2.0.1.0/build/Codec/Picture/Types.o )
    <command line>: can't load .so/.DLL for: libgmp.so (libgmp.so: cannot open shared object file: No such file or directory)
```

### Stack version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2

**Comment by dbaynard** [comment]
Hi @shengc,

Would you please paste your stack.yaml file and the output of the same command you ran but with the `-v` flag?

**Comment by shengc** [comment]
@dbaynard 
Thanks a lot for your response. I was trying to build this project: https://github.com/bravit/hid-examples

It is obvious that stack insisted looking for the that lib in `/lib64`, and given the fact there is `libgmp.so.10` but _not_ `libgmp.so` in the same directory, it crapped out. Problem is I don't have the root privilege, otherwise I could just create a symlink there. My question is, since I do have a local installation of `libgmp.so` at `$HOME/.linuxbrew/lib`, is it possible to let stack pick up that dependency directly from there ?

**Comment by dbaynard** [comment]
It should be. It would be really helpful to see the logs from the attempted installation.

**Comment by snoyberg** [comment]
This should be addressed by https://github.com/commercialhaskell/stack/pull/4651. Closing as fixed, if there is still a problem, please comment.
