### ISSUE TITLE
Test suite in multi-package project fails to compile (`stack ghci --test` compiles well)

### ISSUE THREAD

**Issue by Unisay** [commercialhaskell/stack#4321]
### General summary/comments (optional)
In my open-source project I wanted to extract `Hedgehog.Gen` functions into a separate package
in order to use them as a dependency in the current project's test suite as well as in other project tests.
https://github.com/DSTOQ/haskell-stellar-core/tree/extract-generators-package

Unfortunately test compilation fails with the following error:
```   
/tmp/haskell-stellar-core/core/test/Stellar/CryptoSpec.hs:33:37: error:
       • Couldn't match expected type ‘Network’
                      with actual type ‘stellar-core-0.1.0.0:Stellar.Types.Network’
          NB: ‘stellar-core-0.1.0.0:Stellar.Types.Network’
                is defined in ‘Stellar.Types’ in package ‘stellar-core-0.1.0.0’
              ‘Network’
                is defined in ‘Stellar.Types’ in package ‘stellar-core-0.1.0.0’
        • In the first argument of ‘signTransactionEnvelope’, namely
            ‘network’
          In the expression: signTransactionEnvelope network keys tx
          In an equation for ‘tx'’:
              tx' = signTransactionEnvelope network keys tx
```
+ similar errors for types in `Stellar.Types` module

### Steps to reproduce

For example:
```bash
$ git clone --single-branch -b  extract-generators-package git@github.com:DSTOQ/haskell-stellar-core.git
$ cd haskell-stellar-core/
$ stack test 
```

but in ghci same spec runs well

```
$ stack ghci --test
> CryptoSpec.run
━━━ Stellar.CryptoSpec ━━━
  ✓ Sign 'hello world' passed 1 test.
  ✓ Sign transaction passed 1 test.
  ✓ Sign transaction envelope passed 100 tests.
  ✓ 3 succeeded.
```
### Expected

No compilation error, green tests

### Actual

Compillation error above

### Stack version

```
$ stack --version
Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
```

### Method of installation

Manjaro linux repository, package 'stack'
Same problem if stack is installed via 'curl | sh'

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and its nature (very specific).
