### ISSUE TITLE
stack github issue template shows wrong stack version

### ISSUE THREAD

**Issue by turion** [commercialhaskell/stack#4323]
Have a look:

> Make sure that you are using the latest release (currently stack-1.__9__.1).

The only versions that would make sense are 1.7.1 (what is installed by default currently) or 1.9.0.1.

**Comment by mihaimaruseac** [comment]
Duplicating comment from duplicating issue:


Stack 1.9.1 is in release candidate phase at the moment. If you want it, you should stack upgrade --git or download it from the releases page. The release is now at 1.9.0.1 as it is only a candidate but when it will be fully released it will be named 1.9.1.

**Comment by turion** [comment]
Still the bug template should say "1.7.1", right? Most people will find and file a bug with that version.

**Comment by mihaimaruseac** [comment]
Most likely. We were planning to get the release candidate fast but it got delayed.
