### ISSUE TITLE
Stack dot should handle properly GHC boot packages

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/stack#4324]
### General summary/comments (optional)

It looks like currently `stack dot` doesn't show dependencies of GHC boot libraries even when such a library comes from a Stackage LTS snapshot. Either the code should be improved by including those dependencies or it should be documented that `stack` doesn't track dependencies of GHC boot packages.

### Steps to reproduce

In the root of the stack repository run `stack dot --external | grep '"process"'`

### Expected

Dependencies of the `process` package will get shown (e.g. `directory` or `filepath`) besides the packages which depend on `process`.

### Actual

Current output (both for versions 1.7.1 and prerelese 1.9.0.1):
```
{rank=max; "process"; };
"Cabal" -> "process";
"cmdargs" -> "process";
"conduit-extra" -> "process";
"echo" -> "process";
"extra" -> "process";
"githash" -> "process";
"gitrev" -> "process";
"open-browser" -> "process";
"optparse-applicative" -> "process";
"rio" -> "process";
"stack" -> "process";
"streaming-commons" -> "process";
"typed-process" -> "process";
"unliftio" -> "process";
"x509-system" -> "process";
```

### Stack version

```
$ stack --numeric-version
1.7.1
$ ~/bin/stack-1.9.0.1 --numeric-version
1.9.0.1
```

### Method of installation

* Other : 1.7.1 install with `gentoo-haskell`, prerelease version downloaded from the Github release page

**Comment by dbaynard** [comment]
I thought `--include-base` might help but it doesn't.

This isn't totally obvious to me — why is it valuable to display boot libraries?

We may want to add an option `--include-boot`, or modify `--include-base`, or make it default, depending on the answer.

**Comment by qrilka** [comment]
Omitting some dependencies results in an incomplete dependency graph, I think Stack should be explicit about this. And actually we could add this information e.g. by using `ghc-pkg describe <pkg>`

**Comment by vanceism7** [comment]
Hey guys, I've been looking at this issue and I think I was able to get those dependencies to load up in the dot graph. I'll post up a PR soon

**Comment by qrilka** [comment]
@vanceism7 the current version of that code is more or less my refactoring of the previous version to use new source maps. As far as I understand it you're correct, probably you've noticed that for `wiredInPackages` we do consult `globalDumpMap` to get package information. Now we have global packages in `smGlobal` field of a `SourceMap` so we could just do that for any of those packages.

**Comment by vanceism7** [comment]
Oh gotcha ok cool, I'll work on the PR for this then

**Comment by snoyberg** [comment]
@qrilka what project did you generate those graphs from?

**Comment by qrilka** [comment]
@snoyberg I just run `stack new testproject` and added some boot packages into `dependencies` of `package.yaml`, namely:
```
dependencies:
- base >= 4.7 && < 5
- ghc
- xhtml
- haskeline
- Cabal
- mtl
- ghc-heap
```
then it's just `stack dot` + `dot`

**Comment by qrilka** [comment]
It's unclear how could that happen but I can't reproduce those incomplete graphs anymore.
