### ISSUE TITLE
Override non-Haskell dependencies with Nix enabled

### ISSUE THREAD

**Issue by rikvdkleij** [commercialhaskell/stack#4329]
I noticed that running Stack commands with Nix enabled are very slow because for every command shell-nix is started in the background (there are a large number of non-Haskell dependencies defined). But all those commands do not need the non-Haskell dependencies. So I added the option `--nix-packages=[]` but that gives the message `You cannot have packages and a shell-file filled at the same time in your nix-shell configuration` 

My feature request is to make it possible to override the Nix non-Haskell packages from the Nix shell file.

Some example Stack commands are: 
`stack exec -- ghc-pkg dump`
`stack ls dependencies [target name]`

The context is the IntelliJ-Haskell plugin. The plugin has to call a number of time Stack commands to get all Haskell packages information about the project.

**Comment by dbaynard** [comment]
Related: #4406 

I'm going to close in favour of that.
