### ISSUE TITLE
64 bit Windows binary

### ISSUE THREAD

**Issue by hamishmack** [commercialhaskell/stack#433]
In Wine you can't easily mix 32bit and 64bit processes, so it would be really handy to have a 64bit Windows binary for use on 64bit Wine.

**Comment by snoyberg** [comment]
I've avoided making this because of confusing Windows users, but there seem to be many requests coming in for this. Let's consider it for the next release.

**Comment by snoyberg** [comment]
Passing to @manny-fp who will be doing the releases this time around

**Comment by snoyberg** [comment]
This has been released.
