### ISSUE TITLE
Different results of stack build on travis-ci and appveyor 

### ISSUE THREAD

**Issue by hanjoosten** [commercialhaskell/stack#4334]
[My project](https://github.com/AmpersandTarski/Ampersand) has a transitive dependency on hspec-discover. It [builds fine with stack on travis-ci](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/434945141). However, the [build with appveyor fails](https://ci.appveyor.com/project/hanjoosten/ampersand/build/build.1645-development).

On appveyor, it fails with a "ignoring (possibly broken) abi-depends field for packages" warning. This might be somehow related with haskell/cabal#5465 . Both build with ghc 8.4. Stack uses linux, appveyor uses windows. 

How can it be that one build goes well, and the other one fails?? And even more important, how can I get appveyor to succeed building the project?

### Stack version

- On travis, always buids with latest stack. [Here is the .travis.yml](https://github.com/AmpersandTarski/Ampersand/blob/9fecd2409b31a17a236141497a47d71201e1e886/.travis.yml) 
- On appveyor, also builds with latest stack. [Here is the .appveyor.yml](https://github.com/AmpersandTarski/Ampersand/blob/92d2f2bab4821d7542aa929e93888d2f19489e6b/appveyor.yml)

### Method of installation

appveyor and travis-ci

**Comment by mihaimaruseac** [comment]
Seems to be a windows issue

**Comment by hanjoosten** [comment]
On my own laptop (Windows 10), if I build the project with `stack install`, the build is succesful. There same "ignoring (possibly broken) abi-depends field for packages" warning is produced, but that doesn't stop the build.

**Comment by hanjoosten** [comment]
This is since we've upgraded to ghc 8.4. With ghc 8.2.2 there was no problem. This is becoming pretty nasty. Is there anything I could do to investigate what is going on?

**Comment by mihaimaruseac** [comment]
Sorry for the delay in answering. I guess you could try changing the compiler but keeping the same stack version and snapshot and see if that causes the bug to go away.

Basically, we need to isolate if the error comes from GHC, stack snapshot or stack binary

**Comment by hanjoosten** [comment]
For as far as I can see, this is related with the bug discussed in https://ghc.haskell.org/trac/ghc/ticket/14381. It says that it should be solved with ghc 8.6.1. Unfortunatly, I have too many dependencys that currentyly don't complile with 8.6 yet.

**Comment by mihaimaruseac** [comment]
So it's a GHC bug, not a Stack one. Closing the issue, thanks for confirming.
