### ISSUE TITLE
Give a warning when implicitly added packages from targets fail to build

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4336]
For better or worse, as a user convenience, Stack will implicitly add packages to its source map when they are specified as targets on the command line. This allows, for example, the following to work:

```
stack --resolver lts-12.10 build acme-missiles
```

Even though `acme-missiles` isn't in the LTS snapshot referenced, Stack will:

* Find the most recent version available in the Hackage package index
* Add it to the build plan, with no reason to believe it will build

This leads to user confusion in many cases when builds fail. Instead, I believe we should:

* (Maybe) warn users when we implicitly add these packages, saying it may not work
* When a build actually fails, print out a message explaining that this is the likely cause, and maybe link to this issue or some other explanation of the problem

**Comment by qrilka** [comment]
@snoyberg here is some example output I currently have:
```
qrilka@qdesktop ~/ws/h/stack $ stack exec -- stack build shelly-1.6.8.5 unix-compat-0.4.3.1
The following packages was added implicitly from the command line as its latest revision available on Hackage:
  shelly, unix-compat
This may result in a build failure.
shelly-1.6.8.5: configure
shelly-1.6.8.5: build

--  While building package shelly-1.6.8.5 using:
      /home/qrilka/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    The following packages were added implicitly as targets from the command line which could be a cause of this failure:
      shelly, unix-compat
    See: https://github.com/commercialhaskell/stack/issues/4336 for details.
    Logs have been written to: /home/qrilka/ws/h/stack/.stack-work/logs/shelly-1.6.8.5.log

    Configuring shelly-1.6.8.5...
    Preprocessing executable 'drain' for shelly-1.6.8.5..
    Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: can't find source for drain in 
```
Please let me know if it looks OK or if something needs to be changed

**Comment by snoyberg** [comment]
How about some wording tweaks:

```
NOTE: The following packages were added implicitly from the command line.
Since they are not part of a tested snapshot, they may not compile correctly.
If a build failure occurs, please see https://... for information on workarounds
```

And then we can put together a short FAQ explaining the problem in more detail.

**Comment by qrilka** [comment]
Sure, that sounds good for the 1st warning, will it be OK to use the same words (changing the part after "If") when showing details of a build failure?

**Comment by snoyberg** [comment]
Yes, perfect

**Comment by qrilka** [comment]
Pushed branch `implicit-target-fail-message`, waiting #4412 to get merged

**Comment by snoyberg** [comment]
#4412 was merged.
