### ISSUE TITLE
Direct download URL for stack executable

### ISSUE THREAD

**Issue by lassik** [commercialhaskell/stack#4337]
The current [instructions for installing Stack on Travis CI](https://docs.haskellstack.org/en/stable/travis_ci/) are based around this command:

`travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'`

That's quite a complex one. Also, the MacOS `tar` command doesn't have the `--wildcards` option, so it's difficult to write a command line that works identically on MacOS and Linux CI jobs.

Our current workaround is this:

```
mkdir -p $HOME/tmp
travis_retry curl -L https://get.haskellstack.org/stable/${TRAVIS_OS_NAME}-x86_64.tar.gz \
    | tar -xz --strip-components=1 -C $HOME/tmp
mv $HOME/tmp/stack $HOME/.local/bin/
```

It would be simpler to just do this:

`travis_retry curl -L https://get.haskellstack.org/stable/stack-${TRAVIS_OS_NAME}-x86_64 > $HOME/.local/bin/stack`

Some other services such as Code Climate provide direct downloads of executables for CI like that.

I see that `get.haskellstack.org` links redirect to https://github.com/commercialhaskell/stack/releases/ which sports quite a long list of files per release, so I understand if you are reluctant to go to the trouble of serving extra files. However, if it fits in your workflow, the easier download URLs would be really helpful for CI jobs. I imagine everyone using services like Travis or Circle CI would prefer them. As for platforms, for CI use it may be enough to cover Linux and MacOS on x86_64.

**Comment by snoyberg** [comment]
We used to provide single-executable bundles and were requested to move in this direction instead. Doubling the number of downloads available isn't going to happen, closing as wontfix.

Note that in practice such a change wouldn't save as many characters as you think; you'd still need to set the file executable with chmod afterward.
