### ISSUE TITLE
network unknown symbol `acceptNewSock' when building with stack 1.9.01rc on appveyor

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#4346]
On appveyor I'm seeing this while using the stack-1.9.0.1-windows-x86_64.tar.gz release candidate from https://github.com/commercialhaskell/stack/releases:
```
stack build --test --copy-bins --local-bin-path=. hledger hledger-web network-2.7.0.2
...
    [11 of 31] Compiling Yesod.Core.Handler ( Yesod\Core\Handler.hs, .stack-work\dist\7d103d30\build\Yesod\Core\Handler.o )
    ghc.EXE: unable to load package `network-2.7.0.2'
    ghc.EXE:  | C:\pr\.stack-work\install\c5eb1f13\lib\x86_64-windows-ghc-8.4.3\network-2.7.0.2-HRKpEmrZF0Z7oBCs9x5PCR\HSnetwork-2.7.0.2-HRKpEmrZF0Z7oBCs9x5PCR.o: unknown symbol `acceptNewSock'
```
I found a little discussion from a few years back, eg https://stackoverflow.com/questions/51347227 which doesn't seem like something I should be doing. Is it possible this is a stack bug ?

**Comment by arrowd** [comment]
Got the same problem with Stack 1.7.1 and `lts-12.13`.

**Comment by snoyberg** [comment]
There have been a number of bugs with compiling recent network releases on Windows, e.g. https://github.com/haskell/network/issues/390. Closing as upstream.
