### ISSUE TITLE
stack upgrade --source-only fails with GHEGitRunFailed

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/stack#4363]
### Steps to reproduce

```
stack upgrade --source-only
```

### Expected

downloads, compiles, installs `stack-1.9.1`

### Actual

```
/tmp/stack-upgrade23108/stack-1.9.1/src/main/Main.hs:136:33: error:
    • Exception when trying to run compile-time code:
        GHEGitRunFailed "." ["rev-parse","--show-toplevel"] (ExitFailure 128) "" "fatal: Not a git repository (or any of the parent directories): .git\n"
      Code: tGitInfoCwd      
    • In the Template Haskell splice $$tGitInfoCwd
      In the first argument of ‘giCommitCount’, namely ‘$$tGitInfoCwd’
      In the expression: giCommitCount $$tGitInfoCwd
    |                        
136 |     commitCount = giCommitCount $$tGitInfoCwd
    |                                 ^^^^^^^^^^^^^
         
```

### Stack version

```
stack --version
Version 1.7.1 x86_64 hpack-0.28.2
```

### Method of installation

built from source

**Comment by jwaldmann** [comment]
Same error with `cabal install stack`

**Comment by dbaynard** [comment]
Have you tried a binary upgrade, i.e. without the `--source-only`?

Alternatively, you could pass the `disable-git-info` flag.

What platform are you using?

**Comment by jwaldmann** [comment]
* binary upgrade: no I haven't, since I am reporting a bug with `--source-only`
* `--disable-git-info`: does not exist for stack-1.7.1
* platform/verbose: not me, but cf. https://hackage.haskell.org/package/stack-1.9.1/reports/3

**Comment by dbaynard** [comment]
Ah, great, that's all helpful information. It wasn't clear that the `source-only` rather than the `upgrade` was the bug.

On the flags: it's a Cabal flag, not a stack command line flag.

I'll get another set of eyes on this one.

**Comment by borsboom** [comment]
Probably same as #4364.  See my [comment](https://github.com/commercialhaskell/stack/issues/4364#issuecomment-431520257) there.

**Comment by dbaynard** [comment]
There's a fix in progress — it's being discussed at #4364, though, so I'm marking this the duplicate (even though it was first).

However, @jwaldmann I don't think it's possible to pass the cabal flags to the `upgrade` command. I'm not sure it's desirable, actually. It may be with .environment files, though I suspect that would just make things worse.

**Comment by jwaldmann** [comment]
Thanks. I see. Meanwhile, I use the work-around of `cabal install stack -f disable-git-info`.

**Comment by dbaynard** [comment]
Great! On the same theme, you could probably bootstrap `stack install stack --flag stack:disable-git-info`, too.

**Comment by snoyberg** [comment]
The fix has been merged to master, closing.
