### ISSUE TITLE
Support GHC 8.4 in addDependentFile for 1.9.3

### ISSUE THREAD

**Issue by ygale** [commercialhaskell/stack#4369]
The fix for yesodweb/yesod#1551 in commercialhaskell/stack@aae15e3 did not make it into stack 1.9.1. From what I see in stable, it's currently not even scheduled to make it into stack 1.9.3.

This GHC 8.4 incompatibility is a show-stopper for our front-end team. All our front-end devs are forced to use stack built from git master in a stable production environment, which is not healthy.

Is there a possibility of including this small but critical patch in stack 1.9.3? Thanks!

cc: @bermanjosh

**Comment by ygale** [comment]
Update: Instead of using master, we now forked stack and manually applied @snoyberg 's 3-line fix to the v1.9.1 tag,

But still, the importance to effort ratio seems really high here. It would still be nice if this could make it into 1.9.3.

**Comment by borsboom** [comment]
@snoyberg Any objection to cherry-picking this fix into the `stable` branch so it gets into the next minor release?

**Comment by snoyberg** [comment]
No objection.

**Comment by ygale** [comment]
Hmm. Unfortunately, it appears that this fix does not actually resolve yesodweb/yesod#1551.

**Comment by ygale** [comment]
It actually does resolve it. @tolysz pointed out that you also need shakespeare >= 2.0.19.

Thanks for doing this!

**Comment by ygale** [comment]
Verified that this is working in the now-released stack 1.9.3. Thanks stack team!
