### ISSUE TITLE
"Ignoring out of range dependency (allow-newer enabled)" warning is unclear

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#4375]
Eg: I'm using nightly-2018-10-24, which contains megaparsec 6.x. I have `allow-newer: true` and an  `cassava-megaparsec-2.0.0` in extra-deps. I believe this causes stack to use megaparsec 7. stack 1.9.1 gives this warning when doing a build:

> WARNING: Ignoring out of range dependency (allow-newer enabled): megaparsec-6.5.0. cassava-megaparsec requires: >=7.0 && <8.0

which I feel is unclear. How about something like:

> WARNING: Using newer dependency (allow-newer enabled): megaparsec-7.0.2 (instead of 6.5.0) since cassava-megaparsec requires: >=7.0 && <8.0

**Comment by simonmichael** [comment]
Or:
> WARNING: Using newer dependency megaparsec-7.0.2 (instead of 6.5.0) since cassava-megaparsec requires: >=7.0 && <8.0 and allow-newer is true

**Comment by dbaynard** [comment]
Hi @simonmichael 

It's actually the other way round — stack is ignoring the lower bound and using the snapshot package (6.5.0). Stack will never use a dependency that is present in neither the snapshot nor extra-deps.

Of course, this means that the warning is indeed unclear — certainly the name is unclear.

From docs:

> ## allow-newer
> (Since 0.1.7)
>
> Ignore version bounds in .cabal files. Default is false.
>
>     allow-newer: true
> Note that this also ignores lower bounds. The name "allow-newer" is chosen to match the commonly used cabal option.

What would you suggest?

**Comment by snoyberg** [comment]
I like that wording. See #4683
