### ISSUE TITLE
Git dependency with `package.yaml` without `foobar.cabal` in `stack.yaml` after pantry.

### ISSUE THREAD

**Issue by NorfairKing** [commercialhaskell/stack#4377]
In the latest commit of stack, it is indeed not possible to have a git repo -based dependency that only has a package.yaml and no cabal file.

Example Scenario:
Repo A with A_stack.yaml has an extra-deps: Repo B.
Repo B has package.yaml but no foobar.cabal
Recent stack will now not be able to build foobar.

CC-ing @snoyberg because he has the paged-in info on why this is the case.
If I remember correctly:

* We should not rely on `hpack` producing reproducible cabal files.
* We do not want the pantry hash to ever depend on generated contents of a cabal file because of the above.

Current suggested approach:

- When a `package.yaml` file is found, run `hpack` on it an cache the result, keyed on the version of `hpack` that is used.
- The cached value would be used so that, when Stack needs to ask for the cabal file contents for a package, it doesn't require dumping all of the files to the filesystem and running hpack on them.

This way we assume that a given `hpack` version produces always produces the same cabal file, but we don't assume the same accross `hpack` versions.

**Comment by snoyberg** [comment]
CC @sol

**Comment by snoyberg** [comment]
Fixed by #4439
