### ISSUE TITLE
Set working directory flag

### ISSUE THREAD

**Issue by vanceism7** [commercialhaskell/stack#4378]
This is more of a convenience feature, but it would be nice if we could make a flag that could set which directory to work out of. I.e: to scan for stack.yaml without actually having to specify the stack.yaml file. E.g: If I'm in the directory `./haskell` and I want to build the package in `./haskell/project`, it would be nice to be able to do `stack build --from ./project` and stack would work as if it was in that directory.  

I know that might sound a little lazy since it only takes another second to type out `stack.yaml`, but conceptually its much easier to think about. It wasn't readily apparent to me that I could work out of a specific directory by specifying the stack.yaml file of that directory.  

I dont know what the flag could be named, I've thought of `--from`, `--use-dir`, or maybe even `--cd`. I'd be open to implementing this feature if this sounds good to you guys

**Comment by snoyberg** [comment]
This can be handled at the shell level with `(cd project && stack build)`. I'm -1 on adding a separate flag to Stack for this, closing as wontfix.
