### ISSUE TITLE
Is it still recommended to post to StackOverflow?

### ISSUE THREAD

**Issue by dspies-leapyear** [commercialhaskell/stack#4379]
The instructions here were to post usage questions not covered in the docs to StackOverflow with the `haskell-stack` tag, but I posted two questions and neither one got a response:

https://stackoverflow.com/q/52895758/403875 and https://stackoverflow.com/q/52893750/403875

Is that no longer the way to submit questions?

**Comment by dbaynard** [comment]
I've answered your `--skip` question. I don't have enough reputation (yet!) to comment on your other q, so I'll ask here — have you tried `stack --verbose`?

On the general SO question, I believe you should continue to post questions there; many questions are answered on stackoverflow far more quickly than new github issues. There's also the `gitter` chat.

**Comment by dspies-leapyear** [comment]
Thank you. I very much appreciate it.
