### ISSUE TITLE
Seemingly unnecessary rebuilds of projects - request for more verbosity

### ISSUE THREAD

**Issue by minad** [commercialhaskell/stack#4383]
Sometimes stack is rebuilding projects with the message "unregistering (dependencies changed)..." and that takes quite some time. Often it is not clear to me what has been changed exactly. It would be nice if stack could show that. For rebuilds triggered due to flag changes, the difference between the flags could also be printed.

**Comment by dbaynard** [comment]
Closing in favour of #4308 — this whole area is changing soon. Thanks for the report, and for your patience.
