### ISSUE TITLE
Passing arguments to test suites does not give meaningful error messages

### ISSUE THREAD

**Issue by recursion-ninja** [commercialhaskell/stack#4384]
I ran the following command and the test didn't run with the arguments I supplied:
```
stack test library-name:test-name --test-arguments --pattern datasets/dynamic/multi-block/dna/arthropods.pcg
Error parsing targets: Directory not found: datasets/dynamic/multi-block/dna/arthropods.pcg
```

I don't understand the error message, what does this mean? I'm not giving `stack` a directory, I'm supplied arguments to the test suite. I think it's not parsing the command line options correctly.

**Comment by mgsloan** [comment]
Try putting the test arguments in quotes!  It's parsing `--pattern` as the only test argument, and the argument after that is being treated as an argument to stack.

**Comment by recursion-ninja** [comment]
Might I suggest that the parse error should recommend using quotes then. As it is, the error message is opaque and doesn't guide the user to the correct syntax.

**Comment by snoyberg** [comment]
There's not really a meaningful way to do that with command line interfaces, the input you've provided could be parsed as passing an extra argument to Stack itself.
