### ISSUE TITLE
'stack upload' should require confirmation before uploading

### ISSUE THREAD

**Issue by manny-fp** [commercialhaskell/stack#439]
I was originally going to title this "'stack upload' should be harder to use."

Uploading a package to hackage is irrevocable and it's a too easy now to accidentally upload without intending to do so (which I did in the last stack release, so now there's a weird version of stack on Hackage that can't be deleted).  `stack upload` could default to just telling you what it would do plus a message saying something like "use `stack upload -y` to actually upload".  Alternatively, it could prompt the user interactively, and also provide a `-y` option to have it skip the prompt.

**Comment by snoyberg** [comment]
I hadn't thought of going in this direction to be honest. What I'd thought of was simply removing the ability of `stack upload` without arguments to do an upload.

**Comment by manny-fp** [comment]
Ah, so you'd *have* to specify the directory/tarball.  Yeah, that'd work too.  Just something more than `stack upload` on its own.

**Comment by snoyberg** [comment]
@manny-fp Confirmed?
