### ISSUE TITLE
Stack can't copy bins on ubuntu with custom snapshot

### ISSUE THREAD

**Issue by dfithian** [commercialhaskell/stack#4396]
### General summary/comments (optional)

On ubuntu 16.04, Stack 1.9.1 (in a docker container), I tried to run `stack install --resolver haddock-resolver.yaml haddocset`. The docker build doesn't fail, but a strange warning about global projects is printed. When I start the image, `haddocset` is not available. If I re-run `stack install --resolver haddock-resolver.yaml haddocset` in the docker image it works the second time. Full output is attached.
[ubuntu-stack-install.txt](https://github.com/commercialhaskell/stack/files/2578264/ubuntu-stack-install.txt)

```
# docker build .
...
Writing implicit global project config file to: /root/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using resolver: custom: haddock-resolver.yaml specified on command line
...
Linking .stack-work/dist/x86_64-linux/Cabal-2.2.0.1/build/haddocset/haddocset ...
Installing executable haddocset in /root/.stack/snapshots/x86_64-linux/custom-haddock-resolver-Fz6C0WptWdGK/8.4.3/bin

--  End of log file: /root/.stack/global-project/.stack-work/logs/haddocset-0.4.3.log

Log files have been written to: /root/.stack/global-project/.stack-work/logs/
Couldn't find executable haddocset in directory /root/.stack/global-project/.stack-work/install/x86_64-linux/custom-haddock-resolver-Fz6C0WptWdGK/8.4.3/bin/

...

# docker run -it 45a3bc8fd85e
root@e3afc6ed3f7a:/# haddocset
bash: haddocset: command not found
root@e3afc6ed3f7a:/# stack install --resolver haddock-resolver.yaml haddocset
Copying from /root/.stack/snapshots/x86_64-linux/custom-haddock-resolver-Fz6C0WptWdGK/8.4.3/bin/haddocset to /root/.local/bin/haddocset

Copied executables to /root/.local/bin:
- haddocset
root@e3afc6ed3f7a:/# haddocset
Missing: COMMAND

Usage: haddocset [--hc-pkg CMD] [-t|--target DOCSET] [-q|--quiet] COMMAND
```

### Steps to reproduce

Put `Dockerfile` and `haddock-resolver.yaml` in a directory. Run `docker build .`.

#### Dockerfile:

```
FROM ubuntu:16.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PATH="/root/.local/bin:${PATH}"

...

RUN curl -L https://github.com/commercialhaskell/stack/releases/download/v1.9.1/stack-1.9.1-linux-x86_64.tar.gz | tar zx -C /tmp
RUN mv /tmp/stack-1.9.1-linux-x86_64/stack /usr/local/bin
ADD haddock-resolver.yaml dependencies.txt /
RUN stack setup --resolver haddock-resolver.yaml --install-ghc
RUN stack install --resolver haddock-resolver.yaml haddocset

...

ENTRYPOINT /bin/bash
```

#### haddock-resolver.yaml

```
resolver: lts-12.0
name: haddock-resolver
packages:
- haddock-api-2.20.0
- haddock-library-1.6.0
- git: https://github.com/philopon/haddocset
  commit: 0e89ffea4f0c375a1eed2493e2a08c3d3953f8b1
  subdirs:
  - .
```

### Expected

I expected `haddocset` to be installed the first time I ran

### Actual

`haddocset` was not installed the first time

### Stack version

```
root@e3afc6ed3f7a:/# stack --version
Version 1.9.1, Git revision f9d0042c141660e1d38f797e1d426be4a99b2a3c (6168 commits) x86_64 hpack-0.31.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by dfithian** [comment]
If I edit the Dockerfile to run the same install command twice, it succeeds in the build.

So, now the Dockerfile looks like:

```
...
RUN stack setup --resolver haddock-resolver.yaml --install-ghc
RUN stack install -v --resolver haddock-resolver.yaml haddocset
RUN stack install -v --resolver haddock-resolver.yaml haddocset
...
```

**Comment by dfithian** [comment]
Log from rerun within docker build:
[ubuntu-stack-install-rerun.txt](https://github.com/commercialhaskell/stack/files/2578272/ubuntu-stack-install-rerun.txt)

**Comment by dbaynard** [comment]
How odd — thanks for the report. I typically break up my DOCKERFILEs even further (setup, build --dependencies-only, build, install) though it really ought to work first time.

I wonder whether it needs a `/root/.stack/global-project/stack.yaml` file. Meanwhile, I'll assign somebody to investigate.

**Comment by snoyberg** [comment]
It's using the global project because you've specified a `--resolver` flag, but not a `--stack-yaml` flag. Can you try creating a `stack.yaml` with `resolver: haddock-resolver.yaml` and see what the result is?

**Comment by snoyberg** [comment]
No response, and the solution above should address this. Closing
