### ISSUE TITLE
Linker error with 'stack ghci'

### ISSUE THREAD

**Issue by pharpend** [commercialhaskell/stack#440]
Source tree: https://github.com/pharpend/desbot

```
[src/desbot master] % stack ghci
Configuring GHCi with the following packages: desbot
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
<command line>: can't load .so/.DLL for: /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/../../../../lib/libncurses.so (-lncursesw: cannot open shared object file: No such file or directory)
[src/desbot master] % locate libncurses.so
/usr/lib/libncurses.so
/usr/lib/libncurses.so.5
/usr/lib/libncurses.so.5.9
```

**Comment by snoyberg** [comment]
I was unable to reproduce this on Ubuntu 14.04.

**Comment by snoyberg** [comment]
FYI, on my system:

```
locate libncurses.so
/lib/x86_64-linux-gnu/libncurses.so.5
/lib/x86_64-linux-gnu/libncurses.so.5.9
/usr/lib/x86_64-linux-gnu/libncurses.so
```

Maybe you're missing the 64-bit version of the library?

**Comment by chrisdone** [comment]
> -lncursesw: cannot open shared object file: No such file or directory

@pharpend Where's a `w` in there (presumably for "wide"; unicode):

```
chris@retina:~$ locate libncursesw.so
/lib/x86_64-linux-gnu/libncursesw.so.5
/lib/x86_64-linux-gnu/libncursesw.so.5.9
```

**Comment by pharpend** [comment]
@snoyberg I'm on Arch Linux 64-bit.

```
[~] % locate libncursesw.so
/usr/lib/libncursesw.so
/usr/lib/libncursesw.so.5
/usr/lib/libncursesw.so.5.9
```

**Comment by pharpend** [comment]
FWIW, I'm getting the same error with the version of stack in master. (Previously, I was using the Hackage version).

I got a new system update today, so I'll see if that fixes it.

**Comment by pharpend** [comment]
I should mention, I can use normal `ghci` and `cabal repl` without issue

**Comment by pharpend** [comment]
So, I actually bothered to trace through the `..`s, and the shared object file does indeed exist at that location. I don't know where GHC is getting this idea that the file doesn't exist.

**Comment by pharpend** [comment]
Well, now I'm getting the same issue with `cabal repl`:

```
Preprocessing library desbot-0.1.0.0...
GHCi, version 7.10.1: http://www.haskell.org/ghc/  :? for help
<command line>: can't load .so/.DLL for: /usr/lib/gcc/x86_64-unknown-linux-gnu/5.1.0/../../../../lib/libncurses.so (-lncursesw: cannot open shared object file: No such file or directory)
```

**Comment by pharpend** [comment]
I'm thinking this might be a problem with GNU Readline, as it depends on ncurses.

**Comment by cocreature** [comment]
I run into the same problem with stack on arch 64bit. Compiling a c hello world with `-lncursesw` is working fine and the file mentioned in the error message exists.

**Comment by geekosaur** [comment]
This looks familiar. Debian oldstable (at least; haven't checked wheezy) makes `libncurses.so` a GNU linker script containing `INPUT(-lncursesw)`. Something is assuming that the parameter to INPUT is a pathname and trying to open it directly, whereas `ld` would do a normal static library search at that point.

**Comment by Earnestly** [comment]
Yes, `/usr/lib/libncurses.so` is a linker script on Arch as well with the same
contents.

**Comment by pharpend** [comment]
@geekosaur Without filing a thousand other bug reports, is there a fix and/or a temporary workaround?

**Comment by geekosaur** [comment]
The usual workaround is to replace the linker script with a symlink. This may annoy the system package manager, but people on Debian have not reported issues with it, and have had this issue with hs-curses etc. for several years now (Debian stable being what it is) so I would expect that problems would have been noticed by now.

The upstream bug is with ghc / ghci, and is one of the things that was supposed to be fixed by using the system linker instead of a home-grown one in the bytecode backend. 7.10.1 seems to have some other linker issues as well (and it may be too late to get fixes into 7.10.2.

**Comment by pharpend** [comment]
@geekosaur That worked. Since this appears to be a bug with GHC, not Stack, I'm closing this issue.

**Comment by puffnfresh** [comment]
I had this problem on Nix. Turns out the ncurses package was split into two parts, `out` having just libs and `dev` having the headers:

```yaml
nix:
  packages: [ncurses.out, ncurses.dev]
```

If you write `ncurses` you'll only get `ncurses.dev`.

It wasn't enough for me to make `stack.yaml` reference both in my project, because Stack caching. I had to clear out my `~/.stack` directory. Below is why, if you care.

---

It looks like Stack only checks compilation before caching packages, it does not check runtime linking. If you compile terminfo with just `ncurses` in your packages, then you will get:

```
library-dirs: /home/brian/.stack/snapshots/x86_64-linux-nix/lts-5.13/7.10.3/lib/x86_64-linux-ghc-7.10.3/terminfo-0.4.0.2-GTEmnLYt1ob2hCwhW9sVjr
              /nix/store/6djmaps8h2a1n05wzmgf774gkk5x1dij-ghc-7.10.3/lib
              /nix/store/hh1y3nd88a0cbs78b060rzlhig9lj69y-ncurses-5.9-dev/lib
```

So only the headers and no libs will be in library-dirs. Adding `ncurses.out` into your packages doesn't invalidate the terminfo package and you'll have a built terminfo which can't be run in GHCi.

**Comment by mgsloan** [comment]
One option for more selectively re-building a package is `stack exec -- ghc-pkg unregister X`.

**Comment by aiya000** [comment]
@geekosaur @pharpend
I have same issue in ArchLinux x86-64

```console
$ stack --version
Version 1.4.1, Git revision ea10057da1b1a49d937e7bcb6f997360bec1f863 (4765 commits) x86_64 hpack-0.17.0
```

```console
$ ls -l /usr/lib/libncurses*
-rw-r--r-- 1 root root     20  4月  4 03:43 /usr/lib/libncurses++.so
lrwxrwxrwx 1 root root     27  4月 12 16:26 /usr/lib/libncurses++.so.5 -> /usr/lib/libncurses++w.so.5
-rw-r--r-- 1 root root 162614  4月 12 16:26 /usr/lib/libncurses++w.a
lrwxrwxrwx 1 root root     18  4月  4 03:43 /usr/lib/libncurses++w.so -> libncurses++w.so.6
lrwxrwxrwx 1 root root     20  4月 12 16:26 /usr/lib/libncurses++w.so.5 -> libncurses++w.so.5.9
-rwxr-xr-x 1 root root  77336  4月 12 16:26 /usr/lib/libncurses++w.so.5.9
lrwxrwxrwx 1 root root     20  4月  4 03:43 /usr/lib/libncurses++w.so.6 -> libncurses++w.so.6.0
-rwxr-xr-x 1 root root  77336  4月  4 03:43 /usr/lib/libncurses++w.so.6.0
-rw-r--r-- 1 root root     18  4月  4 03:43 /usr/lib/libncurses.so
lrwxrwxrwx 1 root root     25  4月 12 16:26 /usr/lib/libncurses.so.5 -> /usr/lib/libncursesw.so.5
-rw-r--r-- 1 root root 774310  4月 12 16:26 /usr/lib/libncursesw.a
lrwxrwxrwx 1 root root     16  4月  4 03:43 /usr/lib/libncursesw.so -> libncursesw.so.6
lrwxrwxrwx 1 root root     18  4月 12 16:26 /usr/lib/libncursesw.so.5 -> libncursesw.so.5.9
-rwxr-xr-x 1 root root 403160  4月 12 16:26 /usr/lib/libncursesw.so.5.9
lrwxrwxrwx 1 root root     18  4月  4 03:43 /usr/lib/libncursesw.so.6 -> libncursesw.so.6.0
-rwxr-xr-x 1 root root 448952  4月  4 03:43 /usr/lib/libncursesw.so.6.0
```

Sorry, I don't know about 'linker library'.  
Please teach concrete of the way of its workaround X(
