### ISSUE TITLE
toggling --profile should not do a full rebuild

### ISSUE THREAD

**Issue by fommil** [commercialhaskell/stack#4404]
Related to, but not the same as, #4308 

If the developer wishes to profile their app, a rebuild is necessary. But when finished with their profiling session, the developer typically wishes to return to their regular build flags. The current behaviour is that another full rebuild will take place at this point.

If the developer is working on performance improvements, where they must benchmark with optimisations and investigate with profiling, this incurs 2 full rebuilds on every cycle. A workaround is to have two checkouts, or to remember to use `--work-dir`, but it is very confusing to work like that.

It would be a very good boost to developer productivity if the `--enable-profiling` toggle used a different binary cache directory, such that every cycle only recompiled what was necessary for the profiled, or optimised, binaries, respectively.

Additionally, it would be good if `--fast` did not require a rebuild either, but that's perhaps best saved for another ticket.

**Comment by dbaynard** [comment]
Thanks for the issue — I see the problem. I suspect nix may help, here, as a workaround.

Would you confirm, please, what you would like to see done differently to #4308?

**Comment by fommil** [comment]
@dbaynard I am not sure if my usecase is the same as #4308 I'm not using any `library-profiling` or `executable-profiling` flags, I'm just bouncing between `--profile` and normal builds.

**Comment by fommil** [comment]
@dbaynard in fact maybe let's just call this a dupe of 4308 since the proposed solution seems to be in the same ballpark.
