### ISSUE TITLE
stack base container

### ISSUE THREAD

**Issue by vsoch** [commercialhaskell/stack#4419]
Hi!

I'm new to using stack, and I'm noticing that it takes a really long time to build! I'm thus interested in creating a base Docker container and bootstrapping it, but I'm not familiar enough with Haskell or stack to know what best practices are, and how to go about doing this. I've tried separating out the install of GHC and stack and doing a `stack build` and `stack install` in a base container, but it doesn't seem to speed things up for a container that bootstraps it, and actually leads to an error. Could you help or give advice? The (very slow to build) working Dockerfile is [here](https://github.com/vsoch/penrose/blob/master/Dockerfile). Let me know if you need any other information and thanks so much!

**Comment by qrilka** [comment]
@vsoch I'm not quite sure how to resolve your question properly but steps from that Dockerfile look to be a bit odd: it's not clear why installation of GHC and Stack is required when `fpco/stack-build` already has them:
```
$ docker run --rm -it fpco/stack-build
root@ae6d6c09548a:/# ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.4.3
root@ae6d6c09548a:/# stack --numeric-version
1.9.1
root@ae6d6c09548a:/#
```

**Comment by vsoch** [comment]
That will save us a little time! Let me try that. I'm still wondering if there is some set of stack commands that can do a first chunk of dependency building (and then the final container finishes up)

**Comment by vsoch** [comment]
It looks like based on the dependencies that a different version is installed anyway?

```
Preparing to download ghc-8.0.2 ...
ghc-8.0.2: download has begun
ghc-8.0.2:   23.71 MiB / 107.55 MiB ( 22.05%) downloaded...
ghc-8.0.2:   51.96 MiB / 107.55 MiB ( 48.32%) downloaded...
ghc-8.0.2:   80.03 MiB / 107.55 MiB ( 74.41%) downloaded...
ghc-8.0.2:  107.55 MiB / 107.55 MiB (100.00%) downloaded...
Downloaded ghc-8.0.2.
Unpacking GHC into /root/.stack/programs/x86_64-linux/ghc-8.0.2.temp/ ...
Configuring GHC ...
Installing GHC ...
```

**Comment by vsoch** [comment]
The chunk of compiling I'm wonder if we can do more efficiently is this bit (this is just a tiny section I had time to copy paste)

```bash
sync-2.1.1.1: download
async-2.1.1.1: configure
async-2.1.1.1: build
async-2.1.1.1: copy/register
th-abstraction-0.2.6.0: copy/register
time-locale-compat-0.1.1.3: download
time-locale-compat-0.1.1.3: configure
transformers-compat-0.5.1.4: download
time-locale-compat-0.1.1.3: build
transformers-compat-0.5.1.4: configure
time-locale-compat-0.1.1.3: copy/register
transformers-compat-0.5.1.4: build
vector-0.12.0.1: download
vector-0.12.0.1: configure
transformers-compat-0.5.1.4: copy/register
vector-0.12.0.1: build
MonadRandom-0.5.1: download
MonadRandom-0.5.1: configure
MonadRandom-0.5.1: build
```
I'm hoping there is some way to create a base and then just finish up the last bit of the penrose library on top of it!

**Comment by qrilka** [comment]
It looks like `penrose` uses LTS-9.10, there's a tag for that LTS, see - https://hub.docker.com/r/fpco/stack-build/tags/
this way you could at least save some time on downloading/installing GHC
as for the dependencies - normally on CI this is achieved with cached directories or with `carche-s3` (for large projects), e.g. see how Stack uses it with Travis - https://github.com/commercialhaskell/stack/blob/master/.travis.yml#L13
Hope that helps a bit

**Comment by vsoch** [comment]
Awesome! I'll try this right now and give you an update. Fingers crossed!

**Comment by vsoch** [comment]
hey @qrilka I tried changing to use the base container, but I wound up still needing to install the custom version because it produced an error on build. I'm still also doing the entire thing in one Dockerfile (without a base) you can see the full build in this PR --> https://github.com/penrose/penrose/pull/152. Do you have any ideas for making it more streamlined (see the Dockerfile under files). You can close the issue if there is either nothing more to be done, or you can't help, thank you for your suggestions thus far!

**Comment by qrilka** [comment]
I'm not sure I have much time for a thorough review of that project and the way Docker gets used for it but I've left the basic improvement in your PR, closing this ticket as the question looks to be more or less resolved. Open new one if you'll have some other issues with Stack. Thanks.
