### ISSUE TITLE
Outdated documentation about adding a remote git repo in stack.yaml

### ISSUE THREAD

**Issue by Lysxia** [commercialhaskell/stack#4425]
(Version 1.9.1.1, Git revision a953002759e52bc1e799590869b812036e766f9e (6170 commits) x86_64)

The manual gives two different ways of adding a dependency via `git` (that one can find in a search using the keyword `git`):

- https://docs.haskellstack.org/en/stable/nonstandard_project_init/#using-git-repositories
- https://docs.haskellstack.org/en/stable/yaml_configuration/#git-and-mercurial-repos

I couldn't get the first one to work (even though it's the first result). The second is fine.

### Steps to reproduce

1. Take any stack project (or create one).
2. Add some package `foo` that can be found on a remote git repo as a dependency to the package
3. Use either of the above two methods to add `foo` to `stack.yaml`
4. `stack build`: the first method results in an error, the second doesn't.

So one of these seems outdated. It's odd that the error is not about invalid syntax, but stack simply seems to ignore that `location:` field under `packages:`.

**Comment by mihaimaruseac** [comment]
Checking whether this is a regression or just outdated documentation

**Comment by Lysxia** [comment]
Indeed it works with an `extra-dep` key. Without it here's a sample error:

```
Error: While constructing the build plan, the following exceptions were encountered:

Unknown package: generic-recursion-schemes

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be convenient when dealing with many complicated constraint
    errors, but results may be unpredictable.


Plan construction failed.
```

That is if the package is not on Hackage. If it is, you get either the usual error if it is not in your resolver, or `stack` installs whatever it finds in your resolver.

A big source of confusion for me was the fact that `stack` seems to just ignore that field (without the `extra-dep` key). It would expect at least a warning about it.

**Comment by dbaynard** [comment]
OK, so two things are needed to resolve the issue fully

1.  Correct the docs to indicate that using `packages` without `extra-dep` is deprecated, that using `packages` for dependency is old behaviour, and recommending the correct formulation.
2.  Parse the old syntax and error with how to resolve the issue.

@Lysxia Would you like to tackle one, or perhaps both (please no animal names for functions)?

**Comment by Lysxia** [comment]
Sadly I don't have time to work on this in the near future, although I would have liked to. But thanks for the offer. ;)

**Comment by snoyberg** [comment]
Sorry, I didn't notice this issue before. I wasn't even aware of the first doc. I'm going to send a PR to have it point to the YAML configuration doc instead.

**Comment by mattaudesse** [comment]
Resolved in #4656 - thanks @snoyberg for fixing and @Lysxia for reporting.

**Comment by mattaudesse** [comment]
Oops, sorry for jumping the gun - I see we still want to support the deprecated format; reopening.

**Comment by snoyberg** [comment]
I don't think we want to do that. We had a deprecation cycle and then removed support for the old format. The next release of Stack (2.0) is taking that even further with implicit snapshots.

**Comment by Lysxia** [comment]
Thanks @snoyberg ! I agree that was probably the last trace of the old format.
