### ISSUE TITLE
Exclude documentation from ghc installations

### ISSUE THREAD

**Issue by miniBill** [commercialhaskell/stack#4438]
I think that the ghc docs shouldn't be installed by default (I'm talking about the docs in `.stack/programs/x86_64-linux/ghc-X.Y.Z/share/doc/ghc-X.Y.Z/html`).

**Comment by mattaudesse** [comment]
Hey @miniBill,

Could you say a little bit more about why you think those docs should be excluded? Is it a space consideration?

```bash
$ du -hsc ~/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.4/share/doc/ghc-8.4.4/html
381M    /home/matt/.stack/programs/x86_64-linux/ghc-tinfo6-8.4.4/share/doc/ghc-8.4.4/html
381M    total
```

381 megabytes definitely isn't small, but on the other hand...
```bash
$ du -hsc ~/.stack
11G     /home/matt/.stack
11G     total
```

:-)

**Comment by miniBill** [comment]
Yes, it's a space consideration... 300MB is not a lot, but multiplied by
the number of ghcs installed it can become significant on a smallish ssd

Il giorno lun 10 dic 2018, 01:53 Matt Audesse <notifications@github.com> ha
scritto:

**Comment by dbaynard** [comment]
Seems like a good option (with my 64GB ssd I speak from personal experience) — though selecting it as default would require more discussion. I suspect as an option it should go in the `config.yaml` as it doesn't affect reproducibility of builds.

@miniBill Would you like to investigate?

**Comment by dbaynard** [comment]
(If it goes in config — which is where it belongs — it will need a fix to #3887, too)

**Comment by mattaudesse** [comment]
Thanks @miniBill - Allowing people to selectively skip storing docs there makes sense to me too.

**Comment by snoyberg** [comment]
Making such a change would end up breaking things like the `--haddock` flag in confusing ways. These kinds of half-working GHC installations are part of the reason we moved away from `system-ghc` being on by default. I'd be -1 on making it easy to do this. If someone really wants to save the disk space, they can manually delete the docs directory (which is exactly what Stack would have to do anyway).

**Comment by mattaudesse** [comment]
Okay, I'm with @snoyberg if this is likely to introduce subtle bugs.

Shall we close?

**Comment by snoyberg** [comment]
Sounds good
