### ISSUE TITLE
Getting “Process exited with code: ExitFailure (-1073741819)” on LiquidHaskell build on Windows AppVeyor

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#4441]
### General summary/comments (optional)
Cannot do executable building of liquidhaskell on AppVeyor cloud instances. Error is Access Violation, but I don't see what could trigger this even using "-v" option. I need some help to debug what is happening.

### Steps to reproduce

For example:

1. Run liquidhaskell build on AppVeyor like the described here:
https://stackoverflow.com/questions/53735133/getting-process-exited-with-code-exitfailure-1073741819-on-liquidhaskell-b

### Expected

Build to finish successfully, because all the steps before are fine.

### Actual

Cannot see what is happening even with "-v" option.

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) i386 hpack-0.31.1
```

### Method of installation

* Official binary

**Comment by dbaynard** [comment]
Thanks for the report. Could this be related to #3765?

https://stackoverflow.com/questions/48232637/haskell-stack-access-violation-error-during-build gives the resolution to that thread

**Comment by dbaynard** [comment]
It would also be helpful to know what change brought on the AccessViolation error — it would help narrow down the issue.

In addition, it isn't clear that this is a stack issue — I see you have some cabal.project files; you might try a cabal-install build on appveyor, too.

**Comment by varosi** [comment]
It is happening right from the start. It's not from a change. So I cannot
make it work on AppVeyor.

I'll try cabal-install, too. This is great idea!

На чт, 13.12.2018 г. в 1:42 ч. dbaynard <notifications@github.com> написа:

**Comment by quasicomputational** [comment]
Try with GHC 8.6. https://ghc.haskell.org/trac/ghc/ticket/15154 was fixed in that release and that's believed to be the culprit.

**Comment by varosi** [comment]
@quasicomputational Building it with GHC 8.6 resolved the problem! Now the problem will be to build LiquidHaskell with latest GHC.
