### ISSUE TITLE
Travis setup used for Stack gets deprecated

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/stack#4442]
Originally I was investigating build error in https://travis-ci.org/commercialhaskell/stack/jobs/467380455
It appears that Mercurial fails because of TLS 1.0 gets used.
And according to https://travis-ci.community/t/travis-ci-linux-build-environments-cant-clone-from-bitbucket-anymore-mercurial/1182 upgrade to Xenial is needed.
At the same time according to Travis documentation [currently used "Trusty Container-based environment" will stop being available after December 2018](https://docs.travis-ci.com/user/reference/overview/#deprecated-virtualization-environments), so we need to switch to other environment and at least because of Mercurial issue it makes sense to switch to Xenial.

**Comment by dbaynard** [comment]
@qrilka So we need to get rid of `sudo: false` (possibly adding `dist: xenial`) and then fix any build failures?

**Comment by dbaynard** [comment]
Some further detail:

* [The Travis CI Blog: Upcoming Required Linux Infrastructure Migration](https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration)
* [The Travis CI Blog: Combining The Linux Infrastructures](https://blog.travis-ci.com/2018-10-04-combining-linux-infrastructures)
