### ISSUE TITLE
stack upgrade --git failed: Could not find module ‘System.Uname’

### ISSUE THREAD

**Issue by ratatosk** [commercialhaskell/stack#4445]
/tmp/stack-upgrade17723/stack/src/Stack/Setup.hs:103:1: error:
    Could not find module ‘System.Uname’
    Use -v to see a list of the files searched for.
    |          
103 | import              System.Uname (uname, release)
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

current version:
Version 1.6.5, Git revision 24ab0d6ff07f28276e082c3ce74dfdeb1a2ca9e9 (5514 commits) x86_64 hpack-0.20.0

**Comment by ratatosk** [comment]
Upgraded without --git first to 1.9.3, then upgrade --git also worked.

**Comment by dbaynard** [comment]
Yes, there were some changes to uname (#4238) for 1.9 release. Glad to see you got it sorted 👍
