### ISSUE TITLE
Travis builds timing out

### ISSUE THREAD

**Issue by dbaynard** [commercialhaskell/stack#4447]
We may be able to fix the timeouts by timing out within the job earlier, leaving enough time for the cache to be uploaded. Any such build failures can be restarted, but this time using the cache.

Sources:

* [Upload the cache before timeout · Issue #6410 · travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues/6410#issuecomment-237812495)
* [Travis caching and incremental builds – Netherlands eScience Center](https://blog.esciencecenter.nl/travis-caching-and-incremental-builds-6518b89ee889)

**Comment by borsboom** [comment]
Now that the Azure Pipelines branch has been merged, we could also consider dropping Travis.  Azure pipelines should now be covering all the cases Travis does (and Appveyor, for that matter).  I believe it will run for PRs as well, just like Travis.

**Comment by qrilka** [comment]
@dbaynard @borsboom should we close this already as we moved to Azure pipelines?

**Comment by borsboom** [comment]
Yes, and we've removed the Travis pipelines now.
