### ISSUE TITLE
Trying to install stack on an ubuntu VM using VirtualBox with 10 GB memory and 2 GB RAM on a mac machine with 4 GB RAM

### ISSUE THREAD

**Issue by dinnu93** [commercialhaskell/stack#4448]
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.                
Installing GHC ...                                                              
Received ExitFailure 2 when running
Raw command: /usr/bin/make install
Run from: /home/dinesh/.stack/programs/x86_64-linux/ghc-8.4.4.temp/ghc-8.4.4/

**Comment by dinnu93** [comment]
I got a message from my ubuntu VM saying that it only has 483 MB remaining, Is that the problem or something else ?

**Comment by dbaynard** [comment]
Hi @dinnu93, it sounds likely. GHC requires ~1GB.

It isn't fully clear what has happened, though — if you need more suggestions, would you kindly fill in the issue template information (might be easier to close this and open a new one) in particular the verbose logs.

**Comment by snoyberg** [comment]
Closing due to lack of response
