### ISSUE TITLE
Building `Cabal` on mac hangs.

### ISSUE THREAD

**Issue by dspies-leapyear** [commercialhaskell/stack#4450]
Please follow the steps below for reporting a bug:

Make sure that you are using the latest release (currently stack-1.9.3).
See the [upgrade instructions](http://docs.haskellstack.org/en/stable/install_and_upgrade/#upgrade) to upgrade.

Please use the following schema for your bug report:

### General summary/comments (optional)
I can't build `Cabal` (trying various different snapshots). It just hangs

### Steps to reproduce
```
$ stack build Cabal --resolver=lts-11.22 -v
```

### Expected
It builds

### Actual
It hangs until I kill it

```
$ stack build Cabal --resolver=lts-11.22 -v
...
[debug] Run process within /private/var/folders/yg/gtwf12bs3dbgnvmxf5tzncn00000gn/T/stack83848/Cabal-2.0.1.1/: /Users/davidspies/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.1.0 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
^C
```

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
```

### Method of installation

* curl -sSL https://get.haskellstack.org/ | sh -s - -f

**Comment by dbaynard** [comment]
Hi @dspies-leapyear, thanks for the report. Would you post the full log (a link, or wrapped in `<details>` tags) and also indicate which snapshots you have tried?

It would be useful to know where you are starting from — what else do you have installed with these resolvers, for example?

It may be worth trying to change the linker. And have you taken a look at similar issues e.g. #3487?

**Comment by snoyberg** [comment]
Closing due to lack of response

**Comment by Krantz-XRF** [comment]
A similar problem occurs on Windows, too. When I run `stack build Cabal --verbose`, I can see the process hangs on a prompt saying 

> Run process within C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\

The process `ghc.exe` seems okay itself, despite that it takes 1307.6MiB memory. I waited for about 20 minutes, but it seemingly takes forever to finish. 

Below is the full log (till the interruption by <kbd>Ctrl</kbd>-<kbd>C</kbd> of course). 

<details>

> Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
> 2019-04-05 18:52:50.985086: [debug] Checking for project config at: E:\Hs-Projects\Bin2Cpp\stack.yaml
> 2019-04-05 18:52:50.989074: [debug] Loading project config file stack.yaml
> 2019-04-05 18:52:50.998049: [debug] Decoding build plan from: D:\Portable-Programs\stack\contents\build-plan\lts-13.15.yaml
> 2019-04-05 18:52:50.999047: [debug] Trying to decode D:\Portable-Programs\stack\contents\build-plan-cache\lts-13.15.cache
> 2019-04-05 18:52:51.010017: [debug] Success decoding D:\Portable-Programs\stack\contents\build-plan-cache\lts-13.15.cache
> 2019-04-05 18:52:51.025976: [debug] Potential GHC builds: standard
> 2019-04-05 18:52:51.026975: [debug] Found already installed GHC builds: standard
> 2019-04-05 18:52:51.038940: [debug] Getting global package database location
> 2019-04-05 18:52:51.042930: [debug] Asking GHC for its version
> 2019-04-05 18:52:51.044926: [debug] Getting Cabal package version
> 2019-04-05 18:52:51.046919: [debug] Run process: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --no-user-package-db list --global
> 2019-04-05 18:52:51.053902: [debug] Run process: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc.EXE --numeric-version
> 2019-04-05 18:52:51.070854: [debug] Run process: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --no-user-package-db field --simple-output Cabal version
> 2019-04-05 18:52:51.354098: [debug] Process finished in 293ms: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc.EXE --numeric-version
> 2019-04-05 18:52:51.356094: [debug] GHC version is: ghc-8.6.4
> 2019-04-05 18:52:51.364071: [debug] Process finished in 317ms: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --no-user-package-db list --global
> 2019-04-05 18:52:51.392992: [debug] Process finished in 320ms: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --no-user-package-db field --simple-output Cabal version
> 2019-04-05 18:52:51.393991: [debug] Resolving package entries
> 2019-04-05 18:52:51.394988: [debug] Trying to decode D:\Portable-Programs\stack\contents\loaded-snapshot-cache\x86_64-windows\ghc-8.6.4\lts-13.15.cache
> 2019-04-05 18:52:51.462809: [debug] Success decoding D:\Portable-Programs\stack\contents\loaded-snapshot-cache\x86_64-windows\ghc-8.6.4\lts-13.15.cache
> 2019-04-05 18:52:51.466799: [debug] Starting to execute command inside EnvConfig
> 2019-04-05 18:52:51.466799: [debug] Parsing the targets
> 2019-04-05 18:52:51.468791: [debug] Running hpack on E:\Hs-Projects\Bin2Cpp\package.yaml
> 2019-04-05 18:52:51.479764: [debug] hpack output unchanged in E:\Hs-Projects\Bin2Cpp\Bin2Cpp.cabal
> 2019-04-05 18:52:51.511676: [debug] Start: getPackageFiles E:\Hs-Projects\Bin2Cpp\Bin2Cpp.cabal
> 2019-04-05 18:52:51.532624: [debug] Finished in 21ms: getPackageFiles E:\Hs-Projects\Bin2Cpp\Bin2Cpp.cabal
> 2019-04-05 18:52:51.536618: [debug] Finding out which packages are already installed
> 2019-04-05 18:52:51.541598: [debug] Run process: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --global --no-user-package-db dump --expand-pkgroot
> 2019-04-05 18:52:51.842791: [debug] Process finished in 301ms: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --global --no-user-package-db dump --expand-pkgroot
> 2019-04-05 18:52:51.843787: [debug] Ignoring package haskeline due to wanting version 0.7.5.0 instead of 0.7.4.3
> 2019-04-05 18:52:51.844784: [debug] Ignoring package Cabal due to wanting version 2.4.1.0 instead of 2.4.0.1
> 2019-04-05 18:52:51.846782: [debug] Run process: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --user --no-user-package-db --package-db D:\Portable-Programs\stack\contents\snapshots\c6f920a2\pkgdb dump --expand-pkgroot
> 2019-04-05 18:52:52.119051: [debug] Process finished in 271ms: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --user --no-user-package-db --package-db D:\Portable-Programs\stack\contents\snapshots\c6f920a2\pkgdb dump --expand-pkgroot
> 2019-04-05 18:52:52.120049: [debug] Run process: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --user --no-user-package-db --package-db E:\Hs-Projects\Bin2Cpp\.stack-work\install\5fdbb79e\pkgdb dump --expand-pkgroot
> 2019-04-05 18:52:52.382346: [debug] Process finished in 262ms: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --user --no-user-package-db --package-db E:\Hs-Projects\Bin2Cpp\.stack-work\install\5fdbb79e\pkgdb dump --expand-pkgroot
> 2019-04-05 18:52:52.385339: [debug] Constructing the build plan
> 2019-04-05 18:52:52.387336: [debug] Trying to decode D:\Portable-Programs\stack\contents\indices\Tsinghua\01-index.cache
> 2019-04-05 18:52:52.704484: [debug] Success decoding D:\Portable-Programs\stack\contents\indices\Tsinghua\01-index.cache
> 2019-04-05 18:52:52.722441: [debug] Checking if we are going to build multiple executables with the same name
> 2019-04-05 18:52:52.723434: [debug] Executing the build plan
> 2019-04-05 18:52:52.728452: [debug] Getting global package database location
> 2019-04-05 18:52:52.728452: [debug] Run process: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --no-user-package-db list --global
> 2019-04-05 18:52:52.958804: [debug] Process finished in 230ms: C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --no-user-package-db list --global
> 2019-04-05 18:52:52.960799: [debug] Exception ignored when attempting to load D:\Portable-Programs\stack\contents\precompiled\x86_64-windows\ghc-8.6.4\2.4.0.1\Q2FiYWwtMi40LjEuMEBzaGEyNTY6NTZjODU4Y2Y4NWU4NzU2YTk0YWFmOTMwZjJiZTRjMmVhZWU2MjNmMDY3ZTdjNTUzOTQxOTRkMzc0MTE0N2FiNywyMTgyNQ==\Kzl5Ohck2epVHDO83tkW8Z4ujSz6lrtQELQhE9flz9I=: D:\Portable-Programs\stack\contents\precompiled\x86_64-windows\ghc-8.6.4\2.4.0.1\Q2FiYWwtMi40LjEuMEBzaGEyNTY6NTZjODU4Y2Y4NWU4NzU2YTk0YWFmOTMwZjJiZTRjMmVhZWU2MjNmMDY3ZTdjNTUzOTQxOTRkMzc0MTE0N2FiNywyMTgyNQ==\Kzl5Ohck2epVHDO83tkW8Z4ujSz6lrtQELQhE9flz9I=: openBinaryFile: does not exist (No such file or directory)
> 2019-04-05 18:52:54.223423: [debug] Exception ignored when attempting to load C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\.stack-work\dist\e626a42b\stack-config-cache: C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\.stack-work\dist\e626a42b\stack-config-cache: openBinaryFile: does not exist (No such file or directory)
> 2019-04-05 18:52:54.223423: [debug] Exception ignored when attempting to load C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\.stack-work\dist\e626a42b\stack-cabal-mod: C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\.stack-work\dist\e626a42b\stack-cabal-mod: openBinaryFile: does not exist (No such file or directory)
> 2019-04-05 18:52:54.225418: [info] Cabal-2.4.1.0: configure
> 2019-04-05 18:52:54.474748: [debug] Run process within C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\: D:\Portable-Programs\stack\contents\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.4.exe --builddir=.stack-work\dist\e626a42b configure --with-ghc=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc.EXE --with-ghc-pkg=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --user --package-db=clear --package-db=global --package-db=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\pkgdb --libdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\lib --bindir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\bin --datadir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\share --libexecdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\libexec --sysconfdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\etc --docdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\doc\Cabal-2.4.1.0 --htmldir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\doc\Cabal-2.4.1.0 --haddockdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\doc\Cabal-2.4.1.0 --dependency=Win32=Win32-2.6.1.0 --dependency=array=array-0.5.3.0 --dependency=base=base-4.12.0.0 --dependency=binary=binary-0.8.6.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 --dependency=deepseq=deepseq-1.4.4.0 --dependency=directory=directory-1.3.3.0 --dependency=filepath=filepath-1.4.2.1 --dependency=mtl=mtl-2.2.2 --dependency=parsec=parsec-3.1.13.0 --dependency=pretty=pretty-1.1.3.6 --dependency=process=process-1.6.5.0 --dependency=text=text-1.2.3.1 --dependency=time=time-1.8.0.2 --dependency=transformers=transformers-0.5.6.2 --extra-include-dirs=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include --extra-lib-dirs=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin --extra-lib-dirs=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib
> 2019-04-05 18:53:03.132583: [debug] Process finished in 8655ms: D:\Portable-Programs\stack\contents\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.4.exe --builddir=.stack-work\dist\e626a42b configure --with-ghc=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc.EXE --with-ghc-pkg=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\ghc-8.6.4\bin\ghc-pkg.EXE --user --package-db=clear --package-db=global --package-db=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\pkgdb --libdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\lib --bindir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\bin --datadir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\share --libexecdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\libexec --sysconfdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\etc --docdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\doc\Cabal-2.4.1.0 --htmldir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\doc\Cabal-2.4.1.0 --haddockdir=D:\Portable-Programs\stack\contents\snapshots\c6f920a2\doc\Cabal-2.4.1.0 --dependency=Win32=Win32-2.6.1.0 --dependency=array=array-0.5.3.0 --dependency=base=base-4.12.0.0 --dependency=binary=binary-0.8.6.0 --dependency=bytestring=bytestring-0.10.8.2 --dependency=containers=containers-0.6.0.1 --dependency=deepseq=deepseq-1.4.4.0 --dependency=directory=directory-1.3.3.0 --dependency=filepath=filepath-1.4.2.1 --dependency=mtl=mtl-2.2.2 --dependency=parsec=parsec-3.1.13.0 --dependency=pretty=pretty-1.1.3.6 --dependency=process=process-1.6.5.0 --dependency=text=text-1.2.3.1 --dependency=time=time-1.8.0.2 --dependency=transformers=transformers-0.5.6.2 --extra-include-dirs=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\include --extra-lib-dirs=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\bin --extra-lib-dirs=C:\Users\krant\AppData\Local\Programs\stack\x86_64-windows\msys2-20150512\mingw64\lib
> 2019-04-05 18:53:03.135576: [debug] Encoding C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\.stack-work\dist\e626a42b\stack-config-cache
> 2019-04-05 18:53:03.139565: [debug] Finished writing C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\.stack-work\dist\e626a42b\stack-config-cache
> 2019-04-05 18:53:03.139565: [debug] Encoding C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\.stack-work\dist\e626a42b\stack-cabal-mod
> 2019-04-05 18:53:03.145550: [debug] Finished writing C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\.stack-work\dist\e626a42b\stack-cabal-mod
> 2019-04-05 18:53:03.146549: [info] Cabal-2.4.1.0: build
> 2019-04-05 18:53:03.147547: [debug] Run process within C:\Users\krant\AppData\Local\Temp\stack7100\Cabal-2.4.1.0\: D:\Portable-Programs\stack\contents\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.4.exe --builddir=.stack-work\dist\e626a42b build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"

</details>

**Comment by snoyberg** [comment]
I still believe this is just a slowly compiling package, not a bug. Please try running with `--interleaved-output` to see if there is progress.
