### ISSUE TITLE
Stack's support of detailed-0.9 test type appears to be broken

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/stack#4453]
### General summary/comments (optional)

Stack claimed to support `detailed-0.9` test suite type starting with #1447
It looks that it got broken somehow, I found it while trying to build Stackage snapshot with Stack.

### Steps to reproduce

1. Clone https://github.com/michaxm/test-detailed-example which was the original minimal example for this feature (from #1429)
2. Run command `stack test`.

### Expected

Test succeeds.

### Actual

Running test hangs indefinitely.

Example Stack log lines before it stalls:
```
Linking .stack-work/dist/x86_64-linux-tinfo6/Cabal-1.22.4.0/build/test-detailed-example-testStub/test-detailed-example-testStub ...
test-detailed-example-0.1.0.0: copy/register
Installing library in
/home/qrilka/ws/h/test-detailed-example/.stack-work/install/x86_64-linux-tinfo6/lts-3.14/7.10.2/lib/x86_64-linux-ghc-7.10.2/test-detailed-example-0.1.0.0-00o8EUyMcEg219fUJPx6Ed
Registering test-detailed-example-0.1.0.0...
test-detailed-example-0.1.0.0: test (suite: test-detailed-example-test)
            
Progress 1/2: test-detailed-example-0.1.0.0
```

### Stack version

Tried with versions 1.7.1, 1.9.1, 1.9.3

### Method of installation

1.9.x:
* Official static binary, downloaded from Github releases
1.7.1:
* gentoo-haskell Gentoo portage overlay

**Comment by snoyberg** [comment]
This should be addressed by 75e1091a22e97280b716340468082e26d40e3f88. I've asked @NorfairKing to put together a PR that includes a regression test to catch this in the future.
