### ISSUE TITLE
Building without 01-index files.

### ISSUE THREAD

**Issue by arrowd** [commercialhaskell/stack#4454]
I'm trying to use stack as a build tool for FreeBSD Ports of Haskell applications. It would be pretty lengthy to explain everything in detail, but it boils down to the following problem:

I plan to archive whole stack root, which is prepared to build given package. However, index files are very large. I tried deleting them, but it worked only for `00-index` ones.

Here are exact commands I'm running:

```
# env HOME=${WRKDIR}/home stack --stack-root ${SR} --system-ghc --no-install-ghc init
# env HOME=${WRKDIR}/home stack --stack-root ${SR} --system-ghc --no-install-ghc build --prefetch --dry-run
```

At this point I have all packages required in `${SR}`, but also two 500-megs index files. Now,

```
# rm ${SR}/indices/Hackage/01-index.cache ${SR}/indices/Hackage/01-index.tar
# env HOME=${WRKDIR}/home stack --stack-root ${SR} --system-ghc --no-install-ghc build
```

works fine - `stack` start building the package right away using prefetched archives and without updating index.

However, removing `01-index` files too makes `build` command fail with:

> Downloading timestamp                                                                            
> Error: No updates to your package index were found, but downloaded index is missing.             
> Update complete                                                                                  
> ${SR}/indices/Hackage/01-index.tar: openBinaryFile: does not exist (No such file or directory)

If it would be still possible to `build` the package without having `01-index.tar` file in place, it would really easen things for me.

**Comment by snoyberg** [comment]
This _might_ be possible on master due to the usage of the Pantry database for holding the relevant information. But as things exist in 1.9.3, the 01-index.tar file is absolutely necessary for getting Hackage revisions of cabal files.

**Comment by arrowd** [comment]
Well, the `pantry.sqlite3` itself weighs almost as much as 01-index.tar, so it doesn't solve the problem for me.

**Comment by arrowd** [comment]
Some tables in `pantry.sqlite3` contain more than 100k rows. I wonder if the database size can be reduced to only what current package needs?

BTW, `--prefetch` now doesn't even download dependencies. I hope this is a temporal regression.

**Comment by qrilka** [comment]
@snoyberg there's also `00-index.tar` which contains only the latest revisions (so it's smaller) but Stackage LTS could depend on not the latest revision so probably it won't suit you needs unfortunately :(

**Comment by snoyberg** [comment]
There's no clear way to make this happen, closing

**Comment by arrowd** [comment]
Note that I was able to solve my problem using `cabal new-build`. Simply unpacking all packages dependencies, creating an empty cabal config and then running `cabal new-build` allows building without any network usage.

**Comment by snoyberg** [comment]
Is there any reason that solution doesn't work with Stack?

**Comment by arrowd** [comment]
Hmm, I actually didn't try to drop dependencies into source dir and adjust `stack.yaml`. Maybe that could've worked too.

You think if I do that, stack wouldn't try to download the index?

**Comment by snoyberg** [comment]
If you set the resolver to a GHC version instead of a snapshot, I think so.
It may even work with a snapshot resolver. I could be mistaken. I'd
certainly be interested if that works.
