### ISSUE TITLE
Proper handling of warning/error output

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#446]
The output of commands like `stack dot` can sometimes be intruded upon by warning and error output. We should ensure that warning/error output is sent to stderr instead of stdout. In addition, as discussed elsewhere, we may want to silence some specific warnings that are not dangerous (specifically: the missing files referenced from a .cabal file).

**Comment by chrisdone** [comment]
Note to self or usurper: Warnings/error output can be tweaked in `Stack.Types.StackT`.

**Comment by chrisdone** [comment]
This was implemented in 4460c36814e8312afd8429461497faafe5955175 which is merged in.

**Comment by chrisdone** [comment]
@snoyberg Can you check on your side that this does the job you intended?

**Comment by snoyberg** [comment]
Confirmed
