### ISSUE TITLE
`stack haddock haskell-src-exts` hangs

### ISSUE THREAD

**Issue by davidspies** [commercialhaskell/stack#4461]
This happens both on Mac and on Ubuntu.

```
$ stack haddock haskell-src-exts --resolver=lts-12.24
haskell-src-exts-1.20.3: configure
haskell-src-exts-1.20.3: build
^C
```

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
```

### Method of installation

* Official binary, downloaded from stackage.org

(sorry if this is a duplicate; I thought I reported it already, but now I can't find the ticket)

**Comment by snoyberg** [comment]
This package takes a long time to compile on any machine. How long did you wait before killing?

**Comment by snoyberg** [comment]
Closing due to lack of response
