### ISSUE TITLE
All commands fail unless ghc is on the PATH (master)

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4466]
### Steps to reproduce

1. Install latest Stack from master (1bbed48cf22ecc7a3fa3ed230e1cc6354fdf809f)
2. Run `stack path` or any other command

### Expected

The command to succeed

### Actual

Get an error along the lines of:

```
Executable named ghc not found on path: [...]
```

### Stack version

```
$ stack --version
Version 1.10.0, Git revision 1bbed48cf22ecc7a3fa3ed230e1cc6354fdf809f (dirty) (6717 commits) x86_64 hpack-0.31.1
```

### More info

The `hashSourceMapData` function is calling `proc compilerExe ["--info"] readProcess`, which seems to be where this error message is coming from. I don't know why Stack isn't using the modified process execution environment to find the appropriate GHC.

**Comment by silky** [comment]
this is what i reported here: https://github.com/commercialhaskell/stack/issues/4465

**Comment by snoyberg** [comment]
Thanks for reporting @silky, sorry I didn't notice. @qrilka got this fixed on master now, please check it out and confirm for yourself when you have a chance.
