### ISSUE TITLE
stack upgrade goes through entire build process, even when already up to date

### ISSUE THREAD

**Issue by ojw** [commercialhaskell/stack#447]
Steps to reproduce:

Run ```stack upgrade```.
After the upgrade, immediately run ```stack upgrade``` again.

Expected:
Stack will notice that it is up-to-date and not run the full build process the second time, probably reporting a message that it is up-to-date already.

Actual:
Stack runs through the build process again.

Here is the ```stack --version``` output:
Version 0.1.1.0, Git revision 91fe70306f51eb3d68667a0d6e09a7d7ebbeb2b6

For the second run, the ```stack --version``` is:
Version 9.9.9

Here is the output of the command when I ran with ```stack upgrade --verbose```:
http://pastebin.com/pZhc6t0n

**Comment by snoyberg** [comment]
Agreed, I commented on this limitation but forgot to open an issue about it. We should solve it. The 9.9.9 issue is a separate one, and a limitation of Hackage it seems...

**Comment by snoyberg** [comment]
I've pushed a commit for this. It doesn't do anything for the Git case, since that seems like a corner case to deal with, but when running `stack upgrade`, it will do nothing if the upstream version if `<=` the current version.
