### ISSUE TITLE
Script interpreter cannot discover packages on master

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4472]
Repro:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-12.21 script --package stm
import Control.Monad.STM

main :: IO ()
main = pure ()
```

Running `stack Main.hs` on the file above works with both the current Stack release (1.9.1) and with Stack HEAD (b227e946b0598b8a87da2c3dfd13debf3638b50c). However, if you remove the `--package stm` bit, it will fail on HEAD while working with the current Stack release.

**Comment by mihaimaruseac** [comment]
Confirmed on a fresh clone (8e3490566b8e2846d99219156bee47047bd44564)

**Comment by qrilka** [comment]
I plan to look into it soon
