### ISSUE TITLE
Move back to FP Complete Hackage mirror?

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4473]
Due to increased reliability of Hackage itself and its CDN providing nice guarantees, I moved Stack to point to Hackage instead of the FP Complete mirror (located on S3) by default. I just saw some discussions of breaking integration tests due to Hackage being down. Should we move Stack back to pointing at the historically more reliable S3 mirror?

**Comment by phadej** [comment]
Can't stack simply support multiple mirrors and try them in turn if some of them fails? Isn't that the point of mirrors? `hackage-security` supports mirrors, so it shouldn't be too difficult to do.

https://www.stackage.org/haddock/lts-13.0/hackage-security-0.5.3.0/Hackage-Security-Client-Repository.html#v:repWithMirror

**Comment by phadej** [comment]
Also, Hackage is back up.

**Comment by DanBurton** [comment]
> Can't stack simply support multiple mirrors and try them in turn if some of them fails? Isn't that the point of mirrors? hackage-security supports mirrors, so it shouldn't be too difficult to do.

+1 to stack trying backup mirrors

However... doesn't the design of pantry basically require its own separate hosting? (Unless there are plans for hackage to support the hash-based api pantry wants to use.)

**Comment by snoyberg** [comment]
@phadej I don't know why the mirror logic doesn't work already. This should be a feature of hackage-security, not Stack.
