### ISSUE TITLE
Windows terminal 64 bits?

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack#4476]
After the stack installation on windows is done it's not really clear what terminal should be used.

I'm on windows 10 64 bits.

When i start my git bash (i had git installed) or windows command prompt and run stack it's using mingw32

When i start mingw64.exe from `%APPDATA%\Local\Programs\stack\x86_64-windows` stack can not be found.

It wouldn't hurt to add some explanation here to the manual. In particular i'm confused if everything is actually setup the right way to compile 64 bits programs.

EDIT:
related question. How to get the path to the gcc compiler? i like to compile some external C code. It's better to use GCC shipped here than to ask the users of my library to install gcc separately or visual studio. Also need the make tool and possible some other tools.

**Comment by mattaudesse** [comment]
Hey @flip111 - this is more of a Windows CLI question than something directly specific to `stack`, and the answer will depend on an individual's personal environment + how it's set up (so it's hard to provide any set of steps that'll apply equally well to everyone, although we'd happily welcome a docs PR if you'd like to volunteer).

> After the stack installation on windows is done it's not really clear what terminal should be used.

Whichever one you'd like! I'm not a Windows user so I can't replicate the problem, but it sounds like you just need to update your `PATH` environment variable. Did you follow [these steps?](https://docs.haskellstack.org/en/stable/install_and_upgrade/#path)

[This](https://www.howtogeek.com/118594/how-to-edit-your-system-path-for-easy-command-line-access/) may be helpful for using Window's default terminal.

`bash` terminals generally let you modify your `PATH` via a "dotfile" which runs when you enter an interactive shell session. Some common places to look:
- `/home/user/.bashrc`
- `/home/user/.bash_profile`
- `/home/user/.profile`

There are lots of ways to run `bash` on Windows these days, and they can each behave differently, so I can't say for sure which will apply to your system. Googling how to update the path for your `bash` distro should fetch plenty of hits, but it generally looks something like this in practice:

```bash
# You'd append this to ~/.bashrc:
export PATH="/some/additional/bin:$PATH"
```

I'm going to close since this doesn't seem like a `stack` problem but please feel free to continue the thread until everything's running smoothly. Perhaps someone who's more of a Windows person could weigh in too.

**Comment by flip111** [comment]
I know about `PATH`. My point is that Stack ships with a build environment windows. This is likely because GHC ships with a build environment for windows and stack ships with GHC. But the stack installer doesn't create icons, doesn't setup PATH or anything. There is no documentation on this either. If you were to install stack on windows and browse it's installation folders you would see what i'm talking about. Also consult GHC documentation.

I like to know how to use this environment as it's "suppose to be used". I mean someone put it in there, so now that it is in i like to know how to use it.

As stack is also about being "reproducible" i like to advise the users of my library how to initialize the right build environment for windows and make reproducible builds.

Can you please re-open the question ?

**Comment by mattaudesse** [comment]
I've put in a question to the other `stack` maintainers in case someone has a Windows box handy and can help you.

**Comment by flip111** [comment]
Thank you for re-opening. By the way gcc is located here:

`%appdata%\local\programs\stack\x86_64-windows\ghc-X.Y.Z\mingw\bin\gcc.exe` so it's also shipped. I need gcc to compile some C libraries together with the haskell library.

**Comment by snoyberg** [comment]
@flip111 I use Stack on Windows regularly enough. I don't follow your questions here. Stack sets up the PATH for processes it executes (like `ghc`) appropriately. Can you pinpoint what your concerns here are?

**Comment by flip111** [comment]
hi @snoyberg at the moment there doesn't seem that gcc is included in PATH. I like to make use of gcc which ships with ghc. Next to gcc (probably in the same directory) there are a bunch of other tools. My question is basically how do i get access to those build tools. It would be best if the users of my library could just use stack on windows and i could use gcc from the library `Setup.hs`. Now that this access doesn't seem to be there i'm asking for best practices in this case.

**Comment by snoyberg** [comment]
Running `stack exec which gcc` works on my Windows machine. Stack configures its internal `PATH` env var to include the directories containing `ghc.exe`, `gcc.exe`, etc. Have you tried calling out to `gcc.exe` from inside your `Setup.hs`?

**Comment by flip111** [comment]
Yes i was about to do that because the external C library comes with it's own make/configure step and it's just more convenient to use the "official" tools instead of tracking which C files are being compiled and then mentioned them in my stack/cabal file one by one.

Is it ok to call `gcc` with `stack exec gcc` from within Setup.hs ? If so we could just add a piece to the documentation of stack to use `stack exec` to get access to the build tools.

**Comment by snoyberg** [comment]
Sure, that's OK, but AFAICT it should be completely unnecessary. To my knowledge, `Setup.hs` is called from an environment that has `gcc` on the `PATH` already. If not, it would be interesting to know, and you could then call `stack exec gcc` instead.

**Comment by flip111** [comment]
Ah great. I will test this as soon as possible and comment again.

**Comment by flip111** [comment]
@snoyberg so i looked into it again (last time was december). I need gcc but i don't want to call gcc directly. Instead i want to use some make program. Preferably `mingw32-make` because i think compiling with visual studio together with the rest being in mingw will just give problems. However there doesn't seem to be a make-like executable available.

So about "environments" .. there seem to be two things:

`%appdata%\Local\Programs\stack\x86_64-windows\ghc-8.6.3\mingw`, tools that come with GHC. Probably to compile the runtime system and things like that. I could re-use this gcc probably. But this doesn't have build tools (don't think GHC needs this so this is obvious then).

However there is also

`%appdata%\Local\Programs\stack\x86_64-windows\msys2-20180531` with a file `InstallationLog.txt` starting with

```
************************************* Invoked: Sun Jun 3 13:23:34 2018
[0] Arguments: C:\Users\Michael Snoyman\Downloads\msys2-x86_64-20180531.exe
```

In this directory there are executables `mingw32.exe` and `mingw64.exe`. I guess the tools that were sufficient for GHC are not enough for stack because stack seems to ship with msys2.

Then in that same directory there is `maintenancetool.exe` when i start that i get a nice wizard asking if i would want to add/remove components. But this doesn't work because it comes with a error `At least one valid and enabled repository required for this action to succeed`. Then there is also the command `pacman` which also should be some package manager.

Should i go down this path, working with the files that ghc & stack install? Or should i ask the user of my library to install his own mingw build environment? Will it then still be compatible? Or is it ok to try to add a repo to that msys2, install a make tool and i'm good to go? Or maybe stack can ship a mingw32-make with the next version or next lts?

I am suppose to do, or can i do something with the tools that stack ships with. Or is it hands off, launch your own environment instead?

Advice is very much appreciated, thanks.

**Comment by snoyberg** [comment]
I'm on mobile and wasn't able to read everything yet, but the typical
answer here is probably: use stack exec Pacman to install the additional
dependencies you need

**Comment by flip111** [comment]
@snoyberg the advice you gave works great. Can i submit a PR against the documentation to add a section when people need more build tools or other tools they can get it from pacman? Maybe somewhere around here https://docs.haskellstack.org/en/stable/architecture/#building ??

The C library compiled into a static library succesfully, unfortunately the haskell project is more or less blocked on https://github.com/haskell/cabal/issues/1317 although i could try the solution with `confHook`.

My findings about using the build tools are as follows:

The following commands can be used to install cmake & make:

```
stack exec -- pacman -S mingw64/mingw-w64-x86_64-cmake
stack exec -- pacman -S mingw64/mingw-w64-x86_64-make
stack exec -- pacman -S msys/cmake
stack exec -- pacman -S msys/make
```

I choose the `mingw64` version because `msys` versions gave me problems. `System is unknown to cmake, create: Platform/MINGW64_NT-10.0 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake`

to uninstall any of the tools:
```
stack exec -- pacman -R mingw-w64-x86_64-make
stack exec -- pacman -R mingw-w64-x86_64-cmake
stack exec -- pacman -R cmake
stack exec -- pacman -R make
```
(notice that section before the slash and slash should not be there)

Under windows cmake has trouble finding gcc and make program. So i find them myself using `System.Directory.findExecutable` and then pass them to make with `-DCMAKE_C_COMPILER=path` and `-DCMAKE_MAKE_PROGRAM=path`.

Then when using cmake one has to use the "MSYS Makefiles" generator.

**Comment by snoyberg** [comment]
A doc PR would be wonderful, thank you! It would be great to have somewhere to point to for this common question. I think I'd recommend a new file dedicated to "Using pacman on Windows" or similar. If anyone else has thoughts on where this should go, please say so.

**Comment by snoyberg** [comment]
@flip111 Bump, are you still planning on making a doc PR?

**Comment by flip111** [comment]
Sure, but i'm not sure under which chapter to place the information

**Comment by snoyberg** [comment]
How about a new file called `pacman-on-windows.md`? If you open up the PR with the content somewhere, I'll be happy to move it into the right location.

**Comment by snoyberg** [comment]
Docs added in #4717, thanks!

**Comment by kenkangxgwe** [comment]
Hi, I would like to ask if there is any way to use mingw32-make instead of make on Windows. When you type `stack exec -- which make`, it definitely cannot find the executable.

**Comment by flip111** [comment]
In the docs I added it says that the environment had "problems" with
finding the installed packages. This is unfortunate... But they are still
there just not loaded on PATH. Probably therefore `which` can not find
them. Maybe we should open an issue for this and fix it.

I recommend you look into your windows folders to see which executables are
available. And then execute them directly with full path.
