### ISSUE TITLE
Unable to load ghci: can't load .so/.DLL

### ISSUE THREAD

**Issue by eckyputrady** [commercialhaskell/stack#448]
Hi,

When I run `stack ghci`, I encounter this error:

```
Loading package livelog-0.1.0.0 ... <command line>: can't load .so/.DLL for: /Users/eckyputrady/Projects/livelog/.stack-work/install/x86_64-osx/lts-2.16/7.8.4/lib/x86_64-osx-ghc-7.8.4/livelog-0.1.0.0/libHSlivelog-0.1.0.0-ghc7.8.4.dylib (dlopen(/Users/eckyputrady/Projects/livelog/.stack-work/install/x86_64-osx/lts-2.16/7.8.4/lib/x86_64-osx-ghc-7.8.4/livelog-0.1.0.0/libHSlivelog-0.1.0.0-ghc7.8.4.dylib, 9): Symbol not found: _livelogzm0zi1zi0zi0_App_runAppIO1_closure
  Referenced from: /Users/eckyputrady/Projects/livelog/.stack-work/install/x86_64-osx/lts-2.16/7.8.4/lib/x86_64-osx-ghc-7.8.4/livelog-0.1.0.0/libHSlivelog-0.1.0.0-ghc7.8.4.dylib
  Expected in: flat namespace
 in /Users/eckyputrady/Projects/livelog/.stack-work/install/x86_64-osx/lts-2.16/7.8.4/lib/x86_64-osx-ghc-7.8.4/livelog-0.1.0.0/libHSlivelog-0.1.0.0-ghc7.8.4.dylib)
```

How to solve this error?

The project is [here](https://github.com/eckyputrady/livelog), in case it's needed to reproduce the error

**Comment by snoyberg** [comment]
@manny-fp As our relative Mac expert, any thoughts?

**Comment by manny-fp** [comment]
Try adding all your modules to `exposed-modules` or `other-modules` in your .cabal file.  E.g.,

```
library
  hs-source-dirs:      src
  exposed-modules:     Lib
  other-modules:       App
                     , Controllers.Common
                     , Controllers.Logs
                     , Controllers.LogTag
                     , Controllers.Tags
                     , Model
                     , Types
  [...]
```

**Comment by eckyputrady** [comment]
Thanks for the response.

I've tried it but still get the error. FYI, I also tried on Elementary OS Freya and got the same error.

**Comment by manny-fp** [comment]
Hmm, interesting, that solved it for me when I tried it.  Did you run `stack build` after changing livelog.cabal, before running `stack ghci`?

**Comment by eckyputrady** [comment]
Running `stack build` before running `stack ghci` fixed it for me. 
Didn't expect that I have to run `stack build` first.

Thanks! :)

**Comment by chrisdone** [comment]
I think there needs to be an implicit `stack build` before running `stack ghci`.

**Comment by DanBurton** [comment]
:+1: @chrisdone, at least, stack should install dependencies before it fires up ghci.
