### ISSUE TITLE
Stack REPL can't find environment variables

### ISSUE THREAD

**Issue by jgertm** [commercialhaskell/stack#4487]
### General summary/comments (optional)

When running `stack repl`, I cannot access environment variable that are set in the shell from which I launched `stack repl` via `System.Environment.getEnv`.

### Steps to reproduce

```bash


> export FOO=bar

> echo $FOO
bar

> ghci
[...]
λ> :m System.Environment
λ> getEnv "FOO"
"bar"

 > stack repl
[...]
Prelude> :m System.Environment
Prelude System.Environment> getEnv "FOO"
*** Exception: FOO: getEnv: does not exist (no environment variable)
```

### Expected

Same behavior as with `ghci`, i.e.
```
Prelude System.Environment> getEnv "FOO"
"bar"
```

### Actual

Cannot find the environment variable in the REPL

```
Prelude System.Environment> getEnv "FOO"
*** Exception: FOO: getEnv: does not exist (no environment variable)
```

Other environment variables are available:

```
Prelude System.Environment> getEnv "HOME"
"/home/tjger"
```

### Stack version

```
> which stack
/home/tjger/.local/bin/stack

> stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1

> uname -a
Linux bs 4.14.90 #1-NixOS SMP Fri Dec 21 13:13:19 UTC 2018 x86_64 GNU/Linux
```

### Method of installation

- first installed via NixOS to `/nix/store`
- updated to latest version via `stack upgrade` to `~/.local/bin`

**Comment by qrilka** [comment]
@jgertm by default Stack uses pure Nix mode (and Nix mod is enabled by default on NixOS) - see https://docs.haskellstack.org/en/stable/nix_integration/#the-nix-shell
regarding keeping `$HOME` see `nix-shell` [docs](https://nixos.org/nix/manual/#sec-nix-shell) :
```
--pure
  If this flag is specified, the environment is almost entirely cleared before the
  interactive shell is started, so you get an environment that more closely
  corresponds to the “real” Nix build. A few variables, in particular HOME, USER
  and DISPLAY, are retained. Note that ~/.bashrc and (depending on your Bash
  installation) /etc/bashrc are still sourced, so any variables set there will
  affect the interactive shell.
```

As a way around that you could try using `--no-nix-pure`

**Comment by jgertm** [comment]
Thanks @qrilka, that fixed it!
