### ISSUE TITLE
Rebuilding dependency at every build

### ISSUE THREAD

**Issue by buggymcbugfix** [commercialhaskell/stack#4490]
Every time I run stack build on my project I get the following

~~~
pretty-show-1.7: unregistering
pretty-show-1.7: configure
pretty-show-1.7: build
pretty-show-1.7: copy/register
~~~

I think at some point I did stack install pretty-show (outside of my current project), but I tried removing the ~/.stack dir and this didn't go away.

Any ideas why this gets rebuilt every time?

(First asked on [StackOverflow](https://stackoverflow.com/questions/54031085/stack-keeps-rebuilding-dependency-at-every-build).)

**Comment by qrilka** [comment]
@buggymcbugfix did you try cleaning project Stack directory e.g. with `stack clean --full`? Do you run `stack build` with the same flags? Do you get any other packages unregistered before `pretty-show`? One possible way to get to this situation is to have some dependency of `pretty-show` itself getting rebuilt for some reason. Did you try to minimize the problem? E.g. does it work for a simple project with only `pretty-show` in its dependencies?

**Comment by buggymcbugfix** [comment]
I'm trying to produce a minimal repro for this, but getting this strange error:

```~/temp ✔︎ stack new --param resolver:lts-12.10 --param category:test  pretty-test

Downloading template "new-template" to create project "pretty-test" in pretty-test/ ...
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- pretty-test/

Selecting the best among 15 snapshots...

Didn't see HsYAML-0.1.1.3@sha256:de79642d13fafd65f301b03fdc0284130943bf8b6e83c47e3c8bb851a3f226b5,3853 in your package indices.
Updating and trying again.
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                Downloading timestamp                                                           No updates to your package index were found                                     Update complete                                                                 Unable to load cabal files for snapshot

----
Deleting cached snapshot file: /Users/vl200/.stack/build-plan/lts-13.2.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new
----

The following package identifiers were not found in your indices: HsYAML-0.1.1.3@sha256:de79642d13fafd65f301b03fdc0284130943bf8b6e83c47e3c8bb851a3f226b5,3853
Possible candidates: HsYAML-0.1.0.0, HsYAML-0.1.1.1, HsYAML-0.1.1.0, HsYAML-0.1.1.2.```

**Comment by qrilka** [comment]
I guess you use `stack new` here? What Stack version do you use? Could you share `pretty-test` project?
`HsYAML-0.1.1.3` is in LTS-13.2

**Comment by buggymcbugfix** [comment]
```
$ stack --version
Version 1.9.1, Git revision f9d0042c141660e1d38f797e1d426be4a99b2a3c (6168 commits) x86_64 hpack-0.31.0
```

```
$ tree pretty-test/
pretty-test/
├── ChangeLog.md
├── LICENSE
├── README.md
├── Setup.hs
├── app
│   └── Main.hs
├── package.yaml
├── pretty-test.cabal
├── src
│   └── Lib.hs
└── test
    └── Spec.hs
```

It seems to be missing the `stack.yaml` file.

**Comment by qrilka** [comment]
Sure it's missing it -  Stack could get a proper one but the question is how did you get `HsYAML` as a dependency, did you just run `stack new pretty-test new-template`? Neither 1.9.3 nor 1.9.1 give me any errors, e.g. see https://gist.github.com/qrilka/4ba6ea2bb6fb22f1d95096751846f9be
If you just want to work on reproducing the issue you could use use something like "resolver: lts-13.2" as `stack.yaml` and post details about `stack new`+`HsYAML` as a separate issue

**Comment by buggymcbugfix** [comment]
I have no idea why, but I can't reproduce it anymore. Will close this issue for now. Thank you for your help.

**Comment by buggymcbugfix** [comment]
Hm, after upgrading to `lts-12.26` now I get this strange behaviour of `pretty-show-1.7` being built at every `stack build`. When I make a new stack project from scratch, however, this doesn't happen, so unfortunately I can't provide a minimal repro.

**Comment by snoyberg** [comment]
Can you upgrade to 1.9.3 and try again? Can you include verbose logs?

**Comment by buggymcbugfix** [comment]
This has stopped happening again. I have no idea why. I have upgraded and will reopen this with verbose logs if it happens again.
