### ISSUE TITLE
stack path should ignore ghc-options

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/stack#4501]
### General summary/comments (optional)

`stack path` should take and silently ignore `--ghc-options`, so that it's safe to globally modify the behavior of Stack by setting, e.g. `STACK_ARGS="--ghc-options -Werror --docker -j 4"`.

### Steps to reproduce

* Create a new Stack project.
* Set `STACK_ARGS="--ghc-options -Werror --docker -j 4"`.
* Run `stack $STACK_ARGS build`.
* Run `stack $STACK_ARGS path --local-install-root`.
* Set `STACK_ARGS="--docker -j 4"` and run `stack $STACK_ARGS path --local-install-root` again.

### Expected

`stack path` should succeed both times, ignoring the irrelevant options `-j` and `--ghc-options`.

### Actual

`stack path` fails with `Invalid option` when called with `--ghc-options` but accepts `-j` with no issue.

```
$ stack --ghc-options -Werror --docker -j 4 path --local-install-root --verbose 
Invalid option `--ghc-options'

Usage: stack [--help] [--version] [--numeric-version] [--hpack-numeric-version]
             [--docker*] [--nix*] ([--verbosity VERBOSITY] | [-v|--verbose] |
             [--silent]) [--[no-]time-in-log] [--stack-root STACK-ROOT]
             [--work-dir WORK-DIR] [--[no-]system-ghc] [--[no-]install-ghc]
             [--arch ARCH] [--ghc-variant VARIANT] [--ghc-build BUILD]
             [-j|--jobs JOBS] [--extra-include-dirs DIR] [--extra-lib-dirs DIR]
             [--with-gcc PATH-TO-GCC] [--with-hpack HPACK]
             [--[no-]skip-ghc-check] [--[no-]skip-msys] [--local-bin-path DIR]
             [--[no-]modify-code-page] [--[no-]allow-different-user]
             [--[no-]dump-logs] [--resolver RESOLVER] [--compiler COMPILER]
             [--[no-]terminal] [--color WHEN] [--terminal-width INT]
             [--stack-yaml STACK-YAML] COMMAND|FILE
```

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
```

### Method of installation

* Upgraded via `stack upgrade`, originally via `brew`.

**Comment by qrilka** [comment]
flag `--ghc-options` is only available for `stack build`, `stack script` and `stack ghci`, why should other commands accept flags which are not defined for them?

**Comment by koterpillar** [comment]
I would like to set all the appropriate Stack flags in the build script depending on the build environment, and then call every command with the lot.

However, fair enough, this is a lazy use case, in that case should `-j` be accepted?

**Comment by dbaynard** [comment]
Can you put the options behind flags in the package you're building itself?

**Comment by snoyberg** [comment]
Closing, we will not be making this change.
