### ISSUE TITLE
Custom setup hooks being ignored.

### ISSUE THREAD

**Issue by Magicloud** [commercialhaskell/stack#4505]
### General summary/comments (optional)
Please checkout my project Magicloud/cairo-core. There are some logic in Setup.hs to generate code. The logic works with `stack build` and `cabal v2-haddock`. But `stack haddock` seems ignoring the change on Render.hs.

### Steps to reproduce

Get the repo, build and haddock with stack and cabal.

### Expected

- Methods in modules like Graphics.Cairo.Drawing.Cairo are all liftIO-ed.

- Graphics.Cairo.Render exports a bunch of wrapped methods like `save`, `restore`.

### Actual

- `stack build` works.
  One thing to notice is that, when another executable depends on cairo-core, if I use github in extra-deps, it seems working. If I use local path in extra-deps, the change to Render.hs misses as well. Not sure this is related to main issue.

- `stack haddock` misses changes to Render.hs

- `cabal v2-build` works

- `cabal v2-haddock` works

### Stack output
[stack.log](https://github.com/commercialhaskell/stack/files/2754827/stack.log)

### Stack version

1.9.3

### Method of installation

Updated via old version of stack.

**Comment by Magicloud** [comment]
At first, I thought `stack haddock` uses different path than cabal, so my changes to Render.hs worked but not affecting haddock. But actually, after `rm .stack-work -r; stack haddock`, there is only one Render.hs with the same path as `stack build`, which content is not "changed".

**Comment by Magicloud** [comment]
About the extra-deps thing mentioned, seems like it is also an issue with stack.

I just built cairo-core and some tool using it via cabal.project, and worked.

But same libs and tools building by stack, Render.hs missed a lot of things.

**Comment by Magicloud** [comment]
I found it. The logic bug in my code and how Cabal handles unchanged source.

**Comment by nh2** [comment]
@Magicloud Great! Should we close the issue?

**Comment by Magicloud** [comment]
Ah, sorry, I thought I closed.
