### ISSUE TITLE
almost all stack actions result in SQLite error ...

### ISSUE THREAD

**Issue by silky** [commercialhaskell/stack#4519]
`stack build`, `stack ghci`, `stack upgrade ...` all fail ... it's a reasonably unfortunate situation.

i'm running the latest from master:

```
07:02 PM noon ∈ ~ ♫ stack --version
Version 1.10.0, Git revision ac20e0da239d2e3f6a7cb4bb67ea33b2a7c95849 x86_64 hpack-0.31.1
```

most unfortunately, it also affects `stack upgrade`:

```
07:02 PM noon ∈ ~ ♫ stack upgrade  
SQLite3 returned ErrorConstraint while attempting to perform step: FOREIGN KEY constraint failed
```

and when running again:

```
07:02 PM noon ∈ ~ ♫ stack upgrade
SQLite3 returned ErrorBusy while attempting to perform step: database is locked
```

( as an aside, i feel like the master branch is much more unstable in the last 6 months or so; i used to upgrade all the time; now, whenever i do i hit some weird bug. maybe the "stack upgrade --git" option could hit a more stable branch, if master isn't stable anymore? )

**Comment by snoyberg** [comment]
We already have a flag that lets you specify which branch to clone.
