### ISSUE TITLE
haddock forces rebuild of empty packages

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#452]
Steps:

1. Run `stack haddock` in the `http-client` repo (as an example)
2. When it succeeds: run it again

Expected: nothing happens

Actual: it rebuilds transformers-compat (presumably because there are no modules in that package), and then rebuilds everything that depends on it

**Comment by manny-fp** [comment]
@snoyberg Fix on master.

**Comment by snoyberg** [comment]
Confirmed, nice
