### ISSUE TITLE
High CPU usage on Mac OS when building with stack

### ISSUE THREAD

**Issue by prokolyvakis** [commercialhaskell/stack#4522]
Hello,

I have made a fresh install of Haskell Platform on Mac OS Mojave. After that, I tried to build various different projects though stack, however, I noticed an extremely high CPU usage. Specifically, when I allowed parallelism during the building process the whole system got stack and I had to manually kill it. I also checked to install with `cabal new-install` and the behavior was exactly the same.

So finally, I built it with only one thread, where again I noticed an extremely high CPU usage. Nonetheless, I was able to proceed by waiting for a significant amount of time.  I performed this experiment for both cabal and stack. FYI, I used the following commands: `cabal new-install -j1 "project_name"` & `stack build -j1`.

Here are some additional information regarding the different versions of ghc, cabal and stack:

* ghc version: 8.6.3
* cabal-install version: 2.4.1.0
* stack version: Version 1.9.3 

Further information for the Macbook can be found [here](https://support.apple.com/kb/SP703?viewlocale=en_US).

Do you know if it is a common issue with either stack or ghc and if there is a workaround?

Thanks in advance!

**Comment by dbaynard** [comment]
Hi @prokolyvakis, GHC often uses extremely high CPU usage — and both `cabal-install` and `stack` will  use as many threads as they can. This in itself isn't a bug — GHC has a lot to do. But if there's excessive memory use, that would be problematic.

Is it just the CPU use?

**Comment by snoyberg** [comment]
Closing due to lack of response, and likely an upstream issue.
