### ISSUE TITLE
(Code ?) improvement: always use verified downloads

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/stack#4524]
While working on #4515 it was found that `Stack.New` uses `download` and not `verifiedDownload` and the main difference between those is that `download` doesn't tack download progress and thus doesn't check download length as `verifiedDownload` could (with correct callback specified as `progressSink` parameter). Also it looks that `redownload` doesn't include verifications from `verifiedDownload` - it makes sense to make any downloads properly verified.

**Comment by mihaimaruseac** [comment]
I agree with these points, even more so from a security point of view. Not checking download length can result in malicious files being transferred instead.
