### ISSUE TITLE
How to install stack

### ISSUE THREAD

**Issue by rwlock404** [commercialhaskell/stack#4529]
### Stack version

current

### Method of installation

```
curl -sSL https://get.haskellstack.org/ | sh
```

but this fails

```
Loaded plugins: fastestmirror, ovl
ovl: Error while doing RPMdb copy-up:
[Errno 13] Permission denied: '/var/lib/rpm/.rpm.lock'
You need to be root to perform this command.
Installing yum packages failed.  Please run 'yum check-update' and try again.
```

I don't have root on this machine. How can I install Haskell without root access?

**Comment by rwlock404** [comment]
I followed your instructions and modified the `./stack.sh` script

```
@@ -21,7 +21,7 @@
 
 STACK_VERSION="1.9.3"
 HOME_LOCAL_BIN="$HOME/.local/bin"
-DEFAULT_DEST="/usr/local/bin/stack"
+DEFAULT_DEST="$HOME_LOCAL_BIN/stack"
 DEST=""
 QUIET=""
 FORCE=""
```

but I still get

```
Loaded plugins: fastestmirror, ovl
ovl: Error while doing RPMdb copy-up:
[Errno 13] Permission denied: '/var/lib/rpm/.rpm.lock'
You need to be root to perform this command.
Installing yum packages failed.  Please run 'yum check-update' and try again.
```

**Comment by qrilka** [comment]
@rwlock404 there exist a statically linked Stack version for X86_64. You could find it on https://github.com/commercialhaskell/stack/releases Could you try out using it? Just download and extract it somewhere on your $PATH (e.g. `~/.local/bin` if it's a part of $PATH)

**Comment by mihaimaruseac** [comment]
@rwlock404 Yes, you still need root access for the dependencies. Please try the statically linked version that @qrilka mentioned, if that doesn't work then you'll have to get an admin of that workstation to install at least the dependencies for you

**Comment by rwlock404** [comment]
Ok. I've talked to the admins and they want me to give them a list of packages I need installed. Where can I find such a list?

**Comment by rwlock404** [comment]
Thanks! They insist on only installing things provided by the Linux distribution vendor into system-wide folders. I passed on the list and all but gmp-devel was already installed. 

I re-ran the `./stack.sh` script and I still get

```
Loaded plugins: fastestmirror, ovl
ovl: Error while doing RPMdb copy-up:
[Errno 13] Permission denied: '/var/lib/rpm/.rpm.lock'
You need to be root to perform this command.
Installing yum packages failed.  Please run 'yum check-update' and try again.
```

I double checked and all the packages you listed show up as installed.

**Comment by mihaimaruseac** [comment]
Comment the `do_os` line at the end of the script and try running it again. Now it should not try to do any install at all

**Comment by rwlock404** [comment]
Progress!

The project I need to work on needs `resolver: lts-12.16` but `stack build` fails with

```
Downloaded lts-12.19 build plan.    
No setup information found for ghc-8.4.4 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-gmp4'.
Supported versions: ghc-7.8.4, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.2
```

I tried with `lts-12.0` hoping it would use `ghc-8.4.2` but still no luck. I also tried `lts-13.4` which failed with the same error. How come that Stack can't install any LTS for either ghc 8.4 nor ghc 8.6?  Is there an ETA for when these will become available?

**Comment by rwlock404** [comment]
I'm not aware of any prior `system-ghc` setting. I tried your `stack config` operation, but the error message saying that the GHC I need for `lts-12.16` is not supported is still occuring.

**Comment by mihaimaruseac** [comment]
Can you try the following set of commands? They are not related to your project, but just checks

```
$ cd
$ mkdir test
$ cd test
$ stack ghci
```

Let me know what the output of that is and then we'll go from there

**Comment by qrilka** [comment]
It looks like #4161 is related and bindists for that platform are really missing from https://github.com/commercialhaskell/stackage-content/blob/master/stack/stack-setup-2.yaml#L415
I think going with the statically linked Stack should be more promising

**Comment by rwlock404** [comment]
The only command which had output was `stack ghci`

```
No setup information found for ghc-8.6.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-gmp4'.
Supported versions: ghc-7.8.4, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.2
```

**Comment by rwlock404** [comment]
> I think going with the statically linked Stack should be more promising

I downloaded and extracted https://github.com/commercialhaskell/stack/releases/download/v1.9.0.1/stack-1.9.0.1-linux-x86_64-static.tar.gz but it results in the same error message

```
No setup information found for ghc-8.6.3 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-gmp4'.
Supported versions: ghc-7.8.4, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.2
```

**Comment by mihaimaruseac** [comment]
Ok, let's go the statically linked way, seems something is missing from the other one.

When you extracted the tar.gz file, which files you got? Can you post the output of `ls` on the directory you extracted stuff to?

**Comment by mihaimaruseac** [comment]
Since it is now a GHC (lack of availability) issue, I think we can now close this.
