### ISSUE TITLE
Add something like 'stack man'.

### ISSUE THREAD

**Issue by pharpend** [commercialhaskell/stack#453]
I would like to include man pages with my software. Cabal doesn't make this possible (for cabal to add a man page, it would require root access). However, could Stack potentially do this, via a command like 'stack man'? The application maintainer could include a man page via `extra-source-files`, and Stack could bandage yet another sore point in the Haskell workflow.

Just an idea.

**Comment by snoyberg** [comment]
Just to confirm: you're asking for `stack man` to copy man pages to `/usr/share/man`, based on the values in `extra-source-files`? What would the criteria be for determining if a file should be treated as a man file or not?

**Comment by radix** [comment]
This sounds like a dangerous path to tread -- Stack is a developer's tool, but this is a clear move toward "system package manager", which is a VERY scary domain to be in :)

**Comment by drwebb** [comment]
I agree, this would seem like stack overstepping it's bounds as a build tool.

**Comment by snoyberg** [comment]
Overall, I concur. I just wanted to confirm that I understood the request first. Since it's a bit ambiguous, I was hoping @pharpend could clarify.

**Comment by rvion** [comment]
I agree, I would -1 this because , amongst all
 - it doesn't have any link with haskell
 - it doesn't make sense on windows or some possible future arch (ios, andriod)
 - it doesn't take advantage of core stack features
 - it doesn't use any specific stack folders.

**Comment by pharpend** [comment]
@snoyberg No, not talking about `/usr/share/man`, I should have been more clear. (I wrote this at 11 PM last night, so I was quite tired).

Perhaps, in `stack.yaml`, there would be a field called `man-pages`, or something like that, where the developer could specify man pages.

**Again, Stack would not be messing with the operating system**

Instead, Stack would keep the man pages in something like `.stack-work/through/the/ghc/version/man/foo.1`. The user could then **view** the manual pages with `stack man`.

**Comment by drwebb** [comment]
@pharpend 
So you are looking for something like a command similar to `MANPATH=<dist-dir_manpath> man <manpage>`?

**Comment by pharpend** [comment]
On Tue, Jun 30, 2015 at 10:35:08AM -0700, Tristan Webb wrote:
> So you are looking for something like a command similar to
> `MANPATH=<dist-dir_manpath> man <manpage>`?

Essentially, yes. Stack already modifies `$PATH`, so I don't see how
modifying `$MANPATH` would be an overstep.

Peter Harpending

**Comment by snoyberg** [comment]
@pharpend I think general consensus is that this is too special-case to be handled well by stack.
