### ISSUE TITLE
Moving a stack directory tree

### ISSUE THREAD

**Issue by dgh1000** [commercialhaskell/stack#4532]
I couldn't understand your example, for one thing I didn't realize those were commands on a command line. They looked like headings, and I've never seen a command-line with a lambda symbol. In the future please provide at least a bare minimum of context.

So I looked closer, and it turns out it's *NOT* the same as what I posted. There is a difference, which is that my A and B don't share the same parent directory. Does that matter?

**Comment by mihaimaruseac** [comment]
No, it doesn't
