### ISSUE TITLE
ls dependencies --tree fails when targets are provided

### ISSUE THREAD

**Issue by wiz** [commercialhaskell/stack#4552]
### General summary/comments (optional)

I've built a stack from the git master and tried to test the thing.

### Steps to reproduce

```bash
$ stack ls dependencies aeson --tree
```

### Expected

Dependency tree for `aeson` package.

### Actual

```
Packages
Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at libraries/containers/Data/Map/Internal.hs:610:17 in containers-0.6.0.1:Data.Map.Internal
```

### Stack version

```bash
$ stack --version
Version 1.10.0 (6854 commits) x86_64 hpack-0.31.1
```

### Method of installation

* git clone https://github.com/commercialhaskell/stack && stack install --resolver snapshot-nightly.yaml

**Comment by mattaudesse** [comment]
Thanks for reporting this @wiz

**Comment by dbaynard** [comment]
The correct behaviour is not defined anywhere. Having investigated (not on master): without `--tree`, it only lists dependencies of the target. However, if run outside a project, the command will list nothing — and will error if there's no target.

@wiz can you please check (and post) the outputs of the following variants?

1. With and without `--tree`,
2. In and not in a project directory (i.e. a directory with a `stack.yaml` in it, or an ancestor, directory), and
3. With and without a target.

(i.e. 8 commands)

The PRs introducing `--tree` are #4339, #4413. @akshaymankar can you take a look?

**Comment by dbaynard** [comment]
> We should probably define behaviour in these situations

I'd like to hear @wiz's thoughts.

For me: If we call `stack build TARGET` outside of a project, stack builds the targets. So I'd argue `stack ls dependencies TARGET` ought to display the dependencies of the target… but as it would be good for `ls dependencies` not to need network access, I would rather see it fail (gracefully) if this is not possible.

@borsboom is probably the person to ask, here.

**Comment by wiz** [comment]
@dbaynard Sorry for the delay. I collected the outputs you've mentioned: https://gist.github.com/wiz/94a9613005c4835416dbaf0aaf87ed67

**Comment by wiz** [comment]
On a related note, `--tree` ignores the `--prune` option.

**Comment by wiz** [comment]
It appears I tried to use `ls dependencies` for something it wasn't designed for - exploring dependencies of targets, not the stack project as a whole :thinking:

**Comment by dbaynard** [comment]
Thanks, @wiz. That's helpful (I like how you found some more bugs in the process).

> stack ls dependencies aeson --tree

So you ran this from the `stack` source directory?

> On a related note, `--tree` ignores the `--prune` option.

We should fix that, too.

> It appears I tried to use `ls dependencies` for something it wasn't designed for - exploring dependencies of targets, not the stack project as a whole 🤔

To be fair, it should be clear in the documentation. Thanks for pointing this out.

**Comment by wiz** [comment]
> So you ran this from the `stack` source directory?

Yep, in a project directory. `stack  new`, `cd`, add aeson dependency, run `ls`.
