### ISSUE TITLE
Redirecting output of `--exec` command

### ISSUE THREAD

**Issue by tomasaschan** [commercialhaskell/stack#4556]
I'm running my program with `stack build --file-watch --exec`, but I can't figure out how to redirect its output. If I try

    stack build --file-watch --exec "my-prog with some-args" > output.txt

then the output of `stack` is of course also sent there, and the output of subsequent runs of my program are appended to the file, leaving old runs there.

If I try

    stack build --file-watch --exec "my-prog with some-args > output.txt"

then `>` and `output.txt` are also sent as arguments to `my-prog`, instead of used to redirect stdout.

This applies to `stack` 1.9.3, tested both on Windows (PowerShell) and on Ubuntu (Bash).

**Comment by tomasaschan** [comment]
Ah, yes - that works, of course. Thanks!

It would be nice if this was a special case that stack could handle, but I do understand that there are _very_ many file redirection variants supported by various shells, so choosing a (sub)set of them to implement is probably infeasible.

**Comment by dbaynard** [comment]
This belongs in the docs. PRs welcome!

**Comment by tomasaschan** [comment]
Coming back to this, I can't get the options right for `stack build --exec`... What would the corresponding incantation be to redirect output in that case?

**Comment by snoyberg** [comment]
My recommendation in this case would be to put the calls, together with any output redirection, into a separate shell script and `--exec` that script. I find it too complicated myself to deal with all of the details of shell escaping that ensue otherwise.

**Comment by snoyberg** [comment]
I think my previous comment addresses this issue, closing.
