### ISSUE TITLE
stack downloads github refs in snapshot.yaml file to local .stack-work

### ISSUE THREAD

**Issue by davidspies** [commercialhaskell/stack#4569]
### General summary/comments (optional)

When using a `snapshot.yaml`, it seems to download github refs to the local `.stack-work` directory every time I do a fresh build. These should only be downloaded once and go in the snapshot, not in the local `.stack-work`

### Steps to reproduce

1. Create a `snapshot.yaml` file with a github ref such as
```
$ cat > snapshot.yaml
resolver: lts-13.6

name: my-snapshot

packages:
- git: https://github.com/commercialhaskell/stack.git
  commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
```

2. `stack new example --resolver=../snapshot.yaml`

3. `cd example`

4. `stack build`
```
Cloning e7b331f14bcffb8367cd58fbfc8b40ec7642100a from https://github.com/commercialhaskell/stack.git
Cloning into '/Users/davidspies/mwe/example/.stack-work/downloaded/BMfD3szzs-Km'...
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (157/157), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 45984 (delta 92), reused 95 (delta 60), pack-reused 45827
Receiving objects: 100% (45984/45984), 15.41 MiB | 6.21 MiB/s, done.
Resolving deltas: 100% (32431/32431), done.
...
```
5. `stack clean --full`
6. `stack build`
```
Cloning e7b331f14bcffb8367cd58fbfc8b40ec7642100a from https://github.com/commercialhaskell/stack.git
Cloning into '/Users/davidspies/mwe/example/.stack-work/downloaded/BMfD3szzs-Km'...
remote: Enumerating objects: 157, done.
remote: Counting objects: 100% (157/157), done.
remote: Compressing objects: 100% (94/94), done.
remote: Total 45984 (delta 92), reused 95 (delta 60), pack-reused 45827
Receiving objects: 100% (45984/45984), 15.41 MiB | 6.40 MiB/s, done.
Resolving deltas: 100% (32431/32431), done.
...
```

### Expected

On step 4, it should download `commercialhaskell/stack` to somewhere inside my home `.stack` directory, not the local `.stack-work` directory
On step 6, it shouldn't have to download it at all because it already did.

### Actual

I had to wait for `commercialhaskell/stack` to download twice (or rather every time I run `stack clean --full` and for every project I use this snapshot with).

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by dbaynard** [comment]
Hi @davidspies thanks for the report. This is a pet peeve of mine, and I often run the following command when there's no `.stack-work` directory:

```sh
rm -rf .stack-work && mkdir -p .stack-work && ln -sv ~/.stack/global-project/.stack-work/downloaded .stack-work
```

Technically this could cause problems (if you have multiple repos checked out at different commits) but I _think_ stack avoids it.

This was reported in #3551. That issue should have appeared below the title bar when you were typing?

The next version of stack will resolve it; I'd recommend continuing with the release version and using the workaround for now, though, rather than using the master branch, as there have been some major changes there.
