### ISSUE TITLE
Setup windows CI (appveyor ?)

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stack#457]
How about setting up windows CI with appveyor ?

related to https://github.com/commercialhaskell/stack/pull/442#discussion_r33525689 (@mgsloan, @snoyberg)
[Appveyor](http://www.appveyor.com/)  is a Continuous Delivery service for Windows

To see an example badge: https://ci.appveyor.com/project/neovim/neovim/branch/master

**Comment by snoyberg** [comment]
It's a great idea. Would you be able to spearhead this?

**Comment by rvion** [comment]
I can give it a try, sure :)

**Comment by rvion** [comment]
@snoyberg It seems like I need to have access to the organisation to set this up

**Comment by snoyberg** [comment]
Welcome to the stack team. Please be considerate :)

**Comment by rvion** [comment]
Thanks, I will :)

**Comment by rvion** [comment]
I got here:

![screen shot 2015-06-30 at 15 57 30](https://cloud.githubusercontent.com/assets/2150990/8432494/c3cff0bc-1f40-11e5-942f-66f2dd1da723.png)

and reproduced https://github.com/commercialhaskell/stack/issues/393 on server 2012

**Comment by snoyberg** [comment]
Thanks for getting a repro on this. Based on previous testing, the problem
here is with the network library, not stack itself. If I provided you with
some sample programs, you think you could get them running on appveyor as
well?

**Comment by rvion** [comment]
Yes, I think.
Setting up an other appveyor project just running binaries should be simple. 

Few notes:
 - Current appveyor setup experimentation for stack is here: https://github.com/rvion/stack/pull/2/files
 - When US wakes up, appveyor free builds delay increase to ~10/20 minutes
 - I'm on a mac, without much experience on windows shell scripting.

**Comment by snoyberg** [comment]
Can you try compiling and running the following program:

```haskell
{-# LANGUAGE OverloadedStrings #-}
import Network
import qualified Data.ByteString as S

main :: IO ()
main = do
    h <- connectTo "www.stackage.org" $ PortNumber 80
    S.hPut h "GET / HTTP/1.1\r\nHost: www.stackage.org\r\n\r\n"
    S.hGetSome h 4096 >>= print
```

Only depends on base, bytestring, and network.

**Comment by snoyberg** [comment]
Is there some kind of badge or the like that we should add to the project for Windows CI info?

Other than that, this seems implemented, closing. Thanks!

**Comment by mboes** [comment]
@snoyberg closed by mistake? I don't see any appveyor.yaml file in the master branch. And the bug identified by @rvion above means that CI fails pretty consistently across multiple versions of the base image: https://ci.appveyor.com/project/rvion/stack-gwnse/branch/appveyor.

**Comment by rvion** [comment]
The script that builds stack on appveyor uses an old stack binary, downloaded from a temporary server I set up back then. Even if the stack executable is supposed to be cached, appveyor may be failing because of 
  - not beeing able to bootstrap stack.exe to build stack
  - stack exe being too old
  - problem still being there

Script is here: https://github.com/rvion/stack/pull/2/files

I'll rebase my branch on master, and fix the hosting later.

**Comment by rvion** [comment]
actually, it seems to be the stack.exe being used to build stack that just fails because of the crashing network lib on windows.

@snoyberg is the new windows build still having problems due to network lib ?

**Comment by snoyberg** [comment]
I believe using the 64 bit binary should work, can you try that out?

**Comment by rvion** [comment]
yep, will do soon

**Comment by snoyberg** [comment]
Any progress here?
