### ISSUE TITLE
Document interaction with stackage-content

### ISSUE THREAD

**Issue by dbaynard** [commercialhaskell/stack#4570]
It would be helpful to explain this in terms of stack's platform support. ~~I'm not yet sure where in the documentation it ought to go.~~ probably in *install_and_upgrade.md*.

Related:
- #3024
- commercialhaskell:stackage-content@3bbfe079501e9b1d47f8737ebbb5ecded8c5a780

**Comment by mpilgrem** [comment]
I am closing this issue because:
* `setup-info` and `setup-info-locations` document their defaults: https://docs.haskellstack.org/en/stable/yaml_configuration/#setup-info; and
* forthcoming `global-hints-location` will document its default (#6491)
