### ISSUE TITLE
Support cabal.project files

### ISSUE THREAD

**Issue by dbaynard** [commercialhaskell/stack#4571]
Cabal now has [`cabal.project`](https://cabal.readthedocs.io/en/latest/nix-local-build.html#configuring-builds-with-cabal-project) files, which overlap with some of the features of `stack.yaml` files. It would be good for stack to be able to convert between `stack.yaml` and `cabal.project` files.

-   [stack2cabal](https://hackage.haskell.org/package/stack2cabal) can do one direction.
-   [This article by @fommil discusses further details](https://medium.com/@fommil/why-not-both-8adadb71a5ed).

**Comment by snoyberg** [comment]
Would you be OK if I moved this to the wishlist?

**Comment by dbaynard** [comment]
Absolutely — it seems like exactly the right place for it. Thanks!

**Comment by snoyberg** [comment]
Awesome, added.
