### ISSUE TITLE
No package revision found for: PackageName "ghc"

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#4572]
I am not sure if the following would be considered to be a `stack` issue or not. It flows from https://github.com/haskell/haskell-ide-engine/issues/1074

The Haskell IDE Engine (HIE) builds with stack 1.9.3 under GHC 8.6.2. Command `stack --stack-yaml=stack-8.6.2.yaml ls dependencies` includes in its output:
```
ghc mkVersion [8,6,2]
```
`ghc-8.6.2` is the library that comes with GHC 8.6.2 (https://downloads.haskell.org/~ghc/8.6.2/docs/html/users_guide/8.6.1-notes.html#included-libraries)

However, the versions of `ghc` on Hackage are limited to 8.2.1, 8.2.2, 8.4.1, 8.4.3, and 8.6.1 (https://hackage.haskell.org/package/ghc).

In trying to build with with `stack --version` `Version 1.10.0, Git revision 48f4befb67860a24fc8c3310e6d55ace9fd35dfe (dirty) (6868 commits) x86_64 hpack-0.31.1`, the command:
```
stack --stack-yaml=stack-8.6.2.yaml install
```
yields error:
```
No package revision found for: PackageName "ghc"
CallStack (from HasCallStack):
  error, called at src/Stack\Build\ConstructPlan.hs:434:42 in stack-1.10.0-Gyq3czmxkWV9B1iWoXQn3F:Stack.Build.ConstructPlan
```
That reference to `Stack.Build.ConstructPlan.hs` leads to function `getHackagePackageVersions`.

My own assumption is that either (1) `stack` should 'know' that package `ghc` 'comes with' GHC, even if it is not on Hackage; or (2) that all versions of `ghc` that come with GHC ought to be on Hackage.

**Comment by dbaynard** [comment]
Hi @mpilgrem, try the current tip of the `master` branch — there was a PR last week which addressed how stack handles these packages.

Also from the version you've given, it looks like you've made changes. If this doesn't resolve the problem, please indicate what they are.

**Comment by mpilgrem** [comment]
That resolved the problem.
