### ISSUE TITLE
Pass `--host` option to `stack hoogle --server`

### ISSUE THREAD

**Issue by dspies-leapyear** [commercialhaskell/stack#4574]
There doesn't seem to be a way to pass the `--host` option to `stack hoogle --server`

I'd like to be able to access it from another machine besides localhost.

**Comment by dspies-leapyear** [comment]
Ok, I figured it out

It's
`stack hoogle -- server --host=<ip> --local`

That's not clear from documentation. `--local` does the _opposite_ of what it says it does and there's no example of using `stack hoogle -- server` (with the whitespace between the `--` and the `server`) anywhere.

**Comment by dbaynard** [comment]
Thanks for reporting, and investigating @dspies-leapyear.

Fancy making a PR?

-   Fixing the help text for `hoogle` and the docs, where needed.
-   Correcting the behaviour for `--local` (what should it do?)

**Comment by dspies-leapyear** [comment]
Added to hoogle help text in https://github.com/commercialhaskell/stack/pull/4575
Unfortunately the `--local` thing is really more of a `hoogle` thing than a `stack` thing.

**Comment by dspies-leapyear** [comment]
Created an issue here: https://github.com/ndmitchell/hoogle/issues/286

**Comment by dbaynard** [comment]
> It's `stack hoogle -- server --host=<ip> --local`

What exact command did you try to do originally?

**Comment by snoyberg** [comment]
PR merged, closing. Thanks!
