### ISSUE TITLE
Document using Travis in sudo:false case WAS: Add stack ubuntu repository to travis whitelists

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#458]
I could do it myself, but it would be better if the request will be from stack maintainers

http://docs.travis-ci.com/user/apt/

---

Rationale: if `stack` could be installed thru travis apt plugin, we could use container based travis builds, which would allow caching (of `.stack/`) for public travis jobs. That will save a lot of build time!

**Comment by snoyberg** [comment]
I haven't had a chance to look into this, but I really like the idea. Where would such a request be made? Pinging @mboes who's done similar work already.

**Comment by mboes** [comment]
Request submitted: https://github.com/travis-ci/travis-ci/issues/4169

@phadej in the meantime, you can install stack locally. It works great with Travis containers. See https://github.com/haskell-distributed/cloud-haskell/blob/master/.travis.yml for an example.

**Comment by phadej** [comment]
@mboes thanks for the tip!

**Comment by phadej** [comment]
After a bit of tweaking got running on two different ghc: https://github.com/futurice/fum2github/blob/master/.travis.yml

To make travis story even more complete (for stack), this is vital: https://github.com/travis-ci/travis-ci/issues/4173

**Comment by snoyberg** [comment]
Once this is all working, I think we should have a wiki page dedicated to using stack for Travis. This is really great stuff.

**Comment by snoyberg** [comment]
@phadej Any progress on documentation for this?

**Comment by phadej** [comment]
@snoyberg I'll come back to this early next week. Seems that travis issues haven't progressed, so I'll write down what we can do currently.

**Comment by phadej** [comment]
Added the page: https://github.com/commercialhaskell/stack/wiki/Travis. Please comment and amend.

**Comment by snoyberg** [comment]
Looks good, thanks! We can always continue editing as things change (as I'm sure we will), so I don't think it's worth keeping this issue open.
