### ISSUE TITLE
Also provide executables in releases

### ISSUE THREAD

**Issue by rvion** [commercialhaskell/stack#460]
I would appreciate to be able to download executables directly from release page, in addition to archives.

### pros: 
 - **easier**: some people don't know how to unzip with command line only: [xkcd: tar](https://xkcd.com/1168/)
 - **more transparent**: as of now, the user don't really know what to expect in the archive. an executbale ? several files ? 
 - **cleaner**: no need to remove the archive
 - **faster**: "right click, save as.. > choose right location > click ok > done" no extra command to unzip, or remove executable. Useful for demo-ing on other people's pc, or to shorten one-liner install script

I know that above arguments apply mostly for non experts users only. One can  `curl -sSL | gunzip`, but point is that some people may fear complexity when seeing archives, and may move away from stack just for that

ping https://github.com/commercialhaskell/stack/issues/324

### cons: 
 - **bigger file**: more brandwidth needed to download

**Comment by snoyberg** [comment]
Big -1: this will lead to a lot of confusion for users. "Do I need to download the .exe or the .zip?" I've never met a developers who couldn't figure out how to unzip a file on their platform.

**Comment by rvion** [comment]
My initial idea for this proposal was to replace archives by executable only.
@snoyberg Can you explain why do you to prefer archive over executable ?

**Comment by snoyberg** [comment]
Because it wastes bandwidth. Just about every developer I've ever met would prefer to decompress a file rather than download something 4 times the size.

**Comment by rvion** [comment]
For small files, I mostly disagree.

This being said, I just took a look at stack executable size on my mac:
5mb compressed, 30 uncompressed => I understand your point better.

**Comment by drwebb** [comment]
Also Rémi, tar archives allow you to set permissions (i.e `chmod 777`) so the one less command you need to type doesn't really apply.

**Comment by rvion** [comment]
Thanks for those precisions :)
I'll update the original post to add your reason on cons list.
I'll also add a few other thought I had afterwise.
