### ISSUE TITLE
`stack setup` (with flag system-ghc: false) fails sanity check on CentOS 6

### ISSUE THREAD

**Issue by adinapoli** [commercialhaskell/stack#461]
```
$ uname -a
Linux ip-172-31-9-24 2.6.32-504.16.2.el6.x86_64 #1 SMP Tue Mar 10 17:01:00 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
```

After installing latest stack (from HEAD), I ran `stack setup` in a project configured to NOT use the system GHC:

```
$ stack setup
Downloaded lts-2.16 build plan.
Caching build plan
Downloading package index from http://our-private-hackage/00-index.tar.gz
Populated index cache.
Downloaded ghc-7.8.4.
Installed GHC.
The GHC located at /home/alfredo/.stack/programs/x86_64-linux/ghc-7.8.4/bin/ghc failed to compile a sanity check. Please see:

    https://github.com/commercialhaskell/stack/wiki/Downloads

for more information. Exception was:
Running /home/alfredo/.stack/programs/x86_64-linux/ghc-7.8.4/bin/ghc /tmp/stack-sanity-check3899/Main.hs exited with ExitFailure 1
[1 of 1] Compiling Main             ( /tmp/stack-sanity-check3899/Main.hs, /tmp/stack-sanity-check3899/Main.o )
Linking /tmp/stack-sanity-check3899/Main ...
/home/alfredo/.stack/programs/x86_64-linux/ghc-7.8.4/lib/ghc-7.8.4/integer-gmp-0.5.1.0/libHSinteger-gmp-0.5.1.0.a(gmp-wrappers.o): In function `cjw_info':
(.text+0x2e4b): undefined reference to `__gmpz_powm_sec'
collect2: ld returned 1 exit status
```

I also have all the required deps installed, according to `yum`:

```
$ sudo yum install perl make automake gcc gmp-devel
Loaded plugins: amazon-id, rhui-lb, security
Setting up Install Process
Package 4:perl-5.10.1-136.el6_6.1.x86_64 already installed and latest version
Package 1:make-3.81-20.el6.x86_64 already installed and latest version
Package automake-1.11.1-4.el6.noarch already installed and latest version
Package gcc-4.4.7-11.el6.x86_64 already installed and latest version
Package gmp-devel-4.3.1-7.el6_2.2.x86_64 already installed and latest version
Nothing to do
```

What am I doing wrong?

Thanks!
Alfredo

**Comment by dysinger** [comment]
How were you able to bootstrap the stack executable on centos 6, @adinapoli ?

I downloaded the generic linux version & it doesn't work.  Linkage broken.

Next I downloaded binary packages from https://www.haskell.org/ghc/download_ghc_7_8_4 & used cabal 1.20 to bootstrap stack.  It fails to install stack. ExitFailure -9.

So I haven't even gotten to the `stack setup` problem yet.

**Comment by dysinger** [comment]
I was running out of memory.  ghc not being super helpful there as to the reason.

**Comment by dysinger** [comment]
`stack setup` fails for the same reason as "I downloaded the generic linux version & it doesn't work. Linkage broken." above. Centos 6 has way older glibc & gmp libs.

```
bash-4.1# stack setup
Using resolver: lts-2.16 from global config file: /root/.stack/global/stack.yaml
Downloaded ghc-7.8.4.                  
Configuring GHC ...Running /tmp/stack-setup18253/ghc-7.8.4/configure --prefix=/root/.stack/programs/x86_64-linux/ghc-7.8.4/ exited with ExitFailure 1
checking for path to top of build tree... utils/ghc-pwd/dist-install/build/tmp/ghc-pwd: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory
configure: error: cannot determine current directory
```

**Comment by dysinger** [comment]
I'm closing this ticket & opening a new one to provide centos/redhat binaries.

**Comment by snoyberg** [comment]
As a short term workaround I'd recommend using the system installable GHC for now.

**Comment by adinapoli** [comment]
@dysinger yes, that seems a reasonable cause to me - I had to manually symlink /usr/lib64/libgmp.so.3 -> /usr/lib64/libgmp.so.10 hoping to fix things up, that's probably why I'm getting a different error as you are: that missing symbol error is probably the result of the GHC binary expecting a more updated version of libgmp.

@snoyberg  there are different reasons why I do not want to use the system-ghc here, so I'm happy to wait for appropriate ghc/stack binaries for centos6.

I'm here if you guys want me to test anything.

Thanks!
Alfredo

**Comment by manny-fp** [comment]
@adinapoli: See https://github.com/commercialhaskell/stack/issues/465#issuecomment-118434410

**Comment by adinapoli** [comment]
Thanks @manny-fp , it's definitely a start! I will give it a shot on Monday ;)

**Comment by manny-fp** [comment]
Looks like the GHC team has decided to provide gmp4 (libgmp.so.3)-compatible binaries for GHC 7.10.2, and I'm updating stack-setup.yaml (https://github.com/fpco/stackage-content/commit/a163f0acf49fbaba61af72eb8a9fc25fc335077b) to include them in https://github.com/fpco/stackage-content/pull/4.  That means I'm going to plan on releasing stack binaries that support gmp4 as well.
