### ISSUE TITLE
Possible to build test dependencies without running tests?

### ISSUE THREAD

**Issue by dkubb** [commercialhaskell/stack#462]
I am using stack with CircleCI, and I'd like a way to build the test dependencies up-front without actually running the tests. With CircleCI I am caching the build output so that repeated runs are done more quickly. Here is what I am doing:

Setup:

```bash
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C5705533DA4F78D8664B5DC0575159689BEFB442
echo 'deb http://download.fpcomplete.com/ubuntu/precise stable main' | sudo tee /etc/apt/sources.list.d/fpco.list
sudo apt-get update
sudo apt-get install stack -y
```

Build:

```bash
# A snapshot of .stack-work and ~/.stack is restored from a previous run (if any)

stack build --no-terminal --install-ghc --jobs 2
stack test --prefetch --dry-run

# A snapshot of .stack-work and ~/.stack is persisted
```

Test:

```bash
stack test
```

The problem is the `stack test` still goes through a lengthy build process. I would love to be able to do this in the build phase rather than when the tests run.

Also if there's anything else I could improve in my stack usage please let me know.

**Comment by DanBurton** [comment]
:+1: great feature request, not sure if we have it yet.

**Comment by dkubb** [comment]
Originally my assumption was that `stack build` would just build *all* dependencies by default. I was surprised when it didn't.

In the meantime I hacked together something ugly that does compile all the test dependencies:

```bash
stack test --prefetch --dry-run \
  | sed -e '1,/^Would build:/d' -e '/^Would test:/,$d' \
  | cut -d":" -f1 \
  | xargs -I{} stack build {} --no-terminal --jobs 2
```

It seems to work, but is obviously brittle since it will break if the prefetch output changes even slightly.

**Comment by snoyberg** [comment]
That's what we added the --only-snapshot flag for. Check out #387 and #310

**Comment by snoyberg** [comment]
I'm going to close this as unnecessary based on the `--only-snapshot` flag. If there's some issue with this, let's discuss (probably in #387).
