### ISSUE TITLE
Implement program-prefix and program-suffix

### ISSUE THREAD

**Issue by ruomad** [commercialhaskell/stack#4621]
Hello,
Would it be possible to implement in stack.yaml an option to prefix or suffix executables (typically with a version tag) ?
This exists in cabal.project.
Thanks

**Comment by snoyberg** [comment]
A little more information would be appreciated, like motivation for this, link to the documentation for the feature in cabal.project, or description of how this would be used.

**Comment by ruomad** [comment]
OK
As for the motivation, I currently develop a project using stack and git, and need (for testing purposes) to keep the different versions of executables built and installed, so I want to suffix the 4 different executables I'm building with a version suffix. The proposed option would eliminate the need to modify the names of the executables in my package.yaml file each time I am changing version (not a very big burden, obviously, but an error-prone process, if I forget it the build will replace the previous version).
I'm also building different executables based on different flags (eg using a different database backend).

This option does exist in modern cabal configuration, at the new "project" level see : 
[https://www.haskell.org/cabal/users-guide/nix-local-build.html#executable-options](https://www.haskell.org/cabal/users-guide/nix-local-build.html#executable-options)

**Comment by snoyberg** [comment]
I'm weakly -1 on this. It adds complexity to the codebase, lots of points to debate the variables that should be supported, and IMO can be addressed by having multiple separate installation directories (via `--local-bin-path`).

**Comment by snoyberg** [comment]
Closing as wontfix

**Comment by andreasabel** [comment]
@mpilgrem : Is this going to stay a "wontfix"?
Basically, this excludes to use `stack install` in a multi-version environment (e.g. if you want to install several version of Agda using stack).

**Comment by mpilgrem** [comment]
@andreasabel, given your current interest, the short answer is 'No'. However, I'd like to avoid an 'all singing, all dancing' solution. Would the following specification work?

> `stack install --tag-bins` adds the package version to the name of any binaries copied to local-bin.

**Comment by andreasabel** [comment]
I guess in most cases you'd want the version, however, we also use it with custom tags indicating the optimization level.  Folks might also want `-beta` or so.
Some defaulting mechanism to the version would be great, though, as this is the most common case.

Would the following work?
* `--program-suffix=SUFFIX` custom suffix
* `--program-suffix` version suffix
* `--program-suffix=""` clear previously set suffix

UX-wise, I think having the same option name as `cabal` has when possible makes for easier transition.

**Comment by mpilgrem** [comment]
Cabal (the library) also has the `configure --program-suffix` option, so `stack.yaml`:
~~~yaml
snapshot: lts-22.22
configure-options:
  $targets:
  - --program-suffix=-my-suffix
~~~

creates an executable named that way in the `bin` directory in the `stack path --local-install-root`.
