### ISSUE TITLE
Gentoo: 'No information found for ghc-8.6.2' for OS key 'linux64-ncurses6'

### ISSUE THREAD

**Issue by Anrock** [commercialhaskell/stack#4622]
Hello, seeing this error when trying to launch a stack script on Gentoo.

I have system-wide installation of ghc-8.6.4, ncurses-5.9-r101 and ncurses-6.1-r3.
Stack is 1.9.3 installed from [Gentoo Haskell overlay](https://github.com/gentoo-haskell/gentoo-haskell)

Seeing quite a few similar issues here and 8.6.2 being released some time ago - is it generally expected that stack team will release corresponding bindists for reported OS keys or if my OS not explicitly listed as supported in stack guide i should find alternative tool/way?

**Comment by qrilka** [comment]
@Anrock do you have `tinfo` use flag enabled for `ncurses`? On my Gentoo with that flag stack works fine:
```
qrilka@qdesktop ~ $ stack exec --resolver=ghc-8.6.2 -- ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.2
qrilka@qdesktop ~ $ uname -a
Linux qdesktop 4.14.65-gentoo #1 SMP Sat Sep 22 15:19:49 MSK 2018 x86_64 Intel(R) Core(TM) i5-2300 CPU @ 2.80GHz GenuineIntel GNU/Linux
```

**Comment by Anrock** [comment]
@qrilka no, I don't have that flag. I'll check if it helps, thanks

**Comment by Anrock** [comment]
Rebulding `ncurses` with enabled `tinfo` flag fixed this issue.
