### ISSUE TITLE
Cabal error: At least the following dependencies are missing:

### ISSUE THREAD

**Issue by zekzekus** [commercialhaskell/stack#463]
I have a project which includes random package as a build dependency in project.cabal file. i init, setup, build and install the project with stack without any problems. Also i installed hdevtools package again via stack install hdevtools command. 

When i tried to check my module with `hdevtools check Module.hs` or `stack exec -- hdevtools check Mobule.hs` it says: `Cabal error: At least the following dependencies are missing: random -any `

Random installed via stack, hdevtools installed via stack etc. Is this behaviour expected?

**Comment by snoyberg** [comment]
Currently, yes. Check out this thread, where proper stack support for hdevtools is being discussed:

https://groups.google.com/d/msg/haskell-stack/Skfd3QGFzgk/U4Y3rQXg-fQJ

**Comment by snoyberg** [comment]
Since this is known behavior coming from something outside of stack's control that's already being worked on, closing.
