### ISSUE TITLE
Introduce a HasCompiler typeclass

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4639]
Note: naming is up for bikeshedding.

Motivation: there have now been a few bugs introduced—most recently by me—where some piece of code expected `ghc` to be available on the `PATH`, but nothing in the type signature said so. I recommend adding a new typeclass:

```haskell
class HasCompiler env where
  -- not sure if this part is even necessary
  actualCompilerL :: Lens' env ActualCompiler
```

This would be a superclass of `EnvConfig`, and would be placed on all functions that require `ghc` to be in the `PATH`. The one place that will require special handling is within `Stack.Setup` where we construct a new `EnvConfig`, but that can be handled with a newtype wrapper around `BuildConfig` I believe.

@qrilka Does this make sense to you?

**Comment by qrilka** [comment]
Yes, makes perfect sense

**Comment by mihaimaruseac** [comment]
I like the idea, it will improve code quality for sure.
