### ISSUE TITLE
`stack exec ghci` does not include the Paths_* modules generated by ghc

### ISSUE THREAD

**Issue by andrewufrank** [commercialhaskell/stack#4645]
### General summary/comments (optional)
`stack exec ghci` does not include the Paths_* modules generated by cabal

### Steps to reproduce
In a project XXX: 
1. import Paths_XXX (version)  in a project. 
2. Load with `stack exec ghci`. 
3. Reports `Could not find module ‘Paths_XXX’

For example:

1. Remove directory *blah*.
2. Run command `stack blah`.
3. Edit file blah.
4. Run command `stack blah`.

What is missing is to set the path to the `Path_XXX` module which is generated when building. It is in `.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/autogen/` and this path must e added when invoking the ghci (with `-i...`). It can be done manualy with `:set -i...` and then the `:r` works.

 
```
$ stack <your command here> <args> --verbose
<output>
```

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
hpack not used 
```

### Method of installation
recently upgraded with stack upgrade (linux debian butcher, installed with curl?)

**Comment by qrilka** [comment]
Minor note: Cabal generates that module, not GHC

**Comment by andrewufrank** [comment]
thank you - I edited the issue text.

**Comment by snoyberg** [comment]
stack exec ghci simply runs the underlying ghci executable with some environment variables set. Can you try running stack ghci instead?

**Comment by snoyberg** [comment]
Closing, as this appears to be expected behavior
