### ISSUE TITLE
Missing 32bit Windows binaries for GHC-8.6.4

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#4662]
### Steps to reproduce

For example:

1. stack setup

### Expected

To have ghc-8.6.4 for windows32 platform.

### Actual

What actually happened.

```No setup information found for ghc-8.6.4 on your platform.
60This probably means a GHC bindist has not yet been added for OS key 'windows32'.
61Supported versions: ghc-7.8.4, ghc-7.10.1, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.1, ghc-8.4.2, ghc-8.4.3, ghc-8.4.4, ghc-8.6.1, ghc-8.6.2, ghc-8.6.3```

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) i386 hpack-0.31.1
```

### Method of installation

https://get.haskellstack.org/stable/windows-i386.zip

**Comment by varosi** [comment]
Interesting that LTS-13.11 that should use GHC-8.6.3:
```Downloaded lts-13.11 build plan. No setup information found for ghc-8.6.4 on your platform.```

**Comment by borsboom** [comment]
> Interesting is that LTS-13.11 that should use GHC-8.6.3

Despite what https://www.stackage.org/lts-13.11 says, lts-13.11 actually **does** use GHC 8.6.4 (see https://github.com/commercialhaskell/lts-haskell/commit/1f60f025c563f96c6e539fcea8c58e4b12c1eac5).  Something didn't quite go right in the process of upgrading the GHC 8.6.4 which has caused stackage.org to show the wrong information.  lts-13.12 was released soon after to rectify this, but unfortunately we're stuck with the confusing info on stackage.org for lts-13.11 for now.

**Comment by snoyberg** [comment]
Given that there are no upstream releases of GHC 8.6.3 or 8.6.4 for 32-bit Windows, should we close this?

**Comment by borsboom** [comment]
Yes, I think we should close since there's no action for us to take right now.  If anyone wants to help with contributing a third-party windows32 bindist, please open a new issue or PR against https://github.com/commercialhaskell/stackage-content/blob/master/stack/stack-setup-2.yaml.

**Comment by varosi** [comment]
I have posted a request to GHC team - https://gitlab.haskell.org/ghc/ghc/issues/16516

**Comment by ozgurakgun** [comment]
I just landed here, followed the link above and it seems the GHC issue was resolved. Does that mean there is an upstream GHC-8.6 windows32 release now? If so, maybe stack can use it now?

See https://gitlab.haskell.org/ghc/ghc/issues/16516

**Comment by varosi** [comment]
There is GHC 8.6.5 which support 32bit Windows builds. We’re waiting for
LTS which support it.

На вт, 30.04.2019 г., 13:52 ч. Özgür Akgün <notifications@github.com>
написа:
