### ISSUE TITLE
Fixed version for download

### ISSUE THREAD

**Issue by pjljvandelaar** [commercialhaskell/stack#4684]
In our build environment, we download stack.
However, we can not specify the specific version we download.
In other words, when `http://www.stackage.org/stack/windows-i386` is changed also our build environment is changed.

Is it possible to get `http://www.stackage.org/stack-x.y.z/windows-i386` such that always the particular version of stack is downloaded within our build environment?

**Comment by snoyberg** [comment]
All releases are available on the Github releases page: https://github.com/commercialhaskell/stack/releases

**Comment by pjljvandelaar** [comment]
Thanks
