### ISSUE TITLE
`stack path` for easier use in scripts

### ISSUE THREAD

**Issue by parsonsmatt** [commercialhaskell/stack#469]
Right now the output of `stack path --local-pk-db` is:

```
local-pkg-db: /home/.... etc
```

which makes it less convenient to use in the terminal. `$(stack path --local-pkg-db | cut -f 2 -d ' ')` handles it. Would it be sensible to omit the path identifier if the path was specifically requested in the command?

**Comment by snoyberg** [comment]
I think Chris already changed this on master. I agree this is better
behavior.

**Comment by parsonsmatt** [comment]
Correct! `stack upgrade` and now it's outputting just the path. Thanks!
