### ISSUE TITLE
Support `delegated` Docker volume mounts on macOS

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#4692]
On macOS, builds using `--docker` have very poor performance due overhead of host<->container volume mounts when these have to cross a VM boundary.  Docker for Mac has recently added options to tune performance:

> * `consistent`: perfect consistency (host and container have an identical view of the mount at all times)
>
> * `cached`: the host’s view is authoritative (permit delays before updates on the host appear in the container)
>
> * `delegated`: the container’s view is authoritative (permit delays before updates on the container appear in the host)

More background here: https://docs.docker.com/docker-for-mac/osxfs-caching/

For Stack's usual use case, `delegated` should be sufficient since it's rare to need build artifacts to be available on the host immediately on macOS.  Changes made on the host are still reflected immediately on the container filesystem, so for example `--file-watch` would still work just like it does now.

I've tried `delegated` with Stack and it greatly improves performance (approaching native filesystem performance).

I propose leaving the default as it is (`consistent`, since that's Docker's default), but adding an additional configuration option in the `docker:` section to override it.

We could also consider making `delegated` the default on macOS since, but this risks surprising behaviour.  For example, a user might be using `stack exec` or `stack build --exec` to do work in the container expecting files to be reflected on the host immediately, and `delegated` would break that.

**Comment by dbaynard** [comment]
> For example, a user might be using stack exec or stack build --exec to do work in the container expecting files to be reflected on the host immediately, and delegated would break that.

Is there a way to confirm whether the host's view matches the container's view?

**Comment by borsboom** [comment]
> Is there a way to confirm whether the host's view matches the container's view?

I suppose one could use a diff tool or `rsync --dry-run` between the host and the container somehow.  But by the time that finished, chances are all changes would have been synced anyway (there's not a big delay).

**Comment by borsboom** [comment]
Implemented in #4844
