### ISSUE TITLE
DISCUSS: Make --interleaved-output the default

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4702]
A few different reasons:

1. People have been reporting issues about "frozen" compiles, when in fact it's just very large dependencies that take a long time to build. This output will make it clear that work is happening, just slowly.
2. I've had CI timeouts in the past due to lack of output for 10 minutes. Basically, same as 1, but impatient machines instead of impatient humans
3. It can be informative to see the output as it happens

Downsides:

1. Subjectively more confusing
2. Arguably people don't want to see the individual modules compiling for each dependency

CC @nh2

**Comment by Wildsoft** [comment]
Maybe indicate some progress in some other way to avoid confusing output

**Comment by NorfairKing** [comment]
I'd like `--interleaved-output` for local packages but not for dependencies, by default.
Or that `--test` implies `--interleaved-output` if there are multiple packages.

**Comment by snoyberg** [comment]
> Maybe indicate some progress in some other way to avoid confusing output

Two problems with this:

1. We'd need to know what "some other way" is. In other words: can you be a bit more specific?
2. It doesn't exist yet, so would have to be implemented

> I'd like --interleaved-output for local packages but not for dependencies, by default.

I get the motivation here. However, it wouldn't address my "frozen compiles" concern above. Not eliminating the possibility, just pointing out a limitation.

**Comment by snoyberg** [comment]
We can continue to refine the behavior up until the next release, but I've opened up a PR to change the default. This may also flush out some additional problems during testing. #4718
