### ISSUE TITLE
Stack claims to have generated documentation, but none exists at the reported location.

### ISSUE THREAD

**Issue by recursion-ninja** [commercialhaskell/stack#4704]
### General summary/comments

`stack haddock` prints the following:

```
Documentation created:
.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/doc/html/<package-name>/index.html,
.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/doc/html/<package-name>/<package-name>.txt
```

However, there is no `.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/doc` folder:

### Steps to reproduce

```
git clone https://github.com/amnh/PCG
cd PCG
git checkout f1bf485c0159151da51fbe3dbae38f29e3a3054e
stack haddock
```

[Logs viewable here](https://gist.github.com/recursion-ninja/f3c331f81dfa77359da9e1f8b2553a46)

### Expected

Documentation generated in the `.stack-work/dist/x86_64-linux/Cabal-2.4.0.1/doc/` folder *or* no message reporting documentation being generated and an error describing why documentation couldn't be generated.

### Actual

Documentation was reported as generated, but it does not exist at the reported location.

### Stack version

```
$ stack --version
Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1
```

**Comment by dbaynard** [comment]
Thanks for the report, @recursion-ninja. How odd. I'll investigate, and try to reproduce.

**Comment by dbaynard** [comment]
It's not in any of the library `.stack-work` directories, either. I wonder whether it relates to internal libraries — @mihaimaruseac ?

**Comment by mihaimaruseac** [comment]
I'm going to try a few things later today. Though I don't think it's related to the internal libraries, but I might be wrong.

**Comment by snoyberg** [comment]
Not on my computer right now so I can't try this myself, but question: did you check both the .stack-work in the repo root and in the subdirectory?

**Comment by dbaynard** [comment]
> It's not in any of the library .stack-work directories, either.

I checked. That's what I meant by this.

**Comment by mihaimaruseac** [comment]
With the same Stack version I was able to get Haddock documentation for `io-manager` (just picked a package which I know doesn't have internal libraries).

Trying and debugging PCG now

**Comment by mihaimaruseac** [comment]
Indeed, the documentation is no longer at the location `stack haddock` says. However, if I try to build documentation for one of the packagesI  get

```
[PCG] λ stack haddock pcg-evaluation\:lib 
Haddock index for local packages already up to date at:
/tmp/mm/PCG/.stack-work/install/x86_64-linux-tinfo6/lts-13.14/8.6.4/doc/index.html
Haddock index for local packages and dependencies already up to date at:
/tmp/mm/PCG/.stack-work/install/x86_64-linux-tinfo6/lts-13.14/8.6.4/doc/all/index.html
Haddock index for snapshot packages already up to date at:
/home/mihai/.stack/snapshots/x86_64-linux-tinfo6/lts-13.14/8.6.4/doc/index.html
```

And indeed, those files exist. So I think somehow the doc gets moved but we don't display that?

**Comment by mihaimaruseac** [comment]
I tried a simple reproduction with

```
.
├── proj1
│   ├── P1.hs
│   └── proj1.cabal
├── proj2
│   ├── P2.hs
│   └── proj2.cabal
└── stack.yaml
```

where the haskell files are

```haskell
-- |
-- Module: P1
-- Just a demo module
module P1 where

-- | Just a function defined in P1
func :: a -> a
func = id
```

the cabal files are

```cabal
cabal-version: 2.2
name: proj1
version: 0.0.1

library
  hs-source-dirs: .
  default-language: Haskell2010
  exposed-modules: P1
  build-depends: base
```

(replace 1 with 2 for the other project) and `stack.yaml` is

```yaml
resolver: lts-13.15
packages:
 - proj1
 - proj2
```

Unfortunately, this generates the documentation properly

```
mihaimaruseac@ankh:/tmp/mms/demo$ stack haddock
proj1-0.0.1: configure (lib)
proj1-0.0.1: build (lib)
proj2-0.0.1: configure (lib)
proj1-0.0.1: haddock
proj2-0.0.1: build (lib)
proj1-0.0.1: copy/register
proj2-0.0.1: haddock
proj2-0.0.1: copy/register
Completed 2 action(s).   
Updating Haddock index for local packages in
/tmp/mms/demo/.stack-work/install/x86_64-linux-tinfo6/lts-13.15/8.6.4/doc/index.html
Updating Haddock index for local packages and dependencies in
/tmp/mms/demo/.stack-work/install/x86_64-linux-tinfo6/lts-13.15/8.6.4/doc/all/index.html
Updating Haddock index for snapshot packages in
/home/mihaimaruseac/.stack/snapshots/x86_64-linux-tinfo6/lts-13.15/8.6.4/doc/index.html
Log files have been written to: /tmp/mms/demo/.stack-work/logs/

mihaimaruseac@ankh:/tmp/mms/demo$ file /tmp/mms/demo/.stack-work/install/x86_64-linux-tinfo6/lts-13.15/8.6.4/doc/index.html /tmp/mms/demo/.stack-work/install/x86_64-linux-tinfo6/lts-13.15/8.6.4/doc/all/index.html
/tmp/mms/demo/.stack-work/install/x86_64-linux-tinfo6/lts-13.15/8.6.4/doc/index.html:                     HTML document, ASCII text, with very long lines, with no line terminators
/tmp/mms/demo/.stack-work/install/x86_64-linux-tinfo6/lts-13.15/8.6.4/doc/all/index.html:                 HTML document, ASCII text, with very long lines, with no line terminators

```

I'll try removing bits and pieces from PCG until documentation is no longer generated

**Comment by mihaimaruseac** [comment]
@dbaynard I see that the `doc` directory gets created in the subdirectory's `.stack-work`:

```
mihaimaruseac@ankh:/tmp/mms/PCG$ stack haddock
mihaimaruseac@ankh:/tmp/mms/PCG$ find . -name "index.html"
./lib/pcg-utility/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-utility/index.html
./lib/pcg-data-normalization/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-data-normalization/index.html
./lib/pcg-serialize/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-serialize/index.html
./lib/pcg-alphabet/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-alphabet/index.html
./lib/pcg-language/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-language/index.html
./lib/pcg-file-parsers/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-file-parsers/index.html
./lib/pcg-tcm-memo/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-tcm-memo/index.html
./lib/pcg-exportable/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-exportable/index.html
./lib/pcg-evaluation/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-evaluation/index.html
./lib/pcg-data-unification/.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/doc/html/pcg-data-unification/index.html
...
```

Probably just the message is wrong?

**Comment by snoyberg** [comment]
I think so, and further, I think this message is being generated by Cabal, not Stack. I can't find anywhere in the Stack codebase that would move the generated documentation around.

**Comment by mihaimaruseac** [comment]
Closing due to lack of response and as the issue seems to be caused upstream

**Comment by recursion-ninja** [comment]
A stock response to reopen. This issue is *not* resolved. 

Lack of response does not change the fact that a defect exists in what `stack` reports.

**Comment by snoyberg** [comment]
We have a policy of not retaining issues which are caused by upstream. From what we can tell, this is an upstream issue.

**Comment by recursion-ninja** [comment]
`stack` should still appropriately list where documentation has been placed or at a minimum refrain from listing an incorrect documentation location, regardless of what `cabal` is generating. I do consider this a `stack` issue and I don't consider this resolved.

**Comment by mihaimaruseac** [comment]
It's cabal who prints the message too, afaik
