### ISSUE TITLE
Missing win32 stack setup for GHC 8.6.4

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#4707]
### Steps to reproduce

```
$ stack setup --arch=i386 > nul
No setup information found for ghc-8.6.4 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'windows32'.
Supported versions: ghc-7.8.4, ghc-7.10.1, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.1, ghc-8.4.2, ghc-8.4.3, ghc-8.4.4, ghc-8.6.1, ghc-8.6.2, ghc-8.6.3
```

### Stack version

Grabbed 10 minutes ago with:

```
curl -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
```

**Comment by dbaynard** [comment]
There's no `i386` release at https://github.com/commercialhaskell/ghc/releases. @borsboom ?

---

The last `windows32` entry is at https://github.com/commercialhaskell/stackage-content/blob/fc783644189af52b80aca9aa913926489697e206/stack/stack-setup-2.yaml#L955-L960

The last `windows64` entry is https://github.com/commercialhaskell/stackage-content/blob/fc783644189af52b80aca9aa913926489697e206/stack/stack-setup-2.yaml#L1030-L1035

**Comment by dbaynard** [comment]
Oh, this is a duplicate (#4662). Apparently, it's an upstream issue.
