### ISSUE TITLE
cabal configure with verbosity flag -v3

### ISSUE THREAD

**Issue by karamellpelle** [commercialhaskell/stack#4708]
`stack build` fails because something is wrong with my foreign C code. I get the error "* Missing (or bad) header file" which I think is similar to [this](https://github.com/haskell/cabal/issues/1747#issuecomment-54801015), but I have no idea what and where that error happens since that's all output I get from `stack build` and `stack build --verbosity debug`.

> Missing (or bad) header file: glfw_foreign.h This problem can usually be solved by installing the system package that provides this library (you may need the "-dev" version). If the library is already installed but in a non-standard location then you can use the flags --extra-include-dirs= and --extra-lib-dirs= to specify where it is.  If the header file does exist, it may contain errors that are caught by the C compiler at the preprocessing stage. In this case you can re-run configure with the verbosity flag -v3 to see the error messages.

I'm suggested to use the `-v3` verbosity flag for cabal, but how do I set this flag through stack?

**Comment by snoyberg** [comment]
I don't know if it's -v3, but can you try --cabal-verbose?

**Comment by karamellpelle** [comment]
Yes, I've tried `stack build --cabal-verbose`. It gives me the same message/hint: _If the header file does exist, it may contain errors that are caught by the C compiler at the preprocessing stage. In this case you can re-run configure with the verbosity flag -v3 to see the error messages_. I guess there should be a way to pass arguments to cabal similar to `stack build --ghc-options`. Right now, this project seems impossible to fix because I can't pinpoint what's wrong.

And talking about `--cabal-verbose`: The output is a mix of two outputs; I guess there are two threads writing to stdout at the same time.

What do you think about adding an option `--cabal-options` to stack?

**Comment by snoyberg** [comment]
Seems good to me, and in line with #1438. Would you be interested in working on a PR?

**Comment by karamellpelle** [comment]
I'm absolutely interested in helping, but what is a PR?

**Comment by karamellpelle** [comment]
I think a good solution could be to add the `-v0` .. `-v3` options inside the `--verbosity [silent, error, warn, info, debug]` option of `stack`. This will make it independent of cabal and simpler for the user.

If we instead create a `--cabal-options` option, we will probably need to split this into (at least) two commands: `--cabal-configure-options` and `--cabal-build-options`.

But for now, I found a solution for debugging: when `stack build` fails it tells me which command failed, and I can just copy, modify and run that command myself. In my case I just add `-v3` to this long line:

>  /Users/karamellpelle/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.0.1.0 configure --with-ghc=/Users/karamellpelle/.stack/programs/x86_64-osx/ghc-8.2.2/bin/ghc --with-ghc-pkg=/Users/karamellpelle/.stack/programs/x86_64-osx/ghc-8.2.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/Users/karamellpelle/.stack/snapshots/x86_64-osx/lts-11.4/8.2.2/pkgdb --package-db=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/pkgdb --libdir=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/lib --bindir=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/bin --datadir=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/share --libexecdir=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/libexec --sysconfdir=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/etc --docdir=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/doc/grid-1.0 --htmldir=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/doc/grid-1.0 --haddockdir=/Users/karamellpelle/Source/grid/GLFW/.stack-work/install/x86_64-osx/lts-11.4/8.2.2/doc/grid-1.0 --dependency=array=array-0.5.2.0 --dependency=base=base-4.10.1.0 --dependency=binary=binary-0.8.5.1 --dependency=bytestring=bytestring-0.10.8.2 --dependency=directory=directory-1.3.0.2 --dependency=filepath=filepath-1.4.1.2 --dependency=ghc-prim=ghc-prim-0.5.1.1 --dependency=mtl=mtl-2.2.2-8XubxMJDT8QLsstvlNotkc --dependency=parsec=parsec-3.1.13.0-7jIoWXeUFiXFkcrm3qWsZW --dependency=random=random-1.1-LLUGZ7T9DqQ5vN0Jbcd0We --enable-tests --enable-benchmarks

**Comment by snoyberg** [comment]
> I'm absolutely interested in helping, but what is a PR?

PR == pull request

* * *

Since we already have an open issue for tracking options to cabal to control verbosity, and you have a short term workaround, I'm going to close this as a duplicate
