### ISSUE TITLE
Missing ghc 8.6.4 bindisit for "linux64-ncurses6"

### ISSUE THREAD

**Issue by RaphyJake** [commercialhaskell/stack#4711]
Just like in [this](https://github.com/commercialhaskell/stack/issues/4144) issue, environment has ncurses 6 installed and stack fails to install ghc 8.6.4.

```
% stack config set resolver lts
Selected resolver: lts-13.15
/home/raphy/.stack/global-project/stack.yaml already contained the intended configuration and remains unchanged.
% stack setup
No setup information found for ghc-8.6.4 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.
Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
```
Using Void Linux, with ncurses 6.1.

**Comment by borsboom** [comment]
Most Linux distributions have standardized on providing `libtinfo.so.6` (either directly or as a symlink to `libncursesw.so.6`).  As such, there aren't GHC 8.6.* bindists that link to `libncursesw.so.6` available.  If Void Linux doesn't provide a compatibility package, you might try creating a symlink yourself.

**Comment by RaphyJake** [comment]
Thanks a lot, making the symlink solved it.

**Comment by borsboom** [comment]
Awesome!  If you have time, a pull request against https://github.com/commercialhaskell/stack/blob/master/doc/faq.md adding a note with the steps you took might be helpful to others.

**Comment by lokesh1197** [comment]
@borsboom I have sent a pull request in the faq for this. Let me know if any modifications are required

**Comment by waynevanson** [comment]
> Most Linux distributions have standardized on providing libtinfo.so.6 (either directly or as a symlink to libncursesw.so.6). As such, there aren't GHC 8.6.* bindists that link to libncursesw.so.6 available. If Void Linux doesn't provide a compatibility package, you might try creating a symlink yourself.

If building GHC on your machine on `voidlinux`, you'll need to install `ncurses-libtinfo-devel`. This installs all the stuff, including the symlink for `libtinfo.so.6`. This definitely works for `x86_64` but unsure with any other variants or musl.
