### ISSUE TITLE
Script in stack similiar to cabal-install's bootstrap.sh?

### ISSUE THREAD

**Issue by joehendrix** [commercialhaskell/stack#473]
On some projects, I need to build from source on machines that are not connected to the internet. 

It would be useful to me if stack came with a script capable of downloading the packages to build stack from a directory, and also to build stack from those archived packages.

Together with stack --dry-run, this would allow one to build a self-contained source archive containing all the main libraries needed to build a software package (beyond the core operating system/compiler requirements).

**Comment by snoyberg** [comment]
I thought there was an issue open about this already, but I don't have
internet access right now so I can't check. The stackage-build-plan package
was specifically designed for generating such build scripts, and therefore
would probably be the right place to start. There's even support for it on
stackage.org that I can give more details about once I have an internet
connection.

Could you check out stackage-build-plan first and see if that provides the
kind of script you're looking for?

**Comment by snoyberg** [comment]
Now that I'm on the ground, how's this look for installing with GHC 7.10.1?

https://www.stackage.org/nightly-2015-07-01/build-plan?package=stack&_accept=application/x-sh

**Comment by snoyberg** [comment]
If you could test this, I'd appreciate it. If this works for you, would you consider updating the Downloads page with this information? Also, I think the following will always be up-to-date:

https://www.stackage.org/nightly/build-plan?package=stack&_accept=application/x-sh

**Comment by joehendrix** [comment]
Thank you for the pointer to stackage-build-plan!  That's exactly what I needed. 

I'm currently travelling, but will try testing the script once I get back to having consistent Internet access.

**Comment by snoyberg** [comment]
Closing as implemented. If there are problems, please reopen.
