### ISSUE TITLE
I hope stack download the dependencies to .stack dir instead of the /tmp dir.

### ISSUE THREAD

**Issue by mut0u** [commercialhaskell/stack#4733]
I find that stack will download the cabal dependencies sources code to /tmp dir and then build them into .stack dir which is in every project and then the stack will delete the source code from /tmp dir.

If I want to jump to the dependencies sources code to see the impl of some function, it will failed.
So I hope that all dependencies sources code can download in project's .stack dir and do not delete the source code  so that I can use ide to jump to the deps source code to see the detail of the function.

**Comment by snoyberg** [comment]
This would use up additional disk space, which many users wouldn't want. What you can do instead is use the `unpack` command with the `--resolver` argument to get the source code.

I'm wondering if we should add a more explicit `--respect-stack-yaml-versions` or something to ensure that we get the exact same source code as the current project is built against.

**Comment by mut0u** [comment]
I love the `cargo` tool policy, which will maintain all source code in `$HOME/.cargo` dir with version. So It is very easy to jump to the source code. Also it will cache the dependent source code by multi projects, it will download the source code once and then use the dependent code locally with the same version.

My root thought is that stack can maintain the dependencies sources code so I do not worry about download them by myself. So I can tell my ide to search where is the source code .

**Comment by snoyberg** [comment]
As I mentioned, there's already an `unpack` command which will provide you the source code.

**Comment by snoyberg** [comment]
Closing as wontfix
