### ISSUE TITLE
Note that you can install stack through halcyon

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#474]
The latest site doesn't say how to install stack e.g. on debian 7. As debs are only provided for ubuntu and the provided binary doesn't work on debian 7 due to a libc missmatch

```
./stack-0.1.1.0-x86_64-linux: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.14' not found (required by ./stack-0.1.1.0-x86_64-linux)
```

I guess it would be very helpful to know that you can just use `halcyon` to install `stack` from source. (e.g. if the distribution doesn't provide a recent ghc/cabal)
```
$ curl -OL https://github.com/commercialhaskell/stack/archive/v0.1.1.0.tar.gz
$ tar xzf v0.1.1.0.tar.gz
$ cd stack-0.1.1.0
$ source <( curl -sL https://github.com/mietek/halcyon/raw/master/setup.sh )
$ halcyon install
```

**Comment by snoyberg** [comment]
I'm definitely open to a documentation pull request for this. Also,I believe @dysinger is planning on including debs for vanilla Debian in addition to Ubuntu.

**Comment by snoyberg** [comment]
The Downloads page now includes Debian, CentOS, Red Hat, and Fedora. I'd be quite happy if someone wants to add instructions on using with Halcyon, but for now I think the originally request has been resolved.

**Comment by manny-fp** [comment]
The binary on the Github releases page now also works on Debian 7, since that's now what I'm using to build it.  I figure following whatever the GHC team does makes the most sense (no point having a stack binary that works but no GHC, or vice-versa), and they use Debian 7.
