### ISSUE TITLE
Dependency resolution for profiling (under GHC 7.10.2 prerelease)

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#475]
Using https://github.com/alanz/ghc-exactprint/tree/b36bf21659cac048cf3e7d215b1a2c0de4bf1158 with the current ghc-7.10 head, I find

    stack test

compiles and runs the tests.

However,

    stack test --library-profiling
    stack test --executable-profiling

both result in a whole lot of output culminating in

```
Recommended action: try adding the following to your extra-deps in /home/alanz/mysrc/github/alanz/ghc-exactprint/stack.yaml
- base-4.8.0.0
- ghc-prim-0.4.0.0
- integer-gmp-1.0.0.0
- template-haskell-2.10.0.0

You may also want to try the 'stack solver' command
```

stack --version
Version 0.1.1.0, Git revision bf086c6d5f8e86e95f161c38c596a6dae571ab65

**Comment by snoyberg** [comment]
Do you have the profiling version of the wired in packages installed? stack
can't do anything to rebuild them for you

**Comment by alanz** [comment]
Nope. Oops. I thought I had done a standard build/install of the compiler.

Thanks
