### ISSUE TITLE
Add support to curator for generating older LTS Haskell/Stackage Nightly YAML format

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#4759]
This will allow us to move over to the new curator tool immediately, without breaking users of Stack currently. This will likely also affect Nix.

**Comment by qrilka** [comment]
@snoyberg how this could affect Nix if we'll keep using the old format when this will be implemented?

**Comment by snoyberg** [comment]
In theory Nix will continue to just work, though it depends on exactly which fields on the file Nix is using.

**Comment by snoyberg** [comment]
This is already implemented in the repo. Plan for deploying the changes and closing out this issue:

1. Move stackage.org over to a new codebase which uses the new snapshot files. This is just waiting on some DevOps work and for the (really really large) database to populate
2. Tweak the new build scripts in stackage to use the conversion tool implemented for this issue
3. Switch over to building nightly with the new tool
4. When we're satisfied with how Nightly is working, start LTS 14 using the new tool

I'm moving this out of the Stack 2 milestone, since this in no way blocks the Stack 2 release.

**Comment by snoyberg** [comment]
We're now generating nightlies with the new curator, and will use the new tool for LTS 14. Closing as resolved.
