### ISSUE TITLE
auto-bundle to Docker container

### ISSUE THREAD

**Issue by alexbiehl** [commercialhaskell/stack#476]
What about a command which copies the project output (binaries, extra-source-files etc) to a Docker container. Something like `stack dockerize some/image --cmd run/some/binary` just with more appropriate configuration etc.. https://github.com/commercialhaskell/stack/issues/427 suggest similar with windows installers.

**Comment by mboes** [comment]
See #401.

**Comment by snoyberg** [comment]
@alexbiehl I'm going to close this so we can focus discussion on #401.
