### ISSUE TITLE
Missing stack 1.9.3.1 tarball

### ISSUE THREAD

**Issue by asr** [commercialhaskell/stack#4775]
Stack 1.9.3.1 was [released](http://hackage.haskell.org/package/stack-1.9.3.1) but the tarball in the link [Linux 64-bit, standard](https://get.haskellstack.org/stable/linux-x86_64.tar.gz) (in the [Manual download](https://docs.haskellstack.org/en/stable/install_and_upgrade/#manual-download_2) section) corresponds to 1.9.3.

**Comment by borsboom** [comment]
1.9.3.1 is a hackage-only release for compatibility with newer versions of a dependency.  There are no user facing changes, and it's not actually a new release of the Stack tool.
