### ISSUE TITLE
stack test should continue when a test suite fails

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#478]
Rationale:

* without this users have to manually specify test targets in order to skip the package with the offending test suite. It gets tiring.
* sometimes test suites are badly written, in which case a non-deterministic failure appears in some package. At this point it's not so helpful for `stack` to refuse to process the dependent test suites, when in previous invocations it would have.
* it's consistent with the behaviour of most test frameworks, which run all tests in a test suite regardless of failures.

Variations:

* don't make this the default, but provide`-k` and `--keep-going` flags, à la `make`.
* don't process dependent packages, but do continue processing test suites for packages that don't depend on the package whose tests don't pass. Then `-k` would mean blindly test everything no matter what (provided it builds).

**Comment by snoyberg** [comment]
@mboes I've implemented `--keep-going` with default behavior as described for `build`, `test`, and `bench`. Confirmed?

**Comment by mboes** [comment]
Nice!
