### ISSUE TITLE
Error when building in docker on ArchLinux - Cannot open shared object file

### ISSUE THREAD

**Issue by JDurstberger** [commercialhaskell/stack#4799]
I don't think this is per se a bug in stack but I am unable to build any project in a docker image on archlinux. 

I get the following error:

```
$ stack build
Received ExitFailure 127 when running
Raw command: /usr/bin/docker run -v /usr/bin/stack:/tmp/stack sha256:f53def16a336f6a0c97c347075cee2273550cfd90369a1546d82c4fce0c22683 /tmp/stack --version
```

which shows the following error for the raw command

```
/tmp/stack: error while loading shared libraries: libHSstack-1.9.3.1-CDcGZe4np4wm9qMGKkZbv-ghc8.6.4.so: cannot open shared object file: No such file or directory
```

Steps to reproduce:
1. Create project with `stack new stack-docker`
2. Enable docker builds in `stack.yaml`
3. Pull docker image with `stack docker pull`
4. Try to build with `stack build`

I think the problem is that archlinux does something funky with shared libraries for it's stack installation but I don't understand enough of it to be honest. 
I just found a reference to the HSstack lib here: https://www.archlinux.org/packages/community/x86_64/stack/files/

**Comment by mattaudesse** [comment]
Hey @JDurstberger - sorry for the slow response.

This sounds like the difference between building *inside* the container vs. building outside then *copying* the resultant binary (on your host machine) into the image - `stack` supports both ways.

I'm guessing you've set up an `image` section in `stack.yaml` similar to this?
https://docs.haskellstack.org/en/stable/GUIDE/#docker

I suspect `stack build` will work if you replace the `image` config with
```yaml
docker:
    enable: true
```
and rerun the steps you provided above. Does that fit your use case? I might be reading
> I am unable to build any project in a docker image on archlinux

too literally but it sounds like that's what you're after, so this might be an easy fix :-)

If you'd like to build your project outside of the Docker container and are still having trouble it'd be helpful if you could share your `stack.yaml`.

**Comment by JDurstberger** [comment]
Hey mattaudesse,

you are right, my working was confusing. 
I was talking about building the project _inside_ a docker container.

I won't be able to reproduce this as I gave up on Archlinux for now and went to Linux Mint. 
Everything works fine there. 

I don't know if you would like to keep this issue open for other arch users?

**Comment by mattaudesse** [comment]
Let's close in the interest of keeping the active issue count a bit lower, but we can reopen later if someone else gets stuck.

Either way, you've probably helped other Arch users arriving here from a Google search.

Glad you've got it working now!

**Comment by DarthFennec** [comment]
>I think the problem is that archlinux does something funky with shared libraries for it's stack installation but I don't understand enough of it to be honest.

As far as I can tell, the problem is that Arch links Stack against shared dependencies, while other systems link it statically (though I don't know enough to say exactly why this is a problem). For anyone who runs into this problem and finds this thread like I did, what worked for me was installing the [`stack-static`](https://aur.archlinux.org/packages/stack-static/) package from the AUR, in place of the dynamic package.

**Comment by borsboom** [comment]
@DarthFennec Have you tried this with stack-2.1.1?  It includes a bug fix that should make `--docker` out of the box by correctly detecting that the host `stack` executable isn't compatible in the case of an Arch dynamically linked binary and auto-download a static exe to use in the container.

**Comment by DarthFennec** [comment]
@borsboom I suppose not, no. I was using the latest from the central Arch repos, which (as of right now) is 1.9.3.1. So it seems that once that gets updated, this should no longer be a problem. Good to know.
