### ISSUE TITLE
stack-build Docker Images with Ubuntu 18.04?

### ISSUE THREAD

**Issue by smasuda** [commercialhaskell/stack#4823]
Now that ubuntu 18.04 has been around for more than a year, would you be able to consider having docker images with ubuntu 18.04 instead of only with 16.04?

We hit this issue when we tried using [hw-kafka-client](https://github.com/haskell-works/hw-kafka-client) package which requires librdkafka 0.9 while ubuntu 16.04 comes with an older version of librdkafka.  Although we can always build or install necessary libraries, however, it would be nice if the images are built on top of the OS versions which are getting common.

**Comment by borsboom** [comment]
The `fpco/stack-build` Docker images follow Stackage's lead when it comes to the Ubuntu version they're based on.  The Stackage build environment switched to Ubuntu 18.04 right after LTS-13 was cut, which means that LTS-14 images will be based on Ubuntu 18.04.
