### ISSUE TITLE
Stack verbs inconsistency

### ISSUE THREAD

**Issue by ivo-stefchev** [commercialhaskell/stack#4829]
Please follow the steps below for reporting a bug:

### Steps to reproduce

`stack path` gives this information about `--local-bin-path`:
```
$ stack path --local-bin-path

'--local-bin-path' will be removed in a future release.
Please use '--local-bin' instead.

/home/user/.local/bin
```

So I try to use like this in `stack build`:
```
$ stack build --copy-bins --local-bin ${PWD}
Invalid option `--local-bin'
```
Not a big bug at all.
Thank you.

**Comment by snoyberg** [comment]
Nice catch. Interested in sending a PR to update the reported information for this?

**Comment by ivo-stefchev** [comment]
Yes, I'll give it a shot. Thanks.

**Comment by mpilgrem** [comment]
`--local-bin` is a flag of `stack path`, not `stack build`. `--local-bin-path <directory>` is a global flag of Stack, almost exclusively used with `stack build --copy-bins` and `stack install`.
