### ISSUE TITLE
Lots of TlsException and FailedConnectionException

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#483]
Trying to build a project in a docker (deb7) container, building looks like this:

```
root@cbfbf0d6e994:/build# stack build
byteorder-1.0.4: downloading
byteorder-1.0.4: configure
byteorder-1.0.4: build
byteorder-1.0.4: install
bytestring-builder-0.10.6.0.0: downloading
bytestring-builder-0.10.6.0.0: configure
bytestring-builder-0.10.6.0.0: build
bytestring-builder-0.10.6.0.0: install
Progress: 3/194TlsException (HandshakeFailed Error_EOF)
root@cbfbf0d6e994:/build# stack build
cereal-0.4.1.1: downloading
cereal-0.4.1.1: configure
cereal-0.4.1.1: build
cereal-0.4.1.1: install
cryptohash-0.11.6: downloading
cryptohash-0.11.6: configure
cryptohash-0.11.6: build
cryptohash-0.11.6: install
data-default-class-0.0.1: downloading
data-default-class-0.0.1: configure
data-default-class-0.0.1: build
data-default-class-0.0.1: install
Progress: 4/192TlsException (HandshakeFailed Error_EOF)
root@cbfbf0d6e994:/build# stack build
data-default-instances-base-0.0.1: downloading
data-default-instances-base-0.0.1: configure
data-default-instances-base-0.0.1: build
data-default-instances-base-0.0.1: install
Progress: 1/189FailedConnectionException "s3.amazonaws.com" 443
Progress: 2/189root@cbfbf0d6e994:/build# stack build
data-default-instances-containers-0.0.1: downloading
data-default-instances-containers-0.0.1: configure
data-default-instances-containers-0.0.1: build
data-default-instances-containers-0.0.1: install
Progress: 1/188FailedConnectionException "s3.amazonaws.com" 443
Progress: 2/188root@cbfbf0d6e994:/build# stack build
digest-0.0.1.2: downloading
digest-0.0.1.2: configure
digest-0.0.1.2: build
digest-0.0.1.2: install
Progress: 1/187FailedConnectionException "s3.amazonaws.com" 443
Progress: 2/187root@cbfbf0d6e994:/build#
```

Not sure what causes it, but keep rerunning `stack build` is not a good solution I think ;-)

**Comment by mgsloan** [comment]
I got the same thing a couple minutes ago, and I'm writing this comment 9 minutes after you created this issue.  So, it may be a temporary glitch in availability.  At the time, I'd chalked it up to my dialup speed cellphone internet (throttled after 5gb are used up, ugh!)

**Comment by angerman** [comment]
This has happened to me only in the docker container. And internet shouldn’t be
an issue here. Yet, maybe it gets better later today.

Still, I think stack should bail out more gracefully and retry a few times.

**Comment by mgsloan** [comment]
Yup, I agree.  Even if it is an availability glitch, retry would be nice so that you don't need to manually rerun `stack build`.

**Comment by snoyberg** [comment]
This may be an upstream issue with tls, see: https://github.com/vincenthz/hs-tls/issues/109

**Comment by angerman** [comment]
How could we debug this properly? Is there a super chatty piece of stack that can be run on it's own just to see where things go wrong?  E.g. from #484 it even fails downloading ghc from haskell.org with `FailedConnectionException "www.haskell.org" 443`. Could one therefore feed stack just the url and get very verbose output, to maybe figure out what's wrong?

**Comment by snoyberg** [comment]
I think the debugging you want would need to be done at the http-client
level.

**Comment by snoyberg** [comment]
Interestingly, the `FailedConnectionException` means that the connection attempt timed out. It may be worth trying to bump the connection timeout value in stack to see if that helps alleviate the problem.

**Comment by vincenthz** [comment]
This is the same for `TlsException (HandshakeFailed Error_EOF)`. The system notify the stack that the connection has been closed (recv == 0), during the handshake which `tls` raises as exception with EOF

**Comment by snoyberg** [comment]
Let's make the first step here implementing retry logic. That's something @DanBurton was going to work on later, but if someone else wants to take a stab at it first, the code is pretty simple.

**Comment by snoyberg** [comment]
Retry logic has landed in the download code. If these kinds of problems are still occurring with master (or after the next release), please reopen.

**Comment by manny-fp** [comment]
Data point: experienced this problam on Debian 7 32-bit when using a stack-0.1.2.0 executable built with tls-1.3.1.  After rebuilding with tls-1.2.18, the problem went away.

**Comment by CRogers** [comment]
Just experienced this a few times on circleci inside a docker container with stack 0.1.2.0: https://circleci.com/gh/CRogers/stack-ide-atom/8 (cmd+f for FailedConnectionException).

**Comment by manny-fp** [comment]
@CRogers: how did you obtain the stack executable in this case?

**Comment by CRogers** [comment]
I downloaded it off of the Stack releases page on github. The actual one that's being used can be found here: https://github.com/CRogers/stack-ide-atom-docker/tree/stack-0.1.2.0_nightly-2015-06-28

**Comment by CRogers** [comment]
I'm actually getting even more crazy errors now (still stack 1.2.0.0). From [this build](https://circleci.com/gh/CRogers/stack-ide-atom/12): `FailedConnectionException2 "s3.amazonaws.com" 443 True <socket: 165>: hPutBuf: resource vanished (Broken pipe)`.

**Comment by manny-fp** [comment]
Ok, so if you used the github release binaries, you shouldn't be hitting the tls-1.3.* bug.  I'm not familar with circleci, but is it possible this is a problem with the configuration on their build infrastructure?  For example, missing CA certificates, proxy settings, could all be causing these problems.  Have you been able to reproduce using as similar an environment possible outside of circleci?

**Comment by rubenmoor** [comment]
Same here:

    FailedConnectionException2 "s3.amazonaws.com" 443 True getAddrInfo: does not exist (error 11002)

on Windows, Stack version 0.1.5.0

**Comment by rubenmoor** [comment]
Retrying a lot seems to help ...

> Interestingly, the FailedConnectionException means that the connection attempt timed out. It may be worth trying to bump the connection timeout value in stack to see if that helps alleviate the problem.

How would I do that?

**Comment by snoyberg** [comment]
In Stack.Types.StackT, there's a usage of tlsManagerSettings. You want to
modify the managerResponseTimeout field of it.

**Comment by Blaisorblade** [comment]
> Retry logic has landed in the download code. If these kinds of problems are still occurring with master (or after the next release), please reopen.

**Comment by nh2** [comment]
@angerman Do you still see issues like this with stack >= 1.7.1, which is dynamically linked?

As per https://github.com/commercialhaskell/stack/issues/2536, there were some issues with the combination of static linking and Linux distribution (CNAME) DNS resolving bugs.

**Comment by snoyberg** [comment]
I'm closing again, as there is no response, and these appear to have been external issues. If there are still problems, I think a new issue would make more sense at this point.
