### ISSUE TITLE
wrong dependency in docs

### ISSUE THREAD

**Issue by Vozf** [commercialhaskell/stack#4831]
### General summary/comments (optional)
invalid package.yaml dependency
### Steps to reproduce
https://docs.haskellstack.org/en/stable/GUIDE/#extra-deps
### Expected
dependencies:
- base >= 4.7 && < 5
- text
- filepath
- containers
- acme-missiles # added

### Actual
dependencies:
- base >= 4.7 && 5
- text
- filepath
- containers
- acme-missiles # added

**Comment by Vozf** [comment]
Moreover it is said
> The appropriate resolver value (resolver: lts-11.22, as is currently the latest LTS)
But the lts is 13.21

**Comment by snoyberg** [comment]
Nice catch. Would you be interested in sending a PR to improve the docs?

**Comment by Vozf** [comment]
Fixed the dependency list issue but the lts reference edit seems useless as it will be invalid on next lts version

**Comment by borsboom** [comment]
I'll make note to update the LTS reference there when we do new releases.
