### ISSUE TITLE
Build stucks when compiling a project using ghcjs 8.6

### ISSUE THREAD

**Issue by DoctorRyner** [commercialhaskell/stack#4834]
### General summary/comments (optional)

Please, checkout this issue
https://github.com/ghcjs/ghcjs/issues/745

The problem is that ghcjs itself works fine, I mean I can use cabal for my projects and ghcjs works without a hitch but when I try to do the same with stack, it just freezes when trying to download and build project dependencies that means that it has something to do with ghcjs support in stack and I understand that support is experimental but I think there are many people who don't want to use nix and want stack instead, it's kinda great and the best option in my opinion

### Steps to reproduce

For example:

Just make an empty stack project and use ghcjs from 8.6 branch as a compiler, try to add any dependency and build it

Or for a more concrete example

1. Clone https://github.com/DoctorRyner/miso-new-stack
2. Install ghcjs-8.6.0.1_ghc-8.6.2 via nix
```bash
nix-channel --add https://nixos.org/channels/nixos-19.03 nixos
nix-channel --update
nix-env -f channel:nixos-19.03 -iA haskell.compiler.ghcjs
```
3. run `stack build --stack-yaml=stack-ghcjs.yaml`
That above works on macOS Mojave 10.14.4 but it could require
```bash
brew install bash gnu-tar coreutils
stack install alex happy
```
or maybe something else, checkout the errors, if junior developer can install it, any one can, to reproduce this you need to use ghcjs-8.6.0.1 and build something with it (its able to build empty project without dependencies but if you add something, it will be just stuck as in this issue https://github.com/ghcjs/ghcjs/issues/745

### Expected

Download dependencies and successfully build project

### Actual

When you run `stack build --stack-yaml=stack-ghcjs.yaml` it stuck as in an issue https://github.com/ghcjs/ghcjs/issues/745

### Stack version
1.9.3

### Method of installation
curl -sSL https://get.haskellstack.org/ | sh

**Comment by DoctorRyner** [comment]
Actually it’s possible to build ghcjs project using stack, one can run stack build then interrupt it and build it with cabal new-build, but it’s pretty tricky and confusing

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
