### ISSUE TITLE
stack fails to download ghc binaries

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#484]
It seemed to me like stack setup tried to download and install ghc from source, could stack not reuse/share halcyons prebuild ghc versions? (e.g. `halcyon install --ghc-version=... --cabal-version=...`) fetches binaries for the current platform, which is a lot faster.

Building ghc is one of those things in my experience that takes very long.

**Comment by snoyberg** [comment]
That's how we do things already. stack never builds GHC from source.

**Comment by angerman** [comment]
`stack setup` just took very long and at some point I killed it. Today I ran it again and it threw an Exception, that it could not download the file. This leads me to believe that there's something not working properly with the network stack in `stack`, as `stack build` keeps on bailing out with exceptions as well.
Strangely enough `curl` and and `halcyon` do not have any issues downloading sources.

**Comment by radix** [comment]
@angerman can you please show exactly what errors you're seeing (and perhaps search for similar bugs / file new ones about the errors)

**Comment by angerman** [comment]
The `stack build` errors are in #483. Currently I'm getting `TlsException (HandshakeFailed Error_EOF)` every third package on average. 

Here's what `stack setup` looks like (I altered `Setup.hs` to show the url as well):

```
root@cbfbf0d6e994:/build# /app/bin/stack setup
Preparing to download ghc-7.10.1(https://www.haskell.org/ghc/dist/7.10.1/ghc-7.10.1-x86_64-unknown-linux-deb7.tar.xz) ...FailedConnectionException "www.haskell.org" 443
root@cbfbf0d6e994:/build# /app/bin/stack setup
Preparing to download ghc-7.10.1(https://www.haskell.org/ghc/dist/7.10.1/ghc-7.10.1-x86_64-unknown-linux-deb7.tar.xz) ...FailedConnectionException "www.haskell.org" 443
root@cbfbf0d6e994:/build# curl -OL https://www.haskell.org/ghc/dist/7.10.1/ghc-7.10.1-x86_64-unknown-linux-deb7.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153    0   153    0     0    147      0 --:--:--  0:00:01 --:--:--   148
100 74.9M  100 74.9M    0     0  3391k      0  0:00:22  0:00:22 --:--:-- 4947k
root@cbfbf0d6e994:/build# ping haskell.org
PING haskell.org (23.253.242.70): 48 data bytes
56 bytes from 23.253.242.70: icmp_seq=0 ttl=61 time=222.006 ms
56 bytes from 23.253.242.70: icmp_seq=1 ttl=61 time=223.355 ms
56 bytes from 23.253.242.70: icmp_seq=2 ttl=61 time=212.677 ms
56 bytes from 23.253.242.70: icmp_seq=3 ttl=61 time=218.552 ms
56 bytes from 23.253.242.70: icmp_seq=4 ttl=61 time=211.040 ms
56 bytes from 23.253.242.70: icmp_seq=5 ttl=61 time=224.842 ms
56 bytes from 23.253.242.70: icmp_seq=6 ttl=61 time=216.629 ms
^C--- haskell.org ping statistics ---
7 packets transmitted, 7 packets received, 0% packet loss
round-trip min/avg/max/stddev = 211.040/218.443/224.842/4.915 ms
```

**Comment by snoyberg** [comment]
Pinging @drwebb and @DanBurton. Let's improve the download code and consider hosting on S3 instead add well.

@vincenthz Any thoughts on the failures mentioned above?

**Comment by snoyberg** [comment]
This may be an upstream issue with tls, see: https://github.com/vincenthz/hs-tls/issues/109

**Comment by snoyberg** [comment]
Let's keep the discussion on #483, which has the more pertinent title.

**Comment by rodlogic** [comment]
Could [this](https://blogs.aws.amazon.com/security/post/TxCKZM94ST1S6Y/Introducing-s2n-a-New-Open-Source-TLS-Implementation) have anything to do with it?

**Comment by snoyberg** [comment]
Probably not, since the errors being reported here happened with haskell.org, which isn't on Amazon hardware.

**Comment by DanBurton** [comment]
Under what circumstances are things going wrong?

On Thursday, July 2, 2015, Michael Snoyman <notifications@github.com> wrote:

> Probably not, since the errors being reported here happened with
> haskell.org, which isn't on Amazon hardware.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/484#issuecomment-118118196>
> .
>


-- 
-- Dan Burton

**Comment by angerman** [comment]
Setup:
Host, OS X 10.10.4
Docker Container with debian:7.8 (from docker hub)
Stack installed from 0.1.1.0 source with halcyon

Trying to run `stack setup`
