### ISSUE TITLE
stack ls dependencies doesn't prune anymore

### ISSUE THREAD

**Issue by akshaymankar** [commercialhaskell/stack#4845]
### General summary/comments

This is a bug in `stack 2.1.0.1 rc`. It is not a problem in `1.9.3`.
The `pruneGraph` function in `Stack.Dot` seems to have regressed. The [tests](https://github.com/commercialhaskell/stack/blob/aa3a5f2573ffe8791f63e621447c9084d5aa0ba1/src/test/Stack/DotSpec.hs#L54-L59) did not catch this because the properties were either wrong or `show` for `PackageName` is no longer being overridden. I could make the tests fail by replacing `show` with `packageNameString`.

### Steps to reproduce

1. Go to any stack project
1. Run command `stack ls dependencies --no-include-base`. The bug can also be reproduced using `--prune base` and it can also be seen in `stack dot`.

### Expected

`stdout` shows all dependencies except `base` and its dependencies

### Actual

All dependencies including `base` and its dependencies are printed.

### Stack version

```
$ stack --version
Version 2.1.0.1, Git revision 72c9f8c741be762a036ce16b6306d08a8be666ad (7614 commits) RELEASE-CANDIDATE x86_64 hpack-0.31.1
```

### Method of installation

* Official osx binary, downloaded from github releases.

**Comment by borsboom** [comment]
Fix merged, so closing.
