### ISSUE TITLE
Custom `package-indices` in snapshot

### ISSUE THREAD

**Issue by dten** [commercialhaskell/stack#4846]
We have a custom snapshot that's shared between several stack.yaml, and we recently added hosted some packages internally on our own index.

Currently that means adding the `package-indices` block to every stack.yaml that is using the custom snapshot, it seems it's not possible to it to the snapshot itself, even though that is the part that adds the packages from that index.

We want them in the snapshot and in the index so that the build outputs are cached / shared between builds.

**Comment by snoyberg** [comment]
With Stack 2 and implicit snapshots, you can refer to the tarballs directly and still get caching. I think this even worked in previous versions of Stack. Closing as wontfix.

**Comment by dten** [comment]
Great thanks.
