### ISSUE TITLE
"Cannot determine project root directory for Docker sandbox." error even when Docker support is disabled

### ISSUE THREAD

**Issue by Kleidukos** [commercialhaskell/stack#4864]
### General summary/comments (optional)

Stack produces a docker-related error when trying to create a new project

```bash
❯ stack new lol
Cannot determine project root directory for Docker sandbox.
```

### Steps to reproduce

1. Configure `config.yaml to explicitly disable Docker:

```yaml
docker:
  enable: false
```
 
2. Run `stack new <name>` 

3. Weep.

### Stack version

```
❯ Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

* `stack upgrade` from the latest version

### How to resolve this

1. Removing ~/.stack and /usr/local/bin/stack
2. Reinstall Stack

### Does it solve it entirely?

No. It comes back after a while.

**Comment by Kleidukos** [comment]
@borsboom Hi! Do you have any idea about what is happening here?

**Comment by dbaynard** [comment]
Hello, thanks for reporting. Would you share some project information (e.g. stack.yaml, package.yaml/cabal files)? Also, precisely which `config.yaml` do you mean?

**Comment by Kleidukos** [comment]
Hi!
The `config.yaml` I was talking about was `~/.stack/config.yaml`. 
<details>
<summary>stack.yaml</summary>

```yaml
nix:
  enable: true
  pure: false
  packages: [glpk, pcre, curl, zlib]

docker:
  enable: false
```
</details>

I am unable to give you the content of any `package.yaml` / `cabal`, because they cannot be generated due to the aforementioned error.

I am indeed running this command (but any other, actually) from my home directory.

**Comment by borsboom** [comment]
A couple of questions:

- Does this happen if you remove the `docker` section (but keep the `nix` section)?
- Alternatively, what happens if you remove the `nix` section but keep the `docker` section?
- And finally, what happens if you remove both?

I suspect the mention of Docker in the error message is a red herring, because the Nix code was initially based on the Docker code and it looks like it re-uses this error message.

**Comment by Kleidukos** [comment]
Hi @borsboom!

* When the `docker` section is removed but the `nix` section is kept, it still doesn't work :disappointed:;
* When the` nix` section is removed, it works :tada:;
* When both of the sections are removed, it works :tada:.

**Comment by qrilka** [comment]
@Kleidukos but I guess 2nd and 3rd options disable nix integration - are you OK with disabling it?
What OS are you on?

**Comment by Kleidukos** [comment]
@qrilka I enabled it at the project level, and it works :/ I don't understand why it would fail at the global level and not at the project level, but it seems to be working :woman_shrugging:

**Comment by qrilka** [comment]
That sounds like some odd bug to me :)
Some moths ago it was decided that there is no sense to use nix and docker modes of Stack simultaneously - probably we've added some improper config handling  with that change. I hope to have time check it out later in the day.

**Comment by ttuegel** [comment]
> I guess 2nd and 3rd options disable nix integration - are you OK with disabling it?

For what it's worth, NixOS users can't use Stack and disable Nix integration, so this effectively makes certain commands unusable there.

**Comment by qrilka** [comment]
@ttuegel that's not quite correct: nix mode is the default but it's not 100% required but you need to supply GHC by some other way (Nix seems to be the most obvious choice in this case) as an example see https://gist.github.com/qrilka/2b21576e541412656bde0c4ca6c2064e

**Comment by qrilka** [comment]
@Kleidukos there was a Stack bug in `stack.yaml` being required for any commands in Nix mode which resulted in that misleading error message about Docker, #4885 fixed that
