### ISSUE TITLE
Ignore warning from stack.yaml: Unrecognized fields in urls: lts-build-plans, nightly-build-plans

### ISSUE THREAD

**Issue by c4dr01d** [commercialhaskell/stack#4866]
At I installed stack and set stackage mirrors at config.yaml, the stack show this warning: Unrecognized fields in urls: lts-build-plans, nightly-build-plans, that warning is very anonying, how can I ignore it?

**Comment by c4dr01d** [comment]
The contents of config.yaml:
![issues](https://user-images.githubusercontent.com/50952350/59544710-176d4d80-8f47-11e9-8064-3bb6c979f705.jpg)

**Comment by dbaynard** [comment]
Hello! I _think_ the documentation is out of date. Does stack work if you just delete the `lts-build-plans` and `nightly-build-plans`?

They aren't mentioned at https://docs.haskellstack.org/en/stable/yaml_configuration/#urls and the code containing them was removed in f3142113 – @snoyberg should be able to explain more, if needed.

**Comment by snoyberg** [comment]
Those fields are no longer used. With the Pantry change in Stack 2, we no longer support the original Stackage file format.

**Comment by c4dr01d** [comment]
@snoyberg emmm, that options is deprecated?

**Comment by c4dr01d** [comment]
@dbaynard I follow the instruction from my mirrors website, and, this configuration is copyed from that website.

**Comment by snoyberg** [comment]
Those instructions apply to Stack prior to version 2.

**Comment by c4dr01d** [comment]
@snoyberg Ok, I know that.

**Comment by dbaynard** [comment]
@c4dr01d Does stack work if you just delete the deprecated entries?

**Comment by c4dr01d** [comment]
@dbaynard yes.

**Comment by dbaynard** [comment]
Great! Glad it's working.
