### ISSUE TITLE
Stack 2 now requires GHC bindist to contain haddock executable?

### ISSUE THREAD

**Issue by arrowd** [commercialhaskell/stack#4867]
In the process of updating FreeBSD port of Stack to version 2 I found that ino64 variant GHC bindists prepared by me can't be used anymore. Stack complains that installed compiler is broken, because there are no `haddock`, `haddock-ghc-x.y.z` executables are found. In my bindist I omitted them to save some space.

Before redoing all the bindists I wanted to ask if having `haddock` in the bindist is a requirement now?

**Comment by dbaynard** [comment]
@borsboom is the best person to answer this, I think. Thanks, @arrowd — hopefully everything will work smoothly, soon.

**Comment by snoyberg** [comment]
That is implicitly the requirement right now, yes. I didn't consider this a problem, though if it's a real issue I'd be open to modifying the way this is done internally. It's all part of the sanity-check-and-cache bit of installing GHC.

**Comment by arrowd** [comment]
Thanks.

I've submitted https://github.com/commercialhaskell/stackage-content/pull/66 and will be including `haddock` in future bindists.

**Comment by borsboom** [comment]
I've merged commercialhaskell/stackage-content#66 and mirrored the bindists.
