### ISSUE TITLE
use alternative mirror with stack 2.1.1

### ISSUE THREAD

**Issue by bjin** [commercialhaskell/stack#4870]
With the recently released `stack 2.1.1`, the [recommended way to use alternative mirror](https://github.com/commercialhaskell/stack/blob/master/doc/install_and_upgrade.md#china-based-users) is outdated. I would like to know what's the best way to use alternative mirror with `stack 2.1.1`, since it's not mentioned in docs or release note. (downstream issue: tuna/mirror-web#132).

1. I get the following error for the Stackage setup, does it mean it's no longer possible to use mirrors to fetch LTS and nightly plans?
```
Unrecognized fields in urls: lts-build-plans, nightly-build-plans
```
2. It seems that `/root.json` is now required for mirror to initialize package indices, as required by Hackage Security. In addition to the [current synchronized directory of TUNA mirror](https://mirrors.tuna.tsinghua.edu.cn/hackage/), what files are required to setup a Hackage mirror compatible with `stack 2.1.1` properly? Is synchronizing [these four JSON files](https://hackage.haskell.org/api#security) enough?
3. I also find [an official mirror list](https://hackage.haskell.org/mirrors.json) from Hackage, if the TUNA mirror mentioned above proved to be popular and reliable, what's the procedure to get it into the official list?

Thanks

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by c4dr01d** [comment]
Hi, I have same problem, I was open a issues at #4866

**Comment by bjin** [comment]
@dbaynard The other issue only addressed the first question I have.The `package-indice` setting change remains unclear. Also the outdated doc is not fixed.

**Comment by bjin** [comment]
@dbaynard Should I open another issue regarding the `package-indices` setting and outdated doc?

**Comment by tfangz888** [comment]
D:\stack\tmp>stack update
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("Cache-Control","no-transform"),("User-Agent","Haskell pantry package")]
  path                 = "/hackage.fpcomplete.com/timestamp.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 NoResponseDataReceived

**Comment by tfangz888** [comment]
I have connection issues
