### ISSUE TITLE
undocumented dependency on gnu-tar on mac os x leads to build failures

### ISSUE THREAD

**Issue by esjmb** [commercialhaskell/stack#4873]
I have put relevant content on comments to a commit here:

https://github.com/commercialhaskell/stack/commit/0c57490fc471ab8757a539804d6d4e204a6a4239

It appears that stack 2.1.1 is now dependant on gnu-tar, which causes projects build with an earlier stack version on macos machines without gnu-tar installed to fail badly (opaque error output) , on an upgrade to stack 2.1.1. 

I suggest that stack should at least test for and advise on the missing dependency. 

I noticed that some templates (all?) have been adjusted to brew install gnu-tar, so its probably not a problem for greenfield projects, but that is not a solution for those who upgrade to stack 2.1.1 to find that what was working before no longer works. The issue will be compounded in that it arises only on a recloning of certain project dependencies, and so may not arise for some time after an upgrade to stack 2.1.x, on a .stack-work deletion for example. 

I didn't spot any documentation on the dependency in release notes while solving my problem this morning, but that might be my bad. 

As an end user, I would suggest the best resolution would be to eliminate the dependency on macos, restricting it to windows which is the platform it seems to have been introduced for, or failing that, to ensure stack provides an installation directive. Obviously the dependency should be documented (and perhaps already is).

cheers for the outstanding work as always. stack 2.1.1 looks to be an excellent upgrade.

**Comment by qrilka** [comment]
Looks to be a duplicated of #4865

**Comment by snoyberg** [comment]
Fixed by #4879, closing.
