### ISSUE TITLE
stack 2.1.1 ends up with Cabal 2.4.0.1 and 2.4.1.0 in the package environment

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#4875]
### General summary/comments (optional)

When building a test project against `lts-13.23`, the dist dir ends up being `..stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1`. 

The snapshot has `Cabal-2.4.1.0` in it.

When compiling the project (admittedly by using cabal-helper at https://github.com/alanz/cabal-helper/tree/wip/new-build) it errors because both Cabal library versions are present.  This can (and will) be fixed in cabal-helper.

But why is stack not using Cabal-2.4.1.0?

**Comment by qrilka** [comment]
I suppose the comments in this issue shine some light on your question @alanz - #4488
The main motivation as I see it is just to save user's time because building `Cabal` takes quite substantial time

**Comment by alanz** [comment]
@qrilka Thanks, I just checked, and see that GHC 8.6.4 and 8.6.5 both ship with Cabal 2.4.0.1.

So I will continue delving into the problem in `cabal-helper`

**Comment by alanz** [comment]
If anyone is interested, I got this working via https://github.com/alanz/haskell-ide-engine/commit/40f9c8869f01863aa5c0224808125d22cd0d6a0a, which does

```haskell
    unsetEnv "GHC_PACKAGE_PATH"
    unsetEnv "GHC_ENVIRONMENT"
    unsetEnv "HASKELL_PACKAGE_SANDBOX"
    unsetEnv "HASKELL_PACKAGE_SANDBOXES"
```
before running the process invoking `cabal-helper`.
