### ISSUE TITLE
Can no longer compile two things at once with 2.1.1 from 1.9.3

### ISSUE THREAD

**Issue by dten** [commercialhaskell/stack#4876]
It used to be fine compiling a project in different .stack-work directories or different projects at the same time.
After upgrading to stack 2.1.1 I can't even build _different_ projets at the same time let a long the same project.

Just get this error until the first build has finished. After that I can try build the second project.
This makes stack ~unusable on CI, and~ pretty awful to use locally with multiple projects.

```
Encountered error while migrating Pantry database:
    SQLite3 returned ErrorProtocol while attempting to perform prepare "PRAGMA journal_mode=WAL;": locking protocol
Please report this on https://github.com/commercialhaskell/stack/issues
As a workaround you may delete Pantry database in /home/david/.stack/pantry/pantry.sqlite3 triggering its recreation.
```

**Comment by dten** [comment]
Tried this on some colleagues' machines, seems like it's to do with WSL 😿

**Comment by dten** [comment]
The internet says WAL is broken on WSL, is there a choice to not use WAL :)?

**Comment by borsboom** [comment]
Oh, that's annoying, it certainly would be nice for Stack to work out of the box on WSL.  Looks like WAL is enabled by default in `persistent-sqlite`, but does provide an option to disable it.  @snoyberg Can you think of any downside for Stack/Pantry to disable WAL by default?  Alternatively, we could provide a configuration option to disable it.

**Comment by igraves** [comment]
I'm seeing this same issue running on MacOS with docker.  `2.1.1` works locally on MacOS, but in the docker image (latest fpco/stack-build) `stack build` fails with this message.

**Comment by jihygk** [comment]
Also encountering this on OS X with the docker build on 2.1.1. Went back to 1.9.3 and it was working again.

**Comment by borsboom** [comment]
Strange, I don't seem to be encountering this on macOS (using the current stable version of Docker for Mac).

**Comment by borsboom** [comment]
Pull request that disables WAL mode for new databases: #4915

**Comment by ygale** [comment]
@borsboom @snoyberg A [comment](https://github.com/Microsoft/WSL/issues/2395#issuecomment-339993293) in Microsoft/WSL#2395 says that disabling WAL will not fix the issue, just make it happen less often. Someone else reports working around it by introducing a delay to avoid the race condition. The core issue is Microsoft/WSL#1927. This was reported more than two years ago, but so far still no response from Microsoft.

**Comment by borsboom** [comment]
I think disabling WAL by default is the right choice anyway (since it also can cause problems on network filesystems and with Docker for Mac).

I think it's out of scope for Stack to do anything more to work around this issue.  SQLite is hardly an esoteric choice for local data storage, and if Microsoft purports Linux compatibility it really should work out of the box.  Adding 0.1 second delays before writing to the DB, as suggested in one comment, would be terrible for performance (and I suspect just makes the problem less likely).

**Comment by ygale** [comment]
@borsboom Agreed. And this is anyway fixed in WSL2. Thanks!
