### ISSUE TITLE
The http-download package refers to this bug tracker

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#4880]
Is that intentional? Or the result of a copy & paste error?

In case that this is the right place to file issues about `http-download`, then I'd like to report that I've built the package successfully with `cryptonite` version 0.26. For purposes of distributing `http-download` and `stack`, it would be great if you could edit the Cabal file on Hackage to allow building with that newer version of the dependency.

http://packdeps.haskellers.com/feed?needle=exact:http-download

**Comment by borsboom** [comment]
> Is that intentional? Or the result of a copy & paste error?

It is intentional, `http-download`'s source code is in this repo under [subs/http-download](https://github.com/commercialhaskell/stack/tree/master/subs/http-download).

> I'd like to report that I've built the package successfully with cryptonite version 0.26. For purposes of distributing http-download and stack, it would be great if you could edit the Cabal file on Hackage to allow building with that newer version of the dependency.

Done (also for `pantry-tmp` and `stack`).
