### ISSUE TITLE
Stack 2.1.1 setup unpacking GHC ExitFailure (-15)

### ISSUE THREAD

**Issue by jamesdbrock** [commercialhaskell/stack#4889]
Since I upgraded to Stack 2.1.1, I've encountered an intermittent `stack setup` bug when running in a Docker container.

The bug occurs rarely on my local development machines.

The bug occurs often on the Docker Hub Cloud infrastructure.

This error happens after Stack has downloaded and unpacked GHC. Unpacking GHC actually always succeeds as far as I can tell, but for some reason the `tar` process sometimes returns error -15 after success.

```
...
2019-06-19 07:06:11.122183: [error] Received ExitFailure (-15) when running
Raw command: /bin/tar Jxf /home/stackuser/.stack/programs/x86_64-linux/ghc-8.6.5.tar.xz
Run from: /home/stackuser/.stack/programs/x86_64-linux/ghc-8.6.5.temp/
2019-06-19 07:06:11.122272: [error]
Error: Error encountered while unpacking GHC with
tar Jxf /home/stackuser/.stack/programs/x86_64-linux/ghc-8.6.5.tar.xz
run in /home/stackuser/.stack/programs/x86_64-linux/ghc-8.6.5.temp/
The following directories may now contain files, but won't be used by stack:
- /home/stackuser/.stack/programs/x86_64-linux/ghc-8.6.5.temp/
- /home/stackuser/.stack/programs/x86_64-linux/ghc-8.6.5/
```

### Steps to reproduce

This minimal `Dockerfile` sometimes succeeds and sometimes fails:
https://github.com/jamesdbrock/docker-stack-setup-test/blob/d2880b3f59ac12571e3be9627150291da7e209f1/Dockerfile

I have built this on Docker Hub and observed it both succeeding and failing, with the same Git commit hash. There is no way to make my Docker Hub build results public, but I will add anyone who asks as a Collaborator on this Docker Hub repository.

#### Failure
Gist: https://gist.github.com/jamesdbrock/c4052cf7af2826cae523650438d78070
Docker Hub: https://cloud.docker.com/repository/registry-1.docker.io/jamesbrock/docker-stack-setup-test/builds/fb9f44ba-d430-4d59-b6cb-64eb997b1176

#### Success
Gist: https://gist.github.com/jamesdbrock/8408aebc0047cd5ebd1ce625eb6cd4d6
Docker Hub: https://cloud.docker.com/repository/registry-1.docker.io/jamesbrock/docker-stack-setup-test/builds/601acc9f-1759-47d2-baa7-2261f0858e47

### Stack version
`Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2`

**Comment by jamesdbrock** [comment]
The `stack setup` output line

```
2019-06-19 13:05:09.749335: [error] (stdin): 175.8 MiB / 1773.5 MiB = 0.099, 17 MiB/s, 1:47
```
Is not actually an error, it's just `xz` reporting to `stdout` in `--verbose` mode.

**Comment by jamesdbrock** [comment]
My best guess about what is happening is that there may be a race condition in [`sinkProcessStderrStdout`](https://hackage.haskell.org/package/stack-1.7.1/docs/Stack-Prelude.html#v:sinkProcessStderrStdout), called by `runStep` in [`installGHCPosix`](https://hackage.haskell.org/package/stack-1.7.1/docs/src/Stack.Setup.html#installGHCPosix).

**Comment by jamesdbrock** [comment]
Duplicate of #4888

**Comment by snoyberg** [comment]
I'm going to close in favor of #4888 so we can focus discussion there.
