### ISSUE TITLE
Documentation for common non-standard project initialization

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#489]
It seems that the common cases for starting a project (just run `stack new` or `stack init` and take the defaults) do not cause people trouble. However, a number of users- especially those coming from specific cabal-imposed workflows- have trouble getting started with stack. We should address this with clear documentation on how to get started in the non-standard cases.

Since @drwebb has been helping a number of people with these problems, he's volunteered (and/or: been bullied into) writing a first version of such a Wiki page.

**Comment by drwebb** [comment]
Started an outline here at: https://github.com/commercialhaskell/stack/wiki/Nonstandard-project-initialization

**Comment by drwebb** [comment]
Outline has been updated as V1, anyone is free to edit as they see fit.
