### ISSUE TITLE
Curator cycle checks are not complete

### ISSUE THREAD

**Issue by qrilka** [commercialhaskell/stack#4891]
We need to improve Stackage curator checks to prevent cases like https://github.com/commercialhaskell/stackage/pull/4634
In principle component-based Stack builds should also resolve the situation but we don't have them yet.

**Comment by DanBurton** [comment]
In particular, for example, if package `x` depends on package `y`, but the test suite for `y` depends on `x`, this appears to be a cycle, but it is not, because you can sequentially build everything you need to:

1. build `y:lib`
2. build `x:lib`, depending on `y:lib`
3. build `y:tests`, depending on `x:lib`

**Comment by qrilka** [comment]
@DanBurton that would be a false positive but the problem was that we had a false negative i.e. `curator` not catching cycles which prevented a Stack build

**Comment by DanBurton** [comment]
@qrilka as I understand it, that example is also a false positive.

```
Given that:

splitmix:splitmix-dieharder (test) requires base-compat-batteries:lib
base-compat-batteries:spec (test)  requires QuickCheck:lib
QuickCheck:lib                     requires splitmix:lib


1. build `splitmix:lib`
2. build `QuickCheck:lib`
3. build `base-compat-batteries:lib`
4. build the tests in any order
```

If this is considered a "cycle" in stack, then obviously our curator checks should also consider it a "cycle" now that we use stack to build stuff. But these components _can_ be built and tested without cycles; this might be considered a bug in `stack`.

**Comment by DanBurton** [comment]
The "easy fix", I presume, would be to build all library targets before building any non-library targets. Cycles only matter if they are between library targets, because non-library targets cannot be dependencies for other targets and thus cannot participate in any cycles.

**Comment by qrilka** [comment]
Oh, you mean false positive from Stack itself, right, I see.
Sure that's a problem, Stack's own cycle resolution is not very clever and not very straightforward. So I guess we need to make curator and Stack do at least the same about cycle detection.
Ok, thanks for this, I'll try to think what could be done here.

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and because it appears to me to be principally about Curator.
