### ISSUE TITLE
Stack local-doc-root is wrong for 2.1.1

### ISSUE THREAD

**Issue by dfithian** [commercialhaskell/stack#4892]
### General summary/comments (optional)

After upgrading to 2.1.1 and trying to install docs, I found that `stack path --local-doc-root` is wrong.

### Steps to reproduce

```
stack build --haddock --no-haddock-deps
...
Updating Haddock index for local packages in
.../.stack-work/install/x86_64-osx/9e8c24a71c82f9b19c848e4aa52470a8c1ccf223f368a919481ba397b1f5de2b/8.6.5/doc/index.html
Updating Haddock index for local packages and dependencies in
...//.stack-work/install/x86_64-osx/9e8c24a71c82f9b19c848e4aa52470a8c1ccf223f368a919481ba397b1f5de2b/8.6.5/doc/all/index.html
Haddock index for snapshot packages already up to date at:
/Users/dan/.stack/snapshots/x86_64-osx/9e8c24a71c82f9b19c848e4aa52470a8c1ccf223f368a919481ba397b1f5de2b/8.6.5/doc/index.html
```

```
ls $(stack path --local-doc-root)
ls: .../.stack-work/install/x86_64-osx/6c9a92c41e7ce4083f1bd67c8cbacc2a6620c22b954d11bc44a07a6f2b8217d9/8.6.5/doc: No such file or directory
```

The docs are in the hash `9e8c24a71c82f9b19c848e4aa52470a8c1ccf223f368a919481ba397b1f5de2b` but Stack says they are in `6c9a92c41e7ce4083f1bd67c8cbacc2a6620c22b954d11bc44a07a6f2b8217d9`.

I did check `stack path --local-install-root` and it uses the `9e8c24a71c82f9b19c848e4aa52470a8c1ccf223f368a919481ba397b1f5de2b` hash.

Important to note that I am using a custom snapshot.

### Stack version

```
stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

Homebrew

**Comment by dfithian** [comment]
As a workaround, I am using `$(stack path --local-install-root)/doc`

**Comment by qrilka** [comment]
That's a side effect of implicit snapshots in Stack 2 - enabling or disabling haddocks changes snapshot hash, and in your case you should see difference between `stack path --local-doc-root` and `stack path --no-haddock-deps --local-doc-root` with the latter pointing to the proper location

**Comment by dfithian** [comment]
```stack path --local-doc-root
.../.stack-work/install/x86_64-osx/6c9a92c41e7ce4083f1bd67c8cbacc2a6620c22b954d11bc44a07a6f2b8217d9/8.6.5/doc
stack --haddock path --local-doc-root
.../.stack-work/install/x86_64-osx/6c9a92c41e7ce4083f1bd67c8cbacc2a6620c22b954d11bc44a07a6f2b8217d9/8.6.5/doc
stack --no-haddock-deps path --local-doc-root
.../.stack-work/install/x86_64-osx/9e8c24a71c82f9b19c848e4aa52470a8c1ccf223f368a919481ba397b1f5de2b/8.6.5/doc```

Okay, while this seems unintuitive, I accept that it's a thing. Where would have been the correct place for me to look that up?

**Comment by qrilka** [comment]
@snoyberg have we documented these details of implicit snapshots anywhere? I don't remember anything other than https://github.com/commercialhaskell/stack/blob/master/doc/build_overview.md and that's not quite what users normally look into...

**Comment by snoyberg** [comment]
It seems like a better approach here may be to simply refuse to include the `local-doc-root` information without the `--haddock` flag passed to Stack. And I don't think we have a clear place to document this right now, no.

**Comment by dfithian** [comment]
Okay, I can try to take a stab at this if it will help you. From what I can see from spending a few minutes reading (this is my first time reading Stack source), I think I need to change behavior of `runHaddock` on line 55 in module `Stack.Path` and surrounding functions to omit the `with` keys when `buildOptsMonoidHaddockL` is false. Does that seem appropriate?

**Comment by snoyberg** [comment]
I'd definitely appreciate if you could take a look. I tried playing around with `Stack.Path`, but wasn't able to fix it. I'm most likely the culprit in breaking things, especially since I didn't fully understand what was going on with the Haddock split in `Stack.Path` previously. I'd be happy to provide any insight I can if you'd like to take a stab at this. Thanks!

**Comment by dfithian** [comment]
Given the discussion in the PR (#4903), I'm unsure if you'd like to keep this open or closed for documentation. Please do as you will, and if the correct place for documentation comes up I can give it a shot.

**Comment by exarkun** [comment]
This bit me recently and I didn't understand the problem or a find a solution until I stumbled over this issue on my way to filing essentially the same bug report.

**Comment by dfithian** [comment]
Closing because it's so old
