### ISSUE TITLE
Snapshot hashes break use of `stack build` to install project-local tools (e.g. intero)

### ISSUE THREAD

**Issue by tejon** [commercialhaskell/stack#4894]
Per https://github.com/chrisdone/intero/blob/master/TOOLING.md#installing:
> Use `stack build` (not `install`) for each of your package sets. Each LTS or nightly should have a separate `stack build`. **If you use `stack install` you will run into incompatibility issues between package sets.**

With `stack` 2.1.1, `stack build intero` from my project folder produces a different hash than `stack build` for my project, and invoking `stack exec` looks only in the project hash:

```
 % pwd
/home/tejon/myproject

 % stack build intero
<...>
intero   > Installing executable intero in /home/tejon/.stack/snapshots/x86_64-linux/bcf0b026ffb660ea74fc52ec969e29bd46a7446771655533f7521ca9daa64f0e/8.6.5/bin

% stack exec intero
Executable named intero not found on path: ["/home/tejon/myproject/.stack-work/install/x86_64-linux/b4bc7b2b6ebd8d4b74edb96691a4a2b87212aef1a6114c9fd9a4112a098fa896/8.6.5/bin","/home/tejon/.stack/snapshots/x86_64-linux/b4bc7b2b6ebd8d4b74edb96691a4a2b87212aef1a6114c9fd9a4112a098fa896/8.6.5/bin",<...>]
```

**Comment by tejon** [comment]
(Edited a few times.)

**Comment by snoyberg** [comment]
I think the intero docs should be updated, @chrisdone added a `--copy-compiler-tool` flag to address this use case IIRC.

**Comment by chrisdone** [comment]
Updated the docs: https://github.com/chrisdone/intero/commit/61caa798bd385acf918b3639cf03f336b618e78b

**Comment by tejon** [comment]
Everything works! Worth noting tho, I _did_ look for anything relevant in the docs at https://docs.haskellstack.org/en/stable/README/ , and on double-checking now I find no mention of `--copy-compiler-bins`, or of `compiler-tools-bin` as a concept.

Now that I know what I'm looking for, `stack build --help` does mention the new flag, so I'm closing this; but IMO discoverability is still an issue. (I absolutely understand what a task it is to update the guide, so this is not a complaint, just making sure it's on the radar!)
