### ISSUE TITLE
Stack 2.1.1 doesn't set package environments like it used to

### ISSUE THREAD

**Issue by vaibhavsagar** [commercialhaskell/stack#4896]
### General summary/comments (optional)

With previous versions of Stack, `stack test` set the package environment so the current package was loaded. This is useful for [IHaskell](https://github.com/gibiansky/IHaskell) which exercises the GHC API.

Stack 2.1.1 doesn't do this, and so I'm getting a lot of errors and a failed test suite.

### Steps to reproduce

1. `git clone https://github.com/gibiansky/IHaskell`
1. `cd IHaskell`
1. `stack test`

### Expected

`ihaskell-0.10.0.0: Test suite hspec passed`

This is with version `1.9.3 x86_64 hpack-0.31.2`.

### Actual

https://travis-ci.org/gibiansky/IHaskell/jobs/548734133

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by qrilka** [comment]
@vaibhavsagar Stack 2 uses explicit dependencies from test stanza of a cabal file

**Comment by qrilka** [comment]
One of motivations behind that is in resolving of ambiguous module issue https://github.com/sol/doctest/issues/119

**Comment by alanz** [comment]
FWIW we had to use the [following](https://github.com/alanz/haskell-ide-engine/blob/c-h-201905-az/test/utils/TestUtils.hs#L298-L303) code to be able to run a sub-process test under hie, which is probably related

```haskell
flushStackEnvironment :: IO ()
flushStackEnvironment = do
  unsetEnv "GHC_PACKAGE_PATH"
  unsetEnv "GHC_ENVIRONMENT"
  unsetEnv "HASKELL_PACKAGE_SANDBOX"
  unsetEnv "HASKELL_PACKAGE_SANDBOXES"
```

**Comment by vaibhavsagar** [comment]
@qrilka `ihaskell` *is* a dependency, so I'm not sure I understand.

**Comment by vaibhavsagar** [comment]
To get this to work with Cabal I have to do something like

 ```bash
export GHC_PACKAGE_PATH=$PWD/dist/package.conf.inplace/:$GHC_PACKAGE_PATH
```

Is there a similar thing I can do with Stack?

**Comment by qrilka** [comment]
oh sorry @vaibhavsagar I didn't read it carefully, yeah, I see that `ihaskell:hspec` depends on `ihaskell` itself, I will take a look into what's going on

**Comment by qrilka** [comment]
@vaibhavsagar could test this with the latest version 2.1.3 which includes #4921 ?

**Comment by qrilka** [comment]
@vaibhavsagar #4921 has resolved a problem of not including `ihaskell` itself in test-suite dependencies and what's seen in https://github.com/gibiansky/IHaskell/pull/1093 is missing dependencies for a test-suite: I've added `ihaskell-gnuplot`, `ihaskell-blaze`, `ihaskell-juicypixels`, `ihaskell-aeson` and `ihaskell-widgets` and `stack test` with Stack-2.1.3 end like
```
ihaskell            > Test suite hspec passed
Completed 8 action(s).
```
on my machine.
Stack 2 requires test dependencies to be set explicitly.
Will you accept a PR to `IHaskell` with missing dependencies added so we could close this ticket?

**Comment by vaibhavsagar** [comment]
I won't accept that PR, because it would break the build with e.g. Nix, which will try to build e.g. `ihaskell-blaze` for the test-suite, which itself depends on `ihaskell`, causing cyclic dependency issues. Is there a way to include those test-suite dependencies only for Stack?

**Comment by qrilka** [comment]
Oh, nixpkgs also doesn't do component-based builds, I've completely forgotten about that. Quite unfortunate. Ok, I'll try to find some other way around.

**Comment by vaibhavsagar** [comment]
Component-based builds would be great for this particular issue, but I would like to point out (once again) that this still works with Cabal in its current state, and it would be ideal if I had a way to persuade Stack to support this too :smile:.

**Comment by vaibhavsagar** [comment]
OTOH I don't think the IHaskell tests depend on any of those libraries, so it may be a code change to IHaskell that is required.

**Comment by qrilka** [comment]
Test code itself doesn't but the code that gets run by those tests does need the dependencies. This makes me wonder how could cabal run those tests properly if those dependencies are not explicitly required... So IHaskell appears to be an interesting edge case :) But failing for the current Stack :-\

**Comment by vaibhavsagar** [comment]
I just found that commenting out the `ihaskell-*` packages in the `extra-packages` section of `stack.yaml` and doing a clean `stack test` does succeed, so here's what I think is happening:

1. [IHaskell tries to import all `ihaskell-*` packages that it finds](https://github.com/gibiansky/IHaskell/blob/4ffe04ae8e76f88ebc695265dc7bf523359563e1/src/IHaskell/Eval/Evaluate.hs#L177-L239).
2. Stack puts the `ihaskell-*` packages in the environment because they're in `extra-packages`, but hides them.
3. IHaskell barfs because it tries to import them and fails.

**Comment by qrilka** [comment]
That sounds like a good find but what is that `extra-packages` you're referring to? I don't see those packages in `extra-deps` and removing them from the `packages` section should make them unavailable at all

**Comment by vaibhavsagar** [comment]
Sorry, I meant `packages`.

**Comment by vaibhavsagar** [comment]
This seems to work for me on Stack 2.1.3, can you confirm? https://github.com/gibiansky/IHaskell/pull/1097

**Comment by qrilka** [comment]
That makes perfect sense and works for me too. I suppose we could close this one.

**Comment by vaibhavsagar** [comment]
Yup, thanks for your help!
