### ISSUE TITLE
Tell the user that a boot package was pruned

### ISSUE THREAD

**Issue by Rufflewind** [commercialhaskell/stack#4897]
I use Stack on CI and sometimes override dependencies intentionally.  Recently, they started failing, but the error message isn't particularly descriptive:

```
Error: While constructing the build plan, the following exceptions were
encountered:
In the dependencies for directory-1.3.3.2:
    time must match >=1.4 && <1.10, but the stack configuration has no specified
         version  (latest matching version is 1.9.3)
needed since directory is a build target.
```

`stack ls dependencies` shows `time 1.6.0.1`, and similarly on [Stackage](https://www.stackage.org/lts-7.24/package/time-1.6.0.1).  Therefore, I was left very confused why Stack suddenly forgot `time` existed.

It took me a while but I eventually figured I should check the release notes in case it was intentional.  I saw this:

> Overriding GHC boot packages results in any other GHC boot
packages depending on it being no longer available as a dependency,
such packages need to be added explicitly when needed. See
[#4510] (#4510).

So that explained a lot, but figuring this out wasted a lot of time.  Could the error message be made a little more detailed?  It at least state that a package was pruned behind the scenes, and preferably include a reason for doing so and/or link to #4510 for rationale.

**Comment by dbaynard** [comment]
> Could the error message be made a little more detailed?

Yeah, that's a good idea. I knew about the issue and still got bitten yesterday (at least I was able to identify the solution quickly). There might be a straightforward way to indicate in that error that a boot package has been overriden. @Rufflewind would you be interested in implementing such a change?
