### ISSUE TITLE
Stack 2.1.1 bootstrap on macOS fails with no response for /hackage.fpcomplete.com/package/mintty-0.1.2.tar.gz

### ISSUE THREAD

**Issue by essandess** [commercialhaskell/stack#4907]
### General summary/comments (optional)

Stack 2.1.1 bootstrap fails with no response for /hackage.fpcomplete.com/package/mintty-0.1.2.tar.gz

See https://github.com/macports/macports-ports/pull/4633

### Steps to reproduce

This is the code used in a MacPorts Portfile bootstrap build of stack.

```
cd <stack source>
export PATH=/usr/bin:${PATH} ;
stack setup --stack-root ${workpath}/.${name} --allow-different-user \
    && stack build --stack-root ${workpath}/.${name} --allow-different-user"
```

### Expected

These are the documented steps for stack to build itself (setup/build/install) and they should work.

### Actual

Error log: https://paste.macports.org/69398e9e9981

```
foundation            > Installing library in /opt/local/var/macports/build/_Users_travis_build_macports_macports-ports_lang_stack/stack/work/.stack/snapshots/x86_64-osx/16b13c672a2b301278cf4e8f9fa778ee4cad11f82b66eb8980697fdf2658bff3/8.2.2/lib/x86_64-osx-ghc-8.2.2/foundation-0.0.21-KfBwx6uOo5C9SF7dT27C3l
foundation            > Registering library for foundation-0.0.21..
HttpExceptionRequest Request {
  host                 = "s3.amazonaws.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/hackage.fpcomplete.com/package/mintty-0.1.2.tar.gz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
```

### Stack version

2.1.1 from https://github.com/commercialhaskell/stack/releases/download/v2.1.1/stack-2.1.1-osx-x86_64.tar.gz

### Method of installation

Download from https://github.com/commercialhaskell/stack/releases/download/v2.1.1/stack-2.1.1-osx-x86_64.tar.gz

**Comment by snoyberg** [comment]
The continuation of the log contains the rest of the error message:

```
(ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 6, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "s3.amazonaws.com", service name: Just "443"): does not exist (nodename nor servname provided, or not known))
```

Looks like a network resolution error. Does this error message happen reliably? Are other tools able to download files from S3?

**Comment by snoyberg** [comment]
The continuation of the log contains the rest of the error message:

```
(ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 6, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "s3.amazonaws.com", service name: Just "443"): does not exist (nodename nor servname provided, or not known))
```

Looks like a network resolution error. Does this error message happen reliably? Are other tools able to download files from S3?

**Comment by essandess** [comment]
Thanks. It happened reliably across networks, but appears to be resolved now. I just pushed an amended commit and will close after this build works on Travis.

**Comment by essandess** [comment]
This is working now: https://paste.z0k.xyz/b4dc60085cd6

Thanks again.
