### ISSUE TITLE
stack downgrade

### ISSUE THREAD

**Issue by yairchu** [commercialhaskell/stack#4909]
Stack helpfully offers the `stack upgrade` command. It would be nice if it also had a "downgrade" command or option to install a specific stack version via the `upgrade` command.

My use case: I just recently upgraded to Stack v2.1.1, and [faced](https://github.com/commercialhaskell/stack/issues/3559) [four](https://github.com/commercialhaskell/stack/issues/4865) [different](https://www.reddit.com/r/haskell/comments/c5bcpd/your_old_commits_dont_build_with_stack_211_stack/) problems with it so far which I have apply time-consuming work-arounds (as deleting `.stack` and `.stack-work` and rebuilding). So I guess I should switch back to Stack v1 for now

**Comment by yairchu** [comment]
For folks looking for this: downloading [a release](https://github.com/commercialhaskell/stack/releases/tag/v1.9.3) and replacing the `stack` executable worked great for me!

**Comment by psibi** [comment]
Doesn't this work already via:

```
stack upgrade --binary-version <version
```

**Comment by yairchu** [comment]
Thanks! I missed the option somehow. Closing this and hopefully Google will bring other confused people to find you answer via this issue..
