### ISSUE TITLE
Build Stack with Cabal-3.0

### ISSUE THREAD

**Issue by hsyl20** [commercialhaskell/stack#4910]
We should build Stack against Cabal 3.* once it is released.

**Comment by hsyl20** [comment]
For some reason I've been trying to compile Stack against the not-yet released Cabal 3.0.

To avoid effort duplication, you can find my branch here: https://github.com/hsyl20/stack/tree/hsyl20-cabal3

**Comment by recursion-ninja** [comment]
`stack` is incompatible with projects that use features added to the `.cabal` file specification in `Cabal-3.0`. It would be useful to prioritize this so `stack` can build projects using modern feature, such as multiple public libraries.

**Comment by mpilgrem** [comment]
I am going to close this, because Stack is currently built with a dependency on `Cabal-3.8.1.0`.
