### ISSUE TITLE
mirrors.json expired: stack build has suddenly stopped working in all my projects

### ISSUE THREAD

**Issue by redfish64** [commercialhaskell/stack#4927]
$ stack build
Cabal file info not found for unagi-chan-0.4.1.0, updating
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Verification error: <repo>/mirrors.json is expired
Downloading root
Downloading timestamp
Downloading snapshot
Downloading mirrors
Verification error: <repo>/mirrors.json is expired
Downloading root
Downloading timestamp
Downloading snapshot
Downloading mirrors
Verification error: <repo>/mirrors.json is expired
Downloading root
Downloading timestamp
Downloading snapshot
Downloading mirrors
Verification error: <repo>/mirrors.json is expired
Downloading root
Downloading timestamp
Downloading snapshot
Downloading mirrors
Verification error: <repo>/mirrors.json is expired
Downloading root
Verification loop. Errors in order:
  <repo>/mirrors.json is expired
  <repo>/mirrors.json is expired
  <repo>/mirrors.json is expired
  <repo>/mirrors.json is expired
  <repo>/mirrors.json is expired

$ curl https://s3.amazonaws.com/hackage.fpcomplete.com/mirrors.json
{"signatures":[{"keyid":"772e9f4c7db33d251d5c6e357199c819e569d130857dc225549b40845ff0890d","method":"ed25519","sig":"xe6JjEZlp8ueG7l0XahzG6itTVNzoYxmfF43HNcb5EdFXBIqC7iRXjcsMseIhANnhv6SgovFZx7M1RiHokRzAw=="}],"signed":{"_type":"Mirrorlist","expires":"2019-06-30T23:59:59Z","mirrors":[{"urlbase":"http://hackage.fpcomplete.com/"},{"urlbase":"http://objects-us-east-1.dream.io/hackage-mirror/"}],"version":5}}

Notice above: **expires":"2019-06-30T23:59:59Z"**

**Comment by unhappychoice** [comment]
I think https://github.com/commercialhaskell/stack/issues/3731 is same.

**Comment by snoyberg** [comment]
Please see #4928 for explanation and workaround. I'd typically close this issue as a dupe, but I'm going to leave it open since it's towards the top of the issue tracker right now and may help others discover the workaround.
