### ISSUE TITLE
Improve error message concerning "Stack no longer supported Cabal versions below..."

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/stack#4931]
My Travis CI build for BNFC to test ghc-7.8 compilation suddenly fails with:
```
Stack no longer supported Cabal versions below 1.19.2,
but version 1.18.1.5was found.
This invocation will most likely fail.
To fix this, either use a newer version of Stack or a newer resolver
Acceptable resolvers: lts-3.0/nightly-2015-05-05 or later
```
(Btw: note the missing space in `1.18.1.5was`. And the dubious grammar `Stack no longer supported`; why past tense and not present tense `supports`?!)
The build log is here:
https://travis-ci.org/BNFC/bnfc/jobs/552087712
Last successful build was on May 24th:
https://travis-ci.org/BNFC/bnfc/jobs/536791354
The stack config file at https://github.com/BNFC/bnfc/blob/master/stack-7.8.4.yaml just says:
```
resolver: lts-2.22
packages:
- source
- testing
```
Here is my travis configuration file:
https://github.com/BNFC/bnfc/blob/master/.travis.yml

**Comment by snoyberg** [comment]
Please try pinning to Stack version 1.9.3 in your CI scripts. A PR to improve the error message to be clearer about this would definitely be welcome.

**Comment by andreasabel** [comment]
Thanks, this worked!

In the light of your solution, the automatic suggestion
```
To fix this, either use a newer version of Stack 
```
is the opposite of what fixes the problem.

> A PR to improve the error message to be clearer about this would definitely be welcome.

Sorry for not being helpful here; I have >500 Agda bugs to worry about.  :D Contributing to large open source projects only becomes efficient if one contributes regularly.

**Comment by snoyberg** [comment]
No problem, I've opened up https://github.com/commercialhaskell/stack/pull/4944
