### ISSUE TITLE
stack clean --full fails on Windows

### ISSUE THREAD

**Issue by psibi** [commercialhaskell/stack#4936]
Right now, the integration test build for Windows seem to be failing
because of `stack clean --full`.

On investigating the reason seems to be that, the stack process is
already opening the `stack.sqlite3` file and then trying to delete
it. While both OS X and Linux happily deletes the files, that doesn't
happen in Windows where an exception is thrown.

### Steps to reproduce

Only reproducible on Windows environment:

```
stack clean --full
```
### Expected

Successful delete of various files and exiting with a status code of 0.

### Actual

An exception is thrown.

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by dbaynard** [comment]
Closing — please reopen, @psibi, if this isn't fixed
