### ISSUE TITLE
Trouble loading CompilerPaths cache message

### ISSUE THREAD

**Issue by dtaskoff** [commercialhaskell/stack#4937]
Since updating to stack 2.1 on macOS, I'm getting the following output during `stack build`:
```
Trouble loading CompilerPaths cache: Control.Exception.Safe.throwString called with:
Compiler file metadata mismatch, ignoring cache
Called from:
  throwString (src/Stack/Storage.hs:492:8 in stack-2.1.1-AFL4re0D1GV4wdhlVT8Mqc:Stack.Storage)
```
However, the build doesn't fail.
What does the warning mean, and should I care about it, at all?

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by dtaskoff** [comment]
2.1.3 still gives me the mentioned output.

**Comment by robertmassaioli** [comment]
I just got this message in Bitbucket Pipelines. 

![Screen Shot 2021-04-14 at 4 31 02 pm](https://user-images.githubusercontent.com/149178/114664283-d4e14b80-9d3e-11eb-9744-df25e8664310.png)

For the record, I add Bitbucket Pipelines Caches for:

```
  caches:
    stack-home: ~/.stack
    stack: .stack-work
```

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time. If it is still a problem with the current version of Stack (2.15.3) please open a fresh issue.

**Comment by dtaskoff** [comment]
wtf

**Comment by mpilgrem** [comment]
To make management of open repository issues manageable, I am closing ones that appear to be stale and no longer applicable to current versions of Stack.
