### ISSUE TITLE
Set the Cabal version used to configure a project

### ISSUE THREAD

**Issue by etorreborre** [commercialhaskell/stack#494]
When I try to build my project I can see that it is configured with:
```
/app/ghc/bin/runhaskell -package=Cabal-1.18.1.5 ...
```

But my `Setup.hs` file requires `Cabal=1.22.3.0` (I'm on GHC 7.8 btw). Is there a way to select the cabal version to use?

**Comment by snoyberg** [comment]
This isn't implemented yet, but it's planned under #174. If you're interested in hacking on this it will happen sooner. Let me know, and we can start to sketch out what the implementation would look like.

Mind closing this and discussing under #174?

**Comment by etorreborre** [comment]
No problem I'll close this one.
