### ISSUE TITLE
Build of optparse-applicative-0.14.3.0 crashes.

### ISSUE THREAD

**Issue by kindaro** [commercialhaskell/stack#4947]
## General summary/comments (optional)

I have installed Stack via Nix, and my goal is to build [Aura](https://github.com/aurapm/aura). It requires `optparse-applicative` using the `lts-13.24` resolver, which specifies version `0.14.3` of that package. But it cannot be built, and therefore Aura also. In fact, there is a segmentation fault at a specific point in the build process. I tried to build the latest `optparse-applicative-0.15.0.0` with the same `stack.yaml` and it went smoothly

I do not know who to blame, Stack or Nix or random corruption of data due to cosmic particle rays. I am creating an issue here, but if you think it is Nix's problem, I will go that way too.

#### Way 1:

1. Install Stack via Nix with `nixpkgs-19.09pre184803.d567c486ca5`.
2. `cabal get optparse-applicative-0.14.3.0`
3. `stack build` with resolver `lts-13.24`.

#### Way 2:

After trying Way 1, you may launch the offending command directly:

    % ~/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 \
        --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1                      \
        build lib:optparse-applicative                                                     \
        --ghc-options " -fdiagnostics-color=always"

### Expected

Everything builds smoothly.

#### Way 1:
    ...
    While building package optparse-applicative-0.14.3.0 using:
          ...
        Process exited with code: ExitFailure (-11)

[Full `stack build --verbose` run.](https://gist.github.com/kindaro/afbb13eaef42cfe43dc6de27b96e5911)

#### Way 2:

    Preprocessing library for optparse-applicative-0.14.3.0..
    Building library for optparse-applicative-0.14.3.0..
    [ 8 of 16] Compiling Options.Applicative.Help.Core
    zsh: segmentation fault (core dumped)   --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build   

### Stack version

    2.1.1.1 x86_64 hpack-0.31.2

### Method of installation

    % nix-env --install stack

**Comment by snoyberg** [comment]
Looks like this is a bug in GHC or Cabal, not Stack, as the segfault is coming from one of those. I'd recommend reporting upstream.

**Comment by kindaro** [comment]
I cannot reproduce this anymore. Maybe it actually were cosmic rays.
