### ISSUE TITLE
network-info installs only from second try.

### ISSUE THREAD

**Issue by kindaro** [commercialhaskell/stack#4948]
## General summary/comments

I have installed Stack via Nix, and started working on a project that requires `network-info`. I am using the `lts-13.24` resolver, which specifies version `0.2.0.10` of that package. But I cannot obtain that package in my snapshot store because it builds only from the second try within the same stack context — that is, if build artifacts in `.stack-work` are kept. So, I can build this package by hand, but when Stack builds it as a dependency, or even for the global project, it does so in a temporary directory, erazing it after every failure!

I do not know who to blame, Stack or Nix or random corruption of data due to cosmic particle rays. I am creating an issue here, but if you think it is Nix's problem, I will go that way too.

#### Installing to global project:

    % cd ~
    % stack install network-info
    network-info> configure
    network-info> Configuring network-info-0.2.0.10...
    network-info> build
    network-info> Preprocessing library for network-info-0.2.0.10..
    network-info> Building library for network-info-0.2.0.10..
    network-info> [1 of 1] Compiling Network.Info
    network-info> 
    network-info> /run/user/1000/stack-61b53ba61262b8b1/network-info-0.2.0.10/src/Network/Info.hsc:46:10: warning: [-Wmissing-methods]
    network-info>     
    --  While building package network-info-0.2.0.10 using:
          /home/kindaro/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build --ghc-options " -fdiagnostics-color=always"
        Process exited with code: ExitFailure (-15)

#### Building manually:

    % cd /tmp
    % cabal get network-info-0.2.0.10
    Unpacking to network-info-0.2.0.10/
    % cd network-info-0.2.0.10
    % stack init
    Looking for .cabal or package.yaml files to use to init the project.
    Using cabal packages:
    - ./
    - test/

    Selecting the best among 15 snapshots...

    * Matches lts-13.27

    Selected resolver: lts-13.27
    Initialising configuration using resolver: lts-13.27
    Total number of user packages considered: 2
    Writing configuration to file: stack.yaml
    All done.
    % stack build
    Building all executables for `network-info-test' once. After a successful build of all of them, only specified executables will be rebuilt.
    network-info     > configure (lib)
    network-info     > Configuring network-info-0.2.0.10...
    network-info     > build (lib)
    network-info-test> configure (exe)
    network-info     > Preprocessing library for network-info-0.2.0.10..
    network-info     > Building library for network-info-0.2.0.10..
    network-info     > [1 of 1] Compiling Network.Info
    network-info-test> Configuring network-info-test-0.1...
    network-info-test> Warning: 'c-sources: ../cbits/network-unix.c' is a relative path outside of
    network-info-test> the source tree. This will not work when generating a tarball with 'sdist'.
    network-info-test> Warning: 'hs-source-dirs: ../src' is a relative path outside of the source
    network-info-test> tree. This will not work when generating a tarball with 'sdist'.
    network-info-test> Warning: 'include-dirs: ../cbits' is a relative path outside of the source
    network-info-test> tree. This will not work when generating a tarball with 'sdist'.
    network-info     > 
    network-info     > /tmp/network-info-0.2.0.10/src/Network/Info.hsc:46:10: warning: [-Wmissing-methods]
    network-infnetwork-info-test> build (exe) 
    network-info-test> Preprocessing executable 'network-info-test' for network-info-test-0.1..
    network-info-test> Building executable 'network-info-test' for network-info-test-0.1..
    network-info-test> [1 of 2] Compiling Network.Info
    network-info-test>             
    network-info-test> /tmp/network-info-0.2.0.10/test/../src/Network/Info.hsc:46:10: warning: [-Wmissing-methods]
    Completed 2 action(s).         

    --  While building package network-info-test-0.1 using:
          /home/kindaro/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build exe:network-info-test --ghc-options " -fdiagnostics-color=always"
        Process exited with code: ExitFailure (-15)

    --  While building package network-info-0.2.0.10 using:
          /home/kindaro/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build lib:network-info --ghc-options " -fdiagnostics-color=always"
        Process exited with code: ExitFailure (-15)

#### Building two times:

    % rm -rf .stack-work
    % stack build
    Building all executables for `network-info-test' once. After a successful build of all of them, only specified executables will be rebuilt.
    network-info-test> build (exe)
    network-info     > configure (lib)
    network-info-test> Preprocessing executable 'network-info-test' for network-info-test-0.1..
    network-info-test> Building executable 'network-info-test' for network-info-test-0.1..
    network-info-test> [2 of 2] Compiling Main
    network-info     > Configuring network-info-0.2.0.10...
    network-info-test> Linking .stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1/build/network-info-test/network-info-test ...
    network-info     > build (lib)
    network-info     > Preprocessing library for network-info-0.2.0.10..
    network-info     > Building library for network-info-0.2.0.10..
    network-info     > [1 of 1] Compiling Network.Info
    network-info-test> copy/register
    network-info-test> Installing executable network-info-test in /tmp/network-info-0.2.0.10/.stack-work/install/x86_64-linux-tinfo6/ad0826719842560062eb409ff118c8e657bd0946dd4df62cc600f3d3295a22e9/8.6.5/bin
    network-info     >        
    network-info     > /tmp/network-info-0.2.0.10/src/Network/Info.hsc:46:10: warning: [-Wmissing-methods]
    Completed 2 action(s).    

    --  While building package network-info-0.2.0.10 using:
          /home/kindaro/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-2.4.0.1 build lib:network-info --ghc-options " -fdiagnostics-color=always"
        Process exited with code: ExitFailure (-15)
    % stack build
    network-info> build (lib)
    network-info> Preprocessing library for network-info-0.2.0.10..
    network-info> Building library for network-info-0.2.0.10..
    network-info> copy/register
    network-info> Installing library in /tmp/network-info-0.2.0.10/.stack-work/install/x86_64-linux-tinfo6/ad0826719842560062eb409ff118c8e657bd0946dd4df62cc600f3d3295a22e9/8.6.5/lib/x86_64-linux-ghc-8.6.5/network-info-0.2.0.10-Hvah5LTyr9qJHUikKEcv5M
    network-info> Registering library for network-info-0.2.0.10..

### Expected

Everything builds smoothly.

### Actual

Only builds from the second try.

### Stack version

    2.1.1.1 x86_64 hpack-0.31.2

### Method of installation

    % nix-env --install stack

**Comment by mpilgrem** [comment]
CLosing given (a) the passage of time and (b) that other users are not reporting similar issues with the current version Stack 2.13.1.
