### ISSUE TITLE
stack setup fails sanity check on RHEL with /usr/bin/ld: cannot find -lgmp

### ISSUE THREAD

**Issue by EasyArray** [commercialhaskell/stack#4956]
Linux version 2.6.32-754.9.1.el6.x86_64 (mockbuild@x86-033.build.eng.bos.redhat.com) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Wed Nov 21 15:08:21 EST 2018

setup fails:
> % stack setup
> The GHC located at ~/.stack/programs/x86_64-linux/ghc-gmp4-8.2.2/bin/ghc-8.2.2 failed to compile a sanity check. Please see:
> 
>     http://docs.haskellstack.org/en/stable/install_and_upgrade/
> 
> for more information. Exception was:
> Received ExitFailure 1 when running
> Raw command: ~/.stack/programs/x86_64-linux/ghc-gmp4-8.2.2/bin/ghc-8.2.2 /tmp/stack-sanity-check27855/Main.hs -no-user-package-db
> Run from: /tmp/stack-sanity-check27855/
> Standard output:
> 
> [1 of 1] Compiling Main             ( /tmp/stack-sanity-check27855/Main.hs, /tmp/stack-sanity-check27855/Main.o )
> Linking /tmp/stack-sanity-check27855/Main ...
> Standard error:
> 
> /usr/bin/ld: cannot find -lgmp
> collect2: ld returned 1 exit status
> `gcc' failed in phase `Linker'. (Exit code: 1)

I'm on a shared machine so I cannot install, e.g., libgmp-dev. The gmp library is there, it's just named with a version:

> % locate libgmp.so
/usr/lib64/libgmp.so.3
/usr/lib64/libgmp.so.3.5.0

In fact, running stack setup --verbose finds this version of gmp:

> % stack setup --verbose
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
2019-07-12 10:55:22.622022: [debug] Checking for project config at: /afs/umich.edu/user/e/k/ekeshet/phosphorus/stack.yaml
2019-07-12 10:55:22.622365: [debug] Loading project config file stack.yaml
2019-07-12 10:55:22.646983: [debug] SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2019-07-11 14:55:22.646676071 UTC]
2019-07-12 10:55:22.647587: [debug] Using package location completions from a lock file
2019-07-12 10:55:22.831136: [debug] Running hpack on /afs/umich.edu/user/e/k/ekeshet/phosphorus/package.yaml
2019-07-12 10:55:22.834821: [debug] hpack output unchanged in /afs/umich.edu/user/e/k/ekeshet/phosphorus/phosphorus.cabal
2019-07-12 10:55:22.836040: [debug] Asking for a supported GHC version
2019-07-12 10:55:22.836706: [debug] Installed tools: 

>  - ghc-gmp4-8.2.2
> 2019-07-12 10:55:22.836849: [debug] Run process: /sbin/ldconfig -p
> 2019-07-12 10:55:22.838641: [debug] Process finished in 2ms: /sbin/ldconfig -p
> 2019-07-12 10:55:22.838803: [debug] Found shared library libtinfo.so.5 in 'ldconfig -p' output
> 2019-07-12 10:55:22.839148: [debug] Did not find shared library libtinfo.so.6
> 2019-07-12 10:55:22.839217: [debug] Did not find shared library libncursesw.so.6
> 2019-07-12 10:55:22.839279: [debug] Did not find shared library libgmp.so.10
> 2019-07-12 10:55:22.839330: [debug] Found shared library libgmp.so.3 in 'ldconfig -p' output
> 2019-07-12 10:55:22.839362: [debug] Potential GHC builds: gmp4
> 2019-07-12 10:55:22.839398: [debug] Found already installed GHC builds: gmp4
> 2019-07-12 10:55:22.839844: [debug] Performing a sanity check on: /afs/umich.edu/user/e/k/ekeshet/.stack/programs/x86_64-linux/ghc-gmp4-8.2.2/bin/ghc-8.2.2
> 2019-07-12 10:55:22.839993: [debug] Run process within /tmp/stack-sanity-check38391/: /afs/umich.edu/user/e/k/ekeshet/.stack/programs/x86_64-linux/ghc-gmp4-8.2.2/bin/ghc-8.2.2 /tmp/stack-sanity-check38391/Main.hs -no-user-package-db
> 2019-07-12 10:55:23.377567: [debug] Process finished in 538ms: /afs/umich.edu/user/e/k/ekeshet/.stack/programs/x86_64-linux/ghc-gmp4-8.2.2/bin/ghc-8.2.2 /tmp/stack-sanity-check38391/Main.hs -no-user-package-db
> 2019-07-12 10:55:23.387067: [error] The GHC located at /afs/umich.edu/user/e/k/ekeshet/.stack/programs/x86_64-linux/ghc-gmp4-8.2.2/bin/ghc-8.2.2 failed to compile a sanity check. Please see:
> 
>     http://docs.haskellstack.org/en/stable/install_and_upgrade/
> 
> for more information. Exception was:
> Received ExitFailure 1 when running
> Raw command: /afs/umich.edu/user/e/k/ekeshet/.stack/programs/x86_64-linux/ghc-gmp4-8.2.2/bin/ghc-8.2.2 /tmp/stack-sanity-check38391/Main.hs -no-user-package-db
> Run from: /tmp/stack-sanity-check38391/
> Standard output:
> 
> [1 of 1] Compiling Main             ( /tmp/stack-sanity-check38391/Main.hs, /tmp/stack-sanity-check38391/Main.o )
> Linking /tmp/stack-sanity-check38391/Main ...
> Standard error:
> 
> /usr/bin/ld: cannot find -lgmp
> collect2: ld returned 1 exit status
> `gcc' failed in phase `Linker'. (Exit code: 1)
> 

### Stack version

```
$ stack --version
Version 2.1.1, Git revision f612ea85316bbc327a64e4ad8d9f0b150dc12d4b (7648 commits) x86_64 hpack-0.31.2
```

**Comment by borsboom** [comment]
> /usr/lib64/libgmp.so.3
> /usr/lib64/libgmp.so.3.5.0

This is the shared library that allows the `ghc` executable itself to run (since it's dynamically linked with libgmp).

However, in order for GHC to be able to link an executable it produces, you also need the _development_ libraries for libgmp available.  This is what the `libgmp-dev` package would install.

**Comment by EasyArray** [comment]
Thanks! I'll look into installing the development library for just my single user.
