### ISSUE TITLE
Allow passing options to benchmarks

### ISSUE THREAD

**Issue by Toxaris** [commercialhaskell/stack#496]
I want to pass `--output something.html` to a criterion benchmark. `stack bench` seems to not support passing options to benchmarks, or maybe I'm missing something.

With cabal, I would do `cabal bench --benchmark-option="--output=$benchmark.html"`. If there were two benchmarks `bench1` and `bench2` in my project, that would build them both and then run them as `bench1 --output bench1.html` and `bench2 --output bench2.html`.

**Comment by snoyberg** [comment]
We have code in place for this to work for tests, it should be almost identical for benchmarks. Would you like to take a stab at implementing this?

**Comment by markus1189** [comment]
Implemented in #512.  The stack equivalent is:
```
$ stack bench --benchmark-arguments '--output=$benchmark.html'
```
@snoyberg I'd say close :)

**Comment by snoyberg** [comment]
Good call, thanks again @markus1189!

**Comment by Toxaris** [comment]
Ah excellent, I upgraded stack to get that feature and it seems to work fine. Sorry for the noise.
