### ISSUE TITLE
stack script interpreter manual could mention these gotchas for mac users

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#4965]
I was really mystified why one of my hledger addon stack scripts would not compile like the others; it always complained about the shebang line. The fix was to stop using CPP in it. https://gitlab.haskell.org/ghc/ghc/issues/6132, Can't use both shebang line and #ifdef declarations in the same file, was fixed a few years back - except on mac. 

Another one that I read about: shebang lines don't work on mac unless they refer to a compiled executable, so eg `#!/usr/local/bin/runhaskell` has no effect; it should be `#!/usr/bin/env runhaskell` instead.

https://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter could mention these.

**Comment by dbaynard** [comment]
Thanks, @simonmichael, and thanks for the PR!

**Comment by simonmichael** [comment]
#4966 was merged so I guess this can be closed.

**Comment by dbaynard** [comment]
Yeah, I guess GitHub doesn't parse "fixes" when it occurs in the title of the PR (TIL). Thanks!
