### ISSUE TITLE
Addition of a new OS support

### ISSUE THREAD

**Issue by ShalokShalom** [commercialhaskell/stack#4973]
Hi there :hugs: 
```

No setup information found for ghc-8.6.5 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.
Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
```

I am on KaOS.

**Comment by borsboom** [comment]
There aren't GHC bindists linked with libncurses6 being produced anymore.  Most Linux distributions now provide libtinfo6 (or symlink it from libncurses6).  Check if there's a libtinfo6 (aka terminfo) package, or compatibility package, in your distribution.  If not, you may be able to create a symlink yourself from` libncurses.so.6` to `libtinfo.so.6` yourself to work around this.

**Comment by ShalokShalom** [comment]
Terminfo is in our ncurses package, since we leave everything as upstream ships. 
core/ncurses 6.1-1      /usr/lib/terminfo

**Comment by borsboom** [comment]
Does `ldconfig -p` list `libtinfo.so.6`?

**Comment by ShalokShalom** [comment]
No. There are tons of Terminfo files in our ncurses packages, while no libtinfo.so.6 anywhere. 
So it is very likely no part of the official ncurses distribution. 
Which package does contain it?

**Comment by borsboom** [comment]
Not sure, that is beyond the scope of Stack :).  It does appear that Ubuntu/Debian install it from the ncurses source code (e.g. see https://packages.ubuntu.com/disco/libtinfo6).

You can likely work around this by adding a symlink, e.g.:
```
sudo ln -s libncursesw.so.6.1 /lib/x86_64-linux-gnu/libtinfo.so.6
```
(you may have to adjust the specific filenames and/or paths for your system).

**Comment by ShalokShalom** [comment]
Well, this goes over my head a little bit: https://github.com/KaOSx/core/blob/master/ncurses/PKGBUILD

So you are saying we have to deliberately install a file from this source code and it does not do so based on their default build instuctions?

**Comment by fuszenecker** [comment]
Same error on Raspberry Pi 3.
```fuszenecker@raspberrypi:~ $ stack build
No setup information found for ghc-8.6.5 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux-armv7', 'linux-armv7-ncurses6', 'linux-armv7-tinfo6'.
Supported versions: ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.6.3
```

**Comment by malyutinegor** [comment]
@fuszenecker Do `sudo ln -s /usr/lib/libncurses.so.6.1 /usr/lib/libtinfo.so.6` fix it?

**Comment by ShalokShalom** [comment]
You use a Debian based Distro, yes?

Then sudo apt install libtinfo6 should be enough
