### ISSUE TITLE
Link error when the same version on Hackage and in extra-deps

### ISSUE THREAD

**Issue by cblp** [commercialhaskell/stack#4989]
### Steps to reproduce

1. Suppose we have a package `bar-1` on Hackage.
2. A package that build-depends on `bar-1` from Hackage compiles and links successfully.
3. Now we want to test our package against the master version of `bar`, we add an extra-dep to the git repository of `bar`. Its master version has **different API**, but the **same version** `1`.
4. Now our package compiles successfully with the changed API of `bar`, but throws a linking error because of linking against the older, Hackage version of `bar-1`.

### Expected

Build ok.

### Actual

https://gist.github.com/cblp/bf1a3a46ec82925b0a48ad23abbde968

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

### Method of installation

Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by qrilka** [comment]
@cblp could you show some reproducible scenario? I couldn't reproduce the problem using your instructions - switching library triggers rebuild so I see a compilation failure so it doesn't go into linking phase.

**Comment by cblp** [comment]
Sorry, I went the same way, and couldn't reproduce. It seems to be more complex. Maybe the condition is so complex that nobody will step into it again. So I close this issue.
