### ISSUE TITLE
missing package libtinfo-dev on ubuntu:bionic

### ISSUE THREAD

**Issue by charala1** [commercialhaskell/stack#4991]
`stack build --only-snapshot` fails in an `ubuntu:bionic`- based docker image with

```
Foreign.Marshal.Compat.Repl
[0m[91mbase-compat                      > [ 94 of 112] Compiling Foreign.Compat
[0m[91mbase-compat                      > [ 95 of 112] Compiling Foreign.Compat.Repl
[0m[91mhaskeline                        > /usr/bin/ld.gold: error: cannot find -ltinfo
haskeline                        > collect2: error: ld returned 1 exit status
```

**Comment by borsboom** [comment]
`libtinfo-dev` is a dependency of **haskeline**, not of Stack or GHC.  There are lots of packages out there with various dependencies on system libraries, and Stack's installer can't install all of them (to see the full list of system dependencies for all packages in Stackage, check out [this script](https://github.com/commercialhaskell/stackage/blob/master/debian-bootstrap.sh)), so all it installs is the minimum to be able to use all of Stack's functionality and compile a basic Haskell program that uses base libraries included with GHC.
