### ISSUE TITLE
Installation of GHC broken

### ISSUE THREAD

**Issue by bitc** [commercialhaskell/stack#4993]
Hi, I am trying to build an old version of a project from CI that was configured with **stack 1.7.1** and **GHC 8.2.2**.

The following command has always worked (until yesterday):

    $ stack path --no-system-ghc --install-ghc --compiler ghc-8.2.2 --compiler-exe

But today I am getting this error on a clean machine:

```
$ stack --version
Version 1.7.1 x86_64 hpack-0.28.2
$ stack path --no-system-ghc --install-ghc --compiler ghc-8.2.2 --compiler-exe
Writing implicit global project config file to: /home/donna/.stack/global-project/stack.yaml
Note: You can change the snapshot via the resolver field there.
Using latest snapshot resolver: lts-14.0
Downloaded lts-14.0 build plan.    
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.2.2.                                      
Installed GHC.                                                                 
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading root                                                                                 
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/                                 
Downloading timestamp                                                                            
Downloading snapshot                                                                             
Downloading mirrors                                                                              
Cannot update index (no local copy)                                                              
Downloading index                                                                                
Updated package index downloaded                                                                 
Update complete                                                                                  
Populated index cache.    
Unable to load cabal files for snapshot

----
Deleting cached snapshot file: /home/donna/.stack/build-plan/lts-14.0.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new
----

Unable to parse cabal file for co-log-0.3.0.0@sha256:0eb5cf2598c3673f39a8e967a6a4f5043f4d1f1fcb50a844653c34fcf0cb068a,4508

- 0:0: Unsupported cabal-version. See https://github.com/haskell/cabal/issues/4899.

```

**Comment by mihaimaruseac** [comment]
Seeing the error message I also remember that Cabal just got upgraded to 3.0. Maybe that's the issue.

Also, can you try upgrading stack to a newer version? It's very likely that support for new Cabal versions is only available in more modern versions of Stack.

**Comment by bitc** [comment]
Thanks for the reply.
I am not using cabal at all. I am just invoking `stack` executable directly with the single command above in order to install GHC. That is what is failing. Until today it has always worked fine.

When I try with stack 2.1.3 then it does succesfully install GHC 8.2.2, but it would be nice if stack 1.7.1 would continue to work because in my project I have stack locked to specific versions in previous commits in order to guarantee reproducible builds, and i find it very valuable to be able to build these old commits

**Comment by qrilka** [comment]
@bitc Stack uses `Cabal` library to parse cabal files and do some other stuff. That means that any project using some features from new Cabal and not supported by older ones could easily cause Stack failure. As you could see on Hackage stack-1.7.1 is compiled with Cabal-2.2 and any non backward compatible feature from Cabal-2.4 or higher will be a problem for `stack-1.7.1`. The same applies for `cabal-version` attribute defined in a cabal file - you could see that http://hackage.haskell.org/package/co-log-0.3.0.0/co-log.cabal sets it to 2.4

**Comment by bitc** [comment]
Ok, but I'm not using any stack project or cabal project or anything. I'm just running the following stack command from my home directory:

    $ stack path --no-system-ghc --install-ghc --compiler ghc-8.2.2 --compiler-exe

All it is supposed to do is download the GHC distribution tarball and extract it to my `~/.stack` directory. I guess I don't understand why this needs to do any "cabal" related work, or why it is touching this "co-log" package.

Thank you for your help so far

**Comment by qrilka** [comment]
@bitc you're using Stack and from the log you could see `Downloaded lts-14.0 build plan.` and that snapshot is a quite recent one. You could use a snapshot corresponding to GHC-8.2.2 (the latest one being lts-11.22) or just use `stack setup ghc-8.2.2` to setup GHC.

**Comment by bitc** [comment]
I added `--resolver lts-11.22` to the command and now it works! Thank you!

**Comment by snoyberg** [comment]
Looks like this is resolved, closing.

**Comment by blackgnezdo** [comment]
I'm also hitting this while trying to use `stack-1.7.1` and `lts-14.4`. Does each LTS need to have a minimal version of `stack` that it speaks baked in?

The command `/bin/sh -c apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442 &&     apt-get update &&     apt-get install -y         libsnappy-dev         libncurses5-dev         libgmp-dev         libcurl3-dev         zlib1g-dev         curl         unzip         netbase         &&     curl -O -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz &&     tar zxf stack-1.7.1-linux-x86_64.tar.gz -C /usr/local/bin stack-1.7.1-linux-x86_64/stack --strip 1 &&     curl -O -L https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip &&     unzip -d /usr/local protoc-3.2.0-linux-x86_64.zip bin/protoc &&     chmod 755 /usr/local/bin/protoc &&     curl -O https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz &&     tar zxf libtensorflow-cpu-linux-x86_64-1.14.0.tar.gz -C /usr/local &&     ldconfig &&     stack setup &&     stack test --only-dependencies' returned a non-zero code: 1`

Produces this output:
```
Downloading lts-14.4 build plan ...
Downloaded lts-14.4 build plan.
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-8.6.5 ...
ghc-8.6.5: download has begun
...
Downloaded ghc-8.6.5.
Unpacking GHC into /root/.stack/programs/x86_64-linux/ghc-8.6.5.temp/ ...
Configuring GHC ...
Installing GHC ...
Installed GHC.
stack will use a sandboxed GHC it installed
For more information on paths, see 'stack path' and 'stack exec env'
To use this GHC and packages outside of a project, consider using:
stack ghc, stack ghci, stack runghc, or stack exec
Updating package index Hackage (mirrored at https://s3.amazonaws.com/hackage.fpcomplete.com/) ...
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading root
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Downloading snapshot
Downloading mirrors
Cannot update index (no local copy)
Downloading index
Updated package index downloaded
Update complete
Populating index cache ...
Populated index cache.
Unable to load cabal files for snapshot

----
Deleting cached snapshot file: /root/.stack/build-plan/lts-14.4.yaml
Recommendation: try running again. If this fails again, open an upstream issue at:
https://github.com/fpco/lts-haskell/issues/new
----

Unable to parse cabal file for co-log-0.3.0.0@sha256:0eb5cf2598c3673f39a8e967a6a4f5043f4d1f1fcb50a844653c34fcf0cb068a,4508

- 0:0: Unsupported cabal-version. See https://github.com/haskell/cabal/issues/4899.
```

I don't believe retrying would change anything as this is a fresh CI machine (nor do I have access to that system)
