### ISSUE TITLE
Need to respect buildable: False and flags for dependency tracking

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#50]
I haven't tracked down exactly what the problem is yet, but somehow I'm seeing that vector-algorithms's dependency on mwc-random - which is in an executable which is off by default - is causing build failures.

**Comment by ghorn** [comment]
Just to be clear, is this a `wontfix`?

**Comment by snoyberg** [comment]
This is a `cantfix` because there's a bug upstream in Cabal. We're purposely doing something dumb because, otherwise, Cabal breaks.

**Comment by ghorn** [comment]
The cabal bug looks like it's fixed. Should this issue be reopened?

**Comment by mgsloan** [comment]
@ghorn Good point, I've opened https://github.com/commercialhaskell/stack/issues/2184
