### ISSUE TITLE
Remove `--haddock` and `--no-haddock` options from `stack haddock` command

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#500]
Hi. These two options don't seem to make sense to me, would be nice to remove them from `stack haddock --help` output.

Thanks!

**Comment by snoyberg** [comment]
This should be a relatively isolated part of the code base. Want to take a stab at implementing this? I believe almost all of the code will be in src/main/Main.hs.

**Comment by k-bx** [comment]
Ok, will do!
