### ISSUE TITLE
stack hoogle --server should disable security headers

### ISSUE THREAD

**Issue by taasan** [commercialhaskell/stack#5021]
### General summary/comments (optional)

`stack hoogle server` adds security headers. Browser upgrades to https  when you submit the search form.

`stack hoogle -- server` has an option `--no-security-headers` to turn off security headers.

### Steps to reproduce

1. Run `stack hoogle --server`
2. Open http://localhost:8080/
3. Click `Search` button

### Expected

Browser should not upgrade to https

### Actual

Browser upgrades to https

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because I cannot see that Stack does anything other than call `hoogle` with the specified arguments or with `server --local --port 8080` if `--server` is specified. Consequently, if this is an issue, it appears to me to be an upstream one.
