### ISSUE TITLE
Cannot Find -lgmp Error

### ISSUE THREAD

**Issue by XinhuaZhang** [commercialhaskell/stack#5027]
I was on vacation in the past week. After I come back, there is something wrong. I removed stack, corresponding folders and reinstalled it. Then I got this error.  Google results show that people solved this problem by installing libgmp-dev. Because I am not a root user, I compiled gmp from source and installed it to my local directory. PATH and LD_LIBRARY_PATH are correct.  The OS is CentOS Linux release 7.4.1708 (Core). The weird thing is that it worked before the vacation. I wonder if it is because I did something wrong when I compiled and installed it from source?  It looks like that GHC was successfully installed, but it failed to compile a sanity check. The libgmp is instlled in the local directory. Is this a problem?

rm -r ~/.stack
rm -r .stack-work

stack setup

Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.6.5.                                      
rts-1.0: Warning: .:464:1: The field "hugs-options" is deprecated. hugs isn't supported anymore
Installed GHC.    
The GHC located at /home/xzhang/.stack/programs/x86_64-linux/ghc-8.6.5/bin/ghc-8.6.5 failed to compile a sanity check. Please see:

    http://docs.haskellstack.org/en/stable/install_and_upgrade/

for more information. Exception was:
Received ExitFailure 1 when running
Raw command: /home/xzhang/.stack/programs/x86_64-linux/ghc-8.6.5/bin/ghc-8.6.5 /tmp/stack-sanity-check14921/Main.hs -no-user-package-db
Run from: /tmp/stack-sanity-check14921/
Standard output:

[1 of 1] Compiling Main             ( /tmp/stack-sanity-check14921/Main.hs, /tmp/stack-sanity-check14921/Main.o )
Linking /tmp/stack-sanity-check14921/Main ...
Standard error:

/usr/bin/ld.gold: error: cannot find -lgmp
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)

**Comment by XinhuaZhang** [comment]
Well, I added LIBRARY_PATH and it solved the problem.

**Comment by harrypunk** [comment]
> Well, I added LIBRARY_PATH and it solved the problem.

What is the value? Same problem here.

**Comment by XinhuaZhang** [comment]
> > Well, I added LIBRARY_PATH and it solved the problem.
> 
> What is the value? Same problem here.

The path to the libgmp. In my case, it equals to $LD_LIBRARY_PATH

**Comment by ju-sh** [comment]
What is the value of those variables though? For me both are empty.
