### ISSUE TITLE
Option to upload package candidates to Hackage

### ISSUE THREAD

**Issue by yairchu** [commercialhaskell/stack#5032]
`stack upload` should have an option to upload a package candidate rather than a package.

Note that hackage doesn't generate haddocks for package candidates automatically, but one can upload them manually and it would be very useful if the upload would also do that, which can be done by

    cp -r `stack path --dist-dir`/doc/html/PACKAGE PACKAGE-VERSION-docs
    tar -c -v -z --format=ustar -f PACKAGE-VERSION-docs.tar.gz PACKAGE-VERSION-docs
    curl -X PUT -H 'Content-Type: application/x-tar' -H 'Content-Encoding: gzip' --data-binary "@PACKAGE-VERSION-docs.tar.gz" "https://USERNAME:PASSWORD@hackage.haskell.org/package/PACKAGE-VERSION/candidate/docs"

(command based on [a script](https://github.com/ChrisPenner/dotfiles/blob/master/bin/haddock-up) by @ChrisPenner, which is for uploading docs for non-candidate packages)

**Comment by dbaynard** [comment]
Possibly one for the [wishlist](https://github.com/commercialhaskell/stack/wiki/Wishlist)?

**Comment by mpilgrem** [comment]
I am closing as this feature was implemented in Stack 2.7.1.
