### ISSUE TITLE
Consider versions "2.1" and "2.1.0" as same

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#504]
I just had a minor but confusing problem that I've put `protocol-buffers-2.1` into `extra-deps`, but got a message `Didn't see protocol-buffers-2.1 in your package indices, updating and trying again` from `stack build`. The reason, as you might guess, is that it couldn't match versions `2.1` and `2.1.0`.

Please confirm that improving version-matcher to handle this would be a way to go. If so – I could take a look at this issue later.

**Comment by snoyberg** [comment]
Unfortunately, I don't think we can do that, since as far as Hackage and cabal are concerned, those are unique versions. However, the error message here could certainly be improved to indicate "did you mean 2.1.0." What do you think about going that route instead?

**Comment by k-bx** [comment]
@snoyberg yes, that seems like the best way to go. Ok, I'll work on this right after a previous bug I've committed myself to :)

**Comment by snoyberg** [comment]
Awesome :)

**Comment by bergmark** [comment]
An alternative is showing the available versions closest to the one you specified, then it might also give a suggestion for 2.0 and 2.2 if 2.1 doesn't exist
