### ISSUE TITLE
Question: How can I safely remove packages installed with stack-2.x?

### ISSUE THREAD

**Issue by lexi-lambda** [commercialhaskell/stack#5040]
I asked this question [on the mailing list](https://groups.google.com/d/msg/haskell-stack/U0XwSaVxgLc/o26lDflxAAAJ) a couple weeks ago, but I didn’t get a response, so I’m asking it here, instead. I am wondering what the proper procedure is to safely remove an installed package on recent versions of stack. I’d like to do this for two reasons:

  1. Sometimes I’d like to clean out old packages for old snapshots I no longer care about.

  2. I am currently trying to reproduce a bug in stack, and I think it may depend on package installation order. It’s very painful to have to blow *everything* away every time I want to try a different installation order.

On older versions of stack, I’d just delete the relevant subdirectories in the `~/.stack/snapshots` directory, but (1) that’s harder to do now that those directories don’t have human-readable names and (2) it seems that deleting those directories leaves something somewhere in an invalid state (due to the source of truth being the pantry database?) that I do not know how to fix without blowing all of `~/.stack` away and starting over.

Is there a way to do this? I’d very much like to reproduce the aforementioned bug, since I’ve hit it a couple times, and it’s a real showstopper.

**Comment by dbaynard** [comment]
Thanks for the issue. It's been a while since I looked at `pantry` stuff; I suspect there's no ready tool.

@qrilka what do you think?

**Comment by qrilka** [comment]
Unfortunately currently I don't think we have a good way to resolve this. While discussing some possible ways to implement GC for `~/.stack` there was an idea to track last time of access for a particular package in a snapshot but there is nothing like that in the code base so that needs to be implemented. In the current version we have only files on a file system and you can't do much with only file creation times.

**Comment by lexi-lambda** [comment]
In that case, I have a different but related question, since maybe this is an XY problem. Let’s say something somehow goes wrong while building a package (from Hackage), and I want to ask `stack` to rebuild it. Do I currently have no other choice than to blow away the entirety of `~/.stack`?

**Comment by qrilka** [comment]
It's hard to say without clear picture about what "goes wrong". But if somehow you get a package incorrectly built and registered then to force its rebuild you could use a hack `stack exec ghc-pkg <broken-package>` (with extra flags if you need those).

**Comment by psibi** [comment]
Similar to what Kirill said, to remove an offending package - I use the unregister sub-command from the directory where I tried to build it:
```
stack exec -- ghc-pkg unregister <broken-pkg>
```

**Comment by yairchu** [comment]
@psibi thanks so much! you just saved me from the dreaded 2 hours feedback loop and made Haskell and stack viable options again! I also had to remove some `.dylib` files in my `~/.stack` for the trick to work. Next time I need it - I'll document all the steps.
