### ISSUE TITLE
Is runghcjs necessary?

### ISSUE THREAD

**Issue by cblp** [commercialhaskell/stack#5048]
## 1. Undocumented `compiler` syntax

```
option --compiler: Failed to parse compiler: ghcjs
option --compiler: Failed to parse compiler: ghcjs-8.4.0.1
```

Okay, I read the source code

## 2. No compiler found

I run with `--compiler=ghcjs-8.4.0.1_ghc-8.4.4` and get
```
I don't know how to install GHC on your system configuration, please install manually
```

But I didn't ask it to install GHC, did I?

I add `--no-install-ghc` and get
```
No compiler found, expected minor version match with ghcjs-8.4.0.1_ghc-8.4.4 (x86_64) (based on resolver setting in /home/cblp/dev/ron/ghc-8.4.yaml).
To install the correct GHC into /home/cblp/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```

Okay, I add `--system-ghc`, but nothing changes, it still suggests `--system-ghc`.

## 3. runghcjs

Only when I started to debug stack, I found
```
Not using compiler at "/opt/ghcjs/8.4.0.1/bin/ghcjs-8.4.0.1": Found an invalid compiler at "/opt/ghcjs/8.4.0.1/bin/ghcjs-8.4.0.1": Control.Exception.Safe.throwString called with:

Could not find any of: ["/opt/ghcjs/8.4.0.1/bin/runghcjs-8.4.0.1","/opt/ghcjs/8.4.0.1/bin/runghcjs"]
```

But GHCJS package is not supplied with `runghcjs` program. Is it necessary? Is the problem in stack requiring `runghcjs` or in GHCJS package not providing `runghcjs`?

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by snoyberg** [comment]
The next version of Stack will no longer have GHCJS support, closing.
