### ISSUE TITLE
Add --resolver param to `stack build`

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#505]
Stack comes with lts-2.9 resolver in `stack.yaml`. I know I already have a lot installed for lts-2.16 set of packages, and using this resolver would let me:

1. save disk space
2. save build time

Right now I had to edit `stack.yaml`, but what I'd like instead is to be able to do `stack build --resolver lts-2.16`.

As usual, if this seems like a good feature, I can put that on my queue and implement.

**Comment by snoyberg** [comment]
Did you try running that command? It should actually work exactly as you typed it :)

**Comment by snoyberg** [comment]
Sorry, it seems that `--resolver lts-2.16` has to come before `build`, so `stack --resolver lts-2.16 build`. I'm not sure why that's the case, @chrisdone any thoughts?

**Comment by k-bx** [comment]
Oops, I only read `stack build --help` and didn't find resolver there.

**Comment by snoyberg** [comment]
I'll open a separate issue about allowing `--resolver` to be placed either before or after the command.
