### ISSUE TITLE
Build fails in complex environment (Windows docker)

### ISSUE THREAD

**Issue by boris-stepanov** [commercialhaskell/stack#5050]
### General summary
I cannot build a project in prepared docker environment. During dependencies check Stack fails with an error "[info] Unable to get a write lock on the Stack database, waiting..."

### Conditions

 1. VMware -> Windows 10 -> docker container. [systeminfo]
 2. stack 2.1.3 (from https://get.haskellstack.org/stable/windows-x86_64.zip)
 3. Local project

### Steps to reproduce

 1. Place `config.yaml` into `c:/sr/`:
 ```yaml
 build:
   split-objs: false
   library-profiling: false
   executable-profiling: false
 allow-different-user: true
 arch: i386
 ```
 2. Place `stack.yaml` into `c:/sr/global-project`:
 ```yaml
 resolver: lts-14.6
 packages: []
 ```
 3. Call `stack install http-client-tls microlens-platform free optparse-applicative file-embed aeson terminal-size`
 4. Create simple "hello-world" cabal project, with dependencies specified above, run `stack install`

### Comments
I can't really reproduce it on my own workstation, but I've patched filelock package and rebuilt Stack with it. Here are the links on `stack install --verbose` [output](https://gist.github.com/boris-stepanov/4bb109caab0e7e69e03fabbc70c31811) and patched filelock [sources](https://gist.github.com/boris-stepanov/ee2a637f84ba7cde008d1a33dea0ac23).

[systeminfo]: https://gist.github.com/boris-stepanov/08f085444dae145fbe499fb3500a89fb

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and because Stack no longer supports 32-bit Windows. If this problem happens again with current versions, please open a fresh issue.
