### ISSUE TITLE
`stack build --test --coverage --haddock` fails to produce test coverage report

### ISSUE THREAD

**Issue by bagrounds** [commercialhaskell/stack#5057]
### General summary/comments
Attempting to produce test coverage and haddock in a single command fails, while it succeeds if attempted in separate commands.

### Steps to reproduce

A1) This successfully produces a test coverage report:
```bash
$ stack build --test --coverage
$ stack path --local-hpc-root
/home/bryan/Projects/gitlab.com/bagrounds/tic-tac-toe/.stack-work/install/x86_64-linux/928db171c7a4c185b8d5d9d466fe58460812a4aa4c15034bd7e21052090d5311/8.6.5/hpc
$ find .stack-work/install -name hpc
.stack-work/install/x86_64-linux/928db171c7a4c185b8d5d9d466fe58460812a4aa4c15034bd7e21052090d5311/8.6.5/hpc
$ tar -cf - $(stack path --local-hpc-root) | cksum
2164977558 61440
```

B1) This (after A1) produces docs and does not delete the test coverage report from step A1
```bash
$ stack build --haddock
$ find .stack-work/install -name doc
.stack-work/install/x86_64-linux/103de1c3fc80aeede1c5f0c7a6f685574df86f089eb2dd2ddfbc2a982f4c96f5/8.6.5/doc
.stack-work/install/x86_64-linux/928db171c7a4c185b8d5d9d466fe58460812a4aa4c15034bd7e21052090d5311/8.6.5/doc
$ stack path --local-hpc-root
/home/bryan/Projects/gitlab.com/bagrounds/tic-tac-toe/.stack-work/install/x86_64-linux/928db171c7a4c185b8d5d9d466fe58460812a4aa4c15034bd7e21052090d5311/8.6.5/hpc
$ tar -cf - $(stack path --local-hpc-root) | cksum
2164977558 61440
```

B2) This (after A1) produces docs and an additional (broken) test coverage report - but does not delete the test coverage report from step A1
```bash
$ stack build --haddock --coverage
$ stack path --local-hpc-root
/home/bryan/Projects/gitlab.com/bagrounds/tic-tac-toe/.stack-work/install/x86_64-linux/928db171c7a4c185b8d5d9d466fe58460812a4aa4c15034bd7e21052090d5311/8.6.5/hpc
$ html2text .stack-work/install/x86_64-linux/103de1c3fc80aeede1c5f0c7a6f685574df86f089eb2dd2ddfbc2a982f4c96f5/8.6.5/hpc/index.html
No hpc_index.html files found in "/home/bryan/Projects/gitlab.com/bagrounds/
tic-tac-toe/.stack-work/install/x86_64-linux/
103de1c3fc80aeede1c5f0c7a6f685574df86f089eb2dd2ddfbc2a982f4c96f5/8.6.5/hpc".
$ tar -cf - $(stack path --local-hpc-root) | cksum
2164977558 61440
```

B3) This (after A1) produces docs and a (differently broken) test coverage report - but also does not delete the test coverage report from step A1
```bash
$ stack build --test --coverage --haddock
$ stack path --local-hpc-root
/home/bryan/Projects/gitlab.com/bagrounds/tic-tac-toe/.stack-work/install/x86_64-linux/928db171c7a4c185b8d5d9d466fe58460812a4aa4c15034bd7e21052090d5311/8.6.5/hpc
$ tar -cf - $(stack path --local-hpc-root) | cksum
2164977558 61440
```

A2) This (instead of A1) produces a broken test coverage report similar to the one from B3, but does not produce a valid test coverage report similar to A1
```bash
$ stack build --test --coverage --haddock
$ stack path --local-hpc-root                      
/home/bryan/Projects/gitlab.com/bagrounds/tic-tac-toe/.stack-work/install/x86_64-linux/928db171c7a4c185b8d5d9d466fe58460812a4aa4c15034bd7e21052090d5311/8.6.5/hpc
# notice that the path reported above does not exist!
$ find .stack-work/install -name hpc
.stack-work/install/x86_64-linux/103de1c3fc80aeede1c5f0c7a6f685574df86f089eb2dd2ddfbc2a982f4c96f5/8.6.5/hpc
```

Verbose logs were captured in CI, and can be found here:
* [Test coverage and haddock in same command fail to produce test coverage](https://gitlab.com/bagrounds/tic-tac-toe/-/jobs/319750706)
* [Test coverage and haddock in different commands successfully produce test coverage](https://gitlab.com/bagrounds/tic-tac-toe/-/jobs/319764682)

### Expected
Adding `--haddock` to `stack build --test --coverage` should produce haddock in addition to producing test coverage (or fail immediately if this combination of flags is not expected to work).

### Actual
Adding `--haddock` to `stack build --test --coverage` does produce haddock, but does not produce test coverage.

### Stack version
I originally found this problem in CI using the `fpco/stack-build:lts-14.4` docker image.

I was also able to reproduce the problem locally:
```bash
$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.9 (stretch)
Release:        9.9
Codename:       stretch
$ uname -r
4.9.0-6-amd64
$ cat /proc/version 
Linux version 4.9.0-6-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Debian 4.9.88-1+deb9u1 (2018-05-07)
```

**Comment by brandon-leapyear** [comment]
Possibly related to implicit snapshots? https://github.com/commercialhaskell/stack/issues/4863 https://github.com/commercialhaskell/stack/issues/5181

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and because I have recently closed https://github.com/commercialhaskell/stack/issues/4838 (`stack build --haddock --test --coverage`) because it works as expected with Stack 2.15.5 on Stack's own repository.
