### ISSUE TITLE
Document how to install specific versions of stack

### ISSUE THREAD

**Issue by sjakobi** [commercialhaskell/stack#5067]
I want to pin the version of stack I'm using in a CI script (AppVeyor). I was looking for instructions on installing specific versions in https://docs.haskellstack.org/en/stable/install_and_upgrade/ but didn't find any.

For now I went with downloading https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-windows-x86_64.zip, but I'm not sure whether that's the recommended way.

**Comment by mattaudesse** [comment]
Yep, I believe most people either use a static link like you've done or incorporate some environment variables to adjust the version portions of their URI.

Any interest in submitting a docs PR?

**Comment by Fyrbll** [comment]
I haven't been involved in this discussion, but I'm interested in this as a possible first contribution to stack.

Based on the comments up to now, I'm thinking of adding a sub-section called "Install older versions" to the [install and upgrade guide](https://docs.haskellstack.org/en/stable/install_and_upgrade/). 

The sub-section will say:
"To install a specific version of stack, navigate to the desired version on [the GitHub release page](https://github.com/fpco/stack/releases), and click the appropriate link under its Assets drop-down menu.

Alternatively, use the URL `https://github.com/commercialhaskell/stack/releases/download/vVERSION/stack-VERSION-PLATFORM.EXTENSION` 
For example, if the tarball for stack 2.1.0.1, osx-x86_64 is at `https://github.com/commercialhaskell/stack/releases/download/v2.1.0.1/stack-2.1.0.1-osx-x86_64.tar.gz`"

Does this look okay?

**Comment by sjakobi** [comment]
That seems like a good start! :)

I think a snippet that people can just copy into their `appveyor.yml` would be very helpful. Feel free to use `dhall`'s [`appveyor.yml`](https://github.com/dhall-lang/dhall-haskell/blob/1079b7a3a7a6922f72a373e47daf6f1b74f128b1/appveyor.yml#L22-L28) for inspiration.
