### ISSUE TITLE
Can't install hoogle on Windows10.

### ISSUE THREAD

**Issue by zhangshenhua** [commercialhaskell/stack#5072]
### Steps to reproduce
C:\Windows\system32>stack install hoogle

### Expected
Be installed.

### Actual
C:\Windows\system32>stack install hoogle
network            > configure
network            > [1 of 2] Compiling Main             ( C:\\Users\zhang\AppData\Local\Temp\stack7992\network-2.8.0.1\Setup.hs, C:\\Users\zhang\AppData\Local\Temp\stack7992\network-2.8.0.1\.stack-work\dist\e626a42b\setup\Main.o )
network            > [2 of 2] Compiling StackSetupShim   ( C:\\sr\setup-exe-src\setup-shim-Z6RU0evB.hs, C:\\Users\zhang\AppData\Local\Temp\stack7992\network-2.8.0.1\.stack-work\dist\e626a42b\setup\StackSetupShim.o )
network            > Linking C:\\Users\\zhang\\AppData\\Local\\Temp\\stack7992\\network-2.8.0.1\\.stack-work\\dist\\e626a42b\\setup\\setup.exe ...
network            > Configuring network-2.8.0.1...
network            > configure: WARNING: unrecognized options: --with-compiler
network            > configure: loading site script /usr/local/etc/config.site
network            > checking build system type... x86_64-w64-mingw32
network            > checking host system type... x86_64-w64-mingw32
network            > checking for gcc... C:\Users\zhang\AppData\Local\Programs\stack\X86_64~1\GHC-86~1.5\lib\../mingw/bin\gcc.exe
network            > checking whether the C compiler works... yes
network            > checking for C compiler default output file name... a.exe
network            > checking for suffix of executables... .exe
network            > checking whether we are cross compiling... no
network            > checking for suffix of object files... o
network            > checking whether we are using the GNU C compiler... yes
network            > checking whether C:\Users\zhang\AppData\Local\Programs\stack\X86_64~1\GHC-86~1.5\lib\../mingw/bin\gcc.exe accepts -g... yes
network            > checking for C:\Users\zhang\AppData\Local\Programs\stack\X86_64~1\GHC-86~1.5\lib\../mingw/bin\gcc.exe option to accept ISO C89... none needed
network            > checking for an ANSI C-conforming const... yes
network            > checking how to run the C preprocessor... C:\Users\zhang\AppData\Local\Programs\stack\X86_64~1\GHC-86~1.5\lib\../mingw/bin\gcc.exe -E
network            > checking for grep that handles long lines and -e... /usr/bin/grep
network            > checking for egrep... /usr/bin/grep -E
network            > checking for ANSI C header files... yes
network            > checking for sys/types.h... yes
network            > checking for sys/stat.h... yes
network            > checking for stdlib.h... yes
network            > checking for string.h... yes
network            > checking for memory.h... yes
network            > checking for strings.h... yes
network            > checking for inttypes.h... yes
network            > checking for stdint.h... yes
network            > checking for unistd.h... yes
network            > checking fcntl.h usability... yes
network            > checking fcntl.h presence... yes
network            > checking for fcntl.h... yes
network            > checking limits.h usability... yes
network            > checking limits.h presence... yes
network            > checking for limits.h... yes
network            > checking for stdlib.h... (cached) yes
network            > checking for sys/types.h... (cached) yes
network            > checking for unistd.h... (cached) yes
network            > checking winsock2.h usability... yes
network            > checking winsock2.h presence... yes
network            > checking for winsock2.h... yes
network            > checking ws2tcpip.h usability... yes
network            > checking ws2tcpip.h presence... yes
network            > checking for ws2tcpip.h... yes
network            > checking arpa/inet.h usability... no
network            > checking arpa/inet.h presence... no
network            > checking for arpa/inet.h... no
network            > checking netdb.h usability... no
network            > checking netdb.h presence... no
network            > checking for netdb.h... no
network            > checking netinet/in.h usability... no
network            > checking netinet/in.h presence... no
network            > checking for netinet/in.h... no
network            > checking netinet/tcp.h usability... no
network            > checking netinet/tcp.h presence... no
network            > checking for netinet/tcp.h... no
network            > checking sys/socket.h usability... no
network            > checking sys/socket.h presence... no
network            > checking for sys/socket.h... no
network            > checking sys/uio.h usability... no
network            > checking sys/uio.h presence... no
network            > checking for sys/uio.h... no
network            > checking sys/un.h usability... no
network            > checking sys/un.h presence... no
network            > checking for sys/un.h... no
network            > checking linux/can.h usability... no
network            > checking linux/can.h presence... no
network            > checking for linux/can.h... no
network            > checking linux/tcp.h usability... no
network            > checking linux/tcp.h presence... no
network            > checking for linux/tcp.h... no
network            > checking net/if.h usability... no
network            > checking net/if.h presence... no
network            > checking for net/if.h... no
network            > checking for readlink... no
network            > checking for symlink... no
network            > checking for if_nametoindex... no
network            > checking for struct msghdr.msg_control... no
network            > checking for struct msghdr.msg_accrights... no
network            > checking for struct sockaddr.sa_len... no
network            > checking for in_addr_t in netinet/in.h... no
network            > checking for SO_PEERCRED and struct ucred in sys/socket.h... no
network            > checking for getpeereid in unistd.h... checking for getpeereid... no
network            > checking for _head_libws2_32_a in -lws2_32... no
network            > checking for getaddrinfo... yes
network            > checking for gai_strerror... no
network            > checking whether AI_ADDRCONFIG is declared... no
network            > checking whether AI_ALL is declared... no
network            > checking whether AI_NUMERICSERV is declared... no
network            > checking whether AI_V4MAPPED is declared... no
network            > checking whether IPV6_V6ONLY is declared... yes
network            > checking whether IPPROTO_IP is declared... yes
network            > checking whether IPPROTO_TCP is declared... yes
network            > checking whether IPPROTO_IPV6 is declared... yes
network            > checking for sendfile in sys/sendfile.h... no
network            > checking for sendfile in sys/socket.h... no
network            > checking for gethostent... no
network            > checking for accept4... no
network            > configure: creating ./config.status
network            > config.status: creating network.buildinfo
network            > config.status: creating include/HsNetworkConfig.h
network            > configure: WARNING: unrecognized options: --with-compiler
network            > build
x509-system        > configure
network            > Preprocessing library for network-2.8.0.1..
x509-system        > Configuring x509-system-1.6.6...
x509-system        > build
x509-validation    > configure
x509-system        > Preprocessing library for x509-system-1.6.6..
x509-system        > Building library for x509-system-1.6.6..
x509-system        > [1 of 4] Compiling System.X509.MacOS
x509-system        >
x509-system        > System\X509\MacOS.hs:8:1: warning: [-Wunused-imports]
x509-system        >     The import of ‘Control.Applicative’ is redundant
x509-system        >       except perhaps to import instances from ‘Control.Applicative’
x509-system        >     To import instances alone, use: import Control.Applicative()
x509-system        >   |
x509-system        > 8 | import Control.Applicative
x509-system        >   | ^^^^^^^^^^^^^^^^^^^^^^^^^^
x509-system        > [2 of 4] Compiling System.X509.Unix
x509-system        > [3 of 4] Compiling System.X509.Win32
x509-system        >
x509-system        > System\X509\Win32.hs:13:1: warning: [-Wunused-imports]
x509-system        >     The import of ‘Control.Applicative’ is redundant
x509-system        >       except perhaps to import instances from ‘Control.Applicative’
x509-system        >     To import instances alone, use: import Control.Applicative()
x509-system        >    |
x509-system        > 13 | import Control.Applicative
x509-system        >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^
x509-system        >
x509-system        > System\X509\Win32.hs:27:1: warning: [-Wunsupported-calling-conventions]
x509-system x509-validation    > Configuring x509-validation-1.6.11...
x509-validation    > build
x509-validation    > Preprocessing library for x509-validation-1.6.11..
x509-validation    > Building library for x509-validation-1.6.11..
x509-validation    > [1 of 5] Compiling Data.X509.Validation.Fingerprint
x509-validation    >
x509-validation    > Data\X509\Validation\Fingerprint.hs:24:10: warning: [-Wmissing-methods]              network            > Building library for network-2.8.0.1..
network            > [1 of 9] Compiling Network.Socket.Types
network            >
network            > Network\Socket\Types.hsc:72:1: warning: [-Wunused-imports]
network            >     The import of ‘Foreign.Marshal.Array’ is redundant
network            >       except perhaps to import instances from ‘Foreign.Marshal.Array’
network            >     To import instances alone, use: import Foreign.Marshal.Array()
network            >    |
network            > 72 | import Foreign.Marshal.Array
network            >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
network            > [2 of 9] Compiling Network.Socket.Internal
network            >
network            > Network\Socket\Internal.hsc:73:1: warning: [-Wunused-imports]
network            >     The import of ‘Foreign.C.Error’ is redundant
network            >       except perhaps to import instances from ‘Foreign.C.Error’
network            >     To import instances alone, use: import Foreign.C.Error()
network            >    |
network            > 73 | import Foreign.C.Error (throwErrno, throwErrnoIfMinus1Retry,
network            >    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
network            >
network            > Network\Socket\Internal.hsc:180:3: warning: [-Wunused-do-bind]
network            >     A do-notation statement discarded a result of type ‘a’
network            >     Suppress this warning by saying
network            >       ‘_ <- throwSocketErrorIfMinus1Retry name act’
network            >     |
network            > 180 |   throwSocketErrorIfMinus1Retry name act
network            >     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
network            >
network            > Network\Socket\Internal.hsc:192:9: warning: [-Wname-shadowing]
network            >     This binding for ‘r’ shadows the existing binding
network            >       bound at Network\Socket\Internal.hsc:185:3
network            >     |
network            > 192 |         r <- act
network            >     |         ^
network            > [3 of 9] Compiling Network.Socket.ByteString.Internal
network            > [4 of 9] Compiling Network.Socket
network            >
network            > Network\Socket.hsc:256:1: warning: [-Wunused-imports]
network            >     The import of ‘Foreign.C.Error’ is redundant
network            >       except perhaps to import instances from ‘Foreign.C.Error’
network            >     To import instances alone, use: import Foreign.C.Error()
network            >     |
network            > 256 | import Foreign.C.Error
network            >     | ^^^^^^^^^^^^^^^^^^^^^^
network            >
network            > Network\Socket.hsc:261:1: warning: [-Wunused-imports]
network            >     The import of ‘Foreign.Marshal.Array’ is redundant
network            >       except perhaps to import instances from ‘Foreign.Marshal.Array’
network            >     To import instances alone, use: import Foreign.Marshal.Array()
network            >     |
network            > 261 | import Foreign.Marshal.Array ( peekArray )
network            >     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
network            >
network            > Network\Socket.hsc:328:1: warning: [-Wmissing-signatures]
network            >     Top-level binding with no type signature: socket2FD :: Socket -> FD
network            >     |
network            > 328 | socket2FD  (MkSocket fd _ _ _ _) =
network            >     | ^^^^^^^^^
network            >
network            > Network\Socket.hsc:583:9: warning: [-Wunused-local-binds]
network            >     Defined but not used: ‘connectBlocked’
network            >     |
network            > 583 |         connectBlocked = do
network            >     |         ^^^^^^^^^^^^^^
network            >
network            > Network\Socket.hsc:633:8: warning: [-Wunused-matches]
network            >     Defined but not used: ‘sock’
network            >     |
network            > 633 | accept sock@(MkSocket s family stype protocol status) = do
network            >     |        ^^^^
network            >
network            > Network\Socket.hsc:805:24: warning: [-Wunused-matches]
network            >     Defined but not used: ‘s’
network            >     |
network            > 805 | sendBuf sock@(MkSocket s _family _stype _protocol _status) str len = do
network            >     |                        ^
network            >
network            > Network\Socket.hsc:863:24: warning: [-Wunused-matches]
network            >     Defined but not used: ‘s’
network            >     |
network            > 863 | recvBuf sock@(MkSocket s _family _stype _protocol _status) ptr nbytes
network            >     |                        ^
network            >
network            > Network\Socket.hsc:1844:1: warning: [-Wunsupported-calling-conventions]
netterminateProcess: permission denied (Permission denied)

terminateProcess: permission denied (Permission denied)

terminateProcess: permission denied (Permission denied)
Progress 3/19

### Stack version
C:\Windows\system32>stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2

**Comment by jneira** [comment]
This seems to be very similar to https://github.com/commercialhaskell/stack/issues/5014. In that case setting `chcp 65001` fixed the issue.

**Comment by mpilgrem** [comment]
I am closing this issue given (a) the passage of time and (b) the following works on Windows 11/Windows Terminal (Windows Terminal also supported by Windows 10) with current versions:
~~~text
stack unpack hoogle
cd hoogle*
stack init # the hoogle package does not provide a stack.yaml file
stack build
~~~
