### ISSUE TITLE
--local-bin-path option not listed after stack install --help

### ISSUE THREAD

**Issue by noughtmare** [commercialhaskell/stack#5073]
### General summary/comments (optional)

`stack install --help` should list the `--local-bin-path` option.

### Steps to reproduce

1. `$ stack install --help | grep "\--local-bin-path"`

### Expected

Same as `$ stack --help | grep "\--local-bin-path"`:

```
  --local-bin-path DIR     Install binaries to DIR
```

### Actual

No results.

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```

### Method of installation

* I think using: `curl -sSL https://get.haskellstack.org/ | sh`

**Comment by mpilgrem** [comment]
`--local-bin-path` is a global option. It applies also, for example to `stack --local-bin-path <directory> path --local-bin` (albeit a somewhat circular use). `stack build --help` does explain (like all commands) `Command 'stack --help' for global options that apply to all subcommands.` The online documentation has been improved.
