### ISSUE TITLE
Print latest *applicable* version of packages on conflicts

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/stack#508]
Extension of #450, showing the latest isn't helpful when there is an upper bound, e.g.

```
--  Failure when adding dependencies:
      classy-prelude-conduit: needed (<0.12), latest is 0.12.0, but 0.12.0 found
      xml-conduit: needed (<1.3), latest is 1.3.0, but 1.3.0 found
```

Here it would be more useful to show the latest version of classy-prelude-conduit that's < 0.12. Perhaps change the message to say "latest applicable is ..."

**Comment by snoyberg** [comment]
Want to take a stab at this? May be faster than iterating together, and
this code is pretty well isolated.

**Comment by bergmark** [comment]
I might take a look over the weekend

**Comment by snoyberg** [comment]
Updating with awaiting-pr label

**Comment by snoyberg** [comment]
Bump
