### ISSUE TITLE
Redeploy documentation

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack#5089]
This doc https://github.com/commercialhaskell/stack/blob/stable/doc/developing_on_windows.md has been on the stable branch since 7 months. But on the website https://docs.haskellstack.org/en/stable/README/ it's still not available. Could the documentation be redeployed please?

**Comment by snoyberg** [comment]
I've never looked at that part of the system, but I believe you need to make an addition to `mkdocs.yml`. Want to try sending a PR to `stable` for that?

**Comment by flip111** [comment]
Thanks @snoyberg i submitted a PR here https://github.com/commercialhaskell/stack/pull/5097 so i'm going to close this for now.
