### ISSUE TITLE
Support binary ghc versions with --nix

### ISSUE THREAD

**Issue by sellout** [commercialhaskell/stack#5094]
Currently, with a resolver like `lts-11.22`, using a recent nixpkgs, `stack build --nix` will complain "error: attribute 'ghc822' missing". However, there _is_ a `ghc822Binary` attribute available.

It seems reasonable to fall back to the binary version if the other one isn't there.

I think this is a change I could make myself, if it seems like something that would be accepted.

**Comment by nh2** [comment]
> It seems reasonable to fall back to the binary version if the other one isn't there.

I don't think the `*Binary` GHC versions are ment to be outside of boostrapping the actual compiler inside nixpkgs, see detail comment in #5111.
