### ISSUE TITLE
User guide dependencies example is broken

### ISSUE THREAD

**Issue by AMDphreak** [commercialhaskell/stack#5109]
### General summary/comments (optional)

User guide: [Dependencies](https://docs.haskellstack.org/en/stable/GUIDE/#adding-dependencies) section not working:

> To tell stack to use text, you need to add it to your package.yaml file — specifically in your dependencies section, like this:
> 
> dependencies:
> - base >= 4.7 && < 5
> - text # added here
> 
> Now if we rerun stack build, we should get a successful result:

If you re-run stack build, it gives:
```
$ stack build
helloworld> configure (lib + exe)
Configuring helloworld-0.1.0.0...
helloworld> build (lib + exe)
Preprocessing library for helloworld-0.1.0.0..
Building library for helloworld-0.1.0.0..
[1 of 2] Compiling Lib

src\Lib.hs:8:23: error:
    * Couldn't match expected type `Data.Text.Internal.Text'
                  with actual type `[Char]'
    * In the first argument of `T.putStrLn', namely `"someFunc"'
      In the expression: T.putStrLn "someFunc"
      In an equation for `someFunc': someFunc = T.putStrLn "someFunc"
  |
8 | someFunc = T.putStrLn "someFunc"
  |                       ^^^^^^^^^^


--  While building package helloworld-0.1.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_2.4.0.1_ghc-8.6.5.exe --builddir=.stack-work\dist\e626a42b build lib:helloworld exe:helloworld-exe --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

Lib.hs:
```haskell
module Lib
    ( someFunc
    ) where

import qualified Data.Text.IO as T

someFunc :: IO ()
someFunc = T.putStrLn "someFunc"
```

package.yaml:
```yaml
dependencies:
- base >= 4.7 && < 5
- text
```

**Comment by qrilka** [comment]
@AMDphreak I think you missed `{-# LANGUAGE OverloadedStrings #-}` when copying the code from user guide

**Comment by mattaudesse** [comment]
@AMDphreak I agree with @qrilka - the `{-# LANGUAGE OverloadedStrings #-}` pragma (which is included in the example docs) should sort you out if you add that to the top of your code, so I'm going to go ahead and close.

Please let us know if you run into more problems :+1:
