### ISSUE TITLE
Minor: Stack suggests using cabal

### ISSUE THREAD

**Issue by JulianBirch** [commercialhaskell/stack#511]
```
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Warning: The package list for 'hackage.haskell.org' is 18 days old.
Run 'cabal update' to get the latest list of available packages.
```

I'm guessing the message is in the cabal lib.

**Comment by snoyberg** [comment]
Please provide more information on how this message was triggered

**Comment by JulianBirch** [comment]
I ran `stack build` on my local copy of stack. `stack --version` gives

```
Version 0.1.0.0, Git revision c2e5af39679439921570552e3e722f6819f4f4bf (dirty)
```

**Comment by snoyberg** [comment]
Please provide the full output of stack build -v

**Comment by JulianBirch** [comment]
Sorry, the problem is, now I've run `cabal update`. I'm also not 100% sure now that I haven't made an error. Closing for now.
