### ISSUE TITLE
Failed to execute `apt-get update` using `fpco/stack-build` image in CI/CD pipeline

### ISSUE THREAD

**Issue by swamp-agr** [commercialhaskell/stack#5120]
### General summary/comments

Following best practices for CI/CD pipelines, it is currently impossible to execute step `apt-get update` using `fpco/stack-build` image in CI/CD pipeline.

**Upd.** This issue depends on `packages.microsoft.com` as you can see below and their caches. It already happened 2019-10-13 (two months ago). Several days later everything becomes fine.

### Steps to reproduce

1. In your preferred CI/CD service add docker image with GHC 8.6.5, i.e. `fpco/stack-build:lts-13.23`. E.g. in CircleCI it could be something like: 

```yaml
executors:
  test-executor:
    docker:
      - image: fpco/stack-build:lts-13.23
```

2. Run `apt-get update` as a part of CI step.

### Expected

- Result 0

### Actual

```
...
E: Failed to fetch https://packages.microsoft.com/debian/9/prod/dists/stretch/main/binary-amd64/Packages.gz  Hash Sum mismatch
E: Some index files failed to download. They have been ignored, or old ones used instead.
Exited with code exit status 100
```

### Stack version

- N/A

### Method of installation

- Via docker as mentioned above, i.e. `fpco/stack-build:lts-13.23`.

**Comment by qrilka** [comment]
@swamp-agr the dockerfile doesn't use anything MS-specific, see it in the repo - https://github.com/commercialhaskell/stack/blob/master/etc/dockerfiles/stack-build/lts-13.20/Dockerfile
and on dockerhub - https://hub.docker.com/layers/fpco/stack-build/lts-13.23/images/sha256-236b8ffda12790e2fe5f4257ad04b33c2eb235a67dc72c76826ae9bf2ce3a4b2
So I suppose it's more about Ubuntu choosing (broken) MS mirror for some reason. Could you tell where is the CI/CD system you're using is located? Could it be that it's using Azure for example?

**Comment by swamp-agr** [comment]
https://raw.githubusercontent.com/fpco/stackage/9f2b7ab95c711794257b059604e80ab9ad3c0c45/debian-bootstrap.sh

I haven't found evidence on CI/CD side.
And meantime, there is, indeed, link on packages.microsoft.com in debian-bootstrap.sh.

**Comment by swamp-agr** [comment]
Right now the issue has gone. 
I think, next time it will appear in January or February, 13th. 
I will reopen it, if it reproduces again.

**Comment by qrilka** [comment]
Just for reference, debian-bootstrap.sh comes from https://github.com/commercialhaskell/stackage/blob/master/debian-bootstrap.sh and `fpco/stack-build-small` images don't run it (but could miss native dependencies, so those should be installed by some custom code)
