### ISSUE TITLE
Emanuel Borsboom's GPG key is missing a signature ?

### ISSUE THREAD

**Issue by homedotorg** [commercialhaskell/stack#5122]
https://docs.haskellstack.org/en/stable/SIGNING_KEY/ says:

"Releases are signed with the GPG key of the individual who builds them. Authorized keys will always be signed by key ID 0x575159689BEFB442, with the key and signature uploaded to the SKS keyserver pool."

The following release:

stack-2.1.3-osx-x86_64.tar.gz

has a signature from Emanuel Borsboom but his key is not signed by key ID 0x575159689BEFB442.

**Comment by borsboom** [comment]
Where did you get my key?  It's shown as signed by dev@fpcomplete.com (9BEFB442) on [pool.sks-keyservers.net](http://pool.sks-keyservers.net/pks/lookup?op=vindex&fingerprint=on&search=0x65101FF31C5C154D) and [pgp.mit.edu](http://pgp.mit.edu/pks/lookup?op=vindex&search=0x65101FF31C5C154D).

**Comment by homedotorg** [comment]
I'm not sure now - maybe just my confusion.  My apologies!
