### ISSUE TITLE
[Win32] Segmentation fault

### ISSUE THREAD

**Issue by rtentser** [commercialhaskell/stack#5127]
When i call `stack` in git-bash on my x86 WIndows 7, i get a segmentation fault. In `cmd` it just crashes. I can reproduce it at least with `stack` command without arguments, `stack --version` and `stack --help`. With `stack install`, `stack update` and `stack build` everything works fine. An example:
```
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) i386 hpack-0.31.2
Segmentation fault
```

I use an official binary.

**Comment by qrilka** [comment]
Just a side comment: mainstream support for Windows 7 ended almost 5 years ago.

**Comment by mpilgrem** [comment]
Closing issue given the passage of time and that Microsoft ended paid for support of Windows 7 over a year ago.
