### ISSUE TITLE
How to build a docker image with Stack Haskell?

### ISSUE THREAD

**Issue by softshipper** [commercialhaskell/stack#5128]
Hi all

I am using Stack 2.13 to build my Haskell project and would like to build a docker image from it.

I've found that Stack supports Docker integration, but as I tried it does not build for me ready to use docker image from my project.

The statement `stack docker pull,` that describes in the section https://docs.haskellstack.org/en/stable/docker_integration/#use-stack-as-normal, it downloads the Haskell compiler

```
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
golang                         1.12.9              669220934599        3 months ago        814MB
kindest/node                   v1.15.3             8ca0c8463ebe        4 months ago        1.45GB
fpco/stack-build               lts-14.17           9adc774bb5e5        4 months ago        8.52GB
gcr.io/kuar-demo/kuard-amd64   blue    

1db936caa6ac        8 months ago        23MB
```
but it does not build an image.

The question is, how to build a docker image from my haskell project with Stack.  

Thanks

**Comment by mpilgrem** [comment]
@softshipper, I think your question is outside the scope of this repository and better directed to users of Docker. As I understand it, Docker builds Docker images. Stack builds executables (and other binaries) from Haskell source code. Stack's Docker integration allows you to use Stack within a Docker container, not to create such containers.
