### ISSUE TITLE
stack ghci can not find installed module outside a project

### ISSUE THREAD

**Issue by DaweiLiuFrance** [commercialhaskell/stack#5130]
I'm using `stack v-2.1.3`, `nightly-2019-12-24`

I've installed `easyplot` with stack outside any project(So I suppose it's global?)
But when I `stack ghci` and import easyplot's library, it says that it couldn't be found.
I'd have to `stack ghci --package easyplot`

Is this a feature of a bug?

**Comment by openingnow** [comment]
Maybe you're executing ghci inside your project?

Try add easyplot as dependencies in package.yaml.

```yaml
dependencies:
- base >= 4.7 && < 5
- easyplot
```

**Comment by mattaudesse** [comment]
Hey @DaweiLiuFrance - sorry nobody from the `stack` maintainer team responded sooner, and yup, it's a feature :-)

`stack` projects normally operate in a sandbox mode to protect you from the [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell) to which global packages are more susceptible.

@openingnow is right; fixing should be a simple matter of adding `easyplot` to your dependencies, so I'm going to go ahead and close this.
