### ISSUE TITLE
Stack build failure

### ISSUE THREAD

**Issue by RLogik** [commercialhaskell/stack#5133]
### General summary/comments

**`stack build`** fails, resulting in the error **'cabal copy' failed**. I followed all of your instructions and it does not work.

### Steps to reproduce

For example:

1. Run command `stack new myProj new-template`.
2. Change to the newly created directory (**myProj**).
2. Run command `rm -rf ~/.stack .stack-work`.
3. Replace the `src/Lib.hs` file's contents with the following code
```
module Lib
    ( someFunc
    ) where

import Network.HTTP.Conduit
import qualified Data.ByteString.Lazy.Char8 as L

someFunc :: IO ()
someFunc = do
    lbs <- simpleHttp "https://raw.githubusercontent.com/commercialhaskell/stack/master/README.md"
    L.putStrLn lbs
```
4. Edit the **library**-part of `myProj.cabal` via
```
library
  hs-source-dirs:      src
  exposed-modules:     Lib
  build-depends:       base >= 4.7 && < 5
                     , bytestring
                     , http-conduit
  default-language:    Haskell2010
```
5. Run command `stack build`.

### Expected

Should build

### Actual

Downloads and installs packages, nearly completes all 58/58 steps, but fails right at the end, resulting in the following message:

```
/opt/local/bin/strip: object: ~/Desktop/hask/dividedTrees/.stack-work/install/x86_64-osx/219ba4adf0ac7c096ab1dfbcb1af6736068f28a794c6c8fa7035d26d53fa8510/8.6.5/bin/dividedTrees-exe malformed object (unknown load command 10)
Completed 58 action(s).     
'cabal copy' failed.  Error message:

--  While building package dividedTrees-0.1.0.0 using:
~/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5 --builddir=.stack-work/dist/x86_64-osx/Cabal-2.4.0.1 copy
    Process exited with code: ExitFailure 1

Possible causes of this issue:
* No module named "Main". The 'main-is' source file should usually have a header indicating that it's a 'Main' module.
* A cabal file that refers to nonexistent other files (e.g. a license-file that doesn't exist). Running 'cabal check' may point out these issues.
```

The second suggestion doesn't bring anything. The first one is utter nonsense, as the `app/Main.hs` file looks like this:

```
module Main where

import Lib

main :: IO ()
main = someFunc
```

### Stack version
```
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

### Method of installation

* installed from the git repository

**Comment by mpilgrem** [comment]
Closing given (a) the passage of time and (b) I can not reproduce the problem with current versions.
