### ISSUE TITLE
Read credentials from environment variables

### ISSUE THREAD

**Issue by nalchevanidze** [commercialhaskell/stack#5139]
i want to automatise uploading. that why i am looking for the feature that would allow me to read credentials from environment variables. 

```bash
export $STACK_USERNAME="<user name>"
export $STACK_PASSWORD="<user password>"
```

so then `ci` can publish new releases automatically

I don't think it will be hard. 

In this code:

https://github.com/commercialhaskell/stack/blob/be1970e48d85ad9d227e8aaa443706309ae770f3/src/Stack/Upload.hs#L75

instead of `fromPrompt`, we can read env variables and ask credentials only if was not provided.

i can provide `PR`

**Comment by mattaudesse** [comment]
Thanks for the feature request + PR @nalchevanidze.

Despite how easy it was to change I feel like we should probably open your idea up to discussion before moving forward. I suspect this is the sort of enhancement that could have unintended consequences and/or maybe illicit strong opinions.

I've added the "discuss" label for now.

**Comment by mattaudesse** [comment]
@snoyberg merged the associated PR so let's mark this as closed.

Thanks again @nalchevanidze!
