### ISSUE TITLE
`stack exec cabal run` fails

### ISSUE THREAD

**Issue by eightyeight** [commercialhaskell/stack#514]
I'm used to using `cabal run` to quickly run my compiled program. When I try to do it via `stack`, I get this:

```
$ stack exec cabal run
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
cabal: Use of GHC's environment variable GHC_PACKAGE_PATH is incompatible with
Cabal. Use the flag --package-db to specify a package database (it can be used
multiple times).
```

Is this expected? Am I doing something wrong? Is there merit to having a dedicated `stack run <target>` command?

**Comment by mboes** [comment]
This is not necessary in stack. In stack `stack build && stack exec <program>` works just fine. This has been asked enough times that it's worth an entry in the FAQ.

**Comment by mboes** [comment]
FAQ entry added: https://github.com/commercialhaskell/stack/wiki/FAQ#can-i-run-cabal-commands-inside-stack-exec.

**Comment by eightyeight** [comment]
Ah, right, I didn't know `stack exec` was supposed to be used in that way. Thanks, that's perfect!
