### ISSUE TITLE
Migrate 'arch' command to 'uname -m' in install script

### ISSUE THREAD

**Issue by 3xpl0it2c** [commercialhaskell/stack#5148]
## General Summary
The installation script uses the `arch` command which isn't  found on all of the linux distros.
It could be replaced with an universal alternative (which I believe will also work on MacOS)
which is `uname -m`.

## Steps to Reproduce
Just install stack on any distro without the `arch` command such as Arch Linux.
Install it by running:
`curl -sSL https://get.haskellstack.org/ | sh`

## Expected
I expected stack to recognize my cpu architecture correctly.

## Actual
stack complains my computer may be unsupported.

## Stack version
`Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2`

## Method of installation
`curl -sSL https://get.haskellstack.org/ | sh`

**Comment by mpilgrem** [comment]
I am closing given the passage of time and because it appears to me that `uname -m` is used in the current `get-stack.sh` in `get_isa()`.
