### ISSUE TITLE
can't build hello-world program on OSX 10.14

### ISSUE THREAD

**Issue by miramar-labs** [commercialhaskell/stack#5150]
Linking .stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/my-project-exe/my-project-exe ...
ld: warning: ignoring file /Users/aaron/my-project/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/libHSmy-project-0.1.0.0-3GgTlmEIQwCB6eMgMXNQ2k.a, file was built for archive which is not the architecture being linked (x86_64): /Users/aaron/my-project/.stack-work/dist/x86_64-osx/Cabal-2.4.0.1/build/libHSmy-project-0.1.0.0-3GgTlmEIQwCB6eMgMXNQ2k.a
Undefined symbols for architecture x86_64:
  "_myzmprojectzm0zi1zi0zi0zm3GgTlmEIQwCB6eMgMXNQ2k_Lib_someFunc_closure", referenced from:
      _Main_main1_info in Main.o
      _Main_main1_closure in Main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time.
