### ISSUE TITLE
Question: how are stack's ghc binaries being build?

### ISSUE THREAD

**Issue by flip111** [commercialhaskell/stack#5154]
How are the ghc binaries that stack downloads being build from source? I already saw this repo https://github.com/commercialhaskell/ghc but i'm not sure what the purpose of it is. The source code has not been updated since 2015 but it still gets releases for new ghc versions https://github.com/commercialhaskell/ghc/releases Though these releases seem to contain source code again. Are there scripts somewhere that build binaries? And from which code? Is there some server doing the builds or is someone doing this locally?

**Comment by mpilgrem** [comment]
I am closing this issue as the versions of GHC that fetches by default have been the ones published by the GHC developers for some now, as set out in Stack's default `setup-info` dictionary.
