### ISSUE TITLE
Project has to be on the same Windows drive as Stack itself

### ISSUE THREAD

**Issue by tom162** [commercialhaskell/stack#5165]
### General summary/comments (optional)

I've installed Stack on my C: drive.  When I stay on C: and try the 5 commands from the quick start guide, it works.  When I go over onto my L: drive (a Network-Attached Storage device) and repeat the process, the `stack build` step fails with an "openBinaryFile: does not exist" error.

I can happily work around this by doing my projects on the C: drive.

I suspect this problem may also be causing #3442 , where the Windows subst command is introducing a new virtual drive.

### Steps to reproduce

On a Windows 10 PC with at least 2 drives, with stack installed on the C: drive:

```
C:
cd \temp\some-dir-with-a-long-name
stack new somename
cd somename
stack build
L:
cd \tmp
stack new somename
cd somename
stack build
```

### Expected

I expected the Quick Start Guide commands to work equally well on the C: and L: drives.

### Actual

The `stack build` step treated the drives differently, failing on L:.

Verbose output:
https://gist.github.com/tom162/b686e4211546586bb9afb69d17cfeaa7

### Stack version

```
L:\tmp\series6>stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

### Method of installation

Official binary, downloaded from https://get.haskellstack.org/stable/windows-x86_64-installer.exe

**Comment by mpilgrem** [comment]
I am closing this because, with the current version of Stack, I have `stack` on the C:\ drive and my projects on the D:\ drive without any problems.
