### ISSUE TITLE
Passing RTS options to GHC via `ghc-options` in `stack.yaml` fails

### ISSUE THREAD

**Issue by TOTBWF** [commercialhaskell/stack#5180]
When trying to pass in RTS options to GHC via `ghc-options` in `stack.yaml`, the RTS options aren't properly threaded through. 

### Steps to reproduce

1. Create a new project via `stack new`
2. Add the following to `stack.yaml`
```
ghc-options:
  "$locals": +RTS -s -RTS
```
3. Run command `stack build`.

### Expected

The RTS options are passed to GHC, and the statistics are printed out while compiling.

### Actual

```
Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.5: unknown RTS option: --ghc-options
```
### Stack version

```
$ stack --version
Version 2.1.3 x86_64
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by EpicOrange** [comment]
It looks like it turns `+RTS -s -RTS` into `--ghc-options +RTS --ghc-options -s --ghc-options -RTS`. Quoting the options (`"+RTS -s -RTS"`) doesn't change it.

While we're at it -- leaving options empty is an error, which doesn't seem right either.
```
ghc-options:
  "$locals": # +RTS -s -RTS
```

```
Aeson exception:
Error in $['ghc-options']['$targets']: failed to parse field 'ghc-options': expected GhcOptions, encountered Null
See http://docs.haskellstack.org/en/stable/yaml_configuration/
```

**Comment by jwaldmann** [comment]
Hi. This does work for `stack install`, but it breaks `stack repl`?  

I built 9fcf300b9f2484796bc7a8ee70caa1b5b4692fe5 . I have this in stack.yaml:
```
ghc-options:
  "$everything" : -O2 -j4 +RTS -A400m
```
and this in my cabal file:
```
executable pure-matchbox
  main-is:             pure-matchbox.hs
  ghc-options:         -threaded -rtsopts -fno-omit-yields  -fdicts-strict
```
when I do `stack repl src/Some/Thing.hs` (with ghc-8.10.5), I get
```
...
pure-matchbox> initial-build-steps (lib)
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded -O2
Configuring GHCi with the following packages: pure-matchbox
ghc: Unknown output flag -op
ghc: Internal error in the RTS options parser
```
I can make an extra issue if you want.

Actual source code: https://gitlab.imn.htwk-leipzig.de/waldmann/pure-matchbox/-/tree/epsilon
