### ISSUE TITLE
.stack consumes so much disk space

### ISSUE THREAD

**Issue by hafizhmakmur** [commercialhaskell/stack#5184]
I just installed stack via apt install haskell-stack and then updating it and before I knew it suddenly I run out of disk space. I examined my storage and I found out Stack has already sit on 2.6 GB. Is this really intended? I'm afraid there's some infinite loop in logging somewhere and it only stops because I run out of storage. For now I'm forced to delete stack because I need the disk space.

**Comment by dpwiz** [comment]
> I just installed stack via apt install haskell-stack

Wrong move. You'd better download it from https://get.haskellstack.org/

> Stack has already sit on 2.6 GB

This is fine :woman: :fire: :coffee:

Unfortunately the Hackage indices downloaded as tar.gz, then there's a copy of unpacked tar, AND a sqlite-indexed database of stuff. Then, on top of that stack downloads the GHC, packages and compiles all the things.

There is some ongoing effort in deduplication. Maybe casa-enabled stack could skip the tarballs and save a few gigs.
