### ISSUE TITLE
Unresolvable SQLite error

### ISSUE THREAD

**Issue by nzeh** [commercialhaskell/stack#5185]
### Steps to reproduce

For example:

1. Remove the entire ~/.stack directory, the pantry.sqlite3 file or do nothing.
2. Run stack ghci or any other stack command

### Expected

GHCI should start

### Actual

```
nzeh@bluenose:~$ rm -rf ~/.stack
nzeh@bluenose:~$ stack ghci
Encountered error while migrating Pantry database:
    SQLite3 returned ErrorIO while attempting to perform step: disk I/O error
Please report this on https://github.com/commercialhaskell/stack/issues
As a workaround you may delete Pantry database in /users/faculty/nzeh/.stack/pantry/pantry.sqlite3 triggering its recreation.
```

### Stack version

```
nzeh@bluenose:~$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```

### Method of installation

Not sure.  Installed by sysadmin.

**Comment by emilakesson99** [comment]
Also have this problem, have you found a solution?

**Comment by mpilgrem** [comment]
@nzeh, I am working through open issues, including old ones. Do you have the same experience with Stack 2.15.5? I can only think it was something to do with 'permissions' to perform certain disk operations on your system.

**Comment by emilakesson99** [comment]
You were right

**Comment by mpilgrem** [comment]
If a problem with a user's permissions is limited to the location that Stack picks a default, that location is configurable. On non-Windows operating systems, the key location is the 'Stack root', configurable as documented here: https://docs.haskellstack.org/en/stable/stack_root/
