### ISSUE TITLE
docker version isn't being parsed

### ISSUE THREAD

**Issue by lehins** [commercialhaskell/stack#5193]
Current bug happens on `master` and I suspect it is because we switched to Cabal-3

Here is a problem I ran into:
```
$ stack build --fast --verbose
Version 2.2.0, Git revision 681ca331609e555d62e9aacbbc18770f81abd8de PRE-RELEASE x86_64 hpack-0.32.0
2020-02-21 23:40:28.302738: [debug] Checking for project config at: <redacted>stack.yaml
2020-02-21 23:40:28.303210: [debug] Loading project config file stack.yaml
2020-02-21 23:40:28.308326: [debug] SELECT COUNT(*) FROM "last_performed" WHERE ("action"=?) AND ("timestamp">=?); [PersistInt64 1,PersistUTCTime 2020-02-20 20:40:28.308297 UTC]
2020-02-21 23:40:28.308994: [debug] Run process: /usr/bin/docker --version
2020-02-21 23:40:28.624191: [debug] Process finished in 315ms: /usr/bin/docker --version
2020-02-21 23:40:28.624667: [error] Cannot get Docker version (invalid 'docker --version' output).
$ /usr/bin/docker --version
Docker version 19.03.6, build 369ce74a3c
```
As it turns out Cabal has changed their version parser and leading zero is no longer valid:
https://github.com/commercialhaskell/stack/blob/df34c0ad06d884c870ce79f2d672335897cd9976/src/Stack/Docker.hs#L402-L412

This definition is from pantry: `parseVersion = simpleParse`
```
λ> import Distribution.Text
λ> simpleParse "19.03.6" :: Maybe Version
Nothing
λ> simpleParse "19.3.6" :: Maybe Version
Just (mkVersion [19,3,6])
```

One possible solution would be to switch to the more general solution provided by base in `Data.Version`, since `docker` is not a Cabal project anyways:

```haskell
λ> import Text.ParserCombinators.ReadP
λ> import Data.Version
λ> let pv = readP_to_S parseVersion
λ> last (pv "19.03.6," :: [(Version, String)])
(Version {versionBranch = [19,3,6], versionTags = []},",")
```

**Comment by chreekat** [comment]
Have you considered that this might be a bug in Cabal? Have you raised an issue there? It looks like there has been a lot of refactoring around some of these code paths in Cabal recently.

**Comment by lehins** [comment]
@chreekat I don't know if PVP or Cabal versioning scheme dictate this as valid version: `"19.03.6"` or not, but regardless of this, I don't think parsing versions for non Haskell packages with Cabal is a smart move regardless if this is a bug in Cabal or not.

`Data.Version.Version` on the other hand promises in Haddock to be general, so it should suit this purpose better.

**Comment by gdziadkiewicz** [comment]
@chreekat This looks very intentional on Cabal side
https://github.com/haskell/cabal/blob/32576917ce9b44ef9d82d53926c38ca540737bca/Cabal/Distribution/Types/Version.hs#L96-L131
```haskell
instance Parsec Version where
    parsec = mkVersion <$> toList <$> P.sepByNonEmpty versionDigitParser (P.char '.') <* tags
      where
        tags = do
            ts <- many $ P.char '-' *> some (P.satisfy isAlphaNum)
            case ts of
                []      -> pure ()
                (_ : _) -> parsecWarning PWTVersionTag "version with tags"

-- | An integral without leading zeroes.
--
-- @since 3.0
versionDigitParser :: CabalParsing m => m Int
versionDigitParser = (some d >>= toNumber) P.<?> "version digit (integral without leading zeroes)"
  where
    toNumber :: CabalParsing m => [Int] -> m Int
    toNumber [0]   = return 0
    toNumber (0:_) = P.unexpected "Version digit with leading zero"
    toNumber xs
        -- 10^9 = 1000000000
        -- 2^30 = 1073741824
        --
        -- GHC Int is at least 32 bits, so 2^31-1 is the 'maxBound'.
        | length xs > 9 = P.unexpected "At most 9 numbers are allowed per version number part"
        | otherwise     = return $ foldl' (\a b -> a * 10 + b) 0 xs


    d :: P.CharParsing m => m Int
    d = f <$> P.satisfyRange '0' '9'
    f c = ord c - ord '0'
```

Would you accept a PR that will change the type used for Docker version handling to `Data.Version`? If yes, then I'm willing to give this a shot.

**Comment by gdziadkiewicz** [comment]
I created a PR that works around this problem by using Data.Version parsing.
