### ISSUE TITLE
`stack ghci` fails with permissions error for multiple users

### ISSUE THREAD

**Issue by rosekunkel** [commercialhaskell/stack#5203]
### General summary/comments

`stack ghci` creates the directory `/tmp/haskell-stack-ghci` if it doesn't exist, which it uses to store ghci-script files that load the appropriate modules for each project. If multiple users try to use `stack ghci`, only the first user to do so will succeed, because `/tmp/haskell-stack-ghci` will be owned by them. Any other user who tries to run `stack ghci` will get a permissions error. This could be fixed by using a user-specific temporary directory instead (e.g. ~/.cache). The relevant code is here:
https://github.com/commercialhaskell/stack/blob/605f74db2ddabc89d2f2ae5f5ed75de666fcd613/src/Stack/Ghci.hs#L437-L450

### Steps to reproduce

1. Create two users, `a` and `b`, and install stack in each of their home directories.
2. Run `stack ghci` as user `a` in their home directory.
3. Exit GHCi and switch to user `b`.
3. Run `stack ghci` as user `b` in their home directory.

### Expected

GHCi should start normally in user `b`'s global project.

### Actual

Starting GHCi fails with:
```
Configuring GHCi with the following packages: 
/tmp/haskell-stack-ghci/2a3bbd58: createDirectory: permission denied (Permission denied)
```

### Stack version

```shell
$ stack --version
Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
```

### Method of installation

* From the Arch official repositories

**Comment by rosekunkel** [comment]
I can write a pull request to fix this, I just want to make sure that my suggested solution (using ~/.cache) is acceptable. I would probably have to add a dependency on https://hackage.haskell.org/package/xdg-basedir if that's ok.

**Comment by tmcdonell** [comment]
We have run into this as well. \*sigh\* A workaround is to set the environment variable `TMPDIR` to something unique for each user.

The [`getXdgDirectory`](http://hackage.haskell.org/package/directory-1.3.6.1/docs/System-Directory.html#v:getXdgDirectory) function since directory-1.2.3.0 can be used without adding an extra dependency.

**Comment by AlijonovMukhammaddiyor** [comment]
Can you please give an example of how to do ?

**Comment by davidsd** [comment]
I just ran into this as well, in a case where a collaborator and I were both trying to use `stack ghci` on the login node of a shared cluster. It would be great to fix it.

**Comment by mauke** [comment]
Argh. I just ran into this issue at work.

It's been 3 years and it's still broken. Can't you at least include the user id in the directory name, like `/tmp/haskell-stack-ghci-${UID}`?

**Comment by mpilgrem** [comment]
@mauke, I will have a stab at fixing this.

**Comment by mpilgrem** [comment]
@mauke, I think the version of Stack in the `rc/v2.11` release candidate branch now behaves as you wish.
