### ISSUE TITLE
Is stack 1.9.3 no longer supported since lts-15?

### ISSUE THREAD

**Issue by dten** [commercialhaskell/stack#5204]
Getting 404 if trying to use lts-15 use 1.9.3 (the same as https://github.com/commercialhaskell/stack/issues/5006)

I can't find anywhere that says since lts-15 is the first to drop support for stack 1.9.3

Can someone confirm this situation?

**Comment by qrilka** [comment]
This was publicly announced 3 weeks ago, see https://www.stackage.org/blog/2020/02/discontinuing-legacy-snapshots

**Comment by dten** [comment]
awesome thanks, i had a search around the net but didn't stumble across it
