### ISSUE TITLE
Yesod "devel.hs" not found error 

### ISSUE THREAD

**Issue by rvelez83** [commercialhaskell/stack#521]
Installed stack repo on Ubuntu 14.04

Been now trying the Yesod quickstart

Everything goes smoothly for me until I do:
stack exec -- yesod devel

I've tried on two computers (same OS), I get this message:

ERROR: file devel.hs not found, checked: ["app/devel.hs","devel.hs","src/devel.hs"]

**Comment by snoyberg** [comment]
Which scaffolding did you select?

**Comment by rvelez83** [comment]
mini

**Comment by snoyberg** [comment]
The mini scaffolding doesn't support the devel server functionality. Check out the output from yesod init. I'd recommend using simple instead.

**Comment by rvelez83** [comment]
(The mini one says something about being the bare bones "hello world" and so for me (being a total n00b) mini sounds like the ideal option for testing/experimenting.) 

 I just went with "simple" and it works. 
Stack does seem to make things a lot easier, so thanks for your contributions.. I can concentrate more on actually learning now that setting up the environment is starting to get out of my way. (previously even just trying to update cabal was confusing to me.)

**Comment by snoyberg** [comment]
I'm open to improvements on the wording to be clearer. This is what `yesod init` currently says about the mini scaffolding:

```
    mini   = bare bones, the "Hello World" of multi-file Yesod apps
             (Note: not configured to work with yesod devel)
```

**Comment by rvelez83** [comment]
I had stopped reading at "hello world" although I'm not sure being a n00b that the Note at the bottom would have indicated the issue to me, in fact by saying "not configured to work with yesod devel" sounds somewhat to me like the missing devel.hs file shouldn't matter (like it doesn't work with it, hence wouldn't need the devel file). 

But that's me from my total n00b perspective, I do think it's valid to suggest then that the quickstart instructions mention selecting the "simple" option... And/or that the simple option mentions something to indicate that it's the one you should select when just learning.

**Comment by snoyberg** [comment]
I've added another note to the quickstart guide that mini doesn't work with yesod devel. If you have ideas for improvements to the text from `yesod init`, feel free to send a PR at https://github.com/yesodweb/yesod/blob/master/yesod-bin/input/database.cg.
