### ISSUE TITLE
Warnings about untested GHC and Cabal

### ISSUE THREAD

**Issue by torgeirsh** [commercialhaskell/stack#5212]
### General summary/comments (optional)

Using the current version of stack (2.1.3) with the current major version of stackage LTS (15) produces the following warnings:

Stack has not been tested with GHC versions above 8.6, and using 8.8.2, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail

It does appear to work otherwise, but it's unclear if LTS 15 is supported by the current version of stack, or if it just works by chance in my specific case and it's better to wait for a new release.

### Steps to reproduce

Run stack with resolver set to lts-15.x

### Expected

No warnings about untested versions.

### Actual

Warnings about untested versions.

### Stack version

Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mklinik** [comment]
Agree, it is not clear what I should do about this warning. Should I switch to an older LTS? Why does selecting an LTS give me an untested GHC? Shouldn't there be a nightly or testing resolver for this?

**Comment by Blaisorblade** [comment]
This appears fixed by the release candidate 2.3.0.1 thanks to PR #5041. The problem was the lack of a release.

**Comment by Blaisorblade** [comment]
This appears fixed by the release candidate 2.3.0.1 thanks to PR #5041. The problem was the lack of a release.
_If_ you want to upgrade to the release candidate (beware it might have other bugs), you can already use `stack upgrade --binary-version 2.3.0.1`.

**Comment by emilypi** [comment]
thanks @Blaisorblade this fixes the problem

**Comment by Blaisorblade** [comment]
Now 2.3.1 has been released, also supporting GHC 8.10; you can upgrade with `stack upgrade` or following [the usual docs](https://docs.haskellstack.org/en/stable/install_and_upgrade/).

So I'm tentatively closing this. :-)
