### ISSUE TITLE
should show hpack warnings

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#5229]
hpack will keep only the last of similar-looking conditionals, it seems: https://github.com/sol/hpack/issues/379 . When hpack 0.33.0 is run directly, it warns about this. When stack 2.1.3 is run, no hpack warning is shown - presumably silenced by stack - which made this harder to track down.

**Comment by mpilgrem** [comment]
I am closing this issue because, with the current version of Stack, it warns about the duplicate field.
