### ISSUE TITLE
Stack build on windows does not have rename permissions?

### ISSUE THREAD

**Issue by DrYSG** [commercialhaskell/stack#5237]
Why do I get a permissions violation with stack build on windows? See below for version of stack and the error message about renaming files. This happens even when I run as ADMIN, so it seems to be more than just a folder's permissions issue.

No I am on a company laptop, so I cannot disable McAfee, is that is what you are going to suggest.

```
C:\CRIME\haskell-call>stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2

C:\CRIME\haskell-call>stack build
Stack has not been tested with GHC versions above 8.6, and using 8.8.3, this may fail
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.
Already downloaded.
Already downloaded.
Decompressing ghc-8.8.3.tar.xz...

7-Zip 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Processing archive: C:\Users\ysg4206\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3.tar.xz

Extracting  ghc-8.8.3.tar

Everything is Ok

Size:       2555330560
Compressed: 204702116
Extracting ghc-8.8.3.tar...
Extracted total of 10091 files from ghc-8.8.3.tar
C:\Users\ysg4206\AppData\Local\Programs\stack\x86_64-windows\ghc-8.8.3-tmp1040\ghc-8.8.3\: renamePath:MoveFileEx "C:\\Users\\ysg4206\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.8.3-tmp1040\\ghc-8.8.3\\" "C:\\Users\\ysg4206\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.8.3\\": permission denied (Access is denied.)
```

**Comment by nukecoder** [comment]
I had this same problem while running stack setup on a company machine. I did the following as a workaround. In this case ghc-8.8.3.tar.xz was in the x86_64-windows directory.

1. Use 7zip to extract `ghc-8.8.3.tar.xz` to `ghc-8.8.3.tar`.
2. Use 7zip to extract `ghc-8.8.3.tar` to `ghc-8.8.3`.
3. Create a new Text document with name `ghc-8.8.3.installed.txt`.
4. Open `ghc-8.8.3.installed.txt` with your preferred text editor and make its contents `installed`.
5. Rename `ghc-8.8.3.installed.txt` to `ghc-8.8.3.installed`.
6. Run `stack setup` to complete the setup [in my case it installed msys-2-20180531 without issue].

**Comment by sharno** [comment]
@nukecoder that work around is a saver, thanks a lot! That issue got me stuck for a while

**Comment by mpilgrem** [comment]
I am going to close this issue given the passage of time and because it appears to be specific to the user's system (the user did not have permission to copy a file to C:\\Users\\ysg4206\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-8.8.3\\).

It is, however, also possible to configure the location of Stack's 'programs' directory: https://docs.haskellstack.org/en/stable/yaml_configuration/#local-programs-path - perhaps configure it to a location where the user has permission to copy files?
