### ISSUE TITLE
Stack cannot build projects that require Alex with the LTS-7.x resolver

### ISSUE THREAD

**Issue by Calvin-L** [commercialhaskell/stack#5242]
### General summary

[One of my older projects](https://github.com/uwplse/epics-tools) uses an ancient resolver that no longer seems to work.

### Steps to reproduce

Save this as `repro.sh` in an empty folder:

```
#!/bin/bash

set -e

cat >please-install-alex.cabal <<EOF
name:    please-install-alex
version: 0.0

executable Main
  main-is:
    Main.hs
  build-depends:
    base
  build-tools:
    alex
EOF

cat >stack.yaml <<EOF
require-stack-version: "==2.1.3"
resolver: lts-7.24
packages: [.]
EOF

cat >Main.hs <<EOF
module Main (main) where

main :: IO ()
main = do
    putStrLn "hello"
EOF

stack build
```

Then run it:

```
$ bash ./repro.sh
```

### Expected

The project should build.

### Actual

```
alex               > configure
alex               > [1 of 2] Compiling Main             ( /private/var/folders/d4/n6djsq8x5dv0jfx84hzl0v000000gn/T/stack-6accc37869a8dddd/alex-3.1.7/Setup.lhs, /private/var/folders/d4/n6djsq8x5dv0jfx84hzl0v000000gn/T/stack-6accc37869a8dddd/alex-3.1.7/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/setup/Main.o )
alex               > [2 of 2] Compiling StackSetupShim   ( /Users/loncaric/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /private/var/folders/d4/n6djsq8x5dv0jfx84hzl0v000000gn/T/stack-6accc37869a8dddd/alex-3.1.7/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/setup/StackSetupShim.o )

[...]

alex               > 9 warnings generated.
alex               > Configuring alex-3.1.7...
alex               > build
alex               > Building alex-3.1.7...
alex               > Preprocessing executable 'alex' for alex-3.1.7...
alex               > setup: The program 'happy' is required but it could not be found

--  While building package alex-3.1.7 using:
      /private/var/folders/d4/n6djsq8x5dv0jfx84hzl0v000000gn/T/stack-6accc37869a8dddd/alex-3.1.7/.stack-work/dist/x86_64-osx/Cabal-1.24.0.0/setup/setup --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build --ghc-options ""
    Process exited with code: ExitFailure 1
Progress 1/2
```

I am happy to provide more verbose logs if they will be helpful.

### Stack version

```
$ stack --version 
Version 2.1.3 x86_64
[...]
```

### Method of installation

* On MacOS via Homebrew

**Comment by qrilka** [comment]
I guess you need to add `happy` as a dependency as well because `alex` doesn't list it as it's dependency.

**Comment by Calvin-L** [comment]
Adding `happy` to the `build-tools` section does not fix the problem. In fact, `happy` won't build either: https://gist.github.com/Calvin-L/ce1e40bde893de7eaa59738c6de7c342

I should clarify that this worked fine with an older version of Stack circa 2017/2018. I will try to reproduce that successful build; there might have been something about my environment that caused it to succeed back then when it shouldn't have.

**Comment by Calvin-L** [comment]
Sure enough, this project does build with [Stack 1.1.2](https://github.com/commercialhaskell/stack/releases/tag/v1.1.2).

(Unrelated: to build with the older version of Stack I had to create a Setup.hs file with these contents:
```
import Distribution.Simple
main = defaultMain
```
)

**Comment by mpilgrem** [comment]
I am closing given the passage of time and that the `master` branch of Stack does not support LTS < 12.0.
