### ISSUE TITLE
project using lts-15.3 uses unexpected ghci 8.8.3, not 8.8.2 as documented

### ISSUE THREAD

**Issue by EdmundsEcho** [commercialhaskell/stack#5244]
Please follow the steps below for reporting a bug:

Sequence to replicate the issue:

1. stack --version
```
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

2. configure stack.yaml using resolver: lts-15.1 (2 or 3, i.e., versions that should use ghc 8.8.2)

3. stack ghci --ghci-options --version

```
Stack has not been tested with GHC versions above 8.6, and using 8.8.2, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
Using main module: 1. Package `tiny-servant' component tiny-servant:exe:tiny-servant-exe with main-is file: /Volumes/EC_Active/Programming/etl/tiny-servant/app/Main.hs
The following GHC options are incompatible with GHCi and have not been passed to it: -threaded
Configuring GHCi with the following packages: tiny-servant
The Glorious Glasgow Haskell Compilation System, version 8.8.3
```

I would have expected that stack would use ghc 8.8.2

I thought that the lts and ghc version were designed to align.  I'm not sure what overrides could be in place to force use of 8.8.3 instead.

\- E

**Comment by nhenin** [comment]
```
Stack has not been tested with GHC versions above 8.6, and using 8.8.3, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.1.0 was found, this may fail
```
Hi, Is there some plans to align Stack with the latest lts snapshots ? I believe it could cause some IDE issues ....

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time.
