### ISSUE TITLE
Stack Build-API?

### ISSUE THREAD

**Issue by LeanderK** [commercialhaskell/stack#5248]
I am developing a GHC source-plugin that would impact the build-process, since i would need to generate different versions of functions based on the package i am developing in. I would need to traverse the dependency-graph forward (starting by main source package), parse its source-code and mark modules as needed to be recompiled with my source-plugin enabled.

Is something like this possible with stack? I think a simple way to get the dependent graph, the source-code for each dependency and mark it as dirty would suffice.

**Comment by mbj** [comment]
@LeanderK You could also use the stack command line. `stack ls dependencies`. This may be less work. There are various options to change the dependency output to make it easier to parse.

**Comment by mbj** [comment]
@LeanderK Also see #4424, dependencies now can rendered as JSON making processing easier.

**Comment by LeanderK** [comment]
Ah, okay. That helps, since it seems to include then URL to the source-code. Is there a way to mark a package as dirty so it gets rebuild? Rebuilding everything all the time is super expensive `---force-dirty` is the only option I've found.

**Comment by mbj** [comment]
@LeanderK The only workaround I know is changing a packages `ghc-config` flags. This can cause a targeted rebuild. Note that if you target a dependency with many dependencies, you'll get to significant build times again as all transitive ones may get re-build also.

**Comment by mbj** [comment]
BTW I meant to overwrite like this:

```
# stack.yaml
ghc-options:
  your-target: -some-flag
```

**Comment by mpilgrem** [comment]
I am closing this issue, given the passage of time.
