### ISSUE TITLE
"Executable named tar not found on path" on Windows since 2.1.3 from 1.9.3 with url dep

### ISSUE THREAD

**Issue by dten** [commercialhaskell/stack#5249]
As part of our upgrade we stopped using a custom package index and referenced the tar ball as suggested previously in https://github.com/commercialhaskell/stack/issues/4846 i.e. using a `url` `extra-deps` to a `.tar.gz` 

What I'm seeing now though and I assume it's related to this is that whilst trying to setup the snapshot stack exists with

`Executable named tar not found on path"

I've made an assumption here that when getting packages from an index such as hackage the `tar.gz` is downloaded and extracted by `stack` with no issue. If so it seems like an error that it would be required for the `url` dep.

**Comment by dten** [comment]
Seems that whilst windows 10 comes with `tar` windows 7 does not

**Comment by mpilgrem** [comment]
I am closing as Windows 7 end of paid support by Microsoft was 10 January 2023 and Windows comes with `tar` since Windows 10.
