### ISSUE TITLE
Support public sublibraries

### ISSUE THREAD

**Issue by expipiplus1** [commercialhaskell/stack#5256]
It would be super to be able to use cabal 3's `visibility: public` feature (https://fgaz.me/posts/2019-11-14-cabal-multiple-libraries/) on auxiliary libraries. Personally I'd like to make use of this feature to avoid cluttering the write-only namespace on Hackage/Stackage. This is also quite important IMO for backpack due to the number of different libraries required for a backpackized project. 
 
Related: https://github.com/commercialhaskell/stack/issues/4910, https://github.com/commercialhaskell/stack/issues/2540 and https://github.com/commercialhaskell/stack/issues/4564

I couldn't find an existing issue for this, and perhaps this is a better fit for the Stackage repo.

**Comment by expipiplus1** [comment]
oh, perhaps stack already has support here, I see there's a test here: https://github.com/commercialhaskell/stack/tree/master/test/integration/tests/cabal-public-sublibraries

**Comment by Qiu233** [comment]
Is there a way to declare multiple libraries in `package.yaml`?

**Comment by mpilgrem** [comment]
@Qiu233, Cabal sublibraries? I think not, given: https://github.com/sol/hpack/issues/483.

**Comment by hasufell** [comment]
@mpilgrem hpack is an optional feature. One doesn't need to use it in order to use stack.

**Comment by mpilgrem** [comment]
On the topic of Stack supporting Cabal's public sublibraries, there is also #4745 (component-based builds).

**Comment by mmhat** [comment]
> oh, perhaps stack already has support here, I see there's a test here: https://github.com/commercialhaskell/stack/tree/master/test/integration/tests/cabal-public-sublibraries

I think this issue can be closed, can't it?

**Comment by mpilgrem** [comment]
@mmhat, if you are proposing this issue be closed because Stack supports public sublibraries, Stack does not (yet) support them.

**Comment by mpilgrem** [comment]
I am closing this issue because #6343 has been merged.
