### ISSUE TITLE
Failed to parse field 'setup-info'

### ISSUE THREAD

**Issue by xuyulim** [commercialhaskell/stack#5270]
I added the below line in the config.yaml, but ran into a problem nowadays.
```
setup-info: "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"
```

```
Could not parse '~/.stack/config.yaml':
Aeson exception:
Error in $['setup-info']: failed to parse field 'setup-info': parsing SetupInfo failed, expected Object, but encountered String
```

```
~ stack --version
Version 2.3.0.1
```

**Comment by Escapingbug** [comment]
I also run into this problem. This field seems to be changed. Use:

```yaml
setup-info-locations:
  - "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"
```
now.

**Comment by xuyulim** [comment]
Thanks. It woks.

**Comment by chenyulue** [comment]
> 
> 
> I also run into this problem. This field seems to be changed. Use:
> 
> ```yaml
> setup-info-locations:
>   - "http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"
> ```
> 
> now.

My stack version is 2.3.1, and it doesn't work, which shows `ConnectionFailure user error`.

> Exception while reading snapshot from lts-15.13:
> HttpExceptionRequest Request {
>   host                 = "raw.githubusercontent.com"
>   port                 = 443
>   secure               = True
>   requestHeaders       = [("User-Agent","Haskell pantry package")]
>   path                 = "/commercialhaskell/stackage-snapshots/master/lts/15/13.yaml"
>   queryString          = ""
>   method               = "GET"
>   proxy                = Nothing
>   rawBody              = False
>   redirectCount        = 10
>   responseTimeout      = ResponseTimeoutDefault
>   requestVersion       = HTTP/1.1
> }
>  (ConnectionFailure user error (Network.Socket.gai_strerror not supported: 11004))

**Comment by Escapingbug** [comment]
I have run into this problem long ago, but cannot remember the solution right now. From the message you showed, this is a proxy issue, since you can't connect to "raw.githubcontent.com" in China.

As I remembered, my solution is to get a proxy and do setup phase, then it will use mirror to download the packages I need. I think this problem is that, this mirror does not handle setup phase (downloading GHC for example).

**Comment by chenyulue** [comment]
@Escapingbug Thanks for the suggestion! I find a workaround [here](https://blog.csdn.net/qq_40464014/article/details/105911061).
Add `199.232.4.133 raw.githubusercontent.com` into `C:\Windows\System32\drivers\etc\hosts`, and then everything is OK.
