### ISSUE TITLE
Improve stack document: There is some ambiguity about extra-deps

### ISSUE THREAD

**Issue by chansey97** [commercialhaskell/stack#5271]
### General summary

I read stack document from https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-deps , it says that

> For the local file path case, the same relative path rules as apply to packages apply.

This sentence is not really correct.

For example,

Suppose you have a package named "pretty-tree-2", you can copy this package to your project folder and setup "stack.yaml" as following:
```
packages:
- .
- pretty-tree-2
```
It will build successfully.

But if you setup "stack.yaml" as following:
```
extra-deps: 
  - pretty-tree-2
```

It will build failed.

```
Cabal file info not found for pretty-tree-2, updating
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
No package index update available and cache up to date
Package index cache populated
Could not find pretty-tree-2 on Hackage
Possible candidates: pretty-tree-0.1.0.0@sha256:49b0e17008f9d30328db2bcc2958f3a7b78d154d2335c2dbaa2073e237b524ae,668.
```

But if you setup "stack.yaml" as following:

```
extra-deps: 
  - ./pretty-tree-2
```

It will build successfully.

This means that in "extra-deps:" we need state relative path explicitly by "./", but in "packages:"  you don't have to.

I guess that stack parse "pretty-tree-2" as a package called pretty-tree, version 2. So it attempt to download "pretty-tree-2" from Hackage.

This may confuses many people.

More detail see this discussion https://chat.stackoverflow.com/rooms/212165/discussion-between-bradrn-and-chansey

### Expected

Remove the ambiguity in document.

### Actual

There is some ambiguity in document.

### Stack version

```
$ stack --version
Version 2.1.3, Git revision 0fa51b9925decd937e4a993ad90cb686f88fa282 (7739 commits) x86_64 hpack-0.31.2
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mpilgrem** [comment]
@chansey97, thanks for reporting. This is now clarified in the online documentation.
