### ISSUE TITLE
Feature: --only-locals flag

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#5272]
Motivation: on a number of projects, we use CI jobs where all snapshot dependencies are built and saved in a Docker image. This means that the CI job itself runs fairly quickly, only building local packages. However, if a new dependency is added or the build plan is changed, the CI job may end up building snapshot packages.

With `--only-locals`, we would be able to say "if the build plan involves building anything except a local package, then fail."

**Comment by axel-h** [comment]
With v2.5.1 there still see to be corner cases where this does not work
```
$ stack build --fast --only-locals
Exception while reading snapshot from https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/9/21.yaml:
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/commercialhaskell/stackage-snapshots/master/lts/9/21.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
```
