### ISSUE TITLE
get.haskellstack.org is down

### ISSUE THREAD

**Issue by andys8** [commercialhaskell/stack#5276]
### General summary/comments

The official install method is currently not working.

![image](https://user-images.githubusercontent.com/13085980/80107499-6b8b8a00-857b-11ea-81a3-b41e1b2d4e6e.png)

### Steps to reproduce

```shell
curl -sSL https://get.haskellstack.org
500: Internal Server Error⏎
```

### Expected

Installation working

### Actual

Http Error 500

**Comment by andys8** [comment]
```

**Comment by manumc** [comment]
IDK if this is related but https://docs.haskellstack.org/ not working either.

```
$ curl -sSL https://docs.haskellstack.org/
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```

**Comment by andys8** [comment]
The original issue is resolved

@manumc Can confirm but I guess the cause is different. Could you create a new issue?
