### ISSUE TITLE
stack upgrade fails on OS X

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#528]
```
$ stack upgrade
Fetched package index.
Populated index cache.
stack-9.9.9: downloading
Downloaded lts-2.9 build plan.
Caching build plan
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:
      base: needed (>=4.7 && <5 && <0), but 4.7.0.2 found
    needed for package: stack-9.9.9
$ stack --version
Version 0.1.1.0, Git revision 91fe70306f51eb3d68667a0d6e09a7d7ebbeb2b6
```

**Comment by manny-fp** [comment]
If you are on stack-0.1.1.0, this is a known issue (and is fixed in stack-0.1.2.0).  Please try `stack upgrade --git && stack upgrade`.

**Comment by phadej** [comment]
... and make sure you have `~/.local/bin` in `PATH`.

**Comment by bitemyapp** [comment]
Dang, thank you @manny-fp and @phadej :)

**Comment by pradd** [comment]
Not sure if it is an issue, but the solution proposed by @bitemyapp  doesn't work as expected:
"stack upgrade --git" builds the latest version from git,
but then "stack upgrade" does nothing saying "Already at latest version, no upgrade required".
My expectation was is had to downgrade to latest release.

**Comment by bitemyapp** [comment]
@pradd I just use whatever's latest master (via `upgrade --git`) for now and it's working for me now.

**Comment by pradd** [comment]
It worked for me too, but in general switching to an unstable current source is very different from upgrade to the latest stable release.
