### ISSUE TITLE
Missing feedback for initial "Downloading index"

### ISSUE THREAD

**Issue by cwitty** [commercialhaskell/stack#5287]
Please follow the steps below for reporting a bug:

Make sure that you are using the latest release (currently stack-2.3.1).
See the [upgrade instructions](http://docs.haskellstack.org/en/stable/install_and_upgrade/#upgrade) to upgrade.

Please use the following schema for your bug report:

### General summary/comments (optional)

I've got a very slow Internet connection here.  When I followed directions and typed "stack setup" the first time, it apparently hung at "Downloading index" and didn't do anything for several minutes.  I didn't expect the "index" to be an 88 megabyte file, so I assumed that something had gone wrong; so I hit Control-C and restarted.  (The second time, I waited even longer, and this time it worked.)

### Steps to reproduce

1. Get some very slow Internet access.
2. Reinstall stack from scratch; make sure you don't have the index file downloaded.
3. Type "stack setup"

### Expected

The "Downloading index" phase should either complete quickly, or provide progress feedback.  For instance, stack does provide progress feedback as it's downloading the ghc binary; using that code for downloading the index file would have kept me from assuming stack had hung.

### Actual

"Downloading index" just sat there for several minutes, apparently doing nothing.  (When I hit Control-C and restarted, I actually used the "-v" verbose flag for the restart; even under verbose, "Downloading index" provides no progress feedback.)

### Stack version

```
$ stack --version
Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0
```

### Method of installation

```
wget -qO- https://get.haskellstack.org/ | sh
```

**Comment by mpilgrem** [comment]
I am going to close this issue as 'won't fix' because Stack (in fact, `pantry`) depends on the `hackage-security` package which handles the downloading of the package index.
