### ISSUE TITLE
have `stack ghci` work more like `cabal repl` in terms of sandboxing .hi and .o files

### ISSUE THREAD

**Issue by wolftune** [commercialhaskell/stack#529]
After running `stack ghci`, all my .hs files have corresponding .hi and .o files. I don't like having those pollute my project directory, so I'm hoping there could be a way to run this where those are stored in some separate hidden or sandboxed place…

**Comment by pharpend** [comment]
FWIW, I can reproduce this

**Comment by DanBurton** [comment]
+1

On Monday, July 6, 2015, Peter Harpending <notifications@github.com> wrote:

> FWIW, I can reproduce this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/529#issuecomment-118920959>
> .
>


-- 
-- Dan Burton

**Comment by chrisdone** [comment]
This is easy enough, will do.

**Comment by chrisdone** [comment]
Implemented in 712c965. @wolftune Confirm?

**Comment by wolftune** [comment]
@chrisdone how do I install this to test? Do I need to run `stack upgrade --git` ? I'm a *little* confused about the strange docs around upgrading with vague references to "this" in the upgrade stuff and then link to an issue comment…

**Comment by chrisdone** [comment]
`stack upgrade --git` works. I tend to just have the git repo open and do `stack install`.

**Comment by wolftune** [comment]
@chrisdone it appears that I didn't have stuff polluted with .o files but I still got .hi files.

I also had a separate problem that appears to be related to failing to import Prelude or something where I had a failure at one point even though I did end up at the prompt anyway…

**Comment by chrisdone** [comment]
Oh, I always thought `-odir` handled interface files too. Turns out there's a `-hidir` flag, which I've added now in fbcdf56.

**Comment by wolftune** [comment]
Yay, it's all working!

**Comment by lukexi** [comment]
Just FYI, there's also -outputdir which I believe redirects all output files in one go (off the top of my head there's also e.g. dyn_o files in dynamic mode, and stub files for foreign exports, so it might be an easier way to go)
