### ISSUE TITLE
Add `--[no-]save-hackage-creds` to `stack upload`

### ISSUE THREAD

**Issue by koterpillar** [commercialhaskell/stack#5290]
### General summary/comments (optional)

When using `HACKAGE_USERNAME` and `HACKAGE_PASSWORD` to run `stack upload` in a non-interactive environment (e.g. on CI), Stack still offers to save those to a file with an interactive prompt and aborts the upload.

### Steps to reproduce

* Create a new Stack project.
* `HACKAGE_USERNAME=fake HACKAGE_PASSWORD=fake stack upload . </dev/null`

### Expected

Package uploaded (if the credentials are correct), or an error message from Hackage saying the credentials are incorrect.

### Actual

```
<stdin>: hGetLine: end of file
Failed to upload to Hackage.
Save hackage credentials to file at <SNIP>/.stack/upload/credentials.json [y/n]? 
```

```
$ stack upload --verbose .
2020-05-03 XX:XX:XX.XXXXXX: [info] Checking package '<SNIP>' for common mistakes
Save hackage credentials to file at <SNIP>/.stack/upload/credentials.json [y/n]? 2020-05-03 XX:XX:XX.XXXXXX: [error] <stdin>: hGetLine: end of file
Failed to upload to Hackage.
```

### Stack version

```
$ stack --version
Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0
```

### Method of installation

`curl -sSL https://get.haskellstack.org/ | sh`

**Comment by koterpillar** [comment]
I would argue that when the environment variables are provided, it doesn't make sense to ask anyway, since the deployment is likely scripted.

**Comment by EduardSergeev** [comment]
I had the same problem when also trying to setup automatic upload via Github actions (Stack v2.3.3).
The error message is also confusing:
```
Checking package 'monad-memo' for common mistakes
<stdin>: hGetLine: end of file
Save hackage credentials to file at /home/runner/.stack/upload/credentials.json [y/n]? 
##[error]Process completed with exit code 1.
```
Adding `save-hackage-creds: false` to project's `stack.yaml` does fix the issue but looks more like a workaround (maybe there should be at least a flag for `stack upload` which would pass `y` or `n` to it thus disabling the prompt?).
