### ISSUE TITLE
Fail to build with cabal-install

### ISSUE THREAD

**Issue by ulysses4ever** [commercialhaskell/stack#5298]
### General summary/comments (optional)

Stack 2.3.1 fails to install for me when using Hackage and cabal-install.

### Steps to reproduce

1. `cabal update`
2. `cabal install stack`

### Expected

Stack installs.

### Actual

```
...
Building library for stack-2.3.1..
...
[ 29 of 109] Compiling Stack.Types.Resolver ( src/Stack/Types/Resolver.hs, dist/build/Stack/Types/Resolver.o, dist/build/Stack/Types/Resolver.dyn_o )

src/Stack/Types/Resolver.hs:71:17: error:
    Ambiguous occurrence ‘SnapName’
    It could refer to
       either ‘Stack.Prelude.SnapName’,
              imported from ‘Stack.Prelude’ at src/Stack/Types/Resolver.hs:34:1-30
              (and originally defined in ‘pantry-0.5.0.0:Pantry.Types’)
           or ‘Stack.Types.Resolver.SnapName’,
              defined at src/Stack/Types/Resolver.hs:67:1
   |
71 | instance NFData SnapName
   |                 ^^^^^^^^
```

There are several more errors of the same kind (Ambiguous occurrence) after this first one -- about `LTS`, `Nightly`, etc.

### Stack version

2.3.1.

### Method of installation

* Via cabal-install
* GHC version: 8.10.1
* Cabal version: 3.2

**Comment by kirelagin** [comment]
That is because `SnapName` was copied to pantry-0.5.0.0 and, apparently, now it gets re-exported from `Stack.Prelude`. You need `pantry < 0.5` to build this version of stack.

**Comment by ulysses4ever** [comment]
Thanks, @kirelagin, it does work with the constraint, indeed. I'm not sure if the issue should be closed or not, so I leave it to decide for those more knowledgeable.

**Comment by jwaldmann** [comment]
Sometimes this helps: if there is a successful build report on hackage (in this case, https://hackage.haskell.org/package/stack-2.3.1/reports/1), do 
```
cabal update 'hackage.haskell.org,2020-04-29T20:25:58Z'
```
(use the date of the report) then `cabal install`.

**Comment by jwaldmann** [comment]
currently,  this seems to work  for stack-2.3.3 and -2.5.0.1, with ghc-8.10.2 and -8.8.4:
```
cabal install --constraint 'base16-bytestring==0.1.1.7' --constraint 'optparse-applicative==0.15.1.0'
```
(that's the versions given in the stackage resolver)

**Comment by arrowd** [comment]
I was able to compile Stack with simple `cabal new-update && cabal new-configure && cabal new-build`.

**Comment by jwaldmann** [comment]
Yes. Can confirm. Then it should also work on hackage? https://hackage.haskell.org/package/stack-2.5.1/reports/ has "no reports available".

**Comment by jwaldmann** [comment]
Truly, a never-ending story. Today's (Tue Nov 10 21:05:29 CET 2020) magic spell seems to be
```
cabal install  --constraint 'persistent==2.10.*'  stack-2.5.1
```

**Comment by jwaldmann** [comment]
while today (Thu Apr  1 20:53:47 CEST 2021) it's `cabal install stack --constraint 'persistent==2.12.*' --constraint 'persistent-template==2.9.1.0'` for me.

**Comment by jwaldmann** [comment]
I was trying to cabal-install  stack-2.7.5. It seems that this works  (cf. https://github.com/JustusAdam/mustache/issues/58)
```
cabal v2-update 'hackage.haskell.org,2022-03-10T11:40:42Z'
cabal install -w/opt/ghc/ghc-8.10.7/bin/ghc stack-2.7.5 --constraint 'unordered-containers<0.2.17' --constraint 'aeson<2'
```
This pinning of cabal's index is like a poor man's resolver - except that it isn't, since cabal still prefers installed versions? Anyway I checked that the above works after `rm -rfv .cabal/store/ghc-8.10.7/` (which also destroyed my `cabal` executable ...)

**Comment by Bodigrim** [comment]
@jwaldmann I don't follow: `stack-2.7.5` mandates `aeson < 1.6` and `mustache >= 2.3.1`, which implies `unordered-containers < 0.2.17`. So both `--constraint` in your incantation are redundant and I believe that fixing `index-state` is redundant as well. At least, `stack install stack-2.7.5` succeeds on my machine as is.

**Comment by hasufell** [comment]
> @jwaldmann I don't follow: `stack-2.7.5` mandates `aeson < 1.6` and `mustache >= 2.3.1`

I guess some people might experience the result of https://github.com/commercialhaskell/stack/pull/5677

It's not clear from the reports if people cloned the repo and attempted install or pulled from hackage.

**Comment by jwaldmann** [comment]
Sorry, it's a mess. This works:
```
cabal install  -w /opt/ghc/ghc-8.10.7/bin/ghc --index-state='2022-03-10T11:40:42Z' --one-shot stack-2.7.5
```
but I'm not at all sure about those cabal options (whether they make the build reproducible). Anyway I thought it's good to note  a buildable hackage state, for when I might need to re-build this in a few weeks, or months, time.

**Comment by hasufell** [comment]
> (whether they make the build reproducible)

That depends on what you mean by that. Pinning index state doesn't ensure the same resolution, mainly because of package flags and pkg-config depends.

**Comment by Bodigrim** [comment]
As a Hackage trustee, I made a bunch of revisions, prohibiting unbuildable configurations. This is far from bulletproof, but at least shields from most common conflicts.

https://hackage.haskell.org/package/pantry-0.2.0.0/revisions
https://hackage.haskell.org/package/pantry-0.4.0.2/revisions
https://hackage.haskell.org/package/pantry-0.5.2/revisions
https://hackage.haskell.org/package/pantry-0.5.2.1/revisions
https://hackage.haskell.org/package/pantry-0.5.2.2/revisions
https://hackage.haskell.org/package/pantry-0.5.2.3/revisions

https://hackage.haskell.org/package/stack-2.1.3.1/revisions
https://hackage.haskell.org/package/stack-2.3.1/revisions
https://hackage.haskell.org/package/stack-2.3.3/revisions
https://hackage.haskell.org/package/stack-2.5.1/revisions
https://hackage.haskell.org/package/stack-2.5.1.1/revisions
https://hackage.haskell.org/package/stack-2.7.1/revisions
https://hackage.haskell.org/package/stack-2.7.3/revisions
https://hackage.haskell.org/package/stack-2.7.5/revisions

**Comment by ulysses4ever** [comment]
Whoever reports on sucessful builds, please, specify versions of GHC and cabal you're using. I currently fail to build stack-2.7.5 (sources delivered by `cabal get stack-2.7.5`) using GHC 9.0 and cabal 3.6 because it wants an older Cabal, which, in turn, requires an older `base`:
<details><pre><code>❯ cabal build -j                                                                                                                                                                                                                                                    0 (0.007s) < 18:09:34
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: stack-2.7.5 (user goal)
[__1] trying: base-4.15.1.0/installed-4.15.1.0 (dependency of stack)
[__2] next goal: Cabal (dependency of stack)
[__2] rejecting: Cabal-3.4.1.0/installed-3.4.1.0 (conflict: stack =>
Cabal>=3.2.1.0 && <3.4)
[__2] skipping: Cabal-3.6.3.0, Cabal-3.6.2.0, Cabal-3.6.1.0, Cabal-3.6.0.0,
Cabal-3.4.1.0, Cabal-3.4.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=3.2.1.0 && <3.4' from
'stack')
[__2] rejecting: Cabal-3.2.1.0 (conflict: base==4.15.1.0/installed-4.15.1.0,
Cabal => base>=4.6 && <4.15)
[__2] skipping: Cabal-3.2.0.0, Cabal-3.0.2.0, Cabal-3.0.1.0, Cabal-3.0.0.0,
Cabal-2.4.1.0 (has the same characteristics that caused the previous version
to fail: excludes 'base' version 4.15.1.0)
[__2] rejecting: Cabal-2.4.0.1 (conflict: stack => Cabal>=3.2.1.0 && <3.4)
[__2] skipping: Cabal-2.4.0.0, Cabal-2.2.0.1, Cabal-2.2.0.0, Cabal-2.0.1.1,
Cabal-2.0.1.0, Cabal-2.0.0.2, Cabal-1.24.2.0, Cabal-1.24.0.0, Cabal-1.22.8.0,
Cabal-1.22.7.0, Cabal-1.22.6.0, Cabal-1.22.5.0, Cabal-1.22.4.0,
Cabal-1.22.3.0, Cabal-1.22.2.0, Cabal-1.22.1.1, Cabal-1.22.1.0,
Cabal-1.22.0.0, Cabal-1.20.0.4, Cabal-1.20.0.3, Cabal-1.20.0.2,
Cabal-1.20.0.1, Cabal-1.20.0.0, Cabal-1.18.1.7, Cabal-1.18.1.6,
Cabal-1.18.1.5, Cabal-1.18.1.4, Cabal-1.18.1.3, Cabal-1.18.1.2,
Cabal-1.18.1.1, Cabal-1.18.1, Cabal-1.18.0, Cabal-1.16.0.3, Cabal-1.16.0.2,
Cabal-1.16.0.1, Cabal-1.16.0, Cabal-1.14.0, Cabal-1.12.0, Cabal-1.10.2.0,
Cabal-1.10.1.0, Cabal-1.10.0.0, Cabal-1.8.0.6, Cabal-1.8.0.4, Cabal-1.8.0.2,
Cabal-1.6.0.3, Cabal-1.6.0.2, Cabal-1.6.0.1, Cabal-1.4.0.2, Cabal-1.4.0.1,
Cabal-1.4.0.0, Cabal-1.2.4.0, Cabal-1.2.3.0, Cabal-1.2.2.0, Cabal-1.2.1,
Cabal-1.1.6, Cabal-1.24.1.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=3.2.1.0 && <3.4' from
'stack')
[__2] fail (backjumping, conflict set: Cabal, base, stack)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: stack, Cabal, base</code></pre></details>

Allow-newer Cabal allows the solver to succeed but the build fails because of API changes in the newer Cabal.

**Comment by Bodigrim** [comment]
No `stack` release is buildable with GHC 9.0 at the moment.

**Comment by ulysses4ever** [comment]
This is helpful, thanks. I wish the cabal file was more specific in the `base >=4.10 && <5` bit.
