### ISSUE TITLE
reasonable way to install stack?

### ISSUE THREAD

**Issue by aryairani** [commercialhaskell/stack#5320]
In `doc/README.md`, it says "the easiest way to install is to run: `curl -sSL https://get.haskellstack.org/ | sh`"

but in `doc/travis_ci.md`, it says "there is only one reasonable way to install Stack: fetch precompiled binary from the Github." and gives this curl / tar combo:
```yaml
before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
```

I'm trying to read between the lines here to understand the difference between easy and reasonable.  Are these Travis instructions still current?  Will I encounter issues if I use the "easy" method in my Travis script?

Thanks in advance!

**Comment by mpilgrem** [comment]
If you examine the script at `https://get.haskellstack.org/` (the one obtained by `curl` and then piped to `sh` for the easy method), I think you will see that it also actually fetches the pre-compiled binary from the same place. I think 'from the Github` is not accurate.
