### ISSUE TITLE
No mention of Windows on stack installation page official link

### ISSUE THREAD

**Issue by AMDphreak** [commercialhaskell/stack#5321]
### General summary/comments (optional)

The [Windows installation instructions for Haskell Platform](https://www.haskell.org/platform/windows.html) links to this [doc page](https://docs.haskellstack.org/en/stable/README/), which says nothing about Windows at all and is exclusively Linux-oriented. While I found a valuable procedure by navigating to the [Developing Under Windows](https://docs.haskellstack.org/en/stable/developing_on_windows/) page, there is probably a reason that the link goes to the overall stack installation page.

**Comment by qrilka** [comment]
Quoting the doc page you mention:

> On Windows, you can download and install the Windows 64-bit Installer.

This doesn't look like "says nothing about Windows at all".

**Comment by AMDphreak** [comment]
> Quoting the doc page you mention:
> 
> > On Windows, you can download and install the Windows 64-bit Installer.
> 
> This doesn't look like "says nothing about Windows at all".

No major section heading, 1 line, skipping. Can't sit and read the page line for line.

Consider this page: https://docs.haskellstack.org/en/stable/install_and_upgrade/
