### ISSUE TITLE
stack exec help docs wrong

### ISSUE THREAD

**Issue by AMDphreak** [commercialhaskell/stack#5322]
### General summary/comments (optional)
The help docs/tips are not accurate for `stack exec`. The abstract shows the CMD before the `--` but the examples show the CMD after the `--`:

```
PS C:\Windows\system32> stack exec --
Missing: CMD
Usage: stack.exe exec CMD [-- ARGS (e.g. stack exec -- ghc-pkg describe base)]
[--[no-]ghc-package-path] [--[no-]stack-exe]
[--package ARG] [--rts-options RTSFLAG] [--cwd DIR]
[--setup-info-yaml URL] [--help]
Execute a command
```

[online docs](https://docs.haskellstack.org/en/stable/developing_on_windows/)

### Stack version

```
$ stack --version
Version 2.3.1, Git revision de2a7b694f07de7e6cf17f8c92338c16286b2878 (8103 commits) x86_64 hpack-0.33.0
```

### Method of installation

* Windows chocolatey installation process

**Comment by mpilgrem** [comment]
Is it a question of _accuracy_, or is it a question of _completeness_ or _consistency_. For example (in PowerShell), these are equivalent:
```
stack exec where.exe -- ghc
stack exec -- where.exe ghc
```
That is, if the CMD is 'empty' (as in the second example), the first of the ARGS is taken to be a command.

So, perhaps the help text should be (for consistency):
```
Usage: stack.exe exec CMD [-- ARGS (e.g. stack exec ghc-pkg -- describe base)]
                      [--[no-]ghc-package-path] [--[no-]stack-exe]
                      [--package ARG] [--rts-options RTSFLAG] [--cwd DIR]
                      [--setup-info-yaml URL] [--snapshot-location-base URL]
                      [--help]
  Execute a command
```
