### ISSUE TITLE
--verbosity info is too terse compared to --verbosity debug

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#5323]
### General summary/comments

I would like to have `--verbose`  be an alias for `--verbosity info` with some of the more informative output from `--verbosity debug` promoted to info.

eg I don't think `stack --verbose` should output all of RawSnapshotLayer: for most general stack users it is not useful and it makes for example `stack -v install` output too heavy.

### Steps to reproduce

For example:

1. run `stack -v install`

### Expected

details like resolver snapshot paths and compiler chosen, etc

### Actual

Outputs all of RawSnapshotLayer - too much information :)

### Stack version

2.3.1

### Method of installation

* Via cabal-install
* An unofficial package repository: Fedora

**Comment by phlummox** [comment]
Yes -- I ran across this issue while trying to work out what was happening in #5326 . `verbosity --info` gives you literally nothing at all when you execute a minimal 
```
main = print ()
```
script, but `verbosity-debug`  gives you 456K of output. Surely there's a happy medium between the two...

**Comment by mpilgrem** [comment]
See also https://github.com/commercialhaskell/pantry/issues/44.

**Comment by juhp** [comment]
Thanks! - will be excited to test this at some point
