### ISSUE TITLE
`stack install package` should display package version first

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#5336]
When running `stack install some-package` I would really like to know up front what version stack has selected.
Specially if it is pulling from Hackage say. Often I end up seeing the final completed built version is older than what
I want and then have to go back and run `stack install some-package-version`.

What would be nice is if there were an easy way to get stack to show what version a package would resolve to.
Even something like `stack install [-n|--dryrun]` perhaps.

**Comment by mpilgrem** [comment]
`stack install` is a shortcut for `stack build --copy-bins` and both `stack install` and `stack build` have a `--dry-run` flag. As such, perhaps `stack install some-package-version --dry-run` provides what you are seeking? For example, on my PC:
```
stack install pandoc --dry-run
```
yields:
```
No packages would be unregistered.

Would build:
HTTP-4000.3.14: database=snapshot, source=HTTP (from Hackage)
...
pandoc-2.7.3: database=snapshot, source=pandoc (from Hackage), after: HTTP-4000.3.14,HsYAML-0.1.2.0,JuicyPixels-3.3.4,SHA-1.6.4.4,aeson-pretty-0.8.8,cmark-gfm-0.2.1,data-default-0.7.1.1,doctemplates-0.2.2.1,haddock-library-1.7.0,hslua-1.0.3.2,hslua-module-system-0.2.1,hslua-module-text-0.2.1,ipynb-0.1,pandoc-types-1.17.6.1,skylighting-0.8.2.1,tagsoup-0.14.8,texmath-0.11.3,xml-1.3.14
...
xml-1.3.14: database=snapshot, source=xml (from Hackage)

Would install executables:
pandoc from snapshot database
```

**Comment by juhp** [comment]
Good point, thanks (though I still feel my rfe is valid -- condemned by my own words etc haha).

I will try to remember to use --dry-run next time.
