### ISSUE TITLE
Centos source repository access denied

### ISSUE THREAD

**Issue by james64** [commercialhaskell/stack#5337]
I want to install stack on centos using package manager by instructions [in docs](https://docs.haskellstack.org/en/v1.0.2/install_and_upgrade/#centos-red-hat-amazon-linux). However the amazonaws download url gives me an access denied error message:
```bash
$ curl -sSL https://s3.amazonaws.com/download.fpcomplete.com/centos/7/fpco.repo
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>021BACDBD309F099</RequestId><HostId>w1hTtl2BZ9otGxgdrEFYnKHcjzv3N0qDal0A5N6prWDGeLM5XrZDx4s3oS1NPpbHzw4i4WLqf7U=</HostId></Error>
```

Am I missing something?

Thanks!

**Comment by psibi** [comment]
The linked doc is for quite an old version. Can you try the latest release docs instead: https://docs.haskellstack.org/en/v2.3.1/install_and_upgrade/

**Comment by james64** [comment]
:facepalm:
of course. Thank you!
