### ISSUE TITLE
Windows installer does not work 

### ISSUE THREAD

**Issue by schuelermine** [commercialhaskell/stack#5339]
### General summary/comments (optional)

The Windows 64-bit installer for Stack 2.31 can't be run.

### Steps to reproduce

Run `stack-2.3.1-windows-x86_64-installer.exe`.

### Expected

Stack being installed.

### Actual

This dialog-box popped up:
![stack-install-error](https://user-images.githubusercontent.com/48802534/86711995-d433c000-c01c-11ea-9e30-9c5f42e301a2.png)

Translation:
Application Error
The application could not be started correctly (0xc000007b).
Click on OK to close the application.

### Stack version

2.3.1

### Method of installation

Downloaded installer from GitHub releases page.

**Comment by NikolaiPohodenko** [comment]
stack-2.3.1-windows-x86_64-installer.exe   md5: 92d38c62f5328332f88ab9caf032a25c
installed successfully

**Comment by schuelermine** [comment]
Is it because I had mandatory ASLR enabled?

**Comment by NikolaiPohodenko** [comment]
Yes it is. with ASLR the installer crashes immediately.

**Comment by schuelermine** [comment]
OK.
