### ISSUE TITLE
Add option to merely build tests

### ISSUE THREAD

**Issue by pharpend** [commercialhaskell/stack#534]
In developing software, it's often helpful to write a suite of failing tests, and then write library functions to make the tests pass. When I'm in the test-writing stage, I don't need stack to tell me that the tests are failing, I just want to make sure they type-check.

Could you please add an option to not run the tests, but just to build them?

Perhaps there already is an option, but I can't find it in the documentation.

**Comment by snoyberg** [comment]
Check out the recently added `--no-run-tests` from #517.
