### ISSUE TITLE
How can I pass flags to cabal?

### ISSUE THREAD

**Issue by codygman** [commercialhaskell/stack#535]
For instance I want dev to be set for this part of my cabal file:

```
if flag(dev) || flag(library-only)
        cpp-options:   -DDEVELOPMENT
        ghc-options:   -Wall -fwarn-tabs -O0
    else
        ghc-options:   -Wall -fwarn-tabs -O2
```

**Comment by snoyberg** [comment]
See the `--help` for the `--flag` option, it's basically `--flag packagename:(-)flagname`.

**Comment by codygman** [comment]
`--flag` doesn't seem to work with `stack exec --flag executable:-fdevelopment -- yesod devel`. I think it works when using `stack exec --flag executable:-fdevelopment build`.

**Comment by snoyberg** [comment]
That's quite a different story. The question is really "how do I tell `yesod devel` to change flags," right? I'm not sure what you're trying to do though, `yesod devel` already sets the appropriate flags to work well with the scaffolding. Can you describe your goal a bit more clearly?

**Comment by codygman** [comment]
I am trying to get my compile cycle to be faster, there was a ghc option
like "no-code" or something I wanted to try.

**Comment by snoyberg** [comment]
It won't work with yesod sites anyway, since no-code can't be used when
you're using template Haskell.
