### ISSUE TITLE
commitBuffer: invalid argument (invalid character) error -- (Fixed)

### ISSUE THREAD

**Issue by fabirkmann** [commercialhaskell/stack#5350]
Hi,

when running `stack build` I am getting
`commitBuffer: invalid argument (invalid character)` 
as in [https://github.com/commercialhaskell/stack/issues/793](url).

The error disappears when setting `LC_ALL=C.UTF-8`  as suggested in 793 and reappers when `unset`ting `LC_ALL`.

- Stack version: 2.3.1 x86_64 hpack-0.34.2
- OS: Ubuntu 20.04
- LTS: Tried both LTS-14.7 and (at the time newest on Stackage) LTS-16.6

I had the same problem after an upgrade to Ubuntu 20.04. 

Cheers

**Comment by BebeSparkelSparkel** [comment]
same problem with building language-javascript. It requires 

`export LC_ALL=en_US.UTF-8` before running `stack build` is there a way to specify that stack should set ther variable in stack.yaml?

**Comment by mpilgrem** [comment]
I am closing this issue as it is marked as fixed.

In respect of setting environment variables in Stack's configuration files that was discussed in #1375 but ultimately closed without that feature being added.
