### ISSUE TITLE
What http uri patterns to whilelist in a proxy for stack?

### ISSUE THREAD

**Issue by luntain** [commercialhaskell/stack#5367]
Is there a list of the patterns to whitelist in a proxy for stack to be able to download tools and packages?

**Comment by mpilgrem** [comment]
@luntain, I am working through open issues, including old ones. Probably too late for you but it may help others:

* `pantry` provides `defaultCasaRepoPrefix`, which is `https://casa.stackage.org`
* `pantry` provides `defaultDownloadPrefix` and `stack` provides `hackageBaseUrl`, which are `https://hackage.haskell.org`
* `stack` makes use of `https://stackage-haddock.haskell.org/snapshots.json`
* `stack ls` makes use of `https://stackage.org/snapshots`
* `pantry` and `stack`, by default, make use of information in various GitHub repositories, including `commercialhaskell/stackage-snapshots`, `commercialhaskell/stackage-content`, `commercialhaskell/stack-templates`, `commercialhaskell/stack` (to upgrade Stack)
* `stack` makes use of the URLs in the default `setup-info` dictionary at https://github.com/commercialhaskell/stackage-content/blob/master/stack/stack-setup-2.yaml
