### ISSUE TITLE
Windows install location and configuration

### ISSUE THREAD

**Issue by Allexxann** [commercialhaskell/stack#5373]
Is there any way no to install EVERYTHING into local user?
When I try to install to custom location, installer explicitly ignores it when updating %PATH%.
When i try to configure things manually, turns out some things are nailed down, like ghc location, again in local user.
When I try to look up documentation, it's written for linux and also doesn't deal with these questions.

Honestly, if you don't like Windows so much - why make Windows version at all?

**Comment by mpilgrem** [comment]
I use `stack` exclusively on Windows 10, and am keen to help make it more user-friendly for all Windows users. Can you clarify for me what you would like to customise? By 'install' do you mean the `stack install` command (an alias for `stack build --copy-bins`) and where it copies the binaries (location: `stack path --local-bin`)?

**Comment by Allexxann** [comment]
No. When you install the stack program itself from a distributive, it's default locations are all in "Users".
You can change the location of the main executable file, but all other paths, like folders for package database or new versions of compiler, are still in "Users" (and you aren't even informed, until you see commline log or check the folder manually), and even %PATH% modifier is still the default one, meaning you have to update it manually.

What I want is option to customize all these paths during the installation. Or at least easily configure them later: turns out some of them are hard-coded, or, at least, I couldn't find them in configs or system variables. I uninstalled stack months ago, so I cannot recall exactly which ones, but for the record I can check them.
I prefer to not use "Users" at all - too much surprises, too complicated paths. Instead I make a directory on another disk entirely, which I can adjust to my needs.

**Comment by mpilgrem** [comment]
In the case of non-Windows OS, the 'programs' (eg GHC itself) used by the `stack` application (which can be located anywhere itself) are located in a `programs` subfolder of the stack root folder (which root folder location is configurable). A code comment in `Config.getDefaultLocalProgramsBase` explains for Windows, however:
```haskell
-- For historical reasons, on Windows a subdirectory of LOCALAPPDATA is
-- used instead of a subdirectory of STACK_ROOT. Unifying the defaults would
-- mean that Windows users would manually have to move data from the old
-- location to the new one, which is undesirable.
```
So, it looks like two evils have been weighed up in the past: [1] the lack of consistency (and, consequently, less configurability on Windows); and [2] all existing Windows users of `stack` (who will have varying degrees of skill) having to move data manually - and the former chosen as the lesser evil.

On my system, the main 'programs'  take up ~2-3 GB for a GHC version and ~0.5  GB for MSYS2. `stack` is not the only application to make 'heavy' use of `%LOCALAPPDATA%` on my system: the `Packages` folder used by all Modern UI apps is ~ 8-9 GB, for example.

It seems to me that the design question is: For Windows users of `stack` who do know what they are doing and able to manually move data if they have to, should there be an override, say to achieve consistency with the non-Windows OS? Is it worth it for what, in modern terms, is relatively little storage space?

**Comment by Allexxann** [comment]
I was asking for an ability to configure _all_ the paths in question, overriding the hard-coded defaults, preferrably during the installation process too, as an optional step.
They **do not** have to be consistent among themselves - just make several independent path variables and explain what part of the program each of them governs.
This way the existing users won't have to move their stuff - by default they'll keep the paths already set, unless they choose otherwise.

And yes, I've encountered such an approach in multiple products, although they all are consumer pure GUI stuff, not professional programming tools. It's a bit annoying to configure 4-6 paths, but very user friendly.

**Comment by mpilgrem** [comment]
I closed this because (on Windows and non-Windows):
* the location of the Stack root is configurable
* the  location of Stack's 'programs' directory (where it puts GHC, MSYS2 etc) is configurable (https://docs.haskellstack.org/en/stable/yaml_configuration/#local-programs-path)
* Stack now, optionally, supports the XDG Base Directory Specification (https://docs.haskellstack.org/en/stable/GUIDE/#setting-the-stack-root-location)
