### ISSUE TITLE
name-as-module from stack new should be PascalCase

### ISSUE THREAD

**Issue by tim2CF** [commercialhaskell/stack#5376]
At the moment, command `stack new hello-world $TEMPLATE_NAME` generates project structure where `name-as-module` value is `Helloworld` instead of `HelloWorld`. Example

```bash
stack new hello-world \
  github:tkachuk-labs/nix-concur-replica \
  -p organization:tkachuk-labs \
  -p env-prefix:HELLO_WORLD \
  --resolver lts-14.27
```

**Comment by ardamose123** [comment]
The `Data.Text` function `toTitle` (used to generate the `name-as-module`) has a bug: apparently, dashes are considered as letters for some reason. This has to be fixed in the `text` package.

**Comment by ardamose123** [comment]
As a workaround,  I can submit a PR that first converts the dashes to spaces, then applies the title-casing, then removes spaces instead of dashes.

**Comment by ardamose123** [comment]
Submitted PR #5386 as a fix.

**Comment by tim2CF** [comment]
Thanks for the fix!
