### ISSUE TITLE
Add Windows 10 ARM64 Support

### ISSUE THREAD

**Issue by hmsjy2017** [commercialhaskell/stack#5377]
I am using a device which runs Windows 10 ARM64. However, x64 applications cannot run on it. I hope that you will release an arm64 version. Thank you!

**Comment by mpilgrem** [comment]
The `stack` tool is downstream of the Haskell compiler (GHC) itself. These two pages provide information about the systems supported by GHC: [1] https://gitlab.haskell.org/ghc/ghc/-/wikis/platforms and [2] https://gitlab.haskell.org/ghc/ghc/-/wikis/platforms/windows.

**Comment by mpilgrem** [comment]
Closing issue, because it does not look like GHC will support Windows/ARM64 in the foreseeable future.
