### ISSUE TITLE
Not compatible with optparse-applicative 0.16

### ISSUE THREAD

**Issue by Lysxia** [commercialhaskell/stack#5379]
### General summary/comments

optparse-applicative-0.16.0.0 added an argument to the `ShowHelpText` constructor of its `ParseError` type.

I can confirm that 0.15.1.0 fixes the build.

### Steps to reproduce

Build stack with optparse-applicative-0.16.0.0

```
src/Options/Applicative/Complicated.hs:155:17: error:
    • Couldn't match expected type ‘ParseError’
                  with actual type ‘Maybe String -> ParseError’
    • Probable cause: ‘ShowHelpText’ is applied to too few arguments
      In the first argument of ‘abortOption’, namely ‘ShowHelpText’
      In the expression: abortOption ShowHelpText
      In the expression:
        abortOption ShowHelpText
          $ long help <> help Show this help text
    |
155 |     abortOption ShowHelpText $
    |                 ^^^^^^^^^^^^
```

### Expected

(I use cabal) Cabal should pick a compatible version of optparse-applicative so the build succeeds.

### Actual

Build fails.

### Stack version

2.3.3 via Hackage

### Method of installation

cabal-install

**Comment by chenrui333** [comment]
Any update on this issue?

**Comment by mpilgrem** [comment]
The current `package.yaml` for Stack specifies `optparse-applicative >= 0.17.0.0`.
