### ISSUE TITLE
Support options like --package for the ghci command.

### ISSUE THREAD

**Issue by seanparsons** [commercialhaskell/stack#538]
It would be really handy to be able to launch a REPL with some random dependencies. Since the runghc command supports this I would assume this to be trivial?

**Comment by chrisdone** [comment]
Currently you can run `stack ghci --ghc-options "-package x"`.

**Comment by snoyberg** [comment]
I had read @seanparsons's comment as requesting a way to tell `stack` to install a package before running `ghci`, like `stack runghc -package foo bar.hs` would force the foo package to be available before running bar.hs. Am I correct?

@seanparsons The code used for `runghc` should transfer easily to ghci, would you be interested in trying out a PR to add this?

**Comment by seanparsons** [comment]
@snoyberg That is exactly what I was thinking. :+1:

**Comment by seanparsons** [comment]
I might give adding that feature a bash.

**Comment by snoyberg** [comment]
Cool, just ping if you need some advice.

**Comment by markus1189** [comment]
@seanparsons did you decide to work on this? Otherwise I will give this a shot myself :)

**Comment by seanparsons** [comment]
@markus1189 I've quite literally just forked the repo to give it a bash myself! :)

**Comment by markus1189** [comment]
have fun =)

**Comment by seanparsons** [comment]
@snoyberg Since this is in master, will this make it into the 0.2.0.0 milestone?

**Comment by snoyberg** [comment]
It will be in the next release.
