### ISSUE TITLE
Stack can't find `time` in `lts-16.13`, if local fork of `Win32` is specified

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#5382]
I am using the latest version of `stack` on Windows 10 version 2004, with resolver `lts-16.13`. (`stack --version` `Version 2.4.0, Git revision 1b1bed5b84b3aed76cf27b02cadd46d09efc611f (8207 commits) PRE-RELEASE x86_64`.)

I have a simple test program (named `win32test`) that is dependent on (1) the `time` package and (2) a local fork of the `Win32` package, so `stack.yaml`:
```yaml
resolver: lts-16.13
packages:
- .
- ../win32
```

and `package.yaml` (extract):
```yaml
dependencies:
- base >= 4.7 && < 5
- time
- Win32
```

However, `stack build` reports that `time` is missing:
```
> stack build

Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for win32test-0.1.0.0:
    time needed, but the stack configuration has no specified version  (latest matching version is 1.10)
needed since win32test is a build target.

Some different approaches to resolving this:

  * Recommended action: try adding the following to your extra-deps in C:\Users\mikep\Documents\Code\GitHub\win32test\stack.yaml:

- time-1.10@sha256:536801b30aa2ce66da07cb19847827662650907efb2af4c8bef0a6276445075f,5738

Plan construction failed.
```
If I comment out the reference to the local version of `Win32` in `stack.yaml`, `stack build` no longer complains that the stack configuration is missing `time`. (Also, if I supply `time` as an `extra-deps`, it builds.)

I don't follow why `stack` thinks `time` is missing from `lts-16.13` when I specify a local version of `Win32`.

**Comment by qrilka** [comment]
@mpilgrem the problem is caused by the fact that `time` and `Win32 are packages shipped with GHC, i.e. "global" or "boot" packages. When you override `Win32` you automatically disable `time` shipped with GHC. There is a blog post giving a bit more details about this kind of situations - https://www.snoyman.com/blog/2019/01/mismatched-global-packages

**Comment by mpilgrem** [comment]
Thank you for the quick answer.
