### ISSUE TITLE
Haskell Tool Stack for Windows7 32bit installer ??

### ISSUE THREAD

**Issue by garymdurante** [commercialhaskell/stack#5384]
Where to download the the old installer ?
All I see is for Windows 10 64 bit.

I'll be using it to learn Haskell & solve exercises.
Please share, thanks

**Comment by mpilgrem** [comment]
`stack` version 2.1.3 had a 32 bit version, see: https://github.com/commercialhaskell/stack/releases/tag/v2.1.3.

**Comment by snoyberg** [comment]
Thanks for answering @mpilgrem, closing.
