### ISSUE TITLE
How to get the dependencies (and their licenses)?

### ISSUE THREAD

**Issue by pjljvandelaar** [commercialhaskell/stack#5396]
With the latest version of stack: `stack list-dependencies --license` doesn't work any more.
I can't find in the documentation 
(note: broken link on https://github.com/commercialhaskell/stack of http://haskellstack.org/)
what happened to this command and/or how to do it with the current version of stack.
I found a discussion of introducing a show command, but that has finished yet.

Thanks in advance for your answer!

Pierre

**Comment by mpilgrem** [comment]
I can't reproduce this with `stack --version` `Version 2.4.0, Git revision 5e89c2cda8b050e3014085a664c75e37181a00cb (8235 commits) PRE-RELEASE x86_64 hpack-0.33.0` on Windows 10. `stack ls dependencies --license` behaves as expected for me.

**Comment by pjljvandelaar** [comment]
With `stack ls dependencies --license` it indeed works fine!
But I was unable to find that `stack list-dependencies --license` was changed to `stack ls dependencies --license`.
So the problem is more documentation related than missing/wrong functionality!

**Comment by mpilgrem** [comment]
This link to the documentation may help: https://docs.haskellstack.org/en/stable/GUIDE/#listing-dependencies.
