### ISSUE TITLE
SSL failures with https://get.haskellstack.org

### ISSUE THREAD

**Issue by blaiseli** [commercialhaskell/stack#5400]
Hello, I tried from two different servers, and in both cases, I can't get haskell stack following the instructions:

```
$ curl -sSL https://get.haskellstack.org 
curl: (35) Unknown SSL protocol error in connection to get.haskellstack.org:443
```

If I enter https://get.haskellstack.org/ in the URL bar of my browser (Firefox), I get the following error:

> Secure Connection Failed
> 
> An error occurred during a connection to get.haskellstack.org. PR_END_OF_FILE_ERROR
> 
>     The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
>     Please contact the website owners to inform them of this problem.

Maybe this is just temporary?

**Comment by mukilan** [comment]
Facing the same issue with stackage.org

```
$ curl -sSL https://www.stackage.org     
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to www.stackage.org:443 
```

**Comment by saurabhnanda** [comment]
Same issue.

**Comment by saurabhnanda** [comment]
Received on private Twitter DM from @snoyberg - 

> We're dealing with a server outage, I did emergency work for Casa, but this one will take another hour or two

**Comment by saurabhnanda** [comment]
I guess casa.fpcomplete.com is down now

![Screen Shot 2020-09-22 at 10 10 05 AM](https://user-images.githubusercontent.com/28369/93844731-d45a6800-fcbb-11ea-88ee-8057dc09aa2e.png)

**Comment by snoyberg** [comment]
Works for me, isup.me works for me too.
