### ISSUE TITLE
non gnu tar fails

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [commercialhaskell/stack#5416]
tries using "tar --version` but `--version is not supported with the system tar

### Steps to reproduce

- Create a new stack project
- Include any remote git repo in the extra-deps in the stack.yaml file
- Run stack build

### Actual

What actually happened.

If you suspect that a stack command misbehaved, please include the output of that command in `--verbose` mode.
If the output is larger than a page please paste the output in a [Gist](https://gist.github.com/).

```
$ stack build --verbose
Raw command: /bin/tar --version
Run from /tmp/with-repo12555/cloned
Standard error:

tar: unknown option -- -
```

### Stack version
stack versions 2.5.1 2.61

### Method of installation

git cloned and installed with stack install

### OS

openbsd

### tar

man.openbsd.org/tar

This tar does not reconize --version like gtar does. non gnu tars should also work

**Comment by mpilgrem** [comment]
@BebeSparkelSparkel, is this still a problem with current versions of Stack on OpenBSD? In the `pantry` package, `Pantry.Repo.getTarType` has:
~~~haskell
getTarType :: (HasProcessContext env, HasLogFunc env) => RIO env TarType
getTarType = do
  (_, stdoutBS, _) <- proc "tar" ["--version"] readProcess
  let bs = toStrict stdoutBS
  pure $ if "GNU" `isInfixOf` bs then Gnu else Bsd
~~~

and that code looks to me like it should distinguish `tar` on OpenBSD from GNU's `tar`.

**Comment by BebeSparkelSparkel** [comment]
This has fixed the issue. Thanks!
