### ISSUE TITLE
`stack repl subpackage` compile time cwd is different from `stack build subpackage` one

### ISSUE THREAD

**Issue by jneira** [commercialhaskell/stack#5421]
### General summary/comments (optional)

The current working dir at compile time is different between `stack build` and `stack repl`. It likely makes template haskell io computations relying in cwd fail, cause the relative file or directory usually does not exist.
This in turn makes that code not usable in a ide (hls, ghcide) that uses `hie-bios` to manage ghc session, as `hie-bios` uses `stack repl` underneath for stack projects.
(original issue https://github.com/haskell/haskell-language-server/issues/481) 

### Steps to reproduce

1. Create a simple stack project with a main package with an exe and a subpackage with a lib
2. Create in the subpackage lib a module with

```haskell
import System.Directory
import Language.Haskell.TH
import Language.Haskell.TH.Syntax

cwd :: FilePath
cwd = $$(runIO getCurrentDirectory >>= \d-> fmap TExp (lift (d :: FilePath)))
```

and in the main package an executable with

```haskell
main = print cwd
```

3. Run command `stack run` and observe cwd is `/path/to/main/package/subpackage`
4. Run command `stack repl subpackage` or `stack repl` and observe cwd evaluation gives us `/path/to/main/package`

### Expected

Both paths should be equal.

### Actual

`stack build` uses the subpackage path and `stack repl` the main package one

### Stack version

```
$ stack --version
Version 2.5.1  x86_64 hpack-0.33.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by qrilka** [comment]
@jneira I see that the situations `stack repl subpackage` and `stack repl` are a bit different. While checkout out what does `cabal-install` do in that situation I see the following:

```
$ cabal v2-repl package subpackage
cabal: Cannot open a repl for multiple components at once. The targets
'package' and 'subpackage' refer to different components..

The reason for this limitation is that current versions of ghci do not support
loading multiple components as source. Load just one component and when you
make changes to a dependent component then quit and reload.
```

I didn't investigate it further (yet) but probably Stack needs to take this problem into account.

As for the `stack repl subpackage` - it looks like `cabal-install` just does `chdir` when building (or running repl for) a package. This detail is easy to fix when it will be decided what to do about multi-package repl

**Comment by qrilka** [comment]
@jneira it looks like in `Cabal` this error was added as a part of  https://github.com/haskell/cabal/pull/4179 but it doesn't list any links to GHC tickets describing concrete problems. As I understand it working directory could be one of such problems as we can't have different working directories for different packages in GHCi. And still loading multiple packages makes sense in some situations but I don't have any examples myself. Maybe @mgsloan could share some ideas about that.
At the moment the plan is to
  * add a warning about the problem when loading multiple packages
  * set cwd properly when loading repl for a subpackage
Will this be an appropriate solution for HLS?

**Comment by jneira** [comment]
Many thanks for take care of that and share your investigation.

> set cwd properly when loading repl for a subpackage
>  Will this be an appropriate solution for HLS?

I think so.

**Comment by qrilka** [comment]
@jneira it would be great if you could check out #5448 which should fix this

**Comment by phadej** [comment]
https://hackage.haskell.org/package/file-embed-0.0.13.0/docs/Data-FileEmbed.html#v:makeRelativeToProject

**Comment by qrilka** [comment]
While #5488 will improve the situation here a bit the proper resolution is blocked by upstream as in #3310
