### ISSUE TITLE
Stack init runs for hours when building git-annex

### ISSUE THREAD

**Issue by AKurilin** [commercialhaskell/stack#543]
Repro:
* stack 0.1.2
* download repo from https://github.com/joeyh/git-annex
* run `stack init`
* on an ubuntu 14.04 instance, I had it run for over 90 minutes without any conclusion, stuck on this line:

```
2015-07-08 01:13:10.749746: [info] Checking against build plan lts-2.3 @(stack-0.1.2.0:Stack.BuildPlan src/Stack/BuildPlan.hs:584:9)
```
and on a separate machine, without verbose mode on:

```
[git-annex (master)]$ stack init
Writing default config file to: /home/alex/code/vendor/git-annex/stack.yaml
Basing on cabal files:
- /home/alex/code/vendor/git-annex/git-annex.cabal

Downloaded lts-2.17 build plan.
Caching build plan
Fetched package index.
Populated index cache.
Checking against build plan lts-2.17
```

**Comment by snoyberg** [comment]
It would seem that git-annex has 24 different flag options, which are all being tested by stack. 2^24==16777216, which obviously takes a long time to test.

I think I'll just hard-code some upper limit like 100 flag combinations to test before giving up.

**Comment by snoyberg** [comment]
Alright, upper limit of 128 pushed, which should solve things.

**Comment by AKurilin** [comment]
Thank you!
