### ISSUE TITLE
Stack fails to install because of missing `DataKinds` (on OpendBSD)

### ISSUE THREAD

**Issue by eyeinsky** [commercialhaskell/stack#5438]
### General summary/comments (optional)

When installing latest stack via cabal-install on OpenBSD I get these errors. (After fixing them stack compiles.)

### Expected

Successful compilation.

### Actual

The errors:
```
[ 54 of 109] Compiling Stack.Storage.User ( src/Stack/Storage/User.hs, dist/build/Stack/Storage/User.o )

src/Stack/Storage/User.hs:53:1: error:
    Generating Persistent entities now requires the DataKinds language extension. Please enable it by copy/pasting this line to the top of your file:

{-# LANGUAGE DataKinds #-}
   |
53 | share [ mkPersist sqlSettings
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build stack-2.5.1. See the build log above for details.
```

And:
```
[ 55 of 109] Compiling Stack.Storage.Project ( src/Stack/Storage/Project.hs, dist/build/Stack/Storage/Project.o )

src/Stack/Storage/Project.hs:40:1: error:
    Generating Persistent entities now requires the DataKinds language extension. Please enable it by copy/pasting this line to the top of your file:

{-# LANGUAGE DataKinds #-}
   |
40 | share [ mkPersist sqlSettings
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
cabal: Failed to build stack-2.5.1. See the build log above for details.
```

### Steps to reproduce

From a fresh OpenBSD install:
```
doas pkg_add ghc cabal-install # get ghc version 8.6.4 and cabal-install version 2.4.0.0
cabal new-update
mkdir -p /home/markus/.cabal/store/ghc-8.6.4/package.db # not sure why this is not there
cabal new-install cabal-install # get cabal version 3.2.0.0
cabal install stack
```

During this I get the aforementioned errors.

### Stack version

The errors are while installing stack rather than using it.

Versions:
- cabal-install 3.2.0.0
- ghc 8.6.4
- OpenBSD 6.8

### Method of installation

`cabal install stack`

**Comment by znmeb** [comment]
Also happens on Ubuntu 18.04 LTS with Stack 2.5.1

**Comment by chenrui333** [comment]
happens with cabal 3.2.0.0 and ghc 8.10.1

**Comment by eyeinsky** [comment]
Funny, but this does not happen to me anymore. I used to needed to add `{-# LANGUAGE DataKinds #-}` 
to `src/Stack/Storage/User.hs` and `src/Stack/Storage/Project.hs`, but now `cabal install stack` just works (and both with cabal-install versions 2.4.0.0 and 3.2.0.0!). What changed?

**Comment by mpilgrem** [comment]
I am closing this because Stack's current `Stack.Storage.User` and `Stack.Storage.Project` specify `DataKinds`.
