### ISSUE TITLE
Stack new myproj produces warning with stack ghci

### ISSUE THREAD

**Issue by AlistairB** [commercialhaskell/stack#5439]
### General summary/comments

`stack new myproj` produces a scary looking warning when you `stack ghci` in it. This made the user concerned and confused (they asked a question about it in the fp slack). I don't understand why this is happening, perhaps there are good reasons for it. Nonetheless, I think ideally the default stack template should not produce any warnings like this.

### Steps to reproduce

1. `stack new myproj`
2. `cd myproj`
3. `stack ghci`

### Expected

No warnings to appear in the log output

### Actual

A warning around `Paths_myproj` appears.

```
Warning: Multiple files use the same module name:
         * Paths_myproj found at the following paths
           * /home/user/temp/myproj/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build/autogen/Paths_myproj.hs (myproj:lib)
           * /home/user/temp/myproj/.stack-work/dist/x86_64-linux/Cabal-3.0.1.0/build/myproj-exe/autogen/Paths_myproj.hs (myproj:exe:myproj-exe)
```

### Stack version

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

### Method of installation

`curl -sSL https://get.haskellstack.org/ | sh` (and `stack upgrade` a couple of times). I am on Ubuntu 18.04.

**Comment by CarstenKoenig** [comment]
Just FYI - seems this issue is with *hpack* and there is already an [issue/solution mentioned on it's github page](https://github.com/sol/hpack/issues/303)

Add

    when:
    - condition: false
      other-modules: Paths_pkg

for the test/executable sections where `pkg` is the name of your package - the one that causes the warning.

After *hpack* will no longer auto-include the generated file into the `other-modules` section

**Comment by AlistairB** [comment]
Ah interesting. So I suppose a possible quick fix is to include this workaround in `new-template`.
