### ISSUE TITLE
stack build and yedod/templates

### ISSUE THREAD

**Issue by angerman** [commercialhaskell/stack#544]
I just found out that when changing a template, `touch path/to/File.hs` is needed prior to calling stack build again. Where `File` is the module using the template.

This is, I assume, a more tricky situation, as it would require figuring out which module uses the template. 

Alternatively, does `stack build` provide a forced rebuild option I did not see?

**Comment by snoyberg** [comment]
This is a known deficiency right now. @DanBurton is currently working on overcoming it in #105. There's not currently a forced rebuild option, touching a random file is the right temporary workaround.
