### ISSUE TITLE
`ls dependencies --license` (fine) != ` ls dependencies --license json` (empty)

### ISSUE THREAD

**Issue by teto** [commercialhaskell/stack#5446]
### Stack version
If I run 
```
$ stack -v --stack-yaml /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/external/hackage-unpinned/stack.yaml ls dependencies --license
Cabal BSD-3
Glob BSD3
HTTP BSD3
...
```
all is well, now if I add `json` then it falls apart I get no output
```
$ stack -v --stack-yaml /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/external/hackage-unpinned/stack.yaml ls dependencies --license json
$
```

stack ls   dependencies --help lists --license as an option so I understand it as just a modifier, but it behaves like a command. I would like ` ls dependencies --license json` to output the same as `ls dependencies --license` but in json format. Even stranger, 
`ls dependencies --license text` returns nothing too (consistant if --license is a command and not a modifier but then stack should reflect that)

```
$ stack --version 
2.5.1 x86_64 hpack-0.34.2
```

### Method of installation

* via nixpkgs unstable

**Comment by mpilgrem** [comment]
`stack ls dependencies --help` reports:
~~~text
Usage: stack.exe ls dependencies [COMMAND | [--separator SEP] [--[no-]license]
                                   [--filter ITEM] [--[no-]external]
                                   [--[no-]include-base] [--depth DEPTH]
                                   [--prune PACKAGES] [TARGET]
                                   [--flag PACKAGE:[-]FLAG] [--test] [--bench]
                                   [--global-hints]]
~~~

That is, Stack is expecting either a command (such as `json`) or the alternative. You are specifying the alternative, with
~~~text
`stack ls dependencies --licence json`
~~~

As there is no `TARGET` `json`, the command correctly reports no output.
