### ISSUE TITLE
cp -p causes rebuild?

### ISSUE THREAD

**Issue by byteflood** [commercialhaskell/stack#5450]
What happened?
I build a project managed by stack using `stack build`
I copy the directory in timestamp preservation mode to a new location (`cp -pr myprojectA myprojectB`).
I build the project in the new folder also using `stack build` 

Expected behaviour:
The compilation of the project in the new location should not be much work since the cache got copied with it

Actual behaviour:
Everything local to the project gets build again.

What did I try:
I have replaced all global file paths of myprojectA in ~/.stack/stack.sqlite3 and ./stack-work/stack.sqlite3 to the new directory, but after doing so `stack build` still causes everything to be rebuild.
Is there something else I can/should try?

**Comment by mbj** [comment]
I suspect that stack may use the absolute file name as part of the cache key?

**Comment by mpilgrem** [comment]
`Stack.Storage.Project.configCacheKey` is indeed based on an absolute path to a directory. I am closing this issue as question answered.
