### ISSUE TITLE
Official support for KaOS

### ISSUE THREAD

**Issue by cosmos64** [commercialhaskell/stack#5452]
Hi there :hugs: 

I implemented KaOS support, which is an independent distro, that packages itself. 

The current situation shows some generic text: 

```
No setup information was found for ghc-8.8.4 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-ncurses6'.
Supported versions: ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2
```

Proposed integration: 

```sh
while true; do
     printf "For stack to work in KaOS is it important to install libtinfo.\nDo you like to do that?" 
     read -p " y or n: " yn
    case $yn in
        [Yy]*)  printf "\e[1;31m Do not edit the PKGBUILD\e[0m " && kcp -u && kcp -i libtinfo; break;;
        [Nn]*)  break;;
        *) printf "Please answer with y or n. ";;
    esac
done

while true; do
    echo
    printf  "To be detectable by IDEs and other applications is it recommended to symlink \e[34mstack\e[0m to the PATH.\nDo you like to do that?" 
    read -p " y or n: " yn
    case $yn in
        [Yy]*)  sudo ln -s /home/$USER/.stack/programs/x86_64-linux/ghc-tinfo6-8.8.4/bin/ghc /usr/bin; break;;
        [Nn]*)  exit;;
        *) printf "Please answer with y or n. ";;
    esac
done
```
Please respect, that I am very new at this. 
I tested the script and like to know if the symlink of ghc is sufficient.

**Comment by chreekat** [comment]
@cosmos64 , it's unusual for a project to support individual Linux distros directly in its own installer. There's just too many of them. Plus, it's usually the job of the distro itself to package up software so it's compatible with the rest of the system. In fact, that's what a distro is all about.

I would suggest bringing this up in the KaOS community!

**Comment by ShalokShalom** [comment]
Stack is in fact 'unusual'  and does precisely that

https://github.com/commercialhaskell/stack/blob/master/etc/scripts/get-stack.sh#L192

**Comment by cosmos64** [comment]
Can I have an update on this?

**Comment by mpilgrem** [comment]
I am closing this issue as attempts to find a user of Stack on KaOS failed: see https://github.com/commercialhaskell/stack/pull/5535#issuecomment-1236781892.
