### ISSUE TITLE
situation with stack repl --package and multiple packages is unclear

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#5455]
`stack repl --package`'s help suggests it can support multiple packages, but it gives an obscure error for the obvious syntaxes (comma or space-separated, as supported by [stack script --package](https://docs.haskellstack.org/en/stable/GUIDE/#using-multiple-packages)):

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
$ stack repl --help | grep '\--package'
                  [--with-ghc GHC] [--[no-]load] [--package PACKAGE(S)]
  --package PACKAGE(S)     Additional package(s) that must be installed
$ stack repl Shake.hs --package regex,shake
Error parsing targets: Directory not found: regex,shake
$ stack repl Shake.hs --package 'regex shake'
Error parsing targets: Directory not found: regex shake
```

PS I'm interested in this because specifying multiple packages without using a space seems possibly helpful in hie.yaml files.

**Comment by qrilka** [comment]
As far as I understand the way to use multiple package would be by repeating `--package <package` for every one of them, probably we should improve CLI help here.

**Comment by mpilgrem** [comment]
I am closing because the current `stack repl --help` explains:
~~~text
--package PACKAGE        Add a package (can be specified multiple times)
~~~

and that is consistent with `Stack.Config.packagesParser`.
