### ISSUE TITLE
Work around GHC bug in macOS 11

### ISSUE THREAD

**Issue by yairchu** [commercialhaskell/stack#5456]
In macOS 11 (which comes pre-installed on new Macs), stack/GHC fails building anything using OpenGL or other system frameworks ([GHC bug #18446](https://gitlab.haskell.org/ghc/ghc/-/issues/18446)).

It's already fixed in GHC HEAD, but not in any currently released version of GHC yet.

However the problem is [work-aroundable](https://www.reddit.com/r/haskell/comments/k9r2cy/workaround_for_haskell_woes_on_macos_11_big_sur/). I already work around it using a `DYLD_INSERT_LIBRARIES=` library inserted to `stack` to emulate the behavior that GHC relied on.

But the workaround can be integrated into `stack` itself and then people won't need to even know about the problem in the first place!

 If integrated into `stack`, the work-around can be more focused with `DYLD_INSERT_LIBRARIES=` done only to GHC and having a simpler implementation than my current one (which contains efforts to make sure that its hooking propagates from `stack` to the actual `ghc` being run within it)

**Comment by catap** [comment]
Since GHC 8.10.3 was released I feel that the right way is just release the next version of stack with GHC-8.10.3 :)

**Comment by yairchu** [comment]
> Since GHC 8.10.3 was released I feel that the right way is just release the next version of stack with GHC-8.10.3 :)

Indeed it would be great if a stockage snapshot with GHC 8.10.3 was released!

Yet even after it will be available, some projects (or older versions of them) are still using older versions of GHC and it would be nice to maintain the support for their reproducible build.

**Comment by neverpanic** [comment]
Ping? Is there some way we can move along shipping a version with a GHC that works on macOS 11? Telling users to inject a preload library really sounds like a massive hack I'd like to avoid.
