### ISSUE TITLE
Clarify why stack does not use a freer license

### ISSUE THREAD

**Issue by Franciman** [commercialhaskell/stack#5459]
Hi,  I noticed that stack is a binary that uses the BSD3 license, why did you choose this license? Wouldn't it be better to use some version of GPL or AGPL in order to make this piece of software have copyleft rights for the community? In this way anyone who wants to improve stack, must give back the code to the whole community. Also, since stack is an executable, a stronger GPL license would not have any consequence on the software built using it.

**Comment by mihaimaruseac** [comment]
BSD3 is freerer, afaik. Also, there are people who currently contribute but won't be able to if the license switched to *GPL as the corp they work at forbids contributions to projects having the cancerous licenses.

**Comment by Franciman** [comment]
Yes, sorry, I meant free in the FSF sense, I wanted to say a license that grants copyleft rights to the users of stack, also for a binary executable the "cancerous" behavior would mean more guarantees for the community, IMHO

**Comment by mihaimaruseac** [comment]
Let's take my case: if license switched to *GPL then I won't be able to contribute. Google does not allow contributing to OSS projects under *GPL. There are many companies that do this.

**Comment by Franciman** [comment]
This is really sad, but I understand, what's cancerous here is not the GPL license, but the attitude and the greed of many companies, but ok, this is another topic. Thanks for clarifying, I'll close here.

**Comment by Calinou** [comment]
> Let's take my case: if license switched to *GPL then I won't be able to contribute. Google does not allow contributing to OSS projects under *GPL. There are many companies that do this.

As far as I know, Google only forbids contributing to AGPL-licensed projects, not GPL- or LGPL-licensed projects.

https://opensource.google/docs/using/agpl-policy/
https://opensource.google/docs/patching/#forbidden
