### ISSUE TITLE
stack --resolver resolver doesn't work

### ISSUE THREAD

**Issue by jsynacek** [commercialhaskell/stack#5462]
### General summary/comments (optional)
Running `stack --resolver <resolver>` prints usage and exits with the return code of 1.

### Steps to reproduce
1. `$ stack --resolver nightly-2020-12-14`

### Expected

The resolver is set correctly.

### Actual

Usage is printed and the program exists with the return code of 1.

### Stack version

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

### Method of installation

Installed from Nix and upgraded.

**Comment by qrilka** [comment]
@jsynacek could you explain what do you mean by "resolver set correctly"? `--resolver` argument is applicable for some of Stack's command but here you don't give any and the error message complains exactly about that - `Missing: COMMAND|FILE`

**Comment by jsynacek** [comment]
Right, maybe I have misunderstood how it should work. The instructions on the stackage web page (https://www.stackage.org/nightly-2020-12-14, for example) say:
```
To use this resolver, edit your stack.yaml and set the following:

resolver: nightly-2020-12-14

or on the command line use: stack --resolver nightly-2020-12-14
```
I was under the impression that when I run the command like that it will set the resolver of the current project in `stack.yaml`.

**Comment by qrilka** [comment]
@jsynacek Stack doesn't modify `stack.yaml` by itself and relies on it as an input but the flag `--resolver` allows you to override a resolver for a command invocation in cases when it's necessary.
If this clears up the situation would you mind closing the ticket as there are no further actions?

**Comment by jsynacek** [comment]
I guess the information on the stackage web page should be adjusted.

Thanks for the explanation.
