### ISSUE TITLE
For snapshot packages, don't use name as build target if package id doesn't exist

### ISSUE THREAD

**Issue by jforberg** [commercialhaskell/stack#5467]
### General summary/comments

"stack install" seems to ignore any version constraints (given on the command line) that it cannot satisfy.

### Steps to reproduce

```
stack install pager    # stack installs the latest version of pager
stack install pager-0.1.0.0    # stack installs version 0.1.0.0 of pager
stack install pager-1.2.3.4    # stack installs **the latest version of pager**
```

(pager being an arbitrary example)

### Expected

Stack should give an error if for any reason it cannot install the requested version.

### Actual

Stack will silently ignore the version constraint and install a different version.

### Stack version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by jforberg** [comment]
In my view it is poor UX when the interpretation of a command depends on context that is invisble or obscure to the user. In this case: whether "pager" happens to be part of the current index or not.

I feel that the command `stack install pager-1.2.3` has only one reasonable interpretation: "please install version 1.2.3 of pager". I have not encountered any build tool or package manager which assigns another meaning to such a command. In my view the tool is afforded only two reasonable behaviours: install the particular version or error out.

That said, I don't use stack anymore so if I'm the only one who was bothered by this in the past three years, please feel free to close this.

**Comment by mpilgrem** [comment]
@jforberg, I agree with you. I'll relabel this as a feature request, and see if I can implement it.

**Comment by mpilgrem** [comment]
@jforberg, this is implemented as a pull request. If you do not use GHCup to manage versions of Stack, you can test with `stack upgrade --source-only --git --git-branch fix5467`.

As an example (in black and white; Stack reports using colour):

For a package name in the snapshot:

~~~text
❯ stack build ansi-terminal-9.9

Error: [S-8506]
       Stack failed to parse the target(s).

       While parsing, Stack encountered the error:

           Stack knows the location of ansi-terminal-1.0.2 but did not know the location of
           ansi-terminal-9.9, and did not find it in the package index.
~~~

For a package name not in the snapshot:
~~~text
❯ stack build acme-missiles-9.9

Error: [S-8506]
       Stack failed to parse the target(s).

       While parsing, Stack encountered the error:

           Stack did not know the location of a package named acme-missiles and could not find
           acme-missiles-9.9 in the package index.
~~~

**Comment by jforberg** [comment]
@mpilgrem That looks exactly right. Thanks for spending time on this!

**Comment by simonmichael** [comment]
That's great, love this change. It's intuitive that if I wrote the version, I'm specifying a constraint on that version; if I didn't, I wouldn't write the version.
