### ISSUE TITLE
Configuring GHC Failed

### ISSUE THREAD

**Issue by zoujieJason** [commercialhaskell/stack#5470]
jay@JacBook-Pro examples % stack install alex happy
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Already downloaded.
configure: error: in /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5': configure: error: C compiler cannot create executables See config.log' for more details
Received ExitFailure 77 when running
Raw command: /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5/configure --prefix=/Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5/
Run from: /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5/

Error: Error encountered while configuring GHC with
/Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5/configure --prefix=/Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5/
run in /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/ghc-8.6.5/

   The following directories may now contain files, but won't be used by stack:
     - /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5.temp/
     - /Users/jay/.stack/programs/x86_64-osx/ghc-8.6.5/
   
   For more information consider rerunning with --verbose flag
Configuring GHC ...

**Comment by zoujieJason** [comment]
I do not know how to fix this problem. (Mac OS 10.15).
I try to `stack clean` and reinstall it, but it still did not work.

**Comment by mpilgrem** [comment]
@zoujieJason, is this still an issue in practice for you, with current versions of Stack? I am looking to close stale issues.
