### ISSUE TITLE
Binary package download extremely slow

### ISSUE THREAD

**Issue by kim** [commercialhaskell/stack#5471]
I am trying to get at a recent version of stack for Arch Linux, but find that the distro packages are broken. Trying to download a binary package via GitHub releases proceeds at a blazing 1K/sec, before timing out entirely. This is quite surprising, as the artifact seems to be served via S3. 

I assume it is ultimately the same issue as reported in #2240, yet since I am also unable to bootstrap `stack` using `cabal-install`, I'm stuck here.

**Comment by mpilgrem** [comment]
I am closing this issue given the passage of time and no other users reporting the same issue recently.
