### ISSUE TITLE
Using uncommited changes from an extra dependency

### ISSUE THREAD

**Issue by yaitskov** [commercialhaskell/stack#5474]
Hi,

It would be nice to have following config supported, because it releases me from make commits just for sake of changes propagation to the app during try/fail integration cycle/experimenting. 
 
```
extra-deps:
- git: ../persistent/
  commit: uncommited
```

**Comment by qrilka** [comment]
What about using it as a package, i.e. use its local path? E.g. uncommitted version is not exactly in git.
Also according to the current architecture of Stack/Pantry git packages are immutable and your idea goes against that.
