### ISSUE TITLE
`stack repl` no longer picks up magic `stack script` comment

### ISSUE THREAD

**Issue by buggymcbugfix** [commercialhaskell/stack#5476]
Tested with: Version 2.5.1, Version 2.4.0

I have `-- stack script --resolver lts-13.18 --package shake` at the top of a script `Build.hs`, however `stack repl Build.hs` doesn't pick this up and instead uses the global `stack.yaml`.

This also causes lsp integration to break: https://github.com/haskell/haskell-language-server/issues/111

**Comment by qrilka** [comment]
Was it ever possible to do that?

**Comment by buggymcbugfix** [comment]
I recall that this used to work and this comment suggests the same: https://github.com/haskell/haskell-language-server/issues/111#issuecomment-752136211

Perhaps time for a git bisect? I'd help fix this with some guidance.

**Comment by qrilka** [comment]
I'm just wondering how it could even work as `stack script` uses shell to sell all the details...
If you want to look into it @buggymcbugfix - sure go ahead, I could help you with some details I know about.

**Comment by mpilgrem** [comment]
I am closing because `stack <haskell_source_file>` and `stack repl` (or `stack ghci`) are distinct commands. The former makes use of the [script interpreter](https://docs.haskellstack.org/en/stable/scripts/). The latter runs GHCi loaded up with project packages or their components.
