### ISSUE TITLE
`stack exec` causes app to fail while by itself it works fine

### ISSUE THREAD

**Issue by nihlete** [commercialhaskell/stack#5477]
### General summary/comments (optional)

Execution of same exe file inside and outside of `stack exec` environment give different results.
I face this problem on Windows 10, there are no problems on Manjaro linux.

### Steps to reproduce

1. Clone https://github.com/nihlete/stack-exec-mwe
2. Install deps
    - `stack exec -- pacman -Suy`
    - `stack exec -- pacman -S mingw64/mingw-w64-x86_64-cairo`
    - `stack exec -- pacman -S mingw64/mingw-w64-x86_64-pkgconf`
3. `stack build`
4. `stack exec -- stack-exec-mwe-exe`
5. Call directly builded exe `d:\workspace\stack-exec-mwe\.stack-work\install\aa98d2a4\bin\stack-exec-mwe-exe.exe`

### Expected

The program works in both environment

### Actual
Minimal application with example from https://github.com/timbod7/haskell-chart/wiki/example-1
and some output to stdout

```
main = do
  print "IDDQD"
  toFile def "example1_big.png" $ do
    layout_title .= "Amplitude Modulation"
    setColors [opaque blue, opaque red]
    plot (line "am" [signal [0, (0.5) .. 400]])
    plot (points "am points" (signal [0, 7 .. 400]))
```

`stack exec` executes the application and immediately closes it,
similar as c++ `int main(){return 0;}`.
There are no side effects on stdout or filesystem.
Same exe outsde `stack exec` do its job including correct output to filesystem.

```
PS D:\workspace\stack-exec-mwe> stack build
stack-exec-mwe-0.1.0.0: unregistering (local file changes: ChangeLog.md README.md app\Main.hs package.yaml src\Lib.hs stack-exec-mwe.cabal)
Building all executables for `stack-exec-mwe' once. After a successful build of all of them, only specified executables will be rebuilt.
stack-exec-mwe> configure (lib + exe)
Configuring stack-exec-mwe-0.1.0.0...
stack-exec-mwe> build (lib + exe)
Preprocessing library for stack-exec-mwe-0.1.0.0..
Building library for stack-exec-mwe-0.1.0.0..
[1 of 2] Compiling Lib
[2 of 2] Compiling Paths_stack_exec_mwe
Preprocessing executable 'stack-exec-mwe-exe' for stack-exec-mwe-0.1.0.0..
Building executable 'stack-exec-mwe-exe' for stack-exec-mwe-0.1.0.0..
[1 of 2] Compiling Main
[2 of 2] Compiling Paths_stack_exec_mwe
Linking .stack-work\dist\29cc6475\build\stack-exec-mwe-exe\stack-exec-mwe-exe.exe ...
stack-exec-mwe> copy/register
Installing library in D:\workspace\stack-exec-mwe\.stack-work\install\aa98d2a4\lib\x86_64-windows-ghc-8.8.4\stack-exec-mwe-0.1.0.0-32d3Xq2aLkyKQJSX5Ej4KG
Installing executable stack-exec-mwe-exe in D:\workspace\stack-exec-mwe\.stack-work\install\aa98d2a4\bin
Registering library for stack-exec-mwe-0.1.0.0..
PS D:\workspace\stack-exec-mwe> stack exec -- stack-exec-mwe-exe
PS D:\workspace\stack-exec-mwe> d:\workspace\stack-exec-mwe\.stack-work\install\aa98d2a4\bin\stack-exec-mwe-exe.exe
"IDDQD"
PS D:\workspace\stack-exec-mwe> 
```

Output with `--verbose` option
https://gist.github.com/nihlete/b9f887dbfdb6654c0f66557da8039a65

#### Note
Without call `toFile` function all works as expected in both environments
```
main = do
  print "IDDQD"
--   toFile def "example1_big.png" $ do
--     layout_title .= "Amplitude Modulation"
--     setColors [opaque blue, opaque red]
--     plot (line "am" [signal [0, (0.5) .. 400]])
--     plot (points "am points" (signal [0, 7 .. 400]))
```

### Stack version

```
PS D:\workspace\stack-exec-mwe> stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mattaudesse** [comment]
@nihlete if I've understood correctly this looks like a matter of running the binary inside `stack exec` not resolving shared library paths on your system when combined with WSL(2?) + Arch's package management overlayed on top.

If you were to run:

```
stack exec -- ldd $(stack exec -- which stack-exec-mwe-exe)
```

I suspect you'd see missing hits for the `cairo` and `pkgconf` dependencies you mention above. Am I right about that?

I'm not a Windows/WSL/Arch user and a little unsure whether this should be considered the expected behavior or not (leaning toward _not_ since this sounds more like a WSL quirk than a `stack` issue, but could be convinced otherwise), but I think a good starting place would be to look for differences between `stack exec`'s concept of `env` (i.e. `stack exec -- env`) and the equivalent for your Windows host user's session. If I'm on the right track there may be a relatively simple configuration change you could make that allows you to get the behavior you're looking for.

Did you do anything special when setting up `pacman` to help running binaries directly from PowerShell work? I'm not really familiar with how people normally situate their WSL environments.

Perhaps this is also relevant: https://docs.haskellstack.org/en/stable/faq/#how-to-get-a-working-executable-on-windows

**Comment by nihlete** [comment]
@mattaudesse, thank you for your reply.
I don't use WSL environment. Just bare bone win msi installer. It brings its own version of msys2 (with integrated `pacman`).
There is only one msys2 distributive.

Also, I should mention, that there are no messages in windows `Event Viewer`.

Seems that all dll have resolved
```
PS D:\workspace\stack-exec-mwe> stack exec -- ldd $(stack exec -- which stack-exec-mwe-exe)
        ntdll.dll => /c/WINDOWS/SYSTEM32/ntdll.dll (0x7fff3e270000)
        KERNEL32.DLL => /c/WINDOWS/System32/KERNEL32.DLL (0x7fff3c350000)    
        KERNELBASE.dll => /c/WINDOWS/System32/KERNELBASE.dll (0x7fff3bc80000)
        msvcrt.dll => /c/WINDOWS/System32/msvcrt.dll (0x7fff3dec0000)        
        dbghelp.dll => /c/WINDOWS/SYSTEM32/dbghelp.dll (0x7fff397a0000)      
        PSAPI.DLL => /c/WINDOWS/System32/PSAPI.DLL (0x7fff3db10000)
        ucrtbase.dll => /c/WINDOWS/System32/ucrtbase.dll (0x7fff3c1d0000)    
        SHELL32.dll => /c/WINDOWS/System32/SHELL32.dll (0x7fff3c880000)      
        msvcp_win.dll => /c/WINDOWS/System32/msvcp_win.dll (0x7fff3c130000)  
        USER32.dll => /c/WINDOWS/System32/USER32.dll (0x7fff3d810000)        
        win32u.dll => /c/WINDOWS/System32/win32u.dll (0x7fff3b9b0000)        
        GDI32.dll => /c/WINDOWS/System32/GDI32.dll (0x7fff3d650000)
        gdi32full.dll => /c/WINDOWS/System32/gdi32full.dll (0x7fff3b9e0000)
        WSOCK32.dll => /c/WINDOWS/SYSTEM32/WSOCK32.dll (0x7ffef5100000)
        WS2_32.dll => /c/WINDOWS/System32/WS2_32.dll (0x7fff3d680000)
        RPCRT4.dll => /c/WINDOWS/System32/RPCRT4.dll (0x7fff3db20000)
        libcairo-2.dll => /mingw64/bin/libcairo-2.dll (0x7ffee42e0000)
        dbgcore.DLL => /c/WINDOWS/SYSTEM32/dbgcore.DLL (0x7fff2db40000)
        MSIMG32.dll => /c/WINDOWS/SYSTEM32/MSIMG32.dll (0x7fff34120000)
        libgcc_s_seh-1.dll => /c/Users/vandrei/AppData/Local/Programs/stack/x86_64-windows/ghc-8.8.4/mingw/bin/libgcc_s_seh-1.dll (0x61440000)
        libfreetype-6.dll => /mingw64/bin/libfreetype-6.dll (0x7ffeee650000)
        libfontconfig-1.dll => /mingw64/bin/libfontconfig-1.dll (0x7fff12c00000)
        zlib1.dll => /c/Users/vandrei/AppData/Local/Programs/stack/x86_64-windows/ghc-8.8.4/mingw/bin/zlib1.dll (0x62e80000)
        libpng16-16.dll => /mingw64/bin/libpng16-16.dll (0x68b40000)
        libpixman-1-0.dll => /mingw64/bin/libpixman-1-0.dll (0x7ffee4230000)
        libwinpthread-1.dll => /c/Users/vandrei/AppData/Local/Programs/stack/x86_64-windows/ghc-8.8.4/mingw/bin/libwinpthread-1.dll (0x64940000)
        libbrotlidec.dll => /mingw64/bin/libbrotlidec.dll (0x7fff256f0000)
        libbz2-1.dll => /mingw64/bin/libbz2-1.dll (0x7fff24e80000)
        libharfbuzz-0.dll => /mingw64/bin/libharfbuzz-0.dll (0x7ffee4130000)
        libexpat-1.dll => /mingw64/bin/libexpat-1.dll (0x7ffee40f0000)
PS D:\workspace\stack-exec-mwe>
```

**Comment by mattaudesse** [comment]
> @mattaudesse, thank you for your reply.
> I don't use WSL environment. Just bare bone win msi installer. It brings its own version of msys2 (with integrated `pacman`).
> There is only one msys2 distributive.

Hmm, I guess this is too far outside my experience to speculate then 🤔

I'll relabel and allow someone more familiar to weigh in - thanks for reporting and good luck in the meantime.

**Comment by nihlete** [comment]
I have reinstalled my windows, and now it seems like I have similar issues inside and outside `stack exec` environment. Seems overall it's my old setup inconsistency, and chart-cairo specific on windows.
