### ISSUE TITLE
how to find snapshot hash for lts resolver?

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/stack#5478]
Hi. When building in CI, I want to get the location of build output, in particular, docs. 

This  https://gitlab.imn.htwk-leipzig.de/autotool/all0/-/blob/master/.gitlab-ci.yml#L103 used to work, but it stopped. 

If I use `lts-foo` as resolver, then the output directory now will be some hash that I don't know how to compute. (It's not a function of the resolver name alone, as I am getting different hashes on different machines.)

`stack ls snapshots -l` sounds promising but it does only show old lts resolvers (or, resolvers installed with older `stack`?) not `lts-16.31`.

### Stack version, Method of installation

from docker image
```
image: "fpco/stack-build:${RES}"
```
but the behaviour is the same with `stack-2.5.1` built via `cabal install`

example CI build log: https://gitlab.imn.htwk-leipzig.de/autotool/all0/-/jobs/69205

**Comment by qrilka** [comment]
Isn't `stack path --local-doc-root` what you need @jwaldmann ?

**Comment by jwaldmann** [comment]
Yes it is! Thanks.
