### ISSUE TITLE
stack does not accept global option --local-bin

### ISSUE THREAD

**Issue by Ionic** [commercialhaskell/stack#5484]
According to the source code and ChangeLog, the `--local-bin-path` global option was deprecated for the `--local-bin` global option a while ago.

[`src/Stack/Path.hs`](https://github.com/commercialhaskell/stack/blob/30224e347624f34c9ebbbb444c07339cd123eb4d/src/Stack/Path.hs#L170-L214) mentions that `local-bin-path` is deprecated and also includes `local-bin` instead.

[`ChangeLog.md`](https://github.com/commercialhaskell/stack/blame/30224e347624f34c9ebbbb444c07339cd123eb4d/ChangeLog.md#L1827) mentions that `--local-bin-path` has been deprecated in favor of `--local-bin`.

[`src/Stack/Options/BuildMonoidParser.hs`](https://github.com/commercialhaskell/stack/blob/46b3dc53d7c2dcaf5ecda4bd8029d7c753727bc3/src/Stack/Options/BuildMonoidParser.hs#L112-L116) has also since been updated to mention `local-bin` instead of `local-bin-path`.

However, [`src/Stack/Options/ConfigParser.hs`](https://github.com/commercialhaskell/stack/blob/30224e347624f34c9ebbbb444c07339cd123eb4d/src/Stack/Options/ConfigParser.hs#L126-L132) only implements a global config option called `--local-bin-path`.

This is confusing and counter-intuitive.

stack should probably accept a global option called `--local-bin` as well and prefer that over `--local-bin-path`. The global option should probably take an argument, as it doesn't make sense to be used without an argument.

This is not a duplicate of #5195. The latter bug report is concerned with **setting** `local-bin` when calling `stack path`, which is a completely different mechanism (I think) and does not map to global options. It's a valid report, I guess, but as far as I can tell, orthogonal to this one.

**Comment by mpilgrem** [comment]
The ChangeLog entry for Stack 1.1.0 was referring to `stack path --local-bin-path` (now `--local-bin`). The global option `--local-bin-path` sets the `local-bin` path, and does take an argument.
