### ISSUE TITLE
stack install/build --copy-bins ignores --ghc-options

### ISSUE THREAD

**Issue by Ionic** [commercialhaskell/stack#5485]
I'm bootstrapping/building stack 2.5.1 on OS X 10.9, which by now is pretty old.

Some packages that are being used by stack use newer features/libc functions such as `utimensat`.

In order to get a working build, I need to specify custom options to the compiler, e.g., `-optc-I... -optl...`.

This works for the build process, i.e., `stack build [other options] --ghc-options="-optc-I... -optl..."`, but seems to be completely ignored for `stack install`/`stack build --copy-bins`.

For some reason, the `stack install` call seems to rebuild a lot of packages, but without the specified GHC options. I can live with the rebuilds, but not with GHC options being ignored.

Searching for a workaround, I tried different alternatives.

For instance, I created a global stack configuration file in `~/.stack/config.yaml` (which is okay, since $HOME is set to a temporary directory for the build) with this content:

```yaml
apply-ghc-options: everything
ghc-options:
    "$everything": -optc-I... -optl...
```

This, likewise, seems to be working fine for the `stack build` command, but seems to be completely ignored by `stack install`/`stack build --copy-bins`.

Unfortunately, I don't understand the code too well. Especially, I still haven't figured out when GHC options are applied and when they aren't. As far as I could see, the only thing that would influence that is the `apply-ghc-options` setting, but that obviously doesn't seem to be true.

**Comment by mpilgrem** [comment]
Given the nature of the issue, the passage of time, and the absence of people reporting similar issues, I am going to close this issue.
