### ISSUE TITLE
Document release signing key somewhere

### ISSUE THREAD

**Issue by thsutton** [commercialhaskell/stack#549]
I couldn't find the id and fingerprint of the key you use to sign your releases of stack anywhere.

There also appear to be other keys for distro packages, etc. It would be nice if you had a single page on your site, protected by HTTPS, etc. which documents the keys used.

**Comment by manny-fp** [comment]
We're converging on using the same `dev@fpcomplete.com` key for all of these, and you can get it here: https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key

@chrisdone, can we make sure this key is included on the in-progress stack web site?

**Comment by chrisdone** [comment]
Right. I [put it on the wiki](https://github.com/commercialhaskell/stack/wiki/Signature-process) which I'll be combing for content when implementing that.

**Comment by manny-fp** [comment]
I've linked to that from the downloads page.  I think we can now consider this documented, so closing the issue.
