### ISSUE TITLE
stack.yaml.lock is not created when --resolver option is used.

### ISSUE THREAD

**Issue by debug-ito** [commercialhaskell/stack#5492]
I use stack 2.5.1 on Linux.

stack doesn't create stack.yaml.lock file when `--resolver` option is used.

For example, the command `stack clean` (with stack.yaml file in the working directory) creates stack.yaml.lock file. `stack --resolver lts-16.11 clean` doesn't create stack.yaml.lock file.

Is this an expected behavior?

**Comment by mpilgrem** [comment]
@debug-ito, thanks for asking. The short answer is: Yes.

When you override the resolver (`--resolver` option) the default lock file behaviour is set to 'read only'.  That happens in `Stack.Options.GlobalParser.globalOptsFromMonoid` (extract):
~~~haskell
  pure GlobalOpts
...
    , globalLockFileBehavior =
        let defLFB =
              case getFirst globalMonoidResolver of
                Nothing -> LFBReadWrite
                _ -> LFBReadOnly
        in  fromFirst defLFB globalMonoidLockFileBehavior
    }
~~~
and that is documented online here: https://docs.haskellstack.org/en/stable/global_flags/#-lock-file-option.

**Comment by debug-ito** [comment]
Thanks for explanation!
