### ISSUE TITLE
Request for feedback on ghc feature `-jsem`

### ISSUE THREAD

**Issue by duog** [commercialhaskell/stack#5499]
Hi Stack devs,

I've written a prototype for a ghc feature to limit its parallelism with a semaphore, GNU make jobserver style. The idea being that stack would pass `-j -jsem ghc` to `ghc --make` on each invocation. There is a datum showing a nice speedup on building lens from scratch (with cabal-install I'm afraid).

https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5176

I'd appreciate any comment on
* why this is a bad idea
* what the UI should look like
* any important semantics

to make this easy and useful to integrate into stack

**Comment by adamgundry** [comment]
`-jsem` has now been implemented, so I think this ticket can be closed? See #6131 for an issue tracking support for `-jsem` in Stack.

**Comment by chreekat** [comment]
Agreed.
