### ISSUE TITLE
Rustup compatibility

### ISSUE THREAD

**Issue by chadbrewbaker** [commercialhaskell/stack#5502]
What would it take to make Stack fully compatible with Rustup?  Using an upstream rust nightly and pinning to the same llvm-project would be amazing. Throw in a Clang build too.

Other than pinning to a commit of Rust's llvm-project the other hurdle would be some feature flag to expect binaries in the rustup directory instead of the stack directory structure.  Perhaps a new shell utility called "stackup" that pulled stack binaries to the existing Rustup install.

**Comment by chreekat** [comment]
Stumbled across this issue just now. I think I'm missing some larger picture, but what do Rustup and Stack have to do with each other? :)

**Comment by mpilgrem** [comment]
I understand that [`rustup`](https://www.rust-lang.org/tools/install) is a tool that installs and manages the Rust programming language. I also do not follow the relationship between the Haskell Tool Stack (which is, at its core, a build tool for Haskell projects relying on GHC and the `Cabal` library) and such a tool.

**Comment by mpilgrem** [comment]
I am clossing this issue given the passage of time.
