### ISSUE TITLE
Support API Keys in stack-upload

### ISSUE THREAD

**Issue by pbrisbin** [commercialhaskell/stack#5513]
Hackage supports API Key based authentication (see `https://hackage.haskell.org/user/{username}/manage`), specifically for uploading packages from CI. These keys can be created, named, and revoked specifically, so that you don't have to store your (only) Username/Password in CI configuration.

I'd like to see `stack-upload` support this, perhaps by another env var and/or extension to the `credentials.json` file?

Here is a simplified example request that I'm using for now:

```console
        stack sdist ...
        curl \
            --silent \
            --header "Accept: text/plain" \
            --header "Authorization: X-ApiKey $HACKAGE_API_KEY" \
            --form "package=@$archive" \
            https://hackage.haskell.org/packages/
```

In reality, I want to output the response body but still catch unsuccessful exit codes, which `curl` doesn't make easy. I also have to go look for the `sdist`-produced archive. These two points actually make it quite a bit more complicated to do from the outside vs `stack upload` doing it internally.

**Comment by kocielnik** [comment]
@pbrisbin, @hasufell - resolving this wouldn't have been possible without your help. Thanks a lot!
