### ISSUE TITLE
Fails to install ghc-9.2.1-alpha1

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack#5514]
### General summary/comments

When using `stack setup` with a custom stack.yaml to install ghc 9.2.1-alpha1, stack fails to install this version of ghc.

### Steps to reproduce

```
VERSION=9.2.1-alpha1
cd /tmp
mkdir ghc-test && cd ghc-test
wget https://raw.githubusercontent.com/DanBurton/stack-setup-info-gen/master/output/stack-ghc-$VERSION.yaml
mv stack-ghc-$VERSION.yaml stack.yaml
stack setup --verbose &> output.txt
```

### Expected

I expected stack to install this version of ghc.

### Actual

Stack failed to install this version of ghc. (This is on macos.)

```
# with the stack.yaml as mentioned above
$ stack setup --verbose &> output.txt
```

output.txt:
https://gist.github.com/DanBurton/d701fb3a606f89f08ac96bb2da1888fe

Of note, perhaps:

```
2021-04-01 18:23:05.352468: [error] ld: unknown option: --version
```

### Stack version

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by DanBurton** [comment]
(Unsurprisingly,) The same is true of 9.2.1-alpha2

```
VERSION=9.2.1-alpha2
cd /tmp
mkdir ghc-test && cd ghc-test
wget https://raw.githubusercontent.com/DanBurton/stack-setup-info-gen/master/output/stack-ghc-$VERSION.yaml
mv stack-ghc-$VERSION.yaml stack.yaml
stack setup --verbose &> output.txt
```

**Comment by DanBurton** [comment]
Possibly related

https://twitter.com/kmett/status/1385616677505667080

**Comment by brandonchinn178** [comment]
Is this still an issue? Adding `compiler: ghc-9.2.1` to `stack.yaml` has been working for me

**Comment by DanBurton** [comment]
`compiler: ghc-9.2.1` has been working for me as well.
