### ISSUE TITLE
s390x support

### ISSUE THREAD

**Issue by e-desouza** [commercialhaskell/stack#5520]
I'm trying to use stack to build Cardano on s390x and while we have `ghc` and all its dependencies via [EPEL](https://download.sinenomine.net/clefos/epel7/) on RHEL, there's no docs on how to build `stack` itself. I can provide a s390x machine for CI/CD etc if required.

Note : The install script as it will install the dependencies/libraries but pull down the x86 based binary, even on s390x so I patched it but now it says the binary doesn't exist.

```bash
# determines the the CPU's instruction set
get_isa() {
  if arch | grep -Eq 'armv[78]l?' ; then
    echo arm
  elif arch | grep -q aarch64 ; then
    echo aarch64
  elif arch | grep -q s390x ; then
    echo s390x
  else
    echo x86
  fi
}```

**Comment by tolysz** [comment]
I would imagine a couple of steps... 
once you have ghc working, you can try to build `stack` using `cabal`, then once you run it - it will complain about missing arch. 
Then you will need to add the correct architecture like here: https://github.com/commercialhaskell/stack/pull/5415/files
