### ISSUE TITLE
stack can't download ghc, I can't find any documentation to get around this

### ISSUE THREAD

**Issue by freefrancisco** [commercialhaskell/stack#5526]
I don't know if this is a bug, or just a question, but I've searched and I can't find any information on this. 
Whenever I try to run any stack command that would require a version of ghc it fails with the following error: 

```
stack build
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-8.8.4 ...
Download expectation failure: HttpExceptionRequest Request {
  host                 = "github.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","The Haskell Stack")]
  path                 = "/commercialhaskell/ghc/releases/download/ghc-8.8.4-release/ghc-8.8.4-x86_64-apple-darwin.tar.bz2"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
 (InternalException (HandshakeFailed (Error_Protocol ("certificate rejected: [InvalidSignature SignatureInvalid]",True,CertificateUnknown))))
```
This happens if I try to build, or even if I try to upgrade stack. I tried a fresh installation from the official website, and a homebrew installation, and they both fail the same way.  I installed a system ghc with ghcup and if I run stack with the `--system-ghc` flag it works fine then. It has no problem downloading the libraries, it's only on downloading ghc that it gives me this error.  Any pointers would be appreciated.

**Comment by ketzacoatl** [comment]
@freefrancisco, AFAICT, the error is buried down in this bit:

>  (InternalException (HandshakeFailed (Error_Protocol ("certificate rejected: [InvalidSignature SignatureInvalid]",True,CertificateUnknown))))

That's saying the HTTPS interactions with github.com failed due to the certificate being rejected. That's pretty odd, but suggests the env/shell environment/os might be missing some certificates or unable to locate the CA/root certs.

Maybe you can test downloading https://github.com/commercialhaskell/ghc/releases/download/ghc-8.8.4-release/ghc-8.8.4-x86_64-apple-darwin.tar.bz2 with `curl` to see if that works in the same shell?

**Comment by mpilgrem** [comment]
@freefrancisco, are you still experiencing this problem?

**Comment by freefrancisco** [comment]
@mpilgrem I no longer have the computer where that happened, that was a work computer and I have left that company since, so I am no longer experiencing the problem. I haven't experienced it on my home computer either.

**Comment by mpilgrem** [comment]
I will close the issue. If you or somebody else experiences something similar, they can post a new one.
