### ISSUE TITLE
Stack invokes the wrong Hadrian build script when building GHC from source

### ISSUE THREAD

**Issue by fwcd** [commercialhaskell/stack#5528]
### General summary

Building a recent version of GHC from source by specifying `compiler: ghc-git-COMMIT-FLAVOUR` in a `stack.yaml` ([as described here](https://github.com/commercialhaskell/stack/blob/master/doc/yaml_configuration.md#building-ghc-from-source-experimental)) fails with the following error:

```
Building GHC from source with `quick` flavour. It can take a long time (more than one hour)...
Did not find executable at specified path: /tmp/with-repo468829/cloned/hadrian/build.stack.sh
```

### Steps to reproduce

For example:

1. Create `stack.yaml` with

```yaml
compiler: ghc-git-7bc7eea3897dcb8a87fdb0921f451b9bc77309f6-quickest
```

(This is the newest GHC commit at the time of writing)

2. Run `stack build`

### Expected

The script `hadrian/build-stack` should be invoked.

### Actual

The script `hadrian/build.stack.sh` was invoked (apparently the script has been renamed).

### Stack version

```
$ stack --version
Version 2.5.1, Git revision d6ab861544918185236cf826cb2028abb266d6d5 x86_64 hpack-0.33.0
```

### Method of installation

Official binary

**Comment by hsyl20** [comment]
Thanks for fixing this! A related issue to fix:

In Stack.Setup, there is still:
```
           hadrianArgs = fmap T.unpack
               [ "-c"                    -- run ./boot and ./configure
               , "-j" <> tshow threads   -- parallel build
               , "--flavour=" <> flavour -- selected flavour
               , "binary-dist"
               ]
```

but `-c` is broken again (cf https://gitlab.haskell.org/ghc/ghc/-/issues/19804) and probably won't be fixed... Instead of using it, we should call the following commands before invoking hadrian:

```
stack --stack-yaml hadrian/stack.yaml exec -- ./boot
stack --stack-yaml hadrian/stack.yaml exec -- ./configure
```

@fwcd If you had the bandwidth to offer a patch for this, it would be great :)
