### ISSUE TITLE
stack build with older stack results in chr exception

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#554]
Steps to reproduce:

1. Run `stack build` with stack 0.1.2.0
2. Run `stack build` with stack 0.1.1.0

Expected: build will succeed

Actual: get an error message like:

> Prelude.chr: bad argument: 2635506

**Comment by snoyberg** [comment]
It appears that there are some lazy values being returned from binary deserialization, my guess being in the `Text` instances. First step: use `deepseq` to fully force those values. Second step: find the offending instance and destroy it.

**Comment by snoyberg** [comment]
Alright, I take it back, it's not binary deserialization.

**Comment by snoyberg** [comment]
Alright, I'm going slightly cross-eyed, so I'm going to stop investigating for now. This is coming from `tryGetCache` and `tryGetBuildCache`. This seems to be coming from parsing a `FilePath`, which makes me think this bug is in the binary package itself.

**Comment by snoyberg** [comment]
@chrisdone is there any reason not to use `decodeFileOrFile` in that function, which would catch a few extra corner cases?

**Comment by chrisdone** [comment]
Nope!

**Comment by themoritz** [comment]
If you run into this problem, deleting the `.stack-work` folder helps.
