### ISSUE TITLE
`stack init` includes packages from `./dist-newstyle/`

### ISSUE THREAD

**Issue by sol** [commercialhaskell/stack#5541]
After running `stack init` for a project that was built with `cabal` before, I ended up with things like

```
- dist-newstyle/tmp/src-1145092/text-1.2.4.1
- dist-newstyle/tmp/src-1145092/text-1.2.4.1/benchmarks
- dist-newstyle/tmp/src-1145092/text-1.2.4.1/tests
```
in `stack.yaml` under `packages`.

```
$ stack --version
Version 2.7.1, Git revision 8afe0c2932716b0441cf4440d6942c59568b6b19 x86_64 hpack-0.34.4
```

**Comment by mpilgrem** [comment]
I assume that something had caused Cabal to put a `*.cabal` file in each of the mentioned directories, but I do not know what. I experimented with: 

~~~text
> stack new goo simple --no-init
> cd goo
> stack exec --no-ghc-package-path -- cabal configure # Creates a dist-newstyle directory
> stack exec --no-ghc-package-path -- cabal build # Creates an empty dist-newstyle/tmp directory
> stack init # No problems, as tmp is empty
~~~

I don't know how `stack init` could distinguish between an intended Cabal file and an unintended Cabal file (unknown to the user too), as it has no way of knowing the user's intent other than through its arguments.

I will, however, add something to the online help for `stack init`.
