### ISSUE TITLE
Correct ghc options might not be used

### ISSUE THREAD

**Issue by modestotech** [commercialhaskell/stack#5542]
When running `stack ghci hello.hs` I get the following error:
```
Couldn't find a component for file target /Users/max/training_repos/haskell_training/helloworld/hello.hs. This means that the correct ghc options might not be used.
```

The program still works, but I don't like errors. I suppose that I need some more configuration, but what?

### Stack version

```
$ stack --version
Version 2.7.1 x86_64
```

### Method of installation

Fresh install of `haskell-stack` on macOS. I've tried it through the curl links, and by using `brew install haskell-stack`. Same problem with both.

**Comment by mpilgrem** [comment]
When you target a `*.hs` file with `stack ghci`, Stack tries to see if the file falls within the scope of one component of a Cabal file and, if it does, use the GHC options specified for that component. This warning is telling you that, for your `hello.hs` file, there is no such component. For some users it will be a warning, for others (including your case) just information.
