### ISSUE TITLE
stack upgrade crashes in android/termux/ubuntu-20.04-LTS

### ISSUE THREAD

**Issue by libweirdness** [commercialhaskell/stack#5548]
stack update worked,
but:
$ stack upgrade

Warning: Exception occured when trying to perform binary upgrade:
         Control.Exception.Safe.throwString called with:

Binary upgrade not yet supported on arch: AArch64
Called from:
  stringException (src/Stack/Setup.hs:1847:23 in stack-1.9.3.1-Ge7G2dqYztGJA30RMpgH55:Stack.Setup)

         Falling back to source upgrade
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
No updates to your package index were found
Update complete
Populated index cache.
Warning: /tmp/stack-upgrade-fad42a84b7c89703/stack-2.7.1/stack.yaml: Unrecognized field in ProjectAndConfigMonoid: drop-packages
Downloading lts-17.10 build plan ...
RedownloadInvalidResponse Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/fpco/lts-haskell/master//lts-17.10.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 "/home/me/.stack/build-plan/lts-17.10.yaml" (Response {responseStatus = Status {statusCode = 404, statusMessage = "Not Found"}, responseVersion = HTTP/1.1, responseHeaders = [("Connection","keep-alive"),("Content-Length","14"),("Content-Security-Policy","default-src 'none'; style-src 'unsafe-inline'; sandbox"),("Strict-Transport-Security","max-age=31536000"),("X-Content-Type-Options","nosniff"),("X-Frame-Options","deny"),("X-XSS-Protection","1; mode=block"),("Content-Type","text/plain; charset=utf-8"),("X-GitHub-Request-Id","4FA8:2E8E:4001F0:529159:60A7CD3B"),("Accept-Ranges","bytes"),("Date","Fri, 21 May 2021 15:09:47 GMT"),("Via","1.1 varnish"),("X-Served-By","cache-yul12821-YUL"),("X-Cache","MISS"),("X-Cache-Hits","0"),("X-Timer","S1621609787.347118,VS0,VE71"),("Vary","Authorization,Accept-Encoding"),("Access-Control-Allow-Origin","*"),("X-Fastly-Request-ID","8b9ce57289f11bc2e9b239024fb5261ae25a3a46"),("Expires","Fri, 21 May 2021 15:14:47 GMT"),("Source-Age","0")], responseBody = (), responseCookieJar = CJ {expose = []}, responseClose' = ResponseClose})

apt installed...
haskell-stack/focal,now 1.9.3.1-1 arm64 [installed]
pkg-haskell-tools/focal,now 0.12build3 arm64 [installed]

I tried informing the company who made stack, FP Complete,
but they have only a sales email.

So, this week I try here...

I'm learning haskell in my tablet,
so if I don't know these systems, there's reason.

if I can help, other infos to include, please tell me.

( :

**Comment by qxjit** [comment]
What does `stack --version` output for you? I just experience a similar `404` error trying to down build plans for various LTS versions with 1.9.3. `stack upgrade`  fixed it for me, but if `stack upgrade` itself is failing for you maybe a manual re-install needs to be done?

I have a feeling some old path-conventions that were hard coded into older versions of stack just reached end-of-life recently.

**Comment by mpilgrem** [comment]
@libweirdness, Stack 1.9.3.1 is quite an old version of Stack (18 Apr 2019). I suggest you install Stack, rather than trying to upgrade it: https://docs.haskellstack.org/en/stable/install_and_upgrade/.
