### ISSUE TITLE
location: git: commit: doesn't work for yesod

### ISSUE THREAD

**Issue by myShoggoth** [commercialhaskell/stack#555]
Trying to use stack to build a docker container for my project that uses custom changes in Yesod Form that are in a PR, I can use the location: git: syntax in the stack.yaml file for a different project I have a custom version of (shakespeare in this case), but when I tried to do the same for Yesod itself it barfs:

    No .cabal file found in directory /home/aboardman/startupspot/.stack-work/downloaded/9c3592f6c12642d73d17fc1731d72e1999aba65c6a2985e75a76c48e4cd96b52.git/

So either I need a .cabal file in the root of Yesod for this to work, or some way of pointing it at one of the subdirectories for the .cabal file in question. Looked for a way to make a .cabal file that just pointed at subdirectory .cabal files but didn't see a supported syntax.

**Comment by snoyberg** [comment]
Check the wiki page on stack.yaml syntax, there's support for a list of
subdirectories.

**Comment by myShoggoth** [comment]
Aha, new syntax. Should have checked there first, tried this and it worked great.
