### ISSUE TITLE
Could not find module ‘Network.HTTP’

### ISSUE THREAD

**Issue by lzunsec** [commercialhaskell/stack#5551]
I'm very new to haskell, stack, cabal, etc.

I'm trying this simple example:

```
module Main where
import Network.HTTP

import Lib

get :: String -> IO String
get url = simpleHTTP (getRequest url) >>= getResponseBody

getCode :: String -> IO ResponseCode
getCode url = simpleHTTP req >>= getResponseCode
    where req = getRequest url

main :: IO ()
main = do 
    x <- get "http://pudim.com.br"
    putStrLn x
```

In a `stack` project. I did `stack new` then `stack setup` and `stack run`

and I get:

```
/workspaces/hask_exercises/api-exercises/app/Main.hs:2:1: error:
    Could not find module ‘Network.HTTP’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
2 | import Network.HTTP
  | ^^^^^^^^^^^^^^^^^^^

```

how and why I should install `Netowork.HTTP`? Isn't it a core library?

**Comment by curaai00** [comment]
Should read [this](https://docs.haskellstack.org/en/stable/GUIDE/#adding-dependencies). Also User Guide in stack will be useful for starting haskell.

Add this lines to your package.yaml:

```yaml 
dependencies:
- base >= 4.7 && < 5
- HTTP # added here
```

**Comment by ocramz** [comment]
@lzunsec no, HTTP is not included in the Haskell prelude, but it's easy to import packages that provide it as @curaai00 shows.

BTW this is not a `stack` issue so it can be closed.
