### ISSUE TITLE
How to get Stack v1.9.3

### ISSUE THREAD

**Issue by H1h8** [commercialhaskell/stack#5553]
I need to have an old **Windows** executable of **Stack v1.9.3** .
Where can I get one?

I want it to build an abandoned Haskell project from Github that I want to study.
And the current  stack version failed to build it because it does no longer support old Cabal.

Do I have to download tag v1.9.3 from the Github repository and build it myself?
If so, would the current version of stack be able to do it and would the result be the "correct" artifact?

Thanks, Hubert.

**Comment by qrilka** [comment]
See https://github.com/commercialhaskell/stack/releases/tag/v1.9.3

**Comment by H1h8** [comment]
Thanks.
You mean that I should then use the current version of Stack to build the old one from the tarball? 

I'll try and report what happens.

**Comment by qrilka** [comment]
If you follow the link I've given above you could get v1.9.3 for a number of platforms including Window

**Comment by H1h8** [comment]
Thanks. That's it.

Started off with
>stack --version
>Version 2.7.1, Git revision 8afe0c2932716b0441cf4440d6942c59568b6b19 x86_64 hpack-0.34.4


Downloaded and ran:
**stack-1.9.3-windows-x86_64-installer.exe**
from:
https://github.com/commercialhaskell/stack/releases/tag/v1.9.3

Got:
>stack --version
>Version 1.9.3, Git revision 40cf7b37526b86d1676da82167ea8758a854953b (6211 commits) x86_64 hpack-0.31.1

I did not have to build it from source. Good.
Thanks again. Closed.
