### ISSUE TITLE
Stack tries to do DNS query bypassing proxy

### ISSUE THREAD

**Issue by gergoerdi** [commercialhaskell/stack#5563]
On a fresh install of Stack 2.7.1, I have the `http_proxy` and `https_proxy` env. vars set. Here's an invocation of `curl` to show that the proxy is set up correctly:

```
mi@mi-rhel6[~] $ curl  -I https://hackage.haskell.org:443/root.json
HTTP/1.1 200 Connection Established
Proxy-Agent: Zscaler/6.1

HTTP/1.1 200 OK
Connection: close
Content-Length: 3850
Server: nginx/1.18.0 (Ubuntu)
Content-Type: application/json
Cache-Control: public, no-transform, max-age=60
Content-MD5: koKoFHhew9GZY7BB+GgPMQ==
ETag: "9282a814785ec3d19963b041f8680f31"
Accept-Ranges: bytes
Date: Thu, 10 Jun 2021 08:16:06 GMT
Via: 1.1 varnish
Age: 0
X-Served-By: cache-hkg17923-HKG
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1623312965.471991,VS0,VE712
Vary: Accept-Encoding
```

Now from the same shell, with the same env. vars, if I try to do a `stack update` which tries downloading the very same file:
```

mi@mi-rhel6[~] $ stack update 
Selected mirror https://hackage.haskell.org/
Downloading root
HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Accept-Encoding",""),("User-Agent","Haskell pantry package")]
  path                 = "/root.json"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure Network.Socket.getAddrInfo (called with preferred socket type/protocol: AddrInfo {addrFlags = [AI_ADDRCONFIG], addrFamily = AF_UNSPEC, addrSocketType = Stream, addrProtocol = 0, addrAddress = <assumed to be undefined>, addrCanonName = <assumed to be undefined>}, host name: Just "sg-mbfc-lan-prx01.global.standardchartered.com", service name: Just "8080"): does not exist (Name does not resolve))
```

The error message suggests that Stack is trying to resolve `hackage.haskell.org` itself instead of going through the proxy.

**Comment by hasufell** [comment]
Stack uses [http-download](https://hackage.haskell.org/package/http-download) for downloads, which uses http-client/http-conduit/http-client-tls.

It appears the env vars should be supported: https://github.com/snoyberg/http-client/blob/c8ee1a978423d825a1d65f2a15080a7fe7757170/http-client-tls/Network/HTTP/Client/TLS.hs#L186-L187

Maybe the parser fails: https://github.com/snoyberg/http-client/blob/c8ee1a978423d825a1d65f2a15080a7fe7757170/http-client-tls/Network/HTTP/Client/TLS.hs#L222

What are the contents of your env vars?

**Comment by mpilgrem** [comment]
I am closing this issue as it cannot be investigated further without knowing the content of the relevant environment variables.
