### ISSUE TITLE
How do I normally use the package installed in the snapshots  directory

### ISSUE THREAD

**Issue by learn-man** [commercialhaskell/stack#5564]

**Comment by learn-man** [comment]
@mattaudesse :

Yes, if the file including some the package installed in `~/.stack/snapshots/*/lib/`.

The same result of directly use `ghc` to compile the file , if the file including the package installed in `~/.stack/snapshots/*/lib/`.

**import** all  packages installed in the `~/.stack/snapshots/*/lib/` were failed to compile.

**Comment by ketzacoatl** [comment]
This is probably good to close, would you agree @mattaudesse?

**Comment by mattaudesse** [comment]
Seems reasonable to me - thanks @ketzacoatl.
