### ISSUE TITLE
Cannot install gi-gdkpixbuf in LTS-17.15

### ISSUE THREAD

**Issue by PaulJohnson** [commercialhaskell/stack#5565]
Please follow the steps below for reporting a bug:

Make sure that you are using the latest release (currently stack-2.7.1).
See the [upgrade instructions](http://docs.haskellstack.org/en/stable/install_and_upgrade/#upgrade) to upgrade.

Please use the following schema for your bug report:

### Steps to reproduce

Stack.yaml:

    resolver: lts-17.15
    packages: []

    $ stack build gi-gdkpixbuf

### Expected

Package gi-gdkpixbuf builds and installs successfully.

### Actual

What actually happened.

```
gi-gdkpixbuf> [20 of 25] Compiling GI.GdkPixbuf.Structs.PixbufModule
gi-gdkpixbuf> 
gi-gdkpixbuf> /tmp/stack-cdec62c7e1bef510/gi-gdkpixbuf-2.0.24/GI/GdkPixbuf/Structs/PixbufModule.hs:194:1: error:
gi-gdkpixbuf>     Could not find module ‘GI.GModule.Structs.Module’
gi-gdkpixbuf>     Use -v (or `:set -v` in ghci) to see a list of the files searched for.
gi-gdkpixbuf>     |
gi-gdkpixbuf> 194 | import qualified GI.GModule.Structs.Module as GModule.Module
gi-gdkpixbuf>     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi-gdkpixbuf> 

--  While building package gi-gdkpixbuf-2.0.24 (scroll up to its section to see the error) using:
      /tmp/stack-cdec62c7e1bef510/gi-gdkpixbuf-2.0.24/.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0/setup/setup --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```
Verbose trace appended as a file.

### Stack version

```
$ stack --version
Version 2.7.1, Git revision 8afe0c2932716b0441cf4440d6942c59568b6b19 x86_64 hpack-0.34.4
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by PaulJohnson** [comment]
The verbose trace turns out to be over 512kbytes. If you need it then let me know how to get it to you.

**Comment by mpilgrem** [comment]
I am going to close this given the passage of time and because the current version of Stack builds `gi-gdkpixbuf-2.0.31
