### ISSUE TITLE
ghc-8.10.4 and ghc-8.10.5 missing for Arch linux

### ISSUE THREAD

**Issue by paweljakubas** [commercialhaskell/stack#5572]
### General summary/comments (optional)

`stack build` does not work with projects using 8.10.4 or 8.10.5

### Steps to reproduce

$ stack build

### Expected

project builds

### Actual

No setup information found for ghc-8.10.4 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'linux64-nopie'.
Supported versions: ghc-7.8.4, ghc-7.10.1, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.1, ghc-8.4.2, ghc-8.4.3, ghc-8.4.4, ghc-8.6.1, ghc-8.6.2, ghc-8.6.3, ghc-8.6.4, ghc-8.6.5, ghc-8.8.1

**Comment by hasufell** [comment]
It's true there are no such bindists for `nopie`: https://github.com/commercialhaskell/stackage-content/blob/42ee038896ebb94e067797b6f741429c87c3da35/stack/stack-setup-2.yaml#L576

But what I don't understand is how you end up with `linux64-nopie` on arch. I get `linux64-tinfo6` for which those bindists exist.

**Comment by paweljakubas** [comment]
Hi Julian @hasufell !

Many thanks for pointing this out. Indeed, I had in `~/.stack/config.yaml` the setting  `ghc-build: nopie` and I changed to `ghc-build: tinfo6` and it started to work.
