### ISSUE TITLE
Consider add `stack config set skip-msys --global`

### ISSUE THREAD

**Issue by jneira** [commercialhaskell/stack#5573]
* Not sure why the options included in `stack config set` are limited and dont apply for all of them in a generic way. I suppose there would be good reasons.
* If make all config options modificable with `stack config set` is not feasible it would propose include at least `skip-msys`, cause it is relative frequent that windows environments has msys already installed. In such envs being able to script this option would be very handy.
* The concrete use case is related with the recent support for stack (and windows) in ghcup. That tool already is installing and managing msys2, so it would be desirable make stack use that installation. But i think it could be useful in more scenarios.
* Other global options related with msys which may be useful are: `extra-path`, `extra-include-dirs` and `extra-lib-dirs`

Thanks in advance!

**Comment by hasufell** [comment]
@jneira why was this closed?

**Comment by jneira** [comment]
Oh, i was cleaning up my issue list and this had no feedback from anyone, specially anyone from the stack team so i guess this will never done.
But i can reopen if you think it can be useful in any way
