### ISSUE TITLE
GHC installation hooks

### ISSUE THREAD

**Issue by hasufell** [commercialhaskell/stack#5580]
## Motivation

A user may want to delegate the installation of GHC to a 3rd party tool or use a custom shell script to have full control over how and where GHC is installed.

## Specification

When stack requests a GHC version, it could:

1. check for the file `$STACK_ROOT/hooks/ghc-install.sh`
2. if the file is executable, invoke it with a set of environment variables set, e.g. GHC version (or commit/repo for the experimental building from source feature @hsyl20 )
3. read the stdout and treat it as the *path* to the GHC `bin/` directory, so it knows where all the tools are

## Rationale

1. Would allow ghcup to better integrate with stack, by providing a default hook
2. No maintenance overhead for the stack team, no need to actively integrate with installer tools
3. Great flexibility for users, they could even use nix or their package manager to install GHC
4. Requires no `PATH` shenanigans
5. This is a very common pattern, used by git, package managers and other tools. It has proven very powerful and light-weight.

## Open questions

1. Would this work on windows the same way?
2. Should hooks be global or also per-repository?
3. What exact variables need to be exposed?

## References

* https://github.com/haskellfoundation/tech-proposals/pull/7
* https://discourse.haskell.org/t/rfc-brokering-toolchain-installations-with-hs/2746/4?u=hasufell
* https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/173

----

I currently don't have the capacity to provide a reference implementation, but I'd guess the stack codebase is well structured that this wouldn't be a huge task.

@bgamari @emilypi

**Comment by cdornan** [comment]
@hasufell as you know there is an ongoing discussion of a proposal to solve this problem in a [forum dedicated to the issue](https://haskell.foundation/projects/), which as we all know is highly delicate. Raising this issue here is really not going to help this process. I am closing it.

**Comment by hasufell** [comment]
@cdornan I am speechless.

**Comment by tchoutri** [comment]
As a stack user who uses ghcup to install HLS for my GHC versions, this would be extremely useful to have.
