### ISSUE TITLE
“Could not find sandboxed compiler” on incomplete compiler removal

### ISSUE THREAD

**Issue by bradrn** [commercialhaskell/stack#5584]
### General summary/comments

When a particular GHC version is required but has not yet been installed, Stack will download that GHC version. All these copies of GHC take up a lot of space on my computer, so I often remove old GHC versions. However, if I subsequently try to use that version of GHC again, this gives me the error `Could not find sandboxed compiler` unless I also remember to remove the corresponding `ghc-x.y.z.installed` and `ghc-x.y.z.tar.xz` files as well. I realise that having the `ghc-x.y.z/` directory but not these other files is a somewhat pathological case, but it comes up regularly enough for me (and presumably others as well) that I feel it would be useful for Stack to deal with this case correctly. (Potentially it could even skip the download step if it finds an already-existing `ghc-x.y.z.tar.xz`, unless this has disadvantages of which I am unaware.)

### Steps to reproduce

1. Delete an old GHC installation by removing the appropriate directory (on my Windows computer at `~\AppData\Local\Programs\stack\x86_64-windows\ghc-x.y.z\`).
2. Try to run a program using that version of GHC.
3. Remove the rest of the GHC installation by deleting `ghc-x.y.z.installed` and `ghc-x.y.z.tar.xz` in the same directory.
4. Run the program again.

### Expected

Stack reinstalls GHC successfully on step (2).

### Actual

On step (2), Stack gives an error `Could not find sandboxed compiler`. GHC is only downloaded successfully at step (4).

### Stack version

```
> stack --version
Version 2.7.1, Git revision 8afe0c2932716b0441cf4440d6942c59568b6b19 x86_64 hpack-0.34.4
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mpilgrem** [comment]
In a sense, Stack is dealing with the case correctly: the presence of the `.installed` file indicates that the Stack-supplied GHC should be installed and Stack is correctly reporting as an error that the GHC is missing.

A command to remove a Stack-supplied GHC was discussed here: https://github.com/commercialhaskell/stack/issues/133 - but ended up on the wishlist.

On the tarball, it is not downloaded if already present. However, https://github.com/commercialhaskell/stack/issues/1768 suggests it be removed. Then again, https://github.com/commercialhaskell/stack/issues/562 rejected that suggestion.

At least, the in-app and online help could be improved.
