### ISSUE TITLE
"stack test --file-watch --no-keep-going" keeps going

### ISSUE THREAD

**Issue by ezyang** [commercialhaskell/stack#559]
Steps to reproduce:

1. Get a copy of Cabal head
2. Run `stack test --file-watch --no-keep-going`
3. Make random changes which break the build

Expected result: While Cabal is broken, tests are not run

Actual result: Sometimes stack gets wedged and starts repeatedly running the test suite, even with no changes.

**Comment by snoyberg** [comment]
I'm unable to reproduce. Can you provide some `stack -v` output to help with debugging?

**Comment by snoyberg** [comment]
No response provided, closing.
