### ISSUE TITLE
[Question] Skip recompilation, but update hashes -- is it possible?

### ISSUE THREAD

**Issue by MuhammedZakir** [commercialhaskell/stack#5601]
Reason:

I use XMonad. Whenever I make a very small/simple modification to `xmonad` lib, `xmonad-contrib` is also recompiled (as it depends on `xmonad`). The problem is `xmonad-contrib` is big, and so it's cumbersome to recompile, especially when it's unnessary. 

Question:

So what I am wondering is, is it possible to "update" a library without recompilation if *user-specified dependencies* are changed? That is, Stack will skip recompilation, but will update the hash (and/or will do whatever other stuff it does when a lib is recompiled).

### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

* GHCup

---

P.S. Why is GHCup not in installation methods? Also, the current "latest stack version" mention in issue template is outdated (is it not automated?).

**Comment by mpilgrem** [comment]
@MuhammedZakir, I am working through open issues, including old ones. If I follow your main question, I think the short answer is no - however, I may not understand fullt what you were asking. The information saved in a snapshot includes an `*.hi` file for each module and that file is generated by GHC when it compiles the module.

On your PSs, with the passage of time, GHCup is now mentioned online as an installation method. The update of the repository GitHub templates is not automated. The current templates are, however, up to date.
