### ISSUE TITLE
can't use stack build in any directory 

### ISSUE THREAD

**Issue by AIengineer13** [commercialhaskell/stack#5602]
for some reason i cant stack build in my computers it comes with follow message :  

Encountered error while migrating Stack database:
    SQLite3 returned ErrorCan'tOpen while attempting to perform open "C:\\Users\\brune\\desktop\\buiop\\.stack-work\\stack.sqlite3".
Please report this on https://github.com/commercialhaskell/stack/issues
As a workaround you may delete Stack database in C:\Users\brune\desktop\buiop\.stack-work\stack.sqlite3 triggering its recreation.   

can someboy help me

**Comment by crypto-gainz** [comment]
Encountering the same issue... I can't seem to get it to work.

**Comment by crypto-gainz** [comment]
Ok, so I actually found the solution with a bit of tinkering.

Not sure which of these fixed it but, here's what I did.

1. Closed my IDE and terminals
2. Opened a new terminal & upgraded Stack `stack upgrade`
2. Opened my IDE and did a fresh `stack new NAME` in my workspace
3. Ran `stack build`
4. I got a notification from my antivirus (AVAST) that told me the database access of Stack was blocked and asked me if I should allow permissions to it. I whitelisted it from the AVAST popup and I did `stack build` again.
5. After that, the behaviour was normal.

@AIengineer13

**Comment by AIengineer13** [comment]
hi im trying dod the same but i cant make it run


Crypto Gainz ***@***.***> escreveu no dia quinta, 19/08/2021
à(s) 17:35:

**Comment by AIengineer13** [comment]
now its running thank you so much man

**Comment by qrilka** [comment]
@crypto-gainz it would be great if you could create a PR adding this into Stack docs
