### ISSUE TITLE
ghc download reports bytes without an indication of when it will be finished

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#561]
I found the byte count odd although it provided a small comfort to know that something was downloading and not completely stuck.
Given that the byte count demonstrates progress immediately, it may be a good idea to keep it.

But it would be better to also indicate when the end will occur. This could be show a % of total size. Just a count of the MB size of the current download would help out a bit also.

**Comment by snoyberg** [comment]
I agree. @DanBurton can you handle that?

**Comment by snoyberg** [comment]
Alternatively, if someone else wants to jump in, this should be a pretty trivial change once the relevant part of the codebase is pointed out, which I'm sure Dan would be happy to help with.

**Comment by chrisdone** [comment]
Right, this reporting part is just incomplete. Tracking it got lost in the ether.

For anyone wanting to implement, [related code is here](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Setup.hs#L680..L718) and the information can be gotten from [here](https://github.com/commercialhaskell/stack/blob/master/src/Network/HTTP/Download/Verified.hs#L271). 

Something like `ghc: downloading 250MB/500MB (50%)` should do the trick.
