### ISSUE TITLE
aarch64 linux binaries generated for 2.7.1, but not 2.7.3

### ISSUE THREAD

**Issue by liam-ly** [commercialhaskell/stack#5610]
I was happy to see aarch64 binaries for 2.7.1, however they have not been generated for 2.7.3. Is this an oversight, a bug, or is this binary not supported in this version of stack? What needs to be done to allow ongoing support for this binary release?

https://github.com/commercialhaskell/stack/releases/tag/v2.7.1 includes
```
stack-2.7.1-linux-aarch64.tar.gz
```

https://github.com/commercialhaskell/stack/releases/tag/v2.7.3 does not include a linux-aarch64 binary. Upon further investigation, the CI job appears to include the binary https://github.com/commercialhaskell/stack/actions/runs/1048914350, but it's not extracted and uploaded to the release.

**Comment by AlistairB** [comment]
Hi, just a note that [docker haskell is looking at supporting ARM including stack via these binaries](https://github.com/haskell/docker-haskell/issues/25). Can the missing 2.7.3 ones be added? Or can we expect them to be included in future releases?

**Comment by hasufell** [comment]
ghcup has the missing binaries

**Comment by AlistairB** [comment]
Probably worth noting that the [2.7.1 aarch64 binaries do not appear to work](https://github.com/commercialhaskell/stack/issues/2103#issuecomment-972329065). So you could just track this issue as part of https://github.com/commercialhaskell/stack/issues/2103
