### ISSUE TITLE
Mac OSX Build Woes

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/stack#5611]
## General summary/comments (optional)

This might not be a Stack-specific issue, but I'm not quite sure where else to ask. I'm also curious if anyone else is running into these issues using Stack. I'm running `stack build --test --no-run-tests --bench --no-run-benchmarks --fast` in a monorepo with multiple packages.

### Attempting to use module which is not loaded

```
attempting to use module ‘my-package-0.1.0.0-9qoNHSv9Jlu52dERPDiZBH:MyPackage.Foo’
(src/MyPackage/Foo.hs) which is not loaded
```

Neither `stack clean my-package` and `rm -rf my-package/.stack-work` work. `stack purge` works.

### Resource temporarily unavailable

```
clang: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
`gcc' failed in phase `Assembler'. (Exit code: 1)
```
```
fatal error: /Library/Developer/CommandLineTools/usr/bin/ar: can't fork a new process to execute:
/Library/Developer/CommandLineTools/usr/bin/ranlib (Resource temporarily unavailable)
```

## Misc info

Stack version: 2.7.3, GitHub binary
MacOS Catalina 10.15.7

```bash
$ sysctl -a | grep maxproc
kern.maxproc: 4176
kern.maxprocperuid: 2784
```

```bash
$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by mpilgrem** [comment]
Closing given the passage of time.
