### ISSUE TITLE
Using --allow-newer results in an older version being used

### ISSUE THREAD

**Issue by wenkokke** [commercialhaskell/stack#5612]
Please follow the steps below for reporting a bug:

Make sure that you are using the latest release (currently stack-2.7.3).
See the [upgrade instructions](http://docs.haskellstack.org/en/stable/install_and_upgrade/#upgrade) to upgrade.

Please use the following schema for your bug report:

### General summary/comments (optional)

I've set allow-newer in PLFA's Stack file, but when running stack build, it outputs:

```
WARNING: Ignoring plfa's bounds on Agda (==2.6.2); using Agda-2.6.1.3.
Reason: allow-newer enabled.
```

I'd not expect allow-newer to use an *older* version. Is this expected behaviour?

### Steps to reproduce

``` bash
git clone git@github.com:plfa/plfa.github.io.git
# change Agda version bound to 2.6.2
stack build
```

### Expected

I'd expect Agda version 2.6.2 or any *newer* version to be used.

### Actual

Agda version 2.6.1.3 is used.

### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by hasufell** [comment]
I believe you only changed the bound in the `.cabal` file, not in `stack.yaml`.

Also see https://docs.haskellstack.org/en/stable/yaml_configuration/#allow-newer

> Note that this also ignores lower bounds. The name "allow-newer" is chosen to match the commonly used cabal option.

**Comment by wenkokke** [comment]
I see, that clarifies things. In that case, I suppose I'd like to change my grievance to 'The --allow-newer option has a misleading name.'
