### ISSUE TITLE
ghc-8.10.7 stack installation not working for Windows

### ISSUE THREAD

**Issue by jmmarulang** [commercialhaskell/stack#5616]
# Steps to reproduce

1. Create a Stack project with multiple executables
2. Add the following configuration to the .yaml file:
```
resolver: lts-18.8
compiler: ghc-8.10.7
compiler-check: match-exact
```

3. Run the command `stack setup`

# Expected

The specified ghc version to be download would be expected.

# Actual

What actually happened.

```
$ stack setup
No setup information found for ghc-8.10.7 on your platform.
This probably means a GHC bindist has not yet been added for OS key 'windows64'.
Supported versions: ghc-7.8.4, ghc-7.10.1, ghc-7.10.2, ghc-7.10.3, ghc-8.0.1, ghc-8.0.2, ghc-8.2.1, ghc-8.2.2, ghc-8.4.1, ghc-8.4.2, ghc-8.4.3, ghc-8.4.4, ghc-8.6.1, ghc-8.6.2, ghc-8.6.3, ghc-8.6.4, ghc-8.6.5, ghc-8.8.1, ghc-8.8.2, ghc-8.8.3, ghc-8.8.4, ghc-8.10.1, ghc-8.10.2, ghc-8.10.3, ghc-8.10.4, ghc-8.10.5, ghc-8.10.6, ghc-9.0.1
```

# Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```
# Windows version
System type 64-bit operating system, x64-based processor

Edition Windows 10 Pro

Version 20H2

CC'ing @asr

**Comment by hasufell** [comment]
It appears there was a mistake in the commit: https://github.com/commercialhaskell/stackage-content/commit/c6620ac570d9f578ae409eeeda392ee326921cea#diff-abdc63e62df05fecf69d1f67bcf237cfa1cd73c8514e1f38713f66c4ef9f421bR1846

The win64 bindist was added to FreeBSD.

@borsboom

**Comment by borsboom** [comment]
Thanks to @hasufell's PR, which I've merged, this should now be fixed.
