### ISSUE TITLE
stack build - I don't know how to install GHC for (OSX,AArch64), please install manually

### ISSUE THREAD

**Issue by WarrickFitz** [commercialhaskell/stack#5617]
### Stack version

```
$ stack --version
Version 2.7.3 aarch64
Compiled with:
- Cabal-3.2.1.0
- Glob-0.10.1
- StateVar-1.2.1
- aeson-1.5.6.0
- annotated-wl-pprint-0.7.0
- ansi-terminal-0.11
- ansi-wl-pprint-0.6.9
- appar-0.1.8
- array-0.5.4.0
- asn1-encoding-0.9.6
- asn1-parse-0.9.5
- asn1-types-0.3.4
- assoc-1.0.2
- async-2.2.3
- attoparsec-0.14.1
- attoparsec-iso8601-1.0.2.0
- auto-update-0.1.6
- base-4.14.2.0
- base-compat-0.11.2
- base-compat-batteries-0.11.2
- base-orphans-0.8.4
- base16-bytestring-1.0.1.0
- base64-bytestring-1.2.0.1
- basement-0.0.12
- bifunctors-5.5.11
- binary-0.8.8.0
- blaze-builder-0.4.2.1
- blaze-html-0.9.1.2
- blaze-markup-0.8.2.8
- byteorder-1.0.4
- bytestring-0.10.12.0
- casa-client-0.0.1
- casa-types-0.0.2
- case-insensitive-1.2.1.0
- cereal-0.5.8.1
- clock-0.8.2
- colour-2.3.6
- comonad-5.0.8
- conduit-1.3.4.1
- conduit-combinators-1.3.0
- conduit-extra-1.3.5
- connection-0.3.1
- containers-0.6.4.1
- contravariant-1.5.3
- cookie-0.4.5
- cryptohash-sha256-0.11.102.0
- cryptonite-0.29
- cryptonite-conduit-0.2.2
- data-default-class-0.1.2.0
- data-fix-0.3.1
- deepseq-1.4.4.0
- digest-0.0.1.3
- directory-1.3.6.0
- distributive-0.6.2.1
- dlist-1.0
- easy-file-0.2.2
- echo-0.1.4
- ed25519-0.0.5.0
- either-5.0.1.1
- exceptions-0.10.4
- extra-1.7.9
- fast-logger-3.0.5
- file-embed-0.0.14.0
- filelock-0.1.1.5
- filepath-1.4.2.1
- filtrable-0.1.6.0
- fsnotify-0.3.0.1
- generic-deriving-1.14
- ghc-boot-th-8.10.5
- ghc-prim-0.6.1
- githash-0.1.6.1
- hackage-security-0.6.0.1
- hashable-1.3.2.0
- hfsevents-0.1.6
- hi-file-parser-0.1.2.0
- hourglass-0.2.12
- hpack-0.34.4
- hpc-0.6.1.0
- http-api-data-0.4.3
- http-client-0.7.8
- http-client-tls-0.3.5.3
- http-conduit-2.3.8
- http-download-0.2.0.0
- http-types-0.12.3
- indexed-traversable-0.1.1
- infer-license-0.2.0
- integer-gmp-1.0.3.0
- integer-logarithms-1.0.3.1
- iproute-1.7.11
- libyaml-0.1.2
- lift-type-0.1.0.1
- lifted-base-0.2.3.12
- lukko-0.1.1.3
- megaparsec-9.1.0
- memory-0.16.0
- microlens-0.4.12.0
- microlens-mtl-0.2.0.1
- microlens-th-0.4.3.10
- mime-types-0.1.0.9
- mintty-0.1.2
- monad-control-1.0.2.3
- monad-logger-0.3.36
- monad-loops-0.4.3
- mono-traversable-1.0.15.1
- mtl-2.2.2
- mustache-2.3.1
- neat-interpolation-0.5.1.2
- network-3.1.2.2
- network-uri-2.6.4.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- open-browser-0.2.1.0
- optparse-applicative-0.16.1.0
- optparse-simple-0.1.1.4
- pantry-0.5.2.3
- parsec-3.1.14.0
- parser-combinators-1.3.0
- path-0.9.0
- path-io-1.6.3
- path-pieces-0.2.1
- pem-0.2.4
- persistent-2.13.1.1
- persistent-sqlite-2.13.0.3
- persistent-template-2.12.0.0
- pretty-1.1.3.6
- primitive-0.7.1.0
- process-1.6.9.0
- profunctors-5.6.2
- project-template-0.2.1.0
- random-1.2.0
- regex-applicative-0.3.4
- regex-applicative-text-0.1.0.1
- resource-pool-0.2.3.2
- resourcet-1.2.4.2
- retry-0.9.0.0
- rio-0.1.20.0
- rio-orphans-0.1.2.0
- rio-prettyprint-0.1.1.0
- rts-1.0.1
- safe-0.3.19
- safe-exceptions-0.1.7.2
- scientific-0.3.7.0
- semigroupoids-5.3.5
- semigroups-0.19.1
- silently-1.2.5.1
- socks-0.6.1
- split-0.2.3.4
- splitmix-0.1.0.3
- stm-2.5.0.1
- stm-chans-3.0.0.4
- streaming-commons-0.2.2.1
- strict-0.4.0.1
- syb-0.7.2.1
- tagged-0.8.6.1
- tar-0.5.1.1
- tar-conduit-0.3.2
- template-haskell-2.16.0.0
- temporary-1.3
- text-1.2.4.1
- text-metrics-0.3.0
- th-abstraction-0.4.2.0
- th-compat-0.1.2
- th-expand-syns-0.4.8.0
- th-lift-0.8.2
- th-lift-instances-0.1.18
- th-reify-many-0.1.9
- these-1.1.1.1
- time-1.9.3
- time-compat-1.9.6
- tls-1.5.5
- transformers-0.5.6.2
- transformers-base-0.4.5.2
- transformers-compat-0.6.6
- typed-process-0.2.6.0
- unicode-transforms-0.3.7.1
- unix-2.7.2.2
- unix-compat-0.5.3
- unix-time-0.4.7
- unliftio-0.2.19
- unliftio-core-0.2.0.1
- unordered-containers-0.2.14.0
- uuid-types-1.0.5
- vector-0.12.3.0
- vector-algorithms-0.8.0.4
- x509-1.7.5
- x509-store-1.6.7
- x509-system-1.6.6
- x509-validation-1.6.11
- yaml-0.11.5.0
- zip-archive-0.4.1
- zlib-0.6.2.3

Warning: this is an unsupported build that may use different versions of
dependencies and GHC than the officially released binaries, and therefore may
not behave identically.  If you encounter problems, please try the latest
official build by running 'stack upgrade --force-download'.
```

### Method of installation

* Installed via brew following these instructions https://medium.com/@dogwith1eye/setting-up-haskell-in-vs-code-with-stack-and-the-ide-engine-81d49eda3ecf

### Question 
When running "stack build" I'm getting the following error:

"I don't know how to install GHC for (OSX,AArch64), please install manually"

I'm new to the ecosystem. What's the best way to resolve this?

I'm on macOS Big Sur (Version 11) Chip: Apple M1

**Comment by hasufell** [comment]
What project are you trying to build and which GHC version does it require?

Currently only `[ 8.10.5, 8.10.6, 8.10.7 ]` are supported:

https://github.com/commercialhaskell/stackage-content/blob/1db7075d057ad109494939e13951418e2a3b3b23/stack/stack-setup-2.yaml#L1428-L1446

**Comment by supermario** [comment]
Ran into this issue as well. 

Looks like potentially install support was only added recently, and isn't yet in a released version of stack?

https://github.com/commercialhaskell/stack/commit/708b516a8d34cc42b6c533d161b18b31f913c3d6

**Comment by supermario** [comment]
Can confirm after having built `stack` from master:
```
$ ~/.local/bin/stack --version
Version 2.7.4, Git revision 708b516a8d34cc42b6c533d161b18b31f913c3d6 (8381 commits) RELEASE-CANDIDATE x86_64
```

And adding `arch: aarch64` to `stack.yml` to force things (given `stack` seems to select the arch automatically based on the architecture the `stack` binary itself is built with), I no longer get the `I don't know how to install GHC for (OSX,AArch64)` error:

```
$ ~/.local/bin/stack install
Preparing to install GHC to an isolated location.
This will not interfere with any system-level installation.
Downloaded ghc-8.10.7.
Unpacking GHC into /Users/mario/.stack/programs/aarch64-osx/ghc-8.10.7.temp/ ...
                                                ^^^^^^^^^^^
```

**Comment by supermario** [comment]
Having issues building anything on M1 with the new stack despite managing to skirt the original issue.

Looks like the conversation here on the PR related to that commit is relevant (sorry, I tried but couldn't find it at first):

https://github.com/commercialhaskell/stack/pull/5562#issuecomment-913015550

Was interested in M1 build for potentially faster build times but seems that's not the case 😬

**Comment by banditpig** [comment]
Hi, What's the latest on this? 
I have Apple M1 Max running Monterey.
stack 2.7.3
ghc 8.10.7 
And doing 
stack ghci 
gives 
"I don't know how to install GHC for (OSX,AArch64), please install manually."

Is there a workaround? Is there anything I could do to help test?
Thanks

**Comment by stackptr** [comment]
I use a wrapper script as a workaround, described here, adding to it options to hard-code `ghc`: https://github.com/commercialhaskell/stack/issues/5607#issuecomment-964435812

Since I mainly work on one project, I've added `--compiler ghc-8.10.7 --system-ghc` to that wrapper

**Comment by banditpig** [comment]
Thanks! I’ll try that.

**Comment by banditpig** [comment]
> 

I couldn't get it to work. 
What I have done is, in .stack/config.yaml        add line  arch: x86_64
this forces use of Rosetta and it works ok.

**Comment by plajjan** [comment]
Newer versions of stack is able to install ghc for aarch64. You can install it using `brew install --HEAD stack`.

**Comment by banditpig** [comment]
Thanks but I tried that and  'cabal v2-install --jobs=8... ' hung.

**Comment by banditpig** [comment]
I was too impatient! It took 20 minutes on i7 Macbook. Running it now on M1.

**Comment by hasufell** [comment]
I added M1 stack binaries to ghcup: https://github.com/haskell/ghcup-metadata/commit/176d619b1f847d452a2149e24e3ef9ac13f42d77

These are unofficial and experimental. They were built on [gitlab GHC CI](https://gitlab.haskell.org/maerwald/stack/-/pipelines/44275)... I wasn't able to make all tests pass, probably because the environment is different than stack CI.

**Comment by MeragNokhiz** [comment]
Hi @hasufell, could you please help me to find the gchiup file to update it? I can't find it and try to solve the issue with 
> I don't know how to install GHC for (OSX,AArch64), please install manually
I'm know 2 days on the same issue and don't know how to solve it... : /
Wenn du mir helfen könntest wär ich dir sehr dankbar ; )
Thanks a lot in advanced. Meer

**Comment by hasufell** [comment]
>  Hi @hasufell, could you please help me to find the gchiup file to update it? I can't find it and try to solve the issue with 
> I don't know how to install GHC for (OSX,AArch64), please install manually
> I'm know 2 days on the same issue and don't know how to solve it... : /
> Wenn du mir helfen könntest wär ich dir sehr dankbar ; )
> Thanks a lot in advanced. Meer

I'm not sure what you're asking. ghcup is a toolchain installer and an unofficial method to install stack.

Follow https://www.haskell.org/ghcup/install/

**Comment by MeragNokhiz** [comment]
@hasufell - I installed it and tried now with "cabal" and not "stack" - its working pretty fine! 
Thanks Julian!
