### ISSUE TITLE
How can I specify the destination for `stack new` command?

### ISSUE THREAD

**Issue by kongxiangyan** [commercialhaskell/stack#5618]
### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

### Question

I want to specify the destination for `stack new`. It should work as CLI's help of `stack new` command said:

```plain
Usage: stack.exe new PACKAGE_NAME [--bare] [TEMPLATE_NAME] 
                     [-p|--param KEY:VALUE] [DIR] ...

Available options:
  ...
  DIR                      Directories to include, default is current directory.
  ...

where ... is just omit
``` 

For project "hello", when I execute `stack new hello new-template ./package/` which `./package` is `[DIR]` option for `stack new` command, the result folder "hello" is expected to be placed to `./package/hello`. In fact it's just lay on `./hello`.

Both relative and absolute `DIR` has been tried, nor of them works.  

If there is a misunderstanding of that command option description, or is an unexpected bug?

**Comment by mpilgrem** [comment]
The `DIR` parameter of `stack new` is the same parameter as that of `stack init` and is a list of directories to include in the search for `.cabal` files. Presently, you cannot specify a location of the new package root directory. The `--help` documentation of `stack new` could be improved.
