### ISSUE TITLE
How do I submit binaries for Stack aarch64?

### ISSUE THREAD

**Issue by ProofOfKeags** [commercialhaskell/stack#5619]
I have spent a painfully long time compiling stack for RPi4 aarch64 and would like to save others from the pain of having to do the same. I cut an issue against [ghcup](https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/230) to add binaries for this but the maintainers don't want to distribute unofficial binaries. How can the community support aarch64 in a way that is cosigned/endorsed by the stack team?

**Comment by hasufell** [comment]
As a sidenote: the stack team is welcome to use the GHC gitlab instance to produce aarch64 binaries (there is CI for linux and mac). @bgamari has expressed this in a HF meeting too afair.

**Comment by juergenpf** [comment]
Any way to share that binary on one of your own repositories or somehow privately? I started building stack on a 64bit aarch64 Debian myself and began to feel it will be some effort.

**Comment by mpilgrem** [comment]
I think this has been overtaken by this repository providing Linux/Aarch64 binaries for Stack 2.9.1 and 2.9.3.
