### ISSUE TITLE
remove ghc tar file after ghc install

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#562]
Is there any reason to keep these around?

```
➜  .stack  cd ~/.stack
➜  .stack  find ./ -name '*tar.xz'
./programs/x86_64-linux/ghc-7.8.4.tar.xz
./programs/x86_64-linux/ghc-7.10.1.tar.xz
```

**Comment by snoyberg** [comment]
Yes, it's kept on purpose:

1. It's a nice safety hatch in case the installed GHC gets corrupted somehow (certainly possible, especially with all of this work happening recently with `cabal configure --package-db=...`)
2. It's convenient for running tests which reinstall GHC regularly
3. The file size is a fraction of the installed GHC, so it's not adding that much weight

**Comment by gregwebs** [comment]
Makes sense although 2) isn't a good reason to make this a default. One option could be to print out the location of the tar.xz file, making it very easy to delete it then if someone is inclined.

**Comment by snoyberg** [comment]
That's the kind of thing I'm hoping the stack rm/stack purge/stack whatever
command makes trivial. You OK with closing this issue then?

**Comment by gregwebs** [comment]
Yes. Is there an issue # for the purge command?

**Comment by snoyberg** [comment]
Yes https://github.com/commercialhaskell/stack/issues/133
