### ISSUE TITLE
can I put config.yaml under ~/.config/stack??

### ISSUE THREAD

**Issue by molleweide** [commercialhaskell/stack#5623]
I am a newbie to stack and I want to ask if I can put stack global config under `~/.config/stack`

**Comment by mpilgrem** [comment]
The short answer, in 2023 and with Stack 2.9.3, is yes, see https://docs.haskellstack.org/en/stable/yaml_configuration/ and what it says under the 'XDG Base Directory Specification'. See also: https://docs.haskellstack.org/en/stable/environment_variables/#stack_xdg.
