### ISSUE TITLE
Stack doesn't check if the compiler has changed when it already has one cached for a variant+version combo

### ISSUE THREAD

**Issue by googleson78** [commercialhaskell/stack#5625]
### General summary/comments
We're building our own "integer-simple" ghc (no gmp linking), because we can't link to GPLd libraries.

What happened is that I accidentally built a ghc 9.0.1 **with** gmp enabled, uploaded it to our ftp, and then ran a build with it.
Afterwards, realising my mistake, I fixed it, and did the same with an "integer-simple" ghc 9.0.1. 

However, my binaries were still being linked to `libgmp`.

After deleting my global `~/.stack` folder, this problem no longer occurred. My hypothesis is that as long as the variant and version are the same, stack does not check whether the compiler that is specified in my `stack.yaml`s `setup-info` matches the compiler that is cached on my system. My suspicion is further reinforced by me trying to use the "correct" `stack.yaml` on a builder that had the "wrong" compiler cached, and still getting the `libgmp` linked binary.
### Steps to reproduce
0. Add a custom compiler to use in your stack.yaml.
1. Build with it.
2. Change the custom compiler you're using (along with the hash of course), without changing the variant or version of the compiler.

### Expected

`stack` uses the compiler added in 2.

### Actual

`stack` still uses the compiler added in 0. and cached in 1.

### Stack version

```
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation
* `stack upgrade`

**Comment by qrilka** [comment]
@googleson78 could you explan "along with the hash" in your words? As of now Stack relies on output from `ghc --info` being unique across GHC versions and it uses it as a part of "source map hash" - see https://github.com/commercialhaskell/stack/blob/255cd830627870cdef34b5e54d670ef07882523e/src/Stack/Build/Source.hs#L118

**Comment by googleson78** [comment]
This part from my `stack.yaml`, which includes a hash of the archive on my ftp:
```yaml
setup-info:
  ghc:
    linux64-integersimple:
      9.0.1:
        url: <ftp-url>/ghc-9.0.1-x86_64-unknown-linux.tar.xz
        sha1: 9a68c3b366b4555b81c2a33a8197c5a38d18f6fa
```

**Comment by googleson78** [comment]
What I would expect is that `stack` checks whether the `sha1` given in the `stack.yaml` is checked against the `sha1` for the currently cached compiler I have on my system. (or something of this sort)

**Comment by qrilka** [comment]
I'm not that familiar with the logic of setting up GHC from source but I guess it just uses the version for paths so you'll get the same path here https://github.com/commercialhaskell/stack/blob/255cd830627870cdef34b5e54d670ef07882523e/src/Stack/Build/Source.hs#L144 for any SHA you provide.
You could check  the logic in https://github.com/commercialhaskell/stack/blob/255cd830627870cdef34b5e54d670ef07882523e/src/Stack/Setup.hs#L810

**Comment by googleson78** [comment]
Sorry if I'm misunderstanding what you're saying, but I'm not setting up stack to build ghc from source for me - I've already built the ghc myself, and uploaded it somewhere, and am just telling stack to use the archive that I've uploaded.

**Comment by qrilka** [comment]
Sorry, that was a wrong link, sure, you've got a bindist and in that case you'll get a fixed path at https://github.com/commercialhaskell/stack/blob/255cd830627870cdef34b5e54d670ef07882523e/src/Stack/Setup.hs#L1155
The only workaround could be a different version name or different output from `ghc --info`.
It's not clear to me if it's in the scope of Stack to take into account cases when user provides not quite correct bindist URL.

**Comment by googleson78** [comment]
I don't understand what you mean by "not quite correct bindist URL"s. Could you elaborate?

**Comment by qrilka** [comment]
> accidentally built a ghc 9.0.1 with gmp enabled
So practically you've supplied gmp bindist as integersimple. I don't know all the details but I think Stack doesn't track what "linux64-integersimple" means, it could use bindist SHAs in theory but I guess just dropping incorrect GHC is good enough workaround (though I'm not sure if that's easily doable without dropping all of ~/.stack)

**Comment by googleson78** [comment]
I agree that the fix is easy (locally on your machine), but it can easily be annoying for builders. 

Anyway, my issue is with the fact that this event is hard to detect - your build will just finish successfully, with little indication of it using a cached compiler instead of the one you want.

On Linux, you can check this easily with `ldd` (if you remember to do so!) but gmp is linked statically under windows, meaning you have no way to check it, unless you want to do some code audit.

**Comment by dtaskoff** [comment]
I couldn't understand the conversation above, but I'd really like to know why stack doesn't check if the currently installed ghc matches the one specified in stack.yaml (or wherever it has been specified).

This means, that the only guarantee that you're using the compiler you want, is to delete the .stack directory, and start from scratch, which is completely crazy, and unhandy.

**Comment by dtaskoff** [comment]
I don't get what does `ghc --info` has to do with this. I asked why stack doesn't check if the installed GHC matches the one specified in stack.yaml, e.g. checks if the currently installed GHC is the one specified in stack.yaml (in other words, if the GHC is downloaded from a specific `url`, and is having a specific `sha1` (and possibly `content-length`).

You can see the fields I'm talking about in [this stack setup file](https://raw.githubusercontent.com/commercialhaskell/stackage-content/master/stack/stack-setup-2.yaml), for example.

```yaml
ghc:
    linux32:
        7.8.4:
            url: "https://github.com/commercialhaskell/ghc/releases/download/ghc-7.8.4-release/ghc-7.8.4-i386-unknown-linux-deb7-patch1.tar.xz"
            content-length: 79802784
            sha1: 476c1ab647bb748e4e4e9ecd7270df08c1e02b8b
 ```

**Comment by googleson78** [comment]
This seems even more relevant, [now that ghc won't display what bignum it's using in `ghc --info`](https://github.com/ghc/ghc/commit/79a26df1475505ee1e87eb7fda04e5fefdf6aa4c).

**Comment by mpilgrem** [comment]
Once Stack has obtained and installed a requested version/build of GHC (eg `x86_64-windows/ghc-9.10.0.20240328`), the [`programs` directory](https://docs.haskellstack.org/en/stable/stack_root/#programs-directory) will include a file marking that version/build of GHC as installed. If that marker is present, Stack does not reinstall that version/build of GHC and does not need to consult the `setup-info` dictionary.

Stack's Haddock documentation includes:
~~~haskell
-- Basic rules:
--
-- * If someone modifies a GHC installation in any way after Stack looks at it,
--   they voided the warranty. This includes installing a brand new build to the
--   same directory, or registering new packages to the global database.
--
~~~

That is, Stack assumes that a version/build of GHC that it has installed is immutable.
