### ISSUE TITLE
Stack installer on Windows doesn't launch (error 0xc000007c) with ASLR enabled

### ISSUE THREAD

**Issue by vlj** [commercialhaskell/stack#5626]
### General summary/comments (optional)

Since a couple month I can't run the Haskell Stack installer, using the exe for github page or winget cli.
The error message is 0xc000007c.

It appears that NSIS (which is used to package haskell on Windows) can trigger this error if some embedded DLLs fail to load. It turns out that for some reason NSIS own DLLs don't load if Adress Space Layout Randomisation is enabled on the system.
It seems that there is a flag that needs to be passed at compile time (/DYNAMICBASE ) when building NSIS, I suspect the NSIS binary used to package Stack wasn't build with this flag.

I disabled ASLR to check and indeed it fixes the issue.

### Steps to reproduce

With Windows 11 (but maybe with Windows 10 too) : 
- download stack-2.7.3-windows-x86_64-installer.exe from haskell stack website.
- Try to launch it with Address Space Layout Randomisation enabled (see https://techcommunity.microsoft.com/t5/windows-security/turn-on-mandatory-aslr-in-windows-security/m-p/1186989)

### Expected

Installation should happen even if ASLR is enabled.

### Actual

Error message 0xc000007c if ASLR is enabled.
It works correctly if ASLR is disabled.

### Stack version

2.7.3

### Method of installation

Via https://get.haskellstack.org/stable/windows-x86_64-installer.exe and/or winget cli.

**Comment by mpilgrem** [comment]
This: https://nsis.sourceforge.io/Docs/AppendixF.html#v3.08 suggests that the NSIS ASLR bug was fixed in NSIS version 3.03, released in January 2018. The command `makensis /VERSION` reports the version (eg `v3.08`). I am thinking: perhaps the `stack` installer scripts could be updated to check, and warn, for that.

**Comment by mpilgrem** [comment]
I have updated the GitHub Actions workflow `integration-tests.yml` to use the Github-supplied NSIS 3.08, which I think should fix this in future releases of Stack.
