### ISSUE TITLE
profiling is not working

### ISSUE THREAD

**Issue by yaitskov** [commercialhaskell/stack#5627]
$ stack new prof 
    $ cd prof
    $ stack build --profile --executable-profiling --library-profiling 
    $ stack exec prof-exe +RTS -p
    stack: the flag -p requires the program to be built with -prof

    $ stack --version
    Version 2.7.1, Git revision 8afe0c2932716b0441cf4440d6942c59568b6b19 x86_64 hpack-0.34.4

ghc 8.10.7

**Comment by hasufell** [comment]
```sh
stack exec --profile --executable-profiling --library-profiling prof-exe -- +RTS -p
```

You're not invoking correctly... you're trying to start stack itself with `+RTS -p`.
