### ISSUE TITLE
ghc installation failure on macOS 

### ISSUE THREAD

**Issue by Pranay0302** [commercialhaskell/stack#5632]
### General Summary

Error encountered while installing ghc 

### Steps to reproduce

* ```stack setup```
* wait for the error

### Expected

The setup to be installed properly

### Actual
```
$ stack setup  --verbose
```

output: [stack.op.txt.gz](https://github.com/commercialhaskell/stack/files/7492055/stack.op.txt.gz)

### Stack version

```
❯ stack --version
Version 2.7.3 x86_64
```

### Method of installation

* **stack** was installed using homebrew

### Component

MacOS Catalina v10.15.5

**Comment by peterbecich** [comment]
Is this an M1 Mac?

**Comment by cmal** [comment]
Hi, how to build from source on M1 Mac? @peterbecich

**Comment by peterbecich** [comment]
@cmal , possibly this:
#5617 
This looks promising:
https://github.com/commercialhaskell/stack/issues/5617#issuecomment-975308723

I haven't done this myself.
