### ISSUE TITLE
stack unable to fetch ghc from downloads.haskell.org

### ISSUE THREAD

**Issue by senorhesles** [commercialhaskell/stack#5635]
### General summary/comments (optional)

installing the stack binary succeeds, but fetching ghc fails

### Steps to reproduce

For example:

1. Install stack: `curl -sSL https://get.haskellstack.org/ | sh`
2. Try to launch ghci: `stack ghci`

### Expected

ghc is fetched and ghci is executed by stack wrapper

### Actual

```
mario@10:14:05:[~]$ stack ghci
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
Preparing to download ghc-tinfo6-8.10.7 ...
Download expectation failure: HttpExceptionRequest Request {
  host                 = "downloads.haskell.org"
  port                 = 80
  secure               = False
  requestHeaders       = [("User-Agent","The Haskell Stack")]
  path                 = "/~ghc/8.10.7/ghc-8.10.7-x86_64-fedora27-linux.tar.xz"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 ConnectionTimeout
```

### Stack version

Running Fedora 35 and with linux kernel version: `5.14.14-300.fc35.x86_64`

```
mario@10:14:37:[~]$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

```
curl -sSL https://get.haskellstack.org/ | sh
```

**Comment by senorhesles** [comment]
Disabling ipv6 "fixes" it.

**Comment by ketzacoatl** [comment]
That would mean the downloads.haskell.org isn't supporting ipv6.

**Comment by mpilgrem** [comment]
This appears to me to be an issue with downloads.haskell.org. I do not know where it should be raised, but @bgamari (who announces new versions of GHC to the [Haskell Community](https://discourse.haskell.org/t/ghc-9-4-1-is-now-available/4901) might know.
