### ISSUE TITLE
Custom list of global libraries ?

### ISSUE THREAD

**Issue by ylecornec** [commercialhaskell/stack#5638]
In [rules_haskell](https://github.com/tweag/rules_haskell), we make use of the `stack ls dependencies json --global-hints` command and are currently working on supporting the [asterius compiler](https://github.com/tweag/asterius) that has different global libraries than ghc.

So we are wondering about the best way to go about this.

For instance, is there a way to specify a custom list of global libraries (such as the one from the [global-hints.yaml](https://github.com/commercialhaskell/stackage-content/blob/53fe1b07907cc16374166bab681cf32beb783625/stack/global-hints.yaml) file)?

Here is what we do at the moment: 
- For packages provided by ghc but not asterius: we add them explicitly to the `packages` field of a custom stack snapshot.
- For packages provided by asterius but not ghc: we add them as local packages in the `packages` field of the `stack.yaml` file, but this requires creating dummy `.cabal` files for these.

This seems to work (the libraries without a `location`field in the resulting json are the right ones) but maybe there is a better way ?

### Stack version

```
$ stack --version
2.7.3 x86_64 hpack-0.34.4
```

### Method of installation

Via nixpkgs.

**Comment by mpilgrem** [comment]
@ylecornec, has your immediate need passed, with the deprecation of Asterius in favour of an enhanced GHC? On your question, currently the `global-hints.yaml` URL is hard-coded in the `pantry` library. I'll raise an issue there.
