### ISSUE TITLE
Windows installer does not register stack version

### ISSUE THREAD

**Issue by andyliuhaowen** [commercialhaskell/stack#5643]
### General summary/comments (optional)

With Windows Package Installer (winget), a package needs to register its version with Windows. Otherwise winget constantly thinks that there is an upgrade.

```
PS > winget upgrade
Name                                             Id                                Version        Available      Source
-----------------------------------------------------------------------------------------------------------------------
Haskell Stack                                    commercialhaskell.stack           Unknown        2.7.3          winget
```

I realize that this is not a stack issue specifically and that you guys owe us users nothing (we owe you guys for the work and awesome product). If somebody can give me a pointer to how the windows installer is currently packaged (I can't find it...), I can go fix it through a PR.

### Steps to reproduce

Install stack. Go to Control panel -> Programs and Features. Look for Haskell Stack.

### Expected

Windows should recognize Stack's version.

### Actual

No version is registered.

### Stack version

```
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by Elewyth** [comment]
I think the key `DisplayVersion` needs to be added to this script: https://github.com/commercialhaskell/stack/blob/master/etc/scripts/build-stack-installer.hs.

See https://github.com/microsoft/winget-cli/issues/1255#issuecomment-902873661 for more information. Unfortunately, I'm not sure how to retrieve the version number. I think it needs to be passed as an argument to the `build-stack-installer.hs` script from https://github.com/commercialhaskell/stack/blob/master/etc/scripts/release.hs. But I couldn't figure out more, just yet.

**Comment by Elewyth** [comment]
Added PR #5660 adding `DisplayVersion`, which enables `winget` to properly read the installed version.
