### ISSUE TITLE
stack build cardano wallet times out

### ISSUE THREAD

**Issue by heath33** [commercialhaskell/stack#5654]
Following guide here: https://developers.cardano.org/docs/get-started/installing-cardano-wallet/#macos--linux

Getting a Connection Timeout.  

Issuing command: > stack build --test --no-run-tests

![image](https://user-images.githubusercontent.com/20148458/146653272-1a2ef9d2-937e-4ca1-b182-daea5ce2d5b7.png)

**Comment by ketzacoatl** [comment]
@heath33 is this persistent?
