### ISSUE TITLE
Windows Defender flags cabal as malware - can I verify this?

### ISSUE THREAD

**Issue by felixlinker** [commercialhaskell/stack#5656]
Windows defender flagged a cabal version which I installed today as potential malware:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/9728715/146779033-6c0cb124-74ce-4ff6-bc55-35feae4d0807.png">

Translation:
> Recognized: PUA:Win32/Pearfoos.A!ml
> Status: active
> To install this potentially unwanted app anyways, chhose "Actions" and "Allow on this device" and start another installation.

The date of installing this version coincides with me using stack/haskell-language server so I suspect this is a false positive. Is there any way, though, I could verify my cabal installation?

### Stack version

```
PS C:\Users\felix> stack --version
Version 2.3.3, Git revision cb44d51bed48b723a5deb08c3348c0b3ccfc437e x86_64 hpack-0.33.0
```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mpilgrem** [comment]
#5661 reported a similar issue with Windows Defender, but I've not seen any other reports. I strongly suspect it is a false positive.

In respect of your question (is it possible to verify the `Cabal-simple_[hash]_[version]_ghc-[version].exe`?), that `.exe` does not 'ship with' `stack.exe` but is built by `stack.exe` when it runs. The source code for the `.exe` is 'hard coded' in the source code of `stack.exe` (it is at `Stack.Build.Execute.simpleSetupCode` - a two-line program) and copied into `C:\sr\setup-exe-src`. What you could do is delete folders `C:\sr\setup-exe-cache` and `C:\sr\setup-exe-src` - `stack` will just rebuild them, the next time it is run.
