### ISSUE TITLE
Stack crashes when stack root is set to a mounted network drive

### ISSUE THREAD

**Issue by mnn** [commercialhaskell/stack#5665]
### Steps to reproduce

1. run `stack test` with `STACK_ROOT` or `--stack-root` set to a mounted network drive

### Expected

It uses the directory and doesn't crash.

### Actual

<img width="805" alt="2022-01-03_20-16" src="https://user-images.githubusercontent.com/1975567/147970493-c046ae8d-588f-4237-b283-2582481e6e9f.png">

It does have access to it (running `ls` from the host machine, stack created those files):

```
<> ls
config.yaml  pantry  snapshots  stack.sqlite3  stack.sqlite3.pantry-write-lock
```

### Stack version

2.7.3

### Method of installation

* Official binary, the Windows installer

**Comment by hasufell** [comment]
That is GHC failing, not stack.

**Comment by mnn** [comment]
I don't know whether its on Stack or GHC. I don't know enough about either, nor about for example how Windows are handling paths. Like is it alright for Stack to convert path `z:\stack-cache` it `\\VBOXSVR\...`?

I noticed the GHC version was a bit old, so I tried setting project to the latest LTS from stackage, and it didn't even got to running the GHC (at least I think).

<img width="561" alt="2022-01-05_19-59" src="https://user-images.githubusercontent.com/1975567/148273670-fed2b553-5e73-4e01-8835-4a393706814d.png">

From the error message I have no idea what could go wrong this time...

**Comment by mnn** [comment]
After extending a system partition, it crashes with a different error (probably related to GHC and not Stack). The error with network drive was either fixed by upgrading GHC or freeing more space. Either way this error is fixed for me, so I'll close this.
