### ISSUE TITLE
Should www.haskell.org advertise Stack as working on FreeBSD?

### ISSUE THREAD

**Issue by tomjaguarpaw** [commercialhaskell/stack#5674]
I am a maintainer of www.haskell.org (and Haskell.org committee member). The [haskell.org downloads page](https://www.haskell.org/downloads/) advertises installation instructions for Stack. I would like to make it clear which platforms it supports. [ghcup](https://www.haskell.org/ghcup/#) explicitly mentions that it supports FreeBSD. Does Stack also? I can't work it out from [the Stack installation page](https://docs.haskellstack.org/en/stable/install_and_upgrade/). It doesn't mention FreeBSD explicitly but it does say "For common Un*x operating systems". Please let me know whether Stack supports FreeBSD and I will make it clear on the downloads page. Thanks.

**Comment by hasufell** [comment]
The stack installer at least doesn't:

```
$ curl -sSL https://get.haskellstack.org/ | sh
Sorry, this installer does not support your operating system: FreeBSD.
See http://docs.haskellstack.org/en/stable/install_and_upgrade/
```

Building stack on FreeBSD is working [fine](https://gitlab.haskell.org/maerwald/stack/-/jobs/757049) and ghcup supports installing stack on FreeBSD via [unofficial binaries](https://github.com/haskell/ghcup-metadata/blob/1dea46b148f13e0fbee7530a1f9cf336a9c1e2b3/ghcup-0.0.6.yaml#L2920-L2923), because there are [no official ones](https://github.com/commercialhaskell/stack/releases/tag/v2.7.3).

**Comment by tomjaguarpaw** [comment]
It looks like the answer is "no, www.haskell.org shouldn't advertise Stack as working on FreeBSD". Unless any of the Stack team have any clarification to make I will action that by adding a caveat to the Stack section of the [downloads](https://www.haskell.org/downloads/) page, or similar.

**Comment by tomjaguarpaw** [comment]
Done: https://github.com/haskell-infra/www.haskell.org/pull/171

**Comment by tomjaguarpaw** [comment]
[Gleb Popov reports on haskell-cafe](https://mail.haskell.org/pipermail/haskell-cafe/2022-April/135186.html) that indeed Stack works on FreeBSD.

Stack maintainers, could you please clarify what you want the [haskell.org downloads page](https://www.haskell.org/downloads/) to say regarding Stack support for FreeBSD? The link we provide on that page is to <https://docs.haskellstack.org/en/stable/install_and_upgrade/> but it doesn't mention FreeBSD support and, as @hasufell reports, the headline installation method (`curl | sh`) doesn't work on FreeBSD. How are FreeBSD users supposed to install stack?

**Comment by hasufell** [comment]
> How are FreeBSD users supposed to install stack

Currently, for both FreeBSD and darwin M1 users, ghcup provides unofficial binaries that are built on GHC gitlab CI, which supports those architectures/platforms.

**Comment by arrowd** [comment]
> How are FreeBSD users supposed to install stack?

I'm maintaining FreeBSD port for it, so it is just `pkg install hs-stack`.

**Comment by tomjaguarpaw** [comment]
That's good to know, thanks. Is this an officially supported installation method? Currently on [the Downloads page](https://www.haskell.org/downloads/) we say

> To install stack, follow the instructions [here](https://docs.haskellstack.org/en/stable/install_and_upgrade/)

But that doesn't mention FreeBSD at all, so I guess it is not officially supported by the Stack team. How should we include the `pkg install hs-stack` information onto the Downloads page?

**Comment by arrowd** [comment]
Well, this is an official binary package produced by the FreeBSD package building cluster. I'd say it is a preferred method, yes, because I always prefer distribution packages over upstream binaries.

**Comment by hasufell** [comment]
> Well, this is an official binary package produced by the FreeBSD package building cluster. 

Do you run the entire GHC testsuite?

**Comment by arrowd** [comment]
As part of the build - no. Periodically - yes.

**Comment by tomjaguarpaw** [comment]
OK, thank you @arrowd, I now understand the status of Stack on FreeBSD. Let us therefore migrate to https://github.com/haskell-infra/www.haskell.org/issues/190.
