### ISSUE TITLE
Throws clang error while building executable on Apple M1

### ISSUE THREAD

**Issue by aravindgopall** [commercialhaskell/stack#5676]
Please follow the steps below for reporting a bug:

### General summary/comments (optional)
When building a repo (private) using the latest master branch on Apple M1 throws the clang error. stack is installed following https://github.com/commercialhaskell/stack/issues/5607 from master branch.

### Steps to reproduce

For example:

1. ~/.local/build/stack build

### Expected

Build successfully
### Actual

Throws clang error 

clang: error: unable to execute command: Segmentation fault: 11
clang: error: linker command failed due to signal (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 254)

### Stack version

```
% ~/.local/bin/stack --version
Version 2.7.4, Git revision 708b516a8d34cc42b6c533d161b18b31f913c3d6 (dirty) (8381 commits) RELEASE-CANDIDATE aarch64
```

### Method of installation

* Manually build latest master branch.

**Comment by aravindgopall** [comment]
It's a web server using following dependencies:

    - aeson
    - basic-prelude
    - base >= 4.7 && < 5
    - base16-bytestring
    - base64-bytestring
    - beam-core
    - beam-postgres
    - bytestring
    - case-insensitive
    - containers
    - cryptonite
    - cryptostore
    - data-default
    - directory
    - dlist
    - errors >= 2.3.0
    - euler-hs
    - extra
    - hashmap
    - hedis
    - http-api-data
    - http-client
    - http-client-tls
    - http-reverse-proxy
    - http-media
    - http-types
    - jwt
    - lens
    - lens-aeson
    - memory
    - pickle
    - postgresql-simple
    - prometheus-client
    - wai-middleware-prometheus
    - random
    - regex-compat
    - regex-tdfa
    - resource-pool
    - scientific
    - servant
    - servant-client
    - servant-client-core
    - servant-server
    - servant-xml
    - stm
    - string-conversions
    - servant-errors
    - text
    - time >= 1.9.3
    - unix
    - unordered-containers
    - uri-encode
    - utf8-string
    - uuid
    - validation
    - vault >= 0.3
    - vector
    - wai >= 3.2.2.1
    - warp
    - warp-tls
    - word8
    - x509
    - xmlbf
    - xmlbf-xeno
    - hxt
    - hsaml2
    - connection

**Comment by mpilgrem** [comment]
I am going to close this due to the passage of time, the current Stack version being 2.15.1, and no other user reporting similar problems on macOS/AArch64.
