### ISSUE TITLE
stack build --enable-tests

### ISSUE THREAD

**Issue by dbp** [commercialhaskell/stack#568]
I'm using stack for a project, and having it run the test suite on CircleCI (the config file is here, if anyone else wants it: https://gist.github.com/dbp/bef96402ea07001dfed2).

One issue is that the caching mechanism runs before the test suite runs. This generally makes sense, but it is a problem with how stack handles test suites. In particular, `stack build` doesn't install libraries needed for the test suite, only `stack test` does. 

Is there a way to install test dependencies without running the test suite?

**Comment by snoyberg** [comment]
There's stack test --no-run-tests, which should do what you want.

**Comment by dbp** [comment]
@snoyberg  Was that added since 1.2.0? It isn't recognized as a command for me (and isn't in the options printed by `stack test --help`)

**Comment by snoyberg** [comment]
Yes. stack lives deeply on the bleeding edge :). See #517 for when this was added.

**Comment by dbp** [comment]
Ahh, I see. I'll look out for it in the next release :) Overall, stack is great!

**Comment by snoyberg** [comment]
Thanks!
