### ISSUE TITLE
Use Hackage only instead of Stackage

### ISSUE THREAD

**Issue by pxeger** [commercialhaskell/stack#5685]
```bash
$ stack --version
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

Installed with ghcup.

I want to use GHC 9.2 with Stack. However, Stackage doesn't yet support this version, even on nightly (see [commercialhaskell/stackage#6318](https://github.com/commercialhaskell/stackage/pull/6318)). But Stack itself seems to support 9.2, so I'd like to know if it's possible to use stack without using Stackage at all, so I can just install packages directly from Hackage. Is this currently possible, or does this issue need to be a feature request?

**Comment by hasufell** [comment]
stack doesn't have a dependency resolver, so using hackage directly will likely not work well, because package bounds won't be respected.

**Comment by pxeger** [comment]
Ah, I see. I guess I should just use cabal on its own then?

**Comment by hasufell** [comment]
> Ah, I see. I guess I should just use cabal on its own then?

If you care about hackage support, that's the best option. Otherwise try stackage nightly: https://www.stackage.org/nightly

**Comment by mbj** [comment]
You can overwrite the GHC in a per `stack.yaml` basis via: `compiler: ghc-9.2.1` and force `stack` to use any GHC with any snapshot.

I've got some success on nightly already.
