### ISSUE TITLE
mysql compile fails

### ISSUE THREAD

**Issue by jelmd** [commercialhaskell/stack#5688]
### General summary/comments (optional)
Unable to use mysql because stack fails to compile it. Errors out with:
```
...
    [2 of 2] Compiling StackSetupShim   ( /export/scratch/elkner/build/.stack/setup-exe-src/setup-shim-mPHDZzAJ.hs, /tmp/stack109257/mysql-0.1.4/.stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/setup/StackSetupShim.o )
    Linking /tmp/stack109257/mysql-0.1.4/.stack-work/dist/x86_64-linux-tinfo6-nopie/Cabal-1.24.2.0/setup/setup ...
    Configuring mysql-0.1.4...
    Preprocessing library for mysql-0.1.4..
    In file included from C.hsc:73:
    /tmp/stack109257/mysql-0.1.4/include/mysql_signals.h:23:1: error: unknown type name 'my_bool'; did you mean 'bool'?
       23 | my_bool STDCALL _hs_mysql_commit(MYSQL * mysql);
          | ^~~~~~~
          | bool
    /tmp/stack109257/mysql-0.1.4/include/mysql_signals.h:24:1: error: unknown type name 'my_bool'; did you mean 'bool'?
...
```

The reason is probably because of https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-1.html#mysqld-8-0-1-compiling.

### Steps to reproduce
1. git clone https://github.com/spechub/Hets.git
2. cd Hets
3. sed -i -e '/mysql:/ s/false/true/' stack.yml
4. make restack
5. (or try to build: `make hets_server`)

### Expected

Anything should compile without errors.

### Actual

Stack is unable to build the software.

### Stack version

```
Version 2.7.3, Git revision 7927a3aec32e2b2e5e4fb5be76d0d50eddcc197f x86_64 hpack-0.34.4
```

### Method of installation
As documented: download stack, extract the binary, do a `stack setup`.

**Comment by sjakobi** [comment]
@jelmd The MySQL changes you linked to were released _after_ `mysql-0.1.4` was uploaded to Hackage. Of course it's not compatible! Try using a more recent version of `mysql`.

In any case, this is the wrong forum to discuss your issue.

**Comment by jelmd** [comment]
@sjakobi Spent almost a whole day to find one, but each time stack comes up with 1+ other unmatched dependencies, at some point even with cyclic dependency errors. It is a real nightmare.

Isn't there a hook one may use to intercept the build, i.e. add a patch or simply do a `sed -i -e 's/my_bool/bool/ $file` to get it build?

**Comment by sjakobi** [comment]
@jelmd You can specify a Git repository as an `extra-dep` in your `stack.yaml`: https://docs.haskellstack.org/en/stable/yaml_configuration/#extra-deps
