### ISSUE TITLE
Latest version stack cannot create ghc-mod

### ISSUE THREAD

**Issue by robert-pearson** [commercialhaskell/stack#5689]
Populating package index cache ...
Package index cache populated

Error: While constructing the build plan, the following exceptions were
encountered:

In the dependencies for ghc-mod-5.8.0.0:
    Cabal-3.2.1.0 from stack configuration does not match >=1.18 && <1.25 
                  (latest matching version is 1.24.2.0)
    base-4.14.3.0 from stack configuration does not match >=4.6.0.1 && <4.10 
                  (latest matching version is 4.9.1.0)
    cabal-helper must match <0.8 && >=0.7.3.0, but the stack configuration has
                 no specified version  (latest matching version is 0.7.3.0)
    djinn-ghc must match <0.1 && >=0.0.2.2, but the stack configuration has no
              specified version  (latest matching version is 0.0.2.3)
    extra-1.7.9 from stack configuration does not match <1.6 && >=1.4  (latest
                matching version is 1.5.3)
    ghc-8.10.7 from stack configuration does not match >=7.6 && <8.2 
    ghc-syb-utils must match <0.3 && >=0.2.3, but the stack configuration has no
                  specified version  (latest matching version is 0.2.3.3)
    haskell-src-exts-1.23.1 from stack configuration does not
                            match <1.20 && >=1.18  (latest matching version
                            is 1.19.1)
    hlint-3.2.8 from stack configuration does not match <2.1 && >=2.0.8  (latest
                matching version is 2.0.15)
    monad-journal-0.8.1 from stack configuration does not match <0.8 && >=0.4 
                        (latest matching version is 0.7.2)
    optparse-applicative-0.16.1.0 from stack configuration does not
                                  match >=0.13.0.0 && <0.14  (latest matching
                                  version is 0.13.2.0)
    semigroups-0.19.2 from stack configuration does not match >=0.10.0 && <0.19 
                      (latest matching version is 0.18.5)
    temporary-1.3 from stack configuration does not match <1.3 && >=1.2.0.3 
                  (latest matching version is 1.2.1.1)
needed since ghc-mod is a build target.

Some different approaches to resolving this:

  * Build requires unattainable version of base. Since base is a part of GHC,
    you most likely need to use a different GHC version with the matching base.

Plan construction failed.

Apparently, you are downloading the wrong versions of your dependencies.

ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.6.5

cabal --version
cabal-install version 2.4.0.0
compiled using version 2.4.0.1 of the Cabal library 

Apparently your code only works with antiquated versions of Cabal base

**Comment by mpilgrem** [comment]
I am going to close this issue because:

1. package `ghc-mod` is deprecated and depends on `base < 4.10`, which implies versions of GHC before 8.2.1; and
2. I am able to build `ghc-mod` with the current version of `stack`, as follows:
~~~
> stack unpack ghc-mod
> cd ghc-mod-5.8.0.0
~~~
Edit `ghc-mod.cabal` to specify `Cabal-Version: 1.18`.
Create a `stack.yaml` file, with:
~~~
resolver: lts-9.21
packages:
- .
~~~
then:
~~~
> stack build
~~~ 
builds the package, as expected, using GHC 8.0.2.
