### ISSUE TITLE
stack install $package-$version silently installs lower version

### ISSUE THREAD

**Issue by jwaldmann** [commercialhaskell/stack#5690]
### Steps to reproduce
```
$ .cabal/bin/stack --resolver=lts  install stack-2.7.5
Selected resolver: lts-18.27
Copying ...
Copied ...
$ .local/bin/stack --version|head -1
Version 2.7.3 x86_64
```
Similarly,
```
stack install --resolver=lts happy-9.9.9   # this does not exist
...
happy --version
Happy Version 1.20.0 -- it built the version that is in the resolver
```
But
```
stack install --resolver=lts happy-1.21.0 # latest from hackage
...
happy --version
Happy Version 1.21.0  -- this worked!
```

### Version
```
$ .cabal/bin/stack --version|head -1
Version 2.7.3 x86_64
```
not using current `stack` because I can't cabal-install it.
 
### Method of installation

* Via cabal-install

**Comment by ketzacoatl** [comment]
```
.cabal/bin/stack
```
how was it installed?

can you use stack to upgrade?

As an aside, how do you plan to use `stack install`, or what do you want it to accomplish for you? It's not a normal part of the recommended workflow, but it's often used in confusion.

**Comment by jwaldmann** [comment]
> how was it installed?

meanwhile, build current stack from hackage seems to work, so
```
cabal -w/opt/ghc/ghc-8.10.7/bin/ghc install stack-2.7.5 --constraint 'persistent<2.14'
```
> can you use stack to upgrade?

probably. But does the behaviour that I described depend on the method of installation? It seems to me that it's a feature of stack's algorithm to pick versions. With stack-2.7.5, installation of happy-9.9.9 still behaves as described above. There may be good reasons for replacing an un-available version with something else. What confused me was that stack does the replacement silently.

> As an aside, how do you plan to use `stack install`, 

install an executable into a directory that I put into my `PATH` because I want to use it often

> It's not a normal part of the recommended workflow, 

what is the recommended workflow, and where does it say so?

**Comment by mpilgrem** [comment]
Closing, as Stack's behaviour is documented in https://docs.haskellstack.org/en/stable/build_command/#target-syntax.
