### ISSUE TITLE
keyserver of signing key seems unavailable

### ISSUE THREAD

**Issue by Cj-bc** [commercialhaskell/stack#5693]
### General summary/comments 
(I'm not good at GPG, so I'm sorry if there're something wrong)

According to [document on docs.haskellstack.org](https://docs.haskellstack.org/en/stable/SIGNING_KEY/), key id 0x575159689BEFB442, which is used to sign authorized keys, is uploaded to https://sks-keyservers.net/.
But it seems that page is currently unavailable.

From [gnupg's mailing list post](https://lists.gnupg.org/pipermail/gnupg-users/2021-June/065261.html), that server is no longer maintained:

> The keyserver *pools* at sks-keyservers.net are no longer maintained for legal reasons. 

If the key 0x575159689BEFB442 can be retrived from other servers, would you mind to update the document on docs.haskellstack.org?

### Steps to reproduce

1. Visit https://docs.haskellstack.org/en/stable/SIGNING_KEY/
2. Click [SKS keyserver pool](https://sks-keyservers.net/) link.

### Expected
Can open that keyserver.

### Actual

It returns error "ERR_NAME_NOT_RESOLVED"

**Comment by ketzacoatl** [comment]
Perhaps the PR should simply drop the link and mention of the SKS keyserver pool?
If there is a new one in use, what is it? If there isn't a new pool in use for distributing that key, do we simply leave the key that is in the docs, or do we figure out who to talk to push the key to a new pool?

**Comment by Cj-bc** [comment]
I've found the key on [ubuntu key server](https://keyserver.ubuntu.com/pks/lookup?search=0x575159689BEFB442&fingerprint=on&op=index), but I'm really not sure whether its valid one or not.

Personally I'm thinking that having one key that signs all authorized keys is a good way to confirm wether it is official release or not. So I hope that information will be updated rather than just dropped.

I think it is really important issue, so I hope someone that can handle this will reply on this...

**Comment by mpilgrem** [comment]
I have updated the documentation.
