### ISSUE TITLE
How to override `default-language` to GHC2021 (for use with GHC9.2.2)

### ISSUE THREAD

**Issue by maerten** [commercialhaskell/stack#5739]
How to set `default-language` to GHC2021 instead of Haskell2010?
When using stack in a project, it sets the `default-language` in the generated cabal file to Haskell2010. Afaik, this disables some modules that would otherwise be enabled by default in GHC9.2.x (via the GHC2021 language extension).

Any suggestions on how to work around this behavior of stack?

**Comment by mpilgrem** [comment]
`stack` can use [`hpack`](https://hackage.haskell.org/package/hpack) (but does not need to) and `hpack` before version 0.35.0 assumes `Haskell2010` by default. Very recently, the `stack` code on this repository was updated to use `hpack-0.35.0`. So you could upgrade to the unreleased version of `stack`, by `stack upgrade --source-only`.

Alternatively, you could not use `hpack` at all. Delete the `package.yaml` file (which `hpack` uses to create a `.cabal` file) and specify the `.cabal` file directly, including your preferred `default-language`.

**Comment by maerten** [comment]
Thanks @mpilgrem, I did not know about hpack and package.yaml.

FYI: `stack upgrade --source-only` did not update stack, it said the newest version was already installed. This might be the case because I installed it with `ghcup`.

The trick with `hpack` worked perfectly though:

1. `stack install hpack-0.35.0 --resolver=nightly-2022-05-05`
2. `stack --with-hpack=/Users/<username>/.local/bin/hpack ghci --test`
3. the `language: GHC2021` entry in package.yaml is now included in the generated cabal file

**Comment by maerten** [comment]
One additional question, can this setting be controlled via `stack.yaml`?

**Comment by mpilgrem** [comment]
Yes, that is correct - see the documentation on the `.yaml` file: https://docs.haskellstack.org/en/stable/yaml_configuration/#with-hpack

**Comment by LeuschkeTressa** [comment]
I still get GHC2010 in the `.cabal` file, although stack now seems to ship with hpack >= 0.35.0.

Any simple workaround? (I'd prefer to keep having the `.cabal` file auto-generated.)

---

Project was created with

    stack new --resolver=lts-20.24 proj

Verifying hpack >= 0.35.0

    stack --hpack-numeric-version
    0.35.1

Still:

    grep default-language proj.cabal
      default-language: Haskell2010
      default-language: Haskell2010
      default-language: Haskell2010

Versions:

    `stack exec -- which ghc` --version
    The Glorious Glasgow Haskell Compilation System, version 9.2.7

    stack --version | head -n 1
    Version 2.9.3, Git revision d0e984f00034552aac7c67675d49ef0807c10c7b (dirty) (112 commits) aarch64

    # macOS version:
    sw_vers -productVersion
    13.4

**Comment by mpilgrem** [comment]
@LeuschkeTressa, if you specify `language: GHC2021` in a package's `package.yaml` file, it should work - it does on my machine.

**Comment by LeuschkeTressa** [comment]
> @LeuschkeTressa, if you specify `language: GHC2021` in a package's `package.yaml` file, it should work

It does!

Thanks.

**Comment by LeuschkeTressa** [comment]
For future readers:

Regarding (from my initial comment):

> I was also a bit confused about GHC and GHCi not defaulting to the same base languages:
> 
> ```
> stack ghci
> λ> :show language
> base language is: GHC2021
> with the following modifiers:
> λ>
> ```

This inconsistency was previously reported as https://github.com/commercialhaskell/stack/issues/5973.

https://github.com/commercialhaskell/stack/commit/b6d11f7d6bd370380987d36814fcffbb2c4294a1 is intended to fix this. It was committed to [release 2.11.1](https://github.com/commercialhaskell/stack/releases/tag/v2.11.1), which is a later release than what I am using.
