### ISSUE TITLE
Add support to only compile script using stack shebang

### ISSUE THREAD

**Issue by brandonchinn178** [commercialhaskell/stack#5755]
I have a file
```hs
#!/usr/bin/env stack
{- stack script --resolver ... --package ... -}
```
and running `./Script.hs` or `stack Script.hs` works as expected. But I would like to have a CI job checking that `Script.hs` builds (but not runs). I do see `stack script` has a `--no-run` flag, but it seems like I would have to copy the entire `stack script` command to do so:
```bash
stack script --compile --no-run Script.hs --resolver ... --package ...
```
Doing `stack Script.hs --no-run` or `stack script Script.hs --no-run` would fail; the first would pass `--no-run` as an argument to `Script.hs`, and the second would fail with "`script` requires `--resolver`".

The most straightforward way I see here is to add a `STACK_INTERPRETER_NO_RUN=true` env var that will add the `--no-run` flag to `stack script` and the appropriate flags to `stack runghc`.

**Comment by mpilgrem** [comment]
The current online help explains:

> With the release of Stack 1.4.0, there is a new command, `script`, which will automatically:
>* Install GHC and libraries if missing
>* Require that all packages used be explicitly stated on the command line
>
>This ensures that your scripts are _independent_ of any prior deployment specific configuration, and are _reliable_ by using exactly the same version of all packages every time it runs so that the script does not break by accidentally using incompatible package versions.

Rather than an environment variable, how about an additional flag for `stack script` that specifies that the script interepter options comment is to be used and not ignored (something like `--use-options-comment`) (disabled by default)?

**Comment by mpilgrem** [comment]
I thought further about this. I have a potential pull request that does the following: if new global flag `--force-script-no-run-compile` is enabled (disabled by default) it forces the options `--no-run --compile` on `stack script`.

So, for example, if you have a script `Script.hs`:
~~~haskell
{- stack script
   --resolver lts-19.9
   --package acme-missiles
-}
import Acme.Missiles (launchMissiles)

main :: IO ()
main = launchMissiles
~~~
If you use:
~~~
 stack --force-script-no-run-compile Script.hs
~~~
then that gets translated (by `stack`, behind the scenes) into:
~~~
stack --force-script-no-run-compile script --resolver lts-19.9 --package acme-missiles -- Script.hs
~~~
which is then forced (by my pull request) to be the equivalent of having asked for:
~~~
stack script --resolver lts-19.9 --package acme-missiles --no-run --compile -- Script.hs
~~~

**Comment by mpilgrem** [comment]
The option - now named `--script-no-run-compile` - has been added to the current source code for `stack`.
