### ISSUE TITLE
remove warning "Stack has not been tested with GHC versions above 9.0" please

### ISSUE THREAD

**Issue by shayne-fletcher** [commercialhaskell/stack#5758]
current stack >= 2.7.3(2.7.5) with any resolvers for ghc > 9.0 produces warning messages of the form "Stack has not been tested with GHC versions above 9.0"... this plays havoc with expect tests downstream and leads them to them getting disabled. can we have a new release without this message please?

**Comment by ntc2** [comment]
This may cause other warnings you actually care about to be suppressed, but if you run `stack --verbosity error` or `stack --silent` you won't see these warnings. For example

    stack --verbosity error exec <your program>

**Comment by shayne-fletcher** [comment]
> This may cause other warnings you actually care about to be suppressed, but if you run `stack --verbosity error` or `stack --silent` you won't see these warnings. For example
> 
> ```
> stack --verbosity error exec <your program>
> ```

good info @ntc2. thanks!

**Comment by mpilgrem** [comment]
The pull request #5763, seeking to move Stack to GHC 9.2.3, proposes also to bump these warning messages to GHC > 9.2 and Cabal > 3.6. The PR is currently stuck with a macOS-specific problem involving the `process` library.
