### ISSUE TITLE
Windows 7 error:  builderMainLoop: permission denied

### ISSUE THREAD

**Issue by Andrey-Shypko** [commercialhaskell/stack#5762]
Windows 7 64

in cmd and MSYS2 Bash

$ stack new test simple
$ cd test
$ stack build
Building all executables for `test' once. After a successful build of all of them, only specified executables will be rebuilt.
test> configure (exe)
Configuring test-0.1.0.0...
C:\Users\User1\AppData\Local\Programs\stack\x86_64-windows\ghc-9.0.2\lib\../mingw/bin/gcc.exe: builderMainLoop: permission denied (Permission denied)

# stack --verbose build
["stack --verbose build"](https://gist.github.com/Andrey-Shypko/6c083fb9c370ad6a53a3988772a5c5af)

### Stack version

```
$ stack --version
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4

```

### Method of installation

* Official binary, downloaded from stackage.org or fpcomplete's package repository

**Comment by mpilgrem** [comment]
I think it is the version of `gcc.exe` that comes with GHC 9.0.2 (located in `ghc-9.0.2\mingw\bin`) that is complaining. Is it GHC 9.0.2 specific? For example, if you replace the resolver in the `stack.yaml` with `resolver: lts-18.28` (which is GHC 8.10.7) does the same thing happen?

**Comment by Andrey-Shypko** [comment]
Pleas install ghc in ghcup!!! same error. And us: `stack --system-ghc build`
or edit
C:\sr\config.yaml and add:
system-ghc: true
