### ISSUE TITLE
extra-deps does not work with binary package

### ISSUE THREAD

**Issue by jchia** [commercialhaskell/stack#5767]
### General summary/comments (optional)
extra-deps for a github repo fails to override the binary package.

### Steps to reproduce
```
$ git clone https://github.com/jchia/extra-deps
$ cd extra-deps
$ stack build
...
$ stack run
25
```
(The stack.yaml in the above `extra-deps` repo is as follows.)
```
resolver: lts-19.11

packages:
- .

extra-deps:
- git: https://github.com/jchia/binary.git
  commit: dd621d70929ed57efbae5adf33ccf232f2961568
```

### Expected
Output of `stack run` should be 8, based on this commit used in the extra-deps: https://github.com/jchia/binary/commit/dd621d70929ed57efbae5adf33ccf232f2961568

### Actual
Output is 25, same as the original binary package.

A similar cabal-based approach using `source-repository-package` in the `cabal.project` file works and results in an output of 8. (Try `cabal build` and then `cabal run` from within the extra-deps repo.)

### Stack version

```
$ stack --version
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4
```

### Method of installation

* stack was installed using ghcup.

**Comment by mpilgrem** [comment]
I am wondering, is `binary` one of GHC's _wired-in_ packages, based on the first sentence of the 'Intro' section of this blog: https://www.snoyman.com/blog/2019/01/mismatched-global-packages/.

**Comment by hasufell** [comment]
> I am wondering, is `binary` one of GHC's _wired-in_ packages, based on the first sentence of the 'Intro' section of this blog: https://www.snoyman.com/blog/2019/01/mismatched-global-packages/. EDIT: No it is not, based on `Stack.Constants.wiredInPackages`.

Yes it is: https://gitlab.haskell.org/ghc/ghc/-/tree/master/libraries

**Comment by mpilgrem** [comment]
@hasufell, thanks! May I double-check something? In respect of packages that ship with GHC, the blog post seems to distinguish those that are 'wired-in' (`ghc`, `base` and `template-haskell` are given as examples - and they also appear in `Stack.Constants.wiredInPackages`) and those that are not 'wired-in' (`process` and `transformers` are given as examples - and they do not appear in `Stack.Constants.wiredInPackages`). The link you provided seems to list `process` and `transformers` as well as `binary`. Can I double-check its 'wired-in' status? (As an aside, 'wired-in' status may have nothing to do with `binary` being dropped silently when it is a 'git' `extra-dep`.)

**Comment by hasufell** [comment]
Sorry, I don't know what *wired in* means. These all are **boot** packages.

The only one that is not reinstallable is `base`.

**Comment by hasufell** [comment]
We should check whether cabal-install behaves different here.

**Comment by mpilgrem** [comment]
`binary` also appears to be not ignored when the 'git' `extra-dep` has a different `version:` to the version that is included in `lts-19.11`. For example:
~~~yaml
resolver: lts-19.11

packages:
- .

extra-deps:
- git: https://github.com/jchia/binary.git
  # version: binary-0.8.9.0
  commit: 6af054b4431fa7c20bf6309536cfef7d47f2c17f
~~~
does what you expect it would.

**Comment by mpilgrem** [comment]
`binary` is also not ignored when it is a local package. I `git clone https://github.com/jchia/binary.git` into a parallel folder, `git reset --hard dd621d70929ed57efbae5adf33ccf232f2961568`, and used:
~~~yaml
resolver: lts-19.11

packages:
- .
# Local copy of https://github.com/jchia/binary.git, commit: dd621d70929ed57efbae5adf33ccf232f2961568
- ../binary
~~~
and `stack build` does what you would expect it to do.

**Comment by mpilgrem** [comment]
I tried an experiment with another, but non-GHC-supplied, package. `lts-19.11` includes `ansi-terminal-0.11.3`. In my fork of that package, I created a version (same `version: 0.11.3`) with a new function `dummy`, and used:
~~~yaml
resolver: lts-19.11

packages:
- .

extra-deps:
- git: https://github.com/mpilgrem/ansi-terminal.git
  commit: 7899d1895a1930ed2ba86b524a57b978e10a7b91
~~~
`stack build` worked as expected: the `extra-deps` shadowed the version in the resolver. So, it would seem that `binary` is 'special' in some way, presumably because it is included in the package database that comes with GHC.

**Comment by mpilgrem** [comment]
I tried a further experiment. I created a remote repository `text` with a `text.cabal` of `version: 1.2.5.0` (the same package name-version as is supplied with GHC 9.0.2). Like `binary-0.8.8.0` that too was silently ignored as a 'git' `extra-deps`. However, if I changed the version to `text-1.2.5.1`, it was acknowledged as a 'git' `extra-deps` and used over the `text` in the resolver.

So, the symptom of the problem may well be this: for any package that is a 'git' `extra-deps` that shares the same `name-version` as a GHC-supplied package, `stack` will silently ignore the `extra-deps`. The 'ignoring' may be 'by design'; if it is, the 'silently' seems to me to be a bug.

**Comment by jchia** [comment]
> So, the symptom of the problem may well be this: for any package that is a 'git' `extra-deps` that shares the same `name-version` as a GHC-supplied package, `stack` will silently ignore the `extra-deps`. The 'ignoring' may be 'by design'; if it is, the 'silently' seems to me to be a bug.

Indeed, I made a further commit (5e97b91f23a81a4d2eabb04851a63769071e89dc) to bump the version number and when I changed the stack.yaml to use it instead, the specified github binary package got used and the program output the expected `8`.

In reality, though, being able to actually specify a different binary package for the project just opens the doors to other problems, such as the following warning if ghc is included in the cabal `build-depends`:
```
Configuring extra-deps-0.1.0.0...
Warning:
    This package indirectly depends on multiple versions of the same package. This is very likely to cause a compile failure.
      package ghci (ghci-9.0.2) requires binary-0.8.8.0
      package ghc-boot (ghc-boot-9.0.2) requires binary-0.8.8.0
      package ghc (ghc-9.0.2) requires binary-0.8.8.0
      package extra-deps (extra-deps-0.1.0.0) requires binary-0.8.8.0.1-Eyw3mt7qBlK3OMvBED68Ui
```

(Including hspec in the `build-depends` would indirectly include ghc)

Apparently, stack does not allow/like using different versions of a package (IDK whether cabal-install does), so I would have to transitively include ghc, ghc-boot & ghci in the `extra-deps`. The problem with that is overriding ghc in the extra-deps has the same problem as binary of requiring the version number to be different for stack to care about it.

**Comment by mpilgrem** [comment]
On the question [above](https://github.com/commercialhaskell/stack/issues/5767#issuecomment-1157893235) about the `cabal` tool, the `extra-deps` project example of @jchia includes the following `cabal.project` and the `cabal` tool does respect and apply its `source-respository-package` stanza:
~~~cabal
with-compiler: ghc-9.0.2
packages: .

source-repository-package
    type: git
    location: https://github.com/jchia/binary.git
    tag: dd621d70929ed57efbae5adf33ccf232f2961568
~~~

**Comment by mpilgrem** [comment]
I think I understand what is happening. The [Cabal User Guide](https://cabal.readthedocs.io/en/3.6/developing-packages.html#package-names-and-versions) says that two packages with the same name and version are considered to be the same. Stack classifies packages as 'immutable' or 'mutable', and a package which comes from a repository is assumed to be 'immutable' (see [documentation](https://docs.haskellstack.org/en/stable/build_overview/#terminology)). So, the supposedly 'immutable' `binary-0.8.8.0` requested in the `extra-deps:` is considered to be the same package as `binary-0.8.8.0` available in GHC's global package database.

So, `Stack.Build.Installed.toInstallMap :: MonadIO m => SourceMap -> m InstallMap` has, just capturing 'immutable' (`Snap`) and the package version (`getPLIVersion pli`):
~~~haskell
    depInstalls <-
        for (smDeps sourceMap) $ \deppkg ->
            case dpLocation deppkg of
                PLImmutable pli -> pure (Snap, getPLIVersion pli)
~~~

and `Stack.Build.Installed.isAllowed :: InstallMap -> Maybe InstalledPackageLocation -> DumpPackage -> Allowed` has (yielding `Allowed`) (extracts only):
~~~haskell
isAllowed installMap mloc dumppkg =
        case Map.lookup name installMap of
            Just pii -> checkFound pii
  where
    PackageIdentifier name version = dpPackageIdent dumppkg
    checkLocation Snap = True
    checkFound (installLoc, installVer)
      | not (checkLocation installLoc) = WrongLocation mloc installLoc
      | version /= installVer = WrongVersion version installVer
      | otherwise = Allowed
~~~
