### ISSUE TITLE
Progress indication in percents for longer operations

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#582]
Currently on "stack init" or "stack setup" some operations take a lot of time. On some operations there is no sign that something is happening at all and I could not guess how much there is more. 

It will be more informative if some progress indication could be added for longer processes or for overall progress.

**Comment by snoyberg** [comment]
These are implemented on master, and will be included in the next release.

**Comment by varosi** [comment]
Cool! You are faster than a thought!

**Comment by snoyberg** [comment]
No credit to me at all on this, it was implemented by @markus1189

**Comment by varosi** [comment]
Thanks @markus1189!
