### ISSUE TITLE
Cleaning one package on a multi-package project

### ISSUE THREAD

**Issue by jcpetruzza** [commercialhaskell/stack#583]
In multi-package projects, `stack clean` will clean every package, but I couldn't find a way of limiting this to only a single package (or a subset of packages). Is it possible at all? (when re-building _all_ the packages in the project takes time, this can become annoying rather fast!)

In case anyone wonders, neither `cabal clean` nor `runhaskell Setup.hs clean` will do the trick...

**Comment by chrisdone** [comment]
Not presently possible but it should be.

Related discussion here: https://github.com/commercialhaskell/stack/issues/493#issuecomment-120786137

**Comment by sjakobi** [comment]
What should the usage look like?

Just `stack clean pkg` and `stack clean path-to-pkg`?

Or a larger subset of `build`'s target syntax?

**Comment by borsboom** [comment]
I'd say just specifying the package would make sense.  It should probably follow similar logic as `stack build` for selecting the default packages to clean based on the current directory, though.

**Comment by sjakobi** [comment]
Resolved via 729b61edbe4f1c677194067035567c0ec289ef4b and released with stack-0.1.8.0

Please reopen if it doesn't work as expected.
