### ISSUE TITLE
Slack shared invite seems dead

### ISSUE THREAD

**Issue by jsoref** [commercialhaskell/stack#5837]
### General summary/comments (optional)

@snoyberg added a shared invite a year ago to https://github.com/commercialhaskell/stack/blob/master/README.md but that appears to have expired.

There's also a page (which feels out of date relative to the above page) that mentions tagging them: https://github.com/commercialhaskell/stack/blob/master/CONTRIBUTING.md#slack-channel

### Steps to reproduce

For example:

1. Visit https://github.com/commercialhaskell/stack/blob/master/README.md
2. Click [Haskell Foundation Slack](https://join.slack.com/t/haskell-foundation/shared_invite/zt-mjh76fw0-CEjg2NbyVE8rVQDvR~0F4A) 
     ![image](https://user-images.githubusercontent.com/2119212/186468470-ade4c392-5bbe-4839-b219-2c06cfcb4967.png)
3. Click Continue with Google
4. Select a Google account
    
![image](https://user-images.githubusercontent.com/2119212/186468622-71ec3bac-780c-410b-adbe-54b2f1178a1a.png)

### Expected

* The invitation should work or have other advice
* Both pages should agree on advice

### Actual

<img width="725" alt="image" src="https://user-images.githubusercontent.com/2119212/186471713-0a7983a7-8ec1-4da2-a4f3-99192ca0b8b6.png">

**Comment by mpilgrem** [comment]
Hello @jsoref - see this recent comment from Michael Snoyman (21 July 2022): https://github.com/commercialhaskell/stack/pull/5788#issuecomment-1190983788.

I am unfamiliar with Slack, but I assumed that whether it was via Google, via Apple or direct input you needed to have an @haskell.foundation email address.

**Comment by hasufell** [comment]
> Hello @jsoref - see this recent comment from Michael Snoyman (21 July 2022): https://github.com/commercialhaskell/stack/pull/5788#issuecomment-1190983788.
> 
> I am unfamiliar with Slack, but I assumed that whether it was via Google, via Apple or direct input you needed to have an @haskell.foundation email address.
> 
> 

I don't think so. Very few people have such an email. The slack was always open to public.

**Comment by mpilgrem** [comment]
I found this https://haskell.foundation/contact/. See the link labelled ‘>>Slack invite’.
