### ISSUE TITLE
allow `resolver: lts-19`, etc

### ISSUE THREAD

**Issue by juhp** [commercialhaskell/stack#5838]
I would also really like to be able to specify just the major resolver version for a project (like just `nightly` or `lts-18`).
That would help cut down on the busy work of having to bump lts-19 or nightly snapshot resolvers regularly for active projects.

eg
```yaml
resolver: nightly
```
or
```yaml
resolver: lts
```
etc

This would correspond to the behavior of `stack --resolver ...`.

**Comment by mpilgrem** [comment]
The User Guide explains why those options are provided only on the command line - see this passage of the Guide https://docs.haskellstack.org/en/stable/GUIDE/#resolvers-and-changing-your-compiler-version. It is before my time, but it seems like it was a deliberate design choice.

**Comment by juhp** [comment]
There is also #1878, but at least for LTS versions I feel this really makes sense.

**Comment by mpilgrem** [comment]
I am going to close this issue as it duplicates #1878.
