### ISSUE TITLE
When throwing YAML parse exception, say which config file.

### ISSUE THREAD

**Issue by philderbeast** [commercialhaskell/stack#5846]
I'm rebasing a branch over master and struck a YAML parse exception. Could we please say which file this parse exception is in? Stack parses multiple YAML files for its configuration; project, global and project on the fly.

I know this error isn't in the `stack.yaml` that I'm merging because I cut it down to 2 lines (`resolver` and `packages`) while troubleshooting and still the exception was reported on line 15!

```yaml
resolver: nightly-2022-08-02
packages: [.]
```

```
> stack build --system-ghc
YAML parse exception at line 15, column 11,
while scanning a simple key:
could not find expected ':'
```

**Comment by philderbeast** [comment]
Unfortunately I moved on with the rebase and lost the reproduction but I do think that we should include the filename being parsed in that exception.

**Comment by mpilgrem** [comment]
I agree with including the file name. What I am not clear about is whether this is a problem with Stack or a problem with one of its dependencies. I'll investigate.

**Comment by mpilgrem** [comment]
I am pretty sure I have found it: `Stack.LockSpec.decodeLocked`:

~~~haskell
decodeLocked :: ByteString -> IO Locked
decodeLocked bs = do
  val <- Yaml.decodeThrow  bs
  case Yaml.parseEither Yaml.parseJSON val of
    Left err -> throwIO $ Yaml.AesonException err
    Right (WithJSONWarnings res warnings) -> do
      unless (null warnings) $
        throwIO $ Yaml.AesonException $ "Unexpected warnings: " ++ show warnings
      -- we just assume no file references
      resolvePaths Nothing res
~~~

Somehow deleting a colon from a simple key in `stack.yaml.lock` would give the cryptic message.
