### ISSUE TITLE
Stack for macOS AArch64 (ARM64)

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#5854]
Stack's stated goals include to provide complete support on macOS.

Apple silicon/Apple M1 is a series of processors mainly using the ARM architecture. The GHC developers have published binary distributions of GHC 8.10.7, 9.0.2, 9.2.4 and 9.4.2 for macOS and the AArch64 machine architecture.

However, GitHub Actions does not offer a runner for macOS/AArch64. Self-hosted runners for ARM64 are supported for Linux only: https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#architectures.

**Comment by hasufell** [comment]
GHCup provides aarch64 macOS binaries.

**Comment by mpilgrem** [comment]
@hasufell, I see - at https://downloads.haskell.org/ghcup/unofficial-bindists/stack/. Are you able to do that because GitLab supports platforms that GitHub Actions does not? Or is it 'hand crafted' by somebody?

**Comment by fwcd** [comment]
> GitHub Actions does not offer a runner for macOS/AArch64

Is cross-compiling from an x86 macOS runner an option? The LLVM toolchain generally handles this case pretty well due to the system libraries being universal/fat binaries.

**Comment by hasufell** [comment]
> @hasufell, I see - at https://downloads.haskell.org/ghcup/unofficial-bindists/stack/. Are you able to do that because GitLab supports platforms that GitHub Actions does not? Or is it 'hand crafted' by somebody?

Yes, GHC gitlab supports all GHC platforms.

**Comment by ysangkok** [comment]
The following offical issue for GitHub

* https://github.com/github/roadmap/issues/528

currently lists as on the roadmap for "Q3 2023 – Jul-Sep"

**Comment by mpilgrem** [comment]
As of 25 December 2022, I am now also a (novice) macOS/AArch64 user. I used GHCup's [binary distribution for Stack for macOS/AArch64](https://downloads.haskell.org/ghcup/unofficial-bindists/stack/2.9.3/) to get up and running. I was not sure if I could use the macOS/x86_64 version of Stack (running under Rosetta 2) to build locally a macOS/AArch64 version of Stack.

**Comment by mpilgrem** [comment]
I've updated Stack's online help to deal expressly with Intel-based Macs versus Apple silicon Macs.

**Comment by hasufell** [comment]
As a sidenote: we now have one M1 runner on Github, but it's restricted to the haskell org.

**Comment by ysangkok** [comment]
@mpilgrem , [on discours](https://discourse.haskell.org/t/github-hosted-runner-for-macos-aarch64/8717?u=janus) your edit suggests that you have added arm64 runners on MacOS. Does that mean this can be closed? If not, what remains?
