### ISSUE TITLE
--only-configure does not play well with --test for stack build

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [commercialhaskell/stack#5865]
### Steps to reproduce

`stack build --test --only-configure`

### Expected

I would have expected --only-configure to override all build flags command to only configure.

### Actual

When I run the command, stack will build all libs, exes and tests.

**Comment by mpilgrem** [comment]
See https://github.com/commercialhaskell/stack/issues/2787. Stack's logic is explained here:
~~~haskell
        case ( ee.buildOptsCLI.onlyConfigure
             , ee.buildOptsCLI.initialBuildSteps && taskIsTarget task
             ) of
          -- A full build is done if there are downstream actions,
          -- because their configure step will require that this
          -- package is built. See
          -- https://github.com/commercialhaskell/stack/issues/2787
          (True, _) | null ac.downstream -> pure Nothing
~~~

That is, `--only-configure` only stops at configuration if there is no downstream action that requires more.
