### ISSUE TITLE
Sharing non-snapshot dependencies between projects

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#587]
Is there a way to share non-snapshot dependencies between separate stack projects? Essentially, when a project has many non-snapshot dependencies, can you revert to shared sandboxes of some sort? Or can you make your own snapshots locally?

**Comment by snoyberg** [comment]
I think you're looking for #111. Maybe worth pinging @feuerbach about that one :)

**Comment by snoyberg** [comment]
@3noch If you don't mind, I'm closing this, and we can discuss on #111.

**Comment by 3noch** [comment]
Good call.
