### ISSUE TITLE
"Global dump did not parse correctly" error after upgrading to 2.9

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/stack#5872]
### General summary/comments (optional)

I saw this error the first time I ran any stack command with the new stack version:
```
Trouble loading CompilerPaths cache: UnliftIO.Exception.throwString called with:

Global dump did not parse correctly
Called from:
  throwString (src/Stack/Storage/User.hs:295:20 in stack-2.9.1-51nMVFIeaUyLG4TNZxOEOo:Stack.Storage.User)
```
but it seems like it passes after the first failure.

### Steps to reproduce

Hard to reproduce cause it passes after the first time

### Stack version

~~~text
stack --version
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
~~~

### Method of installation

Official binary (github releases)

**Comment by mpilgrem** [comment]
@brandon-leapyear, thanks for reporting. That is indeed a one-time-only message - a result, I think, of Stack having been moved to a more recent version of the Cabal library.

**Comment by brandon-leapyear** [comment]
Cool, feel free to close. Just wanted to have an issue opened for other people who might be searching for the same issue.

In the future, it would be great to do at least one of the following:
1. Mention in the release notes
2. Add check for old format + migrate automatically
3. Show a more informative error message (i.e. "try rerunning command")

**Comment by brandon-leapyear** [comment]
Note: it's not just a warning, it'll exit with a non-zero exit code

**Comment by mpilgrem** [comment]
I've added a release note. It was my oversight - I've been using the 'new' Stack for so long, I'd forgotten the message on first use. Interesting on the non-zero exit code - my recollection was that the message actually did not prevent Stack working.

**Comment by brandon-leapyear** [comment]
Oh sorry you're right; the Stack command I ran failed for another reason. But still, the "warning" message mentions `throwString`, so it's a bit misleading. I assume Stack is catching and printing out this exception; maybe it should have some wording like "Ignoring this exception..."?

**Comment by istathar** [comment]
I'm encountering this multiple times per day in a repo that has long since had Stack 2.9.1 run in it. I thought the one-time fix was to remove _.stack-work_ but the error recurs even after having done that. Recommend re-opening, I'm afraid.

**Comment by istathar** [comment]
> I am pretty confident (from my own experience) that Stack rebuilds the affected cache only once. Could the CI script in your repository be configured ...

It's not a CI script. It's a normal repo on a developer laptop with VSCode and haskell-language-server doing their thing. Then go to `stack build` on command-line and you get this warning. The _~/.stack_ and all the _.stack-work_ directories on this machines were removed so it was completely fresh and the message is recurring.

**Comment by mpilgrem** [comment]
@istathar thanks for the additional information. First, I should clarify two things: (1) the warning should be a one-time-only message _for each compiler in Stack's cache of information about compilers it has already experienced_; if you have been using more than one compiler with the old version of Stack, you'll see the message for the first use of each compiler with the new version of Stack; and (2) the cache in question is the `stack.sqlite3` database in the Stack root; you do not need to worry about the contents of `.stack-work`.

At least, that's the theory. What _should_ be happening is reflected in this code extract from `Stack.Setup.pathsFromCompiler`:
~~~haskell
withCache inner = do
      eres <- tryAny $ loadCompilerPaths compiler compilerBuild isSandboxed
      mres <-
        case eres of
          Left e -> do
            logWarn $ "Trouble loading CompilerPaths cache: " <> displayShow e
            pure Nothing
          Right x -> pure x
      case mres of
        Just cp -> cp <$ logDebug "Loaded compiler information from cache"
        Nothing -> do
          cp <- inner
          saveCompilerPaths cp `catchAny` \e ->
            logWarn ("Unable to save CompilerPaths cache: " <> displayShow e)
          pure cp
~~~

That is, it tries to get the compiler paths (`cp`) for the particular compiler (uniquely identified by the path to the GHC executable) from Stack's cache. If it can't, it gets the `cp` from the `inner` action and tries to save them in the cache. If all is well with the rebuilding of the cache, the debug output will not have the line starting `Unable to save CompilerPaths cache:`.

So, this should result in the follow example behaviour. With Stack 2.7.5, I've created a simple `stack new foo` and built it with the default resolver (currently `lts-19.25` GHC 9.0.2) and with `nightly-2022-09-30` GHC 9.2.4. If I then upgrade to Stack 2.9.1 (`stack upgrade`) and try to build again (extracts of verbose output only):

~~~text
stack --verbose build
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
...
2022-10-02 00:19:51.057459: [debug] Asking for a supported GHC version
2022-10-02 00:19:51.059460: [debug] Installed tools:
...
2022-10-02 00:19:51.068462: [warn] Trouble loading CompilerPaths cache: UnliftIO.Exception.throwString called with:

Global dump did not parse correctly
Called from:
  throwString (src/Stack\Storage\User.hs:295:20 in stack-2.9.1-E2VJr54ZMIA7bUTQbTwYp8:Stack.Storage.User)

...
2022-10-02 00:19:51.337304: [debug] (SQL) INSERT INTO "compiler_cache" ...
~~~

The long debug line that starts `(SQL) INSERT INTO "compiler_cache"` is the rebuilding of Stack's cache for that compiler. Much the same output comes from the first use of `stack --verbose --resolver nightly-2022-09-30 build` (but with references to GHC 9.2.4 replacing references to GHC 9.0.2).

The second time around, the `stack --verbose build` output should recognise that Stack's cache has been rebuilt for that compiler:

~~~text
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
...
2022-10-02 00:21:00.262229: [debug] Asking for a supported GHC version
2022-10-02 00:21:00.263259: [debug] Installed tools:
...
2022-10-02 00:21:00.315315: [debug] Loaded compiler information from cache
~~~

Are you experiencing the `Global dump did not parse correctly` message second time around _for the same compiler_? If you are, what is Stack's debug output? Are you experiencing the `Unable to save CompilerPaths cache:` message?

**Comment by istathar** [comment]
@mpilgrem ok, I may have an idea why I thought I was seeing it more than I thought I should: the GHC being used by VSCode is from **ghcup** maybe? whereas the GHC being used by `stack build` is brought in by **stack**? So yes, _possibly_ this was indeed the first time being run for "that compiler".

But tbh my subjective judgment is that I've seen it more than once per new compiler. New compilers do NOT happen that often. This message does. I'll keep an eye out. If it happens again after I've controlled for **haskell-language-server** doing its thing I'll post here.

Thanks for your exploratory work above.

**Comment by istathar** [comment]
Still happening constantly. Seems to be related to switching from VSCode running a Stack build and doing `stack build` on the command-line. Haven't been able to reproduce it reliably, though. I'll keep trying.

**Comment by mpilgrem** [comment]
Is it possible that you are switching back and forth between new Stack and old Stack? Each will complain about the cached compiler info of the other.

**Comment by istathar** [comment]
oh! You nailed it. 

```
$ stack --version
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
turminder-xuss 
$ which stack
~/.local/bin/stack
```
Yup. But,

```
$ ~/.ghcup/bin/stack --version
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4
```

argh. I totally didn't realize Ghcup would have left the Stack version behind when everything else was upgraded to something recent enough to use GHC 9.2.4 (and even more so, the big reason we the work to get Stack upgraded recently was to support GHC 9.2.x!). And since HLS was running things, I didn't see the warning we got rid of.

I've told Ghcup to do the right thing and the recurrence appears to have gone away.

Thanks @mpilgrem
