### ISSUE TITLE
hpack generates wrong cabal file the first time

### ISSUE THREAD

**Issue by brandon-leapyear** [commercialhaskell/stack#5873]
### General summary/comments (optional)

I'm putting the issue here because I'm assuming the issue is something to do with the way Stack invokes hpack.

### Steps to reproduce

1. `stack new foo`
2. `cd foo`
3. `rm foo.cabal`
4. (Optional) Add `verbatim: { cabal-version: 2.2 }` to the top of `package.yaml` (
5. Add `verbatim: { import: foo }` to the library stanza in `package.yaml`
6. `stack build`
7. `foo.cabal` has `import: foo` at bottom of library stanza (which is incorrect)
8. `stack build`
9. `foo.cabal` has `import: foo` at top of library stanza (correct)

### Expected

Should have `import: foo` at the top of the stanza (https://github.com/sol/hpack/pull/490)

### Actual

Had it at the bottom the first time, then corrected the second time.

For some reason, `stack path` generates the cabal file twice, so running `stack path` once will generate the incorrect version, then the correct version immediately after

### Stack version

~~~text
stack --version
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
~~~

### Method of installation

* Official binary, downloaded via haskellstack.org or from Stack's repository
* Via GHCup
* Via Cabal (the tool)
* An unofficial package repository (please specify which)
* Other (please specify)

**Comment by brandon-leapyear** [comment]
Never mind, this is an hpack issue. Corresponding issue: https://github.com/sol/hpack/issues/522

**Comment by mpilgrem** [comment]
@brandon-leapyear, thanks for reporting and following up.
