### ISSUE TITLE
error while loading shared libraries: libHSpath-0.9.2-9

### ISSUE THREAD

**Issue by killawat** [commercialhaskell/stack#5875]
Doing anything with stack throws this error.

stack: error while loading shared libraries: libHSpath-0.9.2-9Ps66to43WaHvlFQJ4Gi5N-ghc9.0.2.so: cannot open shared object file: No such file or directory

haskell-path-0.9.2-74   is installed
Running on Arch

**Comment by mpilgrem** [comment]
@killawat, any further information you can provide about the version of the Stack executable, how you obtained it, and your system would help in working out what is happening.

**Comment by killawat** [comment]
Stack was installed with pacman on an Seeed Odyssey x86j4125. I removed the package and reinstalled it today in an attempt to resolve. I can not determine the version with stack --version as that throws the same trouble. Can you advise me on another way to get the version info for you?

**Comment by mpilgrem** [comment]
I assume that it is Stack 2.7.5, based on this: https://archlinux.org/packages/community/x86_64/stack/. Although I note that states it links to `libHSpath-0.9.2-DO7oflsFsnq7jhC0YStmqP-ghc9.0.2.so`, so perhaps it is an earlier build that you have?

Could you perhaps try the non-pacman way of installing? See https://docs.haskellstack.org/en/stable/install_and_upgrade/. That should get you Stack 2.9.1.

**Comment by s5k6** [comment]
Same problem here.

> Could you perhaps try the non-pacman way of installing?

Sorry, but `curl whatever | sh` is a no-go.  especially so when the its documentation says “will ask for root access”.  Installing *exclusively* through a Linux distribution's packaging system has the benefit that what ever is been done to the system was (hopefully) reviewed by a knowledgeable packager, with the competence to keep the system somewhat clean.

I'll try to raise an issue with Arch Linux, maybe it is a packaging problem.

**Comment by s5k6** [comment]
Arch Linux ticket: https://bugs.archlinux.org/task/75973

**Comment by huntears** [comment]
Same problem here with stack 2.7.5-162 on arch

**Comment by killawat** [comment]
@mpilgrem Replacing the current pacman version (2.7.5-162) with 2.9.1 via "curl -sSL https://get.haskellstack.org/ | sh -s - -f" has resolved.

**Comment by s5k6** [comment]
This now seems fixed in Arch Linux repositories as well.  Pacman now installs version 2.7.5-163, which does not exhibit the error.

https://bugs.archlinux.org/task/75973#comment211322
