### ISSUE TITLE
Build failure on AArch64: InvalidRelFile "package.cache"

### ISSUE THREAD

**Issue by arrowd** [commercialhaskell/stack#5890]
When building 2.9.1 release on AArch64 for FreeBSD, the following error arises:

```
[ 53 of 110] Compiling Stack.Storage.User ( src/Stack/Storage/User.hs, /wrkdirs/usr/ports/devel/stack/work/stack-2.9.1/dist-newstyle/build/aarch64-freebsd/ghc-9.2.4/stack-2.9.1/build/Stack/Storage/User.o, /wrkdirs/usr/ports/devel/stack/work/stack-2.9.1/dist-newstyle/build/aarch64-freebsd/ghc-9.2.4/stack-2.9.1/build/Stack/Storage/User.dyn_o )

src/Stack/Storage/User.hs:325:74: error:
    * Exception when trying to run compile-time code:
        InvalidRelFile "package.cache"
CallStack (from HasCallStack):
  error, called at src/Path/Include.hs:775:21 in path-0.9.2-inplace:Path.Posix
      Code: (mkRelFile "package.cache")
    * In the untyped splice: $(mkRelFile "package.cache")
    |
325 |   globalDbStatus <- liftIO $ getFileStatus $ toFilePath $ cpGlobalDB </> $(mkRelFile "package.cache")
    |                                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
*** Error code 1
```

Full build log: http://ampere3.nyi.freebsd.org/data/131arm64-default/b46629e97f41/logs/hs-stack-2.9.1.log

**Comment by mpilgrem** [comment]
@arrowd, thanks for reporting. I think the exception thrown has its origins in this part of the `path-0.9.2` package:

~~~haskell
parseRelFile :: MonadThrow m
             => FilePath -> m (Path Rel File)
parseRelFile filepath =
  case validRelFile filepath of
    True
      | normalized <- normalizeFilePath filepath
      , validRelFile normalized -> return (Path normalized)
    _ -> throwM (InvalidRelFile filepath)

validRelFile :: FilePath -> Bool
validRelFile filepath =
  not
    (FilePath.isAbsolute filepath || FilePath.hasTrailingPathSeparator filepath) &&
  not (null filepath) &&
  not (hasParentDir filepath) &&
  filepath /= "." && FilePath.isValid filepath
~~~

but I don't know why `package.cache` on FreeBSD would not parse as a relative file.

**Comment by arrowd** [comment]
Where does this `package.cache` file come from? I don't see it in the Stack source tree.

**Comment by hasufell** [comment]
> Where does this `package.cache` file come from? I don't see it in the Stack source tree.

That's irrelevant to the error. The path library deals with the static filepath, not the actual file.

**Comment by mpilgrem** [comment]
@arrowd, I don't have access to a FreeBSD platform, but if I did, the next thing I would do is investigate the behaviour of a minimal program depending on `path-0.9.2`. Something like:

~~~haskell
module Main (main) where

import Path (parseRelFile)

main :: IO ()
main = do
  fp <- parseRelFile ("package.cache")
  print fp
~~~

If that throws an exception on FreeBSD, then the problem is upstream with the `path` package.

**Comment by arrowd** [comment]
I already done that on amd64 and it works fine. I can't check on aarch64 for now due to hardware problems.

**Comment by arrowd** [comment]
The problem somehow resolved itself.
