### ISSUE TITLE
Smart behavior for exec/ghc/etc commands outside of a project

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#59]
Desired behavior: you're working on a project that uses LTS 2.9. You leave that project and go to a directory which has no stack.yaml file. You run `stack runghc foo.hs`. Instead of using some random snapshot, it should use the most recently used snapshot (LTS 2.9) so that there's a good chance that your desired libraries are available. It should also print out a message to the user explaining what happened and recommending a config file for more determinism.

**Comment by chrisdone** [comment]
* Have a `~/.stack/global/stack.yaml` config file.
* Somewhere in `~/.stack/global` will be the usual installed package database.
* In [ExecStrategy](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Config.hs#L305..L306):
   * Choose the latest LTS.
   * Create a Project config type with empty fields apart from `projectResolver`.

When running e.g. `stack ghc` that'll create this config file (or load it in) and proceed as normal.

**Comment by snoyberg** [comment]
One other point: we should have some way of letting the user know that they're using the implicit global and how to change the snapshot it uses.

**Comment by netroby** [comment]
A default gloabl config file were good .

I pefered using stack to auto install ghc and packages automatic.

so , when i need run ghci anywhere, I just want to type  ```stack ghci```

**Comment by chrisdone** [comment]
Implemented in afb074e. Now if I run `stack ghc` it'll say this:

```
chris@retina:~$ stack ghc -- X.hs -o x.hs
Using latest snapshot resolver: lts-2.14
Writing global (non-project-specific) config file to: /home/chris/.stack/global/stack.yaml
Note: You can change the snapshot via the resolver field there.

X.hs:3:8:
    Could not find module ‘Lucid’
    Use -v to see a list of the files searched for.
chris@retina:~$ stack ghc -- X.hs -o x.hs

X.hs:3:8:
    Could not find module ‘Lucid’
    Use -v to see a list of the files searched for.
```

(Subsequent runs don't warn about this.)

Then I can go ahead and change the resolver in my stack.yaml to be lts-2.9 (which is what my `~/Work/stack/stack.yaml` has), and now it compiles:

```
chris@retina:~$ stack ghc -- X.hs -o x.hs
[1 of 1] Compiling Main             ( X.hs, X.o )
Linking x.hs ...
chris@retina:~$ 
```

And I can load up GHCi and load Lucid happily:

```
chris@retina:~$ stack ghci
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
Loading package ghc-prim ... linking ... done.
Loading package integer-gmp ... linking ... done.
Loading package base ... linking ... done.
Prelude> import Lucid
Prelude Lucid> 
```

Alternatively, if I want a separate global snapshot, I want to use the latest 2.14 one, then I can install lucid into that instead:

```
chris@retina:~$ stack install lucid
text-1.2.0.6: configure
text-1.2.0.6: build
text-1.2.0.6: install
hashable-1.2.3.2: downloading
blaze-builder-0.4.0.1: downloading
hashable-1.2.3.2: configure
blaze-builder-0.4.0.1: configure
hashable-1.2.3.2: build
blaze-builder-0.4.0.1: build
hashable-1.2.3.2: install
blaze-builder-0.4.0.1: install
unordered-containers-0.2.5.1: downloading
unordered-containers-0.2.5.1: configure
unordered-containers-0.2.5.1: build
unordered-containers-0.2.5.1: install
lucid-2.9.2: configure
lucid-2.9.2: build
lucid-2.9.2: install
Completed all 5 actions.
chris@retina:~$ stack ghc -- X.hs -o x.hs
[1 of 1] Compiling Main             ( X.hs, X.o )
Linking x.hs ...
```

**Comment by chrisdone** [comment]
@snoyberg Can you review? https://github.com/commercialhaskell/stack/commit/afb074e5e0efebdcd49949ac80c58d8249961961 Pretty simple but I might've missed something.

**Comment by snoyberg** [comment]
This doesn't look right. Running `stack build` outside of a project succeeds when it shouldn't.

**Comment by snoyberg** [comment]
Recent commits fixed all issues with this, closing.
