### ISSUE TITLE
Windows: Suggest add to PATH directory with mingw64 DLLs

### ISSUE THREAD

**Issue by Sorokin-Anton** [commercialhaskell/stack#5901]
When I install executable that depends on some FFI (e.g. https://github.com/serokell/xrefcheck) using `stack install` and then  try to run executable `xrefcheck.exe` from cmd, it exits with popup `System Error: The code execution cannot proceed because libstdc++-6.dll was not found.`. If I try to run it from powershell, it silently exits with no output (which was really confusing, because this is what I tried to do first). 
But if I run it with `stack run` or `stack exec xrefcheck.exe`, it runs correctly. 
Also it runs correctly if I add `%LocalAppData%\Programs\stack\x86_64-windows\msys2-<...>\mingw64\bin` to PATH
I think we should add some information about this to users manual, or warn user (like we're warning him when dir with executable is not on PATH)

**Comment by mpilgrem** [comment]
I'll add something to the online help. The current content, being:

> `stack exec` works by providing the same reproducible environment that was used to build your project to the command that you are running. Thus, it knew where to find `helloworld-exe` even though it is hidden in the `.stack-work` directory.

(a) is a little terse (b) does not explain that, on Windows, MSYS2 and its supplied C libraries is part of the 'same reproducible environment' and (c) is not express that if you run an executable outside of that environment, it will not work if it depends on things are only in that environment.

I have also noted that the `stack run` command is undocumented online.

**Comment by mpilgrem** [comment]
@Sorokin-Anton, thanks for raising the issue. The addition is now live at: https://docs.haskellstack.org/en/stable/GUIDE/#the-stack-exec-command.

**Comment by Sorokin-Anton** [comment]
@mpilgrem IMHO it would be better to update this part of online help https://docs.haskellstack.org/en/stable/developing_on_windows/

**Comment by mpilgrem** [comment]
@Sorokin-Anton, I have added something there too: https://docs.haskellstack.org/en/stable/developing_on_windows/.
