### ISSUE TITLE
Doesn't respect --no-install-ghc

### ISSUE THREAD

**Issue by ulidtko** [commercialhaskell/stack#5902]
### Steps to reproduce

Select a version of GHC you *don't* have installed anywhere; I picked 8.8.2 for example.

1. `cd /tmp`
2. `stack new acme && cd acme`
3. `echo 'resolver: ghc-8.8.2' > stack.yaml`
4. `stack setup --no-install-ghc`

### Expected

Bail out with an error like so:

```
No compiler found, expected minor version match or newer with ghc-8.8.2 (x86_64-tinfo6) (based on resolver setting in /tmp/acme/stack.yaml).
To install the correct GHC into /home/ulidtko/.stack/programs/x86_64-linux/, try running "stack setup" or use the "--install-ghc" flag. To use your system GHC installation, run "stack config set system-ghc --global true", or use the "--system-ghc" flag.
```

### Actual

Download & installation proceeds regardless of `--no-install-ghc` and `install-ghc: false` in `~/.stack/config.yml`:

```
 /t/acme> stack setup --no-install-ghc
Preparing to install GHC (tinfo6) to an isolated location.
This will not interfere with any system-level installation.
ghc-tinfo6-8.8.4: download has begun^C  
```
— contrary to [as documented](https://docs.haskellstack.org/en/v2.9.1/yaml_configuration/#install-ghc).

### Stack version

Tested on 5 builds:
 * 2.7.5 from Archlinux community repo
 * 2.9.1 from official releases here on github (`stack-2.9.1-linux-x86_64-bin`), on Archlinux
 * 2.7.5 from `ghcup` on Ubuntu 22.04 LTS
 * 2.9.1 from `ghcup` on Ubuntu 22.04 LTS 
 * 2.3.3 from stock apt repository on Ubuntu 22.04 LTS — `apt install -y haskell-stack`

— with exact same results.

Each respective build's `stack --version | head -n1` detailed below:

~~~text
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 (dirty) (8407 commits) x86_64
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
Version 2.7.5, Git revision ba147e6f59b2da75b1beb98b1888cce97f7032b1 x86_64 hpack-0.34.4
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
2.3.3 x86_64
~~~

**Comment by mpilgrem** [comment]
@ulidtko, I think that behaviour is intentional, but undocumented. That is, if you command `stack setup`, Stack **will** setup GHC, as commanded. However, it would probably be best if it warned that `--no-install-ghc` is incompatible with the `setup` command and did nothing.

It is definitely intentional that the use of the GHCup script 'hook' to override the Stack-supplied management of GHC ignores `--no-install-ghc`. See https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-installation-customisation.

**Comment by hasufell** [comment]
> It is definitely intentional that the use of the GHCup script 'hook' to override the Stack-supplied management of GHC ignores --no-install-ghc.

I wouldn't say it's ignored.

Usually, when the script hook fails, stack will fall back to install it on its own.

With `--no-install-ghc` it now will fail early.

**Comment by ulidtko** [comment]
Thanks for tackling this @mpilgrem :pray: I've tested your PR and commented there.

Just learned of the ghc install hook today (and that it requires `system-ghc: false`), will give it another try.
