### ISSUE TITLE
Separate containers for executables

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack#591]
I'd like to have different containers for my executables.

The rational behind this is that I put packages in one project that somehow logically fit together (e.g. a web scraper and a webservice presenting the scraped data) but imho it really would make more sense to have separate images for this. Obviously I could have one image and then use different containers which start separate executables but since they don't really share anything I feel like having separate images here is better.

**Comment by dysinger** [comment]
ok.  Let's just talk about how the config might look @cocreature.  Seems reasonable as long as there is still a simple path.

**Comment by borsboom** [comment]
The latest version of Stack supports this.  You can now specify multiple images, each of which can have a list of executables to include.  See the [docs](http://docs.haskellstack.org/en/v1.0.2/yaml_configuration.html#image).
