### ISSUE TITLE
Can't run `stack ghci` for library only in library+executable project

### ISSUE THREAD

**Issue by w3rs** [commercialhaskell/stack#592]
Consider this cabal file:

```
name:                test
version:             0.1.0.0
build-type:          Simple
cabal-version:       >=1.10

library
  exposed-modules: Test
  build-depends:       base
  hs-source-dirs:      src
  default-language:    Haskell2010

executable runtest
  build-depends:       base, test
  hs-source-dirs: runtest
  default-language:    Haskell2010
  main-is: RunTest.hs
```

`stack ghci -v` produces this ghci call:

> ghc --interactive -hide-all-packages -itest/ -itest/src/ -itest/.stack-work/dist/x86_64-linux/Cabal-1.22.2.0/build/autogen/ -optP-include -optPtest/.stack-work/dist/x86_64-linux/Cabal-1.22.2.0/build/autogen/cabal_macros.h -package=base -itest/runtest/ **-package=test** test/src/Test.hs

(paths converted  to local, emphasis added)

Same if I run `stack ghci test -v`

As you can see, it wants to compile `test` library with `-package=test`, so if the package is not built, it outputs:

> `<command line>: cannot satisfy -package test`

Expected behavior would be act like `cabal repl` which would add `-package=test` only if given executable as a target: `cabal repl runtest`

I can't even bypass this problem with `--no-load` - it still adds `-package=test` to ghci args.

**Comment by cocreature** [comment]
I think this should be fixed by #536.

**Comment by chrisdone** [comment]
Yep, I'm merging that in now.

**Comment by chrisdone** [comment]
Okay, would you like to retry this?

**Comment by w3rs** [comment]
@chrisdone thanks! I can confirm the problem is fixed.

However, now `stack ghci runtest` (executable) doesn't `test` library as a package, so this occurs:

>
$ stack ghci runtest
ghci> :l runtest/Main.hs 
runtest/Main.hs:2:8:
    Could not find module ‘Test’
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
>

This works though:

> $ stack ghci test runtest

If this behavior is intentional, let's close the issue

**Comment by chrisdone** [comment]
You can't pass cabal targets to `stack ghci`, only package names.

**Comment by w3rs** [comment]
Ok, I'm closing this issue.
