### ISSUE TITLE
Consider dropping support for cabal 1.x and GHC less than 8.0

### ISSUE THREAD

**Issue by theobat** [commercialhaskell/stack#5924]
Considering that cabal 2.0 was released in 2017, I think it's time for stack to drop support for cabal 1.x, as there are many places where the logic is heavy because of cabal 1.x.

The same goes for GHC less than 8.0, I believe many tools in the haskell ecosystem, EDIT (unfinished sentence lol) : have already taken this decision.

Another aspect to this is, it would be a good behavior to clarify a systematic policy regarding the supported versions for both tools.

**Comment by mpilgrem** [comment]
By way of historical context, and perhaps precedent, when Stack 2.1.1 was released on 2019-06-13, it dropped Cabal versions < 1.18.2 and, consequently, LTS < 3.0. LTS 2.22 (GHC 7.8.4, released 2014-12-23) came with Cabal-1.18.1.5, released 2014-12-15. So, the things that were then dropped were about four and half years old.

GHC 7.10.3 was released 2015-12-08. GHC 8.0.2 was released 2017-01-11. Cabal >= 2 was first shipped with GHC 8.2.1, which was released 2017-07-22. So, dropping Cabal < 2 and GHC < 8.2.1 today would be dropping things that are over five years old.

@theobat, I see you use Haskell Community (https://discourse.haskell.org/). Why don't you canvas your suggestion there, to see if there is any immediate/strong reaction against it? It will get a wider audience there than here.

**Comment by mpilgrem** [comment]
On 'policy', looking to see what others do, the `Cabal` repository seems to think in terms of 'five years'.

Perhaps a policy could be put in these terms: "The most recent release of Stack will aim to support all versions of GHC and the Cabal package in Stackage snapshots published within five years."

However, that would clash with @theobat's suggestion, as it would support LTS 9.12 released on 2017-11-05 (GHC 8.0.2 and `Cabal-1.24.2.0`).

Dialling back to four years would support LTS 12.17 released on 2018-11-05 (GHC 8.4.4 and `Cabal-2.2.0.1`).

**Comment by hasufell** [comment]
This probably needs some discussion with stackage maintainers?

**Comment by mpilgrem** [comment]
I have put the 'five years' proposal to the #stack-collaborators channel of the Haskell Foundation's Slack workspace, to see if anybody objects.

**Comment by mpilgrem** [comment]
Closing as it was, ultimately, overtaken by https://github.com/commercialhaskell/stack/issues/6377.
