### ISSUE TITLE
Addition of '--exec-always' flag: a '--exec' that runs even on build failure

### ISSUE THREAD

**Issue by xave** [commercialhaskell/stack#5925]
**Introduction**

There are times when one would like to use `--exec` even when the build fails. As an example, imagine running 
`stack build ... --exec 'do-stuff-with-error-messages-on-stdout.sh  input.txt' --file-watch"`. In this scenario, we want to process the stdout that was generated every time `--file-watch` causes a rebuild. 

With the current `--exec` flag implementation, that shell script would only run on a successful build. Yet since it is doing something with the error messages, it would be useful to have it run even on failure as that would ultimately help the programmer make the build succeed in this case. 

**Proposal**

The proposal is a new flag `--exec-always` that can execute even if the build fails and also while the `--file-watch` flag has been passed. This would go a long way to helping people build their own tooling workflows around `stack`.

**Comment by mpilgrem** [comment]
@xave, is there any interaction between your idea and the existing `--[no-]keep-going` flag?

**Comment by xave** [comment]
I don't think so.

I get a `Process exited with code: ExitFailure 1` on some broken code in either case. I would imagine that the `--keep-going` flag would continue without that behavior. Or if that isn't expected behavior, this highlights the need for this feature request as I don't mind the build exiting suddenly; I just need things to happen whether it fails or succeeds.

**Comment by mpilgrem** [comment]
@xave, if `--exec <do_something>` does something if, and only if, the build succeeds, do you want `--on-fail <do_something_else>` that only does something if, and only if, the build does not succeed?

**Comment by xave** [comment]
Yes.

**Comment by mpilgrem** [comment]
The following are some notes for myself, thinking about this:

The `--exec` commands are `proc`-ed at the end of `Stack.Build.Execute.executePlan`, presumably they are not reached if an exception is thrown beforehand. I suppose the `--on-fail` commands need to be `proc`-ed after the exception has been thrown and dealt with, because otherwise there is nothing in the output to process.

~~~haskell
-- | Perform the actual plan
executePlan :: HasEnvConfig env
            => BuildOptsCLI
            -> BaseConfigOpts
            -> [LocalPackage]
            -> [DumpPackage] -- ^ global packages
            -> [DumpPackage] -- ^ snapshot packages
            -> [DumpPackage] -- ^ local packages
            -> InstalledMap
            -> Map PackageName Target
            -> Plan
            -> RIO env ()
executePlan boptsCli baseConfigOpts locals globalPackages snapshotPackages localPackages installedMap targets plan = do
    logDebug "Executing the build plan"
    bopts <- view buildOptsL
    withExecuteEnv bopts boptsCli baseConfigOpts locals globalPackages snapshotPackages localPackages mlargestPackageName
      (executePlan' installedMap targets plan)

    copyExecutables (planInstallExes plan)

    -- Deal with the `--exec` commands
    config <- view configL
    menv' <- liftIO $ configProcessContextSettings config EnvSettings
                    { esIncludeLocals = True
                    , esIncludeGhcPackagePath = True
                    , esStackExe = True
                    , esLocaleUtf8 = False
                    , esKeepGhcRts = False
                    }
    withProcessContext menv' $
      forM_ (boptsCLIExec boptsCli) $ \(cmd, args) ->
      proc cmd args runProcess_
  where
    mlargestPackageName =
      Set.lookupMax $
      Set.map (length . packageNameString) $
      Map.keysSet (planTasks plan) <> Map.keysSet (planFinals plan)
~~~

Pretty much all exceptions `e` thrown are caught and thrown again at the end of `Main.main` (extracts):

~~~haskell
  eGlobalRun <- try $ commandLineHandler currentDir progName False
  case eGlobalRun of
    ...
    Right (globalMonoid,run) -> do
      global <- globalOptsFromMonoid isTerminal globalMonoid
      ...
      withRunnerGlobal global $ run `catch` \e ->
          -- This special handler stops "stack: " from being printed before the
          -- exception
          case fromException e of
              Just ec -> exitWith ec
              Nothing -> do
                  logError $ fromString $ displayException e
                  exitFailure
~~~

I think that may mean that `--on-fail` needs to be a gobal option. If `--on-fail` is triggered by all exceptions, is there any benefit of having it 'within Stack'? If it is not triggered by all exceptions, which exceptions should trigger it?

**Comment by xave** [comment]
What part of the codebase would one inspect to make this change happen?

**Comment by mpilgrem** [comment]
@pbrisbin, if what you are (or were) seeking is:
~~~
> stack build ... --exec foo-bar --on-fail foo-bar
~~~

then why not just chain the commands? (eg PowerShell)
~~~
> stack build ...; foo-bar
~~~

or (if `foo-bar` needs to run in the Stack environment):
~~~
> stack build ...; stack exec -- foo-bar
~~~

That is, is executing a sequence of commands not simply something for the shell?

**Comment by mpilgrem** [comment]
@xave, the handling of exceptions currently occurs at the end of `Stack.main`. The current code has moved on from what I posted above. It now reads (extracts):
~~~haskell
  eGlobalRun <- try $ commandLineHandler currentDir progName False
  case eGlobalRun of
    ...
    Right (globalMonoid, run) -> do
      global <- globalOptsFromMonoid isTerminal globalMonoid
      ...
      withRunnerGlobal global $ run `catches`
        [ Handler handleExitCode
        , Handler handlePrettyException
        , Handler handlePantryException
        , Handler handleSomeException
        ]
~~~

**Comment by mpilgrem** [comment]
@pbrisbin, I see: I had missed the `--file-watch` context from your original post. The relevant code for that is at the end of `Stack.FileWatch.fileWatchConf`:
~~~haskell
eres <- tryAny $ inner setWatched
...
case eres of
  Left e ->
    case fromException e of
      Just ExitSuccess ->
        prettyInfo $ style Good $ fromString $ displayException e
      _ -> case fromException e :: Maybe PrettyException of
        Just pe -> prettyError $ pretty pe
        _ -> prettyInfo $ style Error $ fromString $ displayException e
 _ -> prettyInfo $
   style Good (flow "Success! Waiting for next file change.")
~~~

I am wondering about the following idea, and interested in your views.

Stack has a 'hook' mechanism for GHC installation customisation: https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-installation-customisation. The customisation kicks in if you put a `sh` shell script in `hooks/ghc-install.sh`.

How about another 'hook' mechanism for `--file-watch` to customise what it does when the build is complete (including if it ends in failure)? The customisation could kick in if you put a `sh` shell script in (say) `hooks/file-watch.sh`.

**Comment by xave** [comment]
This hook idea seems interesting. How might that affect the way the watch behavior works now? In other words, if we were to move forward with this idea, would everyone have to put a script in that directory to get the functionality already provided by `stack` today?

**Comment by mpilgrem** [comment]
I was thinking that if there was no 'hook' shell script, `--file-watch` would do what it always does and if there was a script `--file-watch` would use it.

**Comment by xave** [comment]
> I probably wouldn't call it hooks/file-watch.sh for a number of reasons: any executable file should do, so .sh should not be required. 

Agreed.

**Comment by mpilgrem** [comment]
@pbrisbin, taking your comments in reverse order, how about:

* the location of the `file-watch-hook` is configurable, as a non-project-specific configuration? If the specified location is relative, it is assumed to be relative to the project root directory.

* on Windows, if the specified hook file ends with `.sh` it is assumed it should be run with `sh`, otherwise it is assumed to be an executable. On Unix-like operating systems, the specified hook file needs to be marked as executable.

In respect of something broader in its ambition than `stack build --file-watch`, the 'problem' as I see it is that, currently, with `--file-watch`, all `stack build` exceptions are handled in one place and, without `--file-watch`, all `stack` exceptions (`build`-related or otherwise) are handled in one place. There is nothing that distinguishes exceptions thrown during building from other exceptions.

As you have identified 'command chaining' does not work with `stack build --file-watch` because the Stack command never terminates, however it seems to me that it is viable outside of that context, because the Stack command comes to an end and the next command can take over.

**Comment by pbrisbin** [comment]
All sounds good to me, I don't have very strong opinions in this are generally.

> I had assumed the mechanism would be environment variables

If that's how the only existing hook works, it makes sense to be consistent. I was just modeling after `git`, which (absent other points in the design space) seemed like a good idea.

**Comment by mpilgrem** [comment]
I've tried to implement this: if not using GHCup to manage Stack, use `stack upgrade --source-only --git-branch fix5925` to test it. See https://github.com/commercialhaskell/stack/pull/6597.

**Comment by xave** [comment]
Thank you. I’ll give it a spin.

**Comment by mpilgrem** [comment]
@xave, for your information, I am thinking of releasing Stack "3.1.1" soon, and whether or not it includes this may depend on your experience of it.

**Comment by xave** [comment]
Thank you @mpilgrem! I have tested it out as follows:

Added this line to stack.yaml
```
file-watch-hook: "./sample.sh"
```
My use-case is automatically populating `vim` quickfix with errors upon build failure. So I would run the command like:

```
stack build --filewatch 2>&1  | tee tmp.txt
```

And the `sample.sh` would do some sort of processing of `tmp.txt` on build failure. At the moment, I just have (based off your sample script in the commit):

```
#!/bin/sh

set -eu

if [ -z "$HOOK_FW_RESULT" ]; then
	echo "XXSuccess! Waiting for next file change."  <----Sanity check that I could change the default message
else
	echo "Build failed with exception:"
	echo $HOOK_FW_RESULT
	cat tmp.txt >quickfix.txt    <---- Some basic modifications of a file
	>tmp.txt                              <---- Some basic modifications of a file
fi
```

----

This feature does everything I desire. Thank you.

**Comment by xave** [comment]
_Addendum_: I have tried adding the same to the global `stack.yaml`, `~/.stack/global-projects/stack.yaml`, but got no result. In the case of working with a shared repo, it is possible that not everyone would want the same script. 

It would thus also be nice to be able to set this in the global `stack.yaml` instead of the project one and have it apply to one machine only without having to burden a team or other collaborators.

**Comment by mpilgrem** [comment]
@xave, thanks for the feedback.

On your addendum, the project-level configuration file (`stack.yaml`) in the `global-project` in the Stack root is not for 'global' configuration; it is for when you use Stack outside of a project. Non-project-specific options in that file are ignored.

The file (or files, on Unix-like operating systems) for 'global' non-project specific options is `config.yaml`.

See: https://docs.haskellstack.org/en/stable/yaml_configuration/#yaml-configuration

**Comment by xave** [comment]
@mpilgrem, I had also tried the `config.yaml` location. In either spot, the message is the same:

```
Warning: File watch hook not executable. Falling back on default.
```

The entry has the full filepath written out for the global `config.yaml`, and the script  used is the same one in the same location as before.

**Comment by xave** [comment]
I'm using `ghcup`, so I compiled this `stack` from source. Likely some wires crossed w.r.t global config settings. I'll keep an eye out once the feature is released.
