### ISSUE TITLE
`stack install hakyll` doesn't work on macs

### ISSUE THREAD

**Issue by radix** [commercialhaskell/stack#594]
hakyll (optionally) depends on fsnotify, which, on macs, needs hfsevents.

hfsevents isn't available on stackage, though hakyll and fsnotify are. So if I try to install hakyll on my mac, I get the following output:

```
radix@purity:~$ stack install hakyll
Using resolver: lts-2.14 from global config file: /Users/radix/.stack/global/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:    
      hfsevents: needed (>=0.1.3), latest is 0.1.5, but not present in build plan
    needed for package: fsnotify-0.1.0.3

--  Failure when adding dependencies:    
      fsnotify: needed (>=0.1 && <0.2), latest is 0.1.0.3, but couldn't resolve its dependencies
    needed for package: hakyll-4.6.9.0

--  While attempting to add dependency,
    Could not find package hfsevents in known packages

Recommended action: try adding the following to your extra-deps in /Users/radix/.stack/global/stack.yaml
- hfsevents-0.1.5

You may also want to try the 'stack solver' command
```

Also, if I try to disable the flags that cause hakyll to depend on fsnotify, it doesn't work:

```
radix@purity:~$ stack install --flag hakyll:-previewServer --flag hakyll:-watchServer hakyll
```
(same output follows)

I suppose this may be two issues, but I'm not really sure if the first part is a stack issue or not. I created this ticket at the Michael's request; it may need to be refined after some discussion.

**Comment by snoyberg** [comment]
One thing to consider is to have a hard-coded list of packages like hfsevents which is not built/tested by the Stackage run, but included in the build plan anyway. Another option would be to whitelist those packages at the stack level instead. I don't have a thought on the right way to do things, so I'm very interested in other opinions.

**Comment by radix** [comment]
It seems like Stackage ought to have a way to support non-linux packages to be truly useful for everyone. But I guess setting up Windows and Mac OS builders is a pretty big undertaking :)

**Comment by radix** [comment]
Should there be a separate issue about --flag not working with `install`? or is that not expected to work?

**Comment by snoyberg** [comment]
It's expected to not work currently, because we don't ever modify the snapshot plan. The argument could be made that, when explicitly choosing a package on the command line, it should be considered a local package whose flags can be modified. Probably worth opening an issue for discussing that change.

**Comment by manny-fp** [comment]
Can stackage add support for build plan variants for different platforms?  E.g., on OS X it would pass an extra flag to hakyll (and/or include hfsnotify but leave out hinotify)?

**Comment by snoyberg** [comment]
It could, but I'd consider that a bad idea: now we'll have competing definitions of "nightly-2015-07-21", for instance. My recommendation: we modify stackage-curator to support "in the build plan but not tested," and add the relevant OS X and Windows packages automatically. Any objection to that?

**Comment by manny-fp** [comment]
Seems like it would work.  And just having been trying to think of more comprehensive solutions, every one of them runs into similar problems: using a snapshot on one platform doesn't absolutely guarantee that snapshot will work on other platforms, at least if we want to support the idea of something like hinotify being in a snapshot at all (making the OS a part of the snapshot name is no solution, that would make cross-platform development a huge pain).

**Comment by manny-fp** [comment]
Added stackage-curator issue for this: https://github.com/fpco/stackage-curator/issues/3

**Comment by manny-fp** [comment]
This is fixed in stackage-curator.  @snoyberg, am I right that this will take effect in new nightly Stackage snapshots, but not in new lts-2.x snapshots?

**Comment by snoyberg** [comment]
That is correct. Starting with the next nightly release (and stack's master code), it should be possible to run `stack install --resolver nightly hakyll`.
