### ISSUE TITLE
Time-out on Windows

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#596]
Stack 0.1.1.0 Windows 8.1 x64 behind proxy which is set in HTTPS_PROXY and HTTP_PROXY.

It is strange that first stages are always passing and the last one doesn't.
```
C:\Users\user>stack upgrade
Updating package index Hackage (mirrored at https://github.com/commercialhaskell

Fetched package index.
Populated index cache.
FailedConnectionException2 "s3.amazonaws.com" 443 True connect: failed (Connecti
on timed out (WSAETIMEDOUT))
```

On my machine it is situated in: C:\Users\user\AppData\Roaming\cabal\bin
When I copy latest 0.1.2.0 by hand it works:
```
C:\Users\user>stack upgrade
Updating package index Hackage (mirrored at https://github.com/commercialhaskell

Fetched package index.
Populated index cache.
Already at latest version, no upgrade required
```

**Comment by snoyberg** [comment]
Can you rerun with `-v`?

**Comment by varosi** [comment]
Since I have only the latest version now, I have tryed with stack install and here it is the result:
```
C:\Users\user>stack install stack -v
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
2015-07-17 15:32:30.0576922: [debug] Checking for project config at: C:\Users\us
er\stack.yaml @(stack-0.1.2.0:Stack.Config src/Stack\Config.hs:496:9)
2015-07-17 15:32:30.0593442: [debug] Checking for project config at: C:\Users\st
ack.yaml @(stack-0.1.2.0:Stack.Config src/Stack\Config.hs:496:9)
2015-07-17 15:32:30.0593442: [debug] Checking for project config at: C:\stack.ya
ml @(stack-0.1.2.0:Stack.Config src/Stack\Config.hs:496:9)
2015-07-17 15:32:30.0593442: [debug] No project config file found, using default
s. @(stack-0.1.2.0:Stack.Config src/Stack\Config.hs:523:13)
FailedConnectionException2 "s3.amazonaws.com" 443 True connect: failed (Connecti
on timed out (WSAETIMEDOUT))
```

**Comment by snoyberg** [comment]
It doesn't look to me like it's using the proxy. Can you try setting the environment variable names as lower case instead?

**Comment by varosi** [comment]
It works with lower case lettes!

But under Windows it is the same. Environment variable names are case-insensitive. So "HTTPS_PROXY", "https_proxy" and "HTTPS_proxy" are the same and it doesn't distinguish differences. The same is for file names, too.

**Comment by snoyberg** [comment]
That change makes sense. Can you open an issue on the http-client repo, where that would be handled?

**Comment by varosi** [comment]
Okay, 10x!
