### ISSUE TITLE
Permission error during stack upgrade 2.5.1 -> 2.9.1 on Windows 

### ISSUE THREAD

**Issue by adamburkegh** [commercialhaskell/stack#5968]
### General summary/comments

Upgrade fails on Windows due to a permission error for a file move operation late in the install. Workaround included.

### Steps to reproduce

Was upgrading an existing install from stack 2.5.1 to 2.9.1 as part of changing the `stack.yaml` resolver from 

```
url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/22.yaml
```

to `resolver: lts-18.19`

Tried under git bash cygwin and windows command prompt first. Here is the output from windows command prompt with admin:

```txt
c:\somepath>stack upgrade
Current Stack version: 2.5.1, available download version: 2.9.1
Newer version detected, downloading
Querying for archive location for platform: windows-x86_64-static
Querying for archive location for platform: windows-x86_64
Downloading from: https://github.com/commercialhaskell/stack/releases/download/v2.9.1/stack-2.9.1-windows-x86_64.tar.gz
Download complete, testing executable
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0

Warning: Installation path C:\Users\Adam\AppData\Roaming\local\bin not found on the PATH environment variable.
New stack executable available at C:\Users\Adam\AppData\Roaming\local\bin\stack.exe
Also copying stack executable to C:\working\tools\stack\bin\stack.exe
Permission error when trying to copy: C:\working\tools\stack\bin\stack.exe.tmp: renameFile:renamePath:MoveFileEx "\\\\?\\C:\\working\\tools\\stack\\bin\\stack.exe.tmp" Just "\\\\?\\C:\\working\\tools\\stack\\bin\\stack.exe": permission denied (Access is denied.)
Should I try to perform the file copy using sudo? This may fail
Try using sudo? (y/n) y
Going to run the following commands:

-  sudo cp C:\Users\Adam\AppData\Roaming\local\bin\stack.exe C:\working\tools\stack\bin\stack.exe.tmp
-  sudo mv C:\working\tools\stack\bin\stack.exe.tmp C:\working\tools\stack\bin\stack.exe
Executable named sudo not found on path: [...]
```

Sure enough the directory will show an old `stack.exe` file and a new `stack.exe.tmp` file.

The file permissions were fine, and as I said I reran with admin.

### Stack version

Old version: 2.5.1, fixed before getting the full version string.

New version
~~~text
Version 2.9.1, Git revision 409d56031b4240221d656db09b2ba476fe6bb5b1 x86_64 hpack-0.35.0
~~~

Windows 10 version 21H2 (OS Build 19044.2251)

As this is a stack upgrade bug I am politely ignoring the request to test on the latest version.

### Method of installation

* Official binary, downloaded via haskellstack.org or from Stack's repository

### Workaround

My workaround was to put a file called `sudo.bat` in the stack installation target directory. `C:\working\tools\stack\bin\`. 

`sudo.bat`:
~~~bat
%*
~~~

This executes the arguments as a command, obviously without any of the elevated permissions you would usually get with sudo, which doesn't exist on Windows.

As inconsistent file operations are a recurring theme on Windows, I am raising the issue to at least document a workaround for others on the platform, or to track if others run into it.

### Similar issues

The issue is similar to [1917](https://github.com/commercialhaskell/stack/issues/1917) and [2426](https://github.com/commercialhaskell/stack/issues/2426), but the exact error is different, and the workarounds mentioned in those, such as disabling virus check, or moving files around, didn't work for me.

**Comment by mpilgrem** [comment]
@adamburkegh, thanks for reporting. I had a look at the underlying code.

I understand that the permissions problem arises (at least, primarily) because, on Windows, you can rename the file of a running executable, but you can't overwrite it. That seems to be recognised in the existing code in `Stack.Setup.downloadStackExe` (extract):
~~~haskell
      case platform of
          Platform _ Cabal.Windows | FP.equalFilePath (toFilePath destFile) currExe -> do
              old <- parseAbsFile (toFilePath destFile ++ ".old")
              renameFile destFile old
              renameFile tmpFile destFile
          _ -> renameFile tmpFile destFile
~~~

but (strangely) not at `Stack.Setup.performPathChecking`, where it matters just as much (extract):
~~~haskell
tmpFile <- parseAbsFile $ executablePath ++ ".tmp"
    eres <- tryIO $ do
      liftIO $ copyFile newFile tmpFile
      setFileExecutable (toFilePath tmpFile)
      liftIO $ renameFile tmpFile executablePath'
~~~

I have a pull request #5968 that I think fixes this (I am about to write it up), but I am able to test it only on Windows. I need to find somebody who can test it does not break non-Windows Stack. The pull request also makes the 'sudo' interactions relevant only to non-Windows versions of Stack.
