### ISSUE TITLE
Prepare for Git endpoints support

### ISSUE THREAD

**Issue by danse** [commercialhaskell/stack#597]
Hello, i want to point out early that Git endpoints are a main feature for any dependency management tool, in my opinion.

They make shared resources [a breeze when using Npm](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies), and they can be a solution to the problem of a cluttered Hackage, among other benefits. A dev or a company can keep its shared components on Github for a long time, versioned with tags, before feeling the need or the advantage of publishing them on Hackage. 

Github is a de facto standard nowadays, and it provides a kind of public, powerful index for shared software, with effective namespacing. Different dependency management systems integrate with Git endpoints more or less smoothly, but a system developed now cannot ignore this.

It is easier to ask for forgiveness than for permission, so i ask to forgive me if i am posing this question in the wrong place or in the wrong terms. Maybe this is already supported by Cabal and i just need to learn how it works, but in the doubt i just wanted to raise the topic it in the early stages of development of Stack

**Comment by snoyberg** [comment]
This is already supported (unless I'm misunderstanding what you mean by endpoints). Check out the docs at: https://github.com/commercialhaskell/stack/wiki/stack.yaml#packages

**Comment by danse** [comment]
Great!
