### ISSUE TITLE
Provide 32-bit precompiled Linux binaries.

### ISSUE THREAD

**Issue by ntc2** [commercialhaskell/stack#598]
Like with Windows, I suggest you provide e.g.
```
stack-0.1.2.0-i386-linux.gz
stack-0.1.2.0-x86_64-linux.gz
```
on the releases page.

**Comment by drwebb** [comment]
I was building Arch 32-bit versions, but am currently dropping support for the short term. We are basically moving to building the releases inside Docker images, and intend to release 0.2.0.0 64-bit only. This may change in the future, and pining @manny-fp because he is a little more up on Docker than I am.

**Comment by manny-fp** [comment]
For the binaries on the Github release, we don't currently use Docker so it's not too difficult to build 32-bit binaries in addition to 64-bit in that case.  However, this is the first request I've heard for 32-bit linux binaries, so I'd appreciate getting a sense of how many people would find 32-bit binaries useful before we start doing that for every release.

Aside: I'm planning to move away from Docker and just use Vagrant for every platform in the release tool, and also automate using Vagrant for Github release binaries, at which point automating this will be easier.  We could then also provide 32-bit debs, RPMs, and Arch packages.

**Comment by PierreGambarotto** [comment]
+1 for 32 bits linux binaries, to use in 32 bits containers (openvz). Thanks in advance

**Comment by manny-fp** [comment]
I've added a 32-bit binary to https://github.com/commercialhaskell/stack/releases/tag/v0.1.2.0, and will do so for future releases as well.
