### ISSUE TITLE
`stack script` and `no-install-ghc`/`system-ghc`

### ISSUE THREAD

**Issue by jeapostrophe** [commercialhaskell/stack#5986]
In my `~/.stack/config.yaml`, I have
```
install-ghc: false
system-ghc: true
```

I have a script that uses `stack script`:
```
#!/usr/bin/env stack
{- stack script
 --optimize
 --ghc-options -Wall
 --resolver    lts-20.2
 --package     directory
 --package     filepath
 --package     split
 --package     time
 --package     safe
 -}
```

But when I run it, it tries to install GHC. I've tried to modify the script:

```
#!/usr/bin/env stack
{- stack script
 --no-install-ghc
 --system-ghc
 --optimize
 --ghc-options -Wall
 --resolver    lts-20.2
 --package     directory
 --package     filepath
 --package     split
 --package     time
 --package     safe
 -}
```

But it still tries to download.

I've also tried to use `--stack-yaml`, but I get:
```
Ignoring override stack.yaml file for script command: ~/.stack/config.yaml
```

Does `stack script` not support these options at all or am I doing something wrong?

**Comment by mpilgrem** [comment]
I think `stack script` ignores all Stack YAML configuration files, including `config.yaml`. That is based on https://docs.haskellstack.org/en/stable/scripts/#stack-configuration-for-scripts.

I also think that `stack script` acts as if `install-ghc: true`. That is based on this part of `Stack.Script.scriptCmd`:
~~~Haskell
    let scriptDir = parent file
        modifyGO go = go
            { globalConfigMonoid = (globalConfigMonoid go)
                { configMonoidInstallGHC = FirstTrue $ Just True
                }
            , globalStackYaml = SYLNoProject $ soScriptExtraDeps opts
            }
 ...
    local (over globalOptsL modifyGO) $
~~~

and the discussion here about how `stack runghc` can be made to mimic `stack script` https://docs.haskellstack.org/en/stable/scripts/#writing-independent-and-reliable-scripts

Do you have the version of GHC that `lts-20.2` needs (GHC 9.2.5) on your PATH? I am assuming that it respects `system-ghc`, but I may be wrong.

**Comment by mpilgrem** [comment]
I have updated Stack's online documentation and also checked that `stack script` does respect `--system-ghc`.

**Comment by jeapostrophe** [comment]
Thank you!
