### ISSUE TITLE
[msys2] the stack supplied msys2 requires upgrading

### ISSUE THREAD

**Issue by shayne-fletcher** [commercialhaskell/stack#5988]
This issue looks very similar to https://github.com/commercialhaskell/stack/issues/5732. I observe from https://www.msys2.org/ there has been a new release [msys2-x86_64-20221216.exe](https://github.com/msys2/msys2-installer/releases/download/2022-12-16/msys2-x86_64-20221216.exe). The failure modes I observe in ghc-lib Azure CI for Windows builds right now I don't recognize but they are all broken so if this isn't the entire reason it will be at least part of it.

**Comment by shayne-fletcher** [comment]
cc @mpilgrem

**Comment by mpilgrem** [comment]
I have bumped the Stack-supplied MSYS2 to msys2-20221216. Existing installations of Stack will only fetch that version of MSYS2 if Stack cannot find a version of MSYS2, so you may need to delete any existing copies of MSYS2 flagged as installed in Stack's 'programs' directory (`stack path --programs`).

If that does not solve your problem, please post details of what you are actually experiencing.

**Comment by shayne-fletcher** [comment]
> I have bumped the Stack-supplied MSYS2 to msys2-20221216. Existing installations of Stack will only fetch that version of MSYS2 if Stack cannot find a version of MSYS2, so you may need to delete any existing copies of MSYS2 flagged as installed in Stack's 'programs' directory (`stack path --programs`).
> 
> If that does not solve your problem, please post details of what you are actually experiencing.

awesome. let me run have a little scratch around given that and I'll let you know! thanks @mpilgrem !

**Comment by shayne-fletcher** [comment]
> > I have bumped the Stack-supplied MSYS2 to msys2-20221216. Existing installations of Stack will only fetch that version of MSYS2 if Stack cannot find a version of MSYS2, so you may need to delete any existing copies of MSYS2 flagged as installed in Stack's 'programs' directory (`stack path --programs`).
> > If that does not solve your problem, please post details of what you are actually experiencing.
> 
> awesome. let me run have a little scratch around given that and I'll let you know! thanks @mpilgrem !

this has fixed the issue. thanks @mpilgrem .

**Comment by shayne-fletcher** [comment]
i spoke a little too soon but afaik the remaining problem is not one for stack https://gitlab.haskell.org/ghc/ghc/-/issues/22672.
