### ISSUE TITLE
"stack test" is not picking up changes in my source

### ISSUE THREAD

**Issue by martinvlk** [commercialhaskell/stack#599]
Hi, I have a project with separate src and test directories.

When I make changes in my source (src) and do "stack test" again, the changes I made are not detected and tests are executed with outdated binary.

Not sure if this is a bug or something I'm missing?

**Comment by chrisdone** [comment]
Can you publish the source? Changes to any source files should be picked up.

**Comment by martinvlk** [comment]
The test case I have been using is available on Github here:
https://github.com/martinvlk/cis194-homeworks

Specifically I run `stack test`, then make a change to:
https://github.com/martinvlk/cis194-homeworks/blob/master/src/HW07/JoinList.hs

and run `stack test` again - and changes are not picked up.

M.

**Comment by snoyberg** [comment]
This is a known issue, see: #481. For now, you need to ensure that all of the modules you're working on are explicitly referenced from the cabal file (which is a good idea anyway to ensure `cabal sdist` works correctly).

**Comment by snoyberg** [comment]
To avoid discussing this is two places, I'm going to close this in favor of #481. If there's something extra going on here that I missed, please reopen.

**Comment by martinvlk** [comment]
That's cool, I was just about to ask should I close this as a duplicate.. thanks!
