### ISSUE TITLE
stack exec swallows my shell variables when Docker is used

### ISSUE THREAD

**Issue by nh2** [commercialhaskell/stack#600]
When using the Docker enabled `stack`, it swallows my shell variables:

```
$ stack exec -- bash -c 'for x in 1 2 3; do echo $x; done'            



$ bash -c 'for x in 1 2 3; do echo $x; done'
1
2
3
```

The problem is inside the docker entrypoint where we use `sudo -s`, which interprets the given command too early.

Pinging @manny-fp.

**Comment by manny-fp** [comment]
I've pushed new images to all the docker repos which include a fixed entrypoint.

**Comment by nh2** [comment]
Thanks Manny!
