### ISSUE TITLE
Reproducibility of hackage packages and lock files.

### ISSUE THREAD

**Issue by philderbeast** [commercialhaskell/stack#6035]
### Location of the documentation

[hackage-packages](https://docs.haskellstack.org/en/stable/pantry/#hackage-packages)

### Is it inaccurate?

Why do you think the documentation is wrong?

The advice around reproducibility could mention lock files. If they are used then it would be sufficent to reference a package only by version wouldn't it? Is the `@sha256` still needed if committing the lock file (that has the sha256 and size already) to source control?

**Comment by hasufell** [comment]
Specifying revision number is enough for reproducibility. 

Checking hashes is a security feature.

**Comment by mpilgrem** [comment]
May I drill down on what is unclear in the existing documentation? 

Could  you follow the following existing Note?

> Specifying package using SHA256 is slightly more resilient in that it does not rely on correct ordering in the package index, while revision number is likely simpler to use. In practice, both should guarantee equally reproducible build plans.

Also, there is separate documentation on Stack's lock files (which are mentioned at the end of the passage). Are you suggesting there should be a clearer cross-reference to it?

**Comment by philderbeast** [comment]
We say, "These files ([lock files](https://docs.haskellstack.org/en/stable/lock_files/#lock-files)) **can** be stored in source control". Let's change this to say these lock files **should** be regenerated and stored in source control.

Aside: The [lock file creation](https://docs.haskellstack.org/en/stable/lock_files/#creation) example could add the `--dry-run` flag as that is all that is needed isn't it?

```diff
- stack build --stack-yaml my-stack.yaml
+ stack build --stack-yaml my-stack.yaml --dry-run
```

Going back to `extra-deps: [ hackage-package-name-x.y.z ]` (what cabal calls constraints). This "basic syntax" (and revision) should be enough as long as I regenerate and commit the lock.

For those that don't want the lock, the rest of the "Hackage packages" section could go into a note. Without putting that stuff in a note, developers are going to err on the side of caution and put `package-x.y.z@sha,size` as their dependency constraint. It is more work with no extra benefit over regenerating and committing the lock.

I'd like the docs to be clearer about what best practice is, as in, do this small thing and you're good.

**Comment by philderbeast** [comment]
When we run a build and are missing a dependency we're given and recommended the option of adding `package-x.y.z@sha,size` to `extra-deps`. Isn't this overkill if using a lock? Why isn't the recommendation to use `package-x.y.z@rev:n`, regenerate and check the lock file?

Deleting the `extra-deps` from stack's own default project.

```
$ stack build --dry-run
WARNING: Ignoring hackage-security's bounds on Cabal-syntax (>=3.7 && <3.10);
using Cabal-syntax-3.6.0.0.
Reason: trusting snapshot over Cabal file dependency information.

Error: [S-4804]
       Stack failed to construct a build plan.
       
       While constructing the build plan, Stack encountered the following errors:      
... 
       Some different approaches to resolving this:
...       
         * Recommended action: try adding the following to your extra-deps in /.../stack/stack.yaml:
       
       - Cabal-3.8.1.0@sha256:155d64beeecbae2b19e5d67844532494af88bc8795d4db4146a0c29296f59967,12220
       - fsnotify-0.4.1.0@sha256:44540beabea36aeeef930aa4d5f28091d431904bc9923b6ac4d358831c651235,2854
       - pantry-0.8.1@sha256:196111414d2489499fda6213deebcb865bc12285023d5af9bd273bf27cdb185d,4099
       - persistent-2.14.4.3@sha256:22237669897fed2b71de521bfeba7f8e0677e54992920288ae1fa8206a4711fc,7199
       - rio-prettyprint-0.1.4.0@sha256:1f8eb3ead0ef33d3736d53e1de5e9b2c91a0c207cdca23321bd74c401e85f23a,1301
```

If I add these as `package-name-x.y.z` instead there is a difference in only one hash in the lock file (a revision).

```diff
diff --git a/stack.yaml.lock b/stack.yaml.lock
index 1c8374b27..443aeb773 100644
--- a/stack.yaml.lock
+++ b/stack.yaml.lock
@@ -10,49 +10,49 @@ packages:
       sha256: f8e89e81fe0ca6e285036e04b165119ccfc59e7e668c1bfc28927f39062c5949
       size: 1280
   original:
-    hackage: fsnotify-0.4.1.0@sha256:44540beabea36aeeef930aa4d5f28091d431904bc9923b6ac4d358831c651235,2854
+    hackage: fsnotify-0.4.1.0
 - completed:
     hackage: hpack-0.35.1@sha256:ef816234cbc7b52b0a6c55f7e904b6bc5292b8dd8f2d81ffcbcbc69ab80d75e5,4762
     pantry-tree:
       sha256: 514f0311eff442ab83ef3c2db456857f360ea173c17df133e575f50915e02da0
       size: 3675
   original:
-    hackage: hpack-0.35.1@sha256:ef816234cbc7b52b0a6c55f7e904b6bc5292b8dd8f2d81ffcbcbc69ab80d75e5,4762
+    hackage: hpack-0.35.1
 - completed:
     hackage: pantry-0.8.1@sha256:196111414d2489499fda6213deebcb865bc12285023d5af9bd273bf27cdb185d,4099
     pantry-tree:
       sha256: f7032e124bda7deb3b70b0fc308e9bbe9ba6c81f79b88a1cd0b5b7932f4ab14a
       size: 2524
   original:
-    hackage: pantry-0.8.1@sha256:196111414d2489499fda6213deebcb865bc12285023d5af9bd273bf27cdb185d,4099
+    hackage: pantry-0.8.1
 - completed:
     hackage: persistent-2.14.4.3@sha256:22237669897fed2b71de521bfeba7f8e0677e54992920288ae1fa8206a4711fc,7199
     pantry-tree:
       sha256: 757771197e4ede18c33addcb4c5b6cf7cd38511b2d9f90e73f1fb41bb482f2ae
       size: 6601
   original:
-    hackage: persistent-2.14.4.3@sha256:22237669897fed2b71de521bfeba7f8e0677e54992920288ae1fa8206a4711fc,7199
+    hackage: persistent-2.14.4.3
 - completed:
     hackage: rio-prettyprint-0.1.4.0@sha256:1f8eb3ead0ef33d3736d53e1de5e9b2c91a0c207cdca23321bd74c401e85f23a,1301
     pantry-tree:
       sha256: 05bb2585e2d93899c62e0b6e1da02d040286b4524d0d363be1c5d99e49ac95bd
       size: 628
   original:
-    hackage: rio-prettyprint-0.1.4.0@sha256:1f8eb3ead0ef33d3736d53e1de5e9b2c91a0c207cdca23321bd74c401e85f23a,1301
+    hackage: rio-prettyprint-0.1.4.0
 - completed:
     hackage: Cabal-3.8.1.0@sha256:155d64beeecbae2b19e5d67844532494af88bc8795d4db4146a0c29296f59967,12220
     pantry-tree:
       sha256: 0df207f33a2167f23ab8192b3c1e5722b60836bcdde18a0b5b24fb85b41c05ef
       size: 8955
   original:
-    hackage: Cabal-3.8.1.0@sha256:155d64beeecbae2b19e5d67844532494af88bc8795d4db4146a0c29296f59967,12220
+    hackage: Cabal-3.8.1.0
 - completed:
-    hackage: Cabal-syntax-3.8.1.0@sha256:4936765e9a7a8ecbf8fdbe9067f6d972bc0299220063abb2632a9950af64b966,7619
+    hackage: Cabal-syntax-3.8.1.0@sha256:bd2bafd280b21d3dd035b320f057f9d50f377a553a3e971feb5de75a6497fcaf,7398
     pantry-tree:
-      sha256: 0471cade235bb93e1fd32630f6d5fa69735a879d2712f47067c51bed0c46d536
+      sha256: 37c19f1f6a7a593edf24953ee2431375137c5c5eebce6d5e7a5181b6ba144d7d
       size: 11052
   original:
-    hackage: Cabal-syntax-3.8.1.0@sha256:4936765e9a7a8ecbf8fdbe9067f6d972bc0299220063abb2632a9950af64b966,7619
+    hackage: Cabal-syntax-3.8.1.0
 snapshots:
 - completed:
     sha256: a2cbcd2f37010a64c4ef74c21fd7e55982a07b49840d2bed306f9bac9981a9c3
```

If I pay attention to the diff in the lock file and use `Cabal-syntax-3.8.1.0@rev:1` then the hashes are the same as before.

```diff
diff --git a/stack.yaml.lock b/stack.yaml.lock
index 1c8374b27..58b05226c 100644
--- a/stack.yaml.lock
+++ b/stack.yaml.lock
...
   original:
-    hackage: Cabal-syntax-3.8.1.0@sha256:4936765e9a7a8ecbf8fdbe9067f6d972bc0299220063abb2632a9950af64b966,7619
+    hackage: Cabal-syntax-3.8.1.0@rev:1
 snapshots:
 - completed:
     sha256: a2cbcd2f37010a64c4ef74c21fd7e55982a07b49840d2bed306f9bac9981a9c3
```

**Comment by mpilgrem** [comment]
> Going back to extra-deps: [ hackage-package-name-x.y.z ] (what cabal calls constraints).

I don't know Cabal (the tool), but an `extra-dep:` is not a constraint; it is a statement of what package and version should be made available to the build. The constraint (what the build should use) is specified in the `package.yaml` file (or in the Cabal file, if not using Hpack).

**Comment by mpilgrem** [comment]
I've made some changes to the online documentation in the light of this discussion, to lead with reproducibility, make clear what are the alternatives for reproducibility, bring in the `--lock-file` option, better explain that option, and add hyperlinks.

On:

> We say, "These files ([lock files](https://docs.haskellstack.org/en/stable/lock_files/#lock-files)) can be stored in source control".

To put this extract in its context, the online documentation states:

> The goal of the lock file is to cache completed locations of project, snapshot packages and snapshots themselves so that:
>
> * These files can be stored in source control
> * Users on other machines can reuse these lock files and get identical build plans given that the used local packages and local snapshots are the same on those machines
> * Rerunning stack build in the future is deterministic in the build plan, not depending on mutable state in the world like Hackage revisions

That is, the documentation already explains the merits of commiting Stack's lock files to repositories. However, there can be drawbacks too, as discussed in https://github.com/commercialhaskell/stack/issues/4795. I don't think the documentation need be prescriptive.
