### ISSUE TITLE
How to suppress warnings from external packages?

### ISSUE THREAD

**Issue by asarkar** [commercialhaskell/stack#6048]
Already [asked on Stackoverflow](https://stackoverflow.com/q/75290306/839733) and got no response.

### Stack version
Version 2.9.3 aarch64

### Method of installation
Homebrew

### Problem Statement

My stack build shows warning from external packages, like:

    happy               > /tmp/stack-d6caed253e9f21bf/happy-1.20.0/src/ProduceGLRCode.lhs:224:12: warning: [-Wincomplete-uni-patterns] 
    176happy               >     Pattern match(es) are non-exhaustive

There's not much I can do about external code, and I don't want to see these warnings. However, I still want to build my project strictly with GHC options `-Wall -Werror.`

Is there a way to suppress the warnings from external packages? I'm using stack with hpack. Note that **the solution has to work from command line**, since updating `stack.yaml` is not possible due to a large number of projects involved.

### Things I've tried:

* In `stack.yaml`:
```
ghc-options:
    "$targets": -Wall -Werror
    "$everything": -w
```

Combined with `--verbosity warn` from command line, this works, but I couldn't find a way to specify the above `ghc-options` from the command line.

* In `stack.yaml`:
```
apply-ghc-options: targets
```

This doesn't work, warning from external packages are still visible. Besides, I couldn't find a way to specify the above `apply-ghc-options` from the command line.

**Comment by mpilgrem** [comment]
There is no command line equivalent to the `$everything` _etc_ syntax. There is no command line option equivalent to the `apply-ghc-options` key.

The information during the build is provided by Cabal (the library) at its 'normal' level of verbosity. You could apply `stack build --cabal-verbosity silent` but that results in no information from Cabal - only information from Stack. The deathly silence during stages of a long build can be disconcerting. You could, I suppose, build the dependencies in deathly silence first (`stack build --only-dependencies --cabal-verbosity silent`).

**Comment by asarkar** [comment]
Thank you for your response. I’ve yet to try the two-stage build, but can this ticket be considered a feature request to make the `$everything` etc. keys available on the command line? The reasoning for this feature is simple, I’d like stack to stop spamming my build logs with warnings that I can do nothing about.

**Comment by mpilgrem** [comment]
@asarkar, are you aware that you can set your current solution as the default in Stack's global configuration file (`config.yaml`)? You don't have to update individual project-level configuration files (`stack.yaml`). See: https://docs.haskellstack.org/en/stable/yaml_configuration/#yaml-configuration.

**Comment by asarkar** [comment]
@mpilgrem I'm aware but depending on a local file that's not checked in is a classic "works on my machine" problem.
