### ISSUE TITLE
Error Update from Version 2.3.3 to 2.9.3

### ISSUE THREAD

**Issue by nau4k** [commercialhaskell/stack#6056]
Hi Everyone, I had a problem with Stack upgrade command. I use Raspberry pi 3b+ and try to install Stack to run VaporTrail by @inguardians
if i type Stack upgrade on Raspbian terminal. its works but i cannot update the version, and the result from the command is :
```
Current Stack version: 2.3.3, available download version: 2.9.3
Newer version detected, downloading
Querying for archive location for platform: linux-arm-static
Querying for archive location for platform: linux-arm

Warning: Exception occured when trying to perform binary upgrade:
UnliftIO.Exception.throwString called with:

Unable to find binary Stack archive for platforms: linux-arm-static linux-arm
Called from:
throwString (src/Stack/Setup.hs:1848:21 in stack-2.3.3-HmH0wUyKukGCU5D45EZuAV:Stack.Setup)

Falling back to source upgrade
Updating index to make sure we find the latest Stack version
Selected mirror https://s3.amazonaws.com/hackage.fpcomplete.com/
Downloading timestamp
Waiting to acquire cache lock on /root/.stack/pantry/hackage/hackage-security-lock
Acquired cache lock on /root/.stack/pantry/hackage/hackage-security-lock
Released cache lock on /root/.stack/pantry/hackage/hackage-security-lock
No package index update available, but didn't update cache last time, running now
Calculating hashes to check for hackage-security rebases or filesystem changes
```

I guess the problem is system can't find _binary Stack archive for platforms: linux-arm-static linux-arm_ but i'am not sure with that
Can you help me overcome the problem?

**Comment by mpilgrem** [comment]
@nau4k, thanks for reporting. I am afraid that, even with the most recently released versions of Stack, `stack upgrade --binary-only` is not supported on `Arm` machine architectures. On those architectures, you need to uninstall old/install new outside of the application itself. The Aarch64 version of the Stack 2.9.3 binary is available here: https://github.com/commercialhaskell/stack/releases.

**Comment by mpilgrem** [comment]
@nau4k, I think what you want is the archive file https://github.com/commercialhaskell/stack/releases/download/v2.9.3/stack-2.9.3-linux-aarch64.tar.gz. If you look inside the archive, there is an executable file `stack` (of size 64,021,496 bytes). I think you want to put that somewhere on your PATH (the default location would be in folder `/usr/local/bin`).

**Comment by nau4k** [comment]
Hi @mpilgrem  thanks for your suggestion, I have tried your suggestion by downloading the acrhive file and I have tried putting it in my stack directory or in the default location /usr/local/bin. but the stack is still version 2.3.3 it doesn't want to update to version 2.9.3, maybe there are suggestions what should I do?

**Comment by mpilgrem** [comment]
@nau4k, please can you try command `which stack` and post the result. That should tell me what is on your `PATH`. If Stack 2.9.3 has been put in `/usr/local/bin` it may be that that folder is not on your 'PATH'.

**Comment by mpilgrem** [comment]
@nau4k, are you still having problems?

**Comment by mpilgrem** [comment]
I am closing this, but please re-open if you are still having problems.
