### ISSUE TITLE
hpack on wrong version yet `stack build` does not fail

### ISSUE THREAD

**Issue by xave** [commercialhaskell/stack#6057]
### Steps to reproduce

For example:

1. hpack on wrong version
2. run `stack build ... --file-watch`
3. get message stating
 ```
foo.cabal was generated with a newer version of hpack,
please upgrade and try again.

Success! Waiting for next file change
```

For reference, the code to be compiled included an obviously malformed line that should have triggered an error, yet a Success! was output:

`qehww = ::`

### Expected

Stack build fails if hpack is not correct

### Stack version

~~~text
stack --version
Version 2.9.1, Git revision 13c9c8772a6dce093dbeacc08bb5877bdb6cfc2e (dirty) (155 commits) aarch64

~~~

### Method of installation

* Via GHCup

### Platform

macOS M1 v 12.6.3

**Comment by mpilgrem** [comment]
@xave, thanks for reporting. Hpack does not over-write an existing Cabal file, if it was generated by a more recent version of Hpack. Pantry (on which Stack depends), when it is using its built-in version of Hpack, warns when this occurs but does not consider it fatal - it will go on to use the existing Cabal file that was not over-written.

I assume that, in this case, the Haskell error (`qehww = ::`) was in a Haskell source file not built given the package description in the existing Cabal file.

If you want to prefer the `package.yaml` package description over the existing Cabal file, you need to delete the existing Cabal file.

**Comment by xave** [comment]
I think the message would be more helpful if it said to delete the file based on one's preference. It is not intuitive that the tools says a build is successful when there is an obvious error in  a file.

**Comment by xave** [comment]
I _eventually_ realized to delete the file.

**Comment by xave** [comment]
Thanks!

**Comment by mpilgrem** [comment]
@chris-martin, I think you are seeking Stack's existing `--hpack-force` flag, see:
* https://docs.haskellstack.org/en/stable/configure/global_flags/#-no-hpack-force-flag
