### ISSUE TITLE
Fail Stack Instalation on raspbian

### ISSUE THREAD

**Issue by nau4k** [commercialhaskell/stack#6058]
I'm trying to build stack on an RPi 3b+ and I got this error:
```
Detected Linux distribution: raspbian
Sorry, currently only 64-bit (x86_64 or aarch64) Linux binary is available.
```
please help me to fix it and install stack on raspbian

**Comment by mpilgrem** [comment]
@nau4k, I am not a Linux user, but that message looks to me like the output of the `get-stack.sh` script, when the detected Linux distribution is raspbian but the detected machine architecture is neither x86_64 or AArch64. However, I understand the architecture of the Raspberry Pi 3 Model B+ to be AArch64, so I am puzzled as to why the script's `get_isa()` function is not detecting that architecture. (`get_isa()` relies on the output of the command `uname -m`. What does that command produce on your machine?)

To install Stack, I think you could replicate, manually, what the script does:

* the script makes sure the following libraries used by Stack are available: `g++` `gcc` `libc6-dev` `libffi-dev` `libgmp-dev` `make` `xz-utils` `zlib1g-dev` `git` `gnupg` `netbase`
* the script extracts the stack executable from the archive - https://github.com/commercialhaskell/stack/releases/download/v2.9.3/stack-2.9.3-linux-aarch64.tar.gz - and puts it in folder `/usr/local/bin` (which needs to be on the PATH).

**Comment by nau4k** [comment]
okay thanks, i'll try

**Comment by nau4k** [comment]
@mpilgrem thanks for the direction, i'll try
