### ISSUE TITLE
Feedback requested: what would be the impact of deleting `System.PosixCompat.User` from `unix-compat`?

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#6069]
Hi there,

I've recently taken over maintainership of `unix-compat`, and I intend to push out a `unix-2.8`-compatible release as soon as I can. One remaining issue is what to make of the `System.PosixCompat.User` module, as the `UserEntry` type has changed.

Here is the first PR that attempts to graft over the differences: https://github.com/jacobstanley/unix-compat/pull/60/files

And here is my preferred solution, to delete the `System.PosixCompat.User` module entirely, based on the observation that `System.PosixCompat.User` doesn't seem useful at all, as all functions either return dummy data or throw exceptions: https://github.com/jacobstanley/unix-compat/pull/62

However, I see that `stack` and `yi-core` actually use this module. For example:

https://github.com/commercialhaskell/stack/blob/835318bce76e167ffe9e25292d35a359c77a1499/src/Stack/Config.hs#L888-L899

This code looks dubious to me: it claims to always return `True` on Windows, yet I believe it instead always throws an exception on Windows, which may be getting swallowed somewhere else.

But there are other uses, too, in `Stack/Docker.hs`. So, could you please consider the effect of deleting `System.PosixCompat.User` on the `stack` codebase, and let me know if that is a reasonable option, or if you'd rather see a different approach to `unix-2.8` support?

Thanks.

**Comment by mpilgrem** [comment]
@mitchellwrosen, thanks for asking. From Stack's perspective, I think it is a reasonable option to delete `System.PosixCompat.User`.

`osIsWindows` is `True` on Windows, so I would not expect `Stack.Config.isOwnedByUser` to throw an exception. Stack's Docker support throws `unsupported` exceptions on Windows - https://github.com/commercialhaskell/stack/issues/2421.

**Comment by mpilgrem** [comment]
Stack no longer imports `System.PosixCompat.User`.

**Comment by mitchellwrosen** [comment]
That's great, thank you!

**Comment by hamishmack** [comment]
I think it might be a good idea to add an upper bound `unix-compat <0.7` to https://hackage.haskell.org/package/stack-2.9.3 and https://hackage.haskell.org/package/stack-2.9.1.
