### ISSUE TITLE
Option for `stack script --compile` to write build artifacts to a separate directory

### ISSUE THREAD

**Issue by chrismwendt** [commercialhaskell/stack#6079]
When you run

```
stack script --compile Main.hs
```

It clutters the directory with a bunch of build artifacts like `Main` (the executable), `Main.hi`, `Main.o`, and `Main.dyn_hi`. You can hide all but the executable itself with:

```
stack script --compile --ghc-options=-outputdir=/tmp/output Main.hs
```

But the executable still gets built to the current directory. If Stack could inspect the [`-o <file>` GHC flag](https://downloads.haskell.org/ghc/latest/docs/users_guide/separate_compilation.html#ghc-flag--o%20%E2%9F%A8file%E2%9F%A9) (if present), then you could also hide the executable and Stack could still find it.

It would be nice to be able to tell Stack to write them all somewhere else like `~/.stack/scripts`:

```bash
stack script --use-work-dir --compile Main.hs
```

To avoid filename conflicts, a unique subdir could be given to each script. The subdir could be an escaped form of the full path to the script (replacing `/` with `#` or similar scheme):

```
~/.stack/scripts/
├── #Users#chrismwendt#Main.hs/
│   ├── Main
│   ├── Main.dyn_hi
│   ├── Main.hi
│   └── Main.o
├── #Users#chrismwendt#Main2.hs/
└── #Users#chrismwendt#other#Main.hs/
```

**Comment by chrismwendt** [comment]
I don't have much of a preference either way, and it's easy to change since it's just a cache (no backcompat issues).

**Comment by mpilgrem** [comment]
Thanks. I may have a stab at implementing that, then.
