### ISSUE TITLE
Reports multiple candidates when there are not

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#609]
```
> stack build
There were multiple candidates for the Cabal entry "Build.hs(C:\Code\windows-client\build\Build.hs), picking C:\Code\windows-client\build\Build.hs
There were multiple candidates for the Cabal entry "BuildUtils(C:\Code\windows-client\build\BuildUtils.hs), picking C:\Code\windows-client\build\BuildUtils.hs
```

But `Build.hs` and `BuildUtils.hs` only occur in one place, in one package. My YAML looks like this:

```
packages:
- build
- HsLibrary/Hs
```

-----
    > stack --version
    Version 0.1.2.1, Git revision 2723b3567e44725b176c35786a5e11db454d183e

**Comment by chrisdone** [comment]
Thanks for reporting. I think the resolving process was returning duplicates. Can you try now?

**Comment by 3noch** [comment]
Seems to be resolved now. Thank you!
