### ISSUE TITLE
Improve error message for missing local extra-dep

### ISSUE THREAD

**Issue by pbrisbin** [commercialhaskell/stack#6114]
I've seen multiple folks on my team struggle with the following scenario:

- Trying to add an extra dep, (say `dotenv`) to our project
- For whatever reason they don't care about a specific version, so they add `- dotenv`
- Get a confusing error,

  ```
  /home/.../dotenv: getDirectoryContents:openDirStream: does not exist (No such file or directory)
  ```

The fix of course is to put `- dotenv-{version}`. Without this, Stack is treating it like a local path and erroring because it doesn't exist. It's easy to internalize what's going on when you've done this a few times, but it can be confusing the first time. Did it try to download from Hackage and fail to extract? Did I typo the name?

I think it would be helpful to append some "Did you mean..."-style suffix to guide the user for this specific mistake.

```
/home/.../dotenv: getDirectoryContents:openDirStream: does not exist (No such file or directory)
If you intended to use a local package, ensure that it exists. If you intended to use a Hackage
dependency, you must specify it in {package}-{version} format.
```

Alternatively, and more disruptively, stack could actually require `- ./dotenv` (if that's what you meant). I don't know what you call this (it's not absolute, maybe "qualified" or "not bare" path?). That way, seeing an unqualified/bare path like `- dotenv` can be always considered an attempted hackage dep and a more concrete error (e.g. "version is required") could be achieved "for free" through the stricter parse failing.

**Comment by mpilgrem** [comment]
@pbrisbin, thanks for reporting. That exception handling can certainly be improved. I am trying to track down where the exception is thrown as a first step. My current hypothesis is that it is the `listDir` function in Pantry's `findOrGenerateCabalFile`, via Stack's `additionalDepPackage` and its use of Pantry's `loadCabalFilePath`.

**Comment by pbrisbin** [comment]
Thanks!
