### ISSUE TITLE
Installs dependencies for all packages when only building one

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#612]
`stack build --help` reports, for `TARGET`, that `If none specified, use all packages defined in current directory`.

However, when running `stack build` from within an individual package directory, `stack` installs the dependencies for all my projects instead of only the dependencies of the one in the current directory.

Am I missing something?

**Comment by snoyberg** [comment]
Documentation issue, this behavior was changed but the text not updated. If
someone can fix that, I'll be most obliged since I don't have keyboard
access right now

**Comment by 3noch** [comment]
I figured that's what happened. So to regain the old behavior, do you need to explicitly specify which package to build?

**Comment by snoyberg** [comment]
Or do "stack build ."

**Comment by manny-fp** [comment]
I just removed ` defined in current directory` from the help text (so it reads "If none specified, use all packages").  Sound right?

**Comment by snoyberg** [comment]
Sounds correct
