### ISSUE TITLE
Casa configuration

### ISSUE THREAD

**Issue by brandonchinn178** [commercialhaskell/stack#6121]
1. `casa-repo-prefix` doesn't seem to be documented at https://docs.haskellstack.org/en/stable/yaml_configuration/. Should it be?
2. Add `casa-enable` configuration (default to true), to enable disabling Casa completely, for corporate environments that want to mirror Hackage and just use that.
    * It can be disabled currently by setting `casa-repo-prefix` to some nonsense URL (or `http://localhost`), but that feels a bit hacky
3. It would also be nice to document why someone would want to specify a Hackage mirror vs a Casa mirror (`package-index.download-prefix` vs `casa-repo-prefix`)
    * Is the Hackage configuration used at all if Casa is accessible?

**Comment by mpilgrem** [comment]
@brandonchinn178, `casa-repo-prefix` should be documented. It seems from https://github.com/commercialhaskell/stack/pull/4988/ that it was introduced without documentation. It also seems that Casa was introduced into `pantry-0.3.0.0` without an entry in the change log.

For my own benefit: Casa is explained here: https://www.fpcomplete.com/blog/casa/ and https://www.fpcomplete.com/blog/casa-and-stack/.

**Comment by mpilgrem** [comment]
@brandonchinn178, I think No. 2 needs a change in the Pantry library, as `Pantry.withPantryConfig` does not anticipate a `Maybe CasaRepoPrefix`. I will open a corresponding issue there. 

On No. 3, my (limited) understanding is that a package index (eg Hackage or a mirror of Hackage) is an original source and a Casa server is a cache of things that have been obtained from an original source. I also understand from the Haddock documentation for `Pantry.loadPackageRaw` of the `pantry` package that looking to a 'third party' (Hackage, an archive or a repository) is only ever a 'last resort', made after an enquiry of the Casa server has not yielded what was sought.

**Comment by mpilgrem** [comment]
The `pantry` step in No. 2 is completed with the release of `pantry-0.8.3`.

@brandonchinn178, I was thinking of changing the Stack settings for Casa to be:
~~~yaml
casa:
  enable: true # Default. `false` to disable use of Casa.
  repo-prefix: https://casa.fp.complete
  max-keys: 1280 # Default (current default)
~~~

`casa-repo-prefix` would be deprecated. `casa: repo-prefix:` would default to `casa-repo-prefix`, while the latter still existed, taking priority over it if both were set.

What are your views?

**Comment by mpilgrem** [comment]
@brandonchinn178, this feature is in the `master` branch version of Stack (`stack upgrade --source-only --git`) and documented at   https://docs.haskellstack.org/en/latest/yaml_configuration/#casa, if you should like to test it before the next release of Stack.
