### ISSUE TITLE
[macOS] Perform or suggest "xcode-select --install" when necessary

### ISSUE THREAD

**Issue by yairchu** [commercialhaskell/stack#6122]
When upgrading macOS (and looks like just upgrading Xcode), some Haskell libraries fail to build with errors like:

```
/var/folders/w1/_vgkxyln4c7bk8kr29s1y1k00000gn/T/ghc83995_0/ghc_10.c:4:10: error:
     fatal error: 'ffi.h' file not found
  |
4 | #include <ffi.h>
  |          ^
#include <ffi.h>
         ^~~~~~~
1 error generated.
```

(example issue: https://github.com/haskell/ghcup-hs/issues/814)

These errors get resolved once the user does `xcode-select --install`, but this piece of information isn't necessarily easy to find.
It appears that the lack of the `/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk` symlink indicates this command needs to be ran.
So what if `stack` checked whether this is the case, or rather do that when projects fail due to missing include files?

**Comment by mpilgrem** [comment]
There is some macOS-specific online documentation at https://docs.haskellstack.org/en/stable/install_and_upgrade/ which refers to `xcode-select --install` (or more) being needed in some circumstances, and that could certainly be improved, extended and made more visible/discoverable. Given the nature of the problem, it is not clear to me that the best way to address it is within the Stack tool itself. I'll try to fix the documentation first, to see what that looks like.

**Comment by mpilgrem** [comment]
The macOS-specific online documentation at https://docs.haskellstack.org/en/stable/install_and_upgrade/ has been updated to include a passage on the Xcode Command Line Tools, including:
> An upgrade of macOS may sometimes require the existing Xcode Command Line Tools to be uninstalled and an updated version of the tools to be installed.

and
> If building fails with messages that *.h files are not found, that may also indicate that Xcode Command Line Tools are not up to date.
