### ISSUE TITLE
please bump the Stack-supplied MSYS2

### ISSUE THREAD

**Issue by shayne-fletcher** [commercialhaskell/stack#6153]
please bump the Stack-supplied MSYS2 to msys2-x86_64-20230526.

**Comment by shayne-fletcher** [comment]
@mpilgrem

**Comment by mpilgrem** [comment]
That is now done. Fresh installations of Stack on Windows will now download msys2-20230526 if the Stack-supplied MSYS2 is missing.

If you want a fresh installation of msys2-20230526 for existing Stack, you need to delete the MSYS2 items in Stack's programs directory (at `stack paths --programs`). However, deleting MSYS2 items will also lose any additions you have made to the Stack-supplied MSYS2 (eg added C libraries). If you want to preserve such things, it is better to upgrade the Stack-supplied MSYS2 in the [normal way](https://www.msys2.org/docs/updating/): `stack exec -- pacman -Suy` (possibly repeated, until all is up to date).

**Comment by mpilgrem** [comment]
@shayne-fletcher , may I ask what was your motivation for the original request? I have discovered that `msys2-20230526` appears to adversely change [some behaviour](https://discourse.haskell.org/t/solved-ghci-9-2-7-to-9-4-5-on-windows-was-there-a-change/6561/2?u=mpilgrem), and I am considering rolling back to `msys2-20221216` while I try to get to the bottom of that.

**Comment by shayne-fletcher** [comment]
@mpilgrem it wasn't for a deep reason. i was investigating some windows issues and noticed it was out and we were behind. i'm not against unlanding it if that's needed.
