### ISSUE TITLE
Suggested name: hakit

### ISSUE THREAD

**Issue by pharpend** [commercialhaskell/stack#616]
There was a [Reddit thread](https://www.reddit.com/r/haskell/comments/3d3e95/please_rename_stack_to_haystack/) a couple of days ago suggesting the name "haystack", because "stack" is too generic. There were issues with the name "haystack".

I would like to suggest the name "hakit", as the "Haskell kit", pronounced "hack it". I think it hits on all the good points of a name:

* It refers to Haskell, via the "ha" prefix
* It has the same theme as "stack", i.e. "kit".
* It's obvious that it's a programming tool because of the syllable "hack"
* It doesn't introduce naming collisions, other than some IT school in India. (I dunno, their website wasn't in English).

**Comment by chrisdone** [comment]
The book is closed on this.
