### ISSUE TITLE
Behavior regarding internal dependencies and file-watch

### ISSUE THREAD

**Issue by pbrisbin** [commercialhaskell/stack#6164]
We (sadly) have a multi-package project at work, something like:

```yaml
packages:
  - core
  - entities
  - api
 ```

Where `api` depends on `entities` and `core`, and `entities` depends on `core`.

One workflow would be to work on `api`, e.g.:

```console
stack build api --fast --pedantic --test --file-watch
```

Passing a single package makes the output more useful because it won't include the `{package}    >` prefix on all the lines and it will colorize the test output. As soon as you build more than one package at a time, that output starts happening, it is not colorized, and you'll run the tests for `core` and `entities` too, which may not be desired.

Problem is, `--file-watch` only triggers if I edit a file under `api/*`. It does not trigger if I change a file under `core/*` or `entities/*`. I have to navigate to the terminal with the `--file-watch` and press `<enter>`. My memory is fuzzy, but I didn't think that was always the case. I thought at some point this would "Just Work"; i.e. touching anything under the named package _or its internal dependencies_ would trigger `--file-watch` to do the thing.

As a workaround, I may instead run:

```console
stack build core entities api --fast --pedantic --test --file-watch
```

But this is sub-optimal because now I'm getting the multi-package output (wide prefix, no color) and running more tests than I'd like to. That latter can be ameliorated with `--test-arguments`, but it's still doing too much work.

I thought I would ask this as a general question here first, since my memory of when this behavior started being this way is very fuzzy. If anything I'm describing sounds like a bug or regression, just let me know and I'd be happy to re-report as a proper bug with repro, etc.

### Stack version

```console
% stack --version
Version 2.11.1, Git revision c1167a6abc3f4978ccded5ba0246a57387da0e2f x86_64 hpack-0.35.2
```

### Method of installation

* https://aur.archlinux.org/packages/stack-static

**Comment by mpilgrem** [comment]
@pbrisbin, based on the online help at https://docs.haskellstack.org/en/stable/build_command/#controlling-when-building-occurs and the code at `Stack.Build.build` (from `for_ msetLocalFiles`), I think `--file-watch` filters by build targets, unless you also pass flag `--watch-all`. In the latter case, all 'locals' are watched. `--watch-all` was introduced in Stack 2.5.1 - see https://docs.haskellstack.org/en/stable/ChangeLog/#v251-2020-10-15.

Does that answer your question?

**Comment by pbrisbin** [comment]
Ah, excellent. So it sounds like the behavior I was used to was changed, and effectively made opt-in with that option. Thank you! I'm glad I asked.
