### ISSUE TITLE
Make `stack build --flag` print warning when flag or package is unknown

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#617]
It can be quite dangerous when you make a mistake in package name (instead of "AdServer" I used lower-case "adserver"), and flag doesn't apply (and you try to deploy debug-build into production because of that). I would like stack to error or warn me about missing name.

**Comment by manny-fp** [comment]
Big +1 on this one.  I've run into this myself on several occasions.

**Comment by DanBurton** [comment]
+1 and I presume the same warning should go for the flags section of stack.yaml.

**Comment by k-bx** [comment]
Btw, the more I think of it, the more I have an opinion that it should actually error, not warn. Why would anyone want a flag that's not declared in .cabal-file?

**Comment by DanBurton** [comment]
I agree. This has the potential to run a lengthy erroneous build, and the warning could be easily missed, especially when the invocation of stack is automated.

+1 should be error. I don't think any sort of "force" option is necessary to bypass the error either; the solution is just to fix the flags.

**Comment by manny-fp** [comment]
Related: #611 (Should show error if setting `--flag` for package in the snapshot database).

**Comment by manny-fp** [comment]
Merging this and #611.  The warning message should be adjusted in the case where the flag matches a snapshot package to inform the user that flags can't be set for those.

**Comment by snoyberg** [comment]
Self-assigning

**Comment by manny-fp** [comment]
I'm also inclined to agree it should be an error rather than a warning.

**Comment by snoyberg** [comment]
OK, this is implemented and has a number of integration tests in place as well. Can others give it a whirl and see how it behaves?

**Comment by k-bx** [comment]
@snoyberg I confirm this works, thank you!
