### ISSUE TITLE
stack fails to install itself

### ISSUE THREAD

**Issue by kolmodin** [commercialhaskell/stack#618]
I usually build binaries in sandboxes to avoid populating the global db, then copy the binaries out somewhere else.
So, I built stack in a cabal sandbox. I then thought I could use stack to compile itself and install the binaries to some suiting path.

By default, stack chose to install stack-9.9.9, but I forced it to use 0.1.2.0 which is the latest of today.

Here's the error I got;

```
 $ .cabal-sandbox/bin/stack install stack-0.1.2.0
Using resolver: lts-2.18 from global config file: /home/kolmodin/.stack/global/stack.yaml
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package path in known packages

--  Failure when adding dependencies:    
      path: needed (-any && >=0.5.1), latest is 0.5.2, but not present in build plan
    needed for package: stack-0.1.2.0

Recommended action: try adding the following to your extra-deps in /home/kolmodin/.stack/global/stack.yaml
- path-0.5.2

You may also want to try the 'stack solver' command
```

Is this meant to work? Looks like stackage/lts-2.18 is it's missing `path` by @chrisdone.

**Comment by snoyberg** [comment]
stack ships with a stack.yaml file to address this, and provides the
command stack upgrade to ensure that it's used. Beyond that, following the
advice in the error message above should solve things.

**Comment by snoyberg** [comment]
Since the upgrade command is the recommended approach for this, closing. If there are issues with using it, please reopen.
