### ISSUE TITLE
Stack upload needs cabal 

### ISSUE THREAD

**Issue by cies** [commercialhaskell/stack#619]
```
stack upload .
Hackage username: abraham
Hackage password: 
cabal: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```

This (obviously) fixed it: `stack install cabal-install`

Installing `cabal-install` if not yet exists should probably become a part of the `upload` command.

**Comment by cies** [comment]
I see that calling the `cabal-install` executable [is a workaround](https://github.com/commercialhaskell/stack/blob/5b6794647eef2c87f9c1cfb12a0dd23ad541b656/src/Stack/Upload.hs#L248).

**Comment by snoyberg** [comment]
There's an open issue about this already, though I can't give you the link
since I'm on my phone

**Comment by cies** [comment]
Sorry. Forgot to check, my wrong. Here's the link: https://github.com/commercialhaskell/stack/issues/313

Please close it.

**Comment by snoyberg** [comment]
No problem

**Comment by mgsloan** [comment]
@cies Coincidentally, I just implemented a fix for this.  Please give this branch a try: https://github.com/commercialhaskell/stack/tree/313-sdist

**Comment by cies** [comment]
Cheers. Will give it a role, probably later this week.
