### ISSUE TITLE
Expose `main` as a library primitive

### ISSUE THREAD

**Issue by sol** [commercialhaskell/stack#6195]
...so that it is easier to use `stack` programmatically.

E.g. add `Stack.main` and reduce the current `Main` module to:

```haskell
module Main (main) where

import qualified Stack

main :: IO ()
main = Stack.main
```

**Comment by mpilgrem** [comment]
Stack's package explains that its library component is 'currently' only intended for use by the executable, and that the package is provided on Hackage only for 'convenience' and bootstrapping purposes. (I think convenience may relate to the online availability of Haddock documentation.) Given (and subject to) that 'health warning', I think its fine to shift code from the executable component to the library component.

However, if Stack's library component was, in the future, to be re-purposed as a (typical) library I suspect more would need to be done (eg think about bounds on dependencies or consciously supporting more than one GHC version).

**Comment by sol** [comment]
> Stack's package explains that its library component is 'currently' only intended for use by the executable, and that the package is provided on Hackage only for 'convenience' and bootstrapping purposes. (I think convenience may relate to the online availability of Haddock documentation.) Given (and subject to) that 'health warning', I think its fine to shift code from the executable component to the library component.
> 
> However, if Stack's library component was, in the future, to be re-purposed as a (typical) library I suspect more would need to be done (eg think about bounds on dependencies or consciously supporting more than one GHC version).

That's great for now. I don't expect any stability guarantees or something.
