### ISSUE TITLE
Hackage revision for `stack-2.11.1`

### ISSUE THREAD

**Issue by sol** [commercialhaskell/stack#6199]
It's possible to build `stack-2.11.1` with GHC `9.6.2`, but it requires some manual interventions.

A Hackage revision with the following list of changes will make this easier:

1.  Widen the `custom-setup` dependency on `Cabal` to `>=3.8.1.0 && <3.12`
2. Require `optparse-applicative == 0.17.0.0` (`0.17.1.0` does not work, it diverges on `--help`. `0.18.*` introduces breaking API changes.)
3. Restrict `pantry` to `>= 0.8.2.2 && < 0.9`.

It's still an *unsupported* build, and there may be other issues, but this is what works for my use case at this point.

**Comment by mpilgrem** [comment]
That is now reflected for `stack-2.11.1` Revision 1 on Hackage.

**Comment by sol** [comment]
Thanks @mpilgrem
