### ISSUE TITLE
How to force hackage index update

### ISSUE THREAD

**Issue by pbrisbin** [commercialhaskell/stack#6223]
I have a project that depends on a library I also maintain. I will often ship a new version of the library to Hackage and then relatively quickly want to use it. *I understand things take time, and this will likely resolve, but I'm curious about some things...*

```console
% stack build --fast --pedantic --test --no-run-tests
Cabal file info not found for stackctl-1.4.3.0, updating
Selected mirror https://hackage.haskell.org/
Downloading timestamp
Waiting to acquire cache lock on /home/patrick/.stack/pantry/hackage/hackage-security-lock
Acquired cache lock on /home/patrick/.stack/pantry/hackage/hackage-security-lock
Released cache lock on /home/patrick/.stack/pantry/hackage/hackage-security-lock
No package index update available and cache up to date
Package index cache populated

Error: [S-476]
       Could not find stackctl-1.4.3.0 on Hackage.
       Possible candidates:
       stackctl-1.4.0.0@sha256:922d1a6b7279b945b43790f10bce7b702ddbd099f45ed76bfd910a84811f0d0f,5908,
       stackctl-1.4.0.1@sha256:2cc3150cb43b71d67c020a74ce4a295809a0d3aebefd34c22a74abea953a9d93,5991,
       stackctl-1.4.2.0@sha256:0b7afaadc6821d84f07e3d3ec91bd9b002f17afc3e85db5b2a50eb71d64d3f2c,6088,
       stackctl-1.4.2.1@sha256:258afb8662cada51438e0f098e5782dd25a1c7421820d01f030a8629839cc5a9,6088
       and
       stackctl-1.4.2.2@sha256:932b3d939f004ae402b75b3e8d68fb564989013d2344b8d90603b95b72c3a8ab,6086.
```

Specifically,

```
No package index update available and cache up to date
```

This for sure exists right now: https://hackage.haskell.org/package/stackctl-1.4.3.0 and has for almost an hour.

It seems Stack thinks the Hackage index is up to date and won't attempt to re-fetch it; what makes it think that? And how do I force it to update anyway? I am probably wrong, but I suspect it's stuck somehow and if I could tell it to try anyway that'd be my way out -- but I can't figure out how.

The documentation for [`stack update`](https://docs.haskellstack.org/en/stable/update_command/) says,

> Generally, Stack automatically updates the package index when necessary.
>
> `stack update` **will** download...

(Emphasis mine.)

IMO, this implies that explicitly issuing a `stack update` should _do the thing_ even if it thinks the index is up to date as it's drawing a distinction between what happens "generally" vs when the command is used -- and really, why else would it exist except to force something that is otherwise automatic? That would be my preference, but if not, can it perhaps grow a `--force` option to do that?

**Comment by mpilgrem** [comment]
@pbrisbin, thanks for reporting. Stack relies on Pantry which, in turn, relies on `Hackage.Security.Client.checkForUpdates` exposed by the `hackage-security` package. `Pantry.Internal.Stackage` does export a `forceUpdateHackageIndex`, but that is not intended for mainstream use. I wonder if Hackage has anything to say about such lags.

**Comment by mpilgrem** [comment]
This Hackage issue may be related: https://github.com/haskell/hackage-server/issues/980.

**Comment by pbrisbin** [comment]
Hmm could be. The "issue" did eventually resolve, a few hours later.

I do think there should be a way to force an update (and/or `stack update` should always do it), but now that you've explained the trail of dependencies down to where that would need implementing, I understand it may not be worth the effort (or perhaps should be something reported on one of those projects instead). I'll go ahead and close this issue. Thanks!

**Comment by mpilgrem** [comment]
@pbrisbin, it may be worth raising your experience at https://github.com/haskell/hackage-server/issues/980.

**Comment by pbrisbin** [comment]
Yeah, I appreciate the suggestion but I don't really feel the need to. Either one of two things were happening:

- The index itself took a long time to update
- The index was updated, but Stack thinks it wasn't and so didn't even try to fetch

This Issue/question was focused solely on [the possibility of] the second, and suggesting some kind of behavior change to tell Stack to try anyway. I don't really feel strongly about the first scenario; distributed systems take time and I find the most recent comment on that Issue perfectly reasonable.
