### ISSUE TITLE
Feature request: `--[no-]project` flag for `stack ls dependencies`

### ISSUE THREAD

**Issue by isomorpheme** [commercialhaskell/stack#6229]
We're using `stack ls dependencies` with `--license` to prevent using certain licenses via a check in CI; it would be convenient to be able to exclude project packages from this. (Right now we use a manual allowlist for those.)

**Comment by mpilgrem** [comment]
@isomorpheme, may I clarify what you want to exclude from the output? Do you want to exclude from the reported information the information for packages that are *local* packages?

I am wondering if what is required is an extended 'prune' option.

That is, `--prune <package>` prunes the specified package *and its dependencies* from the output (this is clearer in the `tree` subcommand; I need to clarify the online documentation), but you want an option (presumably only for the `text` subcommand) that prunes *only* the specified package and not also its dependencies? 

That is, something like (if `foo` is the local package):
~~~text
> stack ls dependencies text --license --prune-only foo
base BSD-3
ghc-bignum BSD-3
ghc-prim BSD-3
rts BSD-3
~~~

**Comment by isomorpheme** [comment]
I think what I want is to exclude what's defined as `$project` here: https://docs.haskellstack.org/en/stable/build_overview/#apply-general-ghc-options (Hence I suggested the name `--[no-]-project` - I guess `--[no-]local` would be clearer but according to that document, that terminology is outdated.) In other words, I want to filter out the packages listed under `packages:` in stack.yaml. I'd rather not have to provide that list as individual `--prune-only` options. (Besides, filtering out individual packages from the text output seems easy enough with standard shell utilities.)

**Comment by isomorpheme** [comment]
I like that, that looks flexible. :)

I'd be happy to try my hand at making a PR for this by the way.

**Comment by mpilgrem** [comment]
I'll take you up on the PR offer - I'm keen for more people to get involved with Stack's code base.

**Comment by isomorpheme** [comment]
Alas, I'm going to have to hand this back - I think I made a small start but it's not a high priority for me right now and I don't have spare time for it.

**Comment by mpilgrem** [comment]
@isomorpheme, pull request #6358 seeks to implement this. If you have time to test it before I merge, I would be grateful.
