### ISSUE TITLE
Filling /tmp results in a crash

### ISSUE THREAD

**Issue by barrucadu** [commercialhaskell/stack#623]
~~~~
Progress: 102/122/tmp/stack12010/texmath-0.8.2.2/lib/mmldict/unicode.xml: hPutBuf: resource exhausted (No space left on device)
~~~~

My VPS has 500MB of /tmp, which isn't very much when building Haskell packages. When /tmp is filled, stack terminates with something like the above. *However*, all the temporary files created by stack were then gone, cleaned up in the shutdown I assume. Running `stack build` then succeeded.

It would be nice if cleaning the temporary files was attempted first, something like this:

 1. stack fails to download or unpack something due to no space in /tmp
 2. Any files remaining for packages which have already been built and installed get deleted
 3. The action is retried. If there is still not enough space, stack notifies the user and exits.

~~~~
>>>  stack --version
Version 0.1.2.0
~~~~

**Comment by snoyberg** [comment]
I disagree about this change. The same behavior can be achieved by calling stack build twice, and allows stack itself to give meaningful exit codes faster for systems where this kind of disk exhaustion is not expected.
