### ISSUE TITLE
Open-source scripts that build docker images

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#624]
Please, open-source (or point me to) your work on building docker images with full stack packages built inside, so that any person could reproduce and/or customize it.

**Comment by manny-fp** [comment]
We're planning to open this, but the current tool contains some proprietary information and needs refactoring to make it possible to extract that and release the non-proprietary parts as open source.

**Comment by k-bx** [comment]
@manny-fp thanks, good to know. We decided to search for less hardcode (in terms of infrastructure-change) ways for now, but I'll be watching this.

**Comment by PierreR** [comment]
:+1:  
I need a `run` minimal image alike [stack-run](https://hub.docker.com/r/fpco/stack-run/) but with ruby 2.x.  I was hoping to get some information from the Dockerfile for stack-run but it is not available unfortunately. I know it should be possible to install an extra ruby on the base image but I would prefer to have something as minimal as possible and a single ruby version (that rules out `phusion` as the base image).

**Comment by borsboom** [comment]
Since the Docker integration can now use any imagecustom images no longer need depend on the images FP Complete generates (see https://github.com/commercialhaskell/stack/blob/master/doc/docker_integration.md#custom-images).  Therefore, reducing the priority of this issue.

**Comment by igrep** [comment]
You mean, the actual docker image is built after adding some changes (by the proprietary tools) to https://github.com/commercialhaskell/stack/blob/a562702b3bcda71bc73663320a38e7cb937d1163/etc/docker/stack-base/Dockerfile ?

**Comment by kanishka-azimi** [comment]
How close is the linked dockerfile to the lts's?

**Comment by borsboom** [comment]
@kanishka-azimi: that Dockerfile is not related at all.  I don't think that Dockerfile is actually used for anything and I'm going to remove it to avoid confusion.

BTW I'm planning to open this up in the very near future.  We're moving away from the current shake- and propellor- based process to build the images to a simplified one without any of the proprietary stuff, so it will just be a simple Dockerfile.

**Comment by borsboom** [comment]
The new scripts for LTS >= 8.0 are here: https://github.com/commercialhaskell/stack/tree/master/etc/dockerfiles/stack-build

This is vastly simplified from the proprietary scripts we were using for LTS <= 7.x.  We're not only building the `stack-build` images (no more `stack-run` and `stack-full` images), and a bunch of stuff is being left out as Stack itself has gotten the functionality built into it.
