### ISSUE TITLE
A coherent approach to Stack's use of output channels

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#6250]
Motivated by @juhp's https://github.com/commercialhaskell/stack/pull/6249.

Stack's current commands whose central purpose is to provide information are:

|Command            |Comment|
|-------------------|-------|
| `config env`      | Outputs to stdout |
| `dot`             | Outputs to stdout | 
| `hpc report`      | Outputs to stderr. Fixed in #6255 |
| `ide packages`    | Outputs to stderr, offers `--stdout` flag |
| `ide targets`     | Outputs to stderr, offers `--stdout` flag |
| `list`            | Subject of https://github.com/commercialhaskell/stack/pull/6249 |
| `ls dependencies` | Outputs to stdout |
| `ls snapshots`    | Outputs to stdout |
| `ls stack-colors` | Outputs to stdout |
| `ls tools`        | Outputs to stdout |
| `path`            | Outputs to stdout |
| `query`           | Outputs to stdout |
| `stack templates` | Outputs to stderr. Fixed in #6254 |
| `stack uninstall` | Outputs to stderr. Fixed in #6254 |

Stack's use of 'logging' functions sends that output to standard error.

My proposed schema:

* commands whose central purpose is to provide information to _people_, should output that information to standard output;
* commands whose central purpose is to provide information to 'machines' and where pipe-friendly is not important, should output that information to standard error but provide a `--stdout` flag. That accommodates `stack ide`, for example; and
* other information produced by commands that is 'logging' in nature can continue to go to standard error.

**Comment by juhp** [comment]
Thank you for this good analysis!
