### ISSUE TITLE
Don't use `renameDir` in `Stack.Setup.withUnpackedTarball7z`

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#6257]
`renameDir` uses `renameDirectory`, which uses `renamePath`, which uses `renamePathInternal`, which - on Windows - uses `Win32.moveFileEx`. However, `MoveFileEx` does not work as between drives. See https://github.com/haskell/directory/issues/132 and https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexw.

The temporary directory may well be on a different drive to Stack's `programs` directory.

**Comment by hasufell** [comment]
You can set the `MOVEFILE_COPY_ALLOWED` flag.

**Comment by mpilgrem** [comment]
Fixed in #6258, not by avoiding `renameDir` but by putting the temporary folder in the same drive as the destination directory.
