### ISSUE TITLE
Stack fails install package correctly on Debian

### ISSUE THREAD

**Issue by andrewjstryker** [commercialhaskell/stack#6260]
# Summary

`stack` is not able to install packages on a fresh version of Debian or Ubuntu.

After installing `stack`, issuing `stack setup`, the command `stack install pandoc-cli`, yields:

```
Error: [S-4804]
       Stack failed to construct a build plan.

       While constructing the build plan, Stack encountered the following errors:

       In the dependencies for pandoc-cli-0.1.1.1:
           hslua-cli must match >=1.4.1 && <1.5, but the Stack configuration has no specified
                     version (latest matching version is 1.4.1)
           pandoc-lua-engine must match >=0.2 && <0.3, but the Stack configuration has no specified
                             version (latest matching version is 0.2.1.2)
           pandoc-server must match >=0.1 && <0.2, but the Stack configuration has no specified
                         version (latest matching version is 0.1.0.3)
       needed since pandoc-cli is a build target.

```

This error happens on (at least) fresh copies of Debian and Ubuntu.

# Details

The [installation process described on the project's website](https://docs.haskellstack.org/en/stable/#how-to-install-stack) logs this message:

```
ar: conftest.a no such file or directory
```

However, installation process returns 0, indicating success. As shown above, the package installation code neither understands version numbers nor realizes that it lacks this capability. Ideally, the installation process would either automatically install `conftest.a` or fail if the system lacks `conftest.a` (assuming that the lack of `conftest.a` is the root cause of the error).

Use this [GitHub Gist](https://gist.github.com/andrewjstryker/5b4f0eed3004202104d48de4fdecff7a) reproduce the error:

```sh
#! /usr/bin/bash
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
# docker-haskell-stack.sh
#
# Verify that Haskell Stack installs Haskell modules correctly.
#
# By default, this script runs the current installation script on the latest
# version of Debian. However, this is configurable via environment variables.
#
# Andrew Stryker <axs@sdf.org>
#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#

STACK_URL="${STACK_URL:-https://get.haskellstack.org}"
BASE_IMAGE="${BASE_IMAGE:-debian:latest}"
TEST_APP="${TEST_APP:-pandoc-cli}"

TAG="${TAG:-haskellstack:testing}"

echo "Building from ${BASE_IMAGE}"
echo "Installing Haskell Stack with the script at ${STACK_URL}"
echo "Testing installation with ${TEST_APP}"
echo "Creating image ${TAG} ..."

docker build \
  --build-arg IMAGE=${BASE_IMAGE} \
  --build-arg URL=${STACK_URL} \
  --tag "${TAG}" \
  - <<-"EOF"
	ARG IMAGE
	FROM ${IMAGE}
	ARG URL
	RUN <<EOT
	  apt-get update
	  apt-get upgrade -y
	  apt-get install -y curl
	  curl -sSL ${URL} | sh
	  stack setup
	EOT
EOF

docker run --rm "${TAG}" stack install "${TEST_APP}"

if [[ $? = 0 ]]
then
  echo "✓ Successfully installed ${TEST_APP}"
else
  echo "✗ Error code: $?"
fi

#-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-#
```

**Comment by mpilgrem** [comment]
@andrewjstryker, what `stack.yaml` (project-level configuration) are you using? Stack is complaining that your Stack configuration applied to the package does not specify all of the packages that `pandoc-cli-0.1.1.1` depends on.

On Windows, I cannot reproduce a problem. The following series of commands work as expected:
~~~pwsh
stack unpack pandoc-cli # Fetch the package from Hackage
cd pandoc-cli-0.1.1.1 # Change into the package's root directory
stack init # Create a stack.yaml configuration for the package
stack install # Build the package and copy the executable to the local binary directory
~~~

The `stack init` creates, essentially, this `stack.yaml`:
~~~yaml
resolver: lts-21.13 # GHC 9.4.7

flags:
  pandoc-cli:
    lua: false
    server: false
~~~

**Comment by mpilgrem** [comment]
@andrewjstryker, as an aside, `stack setup` is generally redundant - other Stack commands that need GHC will fetch it.

**Comment by andrewjstryker** [comment]
@mpilgrem, I don't have access to a Windows machine. I provided a script that makes a Docker image to ensure that anyone can reproduce the error.

I first encountered the error under Debian and I also encountered in a virtual machine running Ubuntu.

Following your example on an Ubuntu VM:
```sh
stack unpack pandoc-cli
cd pandoc-cli-0.1.1.1
stack init
stack install
```
... I still see the message about a missing `conftest.a` and I get a build failure, error code `[S-7282]`. This is a different error message than what I get from `stack install pandoc-cli`.

Here is the relevant section of `stack.yaml`:
```yaml
# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/21/13.yaml
```

If this works correctly on Windows but not Linux (at least Debian-based), that might be big clue.

A couple questions:
* Is the missing `conftest.a` file a problem?
* Should `stack install pandoc-cli` work as expected. The [website](https://docs.haskellstack.org/en/stable/#step-1-start-your-new-project) documents this as the method to install executable applications, but I may be confused.
* Is showing how to reproduce the error using Docker helpful? If not, is there a different method that you would prefer?
* Would you like me to change the script such that it does not invoke `stack setup`?

Thanks for looking into this right away. :smile:

**Comment by haoyun** [comment]
On my `Fedora`, the following works without any problem.

> ```powershell
> stack unpack pandoc-cli # Fetch the package from Hackage
> cd pandoc-cli-0.1.1.1 # Change into the package's root directory
> stack init # Create a stack.yaml configuration for the package
> stack install # Build the package and copy the executable to the local binary directory
> ```

In contrast, with a freshly installed `stack`, without any project-level `stack.yml`, only the global `~/.stack/global-project/stack.yaml`,

```
packages: []
resolver: lts-21.14
```

which is generated automatically,  `stack install pandoc-cli` produces the same problem:

```
Error: [S-4804]
       Stack failed to construct a build plan.

       While constructing the build plan, Stack encountered the following errors:

       In the dependencies for pandoc-cli-0.1.1.1:
           hslua-cli must match >=1.4.1 && <1.5, but the Stack configuration has no specified
                     version (latest matching version is 1.4.1)
           pandoc-lua-engine must match >=0.2 && <0.3, but the Stack configuration has no specified
                             version (latest matching version is 0.2.1.2)
           pandoc-server must match >=0.1 && <0.2, but the Stack configuration has no specified
                         version (latest matching version is 0.1.0.3)
       needed since pandoc-cli is a build target.
```

**Comment by mpilgrem** [comment]
@haoyun, thanks. It seems Stack is working as expected:

* snapshots `lts-21.13` and `lts-21.14` do not include package versions for `hslua-cli`, `pandoc-lua-engine` or `pandoc-server`;
* if you build `pandoc-cli-0.1.1.1` with the Cabal flags `lua` and `server` enabled (the default) it depends on those packages - and Stack will warn that they are not available in the configuration; and
* if you build `pandoc-cli-0.1.1.1` with the Cabal flags `lua` and `server` disabled (which is what `stack init` works out is needed to build) it does not depend on those packages.
