### ISSUE TITLE
A chat room for stack users and devs ?

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#6262]
### Location of the documentation

https://docs.haskellstack.org/en/stable/#questions-feedback-and-discussion

### Is it incomplete?

There's no obvious real-time chat room for stack users or developers. Cabal has used [#hackage](https://matrix.to/#/%23hackage:matrix.org) for a long time and it helps that project a lot. There is the [Haskell Tooling](https://matrix.to/#/%23haskell-tooling%3Amatrix.org) room on matrix, but no obvious stack devs there. You (especially you mpilgrem) might not have the bandwidth, but wouldn't a dedicated chat room for stack users and developers help the project ?

I would recommend a matrix room. @mpilgrem I'd be happy to walk you through setup, or if it's helpful, to do that and keep an eye on it.

**Comment by mpilgrem** [comment]
@simonmichael, I think that is out of date. For Stack users, I would direct them first to the Haskell Community and second to the #stack-users channel of the Haskell Foundation's workspace on Slack. For Stack developers/collaborators, who want a space more specific/less 'public' (although it is all public) than the entire Haskell Community, I would direct them to the #stack-collaborators channel of the Slack workspace. The one disadvantage of Slack is that if you don't pay for access (and I don't) you only see the last 90 days of activity.

**Comment by simonmichael** [comment]
@mpilgrem, thanks for the info. Many FOSS developers will avoid Slack and similar for-profit chat platforms, considering them not safe places to build long term community knowledge bases.

**Comment by mpilgrem** [comment]
@simonmichael, the origins of the Slack decision is before my time, but I imagine it arose from a desire to work collaboratively with the Haskell Foundation. If the Foundation changed its mind about where to locate the 'town square', I assume that the Stack project would be likely to follow.

**Comment by simonmichael** [comment]
Is there any discussion happening in stack's Slack room ? It's not easy for me to find or access it.

**Comment by mpilgrem** [comment]
In case that access issue is the 'open invite' URL, it is here: https://haskell-foundation.slack.com/join/shared_invite/zt-z45o9x38-8L55P27r12YO0YeEufcO2w#/shared-invite/email. It's source is at the bottom of this page: https://haskell.foundation/contact/.

In terms of discussion there, it is a rather sedate place - I can see four topics in the last 90 days. I mostly use it myself when I think I may be planning something controversial and I should get the buy-in of other Stack collaborators. The content there tends to be emphemeral in nature. This repository is really place for discussions of substance that need to endure.

**Comment by mpilgrem** [comment]
I found this topic on the Haskell Community: https://discourse.haskell.org/t/reconsider-slack-for-hf/4230

**Comment by simonmichael** [comment]
Good news everyone! There is an existing [#haskell-stack:matrix.org](http://matrix.to/#/%23haskell-stack:matrix.org) room. It was created in 2018, and at times was bridged with the #haskell-stack channel on Libera IRC. I have added it to the #haskell-space:matrix.org (under Haskell Projects, alongside the cabal room). I'll leave this open as a reminder to link it in stack docs.

**Comment by simonmichael** [comment]
PS, currently it has 12 members and even less activity than the slack room, but I expect that to increase a bit. @mpilgrem , if you ever have time to keep a presence there or drop by for another set of opinions, please do! An active accessible project chat helps attract contributors.

**Comment by mpilgrem** [comment]
@simonmichael, thanks - I'll look at that. Matrix had not crossed my radar, until you posted here. 

Actually, I reacted too quickly about the online documentation being out of date. On reflection, the link that you identified on Stack's landing page (https://docs.haskellstack.org/en/stable/#questions-feedback-and-discussion) is aimed at Stack users and, in particular, new users who are looking mostly for 'How do I use Stack?' sort of support. They are best advised to post in the Haskell Community under the 'Learn' category.

It is anticipated that people interested in Stack's development will read the Contributors guide: https://docs.haskellstack.org/en/stable/CONTRIBUTING/. Relevant parts of that, as it stands, are:

* https://docs.haskellstack.org/en/stable/CONTRIBUTING/#stacks-support; and
* https://docs.haskellstack.org/en/stable/CONTRIBUTING/#slack-channel.

I will add something to the documentation to acknowledge the existence of the Matrix room.
