### ISSUE TITLE
Mapping stack ide targets to build location

### ISSUE THREAD

**Issue by dbeacham** [commercialhaskell/stack#6272]
Is there a simple way to discover the location of build target, e.g. with

```
> stack ide targets --tests
package-name:test:test-suite
```

can I get stack to point to the location on disk it either is or will be?

**Comment by mpilgrem** [comment]
@dbeacham, can you clarify what you after? `package-name:test:test-suite` refers to a stanza in the Cabal file for package `package-name`. 

That stanza is unlikely to correspond to a single location on a disk. Even the `hs-source-dirs:` key in the stanza (if any) could be a list of more than one directory.

**Comment by mpilgrem** [comment]
@dbeacham, I have now seen your related topic on the Haskell Community and understand better the context. See https://discourse.haskell.org/t/store-test-benchmark-suites-from-stack-or-cabal-for-use-in-a-separate-build-job/7785/5?u=mpilgrem.

**Comment by dbeacham** [comment]
Everything's answered in the link above.
