### ISSUE TITLE
Get dependencies before calling Ghci

### ISSUE THREAD

**Issue by NightRa** [commercialhaskell/stack#629]
Stack should get all the project's dependecies before calling ghci.

**Comment by cocreature** [comment]
I also would like this.

**Comment by chrisdone** [comment]
Opened PR for this here: https://github.com/commercialhaskell/stack/pull/726

**Comment by ntc2** [comment]
Is this issue tracking the problem where you need to run `stack test` and `stack bench` before `stack ghci` in some cases? The title is not very descriptive, but there is a hint here: https://github.com/commercialhaskell/stack/issues/665#issuecomment-128464600.

**Comment by chrisdone** [comment]
Yes, it is.

**Comment by chrisdone** [comment]
Implemented!

**Comment by chrisdone** [comment]
Well, it works. But it reconfigures and recompiles the project every time you run it, which I don't like. But I don't see an obvious reason why it would at this moment, so I'll leave this open.

**Comment by chrisdone** [comment]
I think this behavior is good enough. It doesn't reconfigure and rebuild every time now.
