### ISSUE TITLE
Update/release repo for fpco/stack-ghcjs-build docker image

### ISSUE THREAD

**Issue by CRogers** [commercialhaskell/stack#630]
I'm having a great time building [`stack-ide-atom`](https://github.com/CRogers/stack-ide-atom) ([`stack-ide`](https://github.com/commercialhaskell/stack-ide) integration for Atom). I've got to the stage were I can actually write some integration tests against the `stack-ide` command! One problem: I am using the [fpco/stack-ghcjs-build docker image](https://registry.hub.docker.com/u/fpco/stack-ghcjs-build/) to build the plugin and run the tests, but it only has stack-0.1.1.0, which doesn't have the `stack ide` command. So I'm a bit stuck (`stack upgrade` also doesn't work from inside the docker image). Would it be possible to run another build of the image so it has more recent stack? Or, even better, put up a repo with the Dockerfile in so I can build and adapt my own docker image to work off?

**Comment by mgsloan** [comment]
Hmm, that's curious.  The same version of `stack` should be present when exec-ing in the container, as the path that contains it gets mounted into the docker container at `/opt/host/bin/`.  What's your output for `stack exec -- which stack`?  With a docker container, I get `/opt/host/bin/stack`.

Here's where the path gets mounted: https://github.com/fpco/stack/blob/b0d95e701b4f2e93df99ecd0798b9e4902223949/src/Stack/Docker.hs#L75

**Comment by CRogers** [comment]
I'm not using `stack` to run docker - I'm using cabal inside the docker image to build stuff as stack doesn't work with ghcjs yet (or boot2docker). I need the version of stack inside the docker image to be newer so I can run integration tests against it.

````
$ docker run -it --rm -v "$(pwd):/blah" fpco/stack-ghcjs-build:lts-2.16
/# stack --version
Version 0.1.1.0
/# which stack
/opt/stackage/lts-2/extra/bin/stack
````

The best solution for me would be to get the Dockerfile for `fpco/stack-build-ghcjs` so I can make my own docker image for deving against.

**Comment by mgsloan** [comment]
Gotcha, yes, I ran into the same thing.  Hopefully we will have GHCJS support in the not-too-distant future.

I used stack exec to run cabal / ghcjs.  Here's a description of how the School of Haskell's build works: https://github.com/commercialhaskell/stack/issues/337#issuecomment-113482050

**Comment by manny-fp** [comment]
I'll kick off a new GHCJS image build in the next day or two, but you should be able to make your own by creating a Dockerfile that starts `FROM fpco/stack-ghcjs-build:lts-2.16` and then `ADD`s a newer stack executable (which you could download the [Github release page](https://github.com/commercialhaskell/stack/releases)) in place of the old one.

We are planning to open the tool that builds the images, but it currently contains some proprietary information and needs to be refactored to make it possible to remove that.  It's not as simple as a Dockerfile, I'm afraid.

**Comment by CRogers** [comment]
@manny-fp Awesome, I totally forgot I could do that. Thanks!

**Comment by manny-fp** [comment]
I've pushed new images to all our Docker image repos that include the latest release of stack.  These have the tag `lts-2.19`.

**Comment by CRogers** [comment]
Awesome, thanks!
