### ISSUE TITLE
Sanity check: Setup.hs should be present when build-type is Custom

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#631]
`cabal-install` fails if `build-type: Custom` but no `Setup.hs` is present. For compatibility, `stack` should implement the same check, which in any case is a reasonable sanity check. Otherwise, it's too easy to write a `.cabal` file that can be compiled with `stack` but cannot be compiled with `cabal-intall`.

Arguably, this check should be factored out into Cabal-the-library, so that it is applied consistently between the two tools. cc @dcoutts.

**Comment by snoyberg** [comment]
Good call
