### ISSUE TITLE
stack exec shouldn't check the GHC version

### ISSUE THREAD

**Issue by nkaretnikov** [commercialhaskell/stack#633]
Why does it need to do that when I already have an executable?

**Comment by DanBurton** [comment]
Because GHC can be called within stack exec, and stack exec makes sure it can give you access to the GHC associated with your project.

If you "already have an executable", I recommend just calling it directly, rather than indirectly through stack exec.

**Comment by nkaretnikov** [comment]
> Because GHC can be called within stack exec, and stack exec makes sure
> it can give you access to the GHC associated with your project.

Right, but can't stack distinguish between GHC and some other
executable?  Can't the GHC check happen later?

> If you "already have an executable", I recommend just calling it
> directly, rather than indirectly through stack exec.

I'm doing it through stack exec because I don't want to type its
absolute location, e.g., .stack-work/install/x86_64-linux/lts-2.13/7.8.4/bin/sdm.

Since I'm on NixOS, I can work around this restriction by picking a
suitable version of GHC like this:

nix-shell -p haskell.compiler.ghc784

Then, stack exec sdm works just fine.

I need to do this because stack setup doesn't work correctly on NixOS
due to the unusual file system structure (mostly).

Anyway, I realize that others probably don't care much about this, so
feel free to close this issue if you like.

**Comment by snoyberg** [comment]
There are real use cases where having GHC available is necessary, such as when your executable uses GHC. I agree with @DanBurton's point of just using the existing executable. You may also want to consider building with something like:

    mkdir -p bin
    stack --local-bin-path bin build --copy-bins

Then your executable with be `bin/sdm`.
