### ISSUE TITLE
stack test --coverage shouldn't include tests in reports

### ISSUE THREAD

**Issue by mboes** [commercialhaskell/stack#634]
The intention of `stack test --coverage` is to provide a report about test coverage, i.e. how good are tests at exercising all of the library/program. In this light, we don't care about whether tests themselves have good coverage. Typically tests have very good coverage, but programs very bad coverage. So including the tests in the results biases the overall coverage report towards being too optimistic.

Perhaps adding/removing tests from the coverage report should be the matter of a flag.

**Comment by mgsloan** [comment]
Another aspect of this is that currently coverage applies to all of the packages at once.   This is pretty cool, but probably not what you want as a default.  With larger projects it also seems to be prone to triggering some ghc / hpc bugs (#607).

Thankfully, `hpc` has an `--include` flag which allows you to restrict to particular packages / modules, which looks like it will do the trick.

**Comment by mgsloan** [comment]
Got it, the package filter needs to look like `--include=PKG-X-Y-Z:`.

**Comment by mgsloan** [comment]
@mboes How's this look?

**Comment by mboes** [comment]
LGTM.
