### ISSUE TITLE
Allow the ability to create project with name containing only numbers (ex. `2023`)

### ISSUE THREAD

**Issue by OatmealLick** [commercialhaskell/stack#6363]
Make sure that you are using the latest release (currently Stack 2.13.1). See the
[upgrade instructions](http://docs.haskellstack.org/en/stable/install_and_upgrade/#upgrade)
to upgrade.

Please state as clearly as you can what feature you are recommending, and the
motivation for adding the feature.

Allow the ability to create project with name containing only numbers (ex. `2023`). There is no OS-level restrictions regarding numeric-only directory names.

**Comment by hasufell** [comment]
That is not a valid package name as per the cabal spec.

See https://cabal.readthedocs.io/en/stable/cabal-package.html#package-properties

Regex is:

```
[[:digit:]]*[[:alpha:]][[:alnum:]]*(-[[:digit:]]*[[:alpha:]][[:alnum:]]*)*
```

BNF:

```
package-name      = package-name-part *("-" package-name-part)
package-name-part = *DIGIT UALPHA *UALNUM

UALNUM = UALPHA / DIGIT
UALPHA = ... ; set of alphabetic Unicode code-points
```

**Comment by mpilgrem** [comment]
@OatmealLick, I understand that you are referring to a project name (the name of the directory that contains the files for one or more packages and Stack's project-level configuration, etc) as opposed to a package name (which is constrained as @hasufell identifies). However, I am not clear what you are after. If you command `stack new <name>`, Stack creates a single-package project where the project has the name of the package (so the project's name has to be a valid package name). If you want to name that project differently from the package it contains, then apply the relevant shell's 'rename directory' command.

**Comment by mpilgrem** [comment]
I've improved the online documentation of `stack new`.
