### ISSUE TITLE
`--file-watch` is broken in master when editing tests.

### ISSUE THREAD

**Issue by mbj** [commercialhaskell/stack#6365]
I'm using the current `master` branch build. 

Note that editing library files triggers a build nicely, the issue is in `--file-watch` semantics not triggering on *test* files.

### Steps to reproduce

Run `stack build --test --file-watch` on any repository, editing a test file after the file watch is waiting.

### Expected

I expect the build/test to be started from the file edit event.

### Actual

Stack does not start a build/test.

~~~text
stack build --test
~~~

### Method of installation

`stack build --copy-bins` from current `master` sha: 89603bb8f3592afc663d564125c1c547429575a6

### Platform

Arch Linux.

**Comment by theobat** [comment]
Oh well, actually, it seems like it's a very simple bug : https://github.com/commercialhaskell/stack/blob/master/src/Stack/PackageFile.hs#L64
I simply forgot to gather the tests files 👎 :sweat_smile:

**Comment by theobat** [comment]
Your call : I won't be able to do it before this evening or tomorrow evening. You're welcome to do it if you'd rather have it earlier.

**Comment by mbj** [comment]
> Your call : I won't be able to do it before this evening or tomorrow evening. You're welcome to do it if you'd rather have it earlier.

did not get to it, other stuff came up. I think you should take it.

**Comment by mpilgrem** [comment]
I'll have a stab at the fix.

**Comment by mbj** [comment]
@mpilgrem Thank you for the fix!
