### ISSUE TITLE
Facilitate testing of a Hackage package candidate

### ISSUE THREAD

**Issue by brandonchinn178** [commercialhaskell/stack#6374]
I'm not sure if this is already supported somehow, but is it possible to test a Hackage package candidate with extra-deps? It seems like right now, the only option is to go via the Git feature of extra-deps.

**Comment by mpilgrem** [comment]
@brandonchinn178, you can specify the URL to the archive file, as in the case of any other local or remote archive file: https://docs.haskellstack.org/en/stable/pantry/#local-or-remote-archives-such-as-github-archives. For example:
~~~haskell
resolver: lts-21.24
extra-deps:
- https://hackage.haskell.org/package/tar-0.6.0.0/candidate/tar-0.6.0.0.tar.gz
~~~

However, be aware, that Stack assumes that packages in archive files are immutable. It would be good to extend `stack unpack` to be able to bring down a local copy of package candidates.

**Comment by brandonchinn178** [comment]
Sounds good! I'm happy with this either being a docs update or some improvement to stack unpack/extra-deps to make this more ergonomic.

**Comment by mpilgrem** [comment]
@brandonchinn178, the `master` branch version of Stack now has `stack unpack PACKAGE --candidate`. See: https://docs.haskellstack.org/en/latest/unpack_command/
