### ISSUE TITLE
Document that Stack use `-O2` by default

### ISSUE THREAD

**Issue by SmartHypercube** [commercialhaskell/stack#6381]
I failed to find any documentation that mentions this. I would like to be able to find this information with ctrl-f on one of these pages:
- https://docs.haskellstack.org/en/stable/GUIDE/
- https://docs.haskellstack.org/en/stable/build_command/
- https://docs.haskellstack.org/en/stable/yaml_configuration/

Also, this is a little misleading: https://docs.haskellstack.org/en/stable/build_command/#-fast-flag
> Pass the flag to build your project with the GHC option -O0. -O0 disables GHC's optimisations (which is GHC's default).
It makes me think -O0 is the default.

**Comment by mpilgrem** [comment]
@SmartHypercube, Stack does not use GHC's `-O2` flag by default. Stack's default is to use GHC without specifying any GHC `-O*` flag. GHC's approach to optimisation is documented here: https://downloads.haskell.org/ghc/latest/docs/users_guide/using-optimisation.html. I'll revist the online documentation for Stack's `--fast` falg if you have found it ambiguous.

**Comment by mpilgrem** [comment]
`stack build --fast` acts as a 'reset' at the command line, if you have previously set a higher level of GHC optimisation in a YAML configuration file: see https://docs.haskellstack.org/en/stable/yaml_configuration/#ghc-options.

**Comment by SmartHypercube** [comment]
Sorry, but I'm still a bit confused. I did 3 tests:
1. No `-O2` or `-O0` in `package.yaml`, `stack build`, `stack exec <name>`.
2. Specify `ghc-options` `-O2` in `package.yaml`, `stack build`, `stack exec <name>`.
3. No `-O2` or `-O0` in `package.yaml`, `stack build --fast`, `stack exec <name>`.

I noticed that 1 and 2 produce a faster program, and 3 produces a slower program. This indicates that Stack (or GHC) uses `-O2` by default. Is this the expected behavior? Is this Stack's or GHC's default setting?

**Comment by mpilgrem** [comment]
@SmartHypercube, I think I have identified what is going on. Stack's default is, indeed, not to pass any `-O*` to GHC. However, Cabal's default seems to be to pass `-O` by default: https://cabal.readthedocs.io/en/stable/setup-commands.html#cmdoption-runhaskell-Setup.hs-configure-enable-optimization.

**Comment by mpilgrem** [comment]
I've added something to Stack's online documentation to document Cabal's default behaviour.

**Comment by SmartHypercube** [comment]
Thanks for your effort and finding the cause so quickly!
