### ISSUE TITLE
Force update Hackage index

### ISSUE THREAD

**Issue by brandonchinn178** [commercialhaskell/stack#6395]
I was trying to run `verify-package` with a package, but `stack unpack` kept trying to use an old version, not the most recent version. `cabal update` didn't help. But when I explicitly specified a version, stack said something like "could not find version, fetching hackage index".

Either a flag should be added to `stack unpack` to force fetch the hackage index, or there should be a new stack comment analogous to `cabal update` that fetches Stack's copy of the hackage index

### Stack version

~~~text
stack --version
Version 2.13.1, Git revision 8102bb8afce90fc954f48efae38b87f37cabc988 x86_64 hpack-0.36.0
~~~

### Method of installation

GHCup

**Comment by mpilgrem** [comment]
@brandonchinn178, I've put that through.

**Comment by brandonchinn178** [comment]
Thank you!
