### ISSUE TITLE
Release Stack 2.15.1

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#6397]
Some pre-conditions:

* [x] A working GitHub self-hosted runner for Linux/ARM64 
* [x] Release, and depend upon, `ansi-terminal > 1.0` with ConHost bug-fix (https://github.com/UnkindPartition/ansi-terminal/pull/164)
* [x] Release, and depend upon, `tar-conduit-0.4.1` with pax extended header data bug-fix (https://github.com/snoyberg/tar-conduit/pull/39)
* [x] Decide whether or not to merge https://github.com/commercialhaskell/stack/pull/6358
* [x] If it works, merge https://github.com/commercialhaskell/stack/pull/6451
* [x] Complete the current refactoring (field name prefixes and @theobat's splitting up of `Stack.Build.Execute`), and test thoroughly that nothing has been broken as a consequence

**Comment by mpilgrem** [comment]
@theobat, you will see from the addition of the last item in the check list above that when the current 'refactoring' actity is safely completed, I plan to release Stack 2.15.1.

**Comment by mpilgrem** [comment]
The first release candidate for Stack 2.15.1 has been published.

**Comment by hasufell** [comment]
@mpilgrem are you going to update https://github.com/haskell/ghcup-metadata/blob/develop/ghcup-vanilla-0.0.8.yaml

**Comment by mpilgrem** [comment]
@hasufell, I have added something to the documentation of Stack's release process to act as a reminder to request an update to GHCup's metadata configuration files.

**Comment by mpilgrem** [comment]
Now released.
