### ISSUE TITLE
Provide `--resolver global` option

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#645]
Provide a `--resolver=global` to overwrite resolver, defined in local stack.yaml with a resolver defined in `~/.stack/global/stack.yaml`. This is convenient way to not have to remember which is your global resolver when you want to reuse your global db.

**Comment by snoyberg** [comment]
OK, give it a shot now on master.

**Comment by k-bx** [comment]
@snoyberg hmm, doesn't seem to work for me:

```
➜  stack git:(master) stack --resolver global install
option --resolver: Invalid resolver value: global. Possible valid values include lts-2.12, nightly-YYYY-MM-DD, and ghc-7.10. See https://www.stackage.org/snapshots for a complete list.

Usage: stack [--version] [--help] [--docker*] ([--verbosity VERBOSITY] |
             [-v|--verbose]) ([--system-ghc] | [--no-system-ghc])
             ([--install-ghc] | [--no-install-ghc]) [--arch ARCH] [--os OS]
             [-j|--jobs JOBS] [--extra-include-dirs DIR] [--extra-lib-dirs DIR]
             ([--skip-ghc-check] | [--no-skip-ghc-check]) ([--skip-msys] |
             [--no-skip-msys]) [--local-bin-path DIR] [--resolver RESOLVER]
             [--no-terminal] [--stack-yaml STACK-YAML] COMMAND
➜  stack git:(master) stack --version
Version 0.1.2.1, Git revision ee83f6c95f0e4f059f4e80b8d055deedcfefcb96
```

**Comment by snoyberg** [comment]
I'm an idiot, I completely misread the issue as `--resolver nightly`, which is what I implemented.

Just to clarify how I think you're asking for this to work: this will take the resolver value from the global stack.yaml and reuse it, but then be equivalent to just passing that resolver in via `--resolver`? The point being: we're only reusing the global snapshot, not the global "locally installed" database, correct?

I'm not certain I understand the use case here, which is probably why I got confused in the first place.

**Comment by snoyberg** [comment]
Alright, should be working this time, can you test it out?

**Comment by k-bx** [comment]
@snoyberg works like a charm, thank you!

**Comment by vlatkoB** [comment]
What do you think about allowing `resolver: global` in project's stack.yaml as well?

**Comment by gibiansky** [comment]
For the record, it's really unintuitive that argument order matters, and that
```bash
stack install --resolver nightly ihaskell
```
fails while
```
stack --resolver nightly install ihaskell
```
works.

I'm not sure if this is on purpose, though...?

**Comment by borsboom** [comment]
@gibiansky: see #519
