### ISSUE TITLE
Wrong versions/Cabal file in uploaded release

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#647]
http://hackage.haskell.org/package/bloodhound-0.7.0.0 Aeson should have a higher upper bound.

http://hackage.haskell.org/package/bloodhound-0.7.0.1 is proper.

Don't remember doing anything special. Just sdist and upload, but stack upload caused the weird deps problem with .0

**Comment by snoyberg** [comment]
aeson does have an upper bound in 0.7.0.0. stack does nothing to modify .cabal files, in fact up until very recently tarballs were generated with `cabal sdist`.

**Comment by bitemyapp** [comment]
My point is that the upper bound is too low and I didn't edit the file between the uploads from Stack and Cabal.

**Comment by snoyberg** [comment]
I still have no idea how stack could have caused this. Without a repro, we really can't do anything about this.

**Comment by bitemyapp** [comment]
I'll see what I can do to put one together.

**Comment by snoyberg** [comment]
Closing due to lack of repro. If you can find a repro, we can reopen.
