### ISSUE TITLE
Make `stack path` require ghc for less options

### ISSUE THREAD

**Issue by deemp** [commercialhaskell/stack#6484]
In https://github.com/freckle/stack-action/issues/33, we discussed how to prevent `stack` from downloading GHC before restoring stack dependencies in CI because they can already include a GHC.

More specifically, we need `stack path --programs` to not trigger a GHC download in GitHub Actions. Is it doable?

I see that a similar issue was resolved for `stack path --stack-root` (https://github.com/commercialhaskell/stack/issues/6340).

What other options can be decouple from GHC downloads?

**Comment by mpilgrem** [comment]
@deemp, this is now implemented in the `master` branch version of Stack.

**Comment by deemp** [comment]
@mpilgrem, will you please make a release so that we can use the new version in pipeline?

**Comment by mpilgrem** [comment]
Stack 2.17.1 will likely come sooner than my usual quarterly rhythmn for releases. However, as 2.15.1 was only released a week ago it will be a few weeks yet.

**Comment by mpilgrem** [comment]
@deemp, Stack 2.15.3 is released, with this behaviour change.

**Comment by deemp** [comment]
Thank you!
