### ISSUE TITLE
Need documents about old LTS, downgrade stack and multiple stack executables

### ISSUE THREAD

**Issue by chansey97** [commercialhaskell/stack#6497]
### Background

On GitHub, there are many old stack projects that use old LTS (before lts-12.0).

Can we seamlessly build them by the latest Stack?

It seems not. 

I did some experiments and asked [the question about the experiment](https://stackoverflow.com/questions/78025629/is-it-safe-to-downgrade-haskell-stack-version) on StackOverflow a few days ago. Unfortunately, no one answered at the moment.

The motivation is that hope to build projects using the author's original snapshot environment, because the purpose of Stack is reproducible build.

The question is that:

1. Is it safe to downgrade Stack version?

   I found [the closed issue](https://github.com/commercialhaskell/stack/issues/4909), but it was 5 years ago.

2. How to configure multiple Stack executables? 

   For example, I want to install two stack.exe into

   ```
   C:/env/haskell/stack/v2.15.1/stack.exe
   C:/env/haskell/stack/v1.5.0/stack.exe
   ```

   For new projects, I can use `PATH=C:/env/haskell/stack/v2.15.1` ; for old projects (e.g. before lts-12.0), I can use `PATH=C:/env/haskell/stack/v1.5.0`, but they share `STACK_ROOT`. Is it safe?

The key point here is: Does Stack ensure that even for different Stack versions, the database under `STACK_ROOT` would never corrupt? Currently, [Stack docs](https://docs.haskellstack.org/en/stable/upgrade_command/) only mentioned about upgrade but not downgrade nor multiple stack executables.

Thanks.

### Stack version

Version 2.15.1

**Comment by mpilgrem** [comment]
@chansey97, 'never' is a high hurdle but I often find myself switching between Stack versions without lasting damage. That said, I tend to switch between the `master` branch version and the most recent or next most recent 'official' releases. Stack 2.15.1 still supports LTS < 12.0 (that is Cabal < 2.2, hence GHC < 8.4.1). However, if you were worried, you could always re-set [`STACK_ROOT`](https://docs.haskellstack.org/en/stable/environment_variables/#stack_root) when you switch Stack executables on the PATH.

**Comment by mpilgrem** [comment]
@chansey97, regarding your specific question about `hpack-convert`, I'll look at it after work, but I can't immediately see that the use of that package is limited to GHC <= 8.0.2 (LTS 8.13).

**Comment by chansey97** [comment]
Thanks!
