### ISSUE TITLE
Stack 2.15.1 does not support GHC < 8.2.1

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#6498]
Stack's support of Cabal < 2.2 (GHC < 8.4.1) is deprecated in Stack 2.15.1, but Stack 2.15.1 was intended to still support Cabal < 2.2, including GHC 8.0.x (Cabal-1.24.0).

However, a [change](https://github.com/commercialhaskell/stack/issues/6267) was made in Stack 2.15.1 - ironically, to avoid a bug in GHC 8.0.1 and 8.0.2 - that made use of GHC's flags `-no-keep-hi-files` and `-no-keep-o-files`. However, those flags were introduced with GHC 8.2.1. So, in practice, inadvertently, Stack 2.15.1 does not support GHC < 8.2.1 (Cabal < 2).

I am not planning to fix this because the `master` branch version of Stack has now dropped support for Cabal < 2.2. A work-around may be to downgrade to Stack 2.13.1.

**Comment by mpilgrem** [comment]
Reopening, given #6509.

**Comment by mpilgrem** [comment]
@andreasabel, I expect to release Stack 2.15.3 tomorrow night. If you want to test it (unless you use GHCup to manage Stack versions): `stack upgrade --source-only --git --git-branch rc/v2.15`.

**Comment by mpilgrem** [comment]
@andreasabel, Stack 2.15.3 is released.

**Comment by andreasabel** [comment]
Thanks! (Sorry I didn't have time to give it a try first.)
