### ISSUE TITLE
GHC options in script mode?

### ISSUE THREAD

**Issue by AKurilin** [commercialhaskell/stack#650]
Hey folks,

Been trying to use some custom GHC options when running a .hs file as a stack script:

```
#!/usr/bin/env stack
-- stack --resolver lts-2.3 --install-ghc runghc --package email-validate --package cassava --package classy-prelude --ghc-options Wall
```
but I get the following result:

```
Usage: stack runghc [-- ARGS (e.g. stack ghc -- X.hs -o x)] ([--plain] |
                    ([--ghc-package-path] | [--no-ghc-package-path])
                    ([--stack-exe] | [--no-stack-exe]) [--package ARG])
  Run runghc

If you are trying to use stack as a script interpreter, a
'-- stack [options] runghc [options]' comment is required.
See https://github.com/commercialhaskell/stack/wiki/Script-interpreter
```

so instead I end up using the pragma to accomplish a similar result:

    {-# OPTIONS_GHC -Wall #-}

Are `--ghc-options` or `--pedantic` not available in script mode as of yet or am I configuring the script totally incorrectly?

**Comment by snoyberg** [comment]
It's not about script mode, it's about the `runghc` command: it doesn't support those. You can, however, pass them as arguments after `--`, e.g.:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-2.17 --install-ghc runghc --package turtle -- -Wall -Werror
{-# LANGUAGE OverloadedStrings #-}
import Turtle
main = echo "Hello World!"
```

**Comment by AKurilin** [comment]
Great, that explains it, thank you.
