### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by MarkowEduard** [commercialhaskell/stack#6519]
https://docs.haskellstack.org/en/stable/GUIDE/

The Cabal User Guide the definitive reference for the [Cabal file format](https://cabal.readthedocs.io/en/stable/cabal-package.html).

Should read

The Cabal User Guide is the definitive reference for the [Cabal file format](https://cabal.readthedocs.io/en/stable/cabal-package.html).

**Comment by mpilgrem** [comment]
Thanks!
