### ISSUE TITLE
Add `stack config set recommend-stack-upgrade`

### ISSUE THREAD

**Issue by m4lvin** [commercialhaskell/stack#6546]
I was expecting
```
stack config set recommend-stack-upgrade false
```
to work, similar to `stack config set system-ghc --global true` etc.

This would provide a more programmatic way to disable the warning shown when running an old version of stack:
```
Warning: You are currently using Stack version 2.13.1 but version 2.15.3 is available.
         
         You can try to upgrade by running stack upgrade
         
         Tired of seeing this? Add recommend-stack-upgrade: false to
         /home/codegrade/.stack/config.yaml.
```

(Motivation/background: I am running `stack` in containers for autograding student code. They should not see with this warning (and in other steps I use `--silent`, but here I want to show compile errors). For now I have a script to write to `config.yml` manually, but that seems a bit fragile.)

**Comment by mpilgrem** [comment]
@m4lvin, thanks for the suggestion. I'll try to implement it.

**Comment by mpilgrem** [comment]
This is implemented in Stack's `master` branch. If you are not using GHCup to manage versions of Stack: `stack upgrade --source-only --git`.

**Comment by m4lvin** [comment]
Wow, super quick!

Looking at the code and because I just now saw the notification about `nix` being in my PATH the first time, maybe a generic way to set `notifyIfNixOnPath`, `notifyIfGhcUntested` and so on with `stack config` would make sense?

**Comment by m4lvin** [comment]
Okay, I do not actually have a specific need for that one.
