### ISSUE TITLE
add ability to specific abstract resolver in stack.yaml

### ISSUE THREAD

**Issue by evan0greenup** [commercialhaskell/stack#6556]
Beside a concrete resolver specification like `lts-22.7` or `nightly-2024-04-19`, it would be nice to make the resolver specified to `lts` or `nightly` which use latest `lts-*` or `nightly-*` at the moment when `stack.yaml` is accessed by the `stack` command.

**Comment by mpilgrem** [comment]
@evan0greenup, thanks for reporting. That is, in fact, a long-standing and deliberate design decision, explained here: https://docs.haskellstack.org/en/stable/GUIDE/#snapshots-and-changing-your-compiler-version. This also duplicates #1878, so I am going to close it as a duplicate.
