### ISSUE TITLE
`HsOpenSSL` `Custom` build output advises use of `cabal.project`

### ISSUE THREAD

**Issue by andreasabel** [commercialhaskell/stack#6578]
Seen at https://github.com/hackage-trustees/hackage-cli/actions/runs/9066793674/job/24910501337#step:7:1459
 ```
HsOpenSSL                        > Error: setup: Can't find OpenSSL library.
HsOpenSSL                        > Install it via 'brew install openssl' or 'port install openssl'.
HsOpenSSL                        > 
HsOpenSSL                        > If you already have OpenSSL installed, specify the location
HsOpenSSL                        > of the installed library in cabal.project:
HsOpenSSL                        > 
HsOpenSSL                        > package HsOpenSSL
HsOpenSSL                        > extra-include-dirs: ...
HsOpenSSL                        > extra-lib-dirs: ...
HsOpenSSL                        > 
HsOpenSSL                        > or use
HsOpenSSL                        > 
HsOpenSSL                        > cabal configure --extra-include-dirs=... --extra-lib-dirs=...
```
I suspect these helpful messages are coming from the `HsOpenSSL` custom setup, but they make a laughing stock out of `stack`...  
Let me find out...

Caused by the fix of https://github.com/haskell-cryptography/HsOpenSSL/issues/75:
- https://github.com/haskell-cryptography/HsOpenSSL/commit/68067cd245f9252708b54817c1a92ca18ec567bc

**Comment by mpilgrem** [comment]
@andreasabel, noted. As this is unrelated to Stack's own code, and you have opened an issue in the relevant package's repository, I will close this issue.
