### ISSUE TITLE
Why parse only to ignore --stack-yaml in a script?

### ISSUE THREAD

**Issue by philderbeast** [commercialhaskell/stack#6600]
If a `--stack-yaml` option in a stack script is ignored then why is it parsed?

https://github.com/commercialhaskell/stack/blob/035ffea0866cd4d74f5b3618c28071410320f33c/src/Stack/Script.hs#L144

If I comment out the resolver line then the parse fails:

```yaml
message: "This is a stack.yaml file for a script."
allow-newer-deps:
  - dhall
allow-newer: true
# resolver: nightly-2024-05-18
```

I struck this when trying to set the resolver on-the-fly with:

```
$ GHC_VERSION=9.8.2 STACKAGE_VERSION=nightly-2024-05-18 make -f project-files.mk stack.yaml
...
Ignoring override stack.yaml file for script command: /.../stack.script.yaml

Error: [S-6602]
       Stack could not load and parse
       /.../stack.script.yaml as a YAML configuraton file.
       
       While loading and parsing, Stack encountered the following error:
       
       Aeson exception:
       Error in $: failed to parse field "snapshot": keys ["snapshot","resolver"] not present
       
       For help about the content of Stack's YAML configuration files, see (for the most recent
       release of Stack) http://docs.haskellstack.org/en/stable/yaml_configuration/.
...
```

This is the script header:

```Haskell
#!/usr/bin/env stack
-- stack script --resolver=nightly-2024-05-18 --package=base --package=dhall --package=filepath --package=text --stack-yaml=stack.script.yaml
```

**Comment by philderbeast** [comment]
Could script errors like these also have error codes?

**Comment by mpilgrem** [comment]
The short answer is that, currently, `stack script` uses other parts of the overall configuration, via `withConfig`, and the (ignored) `stack.yaml` configuration comes along for the ride. See module `Stack.Script`.

**Comment by mpilgrem** [comment]
@philderbeast, the behaviour was indeed a regression introduced by #6080, it should be fixed by:

* https://github.com/commercialhaskell/stack/pull/6601

**Comment by philderbeast** [comment]
Thanks for the quick fix @mpilgrem. I can confirm that the linked `--stack-yaml=stack.script.yaml` is ignored and not parsed. I also tried invalid YAML (with `:`, or `%`, or `*` as its single character content, verified as invalid by https://onlineyamltools.com/validate-yaml) as well as commenting out the resolver line.
