### ISSUE TITLE
GitHub self-hosted runner for AArch64 offline, pending re-configuration

### ISSUE THREAD

**Issue by mpilgrem** [commercialhaskell/stack#6605]
The self-hosted runner machine ran out of space, apparently due to the space taken up by versions of the runner software. I deleted the `actions-runner` software and reinstalled the latest version from https://github.com/actions/runner/releases, to free up space. However, I do not have rights to access the 'New self-hosted runner' option under Settings/Actions/Runners in this repository, which I think is needed to be able to configure the runner. On Slack, I've asked @snoyberg for help.

**Comment by snoyberg** [comment]
Hey @mpilgrem I've just bumped your permissions on the repo to admin, you should be able to do anything needed.

**Comment by mpilgrem** [comment]
@snoyberg, many thanks, and thanks for the pointer about `tmux`.
