### ISSUE TITLE
data-default-instances-base fails to build on windows with nightly snapshots/ghc 7.10

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#661]
On a windows 7 machine I get an error like the below when installing with nightly/ghc 7.10 (but not with lts/ghc 7.8):
```
C:\Users\Mariners Bay>stack --resolver nightly-2015-07-13 install data-default-instances-base
Using resolver: nightly-2015-07-13 specified on command line
data-default-instances-base-0.0.1: configure
data-default-instances-base-0.0.1: build

--  While building package data-default-instances-base-0.0.1 using:
      C:\\Users\\Mariners Bay\\AppData\\Local\\Programs\\stack\\i386-windows\\ghc-7.10.1\\bin\\runhaskell.exe -pack
age=Cabal-1.22.2.0 -clear-package-db -global-package-db -package-db=C:\Users\Mariners Bay\AppData\Roaming\stack\sna
pshots\i386-windows\nightly-2015-07-13\7.10.1\pkgdb\ C:\Users\MARINE~1\AppData\Local\Temp\stack5000\Setup.hs --buil
ddir=.stack-work\dist\i386-windows\Cabal-1.22.2.0\ build
    Process exited with code: ExitFailure 1
    Logs have been written to: "C:\\Users\\Mariners Bay\\AppData\\Roaming\\stack\\global\\.stack-work\\logs\\data-d
efault-instances-base-0.0.1.log"

    Configuring data-default-instances-base-0.0.1...
    Building data-default-instances-base-0.0.1...
    Preprocessing library data-default-instances-base-0.0.1...
    [1 of 1] Compiling Data.Default.Instances.Base ( Data\Default\Instances\Base.hs, .stack-work\dist\i386-windows\
Cabal-1.22.2.0\build\Data\Default\Instances\Base.o )
    C:\Users\Mariners Bay\AppData\Local\Programs\stack\i386-windows\ghc-7.10.1\mingw\bin\ar.exe: .stack-work\dist\i
386-windows\Cabal-1.22.2.0\build\libHSdata-default-instances-base-0.0.1-LR4yndHAJKeFBWh17G7OLY.a-3516\libHSdata-def
ault-instances-base-0.0.1-LR4yndHAJKeFBWh17G7OLY.a: No such file or directory
```

**Comment by simonmichael** [comment]
It looks like https://github.com/haskell/cabal/issues/2502 , perhaps a newer cabal will fix it.

**Comment by manny-fp** [comment]
Have you tried it with the ghc-7.10.2 release candidate?

**Comment by simonmichael** [comment]
I did not. I did try installing the latest cabal-install, but couldn't figure out how to make stack use it.

**Comment by snoyberg** [comment]
stack doesn't use cabal-install at all, just the Cabal library. In order to get the new library, you could either install it to the global GHC database, or (as @manny-fp mentioned) use GHC 7.10.2, which has the newer version included.

I'm not certain that this will actually fix the problem, though, we may need to do something else.

**Comment by snoyberg** [comment]
This does seem to be resolved when using GHC 7.10.2, closing. @simonmichael if you still hit this problem after upgrading, please report back.

**Comment by tomberek** [comment]
@snoyberg : How does one upgrade to 7.10.2 or the Cabal library to 1.22.6.0 with stack. I'm on nightly-2015-07-30.

**Comment by snoyberg** [comment]
`stack setup --reinstall` should do it. If you get stack from master, you can also try out `stack setup --upgrade-cabal` to just upgrade to the newest Cabal library.

**Comment by tomberek** [comment]
Worked well, thanks. Also dealing with some issues with building on Cygwin/WIndows, updating haskell-vim-now to use `stack` vice `cabal`, etc. Good job on the tooling work you've done. The community appreciates it.

**Comment by simonmichael** [comment]
I haven't had access to a windows machine to retest since, but this sounds good. Now windows users should be able to stack install hledger-web. Thank you!
