### ISSUE TITLE
Build one `ide-backend-server` per snapshot (for stack-ide)

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#662]
Currently `stack` doesn't manage installing `ide-backend-server`, so you need to ensure the right one is on the PATH / in the bin dirs for the project.

See #657.  While having an `ide-backend-server` per project isn't so bad, ideally we'd only need one per snapshot.

**Comment by snoyberg** [comment]
I'd say one per snapshot (which should be the default) is the right thing
to do.

**Comment by mgsloan** [comment]
Good point! I've updated the title / description.

**Comment by jcpetruzza** [comment]
Just to repeat here what I proposed in #657, it would be nice if this feature could be somewhat configurable:

  1. to allow a non-snapshot version of `ide-backend-server` to be used (which would then be built in the project, not the snapshot)

  2. to have installed in the snapshot/project other development tools that depend on `ghc` (or on `haskell-src-exts`), such as `HaRe`, `hlint`, `hindent`, etc.

**Comment by rvion** [comment]
What would be the best ?

 1. `stack ide --setup`
 2. `stack ide` automatically setting up ide-backend-server for current snapshot it not present
 3. `stack setup --ide` to specify ide-backend-server is wanted too
 4. `stack setup` automatically setting up ide-backend-server for current snapshot it not present

Any other suggestion ?

**Comment by snoyberg** [comment]
I'm a bit confused; how is the requirement for this issue more than just running `stack build ide-backend-server`?

**Comment by mgsloan** [comment]
@snoyberg I thought the issue was more than that because "ideally we'd only need one per snapshot".  However, I just realized that executables built from packages in the snapshot do get shared.  Awesome!
