### ISSUE TITLE
Option for stack build to build all local dependents while building set of local packages

### ISSUE THREAD

**Issue by viviag** [commercialhaskell/stack#6622]
### Use case

We have a monorepo with a single `stack.yaml` and multiple packages forming some non-trivial and non-complete dependency graph regardless of external dependencies.

This repo is deployed via CI which performs `stack install`. Packages in the monorepo are partially distinct in the sense that some updates do not affect some of the packages. We do not want to update their deployments when this is the case.

In our setup, if a binary reaches the CI artifacts, it is getting deployed, so the solution must be on the build level. We can run `stack install <package>` only for packages affected by update. To collect packages directly changed in the update, it's quite easy to parse some form of `git diff <--opts>` output.
But then we need to know which packages are affected. This is doable by parsing the output of `stack dot` command (or some other way I missed), but it's more complex. Stack probably could do it on itself, as it definitely knows the dependency graph and detects dependencies, probably executing the algorithm for the same task on a graph with arrows reversed.

Hence the feature request:

### Feature description

On run with `stack build --with-dependents pkg1 pkg2` `stack` detects local dependents of local packages `pkg1` and `pkg2` and builds them also.

**Comment by mpilgrem** [comment]
@viviag, I am seeking to understand better what you are after. May I give a simple example? Imagine you have a project `test6622` with two local packages: `package1` and `package2`, each in their own package directory, where `package2` has an exectuable that depends on the main library of `package1`. That is:

The `package.yaml` of `package1`:
~~~yaml
name: package1
version: 0.1.0.0
dependencies:
- base

library:
  source-dirs: src
~~~ 

The `package.yaml` of `package2`:
~~~yaml
name: package2
version: 0.1.0.0
dependencies:
- base
- package1

executables:
  package2-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
~~~

and the project-level configuration file:
~~~yaml
snapshot: lts-22.28
packages:
- package1
- package2
~~~

If I build `package2` (`stack build package2`), Stack first builds `package1`, its local dependency.

If I edit the source code of `package1` and re-build `package2`, Stack recognises that change and first re-builds `package1`.

If I edit the source code of `package2` and re-build `package2`, Stack recognises that it does not need to re-build `package1` and re-builds only `package2`.

I don't follow what different behaviour you are seeking. Please can you elaborate further?

**Comment by viviag** [comment]
@mpilgrem 

If you build `package1`, Stack will only build `package1`. But there is a `package2` which behaviour may change due to update of `package1`. I am seeking an option to tell `stack` to build all the local packages which depend, directly or indirectly, on a set of packages explicitly mentioned in the `build` command.

Assume there is a following global configuration file:
```
snapshot: lts-22.28
packages:
- package1
- package2
- package3
- package4
- package5
```
with the following dependency graph (arrows like in the output of `stack dot `):
```
package1 -> package2
package2 -> package3
package4 -> package5
```
Assume also `package1` and `package4` have executables. I am pushing a change in `package3`. I want CI to rebuild `package2` and `package1` as probably affected by the change, install `package1`, but keep `package4` and `package5` intact. In the procedure I have it will save me from redundant redeploy of  `package4` executable.

**Comment by mpilgrem** [comment]
@viviag, the executables that are built will be in the `bin` directory of the `stack path --local-install-root` directory. Stack will not re-build an executable if it does not need to and that will be reflected in the 'last modified' date of the executable files in that directory. So, rather than use `stack build --copy-bins` (that is, `stack install`) to copy all the files from that directory, you could use a OS command that only copies files that are last modified after a specified date and time (i.e. the date and time when the `build` command was started).

**Comment by viviag** [comment]
@mpilgrem Thank you. It solves the problem in our use case and I don't have other use cases for the initial issue statement in mind.

**Comment by mpilgrem** [comment]
@viviag, in the same vein, but simpler, you can simply delete the existing contents of that `bin` directory before `stack build` - Stack does not refer to its existing contents during building.

**Comment by viviag** [comment]
@mpilgrem 
This observation helps not only with simplicity, it removes dependency on a CI build cache. I think it is optimal for our scenario. Thank you again.
