### ISSUE TITLE
Stack passes -optcxx=-std=c++14 even when told by cabal file to use version 17.

### ISSUE THREAD

**Issue by noahmartinwilliams** [commercialhaskell/stack#6626]
### General summary/comments (optional)
I was working on my fork of llvm-hs [here](https://github.com/noahmartinwilliams/llvm-hs/tree/llvm-16) (which is currently at commit 6f70e9846e425275252aaa1e10b31c1d33831e83 which can be found [here](https://github.com/noahmartinwilliams/llvm-hs/commit/6f70e9846e425275252aaa1e10b31c1d33831e83)) and it won't compile. I used strace on "stack build" to find out what was going wrong, and when it calls up ghc it tells ghc to pass arguments to the c++ compiler telling it to use both version 14 and version 17 of the c++ standard.

The llvm-hs/llvm-hs.cabal file specifies to use version 17, but stack tells ghc to use 14 and 17. This seems to cause it to default to version 14 and generate tons of c++ errors.

### Steps to reproduce

```
git clone --recursive git@github.com:noahmartinwilliams/llvm-hs.git -b llvm-16
cd llvm-hs
stack build
```

To see what strace spit out just run:
`strace -s 1024 -e trace=process -ff stack build 2>&1 | grep 'std=c++14'`

### Expected
I expected it to compile the library and pass just -optcxx=-std=c++17 to ghc.

### Actual

It told ghc to use both version 17 and 14 of the c++ standard.

~~~text
stack build --verbose
~~~
see attached file.
[errors.txt](https://github.com/user-attachments/files/16288711/errors.txt)

### Stack version

~~~text
stack --version
Version 2.15.7, Git revision 75bb479f04755c1daf91ec8f445e17e2ba2ab7a3 x86_64 hpack-0.36.0
~~~

### Method of installation

ghcup 

### Platform
Arch Linux up to date as of July 14th 2024.

**Comment by mpilgrem** [comment]
@noahmartinwilliams, thanks for reporting. I see that `llvm-hs.cabal` has a `Custom` build type, and - from `error.txt` - that Stack builds a `setup` executable. Stack then uses it with (formatted):
~~~text
Run process within /home/noah/src/accelerator/package-sources/llvm-hs/llvm-hs/: /home/noah/src/accelerator/package-sources/llvm-hs/llvm-hs/.stack-work/dist/x86_64-linux-tinfo6/ghc-9.2.7/setup/setup 
--verbose=1 
--builddir=.stack-work/dist/x86_64-linux-tinfo6/ghc-9.2.7 
build 
lib:llvm-hs 
--ghc-options ""
~~~

So, one thing on my mind is: Why is Stack not passing any GHC options to the custom `setup` executable? Answer: the 'configure' step is being skipped in `error.txt`.

Starting from scratch on Ubuntu (via WSL), I have (formatted):
~~~text
Run process within .../llvm-hs/llvm-hs/: .../llvm-hs/llvm-hs/.stack-work/dist/x86_64-linux-tinfo6/ghc-9.2.7/setup/setup 
--verbose=1 
--builddir=.stack-work/dist/x86_64-linux-tinfo6/ghc-9.2.7 
configure 
--with-ghc=.../.stack/programs/x86_64-linux/ghc-tinfo6-9.2.7/bin/ghc-9.2.7 
--with-ghc-pkg=.../.stack/programs/x86_64-linux/ghc-tinfo6-9.2.7/bin/ghc-pkg-9.2.7 
--user 
--package-db=clear 
--package-db=global 
--package-db=.../.stack/snapshots/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/pkgdb 
--package-db=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/pkgdb 
--libdir=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/lib 
--bindir=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/bin 
--datadir=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/share 
--libexecdir=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/libexec 
--sysconfdir=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/etc 
--docdir=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/doc/llvm-hs-16.0.0 
--htmldir=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/doc/llvm-hs-16.0.0 
--haddockdir=.../llvm-hs/.stack-work/install/x86_64-linux-tinfo6/8aca01cf5dfa6064e1ca6fa4e8d6c905bec4fbabf4f713f0a4e9ecde36d440a1/9.2.7/doc/llvm-hs-16.0.0 
--dependency=Cabal=Cabal-3.6.3.0 
--dependency=array=array-0.5.4.0 
--dependency=attoparsec=attoparsec-0.14.4-Jg2DNZol4ow40I1tChhYQd 
--dependency=base=base-4.16.4.0 
--dependency=bytestring=bytestring-0.11.4.0 
--dependency=containers=containers-0.6.5.1 
--dependency=exceptions=exceptions-0.10.4 
--dependency=llvm-hs-pure=llvm-hs-pure-16.0.0-F6rgz83938eI6Qq1MHgN2p 
--dependency=mtl=mtl-2.2.2 
--dependency=template-haskell=template-haskell-2.18.0.0 
--dependency=transformers=transformers-0.5.6.2 
--dependency=utf8-string=utf8-string-1.0.2-KOPUXETbFeRLoWT9IcwQzV 
--dependency=attoparsec:attoparsec-internal=attoparsec-0.14.4-Kq41zOIZ2VFHSdA7la3FYB-attoparsec-internal 
-f-debug 
-f-llvm-with-rtti 
--ghc-options -optcxx=-std=c++14  <<<< This is the key part 
--ghc-options -optcxx=-lstdc++    <<<< This is the key part
--ghc-options -optcxx=-fno-rtti   <<<< This is the key part
--exact-configuration 
--ghc-option=-fhide-source-paths
~~~

**Comment by mpilgrem** [comment]
The options that Stack is passing to Cabal (the library) is consistent with what is being requested in the project-level configuration file (`stack.yaml`), namely:
~~~yaml
resolver: lts-20.16

packages:
- llvm-hs
- llvm-hs-pure

# We should not need to do this, but unfortunately, removing it breaks the stack build.
ghc-options:
  llvm-hs: -optcxx=-std=c++14 -optcxx=-lstdc++ -optcxx=-fno-rtti

# vim: nospell
~~~

**Comment by mpilgrem** [comment]
@noahmartinwilliams, I am having difficulty in reproducing your problem because I don't know how to get an out-of-date version of `llvm-config`. I am stuck on:
~~~text
[warn] llvm-hs     > setup: The program 'llvm-config' version >=16.0 && <16.1 is required but the
[warn] llvm-hs     > version found at /usr/bin/llvm-config is version 18.1.3
~~~

That said, I think Stack is behaving as expected, because:
* the Cabal file specifies `-optcxx=-std=c++17` as a GHC option; and
* in addition, the `stack.yaml` file specifies `-optcxx=-std=c++14` as a further GHC option;

so, I would expect Cabal (the library) to pass both on to GHC. If you only want `-optcxx=-std=c++17`, don't specify the additional GHC option.

**Comment by mpilgrem** [comment]
@noahmartinwilliams, sorry - closed prematurely, in error.

**Comment by noahmartinwilliams** [comment]
@mpilgrem , Don't worry, it's okay. 
Changing it in the stack.yaml file prevents it from passing the wrong option to gcc, but llvm-hs still won't compile. :/
Thanks for your help anyways.
