### ISSUE TITLE
Local (flag) configuration file

### ISSUE THREAD

**Issue by maxigit** [commercialhaskell/stack#6650]
At the moment you can have two configuration files:  `config.yaml` (project agnostic) and `stack.yaml` project specific. However, sometime a 2nd project specific file could be useful. The common usecase is compiling for developpment or production. In that case, I have two folders one for development when a `dev` flag is set and a production one without this flag.
Profiling can also requires a third folders with a different set of flags.

I am not aware of any method to "save" (or freeze) the set of flags without having to modify the `stack.yaml` file. 
The issue with modifying the `stack.yml` file is usually it is under source control and it is somewhat easy to mess up and copy a set of flag value from developpment to production.

An easy solution would be to allow 2 (or more) `stack` files. This way, one file could locally override the normal `stack.yaml` but kept out of source control (`.gitignore`) if needed.

The problem of having multiple files is how to name them and in which order apply or merge them. As the feature is mainly requested for flags, I was thinking of just have a `flags.yaml` (or `stack-flags.yaml`) file. 

What do you think ? (Were the request be accepted I'd be happy to try to implement it)

**Comment by mpilgrem** [comment]
@maxigit, thanks for reporting. `config.yaml` is global and contains non-project specific options. The project-level configuration file (named `stack.yaml`, by default) contains project-specific and non-project specific options.

It is not uncommon to have more than one project-level configuration file available for a project. You give the example of changing Cabal flags. Another is specifying a different version of GHC. Selecting between project-level configuration files is done using `--stack-yaml` at the command line or by using the `STACK_YAML` environment variable (which takes precedence). So, in your example, you might command:
~~~text
stack --stack-yaml stack-flags.yaml build
~~~

The contents of the chosen project-level configuration file affects Stack's caching, so you should be able to switch from one file to another without Stack building unnecessarily.

Stack's use of configuration files is documented here: https://docs.haskellstack.org/en/stable/configure/yaml/

**Comment by maxigit** [comment]
Sorry I wasn't clear. What I mean is not having multiple files that you can chose from (as per your example) but multiple files at the same time (like yesod do) when each file override previously set variable.

In my example `stack-flags.yaml` would only set the flags (without even the `flags:` keyword). 
The point is , once your directory is setup , you do `stack build` withou having to remember which file to select: stack picks up all the yaml files present and merge them somehow.

**Comment by mpilgrem** [comment]
Stack's design choice is to put all project-level configuration into a single file (with the possibility of a heirarchy of custom snapshot fies). Splitting aspects of configuration between different files brings complexity, and it is not clear to me that the benefits could outweigh the 'costs'.

However, currently, I think you can have a synthetic version of what you are seeking by putting most of the non-local project-level configuration into a custom snapshot file (eg `my-snapshot.yaml`) and leaving the local project-level configuration (if there is any) and the Cabal flags in the `stack.yaml` (so it behaves like your `stack-flags.yaml).

That is, the custom snapshot has:
~~~yaml
snapshot: lts-22.33 # Or whatever you are using
packages: # If any (used like non-local extra-deps)
  ...
~~~

and `stack.yaml` has the residue:
~~~yaml
snapshot: my-snapshot.yaml
flags:
  ...
~~~

**Comment by maxigit** [comment]
> Splitting aspects of configuration between different files brings complexity
To the final user of the developer ?
> and it is not clear to me that the benefits could outweigh the 'costs'
I am probably underestimated the cost.

The benefit is to have ONE stack file (under version control) which works. I can clone a repo and launch `stack install` and everything works fine. And then create a second file which override the flags (for example) and ignore this 2nd file in git (.gitignore). Being ignored by git is the raison d'etre of this second file : it allow me to change my configuration locally without risk to be propagated upstream.

However I wasn't aware of the "local" snapshots. This doesn't really allow to hide local modifications to git  but might help my curret workflow. Out of curiosity how do work on stack in development mode (with some DEVEL flags set) but make sure that those flags are not set for CI on deployment ?

**Comment by mpilgrem** [comment]
To answer your last question, Stack itself uses its `etc/script/release.hs` script in its CI. That script expressly turns off Stack's `developer-mode` Cabal flag (disabled by default, but enabled in Stack's `stack.yaml`).

So, people developing Stack with Stack using the default `stack-yaml` get 'developer mode', and Stack's official releases (created via the CI) turn it off.

**Comment by maxigit** [comment]
Fair enough.
