### ISSUE TITLE
stack clean should avoid depending on stack.yaml info

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack#669]
1. stack build some project
2. edit the stack.yaml to set the resolver to a nightly plan that hasn't been cached yet
3. stack clean

Expected: just a normal stack clean
Actual:

```
$ stack clean
DDownloaded nightly-2015-07-24 build plan.    
Caching build plan
```

It was a bit jarring that `stack clean` did this.

(Perhaps worth creating a second issue: `DDownloaded`)

```
$ stack --version
Version 0.1.2.1, Git revision 2af3d1bb4818a80188391440c13aee69d231ff86
```

**Comment by snoyberg** [comment]
This is enough of a corner case that it's not worth pursuing.
