### ISSUE TITLE
stack test does not rebuild the test suite when there is a change in the test suite.

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#671]
When I make a change to the library section of my project, `stack test` behaves as expected.

When I edit a test file and run `stack test`, stack does not rebuild the test suite to pick up the change. Instead it just executes the test suite. I have to modify a file from the library section to get the test section to rebuild.

I saw this behavior when upgrading to the latest git version perhaps a week ago. I just did a `stack upgrade --git` and I see the same behavior

```
~/.local/bin/stack --version             
Version 0.1.2.1, Git revision 545b3ec46f694da4c0c4367a4f50461d56c0a196
stack --version
Version 0.1.2.1, Git revision 1d585b176db07ddf0cc087c3e73d033766d2d44c (dirty)
```

**Comment by snoyberg** [comment]
There's not nearly enough information here to diagnose correctly, but I have a very strong feeling you're reporting #481, which @DanBurton is working on right now. If that's the case: you're missing modules in the other-modules section of your test suite.

**Comment by gregwebs** [comment]
Thanks. That could be it. Let me know when #481 is fixed and I will try it out

**Comment by snoyberg** [comment]
Should probably be closed as a dupe, but reassigning to @manny-fp for now, who's taking over #481.

**Comment by borsboom** [comment]
@gregwebs, fix for #481 is in master.  Can you try it?

**Comment by gregwebs** [comment]
great! Thank you!

**Comment by gregwebs** [comment]
To be clear, I tested with version dc10066580e683db86b825229e22a2ae1000db26
