### ISSUE TITLE
stack build package-from-hackage should advise the user

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#673]
If a user performs `stack build package-from-hackage-0.2` then they need to perform one of 2 additional actions.

* copy the executable
* add the library to the cabal file

If there is no --copy-bins argument, and the package is not in the .cabal file, stack should tell the user:

    package package-from-hackage-0.2 is built. You should expose its library by adding it to project.cabal or expose its executables by running: stack build --copy-bins package-from-hackage-0.2.

https://stackoverflow.com/questions/31593438/how-can-packages-be-unhidden-when-using-only-stack

**Comment by snoyberg** [comment]
I disagree. `stack build foo-0.2` has meaning if the user wants to immediately use it for `stack ghc` or similar. I think the current behavior is correct.

**Comment by gregwebs** [comment]
Good point. However, I would say that if a cabal file exists the use case you mention is not wanted 99% of the time

**Comment by snoyberg** [comment]
And then we'll include the warning and someone who's trying to do that will get very confused about why he's getting a warning about a perfectly valid use case. I don't say this theoretically, we get these kinds of bug reports regularly.
