### ISSUE TITLE
docker: stack runghc should pass stdin/stdout through

### ISSUE THREAD

**Issue by DanBurton** [commercialhaskell/stack#675]
```
$ cat echo.hs
main = interact id
$ echo 'hello' | runghc echo.hs
hello
$ echo 'hello' | stack runghc echo.hs
```

If stack uses its default (non-docker) configuration, then this will work as expected, with output `hello`. If stack is configured to be inside of a docker container, then there will be no output.

Stack version: 6adb449f1083a0c4768924d59956b46486b31be7

**Comment by manny-fp** [comment]
This is an unfortunate case where we can't get a Docker container to behave like a normal process in all cases, and we're stuck between two non-ideal solutions when stdin/stdout/stderr are not connected to a terminal:

1) Use `docker run -i` (but not `-t`), in which case piping standard input works (also nice for running in an Emacs shell) but docker processes never exit when run in Bamboo and other Java-based tools.

2) Use `docker run` (without `-i` or `-t`), in which case Bamboo works but piping standard input doesn't. 

So we ended up switching to option (2).  We never did do any deep investigation into why Bamboo triggers this problem, so it would be better to have a way to correct the underlying issue

**Comment by snoyberg** [comment]
I'm reading this as wontfix, closing.
