### ISSUE TITLE
stack init automatically chooses wrong haskell version

### ISSUE THREAD

**Issue by egonSchiele** [commercialhaskell/stack#677]
I ran `stack init`, and then `stack build`. I got this error message:

    $ stack build

    GHC version mismatched, found 7.8.3 (x86_64), but expected version 7.8.4 (x86_64) (based on resolver setting in /foo/bar/stack.yaml). Try running stack setup

That's correct, my ghc version is `7.8.3`:

    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 7.8.3

Is it possible for stack to use the ghc version I have installed, instead of having me download a new one? Maybe this would mean choosing a different plan?

**Comment by snoyberg** [comment]
`stack init` takes a number of arguments to tell it what to prefer. In this case though, there is no snapshot that supports GHC 7.8.3, so there's nothing you can do about it. If desired, you could switch to the `ghc-7.8` resolver, but that means you'll have to manually choose all package dependencies.

**Comment by egonSchiele** [comment]
Ok, makes sense. Should I close this issue?

**Comment by snoyberg** [comment]
Sure
