### ISSUE TITLE
stack ghci needs to explicitly state which package versions to use

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#678]
Otherwise, if a local database has an older version than the snapshot, the snapshot version will be used. Originally reported at: https://github.com/commercialhaskell/stack/issues/658

**Comment by chrisdone** [comment]
Done in 3fe10b9.

**Comment by chrisdone** [comment]
@snoyberg Can you confirm? I assumed `loadSourceMap` yields the correct set of versions.

**Comment by snoyberg** [comment]
I wasn't experiencing this problem myself, so I can't check that it's resolved, but the code looks right.
