### ISSUE TITLE
--no-terminal accepted in unexpected position

### ISSUE THREAD

**Issue by Fuuzetsu** [commercialhaskell/stack#679]
As per `stack --help`:

```
Usage: stack [--version] [--help] [--docker*] ([--verbosity VERBOSITY] |
             [-v|--verbose]) ([--system-ghc] | [--no-system-ghc])
             ([--install-ghc] | [--no-install-ghc]) [--arch ARCH] [--os OS]
             [-j|--jobs JOBS] [--extra-include-dirs DIR] [--extra-lib-dirs DIR]
             ([--skip-ghc-check] | [--no-skip-ghc-check]) ([--skip-msys] |
             [--no-skip-msys]) [--local-bin-path DIR] [--resolver RESOLVER]
             [--no-terminal] [--stack-yaml STACK-YAML] COMMAND
```

So I would expect `stack build --haddock --ghc-option "-fPIC" --no-terminal` to not work, but it does. But `stack build --haddock --no-terminal --ghc-options "-fPIC"` does not work. From the help text I'd expect that only `stack --no-terminal build …` would work.

To me it seems that the `stack` flags are also accepted after `COMMAND` which is not reflected in the help text.

**Comment by manny-fp** [comment]
This is a symptom of #519, closing in favour.
