### ISSUE TITLE
stack freeze

### ISSUE THREAD

**Issue by jkarni** [commercialhaskell/stack#681]
When working with both stack and cabal, a `stack freeze` option would be very helpful in making sure both use the same versions of dependencies. This would likely just add `extra-deps` to the `cabal.config` file one can already get from stackage.

**Comment by snoyberg** [comment]
Can you check out the new `list-dependencies` command and see if that provides something close to what you're looking for?

**Comment by jkarni** [comment]
Perfect! Thanks very much!
