### ISSUE TITLE
Request: extend hermetic builds / reproducability to stack haddock

### ISSUE THREAD

**Issue by rrnewton** [commercialhaskell/stack#684]
We run on all kinds of machines with various messy local installs (e.g. where sysadmins installed old RHEL or Ubuntu packages for ghc in `/usr/bin`), so I greatly love `stack --no-system-ghc --install-ghc`.

But this approach doesn't seem to extend to other "tools" like haddock.  We began to run into errors with `haddocks` based on mismatched GHC versions cropping up in the path and then leading to failures of `stack haddock`.

It would be great to have either:

  * `--no-system-haddock`, or
  * `--no-system-tools` that completely disregards all system installed ghc/happy/haddock/alex/etc tools.

**Comment by snoyberg** [comment]
We need more information in order to understand this correctly. The version of `haddock` should be coming from the installed GHC dist, and does so in every case I've found. Can you clarify exactly what you did and what errors you saw?

**Comment by rrnewton** [comment]
Sure. There was an old haddock built with GHC 7.8.3 lying around and stack tried to use it for a build with a newer GHC (installed by stack orotherwise) and then barfed.

**Comment by snoyberg** [comment]
That's not really enough information. Where was is "lying around?" Even if it was early on the PATH, stack places all of its directories at the beginning of the PATH, so it should take precedence.

**Comment by rrnewton** [comment]
Ah, that makes sense, but stack had not installed haddock *at all* in this case.  The *only* haddock available was the old one sitting in the PATH, and `stack haddock` grabbed and used that one, even though the project was being built with a different version of (stack-installed) GHC.

So with the philosophy of LTS snapshots, we alway specify a specific version of all the packages we depend on, but is there a way for a `stack.yaml` to specify a specific haddock tool version that it should use for `stack haddock`?

**Comment by snoyberg** [comment]
The `haddock` executable ships with GHC, which is why whenever you use the stack-installed GHC you get its copy of haddock. Perhaps you were using the system-installed GHC and didn't realize it?

**Comment by rrnewton** [comment]
Ah right, since it's on hackage I guess I forgot it ships with GHC.

Does this mean `--no-system-ghc` should imply "no system haddock"?  That is, should the behavior be:

  * `stack haddock` -- uses system `ghc` and `haddock` and they'd better match
  * `stack --no-system-ghc haddock` -- uses stack versions of both, and it doesn't matter if there are "bad" haddocks or ghcs in the PATH.

Maybe the errors I was getting was because I was in the former case and forgetting to pass in --no-system-ghc.  I'll close this now and reopen if I get a reproducible violation of the above policy.

**Comment by snoyberg** [comment]
Yes, that's the correct intended behavior.
