### ISSUE TITLE
"base version 4.7.0.2 found     - system-uuid requires <4 && <4"

### ISSUE THREAD

**Issue by k-bx** [commercialhaskell/stack#690]
For package `system-uuid`, which has this piece in its cabal-file:

```
library
  if flag(split-base)
    build-depends             : base >= 4 && < 5
  else
    build-depends             : base < 4
```

Stack init says:

```
* Build plan did not match your requirements:
    base version 4.7.0.2 found
    - system-uuid requires <4 && <4

    murmur-hash not found
    - system-uuid requires -any && -any
```

This seems very confusing to me.

**Comment by snoyberg** [comment]
`stack init` tests out a number of different flag combinations. However, it doesn't tell you about everything it tests, because that would be too much output. Instead, it just reports on an arbitrary flag set.

The real error is that none of the build plans have murmur-hash in them, so system-uuid cannot be used without adding it. My strong recommendation is to add both murmur-hash and system-uuid to Stackage if you intend to use them.

The following stack.yaml works:

```yaml
resolver: lts-2.18
extra-deps:
- murmur-hash-0.1.0.8
```

**Comment by k-bx** [comment]
@snoyberg thank you! I am indeed adding a bunch of packages to stack right now (murmur-hash added yesterday), the issue-report is that error is somewhat confusing, maybe just making it slightly different would resolve the issue. Seeing "<4 && <4" is just confusing. If you think this bug-report is not worth taking care of – I'm totally ok closing it, I just find things like that weird-looking and potentially confusing stack's users.

**Comment by snoyberg** [comment]
I'm about to push a commit that would simplify `<4 && <4` down to `<4`, so I do think you're right on raising that ;). I can't think of any other improvements though.

**Comment by k-bx** [comment]
Haha, ok! Let's not spend more time on this then :)

**Comment by snoyberg** [comment]
OK, commit pushed, so if you build from master, you should be safe.

**Comment by k-bx** [comment]
```
➜  system-uuid-2.1.1  stack build
While constructing the BuildPlan the following exceptions were encountered:

--  While attempting to add dependency,
    Could not find package murmur-hash in known packages

--  Failure when adding dependencies:
      murmur-hash: needed (-any), latest is 0.1.0.8, but not present in build plan
    needed for package: system-uuid-2.1.1

Recommended action: try adding the following to your extra-deps in /Users/kb/workspace/system-uuid-2.1.1/stack.yaml
- murmur-hash-0.1.0.8

You may also want to try the 'stack solver' command
```

Perfect!
