### ISSUE TITLE
Could not upgrade to GHC 7.10.2 using stack

### ISSUE THREAD

**Issue by ecognium** [commercialhaskell/stack#695]
I thought I will upgrade my GHC to 7.10.2 using `stack` as I used it to install GHC 7.10.1.  Unfortunately I run into some issues.  Copying the discussion from here: http://www.reddit.com/r/haskell/comments/3f1fif/announce_ghc_version_7102/ctlspao

OS: Mac OS X Yosemite. 

    ⇒  stack upgrade
    Fetched package index.
    Populated index cache.
    GHC version mismatched, found 7.10.1 (x86_64), but expected version 7.8.4 (x86_64) 
    (based on resolver setting in 
    /var/folders/f0/sv1p2xfs1t75vt2_nptr68r80000gn/T/stack-upgrade22491/stack-9.9.9/stack.yaml). 
    Try running stack setup
    
    dev:~/dev/api|master⚡ ⇒  stack setup
    Downloaded nightly-2015-07-30 build plan.
    Caching build plan
    GHC on PATH would be used
    
    dev:~/dev/api|master⚡ ⇒  which ghc
    /Users/dev/.stack/programs/x86_64-osx/ghc-7.10.1/bin//ghc
   

After trying borsboom's suggestion I get this: 
  
     ⇒  which ghc
     ghc not found
    
     ⇒stack setup 
     Would add the following to PATH: /Users/dev/.stack/programs/x86_64-osx/ghc-7.10.1/bin
    
    ## I removed the ghc folder from .stack/programs 
    
    ⇒  stack setup
    Executable named ghc not found on path: ["/Users/dev/.stack/programs/x86_64-osx/ghc-7.10.1/bin",
    "/usr/local/bin","/usr/bin","/bin","/usr/sbin","/sbin","/usr/local/go/bin","/Users/dev/opt/go_appengine",
    "/Users/dev/stack","/Users/dev/opt/hdevtools"]
    
    ⇒  stack upgrade
    Fetched package index.
    Populated index cache.
    No GHC found, expected version 7.8.4 (x86_64) (based on resolver setting in 
    /var/folders/f0/sv1p2xfs1t75vt2_nptr68r80000gn/T/stack-upgrade47856/stack-9.9.9/stack.yaml). 
    Try running stack setup

I have an active project going so I have not had a chance to completely remove stack and try fresh.

**Comment by snoyberg** [comment]
Removing the folder isn't correct, you need to remove the `.installed` file. Can you try running `stack setup --reinstall`?

**Comment by johnynek** [comment]
I think I am seeing the same issue:
```
[tw-mbp-oscar depgraph.hs]$ stack --version
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
[tw-mbp-oscar depgraph.hs]$ stack setup
Would add the following to PATH: /Users/oscar/.stack/programs/x86_64-osx/ghc-7.8.4/bin
[tw-mbp-oscar depgraph.hs]$ stack upgrade
Fetched package index.
Populated index cache.
Already at latest version, no upgrade required
[tw-mbp-oscar depgraph.hs]$ stack setup --reinstall
Already downloaded.
Installed GHC.
Would add the following to PATH: /Users/oscar/.stack/programs/x86_64-osx/ghc-7.8.4/bin
```
How do I configure for 7.10.2? This is on OSX 10.10.4

**Comment by snoyberg** [comment]
You have a resolver chosen which indicates GHC 7.8.4 (probably LTS). You need to make a selection that would force GHC 7.10. One possibility is to try running:

    stack --resolver ghc-7.10 setup

**Comment by ecognium** [comment]
Hi Michael, 

This is what happens when I try to change the resolver. I also removed the .installed file. 

     ⇒  stack --resolver ghc-7.10 setup
    Using resolver: ghc-7.10 specified on command line
    GHC on PATH would be used

    ⇒  stack setup --reinstall
    Using resolver: lts-2.16 from global config file: /Users/dev/.stack/global/stack.yaml
    Preparing to download ghc-7.8.4 ...^Cuser interrupt

    # global stack.yaml looks like this
    flags: {}
    packages: []
    extra-deps: []
    resolver: lts-2.16

I cannot figure our what `lts-2.16` maps to. Do I have to change this to something else to make it download ghc-7.10.2? Also, I don't recall touching this file before -- existence of this file is something I just learned from running `reinstall`. When I did stack setup with my project a month ago, it automatically downloaded `ghc-7.10.1`..not sure why it is trying to download `ghc-7.8.4` now.

**Comment by snoyberg** [comment]
Did you try both setting the resolver and passing in --reinstall?

**Comment by ecognium** [comment]
That did it! Thank you.  After your initial comment I was searching the FAQ for the resolver setting and I could not find anything. It will be super helpful if this command is listed in the FAQ. 

    stack --resolver ghc-7.10 setup --reinstall
    Using resolver: ghc-7.10 specified on command line
    Downloaded ghc-7.10.2.
    Installed GHC.
    Would add the following to PATH: /Users/dev/.stack/programs/x86_64-osx/ghc-7.10.2/bin

**Comment by snoyberg** [comment]
Please do add any documentation you'd find useful to the FAQ

**Comment by ecognium** [comment]
Sounds good. Since this is new to me: to update the FAQ, I will clone, make the change and send a PR?

**Comment by snoyberg** [comment]
No. It's just a wiki page, you can edit it on the Github web interface

**Comment by ecognium** [comment]
Got it. That's so much easier. Will update it.
