### ISSUE TITLE
'stack new' fails for directories with underscores in them

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#696]
```
$ mkdir foo_bar
$ cd foo_bar/
/tmp/foo_bar$ stack new

Writing: LICENSE
Writing: Setup.hs
Writing: app/Main.hs
Writing: foo_bar.cabal
Writing: src/Lib.hs
Writing: test/Spec.hs
Writing default config file to: /tmp/foo_bar/stack.yaml
Basing on cabal files:
- /tmp/foo_bar/foo_bar.cabal

Unable to parse cabal file /tmp/foo_bar/foo_bar.cabal: NoParse "name" 1
```

Version 0.1.2.2, Git revision a1d7799d6585653d5629ff1224ba740a36b8ab0f

**Comment by mboes** [comment]
This is a Cabal limitation: Cabal does not allow package names with underscores.

**Comment by alanz** [comment]
Yes, but surely stack should warn about this, or replace any underscore
with a hyphen when invoking the templating machinery.

**Comment by mboes** [comment]
Replacing with hyphens is what `cabal-install` happens to do. Makes sense to replicate.

**Comment by manny-fp** [comment]
Similarly, a directory name that starts with digits or contains periods also fails.  My inclination would be to just attempt to attempt to parse the directory name as a package name before starting the `stack new` process, and emit a helpful error message that indicates what a valid package name is if it doesn't parse.  When `stack new` is improved, it could include prompts and/or command-line arguments to set the package name instead.

**Comment by DanBurton** [comment]
Stack new already accepts arguments for setting the package name. It
accepts arbitrary arguments for the selected template. The default template
only has one argument right now called "name". The following should work:

stack new name:my-pkg

As for parsing the default name, it should be relatively easy to see what
part of the Stack.New code to tweak. (This is a good feature for a new
contributor to work on.)

On Friday, July 31, 2015, Emanuel Borsboom <notifications@github.com> wrote:

> Similarly, a directory name that starts with digits or contains periods
> also fails. My inclination would be to just attempt to attempt to parse the
> directory name as a package name before starting the stack new process,
> and emit a helpful error message that indicates what a valid package name
> is if it doesn't parse. When stack new is improved, it could include
> prompts and/or command-line arguments to set the package name instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/696#issuecomment-126722837>
> .
>


-- 
-- Dan Burton

**Comment by alanz** [comment]
I think the problem at the moment is that `stack new` creates the project
but then stops with a parse error on the cabal file. It is not at all clear
initially what the problem is.

I think simply failing with an appropriate error message and suggesting
using a name parameter is all that is needed.

**Comment by snoyberg** [comment]
@alanz interested in taking a stab at doing the name parsing before the rest of the code runs?

**Comment by alanz** [comment]
Possibly. My plate is pretty full at the moment. If it is not done when I
have some time I will jump in.

**Comment by chrisdone** [comment]
I've just pushed the start of an overhaul of `stack new` which now creates the directory itself and does not fiddle with any existing thing. There is also a better error message now about invalid package names.

```
chris@retina:/tmp/696$ stack new foo_bar^
Expected valid package name, but got: foo_bar^

Usage: stack new PACKAGE_NAME [TEMPLATE_NAME] ([--solver] |
                 [--resolver RESOLVER] | [--prefer-lts] | [--prefer-nightly])
                 [--force] [--ignore-subdirs]
  Create a brand new project
chris@retina:/tmp/696$ stack new foo
Downloading template "new-template" to create project "foo" in foo/ ...
Writing default config file to: /tmp/696/foo/stack.yaml
Basing on cabal files:
- /tmp/696/foo/foo.cabal

Checking against build plan lts-2.19
Selected resolver: lts-2.19
Wrote project config to: /tmp/696/foo/stack.yaml
chris@retina:/tmp/696$ ls foo
app  foo.cabal  LICENSE  Setup.hs  src  stack.yaml  test
```
