### ISSUE TITLE
stack new mypackage should create a brand new project with mypackage instead of new-template

### ISSUE THREAD

**Issue by beerendlauwers** [commercialhaskell/stack#698]
Apologies if this is already possible, I could not find it in the options of `stack new`:

```
Usage: stack new ([--solver] | [--resolver RESOLVER] | [--prefer-lts] |
                 [--prefer-nightly]) [--force] [--ignore-subdirs]
  Create a brand new project
```

I've read elsewhere that `stack new` might become interactive and that all those questions should also be provideable via the command-line, so perhaps do something like `stack new --name mypackage` instead?

**Comment by snoyberg** [comment]
Can you try again with the version on master? `stack new` has changed quite a bit since then. The current functionality is to use the current directory name.

**Comment by DanBurton** [comment]
If I recall correctly, the desired syntax is:

`stack new name:mypackage`

Should work on master. Ping me if it doesn't.

On Friday, July 31, 2015, Michael Snoyman <notifications@github.com> wrote:

> Can you try again with the version on master? stack new has changed quite
> a bit since then. The current functionality is to use the current directory
> name.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/698#issuecomment-126738364>
> .
>


-- 
-- Dan Burton

**Comment by chrisdone** [comment]
@beerendlauwers On master I've just pushed a beginning of an overhaul of the `stack new`. Now you write `stack new foo`:

```
$ stack new foo
Downloading template "new-template" to create project "foo" in foo/ ...
Writing default config file to: /home/chris/Work/stack/foo/stack.yaml
Basing on cabal files:
- /home/chris/Work/stack/foo/foo.cabal

Checking against build plan lts-2.19
Selected resolver: lts-2.19
Wrote project config to: /home/chris/Work/stack/foo/stack.yaml
```
