### ISSUE TITLE
many dependencies for stack install on Debian Jessie

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#699]
If I run the following docker file

``` docker
FROM debian:jessie

ENV DEBIAN_FRONTEND noninteractive

#------------------------------------------------------------------
# From https://github.com/commercialhaskell/stack/wiki/Downloads#debian
RUN echo "2015-07-31"
RUN apt-get update
RUN apt-get install -y wget
RUN wget -q -O- https://s3.amazonaws.com/download.fpcomplete.com/debian/fpco.key | apt-key add -
RUN echo 'deb http://download.fpcomplete.com/debian/jessie stable main'> /etc/apt/sources.list.d/fpco.list
RUN apt-get update
RUN apt-get install -y stack
```

It ends up installing the following as dependencies of stack

```
Step 8 : RUN apt-get install -y stack
 ---> Running in 75349aa3bfec
Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  binutils cpp cpp-4.9 g++ g++-4.9 gcc gcc-4.9 git git-man krb5-locales less
  libalgorithm-c3-perl libarchive-extract-perl libasan1 libatomic1 libbsd0
  libc-dev-bin libc6-dev libcgi-fast-perl libcgi-pm-perl libcilkrts5
  libclass-c3-perl libclass-c3-xs-perl libcloog-isl4 libcpan-meta-perl
  libcurl3-gnutls libdata-optlist-perl libdata-section-perl libedit2
  liberror-perl libexpat1 libfcgi-perl libffi-dev libgcc-4.9-dev libgdbm3
  libgmp-dev libgmpxx4ldbl libgomp1 libgssapi-krb5-2 libisl10 libitm1
  libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2
  liblog-message-perl liblog-message-simple-perl liblsan0 libmodule-build-perl
  libmodule-pluggable-perl libmodule-signature-perl libmpc3 libmpfr4
  libmro-compat-perl libpackage-constants-perl libparams-util-perl
  libpod-latex-perl libpod-readme-perl libpopt0 libquadmath0
  libregexp-common-perl librtmp1 libsasl2-2 libsasl2-modules
  libsasl2-modules-db libsoftware-license-perl libssh2-1 libstdc++-4.9-dev
  libsub-exporter-perl libsub-install-perl libterm-ui-perl
  libtext-soundex-perl libtext-template-perl libtsan0 libubsan0 libx11-6
  libx11-data libxau6 libxcb1 libxdmcp6 libxext6 libxmuu1 linux-libc-dev make
  manpages manpages-dev openssh-client patch perl perl-modules rename rsync
  xauth xz-utils zlib1g-dev
```

Are all of these required? Are they installed to ensure that haskell packages will build?

**Comment by cies** [comment]
Find the dependencies for the `.dev` specified here here:

https://github.com/commercialhaskell/stack/blob/master/scripts/release/templates/deb/docker/run.sh

It seems that `git` and `gnupg` add most of the cruft. I guess `git-core` is sufficient (add a lot less deps to the game). The other offender, `gnupg`, depends on `xloadimage` which depends on the image format devel libs and `libx11`.

I have not found what causes the `*-perl` family to be dependencies. I also seem to remember that "suggestions" are not dependencies by default, while "recommendations" are. Maybe we can make git/gnupg suggestions instead.

**Comment by manny-fp** [comment]
I think git and gnupg really should be recommendations, since they improve stack's functionality significantly (it falls back to less desirable backups, like not checking package signatures, if they are not there).  I'd recommend using apt-get's `--no-install-recommends` option if you don't want them in your docker image (I use that for almost everything I install in Docker images).  I'm hesitant to make it recommend `git-core` instead of `git`, since the description of that package says it is obsolete.  All that said, it would be nice to pare down the transitive dependencies, so if you can find ways to do so without affecting functionality I'd love to see a PR.

**Comment by snoyberg** [comment]
Bump

**Comment by snoyberg** [comment]
Given that we've deprecated the deb packages, can this be closed @borsboom?

**Comment by mgsloan** [comment]
@snoyberg Seems reasonable!
