### ISSUE TITLE
Exclude files from --file-watch and more debugging info

### ISSUE THREAD

**Issue by agrafix** [commercialhaskell/stack#703]
I'm currently moving a project to stack, and it's been working out great so far! I like the `--file-watch` flag, but it seems to rebuild way to often. I think this is due to my emacs configuration which creates temporary files in the source tree. Would it be possible to read .hgignore or .gitignore files to exclude files from being watched? For debugging purposes, it would also be very useful if `stack build --file-watch` gave some information why it thinks a rebuild is useful, eg:

Rebuilding due to changes in files X.hs, Z.hs, ...

**Comment by snoyberg** [comment]
All of the filewatch code is in its own module at `Stack.FileWatch`, and should be relatively easy to modify without diving into the rest of the code. In particular, indicating which files changed should be a trivial change. Interested in trying your hand at a PR for this?

**Comment by agrafix** [comment]
Sure, I'll look into this!

**Comment by snoyberg** [comment]
I've pushed a commit to master that significantly improves this experience. I'm going to close this issue, please ping if master doesn't do what you're looking for.

**Comment by agrafix** [comment]
Alright, great, thank you! I'm very busy this week, but I'll provide feedback next week.
