### ISSUE TITLE
`stack ghci` fails when running on a project that hasn't been built with `stack build` yet

### ISSUE THREAD

**Issue by cleichner** [commercialhaskell/stack#704]
❯❯❯ stack ghci
Configuring GHCi with the following packages: new-template
GHCi, version 7.8.4: http://www.haskell.org/ghc/  :? for help
<command line>: cannot satisfy -package new-template
    (use -v for more information)

That error doesn't give a very good description of the problem in terms of what can be done to fix it. I figured it out after thinking about it for a bit, but running into that error was enough to stop my project progress in its tracks and have me leave and do something else for a while. If the config is found but the project isn't built, can it auto-build before starting ghci so you can't run into this problem on an otherwise working project?

Stack version: stack-0.1.2.0-x86_64-osx
OS version: OS X 10.10.3

**Comment by andrewthad** [comment]
Also, in my experience, `stack ghci` seems to have some unusual behaviors. Calling `:load` and `:reload` doesn't actually cause modules to be rebuilt. I always have to run `stack build`.

**Comment by chrisdone** [comment]
I think this is fixed on stack master. @cleichner Can you try with the master version of stack?

**Comment by chrisdone** [comment]
Think it was fixed in c3284b42463e6b4294b683d2bdd08c7263a23061, which is to not specify `-package x` where `x` is a local source package, as is the case here.

**Comment by borsboom** [comment]
Please reopen if this isn't fixed in master.
