### ISSUE TITLE
Slightly weird argument handling with `--no-terminal`

### ISSUE THREAD

**Issue by rrnewton** [commercialhaskell/stack#706]
I normally am careful to pass stack general options before the command, but I copied a `travis.yml` file linked from the wiki which had this line:

```bash
stack test --only-snapshot --no-terminal
```

But, then when I tried to add an extra option to the end, it failed:

`stack test --only-snapshot --no-terminal --ghc-options="-j3"`

Yet moving the `--no-terminal` to where it should be (before `test`) fixes the problem:

`stack --no-terminal test --only-snapshot --ghc-options="-j3"`

This behavior holds on the 0.1.2.0 release, and a recent dev version, 3135624fc43585329bc4ceed2a9c11b158f4099f.

#### Expected behavior:

That the first two commands above would both fail or succeed (preferably fail).

##### Actual behavior:

First command succeeds and second fails.

**Comment by borsboom** [comment]
Looks like #519.

**Comment by rrnewton** [comment]
Wow, and 679 too!  Sorry for the dup.
