### ISSUE TITLE
Project fails to build if LICENSE is missing

### ISSUE THREAD

**Issue by karls** [commercialhaskell/stack#711]
I noticed this while converting some of my old, `Cabal`-based projects to use `stack`. I noticed that some projects were failing to compile for no apparent reason. I was greeted with error that looks like this:

```bash
% stack build
project-x-0.1.0.0: build
Building project-x-0.1.0.0...
Preprocessing executable 'project-x' for
project-x-0.1.0.0...
[1 of 1] Compiling Main             ( Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/project-x/project-x-tmp/Main.o )
Linking .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/project-x/project-x ...
project-x-0.1.0.0: install
Setup.hs: LICENSE: does not exist

--  While building package project-x-0.1.0.0 using:
      /Applications/ghc-7.10.2.app/Contents/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/karl/.stack/snapshots/x86_64-osx/nightly-2015-08-03/7.10.2/pkgdb/ /var/folders/c7/4_vjptjd75x22wq_xn3flbz00000gn/T/stack5904/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ install
    Process exited with code: ExitFailure 1
```

Turning on the `--verbose` flag showed the missing LICENSE file line as a `[warn]`, to which I did not pay much attention. Only after getting nowhere for some time I added the LICENSE file, just in case. After that, the project compiled without issues. The output of running `stack build --verbose` is [here](http://lpaste.net/1914508751960801280).

The error message is a bit cryptic and I glanced over the fact that it notified me about a missing LICENSE file, which I didn't believe was the cause of the failing build. Perhaps the user experience can be improved here with a better error message and/or fail early if LICENSE is missing?

Steps to reproduce:

1. Create a new project with `stack new`
2. `rm LICENSE`
3. Run `stack build`

Making it build again is as easy as doing:

1. `touch LICENSE`
2. Change a file (e.g the string in `src/Lib.hs`), otherwise recompilation won't be triggered
3. Run `stack build`

```bash
% stack --version
Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911
```

```bash
% cabal --version
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library
```

```bash
% ghc --version
The Glorious Glasgow Haskell Compilation System, version 7.10.2
```

**Comment by snoyberg** [comment]
I am unable to reproduce with stack master using the repro you listed above. Can you try the code on master (or even first try the latest released version) and see if that solves things?

**Comment by karls** [comment]
I've just tried both the latest release (0.1.2.2) and master (0.1.2.7, rev a2c19479), and they both fail in the same fashion.

Here's a screenshot of the workflow to reproduce, right after compiling from master.
<img width="1440" alt="screenshot 2015-08-05 12 13 38" src="https://cloud.githubusercontent.com/assets/251402/9084467/e3612dc8-3b6b-11e5-8267-a52338824a49.png">

I've also just realised that removing the `license-file` field in the `project.cabal` file allows building the project just fine.

**Comment by karls** [comment]
I think ultimately it's up to you guys to decide what to do here, as it's not a major bug or a big issue -- there is a warning, after all. I was just surprised that a missing license file could prevent the project from building.

**Comment by snoyberg** [comment]
I was able to repro now, I don't know why I thought I couldn't before. The error itself is coming from Cabal (the library), not stack. The `runghc Setup.hs install` step is failing when the LICENSE file is missing, which IMO is overkill. This is something we can't reasonably solve in stack. If you want to follow up on this, I'd recommend opening an issue on the cabal tracker.
