### ISSUE TITLE
stack fails on Windows with git package in stack.yaml and no git binary on path

### ISSUE THREAD

**Issue by conklech** [commercialhaskell/stack#712]
On a Windows system with no `git` on the system/user %PATH% and a git repository package in `stack.yaml`, `stack` (sometimes?) completely fails within the project folder.

```
$ cat stack.yaml
[...]
- location:
    git: https://github.com/conklech/threepenny-gui.git
    commit: b426b55bc34704b66da35b256c3e7505b044b636
$ stack build
Executable named git not found on path: ["C:\\ProgramData\\Oracle\\Java\\javapath","C:\\Windows\\system32","C:\\Windows","C:\\Windows\\System32\\Wbem","C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\","C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common","%SystemRoot%\\system32","%SystemRoot%","%SystemRoot%\\System32\\Wbem","%SYSTEMROOT%\\System32\\WindowsPowerShell\\v1.0\\","C:\\Users\\chris\\AppData\\Roaming\\local\\bin"]
$ stack exec -- echo "nothing"
Executable named git not found on path: ["C:\\ProgramData\\Oracle\\Java\\javapath","C:\\Windows\\system32","C:\\Windows","C:\\Windows\\System32\\Wbem","C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\","C:\\Program Files (x86)\\NVIDIA Corporation\\PhysX\\Common","%SystemRoot%\\system32","%SystemRoot%","%SystemRoot%\\System32\\Wbem","%SYSTEMROOT%\\System32\\WindowsPowerShell\\v1.0\\","C:\\Users\\chris\\AppData\\Roaming\\local\\bin"]
$ cd ..
$ stack exec -- where git
Run from outside a project, using implicit global config
Using resolver: lts-2.20 from global config file: C:\Users\chris\AppData\Roaming\stack\global\stack.yaml
C:\Users\chris\AppData\Local\Programs\stack\i386-windows\git-2.4.5.1\cmd\git.exe
```

This condition is fragile. After adding `git.exe` to the %PATH% and running `stack build` (which succeeds), and then opening a new shell with the original %PATH%, `stack` functions normally again, even after `stack clean`. I don't know what the exact preconditions for the buggy behavior are.

**Comment by snoyberg** [comment]
Are you using a system-installed GHC in this case?

What is the resolution you're proposing here? Obviously git *is* necessary in order to execute the build plan.

**Comment by conklech** [comment]
No, there is no system-installed ghc or git. 

The `stack` copy of git is available (see last line of log) and can be run via `stack exec`, but `stack` isn't looking in `%APPDATA%\Programs\stack\...\git-*\cmd\` when it tries to run git within the project directory. (It's not in the list of folders following "Executable named git not found on path:"). I could have made the report clearer on that point; sorry.

The requested resolution is for `stack` to use the `git` installed via `stack setup` in all cases when there is no system `git`.

**Comment by snoyberg** [comment]
Thanks, that clarifies. I've just pushed a commit to the 712-clone-modified-env branch that should resolve this. Can you give it a try and, if it works correctly for you, I'll merge to master and close out this issue.

**Comment by conklech** [comment]
Works perfectly. Thanks!

**Comment by snoyberg** [comment]
Cool, merged to master.
