### ISSUE TITLE
stack new should create simpler project

### ISSUE THREAD

**Issue by seanhess** [commercialhaskell/stack#714]
I'm starting a Haskell meetup group here in Utah, and I've been thinking about beginner friendliness. A critical part of smoothing out the learning curve is to help beginners have early successes. For beginners an executable is more intuitive I think.

I think it would make more sense to have `stack new` create a simple executable instead of a library and executable. I used it when walking someone through their first project and the recursive dependencies confused them. 

I also think that more experienced Haskell devs will have no problem modifying the template to have both a library and an executable if that's what they need. 

What do you think?

**Comment by drwebb** [comment]
Sounds like a good idea, though I'm not sure about it being a default. Though not having it as a default would sort of defeat the whole "it's for beginners". Perhaps `stack new` should present the user a choice like `executable-only`, `library-plus-executable`, `everything-but-the-kitchen-sink`. There are also a lot of experienced Haskell devs trying out stack, so it also makes sense to cater to them.

**Comment by seanhess** [comment]
The main issue is generating a cabal file without having cabal-install on
the command line. If I recommend using stack to new haskellers how can I
get something as simple as cabal init?

**Comment by snoyberg** [comment]
I actually specifically *avoided* trying to reimplement `cabal init`: it gives a false dichotomy between "library only" and "executable only," is bad at encouraging testing, and asks for a lot of information from the user.

One of the goals of `stack new` is to make it easy to have multiple different templates to work from, so having an executable-only option makes sense.

**Comment by chrisdone** [comment]
For a simpler project, we can create a simple template under [stack-templates](https://github.com/commercialhaskell/stack-templates/). The new syntax is simply: `stack new project-name`, with an optional additional argument for the template to use. So if you have a `simple.hsfiles` template, you'll be able to write `stack new myproject simple`.

**Comment by seanhess** [comment]
That would be great! Does this already work? Where does simple.hsfiles need
to be? Or is it bundled with stack?

**Comment by chrisdone** [comment]
@seanhess This works on `master`. I've just copy/pasted `new-template.hsfiles` to `simple.hsfiles` and pushed to [stack-templates](https://github.com/commercialhaskell/stack-templates/blob/master/simple.hsfiles).  Now I can run:

```
chris@retina:/tmp/714$ stack new simple
Downloading template "new-template" to create project "simple" in simple/ ...
Writing default config file to: /tmp/714/simple/stack.yaml
Basing on cabal files:
- /tmp/714/simple/simple.cabal

Checking against build plan lts-2.19
Selected resolver: lts-2.19
Wrote project config to: /tmp/714/simple/stack.yaml
```

It downloads from that specific Git repo automatically.

Feel free to open a PR with the modifications to `simple.hsfiles` that would match your notion of simple. We can rename it later. This support is early days, so nobody will be using it.

I will next be implementing something to list out the available templates from the command-line.

**Comment by chrisdone** [comment]
(Woops, gave a bad example. Updated it with what I meant to demonstrate.)

**Comment by seanhess** [comment]
Just submitted a pull request: https://github.com/commercialhaskell/stack-templates/pull/2. Thanks!

**Comment by snoyberg** [comment]
PR merged. Looks like this can be closed.
