### ISSUE TITLE
stack build fails with: After installing Cabal, the package id couldn't be found

### ISSUE THREAD

**Issue by carlohamalainen** [commercialhaskell/stack#715]
I'm trying to build an old Yesod project using stack. I run stack init with the solver:

    $ stack init --solver
    Writing default config file to: /home/carlo/production/cli-yesod-blog/blog/stack.yaml
    Basing on cabal files:
    - /home/carlo/production/cli-yesod-blog/blog/blog.cabal
    
    Asking cabal to calculate a build plan, please wait
    Selected resolver: ghc-7.6
    Wrote project config to: /home/carlo/production/cli-yesod-blog/blog/stack.yaml

But stack build fails:

    $ stack build
    After installing Cabal, the package id couldn't be found (via ghc-pkg describe Cabal). This shouldn't happen, please report as a bug

**Comment by snoyberg** [comment]
stack doesn't have proper support for GHC 7.6 and earlier, see https://github.com/commercialhaskell/stack/issues/648. master already contains code to print an error message when using an unsupported GHC.

**Comment by carlohamalainen** [comment]
Thanks. For the sake of the archive, I was running this version on Ubuntu 14.04:

    ii  stack                                     0.1.2.0-1189-65246552936b amd64                     The Haskell Tool Stack
