### ISSUE TITLE
stack build in windows fails: ldscript says "file not recognized" for persistent-sqlite

### ISSUE THREAD

**Issue by rubenmoor** [commercialhaskell/stack#720]
Any clue where this might be at?

$ ..\stack.exe build
persistent-sqlite-2.1.4.2: configure
persistent-sqlite-2.1.4.2: build
Progress: 1/2
--  While building package persistent-sqlite-2.1.4.2 using:
      C:\\Users\\TR@FI_02\\AppData\\Local\\Programs\\stack\\i386-windows\\ghc-7.10.1\\bin\\runhaskell.exe -package=Cabal-1.22.2.0 -clear-package-db -global-package-db -package-db=C:\Users\TR@FI_02\AppData\Roaming\stack\snapshots\i386-windows\nightly-2015-06-17\7.10.1\pkgdb\ C:\Users\TR@FI_02\AppData\Local\Temp\stack6308\Setup.hs --builddir=.stack-work\dist\i386-windows\Cabal-1.22.2.0\ build
    Process exited with code: ExitFailure 1
    Logs have been written to: "C:\\Users\\TR@FI_02\\Desktop\\debian-shared\\holger\\core\\.stack-work\\logs\\persistent-sqlite-2.1.4.2.log"

    Configuring persistent-sqlite-2.1.4.2...
    Building persistent-sqlite-2.1.4.2...
    Preprocessing library persistent-sqlite-2.1.4.2...
    [1 of 2] Compiling Database.Sqlite  ( Database\Sqlite.hs, .stack-work\dist\i386-windows\Cabal-1.22.2.0\build\Database\Sqlite.o )

    Database\Sqlite.hs:50:1: Warning:
        The import of `Data.Monoid' is redundant
          except perhaps to import instances from `Data.Monoid'
        To import instances alone, use: import Data.Monoid()
    C:\Users\TR@FI_02\AppData\Local\Temp\ghc2164_0\ghc2164_9.ldscript: file not recognized: File format not recognized
    collect2: ld returned 1 exit status

**Comment by snoyberg** [comment]
No idea. Does this problem reoccur reliably? I'm unable to reproduce any issue building on my system.

The only strange thing I noticed from your output was that your username has an `@` in it, though I have no reason to believe that that's the source of the problem.

**Comment by rubenmoor** [comment]
Thanks!

This issue doesn't seem to be related to stack and I'll open issues elsewhere. Of course, all help is welcome. I'll check if there might be a problem with my windows installation (i.e. try on other pcs). The fact that you don't have the issues gives hope.

This is the current status of my reproducing the bug:

* run something like `stack install persistent-sqlite` or `cabal install persistent-sqlite` in windows and I get
    
		Resolving dependencies...
		Configuring persistent-sqlite-2.2...
		Building persistent-sqlite-2.2...
		Failed to install persistent-sqlite-2.2
		Build log ( C:\Users\TR@FI_02\AppData\Roaming\cabal\logs\persistent-sqlite-2.2.log ):
		Building persistent-sqlite-2.2...
		Preprocessing library persistent-sqlite-2.2...
		[1 of 2] Compiling Database.Sqlite  ( Database\Sqlite.hs, dist\build\Database\Sqlite.o )
		C:\Users\TR@FI_02\AppData\Local\Temp\ghc4324_0\ghc4324_9.ldscript: file not recognized: File format not recognized
		collect2: ld returned 1 exit status
    
* occurs on two different windows machines, both running Win7
* occurs for persistent-sqlite version 2.2 and 2.1.4.2
* occurs for ghc version 7.10.1, 7.8.4

**Comment by rubenmoor** [comment]
I was not able to reproduce this on other windows machines and I conclude there is something odd with my office machines. Moving the issue to [stackoverflow](http://stackoverflow.com/questions/31838660/haskell-package-persistent-sqlite-fails-to-install-in-windows-with-ld-error).
