### ISSUE TITLE
`stack solver` fails on Windows with streamingProcess error

### ISSUE THREAD

**Issue by conklech** [commercialhaskell/stack#723]
On Windows system, `stack solver` fails with this error:

```
$ stack solver
[..]
Asking cabal to calculate a build plan, please wait
C:\Users\chris\AppData\Roaming\local\bin\cabal.exe: streamingProcess: does not exist (No such file or directory)
```

The path stated in the error is the correct path for `cabal.exe`; it exists at that location, and works correctly with `stack exec`. The same error appears when cabal.exe is located elsewhere, with the reported path adjusted accordingly.

The failure mode seems to occur under all circumstances: in or not in a project directory, with or without a `.cabal` file present, etc.

I spent some time looking into the problem a few days ago, with no useful result. If the error message is generated by cabal itself, this may (or may not) be an upstream bug.

(The fix for #712 has no effect on this problem.)

**Comment by snoyberg** [comment]
I just reproed this on Windows, investigating.

**Comment by snoyberg** [comment]
After some investigation: it appears that the command line arguments are somehow triggering this.

**Comment by snoyberg** [comment]
This should now be resolved. The problem does in fact seem to be large argument lists to System.Process functions, which I'll investigate now separately. My workaround- which is actually a better architecture anyway- is to move the package constraints into a config file. Rerunning from master should solve the problem, please ping if it doesn't.

**Comment by snoyberg** [comment]
I've opened up https://github.com/haskell/process/issues/37 to track the upstream bug.
