### ISSUE TITLE
stack install hoogle use wrong folder under Windows

### ISSUE THREAD

**Issue by varosi** [commercialhaskell/stack#724]
I do:
stack install hoogle

and it gave me:
> Installation path C:\Users\me\AppData\Roaming\local\bin\ not found in PATH environment variable
> Copying from C:\Users\me\AppData\Roaming\stack\snapshots\i386-windows\lts-2.15\7.8.4\bin\hoogle.exe to C:\Users\me\AppData\Roaming\local\bin\hoogle.exe
> 
> Installed executables to C:\Users\me\AppData\Roaming\local\bin\:
> - hoogle.exe

Which path of course is not part of PATH under Windows.
Normally using cabal it should go in: 
C:\Users\me\AppData\Roaming\cabal\bin

Windows 8.1 x64

**Comment by snoyberg** [comment]
Please see the documentation on paths:

https://github.com/commercialhaskell/stack/wiki/Downloads#path

Using the cabal path would not make sense for stack. The only purpose for the install command is to make executables available *outside* of the Haskell package ecosystem. stack automatically provides built executables to Haskell code.

**Comment by varosi** [comment]
Okay, thanks!
