### ISSUE TITLE
stack ghci: Ability to specify stanzas of cabal file for different packages 

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#727]
We can specify like:

    $ stack ghci 
    $ stack ghci packagename1 packagename2
    $ stack ghci packagename1:targetname packagename2

**Comment by mgsloan** [comment]
This would be nice!  `stack ghci` currently doesn't work on ide-backend because the test-suite stanza has `monads-tf` whereas the libraries stanza has `mtl`.  This causes ambiguities for some modules.

**Comment by feuerbach** [comment]
I need this badly, esp. because some of my test suites are flag-incompatible with their libraries (eg. wrt. NoImplicitPrelude).

**Comment by chrisdone** [comment]
This is implemented now actually. Try `stack ghci packagename:lib packagename:exe:foo` or whatnot.

**Comment by feuerbach** [comment]
Ha, indeed! So why is this issue marked as open?

**Comment by chrisdone** [comment]
Oversight, it came for free as part of another issue.
