### ISSUE TITLE
Specify local-bin-path

### ISSUE THREAD

**Issue by nmk** [commercialhaskell/stack#730]
`local-bin-path` defaults to `$HOME/.local/bin`. Is there a way to (globally) set this to some other path, possibly in the global or user stack.yaml?

**Comment by drwebb** [comment]
yes, either with `--local-bin-path` on the command line or the
`local-bin-path` option in `stack.yaml`

On Fri, Aug 7, 2015 at 4:47 AM, Nickolay Kolev <notifications@github.com>
wrote:

> local-bin-path defaults to $HOME/.local/bin. Is there a way to (globally)
> set this to some other path, possibly in the global or user stack.yaml?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/730>.
>



-- 
Tristan Webb PhD
Haskell Application Engineer
FP Complete
San Diego, CA
M: 619-452-9545
