### ISSUE TITLE
Stack install without a stack.yaml does nothing

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#733]
Checkout HLint. Go to HLint directory. Type `stack install`. It does nothing, probably because there is no `stack.yml`. If I type `stack init` then it starts doing stuff.

**Comment by DanBurton** [comment]
What is the expected behavior here? Is stack install not informative enough about why it did nothing?

**Comment by ndmitchell** [comment]
I expected it to compile and install HLint. If it's not going to do that (for example, because it doesn't have a stack.yml) then it should say why it isn't doing what I'd expect, and (probably) actually do what I expect - namely automatically run `stack init` first.

**Comment by borsboom** [comment]
This looks like a variant of #687 (`install` implies `build`, so both should be taken care of with the same fix).
