### ISSUE TITLE
Default parallelism broken by -N1

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#741]
We choose the number of jobs currently based on the number of capabilities. When this was switched to -N1 by default, we also switched default jobs to 1, which is clearly a mistake.

Pinging @rrnewton @mboes. Any recommendation on the right way to determine number of parallel jobs to run by default?

**Comment by snoyberg** [comment]
My initial thought is `getNumProcessors`, if there's a problem with this, let me know.

**Comment by mboes** [comment]
LGTM.

**Comment by rrnewton** [comment]
Yes, definitely getNumProcessors.
