### ISSUE TITLE
(docker) lts-2.21 is not a tag in fpco/stack-build

### ISSUE THREAD

**Issue by beerendlauwers** [commercialhaskell/stack#742]
Used `boot2docker` on Windows, went to my directory where `stack.yaml` resides and ran this:

```
$ stack docker pull
Pulling image from registry: 'fpco/stack-build:lts-2.21'
Pulling repository fpco/stack-build
FATA[0011] Tag lts-2.21 not found in repository fpco/stack-build
Could not pull Docker image:
    fpco/stack-build:lts-2.21
There may not be an image on the registry for your resolver's LTS version in
stack.yaml.
```

There is indeed no such tag: https://hub.docker.com/r/fpco/stack-build/tags/

**Comment by borsboom** [comment]
Not every LTS release will necessarily get an image, and it won't necessarily happen right away.  I'd recommend adjusting your resolver to an tag that does exist (such as lts-2.20).
