### ISSUE TITLE
`stack build package' resets flags of other local packages

### ISSUE THREAD

**Issue by bergmark** [commercialhaskell/stack#743]
I commonly have this workflow

1. git pull
2. stack build --ghc-options=-Werror
3. make changes
4. stack build --ghc-options=-Werror changed-package
5. Repeat 3 and 4 until happy.

Currently `4` rebuilds local dependencies of `changed-package` without any flags.

I see two other options which would be preferable to me:
* Use `-Werror` for everything that needs to be built
* Don't care what flags the other packages were built with

Is there a good reason for the current behavior?

**Comment by snoyberg** [comment]
This sounds like: https://github.com/commercialhaskell/stack/wiki/FAQ#stack-sometimes-rebuilds-based-on-flag-changes-when-i-wouldnt-expect-it-to-how-come

**Comment by bergmark** [comment]
It is, thank you.

My problem currently is that I do `4.` by accident not realizing I'll have to rebuild everything (which takes quite some time for us), in my mind `stack build` points to all packages and their (local) dependencies and `stack build foo` should point to foo and all its (local) dependencies.

But since this has been discussed already perhaps there's little point re-iterating the discussing, closing.
