### ISSUE TITLE
Have `stack new` automatically run `git init`, if git is installed

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#745]
And have it be disableable via the config file described in #744.

**Comment by int-index** [comment]
If I have `git` installed, it doesn't mean it's my favorite VCS (maybe I prefer `darcs` or `mercurial`). The feature should be opt-in.

**Comment by mboes** [comment]
Agreed - I think this should be opt-in using a flag.

**Comment by snoyberg** [comment]
I'm tempted to say that, if it's going to be opt-in, it's not even worth doing. Remembering to type `--git-init` is the same as remembering to type `git init` IMO.

**Comment by mboes** [comment]
Yes, that's quite fair. I for one just think that this level of automagic potentially creates more problems than the payoff (saving a *one-off* `git init` on the command line) for the reason @int-index mentions. Also, some companies have mega git repos (one git repo for everything). They may want to `stack new` in some subdir, without this implying a new git repo.

There is the option of making this opt-out, say with `--no-vcs`. But for mercurial/svn/whatever users and those who never want a fresh new git repo, the ideal is to just make this a global setting in `~/.stack/.stack.yaml`. Then it doesn't matter what the default is.

**Comment by feuerbach** [comment]
Agreed that if implemented, this should only be opt-in. Very few people would *expect* `git init` as a side effect of running `stack new`, so this violates the principle of the least surprise.
