### ISSUE TITLE
`stack ghci` fails before `stack build`

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#746]
Checkout Hoogle repo. Type `stack init`. Then:

    C:\Neil\hoogle>stack ghci
    Configuring GHCi with the following packages: hoogle
    GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help
    <command line>: cannot satisfy -package utf8-string
        (use -v for more information)

Shouldn't `stack ghci` install the packages it needs in the sandbox first?

**Comment by chrisdone** [comment]
Ongoing implementation for this. There's an open issue for it here: #629 Awaiting on some work on targets by Michael which should be completed in the next day or so.

**Comment by ndmitchell** [comment]
Thanks, that looks like it subsumes this issue.
