### ISSUE TITLE
Support building code with GHCJS

### ISSUE THREAD

**Issue by mgsloan** [commercialhaskell/stack#748]
There's a WIP branch for this here https://github.com/commercialhaskell/stack/tree/337-ghcjs , pushed so that people can see the status of this / use it as a starting point.

The current commit on that branch, https://github.com/commercialhaskell/stack/commit/b5323e5107eb1f9ca03732054104eefd4fadd1b8 , makes it so that you can add `use-ghcjs: true` to `stack.yaml`, or pass in `--use-ghcjs`.  When one of these is set, `--ghcjs` gets passed to invocations of `runhaskell Setup.hs configure` / `build`.

I'm currently blocked on having a locally booted GHCJS (running into https://github.com/ghcjs/ghcjs/issues/374).  Once we know how it fails, we can fix things until it works.

**Comment by mgsloan** [comment]
I've updated the 337-ghcjs branch.  It now works!  See [this comment](https://github.com/commercialhaskell/stack/issues/337#issuecomment-130148929) for some caveats / info about using it.  This issue will track the specifics of implementing building code with GHCJS.

One rather nice thing about this implementation is that it seems like stack can support GHCJS even when it is built with Cabal-18.* - see the trickiness [here](https://github.com/commercialhaskell/stack/commit/d49426976ae2a665904b6a20edfcd80adc26d58b#diff-9fe1770b08b2871a8d3e3e229168b13dR627 ).  I tried it out with a project containing a `js-sources` field and happily / oddly didn't get a parse error.

This isn't done yet.  Most of what remains is touched upon by a discussion of why we'd want ghcjs specific resolvers:

  - In order for the GHC version checking / setup code to work, we'll need a ghcjs version specified somewhere.  It would be weird to specify the version of GHC one way (resolver), and specify the version of GHCJS some other way.

  - The `use-ghcjs: true` and `--use-ghcjs` are kinda ugly.  `compiler: ghcjs` is a little bit better, but strange given that resolvers specify ghc versions.  We're going to want the resolver to specify the GHCJS version _and_ the GHC version it's based on.

  - Since stackage snapshots don't have versions which match the GHCJS boot packages, stack ends up trying to download and build these boot packages.  However, since it's pulling them from hackage, they aren't the special GHCJS versions, and so compilation fails.  To avoid this, I currently need to use `resolver: ghc-7.10`.

  - This makes it unnecessary to add any new path munging, of the variety I added [here](https://github.com/commercialhaskell/stack/commit/164d3ab1e7cf511d37657e620bfa207ad3e3b783#diff-f898a733193708fcc5ed529a3d5badceL748).  This particular munging is ugly because instead of having `install/.../7.10.2/pkgdb`, you've got `install/.../7.10.2-ghcjs/pkgdb`.  Yuck!  Looking into this, I just noticed that I'm not applying any munging to the dist paths.

I started writing this with the idea that it would be an open question for discussion.  However, now I've convinced myself it's the only sensible way forward.  I will add a `ghcjs-0.1` resolver, and support for ghcjs specific snapshots can come later.

**Comment by cies** [comment]
Great news. I think the "specific ghcjs resolver" approach is a good one. Could this at some point be lined up with the LTSes? For example we could then specify a resolver like `ghcjs-lts-3.2`.

**Comment by mgsloan** [comment]
PR opened: https://github.com/commercialhaskell/stack/pull/802

**Comment by snoyberg** [comment]
PR merged onto master, closing this. Great work @mgsloan!
