### ISSUE TITLE
`stack upgrade --git` fails if you are not a Stack contributor

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#751]
C:\Neil\hoogle>stack upgrade --git
    Cloning stack
    Cloning into 'stack'...
    Permission denied (publickey).
    fatal: Could not read from remote repository.

    Please make sure you have the correct access rights
    and the repository exists.
    Exit code ExitFailure 128 while running ["git","clone","git@github.com:commercia
    lhaskell/stack","stack","--depth","1"] in C:\Users\NDMIT_~1\AppData\Local\Temp\s
    tack-upgrade2784\

I suspect you should be cloning from https://github.com/commercialhaskell/stack.git which everyone can get to and is firewall friendly, rather than a contributor only git repo.

**Comment by snoyberg** [comment]
Already resolved in a8b48102213c1f0a60bb01d7ba387285bb474c15, you just need to upgrade first ;)

**Comment by ndmitchell** [comment]
Perhaps put a compiled release out shortly, so people can do `stack upgrade && stack upgrade --git`?

**Comment by snoyberg** [comment]
We're already working on one
