### ISSUE TITLE
Stack --version should say how many patches are included

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#752]
Currently I get:

    C:\Neil\hoogle>stack --version
    Version 0.1.2.0, Git revision 65246552936b7da4b64b38372feac903d96a8911

For version upgrades, it's hard to know which SHA1 is greater than another. I suggest number of patches in HEAD, e.g. `git rev-list HEAD --count`.

**Comment by snoyberg** [comment]
First step in this would be getting the appropriate code added to [gitrev](https://www.stackage.org/package/gitrev) (pinging @acfoltzer). Once the functionality is added there, using it here should be pretty trivial.

**Comment by acfoltzer** [comment]
Released [gitrev-1.1.0](http://hackage.haskell.org/package/gitrev-1.1.0); thanks for the idea!

**Comment by snoyberg** [comment]
Wow, that was fast, thanks!

**Comment by acfoltzer** [comment]
@snoyberg: open source happens fast when there are other things demanding procrastination :wink:
