### ISSUE TITLE
Stack --version should not change my code page

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#755]
C:\Neil>stack --version
    Setting codepage to UTF-8 (65001) to ensure correct output from GHC
    Version 0.1.2.7, Git revision cb68a39c5eb17e76c734bddd5dcdd13e27f126c5 (dirty)

Not sure --version should change my code page. Ideally version should just tell me the version.

**Comment by snoyberg** [comment]
This one is easy and doesn't break other things: I've just deferred the code page change until after argument parsing. The more general issue of #757 does remain.
