### ISSUE TITLE
Stack ghci should add in objects that get compiled

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#756]
The https://github.com/ndmitchell/hoogle project uses a .c extra-source-file, which means a standard `stack ghci` gives:

    [19 of 25] Compiling Output.Names     ( C:\Neil\hoogle\src\Output\Names.hs, inte
    rpreted )

    ByteCodeLink: can't find label
    During interactive linking, GHCi couldn't find the following symbol:
      text_search_bound
    This may be due to you not asking GHCi to load extra object files,
    archives or DLLs needed by your current session.  Restart GHCi, specifying
    the missing library using the -L/path/to/object/dir and -lmissinglibname
    flags, or simply by naming the relevant files on the GHCi command line.
    Alternatively, this link failure might indicate a bug in GHCi.
    If you suspect the latter, please send a bug report to:
      glasgow-haskell-bugs@haskell.org

I can workaround it with `stack ghci --ghc-options cbits\text_search.o`, but that doesn't recompile the C file for me when I need it to.

**Comment by ndmitchell** [comment]
Following #794, I think this is the only outstanding issue for me to switch from cabal to stack by default.

**Comment by chrisdone** [comment]
Bit of research on how this is supposed to work. I see that running a `stack build` (and thus Cabal build) produces:

```
bash-3.2$ find .stack-work/dist/x86_64-osx/ -name 'text_search.o'
.stack-work/dist/x86_64-osx//Cabal-1.22.4.0/build/cbits/text_search.o
.stack-work/dist/x86_64-osx//Cabal-1.22.4.0/build/hoogle/hoogle-tmp/cbits/text_search.o
```

The first line is from the library section that I added for testing, and the latter is for the executable. It's easy enough for the GHCi initialization code to inspect the `c-sources` field for each target and for each of those targets provide the corresponding `build/<path>` or `build/<targetname>/<targetname>-tmp/<path>` to call to `ghc --interactive`.

From testing `stack ghci --ghc-options="dist/build/hoogle/hoogle-tmp/cbits/text_search.o dist/build/cbits/text_search.o"` it seems that providing two object files with the same symbols isn't a problem. `cabal repl` doesn't shed much light, as it doesn't support loading multiple targets.

A `stack build && stack ghci` recompiles the `.c` file and would, if above was implemented, load the object file too. I'm surprised that `stack ghci` doesn't rebuild the `.c` file when it has changed. I think I'll consider that a bug and open a separate issue.

**Comment by chrisdone** [comment]
Okay, `stack ghci` doesn't run `stack build` anymore, it runs `stack build --only-dependencies`. It does that to avoid build failures of the current package from stopping ghci from running. I think instead we'd be better off running a full build and catching the build failure and ignoring it and continuing onwards.

**Comment by ndmitchell** [comment]
Any way to build only the C dependencies of a project? If so, that would let the `stack ghci` start up faster because it would have less to rebuild, yet still be correct.

**Comment by chrisdone** [comment]
I don't know if that's possible, I don't see anything in the manual.

**Comment by chrisdone** [comment]
@ndmitchell Okay, I noticed that the path was `hoogle-tmp` and not `hoogle/hoogle-tmp`. I fixed this and now it works with hoogle. I don't know what mistake I made while testing it but it works now. Want to try?

**Comment by ndmitchell** [comment]
@chrisdone Works perfectly! Thanks :)
