### ISSUE TITLE
stack ghci should allow multiple --ghc-options

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#758]
C:\Neil\hoogle>stack ghci --ghc-options cbits\text_search.o --ghc-options Main.hs
    Setting codepage to UTF-8 (65001) to ensure correct output from GHC
    Usage: stack ghci [TARGET] [--ghc-options OPTION] [--with-ghc GHC] [--no-load]
                      [--package ARG]
      Run ghci in the context of project(s)

Would be nice if I could pass two `--ghc-options` and they would be passed as different options to GHC.

**Comment by chrisdone** [comment]
You can pass `--ghc-options="foo bar mu"` like in cabal.

**Comment by chrisdone** [comment]
(Having a list of `--ghc-options` arguments and then concat'ing the list is also acceptable.)

**Comment by borsboom** [comment]
Related: #652

**Comment by afcowie** [comment]
This seems to not be working. Do you want a new issue, or commentary here?

```
stack build regex-tdfa-text --ghc-options=-XFlexibleContexts
```

doesn't pick up `FlexibleContexts`, build fails.

AfC

**Comment by snoyberg** [comment]
I'd definitely say a new issue. I don't actually see how that report is related to the original one, maybe I'm missing something.

**Comment by masaeedu** [comment]
@snoyberg On Windows, I'm getting:

```
$ stack ghci --ghc-options="-ddump-simpl -dsuppress-idinfo"
Configuring GHCi with the following packages:
GHCi, version 8.0.2: http://www.haskell.org/ghc/  :? for help
ghc.EXE: unrecognised flag: -ddump-simpl -dsuppress-idinfo

Usage: For basic information, try the `--help' option.
```

Using either option individually seems to work, and I'm just copy pasting these options, so I'm pretty sure there isn't anything wrong with the options themselves.

**Comment by mgsloan** [comment]
@masaeedu I've opened https://github.com/commercialhaskell/stack/issues/3315 and created a PR that should address that.
