### ISSUE TITLE
Programmaticly generate a man page

### ISSUE THREAD

**Issue by drwebb** [commercialhaskell/stack#761]
Now that many cli options parsers moved out of `main.hs` I'd like to use pandoc to construct the man page programtically. From my experiments before this is entirely possible, it's just a matter of writing a new executable that generates the output. If we have text that we want to be included in the manual it's also possible to include snippets from the README, or to have auxiliary texts in markdown form that will be included. 

Hopefully this may lead to organization of the code as it will be easier to generate the manual, as moving the options parsers did.

At the man page is too much work to update manually.Speaking from experience, writing Groff by hand is not something I would wish to subjugate anyone to. The man page can also suffer from being incomplete before every release.

**Comment by borsboom** [comment]
I'm thinking we should stop distributing the current man page until this is done.  I don't think anyone is maintaining it, and an out-of-date man page is worse than no man page.

**Comment by snoyberg** [comment]
:+1:. I was going to do :+100:, but there's no emoticon for that.

**Comment by drwebb** [comment]
I'm all in favor of dropping the man until this is finished! But it may be worth fixing this issue before the next release, as there are probably a lot of distribution scripts that are already sourcing the man. Currently, I last hand generated the man page for 0.1.2.0.

**Comment by borsboom** [comment]
What if we just have the man page link to the README until then?

**Comment by drwebb** [comment]
Currently my pandoc experiment does take in the README and spits out
groff man page, so the man page could be the README with with little
fuss. If we were inclined we could also go the other way once the
options parsing portion comes online, and produce markdown documentation
of the command line parameters. You know for people not stuck in the
80s. :)

**Comment by borsboom** [comment]
I've adjusted the RPM/DEB generation to leave out the man page for now.  When the man page is being generated, revert 2b46df3c4e697d6d9325ac367090176a654a59c2 to add the man page back again.

**Comment by phadej** [comment]
@snoyberg there is :100: :+1:
I'm not sure if it could be possible to annotate `optparse-applicative` flags/options with more prose, and generate options documentation from that. It would be cool to switch from `stack cmd --help` to `stack cmd --man` which would open man page with description of that command (I have no idea how git folks maintain theirs).

**Comment by snoyberg** [comment]
I'm going to close this; I haven't heard a lot of demand for man pages, and the work involved is non-trivial.
