### ISSUE TITLE
Question: ghc options in stack.yaml

### ISSUE THREAD

**Issue by rpglover64** [commercialhaskell/stack#762]
Is there a way to specify package-specific ghc options in stack.yaml?

**Comment by snoyberg** [comment]
No, though I'm probably going to be adding a way to add GHC options for _all_ packages. Is there a reason adding these options in the .cabal file doesn't work for you?

**Comment by rpglover64** [comment]
No reason it doesn't work; I just think of some options (specifically `-fdefer-typed-holes`) as properties of the build rather than of the package.

**Comment by snoyberg** [comment]
I typically put something like that on the command line.

**Comment by rpglover64** [comment]
I do too, but that led to other dependencies being recompiled; not intolerable, but annoying.

**Comment by snoyberg** [comment]
Forgot to update this issue too: I implemented this as part of #796. It's on master now, let me know if there are any problems.
