### ISSUE TITLE
failure on 0.1.3 upgrade: executable that is Buildable: False

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#763]
Our CI server automatically upgrades to new releases and this happened:

```
NOTE: the test command is functionally equivalent to 'build --test'
Progress: 0/11                                          frontrow-entities-0.0.1.1: configure
Progress: 0/11                                          frontrow-entities-0.0.1.1: build
Progress: 0/11                                          P
--  While building package frontrow-entities-0.0.1.1 using:
      /opt/ghc/7.8.4/bin/runhaskell -package=Cabal-1.18.1.5 -clear-package-db -global-package-db -package-db=/home/ubuntu/.stack/snapshots/x86_64-linux/lts-2.3/7.8.4/pkgdb/ /tmp/stack14295/Setup.hs --builddir=.stack-work/dist/x86_64-linux/Cabal-1.18.1.5/ build exe:entities --ghc-options -hpcdir .stack-work/dist/x86_64-linux/Cabal-1.18.1.5/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/ubuntu/backend/.stack-work/logs/frontrow-entities-0.0.1.1.log

    Configuring frontrow-entities-0.0.1.1...
    Setup.hs: Cannot build the executable 'entities' because the component is
    marked as disabled in the .cabal file.

 stack test returned exit code 1
```

cabal file in question has this

```
executable    entities
  if flag(executable-too)
    Buildable: True
  else
    Buildable: False
```

This is a multi-cabal file project, and it works if I build just the individual cabal file.

fails: `stack test`
passes: `stack test frontrow-entities`

**Comment by gregwebs** [comment]
I did run `stack clean` before hand.

**Comment by snoyberg** [comment]
Mea culpa, this was a bad mistake on my part, and needs to a hotfix released. Pinging @borsboom.

@gregwebs Can you test the 763-disabled-executable branch and confirm that it fixes things for you?

@borsboom That branch is a single commit on top of the 0.1.3.0 release tag, so should be easy to make a release for. Sorry for creating extra work for you here :(

**Comment by adinapoli** [comment]
I was hit by the very same issue during this morning upgrade - great to see Greg so quickly reporting it and Micheal so swiftly addressing the problem. Thank you guys!

**Comment by snoyberg** [comment]
@adinapoli Can you confirm that my branch fixes your problem? Confirmation will help us get the official release out faster.

**Comment by adinapoli** [comment]
@snoyberg Building your branch as we speak!

**Comment by snoyberg** [comment]
:)

**Comment by adinapoli** [comment]
Sorry, I had some cabal hell despite I was installing in a sandbox - it was trying to install a very old version of `mono-traversable` and `vector-instances`. I eventually got  around it by using `--allow-newer` in my `cabal install` command.

I'm happy to report your patch did indeed the trick, and now my package builds successfully till the end. :tada:

**Comment by snoyberg** [comment]
Thanks!

I've been hit by that mono-traversable thing as well, I have no idea what cabal solver bug is triggering it unfortunately. I always just build stack with stack though, so I don't hit these problems often (the time I hit it was an old .travis.yml on a different project).

**Comment by adinapoli** [comment]
Glad it was not just me then! Hopefully this thread will be helpful to some other guy scratching his head on that.

**Comment by gregwebs** [comment]
Thanks for the quick fix! Can you push the tag for the new version?

**Comment by borsboom** [comment]
Just waiting on a few more binaries to finish their builds and integration tests, then I'll publish the Github release (which will create the tag).

**Comment by borsboom** [comment]
Tag is pushed, and package uploaded to hackage.  RPM/DEB packages being built and uploaded, will appear on the APT/YUM repos over the next hour or so.

**Comment by gregwebs** [comment]
thanks!
