### ISSUE TITLE
Listing redundant constraints on stack init

### ISSUE THREAD

**Issue by gibiansky** [commercialhaskell/stack#765]
This may be a duplicate or too minor, but figured I would report it.

`stack` does not clean up the dependency info when there are multiple executables present, leading to a redundant/confusing error message.

**Reproduce:** 
I downloaded [`brick`](https://github.com/jtdaugherty/brick) and ran `stack init` in the `brick` directory.

**Result:**

```
    vty not found
    - brick requires >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1 && >=5.3.1
```

**Expected:** 
Only listing `>= 5.3.1` once:

```
    vty not found
    - brick requires >=5.3.1
```

This is likely because the `vty >=5.3.1` constraint exists in multiple executables in the `brick.cabal` file.

**Comment by snoyberg** [comment]
I believe this is already resolved on master, can you check?

**Comment by gibiansky** [comment]
Ah, sorry. I will check and re-open if it's still an issue.
