### ISSUE TITLE
--only-dependencies vs --dependencies-only

### ISSUE THREAD

**Issue by alanz** [commercialhaskell/stack#767]
stack uses the flag `--only-dependencies`, cabal-install uses `--dependencies-only`.

Is there a reason for the difference? My fingers get confused.

**Comment by snoyberg** [comment]
I actually didn't know `dependencies-only` existed. In fact, both versions exist in cabal:

```
    --only-dependencies             Install only the dependencies necessary to
    --dependencies-only             A synonym for --only-dependencies
```

I don't mind having the same synonym setup in stack. It's a trivial one-line change. I can make it, but thought perhaps you (or someone else reading) may want to play with the option parsing code themselves.

**Comment by snoyberg** [comment]
Implemented

**Comment by alanz** [comment]
Thanks. It will ease the pain of cabal-install refugees
