### ISSUE TITLE
stack upgrade issue

### ISSUE THREAD

**Issue by eccstartup** [commercialhaskell/stack#776]
It starts from this [post](https://www.reddit.com/r/haskell/comments/3go8up/ann_stack0130/cu12hx9).

I try to reproduce the error. And it turns out that `stack --install-ghc upgrade` works. [Here](https://gist.github.com/eccstartup/1f918ef80e16e6081df6) is a gist of the whole process. Due to network failure(too many downloads), the process interrupts a few times, but succeeds at last. 

The resolver in `stack.yaml` is ghc-7.10, because I use ghcformacosx. 

I also want to add a comment. The `~/.stack/global/stack.yaml` seems to be the only file a user can configure his/her environment. But it does not often work as expected. Besides, we have a local hackage site, but we don't know how to use it.

**Comment by snoyberg** [comment]
Error message updated, thanks! And yes, upgrading from source can take a long time. The binary packages are usually the best approach.
