### ISSUE TITLE
"unlisted" modules are actually listed for different components

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#779]
Not sure this is a bug or a feature. 

    Warning: modules not listed in Snowdrift.cabal for 'SnowdriftEmailDaemon' component (add to other-modules):
        Foundation
        Import
        ...

Those modules are (obviously) listed for the 'lib:Snowdrift' component.

**Comment by chreekat** [comment]
The duplication is [significant](https://github.com/snowdriftcoop/snowdrift/commit/732d71f5f22e83d59c59e44392ed8b1f3ad17d27).

Now, I already sort of wish SnowdriftEmailDaemon was a separate *package* rather than component, but I think that's orthogonal.

**Comment by chrisdone** [comment]
I think the problem is your library and executable share the same source directory, so your executable loads the source directly from your library. Instead, you can pop your executable's source in `app/` or whatnot and depend on your `Snowdrift` library. This will also save unnecessary recompilation.

**Comment by chreekat** [comment]
I guess my question is, *should* I be listing the modules twice, anyway? If so, bully for stack.

**Comment by chrisdone** [comment]
You should normally list the modules you use in the Cabal file, yes. But in this case, it doesn't seem like you have to use them directly.

**Comment by chreekat** [comment]
Ah! That's surprising that moving the source file to a different directory ('.' -> './app') makes a difference, but it also solves the problem. Thanks.
