### ISSUE TITLE
Killing 'stack build' (<c-c>) at the wrong time seems to upset the terminal/tmux

### ISSUE THREAD

**Issue by chreekat** [commercialhaskell/stack#780]
vim gets *terribly* confused and must be quit blindly. This is true whether vim is suspended while 'stack build' runs in the foreground, or if makeprogram=stack\ build and I run :make.

Further, flow control gets permanently enabled; no amount of 'stty -ixoff' makes it go away again. I have to exit the shell/close the tmux buffer, and pull out a fresh one.

This has happened twice since yesterday, though I don't know how to reproduce it yet.

**Comment by chreekat** [comment]
The flow control thing may(?) have been because I tried 'reset' among other things. Something I just reproduced was the following:

* vim View/Project.hs
* set mk=stack\ build
* :w
* :mak
* ^c at "Preprocessing library Snowdrift-0.1.4..."
* vim is broken

However, I've also found I can fix vim! t(probably)mtowtdi, but :ls<enter><enter><c-l> is sufficient.

**Comment by borsboom** [comment]
I have not been able to reproduce this in Vim for Linux or OS X (using stack master).  Can you confirm that you still see this behaviour in the current master?  If so, which platform and Vim version are you using?

**Comment by chreekat** [comment]
Hasn't happened in a while. I'll reopen if I ever see it again.
