### ISSUE TITLE
local templates

### ISSUE THREAD

**Issue by legrostdg** [commercialhaskell/stack#783]
It would be cool if "stack new" and "stack templates" could use local template files, instead of getting templates from https://github.com/commercialhaskell/stack-templates.git only.

**Comment by tfausak** [comment]
:+1: I would like this, too! 

In fact, I would like to be able to specify a remote template. I am able to do that with [hi](https://github.com/fujimura/hi), which I would consider `stack new`'s closest competitor.

**Comment by lukexi** [comment]
Agreed! Allowing a list of repo URLs to be entered in the global stack.yaml (defaulting to commercialhaskell's to start with) would be particularly great as devs could then offer template repos to go with their packages.

**Comment by AaronFriel** [comment]
Also agreed, I'd prefer if Stack cached templates that were available a la `apt-get update` versus `apt-get install`.

I write this not coincidentally because my local VM for development isn't on the network right now, and `stack new` is broken without network access.

**Comment by aleator** [comment]
:+1:  Also, optionally giving templates as URLs would also be great!

**Comment by GregorySchwartz** [comment]
I'll take a stab at this, the local templates.

**Comment by snoyberg** [comment]
Closing in favor of PR #1095.
