### ISSUE TITLE
Coverage report not picking any tests with ghc-7.10 resolver

### ISSUE THREAD

**Issue by jdnavarro** [commercialhaskell/stack#785]
The tests run properly, but none are shown in the coverage report. This only happens with the ghc-7.10 resolver. The coverage is coming fine when using lts-2.22 resolver or when using a `cabal-install` sandbox with ghc-7.10.1.

I can provide more detailed information to reproduce the bug, but wanted to confirm this doesn't sound like a known problem.

**Comment by mgsloan** [comment]
Hi!  Sorry for not getting back to this sooner.  That doesn't sound like a known problem to me.  Do you still have the details about how to reproduce the bug?

**Comment by mgsloan** [comment]
Also, this might be relevant: https://github.com/commercialhaskell/stack/issues/1009

**Comment by jdnavarro** [comment]
Yes, it's exactly the same error as in #1009. Here it's a way to reproduce it:

```
$ git clone https://github.com/plutonbrb/nero
$ cd nero
$ stack --stack-yaml=stack-7.8.yaml test --coverage nero:tasty
```
That works as expected.

But the following gives 100% coverage with 0 tests run:
```
$ stack --stack-yaml=stack-7.10.yaml test --coverage nero:tasty
```

My stack binary is coming from Arch Linux AUR, this is what `stack --version` prints:

`Version 0.1.4.0, Git revision 165db5bd77cc88745e0ec8e143275575e5a75d93 (1723 commits) X86_64`

I was about to try with `HEAD` but I'm getting some `libtinfo` missing dependency issue after the recent Arch Linux GHC upgrade. I'll let you know when I get around fixing it.

**Comment by jdnavarro** [comment]
I can confirm this also happens with `stack-HEAD` as of 4e58783f5999e86027a1ab12ef9707d9573ea3ce.

**Comment by mgsloan** [comment]
Thanks for the repro, it works for me.  Very strange!

**Comment by jdnavarro** [comment]
@mgsloan what OS are you on? :confused:

**Comment by mgsloan** [comment]
Ubuntu Tasty.  The repro **does** work.  The very strange thing is the bug.

The verbose logs don't show the two builds doing anything very different, and both of the runs generate .tix files.  This means the behavior of the `hpc` program must have changed in 7.10

**Comment by jdnavarro** [comment]
If I remember correctly with `cabal-install` the coverage was working with 7.10.

**Comment by mgsloan** [comment]
Ah, looks like the problem has something to do with the hashed package identifier stuff, I'm ending up with folders like `nero_9bTCpMF7G4UFWJJvtDrIdB` in the hpc directory, whereas on 7.8 I'd get `nero-0.3.1`

**Comment by jdnavarro** [comment]
Is this related? https://github.com/ttuegel/cabal/commit/1bda4281723542ff97096ee3d774ae8d9c0df111

**Comment by mgsloan** [comment]
Yup, that's related!  The fix was more involved than I'd hoped (parsing `ghc-pkg describe` results for the package key), but it works!

Please close the issue if it works for you.  Thanks for reporting it!

**Comment by jdnavarro** [comment]
Works now for me. Thank *you*!

**Comment by mgsloan** [comment]
@jdnavarro Turns out my implementation approach was flawed.  Asking ghc-pkg for the package key only works if the package version you're testing is the exact one that's installed..  I've just pushed a commit that instead parses the key out of package.conf.inplace.

**Comment by jdnavarro** [comment]
I didn't notice the flaw, but may have created some confusion in the future. Thanks for fixing it.

**Comment by mgsloan** [comment]
Welcome!  I'm actually back on the case, as the fix caused issues: https://github.com/commercialhaskell/stack/issues/1162
