### ISSUE TITLE
parsing of docker --version fails on CircleCI

### ISSUE THREAD

**Issue by Fuuzetsu** [commercialhaskell/stack#786]
On CircleCI, `docker --version` looks like

```
docker --version

Docker version 1.6.2-circleci, build 2f3236d 
```

which `parseVersionFromString` can't deal with.

**Comment by Fuuzetsu** [comment]
slightly incorrect: we're giving `parseVersionFromString` something it can't deal with; either way I'll send a PR soon

**Comment by borsboom** [comment]
Thanks.
