### ISSUE TITLE
stack should build without warnings

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#791]
When I do `stack upgrade --git` it builds all the dependent libraries without showing their build output (fine), but for stack it displays every warning. Given that, having zero warnings would probably be a good idea. For note, I always compile all my packages on Travis with `-Werror`, and I would encourage you to do the same - it gives a better feeling if the compiler doesn't complain while upgrading. Examples of warnings:

    src\Stack\Build\Target.hs:30:1: Warning:
        The import of `Data.Monoid' is redundant
          except perhaps to import instances from `Data.Monoid'
        To import instances alone, use: import Data.Monoid()

    src\Stack\Build\Target.hs:57:60: Warning:
        Unticked promoted constructor: `HasIdents'.
        Use 'HasIdents instead of `HasIdents'.

    src\Stack\Docker.hs:21:1: Warning:
        The import of `Control.Applicative' is redundant
          except perhaps to import instances from `Control.Applicative'
        To import instances alone, use: import Control.Applicative()

**Comment by borsboom** [comment]
Generally speaking we do the same, but in this case we *just* upgraded to GHC 7.10/LTS 3.0 and haven't cleaned up the warnings yet (we need to take extra care so that we don't break compatibility with GHC 7.8).  I'm going to close this since, as a matter of course, we will be fixing the warnings.

**Comment by borsboom** [comment]
Actually I changed my mind and am re-opening this just to make sure it's taken care of.

**Comment by mgsloan** [comment]
I'm not sure what the best way to fix this is without littering the code with error prone CPP.  My suggestion would be to put the affected imports in a `Stack.Import` module.  This doesn't need to grow into one of those giant `Import` modules, and could instead just be around for avoiding these warnings.

**Comment by borsboom** [comment]
All the warnings should be fixed, and only needed CPP in one place.

**Comment by ndmitchell** [comment]
The standard trick is to add an import of Prelude at the end of the list then the warnings about Applicative/Monoid go away without CPP. I build with no warnings from 7.2 to 7.10 with no CPP.

**Comment by cies** [comment]
@ndmitchell Came here to learn that trick. Worked like a charm!
