### ISSUE TITLE
Include last Git commit date in --version output WAS Stack version says the wrong number of commits

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#792]
Stack version after a `stack upgrade --git` says:

    Version 0.1.3.1, Git revision c7f14a6adfda2ee3a0b9da35d72044e0ad99dc7b (1 commits)

I do not believe that Stack contains only one commit.

**Comment by borsboom** [comment]
I'll bet it's because `stack upgrade --git` uses `git clone --depth 1`.  Probably want to keep doing that to avoid download unnecessary history, so I wonder if in this case it would make more sense to just leave out the number of commits.

**Comment by ndmitchell** [comment]
Is there no way to get the number of commits even so?

**Comment by borsboom** [comment]
Hmm, possibly using the [Github API](https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository), but there doesn't seem to be a way to just get the count and that's not going to integrate nicely with gitrev, so I don't really like that idea.

**Comment by borsboom** [comment]
I'm going to have it leave out the number of commits in this case, and if anyone wants to make a PR to improve I'll be happy to merge it.

**Comment by ndmitchell** [comment]
Seems reasonable - I certainly won't be providing such a PR. I couldn't figure out any way of getting it from git, but just in case, I asked on StackOverflow: http://stackoverflow.com/questions/32069186/find-the-number-of-commits-in-a-git-repo-when-cloning-with-depth-1

**Comment by ndmitchell** [comment]
In fact, thinking sideways, if `stack upgrade --git` contained the date of the most recent commit, or the date at which it compiled, that would provide most of the useful information. I really just want to check that my `stack upgrade --git` really did change the binary, and is progressing forward on some metric.

**Comment by borsboom** [comment]
I like that idea.  It'll need another feature added to [gitrev](https://www.stackage.org/package/gitrev) (pinging @acfoltzer, again!).

**Comment by mgsloan** [comment]
This is blocked on an update of [gitrev](https://github.com/acfoltzer/gitrev).  Pinging @acfoltzer

**Comment by mgsloan** [comment]
Unblocked and added as an extra-dep!
