### ISSUE TITLE
stack ghci puts the wrong module open

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#794]
Taking the Hoogle repo, running `stack ghci --ghc-options cbits\text_search.o` opens GHCi with:

    [26 of 26] Compiling Main             ( C:\Neil\hoogle\src\Main.hs, interpreted )
    Ok, modules loaded: Action.CmdLine, Paths_hoogle, Action.Generate, Output.Items, Output.Tags, Output.Names, Output.Types, Input.Cabal, Input.Haddock, Input.Download, Input.Reorder, Input.Set, Input.Item, General.Util, General.Store, General.Str, General.Conduit, Action.Search, Query, Action.Server, General.Web, General.Template, General.Log, Action.Test, General.IString, Main.
    *Action.CmdLine>

Specifically, the Main module is loaded (as it should be), but Action.CmdLine is the one in scope (which is wrong). As a result, I can't run `main`.

**Comment by WarDaft** [comment]
Ran into a similar problem with a toy project. It insists on only loading the CSS module. Only thing I've found so far that affects it is deleting the `main-is:` field from the `.cabal` file and setting up a `.ghci` file to load Main, which isn't exactly great. Otherwise, it will actually re-load the (same every time) *wrong* module after the `.ghci` file loads the right one.

**Comment by chrisdone** [comment]
Stack doesn't specify any one module to be in scope, it just gives the list to GHCi and this just seems to be what GHCi arbitrarily chooses. You can run main by `import Main` or `Main.main`. I don't yet know how to tell GHCi which module to put in the context.

**Comment by chrisdone** [comment]
As a workaround we could send:

```
:m +Foo +Bar +Etc +Main
```

to the subprocess.

**Comment by ndmitchell** [comment]
In my tests, `ghci` always puts the first module on the list in scope. e.g. `ghci A B C` puts `A` in scope, while `ghci C A B` puts `C` in scope. All tests with 7.10.2.

**Comment by chrisdone** [comment]
In that case popping the Main one first in the list is a one liner.

**Comment by chrisdone** [comment]
Pushed that change. @ndmitchell Confirm?

**Comment by ndmitchell** [comment]
Confirmed. Thanks a lot!
