### ISSUE TITLE
GHC options are not passed to GHC when using --ghc-options

### ISSUE THREAD

**Issue by rkarp** [commercialhaskell/stack#796]
When calling for example `stack build regex-tdfa-text --ghc-options -XFlexibleContexts` (a workaround for a bug in that package) the option --ghc-options has no effect and the build fails.

It's the same problem as in [this thread](https://groups.google.com/forum/#!topic/haskell-stack/i9i0fIoHUos)

I've looked at the sources and the reason is [this line](https://github.com/commercialhaskell/stack/blob/7323459c1abbd6155cf6d79a51a5fa2bd847b8da/src/Stack/Types/Build.hs#L568). If I change it to `if True` and rebuild Stack, the GHC Options are passed correctly.

There's obviously a reason why this check is there, but it doesn't work properly.

**Comment by snoyberg** [comment]
This discussion explains a lot of the reasoning around which flags are applied where: https://github.com/commercialhaskell/stack/wiki/FAQ#stack-sometimes-rebuilds-based-on-flag-changes-when-i-wouldnt-expect-it-to-how-come

In order to work around that bug in regex-tdfa-text, you'll likely need to check out the package locally, or possibly via the Git packages feature. Adding ghc-options to stack.yaml (something we've been discussing) may help you get a reliable build out of this situation.

**Comment by rkarp** [comment]
Alright, I've read the discussion [here](https://github.com/commercialhaskell/stack/issues/382). I'm not sure I understand the definition of "wanted". Shouldn't `regex-tdfa-text` be a wanted dependency in my case?

I actually wanted to build Leksah with Stack, but I cannot do that in a straightforward way due to the `regex-tdfa-text` package. Problems like this are going to happen again and providing per-package GHC options in stack.yaml would provide an easy solution.

**Comment by snoyberg** [comment]
I've just added this to master and documented it in:

https://github.com/commercialhaskell/stack/wiki/stack.yaml#ghc-options

Can you try this out and confirm that it works for you?

**Comment by rkarp** [comment]
Thanks, setting ghc-options in the stack.yaml works.

`--ghc-options` still has no effect when building the regex package alone, though. I think how this works exactly needs to be documented somehow and the user should be informed. As a user you'd expect the options to apply at the very least to the packages you've specified to be built.

**Comment by snoyberg** [comment]
Please see the wiki page, where I've added an explanation. If you have ideas on how to improve the docs on this, please do! Community contributions on this are very welcome.
