### ISSUE TITLE
No proxy support in stack 1.3.1 (Regression over stack 1.???)

### ISSUE THREAD

**Issue by habbler** [commercialhaskell/stack#804]
If in stack modules Network.HTTP.Download and Network.HTTP.Download.Verified
I change all instances of 
withResponse  req
to
 withResponse ((addProxy "proxy" 8080) req)

stack works through our proxy.

In an earlier version I don't think I needed to do this.

It would be good if environment variable http_proxy was respected.

(This is under windows 7.0)

**Comment by snoyberg** [comment]
The variable the will be used most of the time is https_proxy. Is that one set? Also, how did you get the new stack? Are you using the official binary, and if so, which architecture?

**Comment by habbler** [comment]
HTTPS_PROXY is set to "https:/proxy:8080"
This is not the official binary due to 

https://github.com/vincenthz/hs-certificate/issues/45#issuecomment-108982126

but one I build myself.

cabal configure -v2
"C:\Downloads\tools\ghc\ghc-7.8.4\bin\ghc.exe" "--numeric-version"
looking for tool ghc-pkg near compiler in C:\Downloads\tools\ghc\ghc-7.8.4\bin
found ghc-pkg in C:\Downloads\tools\ghc\ghc-7.8.4\bin\ghc-pkg.exe
"C:\Downloads\tools\ghc\ghc-7.8.4\bin\ghc-pkg.exe" "--version"
"C:\Downloads\tools\ghc\ghc-7.8.4\bin\ghc.exe" "--supported-languages"
"C:\Downloads\tools\ghc\ghc-7.8.4\bin\ghc.exe" "--info"
Reading available packages...
Choosing modular solver.
Resolving dependencies...
Configuring stack-0.1.3.1...
Flags chosen: integration-tests=False
Dependency Cabal ==1.22.3.0: using Cabal-1.22.3.0
Dependency Win32 ==2.3.0.2: using Win32-2.3.0.2
Dependency aeson ==0.9.0.1: using aeson-0.9.0.1
Dependency async ==2.0.2: using async-2.0.2
Dependency attoparsec ==0.13.0.0: using attoparsec-0.13.0.0
Dependency base ==4.7.0.2: using base-4.7.0.2
Dependency base16-bytestring ==0.1.1.6: using base16-bytestring-0.1.1.6
Dependency base64-bytestring ==1.0.0.1: using base64-bytestring-1.0.0.1
Dependency bifunctors ==5: using bifunctors-5
Dependency binary ==0.7.1.0: using binary-0.7.1.0
Dependency blaze-builder ==0.4.0.1: using blaze-builder-0.4.0.1
Dependency byteable ==0.1.1: using byteable-0.1.1
Dependency bytestring ==0.10.4.0: using bytestring-0.10.4.0
Dependency conduit ==1.2.4.2: using conduit-1.2.4.2
Dependency conduit-combinators ==1.0.1: using conduit-combinators-1.0.1
Dependency conduit-extra ==1.1.9: using conduit-extra-1.1.9
Dependency containers ==0.5.5.1: using containers-0.5.5.1
Dependency cryptohash ==0.11.6: using cryptohash-0.11.6
Dependency cryptohash-conduit ==0.1.1: using cryptohash-conduit-0.1.1
Dependency deepseq ==1.3.0.2: using deepseq-1.3.0.2
Dependency deepseq-generics ==0.1.1.2: using deepseq-generics-0.1.1.2
Dependency directory ==1.2.1.0: using directory-1.2.1.0
Dependency either ==4.4.1: using either-4.4.1
Dependency enclosed-exceptions ==1.0.1.1: using enclosed-exceptions-1.0.1.1
Dependency exceptions ==0.8.0.2: using exceptions-0.8.0.2
Dependency extra ==1.4.1: using extra-1.4.1
Dependency fast-logger ==2.3.1: using fast-logger-2.3.1
Dependency file-embed ==0.0.8.2: using file-embed-0.0.8.2
Dependency filelock ==0.1.0.1: using filelock-0.1.0.1
Dependency filepath ==1.3.0.2: using filepath-1.3.0.2
Dependency fsnotify ==0.1.0.3: using fsnotify-0.1.0.3
Dependency hashable ==1.2.3.2: using hashable-1.2.3.2
Dependency hastache ==0.6.1: using hastache-0.6.1
Dependency http-client ==0.4.15: using http-client-0.4.15
Dependency http-client-tls ==0.2.2: using http-client-tls-0.2.2
Dependency http-conduit ==2.1.5.1: using http-conduit-2.1.5.1
Dependency http-types ==0.8.6: using http-types-0.8.6
Dependency lifted-base ==0.2.3.6: using lifted-base-0.2.3.6
Dependency monad-control ==1.0.0.4: using monad-control-1.0.0.4
Dependency monad-logger ==0.3.13.1: using monad-logger-0.3.13.1
Dependency monad-loops ==0.4.3: using monad-loops-0.4.3
Dependency mtl ==2.2.1: using mtl-2.2.1
Dependency old-locale ==1.0.0.6: using old-locale-1.0.0.6
Dependency optparse-applicative ==0.11.0.2: using
optparse-applicative-0.11.0.2
Dependency optparse-simple ==0.0.3: using optparse-simple-0.0.3
Dependency path ==0.5.2: using path-0.5.2
Dependency persistent ==2.2: using persistent-2.2
Dependency persistent-sqlite ==2.2: using persistent-sqlite-2.2
Dependency persistent-template ==2.1.3.4: using persistent-template-2.1.3.4
Dependency pretty ==1.1.1.1: using pretty-1.1.1.1
Dependency process ==1.2.0.0: using process-1.2.0.0
Dependency project-template ==0.2.0: using project-template-0.2.0
Dependency resourcet ==1.1.5: using resourcet-1.1.5
Dependency retry ==0.6: using retry-0.6
Dependency safe ==0.3.9: using safe-0.3.9
Dependency split ==0.2.2: using split-0.2.2
Dependency stack -any: using stack-0.1.3.1
Dependency stm ==2.4.4: using stm-2.4.4
Dependency streaming-commons ==0.1.12.1: using streaming-commons-0.1.12.1
Dependency tar ==0.4.1.0: using tar-0.4.1.0
Dependency template-haskell ==2.9.0.0: using template-haskell-2.9.0.0
Dependency temporary ==1.2.0.3: using temporary-1.2.0.3
Dependency text ==1.2.1.1: using text-1.2.1.1
Dependency time ==1.4.2: using time-1.4.2
Dependency transformers ==0.4.3.0: using transformers-0.4.3.0
Dependency transformers-base ==0.4.4: using transformers-base-0.4.4
Dependency unix-compat ==0.4.1.4: using unix-compat-0.4.1.4
Dependency unordered-containers ==0.2.5.1: using unordered-containers-0.2.5.1
Dependency vector ==0.10.12.3: using vector-0.10.12.3
Dependency vector-binary-instances ==0.2.1.0: using
vector-binary-instances-0.2.1.0
Dependency void ==0.7: using void-0.7
Dependency word8 ==0.1.2: using word8-0.1.2
Dependency yaml ==0.8.11: using yaml-0.8.11
Dependency zlib ==0.5.4.2: using zlib-0.5.4.2
Using Cabal-1.22.3.0 compiled by ghc-7.8
Using compiler: ghc-7.8.4

**Comment by habbler** [comment]
Accidently closed the issue

**Comment by snoyberg** [comment]
Please recompile with a more recent http-client (preferably the newest, 0.4.19), 0.4.17 added changes for proxy variables on Windows. See the changelog at:

http://www.stackage.org/package/http-client

**Comment by habbler** [comment]
Could confirm this. Removing HTTPS_PROXY in the system settings and adding
set https_proxy=proxy:8080
fixes the problem.
Having troubles rebuilding at the moment so could not confirm is using http-client also fixes the problem.
