### ISSUE TITLE
stack exec --help is invalid

### ISSUE THREAD

**Issue by Fuuzetsu** [commercialhaskell/stack#806]
```
Invalid option `--help'

Usage: stack exec CMD [-- ARGS (e.g. stack ghc -- X.hs -o x)] ([--plain] |
                  ([--ghc-package-path] | [--no-ghc-package-path])
                  ([--stack-exe] | [--no-stack-exe]) [--package ARG])
  Execute a command
```

**Comment by borsboom** [comment]
Would you mind being more specific about what is incorrect?  I do see the `(e.g. stack ghc -- X.hs -o x)` is more relevant for another command, is there anything else?

**Comment by chrisdone** [comment]
I think he means the fact that `--help` says "invalid option --help". I don't know why optparse-applicative does this.

**Comment by Fuuzetsu** [comment]
Yes, what Chris said.

**Comment by chrisdone** [comment]
I found while writing `stack new` that I can add a `--help` option manually, as [here](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Options.hs#L633..L633), but it seems like this shouldn't be necessary. We could, at least, add this to `addCommand` automatically. Although it feels like optparse should probably have some non-manual way of enabling this.

**Comment by borsboom** [comment]
That's very strange, other subcommands seem to have working `--help` without adding it manually.  And optparse-simple's `addCommand` uses `simpleParser`, which [adds a `--help` option](https://github.com/fpco/optparse-simple/blob/32c6f2693494ee08a7b0751e3b206522ebd3db9a/src/Options/Applicative/Simple.hs#L168) just like the one you add manually for `stack new`.  Probably chalk this down to another bizarre argument-order/subcommand-related behaviour in optparse-applicative.

**Comment by snoyberg** [comment]
This is definitely buggy behavior, I was bitten by this a bit ago and got curious. I'm preparing a PR with an ugly hack that solves it, though the usability downside makes me nervous about just committing to master.

**Comment by snoyberg** [comment]
See PR #903
