### ISSUE TITLE
Version tagging breaks dependency resolution

### ISSUE THREAD

**Issue by TomMD** [commercialhaskell/stack#808]
If `A` depends on `B >= 0.2` and we have available `B 0.2-dev, B 0.1` then the resolution will fail.  It seems these sorts of tags should be handled gracefully, perhaps with a warning. 

For example, package A has in its cabal  `B >= 0.2.3`.  Package B has a version of `0.2.4-dev`.  This produces:

```
--  Failure when adding dependencies:    
      B: needed (>=0.2.3), but 0.2.1 found
    needed for package: A-0.14
```

**Comment by borsboom** [comment]
I was under the impression that version tags are [broken in Cabal anyway](https://github.com/haskell/cabal/issues/890) and not planned to be fixed.  Should we support them at all?

**Comment by TomMD** [comment]
Sorry for the false alarm, I had a few other incorrect deps that cause this specific issue in my case - sort of an odd storm of dependency inference - things are working even with `-dev`.  I'll close, but if tags are indeed broken that is good to know.
