### ISSUE TITLE
Subcommands should show help with no args

### ISSUE THREAD

**Issue by chrisdone** [commercialhaskell/stack#809]
This subcommand currently isn't too helpful:

```
chris@retina:~/Work/stack$ stack ide
Usage: stack ide [--help] COMMAND
  IDE-specific commands
```

Running `stack` by itself produces `stack --help`, but seems that subcommands still have this issue.

**Comment by HuwCampbell** [comment]
Can now use `showHelpOnEmpty`.

**Comment by mpilgrem** [comment]
I will propose a pull request that I think fixes this.
