### ISSUE TITLE
Need more codepage hacks on stack upgrade

### ISSUE THREAD

**Issue by ndmitchell** [commercialhaskell/stack#812]
$ stack upgrade --git
    ...
    [17 of 68] Compiling Network.HTTP.Download ( src\Network\HTTP\Download.hs, .stack-work\dist\i386-windows\Cabal-1.22.4.0\build\Network\HTTP\Download.o )
    .stack-work\dist\i386-windows\Cabal-1.22.4.0\build\src/Network\HTTP\Download.dump-hi: commitBuffer: invalid argument (invalid character)

    --  While building package stack-0.1.3.1 using:
          C:\\ghc\\minghc-7.10.2-i386\\ghc-7.10.2\\bin\\runhaskell.exe -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=C:\Users\ndmit_000\AppData\Roaming\stack\snapshots\i386-windows\lts-3.0\7.10.2\pkgdb\ C:\Users\NDMIT_~1\AppData\Local\Temp\stack6972\Setup.hs --builddir=.stack-work\dist\i386-windows\Cabal-1.22.4.0\ build exe:stack --ghc-options -hpcdir .stack-work\dist\i386-windows\Cabal-1.22.4.0\hpc\.hpc\ -ddump-hi -ddump-to-file
        Process exited with code: ExitFailure 1

After I ran `chcp 65001` by hand and it worked. Confirmed it still fails with a fresh version. Ping @snoyberg.

**Comment by snoyberg** [comment]
@ndmitchell Can you try newest master? I added the hack in a few more locations.

**Comment by snoyberg** [comment]
And for the record, I've been busy sending patches to GHC to fix the problem at the source, so hopefully GHC 7.10.3 and onward won't suffer from these problems and we can do away with this ugly hack.

**Comment by ndmitchell** [comment]
Works for me, thanks!
