### ISSUE TITLE
stack master fails when c2hs is used

### ISSUE THREAD

**Issue by Fuuzetsu** [commercialhaskell/stack#821]
```
    setup-Simple-Cabal-1.18.1.5-x86_64-linux-ghc-7.8.4: The program c2hs version
    >=0.15 is required but the version of
    /home/shana/.stack/snapshots/x86_64-linux/lts-2.14/7.8.4/bin/c2hs could not be
    determined.
1/4
[nix-shell:~/programming/HaskellR]$ c2hs --version
C->Haskell Compiler, version 0.26.1 Budburst, 4 April 2015
  build platform is "x86_64-linux" <1, True, True, 1>
```

On stack 250186216e6f97d2955003418b5342132b46a45e

It built fine on previous versions so presumably it's some regression, running `stack build`.

**Comment by snoyberg** [comment]
Trying to repro now. What is the output of the following commands:

```
which c2hs
c2hs --numeric-version
/home/shana/.stack/snapshots/x86_64-linux/lts-2.14/7.8.4/bin/c2hs --version
/home/shana/.stack/snapshots/x86_64-linux/lts-2.14/7.8.4/bin/c2hs --numeric-version
```

**Comment by snoyberg** [comment]
And if you can provide a minimal reproducing case, that will be useful. I've tried a few different combinations and have been unable to reproduce that problem.

**Comment by Fuuzetsu** [comment]
Oh, I think user error happened:

```
/home/shana/.stack/snapshots/x86_64-linux/lts-2.14/7.8.4/bin/c2hs: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory
```

I'm on NixOS and I've in the meantime garbage collected. What happened is the libgmp in question got deleted since. So you can close this issue.

But is there a way to get stack to rebuild c2hs without clobbering my stack sandbox?

**Comment by snoyberg** [comment]
This is definitely pulling back a few layers of abstraction, but the following should work:

    rm $(stack path --snapshot-install-root)/installed-packages/c2hs*
