### ISSUE TITLE
`stack build --file-watch` infinite loop on build error with template haskell

### ISSUE THREAD

**Issue by MaxDaten** [commercialhaskell/stack#822]
Under some circumstances "--file-watch" loops the building process. I think a TH splice causes this behavior. I prepared a repo based on `stack new` with necessary additions and build error caused by https://github.com/MaxDaten/stack-file-watch-loop/blob/master/app/Main.hs#L19.

**Stack Version**

```
> stack --version
Version 0.1.3.1, Git revision 908b04205e6f436d4a5f420b1c6c646ed2b804d7
```

**Steps To reproduce:**

1. `git clone git@github.com:MaxDaten/stack-file-watch-loop.git`
2. `cd stack-file-watch-loop`
3. `stack build --file-watch`

**Expected:**

One single build step with printing the error

```
[2 of 2] Compiling Main             ( app/Main.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/stack-file-watch-loop-exe/stack-file-watch-loop-exe-tmp/Main.o )

/Users/xxx/Workspace/briends/stack-file-watch-loop/app/Main.hs:19:23:
    No instance for (Num String) arising from the literal ‘10’
    In the first argument of ‘pure’, namely ‘10’
    In the fourth argument of ‘simpleOptions’, namely ‘(pure 10)’
    In a stmt of a 'do' block:
      (opt, ()) <- simpleOptions
                     (concat
                        (["Version ", "0.1.0.0"]
                         ++
                           (if ("40b71e841475731eff58b5d3acf145d83adf3eb7"
                                == ("UNKNOWN" :: String)) then
                                []
                            else
                                [", Git revision ", "40b71e841475731eff58b5d3acf145d83adf3eb7",
                                 if False then " (dirty)" else ""])))
                     "header"
                     "descr"
                     (pure 10)
                     empty

--  While building package stack-file-watch-loop-0.1.0.0 using:
      /Applications/ghc-7.10.2.app/Contents/bin/runhaskell -package=Cabal-1.22.4.0 -clear-package-db -global-package-db -package-db=/Users/xxx/.stack/snapshots/x86_64-osx/lts-3.0/7.10.2/pkgdb/ /var/folders/xp/8fbnz73x77786vmh_8zhct3w0000gn/T/stack44232/Setup.hs --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ build exe:stack-file-watch-loop-exe --ghc-options -hpcdir .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/hpc/.hpc/ -ddump-hi -ddump-to-file
    Process exited with code: ExitFailure 1
```

**Actual:**

repeatedly executed build steps with the same output above, again and again. Fixing the type error at https://github.com/MaxDaten/stack-file-watch-loop/blob/master/app/Main.hs#L19 stops the endless building:

```

main :: IO ()
main = do
  (opt,()) <- simpleOptions
                $(simpleVersion Meta.version)
                "header"
                "descr"
                (pure "A String") -- No Err
                empty
  putStrLn opt
```

---
_OR_

Puting the `$(simpleVersion Meta.version)` into quotes and keeping the type error results in the expected behavior (printing error and stop).

```
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TemplateHaskell   #-}
module Main where

import Data.Maybe                        (fromJust, maybe)
import Control.Applicative
import Options.Applicative               as Opts
import Options.Applicative.Simple        as Opts
import Paths_stack_file_watch_loop       as Meta

import Lib

main :: IO ()
main = do
  (opt,()) <- simpleOptions
                "$(simpleVersion Meta.version)"
                "header"
                "descr"
                (pure 10) -- err
                empty
  putStrLn opt
```

**Comment by MaxDaten** [comment]
Maybe related: https://github.com/commercialhaskell/stack/issues/559

**Comment by snoyberg** [comment]
Beautifully written bug report, thank you :)

I'm not actually able to reproduce the problem, but I probably have a simple change to the codebase: clear the dirty flag *after* running the build instead of before. The reason I wrote it to clear the dirtiness before was so that, if you're editing during the build, it will rebuild immediately thereafter. However, the possibility of these kinds of situations makes me think it's better to do it the other way. I'll push a change for this now.

**Comment by snoyberg** [comment]
Alright, can you give master a shot?

**Comment by MaxDaten** [comment]
> Beautifully written bug report, thank you :)

You are welcome. stack eases A LOT in my production flow. 


> The reason I wrote it to clear the dirtiness before was so that, if you're editing during the build, it will rebuild immediately thereafter. 

Uhm that is something I'm doing quite often, especially in the "brain dumping phase". But okay, should not be a problem to keep in mind to trigger the save one more time. And this solution is better than keep spinning all the time :)

---

**Now to the important part:**

> Alright, can you give master a shot?

```
stack --version                                                                                                                                                                                                                        
Version 0.1.3.1, Git revision e7df61a70f286ddfa9f1d3c19b87c0bd7e19c571 (1634 commits) X86_64
```

Done, and it's fixed for me :). It rebuilds only once on file change and stops on `ExitSuccess` or `ExitFailure 1`. Thank you all!
