### ISSUE TITLE
Problem with building local project

### ISSUE THREAD

**Issue by d12frosted** [commercialhaskell/stack#823]
Hey, I am not sure where to write about my issue, but hope this is the right place.

I've been trying to build `hakyll` from sources by using `stack build` and encountered following error.

```
hakyll-4.7.2.3: configure
Configuring hakyll-4.7.2.3...
hakyll-4.7.2.3: build
Preprocessing executable 'hakyll-init' for hakyll-4.7.2.3...
[1 of 3] Compiling Paths_hakyll     ( .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/Paths_hakyll.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/hakyll-init/hakyll-init-tmp/Paths_hakyll.o )
[2 of 3] Compiling Hakyll.Core.Util.File ( src/Hakyll/Core/Util/File.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/hakyll-init/hakyll-init-tmp/Hakyll/Core/Util/File.o )

src/Hakyll/Core/Util/File.hs:11:1: Warning:
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
[3 of 3] Compiling Main             ( src/Hakyll/Init.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/hakyll-init/hakyll-init-tmp/Main.o )
Linking .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/hakyll-init/hakyll-init ...
hakyll-4.7.2.3: install
Installing library in
/Users/d12frosted/Developer/d12frosted/_hakyll/.stack-work/install/x86_64-osx/lts-3.1/7.10.2/lib/x86_64-osx-ghc-7.10.2/hakyll-4.7.2.3-95Jt8ztOnFTBufnWQKdRZI
Installing executable(s) in
/Users/d12frosted/Developer/d12frosted/_hakyll/.stack-work/install/x86_64-osx/lts-3.1/7.10.2/bin
setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2: Error: Could not find
module: Hakyll with any suffix: ["hi"] in the search path:
[".stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build"]

--  While building package hakyll-4.7.2.3 using:
      /Users/d12frosted/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0/ install
    Process exited with code: ExitFailure 1
```

I tried to remove `.stack-work` dir, removing `stack.yaml` and `stack init`, but it didn't help. So then I've tried to build `hakyll` by calling `stack install hakyll` when I am not in stack project dir. And everything was fine - it builded. Also the strange thing is that when I call `stack test` everything was built and worked fine.

My configs are

```
OS X 10.10.5 (14F27)
Version 0.1.3.1, Git revision 3da2a5b1faf8ef045fed550840647571cda9ff3e
The Glorious Glasgow Haskell Compilation System, version 7.10.2
build plan: lts-3.1 (both locally and globally)
```

Also I've tried using cabal (in sandbox) and it worked well.

```
$ cabal sandbox init
$ cabal install --only-dependencies
$ cabal build
```

Does anyone has any clues?

**Comment by snoyberg** [comment]
How did you get the sources, and what does your stack.yaml file look like?

**Comment by d12frosted** [comment]
I cloned master branch from [official repository](https://github.com/jaspervdj/hakyll). Then I did `stack init` inside of project root. My `stack.yaml` file has following content.

```
flags:
  hakyll:
    watchserver: true
    previewserver: true
    checkexternal: true
packages:
- '.'
extra-deps: []
resolver: lts-3.1
```

**Comment by snoyberg** [comment]
That's very strange. I can't reproduce this problem on my system. I suppose it may be OS-specific, but I'm not sure how. After running `stack build`, what's the output of:

    ls -la .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build

The build error you're getting is actually during Cabal's copy step, meaning that the build completed successfully, and then somehow a .hi file was not generated.

**Comment by d12frosted** [comment]
Uh-oh. 

```
$ ls -la .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build
total 0
drwxr-xr-x  4 d12frosted  staff  136 Aug 20 09:43 .
drwxr-xr-x  8 d12frosted  staff  272 Aug 20 09:43 ..
drwxr-xr-x  4 d12frosted  staff  136 Aug 20 09:43 autogen
drwxr-xr-x  4 d12frosted  staff  136 Aug 20 09:43 hakyll-init
$ ls -la .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/autogen/
total 32
drwxr-xr-x  4 d12frosted  staff   136 Aug 20 09:43 .
drwxr-xr-x  4 d12frosted  staff   136 Aug 20 09:43 ..
-rw-r--r--  1 d12frosted  staff  1549 Aug 20 09:43 Paths_hakyll.hs
-rw-r--r--  1 d12frosted  staff  9777 Aug 20 09:43 cabal_macros.h
$ ls -la .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/hakyll-init/
total 3184
drwxr-xr-x  4 d12frosted  staff      136 Aug 20 09:43 .
drwxr-xr-x  4 d12frosted  staff      136 Aug 20 09:43 ..
-rwxr-xr-x  1 d12frosted  staff  1628196 Aug 20 09:43 hakyll-init
drwxr-xr-x  9 d12frosted  staff      306 Aug 20 09:43 hakyll-init-tmp
$ ls -la .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/hakyll-init/hakyll-init-tmp/
total 112
drwxr-xr-x  9 d12frosted  staff    306 Aug 20 09:43 .
drwxr-xr-x  4 d12frosted  staff    136 Aug 20 09:43 ..
drwxr-xr-x  3 d12frosted  staff    102 Aug 20 09:43 .stack-work
drwxr-xr-x  3 d12frosted  staff    102 Aug 20 09:43 Hakyll
-rw-r--r--  1 d12frosted  staff   2622 Aug 20 09:43 Main.hi
-rw-r--r--  1 d12frosted  staff  23832 Aug 20 09:43 Main.o
-rw-r--r--  1 d12frosted  staff   9499 Aug 20 09:43 Paths_hakyll.hi
-rw-r--r--  1 d12frosted  staff  15172 Aug 20 09:43 Paths_hakyll.o
drwxr-xr-x  3 d12frosted  staff    102 Aug 20 09:43 src
```

> The build error you're getting is actually during Cabal's copy step, meaning that the build completed successfully, and then somehow a .hi file was not generated.

Oh that's strange. You see, it's really working with bare `cabal`. 

Also I've just tried to build with older version of stack.

* `master` - doesn't build
* official `0.1.3.1` from releases - doesn't build
* `0.1.3.0` - doesn't build
* `0.1.2.0` - works
* `0.1.1` - works

I am installing official releases by downloading OS X binary, copying it to `~/.local/bin/stack` and `chmod +x ~/.local/bin/stack`. The latest version from master was installed via `stack upgrade --git` (btw, cool feature!). 

To make sure that I am running on right version I was always checking `stack --version` output, and here is `which stack`.

```
$ which stack
/Users/d12frosted/.local/bin/stack
```

Also, I've checked using `find` utility that I have only once `stack` executable.

**Comment by snoyberg** [comment]
Can you capture the full stack build -v output and put it in a gist?

**Comment by d12frosted** [comment]
Sure, [here it is](https://gist.github.com/d12frosted/3929863e9ee7fae0db88).

**Comment by snoyberg** [comment]
There are two bugs here:

1. stack is telling Cabal to only build the executable component (see: `build exe:hakyll-init`)
2. Cabal has a bug when building only some components (https://github.com/haskell/cabal/issues/2780)

I believe I solved (1) with 603c7916d02c7c7a17478a0b6c19870293f2173e. I'm not sure which master you tried previously, but if you could try again with the current master, I'd be interested in the result.

**Comment by d12frosted** [comment]
Oh @snoyberg . It's very silly from my side. I've really done `stack upgrade --git` before 603c791. Just upgraded again and everything is working! Thanks for helping me with my issue. Feel free to close it.

P. S. I wasn't aware of problems with `build exe:hakyll-init`, thanks for pointing that out.

**Comment by snoyberg** [comment]
Thanks for the feedback, it's good to know that the patch I put in actually works :).

**Comment by d12frosted** [comment]
> it's good to know that the patch I put in actually works

Indeed :smile:

**Comment by simonmichael** [comment]
I also confirm that `stack upgrade --git` (from stack 0.1.3.0) fixed this problem for me just now (building an older version of hledger on OSX). Thanks!
