### ISSUE TITLE
Readme should say which GHC/GHCJS is supported

### ISSUE THREAD

**Issue by GetContented** [commercialhaskell/stack#830]
It'd be really handy to know this on the readme / front page of the github proj.

**Comment by snoyberg** [comment]
Mind sending a pull request?

**Comment by GetContented** [comment]
I would, but I don't know which versions are supported. :-)

**Comment by snoyberg** [comment]
I didn't understand that you were asking about versions. For GHC it's 7.8
and up. GHCJS likely requires bleeding edge.

**Comment by GetContented** [comment]
Yes. That's what I was asking about. Nevermind if you don't see it as an issue, perhaps others find it easy to know which versions of stack are required to use which versions of GHC/JS

**Comment by snoyberg** [comment]
I'd still be happy to merge a doc pull request on this

**Comment by GetContented** [comment]
That's cool, but I don't know what the versions are. In other words, if I install the current version of stack, what version of GHC do I have to have installed before it will work? or does stack install GHC itself, in which case what version will it install?

How can I update GHC through stack? or can't I? It's not very clear.

**Comment by borsboom** [comment]
Stack will install GHC itself, if you don't already have the correct version on the PATH.  Which version depends on the value of the [resolver](https://github.com/commercialhaskell/stack/wiki/stack.yaml#resolver) setting.  For new projects, it'll use the current LTS resolver, and that uses GHC 7.10.2.  Note that stack will never modify your existing GHC installation.
