### ISSUE TITLE
Stack project introspection

### ISSUE THREAD

**Issue by gibiansky** [commercialhaskell/stack#839]
Is there a way to use `stack` for introspection of the stack project? For example, I'd like to know what `stack exec` does so that I can emulate it.  Things such as

- which ghc does this stack project use
- what is the resolver of this project
- what is GHC_PACKAGE_PATH set to
- a list of all targets in this session

And so on. Some sort of `stack info` command, or something?

**Comment by drwebb** [comment]
`stack path` will give you the resolver, ghc version (from the path to a package db), and directories added to GHC_PACKAGE_PATH (`snapshot-pkg-db`, `local-pkg-db`). You would have to do some parsing though. No idea if it's possible to currently get the targets from the command line.

**Comment by snoyberg** [comment]
`stack path` may end up being useful for IDE authors in general. @hamishmack maybe you have some ideas for what should be included here? As far as output format, we could generate JSON, YAML, or something else (I'm sure y'all would love to parse you some XML, right? /s).

**Comment by snoyberg** [comment]
It looks like there's no open work item left on this issue, as `stack path` is providing this information. Closing for now. @gibiansky if you do need more information, let us know.
