### ISSUE TITLE
Parallel builds don't work: Cabal (library) bug on configure?

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#84]
When I have parallel builds on, the `runhaskell Setup.hs build` steps will sporadically fail about "need to configure", but if I set the number of Shake flags to 1, it works. We may want to conditionally set threads to 1 on Windows for an initial release, and then debug what's happening.

**Comment by mpilgrem** [comment]
It seems that, after eight years, something may have happened somewhere to cure the original problem that the workaround fixed. See #6361.
