### ISSUE TITLE
Add --numeric-version

### ISSUE THREAD

**Issue by DanielG** [commercialhaskell/stack#842]
Parsing the output of `stack --version` is tricky as the format depends on whether stack was built from git or not. All other build tools I know of i.e. cabal, ghc and ghc-pkg support `--numeric-version` which prints only the version number and nothing else making it easy to use for feature checks.

**Comment by borsboom** [comment]
I'm all for this.  Might be a good task for someone new to the codebase, so a PR would be most welcome.

**Comment by DanielG** [comment]
There you go: #869

**Comment by borsboom** [comment]
Great, merged the PR.  Thanks again!
