### ISSUE TITLE
Sticky logging displays poorly on Travis CI

### ISSUE THREAD

**Issue by MaxGabriel** [commercialhaskell/stack#843]
Not a pressing issue, but the sticky logging displays poorly on Travis CI ([example output](https://travis-ci.org/yesodweb/yesod-scaffold/builds/76993733)).

```
Progress: 183/188classy-prelude-0.12.1.1: build
Progress: 183/188classy-prelude-0.12.1.1: install
Progress: 183/188Progress: 184/188conduit-combinators-1.0.3: install
Progress: 184/188Progress: 185/188classy-prelude-conduit-0.12.0.1: download
classy-prelude-conduit-0.12.0.1: configure
```

**Comment by snoyberg** [comment]
We added the `--no-terminal` option specifically because of Travis, where detecting terminal didn't work reliably. Can you try that?

**Comment by MaxGabriel** [comment]
My mistake; checked for an option like that but was checking on an old version of stack that didn't have that. `--no-terminal` works great!

**Comment by nh2** [comment]
I had the same problem on CircleCI, and using `--no-terminal` fixed it there too.
