### ISSUE TITLE
"stack ghci" should be usable outside of a project.

### ISSUE THREAD

**Issue by seanparsons** [commercialhaskell/stack#844]
Sometimes I just want GHCi with some dependencies added using the --package option, like to quickly scratch through a CSV with cassava for example. So it would be nice to be able to run "stack ghci --package cassava" in a random non-project folder and the appropriate things happen before I'm then dropped into the REPL.

**Comment by snoyberg** [comment]
What output are you seeing from `stack ghci --package cassava`?

**Comment by seanparsons** [comment]
```
➜  /tmp  mkdir test
➜  /tmp  cd test 
➜  test  stack ghci --package cassava
Run from outside a project, using implicit global config
Using resolver: lts-2.21 from global config file: /home/sean/.stack/global/stack.yaml
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?
```

**Comment by seanparsons** [comment]
That's with 0.1.3.1 BTW.

**Comment by snoyberg** [comment]
Can you try master?

**Comment by seanparsons** [comment]
@snoyberg Sweet, that works with master!
