### ISSUE TITLE
Stop nagging people that call `stack test`

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#845]
/cc @chreekat 

`NOTE: the test command is functionally equivalent to 'build --test'`

baits people into typing more for no functional purpose. If the issue is with build target discoverability, we should fix the docs or command-line help.

**Comment by cocreature** [comment]
The same also goes for `stack install`. I realize that some people might be confused, but if you don't plan to remove the commands and they are accepted, I don't see why I need to see a big warning every time I run them.

**Comment by bitemyapp** [comment]
yeah I agree @cocreature - it confuses people into thinking they're deprecated when they're not.

**Comment by snoyberg** [comment]
As the guy who wrote those comments: I agree, let's kill them. The --help output already explains this, which is sufficient. Does someone else want to send a PR for this? It's some easy changes in `src/main/Main.hs` (my internet is acting up right now).

**Comment by snoyberg** [comment]
Internet fixed, and...

**Comment by cocreature** [comment]
Thanks!

**Comment by bitemyapp** [comment]
Thank you @snoyberg :)

**Comment by snoyberg** [comment]
Sure. It was bugging me too.

**Comment by simonmichael** [comment]
Thanks! :-)
