### ISSUE TITLE
How do I add dependencies?

### ISSUE THREAD

**Issue by sid-kap** [commercialhaskell/stack#850]
Suppose I have a stack project and I want to add `wreq` as a dependency.
Should I just edit the `.cabal` file and add `wreq`, or maybe `wreq [most up-to-date version]` as a dependency, just as I used to in a cabal project?
I imagine that stack has a better way of doing this, where I simply tell stack which package I want, and it figures out which version of the package I should use (i.e. which version is in stackage).

**Comment by borsboom** [comment]
Can you just add `wreq` as a dependency in the .cabal file, no need to specify any version bounds.  Stack will always use the version in the snapshot selected by stack.yaml's `resolver` value.

Note: if others will be building your code using cabal-install (like, you're planning to upload it to hackage or your team isn't all using stack), it's still a good idea to add version bounds to your .cabal file for their benefit.

**Comment by sid-kap** [comment]
That makes sense. Thanks!
