### ISSUE TITLE
C.UTF-8 locale is debian specific

### ISSUE THREAD

**Issue by cocreature** [commercialhaskell/stack#856]
Since 9787aed688187b6c00b778c76bdabe7df2147cf0 stack tries to set `LC_ALL` to `C.UTF-8`. This is a bad idea, since that locale is Debian (and transitively Ubuntu) specific. There is an upstream [glibc bug](https://sourceware.org/bugzilla/show_bug.cgi?id=17318) to support this, but it's not yet fixed.

On distros that do not support this (at least Arch and Fedora) it actually makes the problem far worse than it was before, since now even if your locales are all fine and utf8 trying to set them breaks this, so we're back to the `commitBuffer: invalid argument (invalid character)` problem.

This means that if people upgrade their stack version, they can't even downgrade and built an old version since the build reproducibly fails.

Pinging @borsboom

**Comment by borsboom** [comment]
Argh, sounds like I need to make this more intelligent.  Maybe something like:

1) If the locale already uses the UTF-8 charmap, just leave it alone.
2) Otherwise, use `locale` to determine if the current locale but with the UTF-8 charmap exists, and if so, use that.
3) Otherwise, check for existence of `C.UTF-8`, and if so, use it.
4) If all else fails, print a warning and leave the locale alone.

How does that sound?

(looking forward to [GHC_CHARENC](https://phabricator.haskell.org/D1167))

**Comment by cocreature** [comment]
Sounds reasonable. Kinda annoying to have to add such a workaround, but there doesn't seem to be an easy way around it.

**Comment by borsboom** [comment]
@cocreature I've pushed more intelligent logic to master.  Turns out trying to do anything cross-platform with locales is tricky (there's no standard for locale names), but I'm hoping this does the right thing for the majority of cases and fails gracefully (with a warning).

**Comment by borsboom** [comment]
(I tested this on OS X, Debian 7, and CentOS 6.6)

**Comment by cocreature** [comment]
Thanks, works on Arch too.

**Comment by wismill** [comment]
Hi, not working here with Archlinux: `commitBuffer: invalid argument (invalid character)` issue.

```
locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=fr_FR.UTF-8
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER="fr_FR.UTF-8"
LC_NAME="fr_FR.UTF-8"
LC_ADDRESS="fr_FR.UTF-8"
LC_TELEPHONE="fr_FR.UTF-8"
LC_MEASUREMENT="fr_FR.UTF-8"
LC_IDENTIFICATION="fr_FR.UTF-8"
LC_ALL=
```

```
stack --version
Version 0.1.3.1, Git revision 9fedeff78805647756502f72aae1ed471821f73d (1702 commits) X86_64
```
