### ISSUE TITLE
hard to run tests and check haddocks efficiently

### ISSUE THREAD

**Issue by simonmichael** [commercialhaskell/stack#857]
I'd like to both run tests and check there are no haddock errors, as efficiently as possible, eg in a travis commit hook. If I understand rightly,

`stack test; stack haddock --no-haddock-deps` builds things twice

`stack build --test --haddock` builds once, but does not support --no-haddock-deps so generates haddocks for all deps, which is undesirable. (And stack haddock's claim that it is equivalent to stack build --haddock is not yet true).

**Comment by borsboom** [comment]
Yeah, that seems strange and must be an oversight.  There's no reason `stack build --haddock` shouldn't accept the same arguments as `stack haddock`.  `stack test; stack haddock --no-haddock-deps` will, unfortunately, build twice (it's not trivial to get Cabal to install haddocks without building in general, although for local packages it would be much easier than for snapshot packages).

**Comment by borsboom** [comment]
`stack build --test --haddock --no-haddock-deps` now supported on master.

**Comment by simonmichael** [comment]
Thanks!
