### ISSUE TITLE
Stack bench should support passing arguments to the benchmark

### ISSUE THREAD

**Issue by j-a-k** [commercialhaskell/stack#858]
Using stack bench there doesn't seem to be a way to pass Crtiterion's --output flag to the benchmark program.

**Comment by markus1189** [comment]
That should work, you can look at #496 and #512 I'm on the phone but there
should be an example.
On Aug 26, 2015 9:52 PM, "j-a-k" <notifications@github.com> wrote:

Using stack bench there doesn't seem to be a way to pass Crtiterion's
--output flag to the benchmark program.

—
Reply to this email directly or view it on GitHub
<https://github.com/commercialhaskell/stack/issues/858>.

**Comment by j-a-k** [comment]
hmm not sure why i didnt find that issue, but yes this should be a duplicate of that

**Comment by markus1189** [comment]
Alright, I'll close then :)
