### ISSUE TITLE
proxy?

### ISSUE THREAD

**Issue by chrand** [commercialhaskell/stack#861]
Hi,
I searched the wiki and the command-line help on how to enable proxy support, but didn't find/missed how to do it.

My case: I (am forced to) use Windows in a corporate network with ntlm proxy authentication (ntlm not necessary, see below). I get the following error:
```
stack-0.1.3.1-x86_64-windows.exe templates

Failed to download templates. The HTTP error was: FailedConnectionException2 "api.github.com" 443 True connect: failed (Connection timed out (WSAETIMEDOUT))
```

Other command-line tools can access external servers, both on cmd.exe and cygwin, by pointing to the proxy specified in the environment variables HTTP_PROXY and HTTPS_PROXY. The variables' content is `http://127.0.0.1:3128`. 

Note: support of ntlm authentication in `stack` is not required: as in my case, one can locally install the [cntlm] (http://cntlm.sourceforge.net/) proxy to expose a local proxy that can take care of wrapping http(s) requests, authenticating down the chain.

**Comment by snoyberg** [comment]
The http_proxy and https_proxy environment variables are both supported by the underlying http-client library. Case-insensitive support for this variable was only recently added, and therefore may not be part of the currently released stack (but should be in the next one). Can you try setting an all-lowercase version of the variable and see if that works?

**Comment by chrand** [comment]
Works, thanks.
Funny: I always thought that Windows environments were case-insensitive :)
