### ISSUE TITLE
`stack ghci` tries to load multiple versions of `text`

### ISSUE THREAD

**Issue by zudov** [commercialhaskell/stack#867]
I am using stack to build [purescript](https://github.com/purescript/purescript) with `lts-3.2`. My ghc is installed system-wide, and I also have several libraries installed system-wide.

While `stack build` works flawlessly, `stack ghci` tries to use `text-1.2.1.3`
(from lts-3.2) and `text-1.2.0.6` simultaneously which causes an error:

```haskell
[ 13 of 110] Compiling Language.PureScript.Names ( Language/PureScript/Names.hs, interpreted )

Language/PureScript/Names.hs:91:52:
    Couldn't match expected type ‘T.Text’
                with actual type ‘text-1.2.0.6:Data.Text.Internal.Text’
    NB: ‘T.Text’
          is defined in ‘Data.Text.Internal’ in package ‘text-1.2.1.3’
        ‘text-1.2.0.6:Data.Text.Internal.Text’
          is defined in ‘Data.Text.Internal’ in package ‘text-1.2.0.6’
    In the first argument of ‘T.unpack’, namely ‘str’
    In the second argument of ‘splitOn’, namely ‘(T.unpack str)’
```

```shell
zudov@x200 ~/prog/haskell/purescript $ stack exec -- ghc-pkg list text
/usr/lib64/ghc-7.10.2/package.conf.d
   text-1.2.0.6
/home/zudov/.stack/snapshots/x86_64-linux/lts-3.2/7.10.2/pkgdb
   text-1.2.1.3
/home/zudov/prog/haskell/purescript/.stack-work/install/x86_64-linux/lts-3.2/7.10.2/pkgdb
```

Here is an output of `stack ghci --verbose`: [paste](http://lpaste.net/139754).

I can reproduce it using latest stack release (0.1.3.1) and stack from master branch
(commit 478ca7118372fe9a500430cae36924ae64e147c6).

**Comment by zudov** [comment]
Related issue https://github.com/commercialhaskell/stack/issues/127

**Comment by chrisdone** [comment]
Interesting....

**Comment by zudov** [comment]
I've also got it appear with both `transformers-0.4.2.0` and `transformers-0.4.3.0` installed in a global database.

**Comment by snoyberg** [comment]
My best bet here is that the usage of `-package=` instead of `-package-id` is giving GHC too much freedom in choosing specific installed instances of packages, leading to this confusion. @chrisdone is it possible to use `GhcPkgId`s instead?

**Comment by snoyberg** [comment]
@zudov I've just pushed a new branch, 867-ghci-package-id, which may fix the problem, can you test it?

@chrisdone See PR #1082

**Comment by zudov** [comment]
I made sure that the problem is gone, created even more entropy in my global database than I originally had and reproduced it without a patch, then tried it with patched stack and it worked perfectly.

:+1: Thanks a lot

**Comment by snoyberg** [comment]
Cool, thanks for the confirmation. I'm going to close this issue, and any problems with the patch can be discussed in the PR.
