### ISSUE TITLE
`stack path` tries to acquire lock

### ISSUE THREAD

**Issue by thomasvnoort** [commercialhaskell/stack#872]
Our build environment uses `stack path` to figure out where to get the binaries to archive. Right now this causes builds to be slow since this step waits for other stack instances in concurrent build jobs to release their lock.

I'd expect `stack path` to not require any locking at all since it just prints some path information, but I might be overlooking something here.

**Comment by chrisdone** [comment]
Is that on master?

**Comment by thomasvnoort** [comment]
Sorry, forgot to mention a version. But yes, this happens both with the 0.1.3.1 release and master.

**Comment by snoyberg** [comment]
@rrnewton any thoughts on the locking issue here?

**Comment by rrnewton** [comment]
Sure, if it doesn't side effect the snapshot it should be another exception.  I was conservative about locking things.

I'm pretty busy here at ICFP this week, and then PPoPP next week, but if it's not urgent I can get to these little fixes after next week.

**Comment by snoyberg** [comment]
This should be much less of a problem now that locking is disabled by default, closing.

**Comment by thomasvnoort** [comment]
I'm a bit confused here, isn't locking required to stay safe when running multiple instances of stack? If so, this issue remains an issue for us and our build environment.

**Comment by snoyberg** [comment]
Not that I'm aware of, see: https://github.com/commercialhaskell/stack/issues/950#issuecomment-138619560

In any event, stack path _definitely_ is safe without locking.

**Comment by thomasvnoort** [comment]
Thanks for clarifying, we'll see how this works out in practice :)

**Comment by rrnewton** [comment]
Hi @thomasvnoort,

I wrote a tiny patch that includes `stack path` in the exceptions, together with the original set of non-locking commands, which are enumerated in the [pull request here](https://github.com/commercialhaskell/stack/pull/670).

I made a pull request (#1112) with the patch.
