### ISSUE TITLE
Imprecise instructions; poor README

### ISSUE THREAD

**Issue by MASantos** [commercialhaskell/stack#874]
I think the readme deserves a revision. The page http://www.yesodweb.com/page/quickstart points to it. Such an nested set of instructions is relatively common nowadays, but it makes less reasonable to expect users will have the time and patience to go through a detail read of instructions and explanations of the idea behind a project/tool. A "quick start" and a readme deserve thus more attention. 

The readme says:
```
stack is a cross-platform program for developing Haskell projects. 
It is aimed at Haskellers both new and experienced. [...]It features:
Installing GHC automatically, in an isolated location.
```

I just happened to lose over two hours in doing ```stack install yesod-bin cabal-install --install-ghc``` just because it wasn't clear to me that what stack does is a **local**, i.e., under $HOME installation.

The definition of sandboxing in wikipedia doesn't imply such a kind of installation necessarily. **If this is also addressed to new users, it should be made clear from the beginning on** -it doesn't take that much.

* "Isolated location" is also extremely vague. Fink also installs packages in an "isolated" location, but it's system-wide.
* As **Stack installs things under ~/.stack**, five simple words like these say much more than the current readme.
* If one wants to have ghc system wide and then try to install yesod, as I understand it, Stack only helps in sorting out the often pesky installation process of yesod, but doesn't help with the first point. If it also allows for a system-wide installation, it should be explicitly clarified as well.
* The README has a nice animation of a use of stack, but fails to make this point clear. I find it more trying to make a pitch than getting the right idea through.

PS: There are many references here and there to Stack. This one is from the Yesod book
```
stack is a complete build tool for Haskell which deals with your compiler 
(Glasgow Haskell Compiler, aka GHC), libraries (including Yesod), additional 
build tools (like alex and happy), and much more.
```
...and it misses the chance to actually add something with some substance as to what Stack is/does: ```make``` is also a build tool, but has little in common with Stack.

Metaphors are worth only so much. If one can be more precise with the same number of words or less, then they are worthless. 

Besides this, all commands worked flawlessly in my ubuntu 14.04. That's much more than what I can say of many other projects. Thanks for stack!

**Comment by drwebb** [comment]
You may have commented just a too little late: https://github.com/commercialhaskell/stack/blob/master/GUIDE.md

I sympathize with your point. In the fourth paragraph of the first section, I feel that some mention of `~/.stack` and `./.stack-work` would be better than just the parenthetical reference. I feel that would address your issue. To be clear, stack does not just install things under ~/.stack, extra dependencies are not shared between projects and go in `./.stack-work`

Some other points. `stack setup` does install GHC. So you are wrong in your third bullet point. 
And, it's a little strange that you would be using `stack` to install `cabal-install`, if I were still using `cabal` I would let it manage itself.

**Comment by MASantos** [comment]
Thanks for your reply.

Your last two paragraphs are way shorter and provide much more insight into stack than the readme and all the text I read starting from the yesod quick start guide to this github repo. They should go in the readme, or better in that new guide: It's even better than the whole section of ```what is stack```.

As for cabal-install, well, that's the doc mess I'm complaining about: I'm following the instructions here http://www.yesodweb.com/page/quickstart. Only after additional 2hours and 2G of hd space did my ```stack exec -- yesod init --bare && stack init```  finish. And I haven't issued yet the ```stack build``` step. If I wanted to give a try with yesod, this is all quite a deterrent. 

My bad for not finding that previous reference, but how much can anyone be blamed for that after having already invested quite some time in dealing with misleading instructions? The web of hyperlinks we live with is an amazing resource of knowledge, but it may as well lead to dispersion.

**Comment by radix** [comment]
@drwebb I think that third bullet point is still correct -- notice that @MASantos said "*system* wide". Stack does not help with installing GHC system-wide, though it can *use* a system-wide installation of GHC if one is available.

I'm not really sure what the use-case is for a system-wide installation that doesn't come from your OS vendor, but maybe @MASantos can help clarify that. Regardless, I am happy to see the "in an isolated location" wording in the README changed to be "in your home directory".

**Comment by MASantos** [comment]
@radix Good to know it can use an already system-wide installation of GHC. 

As for your question, afaik OSX doesn't provide any Haskell distribution. For that one has to go to Haskell Platform (HP)...or not. Back in May/June I tried installing yesod on a OSX10.6 which I managed only using a sandbox, but I had people telling me that HP may not be the best way to go. Besides, I still view GHC as gcc: I don't have a distinct copy of it for every project I build.

I still see the "isolated" in the README...

**Comment by radix** [comment]
@MASantos FWIW, there's also https://ghcformacosx.github.io/, which is a more minimal system-wide installer of GHC for Mac.

Also: stack does *not* install GHC per project -- it installs it for all projects to share in your home directory in `~/.stack`.

**Comment by drwebb** [comment]
Yes, I stand corrected!

**Comment by MASantos** [comment]
Thanks for that link. I'll have a look.  However my main problem in OSX was to install yesod (more precisely Shakespeare). GHC installed for me always more or less flawlessly.

You are right. Bad wording. And in perspective it would be overkill to be per project.

All in all, I think your (both) comments here should go early in the readme and guide.



On August 28, 2015 9:03:34 PM EDT, Christopher Armstrong <notifications@github.com> wrote:
>@MASantos FWIW, there's also https://ghcformacosx.github.io/, which is
>a more minimal system-wide installer of GHC for Mac.
>
>Also: stack does *not* install GHC per project -- it installs it for
>all projects to share in your home directory in `~/.stack`.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/commercialhaskell/stack/issues/874#issuecomment-135923977

-- 
Sent from my Android device with K-9 Mail (Open Source). Strange or incorrect phrases may be due to auto-correction software. Public key ID: E8FE60D7

**Comment by wuzzeb** [comment]
I was just reading the GUIDE.md, and came across an error.  The last displayed command to set the PATH is incorrect, it currently reads `echo 'export HOME=$HOME/.local/bin:$PATH' >> ~/.bashrc` but it should be `export PATH=$HOME....`

**Comment by snoyberg** [comment]
@MASantos would you be able to send a PR for the improved wording you think would be useful to users? That would be most appreciated.

**Comment by MASantos** [comment]
It's tempting but I don't think I know enough of Stack yet. This is my
first time dealing with it.
Plus, my idea of what should go in this (quick) guides may not be what you
or many other are used to.

Given the proliferation of these package managers, sandboxes or wrappers,
my main concerns are
A) Sensible overview of what this is about. Breath-first exposition; not
depth-first.
B) Logistics of the installation/deinstallation process. If I ended up
installation something I then think is crap,
how can I get rid of *everthing it came with*? But also, how much will it
download for me to be ready use it?

As stated above, both points A) & B) overlap to some extend. Notice, when I
say "logistics of installation" I don't mean
simply the steps I have to follow to install something. Knowing these
things in advance, before that "shotgun" installation
process, reassures me of the value of it all and helps me plan and get the
rigth mindset for spending time
troubleshooting any possible issue.

Some detail of these points:
1) The download size. I'm using my phone as my internet connection, or may
be at a place with a somewhat slow/busy
one. The stack installation of Yesod [1] I did on friday consisted of
1.9GB! I would like to know that in advance
so I can plan the best time for it.
2) 1.9GB is almost crazy. LaTeX takes twice as much, but its fame precedes
it, meaning, one can justify it, "you know
you can do many things with it". However, you know as well in advance it'll
be a huge download. For trying out Yesod, you still don't know if it's
worth, and worse, you don't know it in advance it will take ~2GB of HD
space. Is it justified? well, I learned here one can reuse in new projects
the packages previously installed for others. That a positive point. [2]
3) It might be easier to tackle these points by coming up with a trivial
test case. I guess the git man pages could be  a very good example of what
I have in mind. For instance the gitworkflows.

Finally, this requires some more time that what I have available right now.
If people thing this is a meaningful approach, I could try to write
something up in  a couple of weeks or so.

MA

[1] This thread is about Stack, not Yesod, I know. I bring it up just an
example. Stack installation is way less in space and time required.
[2] Don't assume this is obvious. This kind of isolated environments could
well be done system-wide. And there it would seem more meaningfull: After
seeing Alice stack installing and using Yesod, Bob decides to give it a
try. As far as I understand things right now, Bob will end up with an
additional 1.9GB in his home. Weird!


--
Public key ID: E8FE60D7
Public key server: see, e.g., hkp://keys.gnupg.net

**Comment by snoyberg** [comment]
I'm definitely getting lost in the details of this issue. But how did toy determine that stack downloaded 1.9gb of data?

**Comment by MASantos** [comment]
(uhm...didn't see that answer of yours till now)

Notice I was using the Yesod quick star guide as an example for discussing what I thing guides&readme should say. 

As for those 1.9Gb, I started from scratch -meaning I had no ~/.stack folder- and when I ended the ```stack build && stack exec -- yesod devel``` a ```du -sh ~/.stack``` gave those 1.9Gb as answer. This was on an ubuntu 14.04.

Stack itself installed fine.

**Comment by drwebb** [comment]
I'm would assume 1.1 GB is that from downloading and unpacking GHC.

snapshots usually end up being about 600-700MB before I decide to move on
to a newer version.

Yesod has a lot of dependencies, so 1.9 GB, including GHC, for getting
started Yesod doesn't sound absurd to me.
I've guess most Haskellers have accepted that fact.

On Tue, Sep 1, 2015 at 12:01 PM, MASantos <notifications@github.com> wrote:

> (uhm...didn't see that answer of yours till now)
>
> Notice I was using the Yesod quick star guide as an example for discussing
> what I thing guides&readme should say.
>
> As for those 1.9Gb, I started from scratch -meaning I had no ~/.stack
> folder- and when I ended the stack build && stack exec -- yesod devel a du
> -sh ~/.stack gave those 1.9Gb as answer. This was on an ubuntu 14.04.
>
> Stack itself installed fine.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/874#issuecomment-136828598>
> .
>



-- 
Tristan Webb PhD
Haskell Application Engineer
FP Complete
San Diego, CA
M: 619-452-9545

**Comment by drwebb** [comment]
closing with suggestions

I've opened a PR, but am not ready to merge yet. I would ask for other suggestions
be made. 

It goes without saying that it's impossible to make a guide to please
everybody. IMO the guide is off to a great start, but should to go into
some more topics. A second project with a little more
assumed Haskell experience would be great, especially IMO to cover stack-ide.

I'm going to close this in favor of a stack guide 2.0 issue. '
