### ISSUE TITLE
local-bin-path should be configurable via global stack.yaml

### ISSUE THREAD

**Issue by jwhitley** [commercialhaskell/stack#876]
**Repro steps**

1.  Add the line `local-bin-path: ~/local/bin` to `~/.stack/global/stack.yaml`.
2.  Run `stack path`

**Expected results**

`stack path` should show local-bin-path according to the stack.yaml setting:

```yaml
local-bin-path: /Users/whitley/local/bin
```

**Actual results**

The config setting is ignored and the default value remains:

```yaml
local-bin-path: /Users/whitley/.local/bin
```

**Notes**

AFAICT, this *should* work from [`src/Stack/Types/Config.hs:612`](https://github.com/commercialhaskell/stack/blob/master/src/Stack/Types/Config.hs#L612), but my Haskell is currently in drydock undergoing rust removal.

I don't use `~/.local`, but rather `~/local`.  (Note the missing dot in the latter.)  As such, every use of `stack install` currently must include the boilerplate local-bin-path parameter:

`stack --local-bin-path ~/local install`

This gets old fast.  I'd vastly prefer to set this once in `~/.stack/global/stack.yaml` and forget about it.

**Comment by snoyberg** [comment]
The user-global configuration file you want to use is:

~/.stack/stack.yaml

I see that the Wiki page had the wrong path; I've fixed the page. Can you test out the new configuration location and confirm that it works?

**Comment by jwhitley** [comment]
@snoyberg That works, thanks for the clarification.  I do note that the literal `~/.stack/stack.yaml` doesn't work, as the path is reported as not found.  A valid absolute system path is required e.g. `/Users/foo/.stack/stack.yaml`.  This presents a problem for putting the user config in version control, as the user id may not be the same on all systems (e.g. a user's development host vs. a vagrant VM with user `vagrant`).  Shall I file a separate issue on that?

Looking at the [`stack.yaml` wiki page](https://github.com/commercialhaskell/stack/wiki/stack.yaml), this paragraph is both difficult to parse and misleading:

> The stack.yaml configuration options break down into project specific and non-project specific options. The latter can be specified in your global config (`/etc/stack/config`) and user config (`~/.stack/stack.yaml`), as well as in the project config. The former must be in the project config.

E.g. Digging in, the `docker` config is explicitly permitted in all of project, user, and global configs per [Docker configuration](https://github.com/commercialhaskell/stack/wiki/Docker#configuration).  This despite its categorization under "Non-project configs".  I caught that, as I recall it from the stackage-view `stack.yaml` file.

I've had a go on the wiki at clarifying things as they stand, but fixing up the apparent false dichotomy between project & non-project options will require more work.  [Have a look at my changes](https://github.com/commercialhaskell/stack/wiki/stack.yaml/_compare/cc3f6ff2daf55e9febe37d01220423d60724aa72...1cd42f027705f1d56ead2c5882657ce8d8f05c3f) and update/revert/discuss as needed.  I'm happy to do some more work clarifying the wiki and/or getting issues/PRs in place to sort this out.

**Comment by snoyberg** [comment]
>  I do note that the literal ~/.stack/stack.yaml doesn't work, as the path is reported as not found.

Where did you try entering that path? If you mean that a valid path is required for `local-bin-path`: yes, that's known. I think the issue you're looking for is https://github.com/commercialhaskell/stack/issues/586

The revised version of the stack.yaml wiki is incorrect: non-project config can go in the project config settings as well, which was the intention of the original write-up. Notice the line which is no line present:

> as well as in the project config

That's why Docker is allowed in all three types of config files.

**Comment by snoyberg** [comment]
I've tweaked the language a bit, and it's now accurate. Closing.
