### ISSUE TITLE
File lock completely locks up the process

### ISSUE THREAD

**Issue by abhinav** [commercialhaskell/stack#879]
If you have have a stack process building something and you try to run another stack process that needs the lock at the same time, the latter decides to wait for a lock as expected, but it is now completely unresponsive to SIGINTs until it actually has the lock.

To reproduce, run two instances of `stack build` using the same resolver simultaneously.

Example:

I ran `stack haddock` in one window,

```
 $ stack haddock lens
Run from outside a project, using implicit global config
Using resolver: lts-3.2 from global config file: /Users/abg/.stack/global/stack.yaml
parallel-3.2.0.6: configure
parallel-3.2.0.6: build
[..]
```

And `stack build` on a project in another,

```
 $ stack build
Failed to grab lock ("/Users/abg/.stack/snapshots/x86_64-osx/lts-3.2/7.10.2/lockfile"); other stack instance running.  Waiting...
^Cuser interrupt
```

The second process didn't respond to that Ctrl-C until after the first process finished executing.

**Comment by snoyberg** [comment]
Pinging @rrnewton

**Comment by rrnewton** [comment]
I'll try to reproduce. Which OS was this on?

(We should probably test this in all of them.)

**Comment by rrnewton** [comment]
Ok, on both Mac OS and Linux what I see is that the second process doesn't respond to the first Ctrl-C, but does respond to a second Ctrl-C keypress.

On both systems they respond to Ctrl-Z on the first try.

@abhinav, do an unlimited number of Ctrl-C's still not work for you?

Ultimately, this is a problem for the [filelock Library](https://hackage.haskell.org/package/filelock).  What we are doing is waiting on a blocking call to take the lock using that library.  (An earlier version attempted to poll it ourselves and sleep inbetween, but that ran into a different bug.)

**Comment by abhinav** [comment]
Sorry, yeah. This was on OSX. I just gave it another go. Multiple Ctrl-Cs do indeed work. Don't know why I didn't try that before. Thanks.
