### ISSUE TITLE
stack init --solver doesn't add test dependencies to the build plan.

### ISSUE THREAD

**Issue by phadej** [commercialhaskell/stack#882]
Steps to to reproduce:
- take any package with test-suite which has dependencies not in the library.
- `stack init --solver`
- the result `stack.yaml` won't have the test dependencies

**Comment by snoyberg** [comment]
Dupe of #862, which should be resolved on master

**Comment by phadej** [comment]
Ah, thanks! Any idea when there will be release with that feature? I need it on travis, and installing from git isn't an option there?

**Comment by snoyberg** [comment]
I think we'll be doing another release this week. I'll touch base with @borsboom later.

**Comment by phadej** [comment]
Ok, I'll try if `stack update --git` will work for now.
