### ISSUE TITLE
Message "No local directories found as children of ..."

### ISSUE THREAD

**Issue by vlatkoB** [commercialhaskell/stack#885]
I cloned [stackage-view](https://github.com/fpco/stackage-view) and when calling `stack build ./stackage-view` (from outside of dir), I get message:
```bash
Run from outside a project, using implicit global config
Using resolver: lts-3.2 from global config file: /home/vlatko/.stack/global/stack.yaml
Error parsing targets: No local directories found as children of ./stackage-view
```
However, `cd stackage-view/ && stack build` works OK (as expected, fails with `lts-3.2`).

stack is 0.1.3.1

**Comment by snoyberg** [comment]
This is by design, and follows the design of other tools like git, e.g.:

```
vagrant@vagrant-ubuntu-trusty-64:~/haskell$ git status stack/
fatal: Not a git repository (or any of the parent directories): .git
```

Reason: we first try to find the package root by looking in the current directory and ancestors for the configuration, and then parse the command line arguments thereafter.

**Comment by vlatkoB** [comment]
There is a `Target syntax` paragraph in [stack build command wiki](https://github.com/commercialhaskell/stack/wiki/Build-command) that says
```
directory, e.g. **stack build foo/bar**, will find all local packages that exist 
in the given directory hierarchy and then follow the same procedure as passing
in package names as mentioned above. There's an important caveat here: if your
directory name is parsed as one of the above target types, it will be treated as that.
Explicitly starting your target with ./ can be a good way to avoid that, e.g. 
stack build ./foo
```
Is this old info than, or it means something else?

**Comment by snoyberg** [comment]
It's accurate, but not intended for the use case you're thinking of. Consider:

```yaml
resolver: lts-3.2
packages:
- ./foo
- ./bar
```

Then inside the project directory, `stack build ./foo` will build just that directory and not `./bar`.

**Comment by vlatkoB** [comment]
Got it. Thanks.

**Comment by snoyberg** [comment]
No problem
