### ISSUE TITLE
stack upload --safe

### ISSUE THREAD

**Issue by mitchellwrosen** [commercialhaskell/stack#888]
It would be nice if `stack upload` could optionally `stack build --test` or `stack build --pedantic --test` before uploading to Hackage. Maybe I'm just lazy =)

**Comment by borsboom** [comment]
My feeling on this is that if you have to remember to add a `--safe` argument, you should be able to remember to run `stack test` before `stack upload`.  So I guess I'm saying: yeah, you're lazy :)

There might be something to be said for `stack upload`, by default, requiring `stack test` to pass (and adding a `--unsafe` argument to skip that).  But this is something I'd want to see more feedback on before making any changes.

A pull request would, of course, prove that you are *not* lazy (but that *I* am).

**Comment by sjakobi** [comment]
I'm merging this issue into #717.
