### ISSUE TITLE
Replace Binary with something more reliable for file storage

### ISSUE THREAD

**Issue by snoyberg** [commercialhaskell/stack#889]
`Binary` instances are quite problematic for file storage, since they store no metadata about the schema itself. This has led multiple times to out-of-memory issues because an `Int` was parsed as a list size, for example. We have some hacks in the code base to essentially embed magic numbers to work around this, but there are certainly better ways we can solve this with improved libraries.

A non-solution: use JSON. We tried this already, and the performance hit was significant. We need a fast (de)serialization.

**Comment by phadej** [comment]
https://github.com/well-typed/binary-serialise-cbor https://www.youtube.com/watch?v=60gUaOuZZsE it's not released but might be an option. [CBOR](http://cbor.io/) is essentially binary json, there are tags indicating what data comes next in the binary stream.

**Comment by snoyberg** [comment]
Awesome, thanks for the link. I remembered hearing @dcoutts discuss this at some point, but didn't know what came of it. Duncan: are there plans to release this in the near term? And there doesn't seem to be any `Generic` support in the type class yet. Is that intentional, or would `Generic` support be a good thing for the library?

**Comment by phadej** [comment]
@snoyberg I have made a small package https://github.com/phadej/binary-tagged during "the morning hack". It's missing a bit of essential instances; but could it be used as a possible solution to this? It's not yet on Hackage, but it could be as soon as I verify API in our own dependant project.

**Comment by snoyberg** [comment]
It definitely looks like an improvement. My concerns are:

* It looks like this requires explicit versioning, am I misreading that?
* How big a performance hit would this introduce?

**Comment by phadej** [comment]
First question: it allows explicit versioning, but data is implicitly versioned by its structure: generic-derivable `HasNominalSop`. Explicit versioning might be needed sometimes, but with enough `newtypes` it should be needed (time shows). Actually one could write tests using this, to track when data formats actually change, i.e. hardcode hash into tests.

Second question: If only top-level data is tagged, then the performance hit shouldn't be noticeable. I'll write some trivial benchmarks to verify that.

**Comment by snoyberg** [comment]
Sounds good, I'm liking where this is headed :)

**Comment by phadej** [comment]
With https://github.com/phadej/binary-tagged/blob/wip/bench/Bench.hs (which is quite nice usage example as well) the result is:
![fireshot capture - criterion report - http___localhost_8000_bench html](https://cloud.githubusercontent.com/assets/51087/9719788/aa4ea418-5590-11e5-87eb-8dca842b617d.png)

I'll try to finalise and realise the package during this week. I'll ping this issue after that.

**Comment by snoyberg** [comment]
Very nice, thanks!

**Comment by phadej** [comment]
First release http://hackage.haskell.org/package/binary-tagged, some (almost) real world usage in https://github.com/futurice/haskell-flowdock-rest/blob/grep/flowdock-grep/src/Main.hs

As the latter is under active development, `binary-tagged` already caught structural changes: didn't need to clean cache files during development by hand at all.

**Comment by snoyberg** [comment]
Cool. Is this ready to go?

And by any chance, would you be interested in making the change to the stack codebase? It should be isolated to just a few specific places (anything calling Binary.encode\* or Binary.decode\*).

**Comment by phadej** [comment]
I can check them out, sure.

**Comment by snoyberg** [comment]
Thanks!
