### ISSUE TITLE
Defaults for options

### ISSUE THREAD

**Issue by pdobsan** [commercialhaskell/stack#893]
May I suggest a small improvement both of the various documentations and of the help messages provided by stack on the command line. There are many flags/config options of the form --something/--no-something. It would be nice to always indicate which one is the default.

Or in the case when such a choice is dependent of other factors, try to give some explanation.

**Comment by chrisdone** [comment]
I think if we mirror the `library-profiling` output, via the `boolFlags` combinator we get a good result:

[Example](https://github.com/fpco/stack/blob/878-shared-database/src/Stack/Options.hs#L94..L97):

``` haskell
libProfiling =
  boolFlags False
            "library-profiling"
            "library profiling for TARGETs and all its dependencies"
            idm
```

=>
``` 
  --library-profiling      Enable library profiling for TARGETs and all its
                           dependencies (--no-library-profiling to disable)
```

Although this is only on `master`, if you have an older release it shows two separate flags.

**Comment by chrisdone** [comment]
Although probably some text from `boolFlags` to say "disabled by default" would enhance that message.

**Comment by pdobsan** [comment]
Combining the help messages for the alternatives is good.
Still, as you also note,  defaults should be made clear.

**Comment by snoyberg** [comment]
Added in #4653
