### ISSUE TITLE
Proposal: expanded documentation on stack's relationship with other tools

### ISSUE THREAD

**Issue by kairuku** [commercialhaskell/stack#894]
(I apologize if these topics have already been covered somewhere else on the Web and I've overlooked this.)

I'm somewhat confused on how stack relates to some other tools (besides cabal), such as *stackage-cli, cabal-src and cabal-meta,* especially whether or not stack is *replacing* any other tools (or perhaps might someday in the future), including any other tools I'm not aware of and didn't mention, but which are also seemingly similar.

For instance, it seemed in the initial public announcements of both stack and stackage-cli that both were covering some similar workflows, and now I wonder if stack has completely superseded either stackage-cli outright or some of the stackage-cli *plugins*.

So I thought maybe it could be useful to add documentation, possibly even a separate markdown file, on specifically this aspect of stack, including any relevant roadmap.

**Comment by snoyberg** [comment]
This could be a great addition to: https://github.com/commercialhaskell/stack/blob/master/GUIDE.md#comparison-to-other-tools. Would you mind sending a PR with an initial comparison to other tools? A newcomer's impression to this would be very good. I'll be happy to fill in any details that need explaining.

**Comment by kairuku** [comment]
I'm new to forking and pull-requests (and at the sub-novice level with Haskell too) so please bare with me :)  I didn't go to deeply yet into differentiation of tools, and in this first branch have mainly just explored some ideas in creating a new directory structure for documentation (I'm happy to undo any of this too). I'll need to repair some URLs in a subsequent commit if this were to be approved for merging.

**Comment by kairuku** [comment]
Sorry, I did not see [#900](https://github.com/commercialhaskell/stack/issues/900) before making my pull-request
