### ISSUE TITLE
stack.yaml package field pointing to *.*.cabal not found

### ISSUE THREAD

**Issue by haroldcarr** [commercialhaskell/stack#895]
I added:

    packages:
    - '.'
    - /Users/carr/openhc/test-hunit-util

but got:

    > stack build
    No .cabal file found in directory /Users/carr/openhc/test-hunit-util/

The cabal file in that location is named `Test.HUnit.Util.cabal`.  If I rename the file to `Test-HUnit-Util.cabal` then it is found

(although, it then has other unrelated problems:

    cabal file /Users/carr/openhc/test-hunit-util/Test-HUnit-Util.cabal has a mismatched package name: Test-HUnit-Util
)

**Comment by snoyberg** [comment]
> (although, it then has other unrelated problems:

This is intended behavior: Hackage and cabal have inconsistent behavior around mismatching package/file names, and in stack we've decided to be consistent and enforce matching names. For details, see: https://github.com/commercialhaskell/stack/issues/317

We can improve the first part about finding .cabal files with periods in them.

**Comment by snoyberg** [comment]
I've updated master with better code for displaying accurate error messages. Now, it says things like:

```
cabal file path /home/vagrant/Desktop/periods/foo.bar.cabal does not match the package name it defines.
Please rename the file to: periods.cabal
For more information, see: https://github.com/commercialhaskell/stack/issues/317
```

**Comment by haroldcarr** [comment]
thx!
