### ISSUE TITLE
Stack master crashes on Windows

### ISSUE THREAD

**Issue by NightRa** [commercialhaskell/stack#898]
Stack master 7153be831735fd10edecf99926b47a04897f4ed8 on windows crashes in the proccess of ```stack build```. last output lines:
```
void-0.7: install
bifunctors-5: build
contravariant-1.3.2: configure
contravariant-1.3.2: build
contravariant-1.3.2: install
comonad-4.2.7.2: configure
bifunctors-5: install
comonad-4.2.7.2: build
comonad-4.2.7.2: install
profunctors-5.1.1: configure
profunctors-5.1.1: build
semigroupoids-5.0.0.4: download
semigroupoids-5.0.0.4: configure
semigroupoids-5.0.0.4: build
profunctors-5.1.1: install
semigroupoids-5.0.0.4: install
Progress: 29/35
```
The native exception:
```Unhandled exception at 0x015B8745 in stack.exe: 0xC0000005: Access violation reading location 0x0035002D.```

**Comment by snoyberg** [comment]
Can you provide --verbose output?

**Comment by NightRa** [comment]
@snoyberg Reproducing this is kind of problematic, because stack installed several packages successfully before crashing, and reruning stack resumes where it left off.
I tried deleting the .stack folder and rerunning build, and it succeeded.

**Comment by snoyberg** [comment]
I don't have a way to reproduce it either, so I'm not sure there's anything we can do. There's no low-level memory access going on in stack, so it's unlikely to be a stack-specific bug.
