### ISSUE TITLE
Binary coping with installed binaries

### ISSUE THREAD

**Issue by NightRa** [commercialhaskell/stack#901]
I'm on master 7153be831735fd10edecf99926b47a04897f4ed8.
If I install a program via stack, for example, ```stack install hlint```, hlint works well and everything. 
But if I then delete the stack directory with all the snapshots, running ```hlint``` results in the following:
```
hlint: Couldn't find file: HLint
Tried with:
  HLint
  HLint.hs
  D:\Users\NightRa\AppData\Roaming\stack\snapshots\i386-windows\lts-3.1\7.10.2\share\i386-windows-ghc-7.10.2\hlint-1.9.21\HLint
  D:\Users\NightRa\AppData\Roaming\stack\snapshots\i386-windows\lts-3.1\7.10.2\share\i386-windows-ghc-7.10.2\hlint-1.9.21\HLint.hs
```
I think this has to do with the binary sharing that was introduced recently.
(Maybe the installed binary of hlint included references to other cached binaries?)

Installing via stack should create standalone binaries, independant of the state stack is in.

**Comment by snoyberg** [comment]
Nope, this is nothing new, and has always worked this way. See https://github.com/commercialhaskell/stack/issues/848 and previous linked discussions, the only way around this with Cabal is double-building.
