### ISSUE TITLE
Symbol not found when loading ghci

### ISSUE THREAD

**Issue by htebalaka** [commercialhaskell/stack#905]
I've got a project which will install correctly with "stack install", but will then raise an error if I try to load the project with "stack ghci". The issue was somehow related to one of the files not being listed in either the exposed-modules or other-modules section in the cabal file. Adding it fixed the problem, though I wasn't able to get a minimal project to reproduce the issue, so something else may also be needed to trigger it.

<command line>: can't load .so/.DLL for: /Users/mg/gits/Expressions/.stack-work/install/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/new-template-0.1.0.0-CjGohjNCvzpCwXDqxMiRj7/libHSnew-template-0.1.0.0-CjGohjNCvzpCwXDqxMiRj7-ghc7.10.2.dylib (dlopen(/Users/mg/gits/Expressions/.stack-work/install/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/new-template-0.1.0.0-CjGohjNCvzpCwXDqxMiRj7/libHSnew-template-0.1.0.0-CjGohjNCvzpCwXDqxMiRj7-ghc7.10.2.dylib, 5): Symbol not found: _newtezuCjGohjNCvzzpCwXDqxMiRj7_TheanoziDynamicziSlice_zdfReadSlice3_closure
  Referenced from: /Users/mg/gits/Expressions/.stack-work/install/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/new-template-0.1.0.0-CjGohjNCvzpCwXDqxMiRj7/libHSnew-template-0.1.0.0-CjGohjNCvzpCwXDqxMiRj7-ghc7.10.2.dylib
  Expected in: flat namespace
 in /Users/mg/gits/Expressions/.stack-work/install/x86_64-osx/lts-3.0/7.10.2/lib/x86_64-osx-ghc-7.10.2/new-template-0.1.0.0-CjGohjNCvzpCwXDqxMiRj7/libHSnew-template-0.1.0.0-CjGohjNCvzpCwXDqxMiRj7-ghc7.10.2.dylib)

**Comment by borsboom** [comment]
Were you trying to load modules from an executable component?  If so, I suspect this is related to [these comments](https://github.com/commercialhaskell/stack/commit/9a2bde432fc6d9b42258b5d9dd2a8e6ee5e42d3b#commitcomment-12724037).  It's probably not finding the unlisted modules, nor warning you about them.  It should be doing both.

@chrisdone, does that seam plausible?

**Comment by chrisdone** [comment]
Probably.

**Comment by chrisdone** [comment]
@htebalaka Can you confirm this is fixed on master?

**Comment by htebalaka** [comment]
Can confirm it is fixed. FWIW, I had commented out the executable portion of the new-template.cabal file, since my project doesn't yet have an executable component. Don't know if that's relevant to the other issue.

**Comment by snoyberg** [comment]
Thanks for confirmation, closing.
