### ISSUE TITLE
A way to derive a custom snapshot from a stackage snapshot

### ISSUE THREAD

**Issue by feuerbach** [commercialhaskell/stack#908]
tThe custom snapshot wiki page mentions that, when writing a custom snapshot config, one can use cabal.config from stackage.

That's what I did, but some additional work was required:

- converting from one format (constraints) to another (yaml package-version list)
- adding flags (for instance, text defaults to using integer-simple and fails)

That last bit is especially annoying, and I belive the flags are already specified in the stackage snapshot; we just need a way to extract them in the right format.

So I propose a command that would convert a stackage snapshot into an equivalent custom snapshot yaml file. That file can then serve as a basis for customization.

**Comment by snoyberg** [comment]
I think #863 will be a better route forward for this, have you seen it?

**Comment by feuerbach** [comment]
I haven't seen it before, but I love it!
