### ISSUE TITLE
--file-watch triggers rebuild when I open a file with my editor

### ISSUE THREAD

**Issue by ezyang** [commercialhaskell/stack#912]
Steps to reproduce:

1. stack build --file-watch some project; wait till it quiesces.
2. Run `vim -u /dev/null` on a file in the project

Expected result: Stack does not rebuild.

Actual result: Stack rebuilds.

More observations: `vim -n -u /dev/null` does not cause a rebuild, so Vim's swapfile support seems to be related? However, when I looked at the inotify traces I didn't see anything too different.

Since inotify is probably related, here's the kernel version:

```
[ezyang@hs01 ghc-quick3]$ uname -a
Linux hs01.scs.stanford.edu 4.1.2-2-ARCH #1 SMP PREEMPT Wed Jul 15 08:30:32 UTC 2015 x86_64 GNU/Linux
```

**Comment by snoyberg** [comment]
Mind giving this a shot on latest master?

**Comment by snoyberg** [comment]
I'm going to close this as fixed, please let me know if you still see a problem.
