### ISSUE TITLE
Allow explicit reconfigure

### ISSUE THREAD

**Issue by ezyang** [commercialhaskell/stack#914]
With a custom setup script, it is sometimes extremely useful to explicitly reconfigure. (For example, `Cabal` self-bootstraps a `Setup.hs` script build with itself; if there are updates to any of the internal data structures it uses, a reconfigure is needed.) So having a `stack configure` which reconfigures the package in question would be useful.

**Comment by snoyberg** [comment]
I'm very much -1 on having an explicit `stack configure` command, as it would give the incorrect impression that stack requires explicit configuring like cabal does (the `install` command has already caused enough pain). Would `stack clean` be too much of a bazooka for triggering a reconfigure?

**Comment by snoyberg** [comment]
What about about a `--reconfigure` flag to `stack build`?

**Comment by snoyberg** [comment]
OK, new `--reconfigure` flag added to master. It won't force your code to rebuild if there are no changes, but *if* the code is being rebuilt, it will start with a reconfigure, which seems like the right behavior in (virtually?) all cases.

**Comment by ezyang** [comment]
Great, thanks a lot!
