### ISSUE TITLE
stack-0.1.4.0 fails during haddock stack

### ISSUE THREAD

**Issue by peti** [commercialhaskell/stack#916]
Citing from http://hydra.cryp.to/build/1140500/nixlog/2/raw:

~~~~~~
src/Stack/Types/Compiler.hs:34:9: parse error on input ‘{-# UNPACK’
~~~~~~

**Comment by snoyberg** [comment]
There's already a point release out for this.

**Comment by peti** [comment]
Very cool. Nixpkgs [distributes it already](https://github.com/NixOS/nixpkgs/commit/636e7fa166f56b9d4043a5187431cdc672d022d8#diff-e4ed6fefa9564bfd27ee249e42e145e2R126338).

**Comment by snoyberg** [comment]
Cool!
