### ISSUE TITLE
'stack solver' also enables tests when 'extra-dep: true'

### ISSUE THREAD

**Issue by hesselink** [commercialhaskell/stack#917]
Since fixing #862, stack solver enables tests, which is great. However, it also does this for local packages marked `extra-dep: true`. This doesn't match what a later `stack build --test` would do, and in our case, causes a failed dependency resolution. I see no easy fix, though.

**Comment by snoyberg** [comment]
The only fix I can think of is to implement a better dependency solver, which i what #116 is tracking. It seems like no one is interested in pushing that forward right now, though a lot of the pieces seem to be in place from others. Interested in trying to start up that discussion again?

**Comment by hesselink** [comment]
Perhaps, unless there's a better solution to my original problem: what I'm trying to do is maintain a custom snapshot. So I want to see which packages in the snapshot can be upgraded. I currently switch to the ghc-only snapshot, and then run the solver to get the newest versions. Perhaps there is a better way to do this?

**Comment by snoyberg** [comment]
Not answering the question directly, but: why maintain a custom snapshot instead of using an LTS or Nightly? Do you have a large number of packages that are not in Stackage? Are you using particularly old (or new) versions of any packages?

**Comment by hesselink** [comment]
Yes, we have both: a set of packages not in stackage, a slightly older compiler (7.8) and a set of packages at older versions because of bugs or dependencies. We moved from a cabal freeze file to extra deps to a custom snapshot.

**Comment by snoyberg** [comment]
Hmm... Is there _any_ cabal-based workaround for this? I can't see an automatic one, just the manual process of doing `--enable-tests` for some packages and then rerunning the solver without `--enable-tests`. An even hackier approach would be to manually edit the .cabal files of the offending packages to remove the test suites.

**Comment by hesselink** [comment]
No, like I said, I didn't see any workaround myself. I ended up editing the .cabal files of the packages like you suggested. But if there's a better way I'd like to use it :)

**Comment by snoyberg** [comment]
With cabal: nope, I can't think of another way. I would recommend adding a comment to #116 about this and see if that can spur any further development around alternative dep solvers.

**Comment by hesselink** [comment]
OK, I've made a note. Should I leave this open or close it?

**Comment by hesselink** [comment]
OK, I'll close it. Good point about the feature request to cabal, I'll try to come up with a nice ticket there.
