### ISSUE TITLE
Preparing to download msys2-20150512 ...Download expectation failure: ContentLength header

### ISSUE THREAD

**Issue by alexbiehl** [commercialhaskell/stack#919]
Hi, it seems there is some adjustment needed somewhere.

```
$ stack setup
Preparing to download msys2-20150512 ...Download expectation failure: ContentLength header
Expected: 33451040
Actual:   33519844
For: https://github.com:443/fpco/minghc/releases/download/2015-05-14/msys2-base-i686-20150512.tar.xz
```

**Comment by alexbiehl** [comment]
Ah, according to https://github.com/fpco/stackage-content/commit/6f3dfdca8bde7955528f93c09a1e73fc6c9c3d54 both 32bit and 64bit download point to the same file. Correcting the 64bit link should fix the issue.

**Comment by borsboom** [comment]
I've fixed the link, please try again (re-open if any difficulty)
