### ISSUE TITLE
stack --version outputs: Version 0.1.4.1 (UNKNOWN commits) X86_64

### ISSUE THREAD

**Issue by MaxGabriel** [commercialhaskell/stack#925]
I upgraded stack from 0.1.3.1 to 0.1.4.1 using `stack upgrade`. When I run `stack --version` now I get:

```
Max@maximilians-mbp ~> stack --version
Version 0.1.4.1 (UNKNOWN commits) X86_64
```

Is the UNKNOWN commits part intentional?

**Comment by borsboom** [comment]
No, not intentional, and should be fixed in master now.
