### ISSUE TITLE
The build stack-0.1.4.0-x86_64-linux.tar.gz results in `cannot execute binary file` when run

### ISSUE THREAD

**Issue by WillSewell** [commercialhaskell/stack#927]
This error happened on Travis, which is x86_64 architecture

### Steps to reproduce:

1. Create a `.travis.yml` as described in https://github.com/commercialhaskell/stack/wiki/Travis#installing-stack using stack-0.1.4.0-x86_64-linux.tar.gz release
2. Run on Travis

Although I suspect the same issue would happen when run manually on other linux x86_64 machines.

### What I expected to see and happen.

Work

### What actually happened.

`/home/travis/build.sh: line 41: /home/travis/.local/bin/stack: cannot execute binary file`

*This issue does not happen for the stack-0.1.3.1-x86_64-linux.gz and stack-0.1.2.0-x86_64-linux.gz releases. I have not tried others.*

**Comment by borsboom** [comment]
I probably should have highlighted this in the release notes, but we switched to using `.tar.gz` files instead of plain `.gz` files. I'll bet you're trying to execute a `.tar` file.

**Comment by borsboom** [comment]
I've [updated the wiki page to handle the .tar.gz](https://github.com/commercialhaskell/stack/wiki/Travis/_compare/a3ee0fc845cf2fd56ea364ccfeeef262998a5b12...11f0bc21132454bbde853bb4d47b7230a1fb5dce).  Can you test that?

**Comment by WillSewell** [comment]
Ah I see. yes that was the problem. Thanks!

You need to drop the brackets in your proposed change. There should also be a `cd` back to the starting directory. May I suggest:

```
travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v0.1.4.0/stack-0.1.4.0-x86_64-linux.tar.gz | tar xz -C ~/.local/bin
```

I've tested this and it works.

**Comment by snoyberg** [comment]
Thanks for confirming, closing.

@WillSewell would you be able to update the Wiki page with the Travis commands you found work best?

**Comment by WillSewell** [comment]
Done. I used the one I posted above.

**Comment by snoyberg** [comment]
Thanks!
