### ISSUE TITLE
Request for a minimal stack-run docker image

### ISSUE THREAD

**Issue by PierreR** [commercialhaskell/stack#930]
I would love to be able to start from a minimal docker images (say < 100 MB) that includes the strict minimum to run haskell exe with stack. 

Unfortunately [phusion](https://hub.docker.com/r/fpco/stack-run) is rather big and comes with ruby-1.9 (which is known to be broken).

AFAIK the Dockerfile for `stack-run` is not publicly available (see #624).

As a note, using `musl libc` might help for providing true static linking.

**Comment by borsboom** [comment]
This is out of scope for stack itself, but take a look here: https://www.fpcomplete.com/blog/2015/05/haskell-web-server-in-5mb (and accompanying repo: https://github.com/snoyberg/haskell-scratch).

@dysinger / @snoyberg: are there base images we can put on fpco's Docker Hub account for others to use easily?  Can stack support building executables that would work with such a base image?

**Comment by borsboom** [comment]
Oh, and while less minimal, https://hub.docker.com/r/fpco/ubuntu-with-libgmp/ might work for you as well.  It's ~100MB.

**Comment by PierreR** [comment]
Unfortunately `ubuntu-with-libgmp` is based on `14.04` too. An image based on `debian jessy` would do. (to be specific I need `hruby` which doesn't work with ruby-1.9)

**Comment by snoyberg** [comment]
I'm fine moving my haskell-scratch image to the fpco docker hub account.

**Comment by dysinger** [comment]
@PierreR ubuntu-with-libgmp is literally that.  You could start with debian jessy and add libgmp for your base image.

**Comment by PierreR** [comment]
@dysinger I actually did try something alike with an `arch linux` image but it did complain about `stack` missing. So I guess what I need is just `jessie + libgmp + a stack binary` ?

**Comment by drwebb** [comment]
I would be interested to hear if you get it working with Arch Linux. With
Arch you also need libtinfo (https://aur.archlinux.org/packages/libtinfo/)
otherwise stack will error at runtime.

On Mon, Sep 7, 2015 at 10:16 AM, Pi3r <notifications@github.com> wrote:

> @dysinger <https://github.com/dysinger> I actually did try something
> alike with an arch linux image but it did complain about stack missing.
> So I guess what I need is just jessie + libgmp + a stack binary ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/930#issuecomment-138342953>
> .
>



-- 
Tristan Webb PhD
Haskell Application Engineer
FP Complete
San Diego, CA
M: 619-452-9545

**Comment by PierreR** [comment]
> I'm fine moving my haskell-scratch image to the fpco docker hub account.

@snoyberg  that would be awesome. I was about to try your[docker hub scratch image](https://hub.docker.com/r/snoyberg/haskell-scratch/) but it seems a bit out-of-dated with https://github.com/snoyberg/haskell-scratch

**Comment by snoyberg** [comment]
@PierreR Check out: https://hub.docker.com/r/fpco/haskell-scratch/
