### ISSUE TITLE
Static linking

### ISSUE THREAD

**Issue by bitemyapp** [commercialhaskell/stack#935]
Got this question on IRC

> hey. I am trying to statically link some binary. I have compiled static dependencies and put them in folder A/ . LD_LIBRARY_PATH=A/ stack build but it seems stack doesn't pass LD_LIBRARY_PATH variable to ghc

What's the fix?

**Comment by snoyberg** [comment]
Perhaps you're looking for the --extra-library-dirs option? stack doesn't hide that environment variable from GHC (I suppose Cabal might, but I don't think it does), but I think GHC itself needs to be more explicitly told where to look for libraries.

**Comment by bitemyapp** [comment]
@snoyberg danke, closing for now unless someone tries it and it doesn't work.
