### ISSUE TITLE
Support Docker with any image

### ISSUE THREAD

**Issue by borsboom** [commercialhaskell/stack#936]
Since Docker support was originally implemented in an internal build tool, much has changed in stack.  Those changes mean the structure of the Docker image is much less important than it used to be, and there's no deep reason for the Docker image to need a special structure anymore.  Changes required, as far as I know:

* Move the `/usr/local/sbin/docker-entrypoint` logic into Stack itself (and remove the entrypoint from future images, after a transition period).

* Make `stack` itself behave as a proper PID 1 `init` daemon (reap processes, etc.).  That means no more need to use phusion/baseimage's my_init.

We will continue to distribute images, but just about any image should work, including the Official Haskell images.  Even images that don't contain GHC should work (stack will just fall back on its usual non-Docker behaviour of installing its own GHC in `~/.stack`).

**Comment by edofic** [comment]
This would enable using ghc with musl to build proper static binaries just with a `repo` setting. :+1:

**Comment by borsboom** [comment]
This is a duplicate of #531.
