### ISSUE TITLE
capitalization: stack vs Stack

### ISSUE THREAD

**Issue by wolftune** [commercialhaskell/stack#938]
I know the command in terminal is just `stack`, but I find it *really* awkward that the word is not capitalized through the GUIDE.md. The word "stack" is a plain English word. Capitalization is almost always used to identify the difference between this special thing named "Stack" versus the general English noun. I really wish we could stick with capitalized Stack or use \`stack\` (with the markdown code markings) in places where we really want to keep the command as the lowercase code command.

**Comment by snoyberg** [comment]
I think you're right. @borsboom and I talked about this, and I'm starting to use Stack unless specifically referring to the executable (at which point we say `stack`). My originally motivation was to avoid the confusing situation we have around Cabal/cabal-install/cabal/cabal-the-standard, but hopefully just capitalization won't cause trouble here.
