### ISSUE TITLE
Fix --[no-]optimizations

### ISSUE THREAD

**Issue by meteficha** [commercialhaskell/stack#956]
* The man pages do not state the fact that these options are noops.

* Using these flags should either issue a warning or fail completely instead of just being silently ignored.

* The `--help` text is extremely confusing:

```
  --optimizations          Enable DEPRECATED: This flag is no longer used, and
                           has no effect. Please use --ghc-options=-O?
  --no-optimizations       Disable DEPRECATED: This flag is no longer used, and
                           has no effect. Please use --ghc-options=-O?
```

**Comment by drwebb** [comment]
I was just looking at this yesterday, was going to suggest a complete
removal.

On Tue, Sep 8, 2015 at 12:26 PM, Felipe Lessa <notifications@github.com>
wrote:

>
>    -
>
>    The man pages do not state the fact that these options are noops.
>    -
>
>    Using these flags should either issue a warning or fail completely
>    instead of just being silently ignored.
>    -
>
>    The --help text is extremely confusing:
>
>   --optimizations          Enable DEPRECATED: This flag is no longer used, and
>                            has no effect. Please use --ghc-options=-O?
>   --no-optimizations       Disable DEPRECATED: This flag is no longer used, and
>                            has no effect. Please use --ghc-options=-O?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/commercialhaskell/stack/issues/956>.
>



-- 
Tristan Webb PhD
Haskell Application Engineer
FP Complete
San Diego, CA
M: 619-452-9545

**Comment by snoyberg** [comment]
Yes, we should remove it for the next release. I deprecated first just in
case someone had it in a script. Tristan, please go ahead with that change.

**Comment by drwebb** [comment]
Closed with commit 4edbde66. No more references in code to anything "optimizations", so I'm assuming I fully killed it.

**Comment by meteficha** [comment]
There's still https://github.com/commercialhaskell/stack/blob/e3e2438e49486ea11b04d8cf0609d1ab957ad619/man/man1/stack.1#L312 AFAICS :).

**Comment by drwebb** [comment]
Yeah, I'm working on auto genning the man page for this next release, it's
been out of date since 0.1.2.1.

**Comment by borsboom** [comment]
Closing in favour of #986 (auto-generate man page).
