### ISSUE TITLE
Support "ghc -e"

### ISSUE THREAD

**Issue by 3noch** [commercialhaskell/stack#957]
It's often nice to inline some Haskell processing on the command line with `ghc -e "<haskell code>"`. It seems `stack ghc -- -e "<haskell code>"` isn't properly routing `stdin`/`stdout` for this to work. It also clutters `stdout` with its own output. Perhaps it's worth adding a top-level option to stack for this (e.g. `stack do "<haskell code>"`)?

**EDIT:** I should clarify that this *does* work when simply doing output like `print 5`, but it doesn't work with `interact`.

**Comment by mgsloan** [comment]
Hmm, seems to work for me:

```
stack ghc -- -e "interact (unlines . lines)"
unknown option: 'c'
Hi!!     
Hi!!
It works!
It works!
```

Though that `unknown option: 'c'` is strange.

**Comment by 3noch** [comment]
I'm on Windows...perhaps that's the problem?

**Comment by 3noch** [comment]
Indeed it does work on Windows! I just upgraded to 1.4.0 so that could have been the issue.

**Comment by 3noch** [comment]
It still might be nice to have `stack do` though! :D

**Comment by snoyberg** [comment]
I'd say open up a separate issue for stack do

**Comment by 3noch** [comment]
Fair: #959
