### ISSUE TITLE
stack test rebuilds the test suite, but not the executable being tested

### ISSUE THREAD

**Issue by jgm** [commercialhaskell/stack#963]
Suggestion:  When the library changes, `stack test` should rebuild not just the test program, but any executables that are built by default and that depend on the library, since the test program may well be trying to test these executables.

Steps to reproduce:

```
git clone https://github.com/jgm/pandoc-citeproc
cd pandoc-citeproc
stack test
```

You should see one test fail.
Now edit `src/Text/CSL/Pandoc.hs`.  Change `references` in line 71 to `bogus`.  This should break multiple tests, but it doesn't:

```
stack test
```

This rebuilds `test-pandoc-citeproc`, but doesn't rebuild the executable being tested, `pandoc-citeproc`.  So, you should see just one failure again.  Now do

```
stack build
stack test
```

Now you should see lots of failures.

Using stack version 0.1.2.0

**Comment by snoyberg** [comment]
This should already be fixed in the newest release of stack, could you try
upgrading?

**Comment by jgm** [comment]
Indeed, it works with the latest version.  Sorry for the noise, and thanks for stack.  I'm finding it very pleasant to use.

**Comment by snoyberg** [comment]
Awesome, glad to hear it!
