### ISSUE TITLE
Add --bare flag to "stack new" (similar to "yesod init --bare")

### ISSUE THREAD

**Issue by sfilipov** [commercialhaskell/stack#965]
I just checked the yesod quickguide and it has been updated recently. It now recommends "stack new my-project template-name" as the way to initialize a new yesod project. What is missing is the option to do so in the current folder. This was previously done using "yesod init --bare" followed by "stack init".

Is this an intentionally missing feature or just a lower priority one?

**Comment by chrisdone** [comment]
I hadn't planned on it, but we can add it.

**Comment by snoyberg** [comment]
Resolved by #1119
