### ISSUE TITLE
Libararies :  libgmp.so.10: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by superinterstellar** [commercialhaskell/stack#967]
Hi,
I am trying to install stack on Centos 6. 
Below is the error message:- 

stack: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory

Could someone please help address this issue.
Thanks
Kevin

**Comment by borsboom** [comment]
You need to install a stack executable linked with `libgmp.so.3` (gmp4) instead.  

I was about to point you to the CentOS 6 instructions on the [Downloads page](https://github.com/commercialhaskell/stack/wiki/Downloads#centos--red-hat--amazon-linux) when I noticed that there aren't any (just a "Looking for CentOS 6 / RHEL 6/ Amazon Linux? See [#465](https://github.com/commercialhaskell/stack/issues/465#issuecomment-118844397)" pointer).  Now that GHC 7.10.2 is releasing CentOS 6 binaries (7.10.1 didn't) I'll add that back.  But in the meantime, try following [these instructions](https://github.com/commercialhaskell/stack/issues/465#issuecomment-118844397).

You can also download one of the binaries with the `-gmp4` suffix from [the latest release](https://github.com/commercialhaskell/stack/releases/latest).

**Comment by borsboom** [comment]
[Downloads page](https://github.com/commercialhaskell/stack/wiki/Downloads#centos--red-hat--amazon-linux) is updated.  Please reopen this issue if you continue to have trouble.
