### ISSUE TITLE
Stack doesn't rebuild even if source file is revised.

### ISSUE THREAD

**Issue by eunchan** [commercialhaskell/stack#968]
I'm currently experiencing an issue that stack doesn't re-compile modified source file which is not specified in main-is but that file is located in hs-source-dirs .

~~~~
name:                ssg
version:             0.3.0.0
license:             BSD3
license-file:        LICENSE
author:              Eunchan Kim
maintainer:          eunchan@outlook.com
category:            Web
build-type:          Simple
cabal-version:       >=1.18

executable ssg
  main-is:             main.hs
  build-depends:       base         >=4        && < 5     ,
                       binary       >= 0.5     && < 0.8   ,
                       blaze-html   >= 0.5     && < 0.9   ,
                       hakyll       >= 4.6     && < 4.9   ,
                       pandoc       >= 1.13    && < 2     ,
                       containers   >= 0.5                ,
                       process      >= 1.2                ,
                       directory    >= 1.2                ,
                       filepath     >= 1.3                

  Hs-source-dirs:      _src/
  extra-source-files:  Sky.hs, Post.hs, Blog.hs, Config.hs
  Ghc-Options:         -Wall
  default-language:    Haskell2010
~~~~

Above is cabal file. Even I revised Sky.hs, stack didn't compile it unless I modifed this cabal file.

**Comment by snoyberg** [comment]
What version of stack are you using?

**Comment by eunchan** [comment]
@snoyberg  I'm using 0.1.4.1

**Comment by snoyberg** [comment]
It could be that the files are not being imported from your main module. In
any event, if you use the other-modules field instead, it should work.

**Comment by eunchan** [comment]
Hi Michael,

main module has import line for below files.

~~~~
--------------------------------------------------------------------------------
{-# LANGUAGE Arrows             #-}
{-# LANGUAGE OverloadedStrings  #-}
module Main where

--------------------------------------------------------------------------------
import           Data.Monoid                     ((<>))
import           Prelude                         hiding (id)

import           GHC.IO.Encoding
--------------------------------------------------------------------------------
import           Hakyll

import           Config
import           Sky
import           Post
import           Blog

--------------------------------------------------------------------------------
-- | Entry point
main :: IO ()
main = do
~~~~

After revising to `other-modules`, it works. Thanks for your help.

  Regards,
  Eunchan

On Sep 10, 2015, at 12:24 AM, Michael Snoyman <notifications@github.com <mailto:notifications@github.com>> wrote:

It could be that the files are not being imported from your main module. In
any event, if you use the other-modules field instead, it should work.

**Comment by chrisdone** [comment]
This field isn't supported in this place in the cabal file. I've added a commit to print Cabal's warnings about unknown fields.

**Comment by borsboom** [comment]
0.1.4.1 also [has an issue](https://github.com/commercialhaskell/stack/commit/9a2bde432fc6d9b42258b5d9dd2a8e6ee5e42d3b#commitcomment-12724037) where detection of unlisted modules (and TH dependencies) didn't work in an executable's main.  This should be fixed in git master.

**Comment by chrisdone** [comment]
Specifically, `extra-source-files` can't be specified in the `executable` section.

**Comment by borsboom** [comment]
Closing the issue.  @eunchan, please reopen if this turns out not to be resolved.
