### ISSUE TITLE
too much package build parallellism

### ISSUE THREAD

**Issue by gregwebs** [commercialhaskell/stack#978]
We have a single core CI server. `stack test` appears to try to build all the packages at once (before testing commences, judging from the Progress output). As a result, we run out of (4 GB) of memory

**Comment by snoyberg** [comment]
What happens if you pass in -j 1 explicitly?

**Comment by borsboom** [comment]
Does this command return a correct number of processors?  It should match `grep ^processor /proc/cpuinfo | wc | awk '{print $1}'`.

```
$ runghc <<END
import GHC.Conc
main = print =<< getNumProcessors
END
```

**Comment by gregwebs** [comment]
`-j  1` seems to work. Weird thing is that  adding on any other options (such as `-j 1 --pedantic`) does not parse at the CLI. I will look at the # of processors

**Comment by borsboom** [comment]
> Weird thing is that adding on any other options (such as -j 1 --pedantic) does not parse at the CLI.
See #519

**Comment by gregwebs** [comment]
Thanks for the #519 pointer, now I can properly specify -j.

Sorry for the noise, This is running inside a CircleCI container which appears to be on a 32 core machine :). There is some other technique that is limiting the active processors down to 1.
