### ISSUE TITLE
GHCJS resolver doesn't work

### ISSUE THREAD

**Issue by mayhewluke** [commercialhaskell/stack#982]
Following the information [here](https://github.com/commercialhaskell/stack/issues/337#issuecomment-131677050) results in:

```
$ stack --version
Version 0.1.4.1 (UNKNOWN commits) X86_64
$ ghcjs --version
The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.1.0 (GHC 7.10.2)
$ stack build --resolver ghcjs-0.1.0_ghc-7.10.2
No compiler found, expected minor version match with ghcjs-0.1.0_ghc-7.10.2 (x86_64) (based on resolver setting in /path/to/project/stack.yaml). Try running stack setup to locally install the correct GHC
```

On the other hand, using an invalid resolver value provides this message:

```
option --resolver: Invalid resolver value: foo. Possible valid values include lts-2.12, nightly-YYYY-MM-DD, ghc-7.10.2, and ghcjs-0.1.0-ghc-7.10.2.
```

So I tried to use the value given by the error message, but apparently using that resolver value does not work either:

```
$ stack build --resolver ghcjs-0.1.0-ghc-7.10.2
option --resolver: Invalid resolver value: ghcjs-0.1.0-ghc-7.10.2. Possible valid values include lts-2.12, nightly-YYYY-MM-DD, ghc-7.10.2, and ghcjs-0.1.0-ghc-7.10.2. See https://www.stackage.org/snapshots for a complete list.
```

**Comment by mgsloan** [comment]
The error message has been fixed in the development version, sorry about that https://github.com/commercialhaskell/stack/commit/06d71e45c6d6fb1f5c84812b362cd5a41788fabf

You need to have that version of GHCJS on your path, such that `ghcjs --version` reports that version.  Then, it should work.  `stack setup` is not yet supported for ghcjs, but the plan is to have `stack setup` install things from source soon.

**Comment by mayhewluke** [comment]
Ah ok, that clears up which resolver value is the correct one, thanks.

I think (somewhat sheepishly) that perhaps my problem was not running `ghcjs-boot` before trying to use it with stack, since I've done that now and it's no longer complaining that it can't find the compiler. It's now complaining about finding dependencies, so I'm assuming that I've made it past the original issue in this thread. Thanks again!

**Comment by nrolland** [comment]
is there a guide/overview/reference on how to develop in ghcjs using stack ?

**Comment by mgsloan** [comment]
@nrolland Not yet, somewhat because "stack setup" didn't yet support it.  However, that changed recently - https://github.com/commercialhaskell/stack/issues/749 !

It's on my TODO list to add a template for GHCJS and write a guide on how to use it.

**Comment by nrolland** [comment]
Cool! Anything, however primitive would be useful to serve as a starting point and reference.

Stack and ghcjs are both very exciting pieces of the Haskell ecosystem.

**Comment by mgsloan** [comment]
A really quick tutorial would be:

Put this in your stack.yaml, next to the cabal file for your ghcjs project (just a standard cabal file)

```
resolver: ghcjs-0.1.0.20150924_ghc-7.10.2
compiler-check: match-exact
```

Run `stack setup` to install it (will take a while, it builds a lot of stuff).  Then, `stack build`, and it should build.  Then, you can find the output in the directory yielded by `stack path --local-install-root`
