### ISSUE TITLE
Killing stack build with Ctrl-C leaves terminal in weird state

### ISSUE THREAD

**Issue by lubomir** [commercialhaskell/stack#985]
When `stack build` is installing dependencies, killing it with Ctrl-C leaves terminal in state when I can not type, or some output is left displayed and overwritten by my typing. Generally, `reset` helps bring it back to normal.

Happens with Bash in gnome-terminal.

**Steps to reproduce**
1) run `stack build` in a project with uninstalled dependencies
2) press Ctrl-C
3) try typing something

**Expected**
The terminal should be in normal state where I can type and see what I'm typing.

**Actual**
Weird things are happening.

```
$ stack --version
Version 0.1.4.0, Git revision 3a665fe1bc52776041a1c25cc47734e691805b6c (1724 commits) X86_64
```

**Comment by borsboom** [comment]
I haven't been able to reproduce this using OS X terminal, but I don't at this moment have a system with gnome-terminal handy.  Does this only happen in gnome-terminal, or have you been able to reproduce it with another terminal or directly on the console?  What is your terminal type set to (e.g. xterm, xterm-256color, vt100, etc.)?  What is your locale?  Is there anything special about your terminal environment that you can think of?

**Comment by lubomir** [comment]
Locale is cs_CZ.utf8, TERM is set to xterm-256color. I don't think there is anything special. However, it happened to me twice, so I filed this report, and I have been unable to replicate it myself ever since. I will close this issue.
