### ISSUE TITLE
Stack throwing error when trying to copy precompiled package into a custom snapshot

### ISSUE THREAD

**Issue by mageshb** [commercialhaskell/stack#993]
I'm trying to create a custom snapshot with a package that has dependencies on alex,happy.
While creating the snapshot, stack tried to copy the prebuilt alex & happy from lts and failed with the following error
>stack ghci
alex-3.1.4: copying precompiled package
happy-1.19.5: copying precompiled package
Progress:/home/magesh/.stack/snapshots/x86_64-linux/custom-proj-deps-lts-3.5/7.10.2/bin/: copyFile: inappropriate type (is a directory)
/home/magesh/.stack/snapshots/x86_64-linux/custom-proj-deps-lts-3.5/7.10.2/bin/: copyFile: inappropriate type (is a directory)

I tried `stack install alex' as well, which gave the same error
Is this a bug? If so, is there any workaround that I could try

**Comment by snoyberg** [comment]
Can you try upgrading to stack master via stack upgrade --git ?

**Comment by mageshb** [comment]
Thanks, upgrading the stack fixes the issue.
